### ISSUE TITLE
Connect to Teradata LDAP

### ISSUE THREAD

**Issue by palonsopinto** [serge-rider/dbeaver#1001]
Hi,

I'm trying to figure out how to connect to a Teradata database through LDAP using DBeaver. Anyone have any tips or advice on how to do this? 

I installed a JDBC driver and got it to connect to LDAP, but I cannot point it towards Teradata (all I get is as displayed below). 

![image](https://cloud.githubusercontent.com/assets/23720538/20606857/c198ede8-b26b-11e6-9618-ef3072ffd871.png)

I'm quite new at this so might be doing something fundamentally wrong.
Thanks!

**Comment by SirBenJammin** [comment]
Hello Pealp,

Ensure to have the correct version of the Teradata JDBC driver installed to the version of Teradata you are trying to access. You do not need to connect to LDAP first before connecting to Teradata rather you need to use the correct logging mechanism (i.e. LOGMECH) in the JDBC url setup,

Few things within the JDBC setup I suggest to fixed your problem:

1. Edit the URL template via the "Edit Driver Settings" to add an extra field for the LOGMECH settings. Try using the following template: **jdbc:teradata://{host}[:{port}]/{database}[,{server}]**

2. Once you modified the URL template, trying the following JDBC values (you may need the port number 1025 or not):
![image](https://cloud.githubusercontent.com/assets/17081097/21642597/aefe3cbe-d283-11e6-931c-290432ef6934.png)

Hopefully with this you will successfully accessed Teradata via LDAP.

Thanks,

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.

**Comment by isakalley** [comment]
Hi,

I am facing the same issue. Wanting to use LDAP authentication to login to Teradata but looks like the above solution doesn't work I keep getting an error that the username or account or password is invalid. I can login using same credentials through Teradata studio but not Dbeaver.

Any solutions??

**Comment by serge-rider** [comment]
@isakalley Please post exact error message  (error stacktrace would be also helpful)

**Comment by Veera93** [comment]
[Teradata JDBC Driver] [TeraJDBC 16.20.00.06] [Error 1536] [SQLState HY000] Invalid connection parameter name **<databse_name>**,TMODE

**Comment by i-namekawa** [comment]
@Veera93 
I think the connection string from @SirBenJammin is missing `database=` part.

    jdbc:teradata://{host}[:{port}]/database={database}[,{server}]

Even with this connection setting, [test connection] in the setting dialog gave me an error about username, password, account not being valid. But Interestingly it worked just fine from the main screen Database Navigator once the setting is registered.

In my environment, I also had to omit port number in the setting (but I kept it in the URL template).

**Comment by vishrantgupta** [comment]
Goto toolbar Database -> search Teradata and double click -> Check below parameters:

![image](https://user-images.githubusercontent.com/1741243/81479092-e218c080-91e6-11ea-8f16-a21ea92ece72.png)

Now, toolbar search newly added Teradata, check below details:
![image](https://user-images.githubusercontent.com/1741243/81479321-1640b100-91e8-11ea-9f17-cf9d999d1814.png)

**Comment by tphani** [comment]
Sorry for commenting on a closed thread, but this is the most relevant issue!

I am using the community edition: Version 22.0.4.202205011839 and connection to teradata fails with error:
```
[Teradata JDBC Driver] [TeraJDBC 17.10.00.23] [Error 1000] [SQLState 08S01] Login failure for Connection to TERA.DEV.COM Tue May 10 09:03:17 EDT 2022 socket orig=TERA.DEV.COM cid=2646bbd0 sess=0 java.net.ConnectException: Connection refused (Connection refused)  at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)  at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)  at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)  at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)  at java.base/java.net.SocksSocketImpl.connect(Unknown Source)  at java.base/java.net.Socket.connect(Unknown Source)  at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)  at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF$ConnectThread.run(TDNetworkIOIF.java:1563) 
  Connection refused (Connection refused)
  Connection refused (Connection refused)
```
After fiddling around with the tera driver params, I realized it tries to use ssl to connect even though custom host and port 
 are specified. To force non-ssl, ended up adding **SSLMODE=DISABLE** and it worked out file. Here are the final JDBC url:
 ```jdbc:teradata://TERA.DEV.COM/DATABASE=DEVDB,TMODE=TERA,LOGMECH=LDAP,SSLMODE=DISABLE,DBS_PORT=1025```

**Comment by prudhviteddu** [comment]
jdbc:teradata://HOSTNAME/DATABASE=DATABASENAME,TMODE=TERA,LOGMECH=LDAP,SSLMODE=DISABLE,DBS_PORT=1025
Thanks a lot @tphani, the above JDBC url worked for me I have been struggling for the access for a while.
