### ISSUE TITLE
Query execution after renaming file

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#1002]
Hi,

DBeaver: 3.8.0
OS: Linux Mint 7.3

Steps to reproduce the problem:

1. Create a new SQL file.
2. Write a query in the file.
3. Rename the file in the project navigator, by a right clic on Script.sql => new_name.sql. The file is renamed in the SQL Editor.
4. Execute the query written on step 2. The query is executed but blue little triangle(s) (depending on how many lines have the query) remain on the left of the query text in the editor.
5. Write a new query under the first one.
6. Execute the new query: an error message appears: "Can''t execute more than one query in one tab. Try to use multiple tabs for simultaneous query execution."

The only way to execute the queries is close the SQL file and reopen it.

I hope you could reproduce it with these elements.

Regards,
Cedric

**Comment by serge-rider** [comment]
Yes, this is 100% reproducible.
Thanks for report.
