### ISSUE TITLE
V3.8.0 with Reliersoft Salesforce JDBC connector not working

### ISSUE THREAD

**Issue by mtortolano** [serge-rider/dbeaver#1003]
I'm using the Reliersoft Salesforce JDBC connector very successfully on machines with DBeaver 3.7.7 and 3.7.8 but when I upgrade any of those machines to 3.8.0 I start getting an error back every time we try to execute a query that states Null pointer exception and no results are returned.

**Comment by serge-rider** [comment]
Please post error stacktrace.
You can get it in Error Log view (main menu windows->Show View->Error Log).
