### ISSUE TITLE
Oracle: can't commit in the table editor

### ISSUE THREAD

**Issue by davitof** [serge-rider/dbeaver#1006]
I enabled the Commit / Rollback buttons. When editing table data, I tried to simply press Commit, but this does not work. I now understand that we are supposed to use the Save / Cancel buttons instead, then press Commit or Rollback. This is counterintuitive. 

I suggest that when using a Table Editor, either the Commit / Rollback buttons should be disabled, or they should perform the same actions as the Save / Cancel buttons and we should not have to press Save then Commit.

**Comment by davitof** [comment]
dBeaver 3.8.0 64 bits / Windows 10 64 bits

**Comment by serge-rider** [comment]
This will make commit/rollback actions senseless. The whole point of having separated save/cancel and commit/rollback actions is to let user to make multiple changes, check how it works in current transaction and then commit changes.

Moreover committing in the moment of data save is dangerous (this may corrupt data and you won't be able to rollback it).

If you don't need this "two-phase" save then you can work in auto-commit mode.

**Comment by davitof** [comment]
Ah, I understand. Makes sense too. Counterintuitive but makes sense. I'll have to remember this.
