### ISSUE TITLE
Table editor does not take column default values into account (refresh needed)

### ISSUE THREAD

**Issue by davitof** [serge-rider/dbeaver#1007]
When adding a new row to a table with a column with a default value, the Table Editor does not show this default value in the new row, but shows [NULL] instead. If the user does not enter anything into this column, then presses Save and sorts the table, dBeaver still displays [NULL]. But when exiting and reentering dBeaver, the default value appears correctly.

**Comment by davitof** [comment]
dBeaver 3.8.0 64 bits / Windows 10 64 bits

**Comment by serge-rider** [comment]
You don't need to reenter DBeaver - just press refresh button (it is on the top toolbar)

**Comment by davitof** [comment]
OK, this is a shorter workaround. But still a workaround :-)

**Comment by serge-rider** [comment]
Agreed, this is a workaround.
Better solution would be to select just inserted/updated row from database. But in some cases this is not possible (e.g. if table doesn't have unique key or if new row has auto-generated pk which is not known at the moment of insert). Another problem - inserting into view or in result of custom SQL query (views do not have unique keys, custom query may contain just a few table columns ).

That's why implicit row refresh isn't yet implemented.

**Comment by davitof** [comment]
OK, I understand this. But the table editor knows the table structure, right? Then he could be aware of default values. Then IMO he should use them. Maybe he could display the default values in gray on the line being created, as a kind of subliminal hint that this is a default value instead of a user-entered value. Anyhow, unless someone changes the table definition between opening the table editor and the moment a new line gets written, default values are the actually correct. If the user doesn't overwrite them during input, those default values will indeed be physically written.

**Comment by serge-rider** [comment]
I think that the only correct way is to re-select inserted row. Default values may contain expressions (and they do this quite often) which can be evaluated only on server side. Also table triggers may update row values as well.

So I don't see any real alternative.

I'll check this in code one more time - and if it won't be too complex then I'll add row refresh (whenever it is possible) in one of next versions.

**Comment by davitof** [comment]
Ah right, I forgot about expressions and triggers. OK. This is not a major issue IMO.

**Comment by serge-rider** [comment]
In my practice most frequent default value is CURRENT_TIMESTAMP or some sequence value.

Anyhow, I think it will be quite easy to add row refresh feature. 
Although more testing will be needed..

**Comment by ejose19** [comment]
I stumbled on this when using data editor for adding rows to a view and calculated fields weren't shown after clicking save. @serge-rider this could be simplified by adding another option to "Refresh result set" (Refresh after save), new/edited row doesn't need to be located, just triggering a refresh is enough (and the user can adjust sorting directly in the query used)
