### ISSUE TITLE
Oracle: cast to xmltype error oracle/xml/parser/v2/XMLParseException

### ISSUE THREAD

**Issue by dariopnc** [serge-rider/dbeaver#1008]
Running the following query:
```
select xmltype('<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body>
<getProductDetails xmlns="http://magazzino.example.com/ws"><productId>827635</productId></getProductDetails></soap:Body></soap:Envelope>') as payload
from dual
;
```

I get this output:
```
oracle/xml/parser/v2/XMLParseException
  java.lang.ClassNotFoundException: oracle.xml.parser.v2.XMLParseException
```

The query works as expected in SQLDeveloper 4.1.3.20

DBeaver version 3.8.0
DB Oracle

**Comment by serge-rider** [comment]
You need to add extra jars: #171

**Comment by dariopnc** [comment]
Adding the jar solved the issue, but no link or indication was present.

I'll add this info in #171

**Comment by serge-rider** [comment]
xdb.jar link is on driver download page:
![image](https://cloud.githubusercontent.com/assets/6398845/20721383/ac5b4938-b673-11e6-83e5-f4015b9fc488.png)

Maybe it is not too obvious. But where else can I put it?

**Comment by dariopnc** [comment]
In the error popup? ;)
