### ISSUE TITLE
Binding variables errors

### ISSUE THREAD

**Issue by dariopnc** [serge-rider/dbeaver#1010]
Running the following query on MySQL:
```
select COMMAND
from information_schema.PROCESSLIST
where COMMAND = :appo
;
```
with the binding variable appo set as **Sleep**

I get this error output:
```
Errore SQL [1054] [42S22]: Unknown column 'Sleep' in 'where clause'
  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'Sleep' in 'where clause'
```

if I run the same query without the where clause i get:
```
COMMAND |
--------|
Query   |
Sleep   |
Sleep   |
```

This issue was not present in DBeaver 3.7.7

Another (probably related, that's why I'm adding it here) issue on Oracle about binding is the following; running the query
```
select * 
from dual
WHERE dummy = :appo
;
```

with appo set as **X**

I get the error:
```
Errore SQL [904] [42000]: ORA-00904: "X": identificativo non valido
java.sql.SQLSyntaxErrorException: ORA-00904: "X": identificativo non valido
```

which is Italian for _invalid identifier_.

running it without the where clause I obviously get:
```
DUMMY |
------|
X     |
```

Both query work as expected in SQLDeveloper 4.1.3.20

DBeaver version 3.8.0

**Comment by serge-rider** [comment]
You need to specify string parameters as SQL strings (e.g. 'Sleep').
Binding dialog was redesigned in 3.8 - now you can specify any valid SQL value or expression.

**Comment by dariopnc** [comment]
Isn't this behavior more prone to SQL Injection? Could a switch be implemented to toggle this new feature?

**Comment by serge-rider** [comment]
Yes, it is SQL injection. And there is no switch (for now).
What problems do you see in this approach?

In older version real JDBC parameters binding was used. Main disadvantages: value parsing problems, inability to specify binary/LOB values and complex values (structs, arrays, etc), inability to use expressions, inconvenient UI (you had to specify parameter data type manually).

**Comment by flequi** [comment]
Hi again Serge.

I have a similar problem with a DB2 Connection with the JDBC4.0 driver (with the older JDBC 3.0 driver too) when I set named variables in my query never works.

select tca.descripcion, ca.* from MOVTO.configuracion_aplicacion ca
inner join MOVTO.tipo_configuracion_aplicacion tca on tca.id_tipo_configuracion_aplica = ca.id_tipo_configuracion_aplica
where tca.id_catalogo_aplicacion IN (:idcat1,:idcat2);

If I set anonimous variables it works fine, but I don't want to remember the order of all variables of more complex queries, for this I prefer to use named variables.
select tca.descripcion, ca.* from MOVTO.configuracion_aplicacion ca
inner join MOVTO.tipo_configuracion_aplicacion tca on tca.id_tipo_configuracion_aplica = ca.id_tipo_configuracion_aplica
where tca.id_catalogo_aplicacion IN (?,?);

I set the parameters with the correct TYPE of the DB column in the Binding window:
![image](https://cloud.githubusercontent.com/assets/4034173/20791604/1bd1c288-b7be-11e6-8b39-6621ff0e6f22.png)

The DDL of the table it's this:
CREATE
    TABLE TIPO_CONFIGURACION_APLICACION
    (
        ID_TIPO_CONFIGURACION_APLICA SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        DESCRIPCION VARCHAR(100) NOT NULL,
        **ID_CATALOGO_APLICACION INTEGER NOT NULL,**
        CONSTRAINT PK_TCONFIGAPLICA PRIMARY KEY (ID_TIPO_CONFIGURACION_APLICA),
        CONSTRAINT FK_TCONFAPL_CATAPL FOREIGN KEY (ID_CATALOGO_APLICACION) REFERENCES CATALOGO_APLICACION (ID_CATALOGO_APLICACION)
    );

The error I get it's this and I attach the ErrorLog exported in text format:
![image](https://cloud.githubusercontent.com/assets/4034173/20791686/80ea3574-b7be-11e6-9fe9-6289c6e54641.png)


[ErrorParameterBinding.txt](https://github.com/serge-rider/dbeaver/files/624353/ErrorParameterBinding.txt)

**Comment by serge-rider** [comment]
You are using older version of DBeaver. In 3.8 parameters binding dialog was redesigned and such error won't happen.

**Comment by dariopnc** [comment]
> Yes, it is SQL injection. And there is no switch (for now).
> What problems do you see in this approach?

With the usual behavior of binding you could provide access to a DB with DBeaver even to untrained/untrusted users with specific queries, while keeping safety.
Also, having to type apostrophes for every string remarkably slows down the workflow

**Comment by serge-rider** [comment]
It'd be a very bad idea to give access to DBeaver SQL editor to untrusted user. You can execute any SQL there, it doesn't make any sense to use SQL injections to harm database - you can do this by simply executing harmful queries.

Agreed about single quote chars you need to use for strings. This is the price we had to pay. Potentially I could quote all "string-like" parameters but this won't let to use expressions.
