### ISSUE TITLE
Vertica Error: "Cannot insert multiple commands into a prepared statement"

### ISSUE THREAD

**Issue by StefanoRomano71** [serge-rider/dbeaver#1012]
Hello,
We were using version prior to 3.8.0 and we can run multiple query in a script simply selecting them and use cmd/ctrl+enter to run all selected lines even if they are more than one query.

With version 3.8.0 we receive folowing error, both with integrate 6.x driver and 7.2 manually added driver:
SQL Error [2446] [42601]: [Vertica][VJDBC](2446) ERROR: Cannot insert multiple commands into a prepared statement
  [Vertica][VJDBC](2446) ERROR: Cannot insert multiple commands into a prepared statement
    com.vertica.support.exceptions.SyntaxErrorException: [Vertica][VJDBC](2446) ERROR: Cannot insert multiple commands into a prepared statement

Can you please check as soon as you can? 
We are data analysts and we use to run script partially quickly test them and this bug/feature is killing our productivity.

Thanks in advance for your kind support.

SR

**Comment by serge-rider** [comment]
There were no changes in SQL query processing in 3.8. 
Maybe you are using another driver version/config? 
Does script execution (alt+x) works with multiple queries?

Please post error stacktrace (you can get it in Error Log view: man menu Window->Show View->Error Log).
You can try to downgrade to 3.7.8 (http://dbeaver.jkiss.org/files/3.7.8/) - if queries will work ok then this is something in DBeaver.

**Comment by serge-rider** [comment]
I found a change which potentially can lead to this problem. Fix committed.

**Comment by StefanoRomano71** [comment]
Hello Serge,
I can cofirm ALT+X works both on mac and Win!
It executes queries one at time, but the patch can be very usefull.

Thanks for your kind support
SR
