### ISSUE TITLE
Row count

### ISSUE THREAD

**Issue by yansolo82** [serge-rider/dbeaver#1013]
Hello,

Would it be possible to have a row count option in the contextual menu of a resultgrid? 
It would be great when results exceeds the limit fixed.

No need to have it systematically for each query execution, on demand is fine

**Comment by serge-rider** [comment]
Total row count calculation will be added in the next version.
![image](https://cloud.githubusercontent.com/assets/6398845/21015026/5db12ef6-bd71-11e6-81b1-3a591b0416f2.png)
