### ISSUE TITLE
Close first result tab and pin tabs in general

### ISSUE THREAD

**Issue by loboaureo** [serge-rider/dbeaver#1014]
Hi, i wonder if would be posible to add a close button to the first result tab (if needed only when is not the unique result tab).

Also i think that would be nice a "pin" tab, so when you execute a new query don't close the pined tabs.

The reason to ask for this changes is that sometimes i need to launch several querys at the same time, keep only the ones than interest me and launch another pack of querys.

Sorry for my English, if i can clarify something, don't hesitate in ask.

**Comment by serge-rider** [comment]
You can pin tabs (from context menu on tab).
You can run multiple queries simultaneously using `ctrl+alt+x`.

**Comment by loboaureo** [comment]
I know the simultaneously using ct+alt+x

But i can't pin tabs, neither close the first one
![screenshot_1](https://cloud.githubusercontent.com/assets/681482/20831616/17c5750e-b886-11e6-8fd2-2919b77929b3.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/681482/20831617/17c7513a-b886-11e6-8c9e-e2236cf60651.png)

**Comment by serge-rider** [comment]
First tab is special. You can't close or pin it.
But you can do this with all other tabs (also you can rename them).

To execute some query in a separate tab you can use `ctrl+\`.

**Comment by loboaureo** [comment]
The screenshot of the maximize and close multiple results its from my fourth result tab

![screenshot_3](https://cloud.githubusercontent.com/assets/681482/20877729/e8004708-baca-11e6-9cff-e3b14babe84c.png)

**Comment by serge-rider** [comment]
Just make tab you want to pin active.

**Comment by loboaureo** [comment]
Thanks, i miss that detail
