### ISSUE TITLE
Unable to view multiple result sets

### ISSUE THREAD

**Issue by 0329liuken** [serge-rider/dbeaver#1015]
Been using DBeaver for a few months now and I loved it! One problem I have is that I am not able to view multiple result sets using neither my DB2 nor MySQL connection. Every time I run a new query, the old result set will be overwritten by the new one.

I am using the latest version (3.8) on Windows 10, could you tell me how to resolve this problem?

Thanks in advance for any help!

**Comment by serge-rider** [comment]
You can execute a query in a new tab (ctrl+/).
Also you can pin tabs (in the context menu)

**Comment by 0329liuken** [comment]
ctrl+/ will comment the selected line instead of executing it. Could you be more specific about pining the tab? Couldn't find the option anywhere. 

I am hoping to get a new result set in a single SQL editor each time after I run a section of code.

**Comment by serge-rider** [comment]
Sorry, ctrl+\

**Comment by serge-rider** [comment]
You can see all possible ways to execute SQL in SQL editor context menu.

**Comment by 0329liuken** [comment]
That worked! Thanks a lot!
