### ISSUE TITLE
Dbeaver not reflecting newly inserted rows in MySQL db for already open connection but works when disconnect and connect is performed

### ISSUE THREAD

**Issue by igupta** [serge-rider/dbeaver#1018]
I am using Dbeaver to connect to MySQL db on AWS machine. When there is a new entry in the table it is not reflected in the current connection I need to disconnect the db and reconnect again to make it work.
I am not using Dbeaver for inserting any row and only for reading purpose.

**Comment by serge-rider** [comment]
Most likely you are in transaction mode. You need to do commit or rollback or to switch into auto-commit mode to see changes made in other clients.
