### ISSUE TITLE
Database Navigator > Export selected sources

### ISSUE THREAD

**Issue by adaliszk** [serge-rider/dbeaver#102]
It would be nice if we can select multiple object (table, view, procedure, etc) and make an export script with one contextmenu item.

**Comment by serge-rider** [comment]
What is "export" - data, DDL?

**Comment by MatyCZ** [comment]
This can resolve #84.

**Comment by serge-rider** [comment]
#84 is mysql (mysqldump) specific. Maybe this is something more general?

**Comment by adamos42** [comment]
Something like the #84 would be great. The "export" should be tree item:
- Export DDL
- Export Data
- Export DDL & Data

Of corse a procedure, function, trigger and view does not have Data, so if just procedure selected then the Export Data options should be disabled (dont hide).
And yes, this should be a general solution.

**Comment by serge-rider** [comment]
This was resolved a time ago
