### ISSUE TITLE
Refreshing views - I can expand the empty view directory/folder

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1021]
When I refresh my views directory/folder it is possible to expand it even though it is empty. For other directories/folders this does work: when I refresh them and they are empty then I can't expand them.

**Comment by serge-rider** [comment]
I don't understand. View folder isn't special, i is expanded by the same rules as any other navigator folders.

**Comment by GiantCrocodile** [comment]
I can expand view when it is empty but I can't expand other folders when they are empty because there is no 'small little dark triangle' next to it to expand it.

**Comment by serge-rider** [comment]
Can't reproduce. View folder behaves exactly as any other folder. 
If there are no views and you expanded the folder then it'll be empty after refresh (unless some view was created in other client).

**Comment by GiantCrocodile** [comment]
Oh I see I was wrong. I had this scenario different in my mind. Then my suggestion is: If you refresh your database and the folder is empty, then you can't expand it.

**Comment by serge-rider** [comment]
DBeaver loads actual metadata on folder expand (i.e. it doesn't cache all possible elements in all folders). That's why it is collapsed by default. And I don;t think we should change this behavior.
