### ISSUE TITLE
Script feature for data transfer

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#1024]
Hi,

Sometimes I want to draw a plot with the data I fetch, however I have to export the data to a file and use that. Could it be possible to add an option to the Data Transfer dialog (when you right-click the result set > Export Resultset...) that would maybe run a script with the result set piped in ?

Thanks.

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/23094057/d4d38776-f602-11e6-8975-82ba5e63876f.png)
