### ISSUE TITLE
More info button for upgrades launches blank page in browser

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#1026]
The url is no longer loaded. Using chrome on ubuntu 15.04

**Comment by serge-rider** [comment]
Can't reproduce. Looks like Chrome doesn't work properly on some Linux machines.
Check this:  #778

DBeaver opens external web browser by running a URL in the program launcher. Maybe there are some issues with web browser config on Linux. Will investigate..

**Comment by serge-rider** [comment]
Also please check error/debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by rml1997** [comment]
Seems to launch in firefox now which works
