### ISSUE TITLE
slow and buggy after update to 3.8.1 on Spring STS

### ISSUE THREAD

**Issue by ahmed89albttashi** [serge-rider/dbeaver#1029]
Very slow to execute simple qury in local DB, IT's taking more than 10 seconds .

before upgrade it's just need time to click, 

Now many time "previous query still running"

BR

**Comment by serge-rider** [comment]
What database?
Is there anything in error log?
What is in Query Manager log (you need to enable metadata queries logging to see what actually happens)?

**Comment by ahmed89albttashi** [comment]
Postgresql 9.5.5
OS ubuntu 16.04

It was working fine before updated yesterday, 

problem start after I try to move Script tap in seprate window in STS Eclipse based.


It's looking working now after I restore it in  normal STS window.

**Comment by serge-rider** [comment]
It is still not clear what exactly is slow - query execution or UI rendering or something else.
Just tested in SpringSTS and it seems to be working well.

Check debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any errors.

**Comment by ahmed89albttashi** [comment]
Dear Serge, 

Thanks for your tracking & developing this important tool. 

After move script tap to seprate window, it's difficult to connect, slow SQL execution. 

hope it's clear to you .
