### ISSUE TITLE
CSV Import Fails Due to Cast Issue

### ISSUE THREAD

**Issue by ColinMc** [serge-rider/dbeaver#1030]
I'm running into an issue trying to import a CSV into SQL Server. From the error produced it looks like DBeaver is interpreting empty values (e.g. stub,,stub) as empty strings. It looks like there isn't a check somewhere in the import code to convert empty values to NULL.

Error Message:
> SQL Error [8169] [S0002]: Conversion failed when converting from a character string to uniqueidentifier.
SQL Error [8169] [S0002]: Conversion failed when converting from a character string to uniqueidentifier.
  Conversion failed when converting from a character string to uniqueidentifier.
  Conversion failed when converting from a character string to uniqueidentifier.

My workaround at the moment is to skip the columns and manually insert the column data that couldn't be inserted through the import. This also involves me writing a SQL statement to convert empty strings to NULL values after the data has been manually inserted.

**Comment by serge-rider** [comment]
How do you perform CSV import - do you use CSV/JDBC driver? As far as I know this driver always treats empty values as zero-length strings. Anyhow this is not DBeaver issue.

We are working on plain CSV import feature. Current database->database import over CSV/JDBC isn't so flexible.

**Comment by ColinMc** [comment]
@serge-rider I'm using the org.relique.jdbc.csv.CsvDriver driver. I wasn't sure if this was a driver or DBeaver issue. I'll see if the driver supports translating empty strings to null values. Thanks!
