### ISSUE TITLE
Associate with "connection" fromeditor

### ISSUE THREAD

**Issue by ross-cohen** [serge-rider/dbeaver#1032]
While working in the editor I often want a script to "associate" with a different "connection".   That is, I have some common sql that I want to run against dev and prod and test (etc).  Right now doing this requires finding the script in DBeavers project view.   It would be a very great convenience if it be done from the editor view a drop down or menu item.

**Comment by serge-rider** [comment]
You already can do this. Connection-selector combo is on the main toolbar. Also you can synchronize editor connection with current selection in database navigator (sync action is on the same main toolbar).

**Comment by ross-cohen** [comment]
1.  I figured out how to turn on the synchronizing between the project view and the current editor.   Thank you. 

2.  I never saw the connection selector because I have my Eclipse toolbar visibility set to "hidden" (vertical space is at a premium here).   Using Eclipse perspectives, I should be able to have my cake and eat it too (no toolbar in my java perspective, visible toolbar in the DBeaver perspective), but no go: Eclipse has only a single toolbar visibility setting for all perspectives.   I guess I'll assign a shortcut to toggle the toolbar visibility.   That should get me what I want, more or less.    Since I have reasonable workarounds, feel free to close this -- sorry to take up your time.
