### ISSUE TITLE
Regression in copying jsonb rows

### ISSUE THREAD

**Issue by ruuda** [serge-rider/dbeaver#1033]
In DBeaver 3.7.4, I was able to select and copy a single field from one row to a different row, and then apply that change. The type of the column is `jsonb` in a Postgres database.

In later versions (3.8.1 is the latest I tried, but I encountered this regression before too), this no longer works. Pasting still works and the field shows up as orange, but when I click the green “save” checkmark, I get an error message:

> SQL Error [42804]: ERROR: column "foo" is of type jsonb but expression is of type character varying
> Hint: You will need to rewrite or cast the expression.
> Position: 46
> org.postgresql.util.PSQLException: ERROR: column "foo" is of type jsonb but expression is of type character varying
> Hint: You will need to rewrite or cast the expression.
> Position: 46

**Comment by serge-rider** [comment]
Thanks for report

**Comment by ruuda** [comment]
Wow, that was a quick fix, great!

**Comment by vladimarius** [comment]
This error is present in version 22.0.2.202204021640

**Comment by asc0910** [comment]
This error is present in version of 22.3.1.202212251901

**Comment by harmanshal** [comment]
Error present in version Version 24.1.1.202406231636
