### ISSUE TITLE
Not able to connect to Hive even after proper Kerberos auth and JCE

### ISSUE THREAD

**Issue by praxnet** [serge-rider/dbeaver#1036]
@serge-rider 

getting following error 
Could not open client transport with JDBC Uri: jdbc:hive2://*.*.*.* : ***/default;principal=hive/****URL****@REALM.NET: GSS initiate failed
  **org.apache.thrift.transport.TTransportException: GSS initiate failed**

I am doing ssh tunnel to connect to Remote host

steps i have tried till now.
I have configured Kerberos and done kinit , also checked for valid ticket using kinit
+ jce installation are on there on all the nodes of my hadoop cluster
+ I have tried using UnlimitedJCEPolicyJDK8 jars in my system
(i am macbook user and using DBeaver 3.8.1 EE)

**Comment by r-richmond** [comment]
This error isn't related to dbeaver it is related to your kerb settings. make sure you have your kerb5.conf setup properly.

**Comment by r-richmond** [comment]
@praxnet I took some time to write out a blog post on connecting to hive. If you're still having issues perhaps this will help

http://justnumbersandthings.com/2017-05-06-Dbeaver-Hive-Kerberos.html

**Comment by hernk** [comment]
well, i've different condition. I made successfully connection to hive via dbeaver several month a go, but i didn't know what happened to my mac. Accidentally it failed to connect till now. I'll check and follow those steps didn't work. 
Error message : 
a. unable to obtain principal name
-Djava.security.krb5.debug=true
-Djava.security.krb5.conf=/etc/krb5.conf   ---> without double quote
-Djavax.security.auth.useSubjectCredsOnly=false

b. GSS initiate failed 
-Djava.security.krb5.debug=true
-Djava.security.krb5.conf="/etc/krb5.conf"   ---> with double quote
-Djavax.security.auth.useSubjectCredsOnly=false

**Comment by ArtichA** [comment]
@hernk Are you able to get it to work? If so, can you share JDBC URL template, Kerberos settings and steps to initiate Kerberos Auth from DBeaver?
