### ISSUE TITLE
Redshift tcpKeepAlive not working

### ISSUE THREAD

**Issue by mactsing** [serge-rider/dbeaver#1038]
I set the tcpKeepAlive to TRUE and Keep-Alive to 9999, but i got disconnected around 2-3 mins.. Is anyone experiencing the same issue? How do I keep myself always connected?

**Comment by serge-rider** [comment]
9999 seconds is much bigger than 3 minutes. You need to set smaller keep-alive interval (e.g. 60 seconds).

If driver settings won't help then you can try to use DBeaver Keep-Alive settings (it is on the General page of connection properties dialog).
