### ISSUE TITLE
Invalid preference category path (Eclipse Mars.1 x64, Dbeaver 3.5.6)

### ISSUE THREAD

**Issue by jakevr** [serge-rider/dbeaver#104]
After Dbeaver installation I receive the following warning each time I start Eclipse (may be found in ErrorLog):
> Invalid preference category path: org.jkiss.dbeaver.preferences.drivers (bundle: org.jkiss.dbeaver.ext.oracle, page: org.jkiss.dbeaver.preferences.oracle.general)

Additionally two warnings appear:
Before exiting eclipse:
> The workspace will exit with unsaved changes in this session.

After eclipse startup:
> The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

Stacktrace will be provided if needed

**Comment by serge-rider** [comment]
Bad preference path error will be fixed in the next version.
Thanks for report.
Warning "The workspace will exit with unsaved changes in this session." is a known issue. It is harmless (it happens when DBeaver cleanups temp files), but annoying. Will try to fix it.
