### ISSUE TITLE
Problem binding variables of DB2 in DBeaver 3.7.8

### ISSUE THREAD

**Issue by flequi** [serge-rider/dbeaver#1040]
Hi, I open a new Issue for better trace of the problem, because my case it's not about sql injection or MySQL like the issue #1010.

I have a similar problem with a DB2 Connection with the JDBC4.0 driver (with the older JDBC 3.0 driver too) when I set named variables in my query never works.

select tca.descripcion, ca.* from MOVTO.configuracion_aplicacion ca
inner join MOVTO.tipo_configuracion_aplicacion tca on tca.id_tipo_configuracion_aplica = ca.id_tipo_configuracion_aplica
where tca.id_catalogo_aplicacion IN (:idcat1,:idcat2);

If I set anonimous variables it works fine, but I don't want to remember the order of all variables of more complex queries, for this I prefer to use named variables.
select tca.descripcion, ca.* from MOVTO.configuracion_aplicacion ca
inner join MOVTO.tipo_configuracion_aplicacion tca on tca.id_tipo_configuracion_aplica = ca.id_tipo_configuracion_aplica
where tca.id_catalogo_aplicacion IN (?,?);

I set the parameters with the correct TYPE of the DB column in the Binding window:
![image](https://cloud.githubusercontent.com/assets/4034173/20791604/1bd1c288-b7be-11e6-8b39-6621ff0e6f22.png)

The DDL of the table it's this:
CREATE
    TABLE TIPO_CONFIGURACION_APLICACION
    (
        ID_TIPO_CONFIGURACION_APLICA SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        DESCRIPCION VARCHAR(100) NOT NULL,
        **ID_CATALOGO_APLICACION INTEGER NOT NULL,**
        CONSTRAINT PK_TCONFIGAPLICA PRIMARY KEY (ID_TIPO_CONFIGURACION_APLICA),
        CONSTRAINT FK_TCONFAPL_CATAPL FOREIGN KEY (ID_CATALOGO_APLICACION) REFERENCES CATALOGO_APLICACION (ID_CATALOGO_APLICACION)
    );

The error I get it's this and I attach the ErrorLog exported in text format:
![image](https://cloud.githubusercontent.com/assets/4034173/20791686/80ea3574-b7be-11e6-9fe9-6289c6e54641.png)

[ErrorParameterBinding.txt](https://github.com/serge-rider/dbeaver/files/624353/ErrorParameterBinding.txt)

**Comment by serge-rider** [comment]
Please update to the recent version (3.8+). 
Parameters binding was changed there and this issue shouldn't happen.
