### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by slavatr** [serge-rider/dbeaver#1041]
I am running dbeaver 3.8.1, 64 bit for MySQL on Ubuntu 14.04. It seems that dbeaver works hard even in idle mode. It constantly utilizes ~30% of CPU on my machine. 

> 

 PID       USER      PR      NI    VIRT          RES        SHR   S    **%CPU**    %MEM     TIME+ COMMAND                                                                                                
13114    slavat       20       0     5934752   308356    31300 S      **30.5**        3.8            548:11.55 /usr/bin/java -jar /usr/share/dbeaver.......

>

**Comment by serge-rider** [comment]
It shouldn't (in idle mode it should consume about 0% of cpu).
Please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and attach it here.

**Comment by slavatr** [comment]
[thead-dump.txt](https://github.com/serge-rider/dbeaver/files/637034/thead-dump.txt)
Attached thread dump

**Comment by serge-rider** [comment]
Don't see anything suspicious or DBeaver-specific. Seems to be Eclipse platform issue.
Check this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=478962

One of solutions is to run `export SWT_GTK3=0` in shell before running DBeaver.

**Comment by slavatr** [comment]
Ok, thanks

**Comment by serge-rider** [comment]
Did that help?

**Comment by slavatr** [comment]
It seems so. After setting SWT_GTK3=0, the CPU usage didn't exceed 2% in idle mode. Is there any dbeaver's configuration file where I can set this setting?

**Comment by serge-rider** [comment]
Generally all options can be added in dbeaver.ini.
By default dbeaver.ini on Linux already contains
```
--launcher.GTK_version
2
```
If it doesn't help then manual env variable set is the only workaround.
