### ISSUE TITLE
Auto-commit and manual commit buttons

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#1046]
![image](https://cloud.githubusercontent.com/assets/14179578/21043394/f41306aa-bdf6-11e6-86ed-c968b0e3214a.png)

As you can see the label should be '_Manual commit_' but is '_Auto commit_'
The right label appears only the first time you switch but then is wrong.

The labels aren't translated in italian as well

**Comment by serge-rider** [comment]
Good point
