### ISSUE TITLE
Oracle package compile cache error, doesn't show compile errors.

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1047]
Oracle package editing has some issues, when you compile a package it doesn't show any error until you refresh object list (with F5 key).

Reproduce:

1- Create a package specification and body:

```
create or replace PACKAGE DEL_TEST AS 

PROCEDURE hello;

END DEL_TEST;
```

```
PROCEDURE hello
IS
BEGIN
    NULL;
END;
```

2 - Manually edit package, rename package specification procedure hello to hellooo
3 - Press ctrl + s to persist changes.
4 - Right click in package and press compile. (Doesn't show any errors)
5 - Right click in package and press refresh.
6 - Right click and press compile (Now shows compile errors)

Also when you open a package it doesn't load the content from DB, it just loads locally cached content of the package.

Why persist changes do not compile package? There is a key for saving + compiling? (That's the case for 99,9% of times)

I'm amazed of all features and perfomance of dbeaver compared with sqldeveloper, but this one keeps me away from actively using it.

**Comment by serge-rider** [comment]
This is because Oracle driver doesn't throw an error when you save/compile invalid procedure. So regular SQL execution says that everything is fine.
There is a special Oracle mechanism of procedure validation.
Potentially it is possible to somehow attach this validation to procedure save action.

**Comment by yevon** [comment]
Ok!, I understand that save option doesn't show any error when you execute it (due to driver issues), but when you compile it, it throws errors. So, if you compile it and doesn't show any errors, then refreshing object list, and compiling the same, why it doesn't show any errors the first time and yes the second? isn't it a caching issue?

The simplest soultion would be behaving like standard oracle sqldevelopr does, save just triggers  persist changes and compile in one shot.

There is also caching issues when a package is being edited concurrently:

If you edit it with another remote client, when you open it in dbeaver again it doesn't show current package code, it just shows last persisted content by dbeaver.

Try this:

1 Create package with dbeaver, edit it and close package object view.
2 Edit with another client and compile changes.
3 Open package object view in dbeaver, and you cannot see changes made in step 2 (Current DB code)

**Comment by serge-rider** [comment]
I think I'll just validate object state after DDL execution (there is no need in extra compile invocation because it is done by Oracle).
That's quite easy, see it in the next version.
