### ISSUE TITLE
Create oracle package doesn't auto create package basic specification and body

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1048]
Whe you create a package with GUI assistant (Create package with right click), it should auto fill basic package specificacion.

1 - It asks you for package name, but it doesn't provide a package specification.

create or replace PACKAGE DEL_TEST
AS
   /*Provide here your function specifications*/
END DEL_TEST;

create or replace PACKAGE BODY DEL_TEST
AS
   /*Provide here your function implementations*/
END DEL_TEST;

**Comment by serge-rider** [comment]
Good point
