### ISSUE TITLE
Help system broken

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#105]
Help system (F1) is broken for a long time.
Has to do something with it.

**Comment by adamos42** [comment]
If you make a HTML5 site for the help menu, you can make it interactive: you can show the open tickets from github or manage a FAQ online. Also it would be nice If we can send a report for you with every information what you need for debugging if we found something like in Eclipse Mars :)

**Comment by serge-rider** [comment]
Silly and heavyweight Eclipse help system will be replaced with GitHub Wiki.
