### ISSUE TITLE
sql autocomplete completes key words as uppercase. Is it possible to change this to lower?

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1050]
autocompletion of keywords is done as upper. Can I change this to lower case somewhere? (or better yet match the case of the first letter I've typed?)

**Comment by serge-rider** [comment]
Preferences->General->Editors->SQL Editor->SQL Completion->Insert Case

**Comment by r-richmond** [comment]
Thanks!

**Comment by andresvargasr** [comment]
File -> Properties -> Editors -> SQL Editor (Then select Global Settings in the right corner if you want to apply overall data sources) uncheck "Convert keyword case"

**Comment by ThusharaBuddhika** [comment]
Version 6.2.4.201911031605
Preferences -> Database -> Editors -> SQL Editor -> SQL Formatting -> (Change Keyword case to Upper) -> Apply and Close

**Comment by genamiga** [comment]
I will be great if we can have UPPERCASE for reserved words and lowercase for table/column

**Comment by Venryx** [comment]
I wish there were an option to say "LEAVE THE CASING ALONE!". (or more precisely, don't activate "autocomplete" if the user has already typed out the entire keyword manually; see last paragraph)

Personally I prefer uppercase (for clearer visual distinction between keywords and table names), but when I am constructing SQL in response to someone on Slack/Discord/StackOverflow, I try to use the same casing as the person I'm responding to. This is hard to do when DBeaver keeps changing the case of all the keywords as I'm typing.

I want DBeaver to just not make any casing-changes when all I'm doing is typing my query. (It can make sense to use my preferred casing if I'm clicking on autocomplete options, but if I've already typed out the entire keyword -- and am just pressing space to start typing the next keyword -- DBeaver should not interpret that as an "autocomplete" that it needs to apply casing for, but instead just as a literal space. Even if I press "escape" to close the autocomplete panel, DBeaver _still_ applies its casing rules when I subsequently press space.)

**EDIT:** Nevermind, apparently this option already exists! Just set the `Preferences -> Database -> Editors -> SQL Editor -> Code Editor -> Auto format -> Convert keyword case` option to disabled. Keeping my comment here for others with the same question.
