### ISSUE TITLE
Question/feature request: Would it be possible to add a sort option for project files based on last update date

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#1051]
Not sure how much is restricted by the eclipse platform, but I was wondering if it could be possible to add an option to display files in the project pane with a sort option based on last update date.  I think this can benefit users like me who deal with lots of ad-hoc scripting and where I organize them primarily outside dbeaver with other files.

**Comment by serge-rider** [comment]
1. In project explorer view click on "Configure" action in toolbar (or right click on columns header -> Configure columns).
2. Set column "Modified" visible.
3. Now you can sort by script modify time by clicking on column name.

**Comment by dbza** [comment]
Thanks,it works for files, but modified date is not populated for folders.
