### ISSUE TITLE
Add missing keywords and functions to autocomplete in PostgreSQL

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1052]
- [ ] keyword 'materialized' missing
- [ ] function `current_database()` missing
- [ ] not all data types are suggested in CREATE TABLE queries: for example serial. This should be dynamically read from database system's tables and not hardcoded.

**Comment by GiantCrocodile** [comment]
Function `current_datatbase()` is also missing.

**Comment by serge-rider** [comment]
See fix in the next version.
All data type aliases (including serial) will be added as type names.

**Comment by GiantCrocodile** [comment]
This didn't work out as expected @serge-rider: if I type `seri` and press CTRL+SPACE for auto completion I get just `SERIALIZABLE` as suggestion, not `serial`.

**Comment by serge-rider** [comment]
Yep, you are right. I didn't test this for auto complete.
Fixed.
