### ISSUE TITLE
Wrong hotkey labels in table's data editor view

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1053]
If you move your mouse on save or cancel button of the table's data editor view you see that `CTRL + ALT + S` is the hotkey to save and `CTRL + ALT + R` to cancel the data changes. In real the hotkey for canceling works but the hotkey for saving is broken to me and bugged. I can save when I press `CTRL + S` so I think the button is labelled wrong or wrong hotkey is bound.

Another issue I just noticed with this: `CTRL + S` works fine. `CTRL + ALT + S` causes an duplicate primary key insert in PostgreSQL. To reproduce this try this:

1. insert a row in table and save (fill out every field, even the primary key field)
2. insert a row in table and save (fill out every field, except primary key field - leave it NULL)

If you try the same with `CTRL + S` it does work!

**Comment by serge-rider** [comment]
CTRL+S saves current editor state (this includes all changes - metadata, data, script, anything).
CTRL+ALT+S saves only changes in results editor.

In case of table data editor there is no difference between these shortcuts (unless you edit metadata too).

**Comment by GiantCrocodile** [comment]
I don't know what you mean with metadata exactly but I don't see a reason why one of the both shortcuts fails then. I will create a gif in some hours to show you what I do.

**Comment by serge-rider** [comment]
Metadata is database structure. E.g. you can create/change columns in a table and these changes can be saved with CTRL+S.

I can't reproduce fail with CTRL+ALT+S. Please attach gif or provide steps to reproduce.

**Comment by GiantCrocodile** [comment]
Ah then I can tell you that I didn't change database's or table's structure and thus no change in metadata happened.

**Comment by serge-rider** [comment]
Ok.
But in this case there is no difference between CTRL+S and CTRL+ALT+S (shouldn't be).

**Comment by GiantCrocodile** [comment]
Steps to reproduce this in PostgreSQL:
1. start with a table with 2 fields (one primary key, one varchar)
2. insert 3 rows with primary NULL and some strings, save with CTRL + ALT + S
3. insert a fourth row with primary key one higher than last inserted primary key and save with CTRL + S

A duplicate unique key error (same primary key as previous one is being tried to be inserted) happens.

**Comment by serge-rider** [comment]
There is no difference between CTRL+S and CTRL+ALT+S in this test case (you can see actual SQL queries in Query Manager view).
If you use explicit key value for auto-generated columns it may conflict with generated value.

**Comment by GiantCrocodile** [comment]
How comes that if I insert ids 1, 2, 3 automatically and insert 4 then manually that he tries to insert 3 then and not the 4? I think this is the problem which leads to the duplicate key error. While I insert them no script or whatever took number 4 and the database itself should be able to determine that 1-3 are used already and 4 is the next. So I don't know why 3 is chosen again. If I try to save again, then the error disappears and it saves with id 5 (not 4).

**Comment by serge-rider** [comment]
I believe that this is a PostgreSQL-specific behavior. You can see what actual queries are executed by DBeaver. If any of them is not correct then this is a bug.
Anyhow this is not related to shortcuts.
