### ISSUE TITLE
Bug in reconnecting on startup

### ISSUE THREAD

**Issue by zsom** [serge-rider/dbeaver#1054]
If I close Dbeaver with opened connections, then the next time I'm starting DBeaver, it's try to reconnect that connections.

It's fine, but if the connections can not be estabilished (because I'm offline) than it takes a lot of time to start the program.

I think a lower timeout could solve this problem. Please fix it!

Thanks
Zsom

**Comment by zsom** [comment]
Something similar happens when you start Dbeaver with a connection, which doesn't has a stored pasword.
The UI won't be ready until you enter the password or cancel that connection.

**Comment by serge-rider** [comment]
Yes. This is because of Eclipse editors state restore strategy.
I'm going to implement some lazy editor initialization so actual connection attempt will happen after main window show up.
