### ISSUE TITLE
Each tables appear twice in the result of the search

### ISSUE THREAD

**Issue by dudul08** [serge-rider/dbeaver#1055]
Hi,
If i search  tables with the search function (by name filter containt),  each tables appear twice in the result of the search.
I have this problem on DBeaver 3.8.1 but not on DBeaver 3.6.1.
The database is postgresql.

Thanks

![search_result](https://cloud.githubusercontent.com/assets/16609450/21100974/11f31b60-c077-11e6-840a-69095d6a7fc2.PNG)

**Comment by serge-rider** [comment]
Thanks for report

**Comment by dudul08** [comment]
You're welcome !
Thanks to you ! DBeaver is a great tool !
