### ISSUE TITLE
No commit available after "Set to NULL" operation.

### ISSUE THREAD

**Issue by roberto2357** [serge-rider/dbeaver#1058]
Hi, in DBeaver 3.8.1, I clicked with right mouse button on a nullable field of an Oracle table and I choosed "Set to NULL". 
The field background became correctly yellow but it did not allow me to commit the edited value to database. To do it I must refresh or exit from table and answer "Yes" when the program asks me about saving the modified data...

Thanks.

**Comment by serge-rider** [comment]
I need to save data (CTRL+S or CTRL+ALT+S or click on save action in the bottom toolbar).
Commit becomes available when you switch into transactional mode (in main menu or main toolbar).

**Comment by roberto2357** [comment]
Ok Serge but I intended that exactly CTRL+S and toolbar button are not available (toolbar button is disabled) after this operation :-)
I hope you can reproduce this. I use DBeaver 3.8.1 - 32 bit installer for windows (it worked in 3.7.6 version).
Thank you so much!

**Comment by serge-rider** [comment]
No, I can't reproduce that. setting to NULL (thru context menu or with CTRL+ALT+N) activates Save/Cancel/Script actions.
Try to switch to some other view and then back to results editor - it helps in some cases.
