### ISSUE TITLE
Can't add records from the GUI grid in Cassandra

### ISSUE THREAD

**Issue by ppanhoto78** [serge-rider/dbeaver#1060]
I've noticed this since I've upgraded to 3.8.0 EE and then on 3.8.1 EE.

to reproduce the problem, steps are simple:

1. connect to a Cassandra Database.
2. open a table in the grid editor.
3. click on the + sign at the bottom of screen: a new line with NULL values will appear.
4. try to edit fields of the new record: the partition key and other fields that compose the primary key won't be changed (eventually, one character will be allowed) and the rest of the fields will be edited normally.

**Comment by serge-rider** [comment]
Yes, key columns are read-only even for new rows. This is a bug.
Thanks for report.
