### ISSUE TITLE
NULL value in result where the result is not NULL

### ISSUE THREAD

**Issue by sjstoelting** [serge-rider/dbeaver#1062]
The Problem occurred with PostgreSQL 9.5. 
Database to reproduce: Chinook, see [http://chinookdatabase.codeplex.com/](http://chinookdatabase.codeplex.com/)
Query to reproduce: 
```SQL
WITH tracks AS
	(
		SELECT "AlbumId" AS album_id
			, "TrackId" AS track_id
			, "Name" AS track_name
		FROM "Track"
	)
, json_tracks AS
	(
		SELECT row_to_json(tracks) AS tracks
		FROM tracks
	)
, albums AS
	(
		SELECT a."ArtistId" AS artist_id
			, a."AlbumId" AS album_id
			, a."Title" AS album_title
			, array_agg(t) AS album_tracks
		FROM "Album" AS a
			INNER JOIN json_tracks AS t
				ON a."AlbumId" = (t.tracks->>'album_id')::int
		GROUP BY a."ArtistId"
			, a."AlbumId"
			, a."Title"
	)
SELECT artist_id
	, array_agg(row_to_json(albums)) AS album
FROM albums
GROUP BY artist_id
;
```

This query returned the correct JSON result as not null in version 3.7.2. [psql](https://www.postgresql.org/docs/9.5/static/app-psql.html) does show the JSON result as not NULL.

**Comment by serge-rider** [comment]
You need to upgrade to the recent DBeaver version. JSON support was improved in one of the last versions.

**Comment by sjstoelting** [comment]
I am using the current version, 3.8.1. I only mentioned 3.7.2, because that was the last version, where the query definitely worked.

**Comment by serge-rider** [comment]
Ah, I see. I've reproduced that.

**Comment by serge-rider** [comment]
See fix in the next version.
Thanks for report.
