### ISSUE TITLE
FIX saved changes to data do not apply without disconnecting and commiting changes

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1064]
## use case:

1. open a mariaDB/MySQL data table
2. edit some data
3. press Ctrl+S to save and commit to server

## expected behaviour:
data is saved in server

## actual behaviour:
data is not saved

## workaround
disconnect from db, then answer Yes to "Do you want to commit current transaction?"

**Comment by serge-rider** [comment]
If you are in transactional mode then you just need to click on Commit action in main toolbar (or main menu or CTRL+ALT+SHIFT+C). In auto-commit mode all changes are saved immediately.

**Comment by allanlaal** [comment]
cool :D 
sorry, didn't see the buttons at first glance on my hiDPI screen
