### ISSUE TITLE
Disable editing in result view when appropriate

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1065]
This is a usability suggestion. 

Editing of query results by the user should be disabled, when it is known that persisting changes will not work (such as when selecting from joined tables or there is no appropriate write permission). Probably not all such cases can be easily/reliably detected in advance.

What happens now is that the user can edit stuff, but gets an error when trying to persist the changes, but only when the effort has been spent already. This can lead to high user frustration - "I did all this editing for nothing!". Disabling the editing would have completely prevented this.

**Comment by serge-rider** [comment]
We going to add joined results edit in future versions.
For now I'll just disable editor.
