### ISSUE TITLE
ADD Ability to reload/refresh/submit/execute a SELECT query in SQL Editor to get a live/interval view of the results

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1066]
## use case:

I want to watch some data in a table. I write a custom query with SQL Editor.
I then select the interval I wish the SQL Editor to execute my query from a preset of:
* 1sec
* 5sec
* 30sec
* 1min
* 5min
* custom (opens dialog)

or have just custom there at first and list 5 most recent custom intervals

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/26286110/add5ebae-3e65-11e7-854d-611be5a942fd.png)

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/26286127/0388eb6e-3e66-11e7-8345-643f8ade01ed.png)

This is the first draft. Any improvements should be tracked in separate tasks.

**Comment by allanlaal** [comment]
@serge-rider you're like my favourite developer in the world :D
