### ISSUE TITLE
Show permissions in properties panel

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1067]
Please add a tab which shows granted privileges on an object in the properties panel.

Right now it's a bit hard to find this info. Some of it is available in the information_schema.

**Comment by serge-rider** [comment]
What database?

**Comment by lacanoid** [comment]
Postgres, but information_schema contains permissions information on several other databases too, perhaps that can be of some use.

**Comment by serge-rider** [comment]
Roles and tables permissions panel will be added in 3.8.4.
It is quite simple for now - read-only and without extra options (grant permissions and hierarchy permissions). However it is quite useful.
Further improvements should be done in separate issues.

![default](https://cloud.githubusercontent.com/assets/6398845/21962473/183ca21c-db38-11e6-92e6-9d2e30875b79.png)

**Comment by lacanoid** [comment]
Wonderful!
