### ISSUE TITLE
Auto-format query does not pay attention to comments or limit

### ISSUE THREAD

**Issue by tannenzaepfle** [serge-rider/dbeaver#1068]
The autoformat doesn't seem to take comments adequately into account.

```
select foo
from bar
where baz = '1'    # makes sure baz equals one 
limit 10
```

When this gets auto-formatted, it changes into this:

```
select
	foo
from
	bar
where
	baz = '1'    # makes sure baz equals one limit 10
```

I've also tripped over things like 
`	baz = '1'   #and bat not in('1','2','3')
`
where the autoformat acted on the code that was commented out but not entirely.

```
#and bat not in(
	'1',
	'2',
	'3'
) 
```

I'm hardly upset about the second one, but the "limit 10" disappearing into the comment is annoying.

I'd rather the auto-format just give "limit" statements a newline and be done with it.

**Comment by serge-rider** [comment]
SQL formatter didn't use SQL dialect-specific comments. will be fixed in the next version.
Thanks for report.
