### ISSUE TITLE
Request: Add Project Name as Variable to Export

### ISSUE THREAD

**Issue by kyleflan** [serge-rider/dbeaver#1072]
It would be useful to be able to use the current project name in the export result set wizard. For instance, all of my exports are set to a general DBeaverExport folder which I then manually file away within an Export folder within the project. While the timestamp is useful to prevent overwriting or duplication, it would be nice to be able to specify the project name as a prefix to the filename, or as part of the path to the directory where the export is being saved.

E.g., something like this:

![image](https://cloud.githubusercontent.com/assets/5608074/21267484/29b720c4-c370-11e6-83da-973c5074d9bb.png)

**Comment by serge-rider** [comment]
Ok. That's easy.
