### ISSUE TITLE
I can't find Cassandra connection

### ISSUE THREAD

**Issue by CostinMarzea** [serge-rider/dbeaver#1075]
While trying to create a new connection I couldn't find Cassandra and MongoDB in the drop-down list

**Comment by serge-rider** [comment]
You need to download EE version.

**Comment by CostinMarzea** [comment]
I’ve got it. Thanks

Kind Regards,
Costin Marzea
CTO

[cid:image001.png@01D258A9.B5CE01E0]<http://www.aqurate.net/>

מאת: Serge Rider [mailto:notifications@github.com]
נשלח: שבת 17 דצמבר 2016 20:50
אל: serge-rider/dbeaver‏ <dbeaver@noreply.github.com>
עותק: Costin‏ <costin@Aqurate.co.il>; Author‏ <author@noreply.github.com>
נושא: Re: [serge-rider/dbeaver] I can't find Cassandra connection (#1075)


You need to download EE version.
