### ISSUE TITLE
New column default value NULL

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#108]
If I make a new column for a table in Firebird and I give the default value NULL then the script will be 'NULL' so I have to remove the quotes and run the alter in a script. Is there any way to give a ``DEFAULT NULL`` option to a new column? This problem mybe not only related to Firebird, but I did not tested other databases.

**Comment by serge-rider** [comment]
By default DBeaver quotes all string literal entered as column defaults. I could remove quoting at all but as I remember some drivers returns unquoted string literals for default values. Need to investigate this issue a bit more.
BTW, just our of curiosity - why do you need NULL as default value? NULLs are already defaults for all columns.

**Comment by adamos42** [comment]
Somehow (maybe somebody configured that way) VARCHAR fields default value is empty string. INTEGER columns default value is 0, but I want NULL :)

**Comment by serge-rider** [comment]
I see.
Ok, I'll try to make some workaround..

**Comment by adamos42** [comment]
a right click make it NULL is a solution also and there you can put the [NULL] tag into the default value cell

**Comment by serge-rider** [comment]
Default values won't be escaped anymore. String literals should be escaped manually.
MySQL/Maria keeps string literal unescaped in system metadata so I'll escape them during metadata load.
