### ISSUE TITLE
slow query execution

### ISSUE THREAD

**Issue by repo2kanagaraj** [serge-rider/dbeaver#1080]
Sql Server query execution in very slow : 

OS : ubuntu 16.04(My Desktop)
SQL SERVER VERSION: 11.0.3128.0 ( Destination DB server)
DBeaver : 3.8.2

**Comment by serge-rider** [comment]
More details needed (I can't reproduce that)
1. How slow exactly?
2. Does ANY query executes slow or just some?
3. Does table data editor work slow or only custom SQL queries?
4. Open Query Manager view (main menu Window->Show View->Query Manager) and check actual query execution performance.
5. Did you try to execute the same query in previous DBeaver versions?

**Comment by repo2kanagaraj** [comment]
1) Connections itself slow(~1 minute it is taking to connect), i check with other editors and it works fine
2) all query's execution time is very high
3) there is only 50 records in that table
4) i have attached the image for this
![screenshot from 2016-12-19 16-18-06](https://cloud.githubusercontent.com/assets/7928874/21310114/09d2b324-c607-11e6-8a76-a2c10cfe3655.png)

5) i checked 3.78, 3.8.0 and 3.8.2( all are same issues)

**Comment by serge-rider** [comment]
Maybe it is a GTK issue (i.e. UI rendering is slow not query execution).
Check this: #1041
Try to run `export SWT_GTK3=0` before starting DBeaver.

**Comment by repo2kanagaraj** [comment]
ok thanks

**Comment by serge-rider** [comment]
Did this help?

**Comment by repo2kanagaraj** [comment]
yes, it works fine. but i need permanent fix, could you help me to do that.

i guess it will be "echo export SWT_GTK3=0 ~/.bashrc"

is it solve the above problem?

Thanks
Kanagaraj

**Comment by serge-rider** [comment]
Yes, it should. Or you can create some bash script which will set this variable+start DBeaver.

Unfortunately I can't fix this for everyone because this problem appears only on some Linuxes. Maybe result of conflict of SWT with window manager or some specific system settings.

**Comment by pdelteil** [comment]
I have the same issue. With version 4.0.4 but the fix didn't help. 

I'm using Ubuntu 17.04. I've tested the same queries using sqlcmd from the same host to the very same SQL Server and the results of the queries are 50 to 100 times less (few seconds against 15 minutes or more). 

Using Windows 7 in the same machine and the same queries takes around the same time sqlcmd takes. 

Any ideas?
