### ISSUE TITLE
no sybase stored proc results shown after execution

### ISSUE THREAD

**Issue by sqlpronj** [serge-rider/dbeaver#1084]
hi,

I'm new to dbeaver and am using version 3.8.1.

I use it to do t-sql development on Sybase servers running ase version 15+. When I run plain sql cmds, the resulting rows are shown. But when I run a stored proc like sp_who, only the proc's executing statistics are shown, not the actual results returned by the proc itself.

Please let me know how to correct this. I've seen other people do it successfully from dbeaver in my workplace, but they are not sure what to set to make it work.

Thank you.

SC

**Comment by serge-rider** [comment]
This works ok (all standard sp_* procedures return some resultset, sometimes multiple resultsets) on SQL Server. Unfortunately I don't have a live test Sybase server. Maybe there is some SQL syntax difference or maybe you use wrong driver. Did you try jTDS driver?

**Comment by serge-rider** [comment]
Closing.
Please reopen if any new information/details will appear.
