### ISSUE TITLE
Auto complete for procedures

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1085]
It would be nice to have auto complete for procedures. I'm missing it in MariaDB but no idea if it is missing somewhere else too.

**Comment by ced75** [comment]
Hi,

With PostgreSQL, it already works.

**Comment by serge-rider** [comment]
It works with MySQL/MariaDB as well. But you need to type first letter(s) of procedure name and press `ctrl+space` otherwise only table names will be shown.

**Comment by GiantCrocodile** [comment]
I can't approve this @serge-rider. I always press `CTRL+space` in editors when I miss a suggestion but there is none: The results shown doesn't change after pressing this hotkey. I do not see my procedure suggested but I can call it successful.

**Comment by serge-rider** [comment]
Still can't reproduce. Please confirm it still doesn't work or close this ticket.

**Comment by GiantCrocodile** [comment]
I'm not able to reproduce this as I do not work with MariaDB anymore at the moment. This issue is more than a half year old so I suspect that this is fixed and was somehow a side-effect.
