### ISSUE TITLE
On Open - "Phantom" script editor window

### ISSUE THREAD

**Issue by JHGelpi** [serge-rider/dbeaver#1086]
This issue has persisted on previous releases and exists on current release (3.8.2).  When opening DBeaver a "phantom" script window opens[1].  Even after connection to database (Oracle) the script window cannot be interacted with.  The only option is to close it and open a new window.

System information:
OS: Fedora 24
Memory: 11.4 GiB
Processor: Intel Core i7-4600U CPU @ 2.10GHz x 4
OS Type: 64-bit
Graphics: Intel Haswell Mobile
GNOME: Version 3.20.2
Disk: 245.7 GB

[1]
![dbeaver_bug_1](https://cloud.githubusercontent.com/assets/11323714/21352617/4f8724de-c690-11e6-8229-6402407f2fb3.png)
![dbeaver_bug_2](https://cloud.githubusercontent.com/assets/11323714/21352618/4f87b732-c690-11e6-95e7-e45157c30cbb.png)

**Comment by serge-rider** [comment]
This is a known bug. This happens because DBeaver deletes empty SQL files on editor close (or application close).
Will fix this (I had to do that a long time ago) in 3.8.3
