### ISSUE TITLE
Timezone issue while accessing MY SQL via DBeaver

### ISSUE THREAD

**Issue by Dheepumsr** [serge-rider/dbeaver#1088]
Hi,

When I try to connect MY SQL server using DBeaver client, I am getting below error. Could you please help me out.

SQLException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Thanks

**Comment by serge-rider** [comment]
Seems to be the same as  #573.
This is 6.x MySQL driver problem. In most cases this issue can be resolved by using 5.1.x driver (this is actually a default driver in DBeaver).
If you already use it then you need to set serverTimezone parameter in connection driver properties (e.g. UTC)

**Comment by Dheepumsr** [comment]
Thanks for your help.
After downgrading to MY SQL 5.1.39 started working.

**Comment by mnezmah** [comment]
For me this worked:
right-click on connection - edit connection.
Under connection settings set 'Server time zone' to your zone.Click OK

**Comment by soamazyng** [comment]
@mnezmah this work for me, thank you so much!

**Comment by baremarco** [comment]
> 
> 
> For me this worked:
> right-click on connection - edit connection.
> Under connection settings set 'Server time zone' to your zone.Click OK

Work for me too, thaks a lot

**Comment by PetrKnedlik** [comment]
@mnezmah worked for me as well, thank you! 👍

**Comment by Emmanuel12345678** [comment]
I don't have 5.1.x driver installed, please help.
