### ISSUE TITLE
Errors in PostgreSQL sequences

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1091]
After opening any sequence in PostgreSQL database, dbeaver treats it like table - displays tabs Properties, Data, Diagram.

When i click Data, it show same info like in first tab Properties. When I try to edit any data and save them I get question about non existent primary key and then error:

![sequence1](https://cloud.githubusercontent.com/assets/24586123/21418872/83818d66-c824-11e6-84b8-8b5c733b48aa.png)

When I open last tab "Diagram" I get another error:

![sequence](https://cloud.githubusercontent.com/assets/24586123/21418820/20abd110-c824-11e6-8db4-d8166dc8ae67.png)

Both errors are understable because sequence is not table.

Looking in source code PostgreSequence if based on PostgreTableBase and in PostgreSchema is loaded with other tables (in pg_catalog sequence is special type of table). I tried to modify source and base in on PostgreObject and in PostgreSchema create separate ExtensionCache. It works for me, but only viewing for now (no editing) and I don't know, whether this is the right approach...

**Comment by serge-rider** [comment]
Bug with diagram rendering and data edit was fixed. However PG doesn't allow to update sequence data directly (as table columns update). 
For now DBeaver doesn't support sequence properties edit so you need to use ALTER SEQUENCE queries in SQL editor.
