### ISSUE TITLE
Fields names not visible in Table Properties/Indexes

### ISSUE THREAD

**Issue by roberto2357** [serge-rider/dbeaver#1092]
Hi, in DBeaver 3.8.2, I expanded all sections in indexes view (see image below) but fields names are not visible.
Thanks.

![indexes](https://cloud.githubusercontent.com/assets/22471800/21431940/b63cac5a-c869-11e6-8225-55aca99e4ffb.png)

**Comment by serge-rider** [comment]
Probably this was fixed as a part of #1081.
Please try to redownload 3.8.2 version and check again.

**Comment by roberto2357** [comment]
Ok, tomorrow I download again the 3.8.2 version and I test it in windows and linux os. I will notify you about the result. Thank you.

**Comment by roberto2357** [comment]
The new download works perfectly !!
Thanks Serge and Merry Christmas to all DBeaver Staff :-)
