### ISSUE TITLE
Update from 3.8.1 to 3.8.2 doesnt work

### ISSUE THREAD

**Issue by SZubarev** [serge-rider/dbeaver#1093]
Update from 3.8.1 to 3.8.2 doesn't work, receive "Cannot complete the install because of a conflicting dependency." error

**Comment by serge-rider** [comment]
Please post error stacktrace (from Error Log view)

**Comment by SZubarev** [comment]
!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-12-23 13:36:15.565
!MESSAGE No remedy found

!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-12-23 13:36:15.600
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-12-23 13:36:15.600
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.600
!MESSAGE Software being installed: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.600
!MESSAGE Software currently installed: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.600
!MESSAGE Only one of the following can be installed at once: 
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.600
!MESSAGE DBeaver Model Plug-in 1.0.35 (org.jkiss.dbeaver.model 1.0.35)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.600
!MESSAGE DBeaver Model Plug-in 1.0.36 (org.jkiss.dbeaver.model 1.0.36)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.600
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE From: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE To: com.jkiss.dbeaver.enterprise.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.601
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE From: DBeaver 3.8.1 (com.jkiss.dbeaver.enterprise.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE To: org.jkiss.dbeaver.standalone.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.601
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE From: DBeaver Core 3.8.1 (org.jkiss.dbeaver.core.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE To: org.jkiss.dbeaver.model [1.0.35]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.601
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE From: DBeaver Core 3.8.2 (org.jkiss.dbeaver.core.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE To: org.jkiss.dbeaver.model [1.0.36]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.601
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE From: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.2]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.601
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE From: DBeaver Standalone 3.8.1 (org.jkiss.dbeaver.standalone.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.601
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.1]

!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-12-23 13:36:15.631
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-12-23 13:36:15.631
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE Software being installed: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE Software currently installed: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Only one of the following can be installed at once: 
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE DBeaver Model Plug-in 1.0.35 (org.jkiss.dbeaver.model 1.0.35)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE DBeaver Model Plug-in 1.0.36 (org.jkiss.dbeaver.model 1.0.36)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE From: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE To: com.jkiss.dbeaver.enterprise.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE From: DBeaver 3.8.1 (com.jkiss.dbeaver.enterprise.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE To: org.jkiss.dbeaver.standalone.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE From: DBeaver Core 3.8.1 (org.jkiss.dbeaver.core.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE To: org.jkiss.dbeaver.model [1.0.35]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE From: DBeaver Core 3.8.2 (org.jkiss.dbeaver.core.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE To: org.jkiss.dbeaver.model [1.0.36]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE From: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.2]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.631
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE From: DBeaver Standalone 3.8.1 (org.jkiss.dbeaver.standalone.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.631
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.1]

!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-12-23 13:36:15.762
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-12-23 13:36:15.762
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE Software being installed: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE Software currently installed: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Only one of the following can be installed at once: 
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE DBeaver Model Plug-in 1.0.35 (org.jkiss.dbeaver.model 1.0.35)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE DBeaver Model Plug-in 1.0.36 (org.jkiss.dbeaver.model 1.0.36)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE From: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE To: com.jkiss.dbeaver.enterprise.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE From: DBeaver 3.8.1 (com.jkiss.dbeaver.enterprise.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE To: org.jkiss.dbeaver.standalone.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE From: DBeaver Core 3.8.1 (org.jkiss.dbeaver.core.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE To: org.jkiss.dbeaver.model [1.0.35]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE From: DBeaver Core 3.8.2 (org.jkiss.dbeaver.core.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE To: org.jkiss.dbeaver.model [1.0.36]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE From: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.2]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.762
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE From: DBeaver Standalone 3.8.1 (org.jkiss.dbeaver.standalone.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.762
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.1]

!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-12-23 13:36:15.767
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-12-23 13:36:15.767
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE Software being installed: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE Software currently installed: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Only one of the following can be installed at once: 
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE DBeaver Model Plug-in 1.0.35 (org.jkiss.dbeaver.model 1.0.35)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE DBeaver Model Plug-in 1.0.36 (org.jkiss.dbeaver.model 1.0.36)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE From: DBeaver Enterprise 3.8.1 (com.jkiss.dbeaver.core.product 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE To: com.jkiss.dbeaver.enterprise.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE From: DBeaver 3.8.1 (com.jkiss.dbeaver.enterprise.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE To: org.jkiss.dbeaver.standalone.feature.feature.group [3.8.1]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE From: DBeaver Core 3.8.1 (org.jkiss.dbeaver.core.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE To: org.jkiss.dbeaver.model [1.0.35]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE From: DBeaver Core 3.8.2 (org.jkiss.dbeaver.core.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE To: org.jkiss.dbeaver.model [1.0.36]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE From: DBeaver Runtime 3.8.2 (org.jkiss.dbeaver.runtime.feature.feature.group 3.8.2)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.2]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-12-23 13:36:15.767
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE From: DBeaver Standalone 3.8.1 (org.jkiss.dbeaver.standalone.feature.feature.group 3.8.1)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-12-23 13:36:15.767
!MESSAGE To: org.jkiss.dbeaver.core.feature.feature.group [3.8.1]
