### ISSUE TITLE
Request: Bootstrap Queries per Connection.Type & Variables

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1094]
After reading about bootstrap queries

http://dbeaver.jkiss.org/docs/features/
> Bootstrap SQL queries which will be executed in the database session right after connect.

I'd like to have separate bootstrap queries for each connection type Metadata|Normal.

Also I'd like to have the variables available for shell commands + have the version of Dbeaver added for both.
<img width="228" alt="screen shot 2016-12-22 at 10 17 53 am" src="https://cloud.githubusercontent.com/assets/9246654/21435675/f02f9dee-c82f-11e6-9066-817324b59a14.png">

In my usecase I'll be using querybanding to identify each connection so I can kill/prioritize the appropriate connection when necessary.

**Comment by serge-rider** [comment]
Not sure about that. Connection types are shared for all drivers, so doesn't make much sense to bind any database specific stuff to them.
Also you made screenshot of events (shell commands) configurator - not bootstrap queries UI.

Maybe defining bootstrap config (and some other connections config) for a folder would make sense. Need to think about that.

**Comment by r-richmond** [comment]
I made a screen shot of shell commands configurator as those are the variables I would like to able to use with bootstrap queries.

Perhaps I did a poor job explaining what I wanted to do. 

Here is my current bootstrap query for one of my connections; to give better context to my request.

`set query_band = 'ApplicationName=Dbeaver;Version=3.8.2;ClientUser=r-richmond;Source=Both;' for session;`

So I'd like variables I could plug into this instead of having to hard code it.
Application name / ${application}: Variable that resolves to `Dbeaver` or `Dbeaver Enterprise`
Version / ${version}: Variable that resolves to x.x.x representing dbeaver's current version
ClientUser / ${user}: Variable that resolves to the username specified in the connection settings
Source / ${connection_type}: Variable that resolves to Metadata or Editor (Metadata being the JDBC-connection that pulls in metadata information | Editor being the JDBC-connection that the user runs queries through)

Also the variables listed above would be nice
${host}: the host used in the Connection Settings
${port}: the port used in the connection settings
${server}: the server used in the connection settings
${database}: the database used in the connection settings
${url}: the jdbc url that is used in the connection / displayed in the connection settings

Essentially I'm using the bootsrap query to mark every sql statement that Dbeaver runs with metadata information (The sql Command listed above only needs to be run once to accomplish this which makes bootstrap query the perfect place to put it) and I'd like to be able to have a more dynamic statement as opposed to a hardcoded statement.

**Comment by r-richmond** [comment]
One more thing to note when I say Connect.Type in the title I'm not talking about Mysql vs Postgres I'm trying to refer to the different connections Dbeaver opens when using a Connection. (Metadata & Editor: the connection the queries I write run against)

**Comment by serge-rider** [comment]
Details are clear.
But this requires too many model and UI changes, let's postpone this till 4.1.

**Comment by r-richmond** [comment]
Sounds good thanks for the update

**Comment by r-richmond** [comment]
Just wanted to respond on this thread and mention that I still think this would be a nice feature, thanks

**Comment by serge-rider** [comment]
This feature will be included in 4.2.1.
All proposed variables are supported but `Source / ${connection_type}`. If this is really important thing then I'll try to figure something out.

**Comment by r-richmond** [comment]
Thanks for implementing this feature, I'm looking forward to testing it out. the `source` variable would have been nice but i'll happily use the current implementation and let you know if anything is broken.
