### ISSUE TITLE
Error in generate UPDATE query

### ISSUE THREAD

**Issue by kelvinwnfeitosa** [serge-rider/dbeaver#1096]
when we generate an update query of the table contains as primary key a decimal(17), the primary key stays with wrong format.
As in the example below.

```
UPDATE DB2PNG.SLCT_LIB_CRD
SET CD_PRD_SLCT=1
WHERE NR_SLCT=2.0163571510208608E16;
```

the right value is 20163571510208609.

**Versions:**

DBeaver: 3.8.2, on Windows 7
DB2 z/OS driver

**Comment by serge-rider** [comment]
Thanks for report
