### ISSUE TITLE
Feature request: functions in inline editor

### ISSUE THREAD

**Issue by lorimz** [serge-rider/dbeaver#1097]
Hello,
I'd like to be able to use simple functions in inline editor, like typing MD5('mypassword') in a password field and get DBeaver to translate this to the corresponding MD5 hash - in the same way done by e.g. phpmyadmin

**Comment by serge-rider** [comment]
I don't think that implementing some custom database-specific functions on a client (DBEaver) side is a good idea.
As I understand phpmyadmin just "injects" values into INSERT/UPDATE SQL query. This let's you to use any expressions (or even subselects) as column values.
While DBeaver assumes that cell value as an instance of some data type. Thus it just binds these values to INSERT/UPDATE queries.

I'll think about possible workarounds (maybe some extra "Edit as expression" command will work)..

**Comment by Pablo1107** [comment]
It's a shame dbeaver can't infect a function output into a field value like other editors.
