### ISSUE TITLE
add checksums for downloads (installers, archives)

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1098]
While I searched for something else I just noticed that on the download page of DBeaver there are no checksums at all. SHA256 or more secure hash functions should be used for the checksum generation. No MD5.

**Comment by axq** [comment]
Unless you also move http://dbeaver.jkiss.org/ to https this doesn't help, since you can't trust the checksums any more than the installers.  One solution would be to include the checksums to README.md served over https by GitHub, or host a copy of the binaries on GitHub to begin with.

**Comment by serge-rider** [comment]
Good point.
We going to make SSL certificates and code sign certificates in version 4.0.
This should happen near to February.

**Comment by serge-rider** [comment]
Checksums are in `checksum` folder of version binaries. E.g. http://dbeaver.jkiss.org/files/4.0.0/checksum/
Will update links on the web site shortly.
