### ISSUE TITLE
Error dropping constraint

### ISSUE THREAD

**Issue by carragom** [serge-rider/dbeaver#1099]
Hi,

There seem to be an issue when dropping constraints (at least in PostgreSQL and MySQL). Steps to reproduce:

1. Create a new unique constraint on a table and name it `test-uk`. This will correctly quote the name of the constraint in the generated SQL and succeed.
2. Try to drop that same constraint. This will not quote the constraint name in the generated SQL and fail since `-` is a special character.

Is there an _always quote identifiers_ option somewhere that I missed ?

Thanks for the great software.
Cheers.

**Comment by serge-rider** [comment]
This is a bug in constraints manager.
Thanks for report.
