### ISSUE TITLE
Error creating foreign key to table with reserved name

### ISSUE THREAD

**Issue by carragom** [serge-rider/dbeaver#1102]
Hi there,

Found an issue of incorrectly generated SQL, steps to reproduce:

1. Create a table with a reserved keyword as name, e.g. user(id int primary key).
2. Create a table that references the other table, e.g. profile(id int primary key, user references user(id)).

The creation of the second table will fail because the column name is not correctly quoted, it will be something like:

    CONSTRAINT profile_user_fk FOREIGN KEY (user) REFERENCES "user"(id) ON DELETE RESTRICT ON UPDATE RESTRICT

In order for this to work, the statement should be something like:

    CONSTRAINT profile_user_fk FOREIGN KEY ("user") REFERENCES "user"(id) ON DELETE RESTRICT ON UPDATE RESTRICT

This fails on PostgreSQL and works on MySQL. Apparently MySQL does not consider `user` to be a reserved keyword.

Cheers.

**Comment by serge-rider** [comment]
Thanks for report
