### ISSUE TITLE
application stuck while fetching all rows

### ISSUE THREAD

**Issue by nimrodhoffman** [serge-rider/dbeaver#1103]
Hi, I am using version 3.8.2 version.  Win 10. SQL Server 2008 R2. jTDS driver 1.3.1
![image 039](https://cloud.githubusercontent.com/assets/24806331/21517805/c1589916-ccea-11e6-83f3-56d51f029100.png)

While trying to fetch all rows from a SQL Server table the app became unresponsive and after a couple of minutes through an error message which is unresponsive as well.
Had to use task manager to close the app.
The table I am trying to fetch its entire entries is an exact copy of an Oracle table with which fetch all data is stuck but with no error message.
Both tables contain about 320,000 rows.

![image 037](https://cloud.githubusercontent.com/assets/24806331/21518122/c81552d8-ccec-11e6-906a-af91efaa7741.png)

**Comment by serge-rider** [comment]
Well, most likely OutOfMemory error happened (one of the very nasty errors which leads to unexpected UI behavior). It is very likely when you fetch all rows from a big table.
Although 320k rows isn't too big number.
1. Please send debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) - here or on serge@jkiss.org
2. You can increase amount of memory available to DBeaver. Add extra command line parameters to dbeaver.exe: `-vmargs -Xmx1024m` - this will give you maximum 1Gb. Should be enough even for 1 million of records (it depends on record size though).

**Comment by nimrodhoffman** [comment]
Hi,
1. Applogies for my ignorance but I have no idea how to generate a debug log.
2. Works like a charm!
Thanks

**Comment by serge-rider** [comment]
1. Page https://github.com/serge-rider/dbeaver/wiki/Log-files contains description how to get debug log.
2. Good. Closing.
