### ISSUE TITLE
Table column sorting in table properties

### ISSUE THREAD

**Issue by MauroMichelotti** [serge-rider/dbeaver#1106]
I noticed that in the last version of the program, in the properties screen of a table, the columns are sorted alphabetically instead of by table position.
Is there a way to have the columns sorted by position by default?
Thanks

![image](https://cloud.githubusercontent.com/assets/23048228/21540921/102cccd8-cdb3-11e6-8fc4-28fb46577bd1.png)

**Comment by serge-rider** [comment]
Most likely you have turned on option "Order elements alphabetically" on preference page Database->Navigator.
Just turn it off.
