### ISSUE TITLE
Quit application with ^q

### ISSUE THREAD

**Issue by rs-aesi** [serge-rider/dbeaver#1107]
Please add ctrl-q as a keyboard short-cut to exit the application. It's much more convenient than using the pointy thing to open the File menu and select the Exit item.

**Comment by serge-rider** [comment]
You can assign exit shortcut in Preferences->Keys.

**Comment by rs-aesi** [comment]
On Thu, 29 Dec 2016, Serge Rider wrote:

> You can assign exit shortcut in Preferences->Keys.

   Great! I'll do that.

Much appreciated,

Rich

**Comment by golopot** [comment]
Can we me this key binding the default? Quitting by `ctrl + q` It is pretty standard.
