### ISSUE TITLE
Flat File Connection Pulling Incomplete List of Tables (CSV Import)

### ISSUE THREAD

**Issue by ezulauf** [serge-rider/dbeaver#1108]
Hey there,

I'm having an issue where I've successfully connected a Flat File (CSV) database to DBeaver but am only able to see one of the tables contained in the folder that it's aimed at. I'm trying to import the CSV file using the Flat File connection so that I can export it to a MS SQL or MySQL server.

Below is a screenshot with an image of the path, Flat File expanded database, and the folder that should be targeted by DBeaver. 

I've tried deleting and re-creating the connection, creating a connection with a different folder (I could see no tables when I tried that), making changes to the table I can see, and re-starting DBeaver, none of which worked. I've imported all the CSVs into a project to see if that made them visible as well, with no luck.

Is there a step I'm missing in order for the Flat File Database to see all of the tables in the folder?

Please let me know, looking forward to resolving this issue.

Thanks,
Ellen
![screen shot 2016-12-29 at 1 25 23 pm](https://cloud.githubusercontent.com/assets/24831958/21554203/b2b57ccc-cdca-11e6-8238-d3c6ffab0866.png)

**Comment by serge-rider** [comment]
Sorry, missed this question.

Generally you just need to specify correct folder path (where CSVs reside). You don't need to copy CSVs into project or anywhere else. Folder path must be a valid OS path (e.g. it may not work in case of some fancy network names).

If this doesn't work please check error log and/or debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any related errors/warnings.
