### ISSUE TITLE
[MS SQLServer] Messy characters of timestamp type in query result

### ISSUE THREAD

**Issue by yao-bin** [serge-rider/dbeaver#1110]
0x0000000000abcxyz value of timestamp type in MS-SQL, but messy characters in DBeaver.

DBeaver 3.8.2
MS-SQL 2014
macOS Sierra 10.12.2

**Comment by serge-rider** [comment]
Please post table DDL.

**Comment by yao-bin** [comment]
@serge-rider 

Hi, could you help to check the below? Thanks!

CREATE TABLE [dbo].[axEmployee](
	[axEmployeeID] [bigint] NOT NULL,
	[GlobalID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[RowTS] [timestamp] NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[MiddleInitial] [nvarchar](1) NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[EmailAddress] [nvarchar](100) NULL,	
 CONSTRAINT [PK_axEmployee] PRIMARY KEY CLUSTERED 
(
	[axEmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_axEmployee_GlobalID] UNIQUE NONCLUSTERED 
(
	[GlobalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

**Comment by serge-rider** [comment]
You can configure binary data type representation.
Preferences->Database->Result Sets->Binaries->Binary data formatter. Set it to 'Hex'.

**Comment by yao-bin** [comment]
it runs ok, thanks a lot!
