### ISSUE TITLE
[PostgreSQL] Table Loading Hangs

### ISSUE THREAD

**Issue by psyonara** [serge-rider/dbeaver#1111]
Since version 3.8.2 (and maybe earlier, but later than 3.7.8), when you've connected to a postgresql database, and then open a table, the operation to load everything seems to just hang. When you click on the Data tab of the table, the operation to load the data also just hangs. Downgrading back to version 3.7.8 solves the problem.

Screenshot on 3.8.2:
![dbeaver_table_3 8 2](https://cloud.githubusercontent.com/assets/771840/21605162/e76fb1c4-d1af-11e6-97b7-e00f6b4803da.png)

Screenshot on 3.7.8:
![dbeaver_table_3 7 8](https://cloud.githubusercontent.com/assets/771840/21605166/ef6d5b56-d1af-11e6-8bd1-d89455084f1c.png)

As you can see above (apart from the layout changes), in 3.8.2 it seems to be waiting for an operation to finish, yet it never does. And the column information never populates, yet in 3.7.8 it shows immediately.

**Comment by psyonara** [comment]
I'm using the Linux (Ubuntu) version of DBeaver.

**Comment by serge-rider** [comment]
Can't reproduce.
When this operation will hang please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and send it here.

**Comment by psyonara** [comment]
I had to install the JDK to get jstack, and after that everything is suddenly working. Could the installation of the JDK have made a difference?

**Comment by psyonara** [comment]
Never mind, it's stopped working again. Seems this might be intermittent. Let me try to get that thread dump again.

**Comment by psyonara** [comment]
Here we go.
[thread_dump.txt](https://github.com/serge-rider/dbeaver/files/692778/thread_dump.txt)

**Comment by serge-rider** [comment]
Doesn't look like DBeaver issue.
Check #1041 (try to execute `export SWT_GTK3=0`)

**Comment by psyonara** [comment]
Ok cool, thanks for your time on this! I'll close this one for now.

**Comment by psyonara** [comment]
FWIW, I figured this out. The problem occurs when I start DBeaver's from Unity's quick launch bar. If I start it from the menu, the problem does not come up at all.

I don't have any idea of where to start looking to solve this, so I'll just not lock the program to the quick launch bar. :-P
