### ISSUE TITLE
Feature request: connection combobox - group connections or show only active (connected)

### ISSUE THREAD

**Issue by shivan** [serge-rider/dbeaver#1113]
currently:
the combobox of the connections in the toolbar doesn't show the items grouped like the treeview

wish:
a) either option to show only the active connections or (btw. synchronization of connections with green check is not always working, sometimes these are connected, but the check symbol in the icon is missing)
b) group them, too

**Comment by serge-rider** [comment]
I can add filters to this combo (toggle all/connected datasources).
Showing whole tree with folders looks too heavy.

**Comment by shivan** [comment]
Hi,
that sounds good :)
