### ISSUE TITLE
Connection via SSH tunnel with SSH key asks for password

### ISSUE THREAD

**Issue by Gixx** [serge-rider/dbeaver#1115]
Why does it asks for password (which I don't know/have) when I set it to use the SSH key (which I have)?

**Comment by serge-rider** [comment]
This is a bug in the recent version. Will be fixed in the next version, thanks for report.

Workaround: change auth method to password and enable "save password" checkbox (with empty password). Then switch back to public key authentication and save settings.

**Comment by Gixx** [comment]
Thanks, works ;)

**Comment by metaturso** [comment]
This is happening again on DBeaver v4.2.6 on Ubuntu 16.04: Configuring SSH key access will still prompt for the password.

Saving the empty password seems to work, but it's counter intuitive.

**Comment by sergeialimov** [comment]
The workaround doesn't work for me on DBeaver 4.3.0 on mac os 10.12.4

**Comment by aissarmurad** [comment]
Same problem happening on DBeaver v4.2.5 compiled in 2017-11-13 on Arch Linux.
Driver: postgresql-42.2.0.jre7.jar

**Comment by serge-rider** [comment]
@metaturso @aissarmurad Yes.
I'll add key encryption. And will ask for password only for encrypted keys.
