### ISSUE TITLE
Function "Select row count for query" throws numberFormatException

### ISSUE THREAD

**Issue by kefeli** [serge-rider/dbeaver#1116]
If filtering column is type of varchar2 and it is defined as long at where defination of query, count function throws like this:
`Can't transform query to SELECT count(*) java.lang.NumberFormatException: Passed value does not contain a parsable long value
`
Here example,
Table DLL:
`CREATE TABLE "STUDENT" 
   (	"STUDENT_NO" VARCHAR2(100), 
	"STUDENT_ID" NUMBER(*,0)
   );`
Sample query:
`select * from student where  student_no = 20161114000000035001;`
According to invalid usage of student_no column, above script can be executable on script tab. I know correct usage should be like this
`SELECT * FROM STUDENT WHERE STUDENT_NO = '20161114000000035001';`
However, it is working on short number(Integer) values, long values should be supported too.
If you are define student_no correctly, this function does not try to convert long value to String. So, there is no problem. It should be handle number format exception according to size of input. 
Thanks

**Comment by serge-rider** [comment]
Looks like JSQLParser library limitation. 
Will try to find some workaround..

**Comment by serge-rider** [comment]
Hopefully this issue will be fixed in JSQLParser. Moving to 4.x.

**Comment by kefeli** [comment]
Good news 👍

**Comment by serge-rider** [comment]
Waiting for JSQLParser 0.9.7 version..

**Comment by serge-rider** [comment]
Works with JSQLParser 0.9.7.
