### ISSUE TITLE
Desktop freezes on Linux randomly while using dbeaver

### ISSUE THREAD

**Issue by krilim** [serge-rider/dbeaver#1117]
I use fedora 25 (**fc25**) and I have been using _dbeaver_ without problems in **debian** and **fc24**, but now desktop freezes completely randomly while using _dbeaver_... I must switch to console mode and back to plasma to be able to continue using the computer.
I think is a java related issue, maybe: https://bbs.archlinux.org/viewtopic.php?id=71634, but I tried that and nothing... Without _dbeaver_ desktop runs ok.

**Comment by GiantCrocodile** [comment]
I had random freezes of my desktop under Linux Mint 17 Cinnamon too! I didn't know what caused them but it sounds like your issue: java or DBeaver related. Thanks for your report here.

**Comment by serge-rider** [comment]
Whenever DBeaver freezes please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and send it here

**Comment by krilim** [comment]
Will do next time thanks.

**Comment by krilim** [comment]
Here is the file with the thread dump. The desktop freezed just after opening dbeaver... I switched to console mode and runned the command (attached).
[threaddump.txt](https://github.com/serge-rider/dbeaver/files/693019/threaddump.txt)

**Comment by serge-rider** [comment]
Probably it is GTK issue.
Check #1111.

**Comment by krilim** [comment]
I use KDE but it is true that when I use arg -_Dsun.java2d.opengl=true_ it shows the same behavior.

**Comment by krilim** [comment]
I tried using _--launcher.GTK_version 3_ and still freezes ... 
Dialog **Help > Intallation information** does not even work

Will keep trying :-D

**Comment by serge-rider** [comment]
No, you need to disable GTK 3. 
Try to execute 'export SWT_GTK3=0' before running DBeaver.

**Comment by williamlopes-dev** [comment]
How can I disable forever without affect any other app?

**Comment by GiantCrocodile** [comment]
You can create a shell script and put this in:
```
export SWT_GTK3=0 <path to DBeaver executable>
```

**Comment by serge-rider** [comment]
BTW this issue will be automatically fixed after we'll migrate to Eclipse 4.6 platform (this will happen in DBeaver 4.0, i.e. pretty soon).

**Comment by williamlopes-dev** [comment]
Thank you @GiantCrocodile !
Waiting for 4.0 version :)

**Comment by krilim** [comment]
Hello.

I have been doing other tests and when I disable _hardware acceleration_ in **chrome** it seems to run ok... Maybe it is not **dbeaver** but **chrome** :(

Thanks anyway.

**Comment by GiantCrocodile** [comment]
@krilim not sure on this. I'm using Firefox (no Chrome installed) and had those freezes too.

**Comment by serge-rider** [comment]
Closing
