### ISSUE TITLE
SQL Error [1109] [42S02]: Unknown table 'c' in field list

### ISSUE THREAD

**Issue by syedhassanshah** [serge-rider/dbeaver#1118]
Following error is thrown when there is empty line anywhere before the WHERE clause.

**Example:**
Try to **Execute SQL Script** (i.e. **Alt+X**) using following **SQL in SQL Editor>New SQL Editor**:

```
select 
	mt.id

from mytable mt
where mt.id in (1,2);
```
The work around is **Ctrl+\\** or **Select all & Ctrl+ENTER** .

> Error occurred during SQL script execution
> 
> Reason:
> SQL Error [1109] [42S02]: Unknown table 'mt' in field list

**Comment by serge-rider** [comment]
By default blank line is statement delimiter.
You can disable this in preferences (General->Editors->SQL Editor->SQL Processing->Blank line is statement delimiter).
Another option: select you query and execute with CTRL+Enter.
