### ISSUE TITLE
Firebird Delete Column not working

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#112]
The interface generating the SQL for column DROP:
```ALTER TABLE <table> DROP COLUMN <column>;```

The right syntax in Firebird is:
```ALTER TABLE <table> DROP <column>;```

**Comment by serge-rider** [comment]
There is a standard workaround for this issue:
![firebird-settings](https://cloud.githubusercontent.com/assets/6398845/11821277/bff530e8-a379-11e5-9067-63fd98c000d5.png)
I'll make this config default for Firebird driver.
