### ISSUE TITLE
Spoof the Remote Program string in an Oracle database connection

### ISSUE THREAD

**Issue by Tamh** [serge-rider/dbeaver#1120]
Hello everyone.
I've been using DBeaver CE merrily for some time now, and I think it is a very apt program for my needs.
However, I've found myself in a weird situation.

One of my Oracle production databases has a restriction in which (for security reasons) it only allows to receive connections from a particular software string. If it doesn't match, connection is refused.
Looking up the Session List on the development database and checking out the Process information, Remote Host, User and Program are displayed.

For DBeaver, it shows as it is "DBeaver 3.8.2"; SQL Developer shows as "SQL Developer", meanwhile for our software the proper software string is displayed.
I was wondering if there is anyway to spoof that string, so that I'm able to mask my connection as if it was from our software?

Thanks again for your work with this software.

**Comment by serge-rider** [comment]
This is reasonable. And I think this won't take much time to implement.

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/21826162/86143bd2-d797-11e6-88c5-75b085dd3f1a.png)

**Comment by Tamh** [comment]
Great. Can't wait to get this and finally ditch SQL Developer.
