### ISSUE TITLE
MariaDB connector J 1.5.6

### ISSUE THREAD

**Issue by deamn** [serge-rider/dbeaver#1121]
With driver 1.5.6 of MariaDB connector, the schemas are not listed in the view Database Navigator, when I click on the "Databases" node, but it works with driver 1.5.5.

**Comment by serge-rider** [comment]
This is MariaDB driver issue, I can't fix it. I'll mark version 1.5.6 as "bad". Thanks for report!

**Comment by victor0801x** [comment]
1.5.7 has been release, it works well now @serge-rider @deamn
