### ISSUE TITLE
Oracle package persist action shows confirmation popup when ignores confirmation setting "persist object changes" is set to never

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1122]
Oracle package persist action shows confirmation popup when ignores confirmation setting "persist object changes" is set to never.

![image](https://cloud.githubusercontent.com/assets/121157/21680826/639c9742-d34c-11e6-93c2-e15a7bb948c3.png)

![image](https://cloud.githubusercontent.com/assets/121157/21680871/a26445b0-d34c-11e6-953d-d76c49d15e99.png)

**Comment by serge-rider** [comment]
Can't reproduce (with any object type, not just Oracle packages).
Persist changes dialog becomes visible only after explicit save or after confirmation dialog on editor close. Do you see confirmation dialog?

**Comment by yevon** [comment]
If i press ctrl+S thos dialog always shows up asking for confirmation to persist changes. It should persist changes without needing to press any button.

**Comment by serge-rider** [comment]
Confirmation settings affects only on confirmation dialog (which appears on editor close).
Persist changes dialog cannot be suppressed. At least for now.

**Comment by yevon** [comment]
mmm this dialog isn't really useful to developer as he already knows what is going to be persisted. It's a bit annoying this additional dialog when you need to persist changes often. Not critical at all but slows down user experience. At first I thought it was a confirmation dialog.

**Comment by serge-rider** [comment]
I can make a special option which will disable SQL preview dialog.

**Comment by yevon** [comment]
mmm yes, in that case it is useful to deploy changes in other instances and obtain "alter commands for tables"(as you cannot overwrite them because they contain data). But the case for packages, triggers, types etc you usually overwrite them all and create DDL after development ends. Thanks for this!
