### ISSUE TITLE
Data formats ignored for Oracle result sets and template date substitutions

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1123]
Data formats ignored for Oracle result sets and template date substitutions

![image](https://cloud.githubusercontent.com/assets/121157/21681294/ef8ed420-d34e-11e6-9b27-75e5c32a15c1.png)

![image](https://cloud.githubusercontent.com/assets/121157/21681311/08749bdc-d34f-11e6-80b6-46ff85fbb751.png)

![image](https://cloud.githubusercontent.com/assets/121157/21681420/6debb220-d34f-11e6-8953-c9f66926a47d.png)

![image](https://cloud.githubusercontent.com/assets/121157/21681446/81558192-d34f-11e6-824d-59e522504688.png)

**Comment by serge-rider** [comment]
SYSDATE returns timestamp (not just date) so you need to change Timestamp pattern.
