### ISSUE TITLE
SQL Templates don't add tabs for second and following lines, also during copy paste of sql code

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1124]
This issue happens in templates and while copying and pasting sql code:

**Example:**
Template definition:
`IF(${conditionClause}) THEN
	${ifClause};
ELSE
	${elseClause};
END IF;`
![image](https://cloud.githubusercontent.com/assets/121157/21682616/e578f950-d355-11e6-91d2-30c98efcf3dd.png)

**Result:**
![image](https://cloud.githubusercontent.com/assets/121157/21682574/aa821764-d355-11e6-9a38-6ba6e62ae3b2.png)

**Expected result:**
![image](https://cloud.githubusercontent.com/assets/121157/21682592/c28a6ef6-d355-11e6-82ce-9cb04066779b.png)

**Comment by serge-rider** [comment]
Thanks for report.
