### ISSUE TITLE
Oracle package editing adds tab automatically when moving a line to next line that starts with a keyword

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1126]
Oracle package editing adds a tab space automatically when moving a line to next line that starts with a keyword. (Pressing enter at very first character of line)

**Comment by serge-rider** [comment]
Don't understand the problem, please clarify (some example?).

**Comment by yevon** [comment]
Example

BEGIN
    IF(condition) THEN
   
         NULL;
   END IF;

END;

If you press enter before "END IF", result is:

BEGIN
    IF(condition) THEN
   
         NULL;
   
         END IF;

END;

Expected result:

BEGIN
    IF(condition) THEN
   
         NULL;
   
    END IF;

END;
