### ISSUE TITLE
Refreshing in record mode resets the current record

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#1128]
Hi,

At the moment, when viewing a single record in a ResultSet that contains multiple rows, refreshing will reset the current record to the first one of the ResultSet. Expected behavior would be to stay on the same record.

This is a follow-up to issue #827.

**Comment by serge-rider** [comment]
This is not so easy to reproduce. Happened just a few times in my environment.
Seems to a result of asynchronous UI update during refresh. Fixed that.

**Comment by Azenet** [comment]
@serge-rider Thanks! I just noticed that it doesn't reproduce 100% on the refresh button, but it does 100% when I press F5 (or at least I think so).

**Comment by serge-rider** [comment]
Yes, you are right. F5 worked a bit differently.
This will be fixed too.
