### ISSUE TITLE
Problem with text field in PostgreSQL

### ISSUE THREAD

**Issue by carragom** [serge-rider/dbeaver#1132]
Hi there,

This is a usability improvement. On PotsgreSQL, the `text` field type does not support a length parameter. Currently when adding a `text` field you have to delete the default value of 100 from the length column otherwise you end up with a query like:

```sql
ALTER TABLE test ADD info text(100) NULL;
```

And the following error:

    SQL Error [42601]: ERROR: type modifier is not allowed for type "text"

I was wondering if it was possible to ignore the length of `text` fields on PostgreSQL even if the value is present, just like `UUID`'s field length is ignored.

Cheers.

**Comment by wklxd** [comment]
it's PostgreSQL Server's feather, Not dbeaver

**Comment by serge-rider** [comment]
See fix in the next version.
