### ISSUE TITLE
Issue with Execute Script function - Version 3.8.2

### ISSUE THREAD

**Issue by SirBenJammin** [serge-rider/dbeaver#1133]
Hey Serge,

I have noticed an issue with the Execute Script (Alt-X) function since updating to version 3.8.2 where it will fail to execute any SQL script which contains spaces between the texts. I'm only able to test this on a Teradata database but its possible its happening on others.

Can you confirm?

Thanks,

**Comment by carlosspohr** [comment]
Hi there, 

I commonly use script execution on postgres and mysql and didn't get any errors, can you post some statements that you're getting error ?

**Comment by SirBenJammin** [comment]
Hey,

The script can be as simple as this:

**Working**
`SELECT * FROM DBC.TABLES;`

**Error**
`SELECT *

FROM DBC.TABLES;`

Teradata will report an Error 3706 - Syntax error: expected something between the 'SELECT' keyword and ';'.

If you look at the Execution Log you will notice that the text only contain the text before the space.

![image](https://cloud.githubusercontent.com/assets/17081097/21767703/d8a3ee6a-d675-11e6-8ae5-82de90e85191.png)

Hope this explains the issue.

Thanks,

**Comment by serge-rider** [comment]
Yes, in 3.8.2 SQL queries extraction was changed (to support blocks processing).
Blank line should be query delimiter only for individual queries. When you execute a script only real delimiter (`;`) should be used.
Thanks for report.

Workaround: disable "Blank line is statement delimiter" option in SQL editor preferences.

**Comment by SirBenJammin** [comment]
Thanks Serge.

Confirmed workaround has solved my issue.

Thanks,
