### ISSUE TITLE
Database List throws NullPointerException at MariaDB connection

### ISSUE THREAD

**Issue by kefeli** [serge-rider/dbeaver#1135]
After establish connection, there is no database listed from database tab. When right click database, choose refresh then application throws java.lang.NullPointerException at Error refreshing node.
<img width="1026" alt="screen shot 2017-01-10 at 14 55 30" src="https://cloud.githubusercontent.com/assets/8394894/21805372/88d582a0-d73c-11e6-8ecb-23ccba8441d0.png">
Error log attached
[error_log.txt](https://github.com/serge-rider/dbeaver/files/696047/error_log.txt)

**Comment by serge-rider** [comment]
Seems to be a duplicate of #1121.
Upgrade to 3.8.3 and use 1.5.5 MariaDB driver version. Or you can use MySQL driver.

**Comment by kefeli** [comment]
Yes, 1.5.6 MariaDB driver has  a problem. I downgrade version of mariadb client to 1.5.5. It is worked now.

**Comment by victor0801x** [comment]
1.5.7 has been release, it works well now @kefeli
