### ISSUE TITLE
There is no mark for all occurrences of a word.

### ISSUE THREAD

**Issue by JanKo44** [serge-rider/dbeaver#1136]
There is no mark for all occurrences of a word, like in Eclipse and a selection of a color for it. (In Eclipse: Preferences - General - Editors - Text Editors - Annotations – Occurrences)
For large queries it would be greatly useful.

**Comment by serge-rider** [comment]
Duplicate of #222 
In fact Eclipse occurrences config is specific for JDT/CDT - but not for any text editor. That's why it is not so easy to do.
