### ISSUE TITLE
Wrong value in StartupWMClass in dbeaver.desktop

### ISSUE THREAD

**Issue by reini-1** [serge-rider/dbeaver#1137]
Hi!

The value according to xprop should be SWT not DBeaver, otherwise you get a second icon in launcher:

```shell
$ xprop WM_CLASS
WM_CLASS(STRING) = "SWT", "SWT"
```

```diff
--- a/dbeaver.desktop	2017-01-10 16:49:59.945945291 +0100
+++ b/dbeaver.desktop	2017-01-10 16:45:48.159438482 +0100
@@ -9,5 +9,5 @@
 Exec=/usr/share/dbeaver/dbeaver
 Icon=/usr/share/dbeaver/dbeaver.png
 Categories=IDE;Development
-StartupWMClass=DBeaver
+StartupWMClass=SWT
 StartupNotify=true
```

Reini

**Comment by serge-rider** [comment]
The same as #609
This makes me a bit frustrating. I can return `StartupWMClass=SWT` option but it looks like in some conditions it is also not appropriate.
Any ideas?

**Comment by reini-1** [comment]
Sorry but I have no idea how to fix this.

**Comment by serge-rider** [comment]
Ok, will investigate it a bit more.
Closing this issue as duplicate.
