### ISSUE TITLE
0001-01-01 Dates appears as [NULL] in result grid

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1139]
DBeaver shows 0001-01-01 as [NULL] instead of showing 0001-01-01 (the actual value in the DB2 database).

Using JTOPEN driver for IBM DB2 database.

Checked if there was a property called "zeroDateTimeBehavior" but do not see it. I tried setting custom property for "zeroDateTimeBehavior" to "Round" but no change.

Not sure how to get DBeaver to show 0001-01-01 instead of showing NULL as all our columns are not nullable in this table, but yet it is showing [NULL]

**Comment by xantari** [comment]
Nevermind. Close this. I just found that with DB2 if you set the following JDBC properties then the NULL issue goes away: date format=iso;time format=iso;

**Comment by serge-rider** [comment]
Ok, good to know that.
