### ISSUE TITLE
Connection - Shell Commands - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#114]
1. Open the 'Edit Connection' dialog
2. Select 'Shell Commands'
3. Tick an event
4. Select the event ticked in 3.
5. Click 'Test Connection'

Result: `ArrayIndexOutOfBoundsException` with no stack trace
Full message is `java.lang.ArrayIndexOutOfBoundsException: ArrayIndexOutOfBoundsException: 0`

As an additional issue, this error does not appear in the DBeaver error log.

**Comment by serge-rider** [comment]
Empty command check added
