### ISSUE TITLE
Generate UPDATE statement

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1140]
There is one feature I use in SQLWorkbench (another open source java based SQL Editor) that I use on occasion.

It is Generate UPDATE statement.

It works just like generate INSERT statement, with the exception that if the primary key of the table cannot be detected (we have a REALLY OLD database without primary keys on a lot of tables), then it pops up a dialog box to put a checkbox next to the columns you wish to consider the primary key, and then it leaves the generated statement in the clipboard and puts it into the active editor with the WHERE clause based on the primary key you selected, or what was auto-detected as the primary key in the table.

This is great for bring some production data to a test environment to try setup "test" scenarios.

It would be great if this feature were in DBeaver, especially now that I have switched to it ;-)

**Comment by serge-rider** [comment]
You can do this in DBeaver.
1. Define virtual unique key for a table (bottom toolbar->Define virtual key)
2. Change your table contents
3. Click on "Script" button - it will generate INSERT/DELETE/UPDATE queries which you can copy/paste.

Isn't this what you need?

**Comment by xantari** [comment]
Thanks for showing me the virtual key.

What I am trying to do is the following:

1. Highlight a specific row in the grid.
2. Right click and go to Generate SQL
3. I only see this:

![image](https://cloud.githubusercontent.com/assets/6610039/21828053/ff9e90e0-d753-11e6-880f-c6e3cfe087fe.png)

**Comment by serge-rider** [comment]
These actions generate SQL for inserting/deleting of existing data.
Do you need a query which uses unique key and updates ALL table columns (besides key)?

**Comment by xantari** [comment]
Yes I need a query which uses a unique key that updates all the table columns (besides the key).

I basically highlight a row, or series of rows in SQL Workbench and it generates the UPDATE statements for me.

It helps to synchronize some data between TEST/DEV/PROD databases.

**Comment by serge-rider** [comment]
I see. This makes sense.

**Comment by xantari** [comment]
Thanks so much!!!! You are awesome!
