### ISSUE TITLE
Problem with checkboxes in table's columns view

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1142]
1. create or edit a table
2. click on a checkbox (for example 'NOT NULL' option)

You have to click twice. First click just selects the row and the second click applies the check/uncheck. This happens on Windows and Linux. On Linux it is a bit more annoying: you have to click twice and select yes or no from a dropdown then ...

**Comment by serge-rider** [comment]
This was made on purpose. 
Otherwise there is a big chance of misclicking.

**Comment by GiantCrocodile** [comment]
What do you mean with misclicking? I never clicked the checkboxes there by accident nor it would be really dramatic as far as I know. Other checkboxes don't behave like this too as far as I know. More often I click on a checkbox to make it NOT NULL as I can't set it directly on creating the column in the editor. Could it become an optional setting?

**Comment by serge-rider** [comment]
Misclicking may happen in existing tables. There may be multiple checkbox columns so there are a lot of checkboxes in column list. It is very easy to click accidentally.

What you saying makes sense only for new object creation. Columns creation will be improved in near future (in MYSQL and PsotgreSQL it is already done with special dialog).
