### ISSUE TITLE
run mogondb shell can't show result

### ISSUE THREAD

**Issue by someorz** [serge-rider/dbeaver#1147]
run command
db.collection.find();
result 
![image](https://cloud.githubusercontent.com/assets/5456361/21926537/222e077e-d9bd-11e6-824f-8e71a26fbf48.png)

**Comment by serge-rider** [comment]
Try this:
`db.collection.find().toArray()` or `db.collection.find().next()`
Otherwise DBeaver will show cursor object (on your screenshot)
