### ISSUE TITLE
Include option to change file encoding in CSV driver

### ISSUE THREAD

**Issue by oulenz** [serge-rider/dbeaver#1148]
I have some CSV files that I didn't manage to import at first. It turned out they were encoded in UTF-16. Manually re-encoding the files wasn't trivial because they were many and some were huge. I managed to load them by adding `?charset=UTF-16` at the end of the path in the CSV driver properties. Could you include character encoding as a proper option, or is this up to the driver creator? (Given the quick-fix described above this is by no means an urgent issue.)

**Comment by serge-rider** [comment]
You can set `charset` property on driver properties tab/page.  Right click on "User Properties"->Add new property.

**Comment by oulenz** [comment]
Ah, thank you! (It was not at all clear from the interface that it is possible to add properties in that tab.)

**Comment by serge-rider** [comment]
Yeah, that's because csvjdbc driver doesn't list supported properties.

**Comment by BrenBarn** [comment]
There really needs to be a UI for this, not just an invisible button to add a setting whose value you have to think up yourself.  Encoding is a fundamental feature of a CSV file.  There should be a dropdown with a list of encodings so you can't make a typo or the like.

**Comment by serge-rider** [comment]
Agreed. That's why we going to make completely different CSV data importer (#130).
