### ISSUE TITLE
Disable or Reorder maven-central and exasol-maven-repo

### ISSUE THREAD

**Issue by davidlday** [serge-rider/dbeaver#1149]
We have an internal repository mirror in our company that provides much faster downloads that going to either of the default included repositories (important when it comes to Hive at least). Is there a way to either remove the two included maven repositories or force DBeaver to check them last and my customer maven repo URLs first?

**Comment by serge-rider** [comment]
Currently it is not supported.
But this could be a good feature.

**Comment by serge-rider** [comment]
Check it in 3.8.4
![default](https://cloud.githubusercontent.com/assets/6398845/21957761/56f7509e-daaf-11e6-8f3e-7a1d64c5fc14.png)

**Comment by davidlday** [comment]
Awesome! Thanks so much!

**Comment by hcoona** [comment]
I tried and found it only take effect after you reboot the whole dbeaver.
