### ISSUE TITLE
DBeaver starts up with really small fonts and small icons on Windows Surface Books (and probably Surface Pros)

### ISSUE THREAD

**Issue by CMCDragonkai** [serge-rider/dbeaver#1151]
The resolution of some new laptops are ridiculously high. I've looked through the preferences, is there an easy one step to changing the sizes of the fonts and icons and tabs to be a big bigger?

**Comment by serge-rider** [comment]
There is no HiDPI support in current version (see #8).
But it is announced in DBeaver 4.0 (has to be released in February).

**Comment by CMCDragonkai** [comment]
Microsoft Surface Books: https://en.wikipedia.org/wiki/Surface_Book

Current resolution is 3000x2000.

Great, hope to see it soon!
