### ISSUE TITLE
Not Showing Security Label Column

### ISSUE THREAD

**Issue by ziasha** [serge-rider/dbeaver#1158]
Hi ,

Using 3.8.3 with DB2 10.5 LUW but it is not showing security label column. It used to show before. 
Second, it looks it gets unresponsive while scrolling through SQL query result.

Regards,
Zia

**Comment by serge-rider** [comment]
Please provide more information (what is security label column?).
What do you mean under "unresponsive", UI freeze?
What is your OS?

**Comment by ziasha** [comment]
Hi Serge-rider,

You can find more detail about Security Label column at...
 http://www.drdobbs.com/understanding-label-based-access-control/199201852
It is row level access control feature.

It doesnt freeze completely, but when I  scroll to right with key in query result pane it becomes unresponsive for few seconds. One more thing I cannot click or access via key the last column of any table in the result pane. 

Hope it will help to understand the issue.

Thanks for your time.

Regards,
ZIa

**Comment by serge-rider** [comment]
I don't think that DBeaver ever had Security Label support. I'm pretty sure it hadn't.
But this could be a good feature request..

Short UI freeze may happen if you have some complex column (e.g. BLOB) and you have value view panel opened. When you navigate with cursor over this column DBeaver will try to render value in the panel - sometimes it takes much time.

If this is not your case - try to notice when exactly this freeze happens.
