### ISSUE TITLE
Navigate objects from SQL text - doesn't work with fully qualified names in packages.

### ISSUE THREAD

**Issue by boriborm** [serge-rider/dbeaver#1160]
In SQL editor I can open object by click ctrl+mouse on name in sql text.
But when I open package body i can't do that :(

**Comment by boriborm** [comment]
It'is my mistake.
mouse hover not working if after object name is "."
for example 
hover on object TBL work
```SELECT * FROM TBL```

hover on object PKG_NAME not work
```SELECT PKG_NAME.FUNC() FROM DUAL```

To be wonderful if hover will open package and stay to his child function/procedure.

**Comment by serge-rider** [comment]
Source code navigation will be improved in next version.
Ctrl+click on procedure name opens package body editor + scroll to procedure.
[SCHEMA.]PACKAGE.PROCEDURE names are resolved by completion processor and hyperlinks navigator.

Although all this needs more testing.
