### ISSUE TITLE
Problem with local date (oracle)

### ISSUE THREAD

**Issue by loboaureo** [serge-rider/dbeaver#1162]
Hi, i've got a problem with the date type results.
If i run SELECT TO_CHAR(SYSDATE, 'DAY') FROM dual; i expect the result in spanish, but it returns the day in english.

What i get
![screenshot_7](https://cloud.githubusercontent.com/assets/681482/22104901/bc8413f8-de41-11e6-9775-f4fa34a000e7.png)
What i expect
![screenshot_6](https://cloud.githubusercontent.com/assets/681482/22104902/bcad0fba-de41-11e6-8b8c-b69dff3405f9.png)

I put an screenshot of the locale config (both of dbeaver and sqldeveloper)
![screenshot_9](https://cloud.githubusercontent.com/assets/681482/22104969/0603c6ea-de42-11e6-86e0-877e15b545b3.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/681482/22104968/05fd94aa-de42-11e6-801a-755a42a3a85c.png)

(by the way, when i modify the pattern section the sample doesn't refresh)

What i'm doing wrong?

**Comment by serge-rider** [comment]
You need to change Oracle NLS settings:
![image](https://cloud.githubusercontent.com/assets/6398845/22105917/70e236b2-de57-11e6-8cce-c8b668f9d49c.png)

![image](https://cloud.githubusercontent.com/assets/6398845/22105934/83bf32d0-de57-11e6-8599-d0520967614d.png)

**Comment by loboaureo** [comment]
Thanks!!

Works like a charm.
