### ISSUE TITLE
Export table to JSON doesn't escape "newline"

### ISSUE THREAD

**Issue by derenio** [serge-rider/dbeaver#1163]
version affected:
 - dbeaver 3.8.3

Problem:
 - The `JSON` export produces invalid files containing unescaped newline characters (instead of the `\n` sequence).

A valid `JSON` string cannot contain `"`, `\` and any of the`control-characters`. They need to be escaped, that is replaces with the following sequences:
- `\"`
- `\\`
- `\/`
- `\b`
- `\f`
- `\n`
- `\r`
- `\t`
- `\u` _four-hex-digits_

http://json.org

**Comment by serge-rider** [comment]
Thanks for report

**Comment by fjanon** [comment]
Is this fix still in 21.0.5?

I am using version 21.0.5 and it seems that this fix isn't in it. Here is a partial record exported in JSON with many "\n" not escaped.

	{
		"id" : 308518,
		"itemid" : "https:\/\/data.datatourisme.gouv.fr\/43\/0fc1d1b2-37d1-3a67-868b-2150fd158791",
		"lastupdate" : "",
		"title" : "JOURNÉES EUROPÉENNES DU PATRIMOINE - MUSÉE PAYSAN D'ÉMILE",
		"shortdescriptionfr" : "Pour la 36ème édition des Journées Européennes du patrimoine, le musée Paysan vous ouvre ses portes.",
		"descriptionfr" : "En plus de la visite du musée et de la découverte de l'exposition temporaire, le musée vous propose plusieurs animations supplémentaires. \n\nAu programme :\n- diaporama \"La table à travers la peinture européenne du Moyen Age au 19ème siècle\"\n- sur le samedi et le dimanche : démonstration de machines à vapeur miniature.\n\nTarif réduit et horaires d'ouverture élargis.\n\nLe vendredi : ouverture du musée de 14h30 à 18h30. Tarif : 5€ pour les adultes et  2€50 pour les enfants de moins de 12 ans.\n\nLe samedi : ouverture du musée de 10h30 à 12h30 et de 14h30 à 19h. Gratuit\n\nLe dimanche : ouverture du musée de 13h30 à 18h30. Tarif : 4€ pour les adultes et 2€ pour les enfants de moins de 12 ans.\nIn addition to visiting the museum and discovering the temporary exhibition, the museum offers several additional activities.\n\nIn the program :\n- slide show \"The table through European painting from the Middle Ages to the 19th century\"\n- on Saturday and Sunday: demonstration of miniature steam engines.\n\nReduced tariff and extended opening hours.\n\n\nFriday: opening of the museum from 2.30 pm to 6.30 pm. Price: 5 € for adults and 2 € 50 for children under 12 years.\n\nSaturday: opening of the museum from 10.30 am  to 12:30 and from 2.30 pm to 7 pm. Free\n\nSunday: opening of the museum from 1.30 pm to 6.30 pm. Price: 4 € for adults and 2 € for children under 12 years.\n\n En plus de la visite du musée et de la découverte de l'exposition temporaire, le musée vous propose plusieurs animations supplémentaires. \n\nAu programme :\n- diaporama \"La table à travers la peinture européenne du Moyen Age au 19ème siècle\"\n- sur le samedi et le dimanche : démonstration de machines à vapeur miniature.\n\nTarif réduit et horaires d'ouverture élargis.\n\nLe vendredi : ouverture du musée de 14h30 à 18h30. Tarif : 5€ pour les adultes et  2€50 pour les enfants de moins de 12 ans.\n\nLe samedi : ouverture du musée de 10h30 à 12h30 et de 14h30 à 19h. Gratuit\n\nLe dimanche : ouverture du musée de 13h30 à 18h30. Tarif : 4€ pour les adultes et 2€ pour les enfants de moins de 12 ans.",
		"shortdescriptionen" : "",
		"descriptionen" : "",
		"lat" : 43451462,
		"lng" : 733963,
		"itemtypes" : "EntertainmentAndEvent, Event",
		"address" : "avenue de la Bourdette, Simorre, 32420",
		"categories" : "HeritageDays",
		"tags" : "",
		"event" : false,
		"accessible" : false
	}

Thanks
