### ISSUE TITLE
Add schema selection for Postgresql

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1169]
It would be nice to have a dropdown list similar to database names for the schemas in Postgresql so I can write queries without putting schemata in front of my table names all time. Though it should be also possible to set no schemata selection to make sure you can work with multiple schemas in one query. Schema names should be put in quotes.

**Comment by serge-rider** [comment]
Actually you can change active schema in PG using database navigator (select schema->context menu->Set Active).
But database combo in main toolbar shows database list (not schemas). I agree, this is quite useless in case of PostgreSQL.
I'll fix this in the next version.
