### ISSUE TITLE
MongoDB Connection Settings shows invalid settings while a connection is being established

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#117]
I have a MongoDB connection on which I'm having some trouble connecting. This is not DBeaver's fault - I'm still configuring the settings. 

The connection setttings look like this: 
![image](https://cloud.githubusercontent.com/assets/1073841/11850268/44c7c0f8-a3fa-11e5-8621-d586d31d5a44.png)

But if I try to expand the connection, then open Connection Settings while it is still trying to connect, the connection settings look like this:
![image](https://cloud.githubusercontent.com/assets/1073841/11850293/69ce135c-a3fa-11e5-8c35-589cee107eba.png)

You can see that the Host field has resolved the hostname to an IP and that the port has changed.

Sorry if this is not the right place to file Enterprise issues.

**Comment by serge-rider** [comment]
I assume you are using SSH tunnel. During connection initiation actual host/port values are changing.
Of course UI shouldn't see it.

**Comment by codebling** [comment]
You are correct. I'd put that in the information in my head to write in to the issue description but it somehow didn't make it. Thanks !
