### ISSUE TITLE
New launcher with high CPU usage

### ISSUE THREAD

**Issue by tetafro** [serge-rider/dbeaver#1170]
DBeaver: 3.8.1 (x64 deb package from http://dbeaver.jkiss.org/download/)
OS: Ubuntu Desktop 16.10

First I'm running DBeaver using standard icon "DBeaver" in Ubuntu menu. Here is launcher code:

    [Desktop Entry]
    Version=1.0
    Type=Application
    Terminal=false
    Name=DBeaver
    GenericName=SQL Database Client
    Comment=Universal Database Manager and SQL Client.
    Path=/usr/share/dbeaver/
    Exec=/usr/share/dbeaver/dbeaver
    Icon=/usr/share/dbeaver/dbeaver.png
    Categories=IDE;Development
    StartupWMClass=DBeaver
    StartupNotify=true

Then I make "Lock to launcher", so that icon stays in panel after closing DBeaver. And if I close DBeaver and run it again using this icon, cpu usage is very high (`top` shows proccess `java` - 125%) and doesn't decrease (even after 20 hours).

Here is code of this launcher from panel (`/home/myusername/.local/share/applications/swt.desktop`):

    [Desktop Entry]
    Encoding=UTF-8
    Version=1.0
    Type=Application
    Name=DBeaver - General 
    Icon=swt
    Path=/usr/share/dbeaver
    Exec=/usr/bin/java -jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /usr/share/dbeaver/dbeaver -name Dbeaver --launcher.library /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so -startup /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar --launcher.overrideVmargs -exitdata 9018040 -vm /usr/bin/java -vmargs -jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
    StartupNotify=false
    StartupWMClass=SWT
    OnlyShowIn=Unity;
    X-UnityGenerated=true

Some more info:

    $ top

    top - 07:47:57 up 41 min,  1 user,  load average: 1,75, 0,89, 0,82
    Tasks: 278 total,   1 running, 277 sleeping,   0 stopped,   0 zombie
    %Cpu(s): 43,1 us, 12,1 sy,  0,0 ni, 44,7 id,  0,0 wa,  0,0 hi,  0,1 si,  0,0 st
    KiB Mem : 16356092 total,  3554884 free,  3568740 used,  9232468 buff/cache
    KiB Swap:        0 total,        0 free,        0 used. 12128496 avail Mem 

      PID USER        PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                        
     7111 myusername  20   0 8027488 330480  46556 S 128,5  2,0   0:40.63 java                                                                                                                                           
     1458 root        20   0  347704 142408  49896 S  66,9  0,9   7:33.76 Xorg                                                                                                                                           
     7018 root        20   0       0      0      0 S  13,6  0,0   0:05.86 kworker/2:1                                                                                                                                    
     3811 myusername  20   0  700940  70804  33912 S   4,0  0,4   1:37.56 gnome-system-mo                                                                                                                                
     3358 myusername  20   0 1531624 173920  66468 S   3,3  1,1   2:03.54 compiz

    $ ps aux | grep 7111
    myusername   7111 96.0  2.5 8098412 409596 ?      Sl   07:47   6:45 /usr/bin/java -jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /usr/share/dbeaver/dbeaver -name Dbeaver --launcher.library /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so -startup /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar --launcher.overrideVmargs -exitdata 9018040 -vm /usr/bin/java -vmargs -jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar

And this is what I when DBeaver runs normally (from Ubuntu menu without high CPU usage):

    $ ps aux | grep java
    myusername   7535 12.3  1.9 7962080 321284 ?      Sl   08:01   0:20 /usr/bin/java -jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /usr/share/dbeaver/dbeaver -name Dbeaver --launcher.library /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so -startup /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar --launcher.overrideVmargs -exitdata 8a800f -vm /usr/bin/java -vmargs -jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar

Is there a way to have normal DBeaver launcher on the Ubuntu panel?

**Comment by serge-rider** [comment]
Check this: #1041 (disabling gtk 3 usually helps). 
Generally this issue should be resolved in 4.0 version.

**Comment by tetafro** [comment]
If I just do this

    export SWT_GTK3=0

nothing changes. Once again to be clear - DBeaver runs normally when launched from Ubuntu menu or when I type `dbeaver` in console. It's only new icon in quicklaunch bar that makes it run slowly.

I ended up by changing `Exec` in the source of launcher (`/home/myusername/.local/share/applications/swt.desktop`) from that long line to

    Exec=/usr/share/dbeaver/dbeaver
