### ISSUE TITLE
Cannot delete or edit and update MongoDB records

### ISSUE THREAD

**Issue by DaniLatin** [serge-rider/dbeaver#1171]
Hy,
I have the following problem and since it's persisting for quite a few releases now, I'm guessing nobody noticed it...

I cannot delete or edit and save changes in MongoDB in DBeaver Enterprise. Every time I try to delete a record and save chages it replies with the following error:
**Error synchronising data with database**
org.jkiss.dbeaver.model.exec.DBCException: Document wasn't deleted: WriteResult{, n=0, updateOfExisting=false, upsertedId=null}

... or when I try to edit a record and save:
**Error synchronising data with database**
org.jkiss.dbeaver.model.exec.DBCException: Document wasn't updated: WriteResult{, n=0, updateOfExisting=false, upsertedId=null}

In previous versions (3.7.4, I think), in works just fine.

That's it, I thought you should know about this issue.
Anyway, I really love using DBeaver, it's a fantastic tool. Keep up the good work   ;)

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
I've reproduced that, thanks for details.
The original problem is _id format. It is parsed as standard Mongo object ID but in fact it should be used as string identifier.
Will fix it in the next version. Fix will be in EA version (https://dbeaver.com/files/ea/) today.

**Comment by serge-rider** [comment]
@huynhtk did you have a chance to check it?

**Comment by huynhtk** [comment]
@serge-rider I am able to delete and update a document now.  Thank-you for the fix =)
