### ISSUE TITLE
Cannot edit(remove or add) new column in SQL server

### ISSUE THREAD

**Issue by asmaddy** [serge-rider/dbeaver#1172]
currently i had issue to alter/add/remove column or table in sql server database using dbeaver using UI.i can only edit table using command line using DML.

i test on oracle database ,the function alter/add/remove column was functioning.

**Comment by serge-rider** [comment]
What exactly issue do you have, are there some errors/crashes?

Generally you should be able to edit SQL Server tables (at least add/remove columns). This is a standard feature for all databases.

**Comment by asmaddy** [comment]
the issue i cannot edit or alter table using GUI.

![screen shot 2017-01-24 at 9 15 17 am](https://cloud.githubusercontent.com/assets/25294408/22229936/c37ecfa4-e215-11e6-82f1-021d66eb7991.png)

after click on the data type there was no list down shown.

it was different when we edit data type on oracle .click on data type it will show list of data type

![screen shot 2017-01-24 at 9 20 12 am](https://cloud.githubusercontent.com/assets/25294408/22230052/6ef1c526-e216-11e6-8ed5-0dfe5f0641a9.png)

**Comment by serge-rider** [comment]
Column properties change is not supported for MS SQL. 
Feature request: #810

**Comment by marcgise** [comment]
+1
