### ISSUE TITLE
Generate SQL not working without open SQL editor

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1174]
When I try to generate some SQL (for example via right click on table and select Generate SQL - DDL) and forgot to open SQL Editor before, nothing happens (no message, just nothing). I must manually open SQL Editor and click Generate SQL again.
Generating SQL commands should work without SQL Editor window (as it doesn't use it - I must copy and paste the SQL manually) OR it could open the SQL editor automatically (and ideally auto insert generated SQL, but this should be probably another issue).

**Comment by serge-rider** [comment]
This is a bug, thanks for report.

Currently generate SQL works only if ANY database editor (not just SQL editor) is open.
