### ISSUE TITLE
[SQLITE] - password protected files

### ISSUE THREAD

**Issue by AndrzejKl** [serge-rider/dbeaver#1177]
Hi.
There's any possibility to connect with sqlite protected file? I try to put pass in "Password" box, but always I get error 26: 
SQL Error [26]: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
  java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)

 when I try to see tables in.

**Comment by serge-rider** [comment]
By default SQLite doesn't support password protection. But this can be supplied by SQLite extensions: http://stackoverflow.com/questions/5669905/sqlite-with-encryption-password-protection
What exactly implementation do you use?

Anyhow, default SQLite driver in DBeaver doesn't support passwords.
