### ISSUE TITLE
DBeaver CE relicense on Apache License

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#1180]
DBeaver CE 4.0 will be licensed under Eclipse Public License (EPL).

Main reason is to allow DBeaver CE sources/binaries usage in commercial/proprietary software.

**Comment by carlosspohr** [comment]
Agreed, thanks.

**Comment by maitrepylos** [comment]
Cool, thanks

**Comment by serge-rider** [comment]
Also check #1145

**Comment by serge-rider** [comment]
After all I think that ASL (https://www.apache.org/licenses/LICENSE-2.0) would be better for DBeaver CE. 
EPL is a bit more restrictive.

**Comment by serge-rider** [comment]
Official statement:
DBeaver CE is licensed under Apache License 2.0 since Feb 02 2017.
