### ISSUE TITLE
Bug in updating value viewer

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1184]
A problem apparent when viewing multiline textual data:

When clicking on a result cell that is already selected, value in F7 panel viewer does not get updated.

Also, when running another query afterwards, selection in the results table view remains (as it probably should), but the value viewer gets blanked. It probably should get updated to the new value in the selected cell and this will fix the problem.

This is particularly annoying when viewing results which contain one and only one cell - it remains selected but there is no easy way to deselect the already selected cell, which renders the value viewer effectively useless.

**Comment by lacanoid** [comment]
Actually, pressing tab (twice) in results view seems to update the widget, bypassing the problem :)

**Comment by serge-rider** [comment]
Thanks for report.
