### ISSUE TITLE
'Empty source' on Declaration-Tab at an customized Oracle View

### ISSUE THREAD

**Issue by biraweich** [serge-rider/dbeaver#1186]
![grafik](https://cloud.githubusercontent.com/assets/25346050/22292640/82c59c8e-e30c-11e6-93c6-bf50aa0d0134.png)
![grafik](https://cloud.githubusercontent.com/assets/25346050/22292665/98afa22e-e30c-11e6-97e1-91f3629eac38.png)

The Screenshots above show the same View, and if i compile view or show data, ist works...

**Comment by serge-rider** [comment]
Sometimes (rarely) Oracle view definition read fails because of JDBC driver error "Stream has already been closed". I'll patch driver config.
Thanks for noticing.

Ref: http://stackoverflow.com/questions/10174951/hibernate-custom-type-to-avoid-caused-by-java-sql-sqlexception-stream-has-al

**Comment by biraweich** [comment]
So thanks a lot, for the fast fix - as i suggest, the configfile will be updated at next updateversion?

**Comment by serge-rider** [comment]
Yes. 
Actually this fix will be included in the hotfix version 3.8.5 (will be released 30.01).

**Comment by ecamargo81** [comment]
Hi, this is an old thread, but still occurring in new versions of dbeaver.

I'm using Version 21.2.3.202110151816

**Comment by uslss** [comment]
@ecamargo81 could you create a new issue with it full description?
thanks in advance

**Comment by ecamargo81** [comment]
Description it's exactly the same that this post.
_____________________________________________________
  Éderson F. de A. Camargo

  MBA - TI Administration /  Bsc.Computer Science
  Porto Alegre - RS - Brazil
 ____________________________________________________


Em ter., 16 de nov. de 2021 às 15:34, Dziyana ***@***.***>
escreveu:
