### ISSUE TITLE
Global column filter only overwrites local filter

### ISSUE THREAD

**Issue by roscoe** [serge-rider/dbeaver#1187]
When I click **Show global filter** to open the **Filtering: All Columns** dialog, the Include and Exclude lists are always empty and adding any filters in the dialog overwrites both column filter lists at the local table level. The column filter lists for other tables are not affected.

Running DBeaver Enterprise 3.8.4 on Mac.

Thank you.

**Comment by serge-rider** [comment]
Thanks for report
