### ISSUE TITLE
Strange separator behavior in procedure editor

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1188]
I have one little problem. In procedure editor when I try to shrink too large "Procedure Columns" section when I hit min or max limits, the separator continues moving (which is normal), but never gets back and stays where I leave it when I release mouse button. Everything on Linux (Mint 18 Mate x64 version). On Windows it works OK (the separator returns back). 

It's better seen on picture below. It's not too big problem, but I just want to let you know about it.
Does anybody else have this problem?

![test](https://cloud.githubusercontent.com/assets/24586123/22303963/d7f0dbfa-e335-11e6-9108-780bd526ad4d.gif)

**Comment by lacanoid** [comment]
Perhaps it would make sense to hide procedure columns panel alltogether when there aren't any to show.

**Comment by elring** [comment]
This issue was about strange separator behavior (separator stays on top when hitting min/max size). Probably problem with some GTK version (?). Can be probably closed as no one has this same problem.

About procedure comlumn size - I was about to file new issue - to allow saving height of procedure columns (probably on procedure editor close). What do you think?

**Comment by serge-rider** [comment]
Yes, please create separate issue for that.
