### ISSUE TITLE
Active catalog/schema set but not working on export resultset

### ISSUE THREAD

**Issue by Xrizoo** [serge-rider/dbeaver#1192]
Hi Serge-Rider
This is a small issue i've found when I try to export a query result on any kind of format. 
In spite of setting a "Active catalog/schema" on the IDE, and working perfectly within the application, when I try to export the resultset I got an error alerting "the table or view does not exist". If I put the schema, It works correctly.
Anyway, apart of this little problem... Thanks for you amazing app.

**Comment by serge-rider** [comment]
You can try to disable option "Open new connection" on "Extraction Settings" page of export wizard. Thus DBeaver will use default connection.

**Comment by Xrizoo** [comment]
Ok... It works!!! 
Thanks so much.
