### ISSUE TITLE
FK creation to tables in different schema (PostgreSQL)

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1193]
When trying to create new foreign key, dbeaver offers list of tables only in current schema. 
Creating FK to table in different schema is (at least in PostgreSQL) completely allowed, but impossible in dbeaver. 

Additionally in list of FK the column "Associated Entity" should contain the table schema.

**Comment by serge-rider** [comment]
Agreed. This had to be done a long time ago.

**Comment by elring** [comment]
Please, don't just make one big list of tables from all schemas. Databases may have hundreds of tables. One selector for schema and then list of tables from this schema or tree simmilar to database navigator would be nice.

Offtopic:
Are you interrested in issues with missing features in dbeaver (sequence editing, FK editing, index editing, proper procedure editing etc.?). 

Offtopic2: Thank you very much for dbeaver. I missed db admin tool on linux for very long time :)

**Comment by serge-rider** [comment]
Sure.

Yes, I'm interested. But please create a feature request only if you think that it is really important and not too hard to add. There are zillions of potential features which can be added but they will just make a mess in issue tracker.
