### ISSUE TITLE
No database appear , Mariadb

### ISSUE THREAD

**Issue by ahmed89albttashi** [serge-rider/dbeaver#1194]
Dear Serge,

With thanks to your appreciated efforts, 

I cannot list my databases available in mariadb local server. 
Hope this image clear to say what I face.

![db-serge-ticket](https://cloud.githubusercontent.com/assets/6708191/22334204/46c67a40-e3f3-11e6-93ef-d4c6e1ce3318.png)

**Comment by serge-rider** [comment]
Duplicate of #1121.
Change MariaDB driver version.

**Comment by ahmed89albttashi** [comment]
A lot of thanks .

updated to 1.5.7. Work
