### ISSUE TITLE
High CPU usage when querying

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#1195]
I updated dbeaver to the latest version this morning. Then, I started having some high CPU usage (60-70%) randomly on executing queries.

I'm running windows 10 N 64 bit

**Comment by serge-rider** [comment]
Duplicate of #1189.
Will be fixed in hotfix version (30.01)

**Comment by gabriele-ricci-kyklos** [comment]
I searched issues for 'cpu' to see if somebody else had reported this one, but I searched only for the open issues :D
