### ISSUE TITLE
Can't Paste Clipboard into Search Box

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#1196]
When I try to ctrl-V paste into any of the tabs that support ctrl-F search, I get the error showcased in this **screenshot:**
http://neartalk.com/ss/2017-01-26_004_1813x979.png

**Past error:**
"Clipbard contains data in unsupported format"

I'm just trying to paste a table-name that I copied out of one of my dBeaver sql queries, so there shouldn't be anything strange about the clipboard data I'm trying to paste.

**Comment by serge-rider** [comment]
Yep. Thanks for report.
