### ISSUE TITLE
Export data gives an error and executing does not

### ISSUE THREAD

**Issue by Omirr85** [serge-rider/dbeaver#1199]
I have following query:

> WITH recentste_onderdeel_bestek AS (
> 	SELECT recente_data.*, onderdeel_set.besteklot_ref 
> 	FROM (
> 		SELECT onderdeel_ref, max(begin_datum) AS recent_datum 
> 		FROM onderdeel_set
> 		GROUP BY onderdeel_ref)	AS recente_data
> 	LEFT JOIN onderdeel_set ON onderdeel_set.onderdeel_ref = recente_data.onderdeel_ref AND onderdeel_set.begin_datum = recente_data.recent_datum),
> recenste_actieve_onderdelen AS (
> 	SELECT 
> 		onderdeel_ref
> 		, besteklot_ref
> 	FROM recentste_onderdeel_bestek 
> 	INNER JOIN onderdeel ON recentste_onderdeel_bestek.onderdeel_ref = onderdeel.id
> 	INNER JOIN onderdeel_type ON onderdeel.dtype = onderdeel_type.id
> 	WHERE onderdeel.status = 'A')
> SELECT onderdeel.id, onderdeel.naam, onderdeel.naam_pad, onderdeel_type.naam AS "TYPE", onderdeel.parent_id AS "Id vader", 
> 	onderdeel.org_id AS "Organisatie", 
> 	onderdeel.laatste_update AS "Laatste wijziging", 
> 	onderdeel.update_user_ref AS "Laatste wijziging door", 
> 	onderdeel.beheerder_wa_ref AS "Beheerder directie", 
> 	onderdeel.beheerder_bh_ref AS "Beheerder district", 
> 	onderdeel.tech_toezichter_ref AS "Toezichter", 
> 	onderdeel.ZONE,
> 	onderdeel.group_id AS Toezichtgroep,
> 	onderdeel.status, onderdeel.toestand, 
> 	onderdeel.begin_datum, onderdeel.eind_datum, 
> 	regexp_replace(onderdeel.commentaar, '[\n\r]+', ' ', 'g' ) AS commentaar , 
> 	regexp_replace(onderdeel.spec_omschrijving, '[\n\r]+', ' ', 'g' ) AS spec_omschrijving ,
> 	provincie, fusie_gemeente, deel_gemeente, 
> 	adressen.zipcode AS "Postcode", straat, 
> regexp_replace(site, '[\n\r]+', ' ', 'g' ) AS site 
> , nis, x AS gps_x, y AS gps_y, r AS gps_r,
> 	besteklot.nummer AS "Bestek nummer", 
> 	besteklot.lot AS "Bestek lot", besteklot.aannemer_ref AS "Aannemer referentie", aannemer.naam AS "aannemer naam", 
> 	aansluitingen.aansluitnr AS "Aansluiting nummer", aansluitingen.ean AS "Aansluiting EAN"
> FROM onderdeel 
> 	LEFT JOIN onderdeel_type ON onderdeel.dtype = onderdeel_type.id 
> 	LEFT JOIN onderdeel_set ON onderdeel.id = onderdeel_set.onderdeel_ref
> 	LEFT JOIN adressen ON onderdeel.adres_id  = adressen.adres_id
> 	LEFT JOIN gps ON onderdeel.gps_id = gps.id
> 	LEFT JOIN recenste_actieve_onderdelen ON onderdeel.id = recenste_actieve_onderdelen.onderdeel_ref
> 	LEFT JOIN besteklot ON recenste_actieve_onderdelen.besteklot_ref = besteklot.id
> 	LEFT JOIN aannemer ON besteklot.aannemer_ref = aannemer.referentie
> 	LEFT JOIN aansluitingen ON onderdeel.aansluit_id = aansluitingen.id
> WHERE onderdeel.group_id = 'AWV_EM_VB' AND onderdeel.status = 'A';

When I run this on my VM (Win10, DBeaver 3.7.8) there are no problems.
However when I run this on my laptop (Win7, DBeaver 3.8.4) there is a problem exporting this query.
I can execute it and get 200 rows (and more by scrolling down). However, when I try to export the query I get following error: 
SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
  ERROR: current transaction is aborted, commands ignored until end of transaction block
    org.postgresql.util.PSQLException: ERROR: relation "recenste_actieve_onderdelen" does not exist
  Position: 280

The query export on 3.7.8 results in a dataset of 55 521 records

Is this a known bug, if so, to what version do I downgrade to not have this bug ;-)

**Comment by serge-rider** [comment]
Probably a duplicate of #1138 or #1192
Try to disable row count fetch and new connection opening in export wizard.

**Comment by Omirr85** [comment]
disabling row count fetch did indeed remove this issue. I'll close this since the problem is known.
Thanks for the help!
