### ISSUE TITLE
Question: Custom queries and data filters

### ISSUE THREAD

**Issue by Tix2garr** [serge-rider/dbeaver#1200]
I am trying to run a query that has multiple parts to it, returning multiple tables.

When I look at the resultsets, it shows that I can't use the filters.  In fact, if I go to Configure - Order/Filter, at the bottom it states "Data filters and custom orderings are disabled for custom queries."

I looked at the features page and the Wiki, but I can't find anything about it.

Is there anyway to get around this?  I'm really liking DBeaver, but not being able to filter my results is a bummer.  <wry smile>

Thanks.

Michael

**Comment by serge-rider** [comment]
Yes, if your query returns multiple resultsets then custom filters cannot be applied - this is a DBeaver limitation.
In most cases multiple resultsets are produced by multiple consequent queries (e.g. in SQL server) or by stored procedures. It is not possible apply filters in both these cases.
I'm afraid there is no workaround for this for now.

If you think you have a different case - please post query example.

**Comment by Tix2garr** [comment]
Sadly, I don't have a different case.  <wry smile>

I'm guessing it's because you are applying the filters to the result-set that comes back after running it again and that can't be done with multiple consequent queries.

I was really hoping there was something that could be done like setting the rows returned to 0 (unlimited) and then it would filter the existing data.  Bummer!

Thank you for the response.

Michael
