### ISSUE TITLE
java.lang.NullPointerException error bug

### ISSUE THREAD

**Issue by kcciti** [serge-rider/dbeaver#1201]
Hi,

There seems to be a bug. I'm running postgresql 9.6 and DBeaver 3.8.4. The bug can be replicated by doing the following.

1.) run an SQL and export the results to to a csv file
2.) attempt to run the same SQL again (doesn't seem to matter whether you've made changes to it or not - note, I did not save the sql when I made the change again).
3.) the error java.lang.NullPointerException gets thrown.

This seems to be fixed if I closed beaver and restart. The sql will be able to run again but will hit the error again as soon as I export the results to a csv file and try to run again.

Thanks.

**Comment by serge-rider** [comment]
Can't reproduce.
Please post error stacktrace (you can get it in Error Log view).

**Comment by kcciti** [comment]
Hi,

 Attached are the error logs. 

The an initial warning was thrown when exporting to CSV at 18:40:04. However, the export completed and looks fine. The error that stopped the sql was thrown at 18:40:31. The SQL did not execute.

Hope this helps.

Thanks.
[ErrorLog.txt](https://github.com/serge-rider/dbeaver/files/736818/ErrorLog.txt)

**Comment by serge-rider** [comment]
For some reason I still can't reproduce that.
Anyhow, having a log I have made a few fixes in SQL editor. Please try EA version (http://dbeaver.jkiss.org/files/ea/) - hopefully this problem was resolved.

**Comment by kcciti** [comment]
Hi,

Just tried it with the EA version. The bug seems to be fixed. Keep up the good work.

Thanks.

**Comment by serge-rider** [comment]
Great, thanks for report.
