### ISSUE TITLE
Database export completed dialog-box juts out desktop dimensions

### ISSUE THREAD

**Issue by snowowl78** [serge-rider/dbeaver#1203]
After exporting  a database, an dialog box appears.

This dilaog box juts out the desktop borders, by writing all the table-names next to another.
Wouldn't it be better to show them shortend or seperated in lines?

![spectacle s21148](https://cloud.githubusercontent.com/assets/17596877/22418983/a1ebd9ca-e6db-11e6-8710-6aee8d6eaf33.png)

**Comment by serge-rider** [comment]
Good point
