### ISSUE TITLE
Result export does not work with CTE

### ISSUE THREAD

**Issue by sjstoelting** [serge-rider/dbeaver#1204]
Tested with 3.8.5, but is reproducible with older versions, too.
Could be reproduced with the [Chinook Database](http://chinookdatabase.codeplex.com/) against PostgreSQL.

`WITH t AS
	(
		SELECT *
		FROM "Album"
	)
SELECT *
FROM t
;`

Right mouse On the resultset -> Export Resultset ...
Choose any export format and go on until the finish button is available. Trying to execute the export does result in: SQL Error [25P02]

A workaround is to create a view with the CTE and export from the  select of that view.

And thanks a lot for your work on this fantastic tool.

**Comment by serge-rider** [comment]
Just disable "Select row count" option in export wizard.

I'll add transaction recovery in export wizard (so bad "select count" won't break export).

**Comment by sjstoelting** [comment]
Thanks a lot, Serge, that solved the problem for me.
