### ISSUE TITLE
Improvement: Tab list search

### ISSUE THREAD

**Issue by guilhas** [serge-rider/dbeaver#1205]
Hello,

When in 'Script editor window' I click CTRL-E, a pop-up appears, with a list of all open tabs, and input box to filter.
Would it be possible to make allow the word to be in the middle of the name?
Currently the search starts from the beginning of name.

Great application.

Regards,
Lino

**Comment by serge-rider** [comment]
It is a base Eclipse function.
To search in the middle of editor name use asterisks (e.g. `*My*`)

**Comment by guilhas** [comment]
ah ok, how did I not tried that... Thanks.
