### ISSUE TITLE
switching presentation modes with keyboard loses focus

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#1206]
Hi,
in dbeaver 3.8.5 in the result pane switching presentation modes between grid and text loses focus on the result pane. If you want to switch back the presentation mode using keyboard you first need to navigate to the result pane and obtain focus again.

How to reproduce:
1. Run any query that returns a result set
2. in presentation mode hit Ctrl+` to switch between grid and text
3. if you hit ctrl+` again you won't be switched back to the original presentation mode because the pane is not in focus anymore.

**Comment by serge-rider** [comment]
Can't reproduce (Windows 10). What is you OS?

**Comment by boriborm** [comment]
3.8.5
If focus on grid or text panel and click Ctrl+`, switch work once and focus lost after rerender panel (no focused elements).
If focus on SQL editor panel, Ctrl+` work fine.
OS Ubuntu 15.10

**Comment by norbitheeviljester** [comment]
OS Ubuntu 16.10 with Unity

**Comment by anophelesgreyhoe** [comment]
I have the same issue on Ubuntu 16.04 / Unity.

**Comment by serge-rider** [comment]
Eventually I've reproduced that. This was caused by differences in controls focus change in Windows and various GTK versions.
