### ISSUE TITLE
Missing Time to execute query in Status bar

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1207]
Time to execute query no longer appears in the status bar.

Steps to reproduce 

1) run a query

<img width="1273" alt="screen shot 2017-01-30 at 4 20 55 pm" src="https://cloud.githubusercontent.com/assets/9246654/22447601/2d293da8-e708-11e6-9631-5b50b00e4787.png">

**Comment by r-richmond** [comment]
#903 was a similar issue

**Comment by serge-rider** [comment]
Thanks for report.
