### ISSUE TITLE
Are column properties not editable via the GUI?

### ISSUE THREAD

**Issue by CMCDragonkai** [serge-rider/dbeaver#1208]
I just tried to click on auto generate and auto increment in on a sqlserver connection, but there's no effect.

**Comment by serge-rider** [comment]
They are not editable for SQL Server. Only basic functions are available in SQL Server extension because it is based on Generic (see #810).

**Comment by CMCDragonkai** [comment]
Ok, so I'm guessing there's no way to export a whole database as well? Only exporting resultsets.

**Comment by serge-rider** [comment]
For SQL Server you can export tables (select all tables->right click->Export table data).

But not whole database (this is supported only for MySQL and PostgreSQL).
