### ISSUE TITLE
Sum selected values from table fetched

### ISSUE THREAD

**Issue by jzlima** [serge-rider/dbeaver#1211]
It would be possible add a label that sum selected values from table fetched?

In below Table fetched have an info about rows fetched and could be contain info about selected columns too.  Like sum selected values.

**Comment by serge-rider** [comment]
Not sure I fully understand that.

If you need sum of some numeric column then you can use Aggregate panel.
If you need information about columns you can use Metadata panel.

**Comment by jzlima** [comment]
Some times we need a partial sum of columns. Only selected values. Like in excel.

**Comment by serge-rider** [comment]
Then just use Aggregate panel.
In results toolbar click on Panels dropdown -> "Aggregate columns".

**Comment by jzlima** [comment]
Great. That's it
