### ISSUE TITLE
Anomaly in Oracle Table DDL

### ISSUE THREAD

**Issue by roberto2357** [serge-rider/dbeaver#1214]
Hi Serge, I'm using DBeaver 3.8.5 - 32 bit for windows on Oracle 12c database. The Table DDL (as you can see in the image below) show a problem with VARCHAR2 data type. The parenthesis containing the field size are missed !
Thanks.

![immagine](https://cloud.githubusercontent.com/assets/22471800/22505985/47e1ca1c-e87e-11e6-82da-f53aa1c4570b.png)

**Comment by serge-rider** [comment]
This is a bug in DDL generation. Thanks for report.

Note: normally Oracle DDL should be generated on server-side but in some cases this function is not available (due to access restrictions).
