### ISSUE TITLE
PostgreSQL: Add owner for tables and views

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1215]
In Postgres, object owner (the role that created the object) is quite distinct from the namespace (schema). This information is very important to the DBA , since access permissions heavily depend on the owner.

DBeaver already displays this information for many objects (such as functions), but not for tables, views or sequences. It would be quite useful to add this to the table properties view.  

Note that it is currently possible to somewhat deduce the owner from the cool new permissions panel, but still, this is not quite the same thing.

Also, it might make sense to display this data in a special column in various listings of objects when viewing properties/listings for entire schema.

**Comment by serge-rider** [comment]
Ok, that's easy to do.
