### ISSUE TITLE
Postgres connection error

### ISSUE THREAD

**Issue by cjunge-work** [serge-rider/dbeaver#1219]
While trying to connect to a Heroku Connect Postgres database I am getting the following error:

```org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "[my ip]", user "username", database "database", SSL off```

I am running DBeaver 3.8.5 on Xubuntu 16.04.

I have tried the `PostgreSQL` and `PostgreSQL (Generic)` drivers, and same result. I can use the psql CLI client fine, and I can connect using HeidiSQL from my computer. I can connect successfully to a MySQL server.

Any help would be appreciated.

**Comment by serge-rider** [comment]
This is not a DBeaver issue (http://stackoverflow.com/questions/20392482/postgres-pg-hba-conf).
If you can connect with psql (from the same machine) then you need to set exactly the same connection settings (host, database, user name) in DBeaver.
If you connecting from a different machine then you need to add its IP in pg_hba.conf.

**Comment by cjunge-work** [comment]
I have set the exact same settings, as far as I can tell.
> $ psql -h [hostname] -p 5432 [dbname] [username] 
> Password for user [username]: 
> psql (9.5.5, server 9.6.1) 
> [dbname]=> `

In DBeaver the parameters are set to the same values (I copied them directly from the command above).

**Comment by cjunge-work** [comment]
The password is a 64 character hexdec string... would it be silently truncated in DBeaver?

**Comment by serge-rider** [comment]
No, DBeaver doesn't truncate passwords (or any other connection parameters).

From http://postgresql.nabble.com/Unable-to-connect-to-9-5-via-JDBC-driver-1207-td5885427.html:
try to uncomment the following in pg_hba.conf:
```
# IPv4 local connections:
# host    all             all             127.0.0.1/32            trust
```

This will enable incoming tcp/ip connections (psql may use something else).

**Comment by cjunge-work** [comment]
Found the problem: Heroku Connect uses SSL. Enabling SSL for the connection is working fine! I guess psql/HeidiSQL were detecting that automatically?

**Comment by serge-rider** [comment]
Interesting. Maybe they do.
Although is is more likely that they used non tcp/ip connection (which was permitted in pg_hba).

**Comment by lcustodio** [comment]
@cjunge-work How did you manage to enable SSL? 
Simply setting `ssl` to true in the Driver properties throws: 

*Same scenario with heroku postgres db.

```
SSL error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

```

**Comment by serge-rider** [comment]
@lcustodio You need to configure it on connection properties->Network->SSL page.

**Comment by cjunge-work** [comment]
@lcustodio on the SSL page, set `SSL mode: require` and either leave the `SSL Factory` blank or use the `org.postgresql.ssl.NonValidatingFactory`

**Comment by lcustodio** [comment]
Awesome! I managed to connect using Ubuntu 16.04 and macOS 10.11.6. Thanks

**Comment by parthpuneet** [comment]
@cjunge-work this worked for me

**Comment by oyepez003** [comment]
And ever choose your database name... never set "postgres" like database name in the connection, because that can also be the error ...

**Comment by Ronald-TR** [comment]
For anyone looking for the MacOS command line, just change the `<>` with the connection info:
`/Applications/DBeaver.app/Contents/MacOs/dbeaver -con "host=<>|name=<>|password=<>|port=5432|user=<>|connect=true|database=<>|driver=postgresql|ssl=true"`

**Comment by arvsr1988** [comment]
it was working on other clients for me. In DBeaver i had to update my postgres drivers. I used this StackOverflow answer to help me out https://stackoverflow.com/a/64546286/728610
