### ISSUE TITLE
Content Assist Highlight Color preference Option

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#122]
After configuring the content assist foreground / background to be more consistent with my dark theme I noticed that I was unable to change the content assist highlight color which leaves the current selection in an unreadable state.

Feature Request: Please add Content Assist Highlight Color as a color preference option.

![image](https://cloud.githubusercontent.com/assets/9246654/11879972/56f3cca4-a4b3-11e5-838c-dcfa5ccebdb3.png)

![image](https://cloud.githubusercontent.com/assets/9246654/11879984/670df678-a4b3-11e5-92bc-62689fcc577d.png)

**Comment by serge-rider** [comment]
These colors are controlled by Eclipse framework. And I can't reproduce that.

What particular dark theme do you use? The default one in the standalone DBeaver?
What's your OS?

**Comment by r-richmond** [comment]
I'm using the default one in standalone Dbeaver.

Windows 7
DBeaver 3.5.6

**Comment by serge-rider** [comment]
Still can't reproduce:
![dark-theme-assist](https://cloud.githubusercontent.com/assets/6398845/11912743/0bd90946-a65c-11e5-9c8d-41b15819e2e1.png)
Actually Eclipse CSS styling is a bit buggy. 
Try to make a fresh install and new workspace (use command line parameter -data "<some-test-folder>"). If it will help then resetting existing workspace (e.g. removing .metadata folder) should also help.

Anyhow, all these colors (as well as Content Assist panel itself) are provided by Eclipse framework.
I won't change default configuration - if it is good enough for millions of Eclipse users then it should be good enough for DBeaver users as well.
