### ISSUE TITLE
display sql when table schema modify issue

### ISSUE THREAD

**Issue by defcon8808** [serge-rider/dbeaver#1220]
i will modify table column attribute.

not null to nullable.

i checked not null.

here is auto-generated sql after save.
![dbeaver_bug](https://cloud.githubusercontent.com/assets/7532571/22538074/1782571c-e953-11e6-83f4-44bc4735e09b.png)

> ALTER TABLE RT_FILM_INFO MODIFY DEFECT VARCHAR2 NULL ;

if i this sql execute, occuring "ORA-00906".

below correct sql code

> ALTER TABLE RT_FILM_INFO MODIFY DEFECT VARCHAR2(80) NULL ;

**Comment by serge-rider** [comment]
Duplicate of #1214
