### ISSUE TITLE
Schema / Users filter doesn't change

### ISSUE THREAD

**Issue by nztaz** [serge-rider/dbeaver#1221]
We are using postgres database, I did not test on any other.

Since last 2 or 3 versions back once we set schema filter to a db connection it is very difficult to change the filter to another schema. Usually it reverts back to original one. We tend to copy that connection multiple times, exit and start dbeaver and changing schema filter before it is saved.

**Comment by serge-rider** [comment]
This happens because filters settings aren't saved (when you change only filters). Thanks for report.

Workaround: change any other property besides filters (e.g. connection description) - then save will work ok..
