### ISSUE TITLE
Rename Connection Problem in Database Navigator

### ISSUE THREAD

**Issue by yagamilighto** [serge-rider/dbeaver#1223]
- I have a connection under a folder in database navigator view.

![image](https://cloud.githubusercontent.com/assets/23170860/22547139/f4d1ca68-e948-11e6-8f0a-bb534d8058bb.png)

- I am renaming this connection by right-click (or F4) "Edit Connection" > General > Connection Name
![image](https://cloud.githubusercontent.com/assets/23170860/22547207/4db205c6-e949-11e6-903d-62c484d7676c.png)

- When I click OK. The connection is moved out of the folder even though I have not changed the connection folder setting above.

![image](https://cloud.githubusercontent.com/assets/23170860/22547255/86fe0636-e949-11e6-8b29-5dc245abf2a0.png)

- Tested with 3.8.5 64 bit.
- This problem does not happen when the connection is renamed by F2 (or right click > Rename)

Thanks in advance...

**Comment by serge-rider** [comment]
Thanks for report.
