### ISSUE TITLE
Filter table names

### ISSUE THREAD

**Issue by danydev** [serge-rider/dbeaver#1225]
I love DBeaver, I just miss little one MysqlWorkbench feature: I would like to filter the tables for a regex, something like `.*customer.*` to see any table that contains 'customer' on its name.
This is useful when inspecting database with hundreds of tables (like our legacy db :-))
Do you think would be possible to add it?

**Comment by serge-rider** [comment]
You can do this. 
Enable tables filter and use SQL patterns instead of regex (%customer%).

**Comment by danydev** [comment]
thank you!
