### ISSUE TITLE
Numeric precision issue working with SQLite

### ISSUE THREAD

**Issue by turboivan** [serge-rider/dbeaver#1228]
Hello,

I'm using dbeaver for Linux X64 and I'm very happy with it. I work on xubuntu.

I think dbeaver ce 3.8.5 has an strange behavior with numeric data type for SQLite. dbeaver does not show fractional part of numeric data type.
I have used sqlite3 binary to check numeric datatype and it was storaged correctly and it is displayed correctly.
Also, I have employed "sqliteman" on ubuntu and it shows correcty the data.
I have verified the "type formatter" option in Window/Preference menu and it have adjusted it for correct display and the issue continues.

![bug](https://cloud.githubusercontent.com/assets/18038110/22562506/74318c32-e942-11e6-851e-79bdcb639572.png)
**Here before edit data type formmater** 

![bug2](https://cloud.githubusercontent.com/assets/18038110/22562507/7433706a-e942-11e6-844f-f454ac09acb3.png)
**Here showing data with sqlite3 on terminal and data is shown correctly**

![bug3](https://cloud.githubusercontent.com/assets/18038110/22562508/7435cd1a-e942-11e6-9e43-7a2d2a6597b9.png)
**Using sqliteman and the data is shown correctly**

![bug4](https://cloud.githubusercontent.com/assets/18038110/22562509/74397e60-e942-11e6-8f30-8e2a781c682a.png)
**Editing "data type formatter" but the issue continues**

If I am doing uncorrectly somethink, Could somebody let me to know it?.
Thanks

Regards.

**Comment by serge-rider** [comment]
Can't reproduce.
What is the data type of column "multyplirate"? Could you post table DDL?

**Comment by turboivan** [comment]
Hello.

Yes of couse.
`create table C_UOM_Convertion (
   AD_Client_ID integer not null,
   AD_Org_ID integer not null,
   C_UOM_ID integer not null,
   M_Product_ID integer not null,
   isActive character(1) default 'Y' not null,
   UOMfromsymbol varchar(10) not null,
   UOMfromname varchar(60) not null,
   C_UOM_To_ID integer not null,
   UOMtosymbol varchar(10) not null,
   UOMtoname varchar(60) not null,
   multiplyrate numeric(10,3) not null,
   dividerate numeric(10,3) not null,

   foreign key (M_Product_ID) references M_Product(M_Product_ID)
);`

![bug5](https://cloud.githubusercontent.com/assets/18038110/22566966/9bd9c8d8-e953-11e6-9cfc-1d0b4b34d7e9.png)

Thanks

Regards

**Comment by serge-rider** [comment]
Still can't reproduce:
![default](https://cloud.githubusercontent.com/assets/6398845/22567382/c0ee20f4-e9a0-11e6-85cf-241a48e2a7a1.png)

What SQLite driver (version) do you use?

**Comment by serge-rider** [comment]
Ah, I did reproduce that.

**Comment by serge-rider** [comment]
This is a bug in SQLite JDBC driver. 
It sets column type according to first fetched value type. So if first value is integer (1 in your case) then it decides that whole column has type integer.

I'll try to make some workaround..

**Comment by turboivan** [comment]
OK, Thanks!

**Comment by serge-rider** [comment]
This issue will be resolved as part of #535.
SQLite uses dynamic types (i.e. any column may store value of any type) so classic relational db approach doesn't work. New SQLite extension will have special value handler.

**Comment by turboivan** [comment]
Thank you! Together we can produce better software!!
