### ISSUE TITLE
Oracle: column length on mouse over for VARCHAR

### ISSUE THREAD

**Issue by nanny07** [serge-rider/dbeaver#1229]
Since 3.8.5 it's seems that, in Oracle, for the column's type VARCHAR dbeaver doesn't show the column's length for it.
No problem for the type NUMERIC

Funny stuff: 

1. create a new table with one VARCHAR column (do not disconnect/reconnect)
2. execute the select query for it: it will show the column's length
3. disconnect and reconnect to the DB
4. execute the same select query of above and it will not show the length.
![errordb](https://cloud.githubusercontent.com/assets/17173586/22585723/7b1bc33e-e9f9-11e6-801e-f7f90a4e4da2.png)

**Comment by serge-rider** [comment]
This is a known issue (#1214). Will be fixed in the next version.
Thanks for report anyway.
