### ISSUE TITLE
Color option preference SQL Comment Color not enforced

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#123]
Bug

I'm currently using the dark theme and I've noticed that the SQL comment color option doesn't appear to be enforced.

![image](https://cloud.githubusercontent.com/assets/9246654/11880069/c3dcadcc-a4b3-11e5-8756-d6eefc5cfc78.png)

**Comment by serge-rider** [comment]
Currently comment color change takes effect only after SQL editor reopen.
