### ISSUE TITLE
PostgreSQL: Bug when persisting column descriptions

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1230]
When editing column description in the table properties columns panel, it is not persisted when saving.

![dbeaver-comments-bug](https://cloud.githubusercontent.com/assets/12818651/22609551/eb908858-ea61-11e6-9be1-aefd62d48d51.png)

Solution: add missing 'COMMENT ON COLUMN' statement.

**Comment by lacanoid** [comment]
It would be kind of cool, it SQL statements were generated only for values which were actually changed. Setting the column type in particular tend to rewrite the whole table, taking a potentially long exclusive lock :(

**Comment by serge-rider** [comment]
Agreed.
