### ISSUE TITLE
[Feature Request] Edit selected procedure  or function in a package

### ISSUE THREAD

**Issue by ceyhunnabiyev** [serge-rider/dbeaver#1231]
Package Functions or procedures only have  properties feature. If package has many procedures or functions, it is difficult to find  them in package body editor  which I want to edit . It would be nice  to add feature that edit selected procedure  or function in a package (something like highlighting selected procedure or function in package body-declaration editor ) 

Thanks for your great work,
Dbeaver  CE  version: 3.8.4

**Comment by boriborm** [comment]
Same issue 1161?!

**Comment by serge-rider** [comment]
Not the same. 
It is about navigation to a procedure declaration/definition in the package body.

**Comment by ceyhunnabiyev** [comment]
Thanks!!! For this feature what dbeaver version I update to, 4.0 milestone ???

**Comment by serge-rider** [comment]
This feature will be included in 4.0 (see milestone info for release date).

Or you can build from sources right now.
