### ISSUE TITLE
Open database object not searching properly for names starting with upper case

### ISSUE THREAD

**Issue by mapes610** [serge-rider/dbeaver#1232]
Hi, Im trying to search for tables

like this:
![dbeaver_2017-02-05_08-59-17](https://cloud.githubusercontent.com/assets/11725433/22624618/78d8efdc-eb81-11e6-9ab2-216335cb6333.png)

I made two copies of table:
D0F15148F
and
d0F15148F

The first one not found again but for the second works properly.

So I think the problem is when the name of table starts with upper case

**Comment by serge-rider** [comment]
Yes, PG extension used case-sensitive search. Thanks for report.
