### ISSUE TITLE
Error trying to expand Tables node

### ISSUE THREAD

**Issue by fmcnish-co** [serge-rider/dbeaver#1235]
Hi. I'm having the following error "[1790] ORA-01790: expression must have same datatype as corresponding expression" trying to expand the Tables node from an Oracle Database Schema.  I have traced the error using the Error Log and Query Manager and I have found the error is in the metadata connection.  The text of the SQL command tha throws the error is the folloing: 
```sql
	SELECT  t.OWNER,t.TABLE_NAME as TABLE_NAME,'TABLE' as OBJECT_TYPE,'VALID' as STATUS,t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS 
	FROM SYS.ALL_ALL_TABLES t
	WHERE t.OWNER='BDSEGUIMIENTO' AND NESTED='NO'
UNION ALL
	SELECT  o.OWNER,o.OBJECT_NAME as TABLE_NAME,'VIEW' as OBJECT_TYPE,o.STATUS,NULL,NULL,NULL,NULL,NULL,NULL,o.TEMPORARY,o.SECONDARY,NULL,NULL 
	FROM SYS.ALL_OBJECTS o 
	WHERE o.OWNER='BDSEGUIMIENTO' AND o.OBJECT_TYPE='VIEW'
```

If I try this command in another SQL tool it gave the same error. The error column is t.NUM_ROWS UNION with NULL. If I change the last NULL by 0 in another SQL tool the command run with errors). ¿How can It be fixed?

Thanks in advance.

PS: The connection is to an Oracle8i database. The driver used is "classes12.zip" (also tried with ojdbc14.jar). Tried in DBeaver version "DBeaver-CE-3.8.4" and 3.8.5.

**Comment by serge-rider** [comment]
Thanks for report. I'll fix this query in the next DBeaver version.
But I'm afraid DBeaver won't work well with Oracle 8.x or earlier. It just wasn't tested against it.

Possible workaround: you can use generic driver (just create new Generic driver in driver manager, set the same driver parameters as in existing Oracle driver). Generic driver doesn't use any custom SQL queries, it uses plain JDBC API. Thus it supports much less number of features but at least it will work.
