### ISSUE TITLE
Refreshing keyspaces in Cassandra results in duplicate entries

### ISSUE THREAD

**Issue by bpaczkowski** [serge-rider/dbeaver#1236]
Title says it all. The same does not happen when refreshing tables inside these keyspaces.

I'm using DBeaver EE 3.8.5 and Cassandra 3.10.

![dbeaver_2017-02-06_19-09-23](https://cloud.githubusercontent.com/assets/1371800/22659913/d43f01f8-ec9f-11e6-9c07-985a643de71a.png)

**Comment by serge-rider** [comment]
Thanks for report.

**Comment by loint** [comment]
Thanks
