### ISSUE TITLE
Where is the information containing the path for recently saved scripts  stored

### ISSUE THREAD

**Issue by timolingh** [serge-rider/dbeaver#1237]
Hi - Apologize if this is already answered.  I noticed that I can save a script when connected to a database and DBeaver  gives you a list of them the next time you connect.  Where does it store the directory where these files are saved and can you edit it?  Also can you toggle this feature?

Thanks, Tim

**Comment by serge-rider** [comment]
Do you mean SQL scripts? They are stored in DBeaver workspace (default location is in folder .dbeaver in user home).
You can press ALT+Enter in script and see exact file location on Resource page.

**Comment by timolingh** [comment]
Thanks for the response.

Yes, I am referring to SQL scripts. 

The files I have are not in the default workspace.  I specifically stored them in a different folder.  However, I do not see the location when I press ALT+Enter.  There is a 'Resource' section in the SQL Editor , but I don't see where it finding my script files.

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/22724976/16616292-eddb-11e6-96be-b1a50e827d46.png)

**Comment by timolingh** [comment]
this is what i see
![capture](https://cloud.githubusercontent.com/assets/11787868/22727592/926e8876-ed8e-11e6-9499-45c40c538200.PNG)

**Comment by serge-rider** [comment]
Ah, sorry, my mistake. Resource properties aren't shown for external (non-workspace) files.
For such files you can see file location in editor tab tooltip:
![image](https://cloud.githubusercontent.com/assets/6398845/22732275/a6766936-edfe-11e6-8452-66d4885ca0de.png)

**Comment by serge-rider** [comment]
BTW - you can link external folder to DBeaver workspace.
Right click on "SQL Scripts" in project navigator view->Link folder. Then you can work with external SQL files in the same manner as with regular ones.

**Comment by timolingh** [comment]
Great.  Thank you.
