### ISSUE TITLE
Improve error handling for SQL script execution

### ISSUE THREAD

**Issue by petrvalkoun-gooddata** [serge-rider/dbeaver#1238]
I am using DBeaver to execute rather long scripts. In case some DDL/DML statement fails, I am not able to see which statement failed, which is very unfriendly and time consuming. For starters, it would be enough to keep the little blue indicator (showing what statement is currently executed) active while presenting the error window and of course print on which line the execution failed to the log. Consider marking the failed statement in red etc.

**Comment by serge-rider** [comment]
This is a bug in one of recent versions. Error query should be highlighted (selected).
Will be fixed in the next version, thanks for noticing.

**Comment by petrvalkoun-gooddata** [comment]
never saw such fast bugfixes on free project in my life, you guys are wonderful!
