### ISSUE TITLE
Binary Format additional Option & Cleanup

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#124]
Feature Request:

1)
Currently using a lot of binary fields which contain bit flags. It would be very useful for a formatting option that displayed the results as 1's & 0's

Feature Request add a binary data formatter that will output strings in an arbitrary base. 
Include a checkbox that will pad the front with 0's (to maximum length of binary strings) if checked.

I'm interested in base 2 which would output 1's & 0's but other base options may be useful to other people.

example output when base is input as 2, and my maximum length of binary strings is 5
select to_byte(0) -> 0,     if checkbox for padding zeros is checked 00000
select to_byte(1) -> 1,     if checkbox for padding zeros is checked 00001
select to_byte(2) -> 10,   if checkbox for padding zeros is checked 00010
select to_byte(4) -> 100, if checkbox for padding zeros is checked 00100

![image](https://cloud.githubusercontent.com/assets/9246654/11880262/991dc57a-a4b4-11e5-93f6-4e1eb48f8b7e.png)

2)
Also is there a reason that Binary fields contain the binary image in every record rather than in just the header as opposed to the other fields such as int & date.

Request remove the small image from binary records and leave the image/data type indicator in the header so its consistent with other data types.

![image](https://cloud.githubusercontent.com/assets/9246654/11880217/5a15b8ba-a4b4-11e5-93f7-587cfa40ffc8.png)

**Comment by serge-rider** [comment]
What is "binary fields" actual type? Is it numeric or byte array?
With attribute transformers (new feature which will present in 3.6.6) I can represent numeric data types in any radix (e.g. in binary or hex). Will it solve your problem?

In regards to cell images - you can disable them on "Result Sets->Presentation" preference page.

**Comment by r-richmond** [comment]
> What is "binary fields" actual type? Is it numeric or byte array?

For my use case it is typically stored on the db as a numeric. Although I think its within reason to assume that the value will be returned as byte array (which is what I'm trying to demonstrate with to_byte).

Being able to display numeric in binary is nice but I'd like to be able to display only byte array datatypes in binary as well. I.e. I don't want to display all numbers as binary only the values i return as byte arrays with to_byte. Does that make sense?

For example consider user_id = 123, preferences_flag = 23 both stored as numeric on the db. 

Ideally, i could configure the binary data formatter in such a way that i could return the following.

select user_id, to_byte(preferences_flag)

user_id | to_byte(preferences_flag)
------- | -------
123 | 10111

**Comment by serge-rider** [comment]
Yeah, it is how it supposed to work.

**Comment by serge-rider** [comment]
![view_as_radix](https://cloud.githubusercontent.com/assets/6398845/14674821/89bb65da-070e-11e6-9b05-41930bd42d14.png)
