### ISSUE TITLE
Redshift connect hangs

### ISSUE THREAD

**Issue by anesthesi** [serge-rider/dbeaver#1240]
Hello,
On Ubuntu 16, version 3.8.4 (tried installing 3.8.5, but rolled back due to the following problem - that apparently happens now also in 3.8.4) - 
It seems that sometimes something gets wrong with my RedShift connection through DBeaver, and I'm unable to retrieve data (through SQL editor selects), and the program just freezes (I need to close it through System Monitor / pkill).
No restart help, only a totally removal of the application and then re-installation.

**Comment by serge-rider** [comment]
If it will hang again - please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and post it here.
Also you could try EA version (it is based on new Eclipse with many fixed GTK bugs): http://dbeaver.jkiss.org/files/ea/ (note: EA version may have another problems, it is not well-tested).

**Comment by anesthesi** [comment]
I installed the new version, I will write here if any problem occurs.
Meanwhile it's fine.
Thank you.
