### ISSUE TITLE
limit blob preview length

### ISSUE THREAD

**Issue by vladojr** [serge-rider/dbeaver#1242]
Hi,

I use postgres and have a table with BYTEA column. It takes ages to load as each row is a few MB in size. It would be great feature if it was possible to limit the max preview size of potentialy long columns.

This may break updates without PK when all columns are used as identifiers. Could be replaced by hash of such column in such case though.

Thank you

**Comment by serge-rider** [comment]
Please clarify - what exactly takes ages - resultset fetching or data visualization?

If you mean value view panel then it'd be better to close when browsing big binaries. 
As for binary presentation in grid - there is a preview size limit already (Preferences->Database->Result Sets->Binaries).

**Comment by vladojr** [comment]
I mean the resultset fetching, it would be nice not to download all the data just for a preview.

**Comment by serge-rider** [comment]
As far as I know bytea values are fetched along with other columns. This means all your huge binaries will be fetched and there is no way to omit them (in case of `select * from ...` query). So select itself will work slowly and I can't fix this.

Workaround: use custom SQL query which selects everything but bytea column.
Generally BLOB data type is designed for lazy value reading. I'm not suggesting you to change your database schema - just a note :)
