### ISSUE TITLE
Error Message can Increase vertical size of status bar

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1243]
I've noticed that when using a generic driver I setup for Cloudera hive I can get really long error messages when I get errors.

This has the side affect of making the status bar explode in size see screenshot.

<img width="809" alt="screen shot 2017-02-08 at 11 24 54 am" src="https://cloud.githubusercontent.com/assets/9246654/22753520/3cbbda4c-edf1-11e6-879f-f83b57e52dbc.png">

**Comment by r-richmond** [comment]
Note when this happens on result panes that I've generated via `control-\` i can just close the result window but for the main window I don't know to clear it without creating a new editor window.

Perhaps it sense to make it so that you can close the main result pane too?

**Comment by serge-rider** [comment]
I can't reproduce that (on Windows/Mac).
However I'll make status label single-line explicitly
