### ISSUE TITLE
Query elapsed time not shown anymore

### ISSUE THREAD

**Issue by kollerma** [serge-rider/dbeaver#1245]
My dbeaver has stopped showing the timings in the info box at the bottom of the query results panel (where the number of rows in the result is shown). I haven't found a setting that could re-enable this. Google doesn't help either. How can I get the timings back? Thanks.

I'm connecting to a PostgreSQL and am using the latest build 3.8.5 on Ubuntu.

**Comment by serge-rider** [comment]
Yep, it's a known issue, already fixed in 4.0. You can try EA version to validate (http://dbeaver.jkiss.org/files/ea/).

**Comment by kollerma** [comment]
Thanks for the quick response. Indeed, it works on version 4.0. Thanks!
