### ISSUE TITLE
Option to Change font color for result set

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#125]
Using the dark theme results in the result set being a little difficult to read.

Please add an option to change the color of the font in the result set.

Image below highlights a setting that changes the font size & font but not the color. (Also this setting applies to the header and I wouldn't want to change the header font color as it currently looks good)

![image](https://cloud.githubusercontent.com/assets/9246654/11883684/6d924420-a4c9-11e5-876c-beaa93963132.png)

**Comment by serge-rider** [comment]
It is pretty hard to customize this color. It is the default foreground color for all controls.
If I will set it to some particular predefined value (say, black) then all non-standard themes will be unusable. Users will have to fix them manually. Although I can prefocnfigure it for dark theme separately. But not for the rest.
Maybe changing odd cells background is a better solution?

**Comment by r-richmond** [comment]
If changing the color presents a high level of risk. Implementing #126 should be sufficient. As it would then allow the user to have complete control over the background of the result sets.

**Comment by serge-rider** [comment]
Solution is the same as for #126
