### ISSUE TITLE
Postgres jdbc-driver issue: dollar-quoted-string inside dollar-quoted anonymous code block

### ISSUE THREAD

**Issue by MarcoBorchert** [serge-rider/dbeaver#1250]
Using a dollar-quoted-string inside a dollar-quoted anonymous code block produces "Internal jdbc driver error java.lang.ArrayIndexOutOfBoundsException". Related to #900 ?

`DO LANGUAGE plpgsql 
$global$
BEGIN
	CREATE OR REPLACE FUNCTION test()
	  RETURNS integer AS
		$function$
		BEGIN
		    RETURN 1;
		END
		$function$
	LANGUAGE plpgsql;
END $global$;`

Replacing either$global$ or $function$ with $$ does not help. 
Replacing $function$ with a non-dollar-quoted string literal circumvents the issue but can become quite hard to read depending on the complexity of the function.

As with  ##900, this issue is not reproducible in pgAdmin.

**Comment by serge-rider** [comment]
DBeaver doesn't yet support multiple different dollar-quotes in a single statement.
Workaround: select whole query and execute it (with ctrl+enter).
