### ISSUE TITLE
Translations for DBeaver

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1253]
Does DBeaver support translations like translating it into German via a file to edit? If not, this could be added as a bigger feature request! Community based translations are great!

**Comment by serge-rider** [comment]
Yes, it does. Actually there is German translation already. It is not complete but still.
For instance this is German translation of core plugin: https://github.com/serge-rider/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.core/plugin_de.properties

Windows installer of version 4 will have German in the list of languages.
