### ISSUE TITLE
All download links in archive are giving me 3.6.2 version. 

### ISSUE THREAD

**Issue by nosnibor89** [serge-rider/dbeaver#1255]
I'm trying to download 3.8.5 and when I installed it, it told me there was an available update (ver. 3.8.5). When I go to 'About' it says I have ver. 3.6.2 installed. 
Anyway I tried to download ver 3.8.4 and the same happened.

Actually , I want to install EE version and I got CE.

**Comment by serge-rider** [comment]
Looks like bad installation.
How do you install new version? 
What is your os and distribution type (windows installer, zip, deb, rpm, dmg)?

**Comment by nosnibor89** [comment]
it is tar.gz.... I have ubuntu 16 - 64 bits.

________________________________
De: Serge Rider <notifications@github.com>
Enviado: domingo, 12 de febrero de 2017 05:23:00 p.m.
Para: serge-rider/dbeaver
Cc: Robinson Marquez; Author
Asunto: Re: [serge-rider/dbeaver] All download links in archive are giving me 3.6.2 version. (#1255)


Looks like bad installation.
How do you install new version?
What is your os and distribution type (windows installer, zip, deb, rpm, dmg)?

**Comment by serge-rider** [comment]
Make sure you removed previous version completely before extracting archive.
Version 3.6.2 doesn't even available for download. Means it is remains of your old installation.

**Comment by nosnibor89** [comment]
Still does not work... I ran `rm -R mydbeaver` also in the hidden .dbeaver dir.


Then I extracted the dbeaver 3.8.5 in a new dir and ran it from there...

________________________________
De: Serge Rider <notifications@github.com>
Enviado: domingo, 12 de febrero de 2017 06:08:06 p.m.
Para: serge-rider/dbeaver
Cc: Robinson Marquez; Author
Asunto: Re: [serge-rider/dbeaver] All download links in archive are giving me 3.6.2 version. (#1255)


Make sure you removed previous version completely before extracting archive.
Version 3.6.2 doesn't even available for download. Means it is remains of your old installation.

**Comment by serge-rider** [comment]
Well, this is a quite mysterious behavior. I believe there is another DBeaver binaries somewhere.
Run dbeaver and close it right after it will start.
Open `~/.dbeaver/.metadata/dbeaver-debug.log`. There are two lines
```
2017-02-05 23:32:09.689 - Install path: '<dbeaver-install-path>'
2017-02-05 23:32:09.692 - Instance path: '<workspace-path>'
```
Install path must be the same where you install DBeaver (extract gz archive).
Instance path must point on ~/.dbeaver.

If path strings are correct then you can:
- Check contents of `.eclipseproduct` file in DBeaver install dir. It must say `version=3.8.5`
- Delete everything in `~/.eclipse` directory. It keeps configuration for all Eclipse-based products you ever run.

I run out of other ideas for now..

Note: never delete `.dbeaver` folder - it keeps your connections, scripts, etc. Before upgrade you need to cleanup only previous dbeaver installation folder.

**Comment by nosnibor89** [comment]
This really helped me.


The log file has the install path as  '/usr/shared/XXX', and there was a CE edition I installed months ago....


Anyway I deleted that dir and the ~/.dbeaver, then I installed ver. 3.8.5 again...



Thanks bro!!

________________________________
De: Serge Rider <notifications@github.com>
Enviado: domingo, 12 de febrero de 2017 06:41:49 p.m.
Para: serge-rider/dbeaver
Cc: Robinson Marquez; Author
Asunto: Re: [serge-rider/dbeaver] All download links in archive are giving me 3.6.2 version. (#1255)


Well, this is a quite mysterious behavior. I believe there is another DBeaver binaries somewhere.
Run dbeaver and close it right after it will start.
Open ~/.dbeaver/.metadata/dbeaver-debug.log. There are two lines

2017-02-05 23:32:09.689 - Install path: '<dbeaver-install-path>'
2017-02-05 23:32:09.692 - Instance path: '<workspace-path>'


Install path must be the same where you install DBeaver (extract gz archive).
Instance path must point on ~/.dbeaver.

If path strings are correct then you can:

  *   Check contents of .eclipseproduct file in DBeaver install dir. It must say version=3.8.5
  *   Delete everything in ~/.eclipse directory. It keeps configuration for all Eclipse-based products you ever run.

I run out of other ideas for now..

Note: never delete .dbeaver folder - it keeps your connections, scripts, etc. Before upgrade you need to cleanup only previous dbeaver installation folder.

**Comment by serge-rider** [comment]
Good.

Yet another note - do NOT delete ~/.dbeaver folder ever. It is your data.

**Comment by nosnibor89** [comment]
Yeah I know, but I just wanted to solve this... Thank you so much anyway...

________________________________
De: Serge Rider <notifications@github.com>
Enviado: domingo, 12 de febrero de 2017 06:53:36 p.m.
Para: serge-rider/dbeaver
Cc: Robinson Marquez; Author
Asunto: Re: [serge-rider/dbeaver] All download links in archive are giving me 3.6.2 version. (#1255)


Good.

Yet another note - do NOT delete ~/.dbeaver folder ever. It is your data.
