### ISSUE TITLE
How could I show db2 "CHARACTER(16) FOR BIT DATA" columns as base64?

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1256]
Oracle RAW columns are shown in base64 but db2 "character for bit data" columns are shown as **garbled** characters. This column type conversion is suggested by http://www.sqlines.com/db2-to-oracle.

**Comment by serge-rider** [comment]
In DB2 you can encode binary data as hex.
E.g.
```sql
UPDATE EMPLOYEE
SET LASTNAME='NAME'
WHERE RID_BIT(EMPLOYEE)=x'0C00000000000000000085C403000000';
```
If you copy binary field with Advanced Copy action in native format then DBeaver will transform it to hex form automatically.
Also you can change binaries representation in preferences->Database->Result Sets->Binaries.

**Comment by yanOnGithub** [comment]
The base64 id is taken from the html source of a webapp,  the href attribute of a link. Can I trace the same record by base64 but not hex among 3 things: dbeaver, db2, webapp href?

**Comment by serge-rider** [comment]
As far as I know DB2 LUW doesn't have builtin base 64 decode functions.
So you need to use some 3rd party utility to decode base64 and then encode binary in hex format. Then you can use this string in SQL.

**Comment by yanOnGithub** [comment]
> Also you can change binaries representation in preferences->Database->Result Sets->Binaries.

This worked for the resultset of "select * from TB_HELLO" but not for the data pane of tables. Please see the screenshot below

![image](https://cloud.githubusercontent.com/assets/25423046/22911948/9d889e4a-f29d-11e6-8046-dfaf0de704d6.png)
