### ISSUE TITLE
where id=parseBase64('AAAAAQACgAAAAAAAAAAAAA==')

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1257]
select * from TB_HELLO where id=parseBase64('AAAAAQACgAAAAAAAAAAAAA==')

After seeing the table data in base64, I would like to turn it into a where clause. The database do not have the parseBase64() function. Are there any binary/string literal/escape sequence that I could use? The column type is "character for bit data" in db2 or "raw" in oracle. Thx.

**Comment by serge-rider** [comment]
See #1256 for binary columns representation details.
