### ISSUE TITLE
Add ability to create index with length.

### ISSUE THREAD

**Issue by RaSpirit** [serge-rider/dbeaver#1258]
Currently it is not possible to specify index length on creating or editing index. When I edit index I see length number in `extra` field, but it is not possible to set or change it via UI. 

It would be nice if this feature existed.

**Comment by RaSpirit** [comment]
@serge-rider Hi. 

Thnanks for the update, but I can't find where it's possible to adjust length of string column. Am I missing something?

I still see "Extra" property for index that is not editable for me.

**Comment by serge-rider** [comment]
Length is property of index column, not index itself:
![image](https://cloud.githubusercontent.com/assets/6398845/23407946/3d2a054e-fdd7-11e6-93f1-e9f70644307f.png)

**Comment by RaSpirit** [comment]
@serge-rider yes, I know.

Thanks for the image! It makes sense now.
