### ISSUE TITLE
Option to change even-row background color in result set.

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#126]
Feature Request

I think this was missed. It was discussed previously [here](http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1421&hilit=even+row)

specifically
>DBeaver doesn't set even rows background explicitly - idea was to use default widget background. It worked well in Eclipse 3.x but Eclipse 4.x has quite fancy css styling which doesn't work in this case. If I won't find a way to use default background for grid then I'll add explicit colors configuration.
 ~Serge

**Comment by serge-rider** [comment]
After all I'm still going to keep default values for foreground/background.
They are the same as for any other control so this config is theme-consistent.
So users can change only odd row background. I'll set it to pure-black by default.
