### ISSUE TITLE
RedShift error when trying to execute an SQL query

### ISSUE THREAD

**Issue by anesthesi** [serge-rider/dbeaver#1262]
Hello,
Today I started receiving the following error on ANY SQL I try to execute:
org.jkiss.dbeaver.ext.postgresql.model.PostgreGenericDataSource cannot be cast to org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource

I am using Ubuntu 16.04, DBeaver v3.8.4
I tried totally cleaning DBeaver from my system, reinstalling it (this time I installed v4.0), and had it re-download the RedShift JDBC driver - but all didn't help.

**Comment by serge-rider** [comment]
1. Please post error stacktrace (you can get it in Error Log view).
2. Make sure you use PostgreSQL driver (not PostgreSQL - Generic).

**Comment by anesthesi** [comment]
Hello,
I'm attaching the log. 
I'm not using PostgreSQL driver at all, I'm using the RedShift driver (tried both auto downloading through DBeaver, and also downloading it manually from Amazon and configuring DBeaver.. there are 3 version there, 4, 4.1, and 4.2. All of them return the same error)
[dbeaver-error.log.zip](https://github.com/serge-rider/dbeaver/files/773728/dbeaver-error.log.zip)

**Comment by serge-rider** [comment]
Error stacktrace is for 4.0 EA version. That's ok (although 3.8.4 should work ok).
Thanks for report.

**Comment by anesthesi** [comment]
Hello,
As I wrote I started to receive the errors on v3.8.4, then I cleaned it from the system and installed v4.0 but continued to receive the same error.
2 additions:
- it happens from my desktop computer only (ubuntu on vbox under windows)
- when using PostgreSQL driver as you suggested instead of Redshift (which I used previously) this work fine.
Best.

**Comment by serge-rider** [comment]
Maybe there is some other error in 3.8.4. But definitely not the same as in attached log file. If you still can reproduce it - please send 3.8.4 error log.

**Comment by anesthesi** [comment]
Hi,
I removed 4 and reinstalled 3.8.4 from the archives.  It doesn't reproduce.  Works fine now with the Redshift driver. Guess we can close this for now.  Thank you.

**Comment by serge-rider** [comment]
Ok, thanks for testing.
