### ISSUE TITLE
Cassandra keyspaces are duplicated when refreshing connection

### ISSUE THREAD

**Issue by loint** [serge-rider/dbeaver#1265]
When I tried to refresh a connection keyspaces are duplicated. I've already tried with MySQL and it works great, this issue is only with keyspaces in Cassandra.

<img width="255" alt="screen shot 2017-02-14 at 10 05 54 pm" src="https://cloud.githubusercontent.com/assets/5317864/22934503/cca190b0-f301-11e6-994a-eb0cf7856c88.png">

**Comment by serge-rider** [comment]
Duplicate of #1236
