### ISSUE TITLE
Remember coloring of the tables results.

### ISSUE THREAD

**Issue by loboaureo** [serge-rider/dbeaver#1267]
I usually work with a lot of log tables, that have a field with the result of an operation, normally filled with 'ERROR' or 'OK'.

For this querys is really useful the feature of coloring rows by these fields.
![screenshot_11](https://cloud.githubusercontent.com/assets/681482/22966922/843f7cac-f364-11e6-984c-a537dfbef8eb.png)

Is there any way to make these rules persistent so if i close dbeaver and open it tomorrow still applies them to my results?

I'm searching for something like the conditional format of excel.

Sorry for my English, regards.

**Comment by serge-rider** [comment]
Currently color settings are saved for tables but not for custom SQL queries.

**Comment by loboaureo** [comment]
Yes, but only last select.

I mean, i select an 'OK' from the 'Result' field and set it to green, after that i select a null from the same field and set it to yellow and at lasta i select an "ERROR" and set it to red.

I'll end with all registers colored with red, green and yellow.

When i close and open again the program, and execute the same "select * from table" it will only color the registers with an "ERROR" in the field result. I would like that remember all sets.

Thanks for your quick response.

**Comment by serge-rider** [comment]
Seems to be a bug. Multiple settings for the same column aren't saved (only the last setting is working).
Thanks for report.
