### ISSUE TITLE
Cannot have more than one top folder in database navigator

### ISSUE THREAD

**Issue by maurizio-lattuada** [serge-rider/dbeaver#1268]
dbeaver 3.8.5 running on macOS Sierra 10.12.3
It seems not possible to have more than one top folder in database navigator, see attachment 01.
<img width="325" alt="01" src="https://cloud.githubusercontent.com/assets/20639827/22977152/d28916ba-f38d-11e6-9010-b75320cacec3.png">

If I select the "docker" top folder, then I can create a new subfolder, see attachment 02.
<img width="321" alt="02" src="https://cloud.githubusercontent.com/assets/20639827/22977153/d289c254-f38d-11e6-9170-e6b2abe42237.png">

If I try to drag and drop the "subfolder" outside the "docker" folder, this is not possible.

**Comment by serge-rider** [comment]
There is no such limitation. You may have any number of top-level folders.
I can't reproduce problem with disabled "New folder" action. Maybe it is a glitch - try to create new folder using context menu.

Folders drag-n-drop isn't yet supported.

**Comment by maurizio-lattuada** [comment]
Thanks for the quick reply.
Got how it works in fact:
- if no entries are selected in the database navigator, then you cannot create a new folder (see screenshot 01 in my opening message), neither with the icon, nor with the context menu
- if you select an existing connection, then the "new folder" button is now active; if you click on it, then a new folder is created containing the selected existing connection. Here is possible to drag&drop that connection outside that new folder

Would it make sense to create a new folder even if no entries are selected in the database navigator?

**Comment by majkinetor** [comment]
This was confusing for me too, enough to have to look here.  DBeaver should let new folder creation even if no entries are selected and new folder item should appear when you right click _Connections_ in Projects.

**Comment by serge-rider** [comment]
Agreed
