### ISSUE TITLE
After edit connection, it get out of its folder.

### ISSUE THREAD

**Issue by acsdev** [serge-rider/dbeaver#1269]
I have many connections to organize, so I create an structure as you can see bellow.

- System 1
    - Enviromment 1
         - Connection 1
         **- Connection 2**
         - Connection 3
    - Enviromment 2
- System 2
    - Enviromment 1
    - Enviromment 2

If a change the configuration of "Connection 2" (for instance), at the moment that I click on "OK" buttom to save my changes, "Connection 2" will get out of folders structure and the organization will be like this:

- System 1
    - Enviromment 1
         - Connection 1
         - Connection 3
    - Enviromment 2
- System 2
    - Enviromment 1
    - Enviromment 2

- **Connection 2**

**Comment by serge-rider** [comment]
Duplicate of #1223
