### ISSUE TITLE
Support View/Table Source Code in Teradata

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#127]
Create a simple plugin/class (similar to the vertica extension) to support source for tables and views.

Syntax for teradata is

show table {schema}.{table_name}

show view {schema}.{view_name}

for reference the syntax for vertica was SELECT EXPORT_OBJECTS('','schema.table_name');

**Comment by serge-rider** [comment]
Main problem - I don't have access to a live instance of Teradata.

**Comment by r-richmond** [comment]
I'd be happy to test the implementation similar to the way we did for your implementation of the vertica plugin.

**Comment by codebling** [comment]
@serge-rider I have a Teradata server ready to launch, to which you can have complete access. Is this useful to you?

**Comment by serge-rider** [comment]
That'd be great, please write me on serge@jkiss.org

**Comment by r-richmond** [comment]
Can I make an inquiry into the status of this?

**Comment by michael-newsrx** [comment]
So, is my inability to click any of the run query buttons a bug or 
something else is going on?

(please see attached img)

**Comment by serge-rider** [comment]
Work on Taradata extension will begin after 3.6 release, currently there are too many tasks with higher priority.

**Comment by r-richmond** [comment]
Can I make another inquiry into the status of this?

**Comment by serge-rider** [comment]
Ok, I believe it'll be in 3.6.8.

**Comment by serge-rider** [comment]
You could try to build from source and check how it works.

**Comment by r-richmond** [comment]
@serge-rider confirmed that this feature works. Thanks for the addition!
