### ISSUE TITLE
Redis no data

### ISSUE THREAD

**Issue by ugate** [serge-rider/dbeaver#1270]
We're trying to connect to a vanilla `redis-windows` instance, but it doesn't look like any data shows up in the `Key list` for Redis(#132) connections using version `3.8.5`. We've verified that there is in fact data in the DB, but DBeaver never shows anything.

![capture](https://cloud.githubusercontent.com/assets/944948/22980626/08b0cbe6-f368-11e6-9764-8cababdc7f7b.PNG)

**Comment by serge-rider** [comment]
It is a bug in keys extraction.
If there are too few keys (and all of them can be read with one SCAN call) in a database then you will see empty list.
Will be fixed in 4.0. Thanks for report.

(you can see key list by executing `KEYS *` command).

**Comment by gencer** [comment]
@serge-rider, I tried **DBeaver EE 4.1** and cannot see any keys even If I execute `KEYS *`. Only one DB (`db1`) exists. Is there anything that I missed?

**Comment by gencer** [comment]
Note: Redis v3.2.x used on server side. Other GUIs can see the databases and keys properly.

**Comment by serge-rider** [comment]
Maybe this is a different issue. DBeaver uses Jedis 2.8.1 to work with Redis.
I'll test it with Redis 3.2 and Redis 4.0 in #1957.
Thanks for report

**Comment by serge-rider** [comment]
Support of all databases will be added in 4.2.
