### ISSUE TITLE
Open local databases automatically

### ISSUE THREAD

**Issue by vineetbansal** [serge-rider/dbeaver#1271]
Is there a way to configure DBeaver to open up locally stored sqlite databases, by doing the heavy-lifting of creating a (temporary) database connection (connection type determined by file extension, say), so that locally stored databases could be opened by right click->open with DBeaver? DBeaver is great tool, but our company deals with a lot of standalone Sqlite databases which get passed around, and having users create connections everytime they want to look inside a database may be prohibitively time consuming. If it's not currently possible, is there a theoretical workaround (even if takes quite a bit of programming, say creating a 'driver' executable that creates a new 'connection' in the data-sources xml file, and then opens up DBeaver with certain command line arguments) to accomplish this? 

Thanks!

**Comment by serge-rider** [comment]
Sound like a good feature.
I think generating datasources.xml + opening new DBeaver instance is too heavy solution.
This can be achieved with command line parameters for standard dbeaver executable.

Will think about that after 4.0 release.

**Comment by serge-rider** [comment]
This feature will be added in 4.0.7.
Command line arguments references: https://github.com/serge-rider/dbeaver/wiki/Command-Line

**Comment by vineetbansal** [comment]
Works great! For others who might be interested, this allows tweaking the registry a little bit to open up .db files in dbeaver automatically:

Add key HKEY_CLASSES_ROOT\.db -> sqlite3_db
Add key HKEY_CLASSES_ROOT\sqlite3_db\shell\Open with dbeaver\command -> C:\Program Files\DBeaver\dbeaver.exe -con "driver=sqlite|database=%1"

**Comment by Labevue** [comment]
out of your command line argument, I made the DBeaver.desktop for Ubuntu (and SQLite)
[dbeaver.desktop_example.txt](https://github.com/dbeaver/dbeaver/files/3837387/dbeaver.desktop_example.txt)
might help some one ....

**Comment by Darker** [comment]
I came here from google when wanting to do this on windows. Here's a batch that will open a file in DBeaver on double click as a new SQlite connection:

```
echo %~f1
@echo off
"C:\Users\<username>\AppData\Local\DBeaver\dbeaver.exe" -con "driver=sqlite|database=%~f1|name=%~n1"
```
