### ISSUE TITLE
export csv issue

### ISSUE THREAD

**Issue by qcktap23** [serge-rider/dbeaver#1272]
When I export the results to a csv file it truncates the zeros in the file. What do I need to change for this not to happen?

**Comment by serge-rider** [comment]
Please clarify. 
What does "truncates the zeros in the file" mean?

**Comment by qcktap23** [comment]
If a column has 021542155 it will take the zero off when the file is exported and only leave 21542155.

**Comment by serge-rider** [comment]
What type this column has?
DBeaver doesn't modify string values. Numeric values cannot have leading zeros.

**Comment by qcktap23** [comment]
They are numeric values and it needs the zero. How can I retain this zero when it is exported?

**Comment by serge-rider** [comment]
If you mean something like MySQL display length then it is not supported.

If you need numbers format with leading zeros then you can configure numbers formatting in preferences. But this affects all columns (you can't set different formats for different columns).

**Comment by MatthiasJust2** [comment]
Hi,
I also thought DBeaver has the error, but when you take a look in the csv-file with Notepad++ for example you'll see that the leading zeros already exists. It's EXCEL which convert it to a false numeric value.
