### ISSUE TITLE
output window hotkey

### ISSUE THREAD

**Issue by plgrm44** [serge-rider/dbeaver#1275]
Is there a way to bind a hotkey to show the output window?
It's need while debug a stored proc. It's main development process.

**Comment by serge-rider** [comment]
Do you mean SQL editor "Output" tab?

**Comment by plgrm44** [comment]
Yes, I do.

**Comment by serge-rider** [comment]
Agreed, this might be useful.

Default shortcut for Output tab toggle is `CTRL+ALT+O`. You can redefine it in preferences.
"Execution Log" tab also has shortcut (`CTRL+ALT+P`).

**Comment by plgrm44** [comment]
I've just tested it.
There is mini bug with output window.
if output window tab sheet isn't selected in tab control you shouldn't close it after "Show server output" command has been executed. I think it will be better switch to this tab. 
I must execute "Show server output"  twice after i've executed sql stored proc.

**Comment by serge-rider** [comment]
Good point

**Comment by plgrm44** [comment]
I've tested. It's exactly what i need. Thanks.
