### ISSUE TITLE
Cursor scrolls up when I hit ctrl+enter on a sql taller than the editor

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1276]
The sql is going to produce 50 downto 1. When I hit ctrl+enter near line 50, it goes back to line 1. I would like to stay at where I hit ctrl+enter.

![image](https://cloud.githubusercontent.com/assets/25423046/23011099/e12b1c64-f459-11e6-92df-382e7b4a2209.png)

**Comment by serge-rider** [comment]
It's a bug, thanks for report.
