### ISSUE TITLE
Hotkeys main menu

### ISSUE THREAD

**Issue by plgrm44** [serge-rider/dbeaver#1277]
There isn't hotkeys in main menu. It's very inconvenient. Many developers don't like a mouse.

**Comment by serge-rider** [comment]
Well, that's odd. DBeaver has hotkeys for most actions and these hotkeys are in the main menu.
What is your OS/window system?

**Comment by plgrm44** [comment]
I use Ubuntu 16.04.2 LTS and openjdk version "1.8.0_121".

**Comment by serge-rider** [comment]
Seems to be GTK + Eclipse issue (https://bugs.eclipse.org/bugs/show_bug.cgi?id=417601)
Not sure how to fix this. You could try 4.0 EA version (it is based on newer Eclipse version): http://dbeaver.jkiss.org/files/ea/

**Comment by plgrm44** [comment]
I've tried 4.0 EA. Hotkey menu works now with some strange behavior.
For example: I'm opening the main menu by <ALT> + <F> and then i MUST RELEASE <ALT> and press <J>(Open Project from file system). Other applications with main menu haven't such behavior. The devil is in the details.  :)
I think i will try to lanch dbeaver with java from Oracle later.

**Comment by serge-rider** [comment]
Ok, thanks for info. 
I hoped that 4.0 will have some improvements in this area. 
But in any case this is not DBeaver issue. 
Closing.

**Comment by plgrm44** [comment]
I've just tested old version dbeaver under oracle java as i promised before. I haven't seen any difference.
