### ISSUE TITLE
DBeaver(3.8.5) unable to connect to Cassandra 2.1.2 (NoHostAvailableException)

### ISSUE THREAD

**Issue by wildthing81** [serge-rider/dbeaver#1278]
My DBeaver Enterprise Edition(3.8.5) is unable to connect to a remote Cassandra store (2.1.2) on a Unix machine in the same network.It's throwing a **NoHostAvailableException- All host(s) tried for query failed**. The firewall is down on the Unix machine,the tcp port in cassandra.yaml is 9042 & I am using the same port in the DBeaver Connection configuration. I am also using SSH tunnel in the configuration to connect to the Unix machine.

**Comment by serge-rider** [comment]
Make sure you set correct connection parameters (Cassandra host name).

To test you can run `telnet <host> 9042` on you SSH target host.  Where `<host>` is the value you enter on Cassandra connection page.

Usually when you connect over SSH you should set Cassandra host name to "localhost" if it is on the same machine.

**Comment by wildthing81** [comment]
I am using "localhost" for Cassandra host name. On the SSH tunnel window, following are the Unix machine details
Host/IP: XX.XXX.XX.53
Port:22
Username: xxxxxp
Authentication method:Password
Password: xxxxxxxxx

However, when SSH tunnel is "checked",  I get the following error

**com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:45942 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:45942] **Channel has been closed**))**

I get a different error when SSH tunnel is "unchecked" with the machine details still present

**com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1:9042] **Cannot connect**))**

**Comment by wildthing81** [comment]
I was able to connect after changing the 'rpc_address' in cassandra.yaml to the host IP

**Comment by irfankhan457** [comment]
<dependency>
    <groupId>org.apache.cassandra</groupId>
    <artifactId>cassandra-all</artifactId>
    <version>2.1.6</version>
</dependency>


use abov
