### ISSUE TITLE
Can't Connect to MS SQL Server Through Mac

### ISSUE THREAD

**Issue by Ketan-Kulkarni** [serge-rider/dbeaver#1279]
Hi - 
I'm trying to connect to a MS SQL Server through a macbook (EL Capitan) using DBeaver Community Edition v 3.8.5 
Our enterprise databases have windows authentication, which is pretty common

I've tried both drivers, but I can't seem to connect to SQL Server using DBeaver. Any ideas?

**Comment by serge-rider** [comment]
What exactly error happens?
BTW check this topic: #1109

**Comment by Ketan-Kulkarni** [comment]
I checked the topic. I can't even get to those levels of error. 

Here are the error 
![image](https://cloud.githubusercontent.com/assets/25830666/23070064/7112887c-f4ef-11e6-909c-d201b6d12ac8.png)

I've also got invalid user, found "null" etc. 

Keep in mind I can connect to the same SQL Server through DBeaver from Windows, through Talend and through other query tools. just not from macbook

**Comment by serge-rider** [comment]
In order to use windows authentication JDBC driver uses native Windows libraries (dlls). Which are obviouly can't be used on Mac. So, I don't think that native windows authentication can be used in your case.

But you could try to use you domain credentials in login/password fields.

**Comment by Ketan-Kulkarni** [comment]
That didn't work either...

**Comment by Ketan-Kulkarni** [comment]
Actually, once i added following domain name and useNTLMv2=true after the server name, I was able to connect.

**Comment by serge-rider** [comment]
Good.
Thanks for info.

**Comment by matpol88** [comment]
> Actually, once i added following domain name and useNTLMv2=true after the server name, I was able to connect.

Can you please clarify? Where did you add "userNTLMv2=true"?

**Comment by goxine** [comment]
It's been a while ago, but I'm just putting this in there for people wondering the same.  

> Can you please clarify? Where did you add "userNTLMv2=true"?
In your connection setting page, click on the Driver properties tab, it's next to the general tab. Once you do, you'll see a list of properties including userNTLMv2 and domain, you can edit the values there.

**Comment by Gaelle00** [comment]
It's been a while ago, but I'm just putting this in there for people wondering the same.

    >Can you please clarify? Where did you add "userNTLMv2=true"?<

In your connection setting page, click on the Driver properties tab, it's next to the general tab. Once you do, you'll see a list of properties including userNTLMv2 and domain, you can edit the values there.

**Comment by MichaelTuchman** [comment]
The list of properties does not include userNTLMv2.  In my version, the geography of the features seems different than what I saw described earlier.

![Screen Shot 2020-03-18 at 5 35 49 PM](https://user-images.githubusercontent.com/5167217/77009959-3d44da00-693f-11ea-99ba-a612b7ce7606.png)

**Comment by saitejal** [comment]
I was able to connect by choosing NTLM in the auth section. I didn't find NTLMv2 option. Perhaps the server I am connecting to accepts NTLM auth.

If NTLM option does not work out, check out this answer on [SO](https://stackoverflow.com/a/37839177/5028870), there is an alterative driver that can be used with NTLMv2 option in the connection string.

![image](https://user-images.githubusercontent.com/11802394/95923750-061a9800-0d6b-11eb-9a92-1aa85f9dd867.png)
