### ISSUE TITLE
hsqldb is still locked after disconnect

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1280]
The lock files are not removed after clicking disconnect on the menu.

![20170217t135458_hp-radw04](https://cloud.githubusercontent.com/assets/25423046/23054110/e1cff5da-f518-11e6-84a7-41db9fdf1f29.png)
![20170217t135524_hp-radw04](https://cloud.githubusercontent.com/assets/25423046/23054111/e58ba548-f518-11e6-8083-482725f470ef.png)

**Comment by serge-rider** [comment]
Yep, it is a bug in driver parameters. As a result database doesn't shutdown in embedded mode.
Thanks for report.

**Comment by yanOnGithub** [comment]
Can I do any configuration in Driver Properties to make it shutdown properly? Or do I need to build the latest version for a fix?

**Comment by serge-rider** [comment]
Yes, you can add connection property "shutdown=true" in driver editor. And remove "Shutdown parameter" property in "Adv. parameters".

Or you can wait for Monday (when version 4 release is planned).
