### ISSUE TITLE
"Choose SQL script" window background is black

### ISSUE THREAD

**Issue by kerhong** [serge-rider/dbeaver#1281]
For the window that is opened with "SQL Editor (F3)" the background is completely dark for light themes.

OS: Ubuntu 16.04
Version 3.8.5 (tested also with 3.8.3) 64bit
Theme: GTK (tested also with Classic)
Color and Font theme: Default (tested also with Classic)

![image](https://cloud.githubusercontent.com/assets/648861/23067589/af99720c-f528-11e6-9a09-fad1cebf3679.png)

Let me know if you require more data.

**Comment by plgrm44** [comment]
I've got the same effect.

**Comment by serge-rider** [comment]
Yeah, I saw it on some Linux machines (these colors depend on local UI theme settings).
Will fix that in 4.0, thanks for noticing.

**Comment by plgrm44** [comment]
I use KDE. There is an option "Apply colors to non-QT application" in "System Settings->Color". If it's enabled i can't see tooltip text. The option is enabled by default in KDE.
