### ISSUE TITLE
Virus reported in installer

### ISSUE THREAD

**Issue by p-ja** [serge-rider/dbeaver#1282]
The installation file available under
http://dbeaver.jkiss.org/files/dbeaver-ce-latest-x86_64-setup.exe

is reported as containing a virus

https://www.virustotal.com/en/file/ceca27c7ac19b8a7e4604f8637240ae4943c3596c516c6976b691f4aba360f52/analysis/

Please check. Thanks :)

**Comment by serge-rider** [comment]
Yet another false positive check. 1 of 58, not that bad ;)
Do you have some local antivirus which blocks installation?

**Comment by p-ja** [comment]
Thanks for your response :)
McAfee WebAdivsor plugin in Firefox blocks the download. I downloaded the file with another browser and checked with virustotal. I'll try installation once the file is "clean".

**Comment by serge-rider** [comment]
Version 4.0 was just released. Try it.
Although I can't promise that some other false-positive check will happen. Nowadays there are too many anti-viruses and sometimes they just checks for some magic sequences of bytes. So this is pretty random.

I'll contact with antivirus vendors if it will fail again (I did this a couple of times if the past - they can fix their checkers).

**Comment by bobtheowl** [comment]
Looks like Avast is showing a false positive as well on dbeaver.exe instead of the installer.

![dbeaver-avast](https://cloud.githubusercontent.com/assets/8972863/23126323/23c0e83c-f744-11e6-9e12-1e8084cd347a.png)

Clicking "I trust this file" didn't seem to do any good, but I was able to exclude the directory from checks so I can still use it.

**Comment by serge-rider** [comment]
Well, it doesn't say positive, it just checks the file. Probably this issue will be resolved in a day or so.

**Comment by dseitz** [comment]
@bobtheowl I had the same error. You have to open the Avast settings and in the section "General" under "activate CyberCapture" select "execute suspicious files" (I translated the names from german, so they may be different). After that Avast will still stop the execution of DBeaver and show the popup, but under the details of the popup is an option to execute DBeaver.

I don't know what "I trust this file" does, but I think it just sends a message to the Avast Virus Lab saying that you think the file is OK.

**Comment by serge-rider** [comment]
Day passed and now no anti-viruses find anything suspicious: https://www.virustotal.com/en/file/cea93714ffc679a0696ffbdace663819097d3f34a877cb4a0ca2d0acbbce5af4/analysis/
Closing.
