### ISSUE TITLE
Button's Commit and Rollback are disabled after PG SQL error

### ISSUE THREAD

**Issue by ricardofpu** [serge-rider/dbeaver#1283]
For production connections, i can choose auto-commit or manual-commit, but button's Commit and Rollback are disabled and i can't control manual-commit.

**Comment by serge-rider** [comment]
Since version 4.x commit/rollback become enabled only if you will perform some transaction operation (INSERT/DELETE/UPDATE, DDL, etc).

If you doing such operation and Commit/Rollback are still disabled the it is a bug. Please provide more details.

**Comment by ricardofpu** [comment]
All right, I did not notice this. But if I make a wrong select and fix the select and try to run again, the following error is displayed:

SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block

So in the previous version I could use the rollback button and normally execute the select, but now it is not possible. Maybe it's not a bug but it's a drawback.

**Comment by serge-rider** [comment]
It is a bug. Or, a kind of miss-function.
This is PostgreSQL specific. Although SELECT query doesn't modify transaction state it is still transactional.
Will be fixed in the hotfix version, thanks for report.

Workaround: execute COMMIT/ROLLBACK query manually (in SQL editor).
