### ISSUE TITLE
German localization is incomplete

### ISSUE THREAD

**Issue by Marcusg562** [serge-rider/dbeaver#1285]
The Langueges are mixed within Version 4

For example - installed in English and you get a german Taskbar

**Comment by Marcusg562** [comment]
![2017-02-20 14_56_44-dbeaver - general - _dbfors-system 10 90 2 15_ script-8](https://cloud.githubusercontent.com/assets/105149/23127853/dafb9df2-f77c-11e6-85b4-47fabd9175b9.png)

**Comment by serge-rider** [comment]
I assume that you have German locale on local machine. German localization is far from complete.

If you want to use English version you need to choose English language in Windows installer. Otherwise you can run dbeaver with command line parameter `-nl en`.
