### ISSUE TITLE
DBeaver 4.x requires Java 8

### ISSUE THREAD

**Issue by juan88** [serge-rider/dbeaver#1286]
Hello!

I've been using 3.8.5 for a couple of days when I recently downloaded version 4.

Splash screen is displayed but DBeaver displays an error popup and closes. I attached the output of the configuration log. From what I can see the java version (v. "1.7.0_121") should be fine, but I couldn't figure out how to install those other dependencies that appear in the log. 

Any ideas? Thanks!
[1487599309950.txt](https://github.com/serge-rider/dbeaver/files/787653/1487599309950.txt)

**Comment by serge-rider** [comment]
DBeaver 4.x requires Java 8 (as said in release notes).
This requirement comes from Eclipse 4.6 platform requirements. DBeaver itself is still Java7 based.

**Comment by juan88** [comment]
Thanks for the reply.

I checked in the home page and it is ok what you say but I think that in the download page (to where I landed in the first place) it still says that it requieres 1.7 and not java 8. It might be out of date?

Thanks!

**Comment by serge-rider** [comment]
Yep, it is outdated. 
I'll fix it now, thanks for reminding.
