### ISSUE TITLE
The Solaris version is Linux instead

### ISSUE THREAD

**Issue by marcheschi** [serge-rider/dbeaver#1288]
It seems that the Solaris version downloadable from the site
http://dbeaver.jkiss.org/files/dbeaver-ce-latest-solaris.gtk.x86_64.tar.gz

does not contain the Solaris version , but contains the linux one.

paolo@xstreamos:~bin/dbeaver$ cat dbeaver.ini
-startup
plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.401.v20161122-1740
-showsplash
--launcher.GTK_version

paolo@xstreamos:~bin/dbeaver$ ls plugins/|grep -i solaris
paolo@xstreamos:~bin/dbeaver$ ls plugins/|grep -i linux
org.eclipse.core.filesystem.linux.x86_64_1.2.200.v20140124-1940.jar
org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.401.v20161122-1740
org.eclipse.swt.gtk.linux.x86_64_3.105.2.v20161122-0613.jar
paolo@xstreamos:~bin/dbeaver$ 
Thank you
Paolo

**Comment by serge-rider** [comment]
Thanks for report. It is a bug in 4.0 build scripts.
