### ISSUE TITLE
DB2 connection error in 4.0.0

### ISSUE THREAD

**Issue by ffblanch** [serge-rider/dbeaver#1291]
All my db2 connections (z/OS) give me this error. Working fine on prevuis version. 
`org.jkiss.dbeaver.DBException: Can't create generic meta model instance 'null'`

Driver name : DB2 / DB2 z/OS

_No problem on AXI with this driver (DB2 / DB2 LUW 8.x)_

**Comment by serge-rider** [comment]
This is a bug in recent version. Affects only DB2 for z/OS.
Will be fixed in hotfix version later on this week.
