### ISSUE TITLE
Procedure List doesn't load when connected with Sybase

### ISSUE THREAD

**Issue by girishpadia** [serge-rider/dbeaver#1295]
I have thousands of procedure in my Sybase Database. I cannot load the list of the procedures when I follow the steps as below.
1) Connect to Sybase Database.
2) Select Database
3) Select Username
4) Click on "Procedures"

It doesn't load procedures and DBEAVER kills after few minutes.

**Comment by serge-rider** [comment]
Check error/debug log for any related errors (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
