### ISSUE TITLE
ODBC connection failed : Version 4.0.0

### ISSUE THREAD

**Issue by Wespontin** [serge-rider/dbeaver#1296]
Hello,
Since the last update, i can't connect with ODBC.
![image](https://cloud.githubusercontent.com/assets/21580607/23155742/32564bc8-f814-11e6-9ae1-827be7b04f2e.png)
Thanks for help

**Comment by dalbocha** [comment]
I'm having the same error while connecting to Oracle DB with DBeaver application

**Comment by Wespontin** [comment]
I put the update 4.0.1 but the problem always exists

**Comment by serge-rider** [comment]
Can't reproduce.
Please post error stacktrace (you can get it in Error Log view)

**Comment by ferrazp** [comment]
4.0.1 works fine, i had oracle issue too but with 4.0.1 no more. Sorry for my bad english

**Comment by serge-rider** [comment]
I think this is duplicate of #1312.
Looks like some problems with particular ODBC driver..
