### ISSUE TITLE
Links under dark theme are not readable

### ISSUE THREAD

**Issue by gaydenko** [serge-rider/dbeaver#1302]
4.0.0 is in use. Under dark theme links are not visible - see attached image. Preferences fonts tuning doesn't help. These UI elements are not connected to listed fonts. The same almost not visible look takes place for, say, view `Owner`field value.
![d01](https://cloud.githubusercontent.com/assets/3740016/23174806/9d7bc4d2-f86e-11e6-9b73-a417eaef0ecd.png)

**Comment by serge-rider** [comment]
Yes, link color must be configurable. It is a bug.

**Comment by gaydenko** [comment]
4.0.1 hasn't got fix for me - links foreground color is still the same and is not connected with some font from "Colors and Fonts" Preferences list.

**Comment by serge-rider** [comment]
You can configure it by setting "Hyperlink text color":
![image](https://cloud.githubusercontent.com/assets/6398845/23207841/c59eb100-f903-11e6-86eb-6306243be658.png)

**Comment by gaydenko** [comment]
Yes, I have already tried (and I have scanned *all* fonts in the tree), but this color is not respected.

**Comment by serge-rider** [comment]
That's weird. This is definitely works for me:
![image](https://cloud.githubusercontent.com/assets/6398845/23210945/b9765b96-f910-11e6-8d55-29025b7655b0.png)

I've just re-downloaded 4.0.1 binaries to be 100% sure - this fix was included in 4.0.1.

Please re-check that you upgraded version correctly (check about box and/or logs).

If this won't help - what is your OS/window system?

**Comment by gaydenko** [comment]
Yes, both splash screen and about dialog show 4.0.1. I use (Arch Linux based) Manjaro Linux and KDE.

**Comment by gaydenko** [comment]
I have used AUR ( https://aur.archlinux.org/ ) package. To separate issues I have tried the official tar.gz distribution, and - yes, the issue has gone. Thanks!

Will escalate the issue to the AUR packager.
