### ISSUE TITLE
Version 4.0.0 detects as Trojan in 360 total security (free version).

### ISSUE THREAD

**Issue by muhin** [serge-rider/dbeaver#1304]
All other earlier versions are OK but 4.0.0 detects as Trojan and can't install the new version.

**Comment by serge-rider** [comment]
This is false positive check.
Thanks for report, I'll talk with 360 support.

**Comment by serge-rider** [comment]
I wrote to their support but I can't say when they will fix this.

Check status of 4.0.1:
https://www.virustotal.com/en/file/cea93714ffc679a0696ffbdace663819097d3f34a877cb4a0ca2d0acbbce5af4/analysis/1487748681/

Qihoo-360 is the only guy who doesn't like something.

**Comment by serge-rider** [comment]
Workaround: download DBeaver in zip archive.

**Comment by serge-rider** [comment]
Seems to be resolved.
https://www.virustotal.com/en/file/cea93714ffc679a0696ffbdace663819097d3f34a877cb4a0ca2d0acbbce5af4/analysis/

**Comment by muhin** [comment]
Thanks...
