### ISSUE TITLE
Version 4.0.0 does not run on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by jkwakman** [serge-rider/dbeaver#1307]
After a succesfull install of the dbeaver-ce_4.0.0_amd64.deb file i get the following error in the log file:

 Application "org.jkiss.dbeaver.core.application.standalone" could not be found in the registry. 

I've read that it could be a java version issue. My java version is 1.7.0_80.

When i reinstall version 3.8.5 everythings works as expected.

**Comment by serge-rider** [comment]
DBeaver 4.x requires Java 8: #1286
