### ISSUE TITLE
@productName@ is displayed instead of DBeaver on Mac

### ISSUE THREAD

**Issue by orbanbalage** [serge-rider/dbeaver#1308]
![image](https://cloud.githubusercontent.com/assets/285574/23202831/301ed38a-f8e0-11e6-80b2-9482845e920a.png)

Noticed this on 4.0.0 and 4.0.1

**Comment by dlee3** [comment]
I have this problem too.

**Comment by serge-rider** [comment]
Will be fixed in 4.0.2

**Comment by stewartbryson** [comment]
You can correct temporarily updating the Info.plist file inside the package. There are 2 references... change both of them.
