### ISSUE TITLE
ODBC connection failed : Version 4.0.1

### ISSUE THREAD

**Issue by Wespontin** [serge-rider/dbeaver#1312]
I have always the same problème:
![image](https://cloud.githubusercontent.com/assets/21580607/23206250/32cf4198-f8ed-11e6-9414-de1d7736f7e1.png)
Thanks for help

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view)

**Comment by Wespontin** [comment]
The ErrorLog view is empty after the error
![image](https://cloud.githubusercontent.com/assets/21580607/23207627/3e442520-f8f2-11e6-9c65-d8c579ef8835.png)

**Comment by serge-rider** [comment]
Ok. 
Then check debug log for any related errors: https://github.com/serge-rider/dbeaver/wiki/Log-files

BTW what ODBC driver do you use?

**Comment by Wespontin** [comment]
Here the log file : 
[logfile.txt](https://github.com/serge-rider/dbeaver/files/793068/logfile.txt)
And for the drivers:
![image](https://cloud.githubusercontent.com/assets/21580607/23208017/ba91ba2e-f8f3-11e6-9379-09b9a28d7263.png)

**Comment by serge-rider** [comment]
This seems to be native ODBC driver issue. Something like this: https://community.oracle.com/thread/1344007

Make sure you use correct driver version (e.g. 64-bit ODBC driver can be used onyl from 64 bit DBeaver/Java, 32-bit driver only from 32-bit DBeaver).

**Comment by Wespontin** [comment]
All my connexion in ODBC worked before the upgrade to version 4.0.0 in my plugin in Eclipse.
I will try to make downgrade in my Eclipse...

**Comment by Wespontin** [comment]
I've just downgrade in my Eclipse to version 3.8.5 and it works fine...

**Comment by serge-rider** [comment]
Ok. What ODBC driver (what database) do you use?

**Comment by Wespontin** [comment]
Here the ODBC driver:
![image](https://cloud.githubusercontent.com/assets/21580607/23252389/f6db5644-f9b0-11e6-8019-7eb4c792969f.png)

**Comment by serge-rider** [comment]
Ok, Version 4.0 doesn't change anything ODBC specific but maybe problem is in changed preferences defaults or in changed connection initialization procedure.

What happens if you open connection editor (of your ODBC connection) and press "Test connection"? Disconnect from all databases to make this test clean.

**Comment by Wespontin** [comment]
Do i have make this in newer version  of 3.8.5?
I am in a developpement phase and i can't upgrade for this moment, i need your great product in a good state.

**Comment by serge-rider** [comment]
In new version, as I understand 3.8.5 work fine. I just can't reproduce this problem so I need any hints.

Do it when you will have free time, thanks.

**Comment by Wespontin** [comment]
I've just installed the last version. 
When i make a new ODBC connexion (and delete the old connexion), it works fine.
Thanks

**Comment by serge-rider** [comment]
Thanks for info.
