### ISSUE TITLE
Active database change is not supported.

### ISSUE THREAD

**Issue by phanthetien** [serge-rider/dbeaver#1313]
I'm using DBeaver Community 4.0.1. I have a problem when I want to change database as file attachment.
"org.jkiss.dbeaver.DBException: Active database change is not supported.

My environment:
Elementary Loki x86_64. Driver type mysql 3.x

![dbeaver](https://cloud.githubusercontent.com/assets/13130351/23206087/ea7c6cea-f91e-11e6-8ea2-36203957a5a0.png)

I wonder that this is a bug? What will help me to fix this.
Thank for any support.

**Comment by serge-rider** [comment]
Yes, MySQL 3.x driver doesn't support that. 
I'll add extra config so it will support active schema get/set.

Workaround: use default MySQL driver if possible.

**Comment by phanthetien** [comment]
Nice! I just changed to mysql driver. Nothing problem here.
Thank you so much for your work around.

**Comment by 7--** [comment]
This affects Informix DBs as well. There should be a button to close database and continue

**Comment by serge-rider** [comment]
Active db change for Informix was added in  #1932.
It should present in 4.2. Please check

**Comment by MichaelPablo13** [comment]
Hello, I got the same problem with the latest version of dbeaver, and I can't change active database. My DB is a Postgres. Someone knows what is going on? 
![image](https://user-images.githubusercontent.com/9862172/45161700-d4fe2f80-b1c2-11e8-85f4-21ce96e3b115.png)
My version:
![image](https://user-images.githubusercontent.com/9862172/45161791-feb75680-b1c2-11e8-9721-444a444f8ae1.png)
 There are only one db but I have three schemas inside the db, and I know that in previous versions I could exchange between the schemas inside the db:
![image](https://user-images.githubusercontent.com/9862172/45161864-1db5e880-b1c3-11e8-9df6-11ca199dd292.png)
Those are my schemas:
![image](https://user-images.githubusercontent.com/9862172/45162069-8a30e780-b1c3-11e8-8c20-be91fa8bd6c1.png)
Hope we can find a solution.

Regards.

**Comment by serge-rider** [comment]
@MichaelPablo13 I can't reproduce this. 
By some reason your (the only) database isn't recognized as active database.

Could you say what connection settings do you use? Do you have "compose" in Database field? Do you set any driver properties?

**Comment by MichaelPablo13** [comment]
@serge-rider O saw om drover properties that in PGDBNAME there is a compose, but I am not sure if that's the information you want about it. Regarding the driver is a PostgreSQL JDBC Driver.

![image](https://user-images.githubusercontent.com/9862172/45178499-3a1a4b00-b1ec-11e8-808a-1babe78f2eef.png)

**Comment by serge-rider** [comment]
I mean main connection page, field database.
![image](https://user-images.githubusercontent.com/6398845/45178599-d4938200-b21e-11e8-9d2d-ccf7de5da579.png)

**Comment by MichaelPablo13** [comment]
![image](https://user-images.githubusercontent.com/9862172/45178848-3cc97000-b1ed-11e8-89bf-61291afa8e9e.png)
I have compose as my database.

**Comment by serge-rider** [comment]
Ok, thanks.
Could you check how it works in 5.2 EA? (https://dbeaver.io/files/ea/)

**Comment by MichaelPablo13** [comment]
Thank you for your suggestion @serge-rider but It didn't go well after I have installed this version in my machine. I just got the same error as before.

**Comment by serge-rider** [comment]
Ah, I see. You are using PostgreSQL Generic driver (it was renamed to PostgreSQL Legacy recently). Generic driver doesn't support database switch.

You need to use default PostgreSQL driver (with elephant icon).

**Comment by MichaelPablo13** [comment]
@serge-rider Thank you for your help. You were right about the drive, the solution worked like a charm.

![image](https://user-images.githubusercontent.com/9862172/45180513-04786080-b1f2-11e8-85a9-e56d87041737.png)

Cheers!
