### ISSUE TITLE
[Feature Request]  Oracle package functions or procedures auto-save during  compilation

### ISSUE THREAD

**Issue by ceyhunnabiyev** [serge-rider/dbeaver#1314]
Compiling package  indicates previous changes. I have mistakes on package editor, but when I click on " compile the package " it gives me  message like 'package compiled successfully'. I must  close the package editor window for compilation package indicating current changes. I think this is not correct way for compilation 

Can you add   Oracle package functions or procedures auto-save during  compilation??

**Comment by yevon** [comment]
Yes, in Oracle we are used to compile & save together always, not separately. But in current version of dbeaver, if you persist changes it compiles it also, you could use this isn't it? You can also hide persist confirmation messages in preferences.

**Comment by ceyhunnabiyev** [comment]
@serge-rider, Thanks a lot for this!!!
