### ISSUE TITLE
Sidebar icons disappear on startup

### ISSUE THREAD

**Issue by trivago-izelenov** [serge-rider/dbeaver#1315]
the sidebar icons disappear on application launch for:
* Project
* Restore
* Database Navigator
* Projects

![image](https://cloud.githubusercontent.com/assets/12135320/23207450/a50b0626-f8f1-11e6-8a08-ce4a0aba5a44.png)

when mouse hover them, they appear again 

![image](https://cloud.githubusercontent.com/assets/12135320/23207491/bf974b12-f8f1-11e6-92d6-72ebbb17fbff.png)

**Comment by serge-rider** [comment]
This is a glitch in the recent Eclipse platform (4.6.2). I can't fix this but most likely this will be fixed in the next minor Eclipse platform update. DBeaver will has this fix once this will happen.
