### ISSUE TITLE
Package editor format issues

### ISSUE THREAD

**Issue by ceyhunnabiyev** [serge-rider/dbeaver#1316]
**1. [Suggestion]** 
Formatted package functions like this: 
```
CREATE OR REPLACE PACKAGE BODY  package_name AS FUNCTION  function1_name.....
FUNCTION  function2_name .......
FUNCTION  function3_name.......
........
```
Suggestion is like this:
```
CREATE OR REPLACE PACKAGE BODY  package_name 
AS | IS 

FUNCTION  function1_name.....

FUNCTION  function2_name.......

FUNCTION  function3_name.......
.......
```

**2. [Compilation Error]**
`query_text = '........WHERE lower(name) LIKE ''%'   '; ` (Compiled  successfully)

When I format editor:
`query_text = '........WHERE lower(name) LIKE ' '%'   '; ` (Compilation error due to space between quotes before %'   ')

**Comment by serge-rider** [comment]
I don't think that client-side auto-formatting makes sense.

Compilation errors refer to server-side source code, thus client and server code must be the same.
Moreover different users prefer different code style.

I'd suggest to format package body manually (or with ctrl+alt+f).

**Comment by ceyhunnabiyev** [comment]
@serge-rider , Sorry for late answer, you say that format package  body manually (or with ctrl+alt+f)) , but this is impossible.  When I  format package  body with  ctrl+alt+f, it shows me message like Compilation Error which I noted reason above..

**Comment by serge-rider** [comment]
Ah, I missed that.
Issue with quoted strings formatting was fixed recently. Try 4.0.4 version.

**Comment by ceyhunnabiyev** [comment]
Yes, I tried and saw this  right now.  Thanks for great work, @serge-rider !!!
