### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by verdantyang** [serge-rider/dbeaver#132]
DBeaver is a cool tool, which I use it as my client of MySQL, MongoDB, SQLite. Have you ever planned to support Redis in future versions ?

**Comment by danieleteti** [comment]
+1 for Redis

**Comment by serge-rider** [comment]
I'd wish to add Redis support asap, but after I started to do it I realized that Redis doesn't support any hierarchical keys browsing. I can search by substring (for instance if keys are divided by ":" character) by I can't read "levels". I have to read all keys to build hierarchy. In case of big databases (almost all Redis databases are really big - at least millions of keys, most of real-life databases have billions and more) it becomes a stopper issue.
If anyone have any ideas on mind - please tell me.

**Comment by danieleteti** [comment]
Redis keys are flat, so some DB tools uses SCAN commando to incremental fetching keys. So you have something like:
Show 50 keys (first returned by SCAN)
Dbsize (num of keys)
A button "Fetch Next Page"
An edit box to start a searching by pattern (as SCAN or keys commands)

**Comment by serge-rider** [comment]
Yes, it is possible to make keys scrolling. + keys search by substring.
I can make something like a single "table" with columns "key" and "value". Each Redis key is a row. Table filter may work as a key filter. Also SQL editor may execute standard Redis commands.

I'm still not sure that it makes sense. It won't be much better than the standard redis-cli..

**Comment by danieleteti** [comment]
A good plus over the redis-cli may be a "value vidualizer".
If the selected key is a strong, then the visualizer show a string, if is a set the visualizer show a list of strings, if is an hash the visualizer show a key/value lista and so on. Also the TTL for each key may be very useful and a client info always accessible and other meta information.

My 2cent

**Comment by serge-rider** [comment]
I have a couple of ideas how to manage big maps in UI.
Will try them after 3.6 release.

**Comment by alvarocantador** [comment]
+ 1 for Redis

**Comment by sachinwalia2k8** [comment]
+1 for Redis. At present I am using Redis Desktop Manager which is good but I'd love to use single tool for all thing DB.

**Comment by ugate** [comment]
+1 for Redis support. Also using Redis Desktop Manager, but it's nothing like a dbeaver one-stop-shop!

**Comment by serge-rider** [comment]
Redis extension development will begin after 3.6.3 release. 
Hopefully will be released in 3.7.

**Comment by danieleteti** [comment]
Great!!

DT
Il 23 mar 2016 10:52 PM, "Serge Rider" <notifications@github.com> ha
scritto:

**Comment by ralic** [comment]
Besides Redis Desktop Manager, I believe some of Spring's API may be also useful to integrate redis support.
https://github.com/spring-projects/spring-data-redis
https://github.com/uglide/RedisDesktopManager

**Comment by serge-rider** [comment]
DBeaver uses Jedis for Redis interactions. Seems good enough so far.

I wondering about SQL editor and Redis scripting.
Simplest solution (which is present in DBeaver 3.6.6) is to execute any SQL query as a LUA script.
But this solution doesn't look very convenient (no access to Redis commands).
Another approach is to simulate redis-cli behavior (but with structured results). But it means that the only way to execute LUA scripts is to use eval command, which is also not very convenient.
Yet another way is to emulate SQL queries (like SELECT FROM KEY/DELETE FROM KEY, etc).
Maybe the best solution would be to somehow combine all these ways.

If anybody has any thoughts about that - please share.

**Comment by taolive** [comment]
How to connect with the password redis？

**Comment by taolive** [comment]
public RedisDataSource(DBRProgressMonitor monitor, @NotNull DBPDataSourceContainer container) throws DBCException { this.container = container;

    DBPConnectionConfiguration connectionInfo = container.getActualConnectionConfiguration();
    String hostName = connectionInfo.getHostName();
    String hostPort = connectionInfo.getHostPort();

    int socketTimeout = 100000;

    JedisPoolConfig poolConfig = new JedisPoolConfig();
    this.jedisPool = new JedisPool(poolConfig, hostName, Integer.parseInt(hostPort), socketTimeout);
    this.executionContext = new RedisExecutionContext(this, "Main Redis Connection");
    this.executionContext.connect(monitor); }


JedisPool  don't have a password ？？？？

**Comment by serge-rider** [comment]
It does. But DBeaver 3.6.8 doesn't support Redis password.
You can get EA version and check how it works (http://dbeaver.jkiss.org/files/ea/).

**Comment by taolive** [comment]
How to query redis in DBeaver?

**Comment by serge-rider** [comment]
Redis extension is not yet ready, it is a kind of alpha version.
However you can browse keys (as plain list or as a hierarchy) and execute LUA scripts in SQL editor.

**Comment by taolive** [comment]
gooooooooooooooooooooood
return redis.call("keys","*")
//
return redis.call("exists","mykey")

**Comment by serge-rider** [comment]
Next version will support commands (in the same way as in redis-cli)
