### ISSUE TITLE
[Improvement] Oracle package editor error highlighting

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1321]
Congratulations for last release, I've seen some nice additions and Oracle package edition is getting better over time.

One of the last things that I really miss, to don't need using sqldeveloper anymore (what a nightmare of performance and connectivity issues compared to dbeaver), is code error highlighting and a compiler log.

Now, when persisting changes, just a pop up with error message is shown.

![image](https://cloud.githubusercontent.com/assets/121157/23210187/bae50680-f8fc-11e6-84b9-93efd8ca4b10.png)

This way is difficult to correct errors and try again, because you have to close this pop up and correct them. If you have a lot of them, you cannot rembember the errors until you persist changes again.

It would be very nice having a compiler log area, where you could select errors one by one, and when clicking over them, go directly to the line and column with error. Also, an icon or line highlighting would be nice, near to line number.

![image](https://cloud.githubusercontent.com/assets/121157/23210353/7f8bb11e-f8fd-11e6-95b4-5ff9d6ce9623.png)

**Comment by serge-rider** [comment]
This is not Oracle-specific.
Error highlighting for package/procedure/view editors added for all databases.
