### ISSUE TITLE
binary type represented as decimal / bit shown as int

### ISSUE THREAD

**Issue by trivago-izelenov** [serge-rider/dbeaver#1322]
I have a table with this column:
  `example_col` bit(8) NOT NULL DEFAULT b'0'

dbeaver shows me: 4, but the actual inserted entry is b'00000100' and should be shown as 00000100

![image](https://cloud.githubusercontent.com/assets/12135320/23212564/9b74071e-f907-11e6-9684-f04164346601.png)

**Comment by serge-rider** [comment]
You can view this column in bin radix:
![default](https://cloud.githubusercontent.com/assets/6398845/23580282/4207386c-010f-11e7-8359-bfe15fba308f.png)

**Comment by serge-rider** [comment]
Full support will be added in the next version. 
Till then you can use workaround (see above).
