### ISSUE TITLE
Disable auto-connect on inicialize dbeaver

### ISSUE THREAD

**Issue by acsdev** [serge-rider/dbeaver#1323]
Everytime I open dbeaver, it try to reconnect an connection that I didn't close last time I have used it. Is there a way to stop or to override this behavior?

**Comment by acsdev** [comment]
I found a place to do this. 
Window > Preferences > Editors > SQL Editor 
disabled option: "Connect on editor activation"

**Comment by bsgmbh** [comment]
The above does not work for me. Anytime I have a table left open for any database when closing DBeaver it tries to reconnect to that database when it is started next time. 
I thought that disabling the option "Connect on query execute" would stop this, but as it seems DBeaver is doing just that, querying the table when it reopens.
>> Is there any way to either stop this behavior and to make DBeaver wait until I explicitly activate that table's tab before it tries to connect and query or alternatively to make DBeaver close all open tables/tabs upon close?

**Comment by serge-rider** [comment]
You can disable this by turning "Reopen database editors after restart" option off:
![image](https://user-images.githubusercontent.com/6398845/32196746-b4edb100-bdd2-11e7-8fa5-5ac4c19d2cba.png)

**Comment by bsgmbh** [comment]
Thank you very much for your super fast and super helpful answer!

Von: Serge Rider [mailto:notifications@github.com]
Gesendet: Montag, 30. Oktober 2017 22:31
An: serge-rider/dbeaver
Cc: Ingmar Gutberlet; Comment
Betreff: Re: [serge-rider/dbeaver] Disable auto-connect on inicialize dbeaver (#1323)


You can disable this by turning "Reopen database editors after restart" option off:
[image]<https://user-images.githubusercontent.com/6398845/32196746-b4edb100-bdd2-11e7-8fa5-5ac4c19d2cba.png>

**Comment by rduivenvoorde** [comment]
For people searching for this in newer versions, not sure which of those is the essential one though... So I disable both :-)

![Screenshot-20200706084118-846x435](https://user-images.githubusercontent.com/731673/86563351-8491bd80-bf64-11ea-8ec7-b18140872d8b.png)

![Screenshot-20200706084436-688x555](https://user-images.githubusercontent.com/731673/86563595-f407ad00-bf64-11ea-85aa-1e44439a1337.png)

**Comment by mike-boost** [comment]
moron design for this and project functions

**Comment by nicolasmafra** [comment]
Again, for people searching for this in newer versions:

![image](https://user-images.githubusercontent.com/19596561/152396363-0dffb6ed-f9ea-4c27-852d-e13c5b22ccee.png)

**Comment by nicolasmafra** [comment]
Why not unify these "connect on startup" settings?

**Comment by pixiekat** [comment]
I love you dBeaver but stop moving this; it was wild following this issue to get the current location of the setting. :)

**Comment by lethargosapatheia** [comment]
For anyone else who comes across this and works on Mac (given that it's unified, I'm guessing it's the same on Windows more or less):
`Settings` – `Editors` – uncheck `Reopen database editors after restart`.

**Comment by rduivenvoorde** [comment]
In Linux it is:  menu Window / Preferences / Editors

And now there is also an option: 
"Keep associated editors open after disconnecting from data source"
which apparently defaults to True:

![image](https://github.com/user-attachments/assets/9ce96e5a-23b2-4075-973d-a756cd6ac0bc)

I think one of the devs does NOT work from a lot of different clients/locations :-)

**Comment by lethargosapatheia** [comment]
In the meantime I've come across what I'd call a bug related to this. I've created another connection to a database and dbeaver keeps connecting to it every time it starts even if the option `Reopen database editors after restart` is not checked anymore.

**Comment by guya65** [comment]
I closed the database browser window in the bottom of my screen and when I restart it does not connect :)

**Comment by lethargosapatheia** [comment]
@guya65 What a weird bug! Indeed, this works, it doesn't reconnect anymore. So this seems to occur only when you open the SQL script window, not when you browse the sql instance (databases, users, whatever). So if you keep the SQL script window open when you close dbbeaver, it will automatically reconnect to the database you've opened the sql script window for. If you open several sql script window for several sql instances, then you get reconnected only to the last sql instance you've ieft the window open for (I hope I'm clear in my explanation). But the bug is quite clear and reproducible.

I'm now using the latest version 25.0.0.202503021833 on Mac OS 15.3.1

**Comment by guy-rouillier** [comment]
Thank you to those who kept this post up to date.  I've been using dbeaver on Windows, and just switched my default OS to Linux.  I disliked that dbeaver opened up the last data I had viewed in a previous session.

**Comment by robertwt7** [comment]
huh even after disabling the "Reopen database editors after restart" mine still ask me to connect and says "Connection Lost" on each restart
