### ISSUE TITLE
highlight or filter text in results

### ISSUE THREAD

**Issue by verajosemanuel** [serge-rider/dbeaver#1325]
Sometimes i need to highlight a pattern text in **all** resultset. Filter box requires SQL, but if I need SQL I write it in the upper pane to get the results. What I'm talking about is filtering AFTER sql query and operate on results pane.

There's two options for this:

1.- **Highlight text** : Similar to browsers when searching for text. A text box and just need to make visible (shadows, text color, cell color...)some text in all columns no matter which column that text is located.

2.- **Subsetting rows:**: same mechanism but just show me the rows where "pattern" is in ANY of the columns. filter out the rest, so reduce the results pane to just the rows that contains text pattern in any column.

Regards

**Comment by verajosemanuel** [comment]
Great Serge!  I think the best option is the second one: Filtering the rows instead of highligh text because sometimes you have many rows.

 Thanks ofr a superb database client.

**Comment by yyx100** [comment]
thanks Serge!   resultset  filtering will be a very useful feature!  please support: 1-regex, 2-can match text in any column in resultset, 3-high light matched grid.

**Comment by sdpurohit** [comment]
Serge - I tried out the new feature using the Find/Replace dialog. 
I think it would be better to have a text box like the one that is used to to apply a SQL Expression to the result set. When typing in that box it would automatically (after each character change) filter the matching rows and highlight the matching cells. Would this be reasonable from your perspective?

**Comment by yyx100** [comment]
wow!  nice!  thanks 👍   
Yes, it can be better if it can filter too via that SQL filter box,  but not so important comparing to other feature requests in the queue at this point.

**Comment by serge-rider** [comment]
@sdpurohit Agreed. For no DBeaver uses standard Eclipse way for find/replace function. Which is, honestly, not very convenient (so 90s).
Please create a separate feature request.

**Comment by sdpurohit** [comment]
I filed [issue 1929](https://github.com/serge-rider/dbeaver/issues/1929) for better result set filtering.
