### ISSUE TITLE
Add option to group objects by Catalog and/or Schema

### ISSUE THREAD

**Issue by tobia** [serge-rider/dbeaver#1328]
With the MySQL driver, all DB objects are grouped by catalog (called "database" in MySQL jargon), and schemas are not used. This is shown in DBeaver as an additional grouping in the navigator, like this:

    MySQL Connection
     \_ Databases
         \_ CATALOG_1
         |   \_ Tables
         |   |  ...
         |   \_ Views
         |      ...
         \_ CATALOG_2
             \_ Tables
             |  ...
             \_ Views
                ...

Other databases like Oracle use schemas instead of catalogs, and again DBeaver shows the grouping correctly. But, as far as I can tell, this is provided by the "Driver Type" setting in the driver manager. Does the "Generic" driver type allow grouping by schema and/or by catalog?

As an example, I'm using a generic driver (ClickHouse) that supports schemas, but I cannot find an option to enable grouping DB objects by schema like this:

    ClickHouse Connection
     \_ Schemas
         \_ SCHEMA_1
         |   \_ Tables
         |   |  ...
         |   \_ Views
         |      ...
         \_ SCHEMA_2
             \_ Tables
             |  ...
             \_ Views
                ...

If it's not currently there, I think it would be useful to add it as a driver configuration option. Some drivers group their items by catalogs, some by schemas, some by both (possibly) and some by none. There should be a setting enabling these 4 options, or equivalently 2 boolean settings (Group by catalog and Group by schema.)

**Comment by serge-rider** [comment]
DBeaver groups tables by schemas always - if this is possible.
Most likely your driver (ClickHouse) doesn't provide information about schemas.
Please check error/debug log for any related errors (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by serge-rider** [comment]
Reopen if any information will be available.
