### ISSUE TITLE
Results viewer: F5 shortcut key not working after connection lost

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#1329]
When viewing some data, if the connection to the database has been lost and I force a "reconnect" (as shown on the first picture), the F5 shortcut key doesn't work anymore and I'm forced to use the "refresh" button (as shown on the second picture).

![Force reconnect](http://i.imgur.com/mzgka5Y.png)

![Refresh button](http://i.imgur.com/PM7CRbw.png)

**Comment by serge-rider** [comment]
It is a bug, thanks for noticing.

**Comment by Otiel** [comment]
I confirm this is fixed in 4.0.2. Thanks for the quick resolution.
