### ISSUE TITLE
dbeaver doesn't get installed on mac osx 10.11

### ISSUE THREAD

**Issue by mark-kolodkin** [serge-rider/dbeaver#133]
when installing dbeaver on mac osx 10.11, i ge the following error
"an error has accord"

see screen shot and log file attached
![image](https://cloud.githubusercontent.com/assets/14827091/12007430/e68ebda0-ac0c-11e5-8ea9-038294ccea65.png)
[1451151289095.log.txt](https://github.com/serge-rider/dbeaver/files/72488/1451151289095.log.txt)

**Comment by serge-rider** [comment]
I have to setup Java 1.7+.
Most likely you have Java 1.6 or earlier.

**Comment by mark-kolodkin** [comment]
i have java v8, see image attached
![image](https://cloud.githubusercontent.com/assets/14827091/12009152/67115484-ac75-11e5-9c99-f813ce036d9d.png)

**Comment by mark-kolodkin** [comment]
i have java version 8
see image attached
<img width="378" alt="screen shot 2015-12-27 at 8 40 29 am" src="https://cloud.githubusercontent.com/assets/14827091/12009156/9546ed78-ac75-11e5-8181-7777207fe7ce.png">

**Comment by serge-rider** [comment]
Looks like a Java for web browser. Sometimes there is mess of different Java versions on Mac. Open terminal and type:
```
java -version
```
If version will differ from 1.8 then you will need to reinstall Java:
http://stackoverflow.com/questions/15624667/mac-osx-java-terminal-version-incorrect

**Comment by mark-kolodkin** [comment]
thanks, this solved the issue

**Comment by rdewolff** [comment]
Having the same problem but the command 
```java -version```
gives me the 1.8

Am using jenv (https://github.com/gcuisinier/jenv/) but seems dbeaver is always taking the java 1.6 version from Apple.

How is the java version determined by dbeaver? Any other way to fix this?

**Comment by codebling** [comment]
DBeaver uses the Eclipse framework. You can see how [Equinox Launcher determines the vm used to launch Java].(https://wiki.eclipse.org/Equinox_Launcher#Finding_a_VM.2C_Using_JNI_Invocation_or_Executing_Java)

As a workaround, you should be able to use the `-vm` option to launch DBeaver using the correct version of Java.

I suspect that this is a jenv issue. Is your `JAVA_HOME` set? (see [jenv #112](https://github.com/gcuisinier/jenv/issues/112)). Are you using the latest version of jenv?

**Comment by rdewolff** [comment]
Am checking the Equinox now.

Concerning the JAVA_HOME var it's set correctly to a valid Java home dir (```/Library/Java/JavaVirtualMachines/1.8.0_66-b17/Contents/Home```). 
The jenv version am using has been installed via an updated brew today (```jenv 0.4.3```).

**Comment by codebling** [comment]
Try executing DBeaver with `-vm /Library/Java/JavaVirtualMachines/1.8.0_66-b17/Contents/Home` option, that should get you going. We'll still have to figure out why it's not working

**Comment by rdewolff** [comment]
It's working! Thanks @codebling !

**Comment by rdewolff** [comment]
The java installation on mac is far from clean. Hope this will change in the futur.

**Comment by dmytro-lytvyn** [comment]
The problem is that DBeaver still requires to install legacy Java 6 during its installation, and even provides a link to download Java 6. This is why I installed Java 6, and not 7 or 8.

**Comment by serge-rider** [comment]
It is a known bug in Mac OS. This error message you see is generated by OS, not by DBeaver.
DBeaver doesn't need Java 6 (in opposite it depends on Java 7, version 4.x will depend of Java 8).

You need to install Java (JDK) 8 form here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Glutnix** [comment]
`brew install Caskroom/casks/java` will install Java 8.

**Comment by Lucidyan** [comment]
@serge-rider Please add requirements to the version of java on the installation page, it was not easy to find this helpful post

**Comment by rdewolff** [comment]
@Lucidyan +1

**Comment by serge-rider** [comment]
@Lucidyan done

**Comment by rafaeloak** [comment]
Installing JDK 8 worked pretty well for me. Thanks!

**Comment by kangbu** [comment]
Hi, all. I had same problem as OP mentioned. Even though I already installed JDK 9 on my MacOS, DBeaver didn't work. I also tried to solve by setting up JAVA_HOME environment variable but it didn't work, too. Finally, I uninstall it and reinstall using [brew](http://macappstore.org/dbeaver-community/), it perfectly worked well. Thank you everyone.

**Comment by hardyoyo** [comment]
Same problem, 3 years later, I have Java installed via jabba, and the JAVA_HOME environment variable is set correctly. I even rebooted. I do have Java 14 installed... so... on the off chance DBeaver secretly *requires* Java 8 I'll try to round up a dusty old copy of it.

**Comment by codebling** [comment]
Closer to 4 and a half years later.  

Have you tried the [solution that I outlined above](https://github.com/dbeaver/dbeaver/issues/133#issuecomment-170159496) which the OP confirmed worked for them?

**Comment by hardyoyo** [comment]
I have not, I will see if I can figure out how to pass a command line option to an application launcher
