### ISSUE TITLE
Request: Explore Temporary Tables/Views

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#1330]
If you do a `create temporary table....` in postgresql, the table gets created in a temporary schema that can be access in the current session in the pg_temp schema (actually an alias).  It would be nice to be able to navigate and explore the pg_temp schema and interact with the things you create in it.

**Comment by serge-rider** [comment]
You can do this.
On connection properties page "General" turn on "Show utility objects" checkbox. Now you can see temp and toast schemas.

**Comment by jk3us** [comment]
So it can... but could it also include the `pg_temp` alias?  I could use schema filters to hide all the numbered ones, but since you get a new temp schema for each connection, there's currently no way to quickly get into "mine": 

![image](https://cloud.githubusercontent.com/assets/41621/23270518/ae9fe828-f9b9-11e6-9947-d75a2468a120.png)

**Comment by serge-rider** [comment]
Do you have any ideas how to make this more helpful?

**Comment by jk3us** [comment]
Under almost all circumstances, only the `pg_temp` pseudo-schema will be useful.  My preference would be to always show that and never show the others.  Maybe `pg_temp` could be included as a "system" object instead of a "utility" object.

**Comment by serge-rider** [comment]
This makes sense (make pg_temp system).

**Comment by serge-rider** [comment]
Although it is still weird. Not very obvious why pg_temp_1 is so special.

**Comment by jk3us** [comment]
It's not special.  That's just the one you happened to be assigned.  Each connection (and transaction, I think) that creates temporary things gets a pg_temp_## schema that temporary objects go into, and the alias pg_temp points to the "current" temp schema. If you open another connection while that one is still open, you'll probably get assigned pg_temp_2.  After you disconnect your first, pg_temp_1 becomes available to reuse by a new connection (but will be empty).  If you're doing anything that directly addresses any of the numbered temp schemas, you're probably doing something you shouldn't.

**Comment by serge-rider** [comment]
Yep, agreed.

In regards to connections: DBeaver with default settings opens 2 connection + 1 connection per each open SQL editor. So yes, it is tricky to find out where your temp table really is.

**Comment by serge-rider** [comment]
Closing as not-doable.
If anybody have any idea regarding this problem - please reopen.
