### ISSUE TITLE
Hive: bad quoted table name

### ISSUE THREAD

**Issue by ray3888** [serge-rider/dbeaver#1333]
seems the exprot from sql need to run the sql beforehand, is this a bug?
also for export from table, sometime need to change the source which is readonly, is it possible to change the source to writable? besides, where to set the resultset number of export from table?    thanks

![image](https://cloud.githubusercontent.com/assets/1989590/23244699/1814d04a-f9c2-11e6-958d-4cb59de47ccb.png)

**Comment by serge-rider** [comment]
I'm not quite understand this. 

What is "read-only source"? And what's the point making it writable?

**Comment by ray3888** [comment]
![image](https://cloud.githubusercontent.com/assets/1989590/23594786/b8d956a2-0257-11e7-9979-a07a88b4cb9f.png)
when export table data, the source is automatically specified as "default".tablename, but in hive this is illegal, need to remove double quote or database name.

**Comment by serge-rider** [comment]
Well, it looks like real problem is in quoted identifiers. I suppose table data viewer also doesn't work.
So, Hive doesn't support quoted identifiers at all?

**Comment by ray3888** [comment]
yes table data viewer doesn't work.  Hive support quoted identifiers for columns but not for database name.
![image](https://cloud.githubusercontent.com/assets/1989590/23638691/19f68434-031e-11e7-9d60-34105fb3e3be.png)

Another thing, exprot from sql need to run the sql beforehand, any consideration for it, thanks.

**Comment by serge-rider** [comment]
I'd wish to fix this (quote database name properly) but this will require extra driver config while I don't have live Hive instance to test this. Probably will have one later (april-may).

You don't have to run SQL before export. Right click->Execute->Export from query.

**Comment by ray3888** [comment]
FYI, it's easier to setup spark-thrift than hive.
yes you are right, not need to run SQL before export, but the display is still old, misled by it.
![image](https://cloud.githubusercontent.com/assets/1989590/23704263/015c4a68-043f-11e7-87e8-487c5b8aff8f.png)

**Comment by serge-rider** [comment]
Spark JDBC driver doesn't provide database metadata info, so I don't even see database or tables.
What JDBC driver do you use?

**Comment by ray3888** [comment]
when starting spark-thrift, it will automatically create metadata if not exist. it works as hive. you can create database/table and run sql. I use apache hive jdbc.
![image](https://cloud.githubusercontent.com/assets/1989590/23834437/9566a974-0791-11e7-8a5e-69fade3e2372.png)

**Comment by serge-rider** [comment]
I tried another driver (org.spark-project.hive:hive-jdbc). It differs from default hive driver.

Anyhow, try EA version (http://dbeaver.jkiss.org/files/ea/) - problem with quoted database name (at least one of) was resolved there.

**Comment by ray3888** [comment]
BTW, spark-thrift not implement all hive metadata interface, so you may not see database/tables in Database Navigator. can use "show databases", "show tables in default"  instead.

**Comment by serge-rider** [comment]
Yep. 
Unfortunately only spark client driver works in my test environment so I can't test this problem with database name right now.
