### ISSUE TITLE
Error while variables in Query

### ISSUE THREAD

**Issue by girishpadia** [serge-rider/dbeaver#1334]
Perform following steps in DBEAVER 4 and you will encounter an error. However the steps works fine with mysql command line utility and mysql-workbench

>mysql>create temporary table t1 (name varchar(20));
>Query OK, 0 rows affected (0.01 sec)
>
>mysql>insert into t1 values ('Bob');
>Query OK, 1 row affected (0.01 sec)
>
>mysql>insert into t1 values ('Jack');
>Query OK, 1 row affected (0.00 sec)
>
>mysql>insert into t1 values ('Marry');
>Query OK, 1 row affected (0.00 sec)
>
>mysql>insert into t1 values ('Mark');
>Query OK, 1 row affected (0.01 sec)
>
>mysql>insert into t1 values ('Maria');
>Query OK, 1 row affected (0.00 sec)
>
>mysql>select * from t1;
>+-------+
>| name  |
>+-------+
>| Bob   |
>| Jack  |
>| Marry |
>| Mark  |
>| Maria |
>+-------+
>5 rows in set (0.00 sec)
>
>mysql>set @x=0;
>Query OK, 0 rows affected (0.00 sec)
>
>mysql>select name,@x := @x+1 as rowid from t1 ;
>+-------+-------+
>| name  | rowid |
>+-------+-------+
>| Bob   |     1 |
>| Jack  |     2 |
>| Marry |     3 |
>| Mark  |     4 |
>| Maria |     5 |
>+-------+-------+
>5 rows in set (0.00 sec)

>mysql>
![screenshot from 2017-02-23 10-16-27](https://cloud.githubusercontent.com/assets/339269/23245259/334699c2-f9b1-11e6-8729-8b69652521cd.png)

**Comment by serge-rider** [comment]
This works fine in my environment:
![default](https://cloud.githubusercontent.com/assets/6398845/23253331/2f8fb2e6-f9c5-11e6-8d0c-ad69e1e47b18.png)

How do you execute these queries: one by one with CTRL+Enter, in script mode (ALT+X) or somehow else?

**Comment by girishpadia** [comment]
Oops!!! I forgot to execute in script mode. Habit of select multiple statement and Ctrl+Enter.
