### ISSUE TITLE
Columns not refresing in select query (ORACLE)

### ISSUE THREAD

**Issue by loboaureo** [serge-rider/dbeaver#1335]
Hi, when i execute a select query on a specific table, the data visor doesnt update the columns.

For example, with dbeaver fresh opened
![screenshot_4](https://cloud.githubusercontent.com/assets/681482/23248979/5d76438c-f9a2-11e6-9b18-6bf36a667eb3.png)

Then if i click two times in the "record" button to change the view to one record view and again to normal view, the data appears.
![screenshot_5](https://cloud.githubusercontent.com/assets/681482/23248985/634e47aa-f9a2-11e6-913f-395d4d58d8c6.png)

Also if i execute another query, it updates the columns, but if i execute this same select query it fills only the previous columns withot refresh names
![screenshot_6](https://cloud.githubusercontent.com/assets/681482/23248989/66bd5214-f9a2-11e6-890f-d3c08c4a66e2.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/681482/23248991/6a14a818-f9a2-11e6-9065-8cbd2e6c0df8.png)

I try it with ojdbc6.jar and ojdbc7.jar as drivers and with version 4, 4.0.1 and return back to 3.8.5.

**Comment by serge-rider** [comment]
Can't reproduce.
Please check Error Log view and/or debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any related errors.

**Comment by loboaureo** [comment]
Is really strange, as it happens only with that table (at least i have notice) and in sqldeveloper doesn't happen

Attach the logs

[log.txt](https://github.com/serge-rider/dbeaver/files/796198/log.txt)

**Comment by serge-rider** [comment]
I see two errors related to results coloring. I'll fix them. Maybe these errors lead to incorrect columns refresh behavior. This will happen only in particular table (because color settings are saved for each table separately).  But I'm not 100% sure. I will publish EA version shortly so you can test this.

**Comment by loboaureo** [comment]
That makes sense, that is the table for what i asked this :)
https://github.com/serge-rider/dbeaver/issues/1267

**Comment by serge-rider** [comment]
You can get EA here: http://dbeaver.jkiss.org/files/ea/

**Comment by loboaureo** [comment]
Works perfect now.

Thanks for your quick response and hard work!!
