### ISSUE TITLE
Setting default value for column: Column <default value> not found

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1339]
Postgresql:
1. Create a table and save it
2. Add a default value like "text" or text (without quotes) to one of your columns
3. Save

Error: The value you defined as default value isn't found - it is interpreted as a column name. Generated query looks correct.

**Comment by serge-rider** [comment]
You need to quote string literal like this: `'test'`.

**Comment by GiantCrocodile** [comment]
Hm true. I hate when it is different implemented by different DBMS. Can you make it convert it maybe if it is wrong type? If you think this is a bad idea, just close this ticket.

**Comment by serge-rider** [comment]
Default column value could be any SQL expression (function call, constant, string literal, etc). 
So I don't think that any conversions will be appropriate.
