### ISSUE TITLE
rename table command for oracle database

### ISSUE THREAD

**Issue by dmitry-luxoft** [serge-rider/dbeaver#134]
1) connect to oracle database
2) select a table in the tree
3) press F2, enter new name, save
The result SQL would look like

RENAME TABLE OLDTABLE TO "NEWTABLE";

That doesn't work for oracle - the word "table" must not be there:
RENAME OLDTABLE TO "NEWTABLE";

**Comment by serge-rider** [comment]
Thanks for report
