### ISSUE TITLE
PostgreSQL: serial data types

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1341]
Please add data type aliases to the dialogue/selection when you create columns. This is an enhancement related to #1052 point 3.

**Comment by serge-rider** [comment]
What database?

**Comment by GiantCrocodile** [comment]
Postgresql.

**Comment by serge-rider** [comment]
Well, there are aliases already (like integer, serial, etc). Is something missing there?

**Comment by GiantCrocodile** [comment]
I tried to find serial in the dropdown dealugie in column creation. It isn't there. I will check again when I'm home. I was only able to write serial in the field (not using dialogue) and then it was converted to int4 with no default type.

**Comment by serge-rider** [comment]
It's complicated. In fact serial is alias of int4. But it has special meaning in DDL (sequence auto-creation + auto-increment default value).
Makes sense to leave it serial.

**Comment by lacanoid** [comment]
Types serial and bigserial (the latter is actually to be preferred for ids and such!) are a bit of a hack and do not really show up in system catalogues as proper types.

The reasonable thing seems to be to just explicitly add them to above mentioned list.

**Comment by lacanoid** [comment]
Also, in the same column-adding dialog:

When length is empty, is gets magically set to 100, at least for default option of varchar. 
Is should probably be omitted if not specified.
