### ISSUE TITLE
Database getting disconnected after 1/2 minutes of inactivity

### ISSUE THREAD

**Issue by Pritraj** [serge-rider/dbeaver#1342]
Database getting disconnected after 1 or 2 minutes of inactivity
and to reconnect it takes too much time (1/1.5 minutes)

**Comment by serge-rider** [comment]
Did you try to configure Keep-Alive?

**Comment by Pritraj** [comment]
my database is on amazon rds and its postgre.... I didn't found keep alive option in dbeaver

**Comment by serge-rider** [comment]
It is in connection properties dialog on page General.

**Comment by Pritraj** [comment]
![image](https://cloud.githubusercontent.com/assets/18588781/23501059/5b3167f8-ff58-11e6-99f9-6a36cdebe27b.png)

**Comment by Pritraj** [comment]
I reduced my connection timeout....now its getting connected fast(does it have any negative impact?)

Thank you so much for help.

**Comment by serge-rider** [comment]
Great. Closing.

Just a note: you can open connection properties by selecting connection in database navigator and pressing F4 (or context menu->Edit connection).

**Comment by Pritraj** [comment]
got it...thank you so much again..!
