### ISSUE TITLE
Version 4.0.1 seems fixed Oracle connection issue but broke Redshift connection

### ISSUE THREAD

**Issue by yshao0711** [serge-rider/dbeaver#1343]
This new release seems fixed the Oracle connection. But when I tried the all the Redshift connection, it always timed out, while they work fine for version 4.0.0

**Comment by serge-rider** [comment]
Can't reproduce.
Post error stacktrace and/or other details.

**Comment by yshao0711** [comment]
I couldn't reproduce it today either, so closing it out.
