### ISSUE TITLE
version 4.0.1: oracle 8 databases

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1345]
Now, I can see table views in oracle 8 databases ( not in former versions ), but it is still an important problem: I can´t edit rows. Previous to that, that error is received when opening the table:

SQL Error [942] [42000]: ORA-00942: la tabla o vista no existe

  java.sql.SQLException: ORA-00942: la tabla o vista no existe

![imagen](https://cloud.githubusercontent.com/assets/26002754/23300585/78688080-fa86-11e6-9e09-8b34e36c0061.png)

[dbeaver-debug.zip](https://github.com/serge-rider/dbeaver/files/799137/dbeaver-debug.zip)

**Comment by serge-rider** [comment]
Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) with related errors/warnings.

**Comment by luisalb85** [comment]
Updated with debug info

Thanks

**Comment by serge-rider** [comment]
Now problem is in table columns reading. 
DBeaver executes query 
```sql
SELECT * FROM SYS.ALL_TAB_COLS c WHERE c.OWNER=? AND c.TABLE_NAME=?
```
I believe it should work on 8.x. Could you check it?

**Comment by luisalb85** [comment]
SQL Error [942] [42000]: ORA-00942: la tabla o vista no existe

  java.sql.SQLException: ORA-00942: la tabla o vista no exist

It works this:

select * from all_tab_columns where owner='owner' and table_name ='table_name'

**Comment by serge-rider** [comment]
Ok, thanks for info.
