### ISSUE TITLE
Open Database Object does not filter out non active schemas when focusd on Sql Editor

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#1347]
In Dbeaver 4.0.0 when using the "Open Database Object" Dialog when focus is on the Sql Editor I get a list of tables not restricted to the active schema only:

![image](https://cloud.githubusercontent.com/assets/6532949/23306167/823fc0c0-faa2-11e6-9ae3-b735ebcab186.png)

when the focus is on the Database Navigator it works fine:
![image](https://cloud.githubusercontent.com/assets/6532949/23306182/975d42c0-faa2-11e6-94d5-178a536d846e.png)

**Comment by serge-rider** [comment]
Looks like it works as expected. By default "Go To Object" dialog searches all tables in all schemas.
If you need to search in particular schema you can select it in navigator (as you did).

Limiting search by current search_path will make global search impossible.
