### ISSUE TITLE
update package from update site

### ISSUE THREAD

**Issue by stepjacky** [serge-rider/dbeaver#135]
why not update from help->update on standalone version,that can make update operation more easy!

**Comment by serge-rider** [comment]
We have this (or similar) feature in plans. 
It will require to add Eclipse p2 support in standalone version. Which means adding pretty many additional plugins.
Probably will try it on EE version first (it is already not-so-lightweight).

**Comment by stepjacky** [comment]
Oh,thanks for doing this

**Comment by serge-rider** [comment]
P2 update was added in DBeaver 3.7 (EE version).
