### ISSUE TITLE
Intellisense / Autocomplete not working with DELETE statements in 4.0.1

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1350]
Doing a Select statement on tables show proper autocomplete during the WHERE clause.

However doing the DELETE statement, followed by a WHERE clause on the exact same table says "no proposals", when it should show column names.

Issue platform: IBM DB2 for IBM i OS. JTOPEN JDBC driver.

**Comment by serge-rider** [comment]
Can't reproduce. SELECT and DELETE acts identical in my environment.
Post query example (and where do you press CTRL+Space).

**Comment by xantari** [comment]
Close this, as I can't reproduce it now either. Strange.

If I figure out how to reproduce it i'll reopen.
