### ISSUE TITLE
Colorize inactive tabs with Development, Test or Production colors

### ISSUE THREAD

**Issue by whyr** [serge-rider/dbeaver#1352]
When DBeaver is used in several environments, you can colorize the connection iwth red (for Production), yellow (for Test) and white (for Development).

If you open different objects (i.e. tables), they are opened in tabs. The active tab get the environment color (red, yellow, white) but the inactive tabs are not getting this color.

It would be a good enhancement to colorize the inactive tabs. Maybe it would be enough to paint a line under the name of the object as the attached example.

![dbeaver feature](https://cloud.githubusercontent.com/assets/23739950/23359475/ad21a2f4-fce6-11e6-8f0c-7632ebaaca48.png)

**Comment by serge-rider** [comment]
Unfortunately that's not easy. SWT rendering styling allows to set one color for active tab and one color for inactive - it is not possible to set different colors for different tabs.

Labeling as duplicate of #300
