### ISSUE TITLE
Oracle TNS connection does not work with IFILE

### ISSUE THREAD

**Issue by zlsmith86** [serge-rider/dbeaver#136]
DBeaver is able to reave the values from my TNS file, but it is not able to resolve the entries from the remotely references TNS file.  I work for a large organization and we use an IFILE to reference our settings from a single network location.  I would like DBeaver to be able to list and connect to the entries referenced in this remote file.  An example of the IFILE entry is below.

    IFILE = T:\remote_tnsnames.ora

**Comment by serge-rider** [comment]
Good point. Fix in 3.6
