### ISSUE TITLE
RedShift view procedure / generate ddl fails

### ISSUE THREAD

**Issue by anesthesi** [serge-rider/dbeaver#1360]
Hello,
With DBeaver 4.0.0, when I try to view a procedure, I get:
SQL Error [500310] [42883]: [Amazon](500310) Invalid operation: function pg_get_functiondef(oid) does not exist;
  [Amazon](500310) Invalid operation: function pg_get_functiondef(oid) does not exist;
    com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: function pg_get_functiondef(oid) does not exist;

**Comment by serge-rider** [comment]
RedShift doesn't support PostgreSQL function pg_get_functiondef (it returns full procedure source code).
All I can do is to return `pg_proc.prosrc` value as source (its value depends on procedure implementation language). Not sure that this makes sense for RedShift. Could you make select from pg_proc and check this?

**Comment by anesthesi** [comment]
Sorry for the delay. 
It seems that executing: 
select prosrc from pg_proc p where p.proname = 'proname'
does the trick.

Thank you!

**Comment by serge-rider** [comment]
Good, thanks for testing
