### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by scataldi** [serge-rider/dbeaver#1363]
dbeaver 4.0.1

`SET @variable =	'X';`

`SELECT * FROM Table WHERE Field = @variable;`

It produces result rows but the export wizard seems to only execute the SELECT command, forgetting the SET instruction. So the export fails with empty file.

**Comment by serge-rider** [comment]
Yes. Export from multiple queries is not supported.

It can be done in MS SQL (execute multiple queries as a single statement) but not in MySQL.

**Comment by scataldi** [comment]
I need this function and It works in DBeaver 3.8.3 with MySQL, so I am still using it. 
So I can't upgrade to DBeaver 4?

**Comment by scataldi** [comment]
**WOW!**
On 4.0.2 this function works again.
Great job! Thank you so much!

**Comment by serge-rider** [comment]
This is a side effect of default config options change. 
In 4.0 DBeaver open separate connection for each SQL editor by default. Now it uses the same connection for all editors (this can be changed in preferences).
