### ISSUE TITLE
Can you add comments to the contents of sql hints?

### ISSUE THREAD

**Issue by liliexuan** [serge-rider/dbeaver#1369]
Can you add comments to the contents of sql hints?

For example 
like this ：

![issue](https://cloud.githubusercontent.com/assets/12954661/23444810/2dbb46a4-fe72-11e6-8b68-331f2ba4a8ae.png)

**Comment by liliexuan** [comment]
I think this feature can facilitate the understanding of the field

**Comment by serge-rider** [comment]
Comments are already included for some databases. What's your database?

**Comment by serge-rider** [comment]
Never mind, I'll just improve general algorithm and will include all object properties in description panel.

**Comment by liliexuan** [comment]
oracle 11g! If you add this field, it's great! Thank you !

**Comment by liliexuan** [comment]
oracle 11g! If you add this field, it's great! Thank you !
