### ISSUE TITLE
Support for execute procedure

### ISSUE THREAD

**Issue by bart404** [serge-rider/dbeaver#137]
According http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1827 execution of stored procedures is not supported

**Comment by serge-rider** [comment]
Execution of stored procedures is supported. But there are many nuances.
Main problem is printing of output parameters.

**Comment by bart404** [comment]
Thx for the response. Much appreciated if you can give some guidance on printing output or calling the execute statement.

Whenever I try in the sql editor "execute schema.procedure(parameter);" I get in return:
Query execution failed.
DBCException: SQL Error [900][42000]: ORA-00900: invalid SQL statement

I am using DBeaver 3.5.8 against Oracle XE 11g with ojdbc7.jar.

When doing the same in SQLPlus all works as expected.

This is a sample procedure:

CREATE OR REPLACE Procedure WORLD.update_unitprice
as
begin
	update world.ORDERDETAILS set UNITPRICE = round(UNITPRICE * 1.01, 2);
	commit;
end;

Thx, Bart

**Comment by serge-rider** [comment]
One of the worst problems with stored procedures is that each database has it's own syntax.
In Oracle you can one of:
```
CALL PROC_NAME(...);
```
or
```
BEGIN
  PROC_NAME(...);
END;
```

**Comment by bart404** [comment]
Cool, when I use "CALL proc_name(...);"  I get the output & results I expect.
Maybe you can add syntax support for "EXECUTE proc_name(...);" as well.
Thx, Bart

**Comment by bart404** [comment]
I did some quick googling on call vs execute, but did not find a good explanation on the diffs. At first sight they are quite similar. You could transform the execute in a call on the fly and make a comment in the release notes about it. Just an idea...

**Comment by serge-rider** [comment]
I still think that trying to adapt all databases to some universal SQL syntax isn't a good idea.
It will require too much efforts. Don't think it worth it.

**Comment by antonio-petricca** [comment]
I think DBeaver is the most beautiful and powerful open source tool of its category, but unfortunately the only lack is the stored procedure execution support like, for example, Oracle SQL developer.
