### ISSUE TITLE
v4.0.2 can't insert space, newline, comma after keyword

### ISSUE THREAD

**Issue by pealp** [serge-rider/dbeaver#1371]
This is odd, but after upgrading to 4.0.2 every time I type a key word (SELECT, FROM, WHERE, etc etc), I can't insert a space, newline, comma, or anything else that would "complete" the word.

Any idea why this is, and how to fix it?

Thanks!

**Comment by Dr4K4n** [comment]
I'm experiencing the same problem after upgrading to 4.0.2, running Ubuntu and OpenJDK 1.8.0_121

**Comment by UkrZilla** [comment]
I have the same problem after upgrading from 4.0.1 to 4.0.2

**Comment by serge-rider** [comment]
@pealp Are you on Linux too?

I can't yet reproduce that. Will try to test on different Linuxes.
You could try to play with auto-completion options (increase "Auto-activation delay", disable "Activate on typing", etc).

**Comment by pealp** [comment]
@serge-rider I'm on Windows 7 x64, have tried playing with auto-complete but nothing fixed it, so I temporarily reverted back to 4.0.1

**Comment by UkrZilla** [comment]
Using Windows 7 64bit version, default autocomplete setting

**Comment by serge-rider** [comment]
I did reproduce that (this is error in Generic driver connection init).
I'll rebuild 4.0.2 right now as this seems to be pretty serious issue.

**Comment by serge-rider** [comment]
Please try to download 4.0.2 again.

**Comment by Dr4K4n** [comment]
Thanks! The newly downloaded version works for me.

**Comment by serge-rider** [comment]
Ok, thanks for testing.

**Comment by bazzilic** [comment]
@serge-rider can you update the Chocolatey package as well? It is bundled with the old installer for 4.0.2.
