### ISSUE TITLE
Set active schema by deafult on openning SQL editor using selection from database navigator

### ISSUE THREAD

**Issue by bsienn** [serge-rider/dbeaver#1372]
Feature request:

If database, `Tables tree` or table name is selected, then opening a new sql editor should set the current database scope for the selection from `database navigator`.

![capture](https://cloud.githubusercontent.com/assets/3149876/23460311/8fb3435a-fea6-11e6-9e4f-14dbd9c703fc.PNG)

**Comment by serge-rider** [comment]
Not sure about that. This will explicitly change current schema for whole connection - such behavior might be unexpected for users.

I think schema change always should be done by users. You can do it right in navigator tree (right click -> Set active).
