### ISSUE TITLE
dbeaver 4.0.x - Generate SQL inside table not working with z/OS db2

### ISSUE THREAD

**Issue by MocniMax** [serge-rider/dbeaver#1375]
Hi.

When using dbeaver 4.0.x, the Generate SQL inside table doesn't work in connection to z/OS db2. It grayes out when selected in context menu.

![clipboard01](https://cloud.githubusercontent.com/assets/26117076/23466945/e5a16558-fe9c-11e6-97cd-97ba1b09660d.jpg)

With connections to any of UDB LUW db2 platforms (Linux, Unix-AIX and Windows) it works correctly.

There is no issues with dbeaver 3.8.5.

Please check where the problem is. Thanks.

Regards,
Mocni Max

**Comment by serge-rider** [comment]
Please send debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files) here or on serge@jkiss.org.
I have no clues so far.

**Comment by MocniMax** [comment]
Hi Serge.

This one is probably related to previous one I reported with missing schema/SQLID #1734.

Here are complete logs from yesterday when I started to use dbeaver version 4.0.2.


[logs.zip](https://github.com/serge-rider/dbeaver/files/813142/logs.zip)

Hope they help.

**Comment by serge-rider** [comment]
Thanks for logs.
I believe this is the same issue: #1371
Try to re-download 4.0.2 (from web site to be sure). Most likely this will resolve the issue (at least some of them).

**Comment by MocniMax** [comment]
Hi Serge.

Both issues are solved with updated 4.0.2. I tested 32 and 64 bit Windows versions.

Thanks a lot for excellent support. dbeaver rules!
