### ISSUE TITLE
PostgreSQL cannot follow UUID foreign key

### ISSUE THREAD

**Issue by vanwalj** [serge-rider/dbeaver#138]
Hello !
First, thanks for this awesome software :)

I just encounter one issue, when I want to follow a foreign key which is an UUID via the shortcut button, it seems like it did not "quote" properly the UUID.

![capture](https://cloud.githubusercontent.com/assets/3532796/12075504/7a78d8ea-b183-11e5-9f4b-95b0ce5b6075.PNG)

![capture2](https://cloud.githubusercontent.com/assets/3532796/12075518/e0eace62-b183-11e5-86bb-95aa97073718.PNG)

DBeaver: 3.5.8
OS: Windows 10
DB: PostgreSQL 9.4.5

**Comment by serge-rider** [comment]
Thanks for report.
