### ISSUE TITLE
Postgres Timestampt and timestamptz

### ISSUE THREAD

**Issue by StepanYankevych** [serge-rider/dbeaver#1381]
Dbeaver 4.0.2 under window 10 64 bit
PostgreSQL 9.6.2 under
cat /proc/version
Linux version 3.10.0-514.6.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) 

```
drop table if exists test_my;

create table test_my
(dt timestamptz);

insert into test_my
select last_analyze from pg_stat_all_tables
where last_analyze is not null
limit 1;

select * from test_my;

alter table test_my alter column dt type timestamp without time zone using dt;
select * from test_my;
```

The Dbeaver shows 
2017-03-02 17:33:45.296545 - Looks good in my TimeZone, but no timezone specified
pgAdmin 

2017-03-02 10:33:45.296545-05 - Looks good with DB timezone 
Then i convert the field using dBeaver

Now both tools show 2017-03-02 17:33:45.296545 - time converted **to client time zone** 

But if i perform alter table not in DBeave but in pg Admin the time is converted **to db time zone** 

So if i run the whole script in Dbeaver 
the final result is 2017-03-02 **17**:33:45.296545
but in PgAdmin 
the final result is 2017-03-02 **10**:33:45.296545

Looks like the bug in Dbeaver. Client's time zone influences on the alter script but it shouldn't

**Comment by StepanYankevych** [comment]
More sample 

/* Run in Dbeaver */
```
drop table if exists test_my;

create table test_my
(dt timestamp);
ANALYZE VERBOSE dwh.test_my;

insert into test_my
select last_analyze 
from pg_stat_all_tables
where last_analyze is not null
and relname = 'test_my'
limit 1;

```
Then run in PgAdmin 

```
insert into test_my
select last_analyze 
from pg_stat_all_tables
where last_analyze is not null
and relname = 'test_my'
limit 1;

```
The result is 
2017-03-02 18:08:10.725761
2017-03-02 11:08:10.725761

**Comment by serge-rider** [comment]
Well, that's not exactly a DBeaver bug but a specific behavior of JDBC driver. By default it lives in local (client) timezone. 
Local timezone can by changed by starting DBeaver with command line parameter `-vmargs -Duser.timezone=<TZ>`. But this can't be considered as a solution, more like a inconvenient workaround.

There is a feature request #238 which probably will be solved with new capabilities added in Java 8 (LocalDate) and recent PostgreSQL driver versions.

**Comment by cjunge-work** [comment]
I think this might be related:
```sql
select localtime, localtimestamp, CURRENT_TIME, EXTRACT(TIMEZONE FROM CURRENT_TIME)/3600.0 as time_offset, current_timestamp, EXTRACT(TIMEZONE FROM CURRENT_TIMESTAMP)/3600.0 as timestamp_offset;
```
time	|timestamp	|timetz	|time_offset	|now	|timestamp_offset
------------ | ------------- | ---------------------- | -------------------- | ---- | ----------------------
12:00:01.392 +1200	|2017-03-14 12:00:01.392 +1300	|11:00:01.392 +1200	|13	|2017-03-14 12:00:01.392 +1300	|13

I've set my timezone to my local timezone (Pacific/Auckland) and adjusted the Time & Timestamp format to include microseconds as well as timezone. There is some really strange behaviour as well as display there!

**Comment by joshhamann** [comment]
Bump.  I have the same issue, and probably thinking the problem is simpler than it is by asking, "Why doesn't dbeaver pull the actual time from the database page that exists on disk?"

**Comment by serge-rider** [comment]
As far as I see this is PG JDBC driver specific.
Don't see how to fix it from DBeaver.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket long time after the last comment. It will be closed. However, if you think that it is actual just let us know.

**Comment by dva** [comment]
It's actual even with Version 7.2.2.202010041557
