### ISSUE TITLE
Support JSON data type Editing for MySQL 5.7+

### ISSUE THREAD

**Issue by BrianWW** [serge-rider/dbeaver#1382]
Feature Request:

I see you have grid editing of JSON data type for MongoDB and PG, but would be really helpful to allow editing JSON data type values in place on the grid for the new data type in MySQL 5.7.

Currently it looks read only in the grid, and even in the "Edit Cell" dialog.

**Comment by serge-rider** [comment]
Yep, makes sense for MySQL 5.7.

BTW in PostgreSQL json columns are editable and even have syntax highlighting:
![default](https://cloud.githubusercontent.com/assets/6398845/23578723/5b099e34-00ee-11e7-9146-35aceb64c731.png)

**Comment by BrianWW** [comment]
This doesn't seem to be working.  I can neither edit the json field in the grid, or in the value editor.  My coworkers confirmed the same.  You can double click to enter the field editing, but it ignores any keys, as if it's readonly.

On OSX Sierra.

**Comment by serge-rider** [comment]
In 4.0.8 JSON type editor is supported only for table editor.
I'll add support for custom SQL queries in the next version. Thanks for reminding.

**Comment by BrianWW** [comment]
Thanks so much!
