### ISSUE TITLE
Internal jdbc driver error

### ISSUE THREAD

**Issue by AFISA-SUCIVE** [serge-rider/dbeaver#1383]
SQL Error: Internal jdbc driver error
Internal jdbc driver error
java.lang.OutOfMemoryError: Java heap space

This happened in the new version 4.0.2 when I type a simple script .

This is easy to fix?

Thank's

**Comment by serge-rider** [comment]
What database?

**Comment by AFISA-SUCIVE** [comment]
MySQL

De: Serge Rider [mailto:notifications@github.com]
Enviado el: jueves, 02 de marzo de 2017 15:28
Para: serge-rider/dbeaver
CC: Diego F. Rodriguez Sreidin; Author
Asunto: Re: [serge-rider/dbeaver] Internal jdbc driver error (#1383)


What database?

**Comment by serge-rider** [comment]
Well, that's odd. Maybe your simple script retrieves too much data (e.g. binaries/texts)?
You can increase amount of memory available for DBeaver by running it with command line parameter `-vmargs -Xmx1024M` (for 1Gb of memory)

**Comment by AFISA-SUCIVE** [comment]
It Fixed when I did -vmargs -Xmx16264M
I don’t know if it’s good, but it works.


De: Serge Rider [mailto:notifications@github.com]
Enviado el: jueves, 02 de marzo de 2017 15:39
Para: serge-rider/dbeaver
CC: Diego F. Rodriguez Sreidin; Author
Asunto: Re: [serge-rider/dbeaver] Internal jdbc driver error (#1383)


Well, that's odd. Maybe your simple script retrieves too much data (e.g. binaries/texts)?
You can increase amount of memory available for DBeaver by running it with command line parameter -vmargs -Xmx1024M (for 1Gb of memory)

**Comment by serge-rider** [comment]
16 gigs is quite a lot, as for me.
Although I'm not familiar with nature of your data.

**Comment by better365** [comment]
For Mac users, 

Go to: `/Applications/DBeaver.app/Contents/MacOS` and then run `./dbeaver -vmargs -Xmx4024M` to change the vm settings.

**Comment by Brunosampaiomartins** [comment]
SQL Error: Internal jdbc driver error
  Internal jdbc driver error
  Internal jdbc driver error
    Java heap space
    Java heap space
    
    Errro está acontecendo na versão 23.1
    Alguém pode me ajudar ?
