### ISSUE TITLE
db2 v8 syscat.nicknames undefined

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1384]
![image](https://cloud.githubusercontent.com/assets/25423046/23534902/d22457f6-fff5-11e6-9832-04cd5a9d7475.png)

**Comment by titou10titou10** [comment]
Hi,
It seems you are using the DB2 LUW DBeaver plugin for your DB2 v8.x server
The minimum version for using the DB2 LUW plugin is Db2 v9.1. For DB2 v8.x, you must use the "generic" plugin
Denis

**Comment by yanOnGithub** [comment]
I have re-created the connection as db2v8. I have got an error about SYSIBM.SQLTABLES after clicking test connection. There was no such error when I created the connection as DB2 LUW.

![20170321t102619_hp-radw04](https://cloud.githubusercontent.com/assets/25423046/24129960/e9759fe4-0e20-11e7-8f8f-bbebcb6abaef.png)

**Comment by Sargul** [comment]
This is an issue with your DB2 Installation. SYSIBM.SQLTABLES is a stored procedure the jdbc driver is using to retrieve a list of tables.  It seems that you have to rebind your meta data procedures:

You can check [IBM Support](http://www-01.ibm.com/support/docview.wss?uid=swg21267177) for details.
