### ISSUE TITLE
PostgreSQL: Bit string types with length

### ISSUE THREAD

**Issue by kleinadil** [serge-rider/dbeaver#1385]
In PostgreSQL bit(n) data type represents a string of 1's and 0's but for now DBeaver shows true/false for any length of bit string types. I'd expect to see binary representation like "00000100" or just "4" as an integer.

It makes DBeaver a perfect tool for me!

**Comment by kleinadil** [comment]
I tried the latest version 4.0.2 and now it always shows "[NULL]" for bit data types regardless of its value...

**Comment by serge-rider** [comment]
Seems to be duplicate of #1322

**Comment by serge-rider** [comment]
It wasn't a duplicate. PostgreSQL has a pretty specific bit string data type support.

**Comment by kleinadil** [comment]
Great! I'm looking forward to 4.0.3 and will report if the problem still persists.
