### ISSUE TITLE
how to set time pattern support microsecond

### ISSUE THREAD

**Issue by victor0801x** [serge-rider/dbeaver#1386]
MySQL/MariaDB time, timestamp support microseconds(10^-6 sec)
I tried to set time pattern to HH:mm:ss.SSSSSS, but it didn't work well
what should I set ?
![2017-03-03 13-00-52](https://cloud.githubusercontent.com/assets/4534038/23538868/b1b51c46-0011-11e7-92b0-31c3c1f42ac2.png)
![2017-03-03 13-01-28](https://cloud.githubusercontent.com/assets/4534038/23538871/b59bd5ac-0011-11e7-8d89-cd7b841e72e7.png)

**Comment by MocniMax** [comment]
You should use **.ffffff** for miliseconds (see timestamp format).

![clipboard01](https://cloud.githubusercontent.com/assets/26117076/23543643/5c4c4f72-fff3-11e6-8ccd-8dfd21ffa1e6.jpg)

**Comment by victor0801x** [comment]
it seems not work for TIME(6) datatype
![2017-03-04 00-38-20](https://cloud.githubusercontent.com/assets/4534038/23559826/3cd2c0e2-0073-11e7-82ee-9daa30f08a1f.png)
![2017-03-04 00-37-08](https://cloud.githubusercontent.com/assets/4534038/23559832/41de0f6a-0073-11e7-832f-2b1d9d721020.png)

**Comment by MocniMax** [comment]
Yes, you are right. I tested it on db2 and it doesn't work for **time** fields only for timestamp. The SSS (or SSSSSS) returns only milliseconds.

Can it be jdbc driver related?

**Comment by serge-rider** [comment]
Yes, this is JDBC driver specific. Can't fix this from DBeaver side.
