### ISSUE TITLE
Automate import/export

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#1389]
In all of my projects I have set connections that would be useful for entire team to use. I now export all of them and put on share, then they import them.

It would be great to simplify importing/exporting projects via command line. Here are some ideas of how this could work:

```sh
#export all projects with drivers
dbeaver --export --projects '*' --with-drivers -o ~/dbeaver.dbp

#export only selected projects
dbeaver --export --projects 'General, ProjectXYZ' -o ~/dbeaver.dbp 

#export only projects starting with Project_ preffix and General.
dbeaver --export --projects 'Project_*, General' -o ~/dbeaver.dbp 

#import all projects from dbp file, overwrite any existing projects
dbeaver --import --projects '*' --with-drivers -f ~/dbever.dbp  --overwrite

#import all projects from dbp file, use specific prefix for project names
dbeaver --import --projects '*' --with-drivers -f ~/dbever.dbp  --prefix 'share_' -overwrite

#import all projects from dbp file, map input names to given names
dbeaver --import --projects 'XYZ:MY_XYZ' --with-drivers -f ~/dbever.dbp 
```

This would allow database manager to put this in a cron job and export to common share or git repository for others/new memebers. Others could use cron job or script to sync, and with given prefix to import into specific 'namespace' so that their own stuff doesn't get changed (so that they can use copy/paste or some other method to update their local projects).

Saved passwords would become a problem then if they are not to be shared. Currently connection fails if password is not given but dbeaver could prompt for it. This applies to scenario in which domain login (OS Auth) is not used.

**Comment by serge-rider** [comment]
This is similar to #1271 (additional command line processing).

**Comment by majkinetor** [comment]
Its not exactly similar, although it would be a nice addition.

I somehow missed _Open Project from File System_ option. Now, I saved project to shared location and each developer can open it from there. Each developer now can add bookmarks, sql files and new connections. Do you consider there to be any problem with that approach if they work on different things for example ? So far I observed the following:

* Working on same SQL files wont be a problem since dbeaver monitors for changes. Anything else that comes to mind perhaps in this workflow ?
* To see bookmarks of others F5 is required in running projects.
* Changing connection properties requires F5.

All looks like something I can work with. Perhaps automatic refreshing on entire project would be nice to have.

**Comment by serge-rider** [comment]
I'd propose to put your shared project under some version control (git, svn, etc). Otherwise eventually there will be many conflicts in SQL scripts and other artifacts.

You can install version control plugins thru Eclipse Marketplace in EE version or use external tools (like Tortoise) in CE version.

**Comment by serge-rider** [comment]
This feature (opening external project) is already there.
Switch to Projects view->Create new project (in toolbar)->Set location of external project.
