### ISSUE TITLE
Button bar for Results tab taking half screen after long SQL error message

### ISSUE THREAD

**Issue by jpastuszek** [serge-rider/dbeaver#1390]
I am using DBeaver to query Hive. Hive can throw a very long error messages that include stack traces etc.. This causes DBeaver UI to brake.

![screen shot 2017-03-03 at 11 51 45](https://cloud.githubusercontent.com/assets/20052/23550257/01ac9698-0008-11e7-9182-483447ab5a31.png)

It is like that since forever and it is quite a problem since sometimes you can wait long a time of a result and you can't see it in the end.

**Comment by serge-rider** [comment]
What is your OS? 
What is your DBeaver version (if it is not 4.0.2 - please update it)?
