### ISSUE TITLE
Resize toolbar butons

### ISSUE THREAD

**Issue by gjannotti** [serge-rider/dbeaver#1391]
Hi guys,

First of all I love this tool !
I'm using DBeaver 4.0.2 on Ubuntu 14.04 and I configured it to use GTK theme.

On this environment the toolbar buttons are too small and are squeezed by the window title:
![image](https://cloud.githubusercontent.com/assets/5468036/23571808/046a31f0-004a-11e7-952e-c37907657b7f.png)

There's a away to change the theme layout to increase the toolbar buttons size or add a space between the toolbar and the window title to make the toolbar buttons easier to click ?

Looks how on Eclipse JDT 4.6 there is a space between the toolbar buttons and the window title bar:
![image](https://cloud.githubusercontent.com/assets/5468036/23571861/43f5a39a-004a-11e7-993c-c31bcbc25291.png)

Regards,

**Comment by rookeward** [comment]
I'd like to second this request.  The icons are very small on a large screen - it would be good to be able to increase their size and space them out.  On my windows 10 second screen, there is a distinct overlap with the bottom of the "Active Data source" cut off.

**Comment by serge-rider** [comment]
Agreed

**Comment by serge-rider** [comment]
Please check #1971

Also you can configure scale factor for DBeaver manually.
E.g. you can add line "-Dswt.autoScale=150" in dbeaver.ini file after -vmargs line. This will scale UI in 150%.

**Comment by serge-rider** [comment]
Extra improvements of HighDPI scaling will be added after DBeaver will migrate on Eclipse Oxygen (4.2.3 or 4.2.4)

**Comment by amacfie** [comment]
> Please check #1971
> 
> Also you can configure scale factor for DBeaver manually.
> E.g. you can add line "-Dswt.autoScale=150" in dbeaver.ini file after -vmargs line. This will scale UI in 150%.

@serge-rider Where's the `dbeaver.ini` file in a Linux distribution?

**Comment by tobiasmuehl** [comment]
@amacfie `/usr/share/dbeaver/dbeaver.ini`

**Comment by tobia** [comment]
In case somebody else is using the Snap package (where `dbeaver.ini` is read-only) and needs to configure the `swt.autoScale` parameter, you can use a custom launcher script:

```bash
#!/bin/bash

# custom Hi-DPI for icons
custom_hidpi=150

vm=/usr/bin/java
base=/snap/dbeaver-ce/current
vmargs=(
    -XX:+IgnoreUnrecognizedVMOptions
    --add-modules=ALL-SYSTEM
    -Xms64m
    -Xmx1024m
    -Dswt.autoScale=$custom_hidpi
    -jar $base/plugins/org.eclipse.equinox.launcher_*.jar
)
args=(
    ${vmargs[@]}
    -os linux -ws gtk -arch x86_64 -showsplash
    -launcher $base/dbeaver
    -name Dbeaver
    --launcher.library $base/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_*/eclipse_*.so
    -startup $base/plugins/org.eclipse.equinox.launcher_*.jar
    --launcher.overrideVmargs
    -exitdata 4910006
    -vm $vm
    -vmargs ${vmargs[@]}
)

export GDK_CORE_DEVICE_EVENTS=1
export LIBOVERLAY_SCROLLBAR=0
export OXYGEN_DISABLE_INNER_SHADOWS_HACK=1

exec $vm ${args[@]}
```

The JVM executable, options and environment variables were discovered using strace. They may vary on your system:

```
strace -f -v -e execve -s 99999 /snap/dbeaver-ce/current/dbeaver 2>&1|grep execve
```

**Comment by katzda01** [comment]
How is this resolved? I've just installed DBeaver latest version on windows 11 and the icons are terribly small!

Edit: I dont have the problem anymore. Not sure if its because I had changed my laptop's resolution to a much lower value (becasue it was smaller but same resolution) so that maybe Windows doesn't scale it weirdly with other screens?

**Comment by devmi** [comment]
> How is this resolved? I've just installed DBeaver latest version on windows 11 and the icons are terribly small!

Same on the latest DBeaver CE for macOS (Version 23.3).

**Comment by rambalachandran** [comment]
Unfortunately `-Dswt.autoScale=150` doesnt work in Linux (Ubuntu) with window manager like i3. The higher the value, the lower the screen part is used. Not sure, how to make it work in the window manager. Any pointers will be of great help
