### ISSUE TITLE
Need configurable connection search_path

### ISSUE THREAD

**Issue by drewed** [serge-rider/dbeaver#1392]
Is there a way to configure the search_path for a specific PostgreSQL connection?

I find that DBeaver keeps resetting my search_path to `"$user", public` whenever I reconnect to the database, which I really do not want it to do.  I went so far as to define a bootstrap query to set the search_path to what I wanted but this only works on the first connect.  If I reconnect the same connection or close DBeaver and reopen it (causing DBeaver to reconnect), the search_path is again reset to `"$user", public`.  I find it frustrating to have to fix the search_path for every new script window or reconnection.  Is there anyway to "fix" this behavior or make it configurable?

I'm using DBeaver enterprise 3.8.5 on Mac OS 10.12.3.

**Comment by serge-rider** [comment]
This was also fixed in 4.0 version.
EE version 4.0 will be released in in a couple of weeks.
