### ISSUE TITLE
Changing "Connection type" resets the "Connection folder"

### ISSUE THREAD

**Issue by drewed** [serge-rider/dbeaver#1393]
If you change the "Connection type" on the General properties page of the Edit Connection dialog, the "Connection folder" is lost such that when you click "OK", the connection moves from it's location in the folder hierarchy back to the root connection folder.  The dialog does not "clear" the display value but if you reopen the dialog, it lists the folder as "<None>".  I presume that the change of the connection type is resetting the underlying connection configuration without updating the UI in the dialog.

It is possible to work around this bug by explicitly reselecting the correct folder in the drop-down box.

I'm using DBeaver Enterprise 3.8.5 on Mac OS 10.12.3.

**Comment by serge-rider** [comment]
This was fixed in 4.0 version.
