### ISSUE TITLE
[Question] How to reinstall an accidentally uninstalled driver?

### ISSUE THREAD

**Issue by EpocDotFr** [serge-rider/dbeaver#1397]
I accidentallly uninstalled the provided SQLite driver. Unfortunately, I'm unable to find information about how to reinstall a driver that was provided natively by BDeaver.

Of course, I already tried to uninstall/reinstall DBeaver completely but whithout success.

Any help appreciated 😃

**Comment by serge-rider** [comment]
There are two options:

1. Open driver manager, find SQLite driver, click Edit, click "Reset to Defaults" (original driver artifact must appear) then "Download/Update".
2. Delete file `~/.dbeaver4/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml` (not recommended - this drops all drivers cache).

**Comment by serge-rider** [comment]
3. If you deleted SQLite driver then you can just create new one.
Add jar files as Maven artifact `org.xerial:sqlite-jdbc:RELEASE`.
URL pattern is `jdbc:sqlite:{file}`, driver class is `org.sqlite.JDBC`.

**Comment by EpocDotFr** [comment]
Thank you for your response Serge.

1. Cannot find the SQLite driver at all because I really uninstalled it :/
2. Already done but has no effect
3. It worked! Thank you 👌

**Comment by jussihirvi** [comment]
A note to new users like me: I had a new installation and nothing to lose. So I got my deleted driver back by uninstalling dbeaver AND manually deleting AppData\Roaming\DBeaverData. Warning: this is of course drastic – it deletes all data.
