### ISSUE TITLE
v 4.0.2 Tunnel connection error

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1398]
Can't initialize tunnel
  Cannot establish tunnel
    com.jcraft.jsch.JSchException: Session.connect: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)

I use the tunneling machines (SunOS 5.8 Generic_117350-54 sun4u sparc SUNW,   Sun-Fire-880, SunOS  5.10 Generic_147440-01 sun4u sparc SUNW,Sun-Fire-V890
)without problem, e.g. with WinScp and Putty

**Comment by serge-rider** [comment]
Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) or SSH error stacktrace.
Log above has nothing to do with SSH (it says that your shell command configuration is incorrect).

**Comment by luisalb85** [comment]
There is no debug log. Only this error:

![imagen](https://cloud.githubusercontent.com/assets/26002754/23609338/ce919020-026d-11e7-8cf5-fdaba145054f.png)

**Comment by serge-rider** [comment]
Seems to be a known issue with Java8 security: http://stackoverflow.com/questions/36298394/java-invalidalgorithmparameterexception-prime-size-must-be-multiple-of-64

Basically it is not SSH problem but crypto algorithms problem. Actual error (Prime size ...) happens on server-side.
Maybe replacing standard security with Bouncy Castle (as suggested in the second reply in article above) would help. Although I didn't try this.

Another topic: http://serverfault.com/questions/785891/sftp-key-issue-java-security-invalidalgorithmparameterexception

**Comment by serge-rider** [comment]
BTW subject says 4.0.2 - does this mean that previous version worked ok?

**Comment by luisalb85** [comment]
No, never worked

**Comment by serge-rider** [comment]
As I thought.
Still have no idea how to resolve this problem from DBeaver side..

**Comment by luisalb85** [comment]
There is a workaround: execute tunnel command with putty line command before connect. Not very smart but it works and you don´t need to remenber to open the tunnel before.

**Comment by serge-rider** [comment]
Closing ad non-DBeaver bug.
Maybe some workaround will be applied later (perhaps after Bounce Castle integration).
