### ISSUE TITLE
can't edit properties

### ISSUE THREAD

**Issue by aleteddy** [serge-rider/dbeaver#1399]
hi, i'm new user of dbeaver.. when i want change properties (table,view, etc) i can not edit any field..
it's issue or i wrong ?

**Comment by serge-rider** [comment]
This depends on database.
MySQL, PostgreSQL, Oracle, DB2 have much more editable functions than most of others.

Generic driver provides ability to create/drop tables, columns, sequences, etc. But objects properties edit is not supported.

**Comment by aleteddy** [comment]
ok thanks!!

**Comment by mastrolube** [comment]
sqlite still not be editable?

**Comment by blanks-hub** [comment]
@mastrolube I have the same problem and can't edit my SQLite columns like the Data Type or default value. Really annoying.

**Comment by aspatzier** [comment]
Same for me - unable to edit table or column properties (while possible in other software like SQliteStudio)

**Comment by madarauciha** [comment]
Use Sqllite Studio to change any column property like auto increment ,datatype etc which is not possible in dbeaver .
Note:- Sqllite Studio is just an examples .
