### ISSUE TITLE
Teradata driver default port should be 1025

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#140]
This is a minor issue. I expect it's because the JDBC driver does not specify a default port when it should, and if there's no existing way for DBeaver to override this value without creating a custom driver (is there?), then it's probably better that this not be fixed/changed.

**Comment by serge-rider** [comment]
Thanks for report, I set default port to 1025. Actually it should be possible to change port in driver editor dialog (at least I can do it).
