### ISSUE TITLE
Import Project error on Project 'General' already exists

### ISSUE THREAD

**Issue by MocniMax** [serge-rider/dbeaver#1400]
Hi.

When I export all project from dbeaver 4.02. on one Windows PC and try to import only selected projects into dbeaver 4.02. on another Windows PC **org.jkiss.dbeaver.DBException: Project 'General' already exists** error is generated even General is not selected.

![clipboard01](https://cloud.githubusercontent.com/assets/26117076/23611618/646b5694-0278-11e7-9891-0abd0ef71ac6.jpg)

Same happens when I rename target General project

![clipboard01](https://cloud.githubusercontent.com/assets/26117076/23611713/b768d16e-0278-11e7-861b-fd18d184d15e.jpg)

Can you, please, check it? Thanks.

**Comment by serge-rider** [comment]
Thanks for report
