### ISSUE TITLE
mariadb?

### ISSUE THREAD

**Issue by edwardsmarkf** [serge-rider/dbeaver#1401]
hello - i notice you mention mysql but not mariadb on your main page.  does dbeaver support mariadb as well?

**Comment by serge-rider** [comment]
Sure, it does. There is a separate MariaDB driver.

**Comment by edwardsmarkf** [comment]
the [first page] says:(http://dbeaver.jkiss.org/) says:

> Free multi-platform database tool for developers, SQL programmers, database administrators and analysts. Supports all popular databases: MySQL, PostgreSQL, SQLite, Oracle, DB2, SQL Server, Sybase, Teradata, MongoDB, Cassandra, Redis, etc.

i thought it might have mentioned **mariadb** in this list.
