### ISSUE TITLE
Oracle 8 metadata read

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1402]
SELECT P.*,CASE WHEN A.DATA_TYPE IS NULL THEN 'PROCEDURE' ELSE 'FUNCTION' END as PROCEDURE_TYPE FROM ALL_PROCEDURES P
LEFT OUTER JOIN ALL_ARGUMENTS A ON A.OWNER=P.OWNER AND A.PACKAGE_NAME=P.OBJECT_NAME AND A.OBJECT_NAME=P.PROCEDURE_NAME AND A.ARGUMENT_NAME IS NULL AND A.DATA_LEVEL=0
WHERE P.OWNER='ACCESO' AND P.OBJECT_NAME='QUEST_SL_USER_MANAGER'
ORDER BY P.PROCEDURE_NAME
[933] ORA-00933: comando SQL no terminado correctamente
SELECT P.*,CASE WHEN A.DATA_TYPE IS NULL THEN 'PROCEDURE' ELSE 'FUNCTION' END as PROCEDURE_TYPE FROM ALL_PROCEDURES P
LEFT OUTER JOIN ALL_ARGUMENTS A ON A.OWNER=P.OWNER AND A.PACKAGE_NAME=P.OBJECT_NAME AND A.OBJECT_NAME=P.PROCEDURE_NAME AND A.ARGUMENT_NAME IS NULL AND A.DATA_LEVEL=0
WHERE P.OWNER='ACCESO' AND P.OBJECT_NAME='QUEST_SL_USER_MANAGER'
ORDER BY P.PROCEDURE_NAME
[933] ORA-00933: comando SQL no terminado correctamente

Fix
ALL_PROCEDURES  doesn´t exist
Solution:
SELECT * FROM ALL_OBJECTS WHERE OBJECT_TYPE='PROCEDURE' AND OWNER='ACCESO' AND OBJECT_NAME='QUEST_SL_USER_MANAGER'

Another one:
SYS.DBA_RECYCLEBIN  doesn´t exist too, Oracle 10g introduced the recycle bin.

**Comment by luisalb85** [comment]
Another:
SELECT s.*,sq.SQL_TEXT FROM V$SESSION s
LEFT OUTER JOIN V$SQL sq ON sq.SQL_ID=s.SQL_ID
WHERE s.TYPE='USER'

Problem:  column SQL_ID doesn't exist

Declares V_$SESSION and V_$SQL:

CREATE OR REPLACE VIEW SYS.V_$SESSION AS
select "SADDR","SID","SERIAL#","AUDSID","PADDR","USER#","USERNAME","COMMAND","OWNERID","TADDR","LOCKWAIT","STATUS","SERVER","SCHEMA#","SCHEMANAME","OSUSER","PROCESS","MACHINE","TERMINAL","PROGRAM","TYPE","SQL_ADDRESS","SQL_HASH_VALUE","PREV_SQL_ADDR","PREV_HASH_VALUE","MODULE","MODULE_HASH","ACTION","ACTION_HASH","CLIENT_INFO","FIXED_TABLE_SEQUENCE","ROW_WAIT_OBJ#","ROW_WAIT_FILE#","ROW_WAIT_BLOCK#","ROW_WAIT_ROW#","LOGON_TIME","LAST_CALL_ET","PDML_ENABLED","FAILOVER_TYPE","FAILOVER_METHOD","FAILED_OVER","RESOURCE_CONSUMER_GROUP","PDML_STATUS","PDDL_STATUS","PQ_STATUS" from v$session

CREATE OR REPLACE VIEW SYS.V_$SQL AS
select "SQL_TEXT","SHARABLE_MEM","PERSISTENT_MEM","RUNTIME_MEM","SORTS","LOADED_VERSIONS","OPEN_VERSIONS","USERS_OPENING","EXECUTIONS","USERS_EXECUTING","LOADS","FIRST_LOAD_TIME","INVALIDATIONS","PARSE_CALLS","DISK_READS","BUFFER_GETS","ROWS_PROCESSED","COMMAND_TYPE","OPTIMIZER_MODE","OPTIMIZER_COST","PARSING_USER_ID","PARSING_SCHEMA_ID","KEPT_VERSIONS","ADDRESS","TYPE_CHK_HEAP","HASH_VALUE","CHILD_NUMBER","MODULE","MODULE_HASH","ACTION","ACTION_HASH","SERIALIZABLE_ABORTS","OUTLINE_CATEGORY" from v$sql

Possible solution ( I'm not entirely sure ):

SELECT
	s.*,
	sq.SQL_TEXT
FROM
	V$SESSION s, V$SQL sq 
WHERE
	sq.ADDRESS = s.SQL_ADDRESS AND s.TYPE = 'USER'

**Comment by serge-rider** [comment]
This is more complicated. 
1. Package procedures list metadata is not supported by Oracle 9 and earlier. There is no workaround. The same about recycle bin. I will just remove these elements from navigator tree for Oracle < 10.
2. I'll play with sessions info reading. Outer join by address seems to be working on new oracle as good as on 8.
