### ISSUE TITLE
cockroachdb

### ISSUE THREAD

**Issue by edwardsmarkf** [serge-rider/dbeaver#1403]
hello - 

i was wondering about using dbeaver on [cockroachdb ](https://www.cockroachlabs.com/)so i asked them if it was compatable. [ here is the response](https://forum.cockroachlabs.com/t/cockroachdb-feature-request-gui-for-rdbms/266/9) i received:

>  I was able to get DBeaver connected using the generic Postgres driver, but discovered we have a compatibility issue with tables containing >200 rows. My guess is that how they're counting rows or using a LIMIT clause is something Postgres supports that we don't.

is it possible for DBeaver to support cockroachdb?

**Comment by jordanlewis** [comment]
The issue is on CockroachDB's side: https://github.com/cockroachdb/cockroach/issues/4035

**Comment by serge-rider** [comment]
I think option "Use SQL to limit results" was turned on. It is off by default. DBeaver uses LIMIT to read data only if this option is on.

It is here: 
![default](https://cloud.githubusercontent.com/assets/6398845/23666382/ed45dda6-036b-11e7-8df0-0fec4f18776d.png)

**Comment by mjibson** [comment]
For the archives: I don't think this is related to the `LIMIT` clause in a SQL query. This is a field set in the postgres protocol that cockroachdb doesn't fully support yet.

**Comment by serge-rider** [comment]
So - it still doesn't work?
It is possible di disable resultset scrolling at all (using driver settings).

**Comment by mjibson** [comment]
If it is using `LIMIT` then it will work. If it is using the postgres protocol limit field (and not a corresponding LIMIT clause in the SQL query), then it will not work. I'm curious what the `Use fetch-size` option does.

**Comment by serge-rider** [comment]
Ok.
Enabled "fetch size" makes DBeaver to use explicit fetch size in JDBC API each time it reads data. May significantly affect performance on some driver. But has no meaning for most drivers. 
Don't touch it unless you have performance issues.
