### ISSUE TITLE
Cassandra UDT displaying as Null

### ISSUE THREAD

**Issue by revelation1** [serge-rider/dbeaver#1404]
Version 3.85.  I see this was fixed in a prior version but is back

`CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;;

CREATE TYPE test.udt_citystate (
    city text,
	state text
);

CREATE TABLE test.people (
    Name text,
    date date,
    citystate FROZEN<udt_citystate>,
    PRIMARY KEY (Name, date)
);

insert into test.people (Name,date,citystate) values ('FRED','2017-07-03',**{city:'Houston',state:'Texas'}**);

select * from test.people;`

![image](https://cloud.githubusercontent.com/assets/7517411/23672786/d8129b28-033d-11e7-9e5d-864c468c170d.png)

**Comment by serge-rider** [comment]
Fixed in 4.0

![image](https://cloud.githubusercontent.com/assets/6398845/23797135/60b690c4-05af-11e7-80fc-257e9fe94a6d.png)
