### ISSUE TITLE
Copy the list of tables/columns/etc as csv/tsv

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1407]
All columns displayed, please.
Name, Schema, Nb Rows (Runstats) Status, Type, Tablespace, Table Id
Ctrl+C seem to just copy the cell where the invisible cursor is located. The invisible cursor seems to move to the last mouse click position.

![image](https://cloud.githubusercontent.com/assets/25423046/23689833/36a5b76e-03f8-11e7-91ff-23f63c0d2b18.png)

**Comment by loboaureo** [comment]
For the same reason i ask to add the "desc" command in oracle. if there is a way of do this, it could help me too.

**Comment by serge-rider** [comment]
At the moment it is not supported (you can copy only individual cells values).
Will mark as feature  request.

**Comment by serge-rider** [comment]
In 4.0.3 you can copy selected rows in tab separated format (CTRL+SHIFT+C or context menu). This format is compatible with Excel and Open/Libre Office Calc.
