### ISSUE TITLE
Couldn't RUN DBeaver with JAVA7

### ISSUE THREAD

**Issue by sgabisaad** [serge-rider/dbeaver#1408]
I had Dbeaver installed and running with JAVA8. I installed another instance of JAVA, being JAVA7 and updated the JAVA_HOME in my environment variables.

DBeaver 4.0.2 stopped running and gave error attached.

As soon as I change my JAVA_HOME to Java8 it works fine.

[1488963616705.txt](https://github.com/serge-rider/dbeaver/files/827099/1488963616705.txt)

**Comment by infectormp** [comment]
DBeaver requires Java 8 since version 4.0

**Comment by sgabisaad** [comment]
Thanks for your reply I only started using Dbeaver since 4.0.1 :)

Great DBMS and keep up the good work.

Regards
Simon
