### ISSUE TITLE
Create New Connection wizard - Generic driver won't allow Finish

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#141]
This is a minor issue.

The generic drivers do not allow the user to click `Finish` if one or more "required" fields on the `General` page have not been entered. 

On the last page of the wizard, it is not clear to the user what action is needed if `Finish` is still disabled. Either the driver should store an empty value for all required fields and allow the user to finish creating the connection (even if this connection cannot possibly ever connect), or the `Next` button should be disabled on the first page if a field there is required. The former behaviour seems to closest to the behaviour for custom drivers (at least the MySQL driver allows clicking through and hitting `Finish`).

As a very minor side note on the wizard behaviour, it seems to me that as soon as a driver has all information necessary to complete the connection, then the `Finish` button should be enabled immediately. For example, the MySQL driver requires no changes to any configuration but the `Finish` button is only enabled on the final screen. This is currently not always the case.

**Comment by serge-rider** [comment]
The only reason why "Finish" do not became enabled on the first page is not-validate connection name (which can be set only on the last page). Although DBeaver generates default connection name (based on connection settings) so potentially it is possible to enable Finish immediately.
But I'm still not sure about that..

**Comment by serge-rider** [comment]
Still thinking that a couple of extra clicks don't make much harm while showing all required options is helpful.
