### ISSUE TITLE
SQL error position with PostgreSQL database

### ISSUE THREAD

**Issue by lpofredc** [serge-rider/dbeaver#1411]
Hi, 
dbeaver is an awesome db client, thanks for that dev. My only problem is for debuging queries.

SQL error position seems to be a caracter position in dbeaver with my PostgreSQL db. Is there a way to find precisely error position like with line/caracter position off the bottom bar (or like in pgadmin). 

![selection_036](https://cloud.githubusercontent.com/assets/22891423/23711891/77bca964-0421-11e7-8088-cb1175d4bbec.png)

Thanks!

**Comment by serge-rider** [comment]
No, PostgreSQL returns only error position (character offset).
But DBeaver positions in exact query line/column (calculated from position). As far as I know pgAdmin does the same (although I didn't check last versions).

**Comment by MathieuDenat** [comment]
Hi,

I've the same request to Ipofredc. It will be very convenient that DBeaver highlight or focus on position error script (using PostgreSQL). PgAdminIII do it (version 1.22.2) by green underline and show a "point on line number".

![image](https://user-images.githubusercontent.com/24882900/43380732-74888ed8-93d2-11e8-98bc-ff87278bec7e.png)

Actually, I copy/paste my script in pgAdmin when I have trouble to debug a script.
With that feature DBeaver become really really more convenient for me (and other users who works with PostgreSQL).

I've perhaps don't see an option which permit to do it, so excuse me if it is.

Anyway, thank you for your work.
Have nice day.

PS: sorry for bad english (it's not my native language).

**Comment by serge-rider** [comment]
@MathieuDenat DBeaver already does this (sets cursor/selection on error position in the query). This feature exists for years.
What PostgreSQL driver do you use?
Could you post an example where it doesn't work?

**Comment by MathieuDenat** [comment]
I'm using "PostgreSQL standard driver" (I think it's your question?):
![image](https://user-images.githubusercontent.com/24882900/43381845-39bbdb80-93d6-11e8-925d-bba17d2db501.png)
With the same query of previous sample I have same problem:
![image](https://user-images.githubusercontent.com/24882900/43381920-74403152-93d6-11e8-88c3-d21a72c00cbf.png)
I'm running DBeaver on Debian.
Thanks a lot to help.

**Comment by serge-rider** [comment]
Thanks.
I guess that maybe it is related to localized error messages. However it works fine for Chinese and Russian languages.
Looks like in your version there is a bit different representation of Position string (extra spaces). I've updated position extraction algorithm.
Please check it in EA (https://dbeaver.io/files/ea/)

**Comment by MathieuDenat** [comment]
Thanks, for your reactivity.
The problem persist with french language, but it could'be bypass to change language.
 
![image](https://user-images.githubusercontent.com/24882900/43424707-902515ca-9450-11e8-9ab8-60eb069f785f.png)

**Comment by MathieuDenat** [comment]
Hello,
For information: bug persists with 5.1.5 and 5.1.6 version running on debian.
Problem could'be bypass to change language: launch dbeaver with "-nl xx" option to change locale
Regards

**Comment by serge-rider** [comment]
I'll add locale-independent way of error position extraction in 5.1.6.

**Comment by MathieuDenat** [comment]
Hi,
Error solved with the 5.2.0 version.
Thank a lot! ;)
