### ISSUE TITLE
Postgres schemas metadata improvement

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1412]
A simple metadata display improvement suggestion:

Please add "owner" (role that created the schema) and "description" to the list of schemas (see picture) and schema properties display.

Please add "description" to the list of roles in the "roles" tab.

![schemas_owner](https://cloud.githubusercontent.com/assets/12818651/23716168/8328ff2e-042f-11e7-8a58-6646454ce48a.png)

These would make administration ever so slightly more useful and consistent. Setting comments on schemas and users en masse (in a list) is actually quite handy.

**Comment by serge-rider** [comment]
Owner is already there (right click on table header->Configure columns).
Schema description is missing. Will add it.

**Comment by lacanoid** [comment]
Ah, wonderful!
I had no idea you could do that.
Thanks!
