### ISSUE TITLE
Import from CSV not working.

### ISSUE THREAD

**Issue by drewed** [serge-rider/dbeaver#1413]
We've recently rolled out DBeaver enterprise to our team of data treatment engineers.  A common task involves loading data delivered to our company in flat-file (CSV) format into our PostgreSQL database.

I've played with this scenario on my Mac without issue but my Windows using colleagues are having problems.  After creating a connection object for the CSV file and running the Import Table Data wizard, we're getting exceptions in DBeaver with the following message:

SQL Error: Syntax error: Encountered " <NAME> "INSERT "" at line 1, column 1.
Was expecting:
    "SELECT" ...

My guess is that DBeaver was trying to run an insert query (which would make sense in this case) but the server is rejecting the query.  We've played with various mapping options and tried this on both 4.0.2 Community Edition and 3.8.5 Server edition on my coworkers machine to no avail.

I'd like to be able to give you more detail on this than I'm able to discover at the moment so if there's a log I'm not aware of that would give more information about the import query generated by the import table data wizard, let me know.

My coworker is running Windows 10.

**Comment by serge-rider** [comment]
Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by drewed** [comment]
I figured out what went wrong with the import.  We had neglected to select the appropriate target container in the wizard so it defaulted to the CSV data source rather than the intended database connection.  Apparently, the wizard doesn't handle CSV to CSV particularly well.  I reran the import on my Mac from CSV to CSV and have attached the requested debug log.  Selecting the originally intended database table as the target _is_ working just fine.

[dbeaver-debug.log.zip](https://github.com/serge-rider/dbeaver/files/832067/dbeaver-debug.log.zip)

**Comment by drewed** [comment]
Serge, the skip column functionality does not appear to be working as the column I set to skip was included in the table anyway.

**Comment by drewed** [comment]
Clarification on my previous comment: it is possible to get the skip to take but you have to do a little hoop jumping by clicking elsewhere in the UI to get the field value to persist the change.  If you just click the drop-down in the mapping dialog and set the value to skip and then click the "OK" button, the changed value isn't saved.  Once I got it to "keep" the skip setting, the wizard did the right thing.

**Comment by serge-rider** [comment]
This seems to be MacOS-specific behavior (dialog close processed earlier than focus lost).
Will check on Mac..

**Comment by serge-rider** [comment]
This bug was fixed in #1368
