### ISSUE TITLE
Create empty table in MySQL gives error.

### ISSUE THREAD

**Issue by JorgeSivil** [serge-rider/dbeaver#1414]
Steps to reproduce:

Start creation of new table.
Set name.
Press Control+S to save.

```
CREATE TABLE nano.financier_practice (

)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_general_ci ;
```

Gives
```

SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_general_ci' at line 3
  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_general_ci' at line 3

```

mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

This is Ubuntu 16.04, x64, DBeaver version 4.0.2

**Comment by serge-rider** [comment]
MySQL doesn't support this. It is not possible to create table without columns. Most of other databases has the same restriction.

**Comment by JorgeSivil** [comment]
@serge-rider can we disable the Save button in this case (no columns) and put a message above saying "You have to add at least one column".
