### ISSUE TITLE
Rename from F2 dialog won't work.

### ISSUE THREAD

**Issue by JorgeSivil** [serge-rider/dbeaver#1415]
Steps to reproduce:

Create new table
Press F2 in the table name NewTable or right click -> rename.
When setting a new name, it will just stick with NewTable.

The way it works is to set property Table Name right above Engine.

This is Ubuntu 16.04, x64, DBeaver version 4.0.2

**Comment by serge-rider** [comment]
One saved (persisted) object can be renamed. For new objects you need to edit name.

I'll fix Rename command enablement so it will be unavailable for new objects.
