### ISSUE TITLE
[Feature Request] Column type combo change with char keys

### ISSUE THREAD

**Issue by JorgeSivil** [serge-rider/dbeaver#1417]
When creating a new column, you can't press for example V (or V-A-R) to go to Varchar.

You have to manually use mouse or down/up arrows to find the column type.

This is Ubuntu 16.04, x64, DBeaver version 4.0.2

**Comment by serge-rider** [comment]
Agreed, this makes sense. And quite easy to implement.

**Comment by JorgeSivil** [comment]
@serge-rider this is buggy, if I write 'int' it shows me the options, but no key has the effect of completing.

Example, with 'in', I select INTEGER UNSIGED with arrows, then ENTER, but the field still says 'in'

Also, the options seems to be showing completing to the right, but not in ANY place, for example, writing UNSIGNED won't pop up any option, but writing INT does.
