### ISSUE TITLE
mysql/mariadb unable to edit constraints

### ISSUE THREAD

**Issue by bsienn** [serge-rider/dbeaver#1419]
**Bug:**

Trying to add new column but unable to edit constraints.

**Comment by serge-rider** [comment]
Constraints are not editable in MySQL. But you can drop previous constraint and create a new one.

**Comment by bsienn** [comment]
Ahh I see, I used to have some x DB-manager that allowed editing. In background it overwrites the constraint delete/create. As there was option named edit constraint so I was confused whats happening.
