### ISSUE TITLE
Allow moving to column type with tab key

### ISSUE THREAD

**Issue by JorgeSivil** [serge-rider/dbeaver#1420]
When creating a new column (maybe other things also), you can't use tab to move to Column Type and/or edit it.

Steps to reproduce:

Start creation of new column
Try to change type to VARCHAR with some length (example: Varchar(20)) with keyboard keys.
You have to use mouse.

I'm very used to move around apps with keyboard, so having to use mouse all the time is very unproductive.
Maybe combine it with a shortcut to start creation of new colum.

**Comment by serge-rider** [comment]
Good point
