### ISSUE TITLE
Globally Defined Parameters

### ISSUE THREAD

**Issue by Choens** [serge-rider/dbeaver#1421]
This is a feature request.

DBeaver's support for named parameters is great. But I would love to be able to define the parameters in the script, which would make it easier to share a specific query with colleagues. For example:

    select * from t_foo where some_date is between :beg_date and :end_date ;

This will, upon execution, open DBeaver's named parameter dialog and request values for "beg_date" and "end_date". What I would like to be able to do is write something like this:

    set beg_date = '2016-01-01'
    set beg_date = '2016-12-31'
    select * from t_foo where some_date is between :beg_date and :end_date ;

Upon execution, DBeaver would interpre :beg_date as '2016-01-01' and :end_date as '2016-12-31'. The parameters dialog box could come up for confirmation, or not. I don't think I care. But being able to define the values of the named parameters would be enormously useful. 

From an implementation stand-point, I am not requesting any change in how to define the named parameters in they query and I don't think I would make this compatible with anonymous parameters.

I work in an office where the staff are transitioning from SQL Workbench/J to DBeaver and the feature I am told they miss the most from SQL Workbench/J is the ability to globally define their named parameters.

**Comment by serge-rider** [comment]
This feature is the first step towards fully functional client-side scripting (#739, #639).
You can do this:
```sql
@set beg_date = '2016-01-01'
@set end_date = '2016-12-31'
select * from film where last_update between :beg_date and :end_date ;
@echo Films updated between ${beg_date} and ${end_date}
```
For now SQL editor will ask parameter event if they were set with @set command. This can be improved later.
