### ISSUE TITLE
[Oracle] Unable to insert row in Data view of table if all column values are NULL; data export to destination table also fails

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1422]
I tried to use data export to create quick backups of a bunch of tables. One of the tables had a row where all values were NULL. After creation of the backup table and during the data transfer itself, I received an ORA-00928: missing SELECT keyword. The row export had successfully exported all rows up to the 'empty' row, but none after.

In trying to reproduce the issue I tried to insert an all-NULL row into a table using the Data tab of the table, but this also failed with the same ORA-00928.
![dbeaver_all_nulls_row_issues](https://cloud.githubusercontent.com/assets/11037075/23774963/31e13be2-058b-11e7-803c-ec1d4b838006.gif)

**Comment by serge-rider** [comment]
Thanks for report
