### ISSUE TITLE
No way to set program language

### ISSUE THREAD

**Issue by Yanpas** [serge-rider/dbeaver#1423]
Plugin and program are semi-translated to russian. I would like to use English language completely. Currently I don't see any way to do it

**Comment by serge-rider** [comment]
You can run DBeaver with command line parameter `-nl en` (command line parameters are readme.txt).
Also if you use Windows installer you can choose language there.

**Comment by Yanpas** [comment]
Thanks for help, that helped, more entries have become english, but some are still russian 
![_2017-03-10_19-03-16](https://cloud.githubusercontent.com/assets/7345761/23802452/73c26f48-05c4-11e7-9de6-de231e3c930f.png)

**Comment by serge-rider** [comment]
That's because Eclipse caches some UI elements.
You can cleanup UI settings by deleting file ~/.dbeaver4/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi

**Comment by dkfour18** [comment]
I use DBeaver4.0.2 Windows installer and choose English at the first step,but after all set up, it come out semi-translated to simplified Chinese. What's wrong? My os is win10 64bit run in traditional Chinese.

**Comment by serge-rider** [comment]
Most likely you have the same problem (try to delete workbench.xmi file).

I'm going to remove all localizations in next version. They are seriously out of date and have to be patched/reorganized.
