### ISSUE TITLE
Drivers broken after just checking them in properties

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1424]
MariaDB and Postgresql:

1. go to connection properties
2. edit driver properties
3. choose a driver and select update/download
4. cancel the dialogue so you do nothing to the driver

After you click on the edited connection or refresh it, then you get this error:

```
Can't create driver instance
  Can't load driver class 'org.mariadb.jdbc.Driver'
    java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver"
```

Also it tells you to download the driver (you already had). I think it just deleted my drivers even though I didn't tell him to do anything. A note because it may be important: While I did the steps above the database was offline.

**Comment by serge-rider** [comment]
Yes, its a known issue.

Workaround - click "Download" button (it won't perform actual download because all driver files are already in local cache).
