### ISSUE TITLE
Better error handling for DB2 on z/OS

### ISSUE THREAD

**Issue by orbanbalage** [serge-rider/dbeaver#1428]
**EDIT:**

actually it is enough to set a JDBC parameter, which is set in Data Studio by default!
`retrieveMessagesFromServerOnGetMessage=true`

So this enhancement request is to set this parameter by default for the DB2 drivers / template.

history below:

> The DB2 Driver will [return a SQLCODE and a SQLSTATE for every statement execution](https://www.ibm.com/support/knowledgecenter/en/SSEPEK_10.0.0/codes/src/tpc/db2z_sqlcodes.html).
> 
> It would be a lot more user friendly to developers if DBeaver could store these codes and states (ideally by DB2 version, as they do add/remove/change codes with new versions) and then parse the returned information. Data Studio does this currently.
> Otherwise for each error you need to look up the documentation for the error code.
> 
> For the query:
> ```
> SELECT TBNAME
> FROM SYSIBM.SYSCOLUMNS
> INNER JOIN SYSIBM.SYSCOLUMNS
> ON TBNAME = TBNAME;
> ```
> 
> Data Studio:
> > A REFERENCE TO COLUMN TBNAME IS AMBIGUOUS. SQLCODE=-203, SQLSTATE=42702, DRIVER=4.18.60
> 
> DBeaver:
> 
> > SQL Error [42702]: DB2 SQL Error: SQLCODE=-203, SQLSTATE=42702, SQLERRMC=TBNAME, DRIVER=4.18.60

**Comment by serge-rider** [comment]
I'm not sure how this is handled in z/OS but in DB2 LUW there is a special connection parameter `retrieveMessagesFromServerOnGetMessage` which makes driver to retrieve/format real error message.
Try to set it to `true` in connection (on "Driver Properties" page).
Please report about results (I'll set this parameter in default driver configuration if it will work).

**Comment by orbanbalage** [comment]
Hi, yes, that is exactly what I found - see the EDIT on the top of the post. It does work, so setting it as a default parameter would be helpful. Thanks!

**Comment by serge-rider** [comment]
Ok, thanks for info.
