### ISSUE TITLE
Create New Connection wizard - Use SSH Tunnel button does not stay ticked

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#143]
Tick the `Use SSH Tunnel` checkbox, then advance or move back a page, then return to the SSH Tunnel page. The `Use SSH Tunnel` checkbox is now unchecked, although any information entered is still retained, the text fields are still enabled, and the connection still attempts to use the connection. This is a minor UI bug.

**Comment by serge-rider** [comment]
Thanks for report
