### ISSUE TITLE
Autoclose extra result tab on error

### ISSUE THREAD

**Issue by geuss** [serge-rider/dbeaver#1430]
Hi, 
is possible to auto close (or better... choose it selecting a specific parameter) the result tab, if the execution break down?

**Comment by serge-rider** [comment]
I don't quite understand this.
DBeaver closes all extra result tabs by default. If they are not pinned and if you execute query with Ctrl+Enter (in opposite to Ctrl+/ which always opens new tab).

**Comment by geuss** [comment]
Sorry... my english is not very good! :-(
When I choose to execute a query with Ctrl+/, and it fails, an empty tab remains pinned to the Results.

I suggest to introduce a way (a Preference) to choose to autoclose empty tabs where a query execution fails.

Thanks a lot!!!

**Comment by serge-rider** [comment]
This makes sense.

**Comment by geuss** [comment]
Thanks!!!!!! :-)

**Comment by serge-rider** [comment]
![default](https://user-images.githubusercontent.com/6398845/27517599-efff25da-59d7-11e7-96bc-eb1a9c16bfe9.png)

**Comment by geuss** [comment]
Y O U  R U L E !!!!!!!
