### ISSUE TITLE
DB2 iSeries: Auto-complete didn't work properly

### ISSUE THREAD

**Issue by OSmeilus** [serge-rider/dbeaver#1432]
The auto-complete works only with direct connection to the related table.

**Example no.1:**
Select xxField1
from MySchema.Tablexx

where xxField2 = 123

Issue: I don't get xxField2 by auto-complete. When deleting the blank line between "from" and "where" the fields of Tablexx are shown.

**Example no.2:**
Select xxField1, yyField2
from MySchema.Tablexx
join MySchema.Tableyy
  on yyField1 = xxField2
where xxField3 = 123

Issue: Auto-complete works only for fields of Tablexx. But at no point the fields of Tableyy are shown.

**Comment by serge-rider** [comment]
In case of joins autocomplete works correctly only if you specify table aliases:
```sql

Select xxField1, yyField2
from MySchema.Tablexx xx
join MySchema.Tableyy yy
on yy.yyField1 = xx.xxField2
where xx.xxField3 = 123
```
