### ISSUE TITLE
[Feature request] Quick filter box, or faster access to filters

### ISSUE THREAD

**Issue by tannenzaepfle** [serge-rider/dbeaver#1433]
The process of using filters is very cumbersome - you need to right click, select the sub-menu, and click through to the filters table, click the "add" button, and then start typing.

I can think of a lot of faster filter options that would be easy to implement:
* Add keyboard shortcut to view filter table on active filter (Ctrl+Shift+F doesn't appear to be used yet)
* Allow the user to click on the empty text field instead of needing to click on the "Add" button
* If the filter table filter is empty, allow the user to start typing in the first "Include" box immediately upon launch of the filter table window.

One feature that might be harder to implement - but that would be even easier to use and is present in a number of other DB clients - would be a "Quick Filter" box on the Database Navigator tab, where entering "text" would apply a '%text%' filter. Obviously, the full filter table offers more functionality, but for 95% of my table filtering needs, this would make things faster.

**Comment by serge-rider** [comment]
Agreed, filtering should be improved.

Hint: you can use quick filter in editors. Double click on Tables/Views node. In the editor you can press ctrl+f and just start typing.

**Comment by tannenzaepfle** [comment]
Thanks - that would really help. 

I just realized a good place where a "quick filter" box could go - in the task-bar, up next to the "Active Catalog/Schema" drop-down box and the "maximum result-set size" text box. A keyboard shortcut to jump to that box also would help me on my quest to never take my hands off the keyboard (I loooove keyboard shortcuts).

**Comment by verajosemanuel** [comment]
+1 for the textbox filter for Database Navigator.
 Some other clients tend to locate textbox over database list panel.

**Comment by verajosemanuel** [comment]
is this filtering option active in 4.0.5 ?    couldn't find it in 4.0.5

**Comment by serge-rider** [comment]
No, it is still open.
Moved to 4.0.6

**Comment by g-rusev** [comment]
+1 for quick searching in the 'Database Navigator' panel.

"Toad for MySQL", (which I use for mySQL), has a good implementation for quick filtering for database objects (tables, views, triggers, etc), which is very very handy. The mySQL database I use has more than 400 tables and the quick filtering is the one of the most used features by me when it comes to a really lot of tables.

**Comment by serge-rider** [comment]
Something like this:
![default](https://cloud.githubusercontent.com/assets/6398845/25783346/91e87fa4-3363-11e7-9c90-a3720ea26ae7.png)
?

**Comment by tannenzaepfle** [comment]
Looks great! Can't wait to use it.

**Comment by verajosemanuel** [comment]
superb!!!
