### ISSUE TITLE
[Feature request] Exasol: add ability to edit scripts

### ISSUE THREAD

**Issue by UkrZilla** [serge-rider/dbeaver#1434]
Hi guys,

Please add ability to edit scripts, like:
create or replace lua script script_name ...

Now only in native ExaPlus you can do it.

Thanks

**Comment by Sargul** [comment]
Hi,

I will implement this feature. This will basically be something like Create DDL. EXAPlus does this the same way as a new tab is opened with the "CREATE OR REPLACE" statement.

As I'm currently on the road this might take some time.

Kind Regards

Charly

**Comment by UkrZilla** [comment]
Hi @Sargul 
It is cool, but if script has parametres DBeaver can't save script and proposes fill parametres in addition window . Could you please fix it?

**Comment by Sargul** [comment]
Hi @UkrZilla ,

I fear I can't do anything in the Exasol Plugin about this as ":name" is always interpreted as paramters on execution in DBeaver as long as SQL-Paramters is enabled. 
![screenshot](https://cloud.githubusercontent.com/assets/5595511/24103603/0fde7d14-0d80-11e7-9084-3b03ce685019.jpg)

@serge-rider is there a way to disable sql parameters for SQLDatabasePersistAction?

I'll open the issue again.

Regards

Charly

**Comment by serge-rider** [comment]
Please provide more details. What exactly should be changed in parameters handling? 
As far as I remember DBeaver ignores parameters in SQLDatabasePersistAction (parameters are valuable only in SQL editor).

**Comment by Sargul** [comment]
Sorry Serge,

wasn't able to verify the informations provided by the user at work. Check at home and you are right. SQLDatabasePersitAction doesn't replace named parameters. Sorry for that.

@UkrZilla you have 2 options:

- directly edit the Scripts and function in the Source view like this:
![image](https://cloud.githubusercontent.com/assets/5595511/24116190/38e766be-0da6-11e7-8f12-617efb9a2831.png)
- disable SQL parameters or set the char for named parameters to a different char than ":"

I'm closing this issue again.

Kind Regards

Charly

**Comment by Sargul** [comment]
@UkrZilla with the next version of DBeaver (4.0.7) @serge-rider  implemented a fix to not parse parameters in scripts (#1635). 

So the workaround of setting the named parameter to something other than ":".

**Comment by UkrZilla** [comment]
Hi @Sargul 
According to directly edit scripts in the Source view: it is not good idea to make it as:

DROP SCRIPT 'scriptname';
CREATE LUA SCRIPT 'scriptname';

Let's assume we are editinig script in the Source view and made mistake, then we click on button 'Persist'. DBeaver will execute: DROP SCRIPT, it will really drop script from database and then won't create script due to mistake
