### ISSUE TITLE
Error "Error [1055] [42000]: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column '01tst.t01.pol_1' which is not functionally dependent on columns in GROUP BY clause"

### ISSUE THREAD

**Issue by it19862** [serge-rider/dbeaver#1436]
**Used**  
МySql - 5,7 x64

There are two tables 

    -- Дамп структуры для таблица 01tst.tst_003_tb_01_calcul
    CREATE TABLE IF NOT EXISTS `tst_003_tb_01_calcul` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `pol_1` char(50) DEFAULT NULL,
      `idsub` int(11) DEFAULT NULL,
      `pol_3` int(11) DEFAULT NULL,
      `pol_scepka` text,
      UNIQUE KEY `id` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;
     
    -- Дамп данных таблицы 01tst.tst_003_tb_01_calcul: ~3 rows (приблизительно)
    /*!40000 ALTER TABLE `tst_003_tb_01_calcul` DISABLE KEYS */;
    INSERT INTO `tst_003_tb_01_calcul` (`id`, `pol_1`, `idsub`, `pol_3`, `pol_scepka`) VALUES
        (1, 'dog 1', 1, 1, '< ТЕКСТ _ ЗАПИСИ pol_4_zp 1>  , < ТЕКСТ _ ЗАПИСИ pol_4_zp 2>  , < ТЕКСТ _ ЗАПИСИ pol_4_zp 3> '),
        (4, 'dog 2', 2, 1, '< ТЕКСТ _ ЗАПИСИ pol_4_zp 4>  , < ТЕКСТ _ ЗАПИСИ pol_4_zp 5>  , < ТЕКСТ _ ЗАПИСИ pol_4_zp 6>  '),
        (7, 'dog 3', 3, 1, '< ТЕКСТ _ ЗАПИСИ pol_4_zp 7>  , < ТЕКСТ _ ЗАПИСИ pol_4_zp 8>  , < ТЕКСТ _ ЗАПИСИ pol_4_zp 9>');
    /*!40000 ALTER TABLE `tst_003_tb_01_calcul` ENABLE KEYS */;
     
    -- Дамп структуры для таблица 01tst.tst_003_tb_02_calcul
    CREATE TABLE IF NOT EXISTS `tst_003_tb_02_calcul` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `pol_1` char(50) DEFAULT NULL,
      `idsub` int(11) DEFAULT NULL,
      `pol_3` int(11) DEFAULT NULL,
      `pol_4` text,
      UNIQUE KEY `id` (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
     
    -- Дамп данных таблицы 01tst.tst_003_tb_02_calcul: ~9 rows (приблизительно)
    /*!40000 ALTER TABLE `tst_003_tb_02_calcul` DISABLE KEYS */;
    INSERT INTO `tst_003_tb_02_calcul` (`id`, `pol_1`, `idsub`, `pol_3`, `pol_4`) VALUES
        (1, 'dog 1', 1, 1, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 1'),
        (2, 'dog 1', 1, 2, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 2'),
        (3, 'dog 1', 1, 3, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 3'),
        (4, 'dog 2', 2, 1, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 4'),
        (5, 'dog 2', 2, 2, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 5'),
        (6, 'dog 2', 2, 3, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 6'),
        (7, 'dog 3', 3, 1, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 7'),
        (8, 'dog 3', 3, 2, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 8'),
        (9, 'dog 3', 3, 3, 'ТЕКСТ _ ЗАПИСИ pol_4_zp 9');
    /*!40000 ALTER TABLE `tst_003_tb_02_calcul` ENABLE KEYS */;

Query to group tables into one table 
    select t01.idsub, t01.pol_1, *GROUP_CONCAT(t02.pol_4)*AS*scepk 
    from tst_003_tb_01_calcul t01 
    inner join tst_003_tb_02_calcul t02*  
        ON t02.idsub*=*t01.idsub 
    group by t01.idsub

When you run the query, you receive an error: 
"SQL Error [1055] [42000]: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column '01tst.t01.pol_1' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column '01tst.t01.pol_1' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
"

**Question**  
How to get rid of the error?

![05](https://cloud.githubusercontent.com/assets/18245828/23901874/2a93c56a-08d0-11e7-958b-a1c72f3a9655.jpg)

**Comment by serge-rider** [comment]
This is not related to DBeaver 
You'd better ask this on stackoverflow.

**Comment by stopsopa** [comment]
I don't agree , that's not excuse that this is not related with DBeaver because user might have need to change `sql_mode` and then execute query. 

I hate to say that but in for example Sequel Pro or in HeidiSql on Window this is not an issue. It is possible there to run this without any issues.

```sql
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
select parent_id, sort, slug from (
	select parent_id, sort, slug 
	from tags t
	order by sort 
	limit 20
) k
group by k.parent_id
```

without adding `SET GLOBAL ...` query before query you might end up with error:

```sql
Query execution failed

Reason:
SQL Error [1055] [42000]: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'k.sort' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
And user might not necessarily want or can reconfigure database only to test queries that require temporary reconfiguration of mysql.

**Comment by leyb-opinya** [comment]
This can be solved:
You can use bootstrap queries configuration for that (in connection properties, page "General").
SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

**Comment by gitressa** [comment]
Thanks! Another way to use this in DBeaver:

1. Place the `SET SESSION ...` line in the SQL editor windows and run it
1. Get the response "updated Rows: 0"
1. Delete the `SET SESSION ...` line, and run your previously failing SQL which might now yield a result
