### ISSUE TITLE
Error log is never really cleared

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#144]
This is a minor issue. 

This may be by design, but after clearing the Error Log, any new error will cause all previously cleared errors to reappear.

**Comment by serge-rider** [comment]
Can't reproduce. Do you mean global QM view or "Execution Log" in SQL editor?
(BTW when you change QM config it brings all previous log messages back - but it is Ok, it was designed this way).

**Comment by codebling** [comment]
The global Error Log, backed by `~/.dbeaver/.metadata/.log`. 

Clearing the log removes all messages from view, but every message reappears when a new message is added to the log. 

I see now (and didn't before!) that there is also a "Delete Log" option, so this is extremely minor. I will close this.
