### ISSUE TITLE
(Mac) Dock icon disappears 

### ISSUE THREAD

**Issue by iron0012** [serge-rider/dbeaver#1441]
I use a mac, using the latest operating system version (10.12.2). 
After installing DBeaver, I check the "keep in dock" option in the OS in order for DBeaver to be easily accessible. However, after restarting the computer, the DBeaver icon is missing, replaced with a question mark. This does not happen with any other software on my computer. This behavior has been the same for at least one year, across all versions of DBeaver released since I started using it. It happens in both community and enterprise editions. It happens in both the current version of Mac OS and in the previous two versions (10.11 and 10.10). 
I wouldn't be surprised if it has something to do with the unusual way that one must install DBeaver on a mac (no installer, and one must force the OS to ignore its security settings in order to launch and use DBeaver). 

As an aside, have you considered getting a proper certificate for your mac version? I know DBeaver is open source, but I use lots of other open source software and they don't require such unusual workarounds. I have to admit, although I love DBeaver, having to essentially disable some security protocols in order to use it makes me nervous.

**Comment by serge-rider** [comment]
Good point.
Yes, signing application/dmg is planned and I hope it'll be done soon (see #95).
We already sign Windows executables and going to do the same with Mac.

Main problem is that Mac software can be signed only on Mac hardware while DBeaver build machine is PC/Linux. 
To sign DBeaver I need to:
- buy Mac developer ID
- buy specific Mac code sign certificate (it looks like standard code sign certificate doesn't work for Mac)
- buy Mac virtual hosting, 
- write a script which will perform actual sign (pass binaries from main build machine, sign them, pass them back)
- maybe something else.

All this is doable but takes time (and money).

**Comment by iron0012** [comment]
Thanks for your response, and for providing context. Excited to hear that mac DBeaver will have signing!
