### ISSUE TITLE
View number column unformatted

### ISSUE THREAD

**Issue by MocniMax** [serge-rider/dbeaver#1442]
Hi,

Sometime it is very useful to temporary display numeric value in one or more columns unformatted. 
Is it posible to add it in **_View/Format -> View As_** menu as **String** or something similar?

Regards,
Mocni Max

**Comment by serge-rider** [comment]
There is no such thing as "unformatted numeric value". Internally all numbers are just sequences of bits - I don't think you need this.

If you need default US format (no grouping, dot is floating point divider) then you can change locale in data format settings or change number format settings manually.

**Comment by MocniMax** [comment]
Hi Serge,

I meant it would be nice to be able to optionally show selected numeric columns without grouping characters and not to change Data format in Profile because it effects all numeric presentations.

But don't bother with this, I just found I can do the same by using Number radix. I should search all possible options before posting here  :grin: .

Thanks.
