### ISSUE TITLE
DBevaver is missing all connections and SQL scripts file !

### ISSUE THREAD

**Issue by llnk** [serge-rider/dbeaver#1443]
So basically yesterday I hibernate my Windows 7, and today when I opened again my DBeaver I can't find anything: all connections and (most important) all my SQL script are gone!

Please what can I do to restore or to find again this files? In which folder are SQL scripts saved?
ATM i don't have admin permission on this windows. 

In my dbeaver install dir I have a dir  "\workspace\General\" that only contains a single ".project" file of 1KB

DBeaver 3.8.2

**Comment by serge-rider** [comment]
By default DBeaver workspace located in `<user-home>\.dbeaver` directory (`.dbeaver4` for version 4+). On windows 7 it is `c:\Users\<your-id>\.dbeaver`.
Check this folder.

**Comment by llnk** [comment]
I don't have perms to access `<user-home>`. I have downloaded dbeaver portable in my desktop and running it from there. Probabily dbeaver didn't have perms either to write in that folder...

In any case today i lost all files. It was saving it since 2 months without problems

**Comment by serge-rider** [comment]
Wow. That's quite unusual (most of program won't even start if you don't have permissions to your own home folder). DBeaver wasn't tested in such aggressive environment.

However if you start it with `-data <workspace-path>` parameter then it still should work.

**Comment by llnk** [comment]
Which workspace-path should I give?

**Comment by serge-rider** [comment]
Any folder where you can write (in corporate world it is quite typical that you can write only in your home folder - but in your case this is more tricky).

If you did run DBeaver without -data parameter and user home is not accessible then I have no idea where it could be. Maybe somewhere in temp folder.

Run `echo %HOMEPATH%` command. It will print default home folder location.

**Comment by llnk** [comment]
`echo %HOMEPATH%` returns:
`\Users\<myname>` (without specifying any drive, sigh)

In any case I think today something happened, since I saw in my portable dbeaver folder install that just today he created a folder named "workspace". Probabily today for some reason the perm to access my home folder was denied and he created this folder inside the install dir.

So probabily my files are inside my home folder but i can't access them. I will try to run from a bootable usb to get them

**Comment by llnk** [comment]
@serge-rider: thanks serge I understood the problem.

Yesterday the permission policy of my company changed: all permission of my homepath were removed, so DBeaver couldn't access to that data. I recovered the .dbeaver containing all my scripts and now I am using -data argument to change the workplace

Thank you

**Comment by serge-rider** [comment]
Great

**Comment by BrusJan** [comment]
Happened to me too. I'm not aware my company's policies have changed. I can see all the connections and scripts in my .dbeaver4/General folder. DBeaver starts normally but does not show any connections. All the scripts i had previously open reported the file is no longer existing so i had to close the tab. Launching DBeaver with -data "C:\Users\xxxx\.dbeaver4" parameter helped to load scripts and connections, but the postgre driver reported an error:
Error resolving driver libraries
Reason:
Error resolving dependencies

Then it prompted me to download it which upon confirmation resulted in this error:
Driver file download failed.
Do you want to retry?
Reason:
Maven artifact 'maven:/net.postgis:postgis-jdbc:RELEASE' not found

Now i need to resolve the driver error and I'm fine
