### ISSUE TITLE
SQL formatter handling backtip quotes in MariaDB/MySQL SQL statements

### ISSUE THREAD

**Issue by l00tr** [serge-rider/dbeaver#1444]
I have a question about the SQL formatter. The overall output is very nice formatted, but when working with SQL statements for MariaDB/MySQL, I've recognized that the SQL Formatter inserts spaces between the backtip quote character ` and the identifier name.

For example for
```
CREATE TABLE `test` (
            `id` BIGINT,
            PRIMARY KEY(
                `id`
            )
        );
```
the formatter will put out
```
CREATE TABLE ` test ` (
            ` id ` BIGINT,
            PRIMARY KEY(
                ` id `
            )
        );
```
When trying the formatted SQL statement, MariaDB returns the error (as to be expected):

> Error Code: 1103. Incorrect table name ' test '

Other DBMS are not affected as they use double quotes, e.g. PostgreSQL or Oracle.

Is there a way to prevent the insertion of additional spaces, e.g. by configuration? Or maybe it is a bug?

**Comment by serge-rider** [comment]
Formatter shouldn't do that. At least in recent DBeaver versions.
What database driver do you use? (this is important because of MySQL-specific quotes characters).

**Comment by l00tr** [comment]
I'm using MariaDB 10.x and the JDBC-Driver org.mariadb.jdbc:mariadb-java-client:1.5.8 at the moment. 
I could try with MySQL and its jdbc driver as well and report back what happens there.

May it cause troubles when several jdbc-drivers for different databases (Oracle, PostgreSQL, H2, MariaDB) are in the (runtime-)classpath?

**Comment by l00tr** [comment]
Because of your question I've found my (thought-)error. I had no active connection to the database. After openening the connection, the formatting result looks fine, no more extra spaces. 

I was too much into hibernate which allows to define the used database dialect and export a DDL without an active connection.

Anyways, thank you very much for your help and your great tool!

**Comment by serge-rider** [comment]
Ok, thanks for info.
