### ISSUE TITLE
Show null value in result text presentation

### ISSUE THREAD

**Issue by MocniMax** [serge-rider/dbeaver#1445]
Hi,

When SQL result is shown as Grid, the null values are shown as [NULL] what is great.

Is it possible to show the same in Text presentation too? It is pretty neccesseary to have it for documenting purposes (currently I am adding NULL manually in each documented SQL result).

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/24073597/b6219cfa-0c0a-11e7-973a-cc5a31cfdac0.png)
![default](https://cloud.githubusercontent.com/assets/6398845/24073602/c9b27c94-0c0a-11e7-9ba6-f59273e5dce4.png)

**Comment by nickklaskala** [comment]
how does one do this in the grid?  both blank and nulls show as blank in the grid.

**Comment by MocniMax** [comment]
It should show by default.
You can check is its representation configured in Grin Configure booleans view - 'Editors'

![image](https://github.com/dbeaver/dbeaver/assets/26117076/20ebb439-b9f7-43ba-957a-4d6e76371ff4)

![image](https://github.com/dbeaver/dbeaver/assets/26117076/f265a456-0990-46db-93ef-504f71d59d39)

**Comment by emanueol** [comment]
1. where is the option to enable display (null) on TEXT results ?
2. and hopefully this is global option agnostic of specific connection (as @serge-rider shows on its [screenshot](https://github.com/dbeaver/dbeaver/issues/1445#issuecomment-287554290)) ?
