### ISSUE TITLE
DBeaver eclipse plugin automatically opens first project in Project Explorer list during startup

### ISSUE THREAD

**Issue by l00tr** [serge-rider/dbeaver#1450]
I've recognized that, probably caused by the DBeaver eclipse plugin, the first project in the Package Explorer project list is automatically opened during eclipse startup if it was closed before. Without DBeaver the project is not opened automatically.

I've tested this with a fresh setup (Eclipse + workspace) as well to exclude side effects by other plugins or a messed up workspace. 
I've used the following versions for testing under Windows 10:
- Eclipse Neon.2 Release (4.6.2) Build id: 20161208-0600 (Eclipse IDE for Java Developers package)
- DBeaver 4.0.2 as eclipse plugin (core components only) installed using the Eclipse Marketplace
- fresh workspace with 2 default/fresh gradle projects (using new gradle project wizard generating default test project)

**Comment by serge-rider** [comment]
It opens not the first but the active project. You can change current active project in DBeaver "Projects" view.

Active project is used to display contents of database navigator and project explorer views.

**Comment by l00tr** [comment]
Thank you very much for the clarification, now I understand the behavior. 

There is no way to turn this off, i.e. have no active DBeaver project at all, right?

**Comment by serge-rider** [comment]
Yes, I'm afraid so.

**Comment by l00tr** [comment]
Thank you very much again. I've found a viable way for me to go along with my usage of projects and working sets: just create an empty eclipse project with no content in a separate working set and make this one the DBeaver active project when no other project requires DBeaver.

**Comment by serge-rider** [comment]
Yep, creating separate project for DBeaver makes sense.

**Comment by tylla** [comment]
I would like to request this behavior to be changed.

It would be nice if DBeaver would check if the active project is otherwise closed and do not attempt to open it. At least not until I change to the DBeaver perspective.

Should I file a separate bug report (as I consider this a bug) or should we keep this ticket for this purpose?
