### ISSUE TITLE
[future request] Drivers management

### ISSUE THREAD

**Issue by annadndann** [serge-rider/dbeaver#1452]
I use Dbeaver to connect with different databases, some of them are the same type of database but different version (like many Vertica databases, versions 7.1, 7.2, 8.0...). It means they use the same type of connection, but different external driver. It would be great to use driver specific for connection instead of for the type of database, so I don`t have to add and remove jars when I switch to another project. Now when I change driver in one connection all others become to share the selected driver.

**Comment by serge-rider** [comment]
You can create as many drivers as you need (each with different set of jars).
Main menu Database->Driver Manager->New.

**Comment by annadndann** [comment]
Thanks for response! Indeed, that helps :) and sorry for my lack of knowledge...
