### ISSUE TITLE
Can't connect to oracle XE

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#1453]
I am using Windows 10 and latest dbeaver CE.

I get this error when connecting to local XE service:

```
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-12705: Cannot access NLS data files or invalid environment specified
```

This is specific to Dbeaver, sqlplus and SQL Developer can connect without any problems. This connection worked on older versions of EE, I didn't touch it 6 or so months.

NLS_LANG is checked and it seems OK (otherwise SQL Developer would complain too).

Any ideas ?

**Comment by pemmasanikrishna** [comment]
Once check if this solves your problem
[ora-00604-ora-12705](http://stackoverflow.com/questions/1629327/ora-00604-ora-12705)

**Comment by majkinetor** [comment]
No, nothing helps. Like I said, problem is specific to dbeaver, it works in sqlplus / sqldeveloepr.

**Comment by serge-rider** [comment]
sqlplus is native application and uses OCI, SQL developer is shipped with a bunch or Oracle drivers, NLS packages, XML drivers, etc (DBeaver can't do this because of Oracle license restrictions).

I'm still pretty sure that this problem is a result of some misconfiguration and/or driver jars.
What exactly Oracle driver (and other jars) do you use?

**Comment by majkinetor** [comment]
Using ojdbc7.jar as a driver, no other jars.
Note that only my local XE db doesn't work. I can connect to remote enterprise db's without a problem.

**Comment by bokanebo** [comment]
I faced the same problem on brand new Win 10 with ODAC installed as the only one component from Oracle. Yesterday, I changed regional setting on that computer. So remembering that, I changed back date/time/num format from Serbian to English and everything is working fine.
Additional info: Set English format and start DBeaver. All your connections to Oracle will work until you restart DBeaver even if you change format during that session.

**Comment by habamax** [comment]
for me `dbeaver.exe -nl en` solves the issue

**Comment by serge-rider** [comment]
@bokanebo @habamax Thanks for info.

**Comment by habamax** [comment]
Actually, I have this bug only with `ojdbc7.jar`.
I have tried dbeaver with `ojdbc8.jar` and it works for me without `dbeaver.exe -nl en`.

**Comment by majkinetor** [comment]
I confirm it works with `-nl en`. Thanks @habamax

**Comment by abetobing** [comment]
2019 and i still read this.
For Mac users out there, go to `/Applications/DBeaver.app/Contents/MacOS`
Start dbeaver with `./dbeaver -nl en`

**Comment by demolaokesola** [comment]
> for me `dbeaver.exe -nl en` solves the issue

This also solved the issue for me.

**Comment by dmxunlimit** [comment]
Add following two properties to /Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini
-Duser.language=en 
-Duser.country=US

**Comment by Palshyn46** [comment]
@dmxunlimit thank you. That works for me without changing system settings!

**Comment by ItsCosmas** [comment]
> dbeaver.exe -nl en

Thank you, this works and I don't have to use `dbeaver.exe -nl en` everytime

**Comment by Harshal-Desale** [comment]
> -Duser.language=en
> -Duser.country=US

It worked for me. But not sure why I was getting this issue
