### ISSUE TITLE
find/replace is buggy

### ISSUE THREAD

**Issue by guyfromwy** [serge-rider/dbeaver#1454]
I'm attempting to use find/replace to replace the "\n" character. RegEx is checked. If I use the find/replace function (ctrl-F), I will get an error saying "Incompatible line delimiter near index 5" (or whatever character position the carriage return is at). If I use the Search function (ctrl-H), weird things happen altogether. It's hard to explain, but it appears to work, then lines of text appear and disappear and overall functionality is affected until I restart DBeaver.

I have tested this on version 4.0.2 on two separate Windows 7 systems. I could not find any other bug reports with this issue, but I apologize if it is already posted somewhere.

BTW, thanks for your hard work on this top-notch tool. We are migrating to it from SQL-Developer and considering replacing Toad, as well.

**Comment by serge-rider** [comment]
This is Eclipse platform issue: http://stackoverflow.com/questions/6619851/remove-empty-lines-in-eclipse-code-editor-by-find-replace-ctrlf
Workarounds:
- Use `\R` instead of `\n` to replace any linefeeds. 
- Convert file linefeeds to UNIX (in File menu) and use `\n`

**Comment by rubabkazmi1** [comment]
find & replace tab add copied line in find field , I want to add it is replace with automatically to speedup working, is there any way to do it ?
