### ISSUE TITLE
DBeaver Enterprise	checks for updates incorrectly

### ISSUE THREAD

**Issue by igortwago** [serge-rider/dbeaver#1458]
When DBeaver Enterprise checks for updates it shows new features of Community Edition 
![check_for_updates](https://cloud.githubusercontent.com/assets/23337617/24103077/d0fa56d4-0d86-11e7-9e18-c8c86aba1695.png)
, and if "Update" button is pressed, no updates are found. 
![no_updates](https://cloud.githubusercontent.com/assets/23337617/24103081/d67393dc-0d86-11e7-9aea-fe48483caeb1.png)

**Comment by serge-rider** [comment]
Yes. This will be fixed in the next EE version release (planned on March 30).
