### ISSUE TITLE
call to xpath function return unexpected null/empty result on postgresql 9.3.15 

### ISSUE THREAD

**Issue by laurentleseigneur** [serge-rider/dbeaver#1459]
when calling this sample query picked here https://www.postgresql.org/docs/9.3/static/functions-xml.html from postgresql official documentation,

 `SELECT xpath('./status/text()' ,'<?xml version="1.0" ?><response><status>SUCCESS</status></response>');`

result in dbeaver 4.0.2 on max osX installed with brew is

> 
> xpath 
> ------
>       
>      

seems to be empty or null

while result using psql on same postgres instance with same query is 

>    xpath   
> -----------
>  {SUCCESS}
> (1 row)

postgresql (docker version) version given by 

`
select version();
`

is:

> 
> version                                                                                        |
> -----------------------------------------------------------------------------------------------|
> PostgreSQL 9.3.15 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit |

**Comment by serge-rider** [comment]
This is a bug in array value handler (PostgreSQL returns xpath expression result as array of strings).
Thanks for report.
