### ISSUE TITLE
Cannot run SELECT .. FOR UPDATE query

### ISSUE THREAD

**Issue by basteln3rk** [serge-rider/dbeaver#146]
Because dbeaver automatically adds a limit clause to SQL query, it is not possible to run this query in dbeaver:

```sql
select * from innodb_deadlock_maker where a = 0 for update;
```

Error message:

![screenshot_2016-01-04_11-32-51](https://cloud.githubusercontent.com/assets/1027746/12087888/e80f8d5a-b2d6-11e5-9c7b-a5108d637e5d.png)

In the mysql terminal, this query runs just fine, since no LIMIT clause is appended

(this problem occurs on version 3.5.8)

**Comment by r-richmond** [comment]
Try changing the limit to 0.

![image](https://cloud.githubusercontent.com/assets/9246654/12096324/6e7d97fa-b2c9-11e5-9678-fc4464b18075.png)

**Comment by codebling** [comment]
@r-richmond nice workaround! 

I'm preparing a fix.

**Comment by codebling** [comment]
The fix also works for `LOCK IN SHARE MODE`.

**Comment by serge-rider** [comment]
BTW standard workaround for all problems with explicit LIMIT is to disable query modifications in preferences. Just disable "Use SQL to limit fetch size" option:
![rs-limit-config](https://cloud.githubusercontent.com/assets/6398845/12221576/649ae3fe-b7b1-11e5-86c5-9604093dd88b.png)

**Comment by serge-rider** [comment]
SELECT .. FOR UPDATE issue was fixed.
Other LIMIT problems should be tracked in different issues.

**Comment by codebling** [comment]
@serge-rider Ok if I open a new issue for the issues discussed in the PR?

**Comment by serge-rider** [comment]
Sure, it is always ok to open new issues if they are reproducible and/or make sense.
