### ISSUE TITLE
transaction fickleness

### ISSUE THREAD

**Issue by jeffmann131** [serge-rider/dbeaver#1460]
Am fairly new to SQL and to dBeaver. Am operating using MySQL server. When adding new rows to a table then save, all appears to be OK. However, when I close the table then re-open often the entered rows are gone, and sometimes there are multiple duplications of rows. This is such a frequent issue it is impossible to use the system. I thought transactions were supposed to be 'atomic'. Is there something I am doing wrong? thanks

**Comment by serge-rider** [comment]
Not sure I quite understand this. Probably you are working in transactional mode and do not perform explicit commit/rollback. Switch to auto-commit mode (there is a button on main toolbar, next to Commit/Rollback buttons) and see how it comes.

**Comment by jeffmann131** [comment]
Serge - thanks shall give it a try - Jeff
