### ISSUE TITLE
Read-only Redshift connections are not really read-only

### ISSUE THREAD

**Issue by noamCClearly** [serge-rider/dbeaver#1461]
Redshift connections that are marked as "Read-only" will not block DML operations (INSERT/UPDATE/DELETE) on the database tables. This behavior was observed both in Linux and MacOS (I didn't check Windows). The workaround is to use the Postgres driver for Redshift connections that must be marked as Read-only.

**Comment by serge-rider** [comment]
This feature must be supported by JDBC driver/database. Otherwise read-only flag doesn't make much sense.
