### ISSUE TITLE
Oracle permissions

### ISSUE THREAD

**Issue by pyhedgehog** [serge-rider/dbeaver#1463]
To be consistent with #1067 it would great to add same tab for oracle driver too.
In Oracle permissions can be retrieved from `all_tab_privs` view (and alike - `user_tab_privs`, `dba_tab_privs`).

**Comment by serge-rider** [comment]
Table privileges tab was added.
Users/roles cross references and privileges tab UI was improved.

**Comment by kiravi** [comment]
Oracle issue:

1. Let us say I am default user under schema (a).
2. Let us say there is table under schema (b) under which there is a table (x) --> b.x where I am granted all privileges insert/delete/select/update.  I can go to that tables and see Grants in oracle sql developer. When I open the table and click Privileges it errors out.  Why is that?
I am on 4.0.4 enterprise edition.

**Comment by serge-rider** [comment]
You can check what exact query DBeaver executes in Query Manager view. 
This may be a bug with wrong schema but I can't reproduce that. Please give me a bit more details.

**Comment by kiravi** [comment]
When clicking on Privileges tab on a table you get an error as mentioned above:

The query being executed  is:

SELECT p.*
FROM DBA_TAB_PRIVS p
WHERE p.OWNER=**<OWNER_NAME>** AND p.TABLE_NAME =**<TABLE_NAME>**

Now the owner seeking this not the same as the table's actual owner name, but has completed access to the table READ/WRITE/SELECT etc.   

We do not need DBA privileges to check permissions:

If you run:
SELECT p.* FROM  table_privileges p
WHERE p.OWNER=**<OWNER_NAME>** AND p.TABLE_NAME =**<TABLE_NAME>**

you can see all the privileges there for the grantee who is querying this.  Why can we not use this?

**Comment by serge-rider** [comment]
`table_privileges` contains privileges only for current user.
But you are right, we can use it if `DBA_TAB_PRIVS` is not accessible (i.e. you are no DBA).

**Comment by serge-rider** [comment]
I'll use ALL_TAB_PRIVS for non-DBA users. Also I'll add privileges tab for views.
