### ISSUE TITLE
How to connect to MS SQL Server database on different domain?

### ISSUE THREAD

**Issue by osrojas** [serge-rider/dbeaver#1464]
Hi,

I am trying to have Aqua Data Studio replaced with DBeaver. However, I am not able to connect to a database that I can connect to just fine in Aqua Data Studio. My username originates from a domain that differs from the domain of the database.

Using the setup in the attached picture in ADS, it connects just fine. On DBeaver, I encounter the error _"Login failed. The Login is from an untrusted domain and cannot be used with Windows Authentication."_ 

Is there a way to fix this issue in DBeaver so I can connect successfully? Thanks!

![aqua data studio](https://cloud.githubusercontent.com/assets/25090143/24167138/aa0b2eb4-0e43-11e7-800a-a5c7a6201c4f.png)

**Comment by osrojas** [comment]
Any ideas?

**Comment by serge-rider** [comment]
This is not DBeaver-specific issue. It is more about JDBC driver and SQL Server. 

Check these topics:
http://www.orsburn.net/2013/01/connecting-to-sql-server-with-jtds.html
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/9634867b-b806-4304-8034-e429bbed4ac0/how-to-connect-to-sql-server-with-creadentials-from-another-domain-with-ssdt?forum=ssdt

**Comment by osrojas** [comment]
Thanks for pointing me in the right direction Serge. It helped me troubleshoot and eventually solve the problem.

For reference, I used the Windows Credentials method outlined in the link below.

https://www.mssqltips.com/sqlservertip/3250/connect-to-sql-servers-in-another-domain-using-windows-authentication/

Thank you and the community of developers for such a great product!

**Comment by reeeno** [comment]
This happened to me as well as we have environments set up in different domains. I found a solution without runas or using Windows Credentials method mentioned above (as it's disabled by system admin in my organization).

When setting up a new connection using jTDS driver, under General tab, enter the user name as is without domain. Enter password associated with it. Under Driver properties tab, change DOMAIN to your domain, change USENTLMV2 to "true", and change USER to your user name. This allowed me to connect to database from any domain within my organization.
