### ISSUE TITLE
Feature Request: keyboard shortcut to move cursor to the query box in Data view

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1466]
Apologies if this already exists, but I think it'd be really helpful if when the Data view was opened for a table, we could press a keyboard combination to move the cursor into the text entry field at the top (to the right of the table name) where we can enter WHERE clause criteria.

Often when opening a table in Data view the first thing I want to do is to filter the data displayed, e.g. by typing into the filter code field something like:

salary > 100

Similar to how in web browsers there is e.g. Ctrl+L to move the cursor to the address bar so that you can start typing a URL.

**Comment by serge-rider** [comment]
Agreed.

**Comment by serge-rider** [comment]
It'll be CTRL+SHIFT+F (by default). 
It switches focus to filter editor and back to data editor (grid).
