### ISSUE TITLE
Export TableData to CSV quotes numbers and not strings

### ISSUE THREAD

**Issue by petrvalkoun-gooddata** [serge-rider/dbeaver#1469]
See below example of exported data to CSV with quotes enabled:

2016-01-12|40|1370|||||"41860"|"43-6014.00"|CA|SAPX||SAN MATEO|USA|ST|"0"|

**Comment by serge-rider** [comment]
DBeaver quotes values in CSV only if:
1. Value contains tab, line feed character or cell delimiter
2. Column has string type but value starts from a digit (quote says that this values is a string and avoids reformatting in Excel/Calc)

**Comment by Moorhed** [comment]
Is there a way how to avoid quotes for number in string column? Or maybe add such feature? I ahve tried some settings in Export wizard but without success.

**Comment by JungWonYong** [comment]
> DBeaver quotes values in CSV only if:
>    Value contains tab, line feed character or cell delimiter
>    Column has string type but value starts from a digit (quote says that this values is a string and avoids reformatting in Excel/Calc)

hmm.. Is there any way to export string column as quoted and numeric column as not quoted?
Some columns of my database are changed value quote dynamically, I have to check almost of all large data has over 80 columns. (Diff after remove quote is not good in my case.)
Any Idea?
