### ISSUE TITLE
Working in full screen (not hafe screen)

### ISSUE THREAD

**Issue by ffblanch** [serge-rider/dbeaver#1470]
Hi 
First of all, you make a **awesome** job and DBEAVER is great tool.

We work with many very long SQL and big results set. We need scrolling a lot of time. Is it possible to editing the SQL full screen and switching automaticaly to result set full screen after running ? (and go back to editing full screen ...) The half screen mode is not optimized for that usage.

**Comment by serge-rider** [comment]
Thanks)

You can double-click on results tab and it will be maximized/restored (or do the same thru tab context menu).
And you can maximize/restore SQL editor by pressing F6 (or again by context menu).

**Comment by ffblanch** [comment]
Yes i know!
It could be very interesting to have automatic option or one shortcut key for emulate double-click on results tab. Many of my teammates prefere WinSql only for this option

**Comment by serge-rider** [comment]
Agreed, this makes sense.

**Comment by serge-rider** [comment]
By default it'll be SHIFT+F6. You can redefine it in preferences.

**Comment by ffblanch** [comment]
**Wow !** Thanks Serge
