### ISSUE TITLE
Chosing "Flat files (CSV)" connection charset

### ISSUE THREAD

**Issue by vser35** [serge-rider/dbeaver#1471]
Hello

Currently if I want to connect to a folder with CSVs encoded with UTF-8 I have to add a new custom property `charset` with value `UTF-8` (as described [here](http://csvjdbc.sourceforge.net/doc.html)). Otherwise only ANSI files are read correctly.

It may be useful to add a drop-down list with `charset` property (and maybe using `UTF-8` as default value).

**Comment by serge-rider** [comment]
Default CSV encoding depends on your local system language/encoding. 
So making it UTF-8 will solve problem with UTF-8 encoded CSVs but may break CSVs in national encodings.

As for me I would restrict all non UTF encodings at all, they are ridiculous in 2017. Unfortunately life is complicated.
So I'd prefer to leave things as is.

**Comment by vser35** [comment]
My suggestion is to explicitly show `charset` property in the CSV driver settings with the default value depending on system settings but letting a user to change it using a drop-down list. Currently the `charset` property is not listed when a new CSV connection is being set up so to change the behavior we have to look at the driver's documentation which is not very convenient.

**Comment by serge-rider** [comment]
That would be a good solution. Unfortunately csvjdbc driver doesn't provide list of supported properties thru JDBC API. That's why property list is empty.
I'll see what I can do..

**Comment by vser35** [comment]
Thank you.

As the csvjdbc documentation says, 
> See the Java [Charset](http://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html) documentation for a list of available character set names.

So maybe the solution is to provide an editable drop-down with the standard charsets listed in Java documentation.

**Comment by serge-rider** [comment]
After all I've made trivial fix. Charset property will be visible in driver settings, default value is UTF-8 (as you proposed in the beginning). It is better than OS-specific implicit charset. 
Dropdown with charset list implementation is complicated.
