### ISSUE TITLE
Sort by Column not working in Table Edit

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#1473]
Using Dbeaver 4.0.3, I wanted to see all the timestamp types in a table's schema (ibm db2). I thought clicking on the column-header would sort the grid so that all timestamps would be grouped together, but the column sort didn't work:
https://youtu.be/LQShhOHeS24

Not a huge problem, but I thought I'd report it.....

**Comment by serge-rider** [comment]
This is a bug, thanks for report.
