### ISSUE TITLE
paste from excel in an existing/new line

### ISSUE THREAD

**Issue by verajosemanuel** [serge-rider/dbeaver#1475]
A feature I use every day, copy a column or a bunch of lines from excel, and paste on a column or paste in a new line.

Column is updated and/or new lines are added.

**Comment by serge-rider** [comment]
You can do this by using "Advanced Paste" function (CTRL+SHIFT+V).

**Comment by verajosemanuel** [comment]
Not really. Adding a new line at the end and using "Advanced Paste" just pastes the first one line. (i've copied 15 lines).

Related to this, adding a new row to last line, the new row is "inserted" before last line. Wouldn't it be a better behaviour to add lines after?

**Comment by serge-rider** [comment]
Yep, advanced paste doesn't create new rows. It only overwrites existing values.
Will mark as enhancement.

**Comment by serge-rider** [comment]
Changes will be tracked in #1474
