### ISSUE TITLE
DB2 z/OS problem with 4.0.3

### ISSUE THREAD

**Issue by DB2User** [serge-rider/dbeaver#1476]
4.0.2 was working fine. I updated to 4.0.3 and now get the following error:

com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10214][10050][3.68.61] java.util.Properties object passed to java.sql.Driver.connect() cannot be overridden by URL: jdbc:db2://aaa.bbb.ccc:1234/AB23RTS1:retrieveMessagesFromServerOnGetMessage=true;emulateParameterMetaDataForZCalls=1;. ERRORCODE=-4461, SQLSTATE=42815

**Comment by serge-rider** [comment]
This seems to be side effect of #1428 fix.
Try to remove retrieveMessagesFromServerOnGetMessage parameter (or change its value).
If this will help I'll update/revert this fix.

**Comment by DB2User** [comment]
On 4.0.2 I can choose Edit Connection, go to Connection settings -> Driver properties, and remove the property 'retrieveMessagesFromServerOnGetMessage' and it works fine. On 4.0.3, if I remove that property it is removed from the grid but when I exit the dialog box and go back in, the property is back again. Even though I remove it, it comes back again. That property is the problem, because on 4.0.2 I got the same error message, and once the property was removed (and there, it stayed removed), I was connected with no problems. For some reason in 4.0.3 even though you tell it to remove, it does not.

**Comment by serge-rider** [comment]
This is because this property is provided by driver configuration. You can't remove it but you can change its value.

Try this: open connections editor, click on Edit Driver Settings, switch to Connection Properties tab, remove retrieveMessagesFromServerOnGetMessage property, click ok. 
Then remove this property from connection itself.

**Comment by serge-rider** [comment]
BTW this property was added only in 4.0.3. And I still not sure what to do with it. Just remove? (as apparently it leads to problems in some environments - probably depending on driver version).

**Comment by DB2User** [comment]
Ok, so I did as you suggested and removed it from the driver settings. That worked. However, when I exit DBeaver and go back in, the property is back again. I have to go back into driver settings and remove it again. It is not staying gone.

**Comment by serge-rider** [comment]
This looks like a bug. I'll create another issue for that.

However - I think that in your case problem can be solved. According to error message you have retrieveMessagesFromServerOnGetMessage parameter right in the connection URL. And driver says that you can't have it in both URL and properties. Try to remove it from URL pattern.

**Comment by DB2User** [comment]
That did it! I removed it from the URL and it was fine. I quit the program and went back in and it still worked, even with the property set in the property grid. Thanks for your help!

**Comment by serge-rider** [comment]
Good, thanks for info.
