### ISSUE TITLE
Prompt for a new script name

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#1477]
This is a small usability improvement suggestion:

When creating a new sql script/editor, the app should prompt user for the script name and present a reasonable default, so that the prompt can be very easily confirmed with enter.

Right now the user has to go hunting for the script in the projects tab to rename it to something more sensible than, say Script-5. This is further complicated by the fact that sql tabs themselves are small so it's hard to see the new script name and one has to mouse over it to see the actual script name. 

Autoselecting the newly created script in projects tab with the big blue selection would help user to find it, too.  Perhaps selecting the appropriate thing in the projects tab when focusing different sql tabs would be a way to go and this should be in another issue.

All this is a bit tedious, so the user didn't really bother with naming of the scripts when creating them and ended with a bunch of scripts named "script" :(

This little piece of information (script name) is often known in advance (as in "I want to do_something.sql")  and it would benefit the app to capture it at the script creation time, should the user prefer something other than the default. It avoids the above distractions related to later renaming.

**Comment by serge-rider** [comment]
Hints:
You can rename current script by pressing `CTRL+F2`. 
Also you can quickly find your script in navigator by pressing on "Link with editor" (`CTRL+SHIFT+,`).
