### ISSUE TITLE
Problem with autoformat and three qoutes ( ''' )

### ISSUE THREAD

**Issue by loboaureo** [serge-rider/dbeaver#1481]
I think a image is better than words (more if english is not my best language :) )

Before autoformat
![hello1](https://cloud.githubusercontent.com/assets/681482/24292178/81c84608-108c-11e7-8795-7e076db5a111.png)
After press ctrl+alt+f
![hello2](https://cloud.githubusercontent.com/assets/681482/24292179/837bad5a-108c-11e7-9693-a71f50027321.png)

**Comment by serge-rider** [comment]
Thanks for report

**Comment by loboaureo** [comment]
As always, thanks to you.
