### ISSUE TITLE
Cant change colour for "Active part foreground". Editor appearance

### ISSUE THREAD

**Issue by dimitriadisg** [serge-rider/dbeaver#1483]
Hello Serge and the rest of the team,

here I am once again for a bug report, a minor one this time.  I am trying to adjust the dark theme a bit, so that the labels are readable, but this bug is general and not theme related (which makes sense to me).

<details>
<summary>1) Here you can see a screenshot with the default settings on Dark theme</summary>
<img src="https://cloud.githubusercontent.com/assets/14919500/24333620/a1e9d16a-125b-11e7-8d3e-6d5867bff975.jpg" />
</details>

<details>
<summary>2) Here I have changed the "Active part foreground" to white and clicked "Apply". The preview shows properly, but you can see 'Database Navigator', 'mytanle' and 'Data' tabs to still be black.</summary>
<img src="https://cloud.githubusercontent.com/assets/14919500/24333646/17f3b6dc-125c-11e7-8b98-164bc74d23c3.jpg" />
</details>

The option for "Inactive part foreground" works properly. Also, maybe it is a good idea to make "Inactive part foreground" and "Active part foreground" colours default to white in the Dark theme.

**Comment by dimitriadisg** [comment]
Version 4.0.8 issue still remains.

**Comment by serge-rider** [comment]
It is a bug in editor tabs renderer.

**Comment by dimitriadisg** [comment]
Tested on version 4.1.1 and it works perfectly, thanks !
Also the default colour for the foreground is switched to white, thanks for that too !

Keep up the good work 👍

**Comment by dimitriadisg** [comment]
@serge-rider Ooops, sorry I spoke too fast, sorry. The bug is still there in 4.1.1, with the difference that it is now default to white foreground (thanks for that) and the preview works only until the "Apply" button is hit.

So, what happens now (under Window->Preferences->General->Appearance->Colors and Fonts) is :
1. Select Active part foreground and pick a colour
2. See the picked colour in the preview
3. Click Apply
4. The editor and the preview still uses the old colours (white for the dark theme). Your changes are saved on the list though.

Same happens to the inactive foreground.

Let me know if I can provide more info. Thanks !
