### ISSUE TITLE
Dbeaver: v.4.0.2: Issue: PostgreSQL: View Table: "java.lang.NullPointerException" Switch to Text, if result null, if Vertical view

### ISSUE THREAD

**Issue by spy686** [serge-rider/dbeaver#1485]
Environment: 
https://www.screencast.com/t/pp4Xr1tzU 

Steps:
https://www.screencast.com/t/XZvGsn8iC5s

**Comment by serge-rider** [comment]
Please upgrade to 4.0.3.
I'm quite sure that this issue was already fixed.
