### ISSUE TITLE
Bind parameters require multiple carriage returns

### ISSUE THREAD

**Issue by guyfromwy** [serge-rider/dbeaver#1486]
This isn't a very big deal, but a small nuisance. 
When running a query that has a bind variable, I key in the value and press **enter**. Usually that is all, but with 4.0.3 I have to hit **enter** a second time to get the query to run. 

I had this issue once before, a few versions back, and it was gone by the next release, so I didn't think much of it. It is rather inconsequential, but if I don't think about it, it will just sit there not doing much.

**Comment by serge-rider** [comment]
This was change on purpose. Because on MacOS and Linux immediate dialog close was handled incorrectly (parameter values wasn't saved).
I didn't find any good workaround.
