### ISSUE TITLE
Individial Formatter Error

### ISSUE THREAD

**Issue by JohneDoe** [serge-rider/dbeaver#1487]
Here is my Formatter for Testing the external Formatter.

```
package test;
public class Formatter {
	public static void main(String[] args) {

	for (int i = 0; i < Integer.valueOf(args[0]); i++) {
			System.out.print("-");
		}
	}
}
```

java -jar Formatter.jar 4120
shows 4120 times '-'

java -jar Formatter.jar 4121
shows, that there is something wrong

Why?

**Comment by serge-rider** [comment]
Thanks for report. This was a bug in external program stdout reading.
I'll also fix external formatter settings page (which is looking really ugly now).
