### ISSUE TITLE
Unable to deserialize "/tmp/drill/sys.storage_plugins/hbase.sys.drill"

### ISSUE THREAD

**Issue by mtiowl** [serge-rider/dbeaver#1488]
Version: 3.8.5
OS: Windows 7, Service Pack 1

Have Apache Drill running on same windows machine and it is working.  When I try to connect from DBeaver, I'm getting:

Failure in starting embedded Drillbit: java.lang.RuntimeException: Unable to deserialize "/tmp/drill/sys.storage_plugins/hbase.sys.drill"
  Unable to deserialize "/tmp/drill/sys.storage_plugins/hbase.sys.drill"
    com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'hbase' into a subtype of [simple type, class org.apache.drill.common.logical.StoragePluginConfig]: known type ids = [InfoSchemaConfig, StoragePluginConfig, SystemTablePluginConfig, file, mock, named]
 at [Source: [B@3b1cbab2; line: 2, column: 12]

**Comment by serge-rider** [comment]
1. Try to update to the most recent DBeaver version (4.0.3 for CE, EE will be released on this weekend). 
2. I don't think that this is DBeaver issue. Hive connection should be properly configured. There are tons of nuances in Hive driver. I had to spent a couple of hours to connect to Hive Spark without errors.

**Comment by mtiowl** [comment]
OK.  I'll wait for EE 4.0.3 and see if that fixes the problem.

The strange thing is that the error message points to hbase.sys.drill but
all I'm trying to do is connect to Apache Drill.  We're not even using hive

**Comment by serge-rider** [comment]
Try another JDBC driver: `org.apache.drill.exec:drill-jdbc-all`.
Remove current Maven artifact from driver libraries and add drill-jdbc-all.
If it'll work well then I'll change default Drill driver config. It seems to be smaller and newer.

![default](https://cloud.githubusercontent.com/assets/6398845/24420555/ed41060a-13fb-11e7-963b-118213a11ca3.png)
