### ISSUE TITLE
How change data source from a ERD file?

### ISSUE THREAD

**Issue by phouverneyuff** [serge-rider/dbeaver#1489]
I Would like to change the data source of my ERD file to another datasource. How can I do that?

I don't have the older connection anymore, and my ERD file was customized. I can't loose it.

Editing the xml file (ERD file), I can see the tag <data-source>, but I don't know the data source id, and I think that it should be possible through DBeaver.

How can a share my ERD file if the data source id is different in each machine? 

tks!

**Comment by serge-rider** [comment]
There is no such feature in UI.
You can edit ERD files directly and update id attribute in tables references:
```xml
<data-source id="mysql5-1370725517603--1301597195">
...
```
To get datasource ID open `.dbeaver-data-sources.xml` file in the root of workspace directory, find your connection there (e.g. by name) and copy `id` attribute.

**Comment by 2mik** [comment]
Is there any plan to create UI for updating data source ID?

**Comment by Mahdi-Hosseinali** [comment]
In newer versions the data source informations are not in a XML file anymore, they can be found in `~/Library/DBeaverData/workspace6/General/.dbeaver/data-sources.json`. And just updating the data source id does not work because the entities also have ids in the ERD file.
