### ISSUE TITLE
generate ddl of view is mistake in Oracle

### ISSUE THREAD

**Issue by skytriper** [serge-rider/dbeaver#1490]
To see ddl of view in oracle . the context no exist field name in create statement.in db2 is ok.
ex:
  create  view test 
    (  prodname,taskid,price )   --no the line statement to generate in dll
  as select prodname,taskid,price from product2 
union all
  select prodname,task,price from product3;

**Comment by serge-rider** [comment]
Sorry, I don't understand the problem.
View definition is retrieved from Oracle system catalog.

**Comment by skytriper** [comment]
ex:
sql :
create view test
**( prodname,taskid,price )** 
as select prodname,taskid,price from product2
union all
select prodname,task,price from product3;

---------
Because the bold text  is not to generate ,it is error  to execute view sql .

**Comment by serge-rider** [comment]
It works fine in most cases.
Please provide some example when view creation fails.

**Comment by skytriper** [comment]
# I create sql of view in oracle:

CREATE VIEW CIB.TEST_V (
        ppid,  ppName)
      as select productid,prodname from SALEDATA

# see ddl in dbeaver :

CREATE OR REPLACE VIEW CIB.TEST_V 
AS  select productid,prodname from SALEDATA
