### ISSUE TITLE
Shortcuts for quick executions

### ISSUE THREAD

**Issue by anton-johansson** [serge-rider/dbeaver#1491]
Hey!

I just found out about DBeaver and I'm impressed so far!

One thing that I haven't been able to find yet is some kind of shortcuts for quick executions (similar to Management Studio).

For example, I would like to bind `Ctrl + 3` to this script:
```sql
EXEC dbo.SPRC_MY_UTILITY_PROCEDURE @pInput = '%s'
```

... where `%s` would be the selected text in the editor.

Is there something like this that I have missed? If not, any plans? I'd be happy to help out (I would just need to get familiar with the code, etc.)

**Comment by serge-rider** [comment]
No, there is not such feature in DBeaver. I like this. 
Unfortunately I can't say when I will have time for it (it will require some extra UI). 
Setting 4.1 milestone for now.

**Comment by serge-rider** [comment]
After all I think this is almost the same as templates: https://github.com/serge-rider/dbeaver/wiki/SQL-Editor-templates
