### ISSUE TITLE
Please add the copy SQL to programming language string

### ISSUE THREAD

**Issue by Andyfoo** [serge-rider/dbeaver#1492]
Please add the copy SQL to programming language string ：

**SQL Editor:  Right-click menu:** 
**copy SQL string to:** 
                    Java/C# string
                    PHP string
                    C/C++ string
                     ![1](https://cloud.githubusercontent.com/assets/864512/24399221/a64f8b76-13de-11e7-9050-04900bdf349d.png)

**Comment by Andyfoo** [comment]
thank you @serge-rider

**Comment by mapes610** [comment]
Hi, do you can add Delphi support as well? Thank you.

**Comment by serge-rider** [comment]
This could be a good feature.
And it makes sense to make target format configurable.

**Comment by serge-rider** [comment]
4.0.6 will contain copying into Java, C/C++, Delphi, HTML and plain (single line) formats.
Further improvements (including additional formats) should be tracked in separate tickets.

**Comment by seveneleven** [comment]
Where is this feature now?
