### ISSUE TITLE
Is it possible to not automatically switch to Statistics after running code (e.g. PL/SQL)

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1494]
I tend to not be particularly interested in the Statistics tab when I'm running PL/SQL scripts, but more often the Output (generated by DBMS_OUTPUT.PUT_LINE etc) which shows what the script wants to communicate to the user.

Currently each time I execute a PL/SQL script by highlighting the script source and pressing Ctrl+Enter, DBeaver switches from the Output tab back to the Statistics tab.

If this is not currently possible (I looked and couldn't seem to find any way to change this behaviour), please treat this as a feature request.

**Comment by serge-rider** [comment]
Agreed, this makes sense.
