### ISSUE TITLE
Show results even if an error occurs

### ISSUE THREAD

**Issue by anton-johansson** [serge-rider/dbeaver#1495]
Using MS SQL, run this:
```sql
SELECT	1 [a], 'test' [b]
RAISERROR (11, 11, N'FAIL')
```

The result set isn't showing, even if the error occurs **after** the selection. Is it possible to always show the result sets?

**Comment by serge-rider** [comment]
This query is executed as a single statement. If you run a script (i.e. two queries which should be executed one by one) then you need to separate your queries with delimiter (`;` or `GO`) and run script with `ALT+X`.
Then you will both results and error.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
