### ISSUE TITLE
New maven repository in 4.0.3 causes driver download issues

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1497]
When trying to install a fresh install of DBeaver, and requesting the IBM i DB2 JTOpen Driver (jt400), we get this error:

![issue](https://cloud.githubusercontent.com/assets/6610039/24457859/fb777c16-145c-11e7-9180-0f75ea3277d8.png)

**Comment by serge-rider** [comment]
Check last comments in #734 (there is a workaround).

I definitely won't change https version of Maven repo to http (this is way too unsecure).
But, I can add http repository in the end of the list so if https won't work then http will. Although I'm still not sure that this is secure. Probably I should show some warning message about missing secured repository.

Any thoughts?

**Comment by serge-rider** [comment]
Let's try this in the next version.

**Comment by Eladar991** [comment]
So, I'm getting a very similar problem, regardless the method I'm trying to use. Neither http nor https works. Tried CE and EE versions as well

```
Error resolving dependencies
  java.io.IOException: Maven artifact 'maven:/org.postgresql:postgresql:RELEASE' not found


Can't create driver instance
  Can't load driver class 'org.postgresql.Driver'
    java.lang.ClassNotFoundException: org.postgresql.Driver

```

Any ideas?

**Comment by serge-rider** [comment]
Could you post full debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) here or on serge@jkiss.org.
Probably something is wrong with network but I need to see all warnings.

**Comment by Eladar991** [comment]
I sent you a mail, and attached the log files there.
If you didn't get it, I'll post them here.
