### ISSUE TITLE
Update Jsch to more recent version for better key support

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#1498]
Hello,

Currently it is not possible to use ed25519 keys when using SSH tunneling to machines.
```
Can't initialize tunnel
  Cannot establish tunnel
    com.jcraft.jsch.JSchException: invalid privatekey: [B@xxxxxxxx
```

**Comment by serge-rider** [comment]
Currently DBeaver uses JSch 0.1.53. The most recent version is 0.1.54.
I will update it but I'm not sure it will resolve your isse (JSch changelog doesn't contain anything about that: http://www.jcraft.com/jsch/ChangeLog).

Good point anyway.

**Comment by Azenet** [comment]
Indeed, sorry I didn't read properly what I found.
There's a [2015 ticket](https://sourceforge.net/p/jsch/feature-requests/7/) on the JSch bugtracker that states it is planned for the next milestone.
