### ISSUE TITLE
Problems creating connection through SSH tunnel 

### ISSUE THREAD

**Issue by tdgroot** [serge-rider/dbeaver#1499]
Since a few updates I can't seem to create a working connection through an ssh tunnel. Existing connections through ssh tunnel are working fine.

Anyone else having this problem?

**Comment by gka** [comment]
Yes, I can connect to a MySQL db through SSH tunnel either. The driver seems to be ignoring the ssh tunnel settings altogether. When I test the connection I see

```
java.sql.SQLException: Access denied for user '#####'@'localhost' (using password: YES)
```

**Comment by serge-rider** [comment]
I can reproduce this only with "Test Connection" in connection settings dialog. Once connection is created SSH tunnel works fine.
Will fix this in the next version, thanks for report.
