### ISSUE TITLE
No copy/paste support for scripts. 

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#150]
You can copy a _**script**_ from the context menu in the Database Navigator or Projects view, but 'paste' never appears in the context menu. 'Paste' **CAN NOT** be accessed from the Edit menu and pasting a script using the hotkey **ALSO FAILS**.

You can copy a _**connection**_ from the context menu in the Database Navigator or Projects view, but 'paste' never appears in the context menu. 'Paste' can only be accessed from the Edit menu. Hotkeys also work for pasting connections.

**Comment by serge-rider** [comment]
Agreed, resources (scripts in particular) should be copyable.

But I don't think that "paste" action should be in all context menus. As well as "cut". They just obstructs menus making them too verbose.

**Comment by codebling** [comment]
I understand your point of view and think it's pretty valid. But if you have made Copy accessible from the context menu, from a user perspective the expectation is that Paste will also be in the context menu (*IF* a resource is in the copy buffer and *IF* it is available for pasting in the resource that was clicked on). Otherwise it makes sense to remove Copy from the context menu, as well. Either adding Paste or removing Copy makes sense to me, but being able to copy from the context menu is useless if one can't paste from the context menu.

**Comment by serge-rider** [comment]
Yes, it makes sense. Although there a few other nuances in copy/paste handlers.
I'll create separate issue for context menu items visibility tracking.

**Comment by serge-rider** [comment]
Resource (files) copy/paste support added.
