### ISSUE TITLE
Cycle round to the first/last tab when switching tabs

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#1501]
When switching tabs using the "Next tab" or the "Previous tab" commands, DBeaver does not cycle round if the current tab is the last or the first tab of the list.

I'm afraid this is too much linked to how Eclipse works, but would you be able to change this behavior by any chance?

**Comment by serge-rider** [comment]
I'm afraid that won't be easy. This is core Eclipse functionality. The only workaround is to use Previous Tab command or Editor navigator  (CTRL+E).

**Comment by Otiel** [comment]
Thanks. We can always hope Eclipse will support this one day. 😄
