### ISSUE TITLE
Do not display connection on script tab

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#1502]
Could it be possible to add an option to hide the connection label currently displayed on the title of a script tab?

![screenshot](http://i.imgur.com/7Gr80Kj.png)

**Comment by serge-rider** [comment]
Yes this is possible. You can configure script title in preferences:
![default](https://cloud.githubusercontent.com/assets/6398845/24524442/3393de62-159f-11e7-9d05-29c29d71663e.png)
You can see supported variable in "Script title pattern" field tooltip or by pressing ctrl+space.

**Comment by Otiel** [comment]
Oops, I didn't see that option is already existing. Thanks!
