### ISSUE TITLE
clicking inside second pane does not set the cursor to that editor

### ISSUE THREAD

**Issue by iddofontijn** [serge-rider/dbeaver#1503]
This occurs when having two package editors open, and tiled next to each other. If you do a mouseclick in the non-active editor, you can start typing but the cursor keeps blinking in the previous active editor.  Also, some input appears in the previous active editor (key combinations like ctrl+v and ctrl+z, but also tab or backspace; behaviour is unpredictable).
When you click on the editor-tab first, this does not happen.

**Comment by serge-rider** [comment]
Please provide more details. 
What database?
Some screenshot would be also helpful.

**Comment by iddofontijn** [comment]
Oracle database.

As you can see in the screenshot, I'm typing in the left panel on line 76, but the cursor is visible in the other panel.
![image](https://cloud.githubusercontent.com/assets/7559060/24544257/ddb09404-1602-11e7-8bfe-2fb07aa57f55.png)

**Comment by serge-rider** [comment]
Can't reproduce. 
At least this works fine if you open two editors by dragging second one.

Could you provide steps to reproduce?
