### ISSUE TITLE
[Feature request] Close results tab after middle (scroll) click

### ISSUE THREAD

**Issue by Karsonito** [serge-rider/dbeaver#1505]
It's a little difficult to aim at the close button of results tab.
Please add ability to close results tab by pressing scroll button on mouse. Similar to closing script tab.
Hotkey is also welcome.

**Comment by serge-rider** [comment]
Default shortcut `CTRL+SHIFT+\`

**Comment by Karsonito** [comment]
Thank you! Very very useful! )
