### ISSUE TITLE
Confirm SQL Execution has no affect

### ISSUE THREAD

**Issue by sdpurohit** [serge-rider/dbeaver#1506]
Connecting to a MySQL database using DBeaver 4.0.3 on Mac OS 10.12.3.

I have a connection configured with the Production Connection Type. In preferences the Production Connection Type has Confirm SQL Execution checked.

When I run any queries against this connection I am not asked for confirmation.  My editor tab does show the red-orange production border.
I expect the application to ask me if I really want to run the statements. Am I misunderstanding this preference?

All of the following statements run without any confirmation.
create table mydb.my_test as select 1 as a;
insert into mydb.my_test(a) values(2);
select * from mydb.my_test;
drop table mydb.my_test;

**Comment by serge-rider** [comment]
Yes, "Confirm  SQL Execution" has no effect. Thanks for noticing.
Will mark as enhancement (confirmation will be shown only for DDL and transactional DML queries).
