### ISSUE TITLE
Column name vs. column label

### ISSUE THREAD

**Issue by p0c07o** [serge-rider/dbeaver#1507]
When you have a query where you assign a different name to a column:

select
  toto as "My very long column name"
from
  mytable

The long column name is shown in the output. But when you click on your result set and choose "Advanced Copy > Copy column name(s)", the short column name is copied (in my case, "toto" instead of "My very long column name").

My guess is that there is a confusion between ResultSetMetaData.getColumnName() and ResultSetMetaData.getColumnLabel().

I honestly don't know if that's a feature or a bug, in other words: is that working as intended?

**Comment by serge-rider** [comment]
Looks like a kind of bug. This should be consistent.
But I can't reproduce this right now (this might be database dependent). What is your database?

**Comment by serge-rider** [comment]
I did reproduce that in MySQL.

**Comment by p0c07o** [comment]
Sorry for the late answer.

I'm on DB2, but it looks like you could reproduce it!

Thanks for the extremly fast reaction and your good product!!!
