### ISSUE TITLE
Support for dots in table names

### ISSUE THREAD

**Issue by mklamra** [serge-rider/dbeaver#1509]
I have an object database that stores Java objects. I connect DBeaver to the database through a custom-built JDBC driver. The table names are the fully qualified names of the Java classes, e.g. com.foo.MyClass. It seems that DBeaver does not support table names with dots. When I use auto-completion to select a table, DBeaver encloses the table name with single quotes, e.g. ‘com.foo.MyClass’. This makes it impossible to use auto-completion since the driver expects table names without quotes. Can you add support for table names with dots or can I make some workaround in my driver?

**Comment by serge-rider** [comment]
DBeaver supports any characters in table names. If table name contains any non-alphanumeric characters then it is quoted. DBeaver uses quote character which is provided by driver. Usually is is double quote `"`. If you driver returns single quote in DatabaseMetaData.getIdentifierQuoteString then it is a problem. Because single quote is used for string literals and this leads to ambiguity.

**Comment by mklamra** [comment]
Thanks for the explanation. Our getIdentifierQuoteString returns a single quote. Is it possible to disable quoting in DBeaver? According to the JavaDoc for DatabaseMetaData.getIdentifierQuoteString, the method should return " " if quoting is not supported. However, when I do that, DBeaver quotes the table names with double quotes anyway. Can I avoid the quoting in some way?

**Comment by serge-rider** [comment]
Do you use the most recent DBeaver version?
Empty quote char (in DatabaseMetaData.getIdentifierQuoteString) should lead to quoting disable.

However, without identifiers quoting your complex table names (with dots, spaces, etc) won't be recognized correctly.

**Comment by mklamra** [comment]
You are right. After upgrading to the latest DBeaver version, it works as expected.
