### ISSUE TITLE
How to disable SQL Auto-Format when viewing procedure?

### ISSUE THREAD

**Issue by super3dmax** [serge-rider/dbeaver#1511]
When I view procedure using dbeaver, the SQL code is automatically formatted.
How to disable this feature?

**Comment by serge-rider** [comment]
What database?

**Comment by super3dmax** [comment]
DB2.I hope that the format of the SQL code remains the same as it was created.don't auto-format.

**Comment by titou10titou10** [comment]
In the next version of DBeaver, a drop down box has been added in the bottom right corner of the routine source code viewer to allow the source code for SQL routines to be display raw (=unformatted)
Denis
