### ISSUE TITLE
ADD ability to copy table and column names in Search dialog results

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1513]
## use case

I need to find all tables having a certain column.
I go to Search -> Search.. and open the DB Metadata tab, I enter the column I wish to search for and press Search.
Then search results will appear in a nice informative list (kudos for that), but when I select a column or a table name (also selecting the whole row) and hit CTRL+C to copy, nothing happens.

It would be great if we could copy the values from individual cells in Search results or atleast the contents of the Name column for the selected row.

**Comment by serge-rider** [comment]
Ok, that's easy to fix.
