### ISSUE TITLE
Explain Execution Plan

### ISSUE THREAD

**Issue by cniweb** [serge-rider/dbeaver#1514]
Hi DBeaver developers,

the explain of execution plan is fundamental for optimization of statements.
It should be supported for all DBMSs.
We mainly use: MS SQL, IBM DB/2, Oracle SQL and MySQL

Tanks,
Chris

**Comment by serge-rider** [comment]
Explain of execution plan is supported for DB2, Oracle, MySQL/MariaDB and PostgreSQL.
MS SQL support will be added along with other MS SQL features in new extension (#810).
