### ISSUE TITLE
When connected to Amazon Athena via Athena JDBC driver, tables aren't listed

### ISSUE THREAD

**Issue by kjedrzejewski** [serge-rider/dbeaver#1515]
When I connect via DbVisualiser, this tables are listed in the EXTERNAL_TABLE group:
<img width="197" alt="zrzut ekranu 2017-04-03 o 20 20 18" src="https://cloud.githubusercontent.com/assets/8270726/24624167/4388e8da-18ab-11e7-9599-316979e75729.png">

**Comment by laithalsaadoon** [comment]
+1 on this issue.

**Comment by serge-rider** [comment]
In DBeaver (Generic driver) there are only two categories: tables and view. External tables should be in Tables (you can open catalog editor and see all tables, table type is a property).

Or these tables are missing completely?

**Comment by kjedrzejewski** [comment]
They aren't listed there:
<img width="122" alt="zrzut ekranu 2017-05-11 o 22 08 32" src="https://cloud.githubusercontent.com/assets/8270726/25971568/05d893fe-369d-11e7-8ae4-318635e3b46d.png">

**Comment by serge-rider** [comment]
Could you try to use most recent Athena driver (http://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html)?

**Comment by kjedrzejewski** [comment]
It works after driver update! (at least in version 4.1.1)

<img width="143" alt="zrzut ekranu 2017-08-29 o 02 09 23" src="https://user-images.githubusercontent.com/8270726/29798862-0510c202-8c60-11e7-9f3a-cf3d27653a7f.png">

**Comment by serge-rider** [comment]
Great, thanks for info.
BTW I can add Athena  in standard DBeaver driver list. 
If you will post parameters of your driver configuration.

**Comment by kjedrzejewski** [comment]
I use default driver parameter values. The only one, that needs to be explicitly set is _s3_staging_dir_. This one has to point to an S3 bucket that is writable using credentials provided as username and password.
As for other connection parameters that may be included in the connection configuration screen:
- region, which is a part of the connection string jdbc:awsathena://athena.[REGION].amazonaws.com:443 (this one may be a combo box, as there is a [list of AWS regions](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html), and a new one is added very rarely)
- username and password, which in this case may be called AWS Access Key and AWS Secret Key (so everything will be less confusing)

**Comment by thomas-ku** [comment]
Yup! confirmed this is a bug. it does not work for me too.

**Comment by serge-rider** [comment]
@thomas-ku What driver version do you use?
