### ISSUE TITLE
Import Table Data wizard quotes new table column names

### ISSUE THREAD

**Issue by drewed** [serge-rider/dbeaver#1516]
My group is in the process of migrating data from an Oracle database to a PostgreSQL database.  If I use DBeaver to migrate data using the Import Table Data wizard, the new table will be created with capitalized field names which breaks default expectations on PostgreSQL servers.  This is happening because the Oracle table uses upper case field names which the wizard borrows the casing and then quotes in the DDL statement.  I believe this behavior is new the enterprise edition.

Note: It is possible to work around the behavior by re-typing the generated mappings but doing so is tedious for tables with many fields.

I'm running on Mac OS X Sierra (10.12.4).  DBeaver Enterprise 4.0.4

**Comment by serge-rider** [comment]
Will be fixed in 4.0.6.
