### ISSUE TITLE
Sybase: Wrong count for updated rows

### ISSUE THREAD

**Issue by tzeumer** [serge-rider/dbeaver#1518]
Maybe this is somewhat related to #424... The problem is that the "Updated rows" count seem to be wrong.

**What I do**
update membershp set expiry_date = '2099-12-31 00:00:00'
where iln = 23
and address_id_nr in (select b.address_id_nr from borrower b where b.iln = 23 and b.borrower_type IN (50, 51, 80))

**What DBeaver says**
Updated rows: 2891

**Checking via query**
select * from membershp where iln = 23 and expiry_date = '2099-12-31 00:00:00'

**What DBeaver says**
1444 rows fetched (as expected)

**Comment by serge-rider** [comment]
This is not related to #424 (it was a problem with manual results editor).

DBeaver gets updated rows count directly from JDBC driver.
Could you verify this problem with some simpler query (e.g. update single row by primary key value)?

**Comment by tzeumer** [comment]
Thank for the quick reply. Even for some very simple example I get a wrong result

**Check**
SELECT * FROM address WHERE address_id_nr = 99954
> Exactly 1 result

**Update**
UPDATE address SET edit_date=getdate() WHERE address_id_nr = 99954

Message is "Updated Rows: 2"


I'm using the 64bit portable Version 4.0.4 for Windows.

**Comment by serge-rider** [comment]
This looks like JDBC driver issue. 
What Sybase driver do you use? 
Did you try jTDS? Native Sybase driver?

**Comment by tzeumer** [comment]
I run DBeaver with the "-data PATH" options for at least two years. In earlier versions I was asked pretty often for database driver updates. Recently this didn't happen and I thought, it became an automatic background process or the driver(s) just did not change.

If I go to "Edit Driver" for the connection, I see 
* Class name: net.sourceforge.jtds.jdbc.Driver
* Libraries: net.sourceforge.jtds:jtds:RELEASE with Version 1.3.1

So everything seems to be fine. Yet, when I click "Download / Update" there is an ambiguous message in the window saying "Sybase driver files are missing". Well, if they were, nothing would happen I guess.

So it looks like I have the most recent (and correct) driver?

**Comment by serge-rider** [comment]
jTDS driver is really old. It appeared in ancient times when MS SQL Server and Sybase were splitted. Since then there were too many changes in each them.

I'd recommend you to try native Sybase driver. It is not free and can be downloaded from SAP web site. Also it is shipped along with Sybase server.

**Comment by tzeumer** [comment]
I fell in love with DBeaver because I could connect to Sybase out-of-the-box and leave the tedious shell behind me. I rarely do update queries, but I could swear it worked some time ago. :)

However, thanks for the tip. In the Sybase manual it says for [SQL Anywhere JDBC 4.0 driver](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc01776.1600/doc/html/san1357754910584.html) (well, not exactly for ASE) is the thing to look for. I'm not finding anything on the SAP sites, but I found a working download link on [dbschema.com](http://www.dbschema.com/sybaseanywhere-jdbc-driver.html). Downloading it I got jconn4d.jar which looked fine. 

I added a new driver and set 
```
Class name: com.sybase.jdbc4.jdbc.SybDriver
Url Template: jdbc:sybase:Tds:{host}:{port}/{database}
```
Now my update gets me the correct result. :)

I just don't know how to add the driver (or path) in a way that it gets put in my data profile (so it keeps working portable). I also wonder if it could be added as a replacement (or addition) to the old jTDS driver option that comes with DBeaver. There seems to be no restriction to this? :)

However. Thank you very much for your help. And for DBeaver! :)

**Comment by tzeumer** [comment]
Oh :(

With the new driver I always get only 1 updated row now. Weird.

**Comment by serge-rider** [comment]
I have one guess:
- Switch back to jTDS driver, go to the driver properties (Edit Driver Settings on connection properties page).
- Switch to Adv. Parameters tab.
- Find "Driver supports multiple results" option and disable it.
- Reconnect. Check update count.

**Comment by tzeumer** [comment]
Hmm, if I disabled it in jTDS I always get "Updated Rows: 1". But it was a good hint because it wasn't set in the "SQL Anywhere JDBC 4.0 driver" (this at least explains this part).
I also found the "original" Sybase driver in the Sybase installation folder - seems just to be a bit older version from the above JDBC 4 driver. Nothing different with it.

But both give me the wrong number. If I have 2 rows, it tells me 3 were updated. Having 4 it says 5.  

But now I found something interesting. Running this query
> select *
> from address where name like '%My Name%' and address_id_nr in (select address_id_nr from > borrower where iln=23 and borrower_type < 11)

I get 29 rows.

Now I do an update like this ...
>update address set name=STR_REPLACE(name, 'My Name', 'My Name1')
> where address_id_nr in (select address_id_nr from borrower where iln=23 and borrower_type < 11)

... or done like this ...
> UPDATE address
> SET a.name=STR_REPLACE(a.name, 'Flugzeug-Systemtechnik', 'Flugzeug-Systemtechnik1')
> FROM address a INNER JOIN borrower b ON a.iln=b.iln AND a.address_id_nr=b.address_id_nr     
> WHERE a.iln=23 AND b.borrower_type < 11;

... I get 3101.

Doing it like this (including the possible additional condition (even though it isn't logically required) ...
>update address set name=STR_REPLACE(name, 'My Name', 'My Name1')
> where address_id_nr in (select address_id_nr from borrower where iln=23 and borrower_type < 11)
> and name like '%My Name%'

... I get 30. Still 1 more but better at least it seems more reasonable. This is similar to the initial query of this post. Only difference is that there I have no other condition to set in the where clause.

And the subquery from above for itself ...
> select address_id_nr from borrower where iln=23 and borrower_type < 11;
... returns 1557 rows. 

For me it looks like "Updated Rows" really returns something more like "Comparisons and updates done by query". 

Maybe it is just a Sybase weirdness (I might be willing to bet on this :)), maybe this is even somehow correct (though not reassuring or useful). But I guess there is not much to do about it, if the driver returns it this way. 

It's pretty possible that it always has been this way and I just did too few updates in my Sybase life to ever have recognized it. I also just found out that our hoster seems to have updated from version 12.5 to 15.7. But I think there is only a slight chance this should have an impact on a generic sybase driver like jTDS or JDBC  (well, that is how I thought of it at least).

Anyway, I'm very ok if you close this ticket. For once I seem to be the last man alive to be bound to Sybase and second it is no DBeaver issue.

Thanks a lot for your time and effort :)
(Btw. there is just no donation button on jkiss.org or did I miss it?)

**Comment by serge-rider** [comment]
Yes, I think this is because of specific Sybase driver behavior. Check this: http://stackoverflow.com/a/21785462/1912589
So it returns number of rows matched, not updated (honestly I didn't find anything about that in JDBC spec). Maybe there is some connection parameter which changes this behavior (like useAffectedRows).

**Comment by tzeumer** [comment]
Whoa, it look like I have some very big misconception (or wrong expectation) how an update statement is supposed to work. Or more to the point about how useful an "affected rows" counter should be out-of-the-box.

I can "reduce" the mysterious +1 count by immediately doing a _select @@rowcount;_  after an update statement in DBeaver. I just did the "31001 affected rows" query in the shell via isql. And it says 3100, too. I'm dumbfounded - obviously all my update queries in the past were "simpler" and yielded reasonable affected rows counts.

I never encountered a similar behavior in MySql for comparable queries, but it looks like it is just the way Sybase (and MS Sql) do work (whatever they actually do). Only, one might be close to a heart stroke the first time :D

Still, it drives me nuts that I just can't figure out a way to - at least theoretically - do the query from my initial post in a way that could reduce the count by more explicit conditions; or by using a join syntax.

**Comment by serge-rider** [comment]
Yeah. That's confusing.
Anyhow, this doesn't look like DBeaver issue. At least I have no idea how to fix this on client side.

Closing for now. If anybody have any thoughts about that - please reopen.
