### ISSUE TITLE
Updates on DBeaver Enterprise Edition?

### ISSUE THREAD

**Issue by osrojas** [serge-rider/dbeaver#1519]
Hi,

I see that DBeaver Enterprise Edition 4.0.4 was released and is still free of charge. When is the next version anticipated to be released? Has the quarterly update cycle started yet or will this still be updated as regularly as the Community Edition for the forseeable future? 

Thanks,
Ogden

**Comment by serge-rider** [comment]
EE version will be updated quarterly. 
Next EE release will be 4.1. It is supposed to be commercial.

I just don't have enough time to make everything for commercial support - that's why it is still not ready. Hopefully it'll be ready in a month or so.
