### ISSUE TITLE
Slow update from table data view results in locked UI

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#152]
A slow update from an SQL Editor window behaves beautifully: it shows the "Read data" progress bar with a cancel button for the duration of the update.

A slow update from the table data view blocks the event thread, completely freezing the DBeaver UI for the duration of the update. This results in "application not responding" messages. (The transaction eventually times out and DBeaver returns to normal, but on my system this takes almost a minute)

**Comment by serge-rider** [comment]
If you still can reproduce this issue - could you try to make a tread dump (jstack &lt;dbeaver-pid&gt;) and post it here?
It's a bit strange issue. Can't yet find any differences in data update from SQL editor of table viewer..

**Comment by codebling** [comment]
I am actually reproducing this using `SELECT * FROM x FOR UPDATE`, then opening table-data view in DBeaver and attempting to edit a cell. Attached is the thread dump. 
[threads_report.txt](https://github.com/serge-rider/dbeaver/files/84061/threads_report.txt)

**Comment by serge-rider** [comment]
Thanks for thread dump.
Entity editor save fixed.
