### ISSUE TITLE
Possible Bug in line delimiter

### ISSUE THREAD

**Issue by carlosspohr** [serge-rider/dbeaver#1521]
Hi there,

After upgrade to 4.0.4 version, we're getting an error when cursor is at the end of sql statement, generally when it ends with ```);``` on a new line.
![image](https://cloud.githubusercontent.com/assets/637767/24677161/35e497d6-195c-11e7-8d08-c64ebe098908.png)
Sometimes when I put cursor at last line of my sql statement then I run ```Ctrl + Enter``` this one, dbeaver runs the next one, from image above, dbeaver executes select instead create table.

This image bellow I got from another machine (with same configuration of my) in exactly moment of this bug:
![smaller](https://cloud.githubusercontent.com/assets/637767/24677522/76d91374-195d-11e7-9ddb-f58d35c7d96c.jpg)

These are my configs:
![image](https://cloud.githubusercontent.com/assets/637767/24677605/b93dc426-195d-11e7-9d40-b943b6b35b5f.png)

**Comment by serge-rider** [comment]
Can't reproduce.
Could you post some example (e.g. selects from system tables).

**Comment by carlosspohr** [comment]
Uhm, OK

I'll provide a gif of screen and the script.

There's something strange in it, because I tested it with another tables
keeping same context, as create table statement using select closed by ()
and single selects also closed by ().

I just figured that the fact of script is using database name before table
name maybe be the problem.
