### ISSUE TITLE
request: scroll bar in error window

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1522]
Sometimes the error messages are very long (greater than the height of my monitor) and i'm unable to read the end of the error messages. It would be helpful if there was a scroll bar in the error message window.

note: error message window refers to the window that pops up when you run invalid sql such as `select 1 fromfrom`

<img width="505" alt="screen shot 2017-04-04 at 3 39 15 pm" src="https://cloud.githubusercontent.com/assets/9246654/24682124/eefbae40-194c-11e7-8da8-77ed504c07e8.png">

**Comment by serge-rider** [comment]
Good point.
