### ISSUE TITLE
Copy & paste remove NULL

### ISSUE THREAD

**Issue by verajosemanuel** [serge-rider/dbeaver#1523]
When copying from table or resultset with some null values, if you paste rows, NULL values are replaced with non NULL empty values.

For me , NULL is different than empty and I think this is a dangerous behaviour that can lead to unexpected results

Windows 10, dbeaver 4 0.4 with mysql

**Comment by serge-rider** [comment]
Could you explain your use case a bit more?

When you copy NULL value it is not copied in clipboard (by default). You can use use advanced copy to specify format (in native format NULL is copied as NULL value).

**Comment by verajosemanuel** [comment]
didn't know that advanced copy is the option to use in this case. 
thanks
