### ISSUE TITLE
recognize current statement

### ISSUE THREAD

**Issue by frankmusolf** [serge-rider/dbeaver#1524]
In case of more than one statements in editor without semicolon with empty line as delimiter current statement end is not correct recognized when statement is closed with comment.

Here with cursor on FROM-Statement CTRL-Enter will execute from Select to Commit
```
SELECT 
*
FROM abc 
where def IN ('xyz')
--heho

COMMIT work

```
dbeaver version is 3.8.5

**Comment by serge-rider** [comment]
This seems to be related to #1521.
Thanks for report
