### ISSUE TITLE
Lock view

### ISSUE THREAD

**Issue by AndrewKhitrin** [serge-rider/dbeaver#1525]
Hi DBeaver users and developers,

Would anyone be interested in using some "Lock view"?

It looks like a table with session locks and details.

And also the lock dependency graph for sessions waiting and holding locks with the possibility of killing the selected session.

I have the issues of analyzing locks on production and dev environment very often, so I did this.

For Oracle, it looks like:

![oralocks](https://cloud.githubusercontent.com/assets/25009233/24701030/b1780072-1a01-11e7-8284-d7aabd3e46c2.png)

For Postgres like:

![pglocks](https://cloud.githubusercontent.com/assets/25009233/24701054/c1d08408-1a01-11e7-93aa-a860d4d1efa2.png)

It's a little better than just text queries.

If anyone else is interested I am ready to send Pull Request.

_Thanks,
Andrew_

**Comment by serge-rider** [comment]
I'm sure that it will be a good addition to sessions manager.

**Comment by AndrewKhitrin** [comment]
I've send Pull Request for LockViewer.

Please review and send  me comment.


_Andrew._

**Comment by serge-rider** [comment]
Great, see comments in pull request

**Comment by serge-rider** [comment]
New extension was successfully merged. Excellent feature.
I've made small code formatting and fixed a couple of minor UI issues.

This new plugin will be included in 4.0.5. 
Thanks, Andrew.

**Comment by karthikbeam** [comment]
Sorry for necroing this, but is there any docs on this view? Im looking to understand how I can debug locks that I am having beyond just killing the bad actor.
