### ISSUE TITLE
Cassandra: dbeaver displays the day prior for all date columns in results.

### ISSUE THREAD

**Issue by revelation1** [serge-rider/dbeaver#1527]
Version 4.04. I query for the July 3 and Dbeaver displays July 2!  This does not happen with native cqlsh or Toad.

`CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;;

CREATE TYPE test.udt_citystate (
city text,
state text
);

CREATE TABLE test.people (
Name text,
date date,
citystate FROZEN<udt_citystate>,
PRIMARY KEY (Name, date));

insert into test.people (Name,date,citystate) values ('FRED','2017-07-03',{city:'Houston',state:'Texas'});
select * from test.people where name = 'FRED' and date = '2017-07-03';`

![image](https://cloud.githubusercontent.com/assets/7517411/24710473/3231d0ce-19eb-11e7-9604-45566ea2cf26.png)

**Comment by revelation1** [comment]
Also, please notice in the results where the complex user defined type is displayed as null.  

Great tool.  I have been working around these little bugs but really liking it so far.

**Comment by serge-rider** [comment]
I can't reproduce both these issues.
![default](https://cloud.githubusercontent.com/assets/6398845/24827995/f4909cf4-1c5c-11e7-872e-30e01c518011.png)
What Cassandra server version do you have?

**Comment by serge-rider** [comment]
Any details?

**Comment by revelation1** [comment]
Cassandra 3.0.9.  Sorry for the slow response.

**Comment by serge-rider** [comment]
Tested on Cassandra 2.2 and 3.10. Still can't reproduce.

Please recheck that you use 4.0.4 version (these bugs were fixed a few versions ago).
If you've upgraded to 4.0.4 make sure you removed previous version completely (do not extract zip archive over previous installation).

**Comment by revelation1** [comment]
I did a fresh 64 bit install on a brand new windows 7 vm.   dbeaver 4.05 testing against cassandra 3.10.

Date is still off by one day.  I think it may have something to do with my date locale settings but they are just the default US ones.

**Comment by serge-rider** [comment]
Interesting.

Please post debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files) - maybe there are some errors/warnings there.

**Comment by revelation1** [comment]
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/930905/dbeaver-debug.txt)

**Comment by revelation1** [comment]
Is it possible its just an outdated driver?  I see dbeaver using DataStax Java Driver for Apache Cassandra [2.1.11]

According to this link that driver will produce bad metatdata on Cassandra 3.0.  Although its odd you don't see the same problem.

http://docs.datastax.com/en/developer/driver-matrix/doc/javaDrivers.html#java-drivers

**Comment by serge-rider** [comment]
I don't see anything suspicious in logs.
2.1.11 is version of DBeaver extension. DataStax Cassandra driver version is 3.0.5.

Changing locale doesn't affect anything.
So I still have no clue. I have almost the same environment.
BTW are complex types still broken in your case?

**Comment by revelation1** [comment]
I replaced the datastax driver jar file with the 3.2 version and no change (no errors either).  I also changed the column name thinking the [date] name would be throwing it off but no luck their either.  I switched from grid to text view...nope.  When I have time i will dig out wireshark...

Good news is that the complex type issue is resolved.

**Comment by revelation1** [comment]
I made a simpler test...

![image](https://cloud.githubusercontent.com/assets/7517411/25189306/c923dfac-24f6-11e7-891f-b9fb85598e81.png)

and ran wireshark during the select...

![image](https://cloud.githubusercontent.com/assets/7517411/25189469/3e7d5512-24f7-11e7-8fbf-51f8e8b883bf.png)

The highlighted hex is the actual date value returned.  \43c6 = 17350.  Adding those days to cassandras start date for that datatype (1970-01-01 + 17350) I get the correct date 2017-07-03.

Upshot is the date is crossing the network correctly.

**Comment by serge-rider** [comment]
Thanks for details.
Complex types: yes, there was an error in metadata reading. Actually you don't need to restart DBeaver - just refresh keyspace list.

Date issue: well, I think I'll have to sit in debugger for some time. This is not the first report about such problem.

**Comment by serge-rider** [comment]
I have a clue. Probably there is a bug in Cassandra LocalDate handling (which relies on local time zone).
Will try to fix this..

**Comment by revelation1** [comment]
That sounds promising.  I would assume that people want to see the actual stored value and that local time zone translation should not be a default.

**Comment by serge-rider** [comment]
I've reproduced this with PST timezone. 
With new fix it is working ok.

**Comment by revelation1** [comment]
Hey serge, I hate to beat a dead horse here but this is still broken (4.10).  It is now showing a month difference.

![image](https://user-images.githubusercontent.com/7517411/28389042-9b1a0728-6ca2-11e7-9c52-6b26e2a8faf0.png)

**Comment by serge-rider** [comment]
@revelation1 I'll take a look.

**Comment by serge-rider** [comment]
Thanks for report, indeed this was a bug in DBeaver.
I didn't remember this before. Perhaps it is a result of Cassandra driver upgrade in 4.1

**Comment by serge-rider** [comment]
This is MySQL-specific. In some cases recent MySQL driver (8.*) cant recognize server timezone properly and thus interprets timezones incorrectly.
Workaround: set driver property "serverTimezone" in driver  properties to a correct value. Valid timezone list: https://github.com/dbeaver/dbeaver/wiki/JDBC-Time-Zones

I think I'll add timezone selector in the main MySQL connection properties page.

Another workaround is to downgrade MySQL driver to 5.x version (note: it is not fully compatible with MySQL 8.* servers).

**Comment by yanirmor** [comment]
Hi Serge,
Thank you for the fast response and implementation in v5.1.2!
Unfortunately the issue persists even after changing the serverTimezone to UTC (through either the "Driver properties" or the new "Server Time Zone:" feature) 

If you have any other advice on how to solve this I would really appreciate it!

DB timezone: UTC
MySQL version: 5.6.39-log
Driver: mysql:mysql-connector-java:RELEASE [5.1.44]

Thanks again!
