### ISSUE TITLE
advanced paste overwrites row, losing data

### ISSUE THREAD

**Issue by verajosemanuel** [serge-rider/dbeaver#1528]
Copy & paste several rows overwrites data when pasting.

**steps to reproduce the issue:**

1- copy a bunch of rows from excel or previous dbeaver resultset
2- add new row to last record to avoid pasting over previous data (at the very end)
3- "advanced paste" over last row in table or resultset
4- last row containing data is overwritten (because new rows is not at the end but just one row above last one)

it's worse if we add a row at the first line. The rest of lines are overwritten.
This happens because adding a new row is actually moving last one just a line below and inserting a new one just above.
It's an unexpected (and dangerous) behaviour to insert new row just above last one.

**Workaround**:

Instead of adding new row, just duplicate last row and paste over the "new" last row. This way you're sure not losing data when pasting.

would not be safer to add new row **below** all rows to avoid this  issue?

Regards

windows 10, Dbeaver 4.0.4, mysql

**Comment by serge-rider** [comment]
I don't fully understand the issue.
You can configure row insertion in Preferences-Database->Result Sets->Insert new rows after current.
But it is not related to advanced paste.
Are there any problems with paste itself?

**Comment by serge-rider** [comment]
BTW you can toggle behavior of new/copy row action by pressing shift key.

**Comment by verajosemanuel** [comment]
You're right. There's an option for this behaviour.
I think that must be active out of the box insert new rows after current, because sometimes there's a lot of config to check and we did'nt notice this one.

regards
