### ISSUE TITLE
Make separate DBeaver windows independent

### ISSUE THREAD

**Issue by zejji** [serge-rider/dbeaver#1533]
When a DBeaver tab is dragged out into a separate window, it would be helpful if each new DBeaver window were independent (with its own taskbar tab).

Currently, if the user minimizes the main DBeaver window, this minimizes all the other DBeaver windows as well. This is somewhat unintuitive and different from the behaviour of the majority of other multi-window programs.

(**Note:** I am using DBeaver on Windows.)

**Comment by serge-rider** [comment]
Do you mean separate application window (main menu Window->Open New Window) or editor windows?
I don' think I can do anything with editor windows behavior - this is controlled by Eclipse framework.

**Comment by zejji** [comment]
Thanks. I did some research re the Eclipse framework and came to the same conclusion (i.e. that it doesn't appear to be possible to have editor panes dragged out into a separate window which is not parented to the main window).

So I'll close this issue...
