### ISSUE TITLE
Is it possible to log the content of UPDATE transactions for manually edited data?

### ISSUE THREAD

**Issue by zejji** [serge-rider/dbeaver#1534]
I occasionally use DBeaver in transactional mode to manually edit table data (by clicking on cells and typing new values). It is very useful to be able to modify multiple rows in multiple tables and then commit all the changes simultaneously.

However, although I have enabled Query Manager logging to file, I cannot see the actual changes made in the log.

Here is an example log excerpt after updating a number of rows and committing:

```
!ENTRY org.jkiss.dbeaver.core 0 201 2017-04-06 11:21:37.381
!MESSAGE COMMIT

!ENTRY org.jkiss.dbeaver.core 1 206 2017-04-06 11:28:42.991
!MESSAGE SELECT x.* FROM <redacted> x
WHERE <redacted> IN <redacted>
!SUBENTRY 1 org.jkiss.dbeaver.core 1 0 2017-04-06 11:28:43.055
!MESSAGE SUCCESS [19]

!ENTRY org.jkiss.dbeaver.core 0 203 2017-04-06 11:28:39.808
!MESSAGE COMMIT

!ENTRY org.jkiss.dbeaver.core 0 207 2017-04-06 11:29:36.427
!MESSAGE COMMIT

!ENTRY org.jkiss.dbeaver.core 0 217 2017-04-06 11:31:01.897
!MESSAGE COMMIT
```

As you can see, only the COMMITs are shown. Is there any way to make DBeaver log the content of the UPDATE queries too, so I can keep a record of the data which was manually changed?

**Comment by zejji** [comment]
Although I only mention UPDATE transactions in the previous post, naturally it would be helpful to log other data-modifying statements such as DELETE, INSERT, REPLACE etc.

**Comment by serge-rider** [comment]
Go to QM preferences (Filters button in QM view or Preferences->Database->Query Manager).
Enable all query types and all object types - thus you will see all logs.
