### ISSUE TITLE
Error creating new table DBeaver 4.0.4

### ISSUE THREAD

**Issue by MurKit** [serge-rider/dbeaver#1535]
I'm using DBeaver 4.0.4 on Linux Mint 32bit
MySQL 5.6.33-0ubuntu0.14.04.1

When trying to create new table in existing DB, get a error.

Here's SQL preview:

    CREATE TABLE magento.NewTable (

    )
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8
    COLLATE=utf8_general_ci ;

Then I click Persist:

    SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8
    COLLATE=utf8_general_ci' at line 3
      com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8
    COLLATE=utf8_general_ci' at line 3

**Comment by zejji** [comment]
You can't create a table with no columns in MySQL.
