### ISSUE TITLE
Possible to omit using "dbo." in front of every table name in MS SQL?

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1539]
I just started using DBeaver with MS SQL. 

I noticed the default is to show all schemas for a database:

![image](https://cloud.githubusercontent.com/assets/6610039/24771925/209b5a84-1ad5-11e7-9aba-bcdb1681522d.png)

When you try type a query. Say this:

select * from Foo. And you type "Ctrl+space" to autosuggest items, it doesn't find anything.

In order for the auto suggest feature to work, every query must begin with "dbo", so for instance "select * from dbo.Foo, and auto suggest will then work.

There almost needs to be a default "schema" drop down box at the top, right next to "GPWebServices" in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/6610039/24772046/8d760e88-1ad5-11e7-9bd9-17a770fd9a6a.png)

Am I missing a function that already exists?

**Comment by ilyacoos** [comment]
Hi,  Im using MSSQL also and have no problem with that. My version is EE 4.04, but elder versions works as well.

To exclude schema you dont need is rather trivial
![1](https://cloud.githubusercontent.com/assets/14123849/24789776/02939382-1b7d-11e7-8728-f78ec1b8dc3a.png)

To autosuggest first you need to choose Database you working in.  Then type the first letters of a table then Ctrl+Space.  Typing "dbo." shows you all tables in schema.
Autosuggestion from another database works also but you have to type those database' name first
![2](https://cloud.githubusercontent.com/assets/14123849/24789961/dd21276c-1b7d-11e7-90a3-c324f9242afb.png)

**Comment by xantari** [comment]
Thank you, I will try on monday, i think my issue was that I put exclude "*" in the schema list to only show dbo, and set "dbo" in the include list

**Comment by xantari** [comment]
I think I see what the problem is now. In order for auto-suggest to work properly you must have the "Tables" folder highlighted in the Database Navigator in the desired schema. If you have just the databasename selected then autosuggest does not work.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
