### ISSUE TITLE
DBeaver 3.5.8 hangs on autocomplete (MS SQL Server)

### ISSUE THREAD

**Issue by meddario** [serge-rider/dbeaver#154]
Hi all,
I'm trying to use DBeaver 3.5.8 as a replacement for MS SQL Server official client (using jTDS driver, automatically downloaded by DBeaver).
I noticed that DBeaver frequently freezes on autocomplete, i suppose in conjunction with a network timeout when communicating with the database. 

Steps to reproduce (however it happens randomly, probably due to a network timeout as i said before:

1. Connect to MS SQL Server database
2. Open a new SQL Editor
3. Start writing a query, for example "select field..." where field.. is the initial part of the name of the field of some table
4. If the autocomplete response is too slow (or completely missing), DBeaver stops responding (menus in Ubuntu's top bar remain usable and you can quit using the "Quit" voice in the menu)
5. If you click the red square button in the bottom bar, the button becomes gray and DBeaver remains unresponsive (menus in Ubuntu's top bar remain usable and you can quit using the "Quit" voice in the menu)

I attach: 

* [thread-dump.txt](https://github.com/serge-rider/dbeaver/files/81462/thread-dump.txt): the thread dump when DBeaver first freezes
* [thread-dump-after-cancelling.txt](https://github.com/serge-rider/dbeaver/files/81461/thread-dump-after-cancelling.txt): the thread dump after trying to click the cancel button at the bottom (red square)

Installation informations: 
[installation-information.txt](https://github.com/serge-rider/dbeaver/files/81466/installation-information.txt)

Is there any way to avoid the freeze?

Thanks in advance,
Dario

**Comment by codebling** [comment]
I spent a while trying to set up a MS SQL Server instance and eventually gave up. Can you confirm that this only occurs on MS SQL Server connection types?

**Comment by meddario** [comment]
Hi,
I tried without success to reproduce the error with a MySQL connection (I think that the reason is that i can't simulate a very slow/losing packets network).

Maybe there is some other information that i can provide?

**Comment by codebling** [comment]
Thanks for the info. I'll try reproducing with forced lag on a MySQL connection, since I already have a few set up. If I am not able to reproduce, I'll try again with MS SQL Server. 

The fact that you only see the SQL Editor freeze in certain cases is already enough information to show that it's not the same cause as #147. 

I'll try reproducing and get back to you

**Comment by meddario** [comment]
I don't know if it can be useful, i tried to reproduce the issue on Windows and for now i can't cause the freeze.

For one moment it seemed freezed and then showed this window:

![dbeaver-win7-reconnect](https://cloud.githubusercontent.com/assets/16596646/12202474/593c3068-b62a-11e5-932e-e2759bbcf048.png)

Maybe on Windows it tries to reconnect while in Linux it couldn't and it freezes (or maybe the two things are totally unrelated)

Installation information:
[dbeaver-windows.txt](https://github.com/serge-rider/dbeaver/files/82915/dbeaver-windows.txt)

**Comment by serge-rider** [comment]
Thanks for report.
Although I also can't reproduce that (yet) thread dump was really useful.
Will try to fix it somehow..

**Comment by codebling** [comment]
If it is helpful for your debugging, I can add artificial delay on my network using [tc netem](https://wiki.openwrt.org/doc/howto/packet.scheduler/sch_netem) and give you access. I don't have an instance of SQL Server on my network but I'm sure I can set one up. Just let me know what you need.

**Comment by serge-rider** [comment]
Now when I have the stack I can just insert delays programatically. 
But thanks anyway.

**Comment by meddario** [comment]
Thank you very much, is this fix included in version 3.5.9?

**Comment by serge-rider** [comment]
Yes.
Please validate.

**Comment by meddario** [comment]
I tried, it hanged on a query, then i pressed "cancel" and now it's stuck (i can't close it because it says "Editor can''t be closed while SQL query is being executed").
[thread-dump-3-5-9.txt](https://github.com/serge-rider/dbeaver/files/103448/thread-dump-3-5-9.txt)

I upgraded the old installation, if you want me to do a clean test i'm available, just tell me which files/folders to delete to reset all preferences (i am on Ubuntu Linux).

**Comment by meddario** [comment]
Overall, now the program itself doesn't freeze, but apparently there isn't a way to cancel tasks.

![dbeaver-3 5 9-tasks](https://cloud.githubusercontent.com/assets/16596646/12556635/36ee86ae-c387-11e5-9c01-1ddfa669f0d3.png)

**Comment by serge-rider** [comment]
That's odd. I tested it against MySQL and cancel worked just fine. As far as I know jTDS driver also supports query cancel.
Will retest this..

**Comment by meddario** [comment]
Retested in 3.6.2, seems solved now.

**Comment by serge-rider** [comment]
Great. Thanks for update.

**Comment by gogosofta** [comment]
Hi, I think this issue is the same as that one:
https://github.com/serge-rider/dbeaver/issues/1699
