### ISSUE TITLE
UI blocks when enumerating a large schema

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1540]
I have a schema with several thousand (~5000) tables.

When I use Database Navigator, connect to the database, expand the schema, then expand the Tables folder, the DBeaver UI blocks for several minutes.

When I instead double click the schema it opens in 2-3 seconds.

I realise the Database Navigator has to manage a much larger data tree since it includes all connections, but was just wondering if there is a way to optimise this or avoid this UI blocking.

**Comment by serge-rider** [comment]
I will try to reproduce this and see what can be done to optimize this.

**Comment by serge-rider** [comment]
Well, I've tested it with 10k tables. UI freezes just for a few seconds (<10). Looks reasonable.
What is your database?
What is your OS?

**Comment by anophelesgreyhoe** [comment]
Oracle database, Ubuntu is my OS.

It's strange that it would take so long in DB Navigator but open the schema view quickly.

**Comment by serge-rider** [comment]
Database navigator works slower with big number of elements because it is hierarchical.
It is controlled by Eclipse UI framework which is a bit different for different OSes.

I'll check this on Ubuntu..

**Comment by serge-rider** [comment]
This issue happens with some GTK versions.
I'm afraid I can't fix this from DBeaver side.
