### ISSUE TITLE
Commit/Rollback Enabled for select statement

### ISSUE THREAD

**Issue by anshu781126** [serge-rider/dbeaver#1544]
Commit/Rollback Enables for any sql statement executed; even for select statements.

Version 4.0.4

![image](https://cloud.githubusercontent.com/assets/26997587/24788570/e34ee5d0-1b8b-11e7-9ff5-e27b59197afb.png)

**Comment by serge-rider** [comment]
Yes, this was made on purpose (#1510). Because SELECT statements locks underlying tables and should be a way to release locks.

**Comment by titopepper** [comment]
@serge-rider  - Select statements do not lock rows in Oracle, yet I still see the uncommitted transactions count increase. Read transactions will only lock if "for update" is used on the select.

**Comment by vineethpisvas1** [comment]
@serge-rider Is there a way to configure enabling/disabling this feature for each Connection Type separately or by any other means?

**Comment by serge-rider** [comment]
@vineethpisvas1 No, currently there is no such config. Please create new ticket for that, with some explanations why this is needed.

**Comment by MiqueiasVieira** [comment]
This issue is back in 7.0 version

**Comment by mzatko** [comment]
Still there in Version 21.0.4

**Comment by hanulful** [comment]
This drives me crazy.. (ver 21.0.4)

**Comment by hanulful** [comment]
> Still there in Version 21.0.4

Why don't you read "Smart commit mode" section
https://dbeaver.com/docs/wiki/Auto-and-Manual-Commit-Modes/

**Comment by jmevel** [comment]
> > Still there in Version 21.0.4
> 
> Why don't you read "Smart commit mode" section https://dbeaver.com/docs/wiki/Auto-and-Manual-Commit-Modes/

Personally I've smart commit enabled and I'm in Auto commit mode. Though, when I want to quit DBeaver it always ask me if I want to commit my transactions even though I only performed some `SELECT` queries... 

So the smart commit seems not to work as it is written in the documentation
