### ISSUE TITLE
Pasting dates in date column dbeaver is dangerously messing data

### ISSUE THREAD

**Issue by verajosemanuel** [serge-rider/dbeaver#1546]
**Steps to reproduce the issue**

Copy dates from any source 

Day - Month - Year
04/04/2017 
05/04/2017
07/04/2017

Date format global options is:
yyyy-MM-dd

when pasting in dbeaver date column you get:

Year - Month - Day
2017-04-04
2017-05-04
2017-07-04

**As you can see is messing with months and days.**  

Windows 10. Spanish sort. Same issue on Mysql and PostgreSQL

**Comment by serge-rider** [comment]
I think it is a bad idea to try to copy/paste dates in different formats.

At first DBeaver tries to parse your string in current format.
If it fails then it parses date using Java default format (here is algorithm description: https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#parse(java.lang.String))

Workaround: change date format in DBeaver preferences so it will match your local format.

**Comment by verajosemanuel** [comment]
Serge, date format  in dbeaver preferences is yyyy-MM-dd 

Double checked all configuration options. Dates format is yyyy-MM-dd. So we are pretty sure dbeaver is taking days as months when pasting dates copied from dbeaver itself

**Comment by serge-rider** [comment]
You are saying that you copy source date in format `04/04/2017` (i.e. MM/dd/yyyy). 
While DBeaver date format is `yyyy-MM-dd`. 
How DBeaver can understand source format (which is completely different)?

**Comment by verajosemanuel** [comment]
That's the issue. Dbeaver is showing me dates in a format that's not the desired one, so when copying and pasting the issue arises.

**Comment by serge-rider** [comment]
Now I'm lost completely.

What is the actual problem - how date/time values are presented or how they are pasted/converted? Is there any 3rd party software in this scenario?

Please provide steps to reproduce.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.

**Comment by verajosemanuel** [comment]
could not reproduce with latest version (downloaded today).
thanks

**Comment by tati-kru** [comment]
@verajosemanuel thank you for your response
