### ISSUE TITLE
Refresh grid after TRUNCATE TABLE

### ISSUE THREAD

**Issue by greenpeas** [serge-rider/dbeaver#1549]
It would be great do refresh data grid after TRUNCATE TABLE.
![image](https://cloud.githubusercontent.com/assets/3856344/24826326/f3928766-1c3b-11e7-8766-bc5a877a6a90.png)

**Comment by serge-rider** [comment]
Agreed.

**Comment by tony-gutierrez** [comment]
Is truncate specific to driver? It doesnt show for mssql?

**Comment by serge-rider** [comment]
Yes, it is specific to driver. Vyt it is supported by MySQL/MariaDB. Check that you are using `MySQL` driver but not `MySQL 3.x`.

**Comment by tony-gutierrez** [comment]
I'm in mssql, not mysql. I tried both drivers and neither had a truncate option.

**Comment by serge-rider** [comment]
@tony-gutierrez It is not yet supported for MS SQL. Will be a part of #810
