### ISSUE TITLE
formatting of case statements leaves a lot to be desired

### ISSUE THREAD

**Issue by farmboy0** [serge-rider/dbeaver#155]
Here is an excerpt from a view definition:
        CASE
            WHEN c.v_k= ''
            THEN 'a' WHEN c.v_k= '1  '
            THEN 'b' WHEN c.v_k= '2'
            THEN 'c' WHEN c.v_k= '3'
            THEN 'd' WHEN c.v_k= '4'
            THEN 'e' WHEN c.v_k= '5'
            THEN 'f' WHEN c.v_k= '6'
            THEN 'g' WHEN c.v_k= '7'
            THEN 'h' WHEN c.v_k= '8'
            THEN 'i'
        END AS S

As you can see the WHEN and the corresponding THEN arent on the same line.
This makes reading this CASE unnecessary hard.
Please change the formatting to have WHEN THEN on the same line.
If the lines get too long they should be broken after WHEN and THEN and clauses after
should be intended one level.

**Comment by codebling** [comment]
Good point

**Comment by serge-rider** [comment]
Fixed. Hopefully this fix won't break WHEN/THEN formatting in other circumstances.
