### ISSUE TITLE
[Feature Request] Selecting column  data type is not user-friendly

### ISSUE THREAD

**Issue by ceyhunnabiyev** [serge-rider/dbeaver#1553]
I think, by default, it would be nice to use editable select box with auto-completion for column data type, because it is difficult   to focus cursor on non-clickable link (data type info tab) area of column data type select box. 

Thanks for great work!!!
Regards..

**Comment by serge-rider** [comment]
Agreed, sometimes active links are really annoying.

I think this could be solved by making links active only if CTRL key is pressed. Or some other similar solution.

**Comment by ceyhunnabiyev** [comment]
Hi @serge-rider ,
Maybe using small info icon on right side of data type area, and if it is possible, as I said  above, it would be nice to use editable selectbox.. ( In this way, copy-paste method will work in order to select data type  quickly )

**Comment by serge-rider** [comment]
This may work. Although links problem happens not only with data types. They are used in properties, foreign keys, etc. So I'm thinking about general solution.

**Comment by ceyhunnabiyev** [comment]
@serge-rider ,  If links  is not changeable for each item, erasing all links and using help like documentation with separate menu tab  would be good idea, I think..
