### ISSUE TITLE
Attempting to connect to a file.fb results in GDS exception - unable to complete network request

### ISSUE THREAD

**Issue by 00cpxxx** [serge-rider/dbeaver#1556]
Hi all, thanks for this great program. It works fine for opening databases over TCP but attempting to open a local path using Firebird results in an error.

GDS Exception. 335544721. Unable to complete network request to host "localhost".
  Unable to complete network request to host "localhost".
    java.net.ConnectException: Conexão recusada (Connection refused)

The end connection string is like:
jdbc:firebirdsql://localhost:3050//databases/DB.FB

I don't have FireBird installed, I just wanted to browse the file data as it is possible with SQLite databses. I tried editting the path to remove the attempt to connect to localhost but that did not work. If this is not achievable I understand and ask apologies in advance.

**Comment by serge-rider** [comment]
Embedded Firebird is tricky. It requires additional native binaries besides driver JAR.

1. You need to add jaybird22_x64.dll to driver libraries.
2. You need to add Jaybird server directory to PATH
3. Restart DBeaver

http://stackoverflow.com/questions/17449967/failed-to-load-firebird-client-library-embedded-database-with-jaybird
