### ISSUE TITLE
JSON editing does not work (for Postgres)

### ISSUE THREAD

**Issue by Jeetah** [serge-rider/dbeaver#1557]
Editing of JSON does not get saved - inline as well as in separate editing window. Saving seems to do this but after commit this is not persisted in DB. If using update statement this works perfectly - so definitely a DBeaver issue.

**Comment by serge-rider** [comment]
Can't reproduce.
How do you edit JSON (inline, in value panel)?
Do you use the most recent version of DBeaver (4.0.4)?

**Comment by Jeetah** [comment]
Inline as well as panel. And yes, using most recent. Perhaps it lost connection to DB (although I think I tried also reconnecting)? That's something I observed also sometimes: Editing is still possible but without a warning it is not saved if connection is lost.

**Comment by serge-rider** [comment]
I still can't reproduce that. If connection was lost and I click save then I see something like this:
![default](https://cloud.githubusercontent.com/assets/6398845/25313559/508b4d0a-2839-11e7-9aa4-a6f5d9bf899b.png)
Please check error log. Maybe there was some error which wasn't visualized in error dialog.

**Comment by Jeetah** [comment]
I had this issue again recently. Had a connection, edited a column and a JSON inline (pretty printed by DBeaver), saved, commited -> column has been saved but not the JSON. Was totally reproducible.

**Comment by serge-rider** [comment]
Could you provide steps to reproduce? 
And table DDL/INSERT.

**Comment by serge-rider** [comment]
In 4.0 and 4.1 version JSON support presents only in EE version
