### ISSUE TITLE
Can't open dbeaver

### ISSUE THREAD

**Issue by Yanniick** [serge-rider/dbeaver#1560]
Hey,

Just installed dbeaver, it said that my Java wasn't up to date so I updated it and after that, when I try to open dbeaver, I get the error:

An error has occurred.
See the log file
/Users/yannick/.eclipse/org.jkiss.dbeaver.product_4.0.4_944233459_macosx_cocoa_x86_64/configuration/1491828471027.log.

In that file I see a very long code and then I see something like this:

!ENTRY org.eclipse.ui.intro 2 0 2017-04-10 14:47:52.190
!MESSAGE Could not resolve module: org.eclipse.ui.intro [92]
  Unresolved requirement: Import-Package: org.eclipse.e4.core.di.annotations
    -> Export-Package: org.eclipse.e4.core.di.annotations; bundle-version="1.5.0.v20151127-1241"; bundle-symbolic-name="org.eclipse.e4.core.di.annotations"; version="0.0.0"
       org.eclipse.e4.core.di.annotations [35]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

!ENTRY org.eclipse.osgi 4 0 2017-04-10 14:47:52.194
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).

I'm all new to this, can somebody help me?
I use a Macbook pro with the latest iOS.

**Comment by serge-rider** [comment]
You need to install JDK 1.8 (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
Simple Java update doesn't work on MacOS.
