### ISSUE TITLE
[Question] How can I change no action to cascade on delete for foreign key constraint in Oracle Connection? 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [serge-rider/dbeaver#1563]
Dbeaver version - 4.0.4,
Regards

**Comment by ceyhunnabiyev** [comment]
Hi @serge-rider , it is important  for my work, any answer for this??

**Comment by serge-rider** [comment]
This feature is not supported for Oracle.
Currently the only option is to drop/create foreign key.

**Comment by ceyhunnabiyev** [comment]
@serge-rider , Other database tools has this option. Can you add this feature??

**Comment by serge-rider** [comment]
As far as I know Oracle doesn't support modifying of FK delete rule. http://stackoverflow.com/questions/4375189/changing-a-fk-delete-rule-in-oracle-without-dropping-and-recreating-it

Potentially it is possible to emulate this as drop+create in DBeaver. Although it will require quite a bit of work.

**Comment by ceyhunnabiyev** [comment]
@serge-rider , however I can change this in edit table window of both Oracle sql Developer and Pl/SQL Developer. Allright, No problem. I will do drop+create.

Thanks for your answers,
Greak Work.
