### ISSUE TITLE
DDL generator broken for Redshift tables (DBeaver 4.0.4)

### ISSUE THREAD

**Issue by dh-rico** [serge-rider/dbeaver#1564]
Right now the DDL generator is throwing an exception for Redshift tables in DBeaver 4.0.4.
The exception appears always when I try to show the DDL using the context menu or double click on the table.  

Following error is thrown:

/* ERROR WHILE READING SOURCE:

org.jkiss.dbeaver.ext.postgresql.model.PostgreDialect cannot be cast to org.jkiss.dbeaver.ext.generic.model.GenericSQLDialect
*/

**Comment by serge-rider** [comment]
Thanks for report.
