### ISSUE TITLE
why I cant use socks proxy ?

### ISSUE THREAD

**Issue by myururdurmaz** [serge-rider/dbeaver#1565]
i have configured sock proxy and database connection informations

![screenshot_2017-04-11_16-05-48](https://cloud.githubusercontent.com/assets/1057861/24910794/8fabde9e-1ed1-11e7-89eb-4496be2b8fd0.png)

![screenshot_2017-04-11_16-06-13](https://cloud.githubusercontent.com/assets/1057861/24910719/542e0fb8-1ed1-11e7-9fc1-e18031b4472e.png)
but why dbeaver try to connect real ip ?
![screenshot_2017-04-11_16-06-31](https://cloud.githubusercontent.com/assets/1057861/24910743/699d093a-1ed1-11e7-9825-3b7a1bc61e13.png)

**Comment by myururdurmaz** [comment]
but my socks proxy always open. it's  my other machine. i will check version number of dbeaver

**Comment by myururdurmaz** [comment]
my versiyon number 4.0.4
![screenshot_2017-04-13_09-47-00](https://cloud.githubusercontent.com/assets/1057861/24993260/425efdb6-202e-11e7-9ff5-e576fd3d3c29.png)

**Comment by serge-rider** [comment]
If socks proxy still doesn't work - please post debug logs (make connection attempt, then exit DBeaver and get log file: https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by myururdurmaz** [comment]
i have tested another connection and same result. log files attached
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/919372/dbeaver-debug.txt)

**Comment by serge-rider** [comment]
Ah, I see what is the problem. You are using custom JDBC URL - socks proxy or SSH tunnel aren't working in this case (because actual URL has to be changed). Try to use Basic connection type.

**Comment by myururdurmaz** [comment]
but i can connect with version 3

![a3](https://cloud.githubusercontent.com/assets/1057861/25082279/724b4b74-2358-11e7-8386-269f4be99b61.png)
![a2](https://cloud.githubusercontent.com/assets/1057861/25082280/724d7a20-2358-11e7-9f73-864e35b65e15.png)
![a1](https://cloud.githubusercontent.com/assets/1057861/25082281/72513e1c-2358-11e7-9b1f-686beefe7b22.png)

**Comment by serge-rider** [comment]
Well, I was wrong about connection URL. SOCKs proxy works differently.

Do you use exactly the same Oracle driver version in DBeaver 3 and 4?
I still can't reproduce this issue (DBeaver 4.0.5, Oracle driver 11.2.0.3.0).

**Comment by myururdurmaz** [comment]
ojdbc8.jar 

manifest
=======
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Implementation-Title: JDBC
Implementation-Version: 12.2.0.1.0
sealed: true
Repository-Id: JAVAVM_12.2.0.1.0_LINUX.X64_161213
Specification-Vendor: Sun Microsystems Inc.
Specification-Title: JDBC
Created-By: 25.91-b14 (Oracle Corporation)
Specification-Version: 4.0
Implementation-Vendor: Oracle Corporation
Main-Class: oracle.jdbc.OracleDriver

Name: oracle/sql/
Sealed: false

Name: oracle/sql/converter/
Sealed: false

Name: oracle/jdbc/logging/annotations/
Sealed: false

Name: oracle/sql/converter_xcharset/
Sealed: false

**Comment by myururdurmaz** [comment]
ojdbc6.jar
Implementation-Version: 11.2.0.3.0
**works fine** i have tested

**Comment by serge-rider** [comment]
Ok then. I'll try to debug with Oracle 12 drivers later, probably they have much more complicated connection procedure which can't be handled by DBeaver.

Thanks for details. Closing this.

**Comment by palytoxin** [comment]
in my pc, ojdbc8.jar hasn't been working yet
dbeaver version is 6.0.1

**Comment by michaelford** [comment]
Hi,

I've found the same issue in Version 7.0.0.202003081756. 

Using the ojdbc6.jar instead of ojdbc8.jar appears to be a workaround however I've only tested making the initial connection.

I've raised https://github.com/dbeaver/dbeaver/issues/8427.

Michael
