### ISSUE TITLE
Cassandra queries fail with org.jkiss.dbeaver.DBException: Connection invalidate not supported

### ISSUE THREAD

**Issue by ksilin** [serge-rider/dbeaver#1568]
I can connect to the cluster, see the keyspaces and the data in the tab, but unable to issue any queries from the script editor. All attempts to execute result in the same error: 

`org.jkiss.dbeaver.DBException: Connection invalidate not supported`

Using DBeaver Enterprise 4.0.4

**Comment by serge-rider** [comment]
Disable "Invalidate connection before execute" option (Preferences->SQL Editor->SQL Processing).
You can disable it only for Cassandra connection.

**Comment by ksilin** [comment]
Worked as advertised. Many thanks, @serge-rider!
