### ISSUE TITLE
[Feature Request]Save custom filters for any table.

### ISSUE THREAD

**Issue by ashe23** [serge-rider/dbeaver#1569]
It would be very handy if we could save our custom filter for specific table.
Example:

![1492066454192](https://cloud.githubusercontent.com/assets/8270558/24993693/29cf456a-2030-11e7-9b76-c508585eba0a.jpg)

We selected our custom filters and ..

![1492066630633](https://cloud.githubusercontent.com/assets/8270558/24993714/39c89566-2030-11e7-91b2-042ce45b928a.jpg)

After that anytime i open this table (even if i quit dbeaver ) my filters apply automatically.

P.S. Maybe that functionality already exists, i just could not find them.

Thanks.

**Comment by anophelesgreyhoe** [comment]
Yes, I came here to add this feature request if nobody had already.

Ideally Dbeaver would allow us to save both filters and sort orders per table, and have a way to select one of them after opening a table/view in Data view.

**Comment by serge-rider** [comment]
This feature was implemented in #894.

**Comment by dakusan** [comment]
The column ordering does not seem to be saved along with the rest of the filters.
