### ISSUE TITLE
Dropped mysql database while trying to grant all permissions

### ISSUE THREAD

**Issue by MurKit** [serge-rider/dbeaver#1571]
I am using 5.6.33-0ubuntu0.14.04.1 (Ubuntu) on Linux Mint 17.3 and DBeaver 4.0.4

I was trying to grant all permissions for new user on one database. It failed, but all the permissions except File and Lock tables were granted. I'm using Magento, so I have to grant ALL permissions.

By the way, when trying grant File privilege, there is always error.

Later I couldn't see the Users list with an error "Table 'mysql.user' doesn't exist".

So I entered mysql through the console and seen that there is indeed no table mysql.user. There was no mysql database either. Then had to reinstall mysql-server-5.6. 

Now I will grant all permissions from console.

**Comment by serge-rider** [comment]
Perhaps you had some issues with initial MySQL server installation. 
DBeaver definitely doesn't drop any tables or databases in any circumstances.
