### ISSUE TITLE
SQL script execution including a stored procedure only displays one row of output for the s.p.

### ISSUE THREAD

**Issue by rgallast** [serge-rider/dbeaver#1572]
I apologize if this has been asked before. Tried searching for a couple of days and couldn't find anything.

I'm using DBeaver against MariaDB 10.1. I'm trying to execute a SQL script that includes declaring a stored procedure and the call to the stored procedure itself. When I try to execute the SQL script, it only shows one row of output from the stored procedure, even though I know I perform several SELECTs inside of it. I checked that the "Fetch resultsets" box is selected as I thought some people had suggested but didn't make a difference. Am I doing something wrong?

Thanks a lot!

**Comment by serge-rider** [comment]
Can't reproduce. Please post an example of such stored procedure.

**Comment by rgallast** [comment]
![image](https://cloud.githubusercontent.com/assets/908838/25021170/dfc740e0-2056-11e7-89ef-f431d952c046.png)

**Comment by serge-rider** [comment]
Ah, you meant multiple results.
It is a misconfiguration in MySQL driver. Fix will be added in the next version, thanks for report.

**Comment by rgallast** [comment]
Thanks for the help! good job, by the way!
