### ISSUE TITLE
Money amount not displayed

### ISSUE THREAD

**Issue by dsearsiii** [serge-rider/dbeaver#1573]
I have a postgres db with a field defined as:
money NOT NULL DEFAULT 0.00
When inserting or updating a value up to 999.99, it displays normally in DBeaver.
When inserting or updating a value 1000.00 or greater, it displays as [null] in Grid presentation and is blank in Text presentation.
lc_monetary = en_US.utf8

**Comment by serge-rider** [comment]
Check #1217
Money data type support in PG JDBC driver is very poor.
You can post debug log - maybe your problem is a different. But most likely there is nothing I can do with that.

**Comment by dsearsiii** [comment]
Sorry, I was out of the office for a few days. Log is attached.
In my own java app, I'm having to cast money amounts to numeric to avoid the error for amounts above 999.99:
select cast (amount as numeric) from payment;
I lose the $ sign, but I don't need it anyway. Looks like it is dropped in dbeaver for amounts < 1000.00 anyway.

Thanks.
Don
[dbeaverlog.txt](https://github.com/serge-rider/dbeaver/files/930197/dbeaverlog.txt)

**Comment by aap4ixx** [comment]
Hi,

Do you have any update about this problem?
I have the same problem, if value >999 they show "null" :(

**Comment by serge-rider** [comment]
Looks like recent PG driver supports money better. At least we can get it with getString()

**Comment by aap4ixx** [comment]
Hi,
Only for information.

I compared money type with int8 (bigint) and found what the range of values is the same.
So i change money type to bigint and didn't see any problem in DB.

Value range:
bigint (8 byte): -9223372036854775808 to 9223372036854775807
mobey: (8 byte): -92233720368547758.08 to +92233720368547758.07 
The difference is only in the points.

**Comment by serge-rider** [comment]
Yes, bigint is the same as money and is not buggy.  However some people still use money directly.
I'll support it as a string data type.
