### ISSUE TITLE
[Feature request] Results window - change layout to vertical or detach results window

### ISSUE THREAD

**Issue by rafpran** [serge-rider/dbeaver#1575]
I assume some of us use one or more displays, sometimes larger than 20 ".
It will be more convenient to maximize the editor (at least in the vertical direction) and move the results window to another screen (or side of the screen).

**Comment by serge-rider** [comment]
Maximize/minimize are already there.
Results orientation switcher will be added in 4.1.
Moving results to a separate view is a bigger task. Please create separate feature request if you still think that this makes sense.

![default](https://user-images.githubusercontent.com/6398845/27515681-dd0e8c2a-59b1-11e7-8853-84bd99a2057a.png)
![default](https://user-images.githubusercontent.com/6398845/27515683-e61b3c3c-59b1-11e7-984c-5683941d6db5.png)
