### ISSUE TITLE
Rearrange columns in the result panel

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#1577]
Just a suggestion, make possible rearrange the columns order on result panel by drag and drop.

![captura de tela de 2017-04-14 11-13-08](https://cloud.githubusercontent.com/assets/7952798/25046014/76be83ba-2105-11e7-92b1-29b0f0d9f107.png)

It would be useful for tables with many columns where you want compare some them, quick, without change the query.

**Comment by serge-rider** [comment]
Agreed, that would be helpful.
Currently you can rearrange columns in filter settings (move column up and down).

**Comment by serge-rider** [comment]
Will be done along with #1591

**Comment by julianblk** [comment]
Would you consider adding the ability to remember column position? (one of the useful things in SQL Developer). When working in a task for a few days you usually need to see the same 4 or 5 columns first. Not having to rearrange them every time would be great.

**Comment by serge-rider** [comment]
Columns rearrange works with pressed <kbd>ALT</kbd> key and column dragging.
Saving results viewer state will be tracked in #894.

**Comment by jeisoncp** [comment]
Left Alt? Right Alt?

I tried but can't move the columns.

**Comment by jeisoncp** [comment]
I managed to change GNOME Shell shortcut combination, but I still can't drag the column.

https://nuvem.jeison.net/s/vS6ZyxpN7zk5MrB

**Comment by serge-rider** [comment]
Any Alt actually. This works in Windows and on my local Ubuntu.

What is your OS version?

**Comment by jeisoncp** [comment]
Ubuntu 16.04.3 LTS 64-bit with Gnome 3 Shell.

**Comment by rythym05** [comment]
I see that it is not possible to drag and drop columns when the columns are many and there is a scrollbar

**Comment by capaj** [comment]
I can't rearange the columns too. I am on Ubuntu 18.04, DBeaver 5.1.2
