### ISSUE TITLE
[question] pl/sql execution

### ISSUE THREAD

**Issue by fayca121** [serge-rider/dbeaver#1578]
Hi,
When I try to execute an oracle pl/sql script (with ALT+X ) for exemple:

BEGIN
	FOR i IN 0..10 LOOP
	dbms_output.put_line(i);
	END LOOP;
	
END;
/

I'm always receiving  the following error message:

![2017-04-16 14_30_07-execution error](https://cloud.githubusercontent.com/assets/547548/25071499/7a167fba-22b1-11e7-95b7-8feaea15502c.png)

As the script is working fine with other database tool like TOAD, I'm asking if there is any configurations/parameters to be applied.

thanks in advance

**Comment by serge-rider** [comment]
DBeaver doesn't support (yet) Oracle style of scripts dividing.

Workaround: select your query and run with CTRL+Enter.

**Comment by fayca121** [comment]
Effectively , the workaround is working fine .

Thank you for this great db tool.
