### ISSUE TITLE
Export/Import configuration from command line?

### ISSUE THREAD

**Issue by rgl** [serge-rider/dbeaver#1579]
I'm trying to automate the DBeaver installation for including it at [rgl/sql-server-vagrant](https://github.com/rgl/sql-server-vagrant). But I'm not sure how to configure a DBeaver Driver for MS SQL and create a DBeaver connection to localhost from the command line or PowerShell script. Can you help me?

I've tried to just copy the drivers.xml and .dbeaver-data-sources.xml to the respective DBeaver configuration directories inside the user home before launching DBeaver, but that does not really worked out... maybe there's a way to export/import the configuration from the command line?

I would also like to use the drivers that come in [sqljdbc](https://chocolatey.org/packages/sqljdbc) chocolatey package instead of the ones that come from maven.

**Comment by rgl** [comment]
I found what seems to be a partial answer at https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Connections but where exactly should I put the csv or xml file before starting DBeaver?

**Comment by serge-rider** [comment]
In drivers.xml you can use absolute path to point to any pre-installed drivers. Also you can check this: https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Drivers

But there is a bug in recent versions (#608) which prevent variables usage in custom libraries path. It is fixed 4.0.5.

**Comment by serge-rider** [comment]
Does drivers.xml generation solve the problem?

**Comment by rgl** [comment]
It worked (see [rgl/sql-server-vagrant](https://github.com/rgl/sql-server-vagrant/commit/4778102e7cef167a036a53f53d59ca1280973655))! Thank you! :-)

Can you update https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Connections to mention that we should create the `.dbeaver-data-sources*.xml` files inside `%HOMEPATH%\.dbeaver4\General`?

**Comment by serge-rider** [comment]
Ok, great.
Wiki was fixed.
