### ISSUE TITLE
uniqueidentifier not displaying

### ISSUE THREAD

**Issue by 65816** [serge-rider/dbeaver#1581]
While connecting to a SQL Anywhere 12 database through a ODBC connection, values of this data type - uniqueidentifier default to NULL.

Using this query will result in them being displayed correctly

select convert(nvarchar(50),code) from table;

Using the PERL to connect to same ODBC allows for the value to be displayable without the need for the convert.

I found googling the issue that perhaps adjust the result sets binary settings would resolve the issue. This seems to have no effect.

Thank you.

**Comment by serge-rider** [comment]
Please attach error/debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files).
Seems to be some error in data type handling.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
