### ISSUE TITLE
Last Edit Location shortcut  is not working (Ctrl+Q by default)

### ISSUE THREAD

**Issue by axel-antunez** [serge-rider/dbeaver#1583]
This issue is related **DBeaver v4.0.5**; 

Steps to reproduce:

1. Download and install a new fresh **DBeaver v4.0.5** (test on linux, using **dbeaver-ce-4.0.5-linux.gtk.x86_64.tar.gz**)
2. Execute DBeaver
3. Create a new connection to any database.
4. Open the connection and open a new SQL Editor window
5. Input a sample text and move the editing cursor to a different position
6. Hit **Ctrl+Q** (default shorcut for _last edit location_). The expected behavior would be that the cursor be located on the last edit location. However, nothing happens.

See that the default preferences are set to Ctrl+Q for this shortcut:
![dbeaver-prefernces](https://cloud.githubusercontent.com/assets/7559600/25102742/2deb6f62-2390-11e7-8d92-56d0030c2d1c.png)
Please notice that when performing these same steps with DBeaver 3.x, it works as expected, so the issue was introduced on the version 4.

If you need more information, please let me know.

Thank you

**Comment by serge-rider** [comment]
Yes. Default navigation action set was disabled in one of recent versions (by mistake).
I'll return it back.
