### ISSUE TITLE
SQL script execution including a stored procedure missing results if the stored procedure produces multiple results

### ISSUE THREAD

**Issue by rgallast** [serge-rider/dbeaver#1584]
I was testing the issue 1572 with the new release (4.0.5) that I saw that incorporates the fix for that issue with the same SQL script and I noticed that there's only 2 results from the execution of the script:

'abc'
and 'def'

I've been checking all over my configuration to see if I have something incorrect, but can't figure out what. Is there anything that needs to be set to get more than 2 results? Thanks

Here's the SQL script I'm testing:

use DB1;

DROP PROCEDURE IF EXISTS proc1;
DELIMITER //
CREATE PROCEDURE proc1(DB_TYPE VARCHAR(100), QA_SYSTEM_NAME VARCHAR(100))
BEGIN
	SELECT 'abc';
	SELECT 'def';
	SELECT 'ghi';
END//
DELIMITER ;

CALL proc1('p1', 'p2');
DROP PROCEDURE IF EXISTS proc1;

**Comment by serge-rider** [comment]
Can't reproduce:
![default](https://cloud.githubusercontent.com/assets/6398845/25151292/beac8c4a-248d-11e7-8f31-df9f50bea063.png)

Is this happens always?
Try to close/open SQL editor.

**Comment by rgallast** [comment]
![image](https://cloud.githubusercontent.com/assets/908838/25151699/1e6ac8dc-244c-11e7-9f96-43bd6d7e9a8e.png)

I've tried that and get the same result. As you can see, I get 2 "Result" tabs only. Based on that fact that it's not happening to you I was wondering if one of my settings is incorrect. Thanks

**Comment by serge-rider** [comment]
I did find some strange behavior of results tabs with MariaDB driver (and don't see it with MySQL driver).
Investigating..

**Comment by serge-rider** [comment]
What exactly MariaDB driver version do you user?

**Comment by rgallast** [comment]
We're running against MariaDB 10.1.19. Client is Windows, server is CentOS 6.8

**Comment by serge-rider** [comment]
I mean driver version. You can see it when pressing "Test connection" or in Properties view (when clicking on connection).
E.g. my driver version is "MariaDB connector/J 1.5.9"

**Comment by rgallast** [comment]
I get:

Driver: MariaDB connector/J 1.5.5

I'll try upgrading and will let you know what I get after that

**Comment by rgallast** [comment]
That was the issue. Thanks for looking into it!

**Comment by serge-rider** [comment]
Ok, good.
BTW I found another issue with recent MariaDB driver (empty trailing resultset). It is also fixed.
