### ISSUE TITLE
Dark theme request

### ISSUE THREAD

**Issue by JimiJones** [serge-rider/dbeaver#1585]
Hi,
Firstly thanks for all that work, I really appreciate your tool.
Just have some design request: In dark mode I would like to have the header of the active tab in white to be able to read it, and in the diagram view I would like to have the grid in an other color, currently it is in white and that breaks the eyes a little...
I attach a screenshot to show you that. Just been able to correct that in preference menu would be great.
![screenshot](https://cloud.githubusercontent.com/assets/27425088/25119270/c1c68058-2419-11e7-83a0-3a13a3131eb9.png)

**Comment by serge-rider** [comment]
Agreed. We need to add some default colors for ERDs in standard dark theme.

For now you can redefine ERD colors in Preferences->General->Appearance->Colors and Fonts.

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/25773641/892e7fba-3289-11e7-9b7e-fdd0ce1c5174.png)
