### ISSUE TITLE
Slow Fetch (Sqlite) - Question

### ISSUE THREAD

**Issue by sprintel** [serge-rider/dbeaver#1586]
I don't have an issue but rather a question related to sqlite. When I fetch all rows from a large table (500K rows), it takes dbeaver a while to complete the task (>15 sec) and sometimes it causes dbeaver to freeze. When i use another software called sqlitespy,  it takes only 1 sec to complete the task. Is this a "java" limitation?

**Comment by kyleflan** [comment]
Are you trying to load ALL 500K rows at once into the results pane? Using the latest version of DBeaver and the default SQLite driver (SQLite JDBC driver by Taro L. Saito (extension of Zentus driver), the results pane populates for me in <1s for a database table with ~2M rows. This is with the result-set size set to the default of 200.

If I up the result-set size to 100,000, it takes about 8s to load the data, so I could imagine loading 500K rows would take a while.

**Comment by sprintel** [comment]
Yeah, I'm trying to load all 500K rows. Sqlitespy can do it in about 1 sec. That's why I'm wondering why it takes a while for Dbeaver to load all rows.

**Comment by serge-rider** [comment]
I think most of time is spent in UI rendering.
It is not surprising that SQlite optimized software may work faster.

Anyhow usually you doesn't need to have 500k rows on one screen. So I don't think that this is a real problem.

**Comment by kyleflan** [comment]
I downloaded Sqlitespy to test it out and it took about 7s to return 500,000 rows, which is much faster than DBeaver. There are a few reasons I can imagine why Sqlitespy is more performant than DBeaver:

Sqlitespy is a specialized application tailored to SQLite. DBeaver is a front-end to a large number of databases (it touts itself as a Universal SQL Client). 

According to the website (https://www.yunqa.de/delphi/products/sqlitespy/index) it uses SQLite's native data types for internal data storage. DBeaver doesn't have this luxury as it is generalized for use across multiple database systems. 

Sqlitespy appears to be written in C/C++ and is only available for Windows OS. Again, this would definitely give it an advantage over DBeaver which is cross-platform. Java is typically going to be slower than C/C++, but is more portable. 

If you normally need to work with 500,000 rows at a time, it's probably worthwhile to do most of your work in Sqlitespy. However, the power and flexibility of DBeaver lies in its ability to provide you a consistent environment across multiple database platforms.

**Comment by sprintel** [comment]
Thank you all for the explanations! 
DBeaver is a great program. I've been using it for several months and I like it. Thank you for your great work, Serge-Rider and team!

**Comment by serge-rider** [comment]
Ok, thanks)
