### ISSUE TITLE
Date in dbeaver-debug.log is wrong

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#159]
I just deleted `~/.dbeaver/.metadata/dbeaver-debug.log` and then reopened DBeaver and the date shows as 2016-01-04 instead of 2016-01-10.

**Comment by serge-rider** [comment]
It was a bug in debug date/time pattern. Thanks for report!

**Comment by codebling** [comment]
Figured as much! Thanks for fixing!
