### ISSUE TITLE
[Feature Request] Formatting consistency across tables and result sets

### ISSUE THREAD

**Issue by shearerp** [serge-rider/dbeaver#1591]
Right now numbers are right-justified in tables, which is good, but they're left-justified in result sets. It would be nice if this and other behaviors were consistent across the two.

**Comment by serge-rider** [comment]
![default](https://user-images.githubusercontent.com/6398845/28250794-de6fb0e8-6a79-11e7-97e8-a0218faf95db.png)

I think that single option for both numbers and timestamps is ok.
