### ISSUE TITLE
New script via right-click context menu is broken inside a folder

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#16]
When you have one or more folders in your **Project - General** tab and try to create a new script inside a folder by right-clicking the desired folder and selecting the *Create SQL Script* option, DBeaver prompts you the DB connection dialog, however no new script is created after selecting the connection for the script.

Using the standard *New script* button in the top toolbar works normally.

**Comment by serge-rider** [comment]
Fixed.
Will be included in 3.5.2.
