### ISSUE TITLE
Cursor focus leaves editor (bug)

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#160]
Currently if you execute any number of queries using control-enter the cursor focus will stay in the query editor so you can continue to edit your queries.

If you continue to execute queries into separate result tabs (using control-\) the cursor focus will continue to stay in the query editor.

However, if you run a query using control-enter after using (control-\\) for multiple result tables the cursor focus will jump down to the results tab and you can no longer continue to type/edit your queries without returning the cursor focus to the editor (using the mouse).

steps to reproduce
1) execute select 1 (using control-enter)
2) execute select 2 (using control-\\)
3) execute select 3 (using control-enter)
4) attempt to modify the query to select 4 and notice that the cursor focus is now in results section

note: what does the command activate editor do? (i thought it might return the cursor focus to the query editor but that doesn't appear to be the case).

**Comment by r-richmond** [comment]
![illustration](https://cloud.githubusercontent.com/assets/9246654/12246990/99adb246-b866-11e5-8c9d-91418baf9192.gif)

**Comment by serge-rider** [comment]
Fixed,
thanks for report!
