### ISSUE TITLE
Unable to delete row because unsigned int

### ISSUE THREAD

**Issue by Dazix** [serge-rider/dbeaver#1600]
When column has unsigned int type and value is bigger than max int32 (2147483647) you cannot delete selected row. Row disappears  from view but after refresh is still here and status bar display 0 rows affected. My version of `DBeaver is 4.0.5 64bit` and 
```
Java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by serge-rider** [comment]
What database?
Please post sample DDL.

**Comment by Dazix** [comment]
Database is MySQL 5.6.32-78.0-log.
DDL and sample insert
```
CREATE TABLE `table1` (
  `col1` int(10) unsigned NOT NULL,
  `col2` tinyint(3) NOT NULL,
  UNIQUE KEY `col1` (`col1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;

INSERT INTO table1
(col1, col2)
VALUES(2593442246, 3);
```

**Comment by serge-rider** [comment]
Thanks for report
