### ISSUE TITLE
Informix: problem with locales

### ISSUE THREAD

**Issue by Srele-krele** [serge-rider/dbeaver#1601]
I have DBeaver version 4.0.5
Database is Informix 11.7 and I have correct login data and DB_LOCALE and CLIENT_LOCALE values that I did set in "Driver priperties" of Database connection. When I enter correct values "cs_cz.cp1250" (that work with other not-free db manager software) DBeaver gives me this error when I click on "Test Connection ..." button:
"java.sql.SQLException: Locale not supported."

But when I remove those variables I get this error: "Database locale information missmatch.".

Can someone help me with this please?

**Comment by amivanovano** [comment]
Try to enter cs_cz.1250
