### ISSUE TITLE
SQLite drop table show script doesn't do anything

### ISSUE THREAD

**Issue by Yanpas** [serge-rider/dbeaver#1602]
STR:
1. Connect to sqlite database
2. Open table list
3. Right click some table -> Delete -> View Script
Nothing happens

dbaver 4.0.4

**Comment by serge-rider** [comment]
Is this still reproducible in your environment?

**Comment by Yanpas** [comment]
No, it works. Thanks

Tested on windows, before tested on linux, but I'm sure it doesn't matter
