### ISSUE TITLE
Bad intepreting of data-base type BIT (logical)

### ISSUE THREAD

**Issue by vckbarth** [serge-rider/dbeaver#1604]
Hello,

I'm struggling with selecting columns from my data-base (FIS Profile DB) which has got logical values. Dedicated JDBC driver maps logical values to BIT type during SQL SELECT but DBeaver doesn't handle this too good.

Here Java sample code i run to test SQLs:
` public static void main(String args[]) {

    	String url, sql;
    	Connection connection;
        PreparedStatement pstmt;
        ResultSet rs;
        ResultSetMetaData metaData;
        
        try {
            Class.forName("sanchez.jdbc.driver.ScDriver").newInstance();
            url        = "usesp=no/fileEncoding=ISO-8859-2/protocol=jdbc:sanchez:/database=" +
                         "192.168.1.175" + ":" + 
                         "61315" + ":" +
                         "SCA$IBS";
            connection = DriverManager.getConnection(url, "1", "XXX");
            sql        = "select * from MYTBL";
            pstmt      = connection.prepareStatement(sql);
            rs         = pstmt.executeQuery();
            metaData   = rs.getMetaData();
            
            // column definition
            for (int i = 1; i <= metaData.getColumnCount(); i++) {
            	System.out.println("Column : " + metaData.getColumnName(i) + " Type : " + metaData.getColumnTypeName(i));
            }
            System.out.println("");
            
            // column meta-data print
            for (int i = 1; i <= metaData.getColumnCount(); i++) {
            	System.out.print(metaData.getColumnName(i) + "\t");
            }
            System.out.println("");
            
            // sql print
            while (rs.next()) {
            	for (int i = 1; i <= metaData.getColumnCount(); i++) {
            		System.out.print(rs.getString(i) + "\t");
            	}
            	System.out.println("");
            }
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
 }`

Java result:
Column : KEY1              Type : BIGINT
Column : CURRENCY   Type : DECIMAL
Column : DAT                Type : DATE
Column : DOUBLENUM Type : DOUBLE
Column : FREQ              Type : VARCHAR2
Column : LOGIC             **Type : BIT**
Column : TEXT               Type : VARCHAR2
Column : TIM                  Type : TIME
Column : UPSTRING      Type : VARCHAR2

KEY1	CURRENCY	DAT	DOUBLENUM	  FREQ	**LOGIC**	TEXT	TIM	UPSTRING	
1	66.99	2017-03-20	222.00000000	  1MAE	**true**	bleee	15:18:07	HIII	
2	66.99	2017-03-20	2234.00000000 1MAE	**true**	bleee	15:21:47	HIII	
3	66.99	2017-03-20	2.11100000	  1MAE	**true**	bleee	15:24:24	YY	

And Dbeaver behave:
![dbeaver_issue](https://cloud.githubusercontent.com/assets/19408985/25355693/c6975512-2937-11e7-9af0-c1265e7b9ee7.png)

Column definition:
![column_def](https://cloud.githubusercontent.com/assets/19408985/25355777/145942a6-2938-11e7-9f3b-d74faee7f1ea.png)

Can you tell me what is actually wrong? Is this a bug or bad settings on my own Dbeaver instance?

Thanks a lot,
Regards from Poland
Bartek

**Comment by serge-rider** [comment]
Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)
I can't reproduce that but I assume that BIT value is returned by driver as boolean (true/false).

**Comment by vckbarth** [comment]
There you go. Indeed BIT value is returned by driver as boolean (Java rs.getString() method easily transform it to true/false). If you'll got any troubles with reproduce this issue I could prepare for you test environment instance as a virtual image (I've done it last time: https://github.com/serge-rider/dbeaver/issues/494).

[log.txt](https://github.com/serge-rider/dbeaver/files/959622/log.txt)
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/959625/dbeaver-debug.txt)

**Comment by serge-rider** [comment]
And again this is a driver error (actual error happens in driver internals).
I've added yet another workaround for such cases - hopefully it'll work.

**Comment by vckbarth** [comment]
I've tested this on 4.0.6 (CE) and works like a charm :)

Thanks a lot.
