### ISSUE TITLE
"Error during SQL job execution: null"

### ISSUE THREAD

**Issue by cjacobs0n** [serge-rider/dbeaver#1605]
The title kind of says it all...I tried running an INSERT INTO statement and got the attached error. The query runs fine without the INSERT INTO statement, and there is no mention of any incorrect data type definitions. 

Any ideas? Could have anything to do with the size of the table? About 125 columns across.

![image](https://cloud.githubusercontent.com/assets/27981933/25363651/1ddbc1a4-2911-11e7-9c7e-2b86d1a69019.png)

**Comment by serge-rider** [comment]
What DBeaver version do you use?
Please post error stacktrace (you can get it in Error Log view or in logs: https://github.com/serge-rider/dbeaver/wiki/Log-files)
