### ISSUE TITLE
Be able to choose which tables to show in diagram

### ISSUE THREAD

**Issue by krilim** [serge-rider/dbeaver#1607]
Is it possible to choose which tables are drawn in ER diagram? Sometimes I want to see only the relations of a few tables and not all of them.

This would be a feature request.

Thanks :-)

**Comment by GiantCrocodile** [comment]
So far there is no way to restrict it like you want. At least that is what I know as a power user of DBeaver.

**Comment by krilim** [comment]
Yes... I suspected as much :'( thus the request ;-)

**Comment by serge-rider** [comment]
You can create custom ER diagram and put any number of tables there (even from different connections).
CTRL+N->ER diagram

**Comment by krilim** [comment]
That's what I wanted. Thanks a lot.

**Comment by GiantCrocodile** [comment]
I feel stupid but when I try this way I can select whatever I want (be it tables or other stuff) and Next or Finish buttons are still grayed out. I can't continue.

**Comment by serge-rider** [comment]
Just enter some diagram name

**Comment by GiantCrocodile** [comment]
Didn't see the input field. I must have been blind haha. Thanks @serge-rider!
