### ISSUE TITLE
tables filtering taking too long - sometimes timing out

### ISSUE THREAD

**Issue by rgallast** [serge-rider/dbeaver#1609]
We have several databases with a huge number of tables (> 100K) and my DB users wanted to use the table filtering capabilities to analyze a few of the tables in one of those databases. When I'm experimenting with the filtering of tables, even a simple one sometimes takes a long time (5 minutes, for example) and some other times it never comes back. I noticed by running "show full processlist" that the query being executed is "SHOW FULL TABLES FROM DB1" and I assume that DBeaver is doing the filtering once the data arrives from the server.

When I was playing with "SHOW FULL TABLES", I noticed that if I apply the filter in the command itself, say "SHOW FULL TABLES FROM DB1 WHERE Tables_in_DB1 LIKE '<pattern1>' OR Tables_in_DB1 LIKE '<pattern2>', I got the list of tables in < 2 seconds.

Can DBeaver change such that the server does the filtering? (that is, if my analysis is correct)

**Comment by serge-rider** [comment]
What is your database?

**Comment by rgallast** [comment]
MariaDB 10.1

**Comment by serge-rider** [comment]
DBeaver worked like that a time ago but then I had to change metadata loading algorithm.
Main problem: loading just subset of tables may break metadata structure (e.g. foreign keys). Maybe it is ok in some cases. But generally it is not ok.

So I'm still not sure about this feature..

**Comment by serge-rider** [comment]
Well, I've added extra config option which may disable this behavior:
![image](https://user-images.githubusercontent.com/6398845/29192271-7ee8f170-7e29-11e7-9b2b-79b63cf86c54.png)

By default it is enabled.
