### ISSUE TITLE
ClassNotFoundException on Postgre connect

### ISSUE THREAD

**Issue by fgblomqvist** [serge-rider/dbeaver#1611]
If I try to connect to my PostgreSQL db I get this error:
```
java/sql/SQLException
  java.lang.ClassNotFoundException: java.sql.SQLException
```
I'm running DBeaver 4.0.5 with Java 9-ea+162 using the `--add-modules=java.se.ee` fix.

**Comment by fgblomqvist** [comment]
I switched to Java 8 and removed the fix. Now it works. But maybe this bug report could still be of interest.

**Comment by serge-rider** [comment]
Interesting. Java 9 keeps me surprising again and again.
Thanks for information.

**Comment by nachaos** [comment]
I'm having exactly the same issue. Any workaround to make it work? Thanks in advance.

**Comment by serge-rider** [comment]
Standard workaround: use Java 8.

BTW could you post the complete stacktrace of this error (you can get it in Error Log view). I can't reproduce this in my environment.

**Comment by serge-rider** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=507417
This will be automatically resolved in DBeaver with next Eclipse Neon platform update.
