### ISSUE TITLE
Blue-screen of death on Windows right after procedure code visualization

### ISSUE THREAD

**Issue by fleo85** [serge-rider/dbeaver#1612]
After the last Windows cumulative update KB4016240 I receive a blue screen of death as soon as the code of a procedure/function/trigger is shown. The code is shown and then after a second a BSOD is triggered. I happens on both 4.0.3 and 4.0.5, Java 1.8 update 131 64 bit.

**Comment by serge-rider** [comment]
Wow.
What Windows version?
Are there any windows logs, dumps? 

DBeaver logs info: https://github.com/serge-rider/dbeaver/wiki/Log-files

**Comment by fleo85** [comment]
Windows 10 x64 Creators Update. The bug was not present before the cumulative update installed on the 26th of April. Nothing interesting in dbeaver log files. What Windows log could be interesting?

**Comment by serge-rider** [comment]
I have no clues so far.
Did you try to install DBeaver from installer (with included Java 1.8.0_77)?

**Comment by fleo85** [comment]
No I didn't. I am installing the same cumulative update on another laptop to understand whether the problem is on this machine only. I will keep you up-to-date.

**Comment by fleo85** [comment]
Haven't had the occasion yet to try on another computer. To integrate the information, 
the BSOD happens as soon as the mouse enter the section of the screen highlighted in red in the attached picture. If the mouse pointer remains after that part of the screen I have no problems.

![dbeavercrash](https://cloud.githubusercontent.com/assets/11192833/25557445/adcda68e-2d11-11e7-9b3e-63cabd6c9e6c.png)

**Comment by kkxcel** [comment]
It seems that "2017-07 Cumulative Update for Windows 10 Version 1703 for x64-based Systems (KB4025342)" has solved this problem.

**Comment by serge-rider** [comment]
Great. Thanks for information.
