### ISSUE TITLE
Issue with enum in MySql

### ISSUE THREAD

**Issue by stshryu** [serge-rider/dbeaver#1617]
I'm having a problem when Dbeaver isn't able to edit enum fields.

The error displayed when trying to edit the field is: 

`An internal error has occurred.
org.jkiss.dbeaver.ext.generic.model.GenericTableColumn cannot be cast to org.jkiss.dbeaver.ext.mysql.model.MySQLTableColumn`

Not sure how to fix the issue, any help would be greatly appreciated!

**Comment by stshryu** [comment]
Actually, it seems the issue is that for some reason, the database isn't recognizing ENUM. The database script for my program (on my other machine that uses sequel pro) has `item_1 enum('1', '2', '3', '4', '5') DEFAULT NULL`. But for some reason Dbeaver recongizes the script as `item_1 ENUM(3)`.

In addition to whatever the error was in the previous comment I left.

**Comment by serge-rider** [comment]
Looks like you are using wrong driver (MySQL 3.x). Enums are not supported there.
Switch to default MySQL driver.

**Comment by stshryu** [comment]
Wow you're right, thanks!

I'm loving Dbeaver right now by the way, one of the best DB managers for Linux out there :)
