### ISSUE TITLE
Queries taking much longer to run and display

### ISSUE THREAD

**Issue by vinit9** [serge-rider/dbeaver#1618]
I've noticed recently that when executing a query its taking a long time to display any results in the output. 

A normal select query with 460,000 rows on Exaplus is currently taking 0.4s with only displaying 20,000 where as the query on DBeaver is taking  1604 ms to display only 200 rows. 

Is there anything I might be missing?

**Comment by serge-rider** [comment]
Maybe it is a side effect of #1541
Try to increase maximum memory limit in deaver.ini

**Comment by vinit9** [comment]
How do I change the file .. I've found the route C:\Program Files\DBeaver but can't seem to find anything when opening it on notepad ++

**Comment by serge-rider** [comment]
It is `C:\Program Files\DBeaver\dbeaver.ini`
E.g. you can change `-Xmx1024m` parameter to something like `-Xmx4000m` (give DBeaver maximum 4 gb).

**Comment by Sargul** [comment]
Hi @vinit9,

this has to do with the way dbeaver executes queries.
Exaplus does just a plain execute SQL and a display of the columns.

DBeaver does a lookup for the entity (if sql is not created by SQL-Auto complete), a lookup of column names and types and a query for unique identifiers. 

This is necessary to provide the direct result set edit feature. However meta data queries are very slow in exasol. I've made various optimizations to speed up meta data query especially for exasol installations with a lot of objects however compared to other databases meta data queries are terribly slow in exasol.

If you want to get details about the execution time enable logging of meta data query
![grafik](https://cloud.githubusercontent.com/assets/5595511/25528870/fb5a125e-2c1f-11e7-92e7-83cdb9134b7e.png)
Enable Metadata read.

When you execute your query you should see the times for additional meta data query and the execution time in the query manager.

For example in our installation with > 50k Tables it takes > 3 s to query columns and constraints:
![grafik](https://cloud.githubusercontent.com/assets/5595511/25528969/76e44480-2c20-11e7-93e7-8077cbc40685.png)
In the example query execution time is only 30ms.
