### ISSUE TITLE
Update Snappydata adapter

### ISSUE THREAD

**Issue by fire** [serge-rider/dbeaver#1619]
Was gemfirexd, but now with their thrift based protocol it's diverging from both derby and gemfirexd.
![screenshot from 2017-05-01 10-22-14](https://cloud.githubusercontent.com/assets/32321/25587285/37024d46-2e58-11e7-9023-3a82f4153309.png)

**Comment by fire** [comment]
Actually the default port is 1528.

**Comment by fire** [comment]
I would probably use the description from:
https://snappydatainc.github.io/snappydata/
`SnappyData fuses Apache Spark with an in-memory database to deliver a data engine capable of processing streams, transactions and interactive analytics in a single cluster.`

**Comment by fire** [comment]
Weird using https://github.com/SnappyDataInc/snappydata/releases/download/v0.8/snappydata-client-1.5.4.jar works but not the one from maven..

**Comment by serge-rider** [comment]
I've added Maven repo in config. In my local env it works just like prepackaged jar.
And I don't want to add reference on a certain driver version.

Anyhow if Maven artifact won't work in some environments I can change it on direct link.
