### ISSUE TITLE
Export database and Import database corrupt encoding

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#162]
**Platform:** mariadb, mysql
**Database default charsert:** utf8
**Database default collation:** utf8_czech_ci
**Table charset:** utf8
**Table collation:** utf8_czech_ci

Export database and after that import generated .sql file, but some data are corrupted. It looks that problem is only with letter **ň**.

Name before export | Name after import | Status
------ | ----- | -----
Klatovy | Klatovy | OK
Pěnčín - Alšovice | Pěnčín - Alšovice | OK
Sudoměřice u Bechyně - Bechyňská Smoleč | Sudoměřice u Bechyně - Bechy | 
Batňovice | Bat | 
Plzeň - Božkov | Plze |

**Comment by JanecekPetr** [comment]
How come Bechy_ň_ská smoleč is fine?

**Comment by serge-rider** [comment]
How do you perform export - using data export wizard or using Tools->Export database (mysqldump actually)?

**Comment by MatyCZ** [comment]
Bechyňská Smoleč is corrupted too, my mistake.

**Comment by MatyCZ** [comment]
Right click in context menu on Database > Tools > Export database.

**Comment by serge-rider** [comment]
Seems to be a problem somewhere in mysqldump.
Could you check the dump file (it is in UTF encoding) - is it already corrupted or problem appears after import?

**Comment by MatyCZ** [comment]
Dump file is in UTF-8 format. I prepare test SQL file, data in file is OK, but after import I see in every table some values with ??.

Test dump file: [test.zip](https://github.com/serge-rider/dbeaver/files/102935/test.zip)

table | column | correct value | value
--- | --- | --- | ---
cis_kraje | nazev | Plzeňský kraj | Plze??ský kraj
cis_okresy | nazev | Plzeň-jih | Plze??-jih
cis_staty | nazev | Řecko | ??ecko

**Comment by serge-rider** [comment]
Still can't reproduce.
As far as I see both dump files are in UTF-8. It is the default encoding for mysqldump (in fact I'm not sure that it is possible to export in any other encoding).
When I import them on my local machine (server encoding utf8, server collation utf8_general_ci) everything looks correct: 
![chezh-enc](https://cloud.githubusercontent.com/assets/6398845/12551258/2a902e74-c37a-11e5-9b8f-1b73ee4a00e2.png)
I also tried to set database collation to utf8_czech_ci - it also works correctly.
So I assumethat there are some problems in your server/system configuration.

**Comment by MatyCZ** [comment]
I tried to import same file test-BAD.sql through Navicat and HeidiSQL. Data was after import OK.

Navicat has option to set encoding of file before import and when I choose UTF-8 everything is OK.  HeidiSQL has no encoding option, but everything is OK too.

Problem must be in DBeaver execute command, which is send to mysql.exe. Set DBeaver encoding command?

**Comment by MatyCZ** [comment]
Can you try add **--default-character-set=utf8** to this file: https://github.com/serge-rider/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/tools/MySQLToolScript.java?

**Comment by MatyCZ** [comment]
Add --default-character-set=utf8 to source code dont resolve this issue.

**Comment by serge-rider** [comment]
I think I have a clue. UTF characters can be broken during script file pump in DBeaver tools wizard. I've added explicit UTF-8 encoding there.

If you can run DBeaver from devel branch then you can test it by yourself.
If not then I can make EA version, let me know if you need it.

**Comment by MatyCZ** [comment]
Thanks a lot, it works right now.

I build core plugin from current devel branch and encoding is after import OK.

**Comment by serge-rider** [comment]
Great!
