### ISSUE TITLE
ClassCastException when Generate SQL > Insert on binary column

### ISSUE THREAD

**Issue by trivago-izelenov** [serge-rider/dbeaver#1620]
I see an Cast Exception error when trying to generate the insert string:

```
CREATE TABLE `example` (
  `example_col` bit(8) NOT NULL DEFAULT b'0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

```
insert into example VALUES(b'00000111')
```

1. right click on table
2. Generate SQL
3. Insert

error: 

*java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number*

![image](https://cloud.githubusercontent.com/assets/12135320/25615852/cc914682-2f39-11e7-83c8-60a20ae781dd.png)

**Comment by serge-rider** [comment]
Thanks for report
