### ISSUE TITLE
v4.0.6: Database disconnect action doesn't release Derby embedded database

### ISSUE THREAD

**Issue by marcosx86** [serge-rider/dbeaver#1621]
Step 1: Create a Derby Embedded connection
Step 2: Notice that there is no tmp or db.lock on the Derby DB folder
Step 3: Connect to Derby Embedded connection
Step 4: Notice the driver created db.lock and tmp into DB folder
Step 5: Disconnect from the connection
Step 6: Notice both items still on the folder. No application can connect until DBeaver is closed.

You have a Bug.

**Comment by serge-rider** [comment]
Are you connecting to the same physical database in embedded mode twice?

**Comment by marcosx86** [comment]
Just once, inside DBeaver. I disconnect from DBeaver and try to run a Java script inside Eclipse. It throws, yellling about unclosed connection.

**Comment by serge-rider** [comment]
Do you use preconfigured Derby driver or your own custom driver?
Preconfigured  driver has special settings for connection close + locks release.

**Comment by marcosx86** [comment]
I used the default one that DBeaver downloaded when I created the connection. There is any option to force full unload of the driver?

**Comment by serge-rider** [comment]
Well, then I assume that something went wrong. By default DBeaver shutdowns database on disconnect. And there is no option to unload driver (but you can use different driver version in driver editor dialog->Download/Update).

Could you post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)? Restart DBeaver, perform connect/disconnect, exit DBeaver and get debug log.

**Comment by marcosx86** [comment]
There is no .log, just dbeaver-debug.log. Its contents: 

> 2017-05-02 17:11:25.205 - DBeaver 4.0.6 is starting
> 2017-05-02 17:11:25.205 - Install path: 'file:/C:/Program Files/DBeaver/'
> 2017-05-02 17:11:25.205 - Instance path: 'file:/C:/Users/marcos.cunha/.dbeaver4/'
> 2017-05-02 17:11:25.205 - Memory available 61Mb/910Mb
> 2017-05-02 17:11:25.220 - Starting RMI server at 31587
> 2017-05-02 17:11:25.283 - Create display
> 2017-05-02 17:11:25.314 - Run workbench
> 2017-05-02 17:11:26.642 - Initializing DBeaver 4.0.6
> 2017-05-02 17:11:26.642 - Host plugin: org.jkiss.dbeaver.core.application 4.0.6
> 2017-05-02 17:11:26.642 - Initialize Core...
> 2017-05-02 17:11:26.813 - Core initialized (171ms)
> 2017-05-02 17:11:26.813 - Configure workbench window
> 2017-05-02 17:11:26.860 - Create actions
> 2017-05-02 17:11:26.860 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
> 2017-05-02 17:11:26.860 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
> 2017-05-02 17:11:27.188 - Initialize workbench window
> 2017-05-02 17:11:27.203 - Finish initialization
> 2017-05-02 17:11:32.229 - Connect with 'Derby - db_sigep/sh-elisangela' (derby-15ba0587948-4b9f9af10658a23d)
> 2017-05-02 17:11:36.960 - Connected (derby-15ba0587948-4b9f9af10658a23d, Apache Derby Embedded JDBC Driver [10.13.1.1 - (1765088)])
> 2017-05-02 17:11:41.423 - Shutdown finished: :Connection authentication failure occurred.  Reason: Invalid authentication..
> 2017-05-02 17:11:41.423 - Disconnected (derby-15ba0587948-4b9f9af10658a23d)
> 2017-05-02 17:11:47.233 - Connect with 'Derby - db_sigep/sh-elisangela' (derby-15ba0587948-4b9f9af10658a23d)
> 2017-05-02 17:11:47.249 - Connected (derby-15ba0587948-4b9f9af10658a23d, Apache Derby Embedded JDBC Driver [10.13.1.1 - (1765088)])
> 2017-05-02 17:11:49.373 - Shutdown finished: :Connection authentication failure occurred.  Reason: Invalid authentication..
> 2017-05-02 17:11:49.373 - Disconnected (derby-15ba0587948-4b9f9af10658a23d)
> 2017-05-02 17:11:59.762 - Shutdown Core...
> 2017-05-02 17:11:59.965 - Shutdown completed in 203ms

**Comment by serge-rider** [comment]
Thanks/
This seems to be reason:
```
Shutdown finished: :Connection authentication failure occurred. Reason: Invalid authentication..
```
DBeaver doesn't use authentication info for shutdown.
