### ISSUE TITLE
Version 4.x not run on linux 64bits

### ISSUE THREAD

**Issue by candido1212** [serge-rider/dbeaver#1622]
> uname -a
Linux  3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I tried running it with java 1.7 and 1.8

See log file
[1493740296796.log.txt](https://github.com/serge-rider/dbeaver/files/971012/1493740296796.log.txt)

**Comment by ceyhunnabiyev** [comment]
Please look at dbeaver readme. It requires java 8, but you have java 7.  Install java 8 and then check your  java   with following command:

`java -version`

**Comment by candido1212** [comment]
I had tried to run it differently, with java 1.8, now correctly installed version 1.8, it worked. Thank you
