### ISSUE TITLE
Error w/ certain queries in Apache Hive

### ISSUE THREAD

**Issue by osrojas** [serge-rider/dbeaver#1625]
Hi,

I have an Apache Hive connection that throws an error only when I run certain queries. For example, if I run a common SELECT FROM WHERE query, it runs just fine. When I add ORDER BY, I get the following error message:

**Query execution failed

Reason: SQL Error [1] [08S01]: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask**

Any idea why this would be happening? Thanks!

**Comment by r-richmond** [comment]
try putting your query in a sub query and then using an order by outside of that.

Also this isn't a dbeaver question its a hive question so you'd find better support on another forum.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
