### ISSUE TITLE
Define a common SQL to be included in other queries?

### ISSUE THREAD

**Issue by llnk** [serge-rider/dbeaver#1627]
I usually find myself in this situation:

I have a complex SQL that returns some output:

```
-- base query:
select * from table where conditions
```

Now i would like to use this base query in other queries, like this:

```
select field1, field2 from ( %basequery% ) as t1

select field3, field5 from ( %basequery% ) as t1
```

Does dbeaver offer this kind of functionalities? Can it be implemented? It can be implemented as a simple automatic search and replace

**Comment by jk3us** [comment]
The "templates" functionality might be what you are looking for.  You can define snippets that you can quickly autoinsert into the sql editor.

Otherwise, you may just want to create a view (or temporary view) in your database and make queries against that.

**Comment by serge-rider** [comment]
Yep. https://github.com/serge-rider/dbeaver/wiki/SQL-Editor-templates
