### ISSUE TITLE
Password always saves locally

### ISSUE THREAD

**Issue by jheerTBG** [serge-rider/dbeaver#1629]
Steps to reproduce: 
1. Create a connection without a password.
2. Connect using connection; provide password; ensure that "Save password" is unchecked.
3. Disconnect
4. Open the "Edit Connection" dialog; under the general section, check the "Save Password Locally" checkbox.
5. Select "Test Connection"

Results:
The test connection action will connect without any prompt, because the password you previously entered into the prompt was saved, even though "Save password" was unchecked.

Priority:
Organizations that do not wish to save production database passwords locally cannot use DBeaver.

**Comment by jheerTBG** [comment]
This is related to #518.

**Comment by serge-rider** [comment]
Thanks for report
