### ISSUE TITLE
Oracle Triggers not listed

### ISSUE THREAD

**Issue by Roill** [serge-rider/dbeaver#1630]
First of all, thank you for the tool. I've been looking for something that can handle an Oracle DB without being as heavy as SQL Developer, and DBeaver is a great replacement.

Overall, the tool is able to do everything I need, but it seems like the triggers are not loading properly within the navigator. When I drill into an actual table and click on the triggers tab, the triggers load fine, but it doesn't seem to be grabbing all of the triggers in the schema. I have tried multiple schemas and multiple oracle databases.

Version 4.0.6. Happening on Linux and within my Windows VM. Examples below.

Triggers appear within my PROJECT table

![image](https://cloud.githubusercontent.com/assets/28357495/25672040/1f521a4c-3000-11e7-8085-8f8c5e605107.png)

Triggers not appearing in the navigator

![image](https://cloud.githubusercontent.com/assets/28357495/25672097/477dc610-3000-11e7-9d06-cdcbb07def85.png)

Triggers not appearing when I drill into the schema

![image](https://cloud.githubusercontent.com/assets/28357495/25672101/4e1841bc-3000-11e7-8bdd-5b6939a7ea76.png)

Any assistance is appreciated. Thanks!

**Comment by serge-rider** [comment]
I can't reproduce that. Probably this depends in particular sequence of actions.
Could you write steps to reproduce?

**Comment by Roill** [comment]
I just removed the connection and re-added it, and I got the same results. Steps below.

1. Create new Oracle connection.
2. Downloaded and added the ojdbc6.jar when prompted
3. Added connection information (Using a SYSDBA user).
4. Tested the connection, and it was successful.
5. Skipped the page about SSH and SOCKS.
6. Renamed the display name of the connection to DEV, checked save password locally, unchecked auto-commit, checked show utility objects, and set the default schema to SYS.
7. Saved connection, connected to it, and triggers are missing.

**Comment by serge-rider** [comment]
Ah, I've just realized that you are expecting table triggers in schema trigger list.
It doesn't work this way. 

Schema triggers are special triggers which are declared for a whole database. While table triggers are declared for a particular table.

**Comment by Roill** [comment]
Ah ok. Good to know. I was used to SQL Developer's method of compiling all of the table triggers in the schema, so I assumed this was the same. Closing
