### ISSUE TITLE
Set cursor on error position

### ISSUE THREAD

**Issue by greenpeas** [serge-rider/dbeaver#1631]
При получении ошибки исполнения SQL, если известна её позиция, было бы неплохо перемещать курсор в позицию ошибки. Автоматически или по клику на позицию:
![image](https://cloud.githubusercontent.com/assets/3856344/25691385/f515cb18-30a2-11e7-8753-1b3ef2775e4e.png)

**Comment by serge-rider** [comment]
This is already implemented. The problem is in localized error message (in Russian).
I'll add a fix in PG extension so it will parse error messages in any language.
