### ISSUE TITLE
Right-aligned toolbars not sticking

### ISSUE THREAD

**Issue by Roill** [serge-rider/dbeaver#1632]
I am having a minor issue where the application is not remembering where I am setting the toolbars once I close the application and come back in. It seems to only happen when moving toolbars to the right side of the header bar.

After I modified the default toolbars to my liking, this is what my setup looked like. This is on my Linux host machine.

![screenshot from 2017-05-04 08 40 41](https://cloud.githubusercontent.com/assets/28357495/25704062/0aa20b9c-30a6-11e7-9973-98a1bf163e77.png)

Then I moved some bars around to set it how I would like it to look.

![screenshot from 2017-05-04 08 42 15](https://cloud.githubusercontent.com/assets/28357495/25704080/18668e60-30a6-11e7-8421-d6f9dc57d246.png)

I exit the program through File -> Exit, and when I come back, the bars I moved to the right side seem to have reverted.

![screenshot from 2017-05-04 08 43 18](https://cloud.githubusercontent.com/assets/28357495/25704105/30ece6be-30a6-11e7-8e73-1d6c9ca69115.png)

Within my Windows 7 VM, I'm having the above issue as well, but I'm alsoi not able to move the execution toolbar. When I try to do the move below, it reverts it back when I restart DBeaver.

![selection_004](https://cloud.githubusercontent.com/assets/28357495/25704634/40a5490a-30a8-11e7-8431-5cf1094b2488.png)

**Comment by serge-rider** [comment]
Unfortunately I can't fix this. 
Toolbars behavior controlled by Eclipse framework. Optional toolbars position is lost on restart if toolbar has some initial positioning configuration.

I'll check Eclipse tollbar contributions config one more time, maybe there is some workaround..

**Comment by tati-kru** [comment]
It looks like this problem can't be fixed. It will be closed.
