### ISSUE TITLE
incompatible character set from dbeaver to System i (AS400)

### ISSUE THREAD

**Issue by w-ti** [serge-rider/dbeaver#1633]
Hi @ll,

we use dbeaver with Connection to System i and it works very fine :)

Problem are the German Umlaute äöü... in this Connection.

When I write "Übergabe-Parameter:" in "Rational Developer for i" - I get "�bergabe-Parameter:" in dbeaver.
When I write "Übergabe-Parameter:" in dbeaver - I get "Ãœbergabe-Parameter:" in "Rational Developer for i".

ä - ö - ü - Ä - Ö - Ü - ß in dbeaver is Ã¤ - Ã¶ - Ã¼ - Ã„ - Ã– - Ãœ - ÃŸ in RDi
ä - ö - ü - Ä - Ö - Ü - ß in RDi is � - � - � - � - � - � - � in dbeaver

Which Setting is for synchronize the character sets???

thanks

**Comment by serge-rider** [comment]
This is driver-specific configuration. Refer to your driver (JTOpen?) documentation. Probably it is controlled by character truncation/translation/ccsid parameters.

**Comment by w-ti** [comment]
thanks - but which Driver configuration?
For dbeaver I have Java8\jt400.jar - therefore I didn't found any Driver Settings
For RDi I have an included Driver in \plugins\com.ibm.datatools.db2.iseries_3.2.1000.v20150728_2354\Driver\jt400.jar (AS/400 Toolbox for Java Standard)

I got same error when I use dbeaver-jt400 in RDi or RDi Driver in dbeaver

I didn't found any documentation for this Drivers and I also found no Settings for drivers
:(

**Comment by serge-rider** [comment]
You can use default iSeries driver config (shipped with DBeaver). It is JTOpen 9.2. There is a bunch of supported connection properties.
Properties description: https://www.ibm.com/support/knowledgecenter/SSAE4W_9.1.0/com.ibm.etools.iseries.toolbox.doc/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html

**Comment by serge-rider** [comment]
You can choose default driver (DB2 iSeries/AS 400) on the first wizard page: https://github.com/serge-rider/dbeaver/wiki/Connect-to-database
Actual driver jar(s) will be downloaded from Maven repo.

If you have problem with SQL script file encoding then you can change it (alt+enter in SQL editor->Resource page). Also you can change default files encoding in Preferences->Database.

I can't say what particular connection properties you need to change.

**Comment by w-ti** [comment]
thanks for your Support - just right now I found the solution myself :) and I like to offer it for everyone who have same Problems

as I established before - reason for non Display German Umlaute is the character set for saving SQL scripts

I imported my Projects from RDi to dbeaver and Default character set in dbeaver is UTF-8
For every Project it is necessary to Change the character set like:
-->Properties -->Resource -->Text file Encoding
from "Inherited from Container (UTF-8)" to "Other ISO-8859-1"

With this Setting all German Umlaute are displayed in RDi for files that are saved in dbeaver
