### ISSUE TITLE
Unclosed quote causes "Internal jdbc Error" (instead of returning error from DB)

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#1634]
`SELECT 'a;`

Trying to run that query returns

```
SQL Error: Internal jdbc driver error
  Internal jdbc driver error
    java.lang.ArrayIndexOutOfBoundsException: 
```

Running this from the command line returns a more useful error from postgresql:

```
$ echo "select 'a;" | psql service=cdev
ERROR:  42601: unterminated quoted string at or near "'a;"
LINE 1: select 'a;
               ^
LOCATION:  scanner_yyerror, scan.l:1382
Time: 1.001 ms
```

This also happens for quotes in much bigger queries, which makes it hard to figure out what's going on.

**Comment by serge-rider** [comment]
This is internal error of PostgreSQL JDBC driver, I can't fix this.
