### ISSUE TITLE
Unnable to run PL/SQL with bind variables

### ISSUE THREAD

**Issue by jackelynoliveira** [serge-rider/dbeaver#1635]
I have recently updated DBeaver to the 4.0.6 version, however I've had a persistent problem in executing a PL/SQL script with bind variables. But, **this problem does not happen when I run the same script in SQL Developer**, what makes me think the problem is in DBeaver.

I try to execute a script like the following example:

```sql
DECLARE V_IDSOMETHING NUMBER(18);

BEGIN

INSERT INTO [TABLE] ( [COLUMNS] ) VALUES( :NMSOMETHING, :NRSOMETHING )
RETURNING IDSOMETHING INTO V_IDSOMETHING;

COMMIT;
END;
```

However, I'm not prompted to fill any bind variable's value, instead this window is shown:
![screenshot](https://cloud.githubusercontent.com/assets/10089671/25710409/993bb332-30c2-11e7-9752-e6b27be78555.png)

I tried running with both `Execute SQL Statement` and `Execute Script` options.

Apologies if this is something I might be doing wrong. I really appreciate DBeaver's efficiency and clean interface, and would like this possible bug to be known so it can be either fixed or ruled out.

**Comment by serge-rider** [comment]
Yes, parameters binding doesn't work inside PL/SQL blocks. This was made on purpose to avoid parameters in DDL statements.

I've made a better fix so parameters will work in anonymous blocks.

**Comment by sschneider-ihre-pvs** [comment]
@serge-rider what is the workaround to bind parameters in a declare block?
