### ISSUE TITLE
Oxygen ComboBox assertion kills DBeaver after initial launch

### ISSUE THREAD

**Issue by microwheels** [serge-rider/dbeaver#1636]
I'm trying to run DBeaver Enterprise 4.0.5 on Kubuntu 14.04 LTS with Oracle Java 1.8.0_131 for 64 bit.

Once the application loads, the new connection dialog displays and then the entire application exits.

Here's the output from the console:

> 2017-05-06 16:49:10.978 - > Start org.eclipse.core.resources [3.11.1.v20161107-2032]
> 2017-05-06 16:49:10.982 - > Start org.eclipse.ui.editors [3.10.1.v20161106-1856]
> 2017-05-06 16:49:11.040 - > Start org.eclipse.ui.workbench.texteditor [3.10.1.v20160818-1626]
> 2017-05-06 16:49:11.063 - > Start org.jkiss.dbeaver.core [4.0.5]
> 2017-05-06 16:49:11.065 - DBeaver Enterprise 4.0.5 is starting
> 2017-05-06 16:49:11.065 - Install path: '/usr/local/share/dbeaver'
> 2017-05-06 16:49:11.066 - Instance path: 'file:/home/sleepy/.dbeaver4/'
> 2017-05-06 16:49:11.066 - Memory available 155Mb/1820Mb
> 2017-05-06 16:49:11.074 - Starting RMI server at 40621
> 2017-05-06 16:49:11.166 - Create display
> 2017-05-06 16:49:11.196 - Run workbench
> 2017-05-06 16:49:11.203 - > Start org.eclipse.e4.ui.workbench.swt [0.14.1.v20160829-0832]
> 2017-05-06 16:49:11.204 - > Start org.eclipse.e4.core.services [2.0.100.v20160509-1032]
> 2017-05-06 16:49:11.205 - > Start org.eclipse.e4.core.contexts [1.5.1.v20170203-1100]
> 2017-05-06 16:49:11.216 - > Start org.eclipse.e4.ui.services [1.2.100.v20160506-0759]
> 2017-05-06 16:49:11.240 - > Start org.eclipse.team.core [3.8.0.v20160418-1534]
> 2017-05-06 16:49:11.263 - > Start org.eclipse.e4.ui.di [1.1.100.v20160506-0759]
> 2017-05-06 16:49:11.304 - > Start org.eclipse.emf.common [2.12.0.v20160420-0247]
> 2017-05-06 16:49:11.317 - > Start org.eclipse.emf.ecore [2.12.0.v20160420-0247]
> 2017-05-06 16:49:11.377 - > Start org.eclipse.emf.ecore.xmi [2.12.0.v20160420-0247]
> 2017-05-06 16:49:11.505 - > Start org.eclipse.core.filesystem [1.6.1.v20161113-2349]
> 2017-05-06 16:49:11.585 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.2.101.v20170206-1129]
> 2017-05-06 16:49:11.599 - > Start org.eclipse.core.expressions [3.5.100.v20160418-1621]
> 2017-05-06 16:49:11.612 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.1.v20170117-1415]
> 2017-05-06 16:49:11.768 - > Start org.eclipse.e4.ui.bindings [0.11.100.v20160509-1025]
> 2017-05-06 16:49:11.836 - > Start org.eclipse.ui.ide [3.12.3.v20170119-0935]
> 2017-05-06 16:49:11.841 - > Start org.eclipse.ui.ide.application [1.1.101.v20160829-0827]
> 2017-05-06 16:49:12.168 - > Start org.eclipse.help [3.7.0.v20160602-1307]
> 2017-05-06 16:49:12.189 - > Start org.eclipse.core.filebuffers [3.6.0.v20160503-1849]
> 2017-05-06 16:49:12.250 - > Start org.eclipse.e4.ui.css.swt [0.12.100.v20160517-1505]
> 2017-05-06 16:49:12.298 - > Start org.eclipse.e4.ui.css.swt.theme [0.10.100.v20160523-0836]
> 2017-05-06 16:49:12.580 - > Start org.eclipse.equinox.security [1.2.200.v20150715-1528]
> 2017-05-06 16:49:12.597 - > Start org.eclipse.core.net [1.3.0.v20160418-1534]
> 2017-05-06 16:49:12.606 - > Start org.eclipse.equinox.p2.core [2.4.100.v20160419-0834]
> 2017-05-06 16:49:12.608 - > Start org.eclipse.equinox.p2.repository [2.3.200.v20160421-0324]
> 2017-05-06 16:49:12.610 - > Start org.eclipse.equinox.p2.transport.ecf [1.1.201.v20161115-1927]
> 2017-05-06 16:49:12.614 - > Start org.eclipse.ecf.filetransfer [5.0.0.v20160823-2221]
> 2017-05-06 16:49:12.631 - > Start org.eclipse.userstorage.ui [1.0.1.v20170201-1648]
> 2017-05-06 16:49:12.631 - Initializing DBeaver Enterprise 4.0.5
> 2017-05-06 16:49:12.632 - Host plugin: com.dbeaver.ent.application 4.0.5
> 2017-05-06 16:49:12.632 - Initialize Core...
> 2017-05-06 16:49:12.636 - > Start org.eclipse.userstorage [1.0.1.v20170201-1648]
> 2017-05-06 16:49:12.779 - > Start com.dbeaver.ent.qmdb [1.0.45]
> 2017-05-06 16:49:12.781 - Opening QMDB connection...
> 2017-05-06 16:49:12.870 - > Start org.eclipse.epp.mpc.core [1.5.4.v20170222-1921]
> 2017-05-06 16:49:12.874 - > Start org.eclipse.epp.mpc.ui [1.5.4.v20170222-1941]
> 2017-05-06 16:49:12.880 - > Start org.eclipse.equinox.p2.operations [2.4.200.v20160504-1450]
> 2017-05-06 16:49:12.884 - > Start org.eclipse.equinox.p2.engine [2.4.100.v20160419-0834]
> 2017-05-06 16:49:12.890 - > Start org.eclipse.equinox.p2.metadata [2.3.100.v20160427-2220]
> 2017-05-06 16:49:12.892 - > Start org.eclipse.equinox.p2.metadata.repository [1.2.300.v20160419-0834]
> 2017-05-06 16:49:12.901 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.3.0.v20161124-1529]
> 2017-05-06 16:49:12.902 - > Start org.eclipse.equinox.p2.updatechecker [1.1.300.v20161124-1529]
> 2017-05-06 16:49:12.970 - Check QMDB deployment
> 2017-05-06 16:49:12.987 - QMDB started
> 2017-05-06 16:49:12.989 - Core initialized (357ms)
> 2017-05-06 16:49:12.989 - Configure workbench window
> 2017-05-06 16:49:13.080 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
> 2017-05-06 16:49:13.081 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.navigation'
> 2017-05-06 16:49:13.081 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
> 2017-05-06 16:49:14.015 - Initialize workbench window
> 2017-05-06 16:49:14.026 - Finish initialization
> java: /build/buildd/gtk2-engines-oxygen-1.4.5/src/animations/oxygencomboboxdata.cpp:87: void Oxygen::ComboBoxData::setButton(GtkWidget*): Assertion `!_button._widget' failed.

Let me know if there is any additional information which would help in diagnosing the problem.

**Comment by serge-rider** [comment]
It is a known bug in Eclipse+Oxygen: https://bugs.eclipse.org/bugs/show_bug.cgi?id=440660

Workaround: https://bugs.eclipse.org/bugs/show_bug.cgi?id=440660#c20

**Comment by microwheels** [comment]
That fixes the problem.  Thank you.
