### ISSUE TITLE
[MSSQL] [Azure] Can only connect to master db

### ISSUE THREAD

**Issue by TheTerrasque** [serge-rider/dbeaver#1638]
When trying to change from "master" to a different DB in MSSQL Azure server, I get this error:

> SQL Error [40508] [S0001]: USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
>   com.microsoft.sqlserver.jdbc.SQLServerException: USE statement is not supported to switch between databases. Use a new connection to connect to a different database.

This is with the MS driver. The jTDS driver gave a similar error. What's worse, "Default schema" doesn't seem to have an effect on which one is selected when logging in.

**Comment by serge-rider** [comment]
Can you just change database name in connection properties?

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.

**Comment by Davilink** [comment]
I have the same problem, i tried to set the _DEV DB active, but i get that error.
Is a way to connect to different DB without needed to create a connection to each of them ?

![image](https://user-images.githubusercontent.com/1498932/33614704-208cc9b6-d9a6-11e7-85e9-15ca6a52383d.png)

**Comment by serge-rider** [comment]
I'm afraid it is not possible. Potentially we can do it similarly to PostgreSQL (DBeaver opens separate connections to each database). But it will require special extension for Azure (see #810, maybe as a part of this ticket).

**Comment by alan-1** [comment]
bump
