### ISSUE TITLE
how print stored procedure  result set?

### ISSUE THREAD

**Issue by bouyeijiang** [serge-rider/dbeaver#1640]

**Comment by serge-rider** [comment]
What database?

**Comment by bouyeijiang** [comment]
db2,

**Comment by bouyeijiang** [comment]
and sql server and so on

**Comment by serge-rider** [comment]
For DB2 (and most of other databases) use
`CALL PROC_NAME(...);`

BTW check  #137

**Comment by bouyeijiang** [comment]
procedure return datatable result sets,only return effect row count,no data sets,

**Comment by serge-rider** [comment]
Well, this depends on procedure and on DB2 server type.
E.g. try this:
`CALL SYSIBM.SQLTABLES(null,'SYSIBM',null,null,null);`
It returns resultset with list of tables

**Comment by bouyeijiang** [comment]
i understood,store procedure need to be add "dynamic result sets 1"  statement

**Comment by tati-kru** [comment]
It looks like this problem was solved. It will be closed.
