### ISSUE TITLE
execute procedure problem

### ISSUE THREAD

**Issue by fayca121** [serge-rider/dbeaver#1641]
Hello,

if I try to call a procedure with execute command I reveive the sql error ORA-00900 invalid SQL statement

**execute** procedure_name(pramaters);

db: oracle 11g

**Comment by serge-rider** [comment]
Use `CALL procedure_name(parameters)`

**Comment by fayca121** [comment]
yes, it works with call command but it would be helpful if you can add **execute** and **exec** commands to call procedures and functions.

thank you.

**Comment by serge-rider** [comment]
This is how Oracle driver works, it doesn't support "EXECUTE" or "EXEC" command. I can't fix this.

**Comment by fayca121** [comment]
ok, I got it, it seems JDBC restriction.
thanks again.
