### ISSUE TITLE
Make execute query on current database easier

### ISSUE THREAD

**Issue by JorgeSivil** [serge-rider/dbeaver#1644]
I can't believe this is so difficult.

I copied a chunk of MySQL text into clipboard, went to DBeaver, selected my database with double click, but no option to open a query editor.

There is the F3 option, Open SQL Editor. However, no button to run the query. It just allows me to save the query in a text file, but I do not want that!

I think it would be best to add a new tab, SQL Editor, next to Properties and Diagram.

**Comment by serge-rider** [comment]
You can select connection in navigator and press CTRL+Enter (this will open recent SQL editor).
Copy-paste query and press CTRL+Enter again (this will execute your query).

Don't see how I can make it easier.
BTW there 4 different ways to run queries and scripts (all of them are in main toolbar, main menu and context menu).

I don't like idea of having special tab in every editor.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
