### ISSUE TITLE
SQL Editor - add script pattern

### ISSUE THREAD

**Issue by Apcio** [serge-rider/dbeaver#1645]
Hi.
In my Database Navigator I had created folders:
Local -> Program 1
Production -> Program 1

In script patterns I would like to add these folders to save SQL Scripts in format:
Folder -> Program -> Script.sql

Is any chance to add folder name variable?

**Comment by serge-rider** [comment]
Do you mean put scripts for different connections in separate folders?
Or create scripts folders for connections which are in connection folders?

**Comment by Apcio** [comment]
The second option.
I would like to create the same path like in Database Navigator:
![image](https://cloud.githubusercontent.com/assets/11940927/25846472/3b0eb6bc-34b2-11e7-8fbb-934092b6ad9d.png)

**Comment by serge-rider** [comment]
Ok. This can be solved with one extra preference option. And that's easy to do.

**Comment by Apcio** [comment]
Thank you.

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/25855343/9eedeee0-34db-11e7-9b48-058db48950bd.png)
