### ISSUE TITLE
Remove/Alter password prompt for non passphrase protected private keys

### ISSUE THREAD

**Issue by kkartaltepe** [serge-rider/dbeaver#1647]
Currently dbeaver brings up the generic "User Credentials" prompt when you ssh in with any private key. I understand from #179 and after playing around with it that I dont have to enter a password here and could "Save password" but this was quite confusing at first.

Ideally dbeaver would only prompt me for a password after identifying the private key I was using was password protected.

Alternately the prompt for a key passphrase should NOT look identical to User Credentials prompt. There is no "Username" in a key passphrase, and the title "User credentials" is misleading me to think that I am entering my password for my user and not actually using private key authentication. It should only contain a password bock and be labeled "Key Passphrase".

**Comment by serge-rider** [comment]
Agreed. Current UI is confusing.
