### ISSUE TITLE
Oracle triggers not visible

### ISSUE THREAD

**Issue by dieners** [serge-rider/dbeaver#1648]
Running 4.0.6 on Linux Mint

Can create triggers but not view them afterwards or see the ones which already exist.

**Comment by serge-rider** [comment]
Can't reproduce.
Isn't this the same as in #1630?

**Comment by dieners** [comment]
That is the same issue I am seeing.  A coworker confirmed that he saw the
same issue. Could it be oracle version specific?

**Comment by serge-rider** [comment]
Well, then this is not a bug.
Probably I should change schema triggers node name to make it less confusing.
