### ISSUE TITLE
Failed to submit a MERGE sql to SQL SERVER

### ISSUE THREAD

**Issue by liujun1105** [serge-rider/dbeaver#1649]
When submitting a MERGE sql to the SQL server, dbeaver returns an error message complaining about the MERGE sql must end with a semicolon even through the semicolon is already there.

Tried to execute the exact query through Microsoft SQL Server Management Studio, it works fine.

**Comment by liuyuanyuan** [comment]
你好，

你是来自中国的DBaver开发者吗？

目前，我刚开始学习RCP的开发和DBaver的代码，请多指教。

如果方便的话请加我QQ：731297616.多谢~

 

媛媛

2017.5.10

 

发件人: Jun Liu [mailto:notifications@github.com] 
发送时间: 2017年5月10日 11:11
收件人: serge-rider/dbeaver
抄送: Subscribed
主题: [serge-rider/dbeaver] Failed to submit a MERGE sql to SQL SERVER (#1649)

 

When submitting a MERGE sql to the SQL server, dbeaver returns an error message complaining about the MERGE sql must end with a semicolon even through the semicolon is already there.

Tried to execute the exact query through Microsoft SQL Server Management Studio, it works fine.

**Comment by serge-rider** [comment]
Please post query sample.

**Comment by liujun1105** [comment]
MERGE INTO table1 AS T
USING (VALUES (166141, '20171229', '20171230', 'F')) as S (id, start_date, end_date, flag)
ON T.id = S.id and T.start_date = S.start_date and T.end_date = S.end_date
WHEN MATCHED 
	THEN UPDATE SET flag = S.flag
WHEN NOT MATCHED
	THEN 
		INSERT (is_latest, id, start_date, end_date, create_time, create_user, update_time, update_user, flag) 
		VALUES (1, 166143,	'20171229', '20171230', '20170510', 'liujunj', '20170510', 'liujunj', 'G');

When this query is submitted through dbeaver to SQL Server, I got the error message listed in the issue description.

**Comment by serge-rider** [comment]
Thanks. Not sure how to fix this yet. 
By default DBeaver cuts trailing semicolon because it shouldn't be there for queries/databases.
Maybe I'll add a special handler for SQL Server and MERGE commands.

Workaround: add double semicolon in the end, select query and execute with ctrl+enter.

**Comment by serge-rider** [comment]
Added extra option which leaves delimiters after queries.

**Comment by lukaseder** [comment]
I wonder if this is fixed correctly, or if there's a regression. I can execute the `MERGE` statement when I select it entirely, like this:

![image](https://user-images.githubusercontent.com/734593/79014174-a26ca380-7b6a-11ea-9883-3f4b413bc667.png)

But when I just place the caret inside of a statement and hit Ctrl+Enter, then the semi colon is not sent to the server

![image](https://user-images.githubusercontent.com/734593/79014215-b6180a00-7b6a-11ea-9304-720953d1ce33.png)

The suggested workaround where I add a double semicolon at the end also doesn't work:

![image](https://user-images.githubusercontent.com/734593/79014289-dea00400-7b6a-11ea-9685-a1c1585327e7.png)

**Comment by lukaseder** [comment]
... Using DBeaver 7.0.0.202003021717 on Windows 10 [Version 10.0.18362.720]

**Comment by kaiten27** [comment]
I think in release 23.2.5.202311191730 this problem is "back"...

Create a table : 

`create table mytest(thekey nvarchar(12),thedescr nvarchar(12)) 
`

and try to merge  : 

```
with s as (
select 'x'     thekey,'descr' thedescr  
          )
merge mytest
   as target
using s as source
   on (target.thekey = source.thekey)
 when matched and target.thedescr <> source.thedescr 
 then update  set target.thedescr =  source.thedescr 
when not matched by target
then
insert (
       thekey
      ,thedescr
) values ( 
        source.thekey                    
      , source.thedescr               
);;
```

Results in : 

```
SQL Error [10713] [S0001]: A MERGE statement must be terminated by a semi-colon (;).

Error position: line: 31

```

Note : The double semicolon at the end was the workaround that did the trick til last release . Now 2 , 1 or no semicolon all end up in the error (  even 3 semicolon :-) )

**Comment by tsileo-wdi** [comment]
I'm also getting this error - only when trying to execute sql that creates a stored procedure with a merge statement as a script.  The same exact code works fine if I execute it directly (not as a script).  The merge statement also executes fine by itself as a script - only fails when inside a stored procedure and running as a script.

```
CREATE PROCEDURE LoadWorkOrdersToImport
AS
    BEGIN
        MERGE INTO myTable AS target
		USING mySource AS source
		ON target.id = source.id
		WHEN MATCHED THEN
		    UPDATE SET 
		    	target.x = source.x
		    	, target.y = source.y
		WHEN NOT MATCHED BY TARGET THEN
		    INSERT (id,x,y)
		    VALUES (source.id,source.x,source.y)
		WHEN NOT MATCHED BY SOURCE THEN 
			DELETE;		
           
    END;
```
