### ISSUE TITLE
Is it possible to run MongoDB javascript scripts in DBeaver

### ISSUE THREAD

**Issue by robshep** [serge-rider/dbeaver#1650]
Hi, I've asked this question on dba.stackexchange.com - not sure if you monitor DBeaver tags there, or whether github issues are best for usage support queries?  I'll delete as appropriate.

https://dba.stackexchange.com/q/173197/124535

DBeaver's wiki [1] show a simple query against a Mongo database but what about admin scripts? It would be great to develop these in DBeaver but I've tried a few permutations to no avail.

Here's an example of a maintenance script:

```
var cursor = db.album.find({}, {"k": 1 })
var albumKeys = []

while( cursor.hasNext() ){
    albumKeys.push( cursor.next()['k']);
}

cursor = db.song.find({ "alb" : { $not : { $in : albumKeys } } } )
var songsWithMissingAlbum = []

while( cursor.hasNext() ) {
    songsWithMissingAlbum.push(cursor.next())
}

printjson(songsWithMissingAlbum)
```

1: https://github.com/serge-rider/dbeaver/wiki/NoSQL-MongoDB

**Comment by robshep** [comment]
Mostly solved, but any other insight would be gratefully received.

https://dba.stackexchange.com/a/173316/124535

**Comment by serge-rider** [comment]
SO reply is quite correct.
DBeaver doesn't perform full JS script parse. It just splits queries using divider and then passes queries to Mongo one by one.
