### ISSUE TITLE
Wrong user/session to run script

### ISSUE THREAD

**Issue by SZubarev** [serge-rider/dbeaver#1653]
- Open two sessions to the same DB using different users credentials (limited user and dba)
- Run SQL query in one session from limited user - get error, ok
- Change session using combo in toolbar to dba session
- Run the same query in dba session - same error
- Disconnect limited user session, disconnect dba session, connect dba, run again - works fine

Tested on AWS Redshift, DBeaver EE 4.0.5

**Comment by serge-rider** [comment]
Can't reproduce.

To check in what exactly database query is executed you can open Query Manager view.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
