### ISSUE TITLE
CR or LF in SQL/TableName causes invalid JSON export

### ISSUE THREAD

**Issue by rmerren** [serge-rider/dbeaver#1654]
To cause this issue in v4.0.4:

- Create a query with multiple lines in the editor. Example:

```
select *
from mytable
where id>0
```

- Execute the query
- Right click on the results and select export resultset
- Export to JSON with the "Print table name" option checked

The resulting json will include the sql query (as the table name) and the newlines will be included in the JSON. As indicated in issue #1163, these are invalid characters. To resolve this in org.jkiss.dbeaver.tools.transfer.stream.impl.DataExporterJSON, the tablename should be cleaned with the same escapeJsonString method created for issue #1163, called in the printHeader method.

As a workaround, leaving the "Print table name" option unchecked will avoid including invalid JSON.

Thanks for the great database tool!

**Comment by serge-rider** [comment]
Fixed, thanks for details.

**Comment by rmerren** [comment]
That's fast service!
