### ISSUE TITLE
Unable to connect to Azure SQL Server on Mac

### ISSUE THREAD

**Issue by tresdna** [serge-rider/dbeaver#1656]
Mac OSX Sierra
DBeaver 4.0.5 and 4.0.6
Microsoft Driver (/sqljdbc_6.0/enu/jre8/sqljdbc42.jar)

I have DBeaver 4.0.5 running just fine on my usual laptop.  I installed DBeaver on my new Mac using brew cask.  Java was installed as version 1.6.0_65. I updated to 1.8.0_131 (SE Runtime). Then installed Eclipse-RCP (brew cask).  I pulled my .dbeaver-data-sources.xml from my usual laptop onto the new computer.  DBeaver starts up just fine and I see all my data sources.  But when I try to connect, I get the following error:

com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed. ClientConnectionId:83bbc1ec-9322-4b0f-9d5d-e30d4ab219dd

I opened up DBeaver on my usual laptop and connected just fine, suggesting it's not a database problem, internet problem, or settings problem.  But just in case, I tried creating a new connection from scratch on the new computer and ran into the same problem.

I'm sure this must be a setup issue on my side.  I did things out of order or installed the wrong files, but I'm not sure how to start diagnosing this.  When I compare the old system to the new system, they look the same.

Attaching log file in case that helps.
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/997860/dbeaver-debug.txt)

**Comment by serge-rider** [comment]
Did you try to connect with jTDS driver? Or newer Microsoft driver (you can download it from Microsoft web site)?

**Comment by tresdna** [comment]
I haven't tried that yet.  DBeaver was doing great on my MacBook using the sqljdbc42.jar driver so I didn't think to try something else.  I'll work on these today suggestions today though and report back.

**Comment by tresdna** [comment]
I was able to get both drivers to work. Definitely user error.  I didn't clear out the default entries in the driver configuration after adding the sqljdbc42.jar. And I don't think I made sure it loaded the class before clicking OK.
