### ISSUE TITLE
Postgres. Exporting data with UUIDs columns

### ISSUE THREAD

**Issue by greenpeas** [serge-rider/dbeaver#1657]
Postgres database.
When I export the data with the UUIDs types columns, I get the SQL at the output in which the values are not framed by single quotes:
![image](https://cloud.githubusercontent.com/assets/3856344/26022975/1c4a1f94-37bb-11e7-8c81-322e5773aec7.png)
Table properties:
![image](https://cloud.githubusercontent.com/assets/3856344/26022985/489c5b5c-37bb-11e7-9c1b-6b1caf50879a.png)
![image](https://cloud.githubusercontent.com/assets/3856344/26023002/8fb3cb92-37bb-11e7-9df6-3cd529e36e18.png)

**Comment by serge-rider** [comment]
Thanks for report
