### ISSUE TITLE
Unable to connect to POSTGRESQL for running an script

### ISSUE THREAD

**Issue by alfonsbataller** [serge-rider/dbeaver#1658]
Hi,
I'm trying to run a script in my connection to Postgresql. 
when select run the log shows an error saying

psql unrecognized option --no--beep

I've tried to change the beep option (flagged and unflagged) without success. 
I've typed as suggeste psql --help but no information found

Versions:
DBeaver: Version 4.0.6
PostgreSQL: Version 9.4.11.0 (9.4.11.0

**Comment by serge-rider** [comment]
It is a bug in PG script exec wizard (it messes psql with pg_dump)

**Comment by alfonsbataller** [comment]
Hi again,
I downloaded version 4.0.7.  and I get the same error. I'm not sure if I'm wrong.  what information do you need to evaluate it?
thanks

**Comment by serge-rider** [comment]
This bug i fixed. 
Fix will be included in 4.1.0 (see milestone info).

**Comment by alfonsbataller** [comment]
thanks. I misunderstood it putting the resolution in 4.0.7
Thanks!!
