### ISSUE TITLE
New "Quick filter" - pasting issue.

### ISSUE THREAD

**Issue by g-rusev** [serge-rider/dbeaver#1659]
Hello,

The new Quick filter is awsome! Thanks for it!

I am already heavy using it and notice an annoying bug:

If I have text in the clipboard, copied from another text editor (notepad++) and I try to PASTE it in the quick search box with CTRL+V, I got an error message:

"Clipboard contains data in unsupported format"

When I right Click on the filter and select PASTE from the context menu, the same text is pasted correctly.

OS Info:
Windows 7 Professional, 64 bit

*** Date: Monday, May 15, 2017 4:48:52 PM EEST

*** Platform Details:

*** System properties:
DRIVERS_LOCATION=C:\Users\George\.dbeaver-drivers
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
awt.toolkit=sun.awt.windows.WToolkit
eclipse.application=org.jkiss.dbeaver.core.application.standalone
eclipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
-launcher
C:\DBeaver\dbeaver.exe
-name
Dbeaver
--launcher.library
C:\DBeaver\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.401.v20161122-1740\eclipse_1617.dll
-startup
C:\DBeaver\\plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
--launcher.overrideVmargs
-vm
C:\DBeaver\jre\bin\server\jvm.dll
eclipse.home.location=file:/C:/DBeaver/
eclipse.launcher=C:\DBeaver\dbeaver.exe
eclipse.launcher.name=Dbeaver
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
eclipse.product=org.jkiss.dbeaver.core.application.product
eclipse.startTime=1494849527614
eclipse.stateSaveDelayInterval=30000
eclipse.vm=C:\DBeaver\jre\bin\server\jvm.dll
eclipse.vmargs=-Xms64m
-Xmx1024m
-Djava.class.path=C:\DBeaver\\plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
equinox.init.uuid=true
equinox.use.ds=true
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
gosh.args=--nointeractive
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\DBeaver\\plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
java.class.version=52.0
java.endorsed.dirs=C:\DBeaver\jre\lib\endorsed
java.ext.dirs=C:\DBeaver\jre\lib\ext;C:\Windows\Sun\Java\lib\ext
java.home=C:\DBeaver\jre
java.io.tmpdir=C:\Users\George\AppData\Local\Temp\
java.library.path=C:\DBeaver;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:/DBeaver/jre/bin/server;C:/DBeaver/jre/bin;C:/DBeaver/jre/lib/amd64;C:\Windows\system32;C:\Windows;*******
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_77-b03
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_77
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.77-b03

![dbeaver_error](https://cloud.githubusercontent.com/assets/13536076/26060959/40443580-398f-11e7-8593-fccf8b967992.png)

**Comment by serge-rider** [comment]
Thanks for report
