### ISSUE TITLE
Corrupt driver jars/dlls are not reloaded after proxy is set

### ISSUE THREAD

**Issue by beirtipol** [serge-rider/dbeaver#166]
We have a corporate proxy which returns HTML to any app which tries to download a file without the proxy configured. This has led to the files in C:\Users\MY_USERNAME\.dbeaver\.metadata\.plugins\org.jkiss.dbeaver.core\drivers\mssql being corrupted.

e.g.
sqljdbc4.jar contains the html source for our proxyconfiguration help page.

Clicking 'download' from the driver page does not re-download these files. Deleting these files allows me to download them again.

**Comment by serge-rider** [comment]
Did you try to set proxy configuration in DBeaver (in preferences or right in download dialog)?

**Comment by beirtipol** [comment]
Yes. The issue is that I had not set the proxy settings for the initial download. Once I set them correctly, I had to delete the corrupt files in order to download again.

**Comment by serge-rider** [comment]
Ok. So, this issue is about re-downloading corrupted driver files?

**Comment by serge-rider** [comment]
Ok. So this is a feature request for re-downloading corrupted jars.

**Comment by beirtipol** [comment]
Yup
