### ISSUE TITLE
Default Bind Variables to NULL

### ISSUE THREAD

**Issue by Roill** [serge-rider/dbeaver#1660]
Can any unassigned bind variables in the prompt be defaulted to null when executing a query? There are cases where I have a query with 50+ variables, and it's kind of a hassle to fill them all in when I only need to provide a few. 

When I run the query with only a few variables assigned, I get an "ORA-00936: missing expression" error. When I fill in all of the blank values with "null" (no quotes), it works.

If there is already an option for this, let me know. I couldn't find it.

Running Oracle 11.02. DBeaver version 4.0.7.

Thanks

**Comment by serge-rider** [comment]
Agreed.
As now DBeaver uses parameter values directly in query text we can consider that empty parameter values can be evaluated as NULL.
