### ISSUE TITLE
Redshift with Postgres JDBC - errors every time after running one query, till you reconnect

### ISSUE THREAD

**Issue by mtortolano** [serge-rider/dbeaver#1661]
I'm consistently having this problem now which didn't use to be an issue. Every time after I connect to Redshift I can run exactly one query, every query after that fails with this error:

SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
  org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block

If I disconnect and reconnect to Redshift then I can run one more query till the error reappears. Using DBeaver 4.0.7 64bit on Windows 10, with the JRE you ship and JDBC driver 9.4-1206-jdbc4 auto downloaded by DBeaver.

**Comment by serge-rider** [comment]
Please attach debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

Workaround: switch to auto-commit mode.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
