### ISSUE TITLE
the two tag's cannot execute scripts in parallel

### ISSUE THREAD

**Issue by bouyeijiang** [serge-rider/dbeaver#1662]
when execute one tag scripts,other need to watting for

**Comment by serge-rider** [comment]
This is configurable:
![default](https://cloud.githubusercontent.com/assets/6398845/26092694/0c7e5c9e-3a1b-11e7-9f31-5d040ad4baf5.png)

**Comment by bouyeijiang** [comment]
also，
When editing stored procedures, I don't need formatting to keep formatting in writing，how to set?

**Comment by serge-rider** [comment]
See SQL editor formatting preferences
