### ISSUE TITLE
[Feature Request] Code Folding

### ISSUE THREAD

**Issue by kyleflan** [serge-rider/dbeaver#1664]
It looks like this has been requested before here: http://dbeaver.jkiss.org/forum/viewtopic.php?f=3&t=1272, but I would like to give a +1 to request code folding/collapsing.

Personally, I would only use code folding with a selection of text (similar to VIM's zf, zo). Automatic folding would probably be useful for some, but if it's simpler to implement folding for a specific selection, that would be my vote.

An option to enable/disable in preferences would be useful as well, so users who don't need the functionality aren't impacted.

**Comment by serge-rider** [comment]
I'm going to add this feature in the next version.
Could you test how it works in EA: https://dbeaver.jkiss.org/files/ea/ ?

**Comment by kyleflan** [comment]
# Initial Feedback

Environment: macOS Sierra v 10.12.5

_For issue 1 reproduction steps I'm using the "Install-Northwind-Script.sql" from [here](http://binaryworld.net/blogs/wp-content/uploads/2014/03/Install-Northwind-Script.zip)_

## Issue 1: Expanding a fold to make edits expands other folds in the editor.

Reproduction steps:

1. Copy and paste Northwind script into new SQL Editor
2. Close folds at line numbers 15, 19, 24, 28, 156, 170.
3. Open fold at line number 24. 
4. Insert a line at 26 before GO, e.g. -- here's a comment
5. After adding the line and moving the cursor, most folds open (except for the fold at 15). Also, the editor jumps from the edited line to a new one, presumably because the folds have been opened.

## Minor Issues

- No option to open/close all folds. 
- Folds do not persist across saves
- No option to disable folding
- No option to manually specify folding area. Justifying use case below. 

Imagine doing a join between tables invoice_header and invoice_line_items on keys: invoice_id, line_item_id, order_date. 

Both tables have many columns that are needed in the final result, but when constructing the join, I only care about invoice_id, line_item_id and order_date when selecting a certain range. Being able to focus on that by collapsing the ancillary columns is useful.

Consider the two scripts below:

It would be much easier to focus on constructing the logic for your joins and where predicates if the extraneous columns could be folded away. Additionally, when reviewing the code, I can quickly see the goal of this query without scrolling my life away. 

```
SELECT 
I.invoice_id,
L.line_item_id,
L.order_date,
...
FROM invoice_header I
INNER JOIN invoice_line_items L
ON I.invoice_id = L.invoice_id
WHERE 
L.line_item_id > 0
AND
L.order_date >= '2017=09-06';

```
This prevents the developer form ever being able to see the whole query (key column, joins, criteria) at the same time:

```
SELECT
I.invoice_id,
L.line_item_id,
L.order_date,
I.bill_to_id,
I.bill_to_address_1,
I.bill_to_address_2,
I.bill_to_city,
I.bill_to_state,
I.bill_to_zip,
I.ship_to_id,
I.ship_to,
I.ship_to_address1,
I.ship_to_address2,
I.ship_to_city,
I.ship_to_state,
I.ship_to_zip,
I.created_date,
I.customer_code,
I.customer_name,
I.sales_rep,
I.sales_region,
L.product_id,
L.line_number,
L.product_code,
L.product_name,
L.product_description,
L.product_qty,
L.product_price,
L.discount,
L.total_line_price,
L.tax,
L.shipping_cost,
L.margin,
L.group,
L.classification,
L.back_ordered,
L.price_break,
L.material_class
FROM invoice_header I
INNER JOIN invoice_line_items L
ON I.invoice_id = L.invoice_id
WHERE 
L.line_item_id > 0
AND
L.order_date >= '2017=09-06'
```

**Comment by serge-rider** [comment]
Thanks for feedback.

Folding enablement option will be added in the next version.
Open/close all folds and manual foldings will be added as separate FRs. 
Folding persistence is not supported by Eclipse framework out of the bx so it will be a bit more complicated.
Problem with folds expand after edit will also be solved in one of next versions.

**Comment by serge-rider** [comment]
Further improvements will be tracked in #2156

**Comment by datauduong** [comment]
I am on Windows version 5.3.5, but I can't find Code Folding (Does it exist ?)

**Comment by yrimal** [comment]
I'm on 6.0.0 windows version and can't see this feature yet.

**Comment by mcunha98** [comment]
Just to update, I enable the option on preferences, but for procedures the content was not 'folded'
![image](https://user-images.githubusercontent.com/6831010/82236465-81863380-990a-11ea-83d4-21ce22ed8e97.png)
