### ISSUE TITLE
When using ORACLE DB, comment script is missing from table and view sql script.

### ISSUE THREAD

**Issue by ch2robin** [serge-rider/dbeaver#1665]
HI!
I am mainly using the oracle database.

When i click DDL of table property, COMMENT SCRIPT of TABLE is not displayed.
Also, Declaration of properties of VIEW does not show commet script.

Commnet scrpit is useful, I hope it is displayed in the ddl or declaration.

**Comment by serge-rider** [comment]
Well,m I can see/edit view comments. Could you provide more details?

Table DDL will include comments in the next version.

**Comment by ch2robin** [comment]
hi!

I'm sorry. I should have written more details.
There is no problem with the modification of View commnet.

I am trying to modify the comment in the View column.

Double click the commnet area to modify it, and the screen will change to the properties of the column.

BUT, To modify the COMMENT of the TABLE COLUMN, double-click the COMMENT of the COLUMN to make it editable.

![view comment of columns](https://cloud.githubusercontent.com/assets/28743365/26229367/3a358d02-3c7c-11e7-9062-d8c158a787bc.jpg)


i'm not good at english
Thank you for your quick reply.

**Comment by serge-rider** [comment]
View column comments issues is tracked in #1678

**Comment by ch2robin** [comment]
HI!
Thank you for applying my request.
I checked the version 4.0.8 today.

There is a slight modification (request).

1. Please add ";" at the end of sql scrpit.
2. Please add ";" to the end of the comment scrpit.
3. Add 1 row between sql scrpit and commect scrpit.

![9](https://user-images.githubusercontent.com/28743365/26865607-6d5103b2-4b98-11e7-8bfe-375b7025e8f5.jpg)

And I have a question.

COMMENT SCRIPT is not yet displayed in DDL of VIEW. Is this registered as milestone in 4.1.0?

I also requested the ability to directly enter or modify the COMMENT value in VIEW PROPERTIES. Is this feature request also registered with milestone in 4.1.0?
