### ISSUE TITLE
Create a PPA for updating dbeaver under ubuntu

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#1667]
It would be really nice to have dbeaver update via apt-get.
The easiest way of doing this would be to have a PPA.
Please see the following for more details:
https://developer.ubuntu.com/en/publish/other-forms-of-submitting-apps/ppa/

**Comment by serge-rider** [comment]
Agreed

**Comment by serge-rider** [comment]
Link above is broken.
However I can google how to do this (and this is quite tricky). Will try to PPA for 4.1 release.

**Comment by y2josei** [comment]
+1

**Comment by benyanke** [comment]
I would also LOVE a ppa. Given that this is one of the few decent multiplatform and multi-database tools, I plan to use this everywhere. A PPA would be far easier to keep up to date on my many systems, both at work and at home.

I know if there is a PPA for the enterprise version, I'd buy that in a heartbeat.

**Comment by serge-rider** [comment]
This seems to be a really wanted feature :)
We'll try to make this till 4.2.2.

**Comment by benyanke** [comment]
Sure is! All my computers are set up by a single bash script, so it's very nice not having to download and manually install DEB files. Just add the PPA, and install it with the rest of my apt packages.

Also, not sure if this is there yet either, but on the enterprise version, if there was a terminal way to specify the key/license, that would also be a killer feature, allowing auto-provisioning of EE installs with just a script.

**Comment by serge-rider** [comment]
PPA itself is ready (https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce) but I keep working on appropriate Debian package for it. 
This is a whole new world actually. Any assistance will be appreciated.

**Comment by serge-rider** [comment]
First DBeaver CE PPA is here: https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce

Usage:
```
sudo add-apt-repository ppa:serge-rider/dbeaver-ce
sudo apt-get update
sudo apt-get install dbeaver-ce
```
I is still in beta. Please try how it works.

**Comment by karser** [comment]
It works thanks! Although it isn't that fast
```
Fetched 43,3 MB in 1min 48s (398 kB/s)  
```

**Comment by skyghis** [comment]
I use Ubuntu `17.04 - zesty` and can't use the repository as described cause you seem to support only LTS. 

```
E: The repository 'http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu zesty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Why not add package for all currently supported Ubuntu versions ?

BTW, manually editing `/etc/apt/sources.list.d/serge-rider-ubuntu-dbeaver-ce-zesty.list` and replace `zetsy` by `xenial` works.

**Comment by serge-rider** [comment]
Added zesty support.

Further improvements will be tracked in #2355

**Comment by stafio** [comment]
Shortly after you added zesty support, Artful Ardvark was released. Can you add that as well? There won't be any new releases for six months now, so there won't be any changes needed until then.

**Comment by andreas-glaser** [comment]
hallelujah thanks so much. Years of manually updating every few weeks come finally to an end! Thanks again!

**Comment by myphp2da** [comment]
Got error on Ubuntu 17.10
`sudo add-apt-repository ppa:serge-rider/dbeaver-ce
 DBeaver Community Edition
Universal Database Tool and SQL Client
https://dbeaver.io/
 More info: https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmpophgy59_/pubring.gpg' created
gpg: keyserver receive failed: No data
Failed to add key.`

**Comment by Racle** [comment]
Old issue, but if someone has tries google, they might find same problem as I had (with pop_os atleast), so here's the fix.

Basically pop_os own package sources has higher priority than this PPA, and they also host dbeaver-ce, so they try install .deb from their source, not from this PPA. You can fix this by adding higher priority to this PPA than their package sources.

edit `/etc/apt/preferences.d/pop-default-settings` file and add these lines to end of the files and you should get .deb from this PPA.
```
Package: *
Pin:release o=LP-PPA-serge-rider-dbeaver-ce
Pin-Priority: 1002
```
