### ISSUE TITLE
Allow CTRL+ENTER to map to new result tab

### ISSUE THREAD

**Issue by fowlerrr** [serge-rider/dbeaver#1668]
Hi,

I often remote into my work desktop and lose functionality of the '\' key.  This keeps me from being able to use Ctrl+\ to create a new tab.

Would it be possible to have the option of using Ctrl+Enter to create new results tabs?

Thanks,
Ryan

**Comment by serge-rider** [comment]
You can redefine any shortcuts (well, almost any) in preferences->General->Keys. Command "Execute SQL in new tab".

**Comment by fowlerrr** [comment]
Excellent.  Thanks.
