### ISSUE TITLE
Add Cassandra 3 support by using datastax java-driver for version 3

### ISSUE THREAD

**Issue by scnt** [serge-rider/dbeaver#167]
Currently Cassandra 3 is not working in DBeaver because some system tables were moved (see https://issues.apache.org/jira/browse/CASSANDRA-6717). 
For example the table system.schema_keyspaces was moved to system_schema.keyspaces. Because of this the metadata can not be retrieved so the connection won't be established. This produces the following error message:
![image](https://cloud.githubusercontent.com/assets/16814982/12475673/d9cee3a2-c024-11e5-92b4-6d1678179899.png)

Datastax released a driver with Cassandra 3 support, version 3.0.0-rc1 (http://datastax.github.io/java-driver/). Using this driver should be enough to enable connections to Cassandra 3 servers.

**Comment by serge-rider** [comment]
I've changed driver to 3.0.rc1 work. Generally it works ok (on both Cassandra 2.x and 3.x). I had to change some model classes due to API changes, hopefully didn't break anything.
Do you have any CQL snippets I can test before release?

**Comment by scnt** [comment]
Here are a few queries, if you want to test more I would recommend https://docs.datastax.com/en/cql/3.0/cql/cql_reference/cqlCommandsTOC.html since it has plenty of examples.

`CREATE KEYSPACE myKeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };`

`CREATE TABLE myKeyspace.users (user_name varchar PRIMARY KEY, birth_year bigint);`

`INSERT INTO myKeyspace.users (user_name, birth_year) VALUES ('johndoe', 1970);`

`SELECT * FROM myKeyspace.users WHERE user_name = 'johndoe'`

`DELETE FROM myKeyspace.users WHERE user_name = 'johndoe'`

**Comment by mysticdelta** [comment]
Datastax has released stable Java Driver for Cassandra version 3.0.0 (http://www.datastax.com/dev/blog/datastax-java-driver-3-0-0-released). I would suggest using this version.

**Comment by serge-rider** [comment]
Ok, I'll take this into account, thanks for info.

**Comment by makosblade** [comment]
Any updates on this? I don't mind using cqlsh so much but DBeaver is much nicer :D

**Comment by serge-rider** [comment]
Cassandra 3 driver will be added in version 3.6 (next one).

**Comment by makosblade** [comment]
Excellent, thanks!

**Comment by lavrenov** [comment]
I can't see it in latest release 3.6.10, so whats happened?

**Comment by serge-rider** [comment]
Please clarify.
DBeaver 3.6+ uses DataStax driver 3.0.0.rc1.

**Comment by lavrenov** [comment]
I apologize for the ignorance, but I do not see anything related to Apache Cassandra or Datastax in Driver manager. I 'll really appreciate your help to resolve my problem. I also can't find any info about it, 
P.S. I have a feeling that I misplaced the question, so sorry for this.
![dbeaver](https://cloud.githubusercontent.com/assets/19730754/16163660/348383ce-34e3-11e6-9092-f71a134a13a0.jpg)

**Comment by serge-rider** [comment]
This is Community Edition.
In order to use Cassandra (and other NoSQL databases) you need Enterprise Edition (http://dbeaver.jkiss.org/download/enterprise/). It is also free.

**Comment by lavrenov** [comment]
Oh, I see... Thank you so much!

**Comment by RSingh1983** [comment]
Even in 3.7.2 version, the client is not able to connect to Cassandra 3.0.3. Do we need to include any other dependency for the same, as the cassandra driver version is still showing as 2.x while creating a new connection

**Comment by serge-rider** [comment]
DBeaver uses DataStax driver 3.x which can connect to both Cassandra 2.x and 3.x. I'll fix driver description (which still says Cassandra 2.x).
Error above looks like some network issue (btw you can test it with `telnet <ip> 9042`).

**Comment by dvasdekis** [comment]
Why do you guys keep the Community edition around, if Enterprise is free? I spent an hour trying to figure out where the Cassandra driver was...

**Comment by serge-rider** [comment]
Community edition is open-source, EE isn't.

And we have pretty silly web-site and very bad marketing. And "we" is actually "I" :)
Don't forget - DBeaver is still my hobby project.

**Comment by apps25** [comment]
hi i am using dbeaver community and i want to use cassandra on ubuntu and i am unable to do so anybody please help how can i do the same, I am new here.

**Comment by naraesk** [comment]
it's not possible with community edition, you need enterprise edition as alreay mentioned.

However, it's not really free. Only the 2 weeks trial version is free.
