### ISSUE TITLE
Oracle RAW(16) datatype shows wrong

### ISSUE THREAD

**Issue by DriesSch** [serge-rider/dbeaver#1672]
Hello guys

I recently started using DBeaver, I must say it's an enormous advantage compared to Oracle SQL Developer.
There is an issue though, we use the datatypeRAW(16) with a default of sys_guid() for primary keys. When doing a select in OSD it shows a normal GUID, in DBeaver it shows some weird symbols. What could be wrong?

**Comment by serge-rider** [comment]
Could you post sample DDL/insert?

**Comment by anti-rsca** [comment]
Thanks for the quick reply!

Table is created like this:
CREATE TABLE MCVSSETDEF(
	PKMCVSSETDEF RAW(16) DEFAULT sys_guid(),
	GROEP CHAR(4) NOT NULL,
	NAAM VARCHAR2(35) NOT NULL,
	TIJDUPDATE DATE DEFAULT SYSDATE,
	GEBRUIKER VARCHAR2(8) DEFAULT USER,
	CONSTRAINT MCVSSETDEF_PK PRIMARY KEY (PKMCVSSETDEF)
);

After I did this insert: INSERT INTO MCVSSETDEF (groep, naam) values('2238','TestSet');
I do this select: SELECT * FROM MCVSSETDEF;

I get this result:
![image](https://cloud.githubusercontent.com/assets/12149704/26189357/95966582-3ba4-11e7-8e12-2cca6db5ab15.png)

In Oracle SQL Developer I get this result:
![image](https://cloud.githubusercontent.com/assets/12149704/26189483/41482726-3ba5-11e7-9b11-fc07ed83728c.png)


Is that the info you need?

**Comment by serge-rider** [comment]
Yes, thanks.
You can change binary presentation in preferences:
![default](https://cloud.githubusercontent.com/assets/6398845/26191888/55f52e5e-3bb8-11e7-87d7-be148aca027b.png)

So results will look just like in SQL Developer:
![default](https://cloud.githubusercontent.com/assets/6398845/26191870/424c72e0-3bb8-11e7-8302-2f3981631eaa.png)

**Comment by DriesSch** [comment]
Wonderful, thanks for the quick replies and the solution!

**Comment by srinivas-os** [comment]
Note: For anyone like me using 4.3.5, this option is under Preferences -> Result Sets -> Editors now.

**Comment by SeabiscuitCZX** [comment]
I'm facing another issue. after changed this option, the display is fine. 
but i did select like SELECT * FROM DEVICE_REGISTRATION d WHERE d.REGISTRATION_ID = 'B69A7BC09C4D428B84EE059EED78348B'; the REGISTRATION_ID type is RAW(16). nothing selected.

**Comment by serge-rider** [comment]
This should work.
I've also fixed native Oracle hex formatter (so you can use result "Filter by" menu).

**Comment by SeabiscuitCZX** [comment]
SELECT * FROM table t WHERE t.ID = HEXTORAW('E6B92841FC9E4CBF97607D87389439C3'); i'v tried this way. it's working.

**Comment by yannickvidal** [comment]
In DBeaver v6.0.1, the option is now under Window > Preferences > Editors > Data Editor > LOB Editors

**Comment by ovidiugabriel** [comment]
This answer is obsolete. The option is now under Window > Preferences > Editors > Data Editor > LOB Editors.

> Yes, thanks.
> You can change binary presentation in preferences:
> ![default](https://cloud.githubusercontent.com/assets/6398845/26191888/55f52e5e-3bb8-11e7-87d7-be148aca027b.png)
> 
> So results will look just like in SQL Developer:
> ![default](https://cloud.githubusercontent.com/assets/6398845/26191870/424c72e0-3bb8-11e7-8302-2f3981631eaa.png)

**Comment by ovidiugabriel** [comment]
This changed once again on 7.3 it is in Editors > Data Editor > Binary Editors
