### ISSUE TITLE
Can't fetch all data.

### ISSUE THREAD

**Issue by DB2User** [serge-rider/dbeaver#1673]
I'm not sure if this is a user issue (me), or a program issue. I know I used to be able to click the button to fetch all data, but now it is grayed out. I am running 4.0.7 against a DB2 table on MVS. The fetch all data button is inoperative, as is the right-click menu option Navigate -> Fetch All Data.

**Comment by serge-rider** [comment]
Fetch all data is disabled if you already have all data in results view. I.e. number of rows in table/resultset less than fetch size (200 by default).

**Comment by DB2User** [comment]
But, I didn't. There were 20,000+ rows, I only had the initial 500.

**Comment by DB2User** [comment]
Never mind. I just tried again and it returned all my rows. I don't know what happened the first time.
