### ISSUE TITLE
Support for Firebird CHAR(16) CHARACTER SET OCTETS

### ISSUE THREAD

**Issue by tJeyhun** [serge-rider/dbeaver#1674]
Hi
Great application, just one issue (something like #1672)
Firebird has support for UUID fields ( CHAR(16) CHARACTER SET OCTETS ) and in editor it should present values like UUID. FlameRobin does that. You have support for binary fields bute not for char fields.

Thanks.

**Comment by serge-rider** [comment]
Please check #1672 solution. Doesn't it work for Firebird?

**Comment by tJeyhun** [comment]
I have tried this, but it seems that DBeaver does not recognise these fields as binary. We use "CHAR(16) CHARACTER SET OCTETS" for these fields. So something else must be done.

Thanks.

**Comment by tJeyhun** [comment]
Any progress on this issue???

**Comment by serge-rider** [comment]
Not yet.
Could you post sample DDL+INSERTs to make it easier?

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
