### ISSUE TITLE
ResultSet: Color by column

### ISSUE THREAD

**Issue by amosmoss** [serge-rider/dbeaver#168]
I just came up with a crazy thought. I was passing over a query's records, looking at some column at the end of the records, but every now and then I had to check that one of the columns at the beginning of the record has not changed.

And then I thought that sliding back and forth of the record's column is stupid, and thought that it could be great if by left-clicking the column name (at the beginning) I could choose a color by option, and then all the records colors will change according to its value (from a preset color theme). If the field is numeric/date, the color could be gradient.

Here are some illustrations:
![image](https://cloud.githubusercontent.com/assets/16815760/12476741/e2f5c234-c033-11e5-898e-2e1e8bd304e8.png)
![image](https://cloud.githubusercontent.com/assets/16815760/12476749/ecf3cef2-c033-11e5-90cf-2bd5492d30ec.png)
![image](https://cloud.githubusercontent.com/assets/16815760/12476751/f248337a-c033-11e5-9c5f-912e77a23217.png)

**Comment by serge-rider** [comment]
Good idea.
I'm going to add this feature in the next major version.

**Comment by amosmoss** [comment]
Great, thanks!

**Comment by serge-rider** [comment]
First version of results coloring added in 3.5.9. Please check.
Additional coloring features will be tracked in different issues.
