### ISSUE TITLE
ResultSet does not apply Custom Filter correctly beyond initial page load

### ISSUE THREAD

**Issue by drewed** [serge-rider/dbeaver#1680]
DBeaver has a wonderful feature in the Custom Filter for result sets.  It allows one to reorder columns, exclude columns, etc.  Unfortunately, when applying a custom filter to a large result set (i.e. greater than the defined initial result set size) and one scrolls loads the next "page" of results, the fetched data does not come from the columns identified in the filter.

Suppose I create a table in a PostgreSQL database as follows:
```sql
begin;
create table custom_filter_test (a varchar(4), b varchar(4), c varchar(4), d varchar(4), e varchar(4) , f varchar(4));

do $$
begin
	for counter in 1..400 loop 
		execute format($q$
			insert into custom_filter_test (a, b, c, d, e, f)
			values ('a%1$s', 'b%1$s', 'c%1$s', 'd%1$s', 'e%1$s', 'f%1$s')
			$q$,
			counter
		);
	end loop;
end;
$$;

commit;
```

If I run the query `select * from custom_filter_test`, apply the following custom filter, and scroll past the end of the initial record set size notice that the f, e, and c column data is replaced by a, d, and b for the second page.

Filter Configuration:
![image](https://cloud.githubusercontent.com/assets/11722145/26257184/e460a33e-3c7c-11e7-97fc-b37cb3437374.png)

First and Second Page Load Data (red line denotes the record set page boundary)
![image](https://cloud.githubusercontent.com/assets/11722145/26257393/ab753778-3c7d-11e7-8468-ec48659dfc22.png)

I'm running DBeaver Enterprise 4.0.5 on Mac OS Sierra (10.12.5).

**Comment by serge-rider** [comment]
This is a bug. Data refresh and extra pages fetch resets columns ordering.
