### ISSUE TITLE
Dbeaver doesn't start. Crashes.

### ISSUE THREAD

**Issue by misutkowski** [serge-rider/dbeaver#1681]
When I try to start the application (under Linux), it shows window about error. In the window, there is an information where there is an log do gather information about crash. Bad behaviour of application began in version 4.0.6. In Windows it works perfectly.
Log is in attachment to this issue.
Thanks, kind regards.
[1495313030799.zip](https://github.com/serge-rider/dbeaver/files/1016504/1495313030799.zip)

**Comment by serge-rider** [comment]
DBeaver 4.x requires Java 8.
