### ISSUE TITLE
Providing an installer without JRE included

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1682]
I would like to see DBeaver site to provide an installer without a JRE included. This reduces download file size and waste of traffic. Most ppl already have a JRE installed and don't want another one which becomes outdated and non-maintained easily as ppl usually only update their self-installed one.

**Comment by serge-rider** [comment]
Windows installer is already the smallest DBeaver distribution.
DBeaver was tested with JRE it is shipped with - this solves a lot of issues with wrong/missing Java.
DBeaver doesn't update system JRE. So it can't became outdated.
If you have any concerns or you need Java 9 (for any reason) then you can't uncheck "Install JRE" option in installer.

After all I don't see any serious reason to remove JRE from installer (plus having too many different distributions confuse people).
