### ISSUE TITLE
Unable connect to DB2 test database (v11)

### ISSUE THREAD

**Issue by fcpxh16** [serge-rider/dbeaver#1686]
I am using DBeaver 4.0.3
I can connect to production (DB2 v10), but unable to connect to test(v11).
Does Dbeaver 4.0.3 support DB2v11?

![dbeaver error connect](https://cloud.githubusercontent.com/assets/28875337/26326450/420813f8-3f09-11e7-9385-c7baa25a9f83.PNG)

**Comment by titou10titou10** [comment]
Hi,
Yes DBeaver fully supports DB2 v11.1
It seems your v11.1 database is not configured the same way your DB2 v10 is, concerning the security setups Does the DB2 v11 instance allows client connections? is it set up to accept only certain specific types of client? Can you connect from another client? from CLI?
Thanks

**Comment by fcpxh16** [comment]
Hi,
Thanks for following up.
Our DBA has changed catalog parameters on the DB2 Connect side for test environment (v11) to match production (v10). Now it’s working fine.

Sincerely,
Pei-Pei Hsu
