### ISSUE TITLE
long time no operate, run a script error

### ISSUE THREAD

**Issue by D-mawl** [serge-rider/dbeaver#1688]
1: i have some time not operate (like 10 min); 
2: then i run script;
3: then show initlizing 
4: i can't cancel, onley two way : 1) close dbeaver, reopen it; 2)wait about 10min , then i can reconnect the database;

**Comment by D-mawl** [comment]
after waiting 10min , the error show up:
SQL Error [08S01]: Communications link failure¶¶The last packet successfully received from the server was 1,973,108 milliseconds ago.  The last packet sent successfully to the server was 935,269 milliseconds ago.

**Comment by serge-rider** [comment]
This may happen if you connecting thru tunnel or VPN.

You could try to enable keep-alive option (in connection properties) to avoid connection die.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
