### ISSUE TITLE
Not able to use Secure Storage (with master password or not) for password encryption

### ISSUE THREAD

**Issue by xfr-dev** [serge-rider/dbeaver#1689]
Hi,
I'm trying to use the DBeaver secure storage to crypt password of my database connections (as i do in Eclipse Neon). I've tested several DBeaver versions including the last one ee (4.0.5) and ce (4.0.7).
But i don't find how to activate it. Anyone can help me please?
Thanks,
Regards,
xfr

PS : This is what i've found about this feature : https://github.com/serge-rider/dbeaver/issues/1005

**Comment by serge-rider** [comment]
Secure storage feature is in EE version only.

**Comment by xfr-dev** [comment]
Ok, but the configuration panel is also shown in CE version at : General \ Security \ Secure storage

As i said, i've already tried EE version but i don't know how to activate secured password encryption.
When i create a connection, all the informations about it (password included) is stored in file : c:\users\XXXXX\.dbeaver4\General\.dbeaver-data-sources.xml
I'm missing something but i don't know what it is.

**Comment by xfr-dev** [comment]
I've uninstalled all Dbeaver versions and reinstalled EE 4.0.5 version and i see know the expected menu in preferences : Database \ Security
I'm finally able to use password encryption with master password! Great!
Sorry for the incovenience(s).
