### ISSUE TITLE
Unable click "run query"

### ISSUE THREAD

**Issue by michael-newsrx** [serge-rider/dbeaver#169]
So, is my inability to click any of the run query buttons a bug or something else is going on?

(please see attached img)

![screenshot-dbeaver](https://cloud.githubusercontent.com/assets/5214185/12494629/557ab06a-c059-11e5-84f3-eb811e5cfd41.png)

**Comment by serge-rider** [comment]
What is your OS, window manager?
Are keyboard shortcuts working (e.g. ctrl+enter)?

**Comment by michael-newsrx** [comment]
> What is your OS, window manager?
>
Ubuntu 15.10, Mate Desktop

> Are keyboard shortcuts working (e.g. ctrl+enter)?
>
>
Pressing 'ctrl-enter' works, and the buttons then become enabled.

**Comment by serge-rider** [comment]
Eventually I was able to reproduce that.
I've fixed command enablement checking of execute statement/script commands.
