### ISSUE TITLE
Interface to edit blob text is very hard to use

### ISSUE THREAD

**Issue by dahousecat** [serge-rider/dbeaver#1692]
When editing the text in a blob field it is very hard to see or make changes to the actual text:

![dbeaver-edit-blob](https://cloud.githubusercontent.com/assets/3747820/26383126/7154f31c-4074-11e7-8b8b-b737036ef4c3.png)

It would be great if we could hide the binary and hex all together and make the text fill all of the space available.

**Comment by serge-rider** [comment]
Looks like you are using very old version. I newer versions you can switch between binary and text presentation

**Comment by dahousecat** [comment]
Just downloaded 4.0.7 - solves this problem and looks great. Thanks!

**Comment by daredude123** [comment]
Hello @serge-rider.

Is there a key shortcut for switching between binary and text presentation when viewing blobs?
