### ISSUE TITLE
Transaction delimiters not working

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#1694]
This is my global configuration
![immagine](https://cloud.githubusercontent.com/assets/14179578/26394741/36f1ad56-406e-11e7-957b-7e15ba4cd663.png)
And this is the configuration for the data source
![immagine](https://cloud.githubusercontent.com/assets/14179578/26394784/57193a5e-406e-11e7-834c-7fc4b5ad1fac.png)

If I exec this script using the script execution (Alt + X) works:
```SQL
CREATE TABLE AA (id NUMBER PRIMARY KEY )
/
INSERT INTO AA VALUES (1)
/
INSERT INTO AA VALUES (2)
/
```

Executing the same on the sql server data source for which I changed the configuration as above leads to an error 

> Incorrect syntax near 'GO'
```SQL
CREATE TABLE AA (id NUMERIC PRIMARY KEY )
GO
INSERT INTO AA VALUES (1)
GO
INSERT INTO AA VALUES (2)
GO
```

**Comment by serge-rider** [comment]
Can't reproduce..
BTW default preconfigured SQL Server driver already has `GO` as delimiter.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
