### ISSUE TITLE
Remove Schema from autocomplete

### ISSUE THREAD

**Issue by tronjs** [serge-rider/dbeaver#1695]
Hi, whether the latest version is included this option?
Like this guy asked from 2015: [http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1782](http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1782)

**Comment by serge-rider** [comment]
Yes, this should work in recent versions (only current and system schemas are used for auto-completion)..

**Comment by tronjs** [comment]
Thank you for your awesome work!
I love this db manager, but i think it will better if we can make the autocomplete works more easier and faster. 
I like how the autocomplete works in DataGrip, it's really fast and it hints exactly what i typing.
I know you have a lot of things to work, this is one of my favorite db managers, i still using it, and it will be so great if we can improve the autocomplete.
Anyway, this is just my question and I am clear now.
Again, thank you so much. Keep up your awesome work!

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed.
