### ISSUE TITLE
Oracle trigger with different schema cannot retrieve / populate DDL

### ISSUE THREAD

**Issue by nathanjohnson3181** [serge-rider/dbeaver#1696]
In Oracle it is valid to have a trigger owned by another schema reside in a table in another schema. 

Viewing a trigger like this shows an empty Declaration and attempting to generate the DDL also yields an empty window.

Here is an example from SELECT * FROM DBA_TRIGGERS:

| OWNER | TRIGGER_NAME | TRIGGER_TYPE | TRIGGERING_EVENT | TABLE_OWNER | BASE_OBJECT_TYPE | TABLE_NAME |
| ----- | ------------ | ------------ | ---------------- | ----------- | ---------------- | ---------- |
| A | TRIG_COMPANY | BEFORE EACH ROW | UPDATE | A | TABLE | COMPANIES |
| B | TRIG_COMPANY_UPD | BEFORE EACH ROW | INSERT OR UPDATE | A | TABLE | COMPANIES |

So the trigger exists in the A schema but the OWNER is the B schema.

**Comment by serge-rider** [comment]
You can check the fix in EA (http://dbeaver.jkiss.org/files/ea/)

**Comment by versusversus** [comment]
Hi Serge!
I was abiut to create a new issue, but found this thread which as almost the same as mine:
Oracle Database 11G, connected with ojdbc8 driver with oracle12 native client. When connected with user A I can't see DDL of a trigger in schema B (though tha actual table trigger is referincing is also in schema B). DDL and Data of the actual table that trigger is referincing - is viewable.
When attempting to edit the trigger i see only "-- Empty source" message.
