### ISSUE TITLE
[Minor Enhancement] Change "maximize" to "minimize" on query results tab.

### ISSUE THREAD

**Issue by osrojas** [serge-rider/dbeaver#1697]
Hi,

When I right-click on the _Results_ tab after running a query and click on **Maximize results panel**, the panel windows maximizes as expected. However, when I right-click on the _Results_ tab on the maximized window, it still shows the text **Maximize results panel** when it should actually be **Minimize results panel**.  Just a spelling/grammar error I thought I'd point out for you. :)

Thanks,
Ogden

**Comment by serge-rider** [comment]
Fixed
