### ISSUE TITLE
dbeaver hangs on occasion when trying to hint table name after typing '.'

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#1699]
db type: postgresql 9.6
OS: mac, win10 (identical behaviour)
Description:
After typing the schema name, followed by '.', dbeaver 'hangs' for about 2-3 minutes while consuming ~20% CPU and then returns to life again which happens to be very annoying.
I'm guessing this only happens on schemes with relatively large number of tables/views inside (in my case 288 tables, 1 view, 800+ procedures, tons of indexes and stuff). I haven't observed such behaviour on other (smaller in terms of objects count) databases.
I traced the query log and there was no avalanche of queries executing during the blackout, so it must be a frontend/application - related issue.

![image](https://cloud.githubusercontent.com/assets/13131218/26485351/71229322-41ff-11e7-9163-ce6be71cd1d9.png)

(waited about 5 minutes to unfreeze in this particular situation)

**Comment by serge-rider** [comment]
What DBeaver version do you use? 
There were a few fixes/improvements in autocomplete performance in recent versions.

Also you can open Query Manager view to see what DBeaver queries actually running (you'll need to enable metadata/util queries logging in QM settings).

**Comment by gogosofta** [comment]
I'm always using the latest version.
QM shows no running queries during the time DBeaver's hanging. It doesn't
execute any queries at all while trying to hint with the relation name.
The DB is on an Amazon host and I experience the same behaviour accessing
it from different high-bandwidth networks.
What I'm going to do next is import the DB on the localhost and try to
reproduce the issue (about 11gigs db).

Georgi Petrov
BI Architect

georgi.petrov@urbanise.com
MN: +359 893 561148
Skype: gogosoft1
www.urbanise.com
[image: Urbanise]

**Comment by serge-rider** [comment]
I have a schema with 10k tables on my local machine. Auto-complete works quite fast - with 1 or 2 seconds delay maybe.

Do you have any special settings (like filters)? 
Or SSH tunnel, VPN? In that case everything might work veery slowly if you have bad ping (even if you have good bandwidth).

**Comment by serge-rider** [comment]
Note: to read table list DBeaver executes query
```sql
SELECT c.oid,c.*,d.description FROM pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0
WHERE c.relnamespace=<schema_id> AND c.relkind not in ('i','c')
```
You could try to run it manually to see how fast it works.
To get schema ID execute
```sql
select oid from pg_catalog.pg_namespace where nspname='<schema_name>'
```

Another note: sometimes it makes sense to disable auto-complete at all for slow remote DB connections. This can be done in preferences.

**Comment by gogosofta** [comment]
The current average DB host ping time is 31 ms.
The result from the above query is 116695 rows and executes (fetching all
records in dbeaver) for about 4.8 sec.
No filters, no vpn.
I've disabled auto-complete a couple of days ago, but still if I need it
(ctrl+space) I pull the shortest straw on occasion - sometimes the hint
list shows immediately, and sometimes the popup window shows and makes me
wait 2-5 minutes until it unfreezes. This happens on different machines and
different OSes (win10/macOS).
In a while the dump import will finish and I'll come back with a feedback.

**Comment by serge-rider** [comment]
Ok, thanks for details. Looks like something else freezes the process.

Could you try to make the thread dump: when UI freezes run jstack (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and post results here.

**Comment by gogosofta** [comment]
Sure.
Please find the dump attached.


Georgi Petrov
BI Architect

georgi.petrov@urbanise.com
MN: +359 893 561148
Skype: gogosoft1
www.urbanise.com
[image: Urbanise]

**Comment by serge-rider** [comment]
GitHub doesn't understand email attachments - you need to drag-n-drop it directly in GitHub comment.

**Comment by gogosofta** [comment]
Sorry.  Updated the post above.
Cleaned my signature from the email replies also.

**Comment by serge-rider** [comment]
Thanks. Now I have a clue.

**Comment by gogosofta** [comment]
I'm glad I could help. This is my favourite DB tool :)

**Comment by gogosofta** [comment]
For the record - also hangs (for the same time) on localhost DB (same one).

Here's the dump:

[thread-dump.txt](https://github.com/serge-rider/dbeaver/files/1033540/thread-dump.txt)

**Comment by serge-rider** [comment]
You can try the fix in EA version: http://dbeaver.jkiss.org/files/ea/

**Comment by gogosofta** [comment]
Respect !
The issue is gone now. Well done. Thanks a lot!

**Comment by serge-rider** [comment]
Great
