### ISSUE TITLE
"JVM terminated. Exit code=1" on long operation when tooltip appear.

### ISSUE THREAD

**Issue by gavenkoa** [serge-rider/dbeaver#170]
I fill table with synthetic data via procedure (mariadb):

    CREATE TABLE item (
      id INT,
      title VARCHAR(80),
      content TEXT,
      PRIMARY KEY (id)
    );

    CREATE PROCEDURE insert_test_data(IN lim INT)
    BEGIN
      DECLARE i INT DEFAULT 0;
      WHILE i < lim DO
        IF i % 1000 = 0 THEN
          COMMIT;
          START TRANSACTION;
        END IF;
        INSERT INTO item (id, title, content) values (i, CONCAT('Title ', i), CONCAT('Long body ', i));
        SET i = i + 1;
      END WHILE;
      COMMIT;
    END;

    CALL insert_test_data(1000*1000);

After 90 sec I get yellow tooltip about operation finishing and DBeaver crash with message box: 
**JVM terminated. Exit code=1**

If operation take less time tooltip isn't showed and DBeaver stays live.

I use official Debian opendjk package

    bash# java -version
    java version "1.7.0_91"
    OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1)
    OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

with Fvwm window manager.

**Comment by gavenkoa** [comment]
I have no desktop try manager application installed.

**Comment by serge-rider** [comment]
Most likely this is result of problems with taskbar notifier. It doesn't function properly on some systems. And it is disabled on MacOS, this is the first time when we have report about problems on Linux. Maybe this is because of Fvwm.
Workaround: disable taskbar notifications (Preferences->Common->Enable long-time operations notification)

**Comment by gavenkoa** [comment]
I use GNOME notification-daemon for notification pop-ups, in my ~/.xinitrc:

    notfy_daemon_cmd=/usr/lib/notification-daemon/notification-daemon
    if [[ -x $notfy_daemon_cmd ]]; then
      $notfy_daemon_cmd &
    fi

and stalonetray for tray, in my ~/.fvwm/config

    AddToFunc InitFunction
    + I Exec  exec stalonetray --window-strut none --grow-gravity S --icon-gravity N --geometry 1x16-$((130+92+24))+0 

I am not sure which of those involved into problem.

Thanks for support!

**Comment by serge-rider** [comment]
Can't be fixed until this issue will be fixed in Eclipse.
The only workaround is to disable taskbar notification.
