### ISSUE TITLE
Decimal separator not working properly

### ISSUE THREAD

**Issue by aguayoff** [serge-rider/dbeaver#1701]
I need to be able to change '.' for ',' as my default decimal separator when copying query results from dbeaver, but although the option is present in the "Data Format" preference tab, it doesn't seem to have an effect on the data copied to the clipboard.

Is there a way to achieve this?
Thank you!

**Comment by serge-rider** [comment]
You can use Advanced Copy (ctrl+shift+c or from context menu). There you can choose target format (Display format is what you need).

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed.

**Comment by serge-rider** [comment]
@IuVI could you clarify this a bit.

What is the actual problem?
Why copy/paste isn't working in your case? Please provide some samples.

If you need to change decimal separator char then you can change locale on Data format pref page.
If you need to use ANSI separator - just use simple copy or copy in database native format.

**Comment by IuVI** [comment]
![2gh](https://user-images.githubusercontent.com/13721680/34404648-96a642da-ebb7-11e7-9eee-62d2d5cb584d.jpg)
See the difference?
Same happens when you try to export table from Oracle to CSV using DBeaver. It keeps display formats so that data from the exported CSV become unreadable for other applications.

**Comment by serge-rider** [comment]
Looks like problem with grouping. In Russian locale thousands are divided by "space"(it is actually a special unicode character). You can disable grouping in Data Format prefs (for  numbers).

**Comment by IuVI** [comment]
Well. yeah. It's not actually spaces, it's special characters. And yeah I can solve the problem with "spaces"
by changing Data Format prefs. Still the problem with ',' and '.' as fractional part separator remains during copypaste and it can't be solved in the DBmanager.
There's a lot of other issues relating to the difference in formatting comparing to default DBmanagers, but it's not related directly to this topic.
I see you have many issues to resolve next year.
Thanks for help! Merry Christmas and happy NY to the DBeaver devteam!

**Comment by serge-rider** [comment]
Thank you!

Please feel free to create new tickets for other formatting issues in DBeaver. If some of them can be fixed easily then this fix will be included in the nearest version. 

Most of our existing open tickets are relatively complex - that's why we have so many of them.
