### ISSUE TITLE
Create new Database Project not function...

### ISSUE THREAD

**Issue by undertherainITA** [serge-rider/dbeaver#1702]
Hi.
With wizard, create new Database Project not function.
The dialog prompts me to press the next key twice and then remains empty with the next and finish keys disabled.
Even copying and pasting of old database project does not work!
I have the latest version, Community Edition 4.0.7.
I do not know what version does not work.
Thanks!!!
Ciao... ;)

**Comment by serge-rider** [comment]
Thanks for report (it is a bug in 4.0.7).

**Comment by undertherainITA** [comment]
Thanks Serge for your speed.
Would you like some developers like you in my company... ;)
Thanks.
Ciao... ;)

**Comment by undertherainITA** [comment]
Thanks for changing the milestone from 4.1.0 to 4.0.8... ;)
