### ISSUE TITLE
Creating Index with Postgresql Quoted column name fails

### ISSUE THREAD

**Issue by leonibr** [serge-rider/dbeaver#1704]
## Version 4.0.7

when creating in index throw the interface before click 'Persist' button it generates a wrong sql statement

`CREATE INDEX tablename_columnname_idx ON schema."TableName" (ColumnName) ;`

when column names are capitalized should be 

`CREATE INDEX tablename_columnname_idx ON schema."TableName" ("ColumnName") ;`

**Comment by serge-rider** [comment]
Thanks for report
