### ISSUE TITLE
Run scripts transactionally

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1706]
I am connecting to a postgres database. Changing names on columns of views will not be permitted unless the view is first dropped. For this reason I do a script where the first commande is drop and the second is create. The problem occurs when there is an error in the create command. Then the drop part of the script is excuted but not the create, meaning the view is erased. 

I would like to run the script transactionally so that neither command are excuted if an error occurs. Is there such a feature or could it be added? As a reference in PgAdminIII the transactional behaviour works by default so the above described does not happen.

**Comment by serge-rider** [comment]
You can just switch into transactional mode (in the main toolbar/menu).
Isn't this what you need? Or do you mean alter scripts which DBeaver generates on object change?

**Comment by TrampolineMan** [comment]
I see the option in the toolbar but I am unable to find a reference to what each of the options mean. What I am looking to do is to make sure two sql commands, a drop command and a subsequent create command are only executed (both of them) when no errors occur in either. Does any of the existing options correspond to this?

**Comment by serge-rider** [comment]
Just switch to manual commit mode.
Then execute DROP and then CREATE. 
If CREATE fails you can perform Rollback. And then retry DROP+CREATE.

Note: this will work in PG but not in Oracle and some other databases (because DDL isn't transactional there).

**Comment by TrampolineMan** [comment]
Thanks. Will try this!
