### ISSUE TITLE
Import data from file directly into table

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1707]
I wish to import data from a text/csv file into a table. When I use the import feature I am asked where to store the imported data. The browser only allows me to choose a project folder. After finnishing the file(s)appears in the project pane. What I would like to do instead is add the data directly to the table. 

Even better would be if I could right click on a table, select import and select the source from a file. Currently this command only seems to allow for importing from other tables in databases. Reference: I would like to import function to work similar to how import functions in PgAdminIII.

**Comment by serge-rider** [comment]
Duplicate of #130

**Comment by shahinchudesara** [comment]
Still, i can't see this feature in DBeaver 5.0.0, is this feature implemented?

**Comment by p91paul** [comment]
this was closed as duplicate, #130 will be closed when this is implemented.
