### ISSUE TITLE
View all result rows immediately when executing script

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1708]
Currently when I execute a query I see the first 200 result rows. Many times I would like to see all rows immediately.  I then have to execute the query twice, once for the first 200 rows and then for all rows using a separate button.

I don't want to change the default number of rows, just being able to select to retreive 200 from case to case without multiple button presses or time loss.

**Comment by serge-rider** [comment]
I don't see how can be solved in UI.
Some tables have too many rows so it can't be done as default behavior. Now You need to click just one extra button (fetch all rows) - how can this be done easier?

**Comment by TrampolineMan** [comment]
It does not need to be easier, it is just that some queries (especially nested queries that take a long time to retreive any result at all) will take twice the time in the end allthough I wanted all rows from beginning. The ability to choose 200 or all rows directly would cut time in half for thoose when needed to retreive all rows. If pushing all rows from the beginnning may casue a crash then I am willing to take the risk (after all the current warning when pressing the current button is good enough guard against this).

**Comment by serge-rider** [comment]
Ok. But how do you see this in UI?
Extra execute action?

**Comment by TrampolineMan** [comment]
It could be a separate execute button or a switch setting like the commit button in the toolbar.

**Comment by serge-rider** [comment]
Select All Rows command will be added in the next version.

**Comment by gavenkoa** [comment]
`Ctrl+Alt+Shift+A` or right click menu: Execute => Select all rows.

**Comment by popovserhii** [comment]
I accidentally click "No" in "Do you want to fetch all rows" popup and now don't know how to change this behaviour. Does anybody know where these default settings persist or how to restore the default behaviour of this popup?

**Comment by ks-2097** [comment]
@popovserhii I have exactly the same issue. Can't get the original behaviour back. Now the button jsut doesn't do anything.
Did you solv it?

**Comment by uslss** [comment]
it could be changed in Preferences
![image](https://user-images.githubusercontent.com/31996417/146361565-ad2d481d-c65a-49dd-bbac-fc52c1eb2bc1.png)

**Comment by ks-2097** [comment]
Awesome thanks so much!

**Comment by popovserhii** [comment]
@uslss Great! Exactly what I was looking for.

**Comment by bricsi22** [comment]
Thanks for adding the feature it's really useful :)

**Comment by stevleibelt** [comment]
Finally the solution from @uslss answered my search question "show total row count of sql statement like in pgAdmin".
Thank you very much, I hope my written down search term will help someone in the future, at least my future me :-).

**Comment by Git-happiness** [comment]
I want to be able to see only the rows updated/inserted after an SQL script run. I can't figure out if this is the same issue. Only thing I get after running a script is the "rows affected" count. I want to see the actual rows.

**Comment by lazyboy0172** [comment]
is there a similar function to select all rows on a script? right now I have to ctrl+a to select the entire script, then ctrl+shift+alt+a to retrieve all rows. just checking if there's a 1-step solution I've overlooked.
