### ISSUE TITLE
Configure "NULL" output in export resultset

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1709]
When I export resultset data null values are shown as "[NULL]" in the output file. I wish for the output format to be configurable so that I can output i.e. no data instead of "[NULL]".

**Comment by serge-rider** [comment]
If you mean CSV export then this is already implemented ("NULL string" option on Export Settings page of wizard).

**Comment by TrampolineMan** [comment]
Sorry for poor explanation.
Your suggestion solves the problem for export, but same feature would also be useful for copy / pasting. Would it be possible to set the appearance directly in the table? E.g. "[NULL]" -> "" (empty string)?

**Comment by serge-rider** [comment]
You can use Advanced Copy + value format "Editable".
