### ISSUE TITLE
Running two queries on the same connection crushes the client

### ISSUE THREAD

**Issue by sudila** [serge-rider/dbeaver#1715]
Hi
I have Impala DB and using the last version of Dbeaver 4.0.7 on Win 7. after this update running two queries crashes the client, it goes not responding.

**Comment by serge-rider** [comment]
Can't reproduce, maybe something is wrong with Impala driver.
Once client will hang please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump)  and post it here.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.

**Comment by sudila** [comment]
Hi,
I have upgraded the version, and the issue did not come back.

p.s. really like your product

**Comment by tati-kru** [comment]
@sudila great! thank you 👍
