### ISSUE TITLE
Automatically open connection

### ISSUE THREAD

**Issue by andyj513** [serge-rider/dbeaver#1718]
When I try to run a query against a DB that is not currently connected, DBeaver reports "Disconnected from database"?  Since, it clearly knows what the issue is, it would be better if it could prompt me if I want to open the connection (and if so, to connect, and then run the query).  But it would be even nicer if it would try to open the connection automatically (perhaps with an option, if not all users would benefit from this behavior).

**Comment by serge-rider** [comment]
![default](https://cloud.githubusercontent.com/assets/6398845/26599205/726511d6-4580-11e7-97b2-dbbd3d96d6a6.png)

**Comment by andyj513** [comment]
I tried this option.  Now, if the connection is closed and I try to execute a statement in a SQL Editor (associated with it), it DOES connect (and shows the table on the left, etc.) - but then DBeaver displays "Not connected to database", and does not execute the query.  But if I click Ctrl-Enter again, then the query does execute.  I was expecting the query to execute the first time (and not display this error).
