### ISSUE TITLE
Inplace editor not working with Cassandra (no unique key)

### ISSUE THREAD

**Issue by qixx811** [serge-rider/dbeaver#1719]
The inplace editor does not work with with Cassandra. While saving, it says that there is no unique key for the table "channel". Additionally, if I try to generate "SELECT by unique key" or "DELETE by unique key", the WHERE expression is empty.
![image](https://cloud.githubusercontent.com/assets/10089119/26593311/ec5f8be6-4563-11e7-825f-1cf80a11f715.png)
![image](https://cloud.githubusercontent.com/assets/10089119/26593329/f98be7e2-4563-11e7-9218-3cc25bb02f92.png)

Here you can see, that the primary key is recognized in the table info:
![image](https://cloud.githubusercontent.com/assets/10089119/26593358/0e860844-4564-11e7-8812-1de446167b80.png)

**Comment by gogosofta** [comment]
The inline editor doesn't work for PG and MySQL tables either. May be a general bug.

**Comment by serge-rider** [comment]
@gogosofta please provide more details/steps to reproduce. 
Generally inline editors work fine.

**Comment by gogosofta** [comment]
mm.. I had the option "Read table metadata" turned off in regard to the auto completion bug that prevented inline editor from editing (no warnings though), but still it accepted new record and pasting content, it also accepted a single character typing in the edited field but could not post the record. I figured that and ticked the checkbox on - now it's ok. Maybe editing should be disabled when the option is off - not sure. 
![image](https://user-images.githubusercontent.com/13131218/27329634-01c4d2dc-55bf-11e7-9b33-81e0212d0195.png)

**Comment by serge-rider** [comment]
Ok

**Comment by qixx811** [comment]
I still have the same problems as in the result after querying. Do I have to configure sth.?

After double clicking on a table in "Database Navigator" and switching to "Data" tab, it seems to work this way: disable "Always use all columns as key" in preferences (Database -> Result Sets) and  select the keys after changing and saving data

I'm using the enterprise version of DBeaver.

**Comment by serge-rider** [comment]
EE 4.1 wasn't yet released, should happen till the end of July.
