### ISSUE TITLE
Export to SQL inserts doesn't work for TEXT or VARCHAR columns with backslashes in it.

### ISSUE THREAD

**Issue by zymurgic** [serge-rider/dbeaver#1720]
Export to SQL inserts doesn't work for TEXT or VARCHAR columns with backslashes in it.

At least, with Mysql, backslashes need to be escaped.

~~~~
CREATE TABLE `test_table` (
  `name` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
~~~~

-- Now populate it with some dubious data

~~~~
INSERT INTO testdb.test_table (name) VALUES 
('Tam o''Shanter')
,('''s Hertogenbosch')
,('Billy o''Reilly')
,('Some random string with backslashes and apostrophes \\''')
;
COMMIT;
~~~~

~~~~
MySQL [testdb]> select * from test_table;
+---------------------------------------------------------+
| name                                                    |
+---------------------------------------------------------+
| Tam o'Shanter                                           |
| 's Hertogenbosch                                        |
| Billy o'Reilly                                          |
| Some random string with backslashes and apostrophes \'  |
+---------------------------------------------------------+
4 rows in set (0.03 sec)
~~~~

Now using DBeaver, Export Table Data / Export to SQL INSERT statements
accept defaults for everything

Observe the difference between the generated SQL inserts, and the required SQL (above). The output doesn't escape the backslashes, which will lead to SQL errors when you try to run them.

Backslashes need escaping in mysql / mariadb.

Other database engines will vary, but most treat backslashes as something that need escaping. Oracle PL/SQL requires backslashes escaping too.

**Comment by serge-rider** [comment]
PostgreSQL doesn't support that. I think this must be database-specific.
