### ISSUE TITLE
Unable to insert new row in newly created table

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1722]
When creating a new table and after populating with one or more columns I go to the data editor. I press the new row button but nothing happens.

**Comment by serge-rider** [comment]
This is a bug in 4.0.8 (side-effect of multiple rows insertion fix). First insert fails if table is empty.

Workaround: insert first row using "insert before" setting. You can change this behavior in preferences or you can make first row insert by pressing Shift key and clicking on green plus button.
After table has at least one row normal insert will work ok.
