### ISSUE TITLE
Pasting quoted strings

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1723]
There is an issue with quotes dissapearing when pasting certain strings in the SQL editor.
Example:
If I copy and paste the string "sdfd ssd" then no problem.
If I copy and paste "sdfd ssd " then the quotes dissapear.

dbeaver version is 4.0.8
os: windows 7
os language: US English

**Comment by TrampolineMan** [comment]
I noted one more thing that might help in debugging:
In some case it is possible to restore quotes by pressing Ctrl+Z when pasting as described above - yet again other cases not. I have not been able to figure out why sometimes and sometimes not.
Does it mean the removal of quotes is an additional step in the undo action queue?

**Comment by serge-rider** [comment]
This is a special feature. Useful if you copying SQL from some source code. DBeaver strips code formatting.
You can disable this by turning option Preferences-SQL editor->SQL Formatting->Extract SQL from source code off.
Ctrl-Z (undo) reverts source code extraction as well.

**Comment by TrampolineMan** [comment]
Thanks for the explanation.
Your instructions solved the issue.

**Comment by florisfo** [comment]
> This is a special feature. Useful if you copying SQL from some source code. DBeaver strips code formatting.
> You can disable this by turning option Preferences-SQL editor->SQL Formatting->Extract SQL from source code off.
> Ctrl-Z (undo) reverts source code extraction as well.

For DBeaver 7.0.3 this option is at Preferences-SQL editor->SQL Completion->Extract SQL from source code off.
