### ISSUE TITLE
Java compatability problem/ini file edit after installation

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1724]
When installing a new dbeaver version from the zip archives Java is initially not recognized. 
![java](https://cloud.githubusercontent.com/assets/29008373/26610962/da6b80ac-45e5-11e7-9410-3cd66a804572.png)
This error started when switching from Java 1.8.121 to 1.8.131. The version of dbeaver used to test this was 4.07 and 4.08 but it seems the actual problem happened during switch of Java not during dbeaver reinstall.

The temporary solution I found was to inser the following line at the top of the dbeaver.ini file. "-vm C:\Program Files\Java\jre1.8.0_131\bin\javaw.exe". The problem is then that this has to be done every time I reinstall dbeaver for it to run at all.

Best thing would be if the change in Java behavriour could be identified and dbeaver can run out of the box without additional ini changes. If instead the ini has to be updated, then ideas for solutions include to move settings to the Registry or to change location of ini file to separate folder.

**Comment by serge-rider** [comment]
I can't reproduce that. Will test on another machine with latest Java.

BTW I'd recommend to use Windows installer instead of zip archive. It is self-sufficient and has smaller size.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
