### ISSUE TITLE
Working Directory field in Shell command configuration not working

### ISSUE THREAD

**Issue by BriceJamin** [serge-rider/dbeaver#1725]
Hi,

DBeaver 4.0.8

My working dir :
```
bja@debian:~/Documents/DBeaver/test$ pwd -P
/home/bja/Documents/DBeaver/test
bja@debian:~/Documents/DBeaver/test$ ls -l
total 4
-rwxr-xr-x 1 bja bja 24 mai   31 08:45 test.bash
```
test.bash (file creator) :
```
#!/bin/bash
touch test
```
Configuration :
![workingdir1](https://cloud.githubusercontent.com/assets/3600741/26619763/2c0e4ecc-45e0-11e7-81b4-3db3d797eb9e.png)

Click on test connection button
No file creation :
```
bja@debian:~/Documents/DBeaver/test$ l
total 4
-rwxr-xr-x 1 bja bja 74 mai   31 08:55 test.bash
bja@debian:~/Documents/DBeaver/test$
```

**Comment by serge-rider** [comment]
Thanks for report.

Actually working directory value is saved but only if you click Ok in connection editor dialog.
