### ISSUE TITLE
Hellow There, 2 little problems

### ISSUE THREAD

**Issue by UltraBober** [serge-rider/dbeaver#1727]
1) Your DBeaver since 4.06 version has lost an ability to delete records directly from grid in tables, wich does't had primary key specified.

2) When i run 30 small SQL scrypts in SQL editor simultaneously, after running i only get one report about changing rows of 1-st numbered scrypt.
 Is it possible to make all 30 reports visible=true in Statistics window below?

PS: I'm Working From DBeaver with PostgreSQL

**Comment by kyleflan** [comment]
It's not _my_ DBeaver, but maybe I can help.

1. If you click on the settings cog in the toolbar below the results pane, there should be an option to define a virtual unique key. Make sure the columns you select as being the key are actually unique; otherwise you'll end up with other rows being deleted.

2. Highlight the scripts and type Ctrl + Alt + X to generate a results tab for each query.

**Comment by UltraBober** [comment]
Thx a lot, now it works good. :)

**Comment by theHilikus** [comment]
The Virtual Unique Key solution seems like a workaround to me. I think there's a real bug still there. I have a cassandra DB where dbeaver can detect correctly all the keys: primary and partition keys. Surely with this info the unique key of the table is known. Am I missing something? the error I get is "there is no physical unique key defined for XXX". It does give me the option to define a "custom unique key" which gets me to the same dialog as @kyleflan mentioned but with hundreds of tables this workaround is unmanageable

**Comment by phheine** [comment]
The Virtual Unique Key option is greyed out for me.

What other options do I have?

**Comment by serge-rider** [comment]
@phheine It is greyed if table already has physical unique key. You can try "Define dictionary". But it is also disabled for custom SQL queries.

@theHilikus Can't reproduce. If this is Cassandra specific - could you create a separate bug report?
