### ISSUE TITLE
Hello,for Oracle data display ,the raw data type display was like messy code.

### ISSUE THREAD

**Issue by yxdxx** [serge-rider/dbeaver#1728]
Hello,for Oracle data display ,the raw data type display was like messy code.

**Comment by serge-rider** [comment]
Duplicate of #1672

**Comment by SeabiscuitCZX** [comment]
Preferences -> Result Sets -> Editors now, then change "binary data formatter" to "Hex"

**Comment by ovidiugabriel** [comment]
This changed once again on 7.3 it is in Editors > Data Editor > Binary Editors
