### ISSUE TITLE
Very slow metadata query while querying Vertica 7.1.2

### ISSUE THREAD

**Issue by mverrilli** [serge-rider/dbeaver#173]
I'm using DBeaver 3.4.5, Vertica 7.1.2 and the 7.1.2 jdbc driver.

I have a simple SELECT COUNT(*) query that takes much longer in DBeaver than in vsql. When I look at Query Manager and watch it run I notice: 

1. The time spent is waiting on "Load Columns" on the Metadata connection. 
2. The Duration seems to lie. It claims 2ms, however I watched it run for almost 3 minutes while the original query finished in only 20 seconds. 

Are there any ways of digging further into this or disabling the metadata queries? 

Thanks!

**Comment by serge-rider** [comment]
This should happen only when DBeaver executes this query first time.
In opposite to vsql DBeaver needs to read and cache metadata (table, columns, data types, etc). Usually metadata caching works very fast (a few seconds maximum) but in some cases it may take much time.
As far as I know Vertica is a column oriented database. For big/old tables all columns reading could be an expensive operation. I'm not sure is it possible to improve this operation performance thru JDBC..

**Comment by serge-rider** [comment]
Could you test v3.6.8.
There was a few fixes in data reading function.

**Comment by mverrilli** [comment]
Will do today, thanks!

**Comment by mverrilli** [comment]
Wow... the initial metadata retrieval seems much faster now.  So definitely an improvement there.  

For some reason I can't find the option to enable all the steps in the execution log anymore (probably because I haven't looked at it in awhile, and just can't remember where to find it).  

The load columns still holds things up after the query execution (but I don't have the log to say how much, I'll need to experiment more to see by how much).  However it does seem to reuse this information on the second execution now. 

I'll be using this all week with Vertica, so I'll let you know if I find anything interesting.

**Comment by mverrilli** [comment]
Ok, I am closing this out, it definitely looks far better now. Thanks!  

(I'm opening a new one for a different issue though if it doesn't exist, sorry)
