### ISSUE TITLE
Can't edit float values

### ISSUE THREAD

**Issue by bellyapple** [serge-rider/dbeaver#1731]
Hi,

I cannot edit values of type float. The field seems to be read-only while other fields on the same row are editable.

I asked Google, but he didn't help me this time. This issue tracker either. Maybe I don't use the good keywords. 
Can someone help me to edit this kind of values ? 

Way to reproduce : 
CREATE TABLE test_float(
	id INT AUTO_INCREMENT,
	val FLOAT,
	PRIMARY KEY (id)
);
insert into test_float (val) values(1.1), (1.3), (10.5), (11);
select * from test_float;

Then try to edit any value of the column "val".

![image](https://cloud.githubusercontent.com/assets/29126575/26688596/60db7a30-46f3-11e7-80dd-cce400f8a98f.png)

**Comment by kyleflan** [comment]
I can confirm the same issue with Postgres (in fact, I cannot edit int or text values either using the results pane generated from a SELECT query). However, if I navigate to the table in the Database Navigator and open it, I can edit the table that way. Additionally, explicit UPDATE statements work as well. 

Works as expected for SQL Server.

**Comment by bellyapple** [comment]
I forgot to mention that I'm using MySQL.

**Comment by serge-rider** [comment]
This is a bug in MySQL custom queries edit (float data type mapping was incorrect).
Thanks for report.

**Comment by serge-rider** [comment]
@kyleflan I can't reproduce this problem in PG. Please create separate bug report for that.

**Comment by kyleflan** [comment]
@serge-rider will do. I'll put together the reproduction steps and open a new issue.

**Comment by kyleflan** [comment]
@serge-rider please disregard. I was using 4.0.6 in Eclipse when testing. No issues in 4.0.8!
