### ISSUE TITLE
Updating rows in Data View then changing sort order causes changes to be lost without warning

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1733]
I'm using DBeaver CE 4.0.7. Yesterday I was updating some rows in Data View and then decided to change the sort order so as to make it easier to find the values I wanted to update. After the sort I noticed that all of my changes were lost, which is understandable, but would it be possible to warn the user that this would happen on changing the sort order when the view is 'dirty' (has unsaved changes)?

**Comment by serge-rider** [comment]
Yes, DBeaver should show confirmation before changes discarding.

**Comment by serge-rider** [comment]
4.1 should show such confirmation. If not - check Preferences->General->Confirmations options.
