### ISSUE TITLE
Cursor should follow the find and replace match instead of staying behind at the starting point

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1734]
After searching for "timestamp", I would expect the cursor to stop at "timestamp" instead of cell A1. If a match is found at cell Z999, hitting the keyboard arrows keys would cause the tabular view to go back near cell A1, which is not I would expect.

![image](https://cloud.githubusercontent.com/assets/25423046/26706977/1d229c52-4774-11e7-82ba-d8b9184f8094.png)

**Comment by serge-rider** [comment]
Yep, its a bug.
