### ISSUE TITLE
Fetch cursor with PostgreSQL does not display result

### ISSUE THREAD

**Issue by JohnnyBGood82** [serge-rider/dbeaver#1735]
In SQL shell or Squirrel, I do :
begin transaction;
select * from test();
fetch all cur;
commit;

And I get the result of a refcursor returned by test(). But with DBeaver 4.0.8 I only have the statistics information.
Did I have a wrong parameter ?

**Comment by serge-rider** [comment]
You could try to execute this a single query (select it and run with ctrl+enter).

**Comment by JohnnyBGood82** [comment]
I have to run it in a single query. Otherwise, the refcursor is lost.
But I think it's giving me the first line result because when I run only : 
select * from test();
fetch all cur;

I get the result of "select * from test();" which is not what I want

**Comment by serge-rider** [comment]
Could post DDL for this test procedure so I could reproduce the problem.

**Comment by JohnnyBGood82** [comment]
The function :

```
create function test()
returns refcursor
as $body$
declare
	mycurs refcursor = 'cur';
begin
	open mycurs for 
	select
		*
	from
	  	test_table;
	return mycurs;
end;
$body$ LANGUAGE plpgsql;
```

**Comment by serge-rider** [comment]
Yes, it is a bug (or a kind of misfunction) in DBeaver. In script mode it closes all cursors returned by script queries.
Will try to fix this in the next version.
