### ISSUE TITLE
Postgresql: sql error [42804] When saving the data of type xml

### ISSUE THREAD

**Issue by georaul** [serge-rider/dbeaver#1736]
SQL Error [42804]: ERROR: la columna «con_xml» es de tipo xml pero la expresión es de tipo text
  Hint: Necesitará reescribir la expresión o aplicarle una conversión de tipo.
  Position: 47
  org.postgresql.util.PSQLException: ERROR: la columna «con_xml» es de tipo xml pero la expresión es de tipo text
  Hint: Necesitará reescribir la expresión o aplicarle una conversión de tipo.
  Position: 47

**Comment by kyleflan** [comment]
You haven't described what you're trying to do. Are you making edits in the data grid and trying to save and commit them to a table? I don't think that's implemented in DBeaver yet.

**Comment by georaul** [comment]
Hello, the error happens when I edit the value of the xml data in a cell in the dbeaver program interface

**Comment by serge-rider** [comment]
Please post sample table DDL and INSERT.

**Comment by georaul** [comment]
DDL example:

CREATE TABLE table (
	id numeric NOT NULL,
	description varchar(150) NULL,
	data_xml xml NULL
) ;

When editing the content of "data_xml" column of the table in the tab Data within the value viewer, can't save, then generates the error. ALWAYS in graphic editor, no Insert nor update query.

**Comment by kyleflan** [comment]
Using the latest JDBC driver from Postgres (42.1.1), I'm receiving the same error as georaul (but in English). Here's some more information on the bug, as it relates to the JDBC driver and Postgres: https://github.com/pgjdbc/pgjdbc/issues/265 . However, changing the stringtype to unspecified in the driver settings did not correct the issue for me. 

> SQL Error [42804]: ERROR: column "xml_val" is of type xml but expression is of type text
>   Hint: You will need to rewrite or cast the expression.
>   Position: 38
>   org.postgresql.util.PSQLException: ERROR: column "xml_val" is of type xml but expression is of type text
>   Hint: You will need to rewrite or cast the expression.
>   Position: 38

DDL and Inserts:

```
CREATE TABLE test_xml(
	id serial primary key,
	txt_val text,
	xml_val xml
	);
INSERT INTO test_xml (txt_val, xml_val) VALUES ('<foo>bar</foo>', '<foo>bar</foo>');
INSERT INTO test_xml (txt_val, xml_val) VALUES ('<bar>foo</bar>', '<bar>foo</bar>');
```

Workaround:

***_Warning: the preferQueryMode parameter is specified to be used for debugging purposes only, so using this in production is not advised_** (https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PreferQueryMode.java)

Edit database connection and under driver properties, set preferQueryMode to simple.

![image](https://cloud.githubusercontent.com/assets/5608074/26798508/57b02338-49f6-11e7-9ff7-432676a8e067.png)

**Comment by georaul** [comment]
Dbeaver works Perfect with change!

thank you very much!

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed.
