### ISSUE TITLE
Do not show tables (postrgesql, mysql). Version 4.0.8

### ISSUE THREAD

**Issue by Kazun3500** [serge-rider/dbeaver#1739]
Do not show tables in Database Navigator
![viber image](https://cloud.githubusercontent.com/assets/13629272/26720917/8e186f72-4792-11e7-8802-2af8c9bd6c93.jpg)

**Comment by Kazun3500** [comment]
OS Linux Ubuntu 16.04
After the program was restarted, all the tables were displayed.

**Comment by serge-rider** [comment]
Can't say what was it.
Perhaps debug log could help.
