### ISSUE TITLE
Editor save error

### ISSUE THREAD

**Issue by raqua** [serge-rider/dbeaver#174]
Hi, 

I log in as an user that has no privilege to make DDL changes, create stored procedures and triggers in MySQL and I edit object, when I attempt to save it and commit changes, nothing is saved, but also no error information is given. After that, it is not possible to close the tab with edited object.

**Comment by raqua** [comment]
I spoke too soon, the same issue happens even when I am logged as root. I am trying to edit stored procedure (happened to me also when editing triggers).
I have to force kill DBeaver.

**Comment by serge-rider** [comment]
It is a bug in 3.5.9 version.
Thanks for report!
