### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by SergeyDjam** [serge-rider/dbeaver#1740]
Hello! This error on start program

`cd ~/rpmbuild/BUILD/dbeaver-4.0.8/product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86_64/dbeaver`
`./dbeaver
`
> !ENTRY org.eclipse.osgi 4 0 2017-06-02 17:45:27.397
> !MESSAGE Application error
> !STACK 1
> java.lang.RuntimeException: Application "org.jkiss.dbeaver.core.application.standalone" could not be found in the registry. The applications available are: org.eclipse.equinox.app.error, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor.
>         at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
>         at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
>         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
>         at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
>         at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
>         at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
> 

How i can fix it?

java-1.8.0-openjdk-headless-1.8.0.60-1.b16-rosa2014.1.x86_64
java-1.8.0-openjdk-1.8.0.60-1.b16-rosa2014.1.x86_64
java-1.8.0-openjdk-devel-1.8.0.60-1.b16-rosa2014.1.x86_64

maven-3.3.9-1-rosa2014.1.noarch

**Comment by serge-rider** [comment]
Well, probably something went wrong during build. Were there any warnings/errors?

BTW did you try to download prebuilt binaries?

**Comment by SergeyDjam** [comment]
/usr/lib/jvm/java-openjdk/bin/java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b16)
OpenJDK 64-Bit Server VM (build 25.60-b16, mixed mode)

mvn --version
Apache Maven 3.3.9 (NON-CANONICAL_2016-04-21T12:20:04Z_mockbuild; 2016-04-21T15:20:04+03:00)
Maven home: /usr/share/java/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.60.x86_64/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "4.9.20-nrj-desktop-1rosa-x86_64", arch: "amd64", family: "unix"

mvn package - no warnings/errors

**Comment by SergeyDjam** [comment]
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000095500000, 208142336, 0) failed; error='Невозможно выделить память' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 208142336 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/admin/rpmbuild/BUILD/dbeaver-4.0.8/hs_err_pid18725.log

**Comment by carlosspohr** [comment]
Hi @SergeyDjam ,

Have you tried run it with current standalone version (.zip) ?

**Comment by SergeyDjam** [comment]
dbeaver-4.0.8.tar.gz

https://github.com/serge-rider/dbeaver/archive/4.0.8.tar.gz

**Comment by carlosspohr** [comment]
Uhmm,

Eventually I got application error after build nightly releases, sometimes maven fails by unknown reasons, after rebuild/compile it just works.

Did you install rpm or zip of that build ?

**Comment by serge-rider** [comment]
Please try to run prebuilt version (https://github.com/serge-rider/dbeaver/releases)

**Comment by SergeyDjam** [comment]
Ok
1. i download https://github.com/serge-rider/dbeaver/releases/download/4.0.8/dbeaver-ce-4.0.8-linux.gtk.x86_64.tar.gz
wget https://github.com/serge-rider/dbeaver/releases/download/4.0.8/dbeaver-ce-4.0.8-linux.gtk.x86_64.tar.gz
2. unpack dbeaver-ce-4.0.8-linux.gtk.x86_64.tar.gz
3. start dbeaver 
./dbeaver
4. result:

> An error has occurred. See the log file
> /home/admin/rpmbuild/BUILD/dbeaver/configuration/1496918873173.log.

**Comment by serge-rider** [comment]
Well, it complains that you don't have Java 1.8+. Maybe it was somehow corrupted (sometimes it happens with OpenJDK after numerous version upgrades/downgrades).
Also `Java version: 1.8.0_60, vendor: Oracle Corporation` conflicts with `OpenJDK Runtime Environment`. These are different JDKs.

Run `java -version` in dbeaver directory.

**Comment by contentfree** [comment]
First time user: Getting this crash at start-up using the current Mac installer downloaded from the web site (CE 4.1.0). 

(I'm on Java 7)

**Comment by serge-rider** [comment]
DBeaver requires Java 8 (you need to setup JDK if you are on Mac)
