### ISSUE TITLE
Column / block text selection in SQL editor

### ISSUE THREAD

**Issue by sdpurohit** [serge-rider/dbeaver#1741]
Is there a way to select text as columns in the SQL editor?  If not, can this be added?

On my Mac, in applications that support it such as bbedit, option-clicking will allow column selection.

**Comment by kyleflan** [comment]
Alt+Command+A on a Mac (Alt+Shift+A on Win/Linux) will put DBeaver into block selection mode. Then you can select a block/column selection. Same key combo to go back to normal selection mode.

**Comment by sdpurohit** [comment]
Excellent, thanks!

It would be nice if option-click was also supported since that seems to be a common way to do this.  Although I assume this would require support in Eclipse.

**Comment by iron0012** [comment]
On my mac keyboard, the block selection toggle shortcut seems to be Option+Command+A.

**Comment by bomuva** [comment]
The absence of the generally accepted classic way of block text selection in the editor (press Alt + select text) is a very annoying circumstance, this is perhaps the biggest drawback of this application

**Comment by depler** [comment]
@bomuva totally agree, that is insane to click `Alt+Shift+A` every time you need vertical selection. Please give us ability to use `Alt + A` like it is implemented in `Notepad++`

**Comment by majkinetor** [comment]
Yeah, its cumbersome, it looks like editor is changed and in my case even zoom level is not obayed.

Vscode ALT SHIFT + mouse selection is how it should be done.
