### ISSUE TITLE
Apache Drill JDBC URL need /<directory>/<cluster ID>

### ISSUE THREAD

**Issue by Cye3s** [serge-rider/dbeaver#1743]
directory is the Drill directory in ZooKeeper, which by default is /Drill. Optional.
cluster ID is drillbits1 by default. If the default has changed, determine the cluster ID and use it. Optional.

If cluster ID is changed, dbeaver has no way to set directory and cluster ID,  error when connection:

Unexpected driver error occurred while connecting to database
  java.lang.IllegalStateException: No active Drillbit endpoint found from ZooKeeper. Check connection parameters?

This is my JDBC URL works on DbVisualizer:
jdbc:drill:zk=192.168.1.210,192.168.1.211,192.168.1.213:2181/drill/mydrillcluster

**Comment by serge-rider** [comment]
What if you enter `192.168.1.210,192.168.1.211,192.168.1.213:2181/drill/mydrillcluster` in the "Host" field?

If it doesn't work - could you post an example of the correct URL pattern.

**Comment by Cye3s** [comment]
If I enter 192.168.1.210,192.168.1.211,192.168.1.213:2181/drill/mydrillcluster in the "Host" field, the URL will turn to:
jdbc:drill:zk=192.168.1.210,192.168.1.211,192.168.1.213:2181/drill/mydrillcluster:2181

Doesn't work.

Drill URL pattern:
`jdbc:drill:drillbit=<node name>[:<port>][,<node name2>[:<port>]/<directory>/<cluster ID>[schema=<storage plugin>]`
And JDBC Docs on Apache Drill website:
http://drill.apache.org/docs/using-the-jdbc-driver/

**Comment by serge-rider** [comment]
I'll fix Drill URL template so it will allow multiple nodes config.
In DBeaver notation it will be `jdbc:drill:zk={host}/{server}[;schema={database}]` (you can change it in Drill driver settings)
