### ISSUE TITLE
Change background colour

### ISSUE THREAD

**Issue by carlosherranz** [serge-rider/dbeaver#1746]
Is there anyway to change the cell background colour in the result set where  the cursor is positioned? 
Sometimes is difficult to see the cell content (white,over background light blue)

**Comment by kyleflan** [comment]
Yes. Preferences -> General -> Appearance -> Colors and Fonts -> Database Query Results -> Selection Background

Click "Edit.." and choose a new color.

**Comment by carlosherranz** [comment]
Thak you, I've tried, but doesn't work.

**Comment by kyleflan** [comment]
Can you send a screenshot of what you're trying to accomplish?

**Comment by carlosherranz** [comment]
Here you have:
![preferences](https://user-images.githubusercontent.com/28946478/27024176-d8e55022-4f55-11e7-9967-cd7b8c27a0ba.png)

**Comment by kyleflan** [comment]
Hmm, this looks like a bug then. Not working for me either in 4.0.8.

The following config settings are made in org.eclipse.ui.workbench.prefs after changing via preferences, but are not reflected in the results set grid:

```
...
org.jkiss.dbeaver.sql.resultset.color.selection.background=255,18,0
org.jkiss.dbeaver.sql.resultset.color.selection.foreground=48,230,0
...
```

**Comment by carlosherranz** [comment]
Yes, I think so too.

**Comment by rythym05** [comment]
I was struggling for long trying to change around all the colors to see which option would change the cell color. The default blue makes the cells unreadable. Default should be a light gray.

**Comment by serge-rider** [comment]
Yes, it is a bug in the spreadsheet renderer.
