### ISSUE TITLE
Can't add data in MySQL via data-tab

### ISSUE THREAD

**Issue by digiuser** [serge-rider/dbeaver#1747]
If a new table (INNODB) is added and I try to add a new line nothing happens. With 4.0.7 everything is working fine! 4.0.8 isn't working.
Working on Ubuntu x64

**Comment by kyleflan** [comment]
This is a bug, see here: https://github.com/serge-rider/dbeaver/issues/1722 

From @serge-rider: 

> Workaround: insert first row using "insert before" setting. You can change this behavior in preferences or you can make first row insert by pressing Shift key and clicking on green plus button.
> After table has at least one row normal insert will work ok.
