### ISSUE TITLE
Bug: Cannot filter results by column alias

### ISSUE THREAD

**Issue by encynator** [serge-rider/dbeaver#1748]
It is not possible to filter results using column alias used in select.

**Reproduction scenario:**
1. Perform select where column has alias within select over Oracle DB, eg.:
   select product_id, technical_status **as tech_stat** from BA.PRODUCT;

2. Try to filter result using column alias instead (tech_stat = 'A') of it's name -> ORA-00904 - see attached picture
It works if real column name is used (technical_status = 'A') -> Result correctly filtered

**Version:**
Community version 4.0.8 with builtin Java

**Expected behavior:**
DBeaver either suggest column name in auto completion, but more likely it should be able to filter using column alias.
As it would not be really comfortable to use real column name within complicated selects.

**As you can see on attached picture:**
1. On auto-complete request DBeaver suggests alias
2. Once aliased used, it throws ORA-00904
3. If real name is used, DBeaver successfully filters results

![dbeaver_filter_bug](https://user-images.githubusercontent.com/11492235/26919434-fa207532-4c35-11e7-9239-bebaa63a4d88.png)

**Comment by serge-rider** [comment]
To perform filter DBeaver executes SQL query. In standard SQL you can't use column alias to filter.
But you can try to use nested selects:
```sql
select * from
(select product_id, technical_status as tech_stat from BA.PRODUCT) x
```
In this case filtering and ordering will work fine with aliases.

**Comment by encynator** [comment]
Alright, but in that case - DBeaver should auto-complete regular column name instead of alias, right?
Now auto-complete suggests alias name. It would be fine if DBeaver suggest real/full column name for auto-complete.

**Comment by serge-rider** [comment]
This is because database driver doesn't provide information about underlying column names. And this makes sense because you can use any SQL expression after alias. E.g.
```sql
select col1, col_num * 25 + 10 as some_alias from some_table
```
The only way to use it in filters is to use subselects.

**Comment by encynator** [comment]
I see. Alright then.

**Comment by esequiel-ferreira** [comment]
I see two solutions to this issues:

1.  check real column name by parsing the query
2.  filter local Resultset (optionally when original filtering fails)

If you guys face this feature as a "WHERE clause automation", the approach is to check real column name by parsing the original query would be more appropriate and the solution number 1 could be implemented.

However filtering local Resultset would be less disappointing. It would work as a post-execution filter, not as a WHERE clause automation.
