### ISSUE TITLE
result set data format locale can't be changed

### ISSUE THREAD

**Issue by oulenz** [serge-rider/dbeaver#1749]
Under window -> preferences -> database -> result sets -> data formats:
* I can't change locale (nothing happens when I try to write).
* When I change language and country to `en` and `GB`, this doesn't change the locale, and it doesn't stick when I click `apply` or `ok`. (The values are reset to what they were when I open the menu again.)
* With the format options for numbers, I can't change the decimal separator (from `,` to `.`).
* In addition, there is a different locale indicator at the bottom of the main DBeaver screen. It is different from the locale in the result sets menu. It appears to be set automatically from the operating system (I am using Kubuntu). Could you tell me whether this affects anything, and if yes, how it can be changed?

**Comment by aledeg** [comment]
I do have the same issue while using Ubuntu. I think it should be allowed to be able to choose the locale.
In my use case, my system is in English but I'd like to be able to get a different locale on each database I am connected to and not only the one of my machine.

**Comment by oulenz** [comment]
@serge-rider Problems 1--3 also apply when I try to change the connection-specific locale, which I accessed like you wrote. I can't get the result sets to use periods as decimal separators.

With respect to the locale indicator at the bottom, I gathered that it is the current system locale, but you haven't answered what this actually affects.

**Comment by serge-rider** [comment]
@oulenz Can't reproduce that:
![default](https://user-images.githubusercontent.com/6398845/27197920-de4c9e92-5218-11e7-8db7-57958d299ef8.png)

![default](https://user-images.githubusercontent.com/6398845/27197936-edd0fd72-5218-11e7-92b0-fc0e0cdb7aad.png)

In regards to system locale - it defines default data format locale. Also it can be used by 3rd party drivers.
You can change DBeaver system locale by running it with parameter -nl. E.g. `-nl en`.

**Comment by danielroehrig-mm** [comment]
Same problem here. No matter what I do, I can't change the locale to en_EN (it stays at de_DE) and decimal numbers are separated by a comma. I can start dbeaver with parameter -nl en but that only changes the system locale.

**Comment by oulenz** [comment]
@serge-rider Sorry, I was away. See the attached screenshot, if I change the language and country, the locale stays the same, and if I press OK, the changes don't stick.

![image](https://user-images.githubusercontent.com/13745168/28407662-3da1eeba-6d35-11e7-8084-9bd2c9fa6ddb.png)

**Comment by serge-rider** [comment]
I've reproduced this on Ubuntu

**Comment by serge-rider** [comment]
Fixed, thanks for detailed reports.
