### ISSUE TITLE
Can't edit Oracle 10g stored procedures

### ISSUE THREAD

**Issue by murilomentor** [serge-rider/dbeaver#175]
I can't edit Oracle 10g stored procedures on versions 3.5.7, 3.5.8 and 3.5.9 of DBeaver. It worked well with versions 3.5.3 and 3.5.6 that I was using previously.

Tested with:
* DBeaver x86_64 3.5.7, 3.5.8, 3.5.9 
* Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit
* ojdbc6, ojdbc14
* Windows 7 64bit

**Comment by serge-rider** [comment]
I think it is a duplicate #174. Although I though that this issue appeared only in 3.5.8.
However - could you check error log (main menu Window) for any errors during procedure save?

**Comment by murilomentor** [comment]
Actually it's not a "save" issue, I can't modify the content of the SQL editor. It's like the editor is locked, it shows the code, it shows a blinking cursor like it's expecting input, but doesn't let me change anything.

**Comment by murilomentor** [comment]
There's a recurring entry in the error log:

```
!ENTRY org.jkiss.dbeaver.model 2 0 2016-01-27 13:36:42.658
!MESSAGE Some project listeners are still register:     [org.jkiss.dbeaver.core.application.ApplicationWorkbenchWindowAdvisor@41241045]
!SESSION 2016-01-27 13:36:44.817 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_BR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2016-01-27 13:40:24.539
!MESSAGE Some project listeners are still register: [org.jkiss.dbeaver.core.application.ApplicationWorkbenchWindowAdvisor@4b4d8780]
```

**Comment by serge-rider** [comment]
Yep, it is a bug Oracle extension, was made during SQL editors refactoring in 3.5.7.
Fix will be added in the next version.
Thanks for report!

**Comment by murilomentor** [comment]
Thank YOU for being so awesome!
