### ISSUE TITLE
View total size of database on disk?

### ISSUE THREAD

**Issue by zejji** [serge-rider/dbeaver#1750]
Is it possible to quickly view the total size of a database on disk? When browsing a database, I can see the size of individual tables but, unless I am missing something, not the database as a whole.

If the option doesn't exist already, perhaps it could be added as an extra row in the 'Properties' tab when you select a database?

(I often find this information useful to have at a glance as it gives a rough idea of how long it is likely to take to export/import/back up a database. It would probably be even more helpful if this information, as well as the table size information, were also available in human-readable values - i.e. in megabytes/gigabytes - as well as just byte counts.)

**Comment by serge-rider** [comment]
What database?

**Comment by serge-rider** [comment]
IF you mean MySQL then there is no such information in database itself.

However you could try to use one of queries suggested here: https://dba.stackexchange.com/questions/14337/calculating-disk-space-usage-per-mysql-db

**Comment by zejji** [comment]
Thanks for the reply.

Yes, I was referring to MySQL. I do occasionally use custom queries to determine the size of a database, but the reason I raised this issue is that, as a former user of HeidiSQL, this is one of the features I miss the most.  (Although Heidi has far fewer features than DBeaver overall, I did find it useful that it is very easy to see the size of both (i) whole databases and (ii) individual tables at a glance.)

**Comment by serge-rider** [comment]
Ok, that's easy to implement:
![default](https://user-images.githubusercontent.com/6398845/27349181-21615c1a-55ff-11e7-95db-1aa643a6c507.png)

Will be included in the next version.

**Comment by zejji** [comment]
Hi - thanks for this!

Is there an option which needs to be enabled in order to see this value? I've updated to DBeaver 4.1.0 but can't see it - please see screenshot below:

![untitled](https://user-images.githubusercontent.com/3524191/27535392-8f4a7510-5a62-11e7-9c27-10a576dcf797.png)

**Comment by zejji** [comment]
I just tried force-reinstalling DBeaver (I'm using Chocolatey on Windows) and the property still does not appear. (I even tried manually deleting the C:\Program Files\DBeaver folder completely and running 'cup -fy dbeaver'.)

Perhaps it has something to do with the Chocolatey build?

**Comment by serge-rider** [comment]
Yes, most likely it is something in Chocolatey build. Honestly I don't know how it works.
You can check MySQL plugin version (main menu Help->Installation information->Plugins->org.jkiss.dbeaver.ext.mysql) - it has to be 2.1.45.

Also you could try to install on other computer. Maybe something is still cached locally. In this case we could create a bug report for Chocolatey maintainers.

**Comment by zejji** [comment]
By way of update, I've tried both (i) reinstalling Dbeaver outside of Chocolatey using the official Windows installer; and (ii) compiling DBeaver from source and, in both cases, I still can't see the 'Database size' property. I've also checked that the MySQL plugin version is indeed 2.1.45.

I also wondered whether it was something to with using MariaDB, but I have double-checked that the property does not show for either MySQL or MariaDB databases (we use both on different servers).

As you say, perhaps something is still cached locally, so I will try installing DBeaver on a completely fresh computer when I get a spare moment and let you know what happens!

**Comment by serge-rider** [comment]
Sorry, I forgot to mention: you need to enable expensive properties reading to see this value. Honestly it has very unobvious name in preferences: 
![default](https://user-images.githubusercontent.com/6398845/27707856-82e10400-5d1f-11e7-9eaa-a069069c3929.png)
I'll fix it in the next version.

**Comment by zejji** [comment]
Thanks! I can confirm that works now :)

**Comment by chriszrc** [comment]
Does this work for postgres?

**Comment by arjunyel** [comment]
I didn't see it for Postgres, as a workaround I used manual SQL command `SELECT pg_size_pretty( pg_database_size('dbname') );` https://www.a2hosting.com/kb/developer-corner/postgresql/determining-the-size-of-postgresql-databases-and-tables#Using-the-command-line

**Comment by karatedog** [comment]
I don't have this data on my DBeaver using Postgres while my colleague has it (using the same Postgres), we both installed the software trough click-click-finish and haven't set up anything, we just use it as it has installed.

**Comment by karatedog** [comment]
Ok, I have solved it. I had to upgrade from 7.0.3 to 7.1.5, which changed the display of the connections dramatically. I have now IP addresses beside the connections, the connections are marked with a colored line (according to test or production), and I have now a "Show statistics info" under Connection View which turns off/on the display of database object sizes.
