### ISSUE TITLE
ADD Database Import: play sound (or display notification OSD) when import complete

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1753]
## use case

I have a massive database that will take hours to import.
I fire up my trusty DBeaver and select Tools→Restore Database from the right click meny of my db.
in the "Database Import" window I then check "Play alarm when Import finished" under the "Settings" section.
I leave it importing and switch to another virtual desktop.

When the import finishes/fails, a notification sound plays once and I will know to check the other desktop.

----

a bonus would be to display an OSD notification if Eclipse supports it and if its not too much extra work :)

**Comment by serge-rider** [comment]
Notification will be added to all data transfer (data import/export) and all external tools (backup/restore/script execute) executions. It will include sound + tray icon popup (if it is enabled in preferences->Database->Task Bar).
