### ISSUE TITLE
set non-dynamic script parameters

### ISSUE THREAD

**Issue by alfonsofiore** [serge-rider/dbeaver#1754]
I've been looking for a few hours into parameters in dbeaver and I've learned about dynamic parameters, so now I can write stuff like:

select *
from table
where
mydate >= :start_date
and mydate <  :end_date

but what I'd really like to do is:

set :start_date = '2017-01-01'
set :end_date = '2017-04-01'
select *
from table
where
mydate >= :start_date
and mydate <  :end_date

for complex queries, the ability to edit dates only once and at the top of the script would be useful.
probably such feature exists but I can't find it.

thank you!

**Comment by kyleflan** [comment]
@set start_date = '2017-04-01' 

Then Alt + X to run the script. The Bind Parameters(s) window will still show, but it will have the values you specified filled in and you can just press OK to run the script with the parameters from the editor.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
