### ISSUE TITLE
unable to type whitespaces in query editor

### ISSUE THREAD

**Issue by rmalarc** [serge-rider/dbeaver#1755]
The editor seems to lockup and does not permit typing a whitespace after a sql keyword under certain conditions. I could not just type "select * from t" because it would not let me add the whitespaces in between. I've been typing "select*fromt" and then adding the whitespaces as needed. I know, silly.

The number of DB sessions is limited in our organization to 2. This happens whenever a third party app uses one of the connections, leaving DBEAVER with a single session left. It seems that dbeaver wants 2 sessions, one for the query from the editor and a second for running "SELECT * FROM _V_JDBC_CATALOG3 ORDER BY TABLE_CAT". 

Thanks!

**Comment by rmalarc** [comment]
just FYI, I was able to avoid the editor freeze by deselecting the "use separate connection for metadata" preference

**Comment by klugemonkey** [comment]
I get weird behavior in the SQL Editor script pane.  When typing text, the cursor blinks a lot and there is lag.

**Comment by klugemonkey** [comment]
Works on 4.0.6, but blinking on 4.0.7 and 4.0.8

**Comment by klugemonkey** [comment]
Nope, my bad, not working on 4.0.6 either

**Comment by klugemonkey** [comment]
Yeah, my issue is on all versions.  4.x and 3.8.5.  Not sure why it's not working.

**Comment by serge-rider** [comment]
You could try to disable auto-completion Preferences->General->Editors->SQL-Editor->SQL Completion). This is triggered by space symbols.

I don't see how else this issues could be resolved..
