### ISSUE TITLE
Request a Scrpit modification of Table DDL(Oracle DB)

### ISSUE THREAD

**Issue by ch2robin** [serge-rider/dbeaver#1757]
HI!
 Thank you for applying my request.
 I checked the version 4.0.8 today. (#1665)

There is a slight modification (request).
1.Please add ";" at the end of sql scrpit.
2.Please add ";" to the end of the comment scrpit.
3.Add 1 row between sql scrpit and commect scrpit.

![9](https://user-images.githubusercontent.com/28743365/27020281-bac76a7e-4f7a-11e7-8744-a796b91de9e1.jpg)

And I have a question.

COMMENT SCRIPT is not yet displayed in DDL of VIEW. Is this registered as milestone in 4.1.0? (#1678 )

I also requested the ability to directly enter or modify the COMMENT value in VIEW PROPERTIES. Is this feature request also registered with milestone in 4.1.0?

Thanks.

**Comment by serge-rider** [comment]
Yes, current behavior is more like a bug.
