### ISSUE TITLE
Foreign key deferrability field not working with SQLite

### ISSUE THREAD

**Issue by Cinosarge** [serge-rider/dbeaver#1759]
I'm using DBeaver 4.0.8 with SQLite 3.18.0

The field **Deferrability** (picture below) says the foreign key is "INITIALLY_DEFERRED" even if the constraint is working and also after DBeaver restart. I set **foreing_keys** to **yes** in the Driver Properties tab and made foreign keys **not deferrable** in my SQL statements.

![bug](https://user-images.githubusercontent.com/29370061/27030593-304e2868-4f6d-11e7-9d76-d2f70a834131.png)

SQLite or DBeaver issue? Thanks.

**Comment by serge-rider** [comment]
This is SQLite JDBC driver limitations (all FKs are marked as initially deferred).

**Comment by Cinosarge** [comment]
Thanks :)
