### ISSUE TITLE
Generate SQL - Insert Does not enclose text fields in parentheses

### ISSUE THREAD

**Issue by stoty** [serge-rider/dbeaver#176]
When using the Generate SQL - Insert context menu on a database row with `text` coulmns, the resulting insert statement does not enclose the contents of the text field in apostrophes.
`varchar` columns are enclosed correctly.

I.e instead of 
`INSERT INTO sometable (id, textfield) VALUES(1, 'sometext');`
it generates
`INSERT INTO sometable (id, textfield) VALUES(1, sometext);`

DBeaver 3.5.9 eclipse plugin, Mysql 5.7.10 on Centos 7.2

**Comment by serge-rider** [comment]
Thanks for report, will be fixed in the next version.
