### ISSUE TITLE
Bug : can't change program language

### ISSUE THREAD

**Issue by Hunter-Yi** [serge-rider/dbeaver#1761]
ubuntu 16.04 x64
dbeaver-ce 4.0.8.deb
the program language always english, but my pc(ubuntu) is chinese default, and i wang to chinese to.
i used -nl command line such as "-nl zh","-nl zhcn","-nl zh-cn","-nl zh_cn", and delete "~/.dbeaver4/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi" before open dbeaver.
it's english again and again .
it's worked on my pc(win 10).
please give me a hand

**Comment by serge-rider** [comment]
Since version 4.0 all localization were disabled in DBeaver (because of outdated translations).
We going to enable them again after 4.2 version. This will require quite a bit of work (translation).

**Comment by Hunter-Yi** [comment]
If this issue fixed in version 4.20? I try "-nl zh_cn" just now, can't work.

**Comment by liuyuanyuan** [comment]
Hi, there~
Which version will enable Chinese localization? When will that version released?
Hope to see your reply soon~

**Comment by liuyuanyuan** [comment]
I‘d like to do Chinese Localization for DBeaver.  I can also do some internationalization work.
Let me help you, OK?

**Comment by serge-rider** [comment]
Yes, we going to return localizations back. 
Thank you,
I'll reply by email.

**Comment by liuyuanyuan** [comment]
OK， looking forward to your reply~

**Comment by Hunter-Yi** [comment]
i just update to 4.2.5,there is still english, how to use chinese UI?

**Comment by serge-rider** [comment]
run DBeaver with command line parameter `-nl zh`.
We plan we enable all localizations by default after 4.3 version.

**Comment by Hunter-Yi** [comment]
Get !
Thank you.

**Comment by HongJheLi** [comment]
Where can I change language now? 
I'm using 4.3.1 version.
Thanks.

**Comment by serge-rider** [comment]
@HongJheLi 
In 4.3.x all localizations were turned on so you should just see it.
If not then you can use command line parameter -nl.
UI language selector isn't yet working (see #2458)

**Comment by wusc972** [comment]
How can I change Dbeaver language in eclipse plugin? 
I have updated  pliugin to 4.3.2，I chosed chinese option but it didnt work

**Comment by HongJheLi** [comment]
@serge-rider 
Thanks, but I got this error.
![image](https://user-images.githubusercontent.com/12004458/34804970-5a028ef6-f6b6-11e7-8732-433bc86f5cad.png)

**Comment by liuyuanyuan** [comment]
@wusc972 The language setting takes effect only when you restart your dbeaver.

**Comment by liuyuanyuan** [comment]
@HongJheLi  The hint is clear,  language switch cannot be executed because of  accessing denied.
you have to change  -nl * in your dbeaver.ini manually. Hope this helps~

**Comment by HongJheLi** [comment]
Solution: 
* `sudo vi /usr/share/dbeaver/dbeaver.ini`
* Add `-Duser.language=en` in dbeaver.ini like below.
```
2
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Duser.language=en
-Xms64m
-Xmx1024m
```

**Comment by ErunamoJAZZ** [comment]
This solution have a problem: Each time the DBeaver got an update, the config file come to default.

There is a way to store that config in the local environment?
