### ISSUE TITLE
Resultset tab naming bug

### ISSUE THREAD

**Issue by collicalex** [serge-rider/dbeaver#1763]
Hi,

When doing:
select * from tableA

The resultset tab name is "tableA". Which is great.

Now when doing:
select * from tableA
select * from tableB

It displayed 2 resultsets. The first tab name is "tableA", but the second tab name is "Results - 2" instead of "tableB".

Now when doing:
select * from tableC
select * from tableD

The first resulsetset tab name is not changed. It still "tableA" instead of "tableC". The second resultset is still displayed ad Results-2.

Now when doing only 1 statement:
select * from tableE

The second resultset is removed. The first resulsetset tab name is displayed correctly as "tableE".

So it seems there is a bug in tab name when displaying multiple resultset.

Regards

**Comment by rythym05** [comment]
Which setting controls the tab name in the result sets ? I am unable to find.

**Comment by collicalex** [comment]
Note that when adding a semi colon at the end of each select; tabs are correctly named.

**Comment by serge-rider** [comment]
This seems to be SQL Server issue, right?
DBeaver can't determine tab name if you execute multiple selects in one SQL query. Driver jsut doesn't provide this information.
If you use delimiters then DBeaver executes each query separately and thus it knows how to name the resultset tab.

@rythym05 To change tab name you can:
1. Insert comment in the beginning of query
```sql
-- NAME: Custom tab name
select 123 
```
2. For additional tabs you can right click on tab->Set tab title

**Comment by collicalex** [comment]
Hmm which jdbc function / getter is used to retrieve the first resultset name / table name?
Can't find it in java doc.

It's not DBeaver which retrieve name(s) from parsing the executed sql statement(s) ?

**Comment by rythym05** [comment]
@serge-rider Thanks for the tip with using the -- NAME: identifier. Works for me. 
From the first post here, it seemed like 
Select * from tableA; 
would automatically name the resultset as tableA. 

Is it not the case ? I am using Oracle and I don't see it name that way.

**Comment by serge-rider** [comment]
Extracting tab name from query is tricky and database-dependent. For some databases it can be obtained from ResultSet.getCursorName(), for others it is taken from resultset metadata or from source table name (by parsing source SQL query). And still for some databases none of these methods work.
