### ISSUE TITLE
cant add new row in empty table

### ISSUE THREAD

**Issue by szegi** [serge-rider/dbeaver#1764]
Im using newest version
and PostgreSQL database

if table is empty
i cant add new row using "+" sing or ctrl+insert:/

**Comment by kyleflan** [comment]
This is a bug in 4.0.8. Workaround here: https://github.com/serge-rider/dbeaver/issues/1722

> Workaround: insert first row using "insert before" setting. You can change this behavior in preferences or you can make first row insert by pressing Shift key and clicking on green plus button.
> After table has at least one row normal insert will work ok.

**Comment by serge-rider** [comment]
Dup0licate of #1722

**Comment by rashidhussainshah** [comment]
press alt + insert key, its working fine in my laptop, my Dbeaver Version 7.3.5.202102151746
