### ISSUE TITLE
Result of AVG is displayed as NUMBER(39, 0) on Oracle

### ISSUE THREAD

**Issue by ThePadawan** [serge-rider/dbeaver#1767]
Given the following schema and query...
```
CREATE TABLE foo (
    id NUMBER (19, 0) PRIMARY KEY,
    bar NUMBER(19, 0)
);

SELECT AVG(bar)
FROM foo
GROUP BY id
```

Mousing over the resulting column in the Result view indicates that the type of the result is NUMBER(39, 0). However, that cannot be true - the NUMBER datatype can only go up to a precision of 38 (according to the [docs](https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1832)), and a scale of 0 would indicate that the results do not contain any decimal digits, which they do.

This might not be an issue within DBeaver, but I would nevertheless appreciate any help in understanding how this occurs.

**Comment by serge-rider** [comment]
You are right. But I don't see how can I fix this.

To view actual columns metadata you can open Metadata panel. Oracle JDBC driver doesn't provide scale/precision information for expressions (they both are equal to zero) so DBeaver uses "display size" value in such cases. Which is always 39 for NUMBERs (perhaps +1 character for sign?).

**Comment by ThePadawan** [comment]
I assumed something like that - thank you for investigating! I don't think there's any improvement you can make on this.
