### ISSUE TITLE
CPU 100% when result tab is open

### ISSUE THREAD

**Issue by kollerma** [serge-rider/dbeaver#1770]
I'm running DBeaver 4.0.8 inside Eclipse. But this has been going on for a long time, and it doesn't happen when I run DBeaver separately.

The problem starts after I have run the first query. When the query is finished and absolutely nothing is supposed to happen, the CPU just stays 100% on one thread. But when I hide the result tab with the little triangle button, then the CPU utilisation goes down to 0%. 

I have attached two tread dumps, one with the result tab open (and 100% cpu) and one where it's closed. Hope this helps.

Thanks for the good software and for looking into this.

[thread-dump-result-tab-hidden.txt](https://github.com/serge-rider/dbeaver/files/1074011/thread-dump-result-tab-hidden.txt)
[thread-dump-with-result-tab-open.txt](https://github.com/serge-rider/dbeaver/files/1074012/thread-dump-with-result-tab-open.txt)

**Comment by kollerma** [comment]
Small update: no query needs to be run, an empty results tab is enough. And the issue disappears when using gtk version 2.

**Comment by serge-rider** [comment]
> And the issue disappears when using gtk version 2.
This is the real issue. SWT still has very poor support of GTK 3. There is a number of known performance issues (including cpu load and huge memory consumption). 
Hopefully Eclipse 4.7 will resolve some of them.

**Comment by kollerma** [comment]
I have run DBeaver from within Eclipse Oxygen and with GTK 3 for a few days now without problems. This issue seems to have been resolved.
