### ISSUE TITLE
Crash on Ubuntu 14.0

### ISSUE THREAD

**Issue by TomZastrow** [serge-rider/dbeaver#1771]
On Ubuntu 14.04, I get the error when starting DBeaver from the CLI:

> 2017-06-14 12:16:13.971 - DBeaver 4.0.8 is starting
> 2017-06-14 12:16:13.973 - Install path: '/usr/share/dbeaver'
> 2017-06-14 12:16:13.974 - Instance path: 'file:/home/thomz/.dbeaver4/'
> 2017-06-14 12:16:13.974 - Memory available 109Mb/910Mb
> 2017-06-14 12:16:13.985 - Starting RMI server at 28782
> 2017-06-14 12:16:14.078 - Create display
> 2017-06-14 12:16:14.136 - Run workbench
> 2017-06-14 12:16:15.753 - Initializing DBeaver 4.0.8
> 2017-06-14 12:16:15.760 - Host plugin: org.jkiss.dbeaver.core.application 4.0.8
> 2017-06-14 12:16:15.761 - Initialize Core...
> 2017-06-14 12:16:15.973 - Core initialized (212ms)
> 2017-06-14 12:16:15.974 - Configure workbench window
> 2017-06-14 12:16:16.071 - Create actions
> 2017-06-14 12:16:16.079 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
> 2017-06-14 12:16:16.080 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
> 2017-06-14 12:16:16.894 - Initialize workbench window
> 2017-06-14 12:16:16.896 - Finish initialization
> java: /build/buildd/gtk2-engines-oxygen-1.4.5/src/animations/oxygencomboboxdata.cpp:87: void Oxygen::ComboBoxData::setButton(GtkWidget*): Zusicherung »!_button._widget« nicht erfüllt.

**Comment by serge-rider** [comment]
Du0plicate of #1636
