### ISSUE TITLE
executing row count returning incorrect for sqls with distinct

### ISSUE THREAD

**Issue by maddogv6** [serge-rider/dbeaver#1773]
I have a sql that has a distinct in it.    when looking at the records in the grid, it was returned 854 rows.  If i did a "execute > select row count", it gave me over 872 rows.   Same as if i took the distinct out from my sql.  

In TOAD for Oracle, the result grid also shows 854 rows.   And its record count also returns the same.   I'm running on Oracle 12i.

after scrolling down all the way to bottom of the grid.
![dbeaver grid count](https://user-images.githubusercontent.com/25310356/27138893-969b6706-50ef-11e7-9afb-40c0627f6081.jpg)

select row count feature
![dbeaver select row count feature](https://user-images.githubusercontent.com/25310356/27138880-93077396-50ef-11e7-9cac-84e8c410f6f3.jpg)

**Comment by serge-rider** [comment]
Thanks for report
