### ISSUE TITLE
Need to enable Word Wrap each time

### ISSUE THREAD

**Issue by rythym05** [serge-rider/dbeaver#1774]
I see that I need to enable word wrap for each editor tab in the application. The setting is lost when I close and restart the application.

Is it possible to set/unset word wrap at the application level for all the editor tabs and the setting be retained in  properties ?

**Comment by serge-rider** [comment]
This is controlled by Eclipse platform. At the moment there is no global word-wrap setting in text editors preferences (but it should be added in the next version).
Check this topic for workaround: https://stackoverflow.com/questions/39597007/how-do-you-enable-word-wrap-by-default-in-eclipse

**Comment by rythym05** [comment]
Thanks. Your tip works 

manually edit the org.eclipse.ui.editors.prefs file (.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs) in your eclipse workspace. There, you can add the settings wordwrap.enabled=true

**Comment by alikrc** [comment]
full path in windows

 `%APPDATA%\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.eclipse.ui.editors.prefs`

**Comment by xiantuteng** [comment]
Use Word Wrap feature that wraps the text within a screen.
Use Auto Format feature to automatically change the appearance of XML/JSON script (fix spaces around operators / commas, fix
indentation, etc) and make it more readable.
To learn more about Value panel, see Panels.
DBeaver user guide 61/285
[https://dbeaver.com/doc/dbeaver.pdf](https://dbeaver.com/doc/dbeaver.pdf)

![image](https://user-images.githubusercontent.com/20884718/144964364-460dcde3-a7f5-46fd-8546-ef9f7a05d188.png)

**Comment by rmtsrc** [comment]
In the version I'm using (`21.3`) these settings seem to have moved to:

[Workspace location](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location): `DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.ui.editors.data/dialog_settings.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<section name="Workbench">
  <section name="AbstractTextPanelEditor">
    <item key="content.text.editor.auto-format" value="true"/>
    <item key="content.text.editor.word-wrap" value="true"/>
  </section>
</section>
```

Note: make sure DBeaver is closed before editing this file.

**Comment by warcayac** [comment]
@rmtsrc,  I'm using v22.0 on Manjaro Linux, I edited this file with your content: 
`~/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.ui.editors.data/dialog_settings.xml`
After opening DBeaver nothing changed.

**Comment by rmtsrc** [comment]
Looking at a fresh install, it seems there are 2 independent settings for word wrap:

1 Sets word wrap for the "Value" panel when inspecting rows etc.

[Workspace location](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location): `DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.ui.editors.data/dialog_settings.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<section name="Workbench">
  <section name="AbstractTextPanelEditor">
    <item key="content.text.editor.auto-format" value="true"/>
    <item key="content.text.editor.word-wrap" value="true"/>
  </section>
</section>
```

2 Sets word wrap for the Script/editor panel:

Add the following to the end of the file: [Workspace location](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location): `DBeaverData/workspace6/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs`

```ini
lineNumberRuler=true
wordwrap.enabled=true
```

Note: make sure DBeaver is closed before editing these files.

**Comment by Powsey** [comment]
> Looking at a fresh install, it seems there are 2 independent settings for word wrap:
> 
> 1 Sets word wrap for the "Value" panel when inspecting rows etc.
> 
> [Workspace location](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location): `DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.ui.editors.data/dialog_settings.xml`
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <section name="Workbench">
>   <section name="AbstractTextPanelEditor">
>     <item key="content.text.editor.auto-format" value="true"/>
>     <item key="content.text.editor.word-wrap" value="true"/>
>   </section>
> </section>
> ```
> 
> 2 Sets word wrap for the Script/editor panel:
> 
> Add the following to the end of the file: [Workspace location](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location): `DBeaverData/workspace6/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs`
> 
> ```ini
> lineNumberRuler=true
> wordwrap.enabled=true
> ```
> 
> Note: make sure DBeaver is closed before editing these files.

Heyo!

Only the second part is required now, the first folder from jkiss is no more in current version (23.0.1). 

As mentionned by @rmtsrc, do make sure DBeaver is closed before editing the file (otherwise it will replace your change). 

Thanks
Have a good one
