### ISSUE TITLE
Oracle SQL with forward slash instead of semicolon terminators

### ISSUE THREAD

**Issue by beirtipol** [serge-rider/dbeaver#1775]
Perhaps I'm missing something obvious because I'm surprised it doesn't work. The commands below can be executed as a sql script in sqlplus.exe or in SQLDeveloper. If I select all the commands (Usually this would be a collection of CRUD and PL/SQL commands) and use ALT+X, I get the following error:

> SQL Error [933] [42000]: ORA-00933: SQL command not properly ended
> 
>   java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
> 
> 

```
SELECT 1 FROM dual
/

SELECT 2 FROM dual
/
```

Am I missing something simple?

**Comment by serge-rider** [comment]
DBeaver doesn't support SQLPlus syntax.
However you can change default statements delimiter in Preferences->General->Editors->SQL Editor->SQL Processing (just change `;` on `/`)

**Comment by beirtipol** [comment]
Ah, that's a shame. I have a 65k line script that needs to run and I like how dbeaver captures results of each statement. Any plans to support it sqlplus syntax in the future?

**Comment by serge-rider** [comment]
Yes, we have such plans. But not in the nearest versions.
