### ISSUE TITLE
Quote cell values in Advanced Copy sets to Double Quote. Need to customize as Single Quote

### ISSUE THREAD

**Issue by rythym05** [serge-rider/dbeaver#1776]
Quote cell values in Advanced Copy sets to Double Quote. In Database such as Oracle, characters are enclosed in  Single Quote. Is there a way to change this ?

**Comment by serge-rider** [comment]
Advanced Copy copies values in CSV format.
If you need SQL format you can use Generate SQL or Export Resultset->SQL features.

**Comment by rythym05** [comment]
I extensively use Advanced copy with "Quote cell values" for copying character values in my grid which I need to use in a IN clause back back in my SQLs. 

The other 2 options don't make things as easy.

**Comment by serge-rider** [comment]
Ok, I see. I'll add extra config option

**Comment by rythym05** [comment]
Great ! Appreciate it.
