### ISSUE TITLE
Color connection

### ISSUE THREAD

**Issue by jzaruba** [serge-rider/dbeaver#1777]
I would like to be able to open a colored editor from particular connections.
I feel stupid, I am pretty sure the feature is there, just properly burried. And apparently not mentioned anywhere within Google's reach. Closest I could find was [this](http://dbeaver.jkiss.org/forum/viewtopic.php?f=3&t=800). No mention of how to reach that feature... 

If the feature is already there, can you please add some lead to it, somewhere in the connection properties pane? (F4, or Alt+Enter...?)

**Comment by fanis** [comment]
You can have different colours based on `Connection Type`.

`Edit Connection` -> `General` -> `Connection type`

In there you can change the colour for as many types as you like. You can also use it for its presumably intended purpose, to save you from accidentally executing queries on production databases.

![2017-06-15 15_06_45-dbeaver - general - _mysql - new connection_ script-3](https://user-images.githubusercontent.com/562545/27180489-6c358bd4-51dc-11e7-9341-2b2fbd452fb8.png)

**Comment by jzaruba** [comment]
oh thank you very much, kind sir! :)

**Comment by VIJAYVIVU** [comment]
> You can have different colours based on `Connection Type`.
> 
> `Edit Connection` -> `General` -> `Connection type`
> 
> In there you can change the colour for as many types as you like. You can also use it for its presumably intended purpose, to save you from accidentally executing queries on production databases.
> 
> ![2017-06-15 15_06_45-dbeaver - general - mysql - new connection script-3](https://user-images.githubusercontent.com/562545/27180489-6c358bd4-51dc-11e7-9341-2b2fbd452fb8.png)


Thank you so much searching for long time
