### ISSUE TITLE
Table view label:enhancement 

### ISSUE THREAD

**Issue by tekyman007** [serge-rider/dbeaver#1778]
Is it possible to open the 3 tabs Properties, data and diagram side by side ?
bdeaver layout should be more  flexible when using big screens 4k

**Comment by serge-rider** [comment]
No, it is not possible (and hard to implement).
But you can split editor area and open two editors side by side (main menu Window->Editor->Toggle Split Editor).

**Comment by tekyman007** [comment]
Thank  you for your feedback. But I have no Editor under Window menu
![greenshot_2017-06-17_13-43-00](https://user-images.githubusercontent.com/29176543/27255039-7220a0dc-5363-11e7-9991-09803b0628a7.png)

**Comment by kyleflan** [comment]
Try **Shift + Ctrl + [** (or Shift + Cmd + [ if on Mac) to toggle the split editor on and off. I don't see the menu option in the stand-alone instance of DBeaver, but the shortcut works.

**Comment by serge-rider** [comment]
Ah, sorry, I forgot that these extra menus present only in EE version (because of extra Eclipse plugins). Anyhow shortcuts should work fine.
![default](https://user-images.githubusercontent.com/6398845/27302909-95b88f84-5541-11e7-9312-a2b66a58d95a.png)

**Comment by tekyman007** [comment]
Thank you very much!
