### ISSUE TITLE
Templates view does not update its content

### ISSUE THREAD

**Issue by jzaruba** [serge-rider/dbeaver#1779]
Adding or removing templates has no apparent effect until the Templates view is closed and opened again.
DBeaver 4.0.8, Win7 64bit

**Comment by serge-rider** [comment]
This is a bug in Templates view refresh.
In fact when you create/drop template it is actually created/dropped (and you start using it). But view contents isn't refreshing properly.
Templates view comes from Eclipse platform, I can't fix it.
