### ISSUE TITLE
Customize database navigator treeview indentation

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#1781]
Is there any way of customizing the treeview indentation of the database navigator? I'd like to reduce the lost space as show here:

![image](https://user-images.githubusercontent.com/3851902/27182246-dee09068-51da-11e7-872a-8bccfdfe9c3f.png)

**Comment by serge-rider** [comment]
I doubt this is possible. DBeaver uses native OS controls (tree, table, etc). 
So in theory this can be controlled by OS windows interface settings.

**Comment by Otiel** [comment]
Got it, thanks.
