### ISSUE TITLE
Wrong text color at first, but correct text color on window refresh/focus/unfocus

### ISSUE THREAD

**Issue by golimarrrr** [serge-rider/dbeaver#1782]
After running a query I try to read the number of rows fetched but the text foreground and background is almost the same:

![problema dbeaver dark theme antes](https://user-images.githubusercontent.com/3762732/27185728-889a5020-51e6-11e7-9d2d-4d01e4ba3279.png)

However if I switch to other application and switch back it shows light foreground over dark background, which is probably the configured colors. Even without switching applications, just clicking away from the DBeaver windows does the same.

![problema dbeaver dark theme despues](https://user-images.githubusercontent.com/3762732/27185744-8ee58300-51e6-11e7-99af-44bf264e5184.png)

Is it the planned behavior or a bug?
Tried with 4.0.7 and 4.0.8 on Windows 7

**Comment by serge-rider** [comment]
It is a bug in status label rendering, thanks for report.

**Comment by golimarrrr** [comment]
Could this be the same problem? However it doesn't change when switching applications or clicking away:

![image](https://user-images.githubusercontent.com/3762732/31174850-5613561e-a90d-11e7-955c-260d8af74b86.png)

**Comment by serge-rider** [comment]
Nope. It was a bad icon. Fixed

**Comment by golimarrrr** [comment]
Oh, I meant the black text on grey background.
It's probably one of the settings in Colors and Fonts but I can't find which one is it

**Comment by serge-rider** [comment]
Looks like it is not possible to customize tool item foreground color in SWT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=401227
