### ISSUE TITLE
Bug: different IP address in error message

### ISSUE THREAD

**Issue by ramazanpolat** [serge-rider/dbeaver#1784]
I'm trying to connect 192.168.1.**24** but the error message says it's failed to connect 192.168.1.**20**

![dbeaverip](https://user-images.githubusercontent.com/3527695/27208413-352792fa-524e-11e7-92d9-787272683fa4.PNG)

**Comment by serge-rider** [comment]
192.168.1.20 is YOUR ip address (this is typical MySQL thing - by default you can't connect from any external IP address). You can use tunnel or you can ask your DBA to grant permissions to root@192.168.1.20 user or something liek that.
