### ISSUE TITLE
Mark odd/even rows -> mark every 5/10/n rows

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1785]
Can you make the number of rows grouped by shading configurable? Thx.

![20170616t111816_hp-radw04](https://user-images.githubusercontent.com/25423046/27210512-9511140c-5285-11e7-8e3a-ca55871af3b2.png)

**Comment by kyleflan** [comment]
This isn't a built in way, but it might help you in the interim. DBeaver can color rows by value. Right click on a value and select View/Format -> Color by <col name>

You could do something like below (this is in Postgres) to band every fourth row.

```
CREATE TABLE banded_rows (
	row_id serial primary key,
	val text);

INSERT INTO banded_rows (val) VALUES 
	('One') ,
	('Two'), 
	('Three'), 
	('Four'), 
	('Five'), 
	('Six'), 
	('Seven'), 
	('Eight'), 
	('Nine'), 
	('Ten'),
	('Eleven'), 
	('Twelve');
	
CREATE OR REPLACE VIEW vw_banded_rows as (
	SELECT val, ((row_number() OVER(ORDER BY row_id) - 1) / 4) % 2 as grp FROM banded_rows
	);
	
SELECT * FROM vw_banded_rows;
```

Then, right click on '1' in the grp column and select View/Format -> Color by grp.. and choose a color.

![image](https://user-images.githubusercontent.com/5608074/27244734-7e7231ea-52ad-11e7-9831-1bc78a6e8b4d.png)

**Comment by serge-rider** [comment]
Ok, this makes sense and easy to implement.

**Comment by serge-rider** [comment]
![default](https://user-images.githubusercontent.com/6398845/27355907-3fc796c2-5615-11e7-8876-1a268df16cf5.png)
