### ISSUE TITLE
set active database 

### ISSUE THREAD

**Issue by tekyman007** [serge-rider/dbeaver#1791]
Is is possible to set a database active just by a double click.

**Comment by kyleflan** [comment]
Not sure about double-click, but if you select the option to 'Auto-sync connection with navigator' from the toolbar, you can single click on a database and it will make it the active database. Use with caution, though. I have my dev/prod connections colored differently so that if I accidentally click on prod while working on some stuff in dev I'm aware that I've switched environments. 

![image](https://user-images.githubusercontent.com/5608074/27288699-1cfce33e-54cd-11e7-9208-811bc98948d4.png)

**Comment by serge-rider** [comment]
Auto-sync is very "special" feature, most of users will find it annoying.
But you can just use manual sync - select connection on navigator and click on "Set connection from navigator" button (`CTRL+SHIFT+.`)

**Comment by zingaburga** [comment]
Sorry to bring up this topic again, but the 'Auto-sync connection with navigator' option is greyed out for me - would you know why?

Also, from what I can tell, the 'active database' concept applies to all open SQL editors - is there a way for each editor to have its own active database? (I've enabled the option for each editor to have its own connection, if that helps)

The typical workflow I'm used to is to select a database in the Database Navigator, then use the shortcut to open an SQL editor - this editor should always retain the database it was opened under as its active database.  This means I can easily work on multiple databases by switching between editor tabs.

Another common idea is, when browsing a table, you realise you need to run a query (e.g. update multiple rows based on some criteria).  I usually do this by the new SQL editor shortcut, typing in the query, and run it - is there any way for DBeaver to have this contextual understanding to automatically create the editor in the same database as the table being viewed?

Thanks!

**Comment by kyleflan** [comment]
What version of DBeaver are you running? For me, each tab has its own connection associated with it. If you're specifically referring to separate databases within the same connection, then you'll have to manually set the active database. 

What I do when I have multiple databases per connection is to create multiple connections, with each connection having a separate database set as the default database in the connection settings. This way, each new tab can be associated with a specific database.

**Comment by zingaburga** [comment]
Thanks for the suggestion.  I'm running version 5.2.5.  Databases are MariaDB, if that matters.

I found that there's an option under connection properties -> Editors -> Auto-sync editor connection with navigator selection, which I presume does the same thing as the menu option (although it's still unchecked and greyed out for me).

Are you suggesting to duplicate connection configurations (i.e. multiple connections to the same database in the Database Navigator)?  I suppose that does work, but seems kinda ridiculous...  
Coming from other database GUIs, this whole notion of being able to select an active database seems rather unwieldy.  IMO, the active database should be selected when creating the SQL editor, and each editor should have its own active database set.  I'd guess it to be rare to ever want to change the active database of an SQL editor, unless you happen to have the same table structures and names across multiple databases.  A much more likely use case is a user to be executing queries in different databases.

**Comment by zingaburga** [comment]
Another thing I noticed - it seems like the active database also affects table editors.  So you have to remember to select the correct active database before you run queries, and possibly as well as saving changes in the table editor (for databases which behave differently depending on the active database a query is run under), which seems a little counter-intuitive IMO.

DBeaver seems like a great tool, and it would be awesome if these sorts of small usability issues could be resolved! :)
