### ISSUE TITLE
Error in parsing ODBC literals in SQL Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#1792]
I'm using the Microsoft Driver.
I create this table and I insert a record
```SQL
CREATE TABLE TEST (ID BIGINT NOT NULL PRIMARY KEY, DATEINSERT DATETIME2 NULL)
INSERT INTO TEST VALUES(1, GETDATE())
GO
```

Then I use dbeaver to generate an insert script, I truncate the table and try to insert the record

```SQL
TRUNCATE TABLE TEST
INSERT INTO [db_name].dbo.TEST(ID, DATEINSERT)
VALUES(1, {ts '2017-06-19 12:29:25.170000'});
```

I get
```
SQL Error [241] [S0003]: Conversion failed when converting date and/or time from character string.
```

The problem are the nanoseconds: if I remove them it works

```SQL
INSERT INTO [db_name].dbo.TEST(ID, DATEINSERT)
VALUES(1, {ts '2017-06-19 12:29:25'});
```

**Comment by serge-rider** [comment]
Can't reproduce (i.e. INSERT works fine).
What SQL Server version do you use?
Did you try jTDS driver?

**Comment by Lucas-Malor** [comment]
I confirm. I'm using SQL Server 2012 with Microsoft driver.

**Comment by gabriele-ricci-kyklos** [comment]
The problem still remains. I'm using SQL Server 2016 with Microsoft Driver.
