### ISSUE TITLE
[Feature Request] Insert SQL from a template by dragging it into an editor

### ISSUE THREAD

**Issue by jzaruba** [serge-rider/dbeaver#1797]
Please make it possible to insert SQL of a template by dragging that template into an editor.
Currently we get the "forbidden" mouse-pointer when trying to drag'n'drop a template into an editor.

**Comment by serge-rider** [comment]
Can't reproduce the problem:
![sql-templates-dnd](https://user-images.githubusercontent.com/6398845/27369433-89b0cf10-5660-11e7-9549-7b0bc3639470.gif)

Maybe you mean something more sophisticated than just drag-n-drop?

**Comment by jzaruba** [comment]
Ah seems like the described behavior only applies when the target editor's underlying connection is not open. Once connection is open I can drag'n'drop the template code into the editor.
When I disconnect again the mouse-pointer still suggests I can drop template into editor, nothing happens though when I do. That is merely a cosmetic issue.

**Comment by jzaruba** [comment]
The behavior is not determined by a connection after all.
It happens whenever I try to drag a template onto a freshly open *empty* editor.
Once I enter even a single character into the editor/script (even without saving) I can drag'n'drop templates in, as expected.
Erasing the content of the editor afterwards has no effect, d'n'n works. Re-opening the editor/script causes d'n'd to malfunction again.

**Comment by serge-rider** [comment]
Seems to be some Eclipse text framework glitch. I've reproduced this but I can't fix this..
