### ISSUE TITLE
How could I select/highlight a tall SQL?

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#1798]
Do we have menu items or keyboard shortcuts to...?
1. select/highlight the SQL statement that the cursor is stepping on
2. move cursor to the beginning/end of SQL
3. extend selection to the beginning/end of SQL
4. to the next/previous SQL, i.e. to the next/previous empty line or semi-colon

The idea is an extension of Ctrl+left, Ctrl+right, Ctrl+shift+left, Ctrl+shift+right. Thx.

**Comment by serge-rider** [comment]
This is not supported, although you can use `ALT+UP` and `ALT+DOWN` to iterate over script queries.

CTRL[+SHIFT]+LEFT/RIGHT are standard shortcuts for words selection.

**Comment by yanOnGithub** [comment]
It worked. Thx.

alt+up = select the previous sql
alt+up, alt+down = select the SQL statement that the cursor is stepping on
alt+up, alt+down, left = move cursor to the beginning of SQL
and so on
