### ISSUE TITLE
auto completion show only keyword

### ISSUE THREAD

**Issue by collicalex** [serge-rider/dbeaver#1799]
Hi,

The auto completion show only keyword (when at least one keyword match) instead of table names.

Example: with a table name "extraction_setup", I typed `select * from extr` and type ctrl+space to have the completion; and it show "EXTRACT" keyword only.

![autocompletion1](https://user-images.githubusercontent.com/24322371/27373507-dd04c812-5668-11e7-9263-d63a061dee5e.png)

![autocompletion2](https://user-images.githubusercontent.com/24322371/27373512-e170af88-5668-11e7-9a74-6662087cb7e7.png)

Is it possible to show both keywords and table names?
Or how to switch from keyword list to table name list? 
I think I have the same issue with field name list.

Alex

**Comment by serge-rider** [comment]
For SQL Server you need to specify schema name to make auto-completion work correctly. This will be fixed along with #810 feature.
