### ISSUE TITLE
File selection dialog for private key file in SSH tunnel setup restricting selection

### ISSUE THREAD

**Issue by alexei-znamensky-movile** [serge-rider/dbeaver#180]
When searching for private keys, the file dialog looks for only these two patterns: *.* or *.ssh
I am on linux and by default the private keys have no extension (probably the choice for these 2 patterns were based on other OS's), thus I am not able to select it from the file selection dialog, I had to actually type in the file name.

**Comment by serge-rider** [comment]
Yes, it seems to be a linux-specific issue, on Windows *.* shows all files.
I'll add "*" file mask.
Thanks for report
