### ISSUE TITLE
Unable to commit BLOB fields in a DB2 on version 4.0.8 but can on version 3.8.5

### ISSUE THREAD

**Issue by sroweuk** [serge-rider/dbeaver#1801]
DB2 Driver JDBC db2jcc version: 3.69.24 for both DBeaver version 4.0.8 & version 3.8.5

When I change a BLOB field containing XML data from within DBeaver using the LOB editor, it does not save the data back to the DB. I do not see the Commit hilighted in the menu bar nor does the Save option at the bottom of the page hilight, when using version 4.0.8. I am unable to commit the changes. When I shutdown the DBeaver app it states that there are uncommitted transactions and if I wish to commit them. However, when I commit i get the error message "The specified size of the InputStream, parameter #1, is less than the actual InputStream length"

However, when I use 3.8.5 the save option appears at the bottom of the page & when I click on it, it commits the changes to the DB. It appears to be a change on 4.0.8 is causing an issue.

**Comment by serge-rider** [comment]
How do you edit BLOB value?
You can open separate editor, open editor in panel or load LOB value directly from file (using context menu).

**Comment by titou10titou10** [comment]
Hi,
You are using a JDBC v3.x driver (v3.69.24). Could you switch to a JDBC v4.x Driver (db2jcc4.jar v4.xx.xx)
Support of XML data is only fully available with JDBC v4+
DB2 Drivers are accessible here: http://www-01.ibm.com/support/docview.wss?uid=swg21363866
Thanks
Denis

**Comment by serge-rider** [comment]
I home that recent fixes will resolve LOB save issue in 4.1.0.
Please reopen if not.
