### ISSUE TITLE
Inline data editor broken - Redshift

### ISSUE THREAD

**Issue by SZubarev** [serge-rider/dbeaver#1806]
Can't edit data in a field when connected to Redshift database. Checked with MySQL - works fine.
DBeaver EE 4.0.5

**Comment by serge-rider** [comment]
Please provide a bit more info.

If you mean edit results of some custom SQL query then most likely DBeaver can't determine source table.
This feature is not implemented by big number of JDBC drivers.
If you mean direct table data edit then this is probably a bug in DBeaver.

**Comment by SZubarev** [comment]
I'm opening Redshift table and the edit functionality is not available

**Comment by serge-rider** [comment]
Please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)
