### ISSUE TITLE
F2 for "inline edit" messes with F2 for "rename"

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#1809]
I've changed my shortcut key for the "inline edit" action from <kbd>Enter</kbd> to <kbd>F2</kbd>, as shown below:

![image](https://user-images.githubusercontent.com/3851902/27479664-1fc00434-5815-11e7-98b2-d8e248eea781.png)

It works fine, but now the <kbd>F2</kbd> shortcut used on an object in the database navigator ("rename" command) doesn't do anything anymore.

PS: Changing the "When" option of the "Rename" command to "Database navigator context" doesn't solve it.

**Comment by lrweck** [comment]
FYI:  select a::text from professor a works as expected...

**Comment by serge-rider** [comment]
Thanks for report.
Will be fixed in the next version.
