### ISSUE TITLE
Issue connecting to Sybase Anywhere

### ISSUE THREAD

**Issue by osrojas** [serge-rider/dbeaver#1813]
Hi,

After setting up a new Sybase Anywhere database connection and testing it by clicking the _Test Connection_ button, it connects just fine and I save the connection. However, when I try to execute a query or try to expand **Tables** from the database navigator on the left-hand side of the application, I get the following error:

**SQL Error [HY010]: Invalid state, the Connection object is closed.**

When I setup this same Sybase Anywhere database connection in Aqua Data Studio, queries and table navigation work just fine. One difference I noticed is that DBeaver uses the _JTDS 1.3.1.jar_ driver whereas Aqua Data Studio uses the _jconnect16.jar_ driver.

I tried setting up a new custom driver in DBeaver utilizing _jconnect16.jar_ from Aqua Data Studio, specifying the class file _com.sybase.jdbc4.jdbc.SybDriver_ and URL template of _jdbc:sybase:Tds://{host}:{port}/_, but I just get this error when testing the connection:

**java.sql.SQLException: JZ003: Incorrect URL format. URL:**

Am I missing something? Any assistance would be great appreciated!

**Comment by serge-rider** [comment]
I suppose URL template should be `jdbc:sybase:Tds://{host}:{port}[/{database}]` - trailing slash makes database name required.

**Comment by osrojas** [comment]
I tried that URL template but I'm still getting the same error for the incorrect URL format. Any other ideas on what it could be?

**Comment by osrojas** [comment]
After playing around with the template, I found that the URL below works fine. The two forward slashes after the Tds colon were causing the incorrect URL format. Hopefully this helps others in the future. Thanks!

**jdbc:sybase:Tds:{host}[:{port}][/{database}]**

**Comment by rogerrafael7** [comment]
I have the same problema:

> [HY010] Invalid state, the Connection object is closed.

I'm using Sybase (jTds)
