### ISSUE TITLE
Add color and the possibility to send to back to Notes in ER Diagram.

### ISSUE THREAD

**Issue by EMBBlaster** [serge-rider/dbeaver#1814]
Notes could benefit from color in ER Diagram.
Also if you could send them to background them they could be used to organize the layout.
![clipboard01](https://user-images.githubusercontent.com/5237402/27500991-2a87c63c-5841-11e7-8f3b-715a228e9304.jpg)

**Comment by ffblanch** [comment]
Great!

**Comment by rodrigoufv** [comment]
Great tip, this feature allows you to improve the organization

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/29996829-8dfba9a4-900e-11e7-9927-b2811d9000e4.png)

As for me - looks good enough for now.
Additional ERD improvements should be tracked in a separate ticket.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/29996839-bc8cbe20-900e-11e7-9c5c-8feac900ef91.png)
