### ISSUE TITLE
MongoDB Export data file format problem

### ISSUE THREAD

**Issue by kervin521** [serge-rider/dbeaver#1816]
EX:
SQL: insert into table1(aa,bb,...)values(#document)
CSV:(#document) 
........................................

it can't export detail data column ,but only to ben '#document'

how to solve?

**Comment by serge-rider** [comment]
It is a bug in DBeaver, thanks for report.

**Comment by kervin521** [comment]
@serge-rider dbeaver-ce-4.1.0 can't support MongoDB and Cassandra

how to solve?

**Comment by serge-rider** [comment]
EE version 4.1 will be released along with CE 4.1.1. 
In the middle of July.

**Comment by serge-rider** [comment]
You can download EE version from https://dbeaver.com/download/
