### ISSUE TITLE
Generate SQL Script sometime was grey color (like disable)

### ISSUE THREAD

**Issue by tranbaohuu** [serge-rider/dbeaver#1817]
Dear supporter 
    DBeaver's Generate SQL Script feature to my database for a few table is OK. But many kind table it's not working e.g: a table wkith 71 columns and i selected with where conditions then clicked on result table and chose Generate SQL Script then it was became GREY color (like disable) and I couldn't did anything more.
Additional I'm using SQL Server 2005.
Thanks, and hope it's going to fix for the next version.
I'm really like this app.

**Comment by serge-rider** [comment]
This may happen if DBeaver can't detect source table from your query.
I will add explanation item to the menu (current UI confuses many people).

Workaround: try to edit table directly (because custom SQL metadata is poorly supported for SQL Server).

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. Perhaps, the question was solved. It will be closed. However, if you think that it is actual just let us know.
