### ISSUE TITLE
Selection of multiple values in column

### ISSUE THREAD

**Issue by mstup** [serge-rider/dbeaver#1818]
I see it very useful to get to be able to copy multiple values in column and later paste values separated by commas in one line for easy to use in SQL's IN statement.
As possible way of implementation that I would suggest to add new option in Preferences dialog of application.

**Comment by serge-rider** [comment]
You can use advanced copy (<kbd>ctrl</kbd> +<kbd>shift</kbd>+<kbd>c</kbd>). 
It supports columns/rows separators config.

**Comment by mstup** [comment]
Yep, I see it.
But provided options are useless in such case.

Take a look at table with example:
--------------
| id | name |
--------------
| 1 |    a     |
| 2 |    b     |
| 3 |    c     |
| 4 |    d     |
| 5 |    e     |
--------------

I would like to select all values in **id** column, copy them into clipboard and paste the result like this:
1, 2, 3, 4, 5

If I copy values of **name** column with text I expect to got the following:
'a', 'b', 'c', 'd', 'e'

In Options dialog which did you mentions, there are no appropriate delimiter for row for do that trick.

**Comment by serge-rider** [comment]
You can do the first: set row delimiter to `,` set column delimiter to empty string and disable quoting.

Second one is more tricky. There is no option to force values quoting. 
I could add one.

**Comment by mstup** [comment]
Thank you, serge-rider
