### ISSUE TITLE
Office Export Plugin not included in Windows full version

### ISSUE THREAD

**Issue by Sargul** [serge-rider/dbeaver#1819]
Hi,

the plugin org.jkiss.dbeaver.data.office_1.1.0.jar and apache poi jar is not included in the windows full version of dbeaver 4.1.0 CE.

Is xlsx export only available in the eclipse plugin dbeaver version?

Regards

Charly

**Comment by serge-rider** [comment]
Office extension is optional (it is too big because of Apache POI bundle - and thus it wasn't included in CE).
Installation instructions: https://github.com/serge-rider/dbeaver/wiki/Extension-Office

More information will be provided in the next release (after this extension will be tested).

**Comment by collicalex** [comment]
Hi,
How to use a proxy to do that?

**Comment by serge-rider** [comment]
Try Preferences->Database->Drivers->HTTP Proxy

**Comment by collicalex** [comment]
Seems strange as the Proxy  here is not for "Database" but for "Install new software" feature.
Whatever it does not worked :/

Note that I've done the same in Eclipse, as DBeaver seems using the eclipse framework, in menu "Windows > Preferences > General > Network Connections"; and under Eclipse it's working fine (to find new eclipse package etc).

**Comment by collicalex** [comment]
I've updated to last version (4.1.1) but still not having office export plugin? 
I thought that it were include by default now?

**Comment by serge-rider** [comment]
No, it won't be included in CE version (at least we don't have such plans in near future).
It is included only in EE version (because distribution size doesn't matter there).

But we have plans to add some UI which will let users to install external DBeaver extensions easier (in a couple of clicks).
