### ISSUE TITLE
Transaction log button appears repeatedly

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#1821]
Hi,

My transaction button bar looks weird: the button appears repeatedly. Somebody have a tip?

![bug_dbeaver](https://user-images.githubusercontent.com/7952798/27539829-669b0944-5a54-11e7-9f21-8fd51949e7a6.png)

**Comment by serge-rider** [comment]
Can't reproduce.
Did you notice when extra button appears?

**Comment by jeisoncp** [comment]
Since I update to version 4.0.

**Comment by serge-rider** [comment]
Try to reset workspace UI (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace)

**Comment by jeisoncp** [comment]
It's works!

Thanks!

**Comment by serge-rider** [comment]
Great

**Comment by jeisoncp** [comment]
So, DBeaver crashed and started to duplicate again.

![new-blank](https://user-images.githubusercontent.com/7952798/27693180-11d981b6-5cbf-11e7-8e30-da23b9dc7e15.png)

**Comment by serge-rider** [comment]
Emm, is any information about crash? Logs?

**Comment by jeisoncp** [comment]
It crashed when I was using another program. I was switch back to DBeaver, I figured that it have be stopped.

**Comment by serge-rider** [comment]
I've been able to reproduce this.
And I'll add extra config fix for this toolbar.
