### ISSUE TITLE
4.1.0 build error

### ISSUE THREAD

**Issue by markuman** [serge-rider/dbeaver#1822]
After `git checkout tags/4.1.0 && git reset --hard` I start just `mvn package`.

        [INFO] --- tycho-compiler-plugin:0.26.0:compile (default-compile) @ org.jkiss.dbeaver.core ---
        [INFO] Compiling 10 source files to /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/target/classes
        [WARNING] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/perspective/DataSourceManagementToolbar.java:[39] 
            import org.eclipse.ui.internal.WorkbenchWindow;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        Discouraged access: The type 'WorkbenchWindow' is not API (restriction on classpath entry '/home/bergholz/.m2/repository/p2/osgi/bundle/org.eclipse.ui.workbench/3.108.3.v20170216-1539/org.eclipse.ui.workbench-3.108.3.v20170216-1539.jar')
        [WARNING] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/perspective/DataSourceManagementToolbar.java:[448] 
            if (workbenchWindow instanceof WorkbenchWindow) {
                                           ^^^^^^^^^^^^^^^
        Discouraged access: The type 'WorkbenchWindow' is not API (restriction on classpath entry '/home/bergholz/.m2/repository/p2/osgi/bundle/org.eclipse.ui.workbench/3.108.3.v20170216-1539/org.eclipse.ui.workbench-3.108.3.v20170216-1539.jar')
        [WARNING] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/perspective/DataSourceManagementToolbar.java:[449] 
            ((WorkbenchWindow) workbenchWindow).updateActionBars();
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        Discouraged access: The method 'WorkbenchWindow.updateActionBars()' is not API (restriction on classpath entry '/home/bergholz/.m2/repository/p2/osgi/bundle/org.eclipse.ui.workbench/3.108.3.v20170216-1539/org.eclipse.ui.workbench-3.108.3.v20170216-1539.jar')
        [WARNING] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/perspective/DataSourceManagementToolbar.java:[449] 
            ((WorkbenchWindow) workbenchWindow).updateActionBars();
              ^^^^^^^^^^^^^^^
        Discouraged access: The type 'WorkbenchWindow' is not API (restriction on classpath entry '/home/bergholz/.m2/repository/p2/osgi/bundle/org.eclipse.ui.workbench/3.108.3.v20170216-1539/org.eclipse.ui.workbench-3.108.3.v20170216-1539.jar')
        [INFO] ------------------------------------------------------------------------
        [INFO] Reactor Summary:
        [INFO] 
        [INFO] dbeaver ............................................ SUCCESS [  0.002 s]
        [INFO] org.jkiss.utils .................................... SUCCESS [  0.567 s]
        [INFO] org.jkiss.wmi ...................................... SUCCESS [  0.079 s]
        [INFO] org.jkiss.dbeaver.model ............................ SUCCESS [  0.590 s]
        [INFO] org.jkiss.dbeaver.core ............................. FAILURE [  1.550 s]
        [INFO] org.jkiss.dbeaver.core.application ................. SKIPPED
        [INFO] org.jkiss.dbeaver.core.eclipse ..................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.db2 .......................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.generic ...................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.derby ........................ SKIPPED
        [INFO] org.jkiss.dbeaver.ext.erd .......................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.ui.locks ..................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.firebird ..................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.import_config ................ SKIPPED
        [INFO] org.jkiss.dbeaver.ext.h2 ........................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.hsqldb ....................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.informix ..................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.mssql ........................ SKIPPED
        [INFO] org.jkiss.dbeaver.ext.mysql ........................ SKIPPED
        [INFO] org.jkiss.dbeaver.ext.netezza ...................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.oracle ....................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.phoenix ...................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.postgresql ................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.sqlite ....................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.vertica ...................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.teradata ..................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.exasol ....................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.wmi .......................... SKIPPED
        [INFO] org.jkiss.dbeaver.data.office ...................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.test ......................... SKIPPED
        [INFO] org.jkiss.dbeaver.core.feature ..................... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.db2.feature .................. SKIPPED
        [INFO] org.jkiss.dbeaver.ext.generic.feature .............. SKIPPED
        [INFO] org.jkiss.dbeaver.ext.mysql.feature ................ SKIPPED
        [INFO] org.jkiss.dbeaver.ext.oracle.feature ............... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.wmi.feature .................. SKIPPED
        [INFO] org.jkiss.dbeaver.ext.exasol.feature ............... SKIPPED
        [INFO] org.jkiss.dbeaver.ext.office.feature ............... SKIPPED
        [INFO] org.jkiss.dbeaver.rcp.feature ...................... SKIPPED
        [INFO] org.jkiss.dbeaver.runtime.feature .................. SKIPPED
        [INFO] org.jkiss.dbeaver.standalone.feature ............... SKIPPED
        [INFO] org.jkiss.dbeaver.ce.feature ....................... SKIPPED
        [INFO] DBeaver CE Repository .............................. SKIPPED
        [INFO] DBeaver CE Standalone .............................. SKIPPED
        [INFO] ------------------------------------------------------------------------
        [INFO] BUILD FAILURE
        [INFO] ------------------------------------------------------------------------
        [INFO] Total time: 01:58 min
        [INFO] Finished at: 2017-06-27T09:29:34+02:00
        [INFO] Final Memory: 194M/501M
        [INFO] ------------------------------------------------------------------------
        [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.26.0:compile (default-compile) on project org.jkiss.dbeaver.core: Compilation failure: Compilation failure: 
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/DBeaverUI.java:[131] 
        [ERROR] 	DBUserInterface.setInstance(this);
        [ERROR] 	                ^^^^^^^^^^^
        [ERROR] The method setInstance(DBUICallback) in the type DBUserInterface is not applicable for the arguments (DBeaverUI)
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetPersister.java:[392] 
        [ERROR] 	super(CoreMessages.controls_resultset_viewer_job_update, executionContext);
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetPersister.java:[783] 
        [ERROR] 	super("Refresh rows", context);
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/perspective/DataSourceManagementToolbar.java:[111] 
        [ERROR] 	super(CoreMessages.toolbar_datasource_selector_action_read_databases, context);
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLContextInformer.java:[399] 
        [ERROR] 	super("Find object '" + objectName + "'", executionContext);
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/sql/GenerateMultiSQLDialog.java:[159] 
        [ERROR] 	final DataSourceJob job = new DataSourceJob(jobName, getExecutionContext()) {
        [ERROR]             public Exception objectProcessingError;
        [ERROR]             @Override
        [ERROR]             protected IStatus run(final DBRProgressMonitor monitor)
        [ERROR]             {
        [ERROR]                 final DataSourceJob curJob = this;
        [ERROR]                 DBeaverUI.asyncExec(new Runnable() {
        [ERROR]                     @Override
        [ERROR]                     public void run() {
        [ERROR]                         scriptListener.beginScriptProcessing(curJob, objects);
        [ERROR]                     }
        [ERROR]                 });
        [ERROR]                 monitor.beginTask(jobName, objects.size());
        [ERROR]                 try (DBCSession session = getExecutionContext().openSession(monitor, DBCExecutionPurpose.UTIL, jobName)) {
        [ERROR]                     for (int i = 0; i < objects.size(); i++) {
        [ERROR]                         if (monitor.isCanceled()) {
        [ERROR]                             break;
        [ERROR]                         }
        [ERROR]                         final int objectNumber = i;
        [ERROR]                         final T object = objects.get(i);
        [ERROR]                         monitor.subTask("Process " + DBUtils.getObjectFullName(object, DBPEvaluationContext.UI));
        [ERROR]                         objectProcessingError = null;
        [ERROR]                         DBeaverUI.asyncExec(new Runnable() {
        [ERROR]                             @Override
        [ERROR]                             public void run() {
        [ERROR]                                 scriptListener.beginObjectProcessing(object, objectNumber);
        [ERROR]                             }
        [ERROR]                         });
        [ERROR]                         try {
        [ERROR]                             final List<String> lines = objectsSQL.get(object);
        [ERROR]                             for (String line : lines) {
        [ERROR]                                 try (final DBCStatement statement = DBUtils.makeStatement(session, line, false)) {
        [ERROR]                                     if (statement.executeStatement()) {
        [ERROR]                                         try (DBCResultSet resultSet = statement.openResultSet()) {
        [ERROR]                                             // Run in sync because we need result set
        [ERROR]                                             DBeaverUI.syncExec(new Runnable() {
        [ERROR]                                                 @Override
        [ERROR]                                                 public void run() {
        [ERROR]                                                     try {
        [ERROR]                                                         scriptListener.processObjectResults(object, statement, resultSet);
        [ERROR]                                                     } catch (DBCException e) {
        [ERROR]                                                         objectProcessingError = e;
        [ERROR]                                                     }
        [ERROR]                                                 }
        [ERROR]                                             });
        [ERROR]                                         }
        [ERROR]                                         if (objectProcessingError != null) {
        [ERROR]                                             break;
        [ERROR]                                         }
        [ERROR]                                     } else {
        [ERROR]                                         DBeaverUI.syncExec(new Runnable() {
        [ERROR]                                             @Override
        [ERROR]                                             public void run() {
        [ERROR]                                                 try {
        [ERROR]                                                     scriptListener.processObjectResults(object, statement, null);
        [ERROR]                                                 } catch (DBCException e) {
        [ERROR]                                                     objectProcessingError = e;
        [ERROR]                                                 }
        [ERROR]                                             }
        [ERROR]                                         });
        [ERROR]                                     }
        [ERROR]                                 }
        [ERROR]                             }
        [ERROR]                         } catch (Exception e) {
        [ERROR]                             objectProcessingError = e;
        [ERROR]                         } finally {
        [ERROR]                             DBeaverUI.asyncExec(new Runnable() {
        [ERROR]                                 @Override
        [ERROR]                                 public void run() {
        [ERROR]                                     scriptListener.endObjectProcessing(object, objectProcessingError);
        [ERROR]                                 }
        [ERROR]                             });
        [ERROR]                         }
        [ERROR]                         monitor.worked(1);
        [ERROR]                     }
        [ERROR]                 } finally {
        [ERROR]                     monitor.done();
        [ERROR]                     DBeaverUI.asyncExec(new Runnable() {
        [ERROR]                         @Override
        [ERROR]                         public void run() {
        [ERROR]                             scriptListener.endScriptProcessing();
        [ERROR]                         }
        [ERROR]                     });
        [ERROR]                 }
        [ERROR]                 return Status.OK_STATUS;
        [ERROR]             }
        [ERROR]         };
        [ERROR] 	                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/runtime/sql/SQLQueryJob.java:[117] 
        [ERROR] 	super(name, executionContext);
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/data/editors/ReferenceValueEditor.java:[313] 
        [ERROR] 	super(
        [ERROR]                 CoreMessages.dialog_value_view_job_selector_name + valueController.getValueName() + " possible values",
        [ERROR]                     valueController.getExecutionContext());
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/sql/GenerateSQLDialog.java:[115] 
        [ERROR] 	DataSourceJob job = new DataSourceJob(jobName, executionContext) {
        [ERROR]             @Override
        [ERROR]             protected IStatus run(DBRProgressMonitor monitor)
        [ERROR]             {
        [ERROR]                 try (DBCSession session = getExecutionContext().openSession(monitor, DBCExecutionPurpose.UTIL, jobName)) {
        [ERROR]                     for (String line : scriptLines) {
        [ERROR]                         DBCStatement statement = DBUtils.makeStatement(session, line, false);
        [ERROR]                         try {
        [ERROR]                             statement.executeStatement();
        [ERROR]                         } finally {
        [ERROR]                             statement.close();
        [ERROR]                         }
        [ERROR]                     }
        [ERROR]                 } catch (DBCException e) {
        [ERROR]                     return GeneralUtils.makeExceptionStatus(e);
        [ERROR]                 }
        [ERROR]                 return Status.OK_STATUS;
        [ERROR]             }
        [ERROR]         };
        [ERROR] 	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetJobAbstract.java:[33] 
        [ERROR] 	super(name, executionContext);
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor DataSourceJob(String, DBCExecutionContext) is undefined
        [ERROR] /home/bergholz/git/dbeaver_source/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/DBeaverCore.java:[221] 
        [ERROR] 	new KeepAliveJob(this).scheduleMonitor();
        [ERROR] 	^^^^^^^^^^^^^^^^^^^^^^
        [ERROR] The constructor KeepAliveJob(DBeaverCore) is undefined
        [ERROR] 15 problems (11 errors, 4 warnings)
        [ERROR] -> [Help 1]
        [ERROR] 
        [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
        [ERROR] Re-run Maven using the -X switch to enable full debug logging.
        [ERROR] 
        [ERROR] For more information about the errors and possible solutions, please read the following articles:
        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
        [ERROR] 
        [ERROR] After correcting the problems, you can resume the build with the command
        [ERROR]   mvn <goals> -rf :org.jkiss.dbeaver.core

Any ideas?
I'm using `jdk8-openjdk 8.u131-1` on Arch Linux.

**Comment by serge-rider** [comment]
Try `mvn clean package`

**Comment by markuman** [comment]
Thx. It works now.
