### ISSUE TITLE
[Feature Request] Script tab context menue: copy path, open path in explorer, rename file

### ISSUE THREAD

**Issue by keen85** [serge-rider/dbeaver#1825]
I would really appreciate it, if the **context menu** of a **script editor tab** would feature the following commands:

1. Open file path in explorer
2. Copy file path to clipboard
3. Rename file

Just like this:
![20170628_script_editor_tab_context_menue](https://user-images.githubusercontent.com/29750255/27629229-f08bd1b2-5bf1-11e7-9085-0cdc9152d93c.png)

Keep up the good work.

Thank you very much.

**Comment by serge-rider** [comment]
Good point.

**Comment by serge-rider** [comment]
![default](https://user-images.githubusercontent.com/6398845/27712420-9c3715ec-5d2f-11e7-9ccc-8d7125d68aae.png)

**Comment by keen85** [comment]
:flushed: damn!
That was fast! :smile:

Cheers mate! :+1:

**Comment by sargons** [comment]
It was here now it's gone again...no right click to copy file path
