### ISSUE TITLE
Windows 10 Dark Theme Alignment Issue

### ISSUE THREAD

**Issue by nealrout** [serge-rider/dbeaver#1829]
After the 4.1.0 release the Dark theme has resulted in the Database Navigator having alignment issues.  I have both  a Windows 7 and 10 computer, and I only see this on my Windows 10 machine.

Obviously this is a very minor issue, I just thought I'd call it out if no one else did.
![alignmentissue](https://user-images.githubusercontent.com/21213885/27657033-457725d8-5c19-11e7-974f-6f84364aec77.PNG)

**Comment by serge-rider** [comment]
I can't reproduce that.
Please try to reset workspace  (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace) - maybe it is a glitch after upgrade.
