### ISSUE TITLE
Requires JRE 6

### ISSUE THREAD

**Issue by bherila** [serge-rider/dbeaver#183]
It says on the site here that the package requires JDK 1.7 but the binaries all require the legacy Java SE 6 runtime. Would it be possible to upload some new builds so that it is not required to install this deprecated JRE?

**Comment by bherila** [comment]
Installing JDK 8 fixed this, similar to: 

https://github.com/serge-rider/dbeaver/issues/133

But the issue remains that the error message is not ideal.

**Comment by serge-rider** [comment]
This message (about JRE 6) isn't triggered by DBeaver, it is a MacOS-specific system warning.
Unfortunately I can't fix it. It is a well-known problem of many Eclipse-based apps on Mac (http://stackoverflow.com/questions/26847411/to-open-eclipse-you-need-to-install-the-legacy-java-se-6-runtime)

The only solution is to have correct Java version.
