### ISSUE TITLE
Not able to connect cassandra from dbeaver

### ISSUE THREAD

**Issue by sharmaji007** [serge-rider/dbeaver#1830]
Error
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /xx.xxx.xx.xx:9042 (com.datastax.driver.core.exceptions.TransportException: [/xx.xxx.xx.xx:9042] Cannot connect))

**Comment by fabiopedrosa** [comment]
@serge-rider I also get this often, mostly because of connection-timeout, but I don't think your JDBC driver allows for that parameter.

**Comment by serge-rider** [comment]
Timeouts config issue will be tracked in #2108
Closing for now.
If connect problem is not related to network timeout then please provide more details (SSH, Cassandra version, etc) and reopen.
