### ISSUE TITLE
Refresh objects

### ISSUE THREAD

**Issue by lrweck** [serge-rider/dbeaver#1833]
Hello, 

I noticed that if I edit a procedure, save it, click on the procedure in the database navigator and refresh it (not the procedures folder, click on the procedure itself), generating a DDL of the procedure does not show the changes I've made.

Thanks!

**Comment by serge-rider** [comment]
What database?

**Comment by lrweck** [comment]
PostgreSQL 9.6.2

**Comment by serge-rider** [comment]
Can't reproduce. 
How do you change procedure - in procedure editor, in SQL editor or in some external program?
