### ISSUE TITLE
[question] Flat files (CSV) connection: how to set data type?

### ISSUE THREAD

**Issue by dariopnc** [serge-rider/dbeaver#1837]
I have a CSV file with a column containing dates values (eg. 30/01/2017) when I export them to a database table in a data column, weird things happen. I suppose this is due to locale-specific settings, could this be?

Is there a way for me to set what data is stored in a column and, possibly, the format for dates?

**Comment by serge-rider** [comment]
Yes, this can be done in driver connection settings.
See Driver Properties at http://csvjdbc.sourceforge.net/doc.html

**Comment by dariopnc** [comment]
for what I read it is COLUMN_NAME specific and applies to every table (file) in the connection (folder)

I tried but it doesn't seem to work, anyway
