### ISSUE TITLE
DB2-Not able to view and bind variables whiile calling procedure

### ISSUE THREAD

**Issue by shahnaman2001** [serge-rider/dbeaver#1839]
I am calling db2 procedure like 

CALL testschema.testproc('11','x','x',?,?,?,?,?,?,?,?,?,?)

which is giving only 
updatedrows
Query
finish time.

the "?" are out variables and I need to see the values of those. How can I make it as bind variables / output varaibles.

**Comment by serge-rider** [comment]
Stored procedures output variables are not yet supported for DB2.

**Comment by serge-rider** [comment]
Out parameters binding support will be added in the next version
