### ISSUE TITLE
Execution fails at launch: "Unable to acquire application service"

### ISSUE THREAD

**Issue by pixeline** [serge-rider/dbeaver#1842]
I downloaded then installed DBeaver CE on a Mac Os X 10.11.6

The startup interrupts with a Fatal Error prompting to check the log, which contains this: 
`
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
`

I don't have eclipse on this computer but DBeaver does not list it as a requirement.

Full log (zipped so github accepts it as attachment):
[1499146063932.log.zip](https://github.com/serge-rider/dbeaver/files/1121056/1499146063932.log.zip)

**Comment by sgauge** [comment]
Hi, have you checked if JRE 1.8+ is installed ? Had the same message before reinstalling with JRE...

**Comment by pixeline** [comment]
Just tried that. I installed  this ( http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html ) but the same symptom and error.

**Comment by serge-rider** [comment]
You need to download and install JDK (not JRE) - http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by pixeline** [comment]
That works. Thank you!!

**Comment by khodrog** [comment]
Thank you @serge-rider  it's work 100%

**Comment by excal1bu7** [comment]
> Thank you @serge-rider it's work 100%

Not works actually.. i have only jdk and get error:
`java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).`
now i want to try download jre

upd: install jdk then reinstall dbeaver and then it works..

**Comment by RewriteH** [comment]
really.. not funny
![image](https://user-images.githubusercontent.com/57995626/126950613-c7dffeb1-1fc0-415e-a569-c9e030b53a63.png)
