### ISSUE TITLE
Unable to connect - Please specify a connection character set

### ISSUE THREAD

**Issue by SynapseUser** [serge-rider/dbeaver#1843]
Hi -
Using DBeaver with a Firebird database. Whenever I try to connect, I get the error - That there is no connection character set specified. Please see attached image

![clipboard-1](https://user-images.githubusercontent.com/20554202/27822855-0978f810-609f-11e7-8568-97dec405ac4c.jpg)

**Comment by sgauge** [comment]
Hi, simply set the charSet property when creating the connection :

![image](https://user-images.githubusercontent.com/29884017/27823888-f7b84bce-60aa-11e7-93c2-1517f3d6b737.png)

**Comment by SynapseUser** [comment]
Ok thanks - yes that worked! I was loking for some sort of drop-down list with char Set options, but could not see any and did not know syntax to manually add connection properties.

Thanks,
