### ISSUE TITLE
Floating help window colors not readable

### ISSUE THREAD

**Issue by brossaip** [serge-rider/dbeaver#1846]
Hi.
I am running dbeaver in Kde with compiz-reloaded and the floating windows that appear when the mouse is over a button are unreadable:
![image](https://user-images.githubusercontent.com/8513129/27835859-219b7db2-60dd-11e7-88ec-4fce2e4aefbb.png)

I have tried to change the color in "Colors and Fonts", Basic, "Content Assist background color" and "Content Assist foreground color", but they aren't affected by these options.

**Comment by serge-rider** [comment]
This seems to be a known SWT bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=484742
Probably will be fixed in the next Eclipse version. And automatically fixed in DBeaver as soon as we'll migrate to E4.7.

**Comment by brossaip** [comment]
Thanks for your answer.

Cheers,
Josep Bonet

2017-07-09 17:14 GMT+02:00 Serge Rider <notifications@github.com>:
