### ISSUE TITLE
Don't check for updates when checking for updates is disabled

### ISSUE THREAD

**Issue by bartlomiejb** [serge-rider/dbeaver#1847]
Tested versions: DBeaver CE 4.0.8, 4.1.0

I have the following settings in Window -> Preferences:
Install/Update -> Automatic Updates: unchecked "Automatically find new updates and notify me"

Despite this there is a HTTP request for http://dbeaver.jkiss.org/product/version.xml during startup (somewhere else?).

Expected behaviour: no external requests coming from the program when updates are disabled.

**Comment by serge-rider** [comment]
Right option is: Preferences->Database->Automatic updates check.

Install/Update -> Automatic Updates is Eclipse specific option. I will disable it (as it is doesn't make sense).

**Comment by bartlomiejb** [comment]
Well, I have this option unchecked, too. It doesn't help, there is still HTTP request for http://dbeaver.jkiss.org/product/version.xml few seconds after start.

**Comment by serge-rider** [comment]
Yep, DBeaver always reads version.xml. 
This option affects only on version update dialog visibility.
I'll fix this too, thanks for noticing.

**Comment by allanlaal** [comment]
issue has reappeared as of 7.0.1

**Comment by tari** [comment]
The relevant setting seems to have moved to User Interface (no subcategory), presumably since 7.0.
![image](https://user-images.githubusercontent.com/506181/103858724-f82ba780-510c-11eb-9536-46186280dd48.png)

**Comment by jzvikart** [comment]
I'm using version 21.1.0.202106021338 and I have unchecked Window -> Preferences -> General -> Install/Update -> Automatic Updates -> Automatically find new updates and notify me.

In spite of that, DBeaver keeps checking for new versions and popping up a "new version available" dialog on start.

How do I disable this?
