### ISSUE TITLE
[Firebird] Set precision while adding new column

### ISSUE THREAD

**Issue by Apcio** [serge-rider/dbeaver#1848]
When I edit table and try to add new column with data type float, double precision, decimal .... I can't set precision (only length). After save, it creates DDL like DECIMAL(8, 0), instead of DECIMAL(8, 2).

**Comment by serge-rider** [comment]
For numbers precision is the same as length. 
Do you mean scale (number of fractional digits)? This is supported for MySQL, PostgreSQL and Oracle but not for generic driver.

**Comment by Apcio** [comment]
Yes. Why it isn't supported?

When I set Data Type DECIMAL with LENGTH 12 I would like set PRECISION to 2, but DBeaver generate DDL:
ALTER TABLE BLOKADY ADD TEST DECIMAL(12,0) ;

When I check table in another program it shows me:
![image](https://user-images.githubusercontent.com/11940927/28153271-e32b421e-67a4-11e7-845b-1fb505761039.png)



But DBEaver shows:
![image](https://user-images.githubusercontent.com/11940927/28153040-be7efbe6-67a3-11e7-9fd5-9133668470ef.png)


So, when I execute SQL:
INSERT INTO BLOKADY VALUES(99998, 'test2', CURRENT_TIME, 153.54)

I have in result:
![image](https://user-images.githubusercontent.com/11940927/28153170-5694b95c-67a4-11e7-912d-9b83325257c5.png)

**Comment by serge-rider** [comment]
This is scale - not precision.
I'll add numeric scale support in the next version (for generic driver).
