### ISSUE TITLE
[PostgreSQL] Only appears one database in Dbeaver when there are three

### ISSUE THREAD

**Issue by Rathdor** [serge-rider/dbeaver#1849]
It happens when the field "Database" in "Connection Settings" is empty. If i fill this field, it connects succesfully.

When empty, the only database that shows is "postgres".

I tried with driver 42.0.0 and driver 42.1.1. I use Dbeaver 4.1.0.

Greetings.
![dbeaver](https://user-images.githubusercontent.com/29913023/27854577-9d38f960-6167-11e7-9b83-0f8a6ee1849d.jpg)

**Comment by serge-rider** [comment]
Check "Show non-default databases" option in connection properties dialog.

**Comment by Rathdor** [comment]
Ok, i didn't see that option. Thank you very much.

**Comment by stolotti** [comment]
Shouldn't be enabled by default?

**Comment by BONDbATIF** [comment]
By default, it should be enabled , I spent almost two days .

**Comment by BONDbATIF** [comment]
> Shouldn't be enabled by default?

By default, it should be enabled, I spent almost two days.

**Comment by dausruddin** [comment]
I don't understand why it is disabled, but it surely confused me a lot.

**Comment by chipytux** [comment]
Thanks @serge-rider @BONDbATIF, did you save my time.

**Comment by jhegner** [comment]
Tks @BONDbATIF

**Comment by boblancer** [comment]
If someone involve is reading this please make enable by default for the greater good of humanity.

**Comment by januwA** [comment]
This problem makes me want to uninstall dbeaver ...
