### ISSUE TITLE
toggle line comment when selection has comment

### ISSUE THREAD

**Issue by zmila** [serge-rider/dbeaver#1850]
There is little issue with toggle line comment on selection, which contains commented lines. 

When I have pasted into Script window a text with "--" at begin.
Say query result in text form:
```
ID    |Type |Value |
------|-----|------|
12340 |Int  |0     |
12341 |Int  |1     |

```

Then I select the three lines and press Ctrl+/ to comment the result
The second line (with -- at start) become shorter, it is "uncommented"

```

--ID    |Type |Value |
----|-----|------|
--12340 |Int  |0     |
--12341 |Int  |1     |

```

I dont know, if it's common problem in Eclipse, or it can be configured in DBeaver.

**Comment by serge-rider** [comment]
This is DBeaver feature, not Eclipse. 
i'm not sure what is the best way to fix this. Currently DBeaver processes each line separately and toggles comment according to current line state.

As a workaround you can use multiline comments (<kbd>ctrl+shift+/</kbd>)

**Comment by serge-rider** [comment]
I've fixed comment action so it will add comment to every line if the first line of selection wasn't commented. And remove comments otherwise.
