### ISSUE TITLE
[Postgres-XL ] Unable to retrieve data from table

### ISSUE THREAD

**Issue by csyoong28** [serge-rider/dbeaver#1851]
Using DBeaver trying to connect to Postgres-XL, able to view table columns details but unable to retrieve data. Error thrown is as shown
![untitled picture](https://user-images.githubusercontent.com/6831056/27866794-49ade324-61ca-11e7-8212-506482aaa387.png)

When click on the "Test connection" button, it is successful as shown
![untitled picture2](https://user-images.githubusercontent.com/6831056/27866795-49c09a64-61ca-11e7-80d1-3a94518c9d6b.png)

**Comment by serge-rider** [comment]
Please post error stacktrace (from Error Log view or from log file: https://github.com/serge-rider/dbeaver/wiki/Log-files).

Also you could try to switch to auto-commit mode (in main toolbar/menu)

**Comment by csyoong28** [comment]
I am suspecting this maybe the issue of Postgres-XL, but my colleague who
is using Valentina Studio 7 is able to access without issue

**Comment by serge-rider** [comment]
This is possible. DBeaver wasn't tested with Postgres-XL.
But if you will post error stacktrace then maybe it will be possible to fix the issue.

**Comment by csyoong28** [comment]
I have already attached the log file in previous email too. I will attach
them again here

**Comment by serge-rider** [comment]
Please add logs in GitHub comment (by drag-n-drop) or send it to me on serge@jkiss.org. 
You can't attach files when you reply to GitHub by email.

**Comment by csyoong28** [comment]
Sorry, not notice about that. 
Attached are the log files involved

[log.txt](https://github.com/serge-rider/dbeaver/files/1151617/log.txt)
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/1151618/dbeaver-debug.txt)

**Comment by kyleflan** [comment]
FYI: I work with a few Postgres-XL instances regularly. The workaround I use is to use the PostgreSQL (Generic) driver. You lose some functionality for doing things like database backups/restores, but I've been using it for 6+ months without other issues.

**Comment by csyoong28** [comment]
@kyleflan thanks a lot, it is able to work as you said, using the PostgreSQL (Generic) driver able to work properly. Thanks a lot. 
But the description of PostgreSQL (Generic) driver of "PostgreSQL JDBC driver. Can be used for old PostgreSQL server versions (before 8.x)." maybe can change a bit, usable for Postgres-XL

**Comment by serge-rider** [comment]
According to log this error happens when DBeaver executes query like `select * from table`. I doubt that using generic driver will resolve this.
@csyoong28 did you try to execute SQL queries in SQL editor?

Also this may be related to Postgres XL config (https://stackoverflow.com/questions/38037716/issue-with-datanodes-on-postgres-xl-cluster).

**Comment by csyoong28** [comment]
As for now, using generic driver option do works well, able to execute SELECT statement in editor without problem. 
I do go through the stackoverflow issue, but I am not sure if that is the solution since Valentina Studio is working correctly.

**Comment by kyleflan** [comment]
@serge-rider I think I've tracked down the cause for this and the reason for the generic driver working but not the latest driver. See issue #1896.

**Comment by serge-rider** [comment]
Great
