### ISSUE TITLE
[Postgres-XL ] Can't select column of jsonb type from table

### ISSUE THREAD

**Issue by minrenkon** [serge-rider/dbeaver#1854]
Thanks!

**Comment by kyleflan** [comment]
If you're positive this isn't a permissions issue on the database, use the PostgreSQL (Generic) driver to connect to your XL instance. The standard PostgreSQL driver had issues for me when connecting to XL (granted this was a few versions of DBeaver and the driver ago).

Using 4.1.0 against Postgres-XL 9.5r1.4, the following script works and returns data as expected. 

```
CREATE TABLE temp.temp_jsonb (
	id serial,
	title varchar,
	pricepackage jsonb
	)
	
INSERT INTO temp.temp_jsonb 
	(title, pricepackage)
	VALUES
	('Title One', '{
	"id": 1,
	"title": "Title One",
	"description": "This is a long description"
	}');

SELECT * FROM temp.temp_jsonb;
```

![image](https://user-images.githubusercontent.com/5608074/28086011-1edfbcbc-6643-11e7-9191-eb4dd05e382c.png)


Opening the temp_jsonb table by double-clicking in the Database Navigator also works as expected.

**Comment by minrenkon** [comment]
Thanks! Can tell me you are using the version of PostgreSQL JDBC jar file.

Below is I use the software.

![1](https://user-images.githubusercontent.com/29967841/28459066-966d459e-6e3e-11e7-813d-87d7a55ca27f.PNG)

![3](https://user-images.githubusercontent.com/29967841/28459082-a77ceea2-6e3e-11e7-86f6-ee04583748ae.PNG)

![2](https://user-images.githubusercontent.com/29967841/28459090-b43f5f4e-6e3e-11e7-991c-a3dca05b33b9.PNG)

**Comment by kyleflan** [comment]
@minrenkon I was able to use the standard Postgres Driver by editing the Client Application Name. Go to Preferences -> DBeaver -> Connections. Check the box for "Override client application name" and set the value to "DBeaver". Restart DBeaver, and then you should be able to connect and query your XL instance. 

See #1896 for more info on why this is needed with Postres-XL.
