### ISSUE TITLE
Export to cassandra error

### ISSUE THREAD

**Issue by marcello-lodi** [serge-rider/dbeaver#1859]
While trying to export a table from Postgres to Cassandra, there is an issue with data types.
In particular the float types are exported as int.
![captura de pantalla 2017-07-08 a las 8 28 10](https://user-images.githubusercontent.com/6000058/27983614-1ff38eb2-63b9-11e7-825c-46bbe336a2cd.png)

**Comment by serge-rider** [comment]
This is not the only problem with Cassandra data types mapping. Thanks for reminding.

This will be fixed in the next version.
