### ISSUE TITLE
Color by column - not working on colored connection type

### ISSUE THREAD

**Issue by amosmoss** [serge-rider/dbeaver#186]
When I try color records by for a specific value, it only works on non-colored connection types. When I try to do this on colored connection types, no record coloring is taking place.

Thanks,

**Comment by serge-rider** [comment]
Never met this problem for months.
So I'll close it as non-reproducible.
If you still see it - please reopen.

**Comment by amosmoss** [comment]
Hi Serge,

I still see it in my current DBeaver version 3.7.3.

Please reopen (or tell me how to do it myself).
Thanks, 
Amos.

**Comment by serge-rider** [comment]
Can you post a screenshot or any other additional info about this issue?

Connections coloring and results coloring are completely unrelated so I have no clue has this can happen..

**Comment by amosmoss** [comment]
There's nothing to show, it just doesn't work.

![14756552120431560705085](https://cloud.githubusercontent.com/assets/16815760/19105853/f10f9b2c-8aec-11e6-91fe-7b727b783192.jpg)

**Comment by serge-rider** [comment]
Here is how it works on my machine:
![color-by-column](https://cloud.githubusercontent.com/assets/6398845/19108801/fb298434-8afa-11e6-9f52-c0dea50446bc.gif)

Note: currently coloring works for actual table columns  only. It doesn't work for constants and expression results (like in your query). So most likely your problem isn't in connection color but in executed queries.

You may create a feature request for further improvements of rows coloring..

**Comment by serge-rider** [comment]
For now I'll show error dialog when user tries to color by computed value.
