### ISSUE TITLE
DBeaver minimizes without asking for

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1860]
1. reset perspective
2. click on connection selector at top
3. click on any entry at the selection
4. (if DBeaver isn't minimized already:) click on postgresql schema selector while having connection selector open

Result: DBeaver minimizes/switches Window manager tab.

**Comment by GiantCrocodile** [comment]
It is even enough if I click on connection switcher and click again (same spot, don't move the cursor). DBeaver just gets minimized.

**Comment by serge-rider** [comment]
I can't reproduce this.
What's your OS/window manager?

**Comment by GiantCrocodile** [comment]
My system:
- Windows 10 Pro
- latest DBeaver version
- latest Java 8 version

Can I provide you with anything else?

**Comment by carlosspohr** [comment]
Hi there,

@GiantCrocodile , @serge-rider I just realized it while I was looking for some database at that combo, when I clicked on the borders of combo's list, all dbeaver main window just did a small/fast wink ...as minimized and maximized.
The image bellow, are the point where I did a single or double click to main window throws that small/fast wink.
![image](https://user-images.githubusercontent.com/637767/28254819-d11f7f06-6a86-11e7-9db4-be96edc5a5da.png)

I believe that can some bug or event that is triggered by click on combo's list, because on database or connection chances, some actions are invoked to refresh or repaint somethings on main window, etc.

PS: I don't remember about this error on previous releases, but I can check about it today at morning.

**Comment by GiantCrocodile** [comment]
`PS: I don't remember about this error on previous releases, but I can check about it today at morning.`

This didn't happen in previous releases (~ maybe 2-3 releases earlier) to me.

**Comment by serge-rider** [comment]
Still can't reproduce that :( Although I've tried every possible way to click on these combos.

**Comment by carlosspohr** [comment]
Uhmm,

First, it's not important or even critical, just a little bit strange. 

When I click in one of those combos, the option list is shown to me and the main window loses his focus, this focus is in selected combo. So, if user clicks in one of those list borders, and, select one item or click back on script editor or dbeaver's main window, that small/fast wink is triggered.

![image](https://user-images.githubusercontent.com/637767/28668212-327e3276-72a5-11e7-9523-4b0f78134dc4.png)

Looking at combo of driver type on default sql editor of Eclipse, it doesn't has that option list resizer:
![image](https://user-images.githubusercontent.com/637767/28668460-44899dc4-72a6-11e7-94fb-71d3dfb1e4cb.png)

I don't know how to explain it, but I think that option list resizer could be the cause of this abnormality.

**Comment by carlosspohr** [comment]
I also tried to record this problem using 'http://recordit.co/' app, but when it's recording my screen this 'bug' doesn't occur.

**Comment by carlosspohr** [comment]
Is that option list an dialog windows ?

**Comment by serge-rider** [comment]
Eventually I've reproduced that on another Win10 machine.

**Comment by serge-rider** [comment]
It was fixed (I doesn't appear on my local environment anymore) although I'm not 100% sure. Please check in 4.1.2 and reopen if it is still there.

**Comment by carlosspohr** [comment]
There is a PC here, where dbeaver minimizes another open window, usually Chrome. I'm not sure about that what is causing it's the fact of that combo of connections and databases are window, maybe their events as resize, moving, etc. are the root of this 'bug'.

What about using common combobox instead these customized combos?

PS: [4.1.2](https://github.com/serge-rider/dbeaver/milestone/45) release still has this strange behavior.

**Comment by carlosspohr** [comment]
Another one, once dbeaver is maximized, when you select one database through database combo, dbeaver minimizes. I tested it in 6 pcs with Windows 10, 3 of them have updates deactivated.

**Comment by serge-rider** [comment]
Yes, I also can see this on some machines (windows 10.1?).

**Comment by GiantCrocodile** [comment]
Issue is still there for me with latest release.

**Comment by serge-rider** [comment]
Yes, it was still there in 4.1.2.
Did you try to build from sources?

**Comment by GiantCrocodile** [comment]
I'm sorry then, I didn't build it this time from source as I thought it is already in latest release.

**Comment by carlosspohr** [comment]
Just providing some feedback about it, it's OK on ```4.1.3```.

Thanks.
