### ISSUE TITLE
Slow performance on Linux with MSSQL

### ISSUE THREAD

**Issue by andersks** [serge-rider/dbeaver#1862]
I am running DBeaver 4.0.5 Enterprise on Linux Mint 18. Attempting to open a MSSQL database that has a large number of table (4000+). I have waited 10 minutes for the list to refresh. It finally does. Problem exists with both the CE and Enterprise Linux versions. Problem does NOT exist with the Windows or Mac versions.

**Comment by ced75** [comment]
Hi,
This could also depend on the JDBC driver you are using? Which one is it?

Regards,
Cedric

**Comment by andersks** [comment]
Using the MSSQL Driver.



Kevin S. Anderson

**Comment by serge-rider** [comment]
Please test it in 4.1.1 version. There were a few performance improvements in database navigator view.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. Perhaps, the question was solved. It will be closed. However, if you think that it is actual just let us know.

**Comment by andersks** [comment]
The problem has NOT be resolved. I have tried, the newest version with both the MSSQL and jTDS drivers. On my Mac, the table list is close to instantaneous. On Linux it *seems* to take forever, normally at least 5 minutes or longer. This is with both the EE and CE editions. It renders the product unusable. Note, again, that there are 4,900 tables in the database.

**Comment by tati-kru** [comment]
@andersks thank you for checking. Reopen.

**Comment by serge-rider** [comment]
I don't think that this is related to MS SQL. Generally it looks like UI performance issue on Linux.

@andersks Could you make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) when DBeaver loads this long table list on Linux? As I can't reproduce it on my test Ubuntu.

**Comment by TheFuzzy** [comment]
@serge-rider I'm currently experiencing the same issue. [Here's my thread dump](https://github.com/serge-rider/dbeaver/files/1313469/thread-dump.txt).

Environment:
Ubuntu 16.04.3 LTS, Gnome Shell 3.18.5

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

DBeaver 4.2.1

**Comment by serge-rider** [comment]
This seems to be the same as #2152
