### ISSUE TITLE
dbeaver can't connect HBase1.2 using phoenix driver

### ISSUE THREAD

**Issue by Hackeruncle** [serge-rider/dbeaver#1863]
**ENV:**
DBeaver Enterprise (4.0.5)
Phoenix-4.9.0-cdh5.9.1+HBase1.2.0(CDH5.11 )

dbeaver can't connect HBase1.2 using phoenix driver.

**ERROR:**
Unexpected driver error occurred while connecting to database
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider

**Comment by Hackeruncle** [comment]
It‘s solved.
1.I can't use the own driver packages.

**2.I only use the one dirver jar with "phoenix-4.9.0-cdh5.9.1-client.jar", save the connection info.**
(must restart dbeaver, otherwise  can't connect the hbase with the above error message)

**3.Restart the dbeaver**, the you can find that dbeaver connect the hbase.

**Comment by serge-rider** [comment]
Thanks for info

**Comment by serge-rider** [comment]
We will change default driver configuration in 6.3.4 (see #6376)
