### ISSUE TITLE
How do i write a query with two connection of diffrent databases.

### ISSUE THREAD

**Issue by ravibiet08** [serge-rider/dbeaver#1865]
I am using oracle and postgres DB. I want to check migrated data from one DB to other. For this purpose i want to write minus query.

**Comment by serge-rider** [comment]
This is similar to #1804 (if I understood this correctly).
Perhaps we make feature request from this.

**Comment by tati-kru** [comment]
1804 is converted to feature request. This ticket will be closed as solved.
