### ISSUE TITLE
Autocompletion over multiple schema's

### ISSUE THREAD

**Issue by wilerjr** [serge-rider/dbeaver#1870]
Hello,

I saw the issue [PostgreSQL - schema and table autocompletion does not work #763](https://github.com/serge-rider/dbeaver/issues/763) and the [comment from jaroet](https://github.com/serge-rider/dbeaver/issues/763#issuecomment-303763403) saying that "for those who want autocompletion over multiple schema's. Version 3.6.10 does this the old way. So I will be using that." 

Is there any intention to include the completion "the old way" in newer versions? For those who works with large databases with multiple schemas and tables, this feature helps a lot.

Best Regards,

**Comment by serge-rider** [comment]
I can add an extra config option for that.
Because part of people want to see only current schema objects others want to see everything.

**Comment by wilerjr** [comment]
That would be awesome, @serge-rider .

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/29191787-855ffbe0-7e27-11e7-9b08-b083ae5fb7e3.png)
