### ISSUE TITLE
Keyword TABLES is missing from autocomplete.

### ISSUE THREAD

**Issue by 71GA** [serge-rider/dbeaver#1871]
When I am trying to check which tables are present in the database and what columns they have I use these queries: 

```
SHOW DATABASES;
USE <database name>;
SHOW TABLES; 
SHOW COLUMNS FROM <table name>;
```
I notice that keywords TABLES and COLUMNS aren't auto completed, while keyword DATABASES is. Could you please add the missing keywords?

**Comment by serge-rider** [comment]
What is your database? (`DATABASES` is shown as keyword for MySQL).

**Comment by 71GA** [comment]
I am using MariaDB.

**Comment by serge-rider** [comment]
Well, DATABASES is a keyword for MariaDB:
![default](https://user-images.githubusercontent.com/6398845/28154274-2da19f98-67b2-11e7-9756-cc28726c4bfb.png)
But `COLUMNS` isn't. 
In fact list of keywords is provided by driver. Maybe your driver version just doesn't do that.

Anyhow - I'll add DATABASES and COLUMNS keywords in MySQL dialect.

**Comment by 71GA** [comment]
Thank you.
