### ISSUE TITLE
When a connection change is attempted while a query is running, UI freezes and the connections dropdown is shown as if set to "always on top" [v4.0.2]

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#1872]
Database: DB2 luw 9.7
[v4.0.2] Sorry about not running the latest :) Not sure if this is reproducible in the latest version
Steps to reproduce: Issue a long-running query and try to change the connection from the dropdown by clicking on a new connection

![image](https://user-images.githubusercontent.com/419093/28130858-0268d2bc-66ed-11e7-9c5f-68a66928a3c3.png)

**Comment by serge-rider** [comment]
Yes, it is reproducible in the latest version.
Thanks for report
