### ISSUE TITLE
Change .dbeaver-data-sources.xml manually problem

### ISSUE THREAD

**Issue by Spoelle** [serge-rider/dbeaver#1877]
1 Create/Save a connection (SQL-Server) in DBeaver with 2 excluded Catalogs and a few excluded Tables
2 Close and reopen DBeaver program => all ok
3 Close DBeaver
4 Edit the file ".dbeaver-data-sources.xml" manually (add a Catalog exclude name)
5 Save file
6 Open DBeaver program -> connection is gone; the xml is at the same location on disk

When I look at the xml file I can not see anything wrong... Is it not possible to edit the xml file? I need to exclude a lot of Catalogs and tables so I want to change it in the file rather then via the wizard in DBeaver.

Thanks, Luc

**Comment by serge-rider** [comment]
OF course it is possible to edit .dbeaver-data-sources.xml manually.
Most likely you still made some mistake in xml. You could post example of your fix and I can test it.

**Comment by Spoelle** [comment]
Ok, thanks for the quick reply. I don't know what happened but it's working now...  :-/ The only difference is that the file was under source control (TFS); maybe something went wrong with a check-in/out?
I will try to force this again but for now all is ok! Thanks for your work because this is a very good program !
