### ISSUE TITLE
Aggregate Numbers on Highlight

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#188]
In other popular tools Excel, Aqua-studio you can preview aggregates as you highlight numbers.

As seen in aquastudio. (my humble opinion is that sum would be the most useful but the other aggregate options would be cool too).
![aquastudio](https://cloud.githubusercontent.com/assets/9246654/12800043/4b7bab7c-ca87-11e5-9cd6-697204834b38.gif)

**Comment by serge-rider** [comment]
Looks like a useful feature, I like it.
But not yet sure where to put this aggregate toolbar in existing UI..

**Comment by r-richmond** [comment]
I think there are two clean options.

1) In the bottom toolbar (like excel; my recommended location)
![image](https://cloud.githubusercontent.com/assets/9246654/12956929/4b52acba-cfdf-11e5-8838-072f7d82bd93.png)


2) Above the result set next to the sql filter
![image](https://cloud.githubusercontent.com/assets/9246654/12956912/357a95ec-cfdf-11e5-89b6-d8a5aa05a206.png)

**Comment by christian-macher** [comment]
+1
Would be a great feature! Preferred position: bottom toolbar!

**Comment by r-richmond** [comment]
Bumping as I think this a great feature and I don't want it to get stale/lost.

**Comment by serge-rider** [comment]
Yeah, I didn't forget about that. Honestly summer isn't the best season to make new features - I can't spend much time on coding. Vacations and other stuff.
I hope I'll back to this feature in the beginning of Autumn.

**Comment by serge-rider** [comment]
Initial version of this feature will be added in the next version.
You can show/hide special panel view on the right side of resultset (new feature in 3.7.3).
You can add/remove aggregate functions, switch grouping by attributes, copy/opaste values, etc.
![aggrgate-panel](https://cloud.githubusercontent.com/assets/6398845/17974194/befc31be-6aed-11e6-8d54-a9234a6f41d5.png)

Further improvements of this feature should be tracked in other issues.

**Comment by r-richmond** [comment]
Awesome! looking forward to trying this out.

**Comment by someotherdataguy** [comment]
Any chance of a select distinct count?

**Comment by serge-rider** [comment]
Sure, you can propose any number of useful aggregate functions. Usually it is pretty easy to add them.
Just create a new feature request.

Although if under "select distinct" you mean "ignore all duplicates during aggregation" then it'll be a bit more complicated (it will affect all functions). However - just create a feature request.
