### ISSUE TITLE
how to export multiple files by paging,can be imported into excel

### ISSUE THREAD

**Issue by bouyeijiang** [serge-rider/dbeaver#1881]
import into excel multiple sheets

**Comment by AndrewKhitrin** [comment]
Hello,

I thought about exporting data on several pages depending on the number of rows and\or column values(s) but it seemed to me that this featire is needed in very rare cases.

Сan you give me a brief description of your vision of multipage export.

Thanks,
Andrew

**Comment by bouyeijiang** [comment]
i need can be export into excel,and can be export into excel multi  sheets at a time

**Comment by AndrewKhitrin** [comment]
Done. Rows must be placed on different excel worksheet depends on rows count and (optional) column value. PR #1895
