### ISSUE TITLE
Install 4.1.0 error on Linux

### ISSUE THREAD

**Issue by javascrept** [serge-rider/dbeaver#1882]
installation of 4.1.0 times depends on the problem, but the Java I installed is 1.8

[root@localhost bao]# java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
[root@localhost bao]# rpm -ivh dbeaver-ce-4.1.0-stable.x86_64.rpm 
错误：依赖检测失败：
        jre >= 1.8 被 dbeaver-ce-0:4.1.0-stable.x86_64 需要

**Comment by GiantCrocodile** [comment]
How did you try to install it? Did you use `mvn package`?

**Comment by ceyhunnabiyev** [comment]
Please read this:
https://unix.stackexchange.com/questions/94091/rpm-failed-jre-dependency-even-though-that-jre-version-is-installed
