### ISSUE TITLE
Possibility to disable autocommit from command line

### ISSUE THREAD

**Issue by antonsjava** [serge-rider/dbeaver#1883]
Is there a possibility to start dbeaver with autocommit=false for connections specified on commandline?
Whenever I start dbeaver like this 
dbeaver.exe -con "name=me-tst|user=test|password=test|url=jdbc:oracle:thin:@localhost:1521:ME|driver=oracle|openConsole=true|folder=adhoc"
autocommit is activated. 
(I uncheck autocommit for all connection types - but it doesn't help)

**Comment by serge-rider** [comment]
Makes sense.
https://github.com/serge-rider/dbeaver/wiki/Command-Line has been updated
