### ISSUE TITLE
SQL Editor Background Color Doesn't Change

### ISSUE THREAD

**Issue by daturkel** [serge-rider/dbeaver#1884]
DBeaver Community Edition 4.1.0
macOS 10.12.5

"Enable Theming" is on.
Theme set to classic. 
Color and font theme set to Default.

When I go into the SQL Editor colors and change SQL Text Background, it never applies. Every other color seems to change properly except for the background.

**Comment by daturkel** [comment]
I was able to solve my problem, but there still seems to be a bug. Only once the General > Editors > Text Editors "Background Color" "System Default" checkbox is unchecked can this actually be set. And then you still have two separate places you can set it (on this page, or back on General > Appearance).

**Comment by serge-rider** [comment]
Thanks for useful information.

Unfortunately I can't change this - this behavior is defined by Eclipse framework.

**Comment by KubaMiszcz** [comment]
it is still occurs in Community Edition 7.2.4

**Comment by yinzhenzhixin** [comment]
hello there,

Is there a due date to fix this issue? Because it's hurt my eyes a lot....:(

**Comment by d9k** [comment]
@serge-rider, please reopen issue or tell us about workaround

**Comment by E1izabeth** [comment]
Maybe you could try using Darkest Dark theme or Eclipse Color Theme extensions https://dbeaver.com/docs/wiki/Eclipse-extensions/

**Comment by d9k** [comment]
@E1izabeth, thanks, it worked! :slightly_smiling_face:

**Comment by a4ff7810** [comment]
Not sure you @mentioned who you meant to, @d9k :)? Don't think I contributed anything to this issue in particular 😅?

**Comment by machinewu** [comment]
To change the editor background color, you can append the following line (or change it if it exists) in the file: `%APPDATA%\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.eclipse.ui.editors.prefs`
```
AbstractTextEditor.Color.Background=30,31,34
```
The three numbers above represent **R**ed=`30`, **G**reen=`31`, and **B**lue=`34` respectively.
Testing DBeaver v24.1 was successful.
