### ISSUE TITLE
Invalidate/Reconnect takes a long time 

### ISSUE THREAD

**Issue by shireexue** [serge-rider/dbeaver#1885]
Invalidate/Reconnect takes a long time after being disconnected to the database.  Restarting the software is the only way to speed it up.  Can this be improved? Thanks

**Comment by serge-rider** [comment]
What database? Maybe some steps to reproduce?

**Comment by petromir** [comment]
Steps to reporoduce:

**Comment by ausiddiqui** [comment]
Same situation using Teradata 15. Takes a very long time, like nearly 2 minutes to invalidate/reconnect on average.

**Comment by cayhorstmann** [comment]
I have the same issue with the PostgreSQL service on Google cloud. If I take a break from working with the database, something times out, and then the program hangs trying to "invalidate" the connection. I have never been able to reconnect without quitting and restarting DBeaver.

**Comment by serge-rider** [comment]
This always happens in case of broken SSH tunnel (because socket timeouts doesn't work anymore).
I'll add a workaround in invalidate action.

**Comment by serge-rider** [comment]
Invalidate job fixed (now it won't wait for socket timeout).
But I can't test all possible network failures. If this issue will still remain - please post some more details (e.g. screenshot and/or logs) and reopen.

**Comment by yuriscom** [comment]
in version 5.0.4 community edition for mac it's still a big problem. Every time i have to wait for socket timeout up to 5-10 minutes. disconnect + connect is not solving it either.

**Comment by AGVeem** [comment]
Hmm...  more than 3 years have passed and the issue is still there

**Comment by mib32** [comment]
Still there

**Comment by surz-p** [comment]
Problem persists for the version on MAC even today.

**Comment by emil-k** [comment]
I second that, whenever I close my mac, and it goes to sleep, it takes a couple of minutes to re-connect, in practice I must close the application and restart it, whenever I close the lid of my mac, it's really cumbersome. I don't think this should be a closed issue.

**Comment by TimNZ** [comment]
Bump!

**Comment by E1izabeth** [comment]
Please create a new issue, if it's actual for you again
