### ISSUE TITLE
Delete > 1 table at once: wrong SQL command executed

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1888]
1. Create tables test1 and test2
2. select both tables and press delete
3. click on preview SQL: You see that it will delete test1 and test2 not.
4. Press yes for all

Result: table2 deleted, table1 not. So previewed command doesn't mention the correct table and I would have expected both tables to be deleted, not only one. This happens with postgresql.

**Comment by serge-rider** [comment]
Thanks for report.
After SQL preview DBeaver must show the same confirmation again.
