### ISSUE TITLE
DBeaver occasionally hangs while establishing connection over a slow network

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#1891]
Hi, 
DBeaver starts consuming 100% CPU when not able to connect in timely fashion, the UI also freezes (it's not refreshing). It always hangs at the step on the attached screenshot. The only way out is terminating its process. I've attached the thread-dump for convenience.

The version is 4.1.0/64bits on win10, but the issue has been here for several versions now. It also appears on Mac.

[thread-dump.txt](https://github.com/serge-rider/dbeaver/files/1152563/thread-dump.txt)

![image](https://user-images.githubusercontent.com/13131218/28267839-8a93ab88-6b04-11e7-8859-eb0cfc288c60.png)

**Comment by serge-rider** [comment]
This may happen if your database has huge number of tables/data types (each table in PG produces 2 data types).

Workaround: try to use `PostgreSQL Generic` driver. It shouldn't cache all existing data types on connect.

**Comment by petromir** [comment]
Can we have the option to change the driver type on exsiting connections, so that I don't need to recreate them.

**Comment by gogosofta** [comment]
@serge-rider the workaround you proposed solves the connection issue, but introduces another, which is just as blocking/boring as the previous one:
![image](https://user-images.githubusercontent.com/13131218/28305393-2664e32a-6ba4-11e7-90a9-a5198f4c9357.png)

**Comment by serge-rider** [comment]
This is a bug in DBeaver. Thanks for details.
