### ISSUE TITLE
Green color for successful results in Query Manager appears yellow for color blind users

### ISSUE THREAD

**Issue by mloupe** [serge-rider/dbeaver#1894]
Hi, I have a mild red/green deficiency and noticed that green color in the background manager is difficult for my eyes to see correctly. 

This is a very minor issue, but I wanted to point it out incase any other users have trouble seeing the UI as intended.

**Comment by serge-rider** [comment]
You can change default colors in preferences (Preferences->General->Appearance->Colors and Fonts->Database Query Results).
Could you propose any better color (as a default value)?

**Comment by mloupe** [comment]
By taking a screenshot and of the application and looking at the color in Photoshop, the original appears to be 226, 254, 189 in RGB and 86°, 26%, 99% in HSB. 

Moving the hue to from 86° to 122° looks green to my eyes. So a final value of 189, 254, 191 in RGB or #bdfebf. 

I'm not sure if that fits the color scheme, but shifting the hue angle to up about 40 degrees definitely makes it appear more green.

**Comment by serge-rider** [comment]
Ok, I'll change the default color (I've just realized that you meant Query Manager colors but not results viewer).
