### ISSUE TITLE
DBeaver Not Honoring ApplicationName Parameter for Postgres JDBC Driver

### ISSUE THREAD

**Issue by kyleflan** [serge-rider/dbeaver#1896]
_Note to Postgres-XL Users: This issue is the cause for the error "Could not begin transaction on data node" on Postgres-XL. When Postgres-XL attempts to start transactions on data nodes, it attempts to set the application name without enclosing the application name in single quotes (obviously bad design on their part). If there's a space in the application name, this fails._ 

_I can't confirm because I don't have an instance of 9.5r1.5, but it appears that this issue has been fixed with the latest release of Postgres-XL: http://files.postgres-xl.org/documentation/release-xl-9-5r1.5.html_

---
When attempting to set the value for ApplicationName explicitly in DBeaver, it is not honored and gets set to the Eclipse version instead. 

Workaround: Use the PostgreSQL (Generic) Driver.

**Attempt 1: Specify the ApplicationName in the driver properties for an individual connection.**

![image](https://user-images.githubusercontent.com/5608074/28320152-72775022-6b95-11e7-8a29-49210bc8b9ec.png)

Result of pg_stat_activity:

![image](https://user-images.githubusercontent.com/5608074/28320075-41b57ffe-6b95-11e7-97b0-51be74a733b2.png)

**Attempt 2: Specify the ApplicationName as a URL parameter.**

![image](https://user-images.githubusercontent.com/5608074/28319942-dec6aefe-6b94-11e7-8d46-331bdeb6e5ce.png)

Result of pg_stat_activity:

![image](https://user-images.githubusercontent.com/5608074/28319975-f96778ce-6b94-11e7-8daf-19ca4c43aa04.png)

**Workaround: Use PostgreSQL (Generic) Driver**

Now, when using the PostgreSQL (Generic) driver, setting the ApplicationName in the Driver properties is honored. (It also works out-of-the-box because ApplicationName is empty by default).

![image](https://user-images.githubusercontent.com/5608074/28320292-cc5a970c-6b95-11e7-9944-9f31211bbd0c.png)

![image](https://user-images.githubusercontent.com/5608074/28320315-de2bbcd6-6b95-11e7-89a0-2bf7819dddc0.png)

**Verify Not a Driver Issue**

To verify this is not a driver issue, I've created a connection via Python's JayDeBe API for JDBC drivers using the same driver DBeaver uses:

```
import jaydebeapi

# Standard Postgres Driver provided by DBeaver
driver_name = 'org.postgresql.Driver'
jdbc_url = 'jdbc:postgresql://host/database'
connect_args = {'user': 'user', 'password': 'pass', 'ApplicationName': 'from_python'}
classpath = '/Users/user/.dbeaver-drivers/drivers/postgres/postgresql-42.1.1.jar'

conn = jaydebeapi.connect(driver_name,
                          jdbc_url,
                          connect_args,
                          classpath)

curs = conn.cursor()
curs.execute('SELECT usename, application_name FROM pg_stat_activity;')

rows = curs.fetchall()
for row in rows:
    print row

curs.close()
conn.close()
```

Result:

> (u'user', u'from_python')

I attempted downloading the latest Postgres JDBC Driver (42.1.3) from https://jdbc.postgresql.org/download.html#current, but the issue is the same.

**Comment by serge-rider** [comment]
Could you try to set client name (ApplicationName) in preferences: Database->Connections->Client Application Name. What happens if you set it to, say, "DBeaver"?

**Comment by kyleflan** [comment]
After updating the value to "DBeaver" in preferences and restarting DBeaver, the Application Name is being set correctly. Using this workaround, I can connect to and query an XL instance from DBeaver with the standard Postgres driver now. Thanks, @serge-rider.

**Comment by serge-rider** [comment]
Great. Thanks for testing.
