### ISSUE TITLE
Empty tooltips

### ISSUE THREAD

**Issue by oulenz** [serge-rider/dbeaver#1901]
When I hover over a menu item with my pointer, the tooltips are empty.

I'm on 4.10, Kubuntu 17:04. This was working fine until a couple of versions ago, unfortunately I don't remember exactly when it stopped working.

![image](https://user-images.githubusercontent.com/13745168/28407838-e04bfd7c-6d35-11e7-8826-8990bd3686c3.png)

**Comment by serge-rider** [comment]
Probably it is a bug in the most recent Eclipse 4.6 update. We going to migrate to Eclipse 4.7 soon so this should be fixed automatically.

**Comment by serge-rider** [comment]
And I can't fix this from DBeaver side in any case.
