### ISSUE TITLE
Code completion for table tab "Data" produces mixed lower-/ uppercase column names

### ISSUE THREAD

**Issue by BuZZ-dEE** [serge-rider/dbeaver#1902]

**Comment by serge-rider** [comment]
What database?
Could you provide some DDL example?

**Comment by serge-rider** [comment]
Maybe this is the same as #1926 ?

**Comment by tati-kru** [comment]
Hi @BuZZ-dEE . Could you, please, check that it can be reproduced or not on the latest version? Or maybe give a bit more details?

**Comment by serge-rider** [comment]
Closing
