### ISSUE TITLE
Freeze "Data View" Tab

### ISSUE THREAD

**Issue by zzz686970** [serge-rider/dbeaver#1906]
Hi there,

When I run a new query, the previous results shown in "Data View" Tab would be gone, is there any way to freeze this tab so I can switch across these tabs?

Thanks for your effort on this great project.

**Comment by yevon** [comment]
You can press ctrl + alt + x for executing your statement in a new tab. I can't find any function to "pin" tabs like sqldeveloper.

**Comment by sdpurohit** [comment]
You can also ctrl+\ to execute the current statement in a new tab.

Pin Tab is not an option in the first tab. It is available in all other tabs through the tab context menu. 

There is an issue filed in the 4.1.1 milestone to make the first tab pinable and also fix an issue with the way those tabs work. ([Pin first tab](https://github.com/serge-rider/dbeaver/issues/1508))

**Comment by serge-rider** [comment]
Yes, it is ticket #1508 . Moved to 4.1.2 milestone.
