### ISSUE TITLE
[Bug/missing functionality] New compile log window and error highlighting not working?

### ISSUE THREAD

**Issue by yevon** [serge-rider/dbeaver#1907]
Hi all,

I thought that error highlighting in code editor and a new compile log window was implemented in 4.1.0 (issue #1321), but i'am not able to see it. I have to do something special?. I can see a new region to hold compile errors, but is always blank and error pop up is still there. Also there isn't any error highlighting in code editor. Tested with oracle DB and dbeaver 4.1.0.

![image](https://user-images.githubusercontent.com/121157/28461956-4f546b30-6e19-11e7-961e-244d020fcff5.png)

Thanks!!

**Comment by serge-rider** [comment]
Now DBeaver first persists package/procedure (if it was changed) before compilation. And then tries to make actual compilation. So eventually it shows two error dialogs (and second one breaks actual error position).
Will fix it in the next version.

Thanks for report.
