### ISSUE TITLE
DBeaver doesn't read Postgres text_pattern_ops indexes

### ISSUE THREAD

**Issue by mausch** [serge-rider/dbeaver#1912]
Given a database with:
```
create table test (something text);
create index on test (something text_pattern_ops);
```
If I right-click on the `test` table in DBeaver and select Generate SQL -> DDL , I get:
```
CREATE TABLE public.test (
	something text NULL
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX test_something_idx ON public.test (something DESC) ;
```
It seems that DBeaver can't read the `text_pattern_ops` qualifier in the index definition.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
DBeaver now supports operator classes and operator families (which are used by index column definition)

**Comment by mausch** [comment]
Thanks for fixing it so fast!
