### ISSUE TITLE
Wrong tooltip in editor tab

### ISSUE THREAD

**Issue by pasha132** [serge-rider/dbeaver#1915]
Hello!
I have a postgres connection with a "Show non-default databases" on. There is a multiple databases on that instance. When i set default database to something different than a postgres the tooltip on editor tab don`t show actual db. 
PostgreSQL driver verion: 9.4.1212.jre7
DBeaver version: 4.1.1
Screenshot (differences marked with red):
![multiple_db_tree](https://user-images.githubusercontent.com/1105714/28564028-690c88c2-7130-11e7-91fb-5a76e2f11a8f.PNG)

**Comment by serge-rider** [comment]
There are two issues actually.
1. SQL editor doesn't update tooltip/title on database/schema change.
2. PostgreSQL extension doesn't update connection properties on database change.

I've fixed both
