### ISSUE TITLE
Check sums of the dowloaded packages of DBeaver are not visible on the site

### ISSUE THREAD

**Issue by kiviman** [serge-rider/dbeaver#1917]
After downloading from your site most of the people would need to check the consistency of the downloaded files.
Unfortunately as far I could see checksums are not provided or easy accessible for the files available to download.
 
Also many sites lately have been hacked to provide hacked packages. So affected developers start to provide gpg signed files informations for the downloaded files.
It will be very nice if check sums and gpg signatures of the available for download files will be available and easy visible to make possible to check the downloads.

**Comment by serge-rider** [comment]
Checksums are generated in build time (in `checksum` subfolder, e.g. http://dbeaver.jkiss.org/files/4.1.1/checksum/) but as dbeaver.jkiss.org doesn't use SSL (yet) this still won't be secure.

Actually I'm thinking about moving all CE version downloads to GitHub releases (as we way out of traffic limit on our hosting). This should be more safe as it uses https always. Do you think it will solve the problem?

**Comment by kiviman** [comment]
Thank you very much for your kind message.

Personally I believe any improvement, including https options will be 
welcome.
Also you can make some GPG signed documents informing about the real 
check sums to prevent some hacking.
Or may be you can sign by GPG the packages?

Sorry I did not know that check sums are available there.
May be because I am just starting to use DBeaver.
But if you can put some message on the download page where people like 
me could find them it will be very helpful.

I can see that DBeaver is a nice software with big potential.
So I wish you all the best and expect big future for DBeaver.
But a better security will be very helpful in order to be considered as 
main tool for production cases.

Some time ago the site of Linux Mint was hacked and some crackers put 
there for download some hacked packages instead of original ones.
This was a very sad thing. So many customers downloaded them and get in 
troubles and get angry to Linux Mint.




На 25.07.2017 в 19:28, Serge Rider написа:

**Comment by serge-rider** [comment]
Totally agreed.
I'll add info about checksums to download page (had to do this long time ago).
And probably will do something with https access.

**Comment by serge-rider** [comment]
Checksums link added to download page. And we'll probably move all dist files to GitHub soon
