### ISSUE TITLE
Eclipse Oxygen freeze after clicking on expand Icon

### ISSUE THREAD

**Issue by marcmuel** [serge-rider/dbeaver#1918]
When I start DB connections with the expand-Icon in Database Navigator eclipse Oxygen freezes nearly every time. If I make a double click on the connection Icon the connect works perfectly every time.

![image](https://user-images.githubusercontent.com/3865744/28577616-8841f19c-7157-11e7-8566-b65d3ce075e0.png)

This happens with DB2 Database and AS400 Database as well. 

I'm on the latest release of DBeaver.
![image](https://user-images.githubusercontent.com/3865744/28577754-f37f0292-7157-11e7-977d-a96b0010f68c.png)

**Comment by serge-rider** [comment]
Thanks for report

**Comment by marcmuel** [comment]
Here is a Thread-Dump of Eclipse while it hangs. Looks like a deadlock. 

[eclipse_thread_dump.txt](https://github.com/serge-rider/dbeaver/files/1182524/eclipse_thread_dump.txt)

Please fix this bug. It's makes me mad to kill eclipse and wait long time to rebuild all my Projects if i forget to avoid the "evil" Icon.

**Comment by serge-rider** [comment]
Thanks for thread dump. 
Although I still can't reproduce this locally now I have a clue how to fix it.
