### ISSUE TITLE
[Feature Request] Package function or procedure folding

### ISSUE THREAD

**Issue by ceyhunnabiyev** [serge-rider/dbeaver#1919]
It would be nice to add  the folding feature that  extends and collapses function or procedure body, loops, conditions in Oracle PL/SQL, because we can do both  programming language operations (loop, condition and etc.) and building query in Pl/SQL, and for big functions and procedures  it is difficult  to seek
necessary parts.

**Comment by serge-rider** [comment]
Agreed.
But I think this FR is duplicate of #1664 (which is more general but should cover PL/SQL as well).
