### ISSUE TITLE
Can't select/change Owner/Schema when Change DB-Connenction in Script

### ISSUE THREAD

**Issue by progsurfer** [serge-rider/dbeaver#1921]
When I open a Script and change the connetion from the Toolbar:

I can change the Schema:

![grafik](https://user-images.githubusercontent.com/24592280/28615074-27c48860-71f8-11e7-8722-3716d17f68e5.png)

Now I change the connetion inside the Script:

I can't chose the schema from the other connetions.

![grafik](https://user-images.githubusercontent.com/24592280/28615149-61194024-71f8-11e7-8337-7edff23c1b2c.png)

I have filters on the schemas.

Please fix it.

Thank you

**Comment by serge-rider** [comment]
Thanks for report
