### ISSUE TITLE
DBeaver plugin in Eclipse 4.7.0, continual memory allocation by SQL Editor

### ISSUE THREAD

**Issue by DzamoNorton** [serge-rider/dbeaver#1924]
I installed DBeaver into Eclipse version: Oxygen Release (4.7.0) Build id: 20170620-1800 using the Eclipse marketplace.  When I open a script with SQL Editor, the heap usage bar at the bottom right of Eclipse increases continually at about 10Mbyte / second, periodically being reset by a GC run.  When I close the script and open it in e.g. Generic Editor, heap usage is stable.

**Comment by serge-rider** [comment]
Do you perform any actions in SQL editor or it consumes memory in idle mode,?
SQL editor is a complicated control which analyses syntax, calls database-side functions while you editing etc. That's ok for it to consume some memory and then return it back.

**Comment by DzamoNorton** [comment]
I don't have to do anything in SQL editor to reproduce it.  Just opening a new empty SQL editor is enough.

**Comment by serge-rider** [comment]
What is your OS/window manager?

**Comment by DzamoNorton** [comment]
The window manager is xfce 4.12.3.  I've tried two arrangements w.r.t. the OS, both behave the same.

1. Debian testing 
2. Ubuntu 16.04 inside an LXC container on the Debian testing machine with the X11 domain socket bind-mounted into the container so that it can connect to the X server running on the Debian host.

**Comment by DzamoNorton** [comment]
Two more pieces of information are 

- the DBeaver 4.1.1 package itself, with whatever version of Eclipse it bundles, has stable heap allocation when I open an empty SQL editor on the same system and
- the problem is still there if I downgrade to Eclipse 4.6.3.  I haven't tried older versions than this.

**Comment by serge-rider** [comment]
Recent DBeaver bundles with Eclipse 4.6 M3.
I will test more on Ubuntu in Eclipse (didn't try that yet).

**Comment by serge-rider** [comment]
Well, I've reproduced that on Ubuntu 16 (in standalone version).

**Comment by DzamoNorton** [comment]
Nice to know I haven't just got a messed up machine :-).  Where do you think it comes from, the included version of GTK libs?  Do you want me to try varying a few things and re-testing?

**Comment by serge-rider** [comment]
Something about GTK+SWT. I'll try to play with options/read Eclipse boards and will reply here.

**Comment by serge-rider** [comment]
You could try to execute
```
export SWT_GTK3=0
```
before running DBeaver.

**Comment by DzamoNorton** [comment]
That does work around the issue, thank you.

**Comment by serge-rider** [comment]
Great.
Perhaps we'll need to make some special DBeaver starter script for this and include it in Linux distribution..
