### ISSUE TITLE
Snippets/Templates are not getting shown in the context assist

### ISSUE THREAD

**Issue by NidhinRV1984** [serge-rider/dbeaver#1925]
I can see that there a few templates already present in the preferences. However typing those in the SQL editor (.sql extension file) does not show/insert the template in the editor.

Regards,
Nidhin

**Comment by serge-rider** [comment]
To trigger SQL templates assistant use <kbd>CTRL+ALT+SPACE</kbd>

**Comment by NidhinRV1984** [comment]
Excellent. A little unintuitive though. Does not follow the normal eclipse way of appearing in the code assist or  ctrl space bringing it up.

Thanks serge for the quick response.
You can close this, if this is the only way of doing this.

regards,
Nidhin

**Comment by serge-rider** [comment]
Maybe templates assistant should be improved (and become a part of regular assistant). But I still not sure (sometimes in a real database you have a huge number of proposals - it is not easy to find template there).
Or this could be configurable.
I'll think about it one more time..
