### ISSUE TITLE
Enhancement the data filter

### ISSUE THREAD

**Issue by greenpeas** [serge-rider/dbeaver#1926]
PostgreSQL.

![image](https://user-images.githubusercontent.com/3856344/28668669-9f164976-72d9-11e7-9929-7240f2f7ae7a.png)

![image](https://user-images.githubusercontent.com/3856344/28668679-aee58ba0-72d9-11e7-948d-2492ecef39b2.png)

![image](https://user-images.githubusercontent.com/3856344/28668698-c71acda2-72d9-11e7-8ea6-0517aff23c86.png)

After press Enter:
![image](https://user-images.githubusercontent.com/3856344/28668708-da5e128e-72d9-11e7-9a83-01ac0e8663aa.png)

It should be like this:
![image](https://user-images.githubusercontent.com/3856344/28668740-00be272a-72da-11e7-9958-f487532d59ce.png)

**Comment by serge-rider** [comment]
This is a kind of bug but also an enhancements.
Anyhow it will be fixed in the next version.
Thanks for report.
