### ISSUE TITLE
ADD command line option: close all

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1928]
start DBeaver with all open tabs closed
could be combined with #1927 into one option

referenced in: https://github.com/serge-rider/dbeaver/issues/890#issuecomment-314892639

**Comment by serge-rider** [comment]
Yes, I'll leave single FR.
This feature will probably allow to execute ANY DBeaver command.

**Comment by serge-rider** [comment]
`-closeTabs` and `-disconnectAll` command line parameters added.

https://github.com/serge-rider/dbeaver/wiki/Command-Line
