### ISSUE TITLE
Performance Issue when data path is set to network share

### ISSUE THREAD

**Issue by Sargul** [serge-rider/dbeaver#1930]
Hi,

when the data path (option -data) is set to a network share (user home on smb share) the performance is bad when an sql error is raised due to long write times of <workspace-path>/.metadata/dbeaver-debug.log

It seems the debug log is synchronously written which takes about 4-5 seconds in my case.

I've tested this with an oracle connection and an invalid sql query to produce an sql exception.

Regards 

Charly

**Comment by Sargul** [comment]
Is there an option to completely disable debug log?

**Comment by serge-rider** [comment]
@Sargul no, there isn't. But we definitely need one.

**Comment by serge-rider** [comment]
![default](https://user-images.githubusercontent.com/6398845/28751432-fdb8b080-750f-11e7-8735-9a8e80f62222.png)
