### ISSUE TITLE
DBeaver icon appears twice when running on ElementaryOS

### ISSUE THREAD

**Issue by afilardo** [serge-rider/dbeaver#1931]
When the app is running on elementary os, a second icon appears between open apps, not the icon used as launcher.

![image](https://user-images.githubusercontent.com/4681845/28693420-d4245d06-7324-11e7-9808-8f4425138eb6.png)

**Comment by serge-rider** [comment]
We'll need to test DBeaver in ElementaryOS (it is actually not in the list of supported systems).

**Comment by anophelesgreyhoe** [comment]
The same happens with Ubuntu. And if the user locks the wrong icon (with the white circle behind it)  to the launcher, instead of the normal launch icon, DBeaver cannot be launched from it.
![dbeaver_two_icons_on_ubuntu](https://user-images.githubusercontent.com/11037075/28757719-398e4ce6-75dd-11e7-8c7a-6e9c63f3c2f5.png)

**Comment by nanny07** [comment]
Same happen to me on Windows 7

![dbeaver2](https://user-images.githubusercontent.com/17173586/28786051-54a44cf2-7618-11e7-90c3-bf0d1284620d.png)

**Comment by serge-rider** [comment]
Wow. That's not good.
Thanks for reports.

**Comment by anophelesgreyhoe** [comment]
I have sometimes seen the Database Navigator pane 'detach' from the main application window when I have it minimised (which I usually do). When it does this it shows as a separate window containing only the DB navigator, and often on a different display to the display I have DBeaver on.

The only way to fix this is to restart DBeaver, although it's not a big problem as I can just ignore it.

So I wonder if the 2nd icon could be for the DB Navigator? Just a thought.

**Comment by MurKit** [comment]
I have the same in Mint 18, while using Plank dock.
![screenshot at 2017-08-07 15-25-04](https://user-images.githubusercontent.com/13369896/29026505-c502c4d0-7b84-11e7-919d-46abdf5ecf92.png)

**Comment by MurKit** [comment]
Seems to be fixed in 4.1.3!

**Comment by afilardo** [comment]
It have been fixed. Thanks a lot @serge-rider!

**Comment by rafaelmartines** [comment]
The problem returned on recent version

**Comment by esl51** [comment]
The same problem on Manjaro XFCE.

**Comment by nguyentrucxinh** [comment]
I have the same in Manjaro 18 XFCE, while using Plank dock.
![screenshot_2018-12-27_15-52-30](https://user-images.githubusercontent.com/14963070/50473458-8da8e280-09ef-11e9-95f5-0b5ec86e50ff.png)
Hope you can fix it again!
