### ISSUE TITLE
Informix: active database change support

### ISSUE THREAD

**Issue by yujishe** [serge-rider/dbeaver#1932]
Why not switch the function of switching the database, and now only switch users.Now use the cool, but to switch the database, I have to switch a connection.
This is just a suggestion！

Best wishes！

**Comment by N3kOnScreeps** [comment]
Aren't database linked to users ?
Which database type do you use ? Each user have his synonyms and grants on databases, how would you change database without switching user ?

**Comment by yujishe** [comment]
We use informix,when change database,it show a error messsage:Active database change is not supported
Active database change is not [supported;]


Is this database that does not support this feature? But DbVisualizer can switch the database without switching users.
I am a newer, not very clear that users and the database can link the function, perhaps this is the database architecture problem. Oracle database should be possible.

![20170728175336](https://user-images.githubusercontent.com/22394316/28712413-9b04b59a-73bd-11e7-9ed3-5a0316a56212.jpg)

**Comment by serge-rider** [comment]
This is actually a configurable behavior.
Do you know how to change active Informix database using SQL query?

**Comment by yujishe** [comment]
I just know how to  operate data using SQL query,like select,update ,delete ,drop...... (′▽`〃)

**Comment by amivanovano** [comment]
Try use SQL query:
DATABASE yourActiveDatabase;

HTH

**Comment by serge-rider** [comment]
```sql
DATABASE yourActiveDatabase;
```
@yujishe does it really work?

**Comment by yujishe** [comment]
I use the oracle database, found that the user and the database binding, it seems informix database function, or the version is too low

**Comment by INGCRENGIFO** [comment]
@serge-rider Yes, this actually works in informix, but if we use it in "dbeaver" the helpers are not activated.

**Comment by serge-rider** [comment]
@INGCRENGIFO thanks.
I'll add active database change config in driver settings.

I believe that under helpers you mean auto-complete. They won't use current database if you change it by executing DATABASE query in SQL editor (because DBeaver don't know about that unless you will set "Refresh active schema after SQL execution" in SQL editor preferences).
