### ISSUE TITLE
Fail to install Office Extension on 4.1.1

### ISSUE THREAD

**Issue by nanny07** [serge-rider/dbeaver#1933]
Hi,

I had succesfully installed the office extension back to the 4.1.0 but when I have upgraded to the 4.1.1 I found out that the plugin was missing.

So I tryied to reinstall but I always get this error:
![apachepoi](https://user-images.githubusercontent.com/17173586/28705349-ae5c205e-736f-11e7-8c62-176300f0a13b.png)

Anyone else have this?

**Comment by dariopnc** [comment]
Me too

**Comment by serge-rider** [comment]
Just rechecked - this works fine in my environment.
When exactly do you see this error?
Try to uninstall DBeaver completely (or remove DBeaver directory if you use portable version) and then install it again.

**Comment by nanny07** [comment]
I've uninstalled and reinstallad but I have the same iusse

**Comment by ChristopherMagee** [comment]
Also running into this issue with the new 4.1.1 version on Win7.  Let me know if I can provide any extra information.

**Comment by serge-rider** [comment]
Do you use 64bit or 32bit version? 
Is it standalone version?

**Comment by ChristopherMagee** [comment]
Hi,

64-bit version, using the "Windows 64 bit (installer + JRE)" option from the DBeaver website.

![image](https://user-images.githubusercontent.com/8886697/28783820-8e117a3e-75df-11e7-9c91-88de844b56f4.png)

**Comment by nanny07** [comment]
Win7+64bit version too

**Comment by serge-rider** [comment]
Indeed, there was broken dependency in the latest CE version.
Thanks for report.

**Comment by mingw46** [comment]
i had that problem too. You should remove from C:\Program Files\DBeaver\plugins office plugin if you have and remove C:\Program Files\DBeaver\artifacts.xml. You can backup artifacts file and paste it after completed installation.
Now if you run dbeaver as administrator you can install office plugin.
