### ISSUE TITLE
DBeaver 4.1.1 crushes on Ubuntu 14.04 with OpenJDK 7

### ISSUE THREAD

**Issue by selivan** [serge-rider/dbeaver#1935]
- DBeaver: 4.1.1, downloaded "Linux 64 bit (tar.gz archive)"
- OS: Ubuntu GNU/Linux 14.04 trusty
- Java:
`java version "1.7.0_131"`
`OpenJDK Runtime Environment (IcedTea 2.6.9) (7u131-2.6.9-0ubuntu0.14.04.2)`
`OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)`
- Crash log: https://gist.github.com/selivan/e747ba2692b559b07efdb54ba62df5b9

**Comment by infectormp** [comment]
Since 4.0 DBeaver requires Java 8

**Comment by selivan** [comment]
@infectormp Thank you, works with openjdk `1.8.0_141`.

I suppose, it would be nice to notify user of required Java version, instead of just crashing.
