### ISSUE TITLE
Not-Null-checkbox not left-aligned in field view

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1938]
Click on a field and see its properties. Everything is left-aligned, except Not-Null. This looks ugly and could be overseen by user.

**Comment by serge-rider** [comment]
Agreed

**Comment by serge-rider** [comment]
I've changed it to left-aligned (for properties editor tree). Also a bit ugly but at least you can see the value.
Will need some other UI solution - native checkbox control isn't very convenient/good looking.
