### ISSUE TITLE
Bug Windows 10 Taskbar

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#194]
Dbeaver seems to want to launch multiple instances of itself and won't maintain one icon on the taskbar.

Furthermore if you accidentally open a second instance you will be presented with this error at some point

An internal error occurred during: "Periodic workspace save.".
Cannot set lower sequence number for root (previous: 3, new: 2). Location: C:\Users\user_name\.dbeaver\.metadata\.plugins\org.eclipse.core.resources\.safetable\org.eclipse.core.resources

![dbeaver_windows10_taskbar_bug](https://cloud.githubusercontent.com/assets/9246654/12895007/2cefcb40-ce4f-11e5-8ca3-83d8777b1075.gif)

**Comment by serge-rider** [comment]
For now I don't realize what is wrong with the starter icon.
For some reason Windows thinks that started application differs from the original shortcut..

**Comment by r-richmond** [comment]
Hmm did some google-sleuthing and turned up the following results which may be useful.

It looks like its a pretty common bug with windows :/

https://discussion.evernote.com/topic/86972-multiple-taskbar-icons/

> This is a Windows 10 shell bug. Calling SetCurrentProcessExplicitAppUserModelID seems to be the cause. (And we need to call that to enable jumplists.)

http://www.ghacks.net/2015/08/04/fix-duplicate-icon-issues-on-the-windows-taskbar/
(Option 1 didn't work)

**Comment by r-richmond** [comment]
I'm not sure when this changed but the bug is no longer present in 3.6.10 community

**Comment by carlosjrcabello** [comment]
Hi @r-richmond ,

Here seems OK this one. At least I remember, previous versions it didn't work..I've pinned DBeaver at taskbar and it keeps using same icon/block.

![image](https://cloud.githubusercontent.com/assets/637767/16017405/19a66a28-3176-11e6-85a6-aca6d2796f9c.png)

**Comment by r-richmond** [comment]
Yea... given the current state I'm going to close this issue and reopen if it reappears but otherwise hurrah.

**Comment by Gnuko** [comment]
Again, 4.1.1
