### ISSUE TITLE
SQL Server icon missing in DBeaver 4.1.1

### ISSUE THREAD

**Issue by anophelesgreyhoe** [serge-rider/dbeaver#1941]
I've just upgraded to 4.1.1, and now when I expand a folder that contains a SQL Server connection in the Database Navigator, I get an error message like the below screenshot.
![dbeaver_4 1 1_missing_sql_server_icon](https://user-images.githubusercontent.com/11037075/28757740-9aadffc6-75dd-11e7-9930-03e4fa81cff6.png)

**Comment by serge-rider** [comment]
Can't reproduce. 
Maybe this is a result of incorrect version upgrade.
Could you try to remove previous version completely (just remove dbeaver folder) and install again?

**Comment by quiescer** [comment]
Thanks for your time and response. I have found after restarting DBeaver this issue has gone away. I am mystified as to the cause, but this ticket can be closed.

**Comment by serge-rider** [comment]
Good, thanks for info
