### ISSUE TITLE
"Active catalog/Schema" not taken into account in 4.1.1 when using PostgreSQL generic driver

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#1942]
"Active catalog/Schema" not taken into account in 4.1.1 when using **PostgreSQL** **generic** driver.
As a result, one should either execute 'set search_path to XXXX' once on connect, or use schema prefixes when referring DB relations.

**Comment by serge-rider** [comment]
Can't reproduce.
Pleae open Query Manager view, enable all query types (in "Filters..." dialog) and check what DBeaver does when you change active schema.
It should execute some like
```sql
SET search_path = schema-name
```
Also you can check error log view. Thanks

**Comment by gogosofta** [comment]
I think schema name should be surrounded by double quotes (in my case it's in uppercase), otherwise the command just sets the search_path to a non-existing one, which doesn't raise an exception.

![image](https://user-images.githubusercontent.com/13131218/28783761-08f59bba-761a-11e7-9c55-5c80fc753434.png)

**Comment by serge-rider** [comment]
Yep, seems to be a bug in DBeaver, thanks for report.
