### ISSUE TITLE
Can't successfully export and import cassandra INSERTs

### ISSUE THREAD

**Issue by ghost** [serge-rider/dbeaver#1944]
I have some cassandra tables with MAP<text,decimal> fields, however if I use the Export to SQL INSERT statements it doesn't put quotes around the text in those MAP fields.

    CREATE TABLE product (
        productid uuid,
        description map<text, text>
        ...

Outputs this:

    INSERT INTO product (productid, description)
    VALUES(xxxxxxxxxxxxxxxxxxxxxxxxxxx, [en-gb=some description]);

If I then paste that into DBeaver it will fail.  Is there a way to force quoted text, am I doing something wrong or is this a bug?

Just looking at this again it seems it is also using [] and an equal sign which also seems wrong for cassandra.  Shouldn't it be more like this:

    INSERT INTO product (productid, description)
    VALUES(xxxxxxxxxxxxxxxxxxxxxxxxxxx, {'en-gb':'some description'});

A similar issue seems to be for LIST type.

Many thanks

**Comment by serge-rider** [comment]
This is a bug (or kind of misfunction) in Cassandra extension. Thanks for report.

**Comment by serge-rider** [comment]
Fix will be in EE 4.2
