### ISSUE TITLE
Export from MS Access with boolean to mySQL is always 0

### ISSUE THREAD

**Issue by knoxyz** [serge-rider/dbeaver#1945]
Hallo dbeaver-team,

I connect with dbeaver EE 4.1.1 (Linux) to a MS Access mdb-file by ODBC-driver "UCanAccess".
Generally i works pretty fine and all values are show correct (also BOOLEAN) and even the export to a mysql-database works fine.

But all columns which are in the mdb-file "boolean" are after the export into a mysql database with value "0" (never 1 or true).

I already tried without success to switch the proposed goal data type from "BOOL" to BIT, TINYINT(1) and VARCHAR as well in the mapping of export as data type in the mySQL table.
But all "true" values in MS Access are lose and will be "0" in mysql. :-(

Could you please check and fix it?

With best regards
knoxyz

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
DBeaver didn't know to map boolean into numeric data type (as MySQL doesn't support real booleans).
It it does.
