### ISSUE TITLE
Error on SQL Execute

### ISSUE THREAD

**Issue by rythym05** [serge-rider/dbeaver#1947]
When using Execute SQL statement or Execute SQL statement in a new tab, I expect that the query executes for lines only within the scope of the delimiter. But I see that even if there is some incomplete statement elsewhere within the .sql, Dbeaver shows a error

![image](https://user-images.githubusercontent.com/29409893/28794947-fcc602ee-75ec-11e7-8736-5beddeae1277.png)

When I do a Execute SQL statement placing my cursor in Line 7 -

![image](https://user-images.githubusercontent.com/29409893/28794828-9195f7c2-75ec-11e7-8034-6c7461853745.png)

If I just highlight line 7 to execute, it works fine.

**Comment by serge-rider** [comment]
DBeaver doesn't support PL/SQL in form of simple SQL.
You can use anonymous SQL blocks to execute PL/SQL:
```sql
[declare
...]
begin
  ...
end;
```

**Comment by rythym05** [comment]
My purpose wasn't with writing PL/SQL. I just had the keyword there which I forgot to comment. This is just a example. I had this part of a bigger sql script and execute was always failing. 

I wanted to point that just executing sql on line 7 should have worked as it was within the scope of the delimiter  ; ?

**Comment by serge-rider** [comment]
Ah, I see. Looks like you executing it as a script.
In order to execute single statement use <kbd>CTRL+Enter</kbd> (or Execute SQL Statement button in toolbar)

**Comment by rythym05** [comment]
No Serge. I am not executing as script. 

As mentioned in my post I am using Execute SQL statement or Execute SQL statement in a new tab. I am using oracle. I think it somehow doesn't like the LOOP keyword there. Not sure if this will occur for other keywords.

**Comment by serge-rider** [comment]
Then I just can't reproduce that.
Please post you SQL here (sometimes there is something special in particular code piece, e.g. hidden special characters) and I will try it on my machine.

**Comment by rythym05** [comment]
I think there is some conflict with my settings. I am able to reproduce always in 1 machine but not in the other. I will try to figure out.
