### ISSUE TITLE
Determine Data table alternating row highlights based on table background

### ISSUE THREAD

**Issue by wyqydsyq** [serge-rider/dbeaver#1948]
I'm using DBeaver on OpenSUSE Gnome with a dark GTK theme ([Flat-Plat](https://github.com/nana-4/Flat-Plat) to be specific), with the default DBeaver "Classic" theme. It inherits colours as expected and looks good in general except for this one part; the alternating row shading on Data tables appears to be hard-coded and doesn't work well with the white text from this theme.

Screenshot:
![image](https://user-images.githubusercontent.com/621277/28806784-37290788-76b5-11e7-919d-0a82d008bb3b.png)

Ideally the background highlight colour should be based on the actual background colour, just shifted lighter or darker by a few %. If that's not possible then at least the text on these highlighted rows should be forced to a dark colour so they contrast with the light background colour.

**Comment by serge-rider** [comment]
This is configurable ("Odd row background" in Preferences->General->Appearance->Database Query results). And it should look better by default.
Also I see that you use a bit outdated version - please try 4.1.1.

**Comment by wyqydsyq** [comment]
Ah sweet I just updated to `4.1.1` and found the new Appearance customization parts. It didn't look any better by default in the new version but at least I was able to customize it to match my GTK theme. Thanks 😄
