### ISSUE TITLE
Some appearance customization options are not respected

### ISSUE THREAD

**Issue by wyqydsyq** [serge-rider/dbeaver#1949]
I'm using a dark GTK theme and have been changing some of the customization variables to suit the look, but I noticed no matter what I do, the Diagrams use a white grid background and white association entity arrows:

![image](https://user-images.githubusercontent.com/621277/28813340-431d6206-76dc-11e7-82e8-9263b67adb4d.png)

With these settings I would expect the grid to have a dark grey background and the association arrows to be cyan.

**Comment by serge-rider** [comment]
Diagram background init was fixed.
Also I've added color config for notes (for #1814)
