### ISSUE TITLE
Add string formatting to binaries during export

### ISSUE THREAD

**Issue by gsaulmon** [serge-rider/dbeaver#195]
There is a "String" format option available for binary columns while viewing in the editor. 
When choosing to export a result set "String" is not available in the binary encoding options list.

**Comment by serge-rider** [comment]
In results viewer "String" means to show raw binary data in character representation.
What do you expect to get in case of data export? Isn't it the same as "Binary" encoding?

**Comment by gsaulmon** [comment]
Sorry. Got some things mixed around.
