### ISSUE TITLE
Descriptions Names instead of Columns Names 

### ISSUE THREAD

**Issue by geuss** [serge-rider/dbeaver#1952]
Hi,
in the Resulset Panel are displayed the columns descriptions instead of the columns names.
I'm using a Teradata JDC Connection with DBeaver 4.1.1 (but the issue is still present with older versions).
In Preference->Database->Result Sets->Presentation the parameter "Show column description in header" is unset.

![image](https://user-images.githubusercontent.com/26387091/28823607-b2858a2e-76be-11e7-8e64-4c14979603d8.png)

Thanks.
Gianni

**Comment by serge-rider** [comment]
Do you see real column names in table editor (tab columns)?
What do you see in metadata panel? (click on Panels->MEtadata)

**Comment by geuss** [comment]
In Table Editor:
![image](https://github.com/dbeaver/dbeaver/assets/26387091/caa4c58f-89d0-41fb-9d66-425d8fa82ca9)

In Panels->Metadata:
![image](https://github.com/dbeaver/dbeaver/assets/26387091/724ec818-71d5-41f3-b77c-973f82ba66b5)

**Comment by serge-rider** [comment]
Most likely option "Show column description in header" was set to true in connection-specific options.
Open connection properties (f4 on connection)->Result Sets->Presentation.

**Comment by geuss** [comment]
The option is not set..... :-(
![image](https://user-images.githubusercontent.com/26387091/28926474-32c94bee-7868-11e7-94f4-361de65066a5.png)

**Comment by serge-rider** [comment]
Teradata JDBC driver returns column descriptions in result column labels (so it is not JDBC-compliant).

I'll add extra config option which will make DBeaver to use column name always (even if there is label).

**Comment by geuss** [comment]
Thank You, Serge.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/29144319-2e428060-7d61-11e7-931a-fa5ddaac942a.png)

**Comment by geuss** [comment]
I'll wait for the new relase!!! Thank you so much!
