### ISSUE TITLE
Dbeaver connnect with phoenix,the timestamp column value is added 8 hours.

### ISSUE THREAD

**Issue by Hackeruncle** [serge-rider/dbeaver#1958]
Env:
Dbeaver: 4.1.0,4.1.1
Phoenix: 4.11
 
Dbeaver connnect with phoenix,the timestamp column value is added 8 hours. 
I think that  this is a timezone problem, please tell me that how to reslove it, thanks. @serge-rider 

correct value:  **2017-02-27 10:04:35**
display value:  **2017-02-27 18:04:35**

![1](https://user-images.githubusercontent.com/20901151/28903682-ef133a60-7838-11e7-82c7-0ca13f7dee1c.png)

**Comment by Hackeruncle** [comment]
It's resolved.
Add this parameter in dbeaver path/**dbeaver.ini**.
**-Duser.timezone=UTC**


**Refernce:** [https://github.com/serge-rider/dbeaver/issues/1224](https://github.com/serge-rider/dbeaver/issues/1224)

![1](https://user-images.githubusercontent.com/20901151/28905071-81325086-7841-11e7-85a2-3f8aa448f775.png)

**correct display value:**
![2](https://user-images.githubusercontent.com/20901151/28905181-0199dbb8-7842-11e7-902a-db44891ed376.png)

**Comment by serge-rider** [comment]
Thanks for information

**Comment by Hackeruncle** [comment]
Use the parameter to test.

-Duser.timezone=UTC
 or
-Duser.timezone=UTC+08:00
