### ISSUE TITLE
Updating a value in a grid view twice fails the second time

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#1960]
If you do a select on a table, double click on a cell, edit the value and save it says 1 record updated.
If you then repeat the process on the same cell, it says 0 records updated. You have to perform the select again. This may be because some other values have changed due to triggers. I'm not sure if a fix is possible for this if I'm right on the reasoning.

**Comment by serge-rider** [comment]
I can't say for sure as I can't reproduce that.
Please post table DDL (if possible).

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
