### ISSUE TITLE
Can't see "table triggers" on Oracle Database

### ISSUE THREAD

**Issue by wecucho** [serge-rider/dbeaver#1963]
Hi there, first of all thanks for dbeaver, it is a great tool :)

I want to see my table triggers and I don't know if I need anything special to do that, what I'm doing so far is:

1. Opening DBeaver 4.1.1
2. Right click on Database Navigator -> Create New Connection
3. Selecting "Oracle" and Next
4. Click on "Custom" tab and paste my dabatase URL (jdbc:oracle:thin:@host:1521:SID)
5. Entering the "user name" and "password"
6. Setting up a fresh "ojdbc6.jar" from Oracle web site and hitting "next"
7. "next" again to skip SSH Tunnel & SOCKS Proxy
8. Entering "development" as the Connection Name and click on "Finish"

Then I go to that connection and expand "development" -> "Schemas" -> "Development" and I see everything but "Triggers" I can see "Schema Triggers" but that is not what I want.

Also, I can successfully execute the following:

SELECT *
FROM SYS.ALL_TRIGGERS WHERE OWNER='DEVELOPMENT'
ORDER BY TRIGGER_NAME;

This SQL prints correctly all the triggers I have, I just want them to be on the Database Navigator so I can browse them and see their DDL.

Any help will be appreciated, thanks.

**Comment by serge-rider** [comment]
Table triggers are visible only under table itself. 
In schema you can see only global schema triggers.

![default](https://user-images.githubusercontent.com/6398845/28997738-8e89004c-7a24-11e7-91c2-a656c0efb07e.png)

You ar not the first who asks about this. So probably we need to put all table triggers somewhere too. Maybe create item "Table triggers" right near the "Schema triggers". 
WDYT?

**Comment by wecucho** [comment]
Thank for helping, I see the triggers now.

I think that an item "Table triggers" would great and maybe more accurate. I mean, personally I don't create a mental link between triggers and tables, for me, triggers are independent as procedures. So, in this moment I have a schema with near 120 tables and 10 triggers. I feel like playing "Where in the world is Carmen Sandiego" trying to find those triggers :)

**Comment by serge-rider** [comment]
Agreed
