### ISSUE TITLE
How do I connect to MAPR Hive Clusters using DBeaver?

### ISSUE THREAD

**Issue by Ketan-Kulkarni** [serge-rider/dbeaver#1964]
I've downloaded the mapr drill odbc driver, but I'm clueless after that. Any ideas?

**Comment by serge-rider** [comment]
You could try ODBC driver in DBeaver (available only in Windows version).
You will need to configure ODBC datasource in windows ODBC admin tool.
Then create new ODBC connection in DBeaver - just set datasource name (in Database/Schema field) and user credentials (if needed).

**Comment by Ketan-Kulkarni** [comment]
Hmm... so this won't work for the mac edition (which is where & why i use DBeaver)

**Comment by serge-rider** [comment]
Then you should use JDBC driver (it works on Mac as good as on other platforms).

You could try to use preconfigured Apache Drill driver (http://maprdocs.mapr.com/home/Drill/Downloading-Configuring-Driver.html)

Also some docs are here: https://mapr.com/blog/connecting-apache-hive-to-odbc/#6

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.
