### ISSUE TITLE
Error while connected to MySQL through ssh tunnel

### ISSUE THREAD

**Issue by ges7** [serge-rider/dbeaver#1965]
This error happens whether I connect to MySQL by configurating the ssh tunnel directly in DBeaver, or making an ssh tunnel on my machine myself with ssh -g -L.

The connection initially works, but when I try to access data or browse the tables, every time an action is issue, an error pops up with an error message saying "Connection with [..] lost, Query execution failed, SQL Error, No operations allowed after connection closed".
![dbeaver_issue](https://user-images.githubusercontent.com/1526152/28962760-009ee6de-7907-11e7-89c5-46f3e669059c.png)

java -version returns :
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by serge-rider** [comment]
Do you able to browse tables? Does connection breaks only when you trying to select data?

Anyhow - please post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) here or on serge@jkiss.org

**Comment by ges7** [comment]
Ultimately I can read the tables, but the error about the "read timeout" pops up all the time, any action I do. I click reconnect and it works but it's disrupting. Here's the debug log (using 4.1.2 actually)
[dbeaver-debug.log.txt](https://github.com/serge-rider/dbeaver/files/1204183/dbeaver-debug.log.txt)

**Comment by serge-rider** [comment]
Did you set any keep-alive configuration (in SSH settings or in general connection settings)?
If yes - try to set it to 0 (disable).
Any custom driver properties?
Check that tunnel connect timeout is big enough (on SSH settings page).

Also, according to https://sourceforge.net/p/jsch/support-requests/23/ :
> 1. Be sure that the host we are connecting to is not in ~/.ssh/known_hosts (e.g. empty it)

**Comment by ges7** [comment]
I removed the target host from my ~/ssh/known_hosts, I disabled TCPKeepAlive (it is enabled by default in debian jessie's ssh), I have set a connect timeout of 10000ms, a Keep-Alive of 0ms. It works OK the first table I open, but any further action I do I get the very same error of "Communications link failure".

**Comment by serge-rider** [comment]
Weird.
Please post debug log again. Something bad happens with SSH tunnel and there should be some errors in logs.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
