### ISSUE TITLE
Firebird unquoted database identifier at sort

### ISSUE THREAD

**Issue by kladogen** [serge-rider/dbeaver#1967]
When I try to **sort** (using the column header up/down icon) a query result set produced from a Firebird database I get the message "Query execution failed Reason SQL Error [335544578][42S22]:Dynamic SQL Error; SQL error code=-206; Column unknown; PRICE; At line 1, Column 405".
The column name should be "price" not PRICE.
I have produced the result set by clicking on "Read data in SQL console". In the header the filed name is correctly shown as price not PRICE so probably the problem is that the query produced to sort does not use quotes although the query that produced the result set has quotes correctly.
I have checked the option "Use case-sensitive names in DDL statements" but it did not help.

Here is the query produced by DBeaver 
SELECT "id", "categoryId", "code", "description", "price", "availability", "discountType", "discount", "fpaRate", "posId", "DisplayOrder", "UsageFrequency", "PrintingConfigurationID", "FPA_Category", "QuanityType", "AvailableQuantity", "AvailabilityCheck", "Deleted", "Hidden", "LongDescription", "PrepareOrderID", "AccessLevel", "UseWithDeliveryOnline", "DeliveryDescription"
FROM "menu";

If I add an "ORDER BY "price" to the query then the sorting icons work.

**Comment by serge-rider** [comment]
It is a bug in query transformer (which used to add ORDER BY clause to custom SQL).
Thanks for report.
