### ISSUE TITLE
How to change color of selected column heading in dark theme

### ISSUE THREAD

**Issue by MurKit** [serge-rider/dbeaver#1975]
I have only found setting Colors and Fonts - Database query results - Selection background,
that changes the background of the column itself, but how to change selected column's heading color?

![screenshot at 2017-08-07 15-22-49](https://user-images.githubusercontent.com/13369896/29026562-0151ce22-7b85-11e7-8733-043dc673a080.png)

**Comment by serge-rider** [comment]
There is no such config for cell header background. 
Looks like there are just two colors which are not yet configurable (and taken from system theme):
- Selected cell header background
- NULL values foreground
I'll add extra options in the next version, thanks for noticing.

**Comment by MurKit** [comment]
Thank you for your product!
