### ISSUE TITLE
Add integrity and authenticity verifyable downloads

### ISSUE THREAD

**Issue by thomaszbz** [serge-rider/dbeaver#1977]
`http://dbeaver.jkiss.org/download/` leads me to a http download like `http://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb`

A https representation is currently not available (`https://dbeaver.jkiss.org/download/` leads me to an "insecure connection" whereas the TLS certificate provided via port 443 is not valid for the domain `dbeaver.jkiss.org`)

There is to say that the page offering the link is not TLS secured as well as the download itself. Download checksums are not offered in the whole process at all and even if they'd be offered, that would be pretty worthless as long as the corresponding http ressource is not TLS secured.

Conclusion 1: The whole process is completely vulnerable to a man in the middle (MITM) attack whereas MITM attacks have become increasingly relevant over time (untrusted networks like open wifi in cafés or hotels, DNS forgery, tainted router firmwares, tainted ISP infrastructure, hijacked IP ranges and so forth).

Conclusion 2: Now that it _can_ be attacked, it most likely _will_ be. The question is when and maybe it already got attacked in the past. It's likely that nobody would have noticed it. Untrusted downloads should not take place any more in 2017.

Conclusion 3: At least the debian package will have to be installed with root privileges. Installing corrupted software (malware) with root privileges gives the attacker full control over a system.

Conclusion 4: TLS-securing the web site and offering TLS-secured hashes has become cheap and easy (e.g. via Let's Encrypt or via your partner company InterTechGeo LLC which seems to deal with TLS certificates). IMO, there is no lame excuse possible any more in terms of cost or effort. I'd even recommend to TLS-secure the download itself (that would imply that the integrity and authenticity of the download itself is checked by default, now that ordinary people tend to not perform sha256 verification of downloads even if available).

Conclusion 5: As soon as https is in place and works, http requests should be 301-forwarded to https so that search engines go for https over time and people using search engines get the https link from the search engine. That said, a https-only strategy should be applied whereas the 301 forwarding _only_ serves to let old incoming links from foreign web sites lead somewhere. Even these sites can automatically check their links using a [link checker](https://validator.w3.org/checklink).

Conclusion 6: Once the https-only strategy is applied, all links pointing to domain `dbeaver.jkiss.org` (web pages and code) should be changed to use the https schema, for two reasons:

- Avoid obsolete round trips for the 301 forwarding (performance, SEO)
- Avoid MITM attacks now that the 301 forwarding is again in http, giving MITM pretty much the old attack surface (by 301 forwarding somewhere else).

Side note 1: Users of dbeaver tend to connect to databases. To me, that seems to be among the most juicy targets an attacker could possibly get in touch with: Databases and victims with admin privileges for organisations and companies, exposing private SSH private key material, SSH private key passwords and database logins to (a manipulated version of) dbeaver and thereby to the attacker. Having untrusted downloads for that (btw. great!) piece of software is really a no-go in 2017.

Side note 2: Please note that this issue is _not_ about encryption, but about integrity and authenticity (TLS provides all three of them, whereas encryption is just overhead in that particular scenario).

Side note 3: Once package maintainers do the job of putting the packages into the repositories of distros, they also need a way to verify downloads. So the whole problem does not shift away at all unless the maintainers pull the sources directly from github (and thereby use ssh or https but not the insecure git protocol, at least not without verifying commit IDs against a trusted source).

Side note 4: An easy catch would be to offer the TLS secured link of the github package download on the download page (e.g. `https://github.com/serge-rider/dbeaver/releases/download/4.1.2/dbeaver-ce_4.1.2_amd64.deb`. However would the link itself still be attackable to a MITM attacker as long as the download page itself is not TLS secured. But as soon as the download page itself is TLS secured, no additional ressources would be needed for the TLS encryption of the download itself at least  (when hosted by github).

**Comment by serge-rider** [comment]
You are right.
We going to add HTTPS to dbeaver.jkiss.org domain before next version release (and always forward http requests to https version).
Moving binaries to GitHub is also an option.

**Comment by thomaszbz** [comment]
Please test with https://www.ssllabs.com/ssltest/analyze.html?d=dbeaver.jkiss.org once TLS is in place.

**Comment by serge-rider** [comment]
Thanks for information. I've run unattended-upgrades and will perform other necessary checks.
Yes, it is Apache 2.4.7 on Ubuntu 14.04. OpenSSL 1.0.1f

**Comment by serge-rider** [comment]
Well, DBeaver is now SSL-enabled. Qualys gives it A rating.

HDYT - are we secured enough?

**Comment by thomaszbz** [comment]
http://dbeaver.jkiss.org/download/ now 301-forwards me to the https secured equivalent:
```
wget dbeaver.jkiss.org
HTTP-Anforderung gesendet, warte auf Antwort... 301 Moved Permanently
Platz: https://dbeaver.jkiss.org/ [folge]
```

That page now points to a https secured download whereas I can have trust in the link because the authenticity of the web page is given.

Qualys went green and pretty much looks as it should be.

Even custom DH params are used:

`DH public server param (Ys) reuse | No
`

Congratulations. That fixes this issue.

**Comment by thomaszbz** [comment]
In respect to DH params, Cryptosense says: The server uses a commonly-shared 2048-bit Diffie-Hellman group.

However, I think just for securing a download, your setup should do as is.

**Comment by serge-rider** [comment]
Great.
Thanks for checking this!

**Comment by thomaszbz** [comment]
@serge-rider Seems that was fixed just in time...
https://www.welivesecurity.com/2017/09/21/new-finfisher-surveillance-campaigns/
