### ISSUE TITLE
Feature request:  Ability to hide the bottom pane (containing results/execution log etc)

### ISSUE THREAD

**Issue by jonnyry** [serge-rider/dbeaver#198]
When writing long SQL scripts it is useful to have the full height of the application to see you script.  It would be useful if it was possible to hide/close the bottom pane containing the Results/Explain/Execution Log/Output tabs temporarily.

Even better if you could assign a key shortcut to toggle the visibility of this pane.

**Comment by serge-rider** [comment]
Its already there.
"Toggle results panel" in the context menu or F6.

**Comment by jonnyry** [comment]
Excellent, thanks!
