### ISSUE TITLE
[FireBird] Table lists contains system tables 

### ISSUE THREAD

**Issue by Apcio** [serge-rider/dbeaver#1993]
System tables in FireBird databases have RDB$ and MON$ prefixes.
Is possible to extract them to another folder, like "System tables" or "DB tables" ?

**Comment by serge-rider** [comment]
No, these tables can't be moved to another folder. But you can hide them (connection properties->General->uncheck  "Show system objects".

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.
