### ISSUE TITLE
[4.1.2] Context Menu bug of Implementation #1825 [Bug]

### ISSUE THREAD

**Issue by keen85** [serge-rider/dbeaver#1995]
Hi,
in #1825 there was a feature request concerning the script editor tab context menue. The feature works (thanks @serge-rider) - but only for newly opened script editors.
If an pre-existing file is opened from local storage, only the orginal context menue without "copy filepath ...." is displayed.
![image](https://user-images.githubusercontent.com/29750255/29119323-fcb9defe-7d05-11e7-88a5-b139c160f4cd.png)

One more request: could you please also add an "Reload file" and "Delete file" context menue entry?

Thanks and regards

**Comment by serge-rider** [comment]
It is a bug, thanks for report.
I'll add the same menu (except "Rename" command which can't be easily implemented for external files) in the next version.

Please create separate feature request for Reload/Delete commands.
