### ISSUE TITLE
SQL Server Procedures and views with dot in name

### ISSUE THREAD

**Issue by jlrozano** [serge-rider/dbeaver#1996]
Hi,

I found a fail in SQL Server procedures and views with dot in name (ej [Cont.SP.XXXXXX]). When double click over item, I get the next message:

SQL Error [15250] [S1000]: The database name component of the object qualifier must be the name of the current database.

Using sql profile, I can see a call to sp_helptext with 'dbo.cont.sp.xxxx' parameter instead 'dbo.[cont.sp.xxxx]' or 'dbo."cont.sp.xxx"'

**Comment by serge-rider** [comment]
Indeed, it is a bug in DBeaver, thanks for report.
