### ISSUE TITLE
Creating new project, then new folder under scripts fails

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1998]
When you create a new project in 4.1.2 using File >> New, and picking Database Project it will create a new project with your name.

Do not type in anything under this screen:

![image](https://user-images.githubusercontent.com/6610039/29125115-7e983536-7ce0-11e7-954d-cf3300c5d47b.png)

You will then get a project.

However if you immediately create a new folder in the new project under the "Scripts" section it will fail with this error:

![image](https://user-images.githubusercontent.com/6610039/29125137-8f9a6eee-7ce0-11e7-8f28-1cc031bbf807.png)

However, if you create a new script in the Scripts folder of the new project it will create the script, and you can then subsequently create a new folder.

Perhaps the auto-folder creation that occurs when you create a new script should be added to the New Folder command as well?

**Comment by xantari** [comment]
Or, perhaps the easier solution is to pre-populate the project resource folder names. Actually that might be better?

**Comment by serge-rider** [comment]
Pre-populating folders isn't very good because in case of Eclipse integration it may create unneeded resources in existing projects. So I've just added "Scripts" (or other parent) folder existence before new folder create.
