### ISSUE TITLE
LIMIT not working with hive

### ISSUE THREAD

**Issue by kst83** [serge-rider/dbeaver#200]
I'm trying to use LIMIT with hive, but everytime I do it I get an error "SQL Error: Method not supported".
Is this a bug in DBeaver?

I know LIMIT should work, because it does with SQuirreL.

**Comment by serge-rider** [comment]
Could you post an full stack of that error (you can get it from Error Log).
And the test query.

**Comment by kst83** [comment]
The error log shows the following:

> eclipse.buildId=unknown
> java.version=1.8.0_65
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Tue Feb 16 10:05:10 CET 2016
> org.jkiss.dbeaver.model.exec.DBCException: SQL Error [40000] [42000]: Error while compiling statement: FAILED: ParseException line 1:0 cannot recognize input near 'limit' '100' '<EOF>'
> 

The query looks like this:

```
select count(*)
from wtr.wtr_events_parquet
where year = 2016
and month = 1
and day = 1;
limit 100;
```

**Comment by serge-rider** [comment]
You have an error in the query - extra semicolon character before LIMIT. Your query should look like this:
```
select count(*)
from wtr.wtr_events_parquet
where year = 2016
and month = 1
and day = 1
limit 100;
```

**Comment by kst83** [comment]
Ah sorry, that was a typo. Without it I get the following error:

> eclipse.buildId=unknown
> java.version=1.8.0_65
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Tue Feb 16 10:33:46 CET 2016
> org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Method not supported
>

**Comment by serge-rider** [comment]
Is there any stacktrace? Doubleclick on the error (or on the nested error).

**Comment by kst83** [comment]
Sorry, didn't notice there was a stack trace. It looks like thos:

> org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Method not supported
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:232)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:1)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:77)
> 	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:549)
> 	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:340)
> 	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1398)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
> 	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:100)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> Caused by: java.sql.SQLException: Method not supported
> 	at org.apache.hive.jdbc.HiveResultSetMetaData.isWritable(HiveResultSetMetaData.java:145)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.isWritable(JDBCResultSetMetaDataImpl.java:224)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:93)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:68)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.createColumnMetaDataImpl(JDBCResultSetMetaDataImpl.java:58)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.<init>(JDBCResultSetMetaDataImpl.java:52)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createResultSetMetaData(JDBCFactoryDefault.java:59)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.createMetaDataImpl(JDBCResultSetImpl.java:1684)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:230)
> 	... 9 more

**Comment by serge-rider** [comment]
It is a bug in DBeaver (or not really a bug - because error actually happens in Hive driver - but a kind of misfunction). I'll add a workaround in the next version.
Thanks for report!

**Comment by kst83** [comment]
That's great, thanks!

**Comment by DanKHansen** [comment]
Sorry for bringing this up again, but just tried it .... 
If DBeavers ResultSet fetch size is set to e.g. 200, setting LIMIT to 500 still only returns 200 :-) ..... setting LIMIT to eg. 100, returns 100 rows as expected .... ie. the ResultSet fetch size overrules the LIMIT calus in the select statement.
You can of course set ResultSet fetch size individual for each connection

This, more or less just for info.

**Comment by serge-rider** [comment]
Thanks for info.
I'll add special config for Hive driver so it won't use JDBC maxRows function.

For now you could just disable fetch size (set it to 0 or some very big number)
