### ISSUE TITLE
Views don't show clickable foreign key links

### ISSUE THREAD

**Issue by zmorris** [serge-rider/dbeaver#2000]
In DBeaver Community Edition 4.1.2 on Mac OS X 10.12.5 (16F73) with MySQL 5.7.9, this example creates a view `foobar` directly from table `groups`:

```sql
CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `user` (`id`, `name`)
VALUES
    (1,'Hans'),
    (2,'Bernd');


CREATE TABLE `groups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user` int(11) unsigned NOT NULL,
  `name` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `user` (`user`),
  CONSTRAINT `groups_ibfk_1` FOREIGN KEY (`user`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `groups` (`id`, `user`, `name`)
VALUES
    (1,1,'Gruppe A');

CREATE VIEW `foobar` AS select * from groups;
```

But the clickable foreign key link only shows when displaying tables, not views:

Showing table `groups`:

![screen shot 2017-08-09 at 1 19 09 pm](https://user-images.githubusercontent.com/1406101/29139791-5da78ee2-7d05-11e7-9499-c04b9b549578.png)

Showing view `foobar`:

![screen shot 2017-08-09 at 1 19 40 pm](https://user-images.githubusercontent.com/1406101/29139816-727c972c-7d05-11e7-974e-38f47aee7889.png)

**Comment by serge-rider** [comment]
This is because views don't have foreign keys.
Potentially it is possible to extract source table(s) from a view in MySQL but it is still tricky. Ciew might be combined from multiple tables and expressions. Some multi-column foreign keys may present there partially etc.
So this feature is questionable.. Any thoughts?

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
