### ISSUE TITLE
Informix Helpers

### ISSUE THREAD

**Issue by INGCRENGIFO** [serge-rider/dbeaver#2002]
Hello, I have noticed that the helpers in informix do not work, it does not show me the tables unless I type "dbname - shcema- table", so does the fields.

Another error that happens, and maybe the reason for being the first error I report is the following.

"Active database change is not supported"

You may be able to configure the following queries to catch the error.

select * from systables where tabname like("tablename%")
select * from syscolumns where colname like("columname%")

**Comment by serge-rider** [comment]
Maybe this will be solved with #1932 and #1870 fix.
