### ISSUE TITLE
Tutorial plugin

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#2003]
We need to add tutorial plugin with demo database (SQLite) packaged in standard DBeaver distribution.

**Comment by Sargul** [comment]
Hi Serge,

I'm not quite sure what you mean by a tutorial plugin?

A plugin to learn how to create plugins or a plugin to show DBeaver features to a use?

**Comment by serge-rider** [comment]
Second one. It will include sample database (SQLite).
