### ISSUE TITLE
Can't see Sybase Database Object in UI

### ISSUE THREAD

**Issue by ghost** [serge-rider/dbeaver#2005]
When  connected to Sybase DB, I can only use  select * from sysobjects  to see tables. The UI can't show tables in side window.  Is this a BUG?

**Comment by serge-rider** [comment]
Please check Error Log view and/or debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any error during connection.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
