### ISSUE TITLE
MSSQL Server. Code completion fail on tables with a dot in name

### ISSUE THREAD

**Issue by jlrozano** [serge-rider/dbeaver#2006]
Code completion don't show column names on tables with a dot in name. (ej [Cat.XXXX])

SQL profiler show this trace when ctlr + space is pressed:

declare @p1 int
set @p1=4
exec sp_prepexec @p1 output,N'@P0 nvarchar(4000),@P1 nvarchar(4000),@P2 nvarchar(4000),@P3 nvarchar(4000)',N'EXEC sp_tables @P0, @P1, @P2, @P3                                ',N'"Cat',NULL,NULL,NULL
select @p1
--------------------------------------------------------------------------------------------------------------
declare @p1 int
set @p1=5
exec sp_prepexec @p1 output,N'@P0 nvarchar(4000),@P1 nvarchar(4000),@P2 nvarchar(4000)',N'EXEC sp_stored_procedures @P0, @P1, @P2                        ',N'"Cat',NULL,NULL
select @p1

sp_columns is not called. 

Nevertheless, if I use a table without a dot in name, sp_columns is called:

declare @p1 int
set @p1=12
exec sp_prepexec @p1 output,N'@P0 nvarchar(4000),@P1 nvarchar(4000),@P2 nvarchar(4000),@P3 nvarchar(4000),@P4 nvarchar(4000),@P5 nvarchar(4000)',N'EXEC sp_columns_100 @P0, @P1, @P2, @P3, @P4, @P5                                                ',N'CHANGELOG',N'dbo',N'DistribucionQA2',N'%',N'2',N'3'
select @p1

**Comment by serge-rider** [comment]
This is a bug in completion processor. Thanks for report.

**Comment by jlrozano** [comment]
Hi. 

I compiled source code and the problem persist. 

I found, in SQLCompletionAnalyzer.java, in makeDataSourceProposals() method that "List<String> tokens = request.wordDetector.splitWordPart();" split tokens start with '['.

**Comment by serge-rider** [comment]
Please post sample DDL and query.
I tested this with column names auto-completion, perhaps it doesn't work in other cases.

**Comment by jlrozano** [comment]
Table:

CREATE TABLE DistribucionQA2.dbo.[Cont.Calendarios] (
	Id int NOT NULL,
	AnioInicio int NOT NULL,
	AnioFin int NOT NULL,
	IdVariante int NOT NULL)

Query:
SELECT DistribucionQA2.dbo.[Cont.Calendarios]. FROM.....

If I add this code to makeDataSourceProposals method, it work:

.......................
List<String> tokens_2 = new ArrayList<String>();
		String t="";
		for (int i = 0; i<tokens.size(); i++) {
			t+= t=="" ? tokens.get(i) :"."+tokens.get(i);
			if (t.startsWith("[")) {
				if (t.endsWith("]")) {
					tokens_2.add(t);
					t="";
				}
				
			} else {
				tokens_2.add(t);
					t="";
			}
			
		}
		
		tokens= tokens_2;
	
        String lastToken = null;
        for (int i = 0; i < tokens.size(); i++) {
......................................................

**Comment by serge-rider** [comment]
Real implementation is a bit more complex (because different databases use different quoting rules).
Please check new fix.

**Comment by jlrozano** [comment]
Ok, 

Thanks for the prompt attention
