### ISSUE TITLE
wrong WM_Class in .desktop file

### ISSUE THREAD

**Issue by michimartini** [serge-rider/dbeaver#2007]
Is this a regresssion?
Maybe not, but a remnant of #609 (DBeaver has incorrect WM_CLASS)
In the /usr/share/applications/dbeaver.desktop file there was an entry:
StartupWMClass=SWT

This causes DBeaver to be lumped together with other SWT based Java-apps  like Pentaho in the application switcher of the Gnome 3 desktop environment.
needs to be changed to this:
StartupWMClass=DBeaver

Then it works perfectly.

**Comment by serge-rider** [comment]
Well, current config is:
```
WM_CLASS=DBeaver
StartupWMClass=SWT
```
I can change StartupWMClass to DBeaver it but as far as I remember there were some issues with that?
Will
```
WM_CLASS=DBeaver
StartupWMClass=DBeaver
```
help everyone?

**Comment by michimartini** [comment]
Yes, there was quite a bit of confusion about how all this stuff about WM_Class and the .desktop files worked. However, it is now all crystal clear to me. There were 2 things that needed fixing: 

1. the app itself needed to set its own WM_Class immediately on startup 
2. the .desktop file needs to use that same value so the app windows are correctly identified

Point 1 was eventually fixed, but before that was acomplished everyone was trying different values in the .desktop file alone to fix it - which didn't work.
My  guess as to why there is both WM_CLASS and StartupWMClass is that you could get the desktop environment to stop the startup notification (bouncing icon or whatever) as soon as the splash screen or some other transient window belonging ot the app popped up (which would have the property mentioned in StartupWMClass) as opposed to the main application window, which would use the Xproperty mentioned in WM_CLASS. 

I can test under ubuntu/unity in addition to gnome3 - but i am very confident that this is the correct configuration.

**Comment by serge-rider** [comment]
Ok. Let's try it in 4.1.3
