### ISSUE TITLE
Script Save As saves changes to the original script as well

### ISSUE THREAD

**Issue by emelsk** [serge-rider/dbeaver#201]
Not sure if this is intended, but I just found out that Save As on script not only saves/creates the script with a new name, but it also saves the original script, too.

After doing Save As, I'd expect the editor to keep the original script intact (meaning 'as saved previously') and the new one saved/created with all of the changes between the two save operations. Currently, one ends up with two identical scripts under two different names. This happens in v3.5.9 EE running on Win x86-64.

**Comment by serge-rider** [comment]
Agreed, original script shouldn't be saved.
Thanks for report.
