### ISSUE TITLE
Exasol: DEFINE support

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#2011]

**Comment by Sargul** [comment]
I'm a bit curious where this comes from?

DEFINE is actually not supported by the exasol database. It's only a feature of the exaplus client which is what \@set does in DBeaver.

So basically it is already supported.

**Comment by Sargul** [comment]
On second thought one difference between DEFINE and @set is that when you DEFINE a variable in EXAPlus and execute a statement using this variable no popup is opened to query for parameters.

This is the only difference between DEFINE and @set I can think of

**Comment by serge-rider** [comment]
I actually can do this (add DEFINE as synonym for command @set specifically for Exasol) similarly to how it was done for MySQL and SOURCE. Popup also can be configurable.
This comes from email support.
