### ISSUE TITLE
DBeaver plugins install for distributions packagers

### ISSUE THREAD

**Issue by muflone** [serge-rider/dbeaver#2015]
Hi

I'm currently maintaining the dbeaver package in Arch Linux distribution but I would like to move in also the Office Extension and some other plugins in order to allow system wide installations for multi user systems and centralized installations.

Can you share some information about the plugins installations for packagers?
What I already tried was to put the plugins data in the plugins and features folders but dbeaver cannot find them.

Is there some way to install them system-wide and making the plugins available for all the users?

thank you in advance

**Comment by muflone** [comment]
After adding:
```
org.jkiss.bundle.apache.poi,3.16.0,plugins/org.jkiss.bundle.apache.poi_3.16.0/,4,false
org.jkiss.dbeaver.data.office,1.1.0,plugins/org.jkiss.dbeaver.data.office_1.1.0.jar,4,false
```
to configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
everything seems to work fine

**Comment by serge-rider** [comment]
Yes, adding these plugins into bundle list should solve the issue.
Also it can be achieved by modifying DBeaver.product or standalone/feature.xml.
The only reason why office is still not included in default CE distribution is big size of poi jars (which increase distribution size on 30%).

**Comment by muflone** [comment]
that's all
https://www.archlinux.org/packages/?q=dbeaver

thank you. closing

**Comment by serge-rider** [comment]
Great,
thanks for maintaining DBeaver package.
