### ISSUE TITLE
Sending query hints to Vertica

### ISSUE THREAD

**Issue by JoeGonzalezSSI** [serge-rider/dbeaver#202]
Hello
Vertica uses query hints that SQL editors generally see as comments.

Example:  insert /*+ direct */ into tablename ....

Some SQL Editors have an option to send the comments to the DB server instead of ignoring them.  Does DBeaver have this option anywhere?

**Comment by serge-rider** [comment]
DBeaver doesn't modify SQL queries before execution.
So these comments will be passed to server without any modifications.
This the default behavior and there are no options which affects it.

**Comment by JoeGonzalezSSI** [comment]
Thanks Serge, that is great to know!
