### ISSUE TITLE
error installing office plugin on 4.1.2

### ISSUE THREAD

**Issue by dariopnc** [serge-rider/dbeaver#2021]
Hi,
I had 4.1.0 with the Office plugin Installed, when I upgraded to 4.1.1 it got lost and I couldn't install it back due to #1933.

Now I'm on 4.1.2 and tried to install it back but I got the following error:

```
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Program Files\DBeaver\plugins\org.jkiss.bundle.apache.poi_3.16.0
```

![Screenshot](https://user-images.githubusercontent.com/15945411/29356590-01487f74-8275-11e7-896c-4a9d48190a86.PNG)

**Comment by serge-rider** [comment]
This is because DBeaver web site is now doesn't support plain HTTP.

So Office extension update site URL now is `https://dbeaver.jkiss.org/update/latest/` (I've just fixed wiki page).
Probably you will need to reinstall DBeaver before trying to setup Office extension (because of P2 cache).

Thanks for report

**Comment by dariopnc** [comment]
changing the protocol and reinstalling DBeaver solved the issue: will I have to go through this every time a new DBeaver update is released?

**Comment by serge-rider** [comment]
No, it was just a temporary problem because of increased web site security and outdated wiki article.

Now if you will use https protocol for office extension download then there shouldn't be any problems (with any version of DBeaver).

**Comment by dariopnc** [comment]
Same problem with 4.1.3 after upgrade, please REOPEN

**Comment by serge-rider** [comment]
Please give me a bit more details.
Office extension install (with https url) didn't work on fresh 4.1.3 install?

**Comment by dariopnc** [comment]
no, when installing the office extension, the error while opening the zip file happens again (probably due to the P2 cache, as you mentioned earlier)

**Comment by gitsno** [comment]
I am still seeing this issue - the resolution for me has been
1. Run DBeaver as Administrator when installing the Office extension.
2. Delete the artifacts.xml file from the C:\Program Files\DBeaver folder before installing the Office extension (I don't know if this could cause other unwanted side-effects but it has not so far for me and I've installed three or four times like this already).
