### ISSUE TITLE
Suggestion: changable "Workspace save interval"

### ISSUE THREAD

**Issue by nhut** [serge-rider/dbeaver#2023]
There is currently no option to change "Workspace save interval":
![image](https://user-images.githubusercontent.com/6004709/29365240-f20a31fe-829e-11e7-8343-24ba8415190d.png)

As the original Eclipse have it:
![image](https://user-images.githubusercontent.com/6004709/29365070-5402036a-829e-11e7-8ebb-0cc79df14805.png)

Would it be possible to have that option? As it's very annoying when "workbench.xmi"-file is being updated for every 5 minutes is in the Dropbox? I use DBeaver with start command: dbeaver.exe -data "%DROPBOX%\ProgramData\DBeaver"

**Comment by serge-rider** [comment]
Good point.
