### ISSUE TITLE
Active database change not supported in SAP Hana

### ISSUE THREAD

**Issue by sdb2017** [serge-rider/dbeaver#2027]
I recently set up a connection SAP Hana and am trying to connect to one of the databases therein. I continue to get the following message:
![image](https://user-images.githubusercontent.com/31081812/29387661-0cfa73b0-82af-11e7-91cd-f8264d0683ff.png)

I've checked the connection and driver settings multiple times and can't find anything entered improperly. The only weirdness I can find is that the driver class is always missing even though I select and save it every time. Otherwise, it's just defaulted to one of the databases and won't let me change to another. What am I missing?

**Comment by Sargul** [comment]
AFAIK every database in SAP HANA runs on a different port and thus the JDBC connection string is different (even on multi tenant installations).

DBeavervis only able to switch databases if it cam be done by an SQL statement within one JDBC connection (like on mysql).

so you will have to create multiple Connections in DBeaver for multiple Sap HANA databases.

**Comment by Sargul** [comment]
No feedback. Closing
