### ISSUE TITLE
[BUG?] When a field is too large scrollbar does not appear

### ISSUE THREAD

**Issue by lvlofenix** [serge-rider/dbeaver#2029]
![image](https://user-images.githubusercontent.com/10848573/29417849-f16d812c-8340-11e7-91fb-b0c79b3d8f92.png)

AUTOMATIC TRANSLATE BY GOOGLE 

Hi, sorry.... my English was very poor

When I try to show a field of type varchar too long I can not see the scroll bar to have full access to information  in grid mode.

Text mode appears normally.

![image](https://user-images.githubusercontent.com/10848573/29417949-47aba2e4-8341-11e7-84a9-392e6138a2a2.png)

**Comment by Sargul** [comment]
Select the value and hit SHIFT-Return:
![image](https://user-images.githubusercontent.com/5595511/29436072-371ec64a-83aa-11e7-859a-292625717934.png)

A popup will apear with the full value and scrollbars
