### ISSUE TITLE
Driver manager cannot set up MS SQL driver

### ISSUE THREAD

**Issue by fovea1959** [serge-rider/dbeaver#2030]
Unable to use the Driver Manager in DBeaver CE 4.1.2 (64 bit on Uvuntu installed from .deb) to set up MS SQL drivers:

```
Drive file download failed.
Do you want to retry?
Reason:
Can't open 'http://dbeaver.jkiss.org/files/jdbc/driver/mssql/sqljdbc4.jar':
Moved Permanently
```

Manually going to that URL produces

`You don't have permission to access /files/jdbc/ on this server.`

**Comment by Sargul** [comment]
fixed by #2024
