### ISSUE TITLE
No Run Button

### ISSUE THREAD

**Issue by timjohnarm** [serge-rider/dbeaver#2031]
I use a lot of VM's and the Ctrl Key is not always easy to use for Execute SQL Statement=Ctrl+Enter and yes I know I can get to it from the SQL Editor menu but that's slower.

**Comment by Sargul** [comment]
You can change the key binding for SQL Execution:
Window -> Preferences -> General ->Keys

![screenshot](https://user-images.githubusercontent.com/5595511/29435157-31f6bf96-83a6-11e7-8d0d-55ab265edee5.jpg)

**Comment by timjohnarm** [comment]
Nice. I still like a Run button though my Eclipse J2EE has one, Visual Studio has one, IBM Integration Bus has one, etc.

But having had a look again this morning  I am prepared to concede there may be a screen real estate issue in the DBeaver perspective.

**Comment by Sargul** [comment]
actually there is a run button in the SQL Editor Window
![image](https://user-images.githubusercontent.com/5595511/29444674-d97b2fa0-83e1-11e7-8670-2058053aa880.png)
