### ISSUE TITLE
Communications link failure[bug]

### ISSUE THREAD

**Issue by Arimis** [serge-rider/dbeaver#2034]
when i connected to remote mysql which set the "wait_timeout" option
 as 5 seconds, it will popup the follow error windows.Can we just auto reconnect to the server in this condition?

![_ _20170818150642](https://user-images.githubusercontent.com/8565266/29448130-baf3e2fc-8427-11e7-8643-7b3e04303dd3.png)
=================================================
SQL Error [08S01]: Communications link failure

The last packet successfully received from the server was 7,156 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
SQL Error [08S01]: Communications link failure

The last packet successfully received from the server was 7,156 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
  Communications link failure

The last packet successfully received from the server was 7,156 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
  Communications link failure

The last packet successfully received from the server was 7,156 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
    Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
    Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

**Comment by serge-rider** [comment]
You could try to set keep-alive settings (in connection properties, page General). This will prevent frequent database disconnect.

**Comment by Arimis** [comment]
I just change the settings following your advice, but the error come out the same way, see the attachment bellow, pls.
![dbware-connection-general](https://user-images.githubusercontent.com/8565266/29501893-8c7eedac-865e-11e7-9204-8fe6adae8b48.png)
![dbware-1-error-window](https://user-images.githubusercontent.com/8565266/29501899-940cea06-865e-11e7-854f-96943d7e2795.png)

And what makes me confused is that when my mysql server really set wait-timeout settings shortly as 5s, whatever I set my dbeaver keep-alive setting, it will disconnect(timeout) automatically  by mysql server, and if the dbeaver won't detect the real connection status and re-connect it automatically, this lost connection error will come out all the time.

**Comment by serge-rider** [comment]
Keep-alive interval value is measured in seconds so you need to set it to some valuer between 1 and 4. 
If you already did try this and this doesn't help - probably auto-reconnect is the only solution..

**Comment by Arimis** [comment]
i tried set the keep-alive interval value as 1000/2000/3000/4000 ms, unfortunately it keep getting the same result. I do think auto-reconnect is the solution. Thanks anyway!

**Comment by serge-rider** [comment]
Keep-alive (on General pref page) is in seconds, not milliseconds.

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.

**Comment by ssyang0102** [comment]
Ha ha ha ha，I also forgot

**Comment by seredniy** [comment]
in my case... i forgot to start server =) lol

**Comment by Ryanmcdermottperth1990** [comment]
Thank you @seredniy you saved me from a big rabbit hole - also forgot to start server lol
