### ISSUE TITLE
Data does not refresh when clicking "refresh" or when pressing F5.

### ISSUE THREAD

**Issue by thomasmoors** [serge-rider/dbeaver#2035]
Affected version is 4.1.2
Only after closing the entire apllication the data will be refreshed.

**Comment by Sargul** [comment]
Affected database type?
Refresh of Resultset in editor or in Table-Data View?

**Comment by thomasmoors** [comment]
**Affected database type?** MariaDB
**Refresh of Resultset in editor or in Table-Data View?** In both a select * query as well as in table-data-view

**Comment by thomasmoors** [comment]
@Sargul I think that was the issue, thank you so much. I must have clicked it on accident.

**Comment by jbrant** [comment]
I'm having the same issue with PostgreSQL 10 partitions not showing and autocommit is on.

**Comment by topharley** [comment]
> I'm having the same issue as the OP with PostgreSQL 10 partitions. Neither refreshing nor invalidating/reconnecting fixes the problem - only closing reopening the application works. Autocommit is turned on.

I'm having the same issue as the OP with PostgreSQL 10 too.
