### ISSUE TITLE
Pending loading of package and triggers 

### ISSUE THREAD

**Issue by nonpervenuto** [serge-rider/dbeaver#2038]
DBeaver 4.1.2
oracle-jdbc-driver-12.1.0.2.jar

When opening a package or a trigger the source code is not loaded. 
I only see: Loading 'some name' source...

But in the 'Query Manager' view i see the query being executed with a success result and no error under .metadata/.log
If I click on the option 'Open in SQL in console' and re-execute the query the text is loaded correcty in the result tab.

*It happens always on the same objects* so maybe is a parser issue?

With a different client i don't have the problem.
My oracle user have permission to read and modify those objects.

**Comment by G3ph4z** [comment]
Same here. (after updated to 4.1.2) When I want to edit my procedures, i see: 
--  Loading 'tranzakciok' source...

**Comment by Sargul** [comment]
when the loading message is shown did you try to hit F5?

I thought I had a bugbin the Exasol Plugin because I see the same behaviour on edit of scripts in Exasol.

There it can be resolved by refreshing the display

**Comment by nonpervenuto** [comment]
Yes, it worked just by pressing F5.

**Comment by G3ph4z** [comment]
The 4.1.3 solved the problem. :)

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.
