### ISSUE TITLE
Redshift JDBC driver in DBeaver needs updating to version 1.2.7.1003.

### ISSUE THREAD

**Issue by BigDataDaddy** [serge-rider/dbeaver#2039]
As a result of resolving [1897](https://github.com/serge-rider/dbeaver/issues/1897) the Redshift JDBC driver that ships with DBeaver needs to be upgraded to version 1.2.7.1003 or higher so that current versions of DBeaver have access to Redshift external table metadata and schemata that are access as part of the Redshift Spectrum feature. 

The new Redshift JDBC driver version can be obtained here: http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html.  

Licensing for driver redistribution can be obtained by following the instruction on the same linked page.

**Comment by serge-rider** [comment]
It was resolved in  #1897
