### ISSUE TITLE
The web directory containing JDBC drivers can't be accessed

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2041]
If I try to downloading JDBC drivers from DBeaver, I get an error message that the driver files can't be downloaded.

Seems that access to the "https://dbeaver.jkiss.org/files/jdbc" director is not allowed. Strangely the "https://dbeaver.jkiss.org/files" is allowed.

1) Start a normal webbrowser.
2) Surt to the address "https://dbeaver.jkiss.org/files/jdbc"
3) Error message "Forbidden. You don't have permission to access /files/jdbc/ on this server." are
    displayed.

**Comment by serge-rider** [comment]
Looks like duplicate of #2024

Directory browsing was disabled for a reason - it is not a bug.
