### ISSUE TITLE
Feature Request: Add of possibility to connect to a Microsoft SQL Server using a SERVER/INSTANCE address

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2042]
I have tried both the jTDS and the Microsoft Driver, but not been able to connect with the information below entered in the DBeaver connection string dialog.

  Host = MYSERVER/SQLXPRESS 
  Port =
  Database/Schema = Northwind
  User name = user_name
  Password = password

Guess that some extra functionality is needed to have that work in DBeaver.

**Comment by pdanie** [comment]
I close this issue myself.

Noted that both jTDS and Microsoft JDBC driver contain Advanced Connection Properties (a bit difference between the two driver types, but both have parameter for it).

**Comment by serge-rider** [comment]
Thanks for information
