### ISSUE TITLE
Feature Request: Would be nice if DBeaver could Navigate to referencing tables

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2044]
DBeaver - **Version 4.1.3**
DBeaver JDBC driver: **jTDS** or **Microsoft**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

It would be benificial if DBeaver could not only Navigate Link (to referenced tables), but also Navigate to referencing tables.

Compare functionality in JetBrains DataGrip.

[www.jetbrains.com/datagrip](http://www.jetbrains.com/datagrip)
[www.youtube.com/watch?v=Xb9K8IAdZNg](https://www.youtube.com/watch?v=Xb9K8IAdZNg) (_at timestamp 01:05 in the movie_)
[www.youtube.com/watch?v=RlNEwBhckDA](https://www.youtube.com/watch?v=RlNEwBhckDA) (_at timestamp 13:40 in the movie_)

**Comment by serge-rider** [comment]
Agreed, that would be helpful.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/33223889-2955af06-d175-11e7-9ebc-ecec2b7e3c88.png)
![image](https://user-images.githubusercontent.com/6398845/33223897-3e4bfc3a-d175-11e7-889f-fc1b282e85ce.png)
