### ISSUE TITLE
Java-style comment blocks are still an issue with execute script (ALT+x)

### ISSUE THREAD

**Issue by mtdeguzis** [serge-rider/dbeaver#2045]
See: #22  
Version: 4.0.5

Invalid with ctrl+enter (execute SQL statement)
```
/* Comment
 * 
 */
show tables;
```

valid with ctrl+enter (execute SQL statement)
```
/* Comment
 * 
 */

show tables;
```

All of the above invalid with alt+x (execute script). Execute SQL statement finds the closest line of actual SQL code and runs it. I appears blank lines are considered some kind of 'line break' for the interpreter.

```
/*
 * Comment <-------- execute SQL statement picks up show databases
 */

show databases;

/*  <-------- execute SQL statement picks up show tables
 * Comment
 */

show tables;
```

Error:
```
SQL Error [40000] [42000]: Error while compiling statement: FAILED: ParseException line 1:0 cannot recognize input near '/' '*' 'Comment'
  Error while compiling statement: FAILED: ParseException line 1:0 cannot recognize input near '/' '*' 'Comment'
    Error while compiling statement: FAILED: ParseException line 1:0 cannot recognize input near '/' '*' 'Comment'
      java.lang.RuntimeException: org.apache.hadoop.hive.ql.parse.ParseException:line 1:0 cannot recognize input near '/' '*' 'Comment'
```

Is there a reason why a blank line after the ending comment delimiter is required?

**Comment by carlosspohr** [comment]
Hi @mtdeguzis ,

Testing it on current release ```4.1.3```, it seems OK with ``Alt+X`` option.

![image](https://user-images.githubusercontent.com/637767/29577748-f3d2cb1a-8742-11e7-8272-7d238f4e73a3.png)

**Comment by mtdeguzis** [comment]
Ok, good. Allow us a little time to get the new version and test.

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.
