### ISSUE TITLE
Feature Request: Include connection name in results set along with details of rows fetched

### ISSUE THREAD

**Issue by rythym05** [serge-rider/dbeaver#2046]
Can you include the Database connection name in the result set like shown below. I often run the same query across different environments such as PROD and Test with multiple tabs and often loose track of which tab was executed with which DB connection  

![image](https://user-images.githubusercontent.com/29409893/29544111-ccbc67c8-869a-11e7-9d8e-ef149144ae27.png)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/30401723-ea526ef8-98e3-11e7-9e00-e9a78b7c890a.png)

**Comment by rythym05** [comment]
Thanks for fixing this. But it doesn't fully fix the issue. Thought the connection name shows in the status, the moment I switch connections, the information refreshes to show as below 

![image](https://user-images.githubusercontent.com/29409893/30709407-fc4e1eee-9eb6-11e7-9bac-9293e70516b4.png)

The main request for this feature is that many often run the same query across different environments such as PROD and Test with multiple tabs and may want to keep track of which results set tab was executed with which DB connection.

**Comment by serge-rider** [comment]
I see. Connection change status message shouldn't be updated in all tabs, just in the active one.

**Comment by serge-rider** [comment]
See fix in the next version

**Comment by rythym05** [comment]
I still see the same issue in 4.2.2. Switching connection and moving to previous tab doesn't list the connection with which the query was executed.

**Comment by serge-rider** [comment]
Can't reproduce. This is how it works in my env:

![connection-name-in-status](https://user-images.githubusercontent.com/6398845/31065098-5830dcf0-a74b-11e7-980e-a777be0debff.gif)

**Comment by rythym05** [comment]
Can you please check this out ? The moment you change the connection, the status info is lost. 

![steps](https://user-images.githubusercontent.com/29409893/31355132-e7450efa-aced-11e7-924d-47a8655bbdef.gif)

**Comment by rythym05** [comment]
@serge-rider Did you get a chance to check my screenshots above ?

Thanks

**Comment by serge-rider** [comment]
Yes, I can reproduce this.
And I don't know how to fix this. Because previous status message is removed by connection re-opening operation status. I can't just ignore this new status message...
