### ISSUE TITLE
Additional software and DBeaver upgrades broken

### ISSUE THREAD

**Issue by dariopnc** [serge-rider/dbeaver#2048]
Everytime I upgrade DBeaver (happened in every update from 4.1.0 through 4.1.3) additional software (Office Extension) gets removed and has to be reinstalled.

That wouldn't be such a big deal if the Availbale Software Sites were preserved on upgrades.

Which wouldn't be that bad if it wouldn't spawn an error about the CheckTrustPhase org.jkiss.bundle.apache.poi_3.16.0 as in #2021 

Is it possible to redesign the process to address the first two problems?

**Comment by serge-rider** [comment]
Yes, I'm going to improve/fix issues with extensions install in 4.2
