### ISSUE TITLE
Add support for native Redshift Driver

### ISSUE THREAD

**Issue by jforr** [serge-rider/dbeaver#205]
This is a feature request to add default support for the redshift driver.  There are some small incompatibility issues with the existing postgres driver.

http://docs.aws.amazon.com/redshift/latest/mgmt/install-odbc-driver-windows.html

**Comment by serge-rider** [comment]
Agreed. And that's easy.
One problem: Amazon still didn't publish jdbc driver in Maven. So automatic driver version update won't be possible. I'll just set the link on the most recent version in driver config.

**Comment by jforr** [comment]
Thanks.  I'll submit a ticket to AWS to get them to add maven repository support.
