### ISSUE TITLE
Open Resource (Ctrl+Shift+R) does not work 

### ISSUE THREAD

**Issue by MahatmaFatalError** [serge-rider/dbeaver#2055]
See screenshot.

I assume all entities should be listed, but there is nothing

![image](https://user-images.githubusercontent.com/776825/29570953-425247e2-8758-11e7-9b0d-1c5ba392d775.png)

**Comment by serge-rider** [comment]
<kbd>Ctrl+Shift+R</kbd> searches for file system resources (e.g. scripts).
To search for database objects use <kbd>Ctrl+Shift+D</kbd> (or Open Database Object menu item)

**Comment by MahatmaFatalError** [comment]
@serge-rider Thanks for enlighten me. Seems this Dialog listens to the datasource of the active selection in the tree. If there are items of different active connections selected in the tree, the selection only gets the datasource of the item which was selected at last. It could be a little improvement to support multi-selection via StructuredSelection. Then the dialog could listen to all datasources which are selected.

Otherwise this ticket can be closed.

**Comment by serge-rider** [comment]
Open Object action support only single connection (combining search results from multiple connections of different types isn't that easy).
However you can create feature request for multiple connections support.
