### ISSUE TITLE
Show disk space per entity as second column in navigation tree

### ISSUE THREAD

**Issue by MahatmaFatalError** [serge-rider/dbeaver#2057]
Like in HeidiSQL it would be great to so which entity (table, materialized view, index) consumes how much disk space.

Suggestion: A second column in Database Navigator or Projects view to show the size of the entity
![image](https://user-images.githubusercontent.com/776825/29572195-d91c3892-875b-11e7-86a5-900fdde2e15b.png)

**Comment by serge-rider** [comment]
You can see this information in schema editor. Double-click on "Tables" element: there are row count and data length columns.

**Comment by serge-rider** [comment]
However, maybe it'll make sense to add configurable set of columns in database navigator view as well..

**Comment by MahatmaFatalError** [comment]
@serge-rider I agree, to let the user configure columns in the navigator seems to be a bigger thing but  opens a lot of other opportunities, like owner or description (if the DB supports to comment on entities, afaik Postgres does https://www.postgresql.org/docs/current/static/sql-comment.html)

BTW, I found the row count in the schema editor. but there is no data length column. I also checkt in column configuration.
![image](https://user-images.githubusercontent.com/776825/29704942-2715c866-897c-11e7-9a26-dec632fa818f.png)

**Comment by serge-rider** [comment]
In regards to tale properties:
1. You can configure visible columns (right click on header->Cofigure columns).
2. To see actual row count enable Preferences->Database->Metadata->"Read expensive properties" option

Probably we need separate feature request for db navigator columns configuration.

**Comment by MahatmaFatalError** [comment]
> To see actual row count enable Preferences->Database->Metadata->"Read expensive properties" option

Thank you, that's what I missed ;) Now disk space is shown.

> Probably we need separate feature request for db navigator columns configuration.
Yes, I will create a new feature request to collect some ideas.
