### ISSUE TITLE
chinese character in json cell can't decoded right!

### ISSUE THREAD

**Issue by cathemlin** [serge-rider/dbeaver#2059]
mysql 5.7-json type, chinese character shows not right, but in varchar type cell, chinese character shows perfect.

encode:utf-8
OS: debian 8

**json cell:**
[{"contactName": "çæä¹¦",  "telCheckResult": "0", "contactRelation": "1"}, {"contactName": "å¼ å°å",  "telCheckResult": "0", "contactRelation": "2"}]

**supposed to be like this:**
[{"contactName":"泡泡糖", "telCheckResult":"0", "contactRelation":"1"},{}]

**Comment by serge-rider** [comment]
Thanks for report.

**Comment by serge-rider** [comment]
This is actually the bug in MySQL driver 5.1.39 (https://bugs.mysql.com/bug.php?id=80631)
I'll change default MySQL driver version config to 5.1.44.

Workaround: go to driver manager, edit MySQL driver, click on Download/Update -> change driver version to 5.1.44 (by clicking on version number).
