### ISSUE TITLE
SQL Editor context menu improvement

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#206]
Dbeaver certainly offers comment toggling via the "View" menu, but as I use Dbeaver I'm constantly wishing these same options were offered in the context-menu that appears when I right-click highlighted text.

This feature would reduce mouse-travel. Placing these options into the context-menu makes sense because it puts the feature "where the user's mouse is at" (at the text just highlighted) requiring the least amount of mouse-travel to achieve the feature.

**Comment by r-richmond** [comment]
to minimize "mouse-travel" why not just use the hotkey?

control /

**Comment by serge-rider** [comment]
+1. Or ctrl+shift+/.
There are a lot of useful command which can be put in the context menu. But eventually this will make context menu unusable. It is already a bit messy.

**Comment by Lonniebiz** [comment]
It wouldn't look messy if you simply added one menu item  "Comments" and then a sub-menu for all that can be done regarding comments:

Comments >
             > Toggle Line Comment
             > Toggle Block Comment

Hot keys are fine, but "context-menus on highlighted text" should answer the question:
"What are all the things I can do with the text I've highlight?"

Right-click in General should tell someone: What can I do with what I've just right-clicked on.

**Comment by serge-rider** [comment]
The problem is: you can do too many different things with highlighted text, putting all of them in the context menu will ruin it.
They are: all clipboard operations, find/replace, comments, case conversion, identifier/line navigation, all sorts of auto-completion and tens of text editor commands (you can see them in shortcut customization preferences). How to decide what commands should be in the context menu? Different people uses different work patterns.
The only good solution would be to make context menu configurable.
You could create another feature request if you think that it's a reasonable option.

**Comment by Lonniebiz** [comment]
The current context-menu has no sub-menus, which (when coupled with proper categorization) minimizes the clutter (you're concerned about) from the initial context-menu.

**Comment by serge-rider** [comment]
Recent text editor improvement added 5 additional context menu items (provided by Eclipse).
I don't very like that, maybe some context menu reorganization is needed but for now I'm too busy to think about this. I renamed this issue to make it more general.
If you have any ideas - please post details.

**Comment by Lonniebiz** [comment]
I do see (as you mentioned) that [the context menu is starting to utilize sub-menus](http://neartalk.com/ss/2016-04-04_001_468x501.png) (for "Open With" and "Show in").

It would indeed take some thought to properly organize a hierarchy of context menus. But, I don't think you have to do it all at once; it seems you could do it one good idea at a time.

You've already divided the context menu into sections I see. Since you have already made the execution icons so conveniently located on the tool bar, I wonder if anyone would complain if you grouped those same icons into a sub-menu called "Execution" in the context menu to make space for "Comments" that would contain a sub-menu of all the comment related tasks.

It's really pretty good as is, I just like commenting/uncommenting to be in the context menu because I keep forgetting the shortcut keys for it :)

**Comment by serge-rider** [comment]
Some SQL editor menu redesign will be done in 3.6.7.
![sql-editor-menu](https://cloud.githubusercontent.com/assets/6398845/15085039/515db4de-13e0-11e6-85a0-bb4caf8f7d07.png)

**Comment by Lonniebiz** [comment]
I really like the way you've organized it; it seems perfect.
