### ISSUE TITLE
Provide instructions how to upgrade Mac (dmg) release to latest version

### ISSUE THREAD

**Issue by christianbalzer** [serge-rider/dbeaver#2062]
Title says it all, pretty much.

It would be helpful if there were instructions on the start page on how to upgrade a dmg installation on a Mac (without loosing settings)... :)

**Comment by serge-rider** [comment]
Just reinstall (overwrite old version) by drag-n-droppping DBeaver into Applications.
Settings won't be lost (settings are store in separate folder `.dbeaver4` in user home).

We'll add extra instructions on the download page, thanks for noticing.

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.

**Comment by christianbalzer** [comment]
This still needs mentioning at the bottom of the downloads page... :)

**Comment by serge-rider** [comment]
Agreed. Info on https://dbeaver.jkiss.org/download/ was updated
