### ISSUE TITLE
Checksums link on download page redirects to old 4.1.1 checksums

### ISSUE THREAD

**Issue by christianbalzer** [serge-rider/dbeaver#2063]
The link on https://dbeaver.jkiss.org/download/ pointing to https://dbeaver.jkiss.org/files/checksum-latest redirects to https://dbeaver.jkiss.org/files/4.1.1/checksum/, i.e. version 4.1.1, when it should currently redirect to https://dbeaver.jkiss.org/files/4.1.3/checksum/, i.e. version 4.1.3... :)

**Comment by serge-rider** [comment]
Fixed (it was a bug in release publishing script).
Thanks for report!
