### ISSUE TITLE
DBeaver's Mac version isn't signed; thus won't run

### ISSUE THREAD

**Issue by christianbalzer** [serge-rider/dbeaver#2064]
<img width="532" alt="screen shot 2017-08-23 at 11 05 17" src="https://user-images.githubusercontent.com/2813098/29610729-051f5216-87f3-11e7-8578-6787192eb8c3.png">

I downloaded the dmg version. Apple now apparently enforces that apps need to be signed with an AppStore dev certificate. I know there are ways to force my Mac to install unsigned software, but it'd be nicer if releases were actually signed... :)

**Comment by tati-kru** [comment]
Hi @christianbalzer. It looks like something went wrong during the new version creation because DBeaver dmg is signed with an AppStore dev certificate. We will check.

**Comment by serge-rider** [comment]
@christianbalzer please provide a bit more details. 
- What is your Mac version? 
- Are you online when you install DBeaver?

Actually dmg is signed with standard code sign certificate and it works well on most of machines/Mac versions.

**Comment by christianbalzer** [comment]
I'm using Sierra 10.12.5 and am connected to the internet via corporate proxy.

**Comment by christianbalzer** [comment]
Just removed it and tried again. Same issue. Are you sure the app in the package is signed?

**Comment by christianbalzer** [comment]
Is this maybe because the root CA isn't Apple, but this?
```
Authority=InterTechGeo
Authority=thawte SHA256 Code Signing CA
Authority=thawte Primary Root CA
```

For comparison, IntelliJ IDEA Community edition:
```
Authority=Developer ID Application: JetBrains s.r.o.
Authority=Developer ID Certification Authority
Authority=Apple Root CA
```

Command run: `codesign -dv --verbose=4 /Path/To/Application.app`

**Comment by serge-rider** [comment]
Thanks for details.
Yes, we need Apple Developer ID so this certificate will be recognized even without public internet access.
We are working on this, hopefully it'll be added to all MacOS distributions after 4.2

**Comment by christianbalzer** [comment]
BTW: KeePassXC has similar issues, and links to relating Apple docs: https://github.com/keepassxreboot/keepassxc/issues/723

**Comment by serge-rider** [comment]
We'll apply Apple developer program in the beginning of October. 
There is a lots of bureaucratic stuff over there. So moving to 4.2.3.

**Comment by serge-rider** [comment]
Done.
Next version of DBeaver will be signed with Apple developer certificate. You can check this in EA (https://dbeaver.jkiss.org/files/ea/)
