### ISSUE TITLE
Large memory consumption 5GiB

### ISSUE THREAD

**Issue by douglascomim** [serge-rider/dbeaver#2065]
Hi,
I'm reporting the overzealous memory consumption, only with the program open, with no scripts running.
Today arrived at 5GiB.

Dbeaver 4.1.3
OS: Ubuntu 17.04 zesty
Kernel: x86_64 Linux 4.10.0-32-generic
Openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

![dbeaver](https://user-images.githubusercontent.com/29402875/29613826-1f3a6ba0-87de-11e7-829d-8ff0477af657.png)

**Comment by carlosspohr** [comment]
Hi there,

I've heard about it before at [this thread](https://github.com/serge-rider/dbeaver/issues/1451), please take a look, may it's the cause for this huge memory consumption.

**Comment by douglascomim** [comment]
Thanks man @carlosspohr,
Using `export SWT_GTK3 = 0` solved my problem.

Thanks.

**Comment by tati-kru** [comment]
Thank you @carlosspohr. It looks like this question was solved. It will be closed.
