### ISSUE TITLE
Foreign key link, open result in new tab

### ISSUE THREAD

**Issue by collicalex** [serge-rider/dbeaver#2066]
Hi,

In result set of a table, if a data (cell) is a foreign key to another table, it displayed an icon into the cell.
Clicking on this icon display the linked data... 
It's a really great feature.

BUT it replace the current displayed data.
Is it possible to display the clicked FK into a new tab?
(and in the new tabl, clicking on a FK will open/display data in a new tab, so having 3 tabs displayed etc etc etc).

Thanks

**Comment by serge-rider** [comment]
You can open referenced table by pressing <kbd>CTRL</kbd> key while clicking.

**Comment by collicalex** [comment]
Yes and no...
I have the SQL Editor part, which can have multiple tab (multiple editor).
Each tab have it's own result part, with multiple tab if I execute multiple select statement at once.

When ctrl+clik; it open a new tab... at the level of sql editor part, not in result part.

**Comment by serge-rider** [comment]
Yep. This is not a bug but a kind of misfunction. 
Perhaps this behavior should be configurable.

**Comment by serge-rider** [comment]
By default in SQL editor FK navigation will open just new results tab. In table editors it will work as before (open new table editor)
