### ISSUE TITLE
systray icon

### ISSUE THREAD

**Issue by collicalex** [serge-rider/dbeaver#2067]
The new 4.1.3 version display an icon in system tray (windows 7).
Why?

The only context menu on this icon is "Show DBEaver"... but as DBEaver is already runnning, it's already into the taskbar... just need a click into the taskbar to put it in front...

Is is possible to remove this systray icon?

**Comment by carlosspohr** [comment]
Hi there,

I always saw this one after long statements were finished, I don't remember if it had some action, but it doesn't gone until you close or restart Dbeaver.

**Comment by serge-rider** [comment]
System tray icon is mostly for notifications about long statements finish/database backup/restore. There are no special actions on this icon (yet).
Anhow you can disable tray icon in preferences.

**Comment by collicalex** [comment]
Do not see the systray icon setup in preference...
Whatevers, it's not important :)
You can close the ticket.

**Comment by serge-rider** [comment]
![default](https://user-images.githubusercontent.com/6398845/29662892-89dcffe2-88d1-11e7-9386-361d7f0b500e.png)

**Comment by allanlaal** [comment]
@serge-rider can the long-time operations functionality work without showing a tray icon?

**Comment by serge-rider** [comment]
In theory yes. In fact - no. And it doesn't make much sense - icon appears only after first notification.
