### ISSUE TITLE
Visual modification with order by: error...

### ISSUE THREAD

**Issue by undertherainITA** [serge-rider/dbeaver#2068]
Hi.
If I am editing the data of a table in visual mode and I make an order by pressing a column, the changes are lost without a confirmation dialog.
Congratulations for the great job.
It's a shame that you've paid for the Enterprise version now.
You did well, congratulations... ;)
Thanks.
Ciao... ;)

**Comment by serge-rider** [comment]
This problem happens only if full resultset is visible (i.e. there are no more rows and reordering can be done without additional server roundtrip).
Will be fixed in 4.2.
