### ISSUE TITLE
PostgreSQL Indexes

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#2069]
postgresql-9.4-1206.jdbc4,jar
Error on open table editor on tab "Indexes":

SQL Error [42703]: ERROR: column am.amcanorder does not exist
  Position: 427
  org.postgresql.util.PSQLException: ERROR: column am.amcanorder does not exist
  Position: 427

**Comment by serge-rider** [comment]
Can't reproduce (this error may be a warning in debug log but it shouldn't break indexes load).
Could you post error stacktrace (you can get it in Error Log view or in log files: https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by gabehollombe-spire** [comment]
Try using the Postgres driver instead of the Postgres Generic Driver. I had the same problem but it was resolved by using the Postgres driver (scroll down in the driver list)

**Comment by serge-rider** [comment]
Yes, this problem happens only with Generic driver and only with 9.4-1206.jdbc4 driver version.
I've fixed PG generic driver config. This problem doesn't happen in recent PG drivers.

**Comment by garbles9100** [comment]
What is "the Postgres driver"? I see a JDBC driver and an ODBC driver from google searches. Which driver should I be updating?

**Comment by serge-rider** [comment]
https://github.com/serge-rider/dbeaver/wiki/Connect-to-database
There are two PostgreSQL drivers:
![image](https://user-images.githubusercontent.com/6398845/30510401-b35e14f8-9acb-11e7-987f-9ab94fcda69e.png)
You need the default `PostgreSQL` one.

**Comment by garbles9100** [comment]
That worked! Thanks! I can see all of my constraints and am no longer getting that Indexes error :)

**Comment by serge-rider** [comment]
Great!
Thanks for info
