### ISSUE TITLE
wrong encoding when generate insert with cyrillic words 

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#207]
When i generate insert with cyrillic words i get unreadable text

![default](https://cloud.githubusercontent.com/assets/9958813/13136030/1000745a-d627-11e5-94c4-102b4442271c.PNG)

DBeaver 3.5.9

**Comment by infectormp** [comment]
checked on mariadb and oracle

**Comment by serge-rider** [comment]
It happens with any database and with any non-latin characters.
Actually it is a bug in "View SQL" dialog - it used utf-8 instead of real local encoding. BTW SQL generation works fine in SQL editor.
Fix will be in the next version. Thanks for report!

**Comment by infectormp** [comment]
Work fine if i use Export Resultset to SQL INSERT statements
When i use Generate SQL->Insert i get bug described above

**Comment by infectormp** [comment]
This fix also fix encoding in Persist Changes dialog?

**Comment by serge-rider** [comment]
Yes, it fixes all View SQL dialogs.
