### ISSUE TITLE
not clear how to compare and synchronize databases

### ISSUE THREAD

**Issue by COLABORATI** [serge-rider/dbeaver#2071]
I am trying to compare and synchronize two databases, but it is totally unclear for me how that happens. Unfortunately there is zero information about how to use that feature.

Please at least would you like to give some hints how to accomplish a compare and synchronization? Thank you very much for your attention!

**Comment by serge-rider** [comment]
Database sync is not yet supported. You can only compare two databases/schemas/tables and generate html report.
Diff generation in DDL form and real sync will be implemented in #957

**Comment by scruel** [comment]
> 
> 
> Database sync is not yet supported. You can only compare two databases/schemas/tables and generate html report. Diff generation in DDL form and real sync will be implemented in #957

When will you support database sync function?

**Comment by AtillaSE** [comment]
I want to bump the request for this feature again. Would be really handy to roll out a new database structure without moving over all data

**Comment by E1izabeth** [comment]
Please create a new issue for this feature request.
