### ISSUE TITLE
Move items in Database Navigator up and down

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#2072]
I have read #833 and https://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1912

How do I re-order the connections in a folder in Database Navigator?

![20170824t092934_hp-radw04](https://user-images.githubusercontent.com/25423046/29645283-18b0683a-88af-11e7-9ca0-77468ce1b9df.png)

**Comment by serge-rider** [comment]
There is no way to reorder connections (they are always in alphanumeric order).
But there was a bug - DBeaver didn't sort connections on new connection create.
Fixed.
