### ISSUE TITLE
Dbeaver not updating to 4.1.3 on ubuntu

### ISSUE THREAD

**Issue by eldarnegrinperion** [serge-rider/dbeaver#2073]
hi,
I have version 4.1.2 64bit installed on my ubuntu 16.04, when clicking install on the latest 4.1.3 the "ubuntu software" goes back to 4.1.2 and 4.1.3 isn't installing.

how do i solve this issue?

**Comment by serge-rider** [comment]
What type of installer do you use (rpm, zip)?
Do you download it directly from dbeaver web site?

**Comment by eldarnegrinperion** [comment]
it's not the debian pkg problem. it's the ubuntu software center. 
`dpkg -i /pathtopkg/dbeaver-ce_4.1.3_amd64.deb; apt install -f; `
works like a charm.

**Comment by serge-rider** [comment]
Thanks for information
