### ISSUE TITLE
String index out of range: -1 error on auto type

### ISSUE THREAD

**Issue by ceesvl** [serge-rider/dbeaver#2075]
Hi,

When using auto type on a simple table I get the following error and the drop down list in the SQL editor is "No proposal"

![image](https://user-images.githubusercontent.com/19190330/29659213-ce9001c0-88bd-11e7-8db0-9744596fca38.png)

I am using the community version 4.1.3 with a connection to Exasol.

Best regards,
Cees

Table example:
CREATE TABLE "Md"."o_Postcode" (
		"Id" DECIMAL(6,0) ,
		"Postcode" VARCHAR(6) UTF8 ,
		"PostcodeId" DECIMAL(8,0) ,
		"PostcodeNumber" DECIMAL(4,0) ,
		"PostcodeCharacter" VARCHAR(2) UTF8 ,
		"MinNumber" DECIMAL(5,0) ,
		"MaxNumber" DECIMAL(5,0) ,
		"NumberType" VARCHAR(5) UTF8 ,
		"Street" VARCHAR(100) UTF8 ,
		"City" VARCHAR(100) UTF8 ,
		"CityId" DECIMAL(5,0) ,
		"Municipality" VARCHAR(100) UTF8 ,
		"MunicipalityId" DECIMAL(5,0) ,
		"Province" VARCHAR(100) UTF8 ,
		"ProvinceCode" VARCHAR(2) UTF8 ,
		"Lat" DECIMAL(16,13) ,
		"Lon" DECIMAL(16,13) ,
		"RijksdriehoekX" DECIMAL(26,20) ,
		"RijksdriehoekY" DECIMAL(26,20) ,
		"Location_detail" VARCHAR(10) UTF8 ,
		"Changed_date" VARCHAR(20) UTF8 ,
		"LatLonPoint_GeoType_D" GEOMETRY(4326) 
);

**Comment by serge-rider** [comment]
Thanks for report
