### ISSUE TITLE
Ctrl + O defect

### ISSUE THREAD

**Issue by btaing** [serge-rider/dbeaver#2078]
Noticed two issues when pressing Ctrl + O to open an sql file:

1. If there is nothing open in SQL editor, pressing Ctrl + O does not do anything. The open file dialog box does not pop up.

2. When pressing Ctrl + O while a sql file is open, the contents of the chosen file in the dialog box will replace the contents of the sql file that was previously opened. I don't think this should be the case.

**Comment by btaing** [comment]
This is actually an enhancement? I'm surprised. Either way, I'm glad I found this product.

**Comment by serge-rider** [comment]
<kbd>Ctrl+O</kbd> is a shortcut in SQL editor ("Load SQL scripts") which actually do replaces contents of current script with specified file.
If you need to open external file you can use main menu File->Open File.
Maybe we need to change shortcut for existing action..

**Comment by btaing** [comment]
I see what you mean. After re-reading what I wrote, I realized I forgot to mention another important part. This is best illustrated with an example.

1. Suppose we have two different SQL files, one is a.sql and the other is b.sql
2. First I open a.sql
3. Next, I press Ctrl + O an open b.sql and it opens in the same window that a.sql was opened in
4. Next, I click on save, and what happens is the contents of b.sql is written into a.sql
5. This means whatever was originally in a.sql is now lost

I happen to be able to recover my file because it was on DropBox. Otherwise, I would have lost everything! Is this intentional?

**Comment by serge-rider** [comment]
I agree that <kbd>Ctrl+O</kbd> is a bit confusing shortcut (usually it opens new editor). This shortcut comes from old times when DBeaver was unable to work with external files.
I'll change the shortcut in the next version. Thanks for noticing.

**Comment by btaing** [comment]
It works much better now on the latest version! Thanks!!!
