### ISSUE TITLE
SQL Editor Scrolls Up After Statement Execution

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#208]
Each time you do a statement execution, the top-pane's SQL editor scrolls up to the top-most scroll-position.

When I'm working on a long query, I don't want to lose my place (scroll-position) after each statement execution. As is, every time I execute a statement, I have to scroll down to the "location I was previously reading". This becomes quite cumbersome in long statements I'm trying to fine-tune.

Dbeaver should retain my previous **SQL-Editor-Scroll-Position** after statement execution instead of scrolling to the top.

I do see that Dbeaver does indeed preserve my **cursor location** after each statement execution, but because it does not preserve the **SQL-Editor's-Scroll-Position**, I have to arrow-right after each statement execution to regain the approximate scroll position I had before statement execution.

**Comment by serge-rider** [comment]
Agreed, that's not convenient when working with long queries. 
I'll make reset to original screen position after query finish.

**Comment by Lonniebiz** [comment]
Excellent.

**Comment by Lonniebiz** [comment]
This is working great in 3.6.0, as long **as the sql doesn't generate an error**.

However, if there is an error in the sql, it continues to lose SQL-Editor-Scroll-Position on long queries.

Should I submit a new issue, or can this be resolved here?

**Comment by serge-rider** [comment]
That was made on purpose.
For most databases DBeaver positions on the error location (inside the query).
I don't think that ignoring error location is a good idea..

**Comment by Lonniebiz** [comment]
Oh, I see. In db2 it just highlights the entire query when there's an error.

That's a cool feature to highlight exactly where the error is, but when the
entire query is highlighted (due to error), it would be better to keep
previous scroll position (cause that's most likely where the error occurred
-- your last modification). Your choice though.

Thanks for the enhancements you've done. Dbeaver is my favorite way to talk
to any database. I just love it.

Respectfully,

Lonnie Best
281-529-5879

**Comment by Lonniebiz** [comment]
This is fixed, except in the event that the SQL statement contains an error. If there is a sql-error, cursor position is lost and you have to re-find your place to correct the error. This is tedious when modifying large and complicated sql statements (ones where errors are frequent until you get the statement just right).

**Comment by serge-rider** [comment]
Agreed. If database driver can't extract exact error position then selection will be reset to original.

**Comment by Lonniebiz** [comment]
Said perfectly.

**Comment by Lonniebiz** [comment]
This was fixed, but I'm seeing it happen again in 4.0.2.

**Comment by serge-rider** [comment]
Can't reproduce, please provide more details (what database? query sample?).

**Comment by Lonniebiz** [comment]
To reproduce, do any query that is vertically taller than the editor's height and put an erroneous letter (like "z") onto the very end of that query. After this, place your cursor to the right of that "z".

When you run the query, the entire query will be highlighted automatically during the attempted execution causing it to scroll to top.

https://youtu.be/hqJ4EO5vxTg

**Comment by serge-rider** [comment]
Yep. This was a side effect of error handling in scripts improvements.

**Comment by jankrejcik** [comment]
The scrolling (the last line of statement scrolls to the top of window) appears when execution trigger and script autosave event are to close to each other. Switching off the "Save editor on query execute" helped for me.

Should be reproducable with Save editor on query execute=ON and Auto-save after any modifications=OFF. Change anything in the query and execute.

Version 21.3.5.202202200327

**Comment by skwzrd** [comment]
When sql execution errors occur, the SQL Editor scrolls to the top of the file automatically in version  22.1.2.202207091909. The setting `Save editor on query execute` is disabled.

An example execution error:
```
Error occurred during SQL query execution

Reason:
SQL Error [22P02]: ERROR: invalid input syntax for type numeric: "02/09/2012 00:00:00"
```

**Comment by JRabotyaga** [comment]
This is an issue running in 24.3.0
