### ISSUE TITLE
PostgreSQL: Schema editor does not show the correct table space of an entity

### ISSUE THREAD

**Issue by MahatmaFatalError** [serge-rider/dbeaver#2080]
Regardless whether the entity is stored in a DB which is in the default table space or in a separate table space created by the user, the table space does not show up in the column at all.
![image](https://user-images.githubusercontent.com/776825/29705165-1da2d9a8-897d-11e7-894d-bda7590d9127.png)

**Comment by serge-rider** [comment]
I can't reproduce this (maybe it depends on server version).
Could you post a sample DDL?

**Comment by MahatmaFatalError** [comment]
```
CREATE DATABASE playground_default_tblsp
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'German_Germany.1252'
       LC_CTYPE = 'German_Germany.1252'
       CONNECTION LIMIT = -1;
```


```
CREATE TABLESPACE temp_tblsp
  OWNER postgres
  LOCATION 'C:\\postgres_test_tablespace';
```

```
 CREATE DATABASE playground_temp_tblsp
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = temp_tblsp
       LC_COLLATE = 'German_Germany.1252'
       LC_CTYPE = 'German_Germany.1252'
       CONNECTION LIMIT = -1;
```

Very basic. Created a table within the databases, but the table space column stays empty.

PostgreSQL 9.6.3. Latest JDBC driver which DBeaver has found (9.4.1212, which is already old since the current driver is [42.1.4](https://jdbc.postgresql.org/download.html))

**Comment by serge-rider** [comment]
Thanks for details.

This is because it is default database tablespace.
I'll show default tablespaces in table properties.

**Comment by MahatmaFatalError** [comment]
OK, but I'm not sure if it is clear that this bug report is regarded to the table space column, which in both cases default-table-space as well as separate-table space does not show any entries for the tables.
![inked29705165-1da2d9a8-897d-11e7-894d-bda7590d9127_li](https://user-images.githubusercontent.com/776825/29916975-b6265390-8e40-11e7-8097-ea057249ed3e.jpg)

**Comment by serge-rider** [comment]
Hm, I can't reproduce this problem with non-default tablespaces..
