### ISSUE TITLE
Error launching DBeaver 4.1.3 on Mac 10.12.6.

### ISSUE THREAD

**Issue by jaredswarren** [serge-rider/dbeaver#2083]
Installing DBeaver .dmg file on Mac 10.12.6 by launching the .dmg, then dragging DBeaver to Applications, then double clicking DBeaver in applications, I receive an error:

"An error has occurred.  See the log file..."

Log file attached.
[1503675685826.txt](https://github.com/serge-rider/dbeaver/files/1252314/1503675685826.txt)

**Comment by serge-rider** [comment]
You need to install Java 8+ JDK (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).

**Comment by jaredswarren** [comment]
D'oh. Fixed.  Thanks :)
