### ISSUE TITLE
4.1.3: JAVA_HOME not working on Linux or Zip

### ISSUE THREAD

**Issue by luyseyal** [serge-rider/dbeaver#2090]
JAVA_HOME does not appear to be working on Linux. I have tried both the DEB and the Zip archive (64-bit).

`JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ./dbeaver`

From the log file:
```
!SESSION 2017-08-27 09:01:13.056 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_95
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

(The workaround is obviously to update the java alternative)

**Comment by serge-rider** [comment]
This is how Eclipse platform works. Java must be in the PATH (i.e. setting JAVA_HOME is not enough).

**Comment by luyseyal** [comment]
Do you think you can [document that here](https://dbeaver.jkiss.org/download/) as many of us are used to JAVA_HOME working?

**Comment by serge-rider** [comment]
I will. In fact JAVA_HOME value isn't relevant at all.
The only important thing is current Java version (the one which is in PATH).
