### ISSUE TITLE
MariabDB Select Execution Error DBeaver 4.1.3 Ubuntu AMD64

### ISSUE THREAD

**Issue by cnizzardini** [serge-rider/dbeaver#2094]
It appears DBeaver is no longer automatically putting in back ticks for protected keywords in MySQL/MariaDB. So the query below it appears to try running the SOURCE command. I believe this is a regression from previous releases.

**SQL Statement:**
SELECT id, source, session_id, url, request, response, created
FROM integration_log

**Error:**
Error encountered during the SQL script execution. Reason: File 'session_id, url, request, response, created' not found

**Environment:**
Client: DBeaver 4.1.3, Ubuntu 16.04 LTS, AMD64
Server: Ubuntu 16.04.2 LTS mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for debian-linux-gnu (x86_64)

**Comment by serge-rider** [comment]
It is a bug in 4.1.3 - DBeaver always evaluates SOURCE keyword as a file inclusion command.

**Comment by serge-rider** [comment]
SOURCE will be processed only if it is in the beginning of line.

And thanks for report.

**Comment by cnizzardini** [comment]
I don't think this should be closed. Source is not "in the beginning of line" in the example I posted.

**Comment by serge-rider** [comment]
> I don't think this should be closed
I've committed the fix so SOURCE will be processed correctly in the next version

**Comment by cnizzardini** [comment]
Sorry I misread your message, my apologies.
