### ISSUE TITLE
Excessive Memory Usage and Freezing Up

### ISSUE THREAD

**Issue by apistil77** [serge-rider/dbeaver#2096]
I have been having problems with dBeaver using an excessive amount of memory when pulling 100k+ rows, causing queries to complete very slowly or even freeze up entirely.

How can I help dBeaver control it's memory usage and be able to pull large queries more efficiently.  I routinely need to pull 3M+ rows.

Thanks!

**Comment by serge-rider** [comment]
You can control maximum memory available for DBeaver by command line parameters: https://github.com/serge-rider/dbeaver/wiki/Command-Line

But do you really need to read 3M of rows in UI? 
You can export table/query results directly to a file (e.g. csv).

**Comment by apistil77** [comment]
I am exporting directly to a CSV and it is still using 2GB of memory.  I'm not as concerned with DBeaver using too much of my system's memory as I am concerned that it seems to be struggling with large queries more than it should.

**Comment by serge-rider** [comment]
Well, it shouldn't consume much memory for export.
What is your database?

**Comment by apistil77** [comment]
I'm using an ODBC connection to a Sybase database.

**Comment by serge-rider** [comment]
Looks like this link (ODBC+Sybase) doesn't support resultset streaming (i.e. all fetched rows are stored in memory).
You could try to export by segments:
![image](https://user-images.githubusercontent.com/6398845/29886242-1ed02b8e-8dc2-11e7-9301-ea5adadb9727.png)

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.

**Comment by apistil77** [comment]
I started using SAS instead of dBeaver because I could not get dBeaver to
work...

**Comment by serge-rider** [comment]
So, export by segments didn't work?
We are going to add Sybase in our test environment soon. Hopefully we'll be able to resolve such issues then.
Thanks for report.
