### ISSUE TITLE
PostgreSQL Remove Database

### ISSUE THREAD

**Issue by sugandaaa** [serge-rider/dbeaver#2109]
i have two database create by ruby (rake db:create), but in the dbeaver and right click->tools not have drop database option.
![screenshot from 2017-08-31 11-32-45](https://user-images.githubusercontent.com/15070585/29906591-30f07b2e-8e40-11e7-994d-c332bfe461b0.png)
How to i remove the database in postgres?

**Comment by serge-rider** [comment]
PG database create/drop functions will be added in the next version.
