### ISSUE TITLE
postgres error resolving dependencies.

### ISSUE THREAD

**Issue by Pascal-be** [serge-rider/dbeaver#2110]
I install dbeaver on a server without internet connection.

I copy the last postgres driver in %userprofile%\.dbeaver-drivers

but when I want to connect to my database dbeaver try to download dependeis and so I have an error.

how can I use dbeaver without internet connection ?

Pascal

**Comment by serge-rider** [comment]
You don't need to do anything on file system. 
Just open Driver Manager (in main menu Database), open PostgreSQL driver and add jar files in Libraries tab. That's it.
