### ISSUE TITLE
Primary Key Creation

### ISSUE THREAD

**Issue by AFAgarap** [serge-rider/dbeaver#2111]
There's no more 'Constraints' in the UI, no way of creating a primary key.

![screenshot from 2017-09-01 17-58-03](https://user-images.githubusercontent.com/11130276/29965164-2c82955e-8f3f-11e7-82e7-816629eb7d56.png)

I'm running the Linux version on Ubuntu 16.04 LTS.

**Comment by AFAgarap** [comment]
Based on migration from T-SQL (console), the Primary Keys are interpreted as Unique Keys in DBeaver.

**Comment by falke2** [comment]
Really. Didn't find any solution to create primary key!
Ver: 6.2.1
