### ISSUE TITLE
DDL unreadable characters (v4.1.3)

### ISSUE THREAD

**Issue by Daniate** [serge-rider/dbeaver#2115]
![5ovy4k6tfl9wz gyv m yx](https://user-images.githubusercontent.com/1210634/29991598-9b0430b4-8fbc-11e7-94e6-996a6d22fda0.png)
![2wa a 0vz t8__b iu2e](https://user-images.githubusercontent.com/1210634/29991612-ea91897e-8fbc-11e7-92e1-ab555a3566ab.png)

**Comment by serge-rider** [comment]
Please provide more details.
Looks like Chinese comments. What is wrong with this?

**Comment by Daniate** [comment]
Yes, Chinese characters. 
You can see that, in the `Properties` pannel, the **Description** of the `articletag` table is "文章标签", and in the **Columns** pannel, the `Comment` of the `name` column is "标签名称", these are readable. 
But in the **DDL** pannel, the comments are unreadable.
I think the character encoding was handled incorrectly in the **DDL** pannel.
I used MySQL Workbench export the structure of  the `articletag` table:
<img width="505" alt="2017-09-05 10 24 03" src="https://user-images.githubusercontent.com/1210634/30042551-98a34a16-9224-11e7-8a41-7a375bb72382.png">
The comments are readable.

**Comment by serge-rider** [comment]
Seems to be a bug in DBeaver. DDL reading code converted DDL text using current system charset which is not always appropriate. Modern MySQL drivers don't this at all.
Fix will be added in the next version, thanks for report.
