### ISSUE TITLE
Misplaced Stored Procedure

### ISSUE THREAD

**Issue by AFAgarap** [serge-rider/dbeaver#2116]
I have the following SQL code:

```
USE dbTravel;
GO

CREATE PROCEDURE spCountTraveller AS
	SELECT dbTravel.dbo.tblTrip.FlightNumber, COUNT (*) AS 'Number of Passengers'
	FROM dbTravel.dbo.tblTrip
	GROUP BY FlightNumber;
GO
```

Instead of `spCountTraveller` being created in `dbTravel`, it's created in `master`. My database connection is with SQL Server for Linux. Is this a bug of dbeaver?

**Comment by serge-rider** [comment]
I can't reproduce that.
I've tried to run this code both in script mode (<kbd>ALT+X</kbd>) and in single statement mode (<kbd>CTRL+ENTER</kbd>).
Are there any additional details?

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.

**Comment by AFAgarap** [comment]
You can't reproduce that since I didn't give the data to be stored in the database. Will get back on this some time.

**Comment by serge-rider** [comment]
@AFAgarap sure. Just leave a comment here and we'll reopen it.
