### ISSUE TITLE
Cant create Foreign Key

### ISSUE THREAD

**Issue by JTMMartins** [serge-rider/dbeaver#2120]
DB:MySql
OS:Ubuntu 17.04

I have two tables (table 1 and Table 2)
One has a unique Key
When I want table 2 to reference table 1, I go to Foreign keys, however the unique key dropdown is never enabled.

Is this a bug, or am I missing something ?

**Comment by JTMMartins** [comment]
I think i find the way...

**Comment by csanyipal** [comment]
Hello Jose,

2017-09-05 12:50 GMT+02:00 Jose Martins <notifications@github.com>:
>
> I think i find the way...

Please, write down the way?

-- 
Best, Pali

**Comment by serge-rider** [comment]
Unique key selector is enabled if you have more than one unique key. Otherwise you don't need to choose anything there.
