### ISSUE TITLE
Open database object: add a way to filter out some results

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#2121]
It would be neat if we could filter out some results of the "Open database object" window. For instance, I'd like to never see the "cell..." tables of the "archive" schema on this example, but only the ones of the "public" schema:

![image](https://user-images.githubusercontent.com/3851902/30064661-be207628-9252-11e7-8e4f-2a19dcb009ea.png)

I think this would require a new field "Exclude" on this window, with a way to add several filters. These filters should be automatically remembered, and could be different per connections.

What do you think?

**Comment by serge-rider** [comment]
Actually you can filter by schema. Just set selection to a schema/database you want to search in and then press <kbd>CTRL+SHIFT+D</kbd>.
After all I don't think that we need to complicate this dialog. There is metadata search dialog which can be used for sophisticated searches.

**Comment by Otiel** [comment]
Thanks I didn't know that.

I'm using this window in order to quickly browse tables, without having to expand the connection/selecting the schema, so I don't think I'll use this trick because it requires 4 more clicks and clutters my treeview when I want to keep my connections collapsed for quick access. So I still would love to see this feature added.

But anyway, I understand your point of view if you don't want to complicate this dialog.
