### ISSUE TITLE
org.postgresql.util.PSQLException: 10 Authentication is not supported.   (scram-sha-256)

### ISSUE THREAD

**Issue by JeeIPI** [serge-rider/dbeaver#2122]
DBeaver: 4.1.13

Description:
--------------

Trying to connect to one PostgreSQL 10 version database set with scram-sha-256 authentication using DBeaver,  but getting  the following error:

`org.postgresql.util.PSQLException: 10 Authentication  is not supported. Check you have setup pg_hba..conf  ...
`

The same connection works fine if database authentication is set to md5 (or others authentication types).

So, DBeaver seems to not work with new PostgreSQL 10 scram-sha-256 authentification.  

Is there any plan to allow DBeaver to work with scram-sha-256 PostgreSQL 10 authentication mode ?If yes any idea when it will be available ?

Many thanks for yoru help.
Best Regards,
Jean-Pierre

**Comment by kyleflan** [comment]
DBeaver uses the Postgres JDBC driver, which, from what I can tell, does not have a SCRAM-SHA-256 authentication method available yet (see [this link](http://paquier.xyz/postgresql-2/scram-drivers/)). Although, there appears to be a [patch](https://github.com/pgjdbc/pgjdbc/pull/842) in the works, but it's not ready yet.

**Comment by JeeIPI** [comment]
Thanks a lot your answer. 
We'll wait for the JDBC driver correction.
I'm closing this issue and thanks again for your help.

Best Regards,

**Comment by ulfedf** [comment]
Any updates on this closed case, can se that other jdbc driven tools supports scram-sha-256 but i  can't get dbeaver to work with password encryption scram-sha-256.
It's works fine with MD5.

Im using dbeaver 5.2.1

Error message:
The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.

**Comment by mirismaili** [comment]
According to https://wiki.postgresql.org/wiki/List_of_drivers JDCB should support SCRAM from version 42.2.0. 
I use JDCB v42.2.5 (on DataGrip and DBeaver), but can't connect to the server when change authentication method from `md5` to `scram-sha-256`. It says: 
FATAL: password authentication failed for user "postgres"

Same issue on pgAdmin 4 v3.2.

**Comment by ygoe** [comment]
So we're at Postgres 13, 2020 is almost over and this still doesn't work. Maybe JDBC is not the right technology to use here if it's unmaintained for years?

Anyway, I've followed the error message and changed Postgres' hb_pga.conf to "md5", restarted the service. Still can't log in. It works on another machine with Postgres 12 but not this fresh installation of the latest bits.

**Comment by jeffjanes** [comment]
The indicated patch was accepted years ago.  Use DBeaver's Driver Manager to use/get a newer version of JDBC.

**Comment by AhmedMASalam** [comment]
for non-prd: pg_hba.config
local   all             all                                     trust

**Comment by karser** [comment]
This worked for me
- go to Database / Driver Manager
- Find Postgres and click edit
- Click the Libraries tab and click Download/Update
