### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zhangyc145** [serge-rider/dbeaver#2123]
When i import the code into eclipse,there are some compile error like 'cannot refer to the non-final local variable defined in an enclosing scope' in class 'org.jkiss.dbeaver.ext.exasol.manager.ExasolPrimaryKeyManager'(68 line and so on).This is because the variable called in anonymous inner class should be final,so i want ask why the developer lost the 'final'?Is there some other reason?

**Comment by serge-rider** [comment]
You need to compile with Java 8.
In Java 8 you don't have to make all variables finel to use them in inner classes.

https://stackoverflow.com/questions/28408109/java-stopped-erroring-on-non-final-variables-in-inner-classes-java-8
