### ISSUE TITLE
DBeaver 4.1.0 hangs on auto-complete for large tables

### ISSUE THREAD

**Issue by WimHe** [serge-rider/dbeaver#2124]
See also "dbeaver hangs on occasion when trying to hint table name after typing '.'  #1699 " 
When doing auto-complete on a fieldname: schema.table. <auto-complete> DBeaver will run a query on the database select count(*) from schema.table.
If the table is large (in my case 64Terra records on an IBM Netezza, it will crash the production environment. This is a very high risk for production databases that have very large tables.
Suggest to have the "show row count" feature default turned off or retrieve row count information from the administrative tables of the database. The latter may require having an SQL template on how to do that for each type of database.

**Comment by serge-rider** [comment]
You already can disable this:
![image](https://user-images.githubusercontent.com/6398845/30115723-3df51580-9324-11e7-9261-66192560cf55.png)

By the way this option is disabled by default.

**Comment by tati-kru** [comment]
It looks like this question was solved. It will be closed. If you think that it is actual just let us know.
