### ISSUE TITLE
Teradata - Connection: Port Attribute will be ignored

### ISSUE THREAD

**Issue by chhaehle** [serge-rider/dbeaver#213]
I have 2 Teradata Servers running on the same host:
1.) One listening on (default teradata port) 1025
2.) One listening on port 22209

I am not able to create a connection to the second Teradata server (port 22209). It always defaults to the first one (port 1025).

According to the [Teradata-Documentation](https://developer.teradata.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html) i am using the **DBS_PORT** parameter in order to specify the port.

Therefore i changed my JDBC-URL template:

![driver-settings jdbc-template](https://cloud.githubusercontent.com/assets/17403548/13214596/ee14f8f2-d950-11e5-9dc1-f708c7a63572.png)

The behavior of the the settings form works:
![connection-settings](https://cloud.githubusercontent.com/assets/17403548/13214682/70ea890e-d951-11e5-82b8-f0d58b039600.png)

But when i connect, i always connect to the first Teradata-Server listening on port 1025.

I'd like to stress that in our own application (that we are developing), this problem doesn't exist.
We are also using JDBC-Connection with the mentioned port attribute. So it should work in general.

Here is my environment information:
- Windows 10 64bit
- DBeaver 3.5.9
- Teradata-JDBC-Driver: i tested it with version 13, 14 and 15 but no one worked.

**Comment by serge-rider** [comment]
Could you try URL template jdbc:teradata://{host}:{port}/{database} ?
I'll fix it in default config if it'll work.

**Comment by chhaehle** [comment]
No it doesn't work. I guess the Teradata-Driver expects a **Type 4** URL and he can not deal with the port suffix in the host name.

I got the following exception when testing your suggested URL-Template:
![type_3_url_exception](https://cloud.githubusercontent.com/assets/17403548/13215957/44377f7c-d959-11e5-83f9-59049320edec.png)

Here is also my setting:
![type_3_connection_setting](https://cloud.githubusercontent.com/assets/17403548/13216000/7ce0795a-d959-11e5-995a-07feaa5be6ed.png)

Seems that JDBC Type 4 is the currently supported URL style:

> The Type 3 Teradata JDBC Driver is no longer included on the Installation CDs and tapes for Teradata Tools and Utilities. Related software, such as the JDBC Gateway and its administration GUI, is also no longer included. To run applications previously written for the Type 3 driver it is necessary to move applications to  the Type 4 Teradata JDBC Driver. To do this, change the application's connection Universal Resource Locator (URL) as follows:
    JDBC Type 3:   jdbc:teradata://gwhost:port/DatabaseServerName
    JDBC Type 4:   jdbc:teradata://DatabaseServerName

**Comment by serge-rider** [comment]
Ok. Your URL is also not correct for Type4 driver. You can't specify database name directly, there is a special parameter DATABASE for it.
Try this one:
jdbc:teradata://{host}/DATABASE={database},DBS_PORT={port}

**Comment by chhaehle** [comment]
It works. 

It's a little bit strange, that this works in our own application though.

But anyway, many thanks.

Will this fix (changed URL-template) be included in the "default config" (i guess you meant the default driver settings provided by DBeaver)?

**Comment by serge-rider** [comment]
Yes, I'll include this template into default config.
Thanks for report.

**Comment by zhanmi7** [comment]
Below is my Driver settings:
![image](https://user-images.githubusercontent.com/53954377/62808968-ad48d300-bac7-11e9-9090-347c538892b4.png)

However I still get error message:
![image](https://user-images.githubusercontent.com/53954377/62809022-cfdaec00-bac7-11e9-808f-5d9a9d7ef83d.png)

Can anyone help? Here is my environment information:
Windows 10 64bit
DBeaver 5.1.1
Teradata-JDBC-Driver
