### ISSUE TITLE
SQL formatting configuration

### ISSUE THREAD

**Issue by tati-kru** [serge-rider/dbeaver#2130]
We need to add SQL formatting configuration: tabs, commas, keywords, etc.

**Comment by quiescer** [comment]
Could this include a way of telling Dbeaver to NOT insert tabs for indentation? I have configured it with 'Insert spaces for tabs', but auto-indentation still inserts tabs on new lines.

**Comment by serge-rider** [comment]
@quiescer Yes, and this too.

**Comment by pdanie** [comment]
One Product to look at when it comes to SQL formating can be _RedGate_ _SQLPrompt_ that has a really nice formater.

[Red Gate Software Ltd](https://www.red-gate.com/products/sql-development/sql-prompt/index)
[Youtube](https://youtu.be/LQznXAKyFoI)

**Comment by serge-rider** [comment]
Compact SQL formatter was added in 4.3. 
Also for both default and compact formatters the only configuration is:
- Keywords case
- Indent size
- Tabs or spaces

All these parameters are consistent with SQL auto-formatting and can be configured with the same preference parameters.
