### ISSUE TITLE
SQLite DDL Generation without index

### ISSUE THREAD

**Issue by ggoelles** [serge-rider/dbeaver#2134]
When generating a DDL script for a table the index isn't included. Using version 4.2.0 on Linux

**Comment by serge-rider** [comment]
Do you see indexes in "Indexes" tab?
Are there any errors/warnings in Error Log view? (main menu Window->Show view)

**Comment by ggoelles** [comment]
Yes, I see the indexes. With "right-mouse button on table -> Generate SQL -> DDL" I get a window with the correct DDL without PRIMARY INDEX in the create-statement nor as an additional constraint. No errors or warnings in the log

**Comment by serge-rider** [comment]
Indexes definition will be included in table DDL in the next version.
