### ISSUE TITLE
500310 Error Requires Reconnecting to Database

### ISSUE THREAD

**Issue by ltlmtgswb** [serge-rider/dbeaver#2135]
Hi, I have DBeaver hooked up to Redshift using the standard Redshift drivers. I'm using a Macbook Pro with the latest OSX installed and DBeaver versions 4.1.3. When I execute an incorrect query, I have to disconnect from Redshift and reconnect, otherwise it gives this error:

SQL Error [500310] [25P02]: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
  [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
    com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;

I saw a similar issue solved via the "auto commit" button, but having it selected or unselected didn't change the behavior. So right now, if I'm testing a query it's very tedious since I have to disconnect and reconnect over and over. Is there another setting that can fix this?

**Comment by serge-rider** [comment]
Does making manual rollback  (or commit) help? (you have to be in transactional mode).
Also you can try to execute 
```sql
SET autocommit ON
```
before running queries.

**Comment by ltlmtgswb** [comment]
@serge-rider I enabled "rollback on error" (I didn't know what this meant) and now it's working. Thanks!

**Comment by serge-rider** [comment]
Good, thanks for information
