### ISSUE TITLE
plz make value panel hex view vary with panel width, which may not be multiples of 8

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#2138]
It should work like HxD or Frhed. It should not be constrained to multiples of 8. It should change interactively with the panel width w/o going thru another modal dialog that accepts a number.

![20170913t113326_hp-radw04](https://user-images.githubusercontent.com/25423046/30358551-c15d1f64-9877-11e7-83c1-7efce05518d2.png)

**Comment by serge-rider** [comment]
Good point
