### ISSUE TITLE
Content assist proposes names of indexes etc instead of tables on PostgreSQL

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#214]
Content assist works in a strange way when trying to complete a regular select * from on Postgresql.

When I write a query and hit ctrl+space before typing the name of the table - it works correctly:
![image](https://cloud.githubusercontent.com/assets/6532949/13215880/d7d33b00-d958-11e5-9455-a5c4c719d767.png)

but when I begin to type the name of the table and hit ctrl+space I get a list of indexes, not even from my active schema:
![image](https://cloud.githubusercontent.com/assets/6532949/13215866/c1416d4e-d958-11e5-965e-138f02175b9f.png)

I would expect to get a list of tables that start with "adas" or just get the whole table name filled out automatically if there is only one such table.
I'm working with PostgreSQL 9.0 and DBeaver 3.5.9 but I've seen this behaviour in earlier versions too.

**Comment by serge-rider** [comment]
Could you try DBeaver 3.6.0. We did a major update of PostgreSQL driver there.

**Comment by norbitheeviljester** [comment]
on it.

**Comment by norbitheeviljester** [comment]
I see that you've added a feature that makes this silent assumption that a postgres schema is created per user like in oracle. 
I am unable to make a schema of my choice active and now the content assist gives me all tables that are present in the existing schemas on the database server.
Could you please reconsider allowing a user to activate a single schema? I know that there is a filter mechanism for schemas but In my case I often move from schema to schema - changing filters each time would be extremely painful.

As for the content assist. When I give no name for the table the content assist gives me a list of all schemas on the server so that I choose one first:
![image](https://cloud.githubusercontent.com/assets/6532949/13216853/cb153a2a-d95e-11e5-9aef-93de314813f6.png)

and if I start typing the name of the table it will list all tables with that name in all schemas:
![image](https://cloud.githubusercontent.com/assets/6532949/13216869/e66250c4-d95e-11e5-9a60-56f462cb23bf.png)

Notice that although I've filtered out all but one schema - the content assist doesn't pick up on that.
So in a way of speaking it's a bit worse than it used to be :-(

**Comment by carlosjrcabello** [comment]
I'm with you @norbitheeviljester, once you have a lot of databases, content assist will bring all tables sorted by schema name. I think that would be nice with when I have one schema selected, content assist show me only content of selected one.

**Comment by serge-rider** [comment]
Unfortunately PostgreSQL doesn't has such thing as "default schema". But it has "search path" session variable. I'll try to use it to narrow content assistant search.
Thanks for report.

**Comment by norbitheeviljester** [comment]
Hi @serge-rider , it seems on dbeaver 3.6.7 this has been reverted. When using content assist I see tables from all schemas, not just the active one.
![image](https://cloud.githubusercontent.com/assets/6532949/15246343/7c05e004-190c-11e6-8d6d-9b8062ad80b8.png)

Is this a bug or have you decided to drop this functionality?

**Comment by norbitheeviljester** [comment]
also content assist shows the list of schemas instead of tables:
![image](https://cloud.githubusercontent.com/assets/6532949/15246434/15f41096-190d-11e6-88a6-8bb2a7ce2844.png)

This is on Postgresql 9.5

**Comment by serge-rider** [comment]
Yep. Side effect of another feature request.

**Comment by serge-rider** [comment]
It'll be fixed in 3.6.8, thanks for report.
Please next time create a separate issue. Its hard to track different problems in a single issue.

**Comment by norbitheeviljester** [comment]
I'll make sure to do that, thanks.
