### ISSUE TITLE
h2-1.4.196 'Timestamp with time zone' is not properly displayed 

### ISSUE THREAD

**Issue by alusbars** [serge-rider/dbeaver#2140]
Tested on h2-1.4.196.

Execute SQL script:

CREATE TABLE test(x TIMESTAMP WITH TIME ZONE);
INSERT INTO test(x) values(CURRENT_TIMESTAMP());
SELECT * FROM test;

Dbeaver displays 'x' column as NULL. H2 console displays as it should.

**Comment by serge-rider** [comment]
This is H2 driver issue: https://github.com/h2database/h2database/issues/413

I'll add a workaround for this
