### ISSUE TITLE
source code frame and re-development

### ISSUE THREAD

**Issue by chenyu-emma** [serge-rider/dbeaver#2142]
Hi,
  I downloaded the source code of DBeaver and configured the maven environment. Then I imported the dbeaver project into eclipse, and packaged the project into the .exe file.
    At present, I want to use DBeaver to connect my own database, so I need to modify the source code of dbeaver. There is less knowledge in this area, and the code involves a lot of plugins, it's hard to re-develop DBeaver.
    Is there exist some directive document for dbeaver source code? And I wonder how to debug DBeaver during the development process?
    Thanks.

**Comment by serge-rider** [comment]
Check this topic for Eclipse dev config: https://github.com/serge-rider/dbeaver/wiki/Develop-in-Eclipse

Generally you will need to create an extension similar to (for instance) SQLite (it is based on Generic driver) or MySQL (it is a fully functional standalone extension).

If you have any particular questions - write me on serge@jkiss.org.
