### ISSUE TITLE
Missing unique constraint on table

### ISSUE THREAD

**Issue by garbles9100** [serge-rider/dbeaver#2147]
I'm using DBeaver 4.2.0 and postgres 9.6.2.

When I view the Unique Keys folder for a table that has a unique constraint on multiple columns, the unique constraint is not listed. All I see is my primary key. When I view the same table in pgAdmin I am able to see both constraints.

**Comment by garbles9100** [comment]
I just verified that I am also not seeing the unique constraint on a single column in another one of my tables. Still just the primary key is shown.

**Comment by serge-rider** [comment]
Please make sure you are using correct PostgreSQL driver (not Generic, see  #2069).

**Comment by garbles9100** [comment]
Switching to the non-Generic postgresql driver solved this issue. Thanks!
