### ISSUE TITLE
Datasource combobox width on two monitors.

### ISSUE THREAD

**Issue by carlosjrcabello** [serge-rider/dbeaver#215]
When I'm using two monitors, sometimes DBeaver opens with his combos of active datasource and schema with wrong width, like in image bellow:

![screen167](https://cloud.githubusercontent.com/assets/637767/13217326/7783c804-d940-11e5-8ff1-d00e9d9cdc65.png)

Usually I restart DBeaver and this ~problem~ is solved, it's not a critical bug, but I don't have idea how complex to solve it is.

Once OK, switching between displays, this bug doesn't come back, sometimes after system's hibernate or suspend mode, this problem come back.

**Comment by serge-rider** [comment]
Selector combos were fixed.
Please check 3.6.1 version.

**Comment by carlosjrcabello** [comment]
Guy, you're fucking awesome!

Thanks a bunch brother.

**Comment by serge-rider** [comment]
:+1:
