### ISSUE TITLE
Is there a way to hook up to do a transformation in a column?

### ISSUE THREAD

**Issue by danydev** [serge-rider/dbeaver#2150]
I'm working on a legacy database where the value of a column is basically a binary produced with something like `gzip(serialize(array))`, would be awesome to see the actual value directly on DBeaver.
Is there something I can use to hook up with an external script to do a transformation in one of the column with a click? (would be ok either in a specific column of a row, or in all the columns of all the selected rows)

**Comment by serge-rider** [comment]
DBeaver supports different column value transformations (see context menu on a value: View/Format->View as->...). But there is no transformer for unzipping.

If this is some standard feature then you can make feature request with details (what database this is, what `serialize` does, etc).
If this is something specific to your company then you can write such transformer by yourself. Or try to use EE version support.

**Comment by danydev** [comment]
yes, it's specific for my company. Can you point me to the API you are referring to?

**Comment by serge-rider** [comment]
You can take a look on URLAttributeTransformer or EpochTimeAttributeTransformer. They convert string/numeric values into something more fancy.
You can create a separate DBeaver extension plugin which will provide configuration for you custom attribute transformer.

**Comment by danydev** [comment]
closing, thanks I think I have enough information!

**Comment by DavidJRobertson** [comment]
I would also find it very useful to be able to un-gzip a particular column from within dbeaver
