### ISSUE TITLE
"Save filter settings for current object" does not work unless at least 1 of either order or criteria is defined

### ISSUE THREAD

**Issue by dakusan** [serge-rider/dbeaver#2157]
# How to reproduce:
1) In the "Result Set Order/Filter Settings" dialog for a table, rearrange or toggle [hide] columns, but do not change anything in "Order" or "criteria".
2) Save via "Save filter settings for current object"
3) Close the table
4) Reopen the table

# Result
The save did not take and everything is back to the original default state.

# Further information
This table dialog seems very buggy. I can't really reproduce the saving problems down to one example because so many different problems are occurring. Once there are already non-default settings saved for a tables filters, sometimes updating row ordering or row toggling works, and some times it doesn't.  If you remove all orders and criteria, and save again, order+toggle status is completely lost

Also, after loading a saved filter, when trying to move some fields in the dialog to the top of the order, they can only get to the second or third top slot.

**Comment by serge-rider** [comment]
Original issue was fixed, thanks for report.
I think the rest will be fixed in #2158

**Comment by serge-rider** [comment]
BTW you can check the fix in EA version (https://dbeaver.jkiss.org/files/ea/)

**Comment by dakusan** [comment]
Thanks!

I confirmed it's good in the latest version. Do you still need me to check the EA version? (Not sure if that is something different).
