### ISSUE TITLE
Double clicking a table name on v4.2.1 no longer opens the table in a tab

### ISSUE THREAD

**Issue by nicklaw5** [serge-rider/dbeaver#2160]
OS: Ubuntu 16.0.4.2 (Xenial)
DBeaver Version: 4.2.1
Driver: MariaDB

I have just installed v4.2.1 but can no longer double click on a table name to open it in a new tab. The table tree extends as seen in the below screenshot, but I can't get it to open in a new tab in the right-hand panel.

![image](https://user-images.githubusercontent.com/7908386/30527974-b7a92c4e-9c71-11e7-96a5-34a36be93719.png)

I'm not sure if other drivers/OS's are affected as I only have MariaDB setup on this machine.

Reverting back to v4.2.0 seems to resolve the issue for now.

**Comment by Shamil-R** [comment]
Same problem with Microsoft JDBC Driver for SQL Server.
I think this problem not related with driver

**Comment by serge-rider** [comment]
It is configurable:
![image](https://user-images.githubusercontent.com/6398845/30531972-5d666bdc-9c5a-11e7-92c4-4f0ff6e1630a.png)

**Comment by creage** [comment]
Why change default commonly used behavior without noting that change in release notes?

**Comment by serge-rider** [comment]
It was in release notes (`Database navigator: double-click behavior is now configurable (expand by default)`).

Although maybe it makes sense to return old behavior as default. If there will be more votes I'll do this in 4.2.2.

**Comment by Shamil-R** [comment]
Vote for old default behavior

**Comment by serge-rider** [comment]
Ok, I've changed default config to properties editor.

**Comment by sirber** [comment]
Thank you!

**Comment by syedhassanshah** [comment]
Thanks

**Comment by ChM40** [comment]
Vote for old default behavior

**Comment by rml1997** [comment]
Is double click on connection now Open SQL Editor by default? I take it that's what it did before?

**Comment by serge-rider** [comment]
No, it wasn't the default. But it was possible to change this behavior. Now extra config options was added (for double click on other nodes).

**Comment by gentildpinto** [comment]
> It is configurable: ![image](https://user-images.githubusercontent.com/6398845/30531972-5d666bdc-9c5a-11e7-92c4-4f0ff6e1630a.png)

thanks @serge-rider
