### ISSUE TITLE
Bug, Lock tab doesn't show anything.

### ISSUE THREAD

**Issue by yoletx** [serge-rider/dbeaver#2162]
Dbeaver 4.2.0

I can't see locks on theses 2 databases  : 

Oracle Database 11g Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

;

Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production	0
PL/SQL Release 12.1.0.2.0 - Production	0
"CORE	12.1.0.2.0	Production"	0
TNS for Linux: Version 12.1.0.2.0 - Production	0
NLSRTL Version 12.1.0.2.0 - Production	0

I don't see anything in error logs tabs, neither in dbeaver-debug.log / .log

![image](https://user-images.githubusercontent.com/32055492/30532588-5a2606a8-9c55-11e7-804e-df1f3d3e76cb.png)

**Comment by serge-rider** [comment]
You won't see anything there is there are no transaction locks.
Are you sure you have locked/pending transactions on server?

**Comment by yoletx** [comment]
You are right, i tested with only one uncommited transaction... and that's not considered as a lock, which is normal in fact !
Sorry for the report.
