### ISSUE TITLE
[MySQL db - Client running on MacOS] error when submitting multiple inserts 

### ISSUE THREAD

**Issue by giulianoformatodc** [serge-rider/dbeaver#2165]

**Comment by giulianoformatodc** [comment]
Hi,

I am using the client on a mac os Sierra (10.12.6), dbeaver is updated at the last version (4.2.1) and I am writing to a MySQL instance on AWS RDS (Aurora).
MySql driver version is 5.1.44 and when I try to run the following: 

``` sql
create table dc_id_dwh.test 
(
	NAME VARCHAR(10),
	AGE INT,
	DDATE DATE
);

INSERT INTO dc_id_dwh.test values ('John', 10, now()); 
INSERT INTO dc_id_dwh.test values ('John', 10, now());
INSERT INTO dc_id_dwh.test values ('John', 10, now());
INSERT INTO dc_id_dwh.test values ('John', 10, now());

```  
I get the following error:

![image](https://user-images.githubusercontent.com/30623481/30535153-8f6acbc6-9c61-11e7-849a-2057ab9d03d2.png)

It happens when executing more than one insert at the same time, do you have any suggestion on this?

Many thanks !

**Comment by serge-rider** [comment]
When you execute multiple queries use script mode (<kbd>ALT+X</kbd>).

**Comment by giulianoformatodc** [comment]
Thanks for your reply!
