### ISSUE TITLE
Incompatibility with "minimize to tray" tools

### ISSUE THREAD

**Issue by Karsonito** [serge-rider/dbeaver#2167]
GUI breaks after changing connection from dropdown list
![dbeaver - general - _dbeaver sample database sqlite _ script 2017-09-05 21 21 22](https://user-images.githubusercontent.com/2379481/30076033-53bf56ae-9280-11e7-925f-4b4ba5d7d28a.jpg)
This problem appeared in 4.1 version - there are no problems with 4.0.5. Version 4.21 also has this issiue.
I tried some tools (rbtray, dm2, 4t Tray Minimizer) - all of them breaks GUI
Can you fix it? Minimize to tray is very usefull for temporary cleaning of taskbar

**Comment by serge-rider** [comment]
What is your OS/window manager?

**Comment by Karsonito** [comment]
Win7
The problem disappears when I close rbtray

**Comment by yoletx** [comment]
Context : Windows 10, dbeaver 4.2.0

Same here, but i don't have "minimize to tray" tool.
To reproduce, i launch dbeaver, open a connection and change the connection with the dropdown list.
And it goes from this : 

![image](https://user-images.githubusercontent.com/32055492/30581812-c5a3597c-9d21-11e7-9d1c-52c37c089280.png)

to this : 

![image](https://user-images.githubusercontent.com/32055492/30581546-dbd3318c-9d20-11e7-93d9-0c3566a32688.png)

And sometimes the main menu turn to a bugged drop down list : 
![image](https://user-images.githubusercontent.com/32055492/30581871-fb255be0-9d21-11e7-98c4-a2e9fa840e2a.png)

**Comment by Karsonito** [comment]
It seems the problem is gone in 4.2.3 )
Thank you!

**Comment by serge-rider** [comment]
Thanks for letting know. 
And there will be yet another fix of schema selector in 4.2.4 (empty list when there is no active schema).
