### ISSUE TITLE
Autocomplete stopped working for double quoted table names

### ISSUE THREAD

**Issue by thebogusman** [serge-rider/dbeaver#2169]
SELECT * FROM ab.table_name
WHERE [autocomplete works here]

SELECT * FROM ab."table_name"
WHERE [no autocomplete here]

This bug was introduced in version 4.1.3. In 4.1.2 everything was ok.

I'm having this problem with my redshift database, but since it uses the same syntax as PostgreSQL, I suspect postgres databases are also affected.

**Comment by serge-rider** [comment]
Thanks for report
