### ISSUE TITLE
[3.6.0] Table refresh - Cassandra

### ISSUE THREAD

**Issue by Stas911** [serge-rider/dbeaver#217]
Not sure if it's issue with table refresh (v 3.6 EE on Ubuntu 14.04 LTS):
1. Connect to Cassandra 3.2
2. Open table with data - can see the data
3. Execute "truncate table" SQL
4. Press "Refresh result set" icon on table tab - still can see the data while table is empty
5. Close tab with table
6. Open tab with table again - no data

**Comment by serge-rider** [comment]
Can't reproduce that.
Could you check Query Manager view - when you press on refresh icon - whether refresh actually happens?

**Comment by Stas911** [comment]
Can't reproduce now. Please close.
