### ISSUE TITLE
Postgres: Simple function doesn't compile anymore (V4.2.1)

### ISSUE THREAD

**Issue by hackenspp** [serge-rider/dbeaver#2171]
I just installed Windows client version 4.2.1 and Postgres 9.6 and dbeaver fails to compile some of my existing functions.
I try with this very simple function:
```sql
CREATE OR REPLACE FUNCTION test()
	RETURNS void AS
$BODY$
DECLARE
BEGIN
	IF true THEN
		RETURN;
	END IF;
END;
$BODY$
	LANGUAGE plpgsql VOLATILE;
```

and it gives the error when compiling : Internal jdbc driver error java.lang.ArrayIndexOutOfBoundsException:

**Comment by serge-rider** [comment]
It is a bug in 4.2.1. Will be fixed in the next version, thanks for report.
Workaround: select your functions text and execute as a single statement (<kbd>CTRL+Enter</kbd>).
