### ISSUE TITLE
Doesn't Start on Mac

### ISSUE THREAD

**Issue by benyanke** [serge-rider/dbeaver#2172]
When starting on my Sierra MacBook pro, I receive the following issue on start. The main DBeaver doesn't even show.

![image](https://user-images.githubusercontent.com/4274911/30548828-cfc8494a-9c58-11e7-9d13-2163a1bff2dd.png)

[1505746925723.log.txt](https://github.com/serge-rider/dbeaver/files/1311123/1505746925723.log.txt)

**Comment by elephantum** [comment]
Same for me

**Comment by serge-rider** [comment]
You need to setup Java 1.8 (from Oracle web site: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html )

**Comment by benyanke** [comment]
Feature request: a more intuitive error message

**Comment by serge-rider** [comment]
Unfortunately I can't make this message more user-friendly (it is controlled by Eclipse platform launcher).
However we have plans to include JRE in MacOS installer (just like in Windows installer) so separate Java installation won't be needed.
