### ISSUE TITLE
SQL Format Breaks Table Names in Query [MSSQL]

### ISSUE THREAD

**Issue by benyanke** [serge-rider/dbeaver#2174]
In some cases, table column names with spaces and dashes in them get broken by the query reformatter.

before:
``` SQL
SELECT
	[table name with spaces],
	[table name with spaces -and dashes],
	[another dash- example],
	[final-dash-example],
FROM
	db.tablename;
```

after:
```SQL
SELECT
	[table name with spaces],
	[table name with spaces -
	and dashes],
	[another dash - example],
	[final - dash - example],
FROM
	db.tablename;
```

Of course, I don't have a table named `final - dash - example`, the table is named `final-dash-example`, so the query breaks.

**Comment by serge-rider** [comment]
Thanks for report.

**Comment by benyanke** [comment]
Dang, that was fast.

Thanks for the fix.
