### ISSUE TITLE
No option to dump DB without data

### ISSUE THREAD

**Issue by bsienn** [serge-rider/dbeaver#2176]
Is there an option to export structure only without data?
Also the backup options doesn't export stored procedures and there is no option.

**Comment by sirber** [comment]
try the -d switch in "extra command args". dBeaver uses mysqldump.

**Comment by bsienn** [comment]
@sirber Can you please tell where to put that option? I don't see where is "extra command args" setting in dbeaver client

**Comment by sirber** [comment]
Right-click on a database, tools, dump database.
Select the database and dables, next.
And there you are! :)

**Comment by bsienn** [comment]
I think you misunderstood.

I CAN dump the database, BUT it dumps the structure and data (insert queries) into the dump.
I just want to create dump with structure. No insert statements.

**Comment by sirber** [comment]
You asked how to dump the structure only, I answer.
Then you asked where was the "extra command args", I told you how to get there.

Combine the two answer and you are good to go.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/30616750-f9aac8b6-9d9b-11e7-9521-412cbf8f7071.png)

**Comment by serge-rider** [comment]
I suppose extra checkbox "Do not dump data" in this wizard would be helpful..

**Comment by sirber** [comment]
"Structure only" is nice too!

**Comment by bsienn** [comment]
@serge-rider and @sirber  Thanks to both of you. I didn't saw the command box, maybe my eysight got weaker. Thanks to you Both. maybe I should have made this a feature request :) Check box would really help.

And about the stored procedure etc. I guess I would have to pass —routines in command. Ana extra checkbox for this would also be useful IMO because I use this many time with phpMyAdmin.

**Comment by Andrey-Pavlov** [comment]
@serge-rider  I see you added the "no data" option for MySQL but is it available for PostgreSQL? I don't see any checkboxes or options.

**Comment by rapomon** [comment]
> @serge-rider I see you added the "no data" option for MySQL but is it available for PostgreSQL? I don't see any checkboxes or options.

Enter "-s" in extra command args for export schema only in postgres

**Comment by ahsandev2019** [comment]
any update of thie request feature?

**Comment by anton-petrov** [comment]
Please, add the checkbox "No data" for PostgreSQL .

**Comment by Amaury-DE-LA-VAISSIERE** [comment]
Hello
I just discovered simple way to do this : 
1) In the databases navigator window, right click on the schema you want to export
2) Choose the menu "Generate SQL" then "Generate DDL"
3) A window will pop up. On the bottom right tick the check box "Show full DDL"
4) The code to generate the structure only (without data) will appear. You then just need to copy it in a text file
![image](https://user-images.githubusercontent.com/122606489/212299944-c6aea1ac-873c-4b9d-a998-e4e9254b212b.png)

**Comment by jerry-ey** [comment]
try `-s` (schema only) for postgres
https://www.postgresql.org/message-id/20050506105546.U40081@wolf.pjkh.com
