### ISSUE TITLE
Displaying timestamp columns in cassandra is broken

### ISSUE THREAD

**Issue by makosblade** [serge-rider/dbeaver#218]
<img width="1084" alt="screen shot 2016-02-22 at 3 40 57 pm" src="https://cloud.githubusercontent.com/assets/336506/13236676/c6b2d660-d97a-11e5-920e-6fb2c6031d5f.png">

Cassandra 3.0 driver ships with support for converting timestamp columns to/from java.util.Date but unfortunately they don't support their concrete implementation of Date, com.datastax.driver.core.LocalDate. 

I imagine they'll fix this eventually but for now, DBeaver is broken when viewing any tables that use the timestamp column type.

**Comment by makosblade** [comment]
Repro:
1) create a new table
 `create TABLE footest ( timestam timestamp PRIMARY KEY , value text );`
2) insert some data
 `INSERT INTO cass_tests.footest (timestam, value) VALUES (1, 'foo');`
3) view data with DBeaverEE
4) failz :(

**Comment by serge-rider** [comment]
Thanks for report.
This issue will be fixed in the next version.

**Comment by sebdotv** [comment]
some issue here - any workaround available?

adding the error message as text to make it searchable:
`com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [timestamp <-> com.datastax.driver.core.LocalDate]`
