### ISSUE TITLE
Tabs seem to use the same connection to the database versus a new connection

### ISSUE THREAD

**Issue by walterjwhite** [serge-rider/dbeaver#2180]
When I have a long-running query and open a tab to run another query (which I know is short-running), it won't return until the long-running query returns.  Shouldn't it use a connection pool, 1 connection per tab?

**Comment by serge-rider** [comment]
It is configurable:
![image](https://user-images.githubusercontent.com/6398845/30667288-b472e200-9e5f-11e7-9db1-0f3c31bae1e4.png)

**Comment by vladchuk** [comment]
This setting seem to have no effect, at least on the datasource/schema selection, which show up the same of all tabs. Is something else missing?

**Comment by serge-rider** [comment]
The only guess I have is transactions. Maybe your first query locks a table and second just waits for first to finish.
This behavior can't be solved from DBeaver.

**Comment by vladchuk** [comment]
I'm not sure I understood your comment. Perhaps I didn't explain the problem clearly: all editor tabs seem to have the connection defined by the active datasource/active schema selector in the tools panel, "Open separate connection for each editor" notwithstanding. I'm comparing this to DbVisualizer, where each editor tab has its own connection/database/schema selectors, and those selections are honored by each tab independently.

Are you saying this functionality is not supported by DBeaver? If it is, then I am missing something - would you care to explain how to achieve it? Thanks!

**Comment by p91paul** [comment]
You can select a different datasource for each tab from the toolbar menu. Changing datasource from there affects only the current tab, not others.

**Comment by vladchuk** [comment]
Unfortunately, this is not my experience. Steps to reproduce (v. 5.0.0, "Open separate connection for each editor" flag set):
1. Open SQL editor, select DS/schema, run a simple test query
2. Open second editor, select a different DS/scheama, run a query
3. Switch back ta editor #1, note the DS/schema reflects #2 selection. Run the query from point 1, get an error: "table or view does not exist".

It seems the the last selection wins and takes effect in all editors. Could this be a bug?

**Comment by serge-rider** [comment]
@vladchuk This definitely sounds like a bug. But I can't reproduce it. I have tens of scripts for different datasources and changing datasource for a single script doesn't affect any other ones.

Could you make a short video (gif) of this issue? Maybe I'm missing some point.

**Comment by gtavoalva** [comment]
Hi. Do you have some update for this issue? I try version 5.2.4 and have the same behaviour. Regards.

**Comment by jimwheeler** [comment]
I have this same issue and its pretty serious.  The expectation is that if I open a tab and begin working on a database / schema and then I open a different tab and work on a different schema then when I switch back to the original tab it will still be pointing to the original schema.  I see the same behavior as gtavoalva in that the original tab has switched to the schema selected in the second tab.  Basically the expectation is that once I have selected a database and schema in one tab it should stick regardless of what I do in other tabs.

**Comment by dariopnc** [comment]
> Hi. Do you have some update for this issue? I try version 5.2.4 and have the same behaviour. Regards.

Hi, I think one of the last versions upgrades flipped off the switch [mentioned by](https://github.com/dbeaver/dbeaver/issues/2180#issuecomment-330979162) serge

That may explain why people are noticing this behaviour on recent versions, while they never experienced it before
