### ISSUE TITLE
Question : Best Way to Sync Config Between Applications

### ISSUE THREAD

**Issue by benyanke** [serge-rider/dbeaver#2181]
I regularly use multiple computers during my development, and keep my configuration files in sync with NextCloud (similar to Dropbox) - most of the dotfiles in my home directories are simply soft-links into my NextCloud folder.

Is there currently a good way to do this with DBeaver, and if so, what's the recommended method? Linking the profile's directory into my sync folder resulted in errors on starting the program.

**Comment by serge-rider** [comment]
You can run DBeaver with command line parameter `-data <path>` where path is location of shared DBeaver workspace (the one which is regularly in `%user_home%\.dbeaver4`).

Also you can use project export/import feature (in main menu File) but this is not very convenient if you have to do this frequently.
