### ISSUE TITLE
How to modify the default font in the dbeaver source code?

### ISSUE THREAD

**Issue by caosuwenwu** [serge-rider/dbeaver#2185]

**Comment by caosuwenwu** [comment]
font

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/30662380-88694114-9e4f-11e7-88e6-81eb792fa152.png)

**Comment by caosuwenwu** [comment]
thank you !! 但是我说的源码里的，已经找到了。
