### ISSUE TITLE
Statement delimiter problem with BEGIN; keyword

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#2186]
Hi,

With DBeaver 4.2.1, I get the same issue as this one: [#1114](https://github.com/serge-rider/dbeaver/issues/1114)

Is it possible to disable the standard behaviour for PostgreSQL, as it used to be in previous version?

Thanks in advance,

Cedric

**Comment by serge-rider** [comment]
Yep, it is a bug in 4.2.1.
This was fixed in #2171
Thanks for report anyway
