### ISSUE TITLE
Unable to save changes in one edited cell

### ISSUE THREAD

**Issue by MurKit** [serge-rider/dbeaver#2187]
1. Double click on cell and edit contents. Then Save (Ctrl+S) button is active and you can save the change.

2. One click on cell and Ctrl+V data into it. Save (Ctrl+S) button is **inactive**. So you cannot save the change when it was made by pasting.

![screenshot at 2017-09-20 11-45-19](https://user-images.githubusercontent.com/13369896/30634960-894260bc-9df9-11e7-87a7-77d780fe8b21.png)

**Comment by serge-rider** [comment]
Thanks for report. Fix will be in the next version.
Workaround: use "Save" button in the results bottom toolbar.
