### ISSUE TITLE
Dark theme error

### ISSUE THREAD

**Issue by Previatto** [serge-rider/dbeaver#2188]
I know that it's not you that do support for Dark theme. But I got an error while using it:

Dbeaver didn't connect to any connection, it just freeze, that circling arrow was frozen, stuck. Also, couldn't get to manipulate much the software, some menus opened, some don't.

After a fresh reinstall, it worked, normal, thinking it was solved, I changed to Dark theme (as I like it more) and it froze again. So looking in debug log I found this on debug.log:

```
2017-09-20 09:03:31.920 - Run workbench
java.io.FileNotFoundException: /css/e4-dark_erd_prefstyle.css
	at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:37)
	at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:169)
(...)
2017-09-20 09:03:34.191 - Initializing DBeaver 4.2.1
```

Thought it might be the cause, a missing css from dark theme. 

Couldn't find this css on my instalation, but in github project I found /css/e4-dark_erd_prefstyle.css in the plugins directory, so, I cloned the whole project and copied all plugins directory into .dbeaver4/.plugins.

It seems to worked as I'm able to connect and use it normal.

Now, I don't know if the .plugins directory should have this css or not, so this is why I'm sending this ticket.

[dbeaver-debug_copy.txt](https://github.com/serge-rider/dbeaver/files/1317678/dbeaver-debug_copy.txt)

**Comment by Previatto** [comment]
Actually, that idea of copying all plugin directory didn't work. I'm stuck again after a restart. But I managed to reset the theme and now dbeaver is working normal again.

**Comment by serge-rider** [comment]
This is a bug in ERD extension packaging. 
For some reason this problem appears only on some Linuxes (and never on Windows/MacOS).
Will be fixed in the next version. Thanks for report.
