### ISSUE TITLE
Enhancement - MSSQL Query Formatter Doesn't Handle "select top n" Well

### ISSUE THREAD

**Issue by benyanke** [serge-rider/dbeaver#2189]
The query formatter doesn't really handle MSSQL's "select top n" construct well. Not a bug, per se, but a usability suggestion:

For example, the following query:
```
select top 10 field1, field2 from thistable where field3 = 0;
```

Gets reformatted to:
```
select
	top 10 field1,
	field2
from
	thistable
where
	field3 = 0;
```

When it really should be formatted something like:
```
select top 10
	field1,
	field2
from
	thistable
where
	field3 = 0;
```

**Comment by serge-rider** [comment]
Agreed
