### ISSUE TITLE
Drop function in MySQL fails

### ISSUE THREAD

**Issue by raqua** [serge-rider/dbeaver#219]
When I attempt to delete function in MySQL, the actual code generated says "drop procedure", which obviously fails. 
Dbeaver 3.6.0

**Comment by serge-rider** [comment]
Thanks for report

**Comment by carlosjrcabello** [comment]
Hi there,

Here at **3.6.0** version, using a directly command to drop it, it works as bellow:

`drop function if exists `mask_phone`;`

If you're using statements delimiters, I believe that doesn't works, this one for instance:

```
DELIMITER $$

DROP FUNCTION IF EXISTS `mask_fone` $$

DELIMITER ;
```

Running on Windows 10 64 bits and MySQL 5.6.25

**Comment by serge-rider** [comment]
Problem will be solved in the next (hotfix) version. Will be released on the next week,
