### ISSUE TITLE
v4.2.1: I can't open ER diagram or tables anymore

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#2196]
Most of the items I try to double click just expend. No ERD or table view opens. This is a major bug to me. I just updated and reset views and perspectives. Nothing helps. Of course I also restarted DBeaver.

**Comment by serge-rider** [comment]
This is just a change in default double click behavior, it is configurable. See #2160

**Comment by GiantCrocodile** [comment]
Maybe there should be a small popup for first time which inform you about changes in default behaviour. Not everyone reads changelogs and this time I hadn't the time to do it so I skipped it. I didn't expect a default behaviour change.
