### ISSUE TITLE
POstgreSQL IF statement not working

### ISSUE THREAD

**Issue by hfculver** [serge-rider/dbeaver#2199]
Loaded DBeaver 4.2.1 (+JRE) 
Connected to PostgreSQL 9.6 instance (Google CloudSQL)
Ran simple test script, anonymous procedure, with IF statement as follows:
DO $$
DECLARE
  a integer := 10;
  b integer := 20;
BEGIN 
  IF a > b THEN
 RAISE NOTICE 'a is greater than b';
  END IF;
  IF a < b THEN
 RAISE NOTICE 'a is less than b';
  END IF;
  IF a = b THEN
 RAISE NOTICE 'a is equal to b';
  END IF;
END $$;

Result: internal jdbc driver error - java.lang.ArrayIndexOutOfBoundsException
![image](https://user-images.githubusercontent.com/2676553/30703950-60f12d2c-9eae-11e7-85f9-e5e803dd95d4.png)
I tested with DBeaver version 3.8.5, and this code ran with no problem.
Please advise as to any work-around.

**Comment by serge-rider** [comment]
This is internal error in PostgreSQL JDBC driver. 
Update driver version to the most recent (e.g. 42.1.4).
You can do this in DBeaver driver manager.

**Comment by serge-rider** [comment]
Also check fix in #2171
