### ISSUE TITLE
Dbeaver issue with Official Java SE 9 release

### ISSUE THREAD

**Issue by harshbhavsar** [serge-rider/dbeaver#2203]
Hi,
I have installed Java SE 9 (JDK 9) general availability release on my Mac OS. After that latest version of DBeaver (4.2.1) is not working. I am getting java.lang.NoClassDefFoundError: java/sql/SQLException. I have added --add-modules=java.se.ee,java.sql in my dbeaver.ini file and still I am not able to run it. Please let me know the fix.

**Comment by ruspl-afed** [comment]
Looks like Eclipse platform issue for Neon, please see https://bugs.eclipse.org/bugs/show_bug.cgi?id=507417

**Comment by harshbhavsar** [comment]
I am using the latest version of STS, which is based on Eclipse Oxygen. So I dont think so it's neon issue.

**Comment by ruspl-afed** [comment]
The Eclipse Oxygen platform should include the fix of https://bugs.eclipse.org/bugs/show_bug.cgi?id=507417
The DBeaver 4.2.1 is based on Eclipse Neon platform that requires Java 8 JRE/JDK according to https://wiki.eclipse.org/Eclipse/Installation#Eclipse_4.6_.28Neon.29
So, I do not expect DBeaver 4.2.1 to work with Java 9 out-of-the-box.

Now it looks like DBeaver should be adopted for Eclipse Oxygen to resolve the issue.
Thanks for the report!

**Comment by harshbhavsar** [comment]
So, is there any way that I can run current version of dbeaver with java 9? I have both version installed (Java 8 and 9). Please let me know the fix, if I can still use Dbeaver with java 9.

**Comment by serge-rider** [comment]
1. We planning to migrate on Eclipse Oxygen in October.
2. To run DBeaver with non-default JRE:
```
dbeaver -vm <path-to-java-binaries>
```
path-to-java-binaries is where java executables reside.

**Comment by carlosspohr** [comment]
As framework developer, sometimes Java migration is a little bit awful :/

**Comment by harshbhavsar** [comment]
Yes, it is awful. But it's good that we always have some other way around to deal with issues.

**Comment by harshbhavsar** [comment]
Thank you @serge-rider. I will try with java 8 path.

**Comment by harshbhavsar** [comment]
It works with commond line from terminal. Thanks @serge-rider  @ruspl-afed

**Comment by livelazily** [comment]
Eidt `/Applications/DBeaver.app/Contents/Info.plist`,
Add somethins like this :
![info-plist](https://user-images.githubusercontent.com/449935/30789718-fe4bc806-a1d9-11e7-90e2-8adfbdac3d10.png)

then you don't need to start dbeaver from command line every time

**Comment by harshbhavsar** [comment]
@livelazily  I tried adding this. I am getting this error:
![image](https://user-images.githubusercontent.com/16673487/30789887-220bb524-a16e-11e7-93f1-083fef8a175d.png)
I have also tried adding the vm args in dbeaver.ini file

**Comment by livelazily** [comment]
@harshbhavsar I  don't know why, maybe it trigger something apple's  security checking😕.
I install dbeave by runinng
```
brew cask install dbeaver-community
```

maybe you can have a try

**Comment by harshbhavsar** [comment]
@livelazily  It worked with brew cask. I don't know how, but it did. Thanks alot :D

**Comment by stevenvo** [comment]
'brew cask install dbeaver-community' does not work for me. Same issue with JDK 9

**Comment by serge-rider** [comment]
DBeaver 4.2.2 is bundled with E4.7 which supports Java 9. Check #2247 for details.
