### ISSUE TITLE
Autocomplete of stored procedures in PostgreSQL still doesn't work

### ISSUE THREAD

**Issue by IntrumHuBd** [serge-rider/dbeaver#2205]
The ctrl+space autocomplete method works fine in Oracle, but not in PostgreSQL. I found in this issue #773 that this feature should have been included in 4.0, but I'm using 4.2.1 and it's still unavailable. 
I've created the connection with the default settings, and the database user has access to the information schema. I also see table names and in the db navigator I can see all the procedures, the only thing I miss is the procedure autocomplete. 
PostgreSQL version: PostgreSQL 9.4.12 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

Update: I just found that autocomplete works only one schema, but we're using 4 different schemas. So the question now is rather: is there a way to enable it for all the available schemas? Is this a db level setting?

**Comment by serge-rider** [comment]
You need to enable "Global search" option in SQL completion.
But there is a bug in 4.2.1 (#2221) which breaks this option. 
Will be fixed in 4.2.2. Thanks for report.

**Comment by robobobeng** [comment]
Hello, still doesn't work for me in DBeaver 5.2.0 (with a PostgreSQL 9.5 database). I checked the relevant checkboxes in the options and PostgreSQL functions (included the ones I created myself) are still not showing in autocompletion. 
![image](https://user-images.githubusercontent.com/41967635/46528151-59f86980-c893-11e8-9627-461847684445.png)

**Comment by serge-rider** [comment]
It works with <kbd>ctrl+space</kbd> and only if you typed at least one letter of procedure name.
Otherwise it produces huge list of procedures (as every PostgreSQL database has a lot of them) making auto-completion senseless.
Maybe we could improve this a bit more but for now I don't have good ideas. Maybe it should be triggered without ctrl+space...

**Comment by Moridin11** [comment]
Is there any update to this issue?  This still happens.  I know I've seen SPs SOMETIMES.  

I also notice that for SPs that are "quoted" it never seems to work. i.e. public."myStoredProcedure"
