### ISSUE TITLE
See Oracle cursors.

### ISSUE THREAD

**Issue by xyu-r0nin-** [serge-rider/dbeaver#2207]
When I execute oracle procedures that returns cursors, the result is not seen, only see -- REFCURSOR in the grid

DBeaver 4.2.1
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Ubuntu Yakkety 16.10
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0

![oracle_refcursor](https://user-images.githubusercontent.com/7806764/30808802-1a634452-a1c5-11e7-84c8-dbef83ca6979.png)

**Comment by serge-rider** [comment]
4.2.2 support REF CURSOR view in value view dialog (<kbd>SHIFT+Enter</kbd>). Please check.

**Comment by xyu-r0nin-** [comment]
Thank you very much. It works very well

**Comment by jfcjfc** [comment]
oracle 11gR2 XE, dbeaver 4.3.4, Ubuntu 17.10
=> procedure, dynamic pivot sql with refcursor, and shift+enter as this issue for looking results

view image
=======
REFCURSOR in the result panel,
 then as described in this shift+enter issue,
the results appear in another window
but no possibility to save the results in spite of a correct presentation on the additional panel (482 lines X 52 rows),.
right click, "export results" not available,
====> how to export in csv (in the procedure or in.. select proc from dual)?? 
![refcursor](https://user-images.githubusercontent.com/4738651/36092188-c5bb805a-0fe6-11e8-9304-b86c3290aa19.png)

**Comment by serge-rider** [comment]
Data export is not supported for cursors.
But you can fetch all rows and copy them in clipboard (<kbd>ctrl+a</kbd> - <kbd>ctrl+c</kbd>). Then you can paste it in any text editor or in Excel.
