### ISSUE TITLE
GC Overhead Limit

### ISSUE THREAD

**Issue by XiozTzu** [serge-rider/dbeaver#2209]
I have seen messages in the past where a large download causes a memory issue in DBeaver.  The solution seems to be Export Tables by Segments.  I have tried this and get partial file downloads but always they end with the java.lang.OutOfMemoryError: "GC overhead limit exceeded" message.  

I am using DBeaver 4.2.1 64-bit with JRE-8u144 x64 and exporting data from a PostGRES server using 9.4.1212.jre7 driver.

**Comment by serge-rider** [comment]
Try to enable fetch size and `Use SQL to limit fetch size":
![image](https://user-images.githubusercontent.com/6398845/30848936-58975b48-a2a9-11e7-9b4c-5cd9ebf0a810.png)

**Comment by XiozTzu** [comment]
That seems to work if I also set the export to by Segments.  

Thank you!  

I would only request that the error message maybe point you to a solution rather than a generic error.

**Comment by serge-rider** [comment]
DBeaver 4.2.2 will support export of huge PostgreSQL tables without these options.

**Comment by jaclas** [comment]
I get this error on export table from FireBird 3, table has about 2500000 records

**Comment by jerherder** [comment]
HEllo

i got this error on a postgres table of 250000 rows. for 100000 rows,no problem for display. but after 100000 problem.

have you a solution?

**Comment by serge-rider** [comment]
How are you viewing 1000000 rows? Do you use Fetch All command or just set max rows to some very big number?
You could try to increase maximum amount of memory for DBeaver (https://github.com/dbeaver/dbeaver/wiki/Command-Line)
However maybe you'd better use data export. It is not very clear why do you need so many rows in results viewer.

**Comment by jerherder** [comment]
Hello
Hello,
i view the 100000 rows.i set the number of rows to display. i have increase the maximum amount of memory(1st at 1024, 2048 in second, 4096 in Third) but always the same problem.

the data export doesn't works. the same error.

thanks

**Comment by serge-rider** [comment]
@jerherder So you set number of rows explicitly?
- Try to set default row number (200) and make data export. Is it still fails with "out of memory"?
- What is your database/driver?

**Comment by jerherder** [comment]
Hello,

yes i set manually the number of rows. until 100000 rows, no problem of memory.

the driver is the driver Postgresql-9.4.1212.jre.7.jar

Kind regards

**Comment by serge-rider** [comment]
Why do you set so big number of fetched rows? Do you experience some issues with rows scrolling or with data export?
What DBeaver driver do you use (`PostgreSQL` or `PostgreSQL Generic` - hint you should use `PostgreSQL`).

**Comment by jerherder** [comment]
Hello

i use postgres driver and not postgresql generic

**Comment by jerherder** [comment]
i set a big number of rows because the developper want works on all the data.

**Comment by serge-rider** [comment]
There is no other workaround than to increase max memory (-Xmx cli parameter).
Actual number of rows is very dependent on table structure. For some compact tables  you can fetch a few millions row.
