### ISSUE TITLE
PostgreSQL: Cyrillic names of the fields

### ISSUE THREAD

**Issue by IgorNovozhilov** [serge-rider/dbeaver#2211]
Autocomplete does not work for Cyrillic names of the fields

> win7, ru_RU. 

#### encoding
![image](https://user-images.githubusercontent.com/3082812/30856150-2853eac0-a2c0-11e7-905a-78d27d29090d.png)

#### for Latin names
![image](https://user-images.githubusercontent.com/3082812/30856498-3bfe0e4c-a2c1-11e7-86a4-274d8c75abf8.png)

#### for Cyrillic names of tables
![image](https://user-images.githubusercontent.com/3082812/30856458-1c4df8d2-a2c1-11e7-8f7b-8c3a133c0901.png)

#### for Cyrillic names of table fields
![image](https://user-images.githubusercontent.com/3082812/30856360-cab490a8-a2c0-11e7-9269-f477e7379cbc.png)

**Comment by serge-rider** [comment]
Thanks for report
