### ISSUE TITLE
PostgreSQL: Indexes predicate 

### ISSUE THREAD

**Issue by IgorNovozhilov** [serge-rider/dbeaver#2212]
There are no conditions for partial indexes in DDL window

In pgAdmin
![image](https://user-images.githubusercontent.com/3082812/30857049-085c8a26-a2c3-11e7-91c2-26b23f494e5d.png)

In DBeaver
![image](https://user-images.githubusercontent.com/3082812/30857024-eb75177a-a2c2-11e7-9b71-de344c8adfb8.png)

![2017-09-26_14h01_01](https://user-images.githubusercontent.com/3082812/30857198-8ad56a4a-a2c3-11e7-95c5-b62a5c4e928b.png)

**Comment by serge-rider** [comment]
Agreed, this makes sense (for any indexes actually).

![image](https://user-images.githubusercontent.com/6398845/30867195-f62969ac-a2e3-11e7-98a1-577772f3056e.png)

**Comment by IgorNovozhilov** [comment]
@serge-rider, In `DDL` description of the table this information will not be displayed?

**Comment by serge-rider** [comment]
Yes, index DDL (in native form) will be included in table DDL as well.
