### ISSUE TITLE
Connection Netezza with Mac

### ISSUE THREAD

**Issue by AngelinaD** [serge-rider/dbeaver#2219]
Hi there,

I am trying to connect to Netezza using Mac and I get the following error:

Can't create driver instance
  Can't load driver class 'org.netezza.Driver'
    org.netezza.Driver
    org.netezza.Driver_

I then tried to find nzoledb driver for Mac to download with no success. How can I work this out?

Thank you :)

**Comment by serge-rider** [comment]
Netezza JDBC driver isn't publicly available, it has to be downloaded from IBM web site:
 https://www.ibm.com/support/knowledgecenter/en/SSULQD_7.2.1/com.ibm.nz.datacon.doc/t_datacon_jdbc_driver_install_win.html

Then you can add Netezza jars in DBeaver driver manager.

**Comment by AngelinaD** [comment]
Thank you,

I found this link before but could not download it because it is windows compatible.

**Comment by serge-rider** [comment]
JDBC driver should be multiplatform. 
While oledb/odbc are Window-only.
