### ISSUE TITLE
DBeaver: SQL Server script separator "GO" not handled/implemented

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2220]
DBeaver - **Version 4.2.1**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

If I try to use SQL Server separator "GO" in SQL commands (to split execution in sections) there is an error message shown:

  Query execution failed
  Reason: Incorrect syntax near 'GO'.

This does work (with no ";" end-of-command markers):

  SELECT '1st'
  GO
  SELECT '2nd'
  GO

This does not work (with ";" end-of-command markers):

  SELECT '1st';
  GO
  SELECT '2nd';
  GO

This does not work (with or without ";" end-of-command markers):

  CREATE TABLE TestTable(Id INTEGER, Value VARCHAR(80))
  GO
  ALTER TABLE TestTable ADD Extra VARCHAR(80)
  GO
  SELECT Extra FROM TestTable

My guess is that "GO" is not implemented as a way of splitting a SQL script into parts on SQL Server connections.

**Comment by serge-rider** [comment]
How do you execute these queries?

Generally if you need to execute a script you can use <kbd>ALT+X</kbd> instead of <kbd>CTRL+Enter</kbd>. In this case DBEaver will parse all queries splitting them by GO keyword.

**Comment by pdanie** [comment]
Super :)

I had not noticed that there where both a _Execute SQL Statement_ (Ctrl+Enter) and a _Execute SQL Script_ (Alt+X).

The second version worked great with the "GO" separator. Thanks for the information!

Are there a special reason that the Execute SQL Statement is available (ie would not the Execute SQL Script suffice) ?

**Comment by serge-rider** [comment]
Execute SQL Statement is helpful if you have a number of queries in a single script.
You can divide them with empty lines or SQL delimiters (`;` or `GO`) and execute at any moment by just positioning cursor on a query and pressing <kbd>CTRL+Enter</kbd>.

**Comment by ceinmart** [comment]
@serge-rider 
I'm using dbeaver 7.0.4 with mssql-jdbc-7.4.0.jre8.jar and it isn't recognizing the GO separator. 
I check the advanced parameters and for this jdbc there is no parameter to set. 
For the jTDS they show the adv. parameters... and there is GO as the separator.
How to workaround without changing the editor separator? 
I need to make this adjustment only for SQL server connections.
