### ISSUE TITLE
"Use global search (in all schemas)" setting in "SQL Completion" preferences not saved

### ISSUE THREAD

**Issue by antonwierenga** [serge-rider/dbeaver#2221]
If I check the "Use global search (in all schemas)" setting in "SQL Completion" and press "Apply" and/or "OK" it is not saved. If I reopen the "SQL Completion" preferences it is unchecked again. 

I am using DBeaver 4.2.1  on OSX 10.12.6.

**Comment by serge-rider** [comment]
Thanks for report
