### ISSUE TITLE
Cannot dock Database Navigator

### ISSUE THREAD

**Issue by nmadham** [serge-rider/dbeaver#2224]
Whenever I try open to open a new SQL editor (Ctrl+F3) ,Dbase navigator is kept as a tab and SQL editor is opening adjacent to it leaving some space on the right,which is annoying. Can you make Db navigator docked ??

![image](https://user-images.githubusercontent.com/16705400/30964964-842e9022-a421-11e7-9dce-aedb3d0c650f.png)

**Comment by serge-rider** [comment]
Looks like broken workbench config.
You could try:
- Main menu Windows->Reset perspective
- or Reset workspace (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace)

**Comment by nmadham** [comment]
Worked ,thanks .
