### ISSUE TITLE
Sort values by name in field "Collation" in Create new database window

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#223]
Maybe let xxx_general_ci at first position.

**Comment by serge-rider** [comment]
Currently general_ci is already at first position, at least in my environment.
In fact collations are in the same order as results returned from "SHOW COLLATION" command. If you have simple some improvement on mind - just tell.

**Comment by MatyCZ** [comment]
You can read values from "SHOW COLLATION" command and after that you can sort them on app side.

**Comment by serge-rider** [comment]
I don't think that sort by name will be helpful. In fact currently DBeaver selects default collation in combo (usually it is *_general_ci). Looks like most reasonable way, doesn't it?.

**Comment by MatyCZ** [comment]
Yes default collation and first value *_general_ci is OK.

But when I need change it to *_czech_ci I can not find this value quickly, because another values are not sorted alphabetically.

**Comment by serge-rider** [comment]
Ok, makes sense.

**Comment by MatyCZ** [comment]
That was quick, thanks.
