### ISSUE TITLE
Oracle: NUMBER(*,0) not shown correctly in "Columns" view

### ISSUE THREAD

**Issue by palbr** [serge-rider/dbeaver#2233]
Steps to reproduce:
1. `CREATE TABLE TEST (
  MY_FLOAT NUMBER,
  MY_MAXINT NUMBER(*,0)
)`
2. Look at the tables properties in "Columns" view:
![grafik](https://user-images.githubusercontent.com/2083705/31016105-a4c0b89e-a523-11e7-8dd0-afa756bbc408.png)

There is no difference visible between column "MY_FLOAT" and column "MY_MAXINT", although there definitely is one:
"MY_MAXINT" should have a "Scale" set to "0".

**Prove of difference:**

````
INSERT INTO TEST VALUES(123.456, 0);
INSERT INTO TEST VALUES(0, 123.456);
````

Leads to:
![grafik](https://user-images.githubusercontent.com/2083705/31016258-4202f176-a524-11e7-914a-88765fcee188.png)

I am using DBeaver in version 4.2.1.

**Comment by serge-rider** [comment]
This is a bug in Oracle numeric types representation.
Thanks for report.

**Comment by palbr** [comment]
Thanks for the very quick fix! :)
