### ISSUE TITLE
global filter on Schema's not working correctly

### ISSUE THREAD

**Issue by herbinator** [serge-rider/dbeaver#2234]
I changed global filter on Schema's on postgress/edb to exclude 'dbms*' . Only now showing 1 schema pg_catalog. All others are gone. 
Creating an Include gloabl filter not working when using 'dbms*' It does work when using 'dbms%'

**Comment by serge-rider** [comment]
Thanks for report

**Comment by herbinator** [comment]
exclude global filter still not working

**Comment by serge-rider** [comment]
Yep (actually this depends on database).
Global filters search fixed. See fix in 4.2.3
