### ISSUE TITLE
cannot change default database collation for MySQL in dbeaver GUI

### ISSUE THREAD

**Issue by bugzc** [serge-rider/dbeaver#2236]
I do not see an option to change the default collation for a MySQL database in dbeaver 4.2.1. When I select a database connection and hit F4 (or right click and "Edit Database"), I can see what the default collation is currently set to, but no edit options appear. This functionality is available in MySQL Workbench.

Maybe I am missing something, and it's there - if so, maybe an intuitive right-click edit option would be good.

Relevant screenshot:

![image](https://user-images.githubusercontent.com/20747402/31021709-a472f81c-a504-11e7-826a-a75fb3cc95f8.png)

**Comment by serge-rider** [comment]
It is not yet supported

**Comment by serge-rider** [comment]
Both charset and collation will be editable in 4.2.4.

**Comment by kid1412621** [comment]
@serge-rider I am using version 5.1.1.Still unable to edit the value in system info under connection menu.Am I doing wrong?
