### ISSUE TITLE
Add of warning message when execting UPDATE or DELETE without WHERE

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2238]
DBeaver - **Version 4.2.1**
Operating System: **Windows 7 / Windows 8.1**

It would be benificial if it was shown a warning message with Yes/No button if I by mistake execute a UPDATE or DELETE command in a SQL script where I have forgotten to write a WHERE clause.

See functionality in RedGate SQLPrompt.
https://www.red-gate.com/products/sql-development/sql-prompt/index

Also look at YouTube demo of SQLPrompt
[https://youtu.be/LQznXAKyFoI](https://youtu.be/LQznXAKyFoI) (at timestamp **3:21**)

**Comment by serge-rider** [comment]
Good point.
And it is easy to implement.
