### ISSUE TITLE
Add functionality to edit multiple grid column cells at once

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2239]
DBeaver - **Version 4.2.1**
Operating System: **Windows 7 / Windows 8.1**

It would be benificial if I could select multiple grid column cells and start to edit all their values as one.

See functionality in DataGrip.
[http://www.jetbrains.com/datagrip](http://www.jetbrains.com/datagrip)

Also look at YouTube demo of DataGrip
[https://youtu.be/RlNEwBhckDA](https://youtu.be/RlNEwBhckDA) (at timestamp **12:55**)

**Comment by serge-rider** [comment]
Do you mean setting the same value in multiple cells? As for me this looks quite weird in DataGrip.
But I like how it is done with copy-paste (paste replaces multiple cells). And it is easy to implement:

![paste-multi](https://user-images.githubusercontent.com/6398845/31052423-d0d86188-a68c-11e7-8418-c1e54ac896c6.gif)

I'll include this in 4.2.2.

**Comment by pdanie** [comment]
I have now tried it out in 4.2.2 CE, and it works as you describe it. Thanks!

But... If I for instance want to change all selected column cells to for instance "**Susan**". I now must start windows _Notepad_ or equivalent and enter "**Susan**" there and choose **Copy**. First then can i in DBeaver make a **Paste** as you show.

Why not have an **Inline Edit** directly on a couple of grid column cells ?

**Comment by serge-rider** [comment]
Agreed, this makes sense.
See additional; improvements in the next version.

**Comment by pdanie** [comment]
One way to do it more in the line of copy/paste could be:

**1**) I select a number of column cells
**2**) I then right click on one of the cells and choose **Multiple edit** in the context menu (or something)
**3**) A popup dialog is displayed and I can fill an edit/text box with the new column value.
**4**) When I press the **Save**/**Ok** button in the dialog, the new value from (**3**) is pasted into the cells.

I guess that this could be easier to implement than how _JetBrains DataGrip_ has implemented their way of doing it. And it would be more in the line on how the new DBeaver version 4.2.2 multi column cell paste work.

**Comment by serge-rider** [comment]
Check EA version ( https://dbeaver.jkiss.org/files/ea/)
Actually it already works this way. You can select  multiple cells and:
1. Open editor (shift+enter)
2. Start inline editor

Both actions will update multiple cells. Although we need some beta testing of this..
