### ISSUE TITLE
Mongo DB 3.x support

### ISSUE THREAD

**Issue by thomas-bishop** [serge-rider/dbeaver#224]
When will add support for Mongo 3.x new authentication model?

**Comment by serge-rider** [comment]
What exactly "authentication model" do you mean?

**Comment by thomas-bishop** [comment]
Hi Serge,

In Mongo DB 3.08, they changed the “model” for authenticating users connecting with the data base.
What you will find is that DBeaver cannot connect to Mongo 3.08 or later. In my Spring application, I had
to use updated MongoDB Java driver, and I had to change my Spring code to use the “MongoClient” to
set the credentials (username, password, plus connection info) for the DB connection.
This is all documented on the Spring site. If you need some more information, let me know, I can go back
and look up again. Shouldn’t be too big a deal. Would be nice if I can continue to use DBeaver with Mongo DB.

Thanks.

-Thomas

**Comment by carlosjrcabello** [comment]
Hi @thomas-bishop, 

Will Mongo DB change his authentication model on each next versions ? Comparing with previous, is there only "model" that you talked above?

**Comment by thomas-bishop** [comment]
Hi,

I can’t say for sure what MongoDB team will do, but I would not think they will be changing this again for awhile.
I don’t know the details motivating the change, but I would think there was a good reason for doing it.
Like I said should not be a big deal. Some other tools already incorporate the needed changes.

-Thomas

**Comment by serge-rider** [comment]
I'll try to adapt DBeaver for Mongo 3.x in the next version.
Hopefully they have some backward compatibility.

**Comment by thomas-bishop** [comment]
Hi Serge,

How do I get this update. I’ve been unable to use DBeaver for Mongo for some time now.
Thanks.

-Thomas

**Comment by infectormp** [comment]
@thomas-bishop you need wait for 3.6.2 release
You can see approximate release dates in milestone details.
https://github.com/serge-rider/dbeaver/milestones

**Comment by thomas-bishop** [comment]
Okay. Looks like it is behind schedule, so please let me know when it is released.
Thanks!

-Thomas

**Comment by serge-rider** [comment]
3.6.2 will be released around March 14.
There was a bad date in the milestone info (dunno how it happened).

**Comment by thomas-bishop** [comment]
Thanks Serge! Looks good.
