### ISSUE TITLE
HELP - DBeaver - Multiple statements not working.

### ISSUE THREAD

**Issue by nya13** [serge-rider/dbeaver#2244]
Hi,

I am running MariaDB.  Not that it will matter.

When we open the SQL Explorer in DBeaver and input more then one statement, the application gives us an error.  If we try each of those statements one at a time, it works without issues.

Try the following statements:

**SHOW tables;
SHOW tables;**

Select all and then execute.  You will get this error message:

_(conn:78) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SHOW tables' at line 2
Query is : SHOW tables;
SHOW tables
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SHOW tables' at line 2
Query is : SHOW tables;
SHOW tables
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SHOW tables' at line 2
Query is : SHOW tables;
SHOW tables_

If you were to try each statement, it works fine.

**Comment by serge-rider** [comment]
Use Execute Script (<kbd>Alt+X</kbd>) command to process multipel statements.

**Comment by kartikea** [comment]
I have used UNION as option.
SHOW tables UNION
SHOW tables;

**Comment by qqcvd** [comment]
Since this year, you can use Blocks in Snowflake scripting 

BEGIN

END;

see :
https://docs.snowflake.com/en/developer-guide/snowflake-scripting/blocks.html#understanding-blocks-in-snowflake-scripting
