### ISSUE TITLE
DBeaver - Maximum statements that can be executed in the SQL Explorer?

### ISSUE THREAD

**Issue by nya13** [serge-rider/dbeaver#2245]
Hi,

So I have tried to import and execute a few hundreds SQL statements and DBeaver gives me an error message when I get somewhere near 1000 statements.  Is that normal?  Can we make it show there is no limit or/and at least, read and execute directly from a .sql file?  This is the error message:

(conn:86) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALTER TABLE `languages` ENABLE KEYS */;

**Comment by serge-rider** [comment]
There are no any limitations in DBeaver itself.

Perhaps it is just an error in SQL file or something. You can check Query Manager view to see what actual query caused the error.

**Comment by nya13** [comment]
I will check that Query Manager and see.  But if I copy and paste the first part and execute them, it works.  Then I copy and paste the last portion, and they work too.  So I can say the entire statements have no errors.

**Comment by serge-rider** [comment]
The maybe something is wrong with query delimiters. 
Anyhow I can't say what is it without actual query example. 
Just open query manager (main menu Window->Show View->Query Manager or click on `Log` item under SQL editor) and check what happens.

**Comment by nya13** [comment]
Found the issue.  The SQL export from HeidiSQL was not understood by DBeaver.  HeidiSQL exported the single quote character ' of a value using \', which may not work in DBeaver.
