### ISSUE TITLE
Problem in updating the gui when db name has '-'

### ISSUE THREAD

**Issue by lartick** [serge-rider/dbeaver#2246]
When I am trying to modify a Mariadb database that has a '-' in its name (e.g. when adding a table 'c' in a db named 'a-b'), hitting the save button prompts the following error in a popup even though the modification is effective. 
```
(conn:6) Unknown column 'Tables_in_a' in 'where clause'
Query is: SHOW FULL TABLES FROM `a-b` WHERE Tables_in_a-b LIKE 'c'
  Unknown column 'Tables_in_a' in 'where clause'
Query is: SHOW FULL TABLES FROM `a-b` WHERE Tables_in_a-b LIKE 'c'
  Unknown column 'Tables_in_a' in 'where clause'
Query is: SHOW FULL TABLES FROM `a-b` WHERE Tables_in_a-b LIKE 'c'
```
Since version 4.1.1 community under ubuntu, it does not happen with version 4.1.0

**Comment by lartick** [comment]
The problem seems to come from the correction of [issue 1609]( https://github.com/serge-rider/dbeaver7/issues/1609) where "WHERE" conditions are not properly quoted. When deactivating "Server side object filters" in the properties of the connection the problem does not appear

**Comment by serge-rider** [comment]
Thanks for report
