### ISSUE TITLE
Java 9 + DBeaver 4.2.2 fails at start with NoClassDefFoundError / IllegalStateException

### ISSUE THREAD

**Issue by mmoehring** [serge-rider/dbeaver#2247]
Hello,
I downloaded the new 4.2.2. to test it with Java9, deleted all settings, started it and got an error preventing the startup. See attached log files:

[dbeaver-debug.log](https://github.com/serge-rider/dbeaver/files/1348730/dbeaver-debug.log)
[dot.log](https://github.com/serge-rider/dbeaver/files/1348731/dot.log)

**Comment by mmoehring** [comment]
Thanks!

**Comment by syhily** [comment]
Yeah, add `--add-modules=ALL-SYSTEM` after `-vmargs` fixed this issue.

**Comment by JonnyTech** [comment]
Worked for me too - this is my file now looks like:

```
$ cat /usr/share/dbeaver/dbeaver.ini
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.500.v20170531-1133
-showsplash
--launcher.GTK_version
2
-vmargs
--add-modules=ALL-SYSTEM
-Duser.language=en_US
-Xms64m
-Xmx1024m
```
