### ISSUE TITLE
Insert records in a sqlite database from a different connection

### ISSUE THREAD

**Issue by mirage51** [serge-rider/dbeaver#2248]
Hi!

I have 2 connections:
1. some DBF files
2. a sqlite database

the sqlite database has all the tables and records from dbf connection tables to a certain date.
But I have a problem..... The dbf files are filled with new records all the time and I want to put those records in my sqlite database.

I know how to use the clause "NOT IN" to read a different records between 2 tables, but is it possible to use SQL commands cross-connection?

PS: another idea?

Thanks!

Best regards!

**Comment by serge-rider** [comment]
This will require composite database driver (see #1804)
Such feature will become available once we'll have such driver.
