### ISSUE TITLE
Query: always run in background

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2251]
[_] always run in background 

cannot be checked when a query is running, nor pressing the button for it. the UI is almost jammed when running a query, like for exemple adding an index.

**Comment by serge-rider** [comment]
UI freeze fixed. However entity save blocks UI during metadata objects modifications.
If you set "always run in background" flag you can still cancel query using status bar progress monitor.

The only workaround is to run DDL query in SQL console (it won't block UI).

**Comment by sirber** [comment]
How can I set  "always run in background" flag? The UI is jammed when the option is showed. Can I pre-set the option?
