### ISSUE TITLE
DBeaver - How do we access the Users GUI?

### ISSUE THREAD

**Issue by nya13** [serge-rider/dbeaver#2252]
Hi,

Is there a screen in DBeaver that allows us to add/change/delete users who has access to our database(s) and where we can specify the various privileges?  Thanks.

**Comment by serge-rider** [comment]
This depends on database.
Full user management is supported in MySQL/MariaDB. Partial user management is supported in PostgreSQL/Oracle/DB2.

**Comment by nya13** [comment]
Ok cool.  I am using MariaDB.  How would I bring up the Users GUI in DBeaver?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/31095286-fa5fd934-a7c0-11e7-8265-e94a481ec163.png)

**Comment by dennisneise** [comment]
Is it possible to change the password of the user of the current connection with DBeaver. I have now searched a little, but could not find anything?
