### ISSUE TITLE
AS400 DB2 Admin mode

### ISSUE THREAD

**Issue by johnnydangster** [serge-rider/dbeaver#2253]
Hi,

Sorry if this question is not posted in the correct area.  
I am using DBeaver to connect to DB2 database on iSeries server.  I can do pretty much everything on the Test server.  However, when it comes to the Production server, I can't update any records. It gives me a "Not authorized to object X"

If I go to the emulator and type "admin (*on) then use STRSQL, I can make the updates.  

Is there anything that we can configure in DBeaver to do the same?  I need to run a lot of SQL stmts one after another and using STRSQL in iSeries would be a huge pain.

Thanks

**Comment by serge-rider** [comment]
If it is possible to switch to admin mode by SQL then you could try to execute this SQL in bootrstrap SQL queries (connection properties->General->Bootstrap queries)

**Comment by johnnydangster** [comment]
Serge-rider, 

Thanks for the response but I have no clue if that is even possible.  The Sysadmin folks are remote and aren't helpful here.

**Comment by serge-rider** [comment]
In any case, in DBeaver you can:
- set some connection (driver) properties
- configure bootstrap SQL (which will be executed right after database connection is initiated)
- configure shell commands (some native command line commands which can be run before/after connection). 

You can pass variables (like user name, host name, etc) in both bootstrap SQL and shell commands.

I think there are no other way to set connection configuration.
