### ISSUE TITLE
Editor highlights a word GO ending as a GO delilmiter (also affects execution)

### ISSUE THREAD

**Issue by DanNanovirus** [serge-rider/dbeaver#2255]
Hi, i found the following issue with the latest version of dbeaver (4.2.2)

In a sybase server trying a select statement having an object with name ending in "go", the editor highlights the go in the word and ignores it from the query.
For example, executing: 
SELECT * FROM dbo.OINGO_BOINGO 

would return the following error
dbo.OIN not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).
![screenshot from 2017-10-02 17-58-53](https://user-images.githubusercontent.com/23339566/31104659-66c6169a-a79b-11e7-9318-6f0ec0ec5919.png)

**Comment by serge-rider** [comment]
It is a bug in SQL parser. Thanks for report.

Workaround: quote your table name, use lower case or check `Ignore native delimiter` option on SQL Editor/SQL Processing preferences page.
