### ISSUE TITLE
Toggle Line Comment improper

### ISSUE THREAD

**Issue by OSmeilus** [serge-rider/dbeaver#2256]
I just upgraded to Windows 10 and now running DBeaver with Version 4.2.2.
Now I've noticed that formatting with "Toggle Line Comment" is now longer working properly. There is no toggle but a unique change.

Initial Situation:
SELECT *
  FROM tab_a
-- WHERE field_1 = 4711
 WHERE field_2 = 'abc'    

Formatting before updates: (by selecting last 2 lines and pressing Ctrl-Shift-7)
SELECT *
  FROM tab_a
 WHERE field_1 = 4711
 -- WHERE field_2 = 'abc'    

Formatting after updates:
either:
SELECT *
  FROM tab_a
-- WHERE field_1 = 4711
---- WHERE field_2 = 'abc'    

or:
SELECT *
  FROM tab_a
 WHERE field_1 = 4711
 WHERE field_2 = 'abc'

**Comment by serge-rider** [comment]
This behavior was changed on purpose - see #1850.
I think this is less confusing if you have a big query with many commented lines.

**Comment by OSmeilus** [comment]
Thank you for your response.

Well, this might fit the requirement when you mark commented lines and executable lines.
But this don't work, when you just want to **toggle** between commented and executable lines.

**Comment by prog-rajkamal** [comment]
Adding my issue to this one as they are related
------------------------

toggle line comment fails when there is a space at beginning of line.

eg: 

When toggling comment

     -- select * from emp; (there is a space at beginning of line)
 
results in

    -- -- select * from emp;

@serge-rider let me know if I should open a new issue for this

**Comment by serge-rider** [comment]
@prog-rajkamal It is a bug in comments processing. Thanks for detailed report.
