### ISSUE TITLE
DBeaver UI error column width

### ISSUE THREAD

**Issue by ems2811** [serge-rider/dbeaver#2259]
Hello.
DBEaver 4.2.2; PostreSQL 9.5.5; Win7; JRE 1.8.0
If the first displayed elements are NULL, after scrolling the result, the column is superimposed on the adjacent
```
WITH RECURSIVE tmp(price, to_dt) AS
	(SELECT 37780.39, '2016-04-30 00:00:00'::timestamp
	UNION ALL
	SELECT t.price, t.to_dt + '1 day'::interval
	FROM tmp t
	WHERE  t.to_dt<'2016-12-31'::date)

SELECT generate_series(1, 40, 1), NULL::timestamp AS to_dt
UNION ALL
SELECT *
FROM tmp
```
before scrolling: https://gyazo.com/64e5c5259cb34cc7473ba8884f889ca7
after scrolling: https://gyazo.com/31e7fd796d76ddd92dc0bc0ace224470

**Comment by serge-rider** [comment]
This is a bug in right-aligned numbers/datetimes rendering.
Thanks for report.
