### ISSUE TITLE
3.6: cannot change dataType

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#226]
Cannot change dataType from VARCHAR2 to NUMBER (or any other dataType). When i change dataType and remove focus from field, dataType set back to VARCHAR2.

**Comment by serge-rider** [comment]
What database?

**Comment by infectormp** [comment]
oracle

**Comment by serge-rider** [comment]
It is a bug in 3.6.0. Will be fixed in the next (hotfix) version.
Thanks for report!
