### ISSUE TITLE
Autocomplete not working with table alias

### ISSUE THREAD

**Issue by jeff-bowles** [serge-rider/dbeaver#2260]
Version 4.22, DB2 for LUW.

With the update to 4.22, autocomplete has stopped working when using a table alias.  I have rolled back to 4.21 and the feature is working again.

Example:

select
  f.field1
from
  foo f
where
  f.field2 = 'something'

In 4.22, autocomplete shows "no proposals" when I activate autocomplete after the "f."

4.22 autocomplete works if I avoid using table aliases.

**Comment by serge-rider** [comment]
In 4.2.2 we've added unicode identifiers support. 
There is a bug in this feature - now we can't properly resolve tables with digits in their names.

Can you confirm that autocomplete doesn't work only for tables with digits in name?

**Comment by jeff-bowles** [comment]
I am seeing the problem with normal table names like MASTER or CUSTOMER.

**Comment by vscherbo** [comment]
Version 4.2.2 CE for PostgreSQL
An autocompletion doesn't work for english schema name and, for example, russian table name, i.e. myschema.МояТаблица with or without alias.

**Comment by serge-rider** [comment]
@vscherbo Thanks for details
