### ISSUE TITLE
The transaction indicator does not increase its value when editing grid cell values

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2263]
DBeaver - **Version 4.2.2 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**

If I have a connection with setting _Connection Type_ set to **Production**, the indicator in the IDE count up every time I execute a SQL statement. But if I change a table row column value in a grid, the indicator does not change. 

This is a bit confusing, since the IDE start a transaction with the grid cell change after I press the grid **Save** button.

**o** Create a **Connection**/**Data Source** with the Connection type "**Production**".

**o** Start a SQL Editor and enter the SQL skript below:

    SELECT * FROM MyTable;

**o** The DBeaver IDE **Transaction Indicator** change from [**None**] to [**1**].

**o** In the DBeaver **Database Navigator**, double click on a table (so that its grid with data rows show).

**o** The DBeaver IDE **Transaction Indicator** change from [**1**] to [**2**] (for reading data for grid).

**o** Edit a grid row column cell value.

**o** Press the **Save** button in the grid to save the change.

**o** No change of the DBeaver IDE indicator (still showing [2]).

The above behaviour is really confusing. Would be better that all SQL commands that change data increase the DBeaver IDE **Transaction Indicator**.

**Comment by serge-rider** [comment]
Initially this was made on purpose. But I agree - now it looks weird.
Will be fixed in the next version.
