### ISSUE TITLE
The login/authentication pop up dialog can not be canceled 

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2264]
DBeaver - **Version 4.2.2 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**

There is no way to stop the popping up of the login/authentication dialog by pressing its **Cancel** button.

**o** Uncheck a DBeaver connection parameter: **General** -> **Security** -> **Save password locally** (ie setting it to False).

**o** Double click on the connection in DBeaver **Database Navigator** to connect to the database.

**o** The login/authentication dialog pops up.

**o** Press the dialog **Cancel** button to close the dialog.

**o** The dialog just pops up again, and again, and again...

It would be more understandable if the login/authentication dialog just close. This so that I can start to connect again, try to open another connection, or just close down DBeaver.

**Comment by serge-rider** [comment]
Thanks for report
