### ISSUE TITLE
Add of grid context menu choice for "master reset" of all grid row coloring

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2265]
DBeaver - **Version 4.2.2 CE**
Operating System: **Windows 7 / Windows 8.1**

It would be benificial if the grid context menu contained a choice for:

**View Format** -> **Reset color by any** (or equivalent)

This would reset all colors on all column values.

If I have set row coloring on different columns and in them different values, I have to choose each column and choose Reset color by <columnname>.

Would be much easier to have a context menu choice that reset all row coloring independet on any columns and any values.

PS. Maybe have a "Are you sure you want to reset all coloring? Yes/No" dialog that popped up. Just so that I don't reset coloring by mistake.

**Comment by serge-rider** [comment]
Agreed, this will be very helpful.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/31305434-64031228-ab42-11e7-8a79-d156934f519a.png)
