### ISSUE TITLE
"begin transaction" and Sybase

### ISSUE THREAD

**Issue by CatoLok** [serge-rider/dbeaver#2268]
DBeaver version: CE 4.2.2
Operating System: Windows 10
Driver: default driver for Sybase (net.sourceforge.jtds.jdbc.Driver)

When I try to execute scripts for creating the procedures that declares transactions within them I get the following error: "Incorrect syntax near 'go'."

I can execute the whole script below if I either:
1) remove both "begin transaction" and "commit transaction" 
2) execute the grant and sp_procxmode separately from the create procedure

Here is a dummy example I have created that is affected by this issue:

if exists(select * from sysobjects where type='P' and name = 'pr_begin_transaction_test')
   drop proc pr_begin_transaction_test
go

create procedure pr_begin_transaction_test
as

begin transaction
   select * from dbo.sysobjects
commit transaction
go

grant execute on pr_begin_transaction_test to your_user --TODO replace with a user in your database
go

sp_procxmode pr_begin_transaction_test, 'Anymode'
go

**Comment by serge-rider** [comment]
Thanks for report
