### ISSUE TITLE
Refresh button move to the first record of the table in "single record view".

### ISSUE THREAD

**Issue by roberto2357** [serge-rider/dbeaver#2269]
Hi Serge, I found a small anomaly in version 4.2.2.
When I press the tab key in a table record, I can view a single record data (very usefull), but if , in this situation, I press the "Refresh result set" button,
![immagine](https://user-images.githubusercontent.com/22471800/31179718-0300f016-a91d-11e7-91bc-959e4829de1c.png)
the "single record view" move to the first record of the table (without refreshing the opened record).

Thanks.

**Comment by serge-rider** [comment]
Yep, it is a bug in one of recent versions.
Thanks for report
