### ISSUE TITLE
Add support for the DBeaver command-line parameter "-data" in the DBeaver.ini file

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2272]
DBeaver - **Version 4.2.2 CE**
Operating System: **Windows 7 / Windows 8.1**

Would be benificial if I could set the **DBeaver.exe** command-line parameter "**-data=[config directory]**" in the **DBeaver.ini** file.

Note: I tried to place the command-line parameter "**-nosplash**" in the **DBeaver.ini** file and that work, which was great. But the "**-data**" parameter seem to have no effect.

**Comment by serge-rider** [comment]
There are two standard ways to do this:

1. Add line `osgi.instance.area=<path-to-your-dir>` in `configuration/config.ini` file
2. Or add line `-Dosgi.instance.area=<path-to-your-dir>` in dbeaver.ini file
