### ISSUE TITLE
DB2 SQL for dropping a primary key is invalid

### ISSUE THREAD

**Issue by djknowles** [serge-rider/dbeaver#2276]
The SQL code to drop a primary key/unique constraints is invalid for a DB2 database.

Steps to reproduce:
* Select/Open a DB2 database.
* Select/Open a schema.
* Select/Open a table.
* Right click on Unique Constraints and select View Unique Constraints.
* Select the primary key and click Delete (or the red cross at bottom right).
* Click Save
This displays the SQL preview for dropping the primary key of the form

ALTER TABLE SCHEMA.TABLENAME DROP PRIMARY_KEY  ;

This SQL is invalid and the command fails.

The correct SQL is

ALTER TABLE SCHEMA.TABLENAME DROP PRIMARY KEY  ;

(note PRIMARY_KEY should be PRIMARY KEY, no underscore).

**Comment by djknowles** [comment]
Sorry this defect manifests in Community edition 4.2.2

**Comment by serge-rider** [comment]
Seems to be fixed in 4.2.3.
