### ISSUE TITLE
update 4.2.2  connecting Database Oracle   return  error  ORA12705

### ISSUE THREAD

**Issue by wisaruty** [serge-rider/dbeaver#2277]
I'm update dbeaver 4.2.2
I 'm connecting to  Database Oracle return  error  ORA12705
I'm downgrade to dbeaver 4.2.1 use normolly

![10-5-2017 10-46-09 am](https://user-images.githubusercontent.com/12456804/31210258-1841bba6-a9bb-11e7-80e4-fd5c2986a7fd.jpg)

**Comment by serge-rider** [comment]
Perhaps it is the same as #2243
You can use workaround described there or re-download DBeaver from the web site (version 4.2.2 was re-published there)
