### ISSUE TITLE
Calculate total row count function with ordered query

### ISSUE THREAD

**Issue by danieleangellotti** [serge-rider/dbeaver#2279]
Hi Serge,
I found a little malfunction in DBeaver standalone version 4.2.2 CE: when I try to use the "Calculate total row count" function in some query ordered by an alias (e.g. SELECT 'a' AS myalias FROM dual ORDER BY myalias) I have an "Error executing row count" message.
I experienced this issue both in Oracle and in Postgres.

Thanks.

**Comment by serge-rider** [comment]
Yep, we just need to remove ORDER BY clause from COUNT query.
Thanks for report.
