### ISSUE TITLE
Error cursor position in Postgres

### ISSUE THREAD

**Issue by danieleangellotti** [serge-rider/dbeaver#2281]
Hi Serge,
I'm using DBeaver standalone version 4.2.2 CE with a Postgres connection: I saw that if I have an error then the cursor position (indicating the error) is correct only if I have the query on one line, otherwise the location is set back of one character for each new line.

Thanks.

**Comment by serge-rider** [comment]
This is related to Windows linefeeds. There was an ancient SQL query transform function in DBeaver which seems to be no longer needed.
Thanks for report.
