### ISSUE TITLE
SYNONYM list doesn't show all possible synonyms

### ISSUE THREAD

**Issue by dariopnc** [serge-rider/dbeaver#2282]
In the Database Navigator Panel, not all the synonyms owned by the current schema/user all displayed in the Synonyms "folder".

I wasn't able to guess the rationale.

I would expect all the records from
```
select * from SYS.ALL_SYNONYMS WHERE OWNER = $USER;
```
to be shown

**Comment by serge-rider** [comment]
Actual query is
```sql
SELECT s.*,O.OBJECT_TYPE 
FROM ALL_SYNONYMS S, ALL_OBJECTS O
WHERE S.OWNER=? AND O.OBJECT_TYPE NOT IN ('JAVA CLASS','PACKAGE BODY')
AND O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME
ORDER BY S.SYNONYM_NAME
```
So, java classes and package bodies are filtered. As far as I remember (this code is written years ago) this was done because of performance issues in Oracle 10 or something.
I think it makes sense to remove this condition. Or make it configurable.

**Comment by serge-rider** [comment]
In 4.2.3 all synonyms will be read by default.
