### ISSUE TITLE
In "Record" mode sort arrows disappear when executing query second time.

### ISSUE THREAD

**Issue by ravshansbox** [serge-rider/dbeaver#2285]
<img width="509" alt="screen shot 2017-10-06 at 4 21 46 pm" src="https://user-images.githubusercontent.com/1499188/31275902-9af66b62-aab2-11e7-94a9-1afa39db58b2.png">
<img width="554" alt="screen shot 2017-10-06 at 4 22 13 pm" src="https://user-images.githubusercontent.com/1499188/31275895-914f3256-aab2-11e7-8538-39b1a9da542f.png">

**Comment by serge-rider** [comment]
Thanks for report
