### ISSUE TITLE
Uncommitted Read 

### ISSUE THREAD

**Issue by sumithar** [serge-rider/dbeaver#2288]
I am using DBeaver with DB2/zOS.  Version 4.2.
When I use the grid to query from a database, is there a way to make sure that it is done with Uncommitted Read?
Like, when I write the SQL I add WITH UR at the end of my query.  But not sure when I use the grid control, the same is happening.
Thanks!

**Comment by serge-rider** [comment]
DBeaver doesn't add `WITH UR` in SQL queries.
But you can use global (per-connection) transaction isolation level. Switch to manual commit mode and choose level in main toolbar drop-down or in main menu `Database`:
![image](https://user-images.githubusercontent.com/6398845/31309088-3fb78c9a-ab89-11e7-99af-3db1e8d4ed57.png)
`Read uncommitted` looks like what you need.

**Comment by sumithar** [comment]
Thanks!  That should work.
