### ISSUE TITLE
How to compare structure & data of 2 tables of different databases in Dbeaver?

### ISSUE THREAD

**Issue by nikitaclarion** [serge-rider/dbeaver#229]
How to compare structure & data of 2 tables of different databases in Dbeaver?

**Comment by carlosjrcabello** [comment]
Hi @nikitaclarion,

I there isn't this feature in DBeaver, so you can use schema metadata, like information schema of mysql for instance, to do it. If you're using MySQL, you can compare columns using this query:

```
SELECT
    c.`TABLE_NAME`,
    GROUP_CONCAT(c.`COLUMN_NAME`) colunas
FROM
    information_schema.columns C
WHERE
    c.table_schema = 'some_db'
    AND 
    c.`TABLE_NAME` LIKE 'from_table%'
    AND 
    c.`COLUMN_NAME` NOT IN(
        SELECT
            xx.`COLUMN_NAME`
        FROM
            information_schema.columns xx
        WHERE
            xx.TABLE_SCHEMA = c.TABLE_SCHEMA
            AND 
            xx.`TABLE_NAME` LIKE 'target_table%'
    )
GROUP BY
    c.`TABLE_NAME`
ORDER BY
    1 ASC
```

**Comment by nikitaclarion** [comment]
thanks for the solution :) but Dbeaver is a data comparison tool too..so there must be some way to compare data automatically...bcoz if we follow the above provided solution (mean manually) then there is no need of this tool as we have to check everything manually.

**Comment by serge-rider** [comment]
DBeaver can compare metadata. Select 2 (or more) object and click on "Compare" in the context menu.
Data compare isn't yet supported.

**Comment by carlosjrcabello** [comment]
hahaha,

20394 years using it and I never realized that had this feature.

**Comment by nikitaclarion** [comment]
@carlosjrcabello : u didn't seem to be so old buddy..

**Comment by nikitaclarion** [comment]
@serge-rider : Please announce once again to the github users to maintain decorum of this group..

**Comment by serge-rider** [comment]
As for me - everything is in a respectful manner :)

As I said - just select two objects in the database navigator, open context menu and choose "Compare". DBeaver will generate HTML report with all metadata differences.

**Comment by nikitaclarion** [comment]
thanks for the solution..will get back to you if stuck somewhere.. :)

**Comment by SuperAtic** [comment]
@serge-rider any option to run a "Data Compare" against two columns in two different db?

**Comment by kriscook2** [comment]
We're migrating our Data Warehouse from SQL Server to Snowflake.  Trying to do a schema compare of tables, and I'm encountering an error stating: "Objects of different types were selected. You may compare only objects of the same type"

I'm comparing table vs. table. Not sure what I'm doing wrong.

**Comment by zwastik** [comment]
> Data compare isn't yet supported.

any status update on this?

**Comment by coderkan** [comment]
Hi there,

is there any update about that feature ? 

> > Data compare isn't yet supported.
> 
> any status update on this?

**Comment by uslss** [comment]
[Data compare](https://github.com/dbeaver/dbeaver/wiki/Data-compare) is already implemented in EE version

**Comment by OmarShezan** [comment]
Data compare only available on the payed version, are there any MariaDB data comparison tool out there that's free and opensource?
