### ISSUE TITLE
Foreign key name is to long

### ISSUE THREAD

**Issue by ChristoforosKor** [serge-rider/dbeaver#2291]
Hello, 
I am trying to create the foreign key bellow:
`ALTER TABLE c1_krimatoglou.haedf_elg_ergon_projectstates_data_power ADD CONSTRAINT haedf_elg_ergon_projectstates_data_power_haedf_elg_power_provider_FK FOREIGN KEY (provider_id) REFERENCES c1_krimatoglou.haedf_elg_power_provider(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
`
but am getting the error name is to long. I can not find a way to change the name of the key to something else.
What can I do?

**Comment by titou10titou10** [comment]
Hi,
What database are you using (DB2, Oracle..) and what version?
Is the error coming from the server or from DBeaver?
Can you show us what message/esception you receive?
Thanks
Denis

**Comment by pyhedgehog** [comment]
If this is about Oracle, then identifier limitation is 30 chars. Your problem identifier is `haedf_elg_ergon_projectstates_data_power_haedf_elg_power_provider_FK`.

**Comment by serge-rider** [comment]
@ChristoforosKor you can change foreign key. 
Before saving table changes click on FK name (in column Name) and set some other value.
