### ISSUE TITLE
[4.2EE Redis] value or key having spaces makes error.

### ISSUE THREAD

**Issue by blackduckdream** [serge-rider/dbeaver#2292]
* working ( even escaping double quote as value. not sure if this is expected behavior or not )
dbeaver> set say "Hello";
redis> get say
"\"Hello\""

* not working ( error popped up )
dbeaver> set say "Hello World";

Similar issues exist with key as well.

**Comment by serge-rider** [comment]
Will be fixed in EE 4.3.

And we'll make EE Early Access after 4.2.4 release.
