### ISSUE TITLE
Link script file

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#2297]
In the same way that we can link a folder under the Scripts root, it would be nice to be able to link one (or several) file(s).

![screenshot](https://user-images.githubusercontent.com/3851902/31341402-a54ba8b2-ad09-11e7-9ef6-ba8b4efaada3.png)

**Comment by ruspl-afed** [comment]
Command "Link File (SQL Script)" added before "Link Folder"

**Comment by Otiel** [comment]
Thanks, works great!

It would be a nice addition if we could select several files at the same time. :)

**Comment by ruspl-afed** [comment]
Good point, created #2543 to implement it
