### ISSUE TITLE
Ident connection on PostgreSQL with Dbeaver

### ISSUE THREAD

**Issue by thiagodiogo** [serge-rider/dbeaver#2298]
Hi folks,

I am trying to use DBeaver as my IDE to work on a PostgreSQL database using the Generic driver configuration but can't connect to my DB.

Actually my DB is using 'ident' connection mode and is not required user or password to obtain a connection (being connecting from my trusted IP is enough).

To do this, I've configured a new connection on DBeaver with blank user and password however I received the error: "FATAL: Ident authentication failed for user 'my_ubunut_user' "

From the same machine I can connect using PgAdmin3, for example, with no problem.

I think the problem would be DBeaver is using a blank login and password instead of don't use it. Or maybe using "" as login and password.

Any thoughts? 

Thanks in advice

**Comment by serge-rider** [comment]
There could be different causes of this problem.
For `ident` method user name is current OS user name (my_ubunut_user) and it has to be mapped in pg_ident.conf file. For trusted connection you should use `trust` auth method.

Can you connect with psql? If so - please tell what option do you specify.

**Comment by thiagodiogo** [comment]
Hi @serge-rider, thanks for you attention.

Yes I can perfectly connect using `psql` with no problem and using pgadmin3 too:
`psql -h HOST`

For test purposes I changed the PostgreSQL auth to `password` and it works pretty well.

Is there any verbose mode in DBeaver? 
_(I tried to find it in the docs but without success)_

**Comment by jsm296** [comment]
Hello,

I am helping Thiago with troubleshooting.

I wrote the simple class below to test.  It uses the PostgreSQL JDBC driver installed on our system to try to make a connection to the database.

To test, I specified our database host and database, my username, and then 1) a password, 2) no password - empty string, and 3) null for password.  In each case I get the same error I get through dbeaver:

"FATAL: Ident authentication failed for user 'my_ubunut_user' "

So, it looks to me like it might be a problem in the JDBC driver, not in dbeaver.  Does this make sense?  Have I replicated the way that dbeaver would make a connection in the case where the username is specified but no password is?

Thanks,

Jonathan Morgan

# The test class:

    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.SQLException;


    public class IdentTester
    {

        public static void main( String[] args )
        {
        
            // declare variables
            String jdbc_driver = "org.postgresql.Driver";
            String jdbc_url = "";
            String db_host = "<host_name>";
            String db_port = "5432";
            String db_database = "<database_name>";
            String db_username = "<username>"
            //String db_password = "";
            String db_password = null;
            Connection my_db_connection = null;

            // set up JDBC URL.
            //jdbc_url = "jdbc:postgresql://" + db_host + ":" + db_port + "/" + db_database;
            jdbc_url = "jdbc:postgresql://" + db_host + "/" + db_database;
            
            System.out.println( "Hello, world!" );
            
            // database connection
            try
            {
                Class.forName( jdbc_driver );
                my_db_connection = DriverManager.getConnection( jdbc_url, db_username, db_password );
                System.out.println( "Connection made..." );
            }
            catch ( SQLException sqle )
            {
                System.out.println( "Unable to create connection: " + jdbc_url + ".  SQLException: " + sqle.getMessage() );
            }
            catch ( ClassNotFoundException cnfe )
            {
                System.out.println( "unable to load the driver class: " + jdbc_driver + ".  ClassNotFoundException: " + cnfe.getMessage() );
            }
        
        } //-- end method main() --//

    } //-- end class IdentTester --//

**Comment by serge-rider** [comment]
Looks so.  
Perhaps this is one of JDBC driver's limitations..

**Comment by serge-rider** [comment]
Closing as we can't fix this from DBeaver side.
