### ISSUE TITLE
hwo to let stored procedure keep first times layout for ddl

### ISSUE THREAD

**Issue by bouyeijiang** [serge-rider/dbeaver#2300]
for example i don't need for that format
WHILE DateDiff(
   'Month',
   @OpTime,
   @EndTime
)>= 0 DO
SET @YearMonth = SUBSTR(
   CHAR( YEAR( @OpTime )),
   1,
   4
)|| Char2(
   MONTH(@OpTime),
   1
);

**Comment by serge-rider** [comment]
What is your database?

**Comment by bouyeijiang** [comment]
db2,

**Comment by serge-rider** [comment]
You can change DDL format in the bottom toolbar (`DDL Format` combo)

**Comment by bouyeijiang** [comment]
okay,i see
