### ISSUE TITLE
Cannot delete function in Postgres

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2301]
When trying to delete a function I got the following error:

`ERROR: function an.rep(integer, integer, integer[], text, text, text, date, numeric, numeric, integer, integer) does not exist`

This function has only 3 input parameters.
`CREATE OR REPLACE FUNCTION an.rep(in_provider_id integer, in_rate integer DEFAULT NULL::integer, in_rgroup_id integer[] DEFAULT NULL::integer[])
 RETURNS TABLE(rgroup_name text, brand_name text, prov text, pricelist date, avg_price numeric, min_price numeric, co_cross integer, co_gen integer)`

Function full name in Postgres is <function_name>+(<**function_param_list**>)
not <function_name>+(<**function_param_list**>+<**function_output_columns**>)
Also such wrong function names I can see in the object list and in the tabs headers.

**Comment by serge-rider** [comment]
Yep, TABLE parameter types are evaluated incorrectly.
Thanks for report.
