### ISSUE TITLE
Version 4.2.2 Thinks it is 4.2.1

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#2303]
I've upgraded to 4.2.2 more than once at this point. After doing so, Help > About reveals that the version is still 4.2.1. Because of this, each time I launch Dbeaver it prompts for an upgrade that I've already upgraded to multiple times.

**Comment by serge-rider** [comment]
That's weird. 
Did you download DBeaver from dbeaver.jkiss.org?

**Comment by Lonniebiz** [comment]
It sure is weird. Yes, of course, I'm downloading from the official website.

Take a look at [this video](https://youtu.be/OB6XgImmIXo).

**Comment by serge-rider** [comment]
Thanks for detailed video.
Looks like a bug in installer. You've installed DBeaver only for current user (so it will reside in user home folder). While you previous version was installed in program files. Program icon and shortcut are also pointing to program files. Sure thing - icon and shortcut must be updated by installer.

Workarounds: 
- install new DBeaver for all users. 
- run DBeaver from `USERHOME\AppData\Local\DBeaver` directory.
- Uninstall DBeaver from Program files and reinstall for current user.

**Comment by Lonniebiz** [comment]
I did Workaround 3, and I'm launching 4.2.2 without issue now. Thank you.

**Comment by Lonniebiz** [comment]
Just some positive feedback: During the upgrade to 4.2.3, the installer was actually aware that my current installation was "Only for me", and it defaulted to that preference during the upgrade. That's probably nothing new you've done, but I just it was pretty good work. I hardly ever encounter an installer that is thorough enough to check such things.

**Comment by serge-rider** [comment]
Thanks for info.
4.2.3 seems to be ok.
