### ISSUE TITLE
DB Full-Text search - double-click on matched table does not update table filter 

### ISSUE THREAD

**Issue by vascool** [serge-rider/dbeaver#2305]
1. DB Full-text search for the string 'hello'.
2. Double-click on matched table A in search result view to open it.
3. Notice the filter for table A is something like  column1 LIKE '%hello%' OR column2 LIKE '%hello%' OR ...
4. Search for the string 'goodbye' this time.
5. Double-click again on matched table A in search result to open it.
6. Notice that the filter for Table A is still the previous one with 'hello'. DBeaver does not update the filter to something like  column1 LIKE '%goodbye%' OR column2 LIKE '%goodbye%' OR ... for table A.

The "Rows Found (>=)" number seems to also get stuck for row count of the first search. It is not updated. This just happens for opened tables. Tables I do not open are in sync with the current search but get stuck if I open them.
If I pin a search view I can switch between searches and the filters are updated fine.
Using DBeaver 4.2.2.

**Comment by serge-rider** [comment]
It is a bug in search results page cleanup.
Thanks for report.
