### ISSUE TITLE
Bug with CASE WHEN ELSE END in Oracle script

### ISSUE THREAD

**Issue by MaxSher** [serge-rider/dbeaver#231]
While debugging an oracle script, I found it worked in Oracle SQL Developer but not DBeaver. On further investigation, I found the issue to be with a CASE statement.

SELECT CASE WHEN COLUMN1 = COLUMN1
THEN 'N'
ELSE 'Y'
END
AS NEWCOL
FROM TABLE1;

returns 
DBCException: SQL Error [911] [22019]: ORA-00911: invalid character
  java.sql.SQLSyntaxErrorException: SQLSyntaxErrorException: ORA-00911: invalid character

(The case is a trivial case in this instance just for ease of testing, it still occurs with more valid ones)

If the semicolon is removed (and it's the last statement in the script) or the CASE is replaced with an equivalent DECODE, the script runs fine.

Driver info: ojdbc6.jar, orai18n.jar, xdb6.jar
Native client: Oracle 11 Version 11.2.0.3.0

**Comment by serge-rider** [comment]
There is a bug in DBeaver - it appends trailing statement delimiter (;) if it thinks that query contains PL/SQL blocks. Which is obviously not true in this case (it is just CASE). This trailing delimiter makes Oracle mad.
Fix will be added in the next version.,
Thanks for report.
(Workaround - remove ; in the end of query and use blank line as query delimiter in SQL editor)
