### ISSUE TITLE
Can I shrink/fit resultset column width to match cell string length?

### ISSUE THREAD

**Issue by yanOnGithub** [serge-rider/dbeaver#2310]
Currently column width is automatically set to match the column name. My column names are longer than my cell contents. This is causing low screen estate utilization. Can I have a checkbox under Windows > Preferences to shrink it?

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/32146303-2e361414-bce6-11e7-90e1-96e7189d76de.png)

**Comment by yanOnGithub** [comment]
thx
