### ISSUE TITLE
How to disable flashing info "Dump server output"

### ISSUE THREAD

**Issue by palbr** [serge-rider/dbeaver#2312]
In my current DBeaver installation (version 4.2.2) I can see the text "Dump server output" in lower right corner of the DBeaver window (I guess it is a view of the current background tasks):
![grafik](https://user-images.githubusercontent.com/2083705/31426944-bc606fee-ae65-11e7-886a-c3852d891867.png)

This text is only displayed for aboug 500 milliseconds. But it appears randomly about 10 times in 40 seconds. So over some time this flashing is quite annoying and distracting.

Is there a way to disable especially this information "Dump server output" popping up and keep other "background task information" like loading progress?

(I am connected to an oracle database)

**Comment by palbr** [comment]
This does not happen, if a change back to version 4.2.1.

**Comment by serge-rider** [comment]
It is already fixed. 
See fix in 4.2.3.
thanks for report anyway.
