### ISSUE TITLE
DBeaver command-line parameter "-con" not supported correctly

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2314]
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

I noticed the wiki page from Serge Rider describing DBeaver command line parameters:

[Serge Rider DBeaver Wiki](https://github.com/serge-rider/dbeaver/wiki/Command-Line#connection-parameters)

The part that does not work at all is the "**-con**" parameter. If I specify more than one "**-con**" parameter then an error is displayed:

  _'driver' is not recognized as an internal or external command, operable program or batch file._

I write the DBeaver parameters like:

`C:\....> DBeaver.exe -con name="Test Connection"|driver="Microsoft Driver"|...`

It does not what parameters/parametersvalues I use. More than one parameter generate the above error message.

**Comment by serge-rider** [comment]
You can specify any number of connection in command line.
But you have to surround whole connection string with double quotes. 
Like `-con "name=Test Connection|driver=Microsoft Driver|..."`

**Comment by pdanie** [comment]
My bad it seems. When enclusing all **-con** parameters with a "-sign it works like a charm. Thank you.

What I was aiming at was to be able to specify **username**, **password** and **server adress** on a current configured connection, not creating a whole new connections that I currently get. See CASE #2389.
