### ISSUE TITLE
Bad insert into editor of text whith quotes

### ISSUE THREAD

**Issue by greenpeas** [serge-rider/dbeaver#2320]
4.2.2
postgresql

![image](https://user-images.githubusercontent.com/3856344/31488167-95890fb2-af45-11e7-8021-c98f010ba7b7.png)
After paste into editor:
![image](https://user-images.githubusercontent.com/3856344/31488215-b085e286-af45-11e7-84e3-33c8abbbda82.png)
But if copy without last quote:
![image](https://user-images.githubusercontent.com/3856344/31488280-ce26cdd2-af45-11e7-9fd7-44d1e8db80ef.png)
paste is norm:
![image](https://user-images.githubusercontent.com/3856344/31488294-dc66c7f8-af45-11e7-993f-d9466b5eaf30.png)
When copy one line:
![image](https://user-images.githubusercontent.com/3856344/31488330-036f106c-af46-11e7-83ec-2069714204bc.png)
all good
![image](https://user-images.githubusercontent.com/3856344/31488348-10b56d66-af46-11e7-879f-42de0a0ab0b1.png)

**Comment by serge-rider** [comment]
It is how auto-conversion of source code into SQL works. You can disable this feature in preferences: 
![image](https://user-images.githubusercontent.com/6398845/31516397-17ee890e-afa1-11e7-9dec-e4dc1ffd1a9d.png)
Or you can just execute `Undo` (<kbd>ctrl+z</kbd>) command after paste - this will revert source code conversion.
