### ISSUE TITLE
Autocomplete option is corrupted in informix

### ISSUE THREAD

**Issue by INGCRENGIFO** [serge-rider/dbeaver#2322]
Hello developers, since two versions, the autocomplete option in informix stopped working,
Now I want to autocomplete the names of the tables I have to write the schema first. Example: "informix.table_name" ()

The column names not autocomplete.

when I change database, the user interface is corrupted.
![image](https://user-images.githubusercontent.com/12200313/31516297-b36999c6-af5d-11e7-977a-535a8e295ce5.png)

Any solution?

**Comment by serge-rider** [comment]
Seems to be fixed in #2260 and/or #2261

**Comment by serge-rider** [comment]
UI issue is tracked in #2235
