### ISSUE TITLE
DBeaver - Sections resetting to default after each "Read data in SQL console" on a table.

### ISSUE THREAD

**Issue by nya13** [serge-rider/dbeaver#2323]
Hi,

Can we put an option to not have each new console/result screen be resized to default after each new console tab is opened?  For example, I resize the height of the SQL query box to be small and the rest of the space will be for  the console/result.  If there is an option to set to remember the size we last set, let me know.  Thank you.

**Comment by serge-rider** [comment]
Good point.
There is no such option - I'll add auto-save of results panel divider position in 4.2.3.
