### ISSUE TITLE
DBeaver not compatible with Java 9 

### ISSUE THREAD

**Issue by soycamiloypunto** [serge-rider/dbeaver#2325]
OS: Deepin 15.4.1 based Debian 8

Log adjunt

[log.txt](https://github.com/serge-rider/dbeaver/files/1380960/log.txt)

**Comment by serge-rider** [comment]
Generally DBeaver is compatible with Java 9 (as well as whole Eclipse platform). It runs ok on most platforms.
Please check #2247
What exactly DBeaver version do you use?
Does dbeaver.ini looks correctly in your case? (see correct one in #2247)

**Comment by serge-rider** [comment]
Looks like Java 9 compatibility settings were missed for MacOS and Linux versions.
Please check in 4.2.3 and reopen if problem persists.
