### ISSUE TITLE
Omit schema name in Generate SQL  

### ISSUE THREAD

**Issue by foal** [serge-rider/dbeaver#2327]
Add some preference to omit schema name in Generate SQL dialogs. It is possible in auto-complete and Export data, but not in "generate SQL"

**Comment by serge-rider** [comment]
Good point
![image](https://user-images.githubusercontent.com/6398845/31587973-e699dbba-b1f3-11e7-9293-eeb2ef6d86c0.png)

**Comment by foal** [comment]
I am sorry, but the same point in the preview dialog (persist changes).

![image](https://user-images.githubusercontent.com/458209/31610447-615bbe2a-b278-11e7-9bfd-a5141365930e.png)

**Comment by foal** [comment]
Not works for DDL generated SQLs

**Comment by foal** [comment]
![image](https://user-images.githubusercontent.com/458209/31663214-8dbc1784-b341-11e7-87e1-b2f4226ea192.png)

**Comment by serge-rider** [comment]
Thanks for noticing.
This will be improved in 4.2.4
