### ISSUE TITLE
SQL error with some bootstrap queries

### ISSUE THREAD

**Issue by shagr4th** [serge-rider/dbeaver#2328]
Hi, nice tool ! Juste one bug for me : Bootstrap queries are executed with a preparedstatement [(according to this)](https://github.com/serge-rider/dbeaver/blob/b4c4e1d4afb608a7c8fc11ca0721eef9ddda3dcf/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/AbstractExecutionContext.java#L96) but one of my init queries works only with a regular Statement (obtained with a createStatement() call).

`Caused by: org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error [2500] [42000]: Syntax error on line 1.  Last symbol read was: 'SET LOCKMODE'.
at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:189)`

Not sure about how to manage this kind of very specific case. Maybe manage a switch if the query starts with 'SET', 'ALTER', 'MODIFY', or some other session related commands...

**Comment by serge-rider** [comment]
This is actually a bug.  Bootstrap queries should be processed with createStatement().
Thanks for noticing.
