### ISSUE TITLE
Go to foreign key row with a shorcut

### ISSUE THREAD

**Issue by matheusmmo** [serge-rider/dbeaver#233]
Hi,

This is not a bug, I just started using dbeaver and really like it (using on Fedora 23). I wanted to know if there is a shortcut to go to a foreign row, I see that there is an icon for this. There is a shortcut that?

Thank you.

**Comment by serge-rider** [comment]
There is no such shortcut for now.
But I agree - it'll be helpful. I'll add a shortcut in the next version.

**Comment by serge-rider** [comment]
Link navigation shortcut will be ALT+SPACE.
History navigation shortcuts (backward/forward) will be ALT+LEFT and ALT+RIGHT.
