### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by ChristoforosKor** [serge-rider/dbeaver#2330]
How can I create database? 
Not a connection, create a database from scratch?

**Comment by filipemanuelofs** [comment]
Try `File -> New` and search for `Database Project`.

**Comment by serge-rider** [comment]
@ChristoforosKor it depends on database type.
For MySQL/MariaDB/PostgreSQL: right click on some existing database -> Create database.

**Comment by ChristoforosKor** [comment]
@filipemanuelofs I tried that but I don't see an option for creatign a new database
@serge-rider I am using mariaDB and there is not an option for creating a database by right clicking on a n existing one.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/31597819-2c89f0d8-b253-11e7-978b-83954f97a890.png)

Please check that you using the most recent version of DBeaver.

**Comment by oliverjanik** [comment]
Having "Create New Database" action in the context menu of an existing database makes zero sense. Why not place it in the context menu of the connection/server instead?

**Comment by serge-rider** [comment]
For MySQL "Create database" command is available when you click on "Databases".
In PostgreSQL there is no folder "Databases". Perhaps we should change navigator tree structure for PostgreSQL. Most of objects under each database are the same for all databases (except Schemas).
Could you create a feature request for that?

**Comment by aruprakshit** [comment]
So how should I create a new Database for projects, I don't see the option.

**Comment by aruprakshit** [comment]
I was trying to connect my locally installed mysql db. And then I am getting the error as I said above.

**Comment by raphatorres89** [comment]
are you using linux? if yes, use the Terminal to create...
$ mysql -u root -p
$ mysql> CREATE DATABASE name_of_database

then, connect with the dbeaver.
File > new > database connection > localhost:3306/name_of_database

**Comment by serge-rider** [comment]
@aruprakshit please post a bit more details. What exactly error do you see? Some screenshot would be helpful.

**Comment by aruprakshit** [comment]
@serge-rider  Look at the attached image.

<img width="1440" alt="screen shot 2018-09-29 at 1 43 17 pm" src="https://user-images.githubusercontent.com/3428463/46243093-bb30c080-c3ed-11e8-85c7-21aa8d0c12bb.png">

@raphatorres89  I am on MacOS. I can login via terminal.

```sh
Last login: Sat Sep 29 13:12:06 on console
~$ mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.12 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

**Comment by serge-rider** [comment]
@aruprakshit Well, this is not related to a database creation. 

Looks like you have incorrect connection configuration. Are you using SSL?
Probably you should add driver property "allowPublicKeyRetrieval" to "true".
Check this: https://stackoverflow.com/questions/50379839/connnection-java-mysql-public-key-retrieval-is-not-allowed

**Comment by aruprakshit** [comment]
@serge-rider It is not related to this issue I realised. I asked here, right after connecting to my existing DB i faced this error. But later, today I figured, once I connect to mysql from normal bash terminal, and then try to reconnect to the mysql DB, it works correctly. So there is an issue with this tool with mysql db server. I don't see the the error when I start mysql workbench FYI.

**Comment by maffe** [comment]
> In PostgreSQL there is no folder "Databases". Perhaps we should change navigator tree structure for PostgreSQL. Most of objects under each database are the same for all databases (except Schemas).
> Could you create a feature request for that?

#4935

**Comment by stefanos82** [comment]
Since this ticket is open I would like to ask: is it possible to give the option during dumping database to check whether the database exists or not?

On MySQL / MariaDB you can simply run: `CREATE DATABASE IF NOT EXISTS dbName;`.

I would like this line to be given as an option from `Tools > Dump database`.

It would make my life a lot easier to dump and restore any MySQL database without having to remind myself to first create the database name **and then** import it.

**Comment by Yuri-Predborskiy** [comment]
Still cannot use DBeaver to create a MySQL database within the application if no database exists. When I create MySQL connection, I have to explicitly state what database I am connecting to. If I didn't create a database yet, I can't connect.

Workaround is rather simple - connect to an existing database that you can access. In my case I had localhost with an existing "sys" database from the start, so I used that instead. That allowed me to connect to an "empty" server and create my database there.

**Comment by SpaceDux** [comment]
In order to show the option (via MySQL) to create a database via the gui, you must right click your connection, hover over "Connection View", then change to advanced. You'll then get the option.

**Comment by gnomeria** [comment]
> In order to show the option (via MySQL) to create a database via the gui, you must right click your connection, hover over "Connection View", then change to advanced. You'll then get the option.

Somehow it still not showing on mine. Other connections that I copied that it's based on, shown. :(

**Comment by daydr3am3r** [comment]
@gnomeria did you perhaps set the connection as read-only? You can check that by editing the connection (F4) > General > Read-only connection
