### ISSUE TITLE
JSON type columns don't appear

### ISSUE THREAD

**Issue by ntopulos** [serge-rider/dbeaver#2331]
I noticed that columns of **json** and **jsonb** types don't appear at all in the columns' list.

dbeaver version: 4.2.2

**Comment by Danlock** [comment]
Yea im using the EE version and its imposible to edit JSONB columns in postgres

**Comment by serge-rider** [comment]
Can't reproduce.
Perhaps this is the same issue as #2250 (i.e. json data type can't be resolved for some reason).
Could you post debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for investigation?

**Comment by serge-rider** [comment]
BTW what is your PostgreSQL server version?

**Comment by ntopulos** [comment]
The bug seems to have been fixed by the last update of dbeaver (v4.2.3).
**json** and **jsonb** types now both appear in the columns list.
