### ISSUE TITLE
Export Resultset hotkey ?

### ISSUE THREAD

**Issue by masebu** [serge-rider/dbeaver#2332]
Hi,

It seems the _Export Resultset_ command is not available for hotkey customization.
Am I not looking for the proper name or is it really not available ?
Would you add it ?

![image](https://user-images.githubusercontent.com/19706602/31555777-ab73e574-b042-11e7-9ef7-c74ca958def1.png)

![image](https://user-images.githubusercontent.com/19706602/31555639-1312f5c2-b042-11e7-9954-e0d11f080428.png)

Thanks,

**Comment by serge-rider** [comment]
Agreed, this should be a real customizable command.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/31588162-d24a2bee-b1f6-11e7-958a-89afe182998a.png)

**Comment by masebu** [comment]
Perfect, thanks.
