### ISSUE TITLE
DBeaver - Number values formatted in thousands by default.

### ISSUE THREAD

**Issue by nya13** [serge-rider/dbeaver#2334]
Hi,

Is there a setting that allows us to disable the thousands number formatting in our cells?

Ex.: My database value for cell X is 34567 and it is displayed as 34,567 in DBeaver.  I'd rather set it to show the raw value with no formatting.

Thank you!

**Comment by serge-rider** [comment]
You can change numbers/datetime formats in Preferences:
![image](https://user-images.githubusercontent.com/6398845/31574906-b284e804-b0e2-11e7-96e7-887f97a2beec.png)

**Comment by JoeCheez** [comment]
Because they significantly reorganized the  Preferences menu and I had to spend 10 minutes looking for it again.

![image](https://user-images.githubusercontent.com/24595138/48799235-3adf5b00-eccc-11e8-93aa-0925d93df3f3.png)

**Comment by potback** [comment]
> Because they significantly reorganized the Preferences menu and I had to spend 10 minutes looking for it again.
> 
> ![image](https://user-images.githubusercontent.com/24595138/48799322-6d895380-eccc-11e8-986c-a94b4452737d.png)

Just a tip: since the IDE is just eclipse in desguise, you can use the 'type filter text' box, type in 'data formats' and it will show you where the menu item is ;-)

**Comment by EskeRahn** [comment]
Things have been rearranged slightly again, so now "Editors" is one level higher up in the tree, so do not look for "Database".
![image](https://user-images.githubusercontent.com/24905467/104722418-122d4180-572e-11eb-9580-c99021bcc11c.png)

**Comment by chephei** [comment]
For dbeaver 7.3.0 on Linux
select in Type = number and unmark use grouping
![image](https://user-images.githubusercontent.com/31193948/109393519-fefebb80-7900-11eb-8518-1f22be1570a0.png)

**Comment by cies** [comment]
On DBeaver 21.1.3 (Linux) I did this: in `Window > Preferences > Editors > Data Editor > Data Formats` check the box for "Disable numeric formatting"

**Comment by kajdo** [comment]
![image](https://user-images.githubusercontent.com/8735942/153728109-feba2e42-793d-4be1-998f-6b3b5eff8788.png)

have a nice day from a german UI

**Comment by cloghin** [comment]
Is there a way to maintain the group separators in the TEXT version of the result set ? I see it in GRID, but then the TEXT tab does not show it. I use it to copy paste the entire result set with headers in a simple way.

**Comment by cloghin** [comment]
Answered my own question : change Value display format from Editable to Display(default)
