### ISSUE TITLE
Right-click context menu in results pane

### ISSUE THREAD

**Issue by x4C6565** [serge-rider/dbeaver#2336]
I am not getting the right-click context menu in the grid results for DBeaver after updating to 4.2.3.  It works in the "text" view of the results.

**Comment by x4C6565** [comment]
Apologies ... works now.

**Comment by serge-rider** [comment]
This is actually a bug. Context menu doesn't show in case of custom SQL queries.
Will be fixed as hotifx in 4.2.3, thanks for report.
