### ISSUE TITLE
"View script" button do nothing

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2337]
When I delete an object in Postgres the confirmation dialog appears and "View script" button doesn't work in it.

**Comment by serge-rider** [comment]
Can't reproduce. Does this happen with any object?
Please check debug/error log for any errors (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by offstate** [comment]
Yes, any object. Window blinks, but nothing happens. Nothing appears in log file.

**Comment by serge-rider** [comment]
What is your OS?

**Comment by offstate** [comment]
xubuntu 16.04

**Comment by serge-rider** [comment]
Please check this is 4.2.4. Reopen if it is still reproducible (and attach debug log just in case).
