### ISSUE TITLE
Unable to export resultset when in grid presentation

### ISSUE THREAD

**Issue by jackse7en** [serge-rider/dbeaver#2338]

**Comment by serge-rider** [comment]
Could you provide any details?
There is an issue with context menu and custom SQL queries. 
But it is not related to results export exactly.

**Comment by jackse7en** [comment]
Yes, I was unable to view context menu from resultset of custom queries under grid presentation.

**Comment by serge-rider** [comment]
Fixed.
You can re-download 4.2.3 again
