### ISSUE TITLE
[PostgreSQL] Partitioned Table not showing in Tree

### ISSUE THREAD

**Issue by andywicht** [serge-rider/dbeaver#2341]
A partitioned table using PostgreSQL 10 and the new table partitioning will not show in the tree under "Tables". Only the child tables appear there.

\dt+ mytable (parent-table) shows:

```
Partition key: LIST (mykey)
Partitions: myschema.child1 FOR VALUES IN ('AA'),
            myschema.child2 FOR VALUES IN ('BB'),
            myschema.child3 FOR VALUES IN ('CC'),
            myschema.child4 FOR VALUES IN ('DD')
```

dbeaver version: 4.2.3

**Comment by serge-rider** [comment]
Partitions and child tables are now organized in hierarchy (see it in 4.3).
