### ISSUE TITLE
Problem with result viewer's focus management

### ISSUE THREAD

**Issue by N3kOnScreeps** [serge-rider/dbeaver#2343]
Hi, 

I updated DBeaver, now the result panel seems to have focus problems : 
 - I can't right click on it
 - when I use tabulation in the script editor, the result panel switch from "table" to "record" and the script editor don't indent my code

> Windows 7 SP1 64bit
> java 1.8.0_131-b11
> DBeaver 4.2.3

**Comment by andywicht** [comment]
+1
same problem here after update

**Comment by N3kOnScreeps** [comment]
There is a console error for the right click in the result window
[log](https://pasteboard.co/GPaVOGf.png)

**Comment by serge-rider** [comment]
This was fixed as a hotfix. You can re-download 4.2.3 form jkiss.org or github (https://github.com/serge-rider/dbeaver/releases/tag/4.2.3)

**Comment by N3kOnScreeps** [comment]
Great work, thanks ! ;-)
