### ISSUE TITLE
[Oracle] Can not edit Number value

### ISSUE THREAD

**Issue by fayca121** [serge-rider/dbeaver#2344]
Hi,
I've tried to edit a cell value directly from editor, but I've not been able to change it with toolbar

![2017-10-16 10_15_56-dbeaver 4 2 3 - _cbiot_ script-3](https://user-images.githubusercontent.com/547548/31604808-5cdf78d0-b25c-11e7-823f-51320ef75a5c.png)

, is that an issue?

Oracle 11g
Dbeaver 4.2.3
Java 8
Windows 7 x64

**Comment by fayca121** [comment]
I'd just add that the problem doesn't occur for some Numbers fields as  shown below

![2017-10-17 11_31_55-alerte sur le bureau](https://user-images.githubusercontent.com/547548/31660397-315efdec-b32f-11e7-94a4-80e8e54afdc0.png)

**Comment by serge-rider** [comment]
DBeaver can't edit cells if it can't determine column source. 
E.g. if cell is a result of expression or DBeaver can't find source table.

**Comment by fayca121** [comment]
I created a sample table with 2 columns

CREATE TABLE sample_table ("a" NUMBER, 
	"b" FLOAT(126));

I made an insert

INSERT INTO sample_table VALUES (124,2017.0);

I tried to edit the values

for the first column I could edit the value but for the 2nd it wasn't possible.

![2017_10_18_09_58_28_a](https://user-images.githubusercontent.com/547548/31709954-8361d800-b3eb-11e7-916d-00c7248313a6.png)

**Comment by serge-rider** [comment]
It is a bug in the recent version.
Thanks for detailed report.
