### ISSUE TITLE
Error on Calculate total row count

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2346]
After a query execution I press the button Calculate total row count and receive an error
"Error executing row count"

(Yes, the query is big and complex :)

[log.txt](https://github.com/serge-rider/dbeaver/files/1387086/log.txt)

**Comment by carlosspohr** [comment]
Hi @offstate,

I tested it here and had not problem on it. I think may your complex query is breaking some kind of parser of dbeaver.

Could you post this query ?

**Comment by offstate** [comment]
```
WITH
            rival as (
                SELECT o.product_id as id,p.rgroup_id, pr.id prov_id, prc.price, prc.ts::date
                from rival.price prc
                join rival.offer o on prc.offer_id=o.id
                join rival.provider pr on pr.id=prc.provider_id
                left join product.product_summary p on p.id=o.product_id
                where prc.provider_id in (1,4) --and p.rgroup_id in (2620)
            ),
            our as (
                select gp.id,p.rgroup_id, 0 prov_id, pr.price, null::date as ts
                from goods.product gp
                join rival.price_mx pr on gp.id=pr.id
                left join product.product_summary p on p.id=gp.id
                --where  p.rgroup_id in (2620)
            ),
            prods as (
                select * from rival
                union all
                select * from our
            ),
            oems AS (
                select distinct pr.id, p.rgroup_id, case when genuine is null then null
                        else (array_remove(r.rel, pr.id))[1] end rel_id, b.id as brand_id_gen,prov_id, price, pr.ts, null as note
                FROM prods pr
                left join product.product_rel r on r.rel @> array[pr.id]  and r.rate>=3 --(in_rate is null or r.rate>=in_rate)
                  left JOIN product.product_summary p ON p.id != pr.id and  p.id=any(r.rel) and p.rgroup_id=pr.rgroup_id
                  left JOIN product.brand b ON b.id = p.brand_id AND genuine = TRUE
            ),
            orv as (
                select  o1.id,array_agg(o1.rel_id) rel_ids, max(o1.rgroup_id) rgroup_id,max(o1.brand_id_gen) brand_id_gen
                from (select id,rel_id, rgroup_id,brand_id_gen from oems where prov_id>0 and rel_id is not null) o1
                left join (select  id,rel_id, rgroup_id from oems where prov_id=0) o2 on o1.rel_id=o2.rel_id
                where o2.id is null
                group by o1.id
            ),
            oems2 as (
                select distinct our.id, our.rgroup_id, unnest(orv.rel_ids),orv.brand_id_gen, our.prov_id, our.price, our.ts, 'generated'::text
                from orv
                join product.product_rel r on r.rel @>array[orv.id] and rate>=3
                join our on our.id=any(r.rel) and our.id != orv.id and our.rgroup_id=orv.rgroup_id
            ),
            oems3 as (
                    select * from oems where rel_id is not null
                    union
                    select * from oems2
            ),
            uq_oems as (
                select rel_id
                from (select distinct prov_id, rel_id from oems3) t
                group by rel_id
                having count(rel_id)=1
            ),
            totals as (
                select rgroup_id,brand_id_gen, count(distinct o.id) as co_cross,
                       count(distinct o.rel_id) as co_gen
                from oems3 o
                group by rgroup_id,brand_id_gen
            )
select  1 some_columns
from oems3 o
    JOIN product.product_summary ps on ps.id=o.rel_id
    JOIN product.product_summary psc on psc.id=o.id
    left join uq_oems uq on o.rel_id=uq.rel_id
    join totals tot on tot.rgroup_id=o.rgroup_id and tot.brand_id_gen=o.brand_id_gen
group by ps.rgroup_name, ps.brand_name,ps.brand_id, ps.rgroup_id, prov_id,tot.co_gen,tot.co_cross
order by ps.rgroup_id, ps.brand_id
```

**Comment by serge-rider** [comment]
Wow.
DBeaver uses JSQLParser for queries modification. This library doesn't support some database-specific features.
I'm afraid I can't fix this issue right now.

**Comment by offstate** [comment]
You can
`select count(*) from ( <origin_query>) t`
without any parsing

**Comment by carlosspohr** [comment]
Yep @offstate, 

I forgot to post this snippet to make a simple count over any sql. I'm not sure about of all others databases supported, but this one will work as expected.

**Comment by serge-rider** [comment]
Agreed. We'll use nested select query if direct query transformation will fail (not that some databases do not support or limit functionality of nested selects - so we can't use this approach as default one).

**Comment by offstate** [comment]
I got strange result on a simple query. After I fetched all rows, row count field show 3117 rows, but after I pressed the refresh button it show 65! 

![default](https://user-images.githubusercontent.com/16996529/32637411-59c33ff8-c605-11e7-9c79-10facb6afb7c.png)

**Comment by offstate** [comment]
I got an error for the following query
```
select *
from dlvr2.route 
where info ?| array['quick','optimal','cheap']
```

[log.txt](https://github.com/serge-rider/dbeaver/files/1465279/log.txt)

**Comment by serge-rider** [comment]
@offstate Was this resolved in 4.2.5? In any case you can see actual COUNT query in query manager view. Is it correct?

In regards to query wrapping (which is now used by default by DBeaver).
It doesn't work in SQL Server/Sybase if original query has unnamed columns (constants and expressions without explicit column name). For instance `SELECT 123`.

**Comment by offstate** [comment]
I can see the count query and it is correct, but DBeaver cannot execute it.

![default](https://user-images.githubusercontent.com/16996529/32996860-4fba2ce8-cdd4-11e7-843e-6a002b762749.png)

First I execute the original query next I pressed the "Calculate ..." button an got the error and then I copied the COUNT query from the log and it done successfully.

**Comment by serge-rider** [comment]
This is because of question mark in the query. DBeaver thinks it is  a parameter binding.
You can disable anonymous parameters at all or redefine the mark in SQL Editor preferences:
![image](https://user-images.githubusercontent.com/6398845/33003688-50772cb4-cdcd-11e7-9367-d76c6aa24827.png)

**Comment by offstate** [comment]
The option "Anonymois SQL parameters" is not checked and when I execute the query, parameter request window doesn't appear. 
Moreover, the error occurs regardless of which character I set there.

**Comment by serge-rider** [comment]
Interesting.
I can't reproduce this.

What is your database and client driver?

**Comment by offstate** [comment]
Postgres 9.5, debian
client xubuntu

![default](https://user-images.githubusercontent.com/16996529/33017681-f6525426-ce3e-11e7-974f-e65c4b4e1358.png)
