### ISSUE TITLE
Bugs with shortcuts and keys in DBeaver 4.2.3

### ISSUE THREAD

**Issue by AlexandraKashnikova** [serge-rider/dbeaver#2347]
Downloaded 4.2.3 this morning and found bugs in using keys during working with the Result-panel
e.g. can't use Tab button in working panel (as a simple Tub), the right button of the mouse doesn't work when I push on the result table to export data and so on -  a lot of bugs

**Comment by serge-rider** [comment]
Both these bugs (tab key #2339 + results context menu #2338) were fixed in hotfix version. 
Just re-download 4.2.3 from jkiss.org or github.

**Comment by serge-rider** [comment]
If you see any other new bugs in 4.2.3 - please report them separately.
