### ISSUE TITLE
Active Catalog/schema list not working

### ISSUE THREAD

**Issue by Nope7** [serge-rider/dbeaver#2348]
Downloaded today 4.2.3 . I checked the new "Chose catalog" feature, the one used to choose the working schema for query editor that on previous version was a drop-down list and now is a popup grid. 

I found that it's not working for every connection type.

 For example, it perfectly lists all the schema on a SQL Server connection type but it's not working at all (empty list) on iSeries DB2 AS400 (and it was working on all the previous versions).

Thanks

**Comment by serge-rider** [comment]
Do you see at least current schema name for DB2/iSeries?
Could you post a screenshot with this error?

**Comment by carlosspohr** [comment]
Hi @serge-rider ,

It also affected for MySQL databases, after upgrade here I got this error to (empty list):

![image](https://user-images.githubusercontent.com/637767/31631232-e0eee850-b297-11e7-8825-e576de51b5e5.png)

**PS:** I didn't fill default active database in my connection, then, this combo always returns empty. So after I use database explorer and activate manually, this database combo is filled.

Connections that have default database filled, it's working normally.

**Comment by serge-rider** [comment]
This happens if there is no active schema in connection.
You can change it in database navigator and this will fix schema selector in popup dialog.
Thanks for report.

**Comment by Nope7** [comment]
The solution you provided worked perfectly.

Thank you serge-rider

**Comment by carlosspohr** [comment]
Thanks @serge-rider

**Comment by mikkk3l** [comment]
Hi, Serge:
Thanks  for your big help to everyone.
I use DBeaver 6.0.1 and I connect correctly to DB2 11 via db2jcc.jar

From 6.0.2 I no longer see the schema chosen in Connection settings / Initialization in the dropdown menu referred in this issue.
![image](https://user-images.githubusercontent.com/15341836/57437175-86b59a80-7241-11e9-8dcb-6a7e3a1abbaf.png)
![image](https://user-images.githubusercontent.com/15341836/57437210-946b2000-7241-11e9-8feb-ca1d5651efa2.png)

Can you explain me what I should do? I don't understand how to perform your workaroun.

Thank you very much. Cheers.
