### ISSUE TITLE
mariadb: Proxy privileges not displayd

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#235]
When set Proxy privileges from mariadb cli dbeaver not display this privileges. I think this happens because dbeaver use wrong syntax with dot (GRANT PROXY ON _._) when check Proxy privileges.

**Comment by serge-rider** [comment]
Is this still makes sense?
Currently DBeaver doesn't show PROXY privilege settings because they are different (proxy is user-specific options while other privileges are object-specific). I'm not quite sure how to show this is UI and whether we really need this.

**Comment by infectormp** [comment]
I think this is not make sense alredy
