### ISSUE TITLE
Switch back to query editor

### ISSUE THREAD

**Issue by Taariqq** [serge-rider/dbeaver#2357]
Hi guys, 

While in query editor, when I hit Tab it takes me to results pane. How do I switch back to the query editor? Ctrl-F6 seems a little cumbersome if you have more than one tab open.

Edit: I am on Linux Mint and have Emacs keys enabled.

**Comment by serge-rider** [comment]
This is an bug (see #2339) and it was fixed in DBeaver 4.2.3 hotfix release. 
Try to re-download dbeaver from jkiss.org or GitHub.
