### ISSUE TITLE
[Postgres] DB reconnect not working

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2358]
I suspend my laptop with dbeaver opened and remote DB connected. Next when I wake it up and try to access db objects I receive an error:  This connection has been closed.

![default](https://user-images.githubusercontent.com/16996529/31695531-8f85f1a4-b3ee-11e7-9c59-3165656e7061.png) 
_(Details not informative)_

Then I press Invalidate/Reconnect and this has no effect.
Disconnect+Connect helps

**Comment by berkinger** [comment]
I have the same problem.

**Comment by serge-rider** [comment]
I've fixed a couple of related issues but not sure that this exactly issue was resolved.
If it is still reproducible in 4.2.4 - please reopen and post error stacktrace (you can get it in Error Log view or in log files: https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by serge-rider** [comment]
Eventually I've reproduced that.
See fix in 4.2.5.
