### ISSUE TITLE
[hsqldb] Invalid DDL Generation

### ISSUE THREAD

**Issue by montehansen** [serge-rider/dbeaver#2359]
Using v4.2.2. The ddl generation of tables that contain default values produces incorrect. This appears to be consistent in various places where ddl is created for tables. 

CREATE TABLE PUBLIC."SESSION" (
	ID BINARY NOT NULL DEFAULT X'00000000000000000000000000000000',
	ENTITYID BINARY NOT NULL,
	CREATEDON DATE DEFAULT CURRENT_DATE,
	ACCESSEDON DATE DEFAULT CURRENT_DATE,
	CONSTRAINT SESSION_PK PRIMARY KEY (ID),
	CONSTRAINT SESSION_PROPRIETOR_FK FOREIGN KEY (PROPRIETORID) REFERENCES PUBLIC.PROPRIETOR(ID)
) ;

Expected behaviors:

1. Output the default specifier before the constraint like so:
	ID BINARY DEFAULT X'00000000000000000000000000000000' NOT NULL
2. Output the length for types such as BINARY, VARBINARY, VARCHAR, etc:
	SESSIONID BINARY(16) NOT NULL

Hope this helps, and thanks for publishing this tool!

**Comment by serge-rider** [comment]
Yes, it is a bug in DDL generator. Thanks for report

**Comment by montehansen** [comment]
My pleasure to help. Thanks for the great tool.
