### ISSUE TITLE
ERROR: Unsupported startup parameter: extra_float_digits

### ISSUE THREAD

**Issue by ilnurgi** [serge-rider/dbeaver#2361]
whats wrong? 

![image](https://user-images.githubusercontent.com/2868558/31703468-55b6efb8-b3e5-11e7-9a63-cb515b838a24.png)

**Comment by serge-rider** [comment]
Looks like some PG config specific to your local env. Perhaps it is somehow related to pgbouncer.
In any case DBeaver doesn't add any such parameters.

Check this: 
https://edwin.baculsoft.com/2016/05/weird-exception-unsupported-startup-parameter-extra_float_digits-when-connecting-to-postgresql/
http://lists.pgfoundry.org/pipermail/pgbouncer-general/2008-November/000301.html

**Comment by lansman** [comment]
I had such error on my production server (dev and test were OK) when specified wrong port and wrong database (i forgot to change it from default _postgres_ in connection settings)

**Comment by allanlewis** [comment]
I think the correct way to resolve this is to uncomment this option in `pgbouncer.ini`:
```ini
;
; Comma-separated list of parameters to ignore when given
; in startup packet.  Newer JDBC versions require the
; extra_float_digits here.
;
;ignore_startup_parameters = extra_float_digits
```

**Comment by rosshadden** [comment]
I don't understand where to change this when using dbeaver with a remote database. I have searched my entire filesystem for a `pgbouncer.ini` but there is none. I don't have postgres installed or running locally because as I said I'm working with remote databases. Sites like the ones linked above say to find the location of the file by looking at running processes, but... well you get the idea.

How can I make dbeaver work with a postgresql database running on GCP when it gives me this `extra_float_digits` error?

**Comment by command0r** [comment]
@rosshadden, you won't find ```pgbouncer.ini``` unless you have pgBouncer installed locally or in the container (or a VM) you can access. pgBouncer can normally be deployed on a separate VM that works as a proxy between the Postgres instance and the client or in a Docker container (as a sidecar). 
In your case, to fix the issue, you have to implement this parameter on the server side (in GCP). I don't use GCP currently, so, can't suggest to you where to find configuration parameters. However, in Azure, you'd find it in Server Parameters:
![postgres](https://user-images.githubusercontent.com/13084816/179060227-4658107d-ed19-47f7-b8cb-9d87163ba969.png)
That said, you have to have access to a GCP console to perform this action.
Once introduced (and the server restarted), it works like a charm. I was able to connect to port 6432 (pgBouncer) via DBeaver, which I use as well as a client.

**Comment by jbdesbas** [comment]
I had the same issue. I got around the problem by installing a local pg_bouncer.

`client --> pgbouncer (local) --> pgbouncer (remote) --> database` :heavy_check_mark: 

On the **local** `pgbouncer.ini` I applied the @allanlewis tricks https://github.com/dbeaver/dbeaver/issues/2361#issuecomment-603223985

pgbouncer is quite simple to config, see https://www.pgbouncer.org/usage.html#quick-start or https://doc.ubuntu-fr.org/pgbouncer

**Comment by ngraef** [comment]
[PgJDBC v42.7.5](https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.5) no longer sets the `extra_float_digits` parameter at startup for PostgreSQL >= 12:

> feat: don't force send extra_float_digits for PostgreSQL >= 12 (https://github.com/pgjdbc/pgjdbc/issues/3432) (https://github.com/pgjdbc/pgjdbc/pull/3446)

Updating the driver in DBeaver should fix this and make it usable for folks who can't change the PgBouncer configuration.

**Comment by scimad** [comment]
Thanks @ngraef . Works. 

Had the same issue, pgbouncer used on server side and didn't / couldn't touch on the server setup. Update did the job. 

To save someone's time to update the driver, here's how (I managed) to do it:
>> Database (on Menu Bar) >> Driver Manager >> (Select) PostgresQL >> (I made a) Copy (using the 'Copy Button) >> Libraries >> org.postgresql:postgresql::RELEASE [your version] >> Edit ... >> Set the version to `42.7.6` 

And it works for me.


![Image](https://github.com/user-attachments/assets/e004be8b-adfb-41c2-9aef-e096673e9e58)
