### ISSUE TITLE
Choose catalog/schema modal is always empty

### ISSUE THREAD

**Issue by psygnoser** [serge-rider/dbeaver#2362]
I just upgraded to v4.2.3 CE. When I open a SQL editor and try to click on 'Active catalog/schema' to select the database to use for querying, the 'Choose catalog/schema' modal that opens is always empty. I have several MySQL and Redshift connection and it doesn't work on any of them.

**Comment by serge-rider** [comment]
Duplicate of #2348. See fix in 4.2.4.
See #2348 comments for workaround.
