### ISSUE TITLE
Bugs in version 4.2.3

### ISSUE THREAD

**Issue by Apcio** [serge-rider/dbeaver#2363]
After Update to 4.2.3 I noticed:
- Tab key change to result view instead input tabulator character into SQL Editor
- In result view I can't open popup menu for export wizard

I couldn't find post with that bugs, so this could be doubled, sorry for that.

//edit
I know why I couldn't open popup menu - after save SQL in menu SQL Editor -> Save SQL script popup menu is disabled. Run the same SQL in another SQL Editor allow popup menu for show and export results

**Comment by serge-rider** [comment]
Duplicate of #2347 (both these bugs were resolved in hotfix version, just re-download 4.2.3)
