### ISSUE TITLE
Using the ppa version (latest?) it stops working

### ISSUE THREAD

**Issue by y2josei** [serge-rider/dbeaver#2364]
I am not sure this is a ppa problem. But as this is new I think is good to be promted
I have just uninstalled dbeaver and install the ppa version, I am getting this error when executing it:

```
JVM terminated. Exit code=1
/usr/bin/java
--add-modules=ALL-SYSTEM
-Duser.language=en
-Xms64m
-Xmx1024m
-jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /usr/share/dbeaver/dbeaver
-name Dbeaver
--launcher.library /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.550.v20170928-1359/eclipse_1629.so
-startup /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.overrideVmargs
-exitdata 7f98005
-vm /usr/bin/java
-vmargs
--add-modules=ALL-SYSTEM
-Duser.language=en
-Xms64m
-Xmx1024m
-jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar 
```

**Comment by y2josei** [comment]
Ubuntu 16.04 with openjkd 9

**Comment by hey-sancho** [comment]
Hello, I was having the same issue as @y2josei with freshly installed .deb from the website
Aside to message box with text above, this was printed into the console: 
```
Unrecognized option: --add-modules=ALL-SYSTEM
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
I was able to start dbeaver after these steps:
1. Open `/usr/share/dbeaver/dbeaver.ini`
2. Remove `--add-modules=ALL-SYSTEM` line & save
3. Start dbeaver normally

My OS/Java info:
```
$ lsb_release -d
Description:	Ubuntu 16.04.3 LTS

$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```
Thanks!

**Comment by serge-rider** [comment]
Looks like you are using very odd Java 9 version (very old Early Access which doesn't support modules).

I'll add `-XX:+IgnoreUnrecognizedVMOptions` option to dbeaver.ini - this should help on most JVMs (including OpenJDK). However not on 100% of them.

**Comment by y2josei** [comment]
Thank you for your help. Finally using official java from oracle did the trick
