### ISSUE TITLE
Add EVENT privilege for MySQL

### ISSUE THREAD

**Issue by MurKit** [serge-rider/dbeaver#2365]
EVENT privilege is required for Magento 2 for example.
So I have to manually grant it in command line. 
Is it possible to add this privilege to Dbeaver?

[Magento\Setup\Exception]                                                                             
  Database user does not have enough privileges. Please make sure SELECT, INSERT, UPDATE, DELETE, CREA  
  TE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW  
   VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER privileges are granted to table 'db'.

**Comment by serge-rider** [comment]
In MySQL user editor:
![image](https://user-images.githubusercontent.com/6398845/32693700-474a0244-c740-11e7-8602-322a2cc248f3.png)

**Comment by MurKit** [comment]
Thanks for adding this feature, but you could get even more specific. 
It can be done like this:
GRANT EVENT ON db.* TO 'dbuser'@'%';
FLUSH PRIVILEGES;
