### ISSUE TITLE
Tab key in sql editor switches to result set view

### ISSUE THREAD

**Issue by GavinHardie** [serge-rider/dbeaver#2366]
Using version 4.2.3, when I press Tab to indent code this switches focus to the result set and then toggles the record/grid view.

Seems pretty much exactly what this forum post describes

https://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1216&p=2748&hilit=tab+result+view#p2748

**Comment by serge-rider** [comment]
Duplicate of #2339. See comments for workaround.
