### ISSUE TITLE
Unable to see postgre databases on dbeaver 3.6.0

### ISSUE THREAD

**Issue by hfantin** [serge-rider/dbeaver#237]
After update from version 3.5.9, I can't see the postgre databases.
In the latest version, he shows the list of databases:
![dbeaver-pg-3 5 9](https://cloud.githubusercontent.com/assets/12260243/13333946/28125646-dbe8-11e5-86a9-1402cb066a36.png)
And after update to 3.6.0, the list becomes strange, see the image below:

![dbeaver-pg-3 6 0](https://cloud.githubusercontent.com/assets/12260243/13333963/4107b114-dbe8-11e5-8d77-1d4f46c05034.png)

**Comment by serge-rider** [comment]
By default 3.6.0  shows all available databases. It may lead to problems if you have too many databases.
In the next version I'll change default UI bahavior - all databases except default one will be hidden.

**Comment by thiagofernando** [comment]
same problem here. Public is not showed and a lot of garbage like this picture is showed.

**Comment by hfantin** [comment]
I tried to filter by databases, but I can't find "public".
I don't know what is this random databases, they are not showed in last version, 
maybe it's a bug.

**Comment by serge-rider** [comment]
It is not a garbage - it is a database name list. You seems to be using some huge shared PG server.
You can find your database there (it has the same name as in connection properties) and you will see public schema inside.

**Comment by thiagofernando** [comment]
Thanks again Serge, as use a free service (https://www.elephantsql.com), it should be returning a shared basis by all users. I will filter only mine.
