### ISSUE TITLE
SELECT DATABASE

### ISSUE THREAD

**Issue by Mateozmaldonado17** [serge-rider/dbeaver#2394]
WHEN I WANNA EXECUTE A QUERY DBEAVER SHOWME AN ERROR AND THE REASON IS "NO DATABASE SELECTED" OK SO I MAKE A CLICK IN "<NONE>" AND THIS SHOWME A WINDOW WITH TITLE "Choose catalog/schema" with a list in blank, i dont understand

**Comment by serge-rider** [comment]
It is a bug in 4.2.3 (see #2348)
Workaround: use database navigator:
![image](https://user-images.githubusercontent.com/6398845/31853540-d96d901e-b692-11e7-9050-76323a4d9da3.png)

**Comment by serge-rider** [comment]
Another workaround: specify database name in connection properties.
