### ISSUE TITLE
Is it possible to display VARCHAR as binary (e.g. HEX)

### ISSUE THREAD

**Issue by MarkusMayer** [serge-rider/dbeaver#2396]
Hi,
in our legacy schema we have VARCHAR columns containg binary information. Is it possible to display a specific VARCHAR column as binary? For example by right clicking on a column in the result pane and tell dBeaver to format as binary (e.g. View/Format -> View as -> Binary).

Thanks for the great tool!
Bye,
Markus

**Comment by serge-rider** [comment]
This is possible with column transformers.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/32688793-a34729b2-c6e8-11e7-8dfe-3a676f923a99.png)

![image](https://user-images.githubusercontent.com/6398845/32688785-8c7e2082-c6e8-11e7-9f3e-0e7074a9e011.png)

Also you can open value editor (<kbd>shift+enter</kbd>) and switch to hex editor.
