### ISSUE TITLE
database dropdown selector popup a new window

### ISSUE THREAD

**Issue by collicalex** [serge-rider/dbeaver#2398]
In button toolbar, the datasource selector and catalog selector, display a popup window instead of a popup dropdown list.

version 4.2.3

It didn't happen in older versions.

**Comment by giulianoformatodc** [comment]
In addition, this new window is showing an empty list while I expected more than one schema.

![image](https://user-images.githubusercontent.com/30623481/32107052-c6a2b5c8-bb2d-11e7-8f0f-c1b3ac99f411.png)

**Comment by serge-rider** [comment]
Popup dialog is a feature (fancy dropdown was too buggy and also dialog provides more infromation).
Problem with empty list is a bug (#2348) and will be fixed in the next version.

**Comment by collicalex** [comment]
Hmm.. dialog provides more information? Example?
For me it's exactly the same as the dropdown list... but in a new, so borring, popup dialog!

It must be exactly the same... a popup dialog or a popup selection list must provide the same code to fill the body content. So I do not understand your point.


There is no way to choose which "feature" we want? Popup dialog or dropdown list?

**Comment by serge-rider** [comment]
Yes. 
Schema list has multiple columns with additional schema info.
Also database (connection) list isn't a simple list but a hierarchical tree.
Also there are checkboxes for database list filtering ("show only connected", "only in current project", maybe something else in future releases). 

There was a batch of feature requests for dropdown lists improvements/fixes. 
So for me it looks like the feature people want.

**Comment by serge-rider** [comment]
1. Datasouces can be organized with folders. This means any number of levels of depth (yep, some people have hundreds and thousands of connections). Having multiple options in dropdown also doesn't sound ok.
2. It has to be consistent with 1.

I can make it non-modal (usually it is more ergonomic).

**Comment by collicalex** [comment]
You can make it non modal,
and then be included in the left panel...
So exactly as the "Database Navigator" panel... 

And it look like a joke said as it... but in fact no, it will be more ergonomic than a popup modal dialog. But it will be less ergonomic than the drop down list...

**Comment by serge-rider** [comment]
You already can use database navigator for that (<kbd>ctrl+shift+.</kbd> sets editor connection from current navigator selection). 

Anyhow - simple dropdown list doesn't work in case of big number of connections.
And non-modal dialog which hides if you click outside of it isn't the same as pinned view..

**Comment by collicalex** [comment]
ctrl shift dot 
do nothing here (in AZERTY mapping)

I've tried ctrl dot (because I already have to hit shift key to access to dot one)

Whatever, I have to navigate (with mouse) in the treelist to select one DB (not active, not in bold) and then hit the ctrl shift dot  (or right click and select "set active")?? Still not really ergonomic...



BUT

It work only when selecting another SCHEMA from the same datasource... else there is no "set active" option.
With the dropdown selection list, we can change the current SQL editor to "work" on another datasource and then to another schema. Here we can't :/

**Comment by serge-rider** [comment]
1. You can redefine any shortcuts (it is command `Set connection from navigator` and it is in the main toolbar).
2. See further enhancements of connection/schema selectors in 4.2.5 (modeless dialog, shortcuts, extra config, etc).
3. I still don't understand why you can't change datasource/schema in new UI

**Comment by collicalex** [comment]
Yes I can, but it just not ergonomic as a dropdown selection list.

In fact I just see that I can resize and put the modal dialog just behind the "input v" boxes... and it still appear at the same place/size even after restart the app. So it's closely look like to a dropdown selection list...
