### ISSUE TITLE
ADD command line option: autoanswer Ignore to "Can't lock workspace"

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2399]
## use case

I use multiple instances of DBeavers with the same workspace, which I run with a keyboard shortcut (often in a hurry).
I am already using the command line parameters  -closeTabs and -disconnectAll to get a sanitized workspace, but I have to manually click the "Ignore" option every time the "Can't lock workspace" error comes up when starting up:

	Can't lock workspace at /home/allan/.dbeaver4.
	It seems that you have another DBeaver instance running.
	You may ignore it and work without lock but it is recommended to shutdown previous instance otherwise you may corrupt workspace data.

## solution

a command line option to automatically ignore that error and continue starting DBeaver (to use at my own peril)

**Comment by serge-rider** [comment]
That's easy.
New CLI option: `-reuseWorkspace`

**Comment by allanlaal** [comment]
will it become available in 4.2.4 ?

**Comment by serge-rider** [comment]
Yep
