### ISSUE TITLE
Can't create a new view.

### ISSUE THREAD

**Issue by Mateozmaldonado17** [serge-rider/dbeaver#2400]
when i try create a new view i get this 
![screenshot_1](https://user-images.githubusercontent.com/5784157/31894827-1c24c434-b7d5-11e7-8463-6f4140882d90.jpg)
![screenshot_2](https://user-images.githubusercontent.com/5784157/31894829-1d7b032a-b7d5-11e7-97f3-ed83ad53eacc.jpg)

**Comment by serge-rider** [comment]
It is a bug in 4.2.3.
Thanks for report.
