### ISSUE TITLE
SQL phrase in Oracle session manager

### ISSUE THREAD

**Issue by danieleangellotti** [serge-rider/dbeaver#2405]
Hi Serge,
using DBeaver (4.2.3 CE) with an Oracle connection, when I select a session in Administer > Session I can see just an uncomplete SQL phrase, as if I selected SQL_TEXT column (instead of SQL_FULLTEXT) in V$SQL: this issue is negligible for small queries.

Thanks.

**Comment by serge-rider** [comment]
Yep, you are right.
We should use SQL_FULLTEXT.
