### ISSUE TITLE
[Postgres] Unwanted search in Edit column attributes

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2409]
I create new column. In attributes dialog I put cursor into Data type field and want to overwrite its value with my own.
But quick search input box appears ((

![default](https://user-images.githubusercontent.com/16996529/31987723-0fc595ec-b9b0-11e7-88cb-a632df781246.png)

Also when I type some letters of a data type and drop down box shows me  filtered variants, then I select one using mouse and I get an error.
![default](https://user-images.githubusercontent.com/16996529/31988229-b76aa782-b9b1-11e7-9c00-87d468303ff5.png)
![default](https://user-images.githubusercontent.com/16996529/31988234-bcfc8da0-b9b1-11e7-91d2-a959f1e8c288.png)

**Comment by serge-rider** [comment]
Agreed. Too smart auto-completion in inline editors just doesn't work properly. I'll disable it.
