### ISSUE TITLE
[Feature Request] Associate SQL editor with different project.

### ISSUE THREAD

**Issue by prog-rajkamal** [serge-rider/dbeaver#2410]
## Problem

I want to use a SQL connection present in different project. However those db connections are not available as options

## Probable cause

It seems when a text editor is opened. It is linked with _currently active project_. 
When we try to change datasource of a text editor, DBeaver only search for connectiosn present in associated project. 

Hence, Active connections in other projects are ignored. 

I am not sure why this is the default behavior. However an option to change active project, would be very helpful.

**Comment by serge-rider** [comment]
There is a an option to change active project (in Project Explorer view). However it won't let you to set script conenction from another project.
This feature will be added in the next version:
![image](https://user-images.githubusercontent.com/6398845/32286865-eaa3616e-bf3f-11e7-9ed8-7ac495419056.png)
