### ISSUE TITLE
read-only connection, cannot do a select in custom query

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2413]
I've set a connection read-only. I cannot set the database active nor use custom scripts. I only want to make a select. Is it a bug or a feature?

**Comment by serge-rider** [comment]
Mostly it depends on driver implementation.
- What is your database?
- What actual error do you see?

**Comment by sirber** [comment]
DB is MySQL 5.7. I don't have the exact error notice, but it resolved when I removed read-only flag.

**Comment by serge-rider** [comment]
This is behavior of recent MySQL driver. I think they restrict anything but SELECT queries when you mark connection as read-only.
In order to set active database you can specify it in connection properties dialog.

**Comment by sirber** [comment]
I couldn't even do a select query...

**Comment by serge-rider** [comment]
Well. For non-select queries I see errors like this:
![image](https://user-images.githubusercontent.com/6398845/32310353-b119a788-bfa2-11e7-9b35-709f90e42215.png)
But selects are working. 
Do you see some other error?
With what kind of select queries?

**Comment by sirber** [comment]
I get the popup if I right-click a database -> set active.

I don't get the popup if I add the database name in the custom select query. I never use the database name in queries, always use "set active". I don't know / cannot reproduce the second error.

**Comment by serge-rider** [comment]
"set active" is not a select query. You can't use it in read-only mode (this is MySQL driver limitation and I can't fix this).
Workaround: use database name in connection properties (this database will be active by default).
If you have multiple databases - create multiple copies of this connectiton with different database names (you can use copy/paste in database navigator).

**Comment by sirber** [comment]
Thank you for the workarounds!
