### ISSUE TITLE
ERD not shows relation between tables. MariaDB Driver 1.5.5

### ISSUE THREAD

**Issue by ansulev** [serge-rider/dbeaver#2419]
ERD does not show relations between tables. MariaDB Driver 1.5.5
![2017-10-27--1509083926_1366x768_scrot](https://user-images.githubusercontent.com/499040/32089870-d1052e6a-baec-11e7-986c-fcf45d32b242.png)
Am I missing something? Thanks!

**Comment by serge-rider** [comment]
Isn't WooCommerce based on classy MyISAM engine (i.e. there are no foreign keys at all)?

**Comment by ansulev** [comment]
Maybe this was not a good example. This happens in all my DBs, mostly all InnoDB engine. Will create a demo DB myself, will post the creation statement and the ERD. Hope today will find time to do it.

**Comment by serge-rider** [comment]
Can't reproduce.
What DBeaver version do you use?
Please use the most recent one.

This is ERD of demo database Sakila (MariaDB server and client driver).
![image](https://user-images.githubusercontent.com/6398845/32573624-a2b08030-c4df-11e7-8194-6343ac473a30.png)

**Comment by ansulev** [comment]
Hi, sorry for the late reply. I did a fresh reinstall of the dBeaver on the same Arch Linux box, imported my projects as well the sakila and now it's ok. Maybe was something about driver broken on my end. Sorry for your time. Please let's close this issue. And thank you very much for the great work on dBeaver!

**Comment by albert-kam** [comment]
I know this has been closed, but i also encountered this issue just now. A restart is just what it took to display the relations. No need to change drivers. Hope this helps others in need.
