### ISSUE TITLE
Zoom result set panel

### ISSUE THREAD

**Issue by ephetic** [serge-rider/dbeaver#2425]
Add ability to zoom the query results grid/text panel by hotkey, gesture, wheel, etc.  

Akin to #671 but for the result panel.

**Comment by serge-rider** [comment]
This can be done by dynamically changing "Results grid font" option (Preferences->General->Appearance->Colors and Fonts).
![image](https://user-images.githubusercontent.com/6398845/32124888-42a19f06-bb72-11e7-85b9-e8252a23c8de.png)

**Comment by serge-rider** [comment]
That's easy to do. Using the same shortcuts as for text/erd zoom.

**Comment by sweet-peas-carrots** [comment]
![Image](https://github.com/user-attachments/assets/c070bea8-a769-409b-bd13-1e9969cdb565)
