### ISSUE TITLE
MacOS X distribution: include JRE

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#2429]
MacOS is the most problem OS in terms of Java installation.
So, we need to include JRE right in DMG installer (similarly to what we did for Windows).

**Comment by serge-rider** [comment]
https://www.eclipse.org/forums/index.php/t/518603/

**Comment by jlolling** [comment]
I would not recommend to bundle the JRE within the application.
Simply provide an simple explanation how to install java 8 under macOS and thats it.
If you bundle it, you will not get updates and it makes the installation procedure much more complex.

**Comment by serge-rider** [comment]
Most people don't want to install any additional software. Most people don't know (and don't want to know) what Java is.
Also Java install is tricky on MacOS (you need to setup JDK, this confusing legacy Java 6 message, etc).

There is no need in any Java updates (besides the ones which will come with new DBeaver version). For users installation procedure won't change at all, JRE will be silently copied in DBeaver dir and that's it.

Note: this doesn't mean installation of new Java version for whole system. No any system properties will change. This JRE will be accessible only for DBeaver. Exactly as it is done now for Windows.

**Comment by serge-rider** [comment]
Beta version of pkg installer with bundled JRE is included in 4.2.6.

**Comment by serge-rider** [comment]
4.3.0 (both CE and EE) includes JRE in PKG.
