### ISSUE TITLE
"View script" button do nothing (as #2337)

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2433]
The bug is still present as in #2337. And I cannot send the log because there is no records about the bug appears. 
I even recorded the video.
[dbeaver.mp4.zip](https://github.com/serge-rider/dbeaver/files/1425988/dbeaver.mp4.zip)

**Comment by serge-rider** [comment]
Please check dbeaver-debug.log file.
There should be something.

**Comment by offstate** [comment]
You can see on the video that this file doesn't appear when I press the button. I think DBeaver doesn't treat this as an error

**Comment by offstate** [comment]
Today I rebooted my computer and this bug disappeared. I don't know why

**Comment by serge-rider** [comment]
Well. As I still can't reproduce it (on Windows, Mac or Ubuntu) I'm closing it.
If anybody will see this again - please reopen (no need to create a new ticket, just reopen this one).
