### ISSUE TITLE
[Postgres] Rename table doesn't work

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2434]
I try to rename a table from its context menu, enter new name in the dialog, press OK but then nothing happens.

**Comment by serge-rider** [comment]
Can't reproduce.
Please check error/debug logs for any errors after you press Ok.

**Comment by offstate** [comment]
Unfortunately, no entries in the log file appear as well as in the Transaction log.
But after I execute ALTER TABLE RENAME manually, the record in the transaction log appears.

**Comment by NekoKoneko** [comment]
I have the same issue trying to rename a table in the **Project** window.
https://github.com/serge-rider/dbeaver/issues/2033#issuecomment-323359927

**Comment by offstate** [comment]
Today I rebooted my computer and this bug disappeared. I don't know why
