### ISSUE TITLE
Install of Office Extension in 4.2.4

### ISSUE THREAD

**Issue by Sargul** [serge-rider/dbeaver#2439]
In the Version 4.2.4 the Office Extention can't be integrated into the standalone version like described in the [Wiki](https://github.com/serge-rider/dbeaver/wiki/Extension-Office).

The repository on https://dbeaver.jkiss.org/update/latest/ doesn't contain the office plugin anymore.

**Comment by serge-rider** [comment]
Thanks for report.
This happened because of splitting update site repositories. But this was planned for future release. 
Will fix update site asap.

**Comment by serge-rider** [comment]
Fixed.
Note: if you tried to install Office extension for 4.2.4 and failed then you will need to remove DBeaver completely (because repository information was cached) and reinstall again.
