### ISSUE TITLE
4.2.4 exe installer is tripping Microsoft SmartScreen filter

### ISSUE THREAD

**Issue by JoeCheez** [serge-rider/dbeaver#2442]
Obviously, I can bypass and it installs fine, but it's not great.

**Comment by serge-rider** [comment]
Sure. From 4.2.4 release notes:
`
Note: we have re-registered all certificates to the Rider Soft LTD company. Windows executables are signed with the Symantec Code-Sign certificate. Windows 10 may warn about this certificate during one or two weeks - that's ok.
`

**Comment by JoeCheez** [comment]
My apologies, didn't really read the release notes or dig into it  and just clicked update.  Just wanted to make sure you were aware =)
