### ISSUE TITLE
Small markup problem in README.md (bullet lists)

### ISSUE THREAD

**Issue by jschleus** [serge-rider/dbeaver#2445]
Only a small remark:

If I convert the file README.md into an HTML file using "pandoc" the bullet lists at top under "DBeaver (feature description) and under "Notes" aren't correctly rendered.

I am only a "markup"-layman but I have the impression that the reason is a missing blank line before the lists (that for e.g. exists before the also by "pandoc" correctly rendered list under "Notes"). GitHub seems more "fault-tolerant".

**Comment by serge-rider** [comment]
Thanks for noticing. Please check how it looks now

**Comment by jschleus** [comment]
Fine, both mentioned lists are now correctly rendered. Thanks!
