### ISSUE TITLE
White dots at top left of cells in Grid results view

### ISSUE THREAD

**Issue by cdabel** [serge-rider/dbeaver#2447]
I use the Dark theme and at the top left of all the cells in Grid view, there is a single pixel that is white. I'm not sure if this is intentional, but I don't think it adds any value being there.

I am using a Macbook Pro (2017) Retina display, but I see the dots on any of my screens.
I'm on DBeaver v4.2.3
Can anyone reproduce this?

**Comment by serge-rider** [comment]
I don't see it.
Please post a screenshot.

**Comment by cdabel** [comment]
<img width="467" alt="screenshot 2017-10-30 15 21 45" src="https://user-images.githubusercontent.com/16951252/32196417-36f3272c-bd86-11e7-804f-0f7a3ed0769e.png">

**Comment by serge-rider** [comment]
Thanks for details
