### ISSUE TITLE
Impala schema selection "Mark as Active" broken

### ISSUE THREAD

**Issue by cdabel** [serge-rider/dbeaver#2448]
Impala schema selection "Mark as Active" broken.

DBeaver 4.2.3 installed on Mac OSX Sierra.

Repro steps:
1. Set up working JDBC connection to Cloudera Impala.
2. Expand the new data source.
3. Right click on a schema, click Mark as Active. 
4. Query:
```select * from tableInSelectedSchema``` 

Note that this query does not work. The schema is not Active. (Do not `select * from selectedSchema.tableInSelectedSchema`; as this WILL obviously work)

Also, the text in the dbeaver toolbar does not change from "<None>" to the selected schema.

------------------

This is a feature of Cloudera Hue, which allows setting the Active schema in the Impala Query editor.
Having this feature would boost efficiency in developing queries.

**Comment by cdabel** [comment]
Noting that this hasn't worked since I started using DBeaver in July 2017.

**Comment by serge-rider** [comment]
DBeaver doesn't have preconfigured Impala driver. Thus there is no configuration for active schema read/write.
I think we need Cloudera driver in default DBeaver config.

Could you post what driver configuration do you use?

**Comment by chrisdabel** [comment]
Hi! I am using the Cloudera JDBC Driver for Impala, downloadable [here](https://www.cloudera.com/downloads/connectors/impala/jdbc/2-5-41.html):

I am using the Cloudera Impala JDBC 41_2.5.34 driver, specifically. 
(I have not tested newer versions)

Here it is:  
[Cloudera_ImpalaJDBC41_2.5.34 (2).zip](https://github.com/serge-rider/dbeaver/files/1447722/Cloudera_ImpalaJDBC41_2.5.34.2.zip)

Driver config:
![driver config](https://user-images.githubusercontent.com/30123467/32462875-310815bc-c2f8-11e7-87b8-13aa381570b4.png)

List of JARs:
![list of jars](https://user-images.githubusercontent.com/30123467/32462981-9bf3afee-c2f8-11e7-9911-63d78aa38d99.png)

Libraries:
![libraries](https://user-images.githubusercontent.com/30123467/32462941-762d46d0-c2f8-11e7-9192-4524721b2e10.png)

Create new connection wizard:
 - ![create new connection wizard](https://user-images.githubusercontent.com/30123467/32463146-24942d1a-c2f9-11e7-95c5-755915e7d742.png)
 - ![create new connection wizard_2](https://user-images.githubusercontent.com/30123467/32463162-34fcac2c-c2f9-11e7-9770-7aa534467c05.png)

**Comment by serge-rider** [comment]
Thanks.
I'll add Impala config template in the next DBeaver version.

**Comment by chrisdabel** [comment]
Thank you!
