### ISSUE TITLE
Questions about editing text

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2449]
1) When I sometimes have multiple spaces in come text/query and I want to delete them at once, I press Ctrl+Delete or Ctrl+Backspace (so I do in my code editor). In this case DBeaver's query editor deletes the spaces **as well as the next word**. Can I make it stop before the next word?

2) When I select an item from the autocomplete list, it **inserts** the value after the cursor position. Sometimes I want it **rewrite** the rest of the word by the inserted value. In my code editor in this case I press  Ctrl+Enter. Is it possible to do this?
![default](https://user-images.githubusercontent.com/16996529/32201737-4f7045ca-be24-11e7-90ff-e731dead7a9c.png)

**Comment by serge-rider** [comment]
1. There is no such standard action in Eclipse text editor framework. However it is possible to fix behavior of existing one
2. This should work like this by default.  So it is a kind of a bug, see fix in the next version.
