### ISSUE TITLE
Option pin / unpin tabs

### ISSUE THREAD

**Issue by jad986** [serge-rider/dbeaver#245]
My proposal next feature -> option pin / unpin tab with result of query. Pin tab always remain until user click unpin option or sql editor will be closed.

**Comment by viniciusam** [comment]
+1

**Comment by serge-rider** [comment]
Can you give me some example of how it may look in UI?

**Comment by viniciusam** [comment]
Hey, I took this screenshot from SQLDeveloper and as you can see the tab has an "pin" icon. When I click on it, the tab is pinned and any other results will be shown in a new tab. I can even rename the tab.

![sqldeveloper](https://cloud.githubusercontent.com/assets/5090796/15182215/c28749b6-1761-11e6-9de9-928035a060b2.png)

**Comment by serge-rider** [comment]
DBeaver has a different look-and-feel.
I can put pin into results status bar or in filters toolbar. Both these ways doesn't look very good..

**Comment by viniciusam** [comment]
Can't you put it on the tab context menu?

I would love to help implement this, but I never wrote an Eclipse plugin before.

**Comment by serge-rider** [comment]
Context menu is easy. Another option is to draw a pin over tab itself.
I'll do it by myself, np, I'm just guessing about good looking and convenient UI.

**Comment by viniciusam** [comment]
A pin over the tab looks great, and the context menu could have an option to rename it.

**Comment by serge-rider** [comment]
Pin/unpin actions will be accessible thru the context menu for now.
