### ISSUE TITLE
Postgres DDL Generation of materialized views without index

### ISSUE THREAD

**Issue by silviucm** [serge-rider/dbeaver#2450]
Hello,

Using the latest 4.2.4 as of October 30th, 2017.

This is similar to issue #2134 except it is for Postgresql and specifically for Materialized Views. As opposed to materialized views, the tables appear to generate the DDL correctly, with the index included at the bottom.

A quick screenshot to showcase a materialized view with indexes, which does not get the index generated with Generate SQL -> DDL command:

![image](https://user-images.githubusercontent.com/6261881/32202733-08863666-bdb5-11e7-965f-ad989d3ddb75.png)

Cheers

**Comment by serge-rider** [comment]
There is no some canonical DDL for PG materialized views (while it is for SQLite).

**Comment by silviucm** [comment]
@serge-rider are you referring to the final layout of the generated DDL ? pgAdmin 3 generates it like a regular statement at the bottom. 
e.g.
```
CREATE UNIQUE INDEX idx_view_article_list_id
  ON public.view_article_list  USING btree(id);
```
Is that acceptable to you as a reference ?

The actual details of the materialized view indexes can be extracted from pg_class and pg_index with relkind = 'm'
e.g.
```
SELECT i.relname AS index_name, idx.indrelid::regclass AS mat_view_owner, 
	   idx.indisunique AS is_unique, 
       am.amname AS index_access_method, idx.indkey AS index_keys,
       ARRAY(
       	SELECT pg_get_indexdef(idx.indexrelid, k + 1, true) FROM 
        generate_subscripts(idx.indkey, 1) as k
       	ORDER BY k
       ) as index_key_names
FROM pg_index as idx
JOIN pg_class as i ON i.oid = idx.indexrelid 
JOIN pg_am AS am ON i.relam = am.oid
JOIN pg_class AS mvclass ON mvclass.relkind = 'm' AND mvclass.oid = idx.indrelid;
```

**Comment by serge-rider** [comment]
See how it will look in 4.2.5
