### ISSUE TITLE
mongodb "find" returns no rows when mongo shell does and data exists

### ISSUE THREAD

**Issue by jonbartlett** [serge-rider/dbeaver#2451]
Hi,

I have a mongodb collection which I have just started working with from within dbeaver. The following command fails to return the data I am expecting:

`db.posts.find({"ygData.subject": "DOTVW MELB 19 NOV"})`

Returns:

```
{
  "_mongo": {
    "slaveOk": false,
    "host": "EMBEDDED"
  },
  "_db": {
    "_mongo": {
      "slaveOk": false,
      "host": "EMBEDDED"
    },
    "_name": "syncro"
  },
  "_collection": {
    "_mongo": {
      "slaveOk": false,
      "host": "EMBEDDED"
    },
    "_db": {
      "_mongo": {
        "slaveOk": false,
        "host": "EMBEDDED"
      },
      "_name": "syncro"
    },
    "_shortName": "posts",
    "_fullName": "syncro.posts"
  },
  "_ns": "syncro.posts",
  "_query": {
    "ygData.subject": "DOTVW MELB 19 NOV"
  },
  "_fields": null,
  "_limit": 0.0,
  "_skip": 0.0,
  "_batchSize": 0.0,
  "_options": 0.0,
  "_cursor": null,
  "_numReturned": 0.0,
  "_special": false
}
```

In mongo shell the exact same command returns the expected data.

MongoDB shell version v3.4.9
MongoDB server version: 3.4.9
dbeaver EE 4.2.0

**Comment by jonbartlett** [comment]
Another example which may help:
`
db.posts.find({"ygData.subject": ""})`

Returns:

```
{
  "_mongo": {
    "slaveOk": false,
    "host": "EMBEDDED"
  },
  "_db": {
    "_mongo": {
      "slaveOk": false,
      "host": "EMBEDDED"
    },
    "_name": "syncro"
  },
  "_collection": {
    "_mongo": {
      "slaveOk": false,
      "host": "EMBEDDED"
    },
    "_db": {
      "_mongo": {
        "slaveOk": false,
        "host": "EMBEDDED"
      },
      "_name": "syncro"
    },
    "_shortName": "posts",
    "_fullName": "syncro.posts"
  },
  "_ns": "syncro.posts",
  "_query": {
    "ygData.subject": ""
  },
  "_fields": null,
  "_limit": 0.0,
  "_skip": 0.0,
  "_batchSize": 0.0,
  "_options": 0.0,
  "_cursor": null,
  "_numReturned": 0.0,
  "_special": false
}
```

When there are records to return. Mongo shell works fine with above query.

In dbeaver, this works:
`
db.posts.find({"ygData.subject": ""}).count()`

Returns:

`{ "retval" : 12.0}`

**Comment by serge-rider** [comment]
DBeaver uses Java model of MongoDB so it is a bit different from shell.
Check this: #1147
(basically db.posts.find({"ygData.subject": ""}).toArray() will work)

**Comment by jonbartlett** [comment]
I see. Would be good if it implemented the same syntax as Shell. Most other MongoDB clients work like this. MongoDB support is probably my only reason to go DB EE.

**Comment by serge-rider** [comment]
I agree but as far as I see this is not possible with Java driver. All custom queries are executed by `eval` command. It doesn't return cursor.

Note: you can use SQL queries instead of JS. E.g. 
```sql
select * from posts where ygData.subject = ''
```
