### ISSUE TITLE
data, text view format change (minor)

### ISSUE THREAD

**Issue by fepetoo** [serge-rider/dbeaver#2454]
the data view can be selected as grid or text, which is great, if i want to copy out the result. However, it would be much better, if the text view could start with a | or, the delimiters could be configured, and the start and line-end delimiter could be optional..

**Comment by serge-rider** [comment]
Agreed, this would be helpful. And easy to do.

![image](https://user-images.githubusercontent.com/6398845/33239880-c92e3c6c-d2bc-11e7-9ef5-b70721d98f30.png)
