### ISSUE TITLE
Empty error message in Status details

### ISSUE THREAD

**Issue by Karsonito** [serge-rider/dbeaver#2455]
Error message is only visible for the first time. Can not to show it again in Status details window
![dbeaver 4 2 4 - _dbeaver sample database sqlite _ script 2017-10-31 13 20 14](https://user-images.githubusercontent.com/2379481/32221819-9f336aae-be3f-11e7-8b8b-cfeb9e4e70f8.jpg)
Version 4.2.4

**Comment by serge-rider** [comment]
Thanks for report

**Comment by Karsonito** [comment]
Thanks for quick fix!
