### ISSUE TITLE
TRUNC function not trunc'ing date

### ISSUE THREAD

**Issue by guyfromwy** [serge-rider/dbeaver#2457]
I noticed this a couple versions back, but I don't know how far back it goes or if it has always done this.
When attempting to truncate a date, the time portion is set to 00:00:00, but is not cut off. It does allow for proper date comparisons, which is good, but in order to get the desired result displayed, I need to use to_char instead.
e.g.
  SELECT trunc(SYSDATE) FROM dual
  ->  2017-10-31 00:00:00

I would expect it to yield
  -> 2017-10-31

BTW, this is in Oracle 12c

**Comment by serge-rider** [comment]
It is a bug in Oracle DATE data type handle. See fix in the next version.

**Comment by Tubaralho** [comment]
Same problem with trunc(date).

In DBeaver:
```
SELECT trunc(sysdate) FROM dual;
TRUNC(SYSDATE)      
--------------------
12-06-2018 00:00:00 
```

In Oracle SQLDeveloper for the same query:
![image](https://user-images.githubusercontent.com/9692595/41295043-6ea246ae-6e51-11e8-8d8f-892352676539.png)

> Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
> PL/SQL Release 12.1.0.2.0 - Production                                      
> CORE	12.1.0.2.0	Production                                              
> TNS for Linux: Version 12.1.0.2.0 - Production                              
> NLSRTL Version 12.1.0.2.0 - Production                                      

![image](https://user-images.githubusercontent.com/9692595/41294882-0194b9ca-6e51-11e8-9316-3a31737b70a2.png)

Need more info?

**Comment by BitExplorer** [comment]
This continues to be an issue with version 6.2.2.
