### ISSUE TITLE
Filter (F11) on DATETIME/DATETIME column generat error message

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2460]
DBeaver - **Version 4.2.4 CE**
DBeaver JDBC driver: **jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

Seems that if table content are displayed in a grid using **Database Navigator** I can not use Filter (F11) on DATETIME/DATETIME2 columns.

**o** Run script below to create a table with a DATETIME (same for DATETIME2) column.

```
   CREATE TABLE TestTbl (Id INTEGER, Value VARCHAR(80), CreateTime DATETIME);
   INSERT INTO TestTbl VALUES (1, 'row #1', GETDATE());
```

**THIS WORK AS EXPECTED - OK**

**o** Run script below to view the table contents

```
  SELECT * FROM TestTbl;
```

**o** Right click in the result grid on column **CreateTime**.

**o** Choose one of the precreated filters.

**o** The filter is applied correctly. 

**THIS DOES NOT WORK AS EXPECTED - ERROR**

**o** In the DBeaver Database Navigator, double click on the **TestTbl** table to show the table contents.

**o** Right click in the result grid on column **CreateTime**.

**o** Choose one of the precreated filters.

**o** An error message "**Query execution failed**" is shown. 

My guess is that the filter does not '-characters around the date-time value.

**Comment by serge-rider** [comment]
Thanks for report
