### ISSUE TITLE
DataSource missing for ER diagrams in Project pane

### ISSUE THREAD

**Issue by artoli** [serge-rider/dbeaver#2462]
In the Project pane the column DataSource is empty for ER Diagrams even though DBeaver knows which data source the diagram is derived from.

![bild](https://user-images.githubusercontent.com/33284166/32283407-8a923f90-bf24-11e7-9511-0bc05c561475.png)

**Comment by serge-rider** [comment]
IT is a bug (or misfunctions), thanks for noticing.
