### ISSUE TITLE
Error in Excel plug-in installation on Windows 10

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#2464]
I tried to install the Office Support plug-in in DBeaver 4.2.4 on Windows 10, but it always fail:

![captura de tela de 2017-11-01 17-46-05](https://user-images.githubusercontent.com/7952798/32294201-9b5ce4bc-bf2c-11e7-88ec-8a1eecfc61c9.png)
Stack trace: [error.txt](https://github.com/serge-rider/dbeaver/files/1435473/error.txt)

I also have DBeaver 4.2.4 installed on my Ubuntu 16.04 LTS and there I can install and reinstall normally.

**Comment by serge-rider** [comment]
Seems to be the same as #2439.
This is because of the bug in office extension.
You need to reinstall DBeaver on Windows (remove DBeaver folder).

**Comment by jeisoncp** [comment]
I removed DBeaver, deleted C:\Program Files\DBeaver and installed again. But I still can't install the extension on Windows.

**Comment by serge-rider** [comment]
@jeisoncp this happens because of Eclipse cache. Perhaps you also need to remove corresponding folder in ~\.eclipse\ directory (it is in the user home).
Or just wait for 4.2.5 release (will be released after a week)
