### ISSUE TITLE
DBeaver - Looped error message on un-wanted change to the DB.

### ISSUE THREAD

**Issue by nya13** [serge-rider/dbeaver#2465]
Hi,

It looks like if we have made some changes (without commit/persist called yet) and we decided to cancel / back out of any of those changes, the application will keep asking us to apply the changes.  We can't close the tab in question either as the tool will ask us to commit, even though we try to, and get an error.  The only way to back out or any commit is to kill the application.

**Comment by serge-rider** [comment]
Can't reproduce.
Please post some screenshot or steps to reproduce. 
What exactly action shows this confirmation dialog?

**Comment by nya13** [comment]
ok..let's try an example that is simple.  Go in a table and rename one of the columns to be the same as another one in the same table.  Now, try exiting (close the tab) from that tab because you no longer want to make any changes.  There's the loop that forces us to fix the problem.

**Comment by serge-rider** [comment]
Still not reproducible. Please check that you use the most recent version (there were multiple changes in object editor save procedure recently).
