### ISSUE TITLE
Missing Precision on edit of grid on long decimal columns (possible cast to double?)

### ISSUE THREAD

**Issue by Sargul** [serge-rider/dbeaver#2472]
Hi,

this behaviour has been tested with 4.2.4 and DB2 LUW & Exasol Plugin.

```sql
CREATE TABLE TEST.DECIMAL_COLS (COL1 DECIMAL(20,0));
INSERT INTO TEST.DECIMAL_COLS VALUES (12345678901234567890);
INSERT INTO TEST.DECIMAL_COLS VALUES (12345678901234567891);

-- refresh metadata
select * from test.DECIMAL_COLS;
```

* Now select any row and press delete
* show generated script -> seems to be cast to double type and value is wrong

Generated SQL:
![generated_sql](https://user-images.githubusercontent.com/5595511/32365095-ba190136-c078-11e7-9287-ac5e91198096.png)

I first thought, that this might be a display issue with the generated sql but when saving (using the save button) no rows are updated:
![execute](https://user-images.githubusercontent.com/5595511/32365153-078a6dc4-c079-11e7-9772-598ea6485678.png)

The strange thing is that when you generate a insert statement from this row the value is shown correctly:
![image](https://user-images.githubusercontent.com/5595511/32365196-31060730-c079-11e7-9e45-b59139f1158d.png)

**Comment by serge-rider** [comment]
Can't reproduce with DB2 Express and standard DB2 driver:
![image](https://user-images.githubusercontent.com/6398845/32701520-96dd4b06-c7e8-11e7-8b98-829bb8c65fcf.png)
Row delete also works fine.

**Comment by Sargul** [comment]
* I now tried to completly remove dbeaver
* Delete Workspace
* Install newest DBeaver and start with a fresh workspace (4.2.5 CE)
* User newest DB2 V11.1 Fixpak2 JDBC Driver

I still run into the sample problem.

What's weird is that my dialog for preview looks different than yours:
I've got an additional line
´´´sql
-- Actual parameter values may differ, what you see is a default string representation of values
´´´

Also there is no "Use fully qualified names" Option.

**Comment by serge-rider** [comment]
Ok, now I got it. For some reason I thought it was about generate SQL feature.

Indeed, there is a bug in parameters binding (DECIMAL type wasn't handled properly)
