### ISSUE TITLE
I tried copy table row and paste

### ISSUE THREAD

**Issue by adaoduque** [serge-rider/dbeaver#2473]
![print_dbeaver](https://user-images.githubusercontent.com/13459554/32372016-43288626-c07a-11e7-8269-4bf1ec8e4e67.PNG)

I tried copy table row and paste, but it not work, the table row information was not pasted into its columns respectively.

Copy row 3 and paste it, result:
![print_dbeaver_2](https://user-images.githubusercontent.com/13459554/32372297-65c2fce2-c07b-11e7-8f61-45a45753b313.PNG)

Thank you.

**Comment by serge-rider** [comment]
Standard paste (<kbd>ctrl+v</kbd>) modifies contents of selected cell.
In order to replace full row use advanced paste (<kbd>ctrl+shift+v</kbd>). You can copy/paste any number of rows this way.

**Comment by adaoduque** [comment]
Very nice, ctrl+shift+v works fine.

Thank you.

**Comment by phazei** [comment]
That doesn't work on MacOS, can't figure out how to copy and paste a row :(

**Comment by Faq** [comment]
@phazei select your data ctrl+c, for target table add 1 or needed amount of rows and do ctrl+shift+v, works for me on mac.

**Comment by mokulus** [comment]
Importantly you need to use actual `control` instead of `command` as you would with regular "ctrl+v"
