### ISSUE TITLE
FIX -closeTabs and/or -disconnectAll  reuse the last opened DBeaver window

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2475]
ever since 4.2.4 it seems that -closeTabs and/or -disconnectAll  reuse the last opened DBeaver window instead of creating a new instance using the same workspace (with or without -reuseWorkspace)

running just "dbeaver" opens up a new instance

**Comment by serge-rider** [comment]
You can use `-newInstance` parameter to force running CLI commands in new DBeaver instance.

**Comment by allanlaal** [comment]
@serge-rider could you add this to the wiki aswell? :)
https://github.com/serge-rider/dbeaver/wiki/Command-Line
