### ISSUE TITLE
Please support cubrid db.

### ISSUE THREAD

**Issue by devSonicgirl** [serge-rider/dbeaver#2479]
cubrid's manager tool is bad.
I hope you can support it with dbeaver.

https://www.cubrid.org

**Comment by serge-rider** [comment]
It is quite easy as CUBRID has JDBC driver. I'll add its configuration in the next DBeaver version.
I can't test/validate how it works so please do it after 4.2.5 release.

For now I'll mark it as beta and will set driver version to 10.1.0.

**Comment by devSonicgirl** [comment]
Thank you very much for supporting DBeaver  4.2.5.
I connected to cubrid. And it is good to test it.
