### ISSUE TITLE
Bug: Editor Options

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#248]
First off, awesome update with 3.6.1 the new editor features are amazing.
However I noticed a couple things

1) I don't believe that the line numbers option in General > Editors > SQL Editor is used anymore. I couldn't get this option to have any affect. I believe it has been superseded by General > Editors > Text Editors > Show Line Numbers.

action item: remove General > Editors > SQL Editor > Line numbers ?

2a) Can't configure tabs to be soft tabs of length 2? (Displayed tab width doesn't appear to be working)
2b) shift-tab followed by tab inserts tabs when insert spaces for tabs is checked
note: shift-tab isn't needed to reproduce. Simply highlight a line and then press tab.
2c) can't shift-tab on soft-tab width of 2
![editor_bugs](https://cloud.githubusercontent.com/assets/9246654/13406237/40ad42fa-ded7-11e5-914f-cbd2e9cc1006.gif)

**Comment by serge-rider** [comment]
1. Yes, SQL editor rulers options were replaced with Text Editors settings. Will remove them.
2. Tab width preference affects only actual tab width. Soft tabs (spaces for tabs) width can't be configured now. Will fix it (use text editors settings).
Thanks for report.
