### ISSUE TITLE
how to remove  the comment message "/* ApplicationName=DBeaver 4.2.4 - Main */"

### ISSUE THREAD

**Issue by yuandianali** [serge-rider/dbeaver#2480]
when I create a SQL with comment at the begging of the SQL, such as,
`/*+abc=int*/ select name from tabname` where id=1.
but DBeaver sent this sql add more comment "/* ApplicationName=DBeaver 4.2.4 - Main */",
so the database server got " `/* ApplicationName=DBeaver 4.2.4 - Main */ /*+abc=int*/ select name from tabname where id=1`" .

how to remove this from the SQL sent to the database server？

Thanks!

**Comment by serge-rider** [comment]
DBeaver doesn't add this comment (at least explicitly). It is so-called client application name and it is set using JDBC API.
What is your database?

**Comment by yuandianali** [comment]
I use mysql jdbc driver. it works using sql benchworkJ tool connect to my database.

**Comment by yuandianali** [comment]
SQL in DBeaver:
/*+ engine=MPP */select sum(5)+sum(2) as c1 from t_fact_2
SQL received by the Database server:
/* ApplicationName=DBeaver 4.2.4 - Main *//*+ engine=MPP */ select sum(4)+sum(2) as c1 from t_fact_2

The JDBC Driver:
MySQL-connector-Java:release5.1.44

**Comment by serge-rider** [comment]
This is a standard way to specify client name thru JDBC driver. It works fine wit hreal MySQL and MariaDB servers.
I can add an config option for client identification disabling.

**Comment by yuandianali** [comment]
Thanks very much for your so quickly response, and we will recommend DBeaver as the top tools for our customers in worldwide. 
Thanks again for your help on this.
