### ISSUE TITLE
Result Set Color by Type

### ISSUE THREAD

**Issue by PatriciaGomesB** [serge-rider/dbeaver#2485]
Is there any way to set the result set with colors by data type? For example, if it is an int would it look blue to integers, green to strings and brown to date type like heidisql does?

![32txn4pjs56eej0xfeqtaq](https://user-images.githubusercontent.com/18722810/32486381-6054b91e-c39e-11e7-8a66-713df9eb154b.png)

**Comment by serge-rider** [comment]
Sounds like an interesting feature.

**Comment by efradkin** [comment]
![image](https://user-images.githubusercontent.com/16664546/33401185-81a645a6-d569-11e7-8cd5-9e21d9e9d6b5.png)

**Comment by PatriciaGomesB** [comment]
That's exactly what I needed, thanks

**Comment by efradkin** [comment]
![image](https://user-images.githubusercontent.com/16664546/33435506-6ae1c824-d5f3-11e7-9ae2-1c42caf7db17.png)
Dark theme

**Comment by serge-rider** [comment]
@efradkin Great job!
