### ISSUE TITLE
GUI: Database navigator

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#249]
We have **```Copy```** menu entry, but maybe we must have **```Paste```** too?

![dialog](https://cloud.githubusercontent.com/assets/9958813/13418902/c5b7c070-df8a-11e5-90fa-78714d499237.png)

**Comment by serge-rider** [comment]
"Paste" command is not yet implemented for the most of database objects.
I think that obstructing context menu with all possible rare commands isn't a good idea..

**Comment by infectormp** [comment]
agree
