### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ti-ku** [serge-rider/dbeaver#2491]
I am using the DBeaver 4.2.4 on Ubuntu 17.10 and there seems to be a memory leak. Opening a SQL Editor causing DBbeaver to eat all my ram up. Also not actually using it, let DBeaver eat 1MB of RAM every ~2 seconds. Closing the SQL Editor stops the memory allocation, but doesn't seem to free any memory. Opening it again, let the memory consumption grow instantly. One of DBeaver java processes  is using 10-30% cpu while the Editor is open.

I attached a screenshot showing htop while an SQL Editor is opened:
![screenshot 2017-11-08 11-01-53](https://user-images.githubusercontent.com/6747073/32542930-73db706e-c474-11e7-9a67-759c89ece64e.png)

**Comment by carlosspohr** [comment]
Hi @ti-ku ,

It sounds as this bug on GTK and SWT here:

https://github.com/serge-rider/dbeaver/issues/1924

Try this trick as described on this comment:
https://github.com/serge-rider/dbeaver/issues/1924#issuecomment-322870359

**Comment by ti-ku** [comment]
thank you, seems to work, but unfortunatelly it breaks Eclipse's dark theme.

**Comment by carlosspohr** [comment]
Uhmmm,

There are some guys using dark theme on DBeaver, try to looking up here in issues to find some helpful information about that or open an issue here.

I don't know enough about themes to help you, sorry man :/

**Comment by ti-ku** [comment]
Ok, thanks ;)
