### ISSUE TITLE
Cannot "Launch an Eclipse application"

### ISSUE THREAD

**Issue by Bludwarf** [serge-rider/dbeaver#2492]
Hello,

I would like to contribute to dbeaver and then I followed the wiki to configure Eclipse to launch DBeaver.product. The project is built but when I launch the product file I get this error :

```
An internal error occurred during: "Launching DBeaver.product".
org.eclipse.jdt.launching.JavaRuntime.isModularJava(Lorg/eclipse/jdt/launching/IVMInstall;)Z
```

I use Eclipse Oxygen.1 Release (4.7.1) on Windows 10 Creators.

Did anyone meet this problem ?

**Comment by serge-rider** [comment]
What is your Java version?
In some cases Java 9 is not really working with Oxygen.

**Comment by Bludwarf** [comment]
Thanks for the pointing me this out. I tried the following solutions :

- Change default installed JREs from JRE 1.8.0_74 to JDK 1.8.0_121
- Add `-vm` parameter to point to this JDK in eclipse.ini

The problem is still the same.

**Comment by serge-rider** [comment]
Looks like you have wrong Eclipse version.
Try Eclipse for RCP and RAP developers (https://www.eclipse.org/downloads/packages/eclipse-rcp-and-rap-developers/oxygen1a)

**Comment by ruspl-afed** [comment]
@Bludwarf , please provide more details regarding your environment.
The JRE that answers you in batch shell may be different from that is used during .product launch.
Please review preferences "Window -> Preferences" then "Java->Installed JREs"

**Comment by Bludwarf** [comment]
Thank you @serge-rider that was just a problem with Eclipse installation.
I installed a fresh Eclipse from your link and followed the wiki. The application starts now... and crashes but this is another problem.
Sorry for the silly question !

**Comment by Bludwarf** [comment]
The other problem was fixed by following this post : https://stackoverflow.com/a/13575823/1655155
