### ISSUE TITLE
[MySQL] Hyphen in the database name

### ISSUE THREAD

**Issue by temporaryaccount** [serge-rider/dbeaver#2494]
Sometimes I'm getting errors refreshing some non-data windows with F5 when the database contains the hyphen (-) symbol in its name.

# Reproducing

1. Create a database named "hyphen-test"
2. Create a table named "testtable" in that database with some columns
3. Open the table, open its Properties, select the Columns tab
4. Hit F5

I get an error titled with "Error refreshing node" with this text (two lines of the same message):

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`hyphen-test` LIKE 'testtable'' at line 1
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`hyphen-test` LIKE 'testtable'' at line 1
```

DBeaver: 4.2.4
OS: Linux
MySQL: 5.1

**Comment by serge-rider** [comment]
Thanks for report
