### ISSUE TITLE
Don't restore tabs when starting DBeaver

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#2496]
I thought that the "☑ Restore editor state on startup" option controls the behavior to restore tabs or not when restarting DBeaver.

![image](https://user-images.githubusercontent.com/3851902/32566398-149f1918-c4b8-11e7-9af2-d74dc86fc4df.png)

I've unchecked that option because I would like to start with an empty environment each time I start DBeaver, but my tabs are always restored. Am I mistaken?

**Comment by serge-rider** [comment]
This behavior is controlled by different prefs option:

![image](https://user-images.githubusercontent.com/6398845/32633786-f4d8bf1e-c5b9-11e7-827d-b17f2aac7cdb.png)

**Comment by Otiel** [comment]
Thanks, I missed that one!

**Comment by andyewen** [comment]
They've moved the option since the answer above. This is the location in version 6.0.4.

![image](https://user-images.githubusercontent.com/7320424/58979439-fc237500-87c5-11e9-808c-a6c536d74556.png)

**Comment by mbrodala** [comment]
And the option was moved/renamed again:

![image](https://github.com/dbeaver/dbeaver/assets/5037116/fe7438ad-960c-447f-8e39-1e46d597b32b)

(DBeaver 23.1.1)

**Comment by BeepBoop888** [comment]
![reopen](https://github.com/dbeaver/dbeaver/assets/61386219/477715b7-b44c-45c7-a5c4-8a5b5eb71791)
Updated for DBeaver Version 24.0.0
