### ISSUE TITLE
[Postgres] Invalid DDL for modify view

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2497]
I changed a materialized view and got an error when tried to save it. Generated DDL is invalid. 

![default](https://user-images.githubusercontent.com/16996529/32580738-6bdd1070-c532-11e7-99c0-0ac64498bea3.png)

![default](https://user-images.githubusercontent.com/16996529/32580751-78596a88-c532-11e7-8d52-0ad8d7a376de.png)

**Comment by serge-rider** [comment]
Thanks for report.

**Comment by offstate** [comment]
I can't find how to reopen an issue.
Now in  4.2.5 DDL creates a view without deleting the existing and you get an error
`SQL Error [42P07]: ERROR: relation "test" already exists`
