### ISSUE TITLE
Configurable local port for SSH tunnels

### ISSUE THREAD

**Issue by Wirone** [serge-rider/dbeaver#2500]
Hello, new user here - first I would like to congratulate great software!

As a former HeidiSQL user I would like to ask is it possible to configure connection with SSH tunnel using custom local port, so after connecting to database with DBeaver tunnel can be used within local application (for example Symfony app)? I can't find the way in connection's configuration.

It can be done with Heidi and I really need it for my workflow. I would really appreciate adding this feature :-)

**Comment by serge-rider** [comment]
Agreed, this makes sense. And easy to do:
![image](https://user-images.githubusercontent.com/6398845/32633633-52f7e33c-c5b9-11e7-82fc-2a9adae09b64.png)

**Comment by Wirone** [comment]
Wow, that's impressive feedback and implementation time :-) Thanks! I'm looking forward for 4.2.5 then.
