### ISSUE TITLE
Why Enable Keep-Alive cause modified data auto saved ?

### ISSUE THREAD

**Issue by Threegirls** [serge-rider/dbeaver#2503]
- I set Keep-Alive to 10 secs
![image](https://user-images.githubusercontent.com/11012561/32648671-de55a45a-c631-11e7-9504-392bd2db63dc.png)
- Modify function_order value from '3' to '33'
![image](https://user-images.githubusercontent.com/11012561/32648775-5ecb80dc-c632-11e7-8d55-257a27089493.png)
- Wait for few seconds... auto saved...
![image](https://user-images.githubusercontent.com/11012561/32648810-79d054ac-c632-11e7-9a62-788bee348602.png)
![image](https://user-images.githubusercontent.com/11012561/32648816-800ca87a-c632-11e7-90c4-da4143adf675.png)

**Comment by serge-rider** [comment]
Seems to be duplicate of #2408
There was a bug in recent version of DBeaver. And this was triggered not by keep-alive but by auto-save preferences:
![image](https://user-images.githubusercontent.com/6398845/32697595-0fecd96a-c7a5-11e7-82ad-a848c4e940ea.png)

Thanks for  report anyway.
