### ISSUE TITLE
Date format does not properly displayed

### ISSUE THREAD

**Issue by jackse7en** [serge-rider/dbeaver#2510]
Hi @serge-rider,

I'm running DBeaver 4.2.5 with Oracle thin driver.
After update, the date format did not display in YYYY-MM-DD HH:mm:ss format, instead, it display in YYYY-MM-DD 00:00:00

![untitled](https://user-images.githubusercontent.com/15628830/32713040-6d52c7f8-c882-11e7-9d61-4c971a5321de.png)

**Comment by serge-rider** [comment]
Seems to be a side effect of #2457 fix.
What is your Oracle version?

**Comment by jackse7en** [comment]
Oracle 11g 11.2.0.4.0

**Comment by serge-rider** [comment]
Will be fixed in the next version, thanks for report.

Workaround: change Date type format:
![image](https://user-images.githubusercontent.com/6398845/32716447-23bf73c2-c867-11e7-8fd4-708335d22fa1.png)

**Comment by jdgszorro** [comment]
Thank you
