### ISSUE TITLE
Bug: Blank Line is statement Delimiter

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#2514]
Hi serge,

This is an old bug but it finally bothered me enough to report it.

If you have a query that ends with a `--` comment and only one blank line after it will incorrectly run both the desired query and the one below it. The bug will not trigger if the comment is a `/*foo-bar*/` comment.

Here's a screen recording showing the issue along with a screen shot of the option. Let me know if you need anymore information.

![dbeaver_delim_bug](https://user-images.githubusercontent.com/9246654/32741898-a24a30e8-c85c-11e7-93be-24401921a0b8.gif)

<img width="270" alt="screen shot 2017-11-13 at 10 11 59 am" src="https://user-images.githubusercontent.com/9246654/32741722-0f7ad1d2-c85c-11e7-9506-c1bdae1ba5ad.png">

also just to be super clear. This issue in the one where it breaks is that it runs both commands as one. AKA when i look at the query manager i can see a failure next to this query

```
select random(0,100000), d_date.*
from dbo.d_date
where "date" = current_date
--this will now break

select *
from dbo.d_date
where "date" = current_date - 2
```

**Comment by serge-rider** [comment]
I didn't see this because it never happens on Windows with \r\n line feeds.
Thanks for report.

**Comment by r-richmond** [comment]
I'm always impressed with the speed of your resolutions. Thanks a Ton!
