### ISSUE TITLE
Query execution failed

### ISSUE THREAD

**Issue by adaoduque** [serge-rider/dbeaver#2518]
Table:
```
CREATE TABLE `virtual_users` (
`id` INT NOT NULL AUTO_INCREMENT,
`domain_id` INT NOT NULL,
`password` VARCHAR(106) NOT NULL,
`email` VARCHAR(120) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
Query:
```
INSERT INTO `virtual_users` (`id`, `domain_id`, `password` , `email`)
VALUES('1', '1', ENCRYPT('gppai', CONCAT('$6$', SHA2(RANDOM_BYTES(64), '256'))), 'adao.duque@example.com.br');
```

Message error:
![erro dbeaver](https://user-images.githubusercontent.com/13459554/32791126-62773c68-c947-11e7-8d8b-9489f108860e.PNG)

But, run the query directly on the Mysql command line, this works perfectly.

What is going on ?

Thank you.

**Comment by adaoduque** [comment]
Sorry for my mistake. 
This is not a bug in DBeaver

**Comment by adaoduque** [comment]
Query in mysql command line works perfectly.

**Comment by serge-rider** [comment]
This is because encrypt functions returns NULL in your case. Maybe you are testing this on Windows machine (while ENCRYPT works ok only if MySQL server is runnign on some Linux machine).

Check this: https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html#function_encrypt

**Comment by adaoduque** [comment]
Thank you for response.
