### ISSUE TITLE
Launch dBeaver twice

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2519]
kinda related to #2251

is it possible to launch dBeaver twice whitout corrupting it's config files? Second launch could use the config files in read-only mode.

Exemple scenario:
I add an index on a 450m rows table, the UI jams for 45 minutes. I have to use phpMyAdmin or another client to continue working.

**Comment by serge-rider** [comment]
Yes, it is possible. You can press "Ignore" button in startup warning dialog. But You can't modify any files in second instance.

Note: if you have so huge indexes I'd recommend to create them in SQL editor. You can copy index creation DDL from SQL preview dialog and execute it in separate SQL editor. 
This won't block UI.

**Comment by sirber** [comment]
I get a warning that "I can corrupt the workspace" in the startup warning dialog...

**Comment by serge-rider** [comment]
Yes, you can corrupt it. 
Generally it is a bad idea to open the same workspace multiple times.
