### ISSUE TITLE
reusing transactions that are no longer active

### ISSUE THREAD

**Issue by wrz333** [serge-rider/dbeaver#252]
Using DBeaver with Teiid and repeating experiencing the following error:
DBCException: SQL Error [30504] [50000]: TEIID30504 Remote org.teiid.core.TeiidProcessingException: TEIID30504 COL_ORA_DS: TEIID11009 java.sql.SQLException: javax.resource.ResourceException: IJ000460: Error checking for a transaction

Red Hat consultants on-site took a look from the Teiid side and had this to say:

> From initial investigation , it appears that the client application was trying to reuse a transaction that is no longer active.   This usually occurs when a program begins a transaction and it eventually gets committed, or aborted, but the application is not aware of the state of the transaction, tries to re-use it since it has a handle to it.
> 
> I see that the same transaction (id - 2a6a92e6:56c377db:1c) was reused multiple times between 2:35pm through 2:41pm. 

Help.  Thanks.

**Comment by serge-rider** [comment]
Hmm.
In fact DBeaver do not operates with transaction handles directly (because JDBC API doesn't provide them). I think it happens somewhere inside the driver.
Could you post full error stack? (you can get it in error log view). I don't even understand where and when this error happens

**Comment by wrz333** [comment]
full error stack added 
[error_20160302.txt](https://github.com/serge-rider/dbeaver/files/155181/error_20160302.txt)

**Comment by serge-rider** [comment]
I'm not familiar with Teiid. It seems to be some wrapper over other data sources and it manages transactions in it's own fashion.
Can't figure out what can I fix in DBeaver.
Does this issue happen in auto-commit mode?

**Comment by serge-rider** [comment]
Will close for now.
If you will have any new information/idea please report.
