### ISSUE TITLE
FireBird Execute Block and declare variable

### ISSUE THREAD

**Issue by Apcio** [serge-rider/dbeaver#2520]
When I try to write EXECUTE BLOCK I had an error:

> 
> GDS Exception. 335544569. Dynamic SQL Error
> SQL error code = -104
> Unexpected end of command - line 4, column 23
> GDS Exception. 335544569. Dynamic SQL Error
> SQL error code = -104
> Unexpected end of command - line 4, column 23
>   Dynamic SQL Error
> SQL error code = -104
> Unexpected end of command - line 4, column 23
>   Dynamic SQL Error
> SQL error code = -104
> Unexpected end of command - line 4, column 23

It stop at section DECLARE VARIABLE:

```
EXECUTE BLOCK
RETURNS ( TYP_REKORDU VARCHAR(60) )
AS
	DECLARE VARIABLE IDA INTEGER;
	DECLARE VARIABLE IDS INTEGER;
BEGIN
	.......
END
```

How can I resolve this ?

**Comment by Apcio** [comment]
I understood how it works in DBEaver.
In FlameRobin I used:

```
SET TERM ^;
EXECUTE BLOCK
RETURNS ( TYP_REKORDU VARCHAR(60) )
AS
	DECLARE VARIABLE IDA INTEGER;
	DECLARE VARIABLE IDS INTEGER;
BEGIN
	....
END^

SET TERM ;^
```

But in DBEaver, I should to use semicolon instead of caret:

```
SET TERM ^;
EXECUTE BLOCK
RETURNS ( TYP_REKORDU VARCHAR(60) )
AS
	DECLARE VARIABLE IDA INTEGER;
	DECLARE VARIABLE IDS INTEGER;
BEGIN
	....
END;

SET TERM ;^
```

**Comment by serge-rider** [comment]
Generally first (classic) version should also work.

**Comment by tJeyhun** [comment]
First version does not work.

    SET TERM ^;

    EXECUTE BLOCK AS
    BEGIN
        IF (NOT EXISTS(SELECT 1 FROM "RDB$GENERATORS" WHERE "RDB$GENERATOR_NAME" = 'VEKALET_NO')) THEN
        BEGIN
            EXECUTE STATEMENT 'CREATE GENERATOR VEKALET_NO;';
        END

        IF (NOT EXISTS(SELECT 1 FROM "RDB$GENERATORS" WHERE "RDB$GENERATOR_NAME" = 'KART_NO')) THEN
        BEGIN
            EXECUTE STATEMENT 'CREATE GENERATOR KART_NO;';
        END

        IF (NOT EXISTS(SELECT 1 FROM "RDB$GENERATORS" WHERE "RDB$GENERATOR_NAME" = 'DAVA_KODU')) THEN
        BEGIN
            EXECUTE STATEMENT 'CREATE GENERATOR DAVA_KODU;';
        END

        IF (NOT EXISTS(SELECT 1 FROM "RDB$GENERATORS" WHERE "RDB$GENERATOR_NAME" = 'FAIZ_NO')) THEN
        BEGIN
            EXECUTE STATEMENT 'CREATE GENERATOR FAIZ_NO;';
        END
            
    END^

    SET TERM ;^

Giving error

    SQL Error [335544634] [42000]: Dynamic SQL Error; SQL error code = -104; Token unknown - line 23, column 4; ^ [SQLState:42000, ISC error code:335544634]
    SQL Error [335544634] [42000]: Dynamic SQL Error; SQL error code = -104; Token unknown - line 23, column 4; ^ [SQLState:42000, ISC error code:335544634]
    Dynamic SQL Error; SQL error code = -104; Token unknown - line 23, column 4; ^ [SQLState:42000, ISC error code:335544634]
        Dynamic SQL Error
        Dynamic SQL Error
        SQL error code = -104
        Token unknown - line 23, column 4
        ^
