### ISSUE TITLE
Select Data Source

### ISSUE THREAD

**Issue by snaveevans** [serge-rider/dbeaver#2525]
Downloaded 4.2.5 and now when I click on the Drop Down to select the Data source I get a pop-up window that doesn't allow me to select the data source.  It seems to only allow me to filter the sources, maybe, I really have now idea what it's supposed to do.  How can I select the datasource now?  Is this a bug?
![image](https://user-images.githubusercontent.com/3487777/32853839-d2a33868-c9f9-11e7-9817-8f1c8a439b34.png)

**Comment by serge-rider** [comment]
Try to resize this dialog

**Comment by snaveevans** [comment]
Oh yep, that worked, they are all there now.  That's too bad it's now a dialog, I prefer the drop down instead.

**Comment by serge-rider** [comment]
I'll fix it (set minimum size).
BTW you can popup this dialog by shortcut (ctrl+9). And it has search and filters which were unavailable in drop-down version (which was also buggy on many systems).
