### ISSUE TITLE
Error when export by Eclipse Product Export Wizard 

### ISSUE THREAD

**Issue by liuyuanyuan** [serge-rider/dbeaver#2528]
The last version of DBeaver could run normally in Eclipse IDE, but when I export DBeaver by Eclipse Product Export Wizard, I got  the following error:

..\workspace\dbeaver\nls\bundles\org.jkiss.utils.nls\build.xml:127: The following error occurred while executing this line:
..\workspace\dbeaver\nls\bundles\org.jkiss.utils.nls\build.xml:99: srcdir ..\workspace\dbeaver\nls\bundles\org.jkiss.utils.nls\src" does not exist!

Please have a look
Thanks and regard : )

**Comment by ruspl-afed** [comment]
Fixed build.properties for NLS fragments without source folders

**Comment by liuyuanyuan** [comment]
OK : )
