### ISSUE TITLE
Cascading Delete UI

### ISSUE THREAD

**Issue by agnahi** [serge-rider/dbeaver#2535]
I like to select a parent table in the DB Navigator pane and initiate a cascading delete from here. Intention is that from here a delete (depending on selection criteria to be provided) is started that is following the dependencies of the table and takes them into consideration.

As a result the selected records of the partent table are deleted plus all referential dependant records in the child tables.

**Comment by serge-rider** [comment]
This is database-specific.
Standard object delete UI has to be able to show custom option (like "Cascade delete")

**Comment by serge-rider** [comment]
MySQL, PostgreSQL and Oracle implementation (they have a bit different meaning of CASCADE - but this is just what comes out of the box) will be added in 4.3.1.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/34314020-e511ba3e-e780-11e7-8a51-896da791625a.png)

Further improvements should be tracked in separate tickets.
