### ISSUE TITLE
Incorrect display of Postgres time data type

### ISSUE THREAD

**Issue by Zhaoseph** [serge-rider/dbeaver#2536]
This is similar to ticket: https://github.com/serge-rider/dbeaver/issues/848
Looks like DBeaver incorrectly handles TIME values (as TIMESTAMP).

Config:
DBeaver 4.2.5
Postgres 9.5.4

Issue:
SELECT operation does not return (or display) the time data type column correctly, instead it displays something like "1970-01-01 08:00:00"

PgAdmin 4 shows it correctly as "08:00:00"

**Comment by serge-rider** [comment]
Please post SQL query to reproduce (`select current_time` renders time correctly)

**Comment by carlosspohr** [comment]
Hi there,

Here it seems OK:

![image](https://user-images.githubusercontent.com/637767/33080798-1518399e-cec0-11e7-9351-5e9883dc962d.png)

**Comment by Zhaoseph** [comment]
Hello, 

I tried replicating the issue today but everything displayed properly. Probably something wrong on my end.
