### ISSUE TITLE
cannot save artifact config

### ISSUE THREAD

**Issue by ericshenjs** [serge-rider/dbeaver#254]
1,add a artifact for mysql
2,download the release jar into Workspace\.metadata\.plugins\org.jkiss.dbeaver.core\maven\maven-central\mysql ,then can connect to mysql server
3,restart dbeaver 
4,cannot connect mysql serverbecause of bad driver configuration 
5,open driver configuration  ,no jar lib

**Comment by ericshenjs** [comment]
![Uploading artifact.JPG…]()

**Comment by ericshenjs** [comment]
![Uploading artifact01.JPG…]()

**Comment by ericshenjs** [comment]
version 3.6.1

**Comment by serge-rider** [comment]
Why do you try to put jar into Maven artifacts directory? If you have a jar then just add it to the driver with "Add file". And remove Maven artifact if you don't have access to maven-central.

**Comment by ericshenjs** [comment]
because i want the lates jar by maven-central

**Comment by serge-rider** [comment]
Then why you just don't use Maven artifact? You can update it to any version from UI.
There is no need to put anything in DBeaver internal cache directories.

**Comment by codebling** [comment]
See also #199
