### ISSUE TITLE
PostgreSQL: Invalid automatically generated update query

### ISSUE THREAD

**Issue by IgorNovozhilov** [serge-rider/dbeaver#2540]
### Example table query
```sql
CREATE TABLE public.projectsource (
	id int4 NOT NULL DEFAULT nextval('projectsource_id_seq'::regclass),
	project int4 NOT NULL,
	repository int4 NOT NULL,
	"path" text NOT NULL,
	branch_type int4 NULL,
	branch_name text NULL,
	branch_tmpl text NULL,
	main bool NOT NULL DEFAULT false,
	watch bool NOT NULL DEFAULT false,
	last_commit text NULL,
	last_commit_date timestamp NULL,
	CONSTRAINT pk__projectsource__id PRIMARY KEY (id),
	CONSTRAINT u__project__path UNIQUE (project,"path"),
	CONSTRAINT u__project__repository UNIQUE (project,repository),
	CONSTRAINT fk__projectsource__project FOREIGN KEY (project) REFERENCES public.project(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT fk__projectsource__repository FOREIGN KEY (repository) REFERENCES public.repository(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
WITH (
	OIDS=FALSE
) ;
CREATE
    UNIQUE INDEX i__project__main ON
    projectsource
        USING btree(
        project,
        main
    )
WHERE
    (
        main IS TRUE
    ) ;
```

### Editable in the interface
![image](https://user-images.githubusercontent.com/3082812/32949429-d35ef682-cbb3-11e7-8dac-72a363e7ac85.png)

### Automatically generated query
![image](https://user-images.githubusercontent.com/3082812/32949445-e685a81e-cbb3-11e7-8f25-d9d8c3ebbea3.png)

### Correct query
```sql
UPDATE public.projectsource
SET main=true
WHERE id=7;
```

### Behavior
At the moment to build the query index is used: ` i__project__main`

And in fact, must be used a primary key: `pk__projectsource__id`

**Comment by serge-rider** [comment]
To update/delete rows DBeaver first searches for unique indexes (they are unique and definitely indexed i.e. work fast).
If your example update query should work correctly. But may be not very obvious..

**Comment by serge-rider** [comment]
However I agree. 
If we can use primary key index then it's better to use it than any other index.

**Comment by IgorNovozhilov** [comment]
@serge-rider, It's good.
However, a unique constraint can not cover the entire table, but only part of it, as in my case. And the change in the user interface one record causes a change in multiple records, as in my case that leads to a fall.
I think it is worth adding a data integrity check by comparing the number of records changed in the interface with the number of records that potentially change the script to update. When differences in the number of records to output an appropriate warning.
