### ISSUE TITLE
Row count doesn't work with line terminator / semicolon

### ISSUE THREAD

**Issue by TheDanO** [serge-rider/dbeaver#2541]
After update from a previous version (not necessarily 4.2.4), pressing ctrl+alt+c to do a row count on a select statement no longer runs correctly.  It throws an error on the semicolon.  Highlighting the select except for the semicolon and running the count seems to work.  This is on SQL Server if that makes a difference.

![image](https://user-images.githubusercontent.com/13124479/32962659-7b47dda2-cb8a-11e7-9182-9bf187fb42a7.png)

![image](https://user-images.githubusercontent.com/13124479/32962675-8ef15022-cb8a-11e7-8b57-e679a8dc3ce3.png)

**Comment by serge-rider** [comment]
Yes, row count query transformation was changed in 4.2.5 (see #2346).

Thanks for report, see fix in the next version.
