### ISSUE TITLE
Database navigator: Connection type highlight not visible when selecting or mouse-hovering

### ISSUE THREAD

**Issue by TheReincarnator** [serge-rider/dbeaver#2542]
First of all: This database client is the greatest that exists, because of so many reasons, and I tested a lot in my every-day work as an almost-20-years software developer.

I have a small (but annoying) issue:
When selecting a connection (or hovering with the mouse), the connection-type coloring (like red=PROD, which I use and love a lot!) is not visible. Instead, default selection and hovering colors kick in.

Can you instead use some other type of highlighting, like a border around the item, or at least use the original color in a modified way (mixed with the selection color?).

This way, I can always see if a production connection is selected or hovered.

I am using Windows 10, if that makes any difference.

Thanks a lot!

**Comment by serge-rider** [comment]
Agreed.
I think something like this might help:
![image](https://user-images.githubusercontent.com/6398845/32980789-2eafb97a-cc7e-11e7-8a25-be7e01d534f1.png)

(Last two rows have types PROD and QA and are selected)

**Comment by TheReincarnator** [comment]
Actually, I think this too hard to read. I was more heading towards the other way round:Leaving the background red resp. green, but using a black border as a selection. This way, the concepts don't mix:/ connection types are background colors, and don't change/ selections are borders, not interfering with the background.

**Comment by serge-rider** [comment]
Background color/visualization is OS-dependent (it is different on each OS/window system). So it is not easy to control it. 

As an alternative I'm thinking about some kind of tags (next to the connection name) instead of background coloring..

**Comment by serge-rider** [comment]
You can check current UI in EA version: https://dbeaver.jkiss.org/files/ea/

**Comment by TheReincarnator** [comment]
I an currently on a party (it's evening GMT), but will in a few hours. Thanks mate!

**Comment by TheReincarnator** [comment]
Thanks, I gave it a check now. It is definitely an improvement, while I still think that the connection-type highlight is more important than the selection/hover indication, so I still would like to see the background not being so much replaced.
But tags instead of background is also a very good idea, and that is, I guess, easier to manage cross-OS.

**Comment by TheReincarnator** [comment]
Either way, big thanks for your response speed and open-minded conversation!

**Comment by serge-rider** [comment]
Let's try current way in 4.2.6 and see how it will go.
And make further improvements in a separate ticket.
