### ISSUE TITLE
Invalid preference category path: org.eclipse.ui.net.NetPreferences

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#2546]
Warning `Invalid preference category path: org.eclipse.ui.net.NetPreferences (bundle: org.eclipse.jsch.ui, page: org.eclipse.jsch.ui.SSHPreferences)` occurs after updating DBeaver from v4.2.4 to v4.2.5. No stacktrace available.

**Comment by ruspl-afed** [comment]
Hmm, 4.2.5 doesn't include org.eclipse.core.net and org.eclipse.ui.net for some reason

**Comment by serge-rider** [comment]
@ruspl-afed It never did (although org.eclipse.ui.net was included in EE).
Do you think we need it there (explicitly)? 

org.eclipse.jsch.ui was added in CE 4.2.4  - perhaps it causes these warnings.

**Comment by ruspl-afed** [comment]
I think it is better to add org.eclipse.ui.net if we need org.eclipse.jsch.ui. 
The dependency from org.eclipse.jsch.core to org.eclipse.core.net is explicit, looks like they missed to specify dependency between UI parts.
