### ISSUE TITLE
Wrong parameters binding

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2547]
[mysql]
I have a query with parameters and I noticed that when the query shifted right in the editor, values insert into wrong positions

![default](https://user-images.githubusercontent.com/16996529/32997824-b3e1a91a-cde0-11e7-9ebe-dc88c72bd0fe.png)

![default](https://user-images.githubusercontent.com/16996529/32997836-cc678c84-cde0-11e7-9015-d8968764ca59.png)

![default](https://user-images.githubusercontent.com/16996529/32997899-92a2eace-cde1-11e7-999a-7bc44b1a3796.png)

**Comment by serge-rider** [comment]
Could you provide steps to reproduce this?
A which moment do you actually modify SQL text?

**Comment by serge-rider** [comment]
Thanks. 
Indeed, it is a bug in query extraction.
Thanks for report.
