### ISSUE TITLE
Producing wrong insert script for arrays in PostgreSQL

### ISSUE THREAD

**Issue by p-o-grishin** [serge-rider/dbeaver#2549]
Let's make table and fill it with some data :

CREATE TABLE public.try (
  id INTEGER NOT NULL,
  qwe TEXT,
  arr INTEGER [] )

Now let's "export table data" into "sql insert statement" - we get 

INSERT INTO public.try (id,qwe,arr) VALUES (2,'sdgsg',{2});
INSERT INTO public.try (id,qwe,arr) VALUES (6,'~',{1,2,3});

That's incorrect, arrays should be reflected as  '{data}' , for instance

INSERT INTO public.try (id,qwe,arr) VALUES (6,'~','{1,2,3}');

Attempt to execute a command without sigle quotes will cause an error: 
SQL Error [42601]: ERROR: syntax error at or near "{"
  Position: 51

**Comment by serge-rider** [comment]
It is a bug in array value handler.
Thanks for report.
