### ISSUE TITLE
rename mysql.table failed 

### ISSUE THREAD

**Issue by ericshenjs** [serge-rider/dbeaver#255]
1) connect to mysql
2) select a table in the tree
3) press F2, enter new name, save
The result SQL would look like

RENAME TABLE table.a TO a_old;

That doesn't work for mysql - the word "table" must be there:

RENAME TABLE table.a TO table.a_old;

**Comment by ericshenjs** [comment]
version 3.6.1

**Comment by serge-rider** [comment]
Thanks for report.
