### ISSUE TITLE
Application icon lost

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2550]
After update to 4.2.5. Xubuntu

![default](https://user-images.githubusercontent.com/16996529/33018351-cae8c998-ce41-11e7-8fa1-4724d4be697f.png)

**Comment by jk3us** [comment]
And more annoying is the missing icon in the task switcher thing (this is windows 7):

![image](https://user-images.githubusercontent.com/41621/33029573-91eda4dc-cdde-11e7-9b94-3f5dca96079b.png)

**Comment by carlosspohr** [comment]
Also confirmed on Windows 8/8.1 and 10.

**Comment by serge-rider** [comment]
Thanks for report.
Something went wrong in 4.2.6 product branding configuration.
