### ISSUE TITLE
Import Navicat Connection

### ISSUE THREAD

**Issue by juliardi** [serge-rider/dbeaver#2554]
I am working in a team that mainly uses Navicat for managing database. They often share the database connection using Navicat export feature in XML format. I want to be able to import it from Dbeaver. 
I am aware that there is a Custom Configuration format in File -> Import menu. But, it doesn't recognize the navicat XML format.
It would be a good feature, at least for me, if you can develop this feature.
Also, navicat encrypts the password in their XML, and I've implemented a Navicat password decryptor class in this repository : 
https://github.com/juliardi/how-does-navicat-encrypt-password

Thank you.

**Comment by serge-rider** [comment]
Agreed, this would be a good feature.

**Comment by juliardi** [comment]
I've tried to implements this feature myself, and it worked when i tried to import a navicat connection export file. I will review my code once more, and will send you a pull request when it's done.

**Comment by serge-rider** [comment]
@juliardi Great, looking forward for it

**Comment by juliardi** [comment]
I've send the pull request here #2581. For now, I exclude the password decryption feature because of licensing issue (I ported the Java implementation from another repository which doesn't include any license file).

**Comment by serge-rider** [comment]
I've merged the PR, thanks!
Feel free to create new PR once you will figure out what to do with passwords.

(btw I've added Navicat icon to config importer- to be more consistent with others. Hopefully this doesn't break any other license :) ).

**Comment by juliardi** [comment]
wow, thank you, looking forward for this feature in the next release :)

**Comment by juliardi** [comment]
@serge-rider I've send the pull request here #2617 for navicat password descryption feature. I hope I added the NavicatEncrypt class correctly. Please review it :)

**Comment by serge-rider** [comment]
Merged that too.
Thanks!
