### ISSUE TITLE
Importing plain Postgres backup 

### ISSUE THREAD

**Issue by MesoX** [serge-rider/dbeaver#2557]
Hello!

I was not able to find similiar issue opened, so I am sorry if it is already reported.

When I backup tables and its data to format "plain" it works fine, but when I try to import them back (by Restore function), it says this:
`pg_restore: unknown format of archive "p", supported types are "c", "d" or "t"`

In short: it tries to specifiy non existang flag in pg_dump. As specified here: https://www.postgresql.org/docs/current/static/app-pgrestore.html

> -F format
> --format=format
> Specify format of the archive. It is not necessary to specify the format, since pg_restore will determine the format automatically. If specified, it can be one of the following:
>     c
>    custom
>    The archive is in the custom format of pg_dump.
>    d
>    directory
>        The archive is a directory archive.
>    t
>    tar
>        The archive is a tar archive.

**pg_restore should not be used to restore data in plain format**, as it can't restore them. Documentation specifies:

> pg_restore is a utility for restoring a PostgreSQL database from an archive created by pg_dump in one of the non-plain-text formats.

psql itself should be used to import (restore) plain text with usage something like this:
`psql -U your_user_name your_db_name < your_dump_file`

**Comment by carlosspohr** [comment]
Hi @MesoX ,

Is this issue related to import database dumps through DBeaver ?

**Comment by MesoX** [comment]
Hey @carlosspohr - yes. You can try that yourself - right click schema in Postgres Database and select Backup, use plain format and backup some tables and datas. When you open it, it is plain SQL format. Now, when you go for Restore, you can again choose "Plain" format for restore. But this one doesn't work.

**Comment by serge-rider** [comment]
@MesoX yep, it is a bug. pg_restore doesn't support format `-p` (in opposite to pg_dump). But it is smart enough to get format from file contents.
