### ISSUE TITLE
Error with boolean when inserting from editor

### ISSUE THREAD

**Issue by inibg** [serge-rider/dbeaver#2558]
I'm using MAC OS version 4.2.5 with a PostgreSQL database.
When I try to insert a new record using the grid editor and I have a boolean column, whenever I choose a value (doesn't matter which value) it turns itself into null again, preventing my insert to succeed.

**Comment by serge-rider** [comment]
It is a bug in boolean editor (happens only on MacOS). Thanks for report.
As a workaround you can use panel editor (click on Panels in the bottom toolbar).
