### ISSUE TITLE
attribute columns collapsed together when creating a column

### ISSUE THREAD

**Issue by AlexLuya** [serge-rider/dbeaver#256]
Look like this:
![workspace 1_006](https://cloud.githubusercontent.com/assets/303353/13455093/4b6cffda-e096-11e5-8d42-d54176163e70.png)

My configuration:
Ubuntu 14.04 64bit 
Oracle JDK 1.8.0_72-b15
Eclipse  4.5.1
DBeaver 3.6.0

**Comment by serge-rider** [comment]
Although I can't reproduce that I fixed column resizing algorithm so this issue should be fixed.
If it won't please reopen this issue.

**Comment by AlexLuya** [comment]
This bug still exists in 3.6.2

**Comment by AlexLuya** [comment]
please reopen it

**Comment by serge-rider** [comment]
Could you provide any additional details.
Steps to reproduce would be helpful.

**Comment by serge-rider** [comment]
Ok, I did reproduce this a time ago and added a fix (tables/tree compacting procedure). This was done 3-4 versions ago.
Closing. If you still see this problem - please write/reopen.
