### ISSUE TITLE
SQL Editor - Multiple query - Separator is ";"

### ISSUE THREAD

**Issue by IgorNovozhilov** [serge-rider/dbeaver#2561]
In the current implementation as the delimiter between requests if the request is not allocated manually, that uses an empty new line.
This in some cases leads to errors of query execution.

Example:
```sql
SELECT
    *
FROM

    project;

SELECT
    *
FROM
    repository;
```

if I put the caret cursor in the first query I get a error:
![image](https://user-images.githubusercontent.com/3082812/33113287-bb11d9e2-cf68-11e7-9f79-39f852e78724.png)

By default, in SQL ,to separate queries, use the `;` character.
Maybe to separate the queries in the "SQL Editor" do the same?

**Comment by serge-rider** [comment]
By default both `;` and empty line are query delimiters. But this is configurable: 
![image](https://user-images.githubusercontent.com/6398845/33150049-f6d09fc0-cfe2-11e7-9739-d43dda6b7035.png)

**Comment by IgorNovozhilov** [comment]
In what DBMS you use an empty string as the delimiter between the queries, I don't know?
I think the default setting should be such behavior which leads to the fewest problems when working with any DBMS.

**Comment by IgorNovozhilov** [comment]
I have set this option. From my example, if you put the cursor on the blank line:
![2017-11-23_09h13_09](https://user-images.githubusercontent.com/3082812/33160575-8e48ca26-d02e-11e7-8749-92dbeb100410.png)
sql is not executed

**Comment by serge-rider** [comment]
Yep, it is a bug, thanks for noticing.
