### ISSUE TITLE
Define variable in script

### ISSUE THREAD

**Issue by babbomaria** [serge-rider/dbeaver#2563]
Hello i have in the same panel query a lot 
```

select x,y from tabA where col1=:param1
UNION
select t,u from tabB where col5=:param1 and col6=:param2
```
.....
This works pop upping the variable request panel.
sometimes i have to redo the query a lot of time changing only param1 value so i like the possibility to write at the begin of my query something like

```
def :param1='XXX'
def :param2='YYY'

select x,y from tabA where col1=:param1
UNION
select t,u from tabB where col5=:param1 and col6=:param2
```
This is useful also if I have to do this on multipl DB so i can copy paste the code in a separate tab change only the value and do the query on another DB.

this syntax can be useful also to remember the last value i used.

**Comment by serge-rider** [comment]
You already can do this with command `set`:
@set paramName=paramValue
Like this:
```sql
@set param1='XXX'
@set param2='YYY'

select x,y from tabA where col1=:param1
UNION
select t,u from tabB where col5=:param1 and col6=:param2
```

Is this what you need?

**Comment by babbomaria** [comment]
Yessssss! Perfect Thanks a lot so the variable are pre inizialized! Well!

**Comment by damaresende** [comment]
That is great! What if I want to get the value from a query? Is that possible? I am trying the following but I get an error (ORA-00936: missing expression).

`@set cust_doc = 123456789`
`@set customer = SELECT customer_id FROM customers WHERE  customer_document_no = :cust_doc`

`SELECT subscription_id FROM subscriptions WHERE customer_id = :customer`
`-- many other queries using variable customer`

**Comment by hedersantos** [comment]
Being able to define a variable based on a query result would be awesome in DBeaver.
 I know Workbench/J does it, it's interface is simpler than DBeaver's but it's very helpful and has some powerful features.

**Comment by karatedog** [comment]
It is possible with Version 6.2.0.201909081341.
I haven't checked all the wrong solutions, but if your query returns a single cell, it can be put into a variable. From the previous example:
`@set customer=(SELECT customer_id FROM customers WHERE customer_document_no = :cust_doc)`

**Comment by ClodoaldoPinto** [comment]
@damaresende 
> That is great! What if I want to get the value from a query? Is that possible? I am trying the following but I get an error (ORA-00936: missing expression).
> 
> `@set cust_doc = 123456789`
> `@set customer = SELECT customer_id FROM customers WHERE customer_document_no = :cust_doc`
> 
> `SELECT subscription_id FROM subscriptions WHERE customer_id = :customer`
> `-- many other queries using variable customer`

In this case it is simpler and more performant to build the adequate query:
```sql
@set cust_doc = 123456789
select subscription_id
from
    subscriptions s
    inner join
    customers c on c.customer_id = s.customer_id
where customer_document_nu = cust_doc
```
