### ISSUE TITLE
Error opening a connecting using command line

### ISSUE THREAD

**Issue by pirrimanson2000** [serge-rider/dbeaver#2564]
DBeaver 4.2.5

I'm opening a Oracle connection from command line with this sentence:
`@start dbeaver.exe -con "driver=oracle|name=Test|connect=true|user=test|password=test|port=1521|database=test|host=test.company.com|autocommit=false"`

DBeaver start running and I can see the connection created, but an "Unexpected driver error occurred while connecting to database  java.lang.NullPointerException:" appears opening the connection.

However, if I right-click in the connection (at the connection's tree), select "Edit Connection", click the OK button (without change any parameter), right click again and select "Connect"....it works fine!

It seems that when the "edit connection" dialog is opened something missing is created, allowing the new connection to start working.

Maybe is there some kind of bug related with the connections opening by command line?

**Comment by serge-rider** [comment]
It is a bug in one of the recent versions. 
Thanks for report.
