### ISSUE TITLE
Add Ctrl+Tab in Sql Editor

### ISSUE THREAD

**Issue by luiseduardo** [serge-rider/dbeaver#2566]
When i have many tabs its waste time using mouse to change tabs, Ctrl+Tab its most easy and default in many softwares.
Dont forget the add MRU ;)

**Comment by serge-rider** [comment]
<kbd>CTRL+Tab</kbd> and <kbd>CTRL+Shift+Tab</kbd>were always there (switching editor tabs).
If this doesn't work then check preferences: 
![image](https://user-images.githubusercontent.com/6398845/33177594-3bd4af9e-d074-11e7-9a18-1683306da8a3.png)

**Comment by limex** [comment]
CTRL+Tab and CTRL+Shift+Tab are "nice" but no substitute for MRU. Every serious Dev Env has this option.
