### ISSUE TITLE
PostgreSQL: Not working auto-completion in section ORDER BY

### ISSUE THREAD

**Issue by IgorNovozhilov** [serge-rider/dbeaver#2567]
Not working auto-completion in section `ORDER BY`

in `SELECT`
![image](https://user-images.githubusercontent.com/3082812/33172940-1304ec02-d063-11e7-91aa-8f6d5ad5e403.png)

in `ORDER BY`
![image](https://user-images.githubusercontent.com/3082812/33172948-1cd5544c-d063-11e7-8536-7f8b3ceb05bd.png)

**Comment by IgorNovozhilov** [comment]
so, too, is working
![image](https://user-images.githubusercontent.com/3082812/33173046-a23d402c-d063-11e7-8214-90382dad5e8b.png)

and so - does not work
![image](https://user-images.githubusercontent.com/3082812/33173126-ed0e5b9a-d063-11e7-9037-db6e44de97d8.png)

**Comment by serge-rider** [comment]
Can't reproduce (in my test env all auto-complete works in all cases including order by).
What server and what jdbc driver (version) do you use?
Are there any error in error log (https://github.com/serge-rider/dbeaver/wiki/Log-files) ?

**Comment by IgorNovozhilov** [comment]
> postgresql-9.4.1212.jre7
> `.log` has not errors

The error persists if an empty string is considered a delimiter.
When the checked flag `Blank line is statement delimiter`.
If remove the flag, auto-completion on a new line will work.
> https://github.com/serge-rider/dbeaver/issues/2561

Maybe by default, this flag after the first installation is disabled?

### Example

**inline**
![image](https://user-images.githubusercontent.com/3082812/33255450-ac7c5b92-d35e-11e7-9b94-2cbd95e3cb99.png)

**new line**
![image](https://user-images.githubusercontent.com/3082812/33255455-b6356778-d35e-11e7-8dd7-99f642071f88.png)

**new line, without flag**
![image](https://user-images.githubusercontent.com/3082812/33255722-f8517632-d35f-11e7-9771-9c473c50aadf.png)

**Comment by serge-rider** [comment]
Yep, now I see it. It is actually a more generic error (SQL query extraction).
Thanks for report.
