### ISSUE TITLE
Setting a shortcut for 'set active' on a database doesn't work

### ISSUE THREAD

**Issue by harryshepard** [serge-rider/dbeaver#2568]
When you right click on an database there is 'edit database' bound by default to F4. There is an option for 'set active' as well which I can't seem to bind.

I have searched the bindings for 'active', and have tried setting 'select active project', 'set active project' and 'set active object' but none of them seem to do it.

ctrl+0 seems to be the closest but instead of just setting the selected database, you get a popup and have to double click the one you want, which is slower than just right clicking then choosing active.

I think double clicking on a connection/database should have set active and expand as the default option, rather than opening the properties, because realistically who needs to do that on a regular basis?

If there is a way to change the double click functionality on the database name (to set active and expand, or if that isn't possible just set active is fine) please let me know

**Comment by serge-rider** [comment]
Set active object wasn't bound to actual command. 
I'll link it and set default shortcut to <kbd>CTRL+SHIFT+A</kbd>
