### ISSUE TITLE
PostgreSQL: only raised error is shown

### ISSUE THREAD

**Issue by Vlczech** [serge-rider/dbeaver#2572]
In postgresql connection there is not shown notices or warning. I have procedure which raises many concrete warnings if whatever is bad. At the end of procedure there is raised error in case when whatever was bad. But DBeaver shows only this error and not shows these warning/notices despite the fact, that I added following line to the first line of SQL editor with procedure:

`SET client_min_messages TO warning;`

**Comment by serge-rider** [comment]
Generally DBeaver shows all warnings on Output log tab.
But ff it is not - could you post a sample SQL to check this.

**Comment by Vlczech** [comment]
Hello,
here you have some example:

```
CREATE OR REPLACE function no_notice_shown() RETURNS VOID AS
$$
BEGIN
  FOR i IN 1..100 LOOP
    RAISE NOTICE 'i = %', i;
  END LOOP;
--  RAISE EXCEPTION 'No notice shown in log...';
END;
$$
LANGUAGE plpgsql;

SELECT no_notice_shown();
```


This code show notices, but if you uncomment RAISE EXCEPTION row, no notices are shown..

**Comment by serge-rider** [comment]
Yep, it was a bug in DBeaver. Thanks for report.

**Comment by JamesInform** [comment]
Currently using version 5.1.3.

It seems that the issue is back. No notice is displayed in DBeaver's output tab!

**Comment by chichivica** [comment]
```
DO $$
DECLARE  
   a integer := 10;  
   b integer := 20;  
   c integer;  
BEGIN  
   c := a + b;
    RAISE NOTICE'Value of c: %', c;
END $$;
```
@serge-rider

**Comment by churuba** [comment]
I am using 5.1.5 and RAISE NOTICE does not how anything in the Output window.

**Comment by serge-rider** [comment]
You should use out view tab in SQL editor:
![image](https://user-images.githubusercontent.com/6398845/44528037-39b08900-a6f1-11e8-95eb-ff7aeaf03dbf.png)

The view you opened in the bottom is legacy and it doesn't work. We'll remove it completely in the next version. Thanks for noticing.
