### ISSUE TITLE
Function-based index description

### ISSUE THREAD

**Issue by danieleangellotti** [serge-rider/dbeaver#2573]
Hi Serge,
in the folder "Indexes" of an Oracle table description, column decription it's not decoded for functional-based indexes. For such type of index, it should be used `DBA_IND_EXPRESSIONS.COLUMN_EXPRESSION` as "column name", although handling a `LONG` field can be a bit annoying.

Thanks.

**Comment by serge-rider** [comment]
Good point.
See fix in the next version:
![image](https://user-images.githubusercontent.com/6398845/33238181-dab2c5ee-d298-11e7-80f2-a5c2cc825f3d.png)

**Comment by shungabubus** [comment]
Hello, it seems this is not a solution either. Now as dBeaver thinks it is an index tries to fetch like one, but it is not the case from what I see:
![image](https://user-images.githubusercontent.com/36946814/63935407-acb7b280-ca5d-11e9-9553-df791e55082c.png)

**Comment by serge-rider** [comment]
@shungabubus Please create new ticket for that
