### ISSUE TITLE
Cannot create view

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2588]
dBeaver: 4.2.6
database: mariadb 10.x
java: 8.x
os: windows 10.x

![dbeaver_error](https://user-images.githubusercontent.com/3911428/33432029-76ad6716-d5a4-11e7-982c-a7eca6588130.png)

In view list, I right click, create new view, then the error pops.

**Comment by sirber** [comment]
also cannot add new column. same error.

**Comment by serge-rider** [comment]
Sounds like a bug but I can't reproduce it.
Perhaps this happens after some other actions.

Could you provide steps to reproduce/gif/video?

**Comment by sirber** [comment]
Installed 4.2.6. 

Add column: OK
Add view: got the error.

**Comment by sirber** [comment]
[2017-11-30 at 17-25-57.zip](https://github.com/serge-rider/dbeaver/files/1519687/2017-11-30.at.17-25-57.zip)

Yeah... a video in a ZIP...... :/

**Comment by serge-rider** [comment]
I've been able to reproduce similar issue (but not exactly the same as on video). Kind of UI glitch.
Thanks for report, will try to fix in the next version.

You could retry to create view again or to expand Views node in the navigator (on the left panel) and click Create View there.

**Comment by sirber** [comment]
Same error using the left tree menu.

**Comment by serge-rider** [comment]
See fix in 4.3. And thanks for detailed report.

**Comment by sirber** [comment]
Thank you!
