### ISSUE TITLE
The generated postgres DDL of altering column is wrong 

### ISSUE THREAD

**Issue by AlexLuya** [serge-rider/dbeaver#259]
If trying to add a column,right ddl must be 

````sql
ALTER TABLE public.staff ALTER COLUMN id_natural TYPE int8 NOT NULL;
````

but dbeaver will generate 

````sql
ALTER TABLE public.staff ALTER COLUMN id_natural  int8;
````

as you can see that key works "Type" missed in generated DDL,and "NOT NULL" shouldn't be presented

**Comment by serge-rider** [comment]
What database?

**Comment by AlexLuya** [comment]
postgres,as described in issue's title

**Comment by serge-rider** [comment]
Yes, PG alter table isn't actually working. In opposite to other databases it can't change all column's properties with one query.

**Comment by wwhai** [comment]
![image](https://user-images.githubusercontent.com/20577297/59663411-91b8fe80-91e1-11e9-9789-98edf44c5dd2.png)
when I define a key,Dbever cause such excepton,how to resolve this problem?
