### ISSUE TITLE
HANA DDL 

### ISSUE THREAD

**Issue by hammeronthenet** [serge-rider/dbeaver#2596]
Hi,
when I try to get view/procedure DDL I obtain, on the SQL Preview :

-- Source code not available;

Is that a driver problem or what?

Thanks!

**Comment by serge-rider** [comment]
Yes, it is driver configuration problem. 
Views/procedures DDL aren't available because DBeaver doesn't know how to read DDL from system tables.

**Comment by hammeronthenet** [comment]
Ok... are there a workaround to solve this issue?
Thank you!

**Comment by serge-rider** [comment]
No, there is no workaround at the moment.
This feature just need to be implemented. I'm not very familiar with HANA, if somebody will assist with SQL queries which read DDL - this feature may be included in one of the next versions.

**Comment by hammeronthenet** [comment]
Okay not a big problem, if you want I can find a solution and I can send
you the  queries. Today or in the next days when I have a little free time
I can see that for you.

Il mer 6 dic 2017, 23:12 Serge Rider <notifications@github.com> ha scritto:

**Comment by serge-rider** [comment]
That would be helpful, thank you.

**Comment by hammeronthenet** [comment]
Hi,
I wrote two base query about retrieving DDL scripts for PROCEDURES and for VIEWS.

Please let me know what fields you need to implement at best this functionality in your code ;).

PROCEDURE:

SELECT SCHEMA_NAME,PROCEDURE_NAME,DEFINITION FROM SYS.PROCEDURES 
WHERE SCHEMA_NAME = '<SCHEMANAME>' and PROCEDURE_NAME = '<PROCEDURENAME>'


VIEWS:
select SCHEMA_NAME,VIEW_NAME,'create view "'||SCHEMA_NAME||'"."'||VIEW_NAME||'" as ' || DEFINITION || ';' as DEFINITION
from SYS.VIEWS
where SCHEMA_NAME='<SCHEMANAME>' and VIEW_NAME='<PROCEDURENAME>';


Please, note that HANA is case sensitive by default and that uppercase object name could be wrote without    "  char, but lowcase or "mixedcase" objects had to be wrote with  "  char (ie. column name BIGCOLUMN, or column name "BigColumn")

Let me know what else you need.

Regards.

**Comment by hammeronthenet** [comment]
Please, note that the SCHEMA_NAME /VIEW_NAME / PROCEDURE_NAME in the where clause need to be used (obviously) as paramenters, passing:

SCHEMA_NAME: the name of current schema (database)
PROCEDURE_NAME: the name of the procedure
VIEW_NAME: the name of the view

Regards.

**Comment by serge-rider** [comment]
@hammeronthenet Thanks!

**Comment by serge-rider** [comment]
Will be added in the next version. I can't validate because I don't have access to a live HANA instance.

Could you check it in EA version: https://dbeaver.jkiss.org/files/ea/ ?

**Comment by hammeronthenet** [comment]
Hi, I download the zip files but I've got some errors (dbvear doesn't
start).
Maybe it could be something in my configuration? Do you need the log?

I don't install the "setup" because I use DBvear in "production" at the
moment and I'm in plain migraton of a database (MSSQL to HANA).

At limit: when I stop with this job activity I can install E.A. without any
problem, but this I don't know when (the next week?)

Il giorno mer 13 dic 2017 alle ore 05:19 Serge Rider <
notifications@github.com> ha scritto:

**Comment by hammeronthenet** [comment]
Hi,
Iive installed  dbeaver-ce-4.3.0-x86_64-setup.exe but I don't see anything new for HANA DDL.

Is 4.3.0 the correct version?

Thank you.
