### ISSUE TITLE
Enhacement: Show reference values when inserting or updating a Foreign Key

### ISSUE THREAD

**Issue by mquintas** [serge-rider/dbeaver#2598]
Hi, a good feature that dbeaver dont have is the ability to choose the possible values when editing a field that is a foreign key to another table.
HeidiSQL has a feature similar to this, when you edit a field shows a dropdown with available values from the parent table, together with a description (I guess it shows the first string column as some kind of description).

**Comment by serge-rider** [comment]
DBeaver supports this. Moreover you can define custom description for dictionary tables. 
Just open value view panel:
![image](https://user-images.githubusercontent.com/6398845/33568405-63c131fa-d937-11e7-814d-00f0b27fc48c.png)

**Comment by mquintas** [comment]
Awesome!
I wasn't aware of that feature!
Thanks!

**Comment by AlphaBravo777** [comment]
Is there any way to make the foreign key value (in this example) in the table view show the value of the foreign key. Meaning, it shows "English" instead of 1? I have been pressing every button and have been going into every menu but I do not find it...
