### ISSUE TITLE
Derby: contents of CLOBs/BLOBs get truncated in result view

### ISSUE THREAD

**Issue by ch-me** [serge-rider/dbeaver#260]
I just tried the new Option "cache BLOB values" in DBeaver 3.6.1 and contents of BLOBs are now showing up in result view, but they are truncated at 8192 bytes for BLOBs and around 4k for CLOBs. Autocommit is set to off.

I'm still recieving messages like these in the error log:
for BLOBs:
`Actual content length (8192) is less than declared: 18392`
for CLOBs:
`Actual content length (3999) is less than declared: 19822`

I think CLOBs did not get truncated in a version of DBeaver around September of last year.

**Comment by serge-rider** [comment]
Can't reproduce. With BLOB caching I can see them in both auto-commit and transaction modes (make sure you enabled BLOB caching for this particular datasource).
What Derby version do you have? And specific options?

**Comment by ch-me** [comment]
I've tested it using Derby 10.12.1.1 in embedded mode using a fresh install of DBeaver 3.6.1.

Right after inserting data into the table it seems fine, but when refreshing the table or restarting DBeaver, I get those warnings written in my first post and the content is truncated.

Yes I enabled BLOB caching for this datasource and I think I don't have any specific options (see below).

The schema I'm using:
`CREATE TABLE APP.NEWTABLE (`
`	ID INTEGER NOT NULL DEFAULT 0,`
`	COLUMN1 CLOB(10000000),`
`	COLUMN2 BLOB(10000000),`
`	CONSTRAINT NEWTABLE_PK PRIMARY KEY (ID)`
`);`

Here is my datasource configuration:

`<data-source id="derby-1533c78b487-6c27a58df8730234" provider="generic" driver="derby" name="Derby - test2" create-date="1457008511986" update-date="1457008527360" save-password="true" show-system-objects="true" read-only="false">`
`	<connection server="" database="***\test2" url="jdbc:derby:***\test2" user="" type="dev">`
`		<bootstrap autocommit="true"/>`
`	</connection>`
`	<custom-property name="content.hex.encoding" value="windows-1252"/>`
`	<custom-property name="resultset.edit.key.use_all_columns" value="false"/>`
`	<custom-property name="resultset.binary.editor" value="EDITOR"/>`
`	<custom-property name="resultset.order.serverSide" value="true"/>`
`	<custom-property name="resultset.commit.oncontentapply" value="false"/>`
`	<custom-property name="resultset.maxrows" value="200"/>`
`	<custom-property name="content.memory.maxsize" value="10000000"/>`
`	<custom-property name="content.cache.clob" value="true"/>`
`	<custom-property name="content.cache.blob" value="true"/>`
`	<custom-property name="resultset.commit.oneditapply" value="false"/>`
`	<custom-property name="query.rollback-on-error" value="false"/>`
`	<custom-property name="resultset.binary.stringMaxLength" value="32"/>`
`	<custom-property name="resultset.binary.representation" value="string"/>`
`	<custom-property name="content.cache.maxsize" value="1000000"/>`
`	<custom-property name="resultset.edit.maxtextsize" value="10000000"/>`
`	<custom-property name="keep.statement.open" value="true"/>`
`	<custom-property name="resultset.autofetch.next.segment" value="true"/>`
`	<custom-property name="resultset.maxrows.sql" value="false"/>`
`	<custom-property name="resultset.edit.longaslob" value="true"/>`
`</data-source>`

Driver settings:
`<?xml version="1.0" encoding="UTF-8"?>`
`<drivers>`
`	<provider id="wmi"/>`
`	<provider id="db2"/>`
`	<provider id="generic">`
`		<driver id="derby" category="Derby" custom="false" embedded="true" name="Embedded" class="org.apache.derby.jdbc.EmbeddedDriver" url="jdbc:derby:{folder}" port="" description="Derby (Java DB) embedded driver">`
`			<library type="jar" path="maven:/org.apache.derby:derby:RELEASE" custom="false">`
`				<file id="org.apache.derby:derby" version="10.12.1.1" path="***\.dbeaver\.metadata\.plugins\org.jkiss.dbeaver.core\maven\maven-central\org.apache.derby\derby-10.12.1.1.jar"/>`
`			</library>`
`		</driver>`
`	</provider>`
`	<provider id="mysql"/>`
`	<provider id="oracle"/>`
`	<provider id="postgresql"/>`
`</drivers>`

**Comment by serge-rider** [comment]
Was able to reproduce with big LOBs (bigger than 1mb).
There was a bug in content reading (sometimes derby driver acts pretty strange - depending on actual LOB sizes).
Thanks for report.

**Comment by ch-me** [comment]
Hello, I tested this in version 3.6.2 and retrieving large BLOBs now seems fine - thank you very much for your support!

But unfortunately there still seems to be a bug regarding the caching of larger CLOB values. Their content still gets truncated at around 4k in result view.
