### ISSUE TITLE
&quot; in erd files

### ISSUE THREAD

**Issue by GHNewbiee** [serge-rider/dbeaver#2605]
Hi,

After saving an ER diagram, and opening the file in Visual Studio Code as XML, a lot of `&quot;` appears here and there.

I remove them and refresh the diagram. That's ok, no problem! I make some change on the diagram and save it, again plenty of  `&quot;`s in erd file.

Is it a DBeaver's or VSC's problem? Any idea how to get rid of them once and for all. 

Tia

**Comment by serge-rider** [comment]
DBeaver add quotes to some database identifiers (e.g. those which contain spaces or conflicts with reserved keywords) and saves them in XML attributes.
It is a valid XML requirement to convert all double quotes into `&quot;` string. I'm not sure why do you see them in VSC. Do you edit raw XML?

**Comment by serge-rider** [comment]
Ok
