### ISSUE TITLE
Cannot save Custom criteria in Dictionary structure dialog

### ISSUE THREAD

**Issue by Teelevision** [serge-rider/dbeaver#2608]
**The bug and how I encountered it**

<img width="392" alt="screen shot 2017-12-06 at 16 17 05" src="https://user-images.githubusercontent.com/4125691/33669041-a8cd6960-daa1-11e7-9f38-a41cb0899031.png">

In the **Data** tab of a MySQL table I opened the **Value viewer** panel. In this panel it shows me a dictionary if I select a foreign key value in the **Data** tab. By clicking **Define Description** I open the **Dictionary structure** dialog as seen in the screenshot above. Changing the value of the **Custom criteria** field (without changing the **Columns** list) does not enable the **OK** button as I would expect.

DBeaver Community 4.2.6 installed via homebrew on macOS 10.13.1

**Why I think this is a bug**

The **Custom criteria** is more powerful than the **Columns** list and therefore is an alternative input rather than a supplementary input. It should be possible to ignore the **Columns** list entirely. In my case I tried to write a custom nested select.

**Workaround**

Workaround is to first select some value from the **Columns** list which enables the **OK** button, and then edit the **Custom criteria**. Note that this first erases all values from the **Custom criteria** input.

**Comment by serge-rider** [comment]
Yep, it is a bug. Will be fixed in the next version.
Thanks for report.
