### ISSUE TITLE
Cassandra: NULL-Value in Date and UDT Columns

### ISSUE THREAD

**Issue by travolta217** [serge-rider/dbeaver#261]
After the issue https://github.com/serge-rider/dbeaver/issues/236 was fixed, another issue with cassandra driver came in. All date and udt fields are NULL!!
![2016-03-03 14_19_44-dbeaver enterprise - general - compare_log_aggregate](https://cloud.githubusercontent.com/assets/16934306/13495522/85f44e00-e14b-11e5-95e9-08f209111fc1.jpg)

**Comment by serge-rider** [comment]
Date and time data types (new in Cas3) handler will be fixed in the next version.
Can you provide me some example with UTD types?

**Comment by travolta217** [comment]
In our case these are JSon-Objects.

**Comment by serge-rider** [comment]
3.6.2 will include major update of Cassandra plugin (for 3.x version).
Including UDT and new metadata objects support.
