### ISSUE TITLE
Oracle, not show all tables

### ISSUE THREAD

**Issue by kristking** [serge-rider/dbeaver#2611]
Hi,
We are currently looking for a free or cheaper tool to replace the "TOAD for Oracle", however when testing DBeaver I realized that it does not show all the tables of a scheme, of the 25 tables it only shows 11.
we are using Oracle 11g, you have to configure something or it is because it is the free version.

**Comment by serge-rider** [comment]
Hello,

There are no limitations in DBeaver CE. All tables should be visible.

Is there anything special about these tables? Maybe you mean views/materialized views?

**Comment by kristking** [comment]
YES!!!! I found the "problem", it happens that there are several db with their accounts, and each account has permissions to some of the tables in those accounts. Then enter with an account that had permission to some tables of that account. XD my mistake

**Comment by serge-rider** [comment]
Thanks for info
