### ISSUE TITLE
Update WIki Develop in Eclipse

### ISSUE THREAD

**Issue by danydev** [serge-rider/dbeaver#2612]
This [wiki page](https://github.com/serge-rider/dbeaver/wiki/Develop-in-Eclipse) should be updated, if you import it with "General->Existing projects into Workspace" the project will not compile out of the box, you need to open it as a "Maven->Existing Maven Project" to let Eclipse build successfully.

Also, do you have any hint to be able to work with IntelliJ? I was not able to make it working with it (in particular it looks like the classes are not correctly found in the class path).

**Comment by serge-rider** [comment]
Ok. 
Generally current wiki instruction works. But if you have any thoughts about its improvements - please share.
