### ISSUE TITLE
Feature request: export blob as file

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2618]
Would be great to have an easy way to save / load a blob to/from a file.

![image](https://user-images.githubusercontent.com/3911428/33780365-78e40ac8-dc1e-11e7-91b5-aa47fb1d737d.png)

DB: MariaDB 10.x

**Comment by serge-rider** [comment]
This feature is already there. Right lick on the cell->Save to file.

**Comment by sirber** [comment]
Oh, I wasn't sure what it would save in the file.
On insert, can I upload a file into it?

**Comment by serge-rider** [comment]
Sure

**Comment by sirber** [comment]
Alright, thank you!

**Comment by tz3tzis** [comment]
@serge-rider what about multiple saving of files? From what i understand saving a compressed file with a .zip extension works as expected. When i try to save multiple compressed files i only get the first file. Not sure if this behavior is the same for uncompressed files.

**Comment by mugshepherd** [comment]
This now seems to be Right Click:  Edit -> Save to file

**Comment by thanh-guong** [comment]
How can I export all the blobs in a table, and export all the files for each table row?

**Comment by E1izabeth** [comment]
@thanh-guong, I guess you can use data export. To export blobs as files you can choose option 'Save to files'. To export part of the data from the table you can use 'Selected columns only' and/or 'Selected rows only'.
![image](https://user-images.githubusercontent.com/28875055/168604450-1fcd52b0-0a47-4262-8db3-552e91ea8d69.png)

**Comment by thanh-guong** [comment]
Thanks for answering @E1izabeth, but I didn't explain myself well. I have a column for filenames, and a column with blob. I need to export the blobs in files with the corresponding filename.

**Comment by E1izabeth** [comment]
@thanh-guong 
There is no such option for now

**Comment by thanh-guong** [comment]
Thank you so much for answering me!

**Comment by markus-franke** [comment]
Looks like this feature is broken if DBeaver is installed via snap. I reckon that this might have something to do with the "/tmp" folder being used differently in this environment but I am not sure.
