### ISSUE TITLE
Expand the Documentation

### ISSUE THREAD

**Issue by cniweb** [serge-rider/dbeaver#262]
Expand the Documentation or Wiki or User Guide.
The following points should be described. Top with screenshots:
 - Steps to connect to a database
 - Discontinuation of a SQL command
 - Presentation of results

Thanks,
Chris

**Comment by serge-rider** [comment]
Working on it

**Comment by carlosjrcabello** [comment]
@serge-rider ,

If you want, I can help you on it, just give me what you want that i'll help you.

**Comment by codebling** [comment]
@cniweb did you have issues figuring out how to do the actions that you listed?  If so, it would be helpful to know your thought process. For example, if you had specific expectations about how something would work or where an option or button would be placed, that would be valuable to know about. 

I personally always prioritise the useability and "obviousness" of a user interface over documentation. As a contrived and made up example, if you had to access the menu Navigate -> Objects -> Databases -> New Connection to create a new connection and people had trouble finding this, it would make more sense to add a "New Connection" button in the main toolbar than to create documentation explaining how to create a new connection, as in the latter case it not only makes it harder for to use the software, but also makes the software harder to maintain for the developer. Does this make sense?  Just explaining why I'm asking.

**Comment by cniweb** [comment]
I meant, how to run a SQL command.

**Comment by cniweb** [comment]
Best to implement the documentation as Eclipse help

**Comment by serge-rider** [comment]
Initial documentation will be in GitHub wiki (https://github.com/serge-rider/dbeaver/wiki)
Then, maybe, it will be converted into Eclipse help.
Unfortunately docs writing is a time eater task and I don't have much time for it.

**Comment by serge-rider** [comment]
DBeaver help system now just references GitHub wiki pages.
