### ISSUE TITLE
Firebird: configure 2.x and 3.x drivers

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#2620]
It seems that Firebird (Jaybird) drivers aren't forward-backward compatible.
Thus we'll need two separate drivers configurations for them.

**Comment by serge-rider** [comment]
I wasn't able to make 3.x driver work with my older 2.x FB server. 
Perhaps this was resolved in recent driver versions, need to check this.

**Comment by mrotteveel** [comment]
I'm the maintainer of Jaybird and Jaybird 3 has worked with all Firebird versions in all 3.0.x versions. But if you have a reproducible case where it doesn't work, I'd be happy to know and fix it.

**Comment by serge-rider** [comment]
+I've tested it one more time. Looks like 3.0.3 driver works fine with all FB versions. 
I'll make it default and replace 2.x driver with 3.x. 
Great job, and thanks for letting know 👍

**Comment by serge-rider** [comment]
BTW could you assist with embedded driver configuration? It needs fbembed.dll and I can't realize where to get it.

**Comment by mrotteveel** [comment]
Firebird embedded is - unfortunately - not a single DLL, it is a collection of dependencies, including `fbembed.dll` for Firebird 2.5 and earlier, and `fbclient.dll` for Firebird 3 and later (+ a number of additional .dlls and files).

For Firebird 2.5, see https://www.firebirdsql.org/en/firebird-2-5/ (and then the 32 bit or 64 bit embedded kit).

For Firebird 3, see https://www.firebirdsql.org/en/firebird-3-0/. You need to use the normal Firebird 3 zipkit download (you can remove a lot of files like executables). See my blog post [Jaybird with Firebird embedded example](https://www.lawinegevaar.nl/firebird/jaybird_embedded_example.html) for details on the necessary files.

If you need more information, let me know.

I have plans to try and package Firebird embedded in a 'self-deploying jar', but I haven't had the time to implement that yet.

**Comment by mrotteveel** [comment]
@serge-rider I will keep you informed.

The complexity of dependencies of Firebird Embedded is also my beef with it, and the core developers of Firebird actually made it even more complex with Firebird 3 than with earlier versions :(

**Comment by hktalent** [comment]
#4796
