### ISSUE TITLE
Firebird - Unique Keys is not shown if it is not PK

### ISSUE THREAD

**Issue by Navodar** [serge-rider/dbeaver#2625]
In TableView on tab 'Unique Keys' only  Primary Key is shown, though DDL clearly show existance of anothet two Unique Keys aside PK.
![dbeaver](https://user-images.githubusercontent.com/1892822/33899237-2decf8f4-df6b-11e7-95f7-f4748406860d.png)

**Comment by serge-rider** [comment]
There are no two other unique keys but there are two other unique indexes. 
Check Indexes tab.

**Comment by Navodar** [comment]
Ah, my bad. I believed I've created keys. Thanks.
