### ISSUE TITLE
MSSQL: Schema list is incorrect on non-master DBs

### ISSUE THREAD

**Issue by ebelew** [serge-rider/dbeaver#2626]
Given a MSSQL Host, using the JDBC driver,  
When I expand the DB in the `Database Navigator` . 
Then the schemas available in `master` show for all DBs, and    
   All user schemas on non-master DBs are missing.

Expected behavior:
Each DB would have its own schema list. 

Repro Steps:
Create new schema in `master` db, refresh connection or DB schema list. New schema shows on all DBs, not just master.

**Comment by serge-rider** [comment]
It is a limitation of SQL Server JDBC drivers. 
But we can try some workaround (e.g. switch active database before reading schemas)

**Comment by serge-rider** [comment]
In 4.3.1 DBeaver will use custom query to read schema list (as underlying driver return incorrect schemas).
