### ISSUE TITLE
Format - Index out of bounds 

### ISSUE THREAD

**Issue by kawinga** [serge-rider/dbeaver#263]
Hello,

after using "Edit - Format - Format SQL" i get an "Index out of bounds"-error.

Log-File: [format.txt](https://github.com/serge-rider/dbeaver/files/157028/format.txt)

Java 1.8.0_73

Kind regards,

Robert

**Comment by carlosjrcabello** [comment]
Hi @kawinga ,

What's database you were/are using? I'll try to reproduce here.

**Comment by serge-rider** [comment]
Duplicate of  #242.
Will be fixed in the next version.
