### ISSUE TITLE
PostgeSQL Child table sorting broken 

### ISSUE THREAD

**Issue by StepanYankevych** [serge-rider/dbeaver#2630]
dBeaver 4.3.0. PostgreSQL 9.6 /10.1
![image](https://user-images.githubusercontent.com/25589816/33936945-14b865cc-e00a-11e7-9564-99ecffa096ba.png)

Child tables are sorted in random order ? 
See screen shot

**Comment by serge-rider** [comment]
Thanks for report. See fix in 4.3.1.
