### ISSUE TITLE
PostgreSQL table DDL generation - missed tablespace

### ISSUE THREAD

**Issue by StepanYankevych** [serge-rider/dbeaver#2631]
dBeaver 4.3.0 PostgreSQL9.6 / 10.1
Tablespace information missed in the output script while DDL generarion. 
Stesp to reproduce 

CREATE some TABLESPACE. Let it be arch_data
CREATE TABLE sy_test
(
    F1 int
)
WITH (
    OIDS = FALSE
)
TABLESPACE arch_data;

Right click on sy_test chose generate SQL->DDL

tablespace info is missed in the output script

**Comment by serge-rider** [comment]
Yep, thanks for noticing.
See fix in the next version.
