### ISSUE TITLE
Search in Procedures like Tables

### ISSUE THREAD

**Issue by PatriciaGomesB** [serge-rider/dbeaver#2632]
It is possible to show only the result of the search in Procedures like it is done in Tables?

![imagem](https://user-images.githubusercontent.com/18722810/33949239-f3e8d496-e020-11e7-8a33-fee1d46e3e24.png)

**Comment by serge-rider** [comment]
No, currently quick filters work only  for tables/views. But you can use navigator filter (from context menu) or inline filters in Procedures editor (double-click on Procedures item -> <kbd>ctrl+f</kbd>).

**Comment by serge-rider** [comment]
I'll add filtering of procedures and sequences in the next version.
