### ISSUE TITLE
FIX extended cell editor does not Save the correct cell if cell selection changes in Data view

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2634]
## use case

I have to edit multiple large text cells concurrently.
I select a cell from Row 1 and hit Shift+Enter to open the extended cell editor.
I select a cell from Row 3 and hit Shift+Enter to open the extended cell editor.
I select a cell from Row 1337 and hit Shift+Enter to open the extended cell editor.
Now I have 3 extended cell editors open
I edit something in the Row 1 extend cell editor and hit Save

## expected result

The edited Row 1 cell contents is saved in the cell at Row 1

## actual result

The edited Row 1 cell contents is saved in the cell at Row 1337, because it this cell is selected in the Data view. Or any other random cell selected in a random column for that matter.

### severity

🔥💣☢

**Comment by serge-rider** [comment]
Check fix in EA: https://dbeaver.jkiss.org/files/ea/

**Comment by allanlaal** [comment]
I can confirm that this issue is fixed in EA
