### ISSUE TITLE
Use Data Editor standalone?

### ISSUE THREAD

**Issue by rspitzde** [serge-rider/dbeaver#2637]
Is it possible to use DBeaver's Data Editor in a "standalone" fashion to provide a user with an editable grid just for one table and hide everything else, like connections, properties etc.? 
I have a requirement to replace an existing scenario where a user utilised MS Access to create an editable grid for an Informix table via ODBC. Now the user is being migrated to a virtual desktop where ODBC Drivers cannot be installed. JDBC has been used in these virtual desktops before, so maybe DBeaver could do the job, but is there a way to start DBeaver so that just the Data Editor with the contents of this one table is displayed?

**Comment by serge-rider** [comment]
Potentially yes, it is possible (to close all views but the editor and maybe even hide main menu/toolbar). 
But there is no such mode currently. And no such command line parameter.

It doesn't sound like something very complicated but honestly this is not very common feature.

**Comment by rspitzde** [comment]
Thanks, will investigate other possibilities.
