### ISSUE TITLE
FIX Database Tables view: selecting multiple tables and pressing Enter should open all selected tables #UX

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2639]
## Use case

in Database Navigator: doubleclick on a database to open it.
click on Tables
select multiple tables
A: right click → Edit Objects
B: hit Enter

## Expected results

B = A = all selected tables opened as tabs

## Actual results:

A = all selected tables opened as tabs
B = only first selected table is opened up as a tab

**Comment by serge-rider** [comment]
Good point

**Comment by allanlaal** [comment]
this fix isn't in EA atm, is EA like a nightly build or was it just for testing #2634 ? :)

**Comment by allanlaal** [comment]
@serge-rider issue fixed in Navigator in 4.3.1, but still persists in Data Editor. 

## Use case

in Database Navigator: doubleclick on a database to open it in Data Editor
* go to Data Editor → database name → Properties → Tables
* select multiple tables
* hit Enter

## Expected result

all selected tables opened as tabs

## Actual result

only first selected table is opened up as a tab

**Comment by serge-rider** [comment]
@allanlaal yep, that's another bug
