### ISSUE TITLE
Postgres Foreign Tables

### ISSUE THREAD

**Issue by bsandro60** [serge-rider/dbeaver#264]
After upgrading to 3.6.0 or 3.6.1 dbeaver does not list the tables in the schema defined as FOREIGN TABLE.
Downgrading to version 3.5.9 is ok.

**Comment by serge-rider** [comment]
Foreign tables support will be added in the next version.
Thanks for report.

**Comment by bsandro60** [comment]
Thanks
What is the release date of version 3.6.2?

**Comment by serge-rider** [comment]
You can see approximate release dates in milestone details.
https://github.com/serge-rider/dbeaver/milestones

**Comment by TheoLechemia** [comment]
Hello,
I'm in 6.1.1 (Ubuntu) and I cannot see my foreign tables. 
Can you tell me how to display them ? Cannot find it in the doc.

Thanks
