### ISSUE TITLE
Oracle queue management

### ISSUE THREAD

**Issue by kalenderdose** [serge-rider/dbeaver#2640]
Hi,
i cant find the oracle queues or queue tables.

**Comment by serge-rider** [comment]
Queue tables are in the same list where regular tables are.
Queues are not yet supported.

**Comment by efradkin** [comment]
Initial Oracle queues support is implemented:
![image](https://user-images.githubusercontent.com/16664546/34245456-00eb4c44-e63b-11e7-9155-f6b93a37c986.png)
They are read-only now.

**Comment by serge-rider** [comment]
@efradkin 👍
