### ISSUE TITLE
ADD set custom window title prefix label per window

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2641]
## Problem:

I usually have 5..11 Dbeaver windows open on 32 desktops and often there are ≥2 Dbeaver windows per desktop, so it is difficult to distinguish between say Live and Dev windows in window selector without opening the windows

## Solution:

Please add a menuentry: Window → Label, which prefixes the Label to the current window title (without separator or spaces - they should be entered by the user [this way the user can set a supercompact prefix, might even be a UTF-32 character for extremists like me]). 
A keyboard shortcut would also be much appreciated :)

**Comment by serge-rider** [comment]
This is already supported:
![image](https://user-images.githubusercontent.com/6398845/34074638-85c8db9a-e2c4-11e7-8e8e-b52e7bd33f31.png)

And you can play with other window (workspace) title options, it is quite flexible.

**Comment by allanlaal** [comment]
it seems that this feature adds the workspace name after the app name:
`DBeaver 4.3.0 - <here> - General - some_table_name`

would it be possible to move this to the front? This way the custom prefix can be seen in any window selector even if one has more than a few windows open, so only the first few letters of each window are visible:
`<here> - DBeaver 4.3.0 - General - some_table_name`

its the same UX logic as browsers putting the tab title before the browser name in their window names

**Comment by serge-rider** [comment]
Agreed.

**Comment by allanlaal** [comment]
unable to set labels, but this will be in 4.3.1
