### ISSUE TITLE
Schema null in Schemas and no data shown

### ISSUE THREAD

**Issue by lidderupk** [serge-rider/dbeaver#2645]
Hi, 

I am using dbeaver to connect to DB2. I am able to successfully and "test connection", but the database does not have any schemas in it. Dbeaver just shows "Schema null". Any ideas? Thank you.

![image](https://user-images.githubusercontent.com/3187457/34020116-4a279da8-e0e7-11e7-9167-663feb0368eb.png)

**Comment by serge-rider** [comment]
Looks like DB2 driver issue. Try to download db2jcc4 driver (from http://www-01.ibm.com/support/docview.wss?uid=swg21363866).
![image](https://user-images.githubusercontent.com/6398845/34027054-4f4a1516-e16b-11e7-9353-0dbcda859d39.png)

BTW what is your DB2 server version?

**Comment by lidderupk** [comment]
@serge-rider: that worked. I don't know the db2 version, but the latest driver worked. Thank you very much !
