### ISSUE TITLE
Add setting to show Triggers at Table/Views/etc level in DBeaver Database Navigator

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2646]
DBeaver - **Version 4.3.0 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1**
Database Server: **Microsoft SQL Express 2014**

Of couse it is a personal preference. But I would like to see a setting in _DBeaver_ that had the effect when set that I could see all database triggers at the same level in the _Database Navigator_ as Tables/Views/etc.

In my _SQL Server_ database, instead of viewing triggers in:

```
Connection
  Database
    dbo
      Tables
        TableA
          Triggers
            OnTableATrigger
            ...
      Views
      Indexes
```

I would like to view in _Database Navigator_ (after change of setting) in _DBeaver_:

```
Connection
  Database
    dbo
      Tables
      Triggers
        OnTableATrigger
        OnTableBTrigger
        OnTableCTrigger
        ...
      Views
      Indexes
```

**Comment by serge-rider** [comment]
This is already supported for MySQL, Oracle and some other databases.
But not for Generic driver (and SQL Server which uses it).

It is not configurable but works in both ways - you can see triggers under tables AND as global trigger list (in schema).

**Comment by serge-rider** [comment]
This feature will be added in the next version. 
Note: it'll be a bit slow (as it will read triggers from all underlying tables one by one).
