### ISSUE TITLE
Disable suggestion list tooltip

### ISSUE THREAD

**Issue by busyscout** [serge-rider/dbeaver#2647]
When I press Enter key to select suggested word from dropdown list, this word is being shown in tooltip (see screenshot).
The problem is this tooltip is being shown for a significant time (until I click mouse on it etc) and it hides some of the previous text. It is very disturbing IMO.
Is it possible not to show this tooltip at all?

![dbeaver keywords tooltip](https://user-images.githubusercontent.com/23096209/34039806-20ce52c4-e1a2-11e7-933a-27a70a94f31e.png)

**Comment by serge-rider** [comment]
Agreed, these tooltips don't make sense.
