### ISSUE TITLE
MS SQL:  Creat/Edit Table Unable to create unique key.

### ISSUE THREAD

**Issue by prog-rajkamal** [serge-rider/dbeaver#2654]
**Steps to reproduce:**

1. Connect to SQL Server instance.
2. Select database -> schema -> Tables.
3. Right click on "Tables" and select "create new table".
4. Under the heading, "Unique Keys". right click and select "create new unique key"
![dbeaver_sql_server_error_step4](https://user-images.githubusercontent.com/11518519/34077201-bf9c725a-e323-11e7-8c3f-65dfe31a9e42.png)

**Expected Result:**
The Dialog box has option to create UNIQUE Key

**Actual Result:**
The Dialog box has Key Type set to "Primary Key" and is disabled 

![dbeaver_sql_server_error](https://user-images.githubusercontent.com/11518519/34077200-bc6d410e-e323-11e7-9796-13b6e196dc98.png)

**Comment by serge-rider** [comment]
In fact you still can create unique key (just select columns and click Ok).
I'll fix this confusing combobox disablement.

**Comment by prog-rajkamal** [comment]
@serge-rider I tried that. 

It added the unique key as another "Primary key".  Which, for obvious reasons, fails when trying to persist changes to Database.

**Comment by serge-rider** [comment]
Yep, thanks for noticing.
Unique key was missed in generic driver dialog.
