### ISSUE TITLE
SQL Error: Internal jdbc driver error

### ISSUE THREAD

**Issue by sirber** [serge-rider/dbeaver#2656]
https://pastebin.com/J0xe3sVe

When I ran a query from a query tab conncected to a mariadb database.
The query was to return a lot of data (20 000 000+ rows) to be use then in a CREATE TEMPORARY TABLE.
I did not add a LIMIT, but usually the editor adds a LIMIT 200 by default?

**Comment by sirber** [comment]
If I add a LIMIT 200 or 400 to the query, no crash and I get 200 rows, even with LIMIT 400.
If i remove the limit, crash! :)

**Comment by sirber** [comment]
Also, dbeaver uses 1.2GB RAM

**Comment by serge-rider** [comment]
You can enable LIMIT n preferences.
Perhaps we need to enable it by default..

![image](https://user-images.githubusercontent.com/6398845/34123284-1629353c-e440-11e7-9215-012c94d64673.png)

**Comment by sirber** [comment]
Indeed, it wasn't checked.
But often when I query it limits auto at 200 row, when I scroll it fetches 200 more. How come?

**Comment by serge-rider** [comment]
This is MySQL/MariaDB JDBC driver trick. 
Actually it reads all rows and then limits them on client side.
Let's try to enable this option for MySQL and MariaDB by default.

**Comment by sirber** [comment]
alright, thank you!

Stéphane B.

2017-12-18 14:41 GMT-05:00 Serge Rider <notifications@github.com>:

**Comment by sirber** [comment]
Will 4.3.1 set it by default in already installed dBeaver?

**Comment by serge-rider** [comment]
Yes (for MySQL and MariaDB only)

**Comment by sirber** [comment]
I have the above check checked, still get the error with dBeaver 4.3.1.
![dbeaver_error_java_heap](https://user-images.githubusercontent.com/3911428/34612891-a25416f0-f1f9-11e7-9209-a3b7439f8fd2.png)

**Comment by serge-rider** [comment]
That's odd.
Just tested against table with 20M of rows - select doesn't consume any extra memory and was executed in 1ms.
And it doesn't matter is option "Use SQL to limit fetch size" is on or off.
![image](https://user-images.githubusercontent.com/6398845/34621342-d3da51c0-f259-11e7-9ce5-ba04d4af4bee.png)

Could you post debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files) - here or on serge@jkiss.org?

**Comment by sirber** [comment]
sent via email!

**Comment by serge-rider** [comment]
Thanks. Meanwhile - could you try to use MySQL driver against the same server/SQL query?

**Comment by sirber** [comment]
Hum... it does seems I cannot change the driver. I need to make a new connection?

**Comment by sirber** [comment]
Query is running (16M rows). dBeaver's going from 300 MB to 1.1GB+...

**Comment by sirber** [comment]
The query is sent whitout setting a limit:

`/* ApplicationName=DBeaver 4.3.1 - Main */ SELECT 
		send_id, 
		email_id, 
		emarketing_account_id, 
		IF(read_on IS NULL, NULL, true) AS read_on, 
		IF(clicked_on IS NULL, NULL, true) AS clicked_on
	FROM email
	INNER JOIN email_sent ON 
		email.id = email_sent.email_id 
	WHERE email.start_date > '2017-12-05' AND 
		email.type = 'newsletter'`

**Comment by serge-rider** [comment]
Yes. Looks like DBeaver can't parse this query to determine that this is a plain SELECT and to apply limits..
Thanks for details, I'll try to make some workaround.

**Comment by sirber** [comment]
Thank you!

**Comment by serge-rider** [comment]
Could you test this in EA version (https://dbeaver.jkiss.org/files/ea/)

**Comment by sirber** [comment]
200 row fetched (139ms). works!

Stéphane B.

2018-01-05 14:51 GMT-05:00 Serge Rider <notifications@github.com>:

**Comment by serge-rider** [comment]
Great, thanks for testing.

**Comment by sirber** [comment]
Glad to help!

Stéphane B.

2018-01-05 15:05 GMT-05:00 Serge Rider <notifications@github.com>:

**Comment by nopelitas** [comment]
Hola.
Yo tengo el mismo error al querer descargar data. Hice una descarga de 4 años y el sistema colapsó; ahora no puedo descargar data desde la conexión "COMERCIAL". Desde las otras dos, no tengo problema.

![image](https://github.com/dbeaver/dbeaver/assets/167645939/89b0a099-68e8-44f2-8efb-a135c8c84214)

¿Qué puedo hacer al respecto? Intento general mas memoria, pero no puedo ejecutar el comando "C:\Windows\system32>DBeaver>dbeaver.exe-vmargs-Xmx102"

![image](https://github.com/dbeaver/dbeaver/assets/167645939/ff99dade-a556-4f82-9de3-e27ca8de4201)

¿Tendrán alguna solución?
