### ISSUE TITLE
dbeaver 4.3 : Problem connexion ms sql server

### ISSUE THREAD

**Issue by jerherder** [serge-rider/dbeaver#2657]
Hello

in the version free 4.3, when i tried to create a connexion to ms sql server with Active directorty authentication, i have this error

Integrated authentication failed. ClientConnectionId:694006d6-0c2b-4428-b1de-5730e1baebfb
  Integrated authentication failed. ClientConnectionId:694006d6-0c2b-4428-b1de-5730e1baebfb
    Unable to obtain Principal Name for authentication 
    Unable to obtain Principal Name for authentication 

the drivers jdbc are the last available. the connexion works with sql authentication but no windows authentication.

Best regards

**Comment by jerherder** [comment]
in the version 4.0.3, this configuration works.

**Comment by jerherder** [comment]
i find the solution. if you use the 32 bit version, don't load the 64 bits drivers and 32 bits driver together.

i you use 64 bits version, any problem if you have the 32 bits and 6' bits version loaded in the libraries

**Comment by serge-rider** [comment]
Thanks for info
