### ISSUE TITLE
FEATURE REQUEST - Improve That Annoying "Properties" Tab

### ISSUE THREAD

**Issue by tellkonkle** [serge-rider/dbeaver#2663]
I absolutely despise that Properties tab. The columns in it are never sized correctly even when I adjust the following:

Windows > Preferences > Database > Result Sets > Presentation > Calculate column width by cell values

Also, it seems to forget how I last set it. If I collapse it and then exit and re-launch DBeaver, the properties tab will not be collapsed all the way like I left it. I would love to have a setting somewhere that forces that darn thing to always be collapsed until I click the arrows.

![dbeaver-suggestion](https://user-images.githubusercontent.com/18474309/34182487-7c0a8208-e4e4-11e7-9a68-7b062a70c918.jpg)

**Comment by serge-rider** [comment]
Good point.

**Comment by serge-rider** [comment]
Divider position save was fixed.
Also now you can move properties panel in the tab list: 
![image](https://user-images.githubusercontent.com/6398845/34314005-bf41789e-e780-11e7-8a5d-a923de2154b5.png)
