### ISSUE TITLE
ADD shortcut key for setting Workspace name (window title prefix)

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2665]
## Use case

daily need to name and rename multiple DBeaver instance windows
I press a shortcut key and a small dialog should appear, which changes the Preferences → Workspace → Window title → Workspace Name setting and also enables the "Show workspace name" setting if the dialog is not empty

referenced in #2641

**Comment by serge-rider** [comment]
Sounds like a very env-specific feature. I doubt that many people need this.
We can't make commands/shortcuts for every possible action - it will mess preferences.

**Comment by allanlaal** [comment]
the idea is to make adding/renaming/removing labels as fast as possible, because that would mean one could use a new separate DBeaver instance for each task and then just close it - sessions become contextual and can be thrown away after the few minutes/hours they are used, making the main workspace collect less crud - like using Firefox with FireTitle: instead of having a King Window with 700 tabs you have 90 windows with fewer tabs related to only the topic researched :)

However, you make a good point: this might be a fringe use case :(

I'll close this for now - hopefully any new users sharing my pain will subscribe to this ticket and we can revisit this in the future if it gains more traction :+1:

**Comment by allanlaal** [comment]
edit: you can completely disregard this feature request

I discovered that I can set a keyboard shortcut to *any* Preferences window - this is more than enough :) 💗
