### ISSUE TITLE
[Feature] Drag 'n drop columns in Results view

### ISSUE THREAD

**Issue by j-brown** [serge-rider/dbeaver#2667]
Other SQL clients (like dbvisualizer) allow you to drag/drop and reorder columns in the results table. 

It's incredibly useful when you're sorting results with a great number of columns. 

I searched the Issues page (figured someone would have requested this already), but did not find anything along these lines. So I'm filing this as a feature request. Cheers!

**Comment by serge-rider** [comment]
You can drag-n-drop columns in DBeaver. 
Just drag column icon: https://github.com/serge-rider/dbeaver/wiki/Data-Appearance

**Comment by j-brown** [comment]
MFW: https://media3.giphy.com/media/14aUO0Mf7dWDXW/giphy.gif

Whelp, I'm embarrassed! But ty for the link, this works great! And ty for the application as a whole 🎉
