### ISSUE TITLE
Unhide column

### ISSUE THREAD

**Issue by alexpetralia** [serge-rider/dbeaver#2668]
Hi, I see there is a way to hide columns from the result set. Is there also a way to "Unhide" these once you've hidden them (similar to Excel?) Or do you have to recompute the result set?

**Comment by serge-rider** [comment]
You can do this in filter settings dialog (4th button in top toolbar or context menu->Order/Filter->Customize).
Also check this for other resultset visualization options: https://github.com/serge-rider/dbeaver/wiki/Data-Appearance

**Comment by alexpetralia** [comment]
Ah thank you, sorry I hadn't checked this sufficiently first.
