### ISSUE TITLE
Database DDL history feature

### ISSUE THREAD

**Issue by stepjacky** [serge-rider/dbeaver#268]
in development progress, maybe modify table many times , can i export all sql  changed for table or database,this is usually!

**Comment by codebling** [comment]
This information is available in the Query Manager. You can find it in the Window menu. If a simple copy/paste from the Query Manager tab is not sufficient for your needs, you can run queries against the query manager database **BUT DO NOT DO THIS FROM DBEAVER WHILE DBEAVER IS RUNNING**. First, shut down DBeaver, then copy `~/.dbeaver/.metadata/qmdb` folder somewhere. Reopen DBeaver and add your **copied** database as an H2 Embedded connection and then run your queries. 


Let me know if this meets your needs!

**Comment by stepjacky** [comment]
yes i use it ,and find all queries  have runed,
what's i means is that the ddl of the database and table, may be qmdb contains all sqls for query, 
that is diffcute to split  ddl and dml operation for me on some duration time!
i need only the ddl operation and use to sync some two database's structure.

**Comment by codebling** [comment]
So how do you think this feature should work?  It might be possible to create some filters in Query Manager and additionally a column which would distinguish each query as DDL, DML or DCL, making it much easier to find the relevant queries for you. 

It sounds like you are trying to sync your development database with your production database. Usually you would write a database migration script in your code, and then apply this to your development database and, after testing/staging, to your production database. It sounds like you have made a bunch of changes using DBeaver and now would like to produce the database migration. What you could do is save the DDL for your current development database, then save the DDL for the database you'd like to sync, and diff the two. There are a few tools for this. You can check out [apgdiff](http://www.apgdiff.com/) or [this Perl script](http://search.cpan.org/dist/SQL-Translator/lib/SQL/Translator/Diff.pm). You should definitely go have a look at some DB migration tools to see if those can help you. [Phinx](https://github.com/robmorgan/phinx) seems like a good stand-alone tool which can run pure SQL migrations (requires PHP to run). Depending on which language/framework you are using, there are several others.

**Comment by stepjacky** [comment]
yes,what 's your describ sence is right for my development status ,i use dbeaver as a database development ide,and then ,the devlopment database and product database is on some different where is ,and can not connect to each other through the  internet network for some security reason.
      at now ,i must copy any table ddl of modified to a text file pressed [copy] button showed,and set it to product to apply changes ,and then ,these operations is done by manual.
      over again and again,sometimes may be forget to copy somthing, i have to export entired database to product 
      i think ,like a git commit ,i can export a ddl of table modified ,dbeaver can give me a whole copy of it?

**Comment by stepjacky** [comment]
yes,whats your describ sence is right for my development status ,i use dbeaver as a database
development ide,and then ,the devlopment database and product database is on some different where
is ,and can not connect to each other through the  internet network for some security reason.

at now ,i must copy any table ddl of modified to a text file pressed [copy] button showed,and set
it to product to apply changes ,and then ,these operations is done by manual.

over again and again,sometimes may be forget to copy somthing, i have to export entired database to production side.

what is needed is  export a ddl of table modified ,dbeaver can give me a whole copy of it?

**Comment by codebling** [comment]
I think you should use database migrations for this. What programming language/framework is the project you are working on?  I may be able to suggest a tool.

**Comment by stepjacky** [comment]
the spring-boot framework is serve on  my projects ,databasies  is mysql/mariadb ,and the development database and production database is on the different two physical ibm server  and can't connect to each other by any network!
can some tool to deal with migrations!
thanks

**Comment by serge-rider** [comment]
Note: you can use QMDB database directly from DBeaver. Just use QMDB driver.
DDL and DML operations have different flags.
Table QM_STATEMENT has column STATEMENT_PURPOSE, values 4 and 5 corresponds to metadata queries and DDL queries.
Essentially I think this issue duplicates #178. Once we'll have UI for history management it'll be possible to extract all DDL queries. Is this the goal?

**Comment by codebling** [comment]
@serge-rider I believe so! 

@stepjacky check out [MyBatis](http://www.mybatis.org/migrations/migrate.html), a stand-alone migration tool in Java, or have a look at [this article](https://blog.pivotal.io/labs/labs/db-migrations-spring-project), which explains how to use set up and integrate [flyway](https://flywaydb.org/) with Maven (they are also working with a Spring project, but I don't think that's relevant).

**Comment by stepjacky** [comment]
@serge-rider yes that is the goal ,
@codebling thanks for the tools,  i will
