### ISSUE TITLE
postgresql on RDS gives "permission denied for relation pg_authid   org.postgresql.util.PSQLException: PSQLException: ERROR: permission denied for relation pg_authid"

### ISSUE THREAD

**Issue by adq** [serge-rider/dbeaver#271]
Hi, if I connect to a postgres db hosted in amazon's RDS, clicking on a database gives the following error:

`DBCException: SQL Error [42501]: ERROR: permission denied for relation pg_authid
  org.postgresql.util.PSQLException: PSQLException: ERROR: permission denied for relation pg_authid
`

This is probably because you don't have complete admin over the database in RDS; It is possible to simply dismiss the error, but it appears every time you click on a database.

**Comment by serge-rider** [comment]
Agreed. 
I don't want to suppress this error at all but showing it only once seems to be a best choice.
BTW this error appears because you have open "Properties" view. It happens when some object's property contains a link on a Postgres user.
Thanks for report.

**Comment by adq** [comment]
Actually, it happens every time I double click on a postgres database (I've enabled the show all databases feature on the connection).

I know you don't have the switching-between-non-default- postgres-dbs working yet, but it's going to be extremely irritating when that is up and running. Guess I'll reassess then, ta.
