### ISSUE TITLE
Export fails for Cassandra table with type smallint

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [serge-rider/dbeaver#274]
One of the clustering keys is of type smallint and when I try to export, I get the following error:

> com.datastax.driver.core.exceptions.CodecNotFoundException: CodecNotFoundException: Codec not found for requested operation: [smallint <-> java.nio.ByteBuffer]

I am using DBeaver 3.6.1 for Windows 64-bit.

![image](https://cloud.githubusercontent.com/assets/14230950/13665956/11b8cfe0-e6d5-11e5-90fc-6ebdfe6c1d68.png)

**Comment by serge-rider** [comment]
It is a bug in Cassandra 3 data types handler.
Thanks for report.
