### ISSUE TITLE
Eclipse Che

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#276]
This new browser based IDE allegedly makes it easy to convert eclipse based plugins to run in the browser as part of the development environment. They are having licencing issues with their existing database tools. Thought it might be worth a look: https://eclipse-che.readme.io/docs/plug-ins

**Comment by codebling** [comment]
Interesting!  I'm not sure how much work it would be to migrate. This is the best info I've found so far:

> As a general rule, the objective is to be able to plug existing
libraries for various languages to run natively within the workspace, and
then to create Che plug-in wrappers around those libraries, turning them
into RESTful services.


So it may be as simple as creating a wrapper, or...not.

**Comment by serge-rider** [comment]
I'm afraid this will require a lot of efforts.
I definitely don't have time for that. 
But if anyone would want to do such a wrapper - be my guest. I can only assist with something.
