### ISSUE TITLE
Add reconnect button

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#278]
**3.6.2**
Please add reconnect button to this dialog (mysql)

![image](https://cloud.githubusercontent.com/assets/9958813/13741177/dfd14e1c-e9e5-11e5-80bd-b2c89411aa88.png)

**Comment by serge-rider** [comment]
Can you provide steps to reproduce that?

DBeaver uses SQL state codes to determine special errors like disconnect.
The actual error (08? - that's not a valid SQL state) doesn't mean that connection was lost/interrupted. It is just a regular SQL error.
Usually MySQL provides good codes (08006, 08007, 08S01, etc).

**Comment by infectormp** [comment]
sorry not mysql, mariadb 10.1.12

1.Open table
2.Open data tab and get content
3.Kill user connection
4.In data tab press F5
![image](https://cloud.githubusercontent.com/assets/9958813/13746189/41c91ed4-ea03-11e5-9768-eecb790b6a81.png)

**Comment by infectormp** [comment]
i use mariadb driver

**Comment by serge-rider** [comment]
Yep. MariaDB driver doesn't yet support valid SQL states.
I'll add a workaround for it.
Thanks for report.
