### ISSUE TITLE
Connect to a remote MySQL server with sockets

### ISSUE THREAD

**Issue by krilim** [serge-rider/dbeaver#279]
The remote MySQL use sockets instead of TCP/IP . I think the console method to connect is:

ssh \
  -R/var/run/mysql.sock:/var/run/mysql.sock \
  -R127.0.0.1:3306:/var/run/mysql.sock \
  somehost

**Comment by serge-rider** [comment]
I'm afraid this is not possible with standard MySQL JDBC driver: http://lists.mysql.com/java/8749
In theory it is possible to emulate Unix sockets and write a custom socket factory but it will require to much efforts.

**Comment by dantheperson** [comment]
You could try configuring this socket factory in driver properties https://github.com/kohlschutter/junixsocket
Demo code: https://github.com/kohlschutter/junixsocket/blob/master/junixsocket-demo/src/main/java/org/newsclub/net/mysql/demo/AFUNIXDatabaseSocketFactoryDemo.java
