### ISSUE TITLE
Postgresql. Connection without specified database name

### ISSUE THREAD

**Issue by TokiTori** [serge-rider/dbeaver#28]
I've got an error when trying to connect to host without specified database name. I just set server, username **test_user** and correct password in window **Connection configuration**. Without DB/schema. Clicked **Test connection** and got message: 
```org.postgresql.util.PSQLException: PSQLException: FATAL: database "test_user" does not exists```
May be should set default DB/schema value as **postgres**, when it's not present? And in error message fix text from username to dbname.

**Comment by serge-rider** [comment]
We are currently working on new PostgreSQL extension. Probably in version 3.6. Beside other things it will support multiple databases and, maybe, default database name as well.

**Comment by serge-rider** [comment]
Default db name is "postgres".
Also it'll be possible to switch to another database (see #34).
