### ISSUE TITLE
Cassandra updating Date field

### ISSUE THREAD

**Issue by berjanjonker** [serge-rider/dbeaver#284]
When editing a Date field in the grid view, DBeaver parses the input based on Timestamp syntax (which is the Cassandra 2.x Date type).
On a submit the driver generates an error: 
````
DBCException: Error binding statement parameter
  com.datastax.driver.core.exceptions.CodecNotFoundException: CodecNotFoundException: Codec not found for requested operation: [timestamp <-> com.datastax.driver.core.LocalDate]
```

**Comment by serge-rider** [comment]
Yes, it is a legacy from Cas2.x version.
Thanks for report.
