### ISSUE TITLE
Postgres buggy handling of text (and possibly other) types

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#285]
Note: This started happening with v 3.6 and new postgres driver!

If one has a table with a name of a built-in type ("text" for example), this will cause the output of that column to display incorrectly. To reproduce:

select cast('Hello, world!' as text)
-- displays 'Hello, world!' string, as it should

create schema foo; create table foo.text (a int, b int);
-- this creates composite type "text" in schema "foo"

-- now disconnect and reconnect dbeaver session

select cast('Hello, world!' as text); 
-- now displays 'a' and 'b' columns, not 'Hello, world!' string as before
-- note that schema foo isn't even in the search path!

Sometimes the result cell would display something like 'org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCompositeStatic@3fcbbfd2' instead of the actual value.

This makes it rather impossible to use a table named 'text' anywhere, which is rather unfortunate, as mediawiki, for example, includes such a table :(

Fix: this usually happens when considering only type name, not schema in metadata processing. Fix catalog queries to handle schemas properly. Function pg_catalog.format_type() can be quite useful for finding type names.

**Comment by lacanoid** [comment]
one can also make use of queries like:

select 'text'::regtype::oid
select 'timestamp with time zone'::regtype::oid
select 'foo.text'::regtype::oid

to find a type oid, while considering current search_path.
Note however, that they will fail (and abort the current transaction), if the type does not exist.
On postgres 9.4+ one can also use to_regtype(), which returns null instead of error.

More useful functions for catalog queries here:
http://www.postgresql.org/docs/current/static/functions-info.html#FUNCTIONS-INFO-CATALOG-TABLE

**Comment by serge-rider** [comment]
I'll fix the problem described above.
But some type resolve problem may remain. Key problem is that PG do not tell fully-qualified type name for resultset columns. It tells just short version, e.g. 'text'. You can only guess in what schema this type was defined.
In most cases I can determine correct type by obtaining source table/column information. But in some cases source table information is not available. I'll use search path to search type by name but even this won't work always.
