### ISSUE TITLE
Can't copy/paste the connection in Database Navigator view with right click context

### ISSUE THREAD

**Issue by mquan86** [serge-rider/dbeaver#291]
In Database Navigator view, right click on a connection, copy and then right click to paste, but the paste menu is not shown. No problem with old version such as 3.3.

OS: Windows 7 - 64 bit
DBeaver 3.6.2 x64.

**Comment by serge-rider** [comment]
You could use main menu of just ctrl+c ctrl+v.

**Comment by limex** [comment]
I suspect Copy/Paste work only when Pasting to a different Folder.

**Comment by serge-rider** [comment]
It works (at least it should) in the same folder too. Or without folder.

**Comment by limex** [comment]
It should, but it doesn't.

**Comment by serge-rider** [comment]
Please create a bug report with some details (environment, particular use-case). I can't reproduce this issue.

It is one of the very frequently used features.
