### ISSUE TITLE
Derby: contents of CLOBs get truncated in result view

### ISSUE THREAD

**Issue by ch-me** [serge-rider/dbeaver#292]
Hello, I tested caching CLOB and BLOB values in version 3.6.2 and retrieving large BLOBs now seems fine - thank you very much for your support! #260 

But unfortunately there still seems to be a bug regarding the caching of larger CLOB values. Their content still gets truncated at around 4k in result view.

**Comment by serge-rider** [comment]
Can't reproduce. Did you enable "Cache CLOB values" option?

**Comment by ch-me** [comment]
Yes I did enable "Cache CLOB values" option. Results get truncated at 8k (not at 4k as I stated before):

`Actual content length (8192) is less than declared: 25809`

**Comment by serge-rider** [comment]
Please post error log with stacktrace.
Can't figure out what is the difference between CLOB and BLOB in this case.

**Comment by ch-me** [comment]
There is no stacktrace, the message is just a warning.

**Comment by serge-rider** [comment]
Good point.
It was hard to catch this issue because it happened only if CLOB value > 8k and < 10k.
Now fixed, thanks for report.
