### ISSUE TITLE
Group tabs by connection

### ISSUE THREAD

**Issue by choclin** [serge-rider/dbeaver#296]
If I have many tabs open, it can happen that I lose track of where I currently am and where I can find the tab I want right now. Is it possible to realize a grouping of tabs within the Eclipse framework?

For example: In SQLyog, I have two bars of tabs: The upper one shows the connections (which can be colored). The lower one shows the query editors of the selected connection.

**Comment by codebling** [comment]
Can you show a screenshot from SQLyog?

**Comment by ctaulien** [comment]
![bildschirmfoto_2016-03-20_21-28-10](https://cloud.githubusercontent.com/assets/10667383/13906923/b0144f56-eee2-11e5-995d-01057a828420.png)

btw. thanks for the External SQL-Formatter feature. 1+

**Comment by serge-rider** [comment]
Two groups of tabs doesn't make sense in DBeaver. Each tab associated with some editor.
Some editors (e.g. custom ER diagram) are associated with multiple connections. And some editors aren't associated with any connection at all.
And you can change active connection of particular SQL editor.
And don't forget about Eclipse integration - potentially you may have a bunch of open editors which are not related to DBeaver (e.g. HTML/Java source code).
So there is no rigid link editor<->connection. This is just another approach, not like SQLyog.

But I agree that some UI improvements can be done.
I think that coloring editor tabs is a good idea. Unfortunately there is no easy way to do this in Eclipse. But it is possible.

If you think this is reasonable - please create another feature request for tabs coloring and close this one.

**Comment by choclin** [comment]
Thanks for your reply. I understand, that it is not that easy. But is there a way to technically do tab grouping within Eclipse? It could also be a way to manually group tabs (maybe like you can do it in firefox with the tab groups addon), so I can arrange my editors connection-based or project-based or however I want.

**Comment by serge-rider** [comment]
No, there is no such feature (tabs can't be grouped, swt doesn't support that).
Moreover it still don't support multiline tabs. That's a shame, they (Eclipse platform team) are working (huh) on this feature for over 14 years and still nothing. Hopefully it'll be in Eclipse 4.6 (crossing fingers).
The most famous bugs in Eclipse (worth reading):
https://bugs.eclipse.org/bugs/show_bug.cgi?id=28722
https://bugs.eclipse.org/bugs/show_bug.cgi?id=58945

After all I think that having colored tabs + multiline tabs will solve most of problems with editors navigation.
Also don't forget about CTRL+F6 and CTRL+E.

**Comment by choclin** [comment]
Okay, I understand. I created a new feature request for colored tabs. Or do you want to leave it here?

**Comment by serge-rider** [comment]
Ok.
I'll close this issue then.
