### ISSUE TITLE
Hierarchical DB Connection management

### ISSUE THREAD

**Issue by ctaulien** [serge-rider/dbeaver#297]
The number of databases my team has to manage will be growing in the near future. So the number of connections to manage will exceed 200 by far.

So what i really need is an efficient way of managing the connections in a tree view in unlimited depth, as well as quick searching through the tree and tagging + coloring connection entries. This would be aweswome.

Currently there seems to be only the one-level-hierarchy of management.

**Comment by serge-rider** [comment]
Currently there are two levels of hierarchy (connection and folders, create folder action is in the view toolbar). I'm afraid that making infinite number of folder levels will just complicate connection management. However I'll think about that.

Also you can color connections.

Tags sounds interesting but for now I don't see how can it be done conveniently..

**Comment by Cris70** [comment]
I also would like to have this feature, since I have to manage a similar number of sql server instances and a few other instances of DB2.
Infinite depth is not a requirement for me, but I'd need folders at least 5-6 levels deep.
Coloring is already there, and tagging is not that important to me (though it would be very nice).

**Comment by serge-rider** [comment]
After all I'll just improve folders management a bit (add context menu items).
I don't think that folders hierarchy will make much sense.

**Comment by Cris70** [comment]
Serge, I respect your decision, but can you elaborate on why you think folders hierarchy does not make much sense?
As a professional database administrator I find it quite indispensable.

**Comment by serge-rider** [comment]
I think there should be some better way to manage big number of connections than just making folders hierarchical.
For me even one level sometimes is a problem (I can't find connection if it is in some folder and I don't remember in what folder exactly).
Maybe connections filter (similar to drivers filter) may help here. Also maybe folders should be also colorized.

I'll create another issue for connection management improvement (more general).

**Comment by serge-rider** [comment]
Hierarchical connections will be available in the next version (3.8.2)

**Comment by Cris70** [comment]
Serge, thank you very much!!
