### ISSUE TITLE
PostgreSQL - Stored Procedures

### ISSUE THREAD

**Issue by ClemensFMN** [serge-rider/dbeaver#299]
I try to write stored procedures with DBeaver version 3.6.2 and postgresql driver 9.4-1206-jdbc4.jar against a 9.5 PostgreSQL database.

Creating a function without parameter declaration works fine (i.e. pressing Ctrl-Enter somewhere in the function)

```
CREATE OR REPLACE FUNCTION somefunc()
	RETURNS integer
	AS $$
BEGIN
	RETURN 0;
END
$$ LANGUAGE plpgsql;
```

However, if I use a declaration, then an error message is thrown: SQL Error [42601], unterminated dollar-quoted string.

If I use ' instead of $$ this works - However, is there any way to get it running with $$?

```
CREATE OR REPLACE FUNCTION somefunc2()
	RETURNS integer
	AS $$
declare
	x integer;
BEGIN
	RETURN 0;
END
$$ LANGUAGE plpgsql;
```

**Comment by serge-rider** [comment]
Good point.
I'll add support of PG specific blocks in the next version.
For now as a workaround you can select whole CREATE query before executing it.

**Comment by ClemensFMN** [comment]
Thanks - regarding the workaround: What do you mean by "select whole create query"? When I select the complete query, I don't find any further options regarding "execute selected" or the like...

**Comment by serge-rider** [comment]
Select query + CTRL+Enter

**Comment by ClemensFMN** [comment]
Thanks - that works!

I just noted a small inconsistency: When I select these two inserts and press Ctrl-Enter, the two rows are inserted; however the GUI says "Updated Rows 1". Shouldn't this be 2? Sorry for being picky...

```
insert into tst values(default, 'bbb');
insert into tst values(default, 'ccc');
```

**Comment by serge-rider** [comment]
When you execute something with Ctrl+Enter it means execution of a single statement. Most databases don't even support execute of multiple SQL queries as a single statement. PostgreSQL executes them all but returns results only for the first query in the list.
To execute multiple statements select them and execute as script (alt+x).
