### ISSUE TITLE
Colored tabs

### ISSUE THREAD

**Issue by choclin** [serge-rider/dbeaver#300]
It would be very nice to have a feature that allows us to colorize the tabs for a better overview.
Maybe we could set a default color in the connection settings, so every query editor started on that connection (e.g. by double clicking the connection's entry) will have that color (which can be changed).

**Comment by serge-rider** [comment]
Well, 3.7.6 support coloring of current tab (#818).
Eclipse UI/CSS styling doesn't support coloring of non-active tabs. There will be too much effort to implement such support in DBeaver. Maybe in future versions Eclipse will support this - but for now I'm closing this issue as partially done.
