### ISSUE TITLE
MySQL DELIMITER support

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#301]
Support of custom MySQL delimiters in scripts.
```sql
DELIMITER $$
SELECT 1$$
SELECT 2$$
DELIMITER 
```

**Comment by carlosjrcabello** [comment]
Man, it will super useful.

**Comment by carlosjrcabello** [comment]
Here, we have a script with lot of queries separated by ';', and we put it inside version build to be executed as external file in MySQL terminal using (-f -B args)...

So, we have some problems using delimiter scopes, when they aren't correctly closed, based on your example, to separate it (or finish) you'll need add ';' at end;

```
DELIMITER $$
SELECT 1$$
SELECT 2$$
DELIMITER ;
```

If you don't put that ';' at the end, next sql statement will throw a syntax error.

**Comment by serge-rider** [comment]
Yeah, there are a few nuances.
Idea of plain DELIMITER is to reset delimiter to default value (;).
So it's meaning is the same as in "DELIMITER ;"
I'm not sure what number of tools supports first syntax, but I'll support both.

**Comment by carlosjrcabello** [comment]
Nice,

I'm not sure about lines between commands, for instance, if after DELIMITER I use one empty line, I'll have to use one line between delimiter statements '$$';

```
DELIMITER $$

SELECT 1 FROM DUAL$$

SELECT 2 FROM DUAL$$

DELIMITER ;
```

**Comment by serge-rider** [comment]
This feature is already committed.
You may try to build devel branch and check how it works.

**Comment by carlosjrcabello** [comment]
I'll try it here.

**Comment by carlosjrcabello** [comment]
I've tested it here.

Based in my experience, to run DELIMITER statements I need to use (Alt + X), run as script, to execute it, because trying to run as selected query text doesn't work (as expected).

Below, the sql script that I used for tests:

```
DROP FUNCTION IF EXISTS `mask_fone` ;
DROP FUNCTION IF EXISTS `mask_cnpj` ;

DELIMITER $$

DROP FUNCTION IF EXISTS `mask_fone` $$

CREATE FUNCTION mask_fone(fone VARCHAR(50)) RETURNS VARCHAR(50) DETERMINISTIC
RETURN IF(LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(fone,' ',''),'-',''),')',''),'(','')) = 10,
CONCAT( '(',LEFT(REPLACE(REPLACE(REPLACE(REPLACE(fone,' ',''),'-',''),')',''),'(',''),2) , ")" , MID(REPLACE(REPLACE(REPLACE(REPLACE(fone,' ',''),'-',''),')',''),'(',''),3,4) , "-", RIGHT(REPLACE(REPLACE(REPLACE(REPLACE(fone,' ',''),'-',''),')',''),'(',''),4))
,
fone) $$

DROP FUNCTION IF EXISTS `mask_cnpj` $$

CREATE FUNCTION `mask_cnpj`(cnpj VARCHAR(100)) RETURNS VARCHAR(20) DETERMINISTIC
BEGIN
	SET cnpj = REPLACE(REPLACE(REPLACE(TRIM(COALESCE(cnpj, '')), '/', ''), '-', ''), '.', '');
	
	SET cnpj = CONCAT(
		MID(cnpj, 1, 2), '.',
		MID(cnpj, 3, 3), '.',
		MID(cnpj, 6, 3), '/',
		MID(cnpj, 9, 4), '-',
		MID(cnpj, 13, 2)
	);
	
	RETURN cnpj;
END $$

DELIMITER ;

select mask_fone('4532640951') as phone, mask_cnpj('97448538000103') as cnpj from dual;
```
The drop statements are out of delimiter area to ensure that functions were dropped to validate delimiter execution.

**Considerations**

I just think that the word `DELIMITER `could have the same syntax color of `DROP FUNCTION` for instance.
![screen184](https://cloud.githubusercontent.com/assets/637767/13966562/cfff0aa2-f051-11e5-9cf3-97fb33ef43e7.png)

**Comment by serge-rider** [comment]
Good.
I think that we need a new color for DELIMITER.
It is actually not an SQL statement at all, more like some macro or control command. Coloring it with SQL colors will be confusing.

**Comment by carlosjrcabello** [comment]
uhmm, you're right.

What do you think about use black and bold for delimiter?

**Comment by serge-rider** [comment]
Let's try dark magenta as default value.
Can be customized in preferences.

**Comment by carlosjrcabello** [comment]
Hey, 

Consider review format option (Ctrl + Alt +F), applying hover delimiter, I got this below:
```

DELIMITER $$ drop
	function if exists `mask_fone` $$ create
		function mask_fone(
			fone varchar(50)
		) returns varchar(50) deterministic return if(
			length( replace( replace( replace( replace( fone, ' ', '' ), '-', '' ), ')', '' ), '(', '' ) ) = 10,
			concat( '(', left( replace( replace( replace( replace( fone, ' ', '' ), '-', '' ), ')', '' ), '(', '' ), 2 ), ")", mid( replace( replace( replace( replace( fone, ' ', '' ), '-', '' ), ')', '' ), '(', '' ), 3, 4 ), "-", right( replace( replace( replace( replace( fone, ' ', '' ), '-', '' ), ')', '' ), '(', '' ), 4 ) ),
			fone
		) $$ drop
			function if exists `mask_cnpj` $$ create
				function `mask_cnpj`(
					cnpj varchar(100)
				) returns varchar(20) deterministic begin
			set
				cnpj = replace(
					replace(
						replace(
							trim( coalesce( cnpj, '' ) ),
							'/',
							''
						),
						'-',
						''
					),
					'.',
					''
				);
set
cnpj = concat( mid( cnpj, 1, 2 ), '.', mid( cnpj, 3, 3 ), '.', mid( cnpj, 6, 3 ), '/', mid( cnpj, 9, 4 ), '-', mid( cnpj, 13, 2 ) );

return cnpj;
end $$ DELIMITER;
```

Now I got a sql error because particularities of delimiter statements.

**Comment by serge-rider** [comment]
Will fix it..

**Comment by carlosjrcabello** [comment]
Hi Serge,

I fetched your last commits and formatter is OK.

**Comment by williamokano** [comment]
hI @serge-rider I tried to run a sample query with delimiter and I'm getting an error with it.

The query I tried to execute is 
```sql
DELIMITER $$

SELECT 1 FROM DUAL$$

SELECT 2 FROM DUAL$$

DELIMITER ;
```

The error I got is the attached one.
![captura de tela de 2016-07-06 17 36 43](https://cloud.githubusercontent.com/assets/5909442/16633551/44700b2e-43a0-11e6-8397-25065c52e4e3.png)

**Comment by carlosjrcabello** [comment]
Hi there @williamokano ,

Yes, not only for dual, every single line as statement must contains the same number of white spaces from start delimiter..., and for functions, procedures, you can have some other traps, like, end must be terminated if delimiter chars, like this one:

```
DELIMITER $$

DROP FUNCTION IF EXISTS `mask_fone` $$

CREATE FUNCTION `mask_fone`(fone VARCHAR(50)) RETURNS VARCHAR(50) DETERMINISTIC
BEGIN
	SET fone = REPLACE(REPLACE(REPLACE(TRIM(COALESCE(fone, '')), '/', ''), '-', ''), '.', '');
	
	set fone = replace(replace(fone, '(', ''), ')', '');

	if( fone is null or fone = '') then
		return '';
	end if;
	
	if( SUBSTRING(fone, 1, 1) = '0' ) then
		set fone = mid(fone, 2, length(fone) -1);
	end if;
	
	if (length(fone) > 10) then
		SET fone = CONCAT(
			'(',
			MID(fone, 1, 2), ')',
			MID(fone, 3, 5), '-',
			MID(fone, 8, 4)
		);
	END IF;
	
	if (length(fone) <= 10) then

		if (length(fone) = 8) then
			set fone = concat('00', fone);
		end if;

		SET fone = CONCAT(
			'(',
			MID(fone, 1, 2), ')',
			MID(fone, 3, 4), '-',
			MID(fone, 7, 4)
		);
	END IF;
	
	RETURN fone;
END $$

DELIMITER ;

```

This `END $$` has `$$` from start delimiter..

**Comment by williamokano** [comment]
@carlosjrcabello Yeah, I noticed that. Thanks for the reply :)

**Comment by fcofdezp** [comment]
Is there any chance to implement this for Firebird databases? The syntax is: 
`set term <new_delimiter> <old_delimiter>`

like:
`set term # ;
...
set term ; #`

Thanks in advance!

P.S. BTW DBeaver is superb!

**Comment by serge-rider** [comment]
Yes, it is possible.
Please create another issue for that.

**Comment by matthewlenz** [comment]
This works but fails when trying to use dumps from mysqldump.  mysqldump uses a delimiter of ";;" for creating triggers/procedures.
