### ISSUE TITLE
Query Trace feature in SQL Editor for Cassandra

### ISSUE THREAD

**Issue by dins2k2** [serge-rider/dbeaver#302]
Hello, I love using DBeaver, simple UI and very fast. It will very helpful if you could add Query Trace feature in SQL Editor for Cassandra like in Datastax DevCenter Tool. Attaching the screenshot of Query Trace in DevCenter.

![qrytrc](https://cloud.githubusercontent.com/assets/17889768/13975467/c71e7b20-f083-11e5-83d0-d889aeae68fe.png)

Thanks,
Dinesh

**Comment by serge-rider** [comment]
I think this can be done in the "Explain plan" tab.
In fact this feature is similar to relational database execution plan.

**Comment by dins2k2** [comment]
Not exactly like Explain plan but Query Trace will allow you to track the progression of reads and writes throughout Cassandra. It will really helpful if you could add this feature in DBeaver. Thanks.

**Comment by serge-rider** [comment]
Will be added in 3.8 (along with a few other Cassandra extension improvements).
