### ISSUE TITLE
Wrong column displayed with self join queries

### ISSUE THREAD

**Issue by rom9** [serge-rider/dbeaver#306]
Hi, i think i've discovered a quite subtle UI bug in **DBeaver 3.6.2**. When i run a query that brings in the same column multiple times from a self-join, like this:

```sql
select a1.item_type, a1.id_item as one, a2.id_item as two
from items a1
join items a2 using(item_type)
where a1.id_company=1
and a2.id_company=3
```
... the results pane shows the correct data at the first execution. If i re-execute the same query repeatedly, **after the third time**, the third column "two" disappears and gets replaced by an exact copy of the second column, "one" (same header and data).
The problem occurs only when i choose "Grid" mode in the output pane, while in text mode everything is ok.

I've encountered the problem using MySQL (on different server versions) using **mysql-connector-java 5.1.38** JDBC driver. Haven't tested on other DB engines.
I am running DBeaver on **Linux x86_64** and **Oracle JDK 1.8.0_74**.

Apart from this, DBeaver is awesome! Keep up the good work :-)

**Comment by serge-rider** [comment]
This is a known issue (although it was found in PostgreSQL/Vertica).
It is already fixed. Thanks for report anyway.

**Comment by serge-rider** [comment]
Please reopen if this issue will still happen in 3.6.3.
