### ISSUE TITLE
Update Mac OS X install instructions to mention JDK Java requirement

### ISSUE THREAD

**Issue by esambo** [serge-rider/dbeaver#307]
DBeaver.app version 3.4 still worked with the Apple provided Java version.
More recent version require `Java 1.7+` as stated in http://dbeaver.jkiss.org/download/
But JRE will NOT work on Mac OS X, it only works with the [JDK](http://www.oracle.com/technetwork/java/javase/downloads/index.html).
`/usr/libexec/java_home -V` will otherwise [NOT find JRE](https://discussions.apple.com/message/28094277#28094277).
Please update the _Install_ section of http://dbeaver.jkiss.org/download/ to mention that.

And why do you call it `MacoOS` instead of `Mac OS X`?

You also mention a workaround to fix the _reject to install unsigned software_. An easier way is to just right click on `/Applications/DBeaver.app` and select _open_ which brings up a dialog box that about the app being downloaded from the Internet as described in [How to open an app from a unidentified developer and exempt it from Gatekeeper](https://support.apple.com/en-us/HT202491)

**Comment by serge-rider** [comment]
Hmm.
Do you know why JRE is not enough on Mac? I didn't know about that and this sounds not very good.
MacOS is the standard id in Eclipse world. I'll change it to Mac OS X on download page.
Thanks for better workaround info.

**Comment by lalato** [comment]
I'm not sure why it is either, but I can confirm that I was forced to install the JDK in order to get dbeaver working on my machine as well.  As for the OS Name...  MacOS (concatenated) is very common; as is Mac OS (separated).  I'm not sure it makes much of a difference.

**Comment by esambo** [comment]
`/usr/libexec/java_home -V` as mentioned in [Info.plist](https://github.com/serge-rider/dbeaver/blob/master/features/org.jkiss.dbeaver.standalone.feature/root/Info.plist#L40) will _ONLY_ work with JDK and _NOT_ JRE.

I assume that I could have found a JRE version of Java 1.7+ with: `find /Applications/Xcode.app/Contents/Applications /Library /usr/bin /System/Library/Frameworks/JavaVM.framework -name java 2>&1 | grep "bin\/java"` and doing a `-version` on each of them.

**Comment by esambo** [comment]
Please update the _Mac OS X_ documentation with:

- install Java JDK 1.7+
- update Info.plist to point to a Java JRE 1.7+

It would also be awesome to have a README in the root directory of the Mac OS X download that mentions this

**Comment by serge-rider** [comment]
Honestly I'm not very familiar with MacOS world.
I still hoping that problem is in configuration and it is possible to run DBeaver under JRE.
Do you have any ideas how to patch Info.plist exactly? For now it doesn't contain any information about preferred VM at all. It is just a default config for Eclipse RCPs.

**Comment by serge-rider** [comment]
Eventually I just did update MacOS system requirements on the download page.
