### ISSUE TITLE
Permissions error when saving CLOB content to a file (Windows 10)

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#308]
When you try to save the content of a CLOB field to a file via right-click option, DBeaver raises a "Unable to write to temp folder" error.

This happens when DBeaver is executed normally. If DBeaver is launched as admimistrator, the CLOB content is successfully saved.

NB: I found this issue on a Sybase DB using a Windows 10 client machine, but I think this error is common to all DBs.

**Comment by serge-rider** [comment]
Can't reproduce. 
In fact there is no such error "Unable to write to temp folder" in DBeaver, this seems to be an OS error.
Please post full stacktrace of that error (from Error Log).
