### ISSUE TITLE
renaming a column on postgresql generates wrong code.

### ISSUE THREAD

**Issue by lBilali** [serge-rider/dbeaver#309]
instead of renaming from old_column_name to new_column_name it does it to old_column_name

using dbeaver 3.6.2 as extension on eclipse 4.5.2

generated code example 
```
ALTER TABLE table_name RENAME COLUMN old_column_name TO old_column_name;
```

**Comment by lBilali** [comment]
Did not test it but looking at the source code it looks like on the end of the file: https://github.com/serge-rider/dbeaver/blob/80beac9ae06c0798fe93f36c805ad45e784feb1b/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/edit/PostgreTableColumnManager.java#L165

instead of ```DBUtils.getQuotedIdentifier(column)``` it should be ```command.getNewName()``` or maybe better  ```DBUtils.getQuotedIdentifier(command.getNewName())``` 

on DB2TableColumnManager.java it is only ```command.getNewName()```

**Comment by serge-rider** [comment]
Thanks for report
