### ISSUE TITLE
delete cassandra row error

### ISSUE THREAD

**Issue by evildecay** [serge-rider/dbeaver#310]
cassandra version: 3.04
dbeaver version: 3.6.3
In grid delete rows, alert error: can't detect source entity.

**Comment by serge-rider** [comment]
Please post full stacktrace (from Error Log view)

**Comment by evildecay** [comment]
I have found a cause, different default keyspace and queries keyspace  can cause this error.

**Comment by serge-rider** [comment]
Ok
