### ISSUE TITLE
Mongodb results as collapsable tree

### ISSUE THREAD

**Issue by hhaawwaa** [serge-rider/dbeaver#311]
I need to work with MongoDB for a while and I am wondering if there is any option to see the query result in collapsable tree format like in Robomongo or MongoChef. 

When there are many embedded documents scrolling makes hard to read the results. Collapse and field type features would make it much easier.

Thanks in advance,

**Comment by serge-rider** [comment]
Version 3.6.6 will include major update of Mongo extension.
It will include edit, update, better JSON navigation (collapse/expand) and other improvements.

**Comment by hhaawwaa** [comment]
Thank you serge-rider. Looks great!
