### ISSUE TITLE
Support SnappyData

### ISSUE THREAD

**Issue by fire** [serge-rider/dbeaver#312]
http://www.snappydata.io/

Currently using it through the Derby / Pivotal GemfireXD category, but it would be useful to have its own section.

**Comment by serge-rider** [comment]
I'm not familiar with this project. Do they have JDBC driver?

**Comment by fire** [comment]
This is their client:

http://mvnrepository.com/artifact/io.snappydata/gemfirexd-client/2.0-BETA

**Comment by serge-rider** [comment]
Ok. I'll just add Maven artifact reference to the existing Gemfire XD driver description.
