### ISSUE TITLE
SQLite datetime display does not parse data correctly

### ISSUE THREAD

**Issue by HeroicKatora** [serge-rider/dbeaver#313]
When viewing an SQLite database with a date or datetime colum in DBeaver in Eclipse, all data in this colum is just displayed as [NULL].  The trace appears in the error log of eclipse shows an exception during parsing. Here is the most relevant part at the bottom of the tracelog:

> Caused by: java.sql.SQLException: Error parsing date
> 	at org.sqlite.jdbc3.JDBC3ResultSet.getDate(JDBC3ResultSet.java:290)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:421)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:65)
> 	... 8 more
> Caused by: java.text.ParseException: Unparseable date: "2016-03-29 01:52:23" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
> 	at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299)
> 	at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490)
> 	at org.sqlite.jdbc3.JDBC3ResultSet.getDate(JDBC3ResultSet.java:287)

What seems to be an issue is that not all date and time formats as specified here:
[SQLite documentation](https://www.sqlite.org/lang_datefunc.html)
are recognized. Instead, only the format with number 4 is correctly recognized

**Comment by serge-rider** [comment]
SQLite do not support datetime types natively. They are stored as strings. and string sormats may differ in different databases.
You can try to play with "date_string_format" driver parameter (connection settings->Driver properties).

**Comment by HeroicKatora** [comment]
I am not able to specify a literal T to appear within the date with the pattern which I can set in this driver parameter. In case I attempt to do this, it refuses to connect because of "Illegal pattern component T".

But a literal T between the date and the time part of such a datetime string is required by [ISO-8601 ](https://www.w3.org/TR/NOTE-datetime).

At the moment, I have not yet found a workaround for this

**Comment by HeroicKatora** [comment]
Further testing shows the following weird behaviour:
When using the date-time driver parameter "y-m-d h:m:s" together with the datetime function of sqlite which, according to my understanding, formats everything according to this same format, the first 200 rows are shown incorrectly while the rest are just parsed accurately.

**Comment by serge-rider** [comment]
Can you send me a sample table where I can reproduce that?

**Comment by HeroicKatora** [comment]
https://gist.github.com/HeroicKatora/8f6a4bb3acf31fda7bf46755f6dd5d08
There is one file to create the scheme and one to insert the values, then view the table History from the eclipse plugin. Some details for operating system , eclipse version etc:
OS: Ubuntu 15.04 x86-64
Eclipse Version: Mars.2 (4.5.2)
DBeaver Core Version: 3.6.3, sqlite driver auto-installed the day the issue was created

**Comment by serge-rider** [comment]
Interesting.
It is a result of two different issues in SQLite driver (Xerial driver is not JDBC compliant and has very specific behavior).
I think I know how to handle it. I'll add a workaround in the next version.
Thanks for report.
