### ISSUE TITLE
Remove DEFINER

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#314]
If we cant select objects to export, can you add new checkbox in Database Navigator > Tools > Export database with option "Remove DEFINER" or "Ignore DEFINER" for MySQL and MariaDB dump?

It will be very helpful for View export from one DB to another DB. I use this feature in SQLyog.

* http://stackoverflow.com/questions/9446783/remove-definer-clause-from-mysql-dumps
* https://github.com/netz98/n98-magerun/issues/130

**Comment by carlosjrcabello** [comment]
Hi there,

It's depends how dump is implemented at this moment. Your question is so nice because 'transfer' sql data from DB to another one is so awful.

I think that for future releases, we should implement specific resources to transfer data between databases.

**Comment by MatyCZ** [comment]
I need download DB from production environment (server) to my development environment (local server via Vagrant), that is my transfer from one DB to another DB.

In Navicat I can choose objects to export, so I uncheck View objects => Import is OK.
In SQLyog I can check Ignore DEFINER => Import is OK.
In DBeaver I can export and import DB, but after that I must run SQL which regenerate my Views to "repair" DEFINER.
