### ISSUE TITLE
[3.6.2] Postgres DROP FOREIGN KEY   alter query is wrong

### ISSUE THREAD

**Issue by hananwm** [serge-rider/dbeaver#316]
version: 3.6.2

DBEAVER generated query: 

`ALTER TABLE table_name DROP FOREIGN KEY foreign_key_name`

Postgres syntax query should be:

`ALTER TABLE table_name DROP CONSTRAINT foreign_key_name`

**Comment by serge-rider** [comment]
Thanks for report
