### ISSUE TITLE
Tab management

### ISSUE THREAD

**Issue by boekhold** [serge-rider/dbeaver#32]
Maybe I'm not looking hard enough, but I can't find the following options for the SQL Editor that I would expect in any text-based editor:

- indent size
- use soft tabs (insert spaces instead of tab

Feature request?

**Comment by serge-rider** [comment]
Yes, standalone version missing this functionality. While Eclipse plugin reuses standard preference page from Eclipse IDE.
I'll add this pref page in standalone too. In one of near releases

**Comment by serge-rider** [comment]
Also we need standard Eclipse GoToResource dialog.

**Comment by r-richmond** [comment]
+1 for Tab Management

**Comment by serge-rider** [comment]
Apparently that's not easy to fix this issue. Indent size and other extended editor properties are defined in Eclipse *.ide plugins which are not shipped with DBeaver.
Still trying to find some workaround of this problem..

**Comment by serge-rider** [comment]
Will be added in 3.6.1
