### ISSUE TITLE
3.6.3: Wrong number format after copy\past action

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#322]
Run ```SELECT TO_NUMBER('0.0000001969', '9999.9999999999') FROM dual```
copy result to clipboard and past back to sql editor and you get **1.969E-7**

**Comment by serge-rider** [comment]
Thanks for report.
As a workaround you can use ctrl+shift+c and copy in display format.

**Comment by infectormp** [comment]
Thank you.
