### ISSUE TITLE
MariaDB driver URL

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#326]
In MariaDB driver properties Vendor's website URL open [mysql](https://www.mysql.com/products/connector/) site insted of [mariadb](https://mariadb.com/my_portal/download/java-client)

**Comment by serge-rider** [comment]
I'll fix it. But I believe correct url is https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/ (your one requires login)

**Comment by infectormp** [comment]
ah, yes. sorry.
