### ISSUE TITLE
Keywords not being highlighted

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#328]
the following keywords aren't being highlighted despite being present in [SqlConstants.java](https://github.com/serge-rider/dbeaver/blob/cb23dc5a5b5443d4b72c9fe599569f0b3a5d7f58/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLConstants.java)

unbounded
preceding
following

![image](https://cloud.githubusercontent.com/assets/9246654/14184570/9e4b7362-f72a-11e5-96c1-cbfcf3d31a44.png)

**Comment by serge-rider** [comment]
10x for report
