### ISSUE TITLE
Named Parameter with underscore '_' character does not work

### ISSUE THREAD

**Issue by adamitj** [serge-rider/dbeaver#331]
I'm using DBeaver 3.6.3 and noticed something weird that I don't remember to see in older releases. When I'm using a named parameter with DB2 10.5 and the named parameter has underscore character "_", the parameter is not recognized and is bypassed as an SQL object, raising an error.

Example:
`SELECT * FROM syscat.tables WHERE tabname = :TABLENAME`
runs ok

`SELECT * FROM syscat.tables WHERE tabname = :RA_NAME`
raises an error

Is there some workaround to do?

I'm using SQL from an ERP software which has some queries with more than 200 named parameters and most of them uses an underscore.

**Comment by adamitj** [comment]
BTW, I'm changing all parameter names, and the error is this:

DBCException: SQL Error [07004]: The number of variables in the EXECUTE statement, the number of variables in the OPEN statement, or the number of arguments in an OPEN statement for a parameterized cursor is not equal to the number of values required.. SQLCODE=-313, SQLSTATE=07004, DRIVER=4.19.26
  com.ibm.db2.jcc.am.SqlException: SqlException: The number of variables in the EXECUTE statement, the number of variables in the OPEN statement, or the number of arguments in an OPEN statement for a parameterized cursor is not equal to the number of values required.. SQLCODE=-313, SQLSTATE=07004, DRIVER=4.19.26

**Comment by serge-rider** [comment]
Thanks for report
