### ISSUE TITLE
Strange DB export wizard UI

### ISSUE THREAD

**Issue by efradkin** [serge-rider/dbeaver#333]
I'm exporting a db. I set up the parameters, press the Next button and then get an empty screen. It's absolutely not clear that I have to press Start button to start the export process. I think it'll be more understandable to see any summary of the set parameters and any message like 'press start button to start the export process' instead of just empty screen.

![image](https://cloud.githubusercontent.com/assets/16664546/14253641/f9f734d6-fa94-11e5-9ed7-ace8abd79e0c.png)

**Comment by serge-rider** [comment]
10x for report
