### ISSUE TITLE
Column mode selection and edition

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#334]
Eclipse supports column mode selection and edition, which is very useful for particular SQL synthaxes (when writting CASE..., multi joins, etc.).
Is it possible to implement this column mode in DBeaver editor ?

Thanks in advance.

**Comment by serge-rider** [comment]
It is already there.
As in Eclipse: Alt+Shift+A

**Comment by ced75** [comment]
Great! I didn't find it.
Thanks for your help and for DBeaver.
