### ISSUE TITLE
Unable to kill long running query OR close app

### ISSUE THREAD

**Issue by vpfaiz** [serge-rider/dbeaver#335]
I am connected to Redshift (from Windows) and I have query that is taking forever. I changed my mind and hit the "Cancel" button but the query never stops. So I tried to close the app but it will give me the error "Editor can''t be closed while SQL query is being executed". The only way to stop is by killing the process in task manager. This is not neat.

**Comment by serge-rider** [comment]
Redshift driver doesn't support query cancellation.
I'll add ability to close SQL editor with hanging query.

As a workaround you can use "Emergency Exit" (menu File) - it will close DBeaver immediately.

**Comment by mbirkenkamp** [comment]
Hi,

but the "emergency exit" workaround is only available in the standalone version (or i am simply unable to find it in eclipse). It would be nice to have this in eclipse as well.

**Comment by ebertugli** [comment]
Hallo, which is the state of this? Is there any workaround to terminate a Redshift query? Thanks!
