### ISSUE TITLE
Excel style results filter

### ISSUE THREAD

**Issue by filterfan** [serge-rider/dbeaver#336]
Hi  @serge-rider ,

Thank you for creating DBeaver. It easily has the best GUI of any free PostgreSQL Windows client.

I would like to request a new feature if I may. Would it be possible to implement an Excel style filter within the results table? Please see the image below an an example from "Toad for Oracle":

![image](https://cloud.githubusercontent.com/assets/18281814/14287213/d955fb80-fb49-11e5-8f8a-73a5d81bbeea.png)

It would be great if you could add a drop-down arrow button next to the column name in the results table and when this is clicked it should show an Excel style filter window of distinct results with tick boxes (So a column containing TRUE or FALSE values would only show these two results and a tick box next to them).

I realise that the results table is already capable of filtering table rows however to be honest it would be great to just click a button on the column and have it return the distinct values for that column. The ability to quickly aggregate data in this way would greatly improve workflow and the Excel style filter is a familiar tool.

Thanks

**Comment by serge-rider** [comment]
DBeaver uses filters in a different fashion (not like Excel).
For example:
![rs-filter](https://cloud.githubusercontent.com/assets/6398845/14332439/48fc5976-fc52-11e5-8d2c-aeeaf68c4f78.png)
I can improve filters by adding extra predefined values.
If you have any particular ideas for datetime, boolean, numeric types - just write them.
Boolean seems obvious (true/false) but boolean isn't actually an SQL data type so it is not so important.

**Comment by filterfan** [comment]
Thanks for your reply Serge.

Rather than predefined values relating to a data type, can we have a list of distinct values relating to the selected column? For reference I include a snapshot of the "AnySQL Maestro" SQL editor that implements the Excel style filter:

![image](https://cloud.githubusercontent.com/assets/18281814/14345051/d8f0d0ac-fca2-11e5-9d1b-1fb7aa12539b.png)

I believe that the advantage of this filtering method is that with **one click** you can choose from a list of distinct values in the selected column and you do not have to type the value to filter on. Another side effect of this filter is that you can see the unique values for each column without having to run separate SQL "group by" statements. I think that this is the only feature that I miss from other SQL editors that I have used.

**Comment by sqlstud** [comment]
Hi

I think this is a really good idea and would be a very quick and handy feature.  I have also used Toad in the past and having something like this made life a lot easier!!

**Comment by serge-rider** [comment]
Agreed.

**Comment by filterfan** [comment]
Hi @serge-rider,

Has any progress been made on this request? Are you likely to add this to a milestone in the near future?

Thanks

**Comment by serge-rider** [comment]
Not much progress so far.
It's a good feature but it requires significant UI improvements.
Maybe it'll be added in 3.7. Bu I can't promise.

**Comment by serge-rider** [comment]
Distinct values selector (or, in case of existence of foreign key - referenced table key values selector) will be added in the next version.
It'll be done in a bit different fashion: as a new filter type (IN ..). This filter will show list of possible values with ability to choose multiple values.

![rsv_filter_menu](https://cloud.githubusercontent.com/assets/6398845/15932434/63a67470-2e64-11e6-83ab-84dba054ffe9.png)
![rsv_filter_dialog](https://cloud.githubusercontent.com/assets/6398845/15932438/68a44c18-2e64-11e6-801d-067b24bda25d.png)

Any additional ideas are welcome.

**Comment by carlosjrcabello** [comment]
Hi there,

I'm not a big fan of visual sql builders, but anyway, I liked those options to apply some filters of result table.

What do you think if user uses some visual filters and run sql select statement, you can highlight target cell (text) column that matched with some of filters...such as Chrome makes when we press `Ctrl + F`:

![image](https://cloud.githubusercontent.com/assets/637767/15938821/33a34e42-2e4b-11e6-8cd5-bf7509899d95.png)

Is it hard/possible to code?

**Comment by carlosjrcabello** [comment]
I tried to explain what I said painting it on Paint:

![image](https://cloud.githubusercontent.com/assets/637767/15939036/5f0ee928-2e4c-11e6-9042-cbcfe3b59873.png)

**Comment by serge-rider** [comment]
That makes sense. I maybe no so hard to do.
Please make a separate feature request, it is a little different than this one.

**Comment by carlosjrcabello** [comment]
Ok Serge,

I'll open it.

**Comment by filterfan** [comment]
Thanks for your time in implementing this feature Serge. I do have some additional ideas to potentially consider (_you probably should not have asked!_):

1. **Shortcut**: 
Can you make it faster to access the filter IN context window? This might be a lazy request but rather than having to navigate through the right-click context menus to access the IN filter; it would be great if there was some sort of shortcut such as double-clicking on the column name brings up the window or clicking a drop down button such as in the image below. If you wanted to compare multiple columns quickly this would make it easier.
![image](https://cloud.githubusercontent.com/assets/18281814/15958538/22f63cbe-2eee-11e6-82f9-bd8b988eb1ca.png)

2. **Select all/ Select none button**
Can you add a "Select all" button to automatically select all distinct value tickboxes? I think you could either have two buttons "Select all" and "Select none / clear" or one button which changes it's behaviour based on the values selected (if all values selected, then button becomes "Select none"):
![image](https://cloud.githubusercontent.com/assets/18281814/15958963/5a57386e-2ef0-11e6-8fa2-cdcdd8a71592.png)

3. **NULL values as first option**
I think it would be useful if NULL values were put to the top of the list (if they exist)
![image](https://cloud.githubusercontent.com/assets/18281814/15959208/8b513eaa-2ef1-11e6-9bac-33344aa11df8.png)

4. **Filter text search**
It looks like you already have this feature but to confirm, it would be great if you could type some text in the available box to reduce the visible results "as you type". So typing "J" would reduce the visible list to values starting with "J" and typing "Jo" would list values starting with "Jo". This would also not deselect any values already selected even though there are less visible results:
![image](https://cloud.githubusercontent.com/assets/18281814/15959333/30541d46-2ef2-11e6-9180-a7cec2a8a818.png)

5. **Count occurences**
This might be a more ambitious request but would it be possible to show a count of the total times each distinct value appears in the table? If you could order the list of distinct values by total descending that would also be really useful. Please see my idea below:
![image](https://cloud.githubusercontent.com/assets/18281814/15959904/fa5813d4-2ef4-11e6-97bb-f23215043642.png)

6. **Able to copy selected text**
It would be great if it is possible to select any of the distinct values and be able to copy that text to the clipboard so you can paste it somewhere else (such as the editor). Please see the example below:
![image](https://cloud.githubusercontent.com/assets/18281814/15960047/d44ebf0c-2ef5-11e6-9c9d-4fe99817474d.png)

I look forward to hearing you thoughts on these additional ideas. Any of these features that you can add would be much appreciated.

**Comment by serge-rider** [comment]
1. Shortcut is already there (CTRL+F11 for now). It shows filters menu like on my first screenshot.
2. Will think about that. Generally selecting all values makes not much sense (it has the same result as no filter at all). But it may simplify value list edit.
3. Agreed. NULLs will be supported.
4. Value filter is already there.
5. Row count is a good idea.
6. Selection copy is implemented in the context menu

**Comment by filterfan** [comment]
Regarding the "Select all" / "Select none" button, I understand that selecting all values makes no sense but it can be used in various ways. Rather than selecting all values manually, by clicking "Select all" this enables you to start out with all values selected and then you can deselect values to exclude them. Similarly by clicking "Select none" you start out with nothing selected and then you select the values you want to see. It is two different approaches- start with everything and remove values or start with nothing and add values. This functionality is also implemented in Excel.

**Comment by filterfan** [comment]
Would it be easy enough to add sorting options? e.g.

- **Sort by values** (_ascending / descending_)
- **Sort by row count** (_ascending / descending_)

**Comment by serge-rider** [comment]
You can test current implementation in EA verison: http://dbeaver.jkiss.org/files/ea/

**Comment by filterfan** [comment]
Hi Serge,

i have done some basic tests in the following environment:

- **Windows 7 - 64 bit**
- **PostgreSQL 9.5.3** _(Win x86-64 installer)_
- **dbeaver-ce-3.6.10-x86_64-setup.exe**

The current implementation of the DBeaver EA version was last modified **2016-06-11 08:41** so may not have the recently added commits?

Here is a screenshot of the IN filter from the EA version listed above:

![image](https://cloud.githubusercontent.com/assets/18281814/15985562/d5bb822c-2fe9-11e6-93aa-584ed6477fba.png)


Here are some notes on the current version:

- CTRL+F11 shortcut is not working but I assume I can bind my own shortcut to the filters context window?
- Select all/none buttons not visible.
- NULL values are supported but are listed at the bottom.
- Value text filter is not visible.
- Row count is not visible.
- Selection copy does not work.
- Columns with integer data types are ordered as if they were text values (please see screenshot). **I think numbers should be ordered differently to text.**

The filter does work as expected other than the issues above. Is there a version available with all the latest commits implemented?

Also, do you think the sorting features are possible as said in my previous comment?

**Comment by serge-rider** [comment]
Ah, sorry, there was a build error I didn't notice so EA version was really old.
Try it again.

Select All/None and copy functions are accessible thru the context menu.
Sorting isn't yet ready.

**Comment by serge-rider** [comment]
In regards to not-working shortcut - you can try to reset UI settings (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace). Usually it helps.
As this is a EA I didn't yet decide what actual shortcut to use..

**Comment by filterfan** [comment]
I have installed the latest EA version and run the UI reset. Here are my notes:

**Fixed**
- CTRL+F11 shortcut is working to bring up the filter context window.
- Select All/None is working from right-click menu.
- NULL values are now listed first.
- Value text filter is visible.
- Row count is visible.
- Selection copy is working from right-click menu.
- Number data types are now ordered as numbers and not as text.

**Issue**

1. If value filter is used after Select All/None button is clicked then values are reset. Currently it reverts back to whatever value was selected in the results table before bringing up the filter IN context window. I think it should remember what values are selected even if you use the value filter bar.
2. If value filter is used, NULL values are still visible after typing something. Is this the intended behaviour?
3. Value filter is not available for integer data types (have not tested dates).
4. Sometimes the total in row count is blank. I am not sure why but it seems that if the value is the same as row count then it disappears. The total of the value 4 in the screenshot below should be 4 but is blank:
![image](https://cloud.githubusercontent.com/assets/18281814/15986485/eb2a93de-3000-11e6-9b9d-f50e7b65ed17.png)

5. Value filter does not work in some cases. The example below has one letter typed. It works correctly when two letters are typed. You can see that some row counts are also blank.
![image](https://cloud.githubusercontent.com/assets/18281814/15986594/6dd7d02e-3003-11e6-8058-e4b40f045b77.png)

6. I am not able to recreate this one, but I created a table and inserted some test values in it. When I clicked on the filter IN window, there were no row count totals and the "Count" column was called "Description". Not sure how this happened but it is working now.

**Comment by serge-rider** [comment]
1. Agreed. Its a more complicated thing, will add it later.
2. Yes, it is made on purpose. NULL is special and you cannot make a pattern which will include NULL values.
3. Yes, filter works only for strings. I can't figure out how to filter numbers. E.g. you enter filter value 100 - what values should present in the list? >=100? That's simple but doesn't make much sense. What pattern to use to find a big number like 100234567? The same about dates.
4. That's odd, I can't reproduce that. Could you post some example (e.g. dump of the table in INSERTs form)?
5. Looks correct for me. It searches by LIKE '%FILTER%', i.e. all strings which contains letter 'g' in your example.
6. Yes, this is also on purpose. By default DBeaver uses `SELECT ColumnName,count(*) FROM TABLE GROUP BY ColumnName` query to read value list. But if a column is a part of a foreign key then value filter works in a different fashion. It shows unique key from a referenced table (+ description columns). This is actually an old feature, it also works when you edit column value in preview panel (f7). Maybe some switcher/explanation will be useful here..

**Comment by filterfan** [comment]
Great, I am happy with these explanations. Here's a dump below of the test table that will reproduce the blank count error (PostgreSQL). Use the IN filter on the "forme" column:

```sql
create table  test (
    id     int,
	forme  varchar(255)
)
;

insert into  test
values       ('1','1'),('2','1'),('3','1'),('3','2'),('4','1'),('5','1'),('6','1'),('6','2'),('6','3'),('7','1'),('8','1'),('9','1'),('9','2'),('10','1'),('11','1'),('12','1'),('13','1'),('14','1'),('15','1'),('16','1'),('17','1'),('18','1'),('19','1'),('20','1'),('21','1'),('22','1'),('23','1'),('24','1'),('25','1'),('26','1'),('27','1'),('28','1'),('29','1'),('30','1'),('31','1'),('32','1'),('33','1'),('34','1'),('35','1'),('36','1'),('37','1'),('38','1'),('39','1'),('40','1'),('41','1'),('42','1'),('43','1'),('44','1'),('45','1'),('46','1'),('47','1'),('48','1'),('49','1'),('50','1'),('51','1'),('52','1'),('53','1'),('54','1'),('55','1'),('56','1'),('57','1'),('58','1'),('59','1'),('60','1'),('61','1'),('62','1'),('63','1'),('64','1'),('65','1'),('65','2'),('66','1'),('67','1'),('68','1'),('69','1'),('70','1'),('71','1'),('72','1'),('73','1'),('74','1'),('75','1'),('76','1'),('77','1'),('78','1'),('79','1'),('80','1'),('81','1'),('82','1'),('83','1'),('84','1'),('85','1'),('86','1'),('87','1'),('88','1'),('89','1'),('90','1'),('91','1'),('92','1'),('93','1'),('94','1'),('94','2'),('95','1'),('96','1'),('97','1'),('98','1'),('99','1'),('100','1'),('101','1'),('102','1'),('103','1'),('104','1'),('105','1'),('106','1'),('107','1'),('108','1'),('109','1'),('110','1'),('111','1'),('112','1'),('113','1'),('114','1'),('115','1'),('115','2'),('116','1'),('117','1'),('118','1'),('119','1'),('120','1'),('121','1'),('122','1'),('123','1'),('124','1'),('125','1'),('126','1'),('127','1'),('127','2'),('128','1'),('129','1'),('130','1'),('130','2'),('131','1'),('132','1'),('133','1'),('134','1'),('135','1'),('136','1'),('137','1'),('138','1'),('139','1'),('140','1'),('141','1'),('142','1'),('142','2'),('143','1'),('144','1'),('145','1'),('146','1'),('147','1'),('148','1'),('149','1'),('150','1'),('150','2'),('150','3'),('151','1'),('152','1'),('153','1'),('154','1'),('155','1'),('156','1'),('157','1'),('158','1'),('159','1'),('160','1'),('161','1'),('162','1'),('163','1'),('164','1'),('165','1'),('166','1'),('167','1'),('168','1'),('169','1'),('170','1'),('171','1'),('172','1'),('173','1'),('174','1'),('175','1'),('176','1'),('177','1'),('178','1'),('179','1'),('180','1'),('181','1'),('181','2'),('182','1'),('183','1'),('184','1'),('185','1'),('186','1'),('187','1'),('188','1'),('189','1'),('190','1'),('191','1'),('192','1'),('193','1'),('194','1'),('195','1'),('196','1'),('197','1'),('198','1'),('199','1'),('200','1'),('201','1'),('202','1'),('203','1'),('204','1'),('205','1'),('206','1'),('207','1'),('208','1'),('209','1'),('210','1'),('211','1'),('212','1'),('212','2'),('213','1'),('214','1'),('214','2'),('215','1'),('216','1'),('217','1'),('218','1'),('219','1'),('220','1'),('221','1'),('222','1'),('223','1'),('224','1'),('225','1'),('226','1'),('227','1'),('228','1'),('229','1'),('229','2'),('230','1'),('231','1'),('232','1'),('233','1'),('234','1'),('235','1'),('236','1'),('237','1'),('238','1'),('239','1'),('240','1'),('241','1'),('242','1'),('243','1'),('244','1'),('245','1'),('246','1'),('247','1'),('248','1'),('248','2'),('249','1'),('250','1'),('251','1'),('252','1'),('253','1'),('254','1'),('255','1'),('256','1'),('257','1'),('257','2'),('258','1'),('259','1'),('260','1'),('261','1'),('262','1'),('263','1'),('264','1'),('265','1'),('266','1'),('267','1'),('268','1'),('269','1'),('270','1'),('271','1'),('272','1'),('273','1'),('274','1'),('275','1'),('276','1'),('277','1'),('278','1'),('279','1'),('280','1'),('281','1'),('282','1'),('282','2'),('283','1'),('284','1'),('285','1'),('286','1'),('287','1'),('288','1'),('289','1'),('290','1'),('291','1'),('292','1'),('293','1'),('294','1'),('295','1'),('296','1'),('297','1'),('298','1'),('299','1'),('300','1'),('301','1'),('302','1'),('303','1'),('303','2'),('304','1'),('305','1'),('306','1'),('306','2'),('307','1'),('308','1'),('308','2'),('309','1'),('310','1'),('310','2'),('311','1'),('312','1'),('313','1'),('314','1'),('315','1'),('316','1'),('317','1'),('318','1'),('319','1'),('320','1'),('321','1'),('322','1'),('323','1'),('324','1'),('325','1'),('326','1'),('327','1'),('328','1'),('329','1'),('330','1'),('331','1'),('332','1'),('333','1'),('334','1'),('335','1'),('336','1'),('337','1'),('338','1'),('339','1'),('340','1'),('341','1'),('342','1'),('343','1'),('344','1'),('345','1'),('346','1'),('347','1'),('348','1'),('349','1'),('350','1'),('351','1'),('352','1'),('353','1'),('354','1'),('354','2'),('355','1'),('356','1'),('357','1'),('358','1'),('359','1'),('359','2'),('360','1'),('361','1'),('362','1'),('363','1'),('364','1'),('365','1'),('366','1'),('367','1'),('368','1'),('369','1'),('370','1'),('371','1'),('372','1'),('373','1'),('374','1'),('375','1'),('376','1'),('377','1'),('378','1'),('379','1'),('380','1'),('381','1'),('382','1'),('383','1'),('384','1'),('385','1'),('386','1'),('386','2'),('386','3'),('386','4'),('387','1'),('388','1'),('389','1'),('390','1'),('391','1'),('392','1'),('393','1'),('394','1'),('395','1'),('396','1'),('397','1'),('398','1'),('399','1'),('400','1'),('401','1'),('402','1'),('403','1'),('404','1'),('405','1'),('406','1'),('407','1'),('408','1'),('409','1'),('410','1'),('411','1'),('412','1'),('413','1'),('413','2'),('413','3'),('414','1'),('415','1'),('416','1'),('417','1'),('418','1'),('419','1'),('420','1'),('421','1'),('422','1'),('423','1'),('424','1'),('425','1'),('426','1'),('427','1'),('428','1'),('429','1'),('430','1'),('431','1'),('432','1'),('433','1'),('434','1'),('435','1'),('436','1'),('437','1'),('438','1'),('439','1'),('440','1'),('441','1'),('442','1'),('443','1'),('444','1'),('445','1'),('445','2'),('446','1'),('447','1'),('448','1'),('448','2'),('449','1'),('450','1'),('451','1'),('452','1'),('453','1'),('454','1'),('455','1'),('456','1'),('457','1'),('458','1'),('459','1'),('460','1'),('460','2'),('461','1'),('462','1'),('463','1'),('464','1'),('465','1'),('466','1'),('467','1'),('468','1'),('469','1'),('470','1'),('471','1'),('472','1'),('473','1'),('474','1'),('475','1'),('476','1'),('477','1'),('478','1'),('479','1'),('479','2'),('479','3'),('479','4'),('479','5'),('479','6'),('480','1'),('481','1'),('482','1'),('483','1'),('484','1'),('485','1'),('486','1'),('487','1'),('487','2'),('488','1'),('489','1'),('490','1'),('491','1'),('492','1'),('492','2'),('493','1'),('494','1'),('495','1'),('496','1'),('497','1'),('498','1'),('499','1'),('500','1'),('501','1'),('502','1'),('503','1'),('504','1'),('505','1'),('506','1'),('507','1'),('508','1'),('509','1'),('510','1'),('511','1'),('512','1'),('513','1'),('514','1'),('515','1'),('516','1'),('517','1'),('518','1'),('519','1'),('520','1'),('521','1'),('522','1'),('523','1'),('524','1'),('525','1'),('526','1'),('527','1'),('528','1'),('529','1'),('530','1'),('531','1'),('532','1'),('533','1'),('534','1'),('535','1'),('536','1'),('537','1'),('538','1'),('539','1'),('540','1'),('541','1'),('542','1'),('543','1'),('544','1'),('545','1'),('546','1'),('547','1'),('548','1'),('549','1'),('550','1'),('551','1'),('552','1'),('553','1'),('554','1'),('555','1'),('555','2'),('556','1'),('557','1'),('558','1'),('559','1'),('560','1'),('561','1'),('562','1'),('563','1'),('564','1'),('565','1'),('566','1'),('567','1'),('568','1'),('569','1'),('570','1'),('571','1'),('572','1'),('573','1'),('574','1'),('575','1'),('576','1'),('577','1'),('578','1'),('579','1'),('580','1'),('581','1'),('582','1'),('583','1'),('584','1'),('585','1'),('586','1'),('587','1'),('588','1'),('589','1'),('590','1'),('591','1'),('592','1'),('593','1'),('594','1'),('595','1'),('596','1'),('597','1'),('598','1'),('599','1'),('600','1'),('601','1'),('602','1'),('603','1'),('604','1'),('605','1'),('606','1'),('607','1'),('608','1'),('609','1'),('610','1'),('611','1'),('612','1'),('613','1'),('614','1'),('615','1'),('616','1'),('617','1'),('618','1'),('619','1'),('620','1'),('621','1'),('622','1'),('623','1'),('624','1'),('625','1'),('626','1'),('627','1'),('628','1'),('629','1'),('630','1'),('631','1'),('632','1'),('633','1'),('634','1'),('635','1'),('636','1'),('637','1'),('638','1'),('639','1'),('640','1'),('641','1'),('641','2'),('642','1'),('642','2'),('643','1'),('644','1'),('645','1'),('645','2'),('646','1'),('646','2'),('646','3'),('647','1'),('647','2'),('648','1'),('648','2'),('649','1'),('650','1'),('651','1'),('652','1'),('653','1'),('654','1'),('655','1'),('656','1'),('657','1'),('658','1'),('659','1'),('660','1'),('661','1'),('662','1'),('663','1'),('664','1'),('665','1'),('666','1'),('667','1'),('668','1'),('669','1'),('670','1'),('671','1'),('672','1'),('673','1'),('674','1'),('675','1'),('676','1'),('677','1'),('678','1'),('678','2'),('679','1'),('680','1'),('681','1'),('681','2'),('682','1'),('683','1'),('684','1'),('685','1'),('686','1'),('687','1'),('688','1'),('689','1'),('690','1'),('691','1'),('692','1'),('693','1'),('694','1'),('695','1'),('696','1'),('697','1'),('698','1'),('699','1'),('700','1'),('701','1'),('702','1'),('703','1'),('704','1'),('705','1'),('706','1'),('707','1'),('708','1'),('709','1'),('710','1'),('710','2'),('710','3'),('710','4'),('711','1'),('711','2'),('711','3'),('711','4'),('712','1'),('713','1'),('714','1'),('715','1'),('716','1'),('717','1'),('718','1')
;

select * from test
;
```

If you can get the sorting working as well for the next release that would be ideal.

Thanks.

**Comment by serge-rider** [comment]
Most of discussed issues will be added in 3.7.
Further improvements should be tracked in different issues.

**Comment by filterfan** [comment]
Great thank you very much! Can I ask when you are planning to release version 3.7?

**Comment by serge-rider** [comment]
Today evening
