### ISSUE TITLE
Export table data to nonexistent directory error

### ISSUE THREAD

**Issue by RobertoDebarba** [serge-rider/dbeaver#337]
When I try to export table data (as JSON for example) to a nonexistent directory the system shows an error message ("Data transfer IO error").
In my opinion the system should create the directory instead of show the error.  
  
When I try to export multiple table data thesystem shows an error for each selected table, crashing my Eclipse.
![error1](https://cloud.githubusercontent.com/assets/5933968/14298096/57b60c40-fb59-11e5-851a-4a26a4254e89.PNG)
![error](https://cloud.githubusercontent.com/assets/5933968/14298100/59db4a58-fb59-11e5-9122-ac28c821b469.png)

**Comment by serge-rider** [comment]
Thanks for report
