### ISSUE TITLE
"Edit Driver Settings" button is partially hidden in Oracle Connection Settings window

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#338]
When you open the "New Connection" window and select the Oracle driver, the vertical size of the Oracle Connection Settings window is not enough and the "Edit Driver Settings" button is partially hidden.

![image](https://cloud.githubusercontent.com/assets/8759452/14310090/57f91030-fbe0-11e5-893b-9bea1a5dc10d.png)

**Comment by serge-rider** [comment]
10x for report
