### ISSUE TITLE
PostgreSQL: Multi-database model support

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#34]
We need to refactor and improve DBS model to support multi-database engines (like PostgreSQL).

**Comment by serge-rider** [comment]
Database switch support has been added

**Comment by isapir** [comment]
I'm sorry, but how do I use this feature?  I created a database and now am trying to switch to it, but I keep getting the error of 'cross database references not implemented`.

**Comment by serge-rider** [comment]
Right click on a database->Set Active

**Comment by Wirone** [comment]
@serge-rider any chances for this feature in CE version?

**Comment by serge-rider** [comment]
It is (and always was) in CE version.

**Comment by Wirone** [comment]
@serge-rider Finally I figured it out, but it's not user friendly. I've migrated my Postgres data from previous laptop and I have multiple databases from the beginning. In configuration window I can't enter multiple databases (comma-separated, colon-separated, space-separated) to open connection. When I don't configure database name I just see `postgres` database and then I can't add already existing databases (for `Set Active` usage). I can create database but it disappears after reconnecting.... :(

**Comment by serge-rider** [comment]
Just enable "Show non-default databases" option in connection properties.

**Comment by Wirone** [comment]
Thank you very much, @serge-rider :-) What a shame I did not notice this option..

**Comment by KajKandler** [comment]
As of 2020 the option is called "Show all databases" on the "PostgreSQL" tab. You still have to define a default database, as it does not pick postgres anymore as default, when this flag is on.

**Comment by yaseen-h-pf** [comment]
As of 2024 This option is on the main tab now and even then I had to scroll to the right it to find it, truly a shame its not the default
