### ISSUE TITLE
Syntax highlight behaves weirdly when changing quote style

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#343]
I've noticed that changing quote styles will cause syntax highlighting to behave strangely

![syntax_highlighting](https://cloud.githubusercontent.com/assets/9246654/14329001/3dbbf6fc-fbee-11e5-9082-b42be3d9c99b.gif)

**Comment by ihabunek** [comment]
I have the same issue. 

The coloring changes when you enter a single quote without the closing quote (which is ok):

![image](https://cloud.githubusercontent.com/assets/482138/14884780/7c53a6de-0d47-11e6-8afa-d6f6f41f82c0.png)

But it's not reverted to proper syntax coloring when you enter the closing quote:

![image](https://cloud.githubusercontent.com/assets/482138/14884800/9ea7c68e-0d47-11e6-927a-40bd580776c4.png)

**Comment by serge-rider** [comment]
SQL syntax rules were fixed in 3.7.5 and a few extra fixes will be in 3.7.6.
Problems with single quote character aren't reproducible now.
