### ISSUE TITLE
PostgreSQL - show temporary tables in database navigator

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#344]
Hi,

Would it be difficult or is it possible to add temporary tables in the database navigator with PostgreSQL ?
For example, temporary tables could appear in a "temp" schema or in any other dedicated category.

Thanks in advance.

**Comment by serge-rider** [comment]
To view temp/toast tables you will need to enable utility objects visibility in connection properties:
![util-objects-config](https://cloud.githubusercontent.com/assets/6398845/14381132/98f44d36-fd8c-11e5-8202-98d1f059f17a.png)
Temporary tables usually resides in schemas pg_temp_x:
![util-objects-schemas](https://cloud.githubusercontent.com/assets/6398845/14381133/990ee5ec-fd8c-11e5-9981-8fa218421ddc.png)

**Comment by ced75** [comment]
Thanks a lot!

**Comment by Anarios** [comment]
Has this been deleted?

**Comment by E1izabeth** [comment]
@Anarios 
you can find it through navigator's context menu -> Connnection view -> Custom...
![image](https://user-images.githubusercontent.com/28875055/208990788-1c15c8b7-a21e-42af-b827-1610136bceb4.png)

or in the connection settings -> Navigator -> Navigator View : Customize..
![image](https://user-images.githubusercontent.com/28875055/208990990-c89c3e71-1425-43b6-b552-94d7da375e55.png)

**Comment by wistlo** [comment]
Footnote to this in Postgres 15.3 / dbeaver 23.0.5.   

1. Temporary table follows the `search_path` and connected database.  (wondering if that's a recent postGRES change?)

2. Cannot view the table in dBeaver as this would access a different session from editor.  

Still, useful to see it was created and if I need to see the table, just turn off `TEMPORARY `temporarily.

**Comment by dss010101** [comment]
so basically this does not show anything with pg15+, correct?
