### ISSUE TITLE
SQL autocomplete dropdown doesn't work properly when script contains comments

### ISSUE THREAD

**Issue by petrus0x13** [serge-rider/dbeaver#347]
1. Use PostgreSQL connector
2. Open SQL editor
3. Write down some queries on table a, b, c, comment it.
4. Start writing new query like "select * from d where " and try to autocomplete (ctr+space)

Result:
Columns that are suggested by dropdown will be from a, b or c table, not from d.

Version: 3.6.3

**Comment by serge-rider** [comment]
Can't reproduce.
Can you post an example of SQL queries?

**Comment by petrus0x13** [comment]
Database creation script below the scenario.

Scenario:
1. Type query: "select * from a", execute it.
2. Type query:
-- select * from a 
select * from b where
3. Press ctrl+space.
4. DBeaver will show dropdown with 'column1' and 'column2' which are present in 'a' table, not 'b'.
5. Remove first query (commented)
6. Press ctrl+space.
7. DBeaver will propose 'column3' and 'column4', which is correct.



CREATE DATABASE test
  WITH OWNER = root
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'pl_PL.UTF-8'
       LC_CTYPE = 'pl_PL.UTF-8'
       CONNECTION LIMIT = -1;

CREATE TABLE a
(
  column1 integer NOT NULL,
  column2 text,
  CONSTRAINT "keyA" PRIMARY KEY (column1)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE a
  OWNER TO root;

CREATE TABLE b
(
  column3 integer NOT NULL,
  column4 text,
  CONSTRAINT "keyB" PRIMARY KEY (column3)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE b
  OWNER TO root;

**Comment by tiagohipolito** [comment]
Same problem here happening not only on PostrgreSQL but on MySQL, DB2 and Oracle too.

Step 5 can be deleting commented query or just inserting a new empty line between them.

**Comment by serge-rider** [comment]
Now I can see it.
Thanks for report.
