### ISSUE TITLE
IOException still happening even after restore driver defaults

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#35]
Hi!

I tryed upgrade to the version 3.5.2, but I found this error:
```
DBException: Error resolving dependencies
  java.io.IOException: IOException: Maven artifact 'maven:/net.sourceforge.jtds:jtds:release' not found
```

I already reset the drivers defaults, restarted DBeaver, but nothing changes.

![captura de tela de 2015-11-03 09 29 35](https://cloud.githubusercontent.com/assets/7952798/10907678/6e96c392-8213-11e5-81ec-6eff67294855.png)

**Comment by serge-rider** [comment]
I think it is a result of the mess with maven artifacts config changes in 3.5.1->3.5.2. In most cases "Reset to defaults" helps but sometimes it is not.
Workaround:
- delete artifact "net.sourceforge.jtds:jtds:release" 
- add artifact "net.sourceforge.jtds:jtds:RELEASE"
- click on "Download/Update" -> Download.

**Comment by jeisoncp** [comment]
Problem solved. Thanks!

**Comment by jeisoncp** [comment]
Now, each time that I restart DBeaver, I have to do this fix.

The artifact "net.sourceforge.jtds:jtds:release" always comes back.

**Comment by serge-rider** [comment]
Well, let's use heavy weapons then.
- Close DBeaver
- Open file $HOME/.dbeaver/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml.
- Find the line with "net.sourceforge.jtds:jtds:release" in it and delete it.
- Start DBeaver

It is definitely not a general solution, just a workaround for the issue I can't reproduce.
Anyhow I'll add a fix in 3.5.3 which will solve similar problems.

**Comment by jeisoncp** [comment]
I edited the drives.xml, delete the line with wrong artifact, but each time that I run DBeaver, the line is inserted again.

And I tried more the once, just to make sure. :D

**Comment by jeisoncp** [comment]
I also tried edit drives.xml while DBeaver was running, then I started a connection. The exception error screen shows up and the line is inserted on the XML.

**Comment by serge-rider** [comment]
That's weird. Could you recheck that you are using 3.5.2 version?
If you have installed deb then try to remove /user/share/dbeaver (rm -rf) and reinstall again.
Also you could try EA version (http://dbeaver.jkiss.org/files/ea/), it contains some fixes related to driver management.

**Comment by jeisoncp** [comment]
Yep, 3.5.2, I checked in About menu. 

But now that you say, the JSON result set export it's not available...

**Comment by jeisoncp** [comment]
Now I think that the problem is definitely fixed. I deleted the /usr/share/dbeaver and install ea version.

Even the JSON export appears now.

Thanks again.

**Comment by serge-rider** [comment]
Great. So there were actually two different issues. That's why its was so hard to reproduce it.
I'll create another issue regarding problems with debian package upgrade..

**Comment by jomach** [comment]
@serge-rider I had the same problem with Hive driver. I deleted the complete block on the xml and then it works for me.
