### ISSUE TITLE
Oracle Connection TNS IFILE entry not working

### ISSUE THREAD

**Issue by d0petrix** [serge-rider/dbeaver#351]
For oracle configuration an IFILE entry can be used to include another configuration file. I am using this inside TNSNAMES.ORA to include the actual TNSNAMES.ORA from another location (so it can be updated from an SVN repository).
https://docs.oracle.com/cloud/latest/db112/REFRN/initparams103.htm#REFRN10070

DBeaver does not currently recognize this and only shows an IFILE entry in the Oracle connection Settings > General > TNS select box instead of the contents in the specified file.

**Comment by serge-rider** [comment]
DBeaver supports IFILE entries. But maybe not all possible forms of it.
Please post example of TNSNAMES with IFILE which isn't recognized.

**Comment by serge-rider** [comment]
Will reopen if new details will be provided.
