### ISSUE TITLE
Table name not quoted in query for table data tab

### ISSUE THREAD

**Issue by gintas** [serge-rider/dbeaver#352]
I have a table named "Option" on my SQL server database. If I double-click the table in DBeaver to view the data, I get an error about incorrect syntax (OPTION is a keyword). However, the query works when the table is quoted either in double quotes as "Option" or with brackets as [Option]. Seems like a good idea to quote table (and schema, and database) names by default.

**Comment by serge-rider** [comment]
Reserved keywords must be quoted.
Quoting all identifiers is simpler but isn't convenient.
I'll add SQL Server keywords in the list of reserved keywords.
