### ISSUE TITLE
Select caret position on templates

### ISSUE THREAD

**Issue by marco-sanjuan** [serge-rider/dbeaver#353]
Hi

I'm moving from TOAD to DBeaver and by now I'm really happy :D 

One little thing I miss is the ability to set caret position when inserting a template value into a sql editor.
In TOAD you can use a pipe to set where cursor must be placed after insert the template, because often you want to insert parameters to queries.
Ex: 
SELECT * FROM USERS
WHERE dept= |
ORDER BY ID

This is a simple query but for complex ones it is very useful to be auto-positioned.

Hope you consider the improvement.

That's a lot!
Marco

**Comment by serge-rider** [comment]
You can use ${cursor} variable for that.
Check this: https://github.com/serge-rider/dbeaver/wiki/SQL-Editor-templates

**Comment by marco-sanjuan** [comment]
Wow thanks! I missed that configuration...

**Comment by serge-rider** [comment]
I've just created it.
Wait for 3.6.4 release for ${cursor} variable support.

**Comment by marco-sanjuan** [comment]
Oh i didn't understood your, then more thanks to you :P

**Comment by marco-sanjuan** [comment]
And last for template section, could it be possible to use also CTRL+SPACE to insert templates? This is the default key on toad and imagine our continuous mistakes :P

Thanks for your help, great job!
