### ISSUE TITLE
MySQL Database export - customize output file names

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#356]
In version 3.6.3 I can select file for dump in dialog Database export, but after upgrade to 3.6.4 I can choose only dir and dump file name is generated automatically.

* In 3.6.3 field Output File has path to file and icon next to field opens dialog to select file
* In 3.6.4 field Output File has path to dir and icon next to field opens dialog to select dir

Can you revert behavior from version 3.6.3?

**Comment by serge-rider** [comment]
I don't think so.
Now you can export multiple databases - which means multiple output files.
If you need some specific output file name then the only workaround I see is to make file names configurable (using some template).

**Comment by MatyCZ** [comment]
If you add configurable templates, it will be OK.

**Comment by MatyCZ** [comment]
One more thing. Hour in dump file timestamp has 12h format, can you edit it to 24h format?

* dump-test-201604111242.sql - 2016-04-11 12:42:00
* dump-test-201604110140.sql - 2016-04-11 13:40:00 - I dont know if this is 01:40 or 13:40

**Comment by serge-rider** [comment]
Ok
