### ISSUE TITLE
MySQL Database export - Unchecked field "Export views" exports views

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#357]
1. Database Navigator > Tools > Export database
2. Dont change anything in modal (1 object is selected, all tables are selected and field "Export views" is unchecked)
3. Start export
4. Generated dump file contains views

**Comment by serge-rider** [comment]
This is a UI bug actually. This checkbox has to have name "Show views".
To provide ability to export definition for particular views.
If you exporting full database then it will be exported with all database objects (including views, procedures, etc).
