### ISSUE TITLE
Oracle triggers not loaded in DBeaver (but are correctly loaded in TOAD)

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#358]
If you CTRL + Click on a table that has a trigger and select "Trigger" from the table information panel, no data is loaded:

![image](https://cloud.githubusercontent.com/assets/8759452/14453884/b20067ca-0097-11e6-9d9d-1056ba4ab61c.png)

Using the same user in TOAD all the triggers are corrrectly loaded:

![image](https://cloud.githubusercontent.com/assets/8759452/14453898/c1fc2bb4-0097-11e6-8df2-b95b6f57143f.png)

Looing in the query manager seems that the following query in DBeaver gives no result:

```SQL
SELECT *
FROM SYS.ALL_TRIGGERS WHERE OWNER='CLL'
ORDER BY TRIGGER_NAME
```

**Comment by serge-rider** [comment]
Yeah, it is hard to compete with TOAD ;) Sometimes they use non-standard ways to extract metadata.
If there is nothing in ALL_TRIGGERS maybe there is something in the USER_TRIGGERS or in the DBA_TRIGGERS?

**Comment by operationgamma** [comment]
The query should bring back results - there'd be no need for anything non-standard.  The only way I can get something similar to these screens in a way that might be similar, is if I use the 'Filter' icon on the right side of the bar that says 'No items' above.

Add an incorrect filter in here with the checkbox to enable them, and despite the triggers existing on the table I would get the same display.
