### ISSUE TITLE
[3.6.4] PostgreSQL: NumberFormatException: For input string: "5beta2"

### ISSUE THREAD

**Issue by ParoX2k** [serge-rider/dbeaver#359]
1.) Fresh installation of dbeaver-ce-3.6.4-x86
2.) Added postgresql driver 9.4.1208.jre7 with the help of the wizard (screenshot 1)
3.) When trying to connect to postgresql server, GUI is screwed up ("Failed to create the part's controls), and error log show "Error initalizing datasource: invalid version 9.5beta2: non-numeric 5beta2" (screenshot 2)

![2016-04-12 14_29_41-edit driver postgresql](https://cloud.githubusercontent.com/assets/1461398/14460056/b6bbc4c0-00bb-11e6-9c68-9bf05ffaa217.png)

![2016-04-12 14_28_58-event details](https://cloud.githubusercontent.com/assets/1461398/14460058/bd543998-00bb-11e6-9580-8a9e30e46690.png)

**Comment by serge-rider** [comment]
It is a bug in PG version detection function.
Will be fixed in the next version
