### ISSUE TITLE
Log data changes made from result set editor

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#36]
Data changes made directly in result set editor aren't showed in Excussion Log tab. Only the SQL commands executed from script editor are logged.

I guess that would be a new feature.

**Comment by serge-rider** [comment]
Data editor updates are logged as "Utility functions".

Preferences->Common->Query Manager. Check all Object types and query types. Now execution log will show all queries processed by DBeaver.

**Comment by jeisoncp** [comment]
I checked all object types and query types, then I updated a specific column data, but the UPDATE entry not appears in the log.

**Comment by serge-rider** [comment]
Yep. It is actually a bug.
Query manager settings affects global Query Manager view but doesn't work for SQL editor Execution Log tab.

**Comment by serge-rider** [comment]
Fixed

**Comment by jeisoncp** [comment]
I saw that the changes made from result set editor now are logged in the Execution Log tab. But in the SQL/UTIL commands, the parameters are not showed, just an interrogation point instead. 

For example:
Current: UPDATE person SET name = ? WHERE id = ?;
Suggestion: UPDATE person SET name = 'Jeison' WHERE id = 1;

**Comment by serge-rider** [comment]
Please create another issue (feature request).
Its really inconvenient to track multiple questions in a single issue.

**Comment by jeisoncp** [comment]
Sorry, I was in doubt if I should create another issue or not.
