### ISSUE TITLE
Oracle database table loading is slow

### ISSUE THREAD

**Issue by BuZZ-dEE** [serge-rider/dbeaver#360]
See topic: ["Faster Oracle table loading"](http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=2964)

**Comment by serge-rider** [comment]
What is your Oracle server version?

**Comment by BuZZ-dEE** [comment]
Oracle Database 12c Enterprise Edition / 12.1.0.2.0 / 64bit Production

**Comment by serge-rider** [comment]
Has anything changed since 3.6.5? There were a couple of minor fixes in Oracle metadata reading.

**Comment by BuZZ-dEE** [comment]
No, it is the same like before.

**Comment by serge-rider** [comment]
Looks like constraints metadata loading takes most of time.
Please post new log (in text form) from Query Manager.

**Comment by masebu** [comment]
Hi, I'm also interested in this issue.
I'm testing dbeaver 3.6.9 on Oracle 12c.
The DB hosts a PeopleSoft application, it's quite large.

Below is the Query Manager Log when I execute a query on a 1 row, 160 cols table right after connection.
I understand the ALL_ALL_TABLES / ALL_OBJECTS part is executed only once per connection. I'm surprised it does not occur upon connection along with other SQL/META that happen at that time, but rather wait for the first query to be executed.
The constraints metadata lookup does indeed take a lot of time. On my DB, removing the /*+RULE*/ hint speeds up things a lot, but I can't tell if that would be a general rule.
The ALL_TAB_COLS is also rather long (we've got 580000+ lines here at the moment)

Thanks for looking into this.

`12:01:10	SQL / UTIL	DECLARE l_line varchar2(255); l_done number; l_buffer long; BEGIN LOOP EXIT WHEN LENGTH(l_buffer)+255 > :maxbytes OR l_done = 1; DBMS_OUTPUT.GET_LINE( l_line, l_done ); l_buffer := l_buffer || l_line || chr(10); END LOOP; :done := l_done; :buffer := l_buffer; END;	55 ms		Success	AL_HR89PROD	SQLEditor <Script-2.sql>

12:01:02	SQL / META	SELECT /*+RULE*/ 
c.TABLE_NAME, c.CONSTRAINT_NAME,c.CONSTRAINT_TYPE,c.STATUS,c.R_OWNER,c.R_CONSTRAINT_NAME,ref.TABLE_NAME as R_TABLE_NAME,c.DELETE_RULE, 
col.COLUMN_NAME,col.POSITION
FROM SYS.ALL_CONSTRAINTS c
JOIN SYS.ALL_CONS_COLUMNS col ON c.OWNER=col.OWNER AND c.CONSTRAINT_NAME=col.CONSTRAINT_NAME
JOIN SYS.ALL_CONSTRAINTS ref ON ref.OWNER=c.r_OWNER AND ref.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME 
WHERE c.CONSTRAINT_TYPE='R' AND c.OWNER='SYSADM' AND c.TABLE_NAME='PS_INSTALLATION'
ORDER BY c.CONSTRAINT_NAME,col.POSITION	7019 ms	0	Success	AL_HR89PROD	Metadata

12:00:43	SQL / META	SELECT /*+RULE*/
c.TABLE_NAME, c.CONSTRAINT_NAME,c.CONSTRAINT_TYPE,c.STATUS,c.SEARCH_CONDITION,col.COLUMN_NAME,col.POSITION
FROM SYS.ALL_CONSTRAINTS c
JOIN SYS.ALL_CONS_COLUMNS col ON c.OWNER=col.OWNER AND c.CONSTRAINT_NAME=col.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE<>'R' AND c.OWNER='SYSADM' AND c.TABLE_NAME='PS_INSTALLATION'
ORDER BY c.CONSTRAINT_NAME,col.POSITION	18752 ms	159	Success	AL_HR89PROD	Metadata

12:00:43	SQL / META	SELECT /*+RULE*/ i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND
FROM SYS.ALL_INDEXES i 
JOIN SYS.ALL_IND_COLUMNS ic ON ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME
WHERE  i.TABLE_OWNER='SYSADM' AND i.TABLE_NAME='PS_INSTALLATION'
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION	56 ms	0	Success	AL_HR89PROD	Metadata

12:00:34	SQL / META	SELECT c.*
FROM SYS.ALL_TAB_COLS c
WHERE c.OWNER='SYSADM' AND c.TABLE_NAME='PS_INSTALLATION'	9128 ms	160	Success	AL_HR89PROD	Metadata

12:00:27	SQL / META		SELECT /*+RULE*/ t.OWNER,t.TABLE_NAME as TABLE_NAME,'TABLE' as OBJECT_TYPE,'VALID' as STATUS,t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.SECONDARY,t.NESTED,t.NUM_ROWS 
	FROM SYS.ALL_ALL_TABLES t
	WHERE t.OWNER='SYSADM' AND NESTED='NO'
UNION ALL
	SELECT /*+RULE*/ o.OWNER,o.OBJECT_NAME as TABLE_NAME,'VIEW' as OBJECT_TYPE,o.STATUS,NULL,NULL,NULL,NULL,NULL,NULL,o.TEMPORARY,o.SECONDARY,NULL,NULL 
	FROM SYS.ALL_OBJECTS o 
	WHERE o.OWNER='SYSADM' AND o.OBJECT_TYPE='VIEW'
	7680 ms	44649	Success	AL_HR89PROD	Metadata

12:00:26	SQL / USER	SELECT * FROM PS_INSTALLATION	118 ms	1	Success	AL_HR89PROD	SQLEditor <Script-2.sql>`

**Comment by serge-rider** [comment]
Yep, RULE hint is controversial. On some databases in significantly increases performance, on others drops it down.
http://dba.stackexchange.com/questions/114631/how-to-tune-the-query-on-all-constraints-in-oracle-12c/114652

On my test Oracle 12.1.0.1.0 RULE increases performance in 5-10 times.
Author of this topic has Oracle 12.1.0.2.0. What's yours?

**Comment by masebu** [comment]
Sorry, what I posted yesterday related to a Oracle 10g (10.2.0.5.0) environment (will upgrade next month).
However, it's true also on our test Oracle 12.1.0.1.0.
For both connections I use the 12c jdbc client (ojdbc7.jar)

`SELECT /*RULE*/
c.TABLE_NAME, c.CONSTRAINT_NAME,c.CONSTRAINT_TYPE,c.STATUS,c.SEARCH_CONDITION,col.COLUMN_NAME,col.POSITION
FROM SYS.ALL_CONSTRAINTS c
JOIN SYS.ALL_CONS_COLUMNS col ON c.OWNER=col.OWNER AND c.CONSTRAINT_NAME=col.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE<>'R' AND c.OWNER='SYSADM' AND c.TABLE_NAME='PS_INSTALLATION'`
159 rows (there's ~385000 rows in both ALL_CONSTRAINTS AND ALL_CONS_COLUMNS)

 | testing 12g | production 10c
------------ | ------------- | -------------
without hint | 1289 ms | 1007 ms
with rule hint | 27075 ms | 46983 ms

1. is it possible to customize the metadata queries on a per-install basis ?
2. is there any way to disable metadata fetching completely; what would be the effects besides losing autocompletion ?

**Comment by serge-rider** [comment]
I can add an option in Oracle driver preferences which will disable/enable hint. However best solution would be to somehow determine this option basing on database/driver version.
I'll recheck ojdbc7 driver in my environment..

Disabling constraints reading will disable a lot of features. Auto-complete, foreign keys navigation, unique keys search (for data edit), ERD connections and some other. So i don't think it is an option.

**Comment by serge-rider** [comment]
Just tested it again.
So I have exactly the same Oracle server version and exactly the same JDBC driver.
Querying ALL_CONSTRAINTS with RULE hint takes 200ms, without hint 6200ms. 
Difference 30 times
So I give up. I'll add an extra config option which will enable/disable RULE hint:

![ora-extra-props](https://cloud.githubusercontent.com/assets/6398845/15778435/e846f4ea-299e-11e6-8fbf-b406fd62b914.png)
It is disabled by default. Not sure it is the best choice - how many people needs this hint and how many don't. We'll see.
Please try EA version (http://dbeaver.jkiss.org/files/ea/) and check how it works in your environment.

**Comment by masebu** [comment]
The new parameter is well taken into account and the timings read in the Query Manager log are much better for me.

I'll try it for the next few days to see if it's generally responsive.

Thanks

**Comment by gyratefiber** [comment]
Using Oracle's Peoplesoft instance with dbeaver as well. 
I just tried the EE version for this, the difference is amazing. 
I didn't want to be stuck with Oracle's SQL Developer bloat. 
Thanks!

**Comment by serge-rider** [comment]
Good, thanks for info.

**Comment by tamushka** [comment]
Enabling RULE hint made life so much better for me! Can't believe I waiting all this time to look this issue up.
