### ISSUE TITLE
Schema objects not loaded at refresh (PostgreSQL)

### ISSUE THREAD

**Issue by imregreilich** [serge-rider/dbeaver#361]
Hi, 

I just started using DBeaver a few days ago on a PostgreSQL database. My problem is the following: 
There are 4 schemas in the database (next to the public, pg_catalog and information_schema). Let's call them A, B, C and D. A is created by user X and can only be read by user Y. B, C and D are created and owned by user Y and can be read / written by user Y. 
When I log in to the database with user Y, all the objects (table names / functions etc.) are loaded to the object browser from schemas A (which is owned by another user) and B (which is the default schema for user Y). But schemas C and D are not loaded, so I can't open the objects in the viewer, nor use auto-complete for those schemas. 

I checked, they are not in the filter. The schema names are visible (even for auto-complete), but the tables / functions are not. I tried refreshing them and still nothing. A "permission denied for relation pg_authid" error used to appear, but not anymore. I can run queries on those tables, they are just not visible. 

Anyone has any idea? 
Thanks, 
Imre

**Comment by serge-rider** [comment]
Check Error Log view for any errors/ warnings which appears there during connection.

**Comment by imregreilich** [comment]
Hi! 
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42501]: ERROR: permission denied for relation pg_authid
This is what I got after restarting the application, connecting and double clicking on the schema name. I tried Squirrel and EMS Sql Manager before, and those could access the object list. Is it possible that DBeaver is just using some other method / query to get the list of objects?

**Comment by serge-rider** [comment]
I still can't reproduce that. Actually don't really understand the use case.

Is it related to the navigator refresh (as specified in issue title) or you just don't see schema contents at all?

**Comment by imregreilich** [comment]
I don't see schema contents at all. Even the 2 schemas, which had content earlier, now don't have any (A and B in the description above). I only see the schema names, and if I open the schema browser, tables and procedures are all empty. 
It seems to me that the "permission denied for relation pg_authid" error stops the client to continue refreshing the objects. I tried the same in a localhost database, where I gave permission to the user to read pg_authid table, and it refreshed successfully. But in this remote database I don't have admin user, so I can't do the same.

**Comment by serge-rider** [comment]
There should be something in logs. It can't just quietly ignore schema contents.
Please check debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by imregreilich** [comment]
Indeed I found something. 
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/219344/dbeaver-debug.txt)
It looks like the OID problem what I found in [this](http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=2973) issue. So as I see now, it is a known issue and will be fixed? (I have 3.6.4 on a Windows 7 64 bit machine) 

Thank you!

**Comment by serge-rider** [comment]
Yep, it seems to be the same issue. If so then it is already fixed.
Because of #367 I'm going to release hotfix version today night so you can check how it works tomorrow.
