### ISSUE TITLE
Postgres dropping functions error

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#366]
Issuing 'Delete' menu command on a function issues DROP PROCEDURE instead of DROP FUNCTION, which is not a legal DDL command in pg, so it throws an error.

Postgres doesn't support procedures as such (but they might very well appear in the future), perhaps it would be better if they would be called "Functions" as they are referred to in postgres documentation.

Another quite useful feature would be to use the icon in the navigator to indicate the function language. This is quite useful info and this would make it visible at a glance. Now all the icons are the same so they don't really convey any extra information to the user.

**Comment by serge-rider** [comment]
10x for report
