### ISSUE TITLE
Incorrect table UPDATE in PostgreSQL (v. 3.6.4, critical)

### ISSUE THREAD

**Issue by psyonara** [serge-rider/dbeaver#367]
In version 3.6.4 (confirmed working in 3.6.3), when you open a PostgreSQL table (not tested with other DBs), switch to the "Data" tab, then edit a field (or multiple) by hand (tried with boolean, integer, and date-time), and apply the change, then refresh, every row in that table is updated, setting that field to a seemingly random value. For date/time, every row was changed to the same date, but not the one I had specified. For boolean, the result seemed random. For integer, when I changed some rows from "0" to "1", all other rows would randomly change to either 0 or 1. At least to me it seems random, haven't detected a pattern.

If this indeed a bug, it is catastrophic, since data that was never edited is randomly changed.

**Comment by serge-rider** [comment]
Can't reproduce.

Sounds very odd. Is there anything special about that table - does it use OID identifier, what structure of PK is has? DDL would be helpful.

DBeaver logs each and every SQL it executes. Go to preferences->Database->Query Manager and enable all query types and all object types.
Then open Query Manager view.
Then try to edit table and you will see actual SQL executed.

**Comment by psyonara** [comment]
Thanks, I'll play around with it and see what I can find. But I suspect something is not right, since switching back to 3.6.3 without any other changes causes it to function normally again.

**Comment by psyonara** [comment]
Some revealing results. The table I'm updating has the field "id" as the primary key, and has another field "created_by_id". So when I update the value of a field (e.g. boolean field "foo") using version 3.6.4, it seems that it thinks that "created_by_id" is the PK, as the query that it runs has:
```
UPDATE blah
SET foo = TRUE
WHERE created_by_id=123
```
But "created_by_id" is not even marked as unique, and so all the rows with that value get updated. So it's not random after all.

See if you can reproduce it now, otherwise let me know what else you need.

**Comment by psyonara** [comment]
DDL for one of the tables it's happening on: (many of my tables have "id" and "created_by_id" as fields)
```
CREATE TABLE public.reports_reporttype (
	id int4 NOT NULL DEFAULT nextval('reports_reporttype_id_seq'::regclass),
	date_created timestamptz NOT NULL,
	created_by_id int4 NOT NULL,
	date_modified timestamptz NOT NULL,
	modified_by_id int4 NOT NULL,
	date_deleted timestamptz NULL,
	deleted_by_id int4 NULL,
	name varchar(100) NOT NULL,
	config_id varchar(50) NOT NULL,
	config_file varchar(100) NOT NULL,
	minimum_role int4 NOT NULL,
	visible bool NOT NULL,
	output_type int4 NOT NULL,
	CONSTRAINT reports_reporttype_pkey PRIMARY KEY (id),
	CONSTRAINT created_by_id_refs_id_d0d6c938 FOREIGN KEY (created_by_id) REFERENCES public.useraccounts_useraccount(id),
	CONSTRAINT deleted_by_id_refs_id_d0d6c938 FOREIGN KEY (deleted_by_id) REFERENCES public.useraccounts_useraccount(id),
	CONSTRAINT modified_by_id_refs_id_d0d6c938 FOREIGN KEY (modified_by_id) REFERENCES public.useraccounts_useraccount(id)
)
WITH (
	OIDS=FALSE
);

CREATE INDEX reports_reporttype_created_by_id ON public.reports_reporttype (created_by_id);

CREATE INDEX reports_reporttype_deleted_by_id ON public.reports_reporttype (deleted_by_id);

CREATE INDEX reports_reporttype_modified_by_id ON public.reports_reporttype (modified_by_id);
```

As an example, I would update the "output_type" field on one row, and then all records with the same "created_by_id" value would be updated as well.

**Comment by pAnt0n** [comment]
I confirm this issue as described

**Comment by serge-rider** [comment]
Yes, it is a bug in the 3.6.4 version. It is PostgreSQL specific - DBeaver uses first first non-unique index as table primary key.
This is definitely a critical bug.
I will release hotfix version today night.
Thanks for report!

**Comment by psyonara** [comment]
Woohoo, glad you could find the bug. Look forward to the new version. :+1:
