### ISSUE TITLE
Oracle - Table DDL cannot be retrieved from Information Panel

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#37]
Using Oracle 11g, when you open the information panel related to an existing table (either by double-clicking table name in DB navigator or by Ctrl + Clicking on table name in editor) and select the **DDL** tab, the following error is displayed and the DDl for the selected table canot be retrieved:

![oracle_ddl_error](https://cloud.githubusercontent.com/assets/8759452/10934555/dbbfb276-82e0-11e5-850a-aa9ad3a56a1c.png)

The table exists in the selected schema because I can execute queries on it.
Using another tool (i.e. Toad) the DDL is correctly retrieved.

**Comment by serge-rider** [comment]
Does this error happen for all tables or only for some particular ones?
Is this table is a regular table or there is something special about it?

**Comment by serge-rider** [comment]
Just reproduced this on IOT table. 
Please confirm that in your case this error happens with index organized tables as well (and doesn't happen with other table types).

**Comment by steromano87** [comment]
Hi Serge,

from our DB I cannot say precisely if the table I used to find this bug is a IOT table or not...
If I execute the following query:
```SQL
select
	TABLE_NAME,
	IOT_NAME,
	IOT_TYPE
from SYS.ALL_TABLES
where OWNER = {my table owner}
	and TABLE_NAME = {my table}
```
the values for IOT_NAME and IOT_TYPE are both null, so I suppose the table is an ordinary table.

Additionally, the reported issue happens with all the tables of our test DB, but does not happen with the development DB, so maybe this could be related to some Oracle instance settings.

**Comment by serge-rider** [comment]
Then most likely this is a security problem: http://stackoverflow.com/questions/116522/what-oracle-privileges-do-i-need-to-use-dbms-metadata-get-ddl
Do you use exactly the same credentials/role as in TOAD?

**Comment by steromano87** [comment]
Hi Serge,

Yes, I use exactly the same account both in Toad and in DBeaver. This account has full CRUD permissions on records on tabled.

**Comment by serge-rider** [comment]
Hi Stefano,

As I still can't reproduce this in my environment I have to ask for your assistance. Could you try the same trick as in #41: execute following query
```
SELECT DBMS_METADATA.GET_DDL('TABLE', '<table-name>', '<schema-name>') FROM DUAL
```
in both TOAD and DBeaver?

Thanks

**Comment by steromano87** [comment]
Hi Serge,

investigating a little further, this issue seems related to the fact that, to retrieve a table DDL, the current schema should be canged into desired table schema. Generating the DDL of a table in the tablespace of the current user works.

A possible workaround that retrieves table specs (excluding indexes) is the following:
```SQL
with table_ddl as (
	select  table_name as table_name,
	        0 as linenum,
	        'CREATE TABLE ' ||
	        rtrim(table_name) ||
	        '(' as DDL
	from    dba_tables
	where   owner = upper('{schema}')
	union
	select  tc.table_name as table_name,
	        column_id as linenum,
	        decode(column_id,1,'    ','   ,')||
	        rtrim(column_name)|| chr(9) || chr(9) ||
	        rtrim(data_type) ||
	        rtrim(decode(data_type,'DATE',null,'LONG',null,
	               'NUMBER',decode(to_char(data_precision),null,null,'('),
	               '(')) ||
	        rtrim(decode(data_type,
	               'DATE',null,
	               'CHAR',data_length,
	               'VARCHAR2',data_length,
	               'NUMBER',decode(to_char(data_precision),null,null,
	                 to_char(data_precision) || ',' || to_char(data_scale)),
	               'LONG',null,
	               '******ERROR')) ||
	        rtrim(decode(data_type,'DATE',null,'LONG',null,
	               'NUMBER',decode(to_char(data_precision),null,null,')'),
	               ')')) || chr(9) || chr(9) ||
	        rtrim(decode(nullable,'N','NOT NULL',null)) as DDL
	from    dba_tab_columns tc,
	        dba_objects o
	where   o.owner = tc.owner
	and     o.object_name = tc.table_name
	and     o.object_type = 'TABLE'
	and     o.owner = upper('{schema}')
	union
	select  table_name as table_name,
	        999999 as linenum,
	        ')'  || chr(10)
	        ||'  STORAGE('                                   || chr(10)
	        ||'  INITIAL '    || initial_extent              || chr(10)
	        ||'  NEXT '       || next_extent                 || chr(10)
	        ||'  MINEXTENTS ' || min_extents                 || chr(10)
	        ||'  MAXEXTENTS ' || max_extents                 || chr(10)
	        ||'  PCTINCREASE '|| pct_increase                || ')' ||chr(10)
	        ||'  INITRANS '   || ini_trans                   || chr(10)
	        ||'  MAXTRANS '   || max_trans                   || chr(10)
	        ||'  PCTFREE '    || pct_free                    || chr(10)
	        ||'  PCTUSED '    || pct_used                    || chr(10)
	        ||'  PARALLEL (DEGREE ' || rtrim(DEGREE) || ') ' || chr(10)
	        ||'  TABLESPACE ' || rtrim(tablespace_name)      ||chr(10)
	        ||'/'||chr(10)||chr(10) as DDL
	from    dba_tables
	where   owner = upper('{schema}')
	order by 1,2
)
select DDL from table_DDL
where table_name = '{table_name}'
```

It is a bit ugly but works with no particular privileges...

Reference: [Burleson Oracle DBA](http://www.dba-oracle.com/oracle_tips_dbms_metadata.htm)

**Comment by steromano87** [comment]
It seems that TOAD internally queries SYS tables to manually retrieve table DLLs.
Here you can find an example of such a script (in hope it is helpful to solve the problem): [Ask Tom](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:1464804639878#1817586421806)

**Comment by steromano87** [comment]
Hi Serge,

maybe there is a bug in the bug... after the reported error occurs, for some tables the Ctrl + Click feature does not work anymore if table is written as {schema}.{table_name} in the editor (but wrks if there is table name only).

If you disconnect and reconnect again on the same connection, this feature works normally.

**Comment by serge-rider** [comment]
I tried both ways to construct DDL manually.
1st way doesn't work without DBA permissions (it queries DBA_* views). So I don't see any sense doing it.
2nd way generates DDL which significantly differs from DDL generated by DBMS_METADATA.GET_DDL. It actually combines metadata from ALL_* views. Potentially DBeaver can generate table DDL on client side from the metadata it already has.

I'll try to apply some workaround. Not yet decided which one in particular :)

**Comment by adesst** [comment]
Serge,

I also has the same problem but as per your comment

> serge-rider commented on Nov 4, 2015

confirm that it solves my error.

I connect to my oracle, say DBA1_APPL, and able to generate the DDL script.
The error raised when i login as other user and tried to generate DDL of other schema.

Linux, debian8 64bit.

**Comment by serge-rider** [comment]
I'll generate default DDL (on DBeaver side) if DBMS_METADATA.GET_DDL will fail.
Can't invent any better solution. for now.

**Comment by r-richmond** [comment]
I just had this exact issue.

I resolved it by running 

grant select_catalog_role to {user};
