### ISSUE TITLE
Phoenix HBase support

### ISSUE THREAD

**Issue by zinking** [serge-rider/dbeaver#371]
I'm planning to add some little support for phoenix hbase 

basically it provides a jdbc driver so most of it works. unfortunately it has special syntax 'upsert' which doesn't support 'update' so, apply changes on the grid will fail as it issues 'update' command instead of 'upsert' command. hence my intention is to change that bit. 

my plan is 
- give an extra tiny driver , probably just fork from vertica
- extend the 'applyChanges' command and handler

is this appropriate way to achieve this ?

**Comment by zinking** [comment]
some drafts here: https://github.com/serge-rider/dbeaver/compare/devel...zinking:phoenix?expand=1

**Comment by serge-rider** [comment]
I think that the best way to solve this is to extend SQLDialect interface and allow to redefine syntax of INSERT/UPDATE statements.
applyChanges just invokes underlying model functions (most of DML queries reside in JDBCTable class).
Post a few examples of UPSERT statement.

BTW what functions do want to cover in Phoenix extension (besides UPSERT) - does it support DDL view or some special metadata objects?

**Comment by zinking** [comment]
the UPSERT reference https://phoenix.apache.org/language/index.html#upsert_values

UPSERT INTO TEST VALUES('foo','bar',3);
UPSERT INTO TEST(NAME,ID) VALUES('foo',123);

it does support VIEWS/INDEX/FUNCTION etc... yeah these should be planned as well. 

for my usage I need the edit functionality , plus one json editor, some appropriate similar PR should get me started.

**Comment by zinking** [comment]
how to reference the modified driver plugin in Connection panel ? @serge-rider

**Comment by serge-rider** [comment]
Yeah, I meant something like that.
I'm going to make core model refactoring by myself (in near days), then you can make pull request with Phoenix extension and I will merge it.

To include plugin in the product it has to be added in one of the product features. E.g. here: https://github.com/serge-rider/dbeaver/blob/devel/features/org.jkiss.dbeaver.ext.generic.feature/feature.xml

**Comment by zinking** [comment]
okay, edit/insert/delete support seems working fine now.

and I am adding support for the phoenix array type. but seems I can't hook things up again.  @serge-rider  see the updated PR, I'm not quite sure how the dataSource for the arrayType provider should be configured.  how to deal with that part?

`+    <extension point="org.jkiss.dbeaver.dataTypeProvider">
 +        <provider
 +                class="org.jkiss.dbeaver.ext.phoenix.model.data.PhoenixValueHandlerProvider"
 +                description="phoenix data types provider"
 +                id="org.jkiss.dbeaver.ext.phoenix.model.data.PhoenixValueHandlerProvider"
 +                label="Phoenix data types provider">
 +
 +            <datasource id="phoenixSource"/> 
 +            <type standard="ARRAY"/>
 +        </provider>
 +    </extension>`

**Comment by serge-rider** [comment]
Well, I've added extra API function for UPSERT. Just override supportsUpsertStatement in your GenericMetaModel implementation and return true.
I assume that UPSERT is identical to INSERT (but with different keyword) and UPDATE is the same as INSERT but with limited column list.

fillStandardTypes is called only if datasource doesn't support data types metadata (in that case standard SQL types are loaded). If Phoenix doesn't support types metadata then you can set driver parameter "omit-type-cache" to true (in plugin.xml).

**Comment by zinking** [comment]
some points:
- I will have to override `schemaUsage`, phoenix driver is not giving parameters correctly. ultimately they should fix those meta parameters. 

- I managed to support bind Array values. so the 'copy' and 'apply' case works. but the in line edit case, the edit box jumps out while it can't be edited (readonly). not sure where I can get that configured to editable.

**Comment by serge-rider** [comment]
Great. Thanks for your contribution!

A few notes:
- I see that there is Maven artifact for Apache Phoenix (http://mvnrepository.com/artifact/org.apache.phoenix/phoenix) - it is much more convenient to have Maven reference in driver libraries than some static URL (moreover there is no such URL repo:/drivers/phoeinx/...). Did you try driver from Maven?
- I'll fix driver id/name/description to match standard naming conventions and update license information in all java sources where it is missing (it has to be GPL).

**Comment by zinking** [comment]
yeah, I was trying to use the maven driver, I think I saw some place of the examples, but seems didn't get it correct.  
For my personal experience with the driver, it's highly dependent on the phoenix/hbase version you are woking with. like I am using a CDH customised version. 

BTW, can you comment on the `readonly` array type editor bit I mentioned? how is that supposed to work. thanks.

**Comment by serge-rider** [comment]
Yep. I noticed that maven reference above doesn't actually contain jdbc driver. But there are plenty of others. I believe there should be a way to configure it thru maven (at least it works for Drill and Hive drivers).
Having Maven reference makes a great sense specifically because of version differences. You can just choose the version you need while static references are linked to some particular version.

Arrays editor isn't yet fully supported. That's true for all databases.
You could create a feature request for it.

**Comment by serge-rider** [comment]
I'll set Maven dependency to "org.apache.phoenix:phoenix-core:RELEASE" for now.
It is huge (~100Mb of jars) and mostly redundant for jdbc but I can't figure out any better way.
