### ISSUE TITLE
Can't create driver instance

### ISSUE THREAD

**Issue by 1362563840** [serge-rider/dbeaver#372]
![image](https://cloud.githubusercontent.com/assets/18475275/14551043/08795b0a-0301-11e6-94ca-eba0980dfa9e.png)

case:
when I try connecting the MySQL after I create it in DBeaver,the software just says

Can't create driver instance
Can't load driver class 'com.mysql.jdbc.Driver'
java.lang.UnsupportedClassVersionError: com/mysql/jdbc/Driver : Unsupported major.minor version 52.0

**Comment by serge-rider** [comment]
1. Try to download version 3.6.5.
2. In driver editor check what version of mysql driver are you using. If it is 6.0.2 then switch to any previous version. You can choose driver version right in download dialog.

**Comment by serge-rider** [comment]
Add a comment here if solution above won't help.

**Comment by operationgamma** [comment]
Sorry if this is naïve - but isn't this caused by the JRE version being used to run DBeaver is too low for the expected JRE version that this jdbc driver requires as a minimum?

Major version 52 being Java 1.8, so a lower version is being used to launch/run DBeaver itself such as 1.7.

**Comment by sumitjha4321** [comment]
I too had to revert back to version 5.1.40
Everything was fine with JRE, still it was showing the same error.
