### ISSUE TITLE
request: comma format limit number

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#374]
Small quality of life improvement request format / allow formatting for the limit number
![image](https://cloud.githubusercontent.com/assets/9246654/14572064/88d260f8-0301-11e6-8a0c-617ee84680bf.png)
-> 90,000

**Comment by serge-rider** [comment]
It might be convenient but native edit controls doesn't support numbers grouping, emulating that will require too much efforts for such small improvements.
Maybe later, if grouping support will be added in SWT.
