### ISSUE TITLE
PostgreSQL shows more than table's columns on autocomplete

### ISSUE THREAD

**Issue by tiagohipolito** [serge-rider/dbeaver#375]
Writing a simple query on SQL Editor (PostreSQL connection) and hitting ctrl+space,  autocomplete shows more than the table columns. 

1 - Write simple query "select * from table where "
2 - Ctrl+Space to lauch autocomplete popup
3 - The popup is showing first (tableoid, cmax, xmax, cmin, xmin, ctid) and then the table's columns.

![selection_005](https://cloud.githubusercontent.com/assets/4875952/14576108/d38c1216-033c-11e6-996e-a3ef8bb18b62.jpg)

![tooltip_003](https://cloud.githubusercontent.com/assets/4875952/14576113/d76b70de-033c-11e6-8814-73af97b8aa23.jpg)

- Just PostgreSQL's connection
- Tested on Linux Mint 17.1 64bits DBeaver 3.6.5 and WinXP 32bits DBeaver 3.6.5

**Comment by serge-rider** [comment]
Well, these columns actually belongs to the table. But they are so called hidden or pseudo columns.
I'll hide them by default.
