### ISSUE TITLE
Nulls  are shown in char fields in Teradata

### ISSUE THREAD

**Issue by winichenkomy** [serge-rider/dbeaver#377]
Teradata base by ODBC. 
sel 'i'(char(1)) shows NULL
It's true for any chars (varchar works)

**Comment by serge-rider** [comment]
Please check error/debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files). If you will find anything related to to CHAR column reading - post it here.

**Comment by r-richmond** [comment]
Are your drivers up to date?

![image](https://cloud.githubusercontent.com/assets/9246654/14659594/3a0dbb9e-0652-11e6-80e7-61fe01f22b08.png)

**Comment by winichenkomy** [comment]
Last drivers download helped! Thanks!

**Comment by vachastepan** [comment]
What driver version helped plz. 
I am facing the same issue with version Teradata ODBC v16, thx

**Comment by kseniiaguzeeva** [comment]
@vachastepan Is your question still actual?
