### ISSUE TITLE
Database export - Progress bar doesn`t work

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#379]
It would be great if progress bar begins to display progress of export again. Right now it is difficult to detect progress.

**Comment by serge-rider** [comment]
It is very hard to visualize export progress. Because MySQL doesn't provide any information about total size of dump. Showing any progress doesn't make sense if you don't know when this process will finish.
The only thing I can do is to show total number of exported bytes/lines.

**Comment by MatyCZ** [comment]
What about calculate exported objects size and compare it with current dump file size?

```sql
SELECT TABLE_SCHEMA AS db, SUM(DATA_LENGTH) AS size
FROM information_schema.TABLES
WHERE
	TABLE_SCHEMA = 'db_a' AND TABLE_NAME IN('table_a', 'table_b', 'table_c', 'table_d')
	OR
	TABLE_SCHEMA = 'db_b' AND TABLE_NAME IN('table_e')
GROUP BY TABLE_SCHEMA;
```

**Comment by MatyCZ** [comment]
@serge-rider How about this solution?

**Comment by serge-rider** [comment]
It is doable but not easy.
Too much effort for so small feature.
