### ISSUE TITLE
Generate "INSERT" scripts of an uuid create quotes on the field

### ISSUE THREAD

**Issue by fclety** [serge-rider/dbeaver#381]
When you try to generate the insertion scripts of your data, and if you have a UUID field in it, the generated scripts looks like : 
('865803f8-056a-11e6-b512-3e1d05defe78') instead of (865803f8-056a-11e6-b512-3e1d05defe78).

So, then when you want to play the scripts, there's a mistake (string detected instead of uuid)

My db is a Cassandra CQL, I work with Dbeaver 3.6.5

Anyway, thanks for your amazing soft :)

**Comment by serge-rider** [comment]
It is complicated. DBeaver uses the same query generation function for UUID types. 
Some databases (e.g. PostgreSQL) works with UUID data type as with string, some are not.
I'll try to figure something out..
