### ISSUE TITLE
PostgreSQL - error during database search

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#382]
Hi,

With dbeaver 3.6.5, PostgreSQL 9.4, when I launch a database search with "Table" as object type, in Metadata tab, I get the following error message : 
'Database search' has encountered a problem.
SQL Error [22P02]: ERROR: invalid input syntax for type oid: ""

Regards,

Cedric

**Comment by serge-rider** [comment]
Thanks for report
