### ISSUE TITLE
Remove DEFINER doesn`t work

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#384]
In version 3.6.5 checked "Remove DEFINER" doesn`t remove DEFINER syntax in dump files. Tested for MySQL and MariaDB drivers.

**Comment by serge-rider** [comment]
Can't reproduce.
Please post an example of dump with DEFINER.

**Comment by MatyCZ** [comment]
[dump-modulservis_modulis_test-201604191424.zip](https://github.com/serge-rider/dbeaver/files/225852/dump-modulservis_modulis_test-201604191424.zip)

**Comment by MatyCZ** [comment]
[dump-xxx-201604191424.zip](https://github.com/serge-rider/dbeaver/files/225856/dump-xxx-201604191424.zip)

**Comment by serge-rider** [comment]
Problem was in bad regex for DEFINER.
10x for report.

**Comment by MatyCZ** [comment]
It doesn`t work again. I modify your regex, can you replace it?

New:
```
"DEFINER\\s*=\\s*`[^*]*`@`[0-9a-z\\-_\\.\\%]*`"
```

Old:
```
"DEFINER\\s*=\\s*`[^*]*`@`[0-9a-z\\-_\\.]*`"
```

Tested on my definer line in SQL file:
```sql
/*!50013 DEFINER=`test`@`192.168.0.%` SQL SECURITY DEFINER */
```

**Comment by serge-rider** [comment]
Ok
