### ISSUE TITLE
dbeaver-enterprise on brew cask is outdated, and breaks on Cassandra

### ISSUE THREAD

**Issue by rdevries-thoughtworks** [serge-rider/dbeaver#387]
Not sure this is the right place to put this bug, but better safe than sorry. `brew cask` installs version 3.6.0, which gives me the error message you can find in 
![failure](https://cloud.githubusercontent.com/assets/17121388/14673910/fea129f6-0700-11e6-9c76-1af9dae63d7f.png).

**Comment by serge-rider** [comment]
We have nothing to do with brew cask (but maybe we should, I'm not sure).
You can write report to https://github.com/caskroom/homebrew-cask.
Error mentioned above was fixed in 3.6.2 or so.

**Comment by rdevries-thoughtworks** [comment]
Thanks for the quick reply. I created an issue caskroom/homebrew-cask#20661

I think it would be a nice added value if you could notify the brewers whenever a new dbeaver is released!

**Comment by adidalal** [comment]
(Homebrew Cask maintainer here)

A PR can easily be created on update by runnning `cask-repair -v {{new_version}} dbeaver-enterprise.rb`  (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))
