### ISSUE TITLE
view definition not available for db netezza

### ISSUE THREAD

**Issue by gumilaris** [serge-rider/dbeaver#391]
i have issue when i connect to netezza database ( IBM Pure Data analytics) why view definition is blank it says 

"-- View definition not available"

**Comment by serge-rider** [comment]
I'll be appreciate if someone will post SQL queries which read view definitions from system catalog. 
The same about table DDL/procedure source.

**Comment by gumilaris** [comment]
SELECT definition FROM _v_view WHERE viewname = '{VIEWNAME}'

**Comment by gumilaris** [comment]
To get list of all the views in Netezza use the below statement:

SELECT viewname FROM _v_view WHERE viewname NOT LIKE '\_%' AND UPPER(objtype) = 'VIEW' ORDER BY viewname;


To get the definition of a view in Netezza  use the below statement. 

SELECT definition FROM _v_view WHERE viewname = <VIEWNAME> AND UPPER(objtype) = 'VIEW';

To get the unique object id associate with the view in Netezza use the below statement:

SELECT objid FROM _v_view WHERE viewname = <VIEWNAME> AND UPPER(objtype) = 'VIEW';

**Comment by gumilaris** [comment]
Hi Serge-Rider,
you can use above SQl to get view definition. appreciate if we can get as soon as possible next release regarding this :). i'm a big fan of Dbeaver!! Viva DBeaver!!

**Comment by serge-rider** [comment]
It won't be too hard to add Netezza support.
Are there any other valuable features besides views?
Procedures, table DDL, sequences, etc.

**Comment by gumilaris** [comment]
for procedure :
SELECT PROCEDURE,OWNER,CREATEDATE,ARGUMENTS,PROCEDURESOURCE FROM _V_PROCEDURE

**Comment by gumilaris** [comment]
For Sequence listing :+1:

**Comment by gumilaris** [comment]
Sequence :

select SEQNAME,OWNER,CREATEDATE,SCHEMA from  _v_sequence

**Comment by serge-rider** [comment]
Check EA version (http://dbeaver.jkiss.org/files/ea/)
I've added view and procedure source view but I can't validate that.

**Comment by carlosjrcabello** [comment]
Tomorrow, at moment, I'm little bit drunken.

Regards.

**Comment by gumilaris** [comment]
i download new version DBeaver 3.6.10, check view definition on netezza still 

-- Netezza view definition not found

pls check..

**Comment by serge-rider** [comment]
Check error log for any errors/warnings regarding Netezza (https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by DragonStorm97** [comment]
This still doesn't seem to work, attached is the log file when checking the definition of  view, everything seems to indicate SUCCESS.
I tried with v6.0.1
[dbeaver_sql_20190325 - Copy.log](https://github.com/dbeaver/dbeaver/files/3003366/dbeaver_sql_20190325.-.Copy.log)

**Comment by DragonStorm97** [comment]
@serge-rider the problem with the query to get the definition is that it is filtering on owned objects, which i feel is incorrect as my user might need to pull a view DDL and not own it. the owner is a user and not a schema, so only if a user creates a view,etc themself will the DDL be visible.
Would it not be better to just pull from `_v_view `instead of joining to `_v_objs_owned`?
 the current query is `SELECT v.definition FROM _v_view v, _v_objs_owned o WHERE v.objid = o.objid AND o.DATABASE='DB_NAME' AND v.VIEWNAME='VIEW_NAME';`
 but it can be: `SELECT v.definition FROM _v_view v where v.VIEWNAME='VIEW_NAME';`
