### ISSUE TITLE
Add Presto DB support.

### ISSUE THREAD

**Issue by BigDataDaddy** [serge-rider/dbeaver#393]
One of the most popular and high performance SQL query engines on the Hadoop ecosystem is Presto DB (https://prestodb.io/).  However, the current versions of DBeaver are not compatible with the validated and supported Presto JDBC drivers.  I get the following error in DBeaver when trying to connect after adding the Presto JDBC driver with the Driver Manager and configuring a new Connection instance.

![presto_jdbc_driver_connect_error](https://cloud.githubusercontent.com/assets/13018379/14722318/062a0b2e-07d9-11e6-9873-a89c6a50504a.JPG)

Presto itself including the simple JDBC driver included in the distro require JRE 1.8.  Also, the newly released commercial JDBC driver for Presto (http://www.teradata.com/products-and-services/presto-download/) also requires JRE 1.8.  However, current version of DBeaver only operate on JRE 1.7.  

In order to run a validated and supported JDBC driver DBeaver needs JRE 1.8 release.

**Comment by serge-rider** [comment]
DBeaver works with any JRE >= 1.7.
Version 3.6.5 (windows installer) shipped with JRE 1.8. 
Just use version 3.6.5+ if you are on Windows or upgrade your local JRE if you are on another OS.
