### ISSUE TITLE
Multi-cell paste

### ISSUE THREAD

**Issue by biji** [serge-rider/dbeaver#394]
In data view, After copying whole row, can only paste first column to newly add row.
I hope dbeaver can copy paste just like in spreadsheet (pasting multi rows would be great :smile: )

Thanks

**Comment by serge-rider** [comment]
Multi-cell paste will be added in the next version.
It can be triggered by CTRL+SHIFT+V shortcut ("Advanced Paste" command).
It assumes that lines are delimited by linefeed (\n) and cells are delimited by tab (\t).

**Comment by jrmidkiff** [comment]
I have data that has the linefeed (\n) in cell values, and I want to copy multiple rows of that data from one table to another table. I am utilizing the advanced-copy where I change the row delimiter from \n to `blank` or to `|`, and the advanced-paste with "Insert Multiple Rows" checked. How can I do this?

**Comment by petervrs** [comment]
Don't know if you managed to work it out, but you might be able to do this using the same approach with the  `\n` delimiter while advanced-copying, then using the `Add row` button for as many rows as you are copying, then selecting these new rows in the destination table and pasting with advanced-paste with `Insert Multiple Rows` checked.
