### ISSUE TITLE
3.6.0: Set active in navigator or dropdown results in error with ODBC OpenEdge(DataDirect) driver

### ISSUE THREAD

**Issue by StefanM66** [serge-rider/dbeaver#396]
I get the error catalog not found.

Got this info from the progress support 

I found out that DBeaver is generating the incorrect SQL command: 
set catalog "PUB" 
instead of the correct SQL command: 
set schema 'PUB'

**Comment by serge-rider** [comment]
That's odd.
DBeaver do not use "set catalog" statement for any of standard database drivers.
Could you post error stacktrace (from Error Log view).
