### ISSUE TITLE
Table name filtering does not work properly if disconnected

### ISSUE THREAD

**Issue by halmai** [serge-rider/dbeaver#400]
Last Friday I turned on Filter Tables to show only tables with names like product[.*]. Some days later I returned and I want to turn the filter off so it shows all tables. Now the software doesn't show the correct list and it is not reconnecting automatically. 

I think, after a disconnection it should ask me whether I want to reconnect or not.

**Comment by serge-rider** [comment]
I didn't understand what is the actual problem. 
Filters (what is wrong with them?), reconnection confirmations?

**Comment by halmai** [comment]
Sorry if I was not clear. The table filtering works well while I am connected to the database. I can filter the tables' list and I can turn the filtering off as well. However, if the connection disappears due to long inactivity and after this I want to change the filtering then the list of the tables is not what I expected. 

Unfortunately, currently I cannot explain it more precisely because it was a little time ago and I don't remember well. If this description is not enough then I will try to give a more detailed description but it takes some days.

**Comment by serge-rider** [comment]
If connection has expired then you need to execute "Invalidate" command. Otherwise connection is in invalid state, most of actions will fail.
Or you can configure connection keep-alive period to avoid connections close (by server).

**Comment by halmai** [comment]
The problem is not that the user doesn't know _how_ to solve the problem. The problem is that the use does not know _that_ there is a problem. 

I managed to reproduce the issue. I use a vagrant virtual machine which contains the database and DBeaver was running on the host. The steps to reproduce:
- start VM with the mysql server
- connect to it from DBeaver that runs on the host. All of the ~300 tables are shown.
- right click on "Tables" in the left hand side tree
- select "Filter Tables..."
- enable an include filter "pets.*" and press OK. Now only 4 tables are listed. Cool.
- stop the VM (vagrant halt). Now the db connection must be destroyed.
- right click on Tables => Filter Tables... again
- untick the Enable checkbox and press OK. 

This should mean that the table filtering is not working any more, that is, all of the 300 tables should be shown. Or, if the DB has gone then it should say that "Hey, there is no DB". None of this happens, it shows instead as if the whole database would contain only my 4 tables which is pretty misleading. This is what should be fixed, I think. 

After this, if I click Tables=>Refresh(F5) then the list is still wrong. If I right click the database name and select Refresh(F5) then it is still wrong. If I click Databases=>Refresh(F5) then it finally goes well. 

Do you agree this is an issue?

**Comment by serge-rider** [comment]
Yep, it's a bug. 
Thanks for details.

**Comment by halmai** [comment]
I'm happy to help in making things better. :)
