### ISSUE TITLE
Please, where can I set codepage for Teradata driver in DBeaver?

### ISSUE THREAD

**Issue by winichenkomy** [serge-rider/dbeaver#402]
Subj.

**Comment by serge-rider** [comment]
You can set any advanced properties in connection properties (tab Driver properties).
Taradata JDBC doc:
https://developer.teradata.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html
Try CHARSET.

**Comment by winichenkomy** [comment]
It helped! Thank U very much!
