### ISSUE TITLE
Postgresql - Find database objects -Full-text search - not all tables are taken into account

### ISSUE THREAD

**Issue by loskultos** [serge-rider/dbeaver#404]
Doing a Full-text search over the database objects, it seems that not all tables are searched - 
e.g. creating the following table:

```
CREATE TABLE public.search_test4 (
	id bigserial,
	src_id varchar(64) NULL,
	uuid uuid NULL,
	creation timestamp NULL DEFAULT now(),
	last_modified timestamp NULL DEFAULT now(),
	language varchar(10) NULL,
	title varchar(255) NULL,
	description text null,
	CONSTRAINT search_test_pkey4 PRIMARY KEY (id)
)
WITH (
	OIDS=FALSE
);
```

Inserting a new row with title 'This is the Beaver test'. Then refresh (F5) the database metadata - the new table appears in the database navigator.

Now doing a Full-text search with Beaver or %Beaver% - the row in the table public.search_test4 is not found

Postgresql 9.5, DBeaver 3.6.6

**Comment by serge-rider** [comment]
Probably fixed in  #214
