### ISSUE TITLE
Cassandra timestamp format

### ISSUE THREAD

**Issue by pstallone** [serge-rider/dbeaver#408]
I’m using DBeaver 3.6.3 with Cassandra 3.4. When using cqlsh directly, I was able to get it to display timestamps in milliseconds (not shown by default), by including the following in my $HOME/.cassandra/cqlshrc file.

[ui]
time_format = %Y-%m-%d %H:%M:%S.%f%z

Is there is a way to do the same thing with DBeaver/Cassandra?

**Comment by serge-rider** [comment]
I think I'll just add support of date/time custom formatting (as it is done for relational databases). 
Silently using cqlsh configuration isn't obvious.

**Comment by pstallone** [comment]
Sounds good. Thanks.
