### ISSUE TITLE
invisible foreign key

### ISSUE THREAD

**Issue by dieselmachine** [serge-rider/dbeaver#409]
It appears that if a foreign key exists, and the referenced table has been deleted (not necessarily by dbeaver), dbeaver will not show any trace of that foreign key in the FK list, like it's using an inner join instead of a left join to pull info from the information schema.

This makes it impossible to remove, because it's not visible. I only stumbled upon it because it caused an Alembic run to fail, and I couldn't figure out why Alembic was showing a FK that is completely invisible in DBeaver.

DBeaver should probably offer a way to delete these, as hiding them makes things very inconvenient.

**Comment by serge-rider** [comment]
Hmm. I can't reproduce this problem. Generally you can't delete a table which is referenced by a foreign key. And DROP TABLE .. CASCADE will drop referencing foreign keys.

But maybe I'm missing something..

**Comment by dieselmachine** [comment]
The database structure was actually a full dump from a company which generated an export for us to load. That dump contained tables with FKs which referenced tables that weren't part of the dump. But really, this isn't the issue at all. The issue is that i can see the FK if I query the information schema myself, but dbeaver will not show the fk when viewing the actual table, so there is no clue that it exists. Dbeaver should show this FK, and allow it to be deleted.

**Comment by dieselmachine** [comment]
Here are steps to reproduce

download the attached mysql dump and load it into the db:

>> mysql test < test.txt

query the info schema to verify that the FK exists

    select * 
    from information_schema.table_constraints
    where table_name = 'fk_test'

+--------------------+-------------------+-----------------+--------------+------------+-----------------+
| CONSTRAINT_CATALOG | CONSTRAINT_SCHEMA | CONSTRAINT_NAME | TABLE_SCHEMA | TABLE_NAME | CONSTRAINT_TYPE |
+--------------------+-------------------+-----------------+--------------+------------+-----------------+
| def                | test              | PRIMARY         | test         | fk_test    | PRIMARY KEY     |
| def                | test              | fk_test_ibfk_1  | test         | fk_test    | FOREIGN KEY     |
+--------------------+-------------------+-----------------+--------------+------------+-----------------+
2 rows in set (0.00 sec)

now check in dbeaver to verify that fk_test_ibfk_1 is not visible in the foreign keys list.

[test.txt](https://github.com/serge-rider/dbeaver/files/241686/test.txt)

**Comment by serge-rider** [comment]
For some reason I though that its a PostgreSQL issue.
Well, now I can reproduce that, thanks for report.
