### ISSUE TITLE
Oracle - Packages body not loaded

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#41]
When you open an Oracle package from the DB Navigator panel by double-clicking it, the declaration part is correctly loaded, whereas the body part is not loaded.

See screnshot below for further details.

![oraclepackage](https://cloud.githubusercontent.com/assets/8759452/10993099/835e6892-846c-11e5-9f12-682b30c30ffc.png)

**Comment by serge-rider** [comment]
Is there anything in error log?

**Comment by steromano87** [comment]
Hi Serge,

the error log is empty, but I observed that one of the metadata queries that are called to retrieve data gives 0 rows as result:

![oraclepackage](https://cloud.githubusercontent.com/assets/8759452/10993833/4f865a88-8472-11e5-9712-548c5a481feb.png)

I don't know if this information can be helpful...

**Comment by serge-rider** [comment]
Thanks for info. At least I'll fix source loading text.
Could you please check that this package body is loaded in other Oracle tools?

**Comment by steromano87** [comment]
Hi Serge,

I confirm that the package body is correctly loaded and parsed by TOAD using the same user.

TOAD retrieves also a slightly different package declaration in header.
TOAD:
```SQL
CREATE OR REPLACE package SER_MIFID.PKG_CALCOLO_PATRIMONIALE as
    TYPE elencoCLI is varray(8) of char(11);
```

DBeaver:
```SQL
package           PKG_CALCOLO_PATRIMONIALE as
    TYPE elencoCLI is varray(8) of char(11);
```

**Comment by serge-rider** [comment]
Yet another strange issue.
Are you working as SYSDBA or as a normal user? Could try it as SYSDBA (if you have such permissions)?

There is a difference in package declarations because TOAD makes additional source processing and inserts CREATE OR REPLACE operator. I think DBeaver also should do it..

**Comment by serge-rider** [comment]
I think that this problem has the same nature as  #37. Something about permissions. 
But if you are using the same user then the only possible difference is a different connection role (SYSDBA, SYSOPER, Normal). Or maybe some additional initialization queries.
Did you try any other tools besides DBeaver and TOAD?

**Comment by steromano87** [comment]
Hi Serge,

using TOAD I connect to the same DB using the same user and the same role (normal).
I tried using SqlDbx too, and I can see the package body without issues connecting as normal user.

**Comment by serge-rider** [comment]
I'm frustrated a bit.
Could you try this trick:
Execute query 
```
SELECT TEXT FROM SYS.ALL_SOURCE WHERE TYPE='PACKAGE BODY' AND OWNER='SER_MIFID' AND NAME='PKG_CALCOLO_PATRIMONIALE'
```
in DBeaver and in TOAD. Is there any difference?

**Comment by steromano87** [comment]
Hi Serge,

executing the query on DBeaver and TOAD gives no result on both of them :-(

Hoping to be more helpful, if I inpect the current user privileges using the following query:
```SQL
select * from session_privs
```
I obtain the following privileges:
* CREATE SESSION
* ALTER SESSION
* UNLIMITED TABLESPACE
* CREATE TABLE
* SELECT ANY TABLE
* INSERT ANY TABLE
* UPDATE ANY TABLE
* DELETE ANY TABLE
* CREATE CLUSTER
* CREATE SEQUENCE
* ALTER ANY SEQUENCE
* SELECT ANY SEQUENCE
* CREATE PROCEDURE
* ALTER ANY PROCEDURE
* EXECUTE ANY PROCEDURE
* CREATE TRIGGER
* CREATE TYPE
* CREATE OPERATOR
* CREATE INDEXTYPE
* SELECT ANY DICTIONARY
* ADVISOR

**Comment by steromano87** [comment]
Hi Serge,

after some googlin I found the solution of the issue :-)

The correct schema to retrieve the package body if the current user has EXECUTE PACKAGE permissions and the package belongs to another schema is *SYS.DBA_SOURCE* and not *SYS.ALL_SOURCE*.
If you execute this query on DBeaver and on TOAD:
```SQL
SELECT TEXT FROM SYS.DBA_SOURCE
WHERE TYPE='PACKAGE BODY'
	AND OWNER='SER_MIFID'
	AND NAME='PKG_CALCOLO_PATRIMONIALE'
ORDER BY line
```
I get the package body.

References: [TOAD Wiki](https://www.toadworld.com/products/toad-for-oracle/w/toad_for_oracle_wiki/206.why-can-t-i-see-package-bodies-from-another-schema-on-the-procs-tab), [Oracle Community](https://community.oracle.com/thread/326756)

**Comment by serge-rider** [comment]
Hey,

Thanks a lot for information. 
However I doubt that using DBA* views everywhere is the best choice. These views are usually not accessible to users without DBA permissions.
But I think I could try to read info from both DBA and ALL views. If DBA* view is missing/not accessible or contains no data then try to read from ALL* (or even USER*).

Will try to fix this in the next version.

**Comment by serge-rider** [comment]
Now DBeaver will read sources from DBA_SOURCE view (if it is available for current user).
