### ISSUE TITLE
3.6.6 Unable to Connect to ODBC Bridge Driver

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#410]
I had a working ODBC Bridge Connection working as of 3.6.2 ish and am now unable to connect.

When trying i receive the following error

Can't create driver instance
  Can't load driver class 'sun.jdbc.odbc.JdbcOdbcDriver'
    java.lang.ClassNotFoundException: sun.jdbc.odbc.JdbcOdbcDriver cannot be found by org.jkiss.dbeaver.core_3.6.6

**Comment by r-richmond** [comment]
Possible cause http://stackoverflow.com/questions/14229072/removal-of-jdbc-odbc-bridge-in-java-8

**Comment by serge-rider** [comment]
Yes, exactly. Odbc bridge was removed in Java 8 (which is now default JRE in Windows installer).
Will try to find some workaround.
