### ISSUE TITLE
Under Teradata procs are not being repalced

### ISSUE THREAD

**Issue by winichenkomy** [serge-rider/dbeaver#412]
Teradata jdbc driver, last version.
query:
REPLACE PROCEDURE dev8_1_100_db_stg.WmyUpds() BEGIN
END
says:
[Teradata Database] [TeraJDBC 15.10.00.14] [Error 5526] [SQLState HY000] Stored Procedure is not created/replaced due to error(s).
[logs.zip](https://github.com/serge-rider/dbeaver/files/238558/logs.zip)
Nonempty procs behave the same :(

**Comment by serge-rider** [comment]
I'm not familiar with Teradata SQL. 
But this looks like Teradata-specific issue. I don't see how it is related to DBeaver..

**Comment by brentgunderson** [comment]
I seem to have exact same issue with Replace Procedure on Teradata.

I don't think it is an issue with SQL, as I can get procedures to compile using Teradata's bteq utility
