### ISSUE TITLE
MySQL dump wizard : unchecking "extended insert" still exports with extended inserts

### ISSUE THREAD

**Issue by jbujonwaibi** [serge-rider/dbeaver#415]
I was using MySQL Workbench and now I'm using dbeaver to connect to MySQL (and other) databases.
I'm connecting to a MySQL 5.0 server database.
I prefer to export data WITHOUT extended insert.
I saw the dump optional "extended-inserts" checkbox that by default is checked.
I tried to UNCHECK that, bug it had NO EFFECT to the generated .sql file !

Is that a bug or am I doing something wrong ?
Can it be due to our old MySQL Server version ?

I wen't to the source code and saw something strange in MySQLExportWizard.java :
> _if (extendedInserts) cmd.add("--extended-insert");_

Would it be better if you add the below line just after the above one ? 
> _else cmd.add("--skip-extended-insert");_

I don"t have recent version of MySQL so I can't test it, sorry.

Path to Java File concerned :
dbeaver/plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/tools/MySQLExportWizard.java

**Comment by serge-rider** [comment]
Thanks for report
