### ISSUE TITLE
Code completion does not work on MySQL and version 3.6.6

### ISSUE THREAD

**Issue by raqua** [serge-rider/dbeaver#416]
Title says it all. Works fine after installing version 3.6.5.

**Comment by serge-rider** [comment]
Can't reproduce.
Check Error Log (and debug log) for any related errors.

**Comment by raqua** [comment]
I have checked error log, there were some old entries so I deleted them. Then restarted DBeaver and reproduced the problem. Nothing appeared there. 
I also started DBeaver from command line and nothing signaling any issue was written to console either. 
How do I provide debug log?

**Comment by serge-rider** [comment]
https://github.com/serge-rider/dbeaver/wiki/Log-files

BTW what do you actually mean under code completion?
What happens when you type "select * from <Ctrl+Space>"?

**Comment by raqua** [comment]
I have attached debug log, but there seems to be nothing related to the issue. 
[dbeaver-debug.log.zip](https://github.com/serge-rider/dbeaver/files/244686/dbeaver-debug.log.zip)

What happens is: I log in to the database. Type "select * from " and I get list of suggested tables. Then I select a table and give it an alias. Using this alias, I try to add fields that I am interested in ->
select  t.<nothing suggested here>
from table_t t

**Comment by serge-rider** [comment]
It is a bug in the recent versions.
Thanks for report.

**Comment by raqua** [comment]
This issue is back again in 3.6.8

**Comment by serge-rider** [comment]
I guess this is duplicate of #467

**Comment by raqua** [comment]
I can not reproduce #467 in 3.6.7 version on my machine. That works as expected. Do you want me to try it again in 3.6.8 anyway?

**Comment by serge-rider** [comment]
#467 is a bug in 3.6.8. And it differs this bug (auto-compelete doesn't work only if you use table alis and empty column name).

**Comment by raqua** [comment]
Ok, I misread the bug report and thought that the bug is reported against 3.6.7.
I went to reinstall 3.6.8 and tested it again and it seems to behave as in #467. It works when no alias is used, but I have not noticed that as I always use aliases. It also works after typing at least one letter.

**Comment by serge-rider** [comment]
Ok. So this is a duplicate. Will be fixed in 3.6.9
