### ISSUE TITLE
Mysql PROCEDURE SQL parse error

### ISSUE THREAD

**Issue by stepjacky** [serge-rider/dbeaver#417]
DBeaver lasted version 3.6.6
in a store PROCEDURE 
I use the fllowwing SQL statement : 
	

>` set @bdate = concat('\'',startdate,'\',\'',enddate,'\'');`

the dbeaver will displayed as : 
       

> `set @bdate = concat(''',startdate,'','',enddate,''');`

as above startdate and enddate should be as parameters,
while dbeaver's SQL will lead to a wrong SQL statement , it will treat the startdate and enddate parameters as a string and not a parameter or variable.

**Comment by serge-rider** [comment]
I don't understand the use case. And I can't figure out at what moment backslash disappears.
Could you provide more details.

**Comment by stepjacky** [comment]
o,ok
```
CREATE DEFINER=`root`@`localhost` PROCEDURE `typedfunds`(
	IN `startdate` CHAR(15),
	IN `enddate` CHAR(15)
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
SET @@group_concat_max_len = 4096;
   	SET @@character_set_results=utf8;
	SET @sql1 = NULL;
	set @bdate = concat('\'',startdate,'\',\'',enddate,'\'');
    SET @sql2 = concat('
     ( select 
 sum(fts.realoutlay) outlay ,
 fts.groupId groupId,
 fts.groupname groupName,
 fts.typeId typeId,
 fts.typeName typeName
from 
 fds_fundtransfer fts
 where is_date_in(fts.fyear,fts.fmonth,',@bdate,' )  group by fts.groupid,fts.typeid )');


SELECT
  GROUP_CONCAT(DISTINCT
    CONCAT('MAX(IF(c.name = \'', c.name,'\', s.outlay, 0)) AS \'', c.name,'\'')
  ) into @sql1
FROM fds_projectType c;



SET @sql1 = CONCAT('Select st.id, st.name, ', @sql1, 
                        ' From fds_department  st 
                        Left Join ',@sql2,' s On st.id = s.groupId
                        Left Join fds_projectType c On c.id = s.typeId');
        
   

SET @sql1 = CONCAT(@sql1, ' Group by st.id');

-- select @sql1;
   PREPARE stmt FROM @sql1;
   EXECUTE stmt;
   DEALLOCATE PREPARE stmt;
END
```
this above is a compeleted store PROCEDURE, open and edit it , make some changes and save it use dbeaver ,then you will find the store PROCEDURE can execute , and mysql complained  

> unkown column startdate 

as above ,startdate is a parameter ,but be treated as a column name because of this line 
`set @bdate = concat('\'',startdate,'\',\'',enddate,'\'');`
be translate into 
`set @bdate = concat(''',startdate,'','',enddate,''');`

**Comment by serge-rider** [comment]
DBeaver sends SQL as is, something happens in JDBC driver or somewhere else.
Investigating..

**Comment by serge-rider** [comment]
The problem was in the way how DBeaver read procedure body.
It used information from INFORMATION_SCHEMA.ROUTINES view. Which, for some reason, contains broken declarations (without backslash char).
Now DBeaver will use SHOW CREATE PROCEDURE query to obtain the body.

**Comment by stepjacky** [comment]
that's great for this and i happy to do the job,also i use DBeaver almost every day,thanks the DBeaver team!
