### ISSUE TITLE
Errors while executing complex sql stuff.

### ISSUE THREAD

**Issue by yoihito** [serge-rider/dbeaver#418]
I was trying to execute this statement for Oracle 11g.
```sql
FUNCTION square (original NUMBER)
  RETURN NUMBER
AS
  original_squared NUMBER;
BEGIN
  original_squared := original * original;
  RETURN original_squared;
END;
/
```
I got this error.
```
13:07:03	SQL / USER_SCRIPT	DECLARE
  
  FUNCTION square (original NUMBER)
    RETURN NUMBER                  
  AS
                                   
    original_squared NUMBER	3 ms		[6550] ORA-06550: line 7, column 27:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   := . ( @ % ; not null range default character
```

**Comment by serge-rider** [comment]
DBeaver doesn't (yet) support Oracle-specific way to terminate procedure declaration (/).
As a workaround you can select whole function declaration (without /) and execute it as a single statement (ctrl+enter)

**Comment by yoihito** [comment]
Ok, thanks! I saw the issue appeared at 2012. Can I work on this?

**Comment by serge-rider** [comment]
Yeah, that's an old one.

At first you can create a feature request.
Implementing this feature won't be easy. Existing SQL parser can't handle such things.
Moreover I don't even know strict algorithm to determine query end.
For instance
``` sql
CREATE FUNCTION square (original NUMBER)
  RETURN NUMBER
AS
  original_squared NUMBER;
```
is a valid statement which creates function with empty body.
The same query with BEGIN/END part is also a valid statement.
So, it's complicated...

**Comment by yoihito** [comment]
Maybe i miss something, but according to the spec https://docs.oracle.com/cd/A97630_01/appdev.920/a96624/13_elems23.htm#34369 <https://docs.oracle.com/cd/A97630_01/appdev.920/a96624/13_elems23.htm#34369> this is not a valid statement. You can try to execute it separately and you’ll get an error. 

Where should I put a feature request? Can you point me where I can start please?

**Comment by serge-rider** [comment]
Just create new issue with request description. I'll mark it as feature request.

Most of magic happens in SQLEditorBase.parseQuery function (block processing).
