### ISSUE TITLE
Cassandra in Connection Options

### ISSUE THREAD

**Issue by ajaytwithme** [serge-rider/dbeaver#419]
I cant see Cassandra option in New Connection wizard. I tried to add Cassandra settings in Driver Manger however not sure what to add in driver class and artifacts section. I tried to add cassandra-driver-core artifacts however it can not find the driver class in the binaries.

Can any one please help me with the instructions for using Cassandra 3 with DBeaver? It would be a great help.
Thanks
AJay

**Comment by serge-rider** [comment]
You need to download EE version.
