### ISSUE TITLE
Oracle - Declaration not displayed for procedures that are declared in package (but it is displayed for standalone procedures)

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#42]
If you open a procedure declared inside a package, the declaration tab is not displayed:

![oracleprocedure01](https://cloud.githubusercontent.com/assets/8759452/10993193/1d2b01ec-846d-11e5-8c2a-be55140b3667.png)

However, if you open a standalone procedure (declared outside a package), the declaration tab is present and correctly populated:

![oracleprocedure02](https://cloud.githubusercontent.com/assets/8759452/10993204/37f9187e-846d-11e5-936c-646ebb23665f.png)

**Comment by serge-rider** [comment]
This is no a bug. DBeaver doesn't (yet) support Oracle packages parsing. And there is no easy way to obtain body of a package procedure using system tables.

So this feature is planned but it is complicated and has relatively low priority. Can't say when I'll add it..

**Comment by steromano87** [comment]
OK. Thank you so much!

**Comment by serge-rider** [comment]
Oracle packages parser implementation will be tracked in a different issue.
It is a quite complex task and relatively low priority.
