### ISSUE TITLE
Feature request: Normal file explorer view without Project interference

### ISSUE THREAD

**Issue by gstoel** [serge-rider/dbeaver#420]
Hi there,

I would be helped very much if dbeaver could include a 'standard' file explorer style window where the user can browse the file system without first setting up a project and mapped directory. 

nice features in there would be (in order of preference):

- sorting on file attributes (size, last edited, created, extension, etc.)
- add/delete/rename/move files and folders
- git integration
  - status
  - add / commit
- bookmarks

Also is there some documentation on how projects work? 

Thanks,

Geoffrey

**Comment by serge-rider** [comment]
We going to improve project management in 3.7.
The only public documentation is at http://dbeaver.jkiss.org/docs/ and in the [wiki](https://github.com/serge-rider/dbeaver/wiki)
