### ISSUE TITLE
in 3.6.5/3.6.6 no connections in database navigator

### ISSUE THREAD

**Issue by hgdebie** [serge-rider/dbeaver#421]
Hello Serge, thanks for an excellent product.
When I start dbeaver 3.6.4 I get my database navigator and all my connections, as in previous versions.
In 3.6.5/3.6.6 after starting I get a Create new connection window, my connections are "gone".
PC/environment is the same for all versions.
Any idea ?

**Comment by serge-rider** [comment]
This shouldn't happen, ever.
Maybe your workspace was corrupted? Or maybe you are workign under different user.
Check %HOMEPATH%\.dbeaver folder.
Connections configuration is stored in General\.dbeaver-data-sources.xml file (for default project).

**Comment by hgdebie** [comment]
Hello Serge,
Found General.dbeaver-data-sources.xml in Mydocuments directory ( don't know how things got there ) copied it to %HOMEPATH%.dbeaver\General, started 3.6.6 and all the connections are there again.
Thanks a lot !
Cheers
