### ISSUE TITLE
SQL-Export Syntax-Error on Databases  with "-" in Name

### ISSUE THREAD

**Issue by Petschko** [serge-rider/dbeaver#422]
Hello, I was exporting a Database named like firstname-lastname and I get this message:

> mysqldump: Got error: 1049: Unknown database '`firstname-lastname`' when selecting the database
> Export finished at Wed May 04 16:07:30 CEST 2016

So I go to the Server and dump it by myself with the CMD mysqldump... May you're missing to add '' arround the Database name?
Because the Database exists! (10x Checked if the name is the same)

Thanks for stepping by

Petschko

**Comment by serge-rider** [comment]
I'm adding `` quotes and this is actually a problem. 
mysqldump command line interface wants plain names without quotes.
Thanks for report.
