### ISSUE TITLE
Postgresql incorrect data update from resultset inline editor

### ISSUE THREAD

**Issue by irizzant** [serge-rider/dbeaver#424]
Hello

we're experiencing a bug when we run the following query from Dbeaver 3.6.6 for kubuntu 64bit:

`select * from wms.wh_picking_cartons pc 
where pc.wh_picking_shipment_id=4586264`

We get a correct resultset of 3 rows but when we try to inline-update any column of table wms.wh_picking_cartons and commit the changes we get a message stating that 299 rows were updated instead of 1!

Attached is the DDL.

[ddl.txt](https://github.com/serge-rider/dbeaver/files/250159/ddl.txt)

We're running Postgresql 9.4.

Thanks

**Comment by serge-rider** [comment]
Preferences->Database->Query Manager. Enable all object types and query types.
Open Query Manager view.
See what exactly update statement is executed when you click on "Apply changes".

**Comment by irizzant** [comment]
Here you go:
`15:06:48	SQL / UTIL	UPDATE wms.wh_picking_cartons
SET cartons=2
WHERE warehouse_id=126 AND barcode IS NULL	216 ms	299	Success	WEBTNG SVILUPPO	Main`

**Comment by irizzant** [comment]
The above query

> 15:06:48	SQL / UTIL	UPDATE wms.wh_picking_cartons
SET cartons=2
WHERE warehouse_id=126 AND barcode IS NULL	216 ms	299	Success	WEBTNG SVILUPPO	Main

shows clearly that WHERE condition is a unique constraint and not the primary key

**Comment by serge-rider** [comment]
DBeaver uses first found unique index as a table unique identifier.
How is it possible that unique index isn't actually unique?

**Comment by irizzant** [comment]
Generally speaking I agree but it's perfectly legal in a unique index to have nullable attributes, meaning that some of them are optional.

In our example you can have multiple rows having null values in the barcode column.

Why not just using the primary key?

**Comment by serge-rider** [comment]
Agreed. So it is a bug.

Unique identifier is searched in the following order:
- Unique pseudo column (ROWID, ctid, etc).
- Unique index
- Unique constraint

This particular order (the same for all databases) was chosen because of performance reasons.
I'll fix it so indexes with nullable columns won't be used as unique identifiers.
Thanks for report.

**Comment by irizzant** [comment]
I think you should avoid using index and constraint with nullable columns at all, in our case we have a unique constraint AND a index with nullable columns

**Comment by serge-rider** [comment]
Yep, constraints too.
