### ISSUE TITLE
http://dbeaver.jkiss.org/ - This Domain Name Has Expired

### ISSUE THREAD

**Issue by djds23** [serge-rider/dbeaver#426]
It appears the domain housing download/documentation for DBeaver has expired. 

<img width="1276" alt="screen shot 2016-05-07 at 1 05 30 pm" src="https://cloud.githubusercontent.com/assets/5833968/15093401/99322b54-1454-11e6-84ed-06912aecefe2.png">

**Comment by threetopia** [comment]
Can't not download because of expired domains

**Comment by carlosjrcabello** [comment]
Hi threetopia,

You can also download dbeaver cloning the repo on github and building his
sources.

https://github.com/serge-rider/dbeaver/#building


On Sun, May 8, 2016 at 8:48 AM, threetopia <notifications@github.com> wrote:

> Can't not download because of expired domains
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/426#issuecomment-217711238>
>



-- 
Atenciosamente,
Carlos Alberto Junior Spohr Poletto

carlos.inf.br

**Comment by lBilali** [comment]
and obviously eclipse plugin url http://dbeaver.jkiss.org/update/latest/ is not working :(

**Comment by serge-rider** [comment]
For some weird reason domain auto-prolongation didn't work this time.
And when I tried to do it manually registrant billing system was broken or something (maybe due to weekend).
Hopefully our domain will be back today/tomorrow...

Till then you can use direct IP: http://104.236.93.175/

**Comment by carlosjrcabello** [comment]
hehehe,

I also had similar problem with Brazilian NIC last year.

On Sun, May 8, 2016 at 12:18 PM, Serge Rider <notifications@github.com>
wrote:

> For some weird reason domain auto-prolongation didn't work this time.
> And when I tried to do it manually registrant billing system was broken or
> something (maybe due to weekend).
> Hopefully our domain will be back today/tomorrow...
>
> Till then you can use direct IP: http://104.236.93.175/
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/426#issuecomment-217726590>
>



-- 
Atenciosamente,
Carlos Alberto Junior Spohr Poletto

carlos.inf.br

**Comment by serge-rider** [comment]
Now it should be Ok.
DNS update may take some time (not more than a few hours usually).

**Comment by djds23** [comment]
Thanks for the quick fix @serge-rider, I'm commenting here to confirm that the site is back up again!
