### ISSUE TITLE
MySQL usage of binary(16) in FK 

### ISSUE THREAD

**Issue by db0x** [serge-rider/dbeaver#427]
I use binary(16) as id column in my entities to store UUIDs and use it in FKs creating realations.

in dbeaver-grid I have the possibility to switch to the record behind the FK (link-button in cell) but with binary FKs I run into sql error

`
SQL Error [1054] [42S22]: Unknown column 'A6D15A1EAC3D46F681A90B2A1F162C6B' in 'where clause'
  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'A6D15A1EAC3D46F681A90B2A1F162C6B' in 'where clause'
`
('A6D15A1EAC3D46F681A90B2A1F162C6B') is an binary(16) as HEX 

I tried to change the data formate for binary - but without success.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by db0x** [comment]
works :+1:
