### ISSUE TITLE
Hide entities in er-diagram

### ISSUE THREAD

**Issue by db0x** [serge-rider/dbeaver#430]
It would be nice to have the possibility to hide entities in the er-diagram.

I use hibernate-envers to create audit-tabes in my system but I don't want to see this in the diagram ;-)

**Comment by serge-rider** [comment]
You can just use custom ER diagrams (from context menu on Diagrams folder or thru Ctrl+N).
Then you can drag-n-drop any number of tables you need. And even make your custom connections.

**Comment by db0x** [comment]
:+1: 

works for me, thanks
