### ISSUE TITLE
Show data editing sql

### ISSUE THREAD

**Issue by rdenxx** [serge-rider/dbeaver#433]
One feature I really liked in MySQL Workbench was after editing data in a table and clicking apply it showed the SQL that was about to be performed.  Really handy for testing changes on a testing database before applying it to production without having to remember what to do (i.e. collect the sql into a text editor, later open the workbench on the real database, cut and paste the collected sql).

**Comment by serge-rider** [comment]
That's a good feature, really useful. And easy to do.
Will be included in the next version.
