### ISSUE TITLE
Implement fuzzy search

### ISSUE THREAD

**Issue by ihabunek** [serge-rider/dbeaver#435]
Here's a wish: Could you implement sublimetext-like fuzzy search when giving column/table/etc auto-completion suggestions?

For example, in a WERE clause,  when i type "pid" and pres Ctrl+Space, the popup window should contain **p**erson_**id** and image_**p**rofile_**id** since they match (fuzzily).

I feel this would be a great addition.

**Comment by serge-rider** [comment]
Good point, I like it.

**Comment by carlosjrcabello** [comment]
It's really nice! 

It seems with auto complete implemented in Eclipse Mars.

![screen207](https://cloud.githubusercontent.com/assets/637767/15178974/4f6f654c-174f-11e6-9fd5-c9d0f7a9342e.png)
