### ISSUE TITLE
Feature Request: Optional binary identifier flag

### ISSUE THREAD

**Issue by gsaulmon** [serge-rider/dbeaver#437]
Since version 3.6.7 when viewing a binary field as hex there is a `0x` prefixed to the value.

Is it no longer possible to display just the hex representation without the binary identifier added? If not, could there be a display option added to disable the inclusion of `0x`?

**Comment by serge-rider** [comment]
Yep, it is a side effect of #427.
0xABCD format is actually for native representation of binary data. In UI it should be without 0x. I don't think we need an additional option, 0x doesn't make sense in UI.
So I'll mark it as a bug.

**Comment by db0x** [comment]
0x makes no sense in UI ... your commit works and the links back to data behind is still working :)

by the way, mvn clean install fails since ~3 days because 
` <module>plugins/org.jkiss.dbeaver.ext.teradata</module>`
is missing in the pom.xml
