### ISSUE TITLE
explain plan cost and cardinality display is suboptimal

### ISSUE THREAD

**Issue by farmboy0** [serge-rider/dbeaver#438]
<img width="960" alt="explain" src="https://cloud.githubusercontent.com/assets/2206262/15210143/31c9e3e6-1835-11e6-96a7-d78369b59e96.png">

It would be much easier to read when the numbers are right aligned and have a fixed number of fraction digits.

**Comment by serge-rider** [comment]
I think this problem is bigger than just explain plan view. It makes sense to make ALL numeric columns right-aligned.
Fraction digits number is a bit more complicated issue.

**Comment by dizdi** [comment]
Hi, thanks for the format option. Would it be very hard to add an alignment setting to Data Formats -> Type: [Numbers] in settings?
Ty

**Comment by serge-rider** [comment]
We have plans to add columns customization (visibility, align, format)) to all tables, including execution plan table.
Will work on that after 3.8 release.

**Comment by nanny07** [comment]
Hi serge-rider, any news on the columns customization? I have looked on the milestone section but I haven't found anything about it

**Comment by shearerp** [comment]
Is this feature available yet? I would really appreciate right-aligned numbers.

**Comment by serge-rider** [comment]
Yes, numbers are right-aligned by default in all DBeaver tables.

**Comment by shearerp** [comment]
Even in query result sets? I just upgraded to the latest version and they
are still left aligned

**Comment by serge-rider** [comment]
No, query results view is separate.

**Comment by shearerp** [comment]
Any chance the alignment can be done with query results too?

**Comment by serge-rider** [comment]
Sure.
Create a feature request.

**Comment by shearerp** [comment]
Will do. Thanks a lot! Huge fan.
