### ISSUE TITLE
SQLite export to PostgreSQL -- Incorrect VARCHAR length -- 2,000,000,000

### ISSUE THREAD

**Issue by skewty** [serge-rider/dbeaver#439]
When trying to [Export Data] - [Database] a table from SQLite to PostgreSQL with Mapping = [new] I get the following error:

```
Can't create target table:
CREATE TABLE auth_group(
id int8 NOT NULL,
name varchar(2000000000) NOT NULL,
PRIMARY KEY (name)
)
  SQL Error [22023]: ERROR: length for type varchar cannot exceed 10485760
  Position: 49
    org.postgresql.util.PSQLException: ERROR: length for type varchar cannot exceed 10485760
  Position: 49
```

The SQLite table's [DDL] section shows:

```
CREATE TABLE auth_group (
    id INTEGER NOT NULL,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT AUTH_GROUP_PK PRIMARY KEY (id)
);

CREATE UNIQUE INDEX sqlite_autoindex_auth_group_1 ON auth_group (name);
```

**Comment by serge-rider** [comment]
Actually it works as expected. SQLite is a pretty special database - all strings have huge length.
By default DBeaver translates varchar columns keeping original length.
The only workaround is to change target column signature manually (in the column mappings dialog).
