### ISSUE TITLE
PostgreSQL - change column type needs explicit cast in ALTER command

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#440]
Trying to change a column type from BPCHAR to SMALLINT using the graphical interface fails (when clicking on "persist" button) because PostgreSQL needs an explicit cast in the ALTER command.
Example: ALTER TABLE public.test ALTER COLUMN corne TYPE int2; => fails
ALTER TABLE public.test ALTER COLUMN corne TYPE int2 USING corne::int2; => OK

Is it possible to add explicit casts in the alter command generated by the graphical interface?

Thanks in advance.

**Comment by serge-rider** [comment]
Type conversion will be added in 3.7.1.
Thanks for good feature idea.
