### ISSUE TITLE
Option to open existing SQL files

### ISSUE THREAD

**Issue by marco-sanjuan** [serge-rider/dbeaver#443]
Hi

Could it be possible to implement an open file option witch automatically create an entry on “Scripts“ for it?
It would be really useful, the current method is hard to find and use.

Thanks!

**Comment by serge-rider** [comment]
It'll be done as a part of project management improvements in the next version.

**Comment by marco-sanjuan** [comment]
Great news!
With also drag and drop of files into DBeaver?

Thanks!

**Comment by serge-rider** [comment]
Yep. #197 will also be resolved.

**Comment by marco-sanjuan** [comment]
Wow amazing, great work, thanks for you effort.
