### ISSUE TITLE
Postgresql active schema should modify search_path

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#444]
When opening a sql editor in order to get content assist I need to activate one of the schemas in the database. But when I try to run a query created using content assist, it will fail because my search_path by default points to public only.
This may cause the odd situation that my content assist uses one schema and my queries run on a different one.
I believe that the active schema and the search_path of the sql editor should be connected. 
when activating a schema please change the search_path to active_schema,public.
Or at least when opening a new sql editor, by default set its search_path to active_schema,public.

**Comment by serge-rider** [comment]
That's odd.
DBeaver updates search_path whenever you switch active schema (using navigator context menu).
What version do you use?

**Comment by norbitheeviljester** [comment]
I'm using dbeaver 3.6.7 and postgresql 9.5.

I'll give you an example on how to reproduce my exact problem.

1. connect to a pg database
2. open new editor, this should by default have search_path=public, since no schema is selected as active.
3. run the following sql:
```
create schema mytest;
create table mytest.mytable (
    id int
);
```
4. close the editor
5. refresh the database (so that the new schema can be seen)
6. set the mytest schema as active
7. open a new editor
8. perform the following queries:
![image](https://cloud.githubusercontent.com/assets/6532949/15281046/d62599e4-1b37-11e6-8a3a-863f6b8a7415.png)

as you can see the search_path is set to public only although I've created a new sql editor when a schema was set to active.

**Comment by serge-rider** [comment]
Yep, this happens when you reopen SQL editor (DBeaver opens a separate connection and doesn't set search path for it).
Thanks for report.
