### ISSUE TITLE
"Link with Editor" should navigate to active schema in "Database Navigator" for a given open Sql Editor

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#447]
When a Sql Editor is open and an active schema for the connection of that Sql Editor is chosen I would expect the "Link with Editor" button on the Database Navigator:
![image](https://cloud.githubusercontent.com/assets/6532949/15282690/37ed1eec-1b45-11e6-8437-76b076496afc.png)
to navigate to the current active schema.

Currently this works only for opened database objects like a table view etc
In our project we have multiple databases with  hundreds if not thousands of schemas setup. I'm really missing this feature instead of scrolling around everything all the time.

**Comment by serge-rider** [comment]
Good feature, I like it.
But it is not PostgreSQL specific.
