### ISSUE TITLE
MySQL foreign key constraints are not listed correctly

### ISSUE THREAD

**Issue by tcak** [serge-rider/dbeaver#448]
I created a table. It has a foreign key. On it, I set "ON DELETE RESTRICT", "ON UPDATE CASCASE".

After creating the foreign key, in the foreign key list,

1. On Delete = No Action
2. On Update = Cascade

are seen.

If I click on "Generate SQL > DDL", generated SQL code doesn't have "on delete restrict" at all. Only the "on update cascase" is there.

I open the same table in MySQL Workbench, both On Delete Restrict and On Update Cascase are delete. So, I am guessing, a handling problem is there.

Version: 3.6.7,  Ubuntu 16.04 x64

**Comment by serge-rider** [comment]
In MySQL ON DELETE RESTRICT is the default value for foreign key (that's why it is missing in DDL). 
And it has the same meaning as "No Action".

So this is not a bug, just a specific feature of MySQL.
