### ISSUE TITLE
Navigating the tree with arrow keys

### ISSUE THREAD

**Issue by ihabunek** [serge-rider/dbeaver#450]
When navigating the tree in the Database Navigator using the keyboard, it's possible to move up and down with up/down arrow keys and to expand/collapse the tree nodes with +/- keys. 

It would be much easier to use if you could also expand a node with the right arrow key and collapse it with the left arrow key.

**Comment by norbitheeviljester** [comment]
for me the right/left arrow keys work correctly. which dbeaver version and OS are you using?

**Comment by ihabunek** [comment]
Latest v3.6.7 on Ubuntu 16.04

```
λ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by norbitheeviljester** [comment]
This may not be the case, but I remember once having problems in eclipse in general (which afaik dbeaver is based on) in gtk. Suppossedly the tree widget and the arrow controls are configured by gtk itself and not dbeaver. Could you take a look at this answer from stack to see if it's relevant to your case?
http://stackoverflow.com/questions/4747264/is-it-possible-to-use-arrow-keys-alone-to-expand-tree-node-in-package-explorer-i

**Comment by ihabunek** [comment]
Yeah, seem to be right. Shift+left and right work. I'll see how to fix it later. Thanks for the reply.
