### ISSUE TITLE
PostgreSQL - schema rename fails

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#451]
I try to rename a schema in a PostgreSQL database using right-clic on the schema, then "rename". After entering the new name and clicking on OK button, I get the following error message:
"Can't rename object 'myschema'
Reason: Direct database rename is not yet implemented in Postgre. You should use export/import functions for that."

But it is not a database rename I try to perform, but a schema rename, which is possible with the following syntax: "ALTER SCHEMA myschema RENAME TO new_name;"

**Comment by serge-rider** [comment]
Agreed. Will add this feature in the next version/
BTW PG table rename was also broken.
