### ISSUE TITLE
automatic switch between record mode and grid mode works incorrectly.

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#452]
I'm using dbeaver 3.6.7 and postgresql 9.5
When this option is enabled:
![image](https://cloud.githubusercontent.com/assets/6532949/15322220/b6fc9298-1c3b-11e6-867b-70cee765aa42.png)
I encounter an issue with the grid mode.
1. run a query that returns a single result:
![image](https://cloud.githubusercontent.com/assets/6532949/15322246/db006d36-1c3b-11e6-9103-2b5c991c80f4.png)
2. the result should be presented in record mode.
3. now run a query with more than one result:
![image](https://cloud.githubusercontent.com/assets/6532949/15322268/fc30816c-1c3b-11e6-9725-e6870d8f664a.png)
the result is still presented in record mode. This is hard to spot and somewhat confusing. If you switch back to tab mode you'll see two rows:
![image](https://cloud.githubusercontent.com/assets/6532949/15322282/12eac5d4-1c3c-11e6-9ead-ca9a7351ea52.png)

**Comment by serge-rider** [comment]
Thanks for report
