### ISSUE TITLE
Data view tab in table editor

### ISSUE THREAD

**Issue by vckbarth** [serge-rider/dbeaver#453]
I have a change request to dev team. This request is pointed to behaviour of data viewer tab in the table editor. When I choose this feature, app use to send a sql select query compatible with example below to daba base.
**SELECT x.* FROM SOME_TABLE x**

This query is acceptable for most database systems but not for one I used to work with - FIS Profile DB. My question is: can you change this template to something like **SELECT * FROM SOME_TABLE**?
Eventually can you add a feature to edit this template?

**Comment by serge-rider** [comment]
Agreed.
But I don't think that configurable template makes sense. I'll just use simple query version by default.
