### ISSUE TITLE
Using tab to switch between cells when adding row in visual editor inserts blank string instead of null

### ISSUE THREAD

**Issue by norbitheeviljester** [serge-rider/dbeaver#454]
Using dbeaver 3.6.7 and Oracle Database 10g Enterprise Edition Release 10.2.0.4.0 - 64bit
when adding a new row to a table in oracle:
![image](https://cloud.githubusercontent.com/assets/6532949/15325574/2a304e12-1c4b-11e6-9298-4071dcea22ce.png)
by default all cells have a null value.
When I use tab to switch to the next cell:
![image](https://cloud.githubusercontent.com/assets/6532949/15325611/4b5c36fa-1c4b-11e6-9599-cf5a6906e7f4.png)
the cell value is edited to hold a blank string instead. Afaik in oracle a blank string is saved as a null anyhow but in other databases this could be an issue.

**Comment by serge-rider** [comment]
Agreed, cell value should be updated only if user changes original value.
Fix will be added in the next version.
