### ISSUE TITLE
PostGreSQL ptoblems with unique lower case indexes

### ISSUE THREAD

**Issue by gianpy** [serge-rider/dbeaver#456]
when I try to update a record using data editor I receive the follow error:
Attributes of 'users.idx_uq_lower_case_email' are missing in result set
The error exists for all unique lower case indexes on database.
For replicate error please create a unique lower index (e.g. CREATE UNIQUE INDEX idx_lower_case_email ON users.users ((lower(email)));) and after try to update a record from data editor grid.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by gianpy** [comment]
great

2016-05-19 16:08 GMT+02:00 Serge Rider <notifications@github.com>:

> Closed #456 <https://github.com/serge-rider/dbeaver/issues/456>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/456#event-665847807>
>



-- 

*In ottemperanza al D.Lgs. n. 196 del 30/6/2003 in materia di
protezione dei dati personali, le informazioni contenute in questo
messaggio sono strettamente riservate ed esclusivamente indirizzate al
destinatario indicato (oppure alla persona responsabile di  rimetterlo
al destinatario). *

*Vogliate tener presente che qualsiasi uso, riproduzione o
divulgazione di questo messaggio e' vietato. Nel caso in cui aveste
ricevuto questo messaggio per errore, vogliate cortesemente avvertire
il mittente e distruggere il presente  messaggio.*
