### ISSUE TITLE
Table data foreign key link opens other table data in same tab

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#46]
The foreign key 'link' is an awesome feature!  It unfortunately leaves the user stranded on another table's data, with no way to return to the original table. This is particularly annoying when adding data, as the only way to return to the original table is to close the tab (losing modifications, if you weren't finished) and reopen the original table.

**Comment by serge-rider** [comment]
There is a way to return to original table. Just click on Back button in the filter panel:
![fk_navigation](https://cloud.githubusercontent.com/assets/6398845/11059481/0e1b1188-87ab-11e5-8e96-43a67a0916fd.png)

Actually I agree - this feature should be somehow improved. I.e. add ability to open new table in new editor. 
So actually this is not a bug but is a feature request. I think.

**Comment by codebling** [comment]
Ah, I didn't know you could get back with the back button. To me, those buttons only control the filter. I had tried clearing the filter but I didn't bring me back to the original table. 

I guess the corollary of this way of the back/forward button way is that you don't know what table you are currently viewing.

**Comment by serge-rider** [comment]
I thought about that a lot of time but still have any no solution.
Loosing visual information about current table (actually you can see this info by clicking on SQL button) is an example of bad usability. It definitely has to be fixed.
If you have any idea on mind (UI solution) - please tell me ;)

**Comment by codebling** [comment]
Hm, couldn't the foreign key table just be opened in a new tab, with the filter set to foreign key's id ?  Then to return you can switch tabs or close the new tab.

**Comment by serge-rider** [comment]
I doubt that it will be the most convenient way. 
- It makes navigation (back/forward) senseless. Navigation is good (web browser style).
- It produces too many tabs - if user clicks on many FK references.
If you browse a custom query results (single query may produce multiple resultsets) or, even worse, script results - you already have multiple result tabs open. Opening new tabs will turn tabs into total mess. How to understand which tab is a "parent" tab to another one?

**Comment by codebling** [comment]
Hm, I see what you mean. 

I think that everyone uses software differently, and that the best UI solutions allow each user to use the software the way that they want to, while the worse solutions force the users to use software a certain way which they perhaps aren't used to. 

Basically the I think that the back/forward navigation is really great, my issue with it is only that the table name doesn't match the name of the tab, and that it's not clear that we have to use the back button to get back. 

It's not obvious that the back button is the how to return, because the back button is usually used for filter history navigation and in this case it's been repurposed for table navigation. We could solve this by giving some visual hints to the user that the back button will return them, such as a tool tip, or changing the colour of the button, but then there's still the problem that we don't have any visual cues indicating that we're on a different table. 

One way to solve both of those UI issues at once is by putting a special filter "extension" that changes the table. Perhaps `{table='fk_table'}`, along with the actual filter (like `fk=id`) that was used to filter the data. The fact that the filter is in place makes it immediately obvious that the back button will return the user to the original table. Clearing the filter should also return the user to the original table. Could additionally add a small button (like the link symbol used beside the foreign keys) to the table part of the filter which would cause it to open in a new tab and clear the filter in the original tab. 

What do you think of this solution?  I came up with a few others, but this one seems the best to me. It's more consistent with your original design, doesn't forcibly open more tabs (although it doesn't prevent users who prefer working with tabs from doing so), gives clear indication of what is happening and an easy way to go stop what's happening and go back to the original table.

**Comment by codebling** [comment]
Maybe brackets aren't the right thing for the table filter, maybe a colon is better. `table=fk_table: fk=id` might look ok.

**Comment by serge-rider** [comment]
I like it. Although I'd better show table name similarly to how modern web browsers shows current site certificate info. For example:
![address-bar](https://cloud.githubusercontent.com/assets/6398845/11250748/106aae54-8e3f-11e5-815e-9b32c81d5aa6.png)
So table name will take place of "GitHub, Inc" (and filter value will take place of url). Clicking on table name will open table editor or new results tab (this could be configurable).
Looks fancy and convenient.

**Comment by serge-rider** [comment]
Moreover we can remove "SQL" button at all. 
Clicking on table name may show context menu or some kind of tile.

**Comment by codebling** [comment]
Yes! I thought about that as well (the certificate info way), but then I thought it would prevent the user from returning to the original table by clearing the filter. But if clicking on it opens a context menu, then that would work, too !   Fancy and convenient !

**Comment by serge-rider** [comment]
Yep. I'll try to implement this in one of the next versions.
Thanks for idea ;)

**Comment by codebling** [comment]
Thanks for making a great product!

**Comment by serge-rider** [comment]
Filters panel was redesigned.
![filter-panel](https://cloud.githubusercontent.com/assets/6398845/11320230/0d459d68-90a3-11e5-935d-ad1e46c7ce8d.png)
Further improvements will be tracked in another issues.

**Comment by codebling** [comment]
Looks awesome!
