### ISSUE TITLE
MySql export database error

### ISSUE THREAD

**Issue by stepjacky** [serge-rider/dbeaver#461]
I want to export mysql database ,and right click database->menu->tools->export database 
and pop a dialog with an error under title,还没有设置连接地址 ,
how can i setting this ,i have look up all options ,but can not find some thing to set!!

**Comment by serge-rider** [comment]
Please check logs (https://github.com/serge-rider/dbeaver/wiki/Log-files).
If this error is there with stacktrace - please post it here.

**Comment by cuzz** [comment]
中文谁翻译的太烂了，其实提示是“Client home is not specified for connection”。导出mysql数据库时，dbeaver调用了外部mysqldump程序，所以需要指定mysqldump的路径，这个提示就是说没有指定mysqldump的路径。
解决方法：连接属性里面，用户名密码下面“Local Client”选择mysqldump的路径就行。选择”浏览“弹出的对话框中，神翻译“数据库地址”其实是指数据库客户端软件的路径，比如MySQL Workbench，或者Oracle Client的路径。

**Comment by serge-rider** [comment]
I don't understand Chinese but I believe I understand the problem and the solution (thanks to google translate :)

**Comment by jianghan-me** [comment]
linux版本解决方案：
今天搞了两个小时，搞定了。
导出数据的时候，需要有 mysqldump 工具（随Mysql一起安装的），再直白的说就是一个可执行文件，dbeaver需要知道mysqldump在什么位置。我的是在 /usr/bin/，直接选择这个目录就行。
