### ISSUE TITLE
Boolean fields in visual editor not updated

### ISSUE THREAD

**Issue by gianpy** [serge-rider/dbeaver#463]
Boolean fields in visual editor not updated if after value selection in drop down list you don't navigate  in a different field. Field update occurs at the focus loss and not  after  control  updating.

**Comment by gianpy** [comment]
Ok, the problem exist in all field updating, text field , combobox etc, If cell row  doesn't  lost focus or new value is not confirmed with return key  field remain null or unchanged.

**Comment by serge-rider** [comment]
I'm not sure that we should fix it. Immediate value update might be not convenient. 
Currently you can play with values then change your mind and press Escape. Immediate update will change cell value on any key press/mouse click.
