### ISSUE TITLE
There is no way to add a record at the end of grid

### ISSUE THREAD

**Issue by gianpy** [serge-rider/dbeaver#464]
There is no way to add a record at the end of grid, record is inserted even before of last row

**Comment by serge-rider** [comment]
Yes, currently new row is inserted before current.
And I don't want to add extra toolbar buttons just to add a row after current.

As a workaround I've added special case: if you press SHIFT and click on Add row/Copy row then new row will be inserted after current.

**Comment by gianpy** [comment]
Why you don't insert after selected row by default and use workaround  for insert  a top row?
I think you can also add "add ner row" in context menu.

**Comment by serge-rider** [comment]
Some people prefer to insert before, others after.
After all there is no any difference. This order doesn't affect anything.
