### ISSUE TITLE
Column suggestion stoped working since 3.6.7

### ISSUE THREAD

**Issue by marco-sanjuan** [serge-rider/dbeaver#467]
Hi

I noted, after installing 3.6.7 ea version, that column suggestion has stoped working after pressing dot. Its mandatory to type at least 1 character to start suggestion with CTLR+SPACE.
I spected that upgrading to 3.6.8 it will back to normal but still have no suggestion after tipe dot or do CTRL+SPACE for a single table:

SELECT * FROM TABLE a WHERE a.

I tried to reset configuration (by deleting .dbeaver file of user home) and, after simply configure a connection, the problem is still there, no suggestions.

The only way I get the suggestion is typing at least 1 character, but it's quite useless when you dont know the table contents, or simply whant to review table columns.

Thanks!

**Comment by carlosjrcabello** [comment]
Hi there,

I'll also test this one here.

On Mon, May 23, 2016 at 6:40 AM, Marco San Juan <notifications@github.com>
wrote:

> Hi
>
> I noted, after installing 3.6.7 ea version, that column suggestion has
> stoped working after pressing dot. Its mandatory to type at least 1
> character to start suggestion with CTLR+SPACE.
> I spected that upgrading to 3.6.8 it will back to normal but still have no
> suggestion after tipe dot or do CTRL+SPACE for a single table:
>
> SELECT * FROM TABLE a WHERE a.
>
> I tried to reset configuration (by deleting .dbeaver file of user home)
> and, after simply configure a connection, the problem is still there, no
> suggestions.
>
> The only way I get the suggestion is typing at least 1 character, but it's
> quite useless when you dont know the table contents, or simply whant to
> review table columns.
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/467>
>



-- 
Atenciosamente,
Carlos Alberto Junior Spohr Poletto

carlos.inf.br

**Comment by carlosjrcabello** [comment]
Confirmed,

Here I got the same problem, it's necessary one letter to throw content assistant.

![screen219](https://cloud.githubusercontent.com/assets/637767/15469205/15620ff2-20bf-11e6-874d-194b1c7d5876.png)

**Comment by carlosjrcabello** [comment]
I've tested based on 3.6.8-ee x64 on http://dbeaver.jkiss.org/files/ea/, and this one seems for MySQL:

Tested in Windows 10 x64, MySQL 5.7 x64

![screen222](https://cloud.githubusercontent.com/assets/637767/15512721/ae208c7a-21b7-11e6-8796-bddbdd905918.png)

**Comment by serge-rider** [comment]
Ok. Thanks for testing.

**Comment by marco-sanjuan** [comment]
Hi
Is this issue resolved on ea version? 
Or when do you plan to release 3.6.9 version?
Thanks!

**Comment by carlosjrcabello** [comment]
Hi there,

This one was fixed on build (ea) of link that I mentioned in previous comment. While 3.6.9 wasn't completed, you can use that one.

**Comment by marco-sanjuan** [comment]
Perfect, Thanks!
