### ISSUE TITLE
Installation of 3.5.3 .deb fails if 3.5.2 already installed

### ISSUE THREAD

**Issue by fracpete** [serge-rider/dbeaver#47]
When running `sudo dpkg -i dbeaver-ce_3.5.3_amd64.deb` on a Linux Mint 17 64bit, with 3.5.2 already installed, will fail with the following error message:
```
Preparing to unpack dbeaver-ce_3.5.3_amd64.deb ...
rm: cannot remove ‘/usr/bin/dbeaver’: No such file or directory
dpkg: error processing archive dbeaver-ce_3.5.3_amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 dbeaver-ce_3.5.3_amd64.deb
```
However, manually un-installing the application using `sudo dpkg --remove dbeaver-ce` allows the installation of 3.5.3 with the aforementioned command.

**Comment by serge-rider** [comment]
Yes, that's a bug in deb installer. Just fixed and published new debs.
Thanks for report!

**Comment by fracpete** [comment]
That was quick! Thanks!
