### ISSUE TITLE
autocomplete for desc command

### ISSUE THREAD

**Issue by williamokano** [serge-rider/dbeaver#473]
Hi, I noticed today that if I write `desc` and hit ctrl + space (open hints) the hints window do not open.

Database: mysql
DBeaver 3.6.8
Running on mint Rafaela
uname -a: Linux WS-SBDEV-326 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by serge-rider** [comment]
Umm, what exactly are you expecting to see after DESC?

**Comment by williamokano** [comment]
After the desc command I have to choose 1 table do describe.

On datagrip (jetbrains) after I write desc and ask for completion it shows me all the tables of the active schema and I can search using code completion.

TL;DL: after desc the hint shold work like after the FROM command.

**Comment by serge-rider** [comment]
Interesting. Is it a standard feature or its datagrip specific?

Desc/asc are reserved SQL keywords for descending/ascending sorting. Reusing them for a very different purpose looks a little odd.

**Comment by williamokano** [comment]
Well, I don't know to be honest, but the desc command works on the mysql cli as if it's a normal command.

Look at this:
http://dev.mysql.com/doc/refman/5.7/en/explain.html

I'll try for the others synonyms.

**Comment by serge-rider** [comment]
Ah, I see. It is MySQL specific.
I'll mark DESCRIBE/DESC as table keyword.

**Comment by williamokano** [comment]
Ok, thanks :)
