### ISSUE TITLE
column suggestion out of order 3.6.8

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#474]
In addition to #467 it appears 3.6.8 also changed the order in which column suggestion results are presented. I imagine that this is the result of #435.

I propose changing it so that the completion results are always presented in the order the columns appear in the table.

That being said I could understand an argument for "% matching" ordering but I would prefer that would be implemented as an option so users could decide which method they prefer. 

Currently however it appears that the column results are returned randomly as I see no reason for k_factor_09 being returned before key_01

example below 
![out_of_order_suggestions](https://cloud.githubusercontent.com/assets/9246654/15479020/e3ab4a0a-20d2-11e6-81c6-d5a12b36b985.gif)

**Comment by serge-rider** [comment]
Yes, this is the result of #435. Objects are ordered according to "search score". If strings have the same score then they ordered alphabetically.
Agreed it's better to sort by column ordinal position than by column name.
