### ISSUE TITLE
quick diff highlighting bugged for a blank row 3.6.8

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#475]
in 3.6.8 line numbers are being highlighted and I can't figure out the purpose / how to turn it off.

![strange_line_number_highlight](https://cloud.githubusercontent.com/assets/9246654/15479297/6e7a3a46-20d4-11e6-8146-10bbd6126b79.gif)

**Comment by r-richmond** [comment]
After further testing I figured out how to disable it (Enable quick diff) (Checkbox circled in blue). Although discovering its intended purpose makes me think that the blank line thing is bugged.

What does the option (Show differences in overview ruler) do? Turning off this option didn't stop this behavior.

![image](https://cloud.githubusercontent.com/assets/9246654/15479482/4854d00a-20d5-11e6-8083-33510cfe3c9e.png)

**Comment by r-richmond** [comment]
To summarize this ticket I think the two following items make sense.

1. Investigate strange blank line behavior demonstrated above. (if easy fix if not it isn't a big issue)
2. Shift the quick diff highlighting to the left (blue column below) so that it doesn't overlap with the line numbers. (Currently it looks a little messy and made it difficult to read the line numbers which is why I made the ticket.)

![image](https://cloud.githubusercontent.com/assets/9246654/15479948/af2ca9cc-20d7-11e6-993b-2a241f27bce9.png)

**Comment by serge-rider** [comment]
It seems to be a bug in Eclipse text editor framework. I can reproduce that in Java editor and other Eclipse editors.
So its not a DBeaver bug. Can't fix.
