### ISSUE TITLE
MySQL: index rename

### ISSUE THREAD

**Issue by felipeths** [serge-rider/dbeaver#476]
I am using mysql connection and am unable to rename indexes , there is no such option , only to columns

**Comment by serge-rider** [comment]
Index rename feature was added in MySQL 5.7. And not supported by MariaDB, as far as I know..

**Comment by felipeths** [comment]
Estou utilizando Mysql 5.5. O DBeaver gera automaticamente o nome dos indices. Dessa forma eu não consigo gerar dois indices. Exemplo:
Tenho a Coluna "Nome" e a coluna "Valor". Se quiser gerar um indice unique em conjunto "Nome + Valor" e depois um indice apenas para "Nome" não é possível, pois diz que já existe indice com o mesmo nome.

**Comment by serge-rider** [comment]
I see. This is actually a bug. 
Index name must be editable during creation. Once you perform real CREATE INDEX statement it's name will become read-only.
Thanks for report.
