### ISSUE TITLE
Column comments in tooltips on select results no longer displayed after 3.6.8 is installed

### ISSUE THREAD

**Issue by alvale** [serge-rider/dbeaver#477]
It was working on 3.6.6.  No matter this, I still have not been able to have it back working in 3.6.6 even after reinstalling and refreshing UI settings

**Comment by serge-rider** [comment]
I can see comments in 3.6.8. Are you sure that comments are really there? Maybe your database was changed.
You can open table column list and check.

**Comment by alvale** [comment]
You are absolutely right.  Comments are available on MySql DB but still 
cannot see them on DB2.
Although comments can be seen when selecting the column at the Database 
Nav; they are not being displayed in tooltips on select results neither 
being extracted when generating DDL SQL (This is on DB2 only)
I'll digg on my side and let you know (I've reproduced the issue on two 
different DB2 DBs so far).

**Comment by serge-rider** [comment]
I've added DB2 column comments visibility in table properties.
Also I've fixed comments editing.
But in regards to broken results columns tooltips - I still can't reproduce that.
