### ISSUE TITLE
Teradata number datatype

### ISSUE THREAD

**Issue by monsieurrouge2** [serge-rider/dbeaver#478]
Hi guys,

I am connecting to Teradata using the JDBC that is downloaded by DBeaver. Connecting is like a breaze. However, when I look at the column list in the properties of a table, NUMBER datatypes are displayed as datatype N (just the letter N). Other datatypes show correctly.
When I run a query "select numbercolumn from table1" I get the following error:

DBCException: SQL Error [1245] [HY000]: [Teradata JDBC Driver] [TeraJDBC 13.10.00.18] [Error 1245] [SQLState HY000] Unable to obtain data value because the Teradata Database indicated that the data type is ambiguous
com.teradata.jdbc.jdbc_4.util.JDBCException: JDBCException: [Teradata JDBC Driver] [TeraJDBC 13.10.00.18] [Error 1245] [SQLState HY000] Unable to obtain data value because the Teradata Database indicated that the data type is ambiguous

Every other select goes ok, but when there is a number column in the resultset, it just crashes. select * from table1 also doesn't work...
This renders the connection pretty useless for me.

When I download the jdbc jars myself and add them as a new driver, everything works correctly
Are you delivering the correct jars?

Thanks in advance.

**Comment by r-richmond** [comment]
The drivers that are automatically downloaded are out of date for teradata.

**Comment by monsieurrouge2** [comment]
Is this something that can easily be changed within DBeaver?

Furthermore, when I replace the driver with a newer one, connection times jump to 10 seconds, while using the automatically downloaded versions takes 1-2 seconds. Does anyone know why?

**Comment by serge-rider** [comment]
I can update driver. Could you recommend some popular modern version?

**Comment by r-richmond** [comment]
the most recent driver from http://downloads.teradata.com/download/connectivity/jdbc-driver

resolves the issue

**Comment by serge-rider** [comment]
Ok. I'll update driver to 15.00.00.33

**Comment by r-richmond** [comment]
not sure if your comment above was a typo or not but to confirm the latest is `Release 15.10.00.14  -  11 Dec 2015`

**Comment by monsieurrouge2** [comment]
The problem is solved now.
