### ISSUE TITLE
  PostgreSQL CONSTRAINT display bug

### ISSUE THREAD

**Issue by zsom** [serge-rider/dbeaver#479]
HI!

I have a table with constraints in a PostgreSQL database.

In DBeaver I can't see the details of the constraints. I only see this at the table's DDL tab:

`CONSTRAINT ck_xxx CHECK (col1,col2)`

In the constraint properties view I see the owner, the affected columns.
But I can't see anywhere the conditions of the constraints.

PgAdmin III (the official client for Postgre) shows the exact constraint definition:

  ```
 ALTER TABLE yyy
      ADD CONSTRAINT ck_xxx CHECK (col1= (-1) AND col2 IS NULL ...);
```

Please fix this bug!

I'm using DBeaver 3.6.7 win 64 bit CE

Thanks,
zsom

**Comment by zsom** [comment]
Copied from the old forum http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=3042

**Comment by serge-rider** [comment]
Please post a valid SQL snippet (CREATE TABLE with columns/constraints).

**Comment by zsom** [comment]
```
CREATE TABLE test2
(
  id integer NOT NULL,
  aaa integer,
  bbb character(100),
  CONSTRAINT test2_pk PRIMARY KEY (id),
  CONSTRAINT test2_check_1 CHECK (aaa > 100)
)
```
This insert will succeed:
`INSERT INTO test2 (id, aaa, bbb) VALUES (1,200, '1')`

This insert will fail (what is right):
`INSERT INTO test2 (id, aaa, bbb) VALUES (2,99, '1')`

Nor the DDL of the table, neither the constraint details don't show the condition of the constraint. See this screenshots:

![postgres_constrain_bug_1](https://cloud.githubusercontent.com/assets/14965185/15532543/9bf06cb0-2260-11e6-8426-2554b2f62f3a.PNG)
![postgres_constrain_bug_2](https://cloud.githubusercontent.com/assets/14965185/15532548/a0aec30a-2260-11e6-8c3b-22f0fad72c3c.PNG)



Now I'm using the latest version: 3.6.8

**Comment by serge-rider** [comment]
Thanks for details.
Will be fixed in the next version.
