### ISSUE TITLE
data export error

### ISSUE THREAD

**Issue by mkahraman** [serge-rider/dbeaver#480]
hi,

I want tı export to .sql but i'm getting this error 'java.lang.NullPointerException:' 
 use version: 3.6.8

**Comment by SirBenJammin** [comment]
Hey Serge,

I am also getting the same error after installing 3.6.8 when exporting data to CSV.

![image](https://cloud.githubusercontent.com/assets/17081097/15512338/a1b5c00e-21df-11e6-8720-25db09c9dfc7.png)

Thanks,

Ben

**Comment by serge-rider** [comment]
It's a known issue.

I think I'll release 3.6.9 on the next week (as a hotfix version).

**Comment by reygoch** [comment]
I have version 4.2.3 and this error appeared when I tried to view ER Diagram.

**Comment by serge-rider** [comment]
This is definitely a different error. 
Please post error stacktrace (you can get in Error Log view: main menu Window->Show View->Error Log).
Also it makes sense to create a separate ticket for that bug.
