### ISSUE TITLE
Grammar regression

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#481]
Changes accepted in #196 were undone in https://github.com/serge-rider/dbeaver/commit/6d0ee551e0738cdb3316f810b3f7a7656c556ce8#diff-93f17c9bedb1fb867907e0c1e6cba40d

was this intentional?

**Comment by serge-rider** [comment]
Nope. I think its a result of mess in Git merges/updates.

**Comment by r-richmond** [comment]
cool thanks for quick fix
