### ISSUE TITLE
Session manager toolbar visibility bug

### ISSUE THREAD

**Issue by williamokano** [serge-rider/dbeaver#485]
Hi, I would like to request for a new feature.

Basically it consists in add the command "kill session" on the context menu of the MySQL DB ->  Administer -> Sessions grid.

Currently it has only the copy option. It should work on multiple selections too.

![captura de tela de 2016-05-25 11 17 26](https://cloud.githubusercontent.com/assets/5909442/15543175/44cb2524-226a-11e6-8c06-29241fec4913.png)

**Comment by serge-rider** [comment]
Hmm. This feature is already there. You can kill/terminate database session using toolbar buttons.
But, for some reason, toolbar isn't visible in GTK (it is at the bottom of editor). So it is a UI bug.

As a workaround you can move slider which divides Database navigator and editor. Surprisingly it makes toolbar visible.

**Comment by serge-rider** [comment]
10x for report.
Also I'll add these actions in the context menu.
