### ISSUE TITLE
Postgres dropping functions error

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#487]
Drop statements for functions are still not allways quite right;
It fails because it specifies both, IN and OUT parameters in the function signature.
Only IN parameters should be specified.
Note that this applies to function signatures in general, not only for DROP.

Example: Create test function:

create function public.foo(in text,out integer) returns int as $$ select length($1) $$ language sql;

DBeaver issues this SQL:
DROP FUNCTION public.foo(text,int4);

Instead, it should be:
DROP FUNCTION public.foo(text);

**Comment by serge-rider** [comment]
Thanks for report
