### ISSUE TITLE
bug: set tab title (result tab) doesnt appear to be working

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#489]
Set tab title doesn't appear to be working

![set_tab_title_broken](https://cloud.githubusercontent.com/assets/9246654/15558192/1f80ecfe-228d-11e6-8be9-d2e3f8c83040.gif)

**Comment by serge-rider** [comment]
Yeah, this is just not yet implemented. Dummy menu item does nothing.

BTW you can set tab title using SQL comments:
```sql
--title: Some title
select * from dual
```
