### ISSUE TITLE
Firebird missing DDL for procedures, views

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#49]
With Firebird, we dont have DDL on procedures and views, also we cant save modifications because the sources are only readable.

**Comment by serge-rider** [comment]
I'll add CREATE/ALTER DDL statements.
But they will remain read-only for a while. Generic driver doesn't support sources modification.

**Comment by adamos42** [comment]
Its okay if the DDL are good :) Im always saving my scripts, after every modification for versioning.
