### ISSUE TITLE
select row count from query doesn't account for group by & ctes

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#490]
Here is what happens if you are using a cte
![cte_row_count_broken](https://cloud.githubusercontent.com/assets/9246654/15558432/010a7a18-228f-11e6-9277-1af6d496655f.gif)

Here is what happens if you are using a group by

![groupby_row_count_broken](https://cloud.githubusercontent.com/assets/9246654/15558584/dca2d5fc-228f-11e6-9974-eb9d4e81bc92.gif)

I see two issues

1) the general form of the row count query is wrong. It should be some like this

```
select count(*) 
from ( 
  {query}
) as x
```

rather than just replacing the select columns with count(*)

2) for queries involving ctes it strips out the cte and has the same issue as above.
 the general form in this case should be something like

```
{with_portion_of_query} 
select count(*) 
from ( 
  {select_portion of query}
) as x
```

my quess is that fixing 1) is easy whereas 2) is a little more challenging. so my opinion is that fixing 1) and not supporting ctes (not fixing 2) with this feature would be ok.

**Comment by serge-rider** [comment]
Main problem is that select count(*) from (select ... ) syntax is not supported by many minor databases. Especially if you have a complex query with it's own subselects and other stuff - in that case even major databases (like MySQL, Oracle, etc) may fail.
DBeaver have used that approach a time ago but it was even worse than current one.

Another problem is that I don't want to spend too much time for such small feature ;)

**Comment by r-richmond** [comment]
I tested the following query on teradata, mysql, oracle (added from dual here), postgres and didn't receive any errors. Although I can't account for the minor databases. 

```
select count(*)
from (
  select c.*
  from (
    select b.*
    from (
      select
        a.*
      from (
        select 1 as id union all
        select 2 as id 
      ) a
    ) b
  ) c
) d
```

that being said I agree that this is a small feature and supporting it may not be worth the effort.

However, in that case I would argue for removing the feature as it is better to return no results rather than wrong results.

**Comment by serge-rider** [comment]
This feature is quite useful for some people, i don't think that removing it is the best solution.
You can see actual query right in results viewer filter panel so you shouldn't be confused too much..

**Comment by r-richmond** [comment]
If you can't use the correct correct query format above 1) & you don't feel comfortable removing the feature

the only other thing I can recommend would be adding a note of some sort to indicate that it may return the wrong results... otherwise feel free to close out...

**Comment by r-richmond** [comment]
closing this out to reduce clutter...
