### ISSUE TITLE
DB2 LUW 9.7 - cannot generate table DDL

### ISSUE THREAD

**Issue by Cris70** [serge-rider/dbeaver#492]
Hi,
I am having problems generating the DDL for any table on DB2 LUW 9.7 (I am testing on AIX).
Whenever I select "Generate SQL" -> "DDL" I get this error:
```
Errore SQL [38553]: Routine "*RATE_DDL" (specific name "*RATE_DDL") has returned an error SQLSTATE with diagnostic text "SQL0727 Reason code or token: 2,-206,42703,OBJ_SUBTYPE     ".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.14.146
  com.ibm.db2.jcc.am.SqlException: Routine "*RATE_DDL" (specific name "*RATE_DDL") has returned an error SQLSTATE with diagnostic text "SQL0727 Reason code or token: 2,-206,42703,OBJ_SUBTYPE     ".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.14.146
```
It seems a column is missing, or something like that.

Thank you in advance for your help.
Cris

p.s. I'm using DBeaver 3.6.8

**Comment by Cris70** [comment]
If you need me to test something on AIX I can do it.

**Comment by titou10titou10** [comment]
Hi,
"SQLCODE=-443" denotes an authorization problem.
DBeaver uses the internal procedures that implements the "db2look" db2 command to generate DDL and it seems that the user you use to connect to the database is not authorized to execute the db2look command in this database.
You have 2 options:
- either connect to the database with a user that has the authority to run the db2look command
- give the user you use, the authority to run the db2look command

[DB2 official  documentation on db2look for DB2 UOW v9.7](http://www.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0002051.html?pos=2)

Denis (author of the DBeaver DB2 extension)
