### ISSUE TITLE
Is there a guide to loading plugins into DBeaver?

### ISSUE THREAD

**Issue by mtustin-handy** [serge-rider/dbeaver#496]
I'd like to use DBeaver to extract a bunch of metadata about my databases (in a specific json format). A DBeaver plugin seems like the way to go. Is there a guide for this, in any form? Any trick to it? I figure I can cargo cult the code under /plugins, but I don't know how to load it - is it enough to put it on the classpath?

**Comment by serge-rider** [comment]
DBeaver is based on Eclipse framework.
http://www.vogella.com/tutorials/EclipsePlugIn/article.html
http://stackoverflow.com/questions/299283/how-to-write-a-plugin-for-eclipse
