### ISSUE TITLE
Driver for OpenLink Virtuoso

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#497]
Please include the driver for OpenLink Virtuoso database.
JDBC driver is available here: http://docs.openlinksw.com/virtuoso/VirtuosoDriverJDBC.html
It works fine with DBeaver, but requires user to go hunting the net to find it. Can run SPARQL, too!

Note: one must set CHARSET to UTF-8 in connection URL for it to work right, such as:
jdbc:virtuoso://localhost:1111/CHARSET=UTF-8

**Comment by serge-rider** [comment]
Aren't you aware of Maven artifact for Virtuoso jdbc driver?

On the link above I don't even see a download link.

**Comment by lacanoid** [comment]
Had no idea about Maven. Tnx.

Here is the link I got my jar from:
https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/JDBCDriverType4/virtjdbc4.jar

**Comment by serge-rider** [comment]
I've hardcoded GitHub URL for now although Maven artifact would be much better. It will let to choose driver version, automatically update version, etc.
