### ISSUE TITLE
Jeeeyul theme and EclipseColorThemes compatibility?

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#50]
Im using in my eclipse the Jeeeyul theme customizer and a custom Eclipse Editor Color theme, sadly the dbeaver dont working from the editor themes so every script window has white background and it looks soo bad. Please make some support for least EclipseColorThemes, but the best will be if we able to customize by Custom CSS in Jeeeyul theme.

Screenshot from the editor:
![DBeaver perpective](http://a42server.net/static/dbeaver/screenshot003.png)

How should be look:
![DBeaver perpective](http://a42server.net/static/dbeaver/screenshot002.png)

It will be even better if in standalone DBeaver we will able to install Jeeeyul and EclipseColorThemes :)

**Comment by serge-rider** [comment]
Eclipse 4.x has its own support of Dark theme. DBeaver has predefined styles for most of its parameters. Does EclipseColorThemes  is better than standard themes support? Honestly I'm not familiar with this plugin.

**Comment by adamos42** [comment]
Eclipse Color Theme if you familiar with or not has 12k theme to customize your editor colors, most of the eclipse users I think using some of this themes, the Eclipse Dark theme its kind of good, but the users cant costumize it. Also if somebody using the Jeeeyul theme then the dark theme is not available to add dark colors to the editor. The Black theme good initiative, but not nearly good enough because its not integrate into the user operating system theme. I hope in future Eclipse will integrate into the operating system theme until then the Jeeeyul plugin can customize the theme for it.

**Comment by serge-rider** [comment]
Frankly I was a bit surprised that DBeaver wasn't affected by EclipseColorThemes automatically.
I never (almost never) use particular hardocoded colors in UI. For instance white background comes from standard eclipse color COLOR_LIST_BACKGROUND. Colors in SQL editor and results panels can be customized using preferences.
I assume that EclipseColorThemes requires some customization for each and every view, editor or control. Or maybe even EclipseColorThemes developers themselves have to make some customization for 3rd party solutions. According to their description on Eclipse Marketplace they are making support of each Eclipse-based IDE by themselves.
Anyhow I'm afraid I don't have resources for such integration for now. Maybe later, when most of more urgent tasks will be solved.

**Comment by adamos42** [comment]
Okay, the "COLOR_LIST_BACKGROUND" property is help a lot, because I can make my own css for that with Jeeeyul. Can you share the other properties what DBeaver using in listing and in scripts?

**Comment by serge-rider** [comment]
You already can change Eclipse/DBeaver look-and-feel by customizing CSS in preferences. COLOR_LIST_BACKGROUND and other standard SWT constants are used by all UI plugins, this is not something DBeaver-specific.
Back to the topic. I think that this is a task for https://github.com/jeeeyul/eclipse-themes/ project. Maybe some modifications will be needed in DBeaver code as well - in that case I'll accept any valuable pull requests.
