### ISSUE TITLE
Special characters in database name support

### ISSUE THREAD

**Issue by dimitriadisg** [serge-rider/dbeaver#505]
Hello,

The database import tool fails for databases that contain special characters in their name.

I discovered this problem when I was trying to import a dump sql file into a database that used ssh connection to a remote server. The database had a name containing dashes, something like "mydb-dev-api" (without quotes). When I ran the tools->import into that database it ran normally, but the log had an error, looking like this :

`ERROR 1044 (42000): Access denied for user myuser@localhost`

(Using localhost as the host, because the connection is established through ssh configuration)

The user has full priviledges and tested from my colleague's db client he could import data normally.
After some testing with SQL commands, I was able to realise what was wrong and reproduce an error locally. After replacing the dashes with underscores I am able to import into the remote database normally with the same configuration.

Now, if you want to reproduce the error, here's what you can do:
- Create a database called my-db-
- Try to import any dump file into this database
- You'll get something similar to this :

```
C:\xampp\mysql\bin\mysql.exe
Database Import started at Wed Jun 01 15:10:17 CEST 2016
ERROR 1049 (42000): Unknown database '`my-db-`'
Database Import finished at Wed Jun 01 15:10:17 CEST 2016
Process exit code: 1The pipe is being closed
```

I am using Windows 10 64 bit and DBeaver Community Edition 3.6.9 and Xampp 5.6.14 local mysql  client.
As always, thank you for your support !

Best regards,
George

**Comment by serge-rider** [comment]
It is a bug. 
Command line with database name shouldn't be escaped.
