### ISSUE TITLE
ssh socks proxy

### ISSUE THREAD

**Issue by msmcgillis** [serge-rider/dbeaver#510]
Often times when I have to access databases through a vpn I use a different machine for the vpn connection than my desktop.

Then I ssh to that vpn box and use a ssh socks proxy to forward all requests to the site with a configuration like:

Host vpn
DynamicForward 14000

I tried to use the socks setting in DBeaver to work through this but it does not work.

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/847762/15801462/8c158536-2a4a-11e6-9595-e00862325461.png)

This socks proxy does not require any user/password to access just localhost:14000. Would love to see this working some day.

**Comment by serge-rider** [comment]
That's a pretty sophisticated way to connect with DB. I'm not even sure I fully understand the configuration.
Can you connect using 3rd party tools for SSH tunnels (like Putty)?

**Comment by msmcgillis** [comment]
Putty not sure openssh yes this is a common alias I use to simplify things for me:

```
alias scppvpn='scp -o ProxyCommand='\''nc -x localhost:14000 %h %p'\'''
```

```
alias sshpvpn='ssh -o ProxyCommand='\''nc -x localhost:14000 %h %p'\'''
```

**Comment by williamokano** [comment]
As a workaround you can use the proxychains.

Just configure the socks5 tunnel there and open the dbeaver using it

```proxychains dbeaver```

Worked for me every time :)

**Comment by msmcgillis** [comment]
Thanks for the suggestion nice tool for my toolbox but unfortunately it isn't working for this in the specific case I wanted it. On MacOS if I use "proxychains open -a DBeaver" It doesn't work and I don't think it will since open exits after starting DBeaver which exits proxychains. Tried "proxychains /path/to/dbeaver/binary/dbeaver" but this just blows up so for now I'm giving up on this for this case. But, have other uses for proxychains thanks for the pointer.

**Comment by serge-rider** [comment]
Still have no idea how to resolve this from DBeaver side.

**Comment by williamokano** [comment]
@serge-rider how do you connects to the databases? RAW JDBC?

I'm not a Java expert (being honestly, like Jon Snow, I know nothing) but you could try this config from the Java.Network package

```java
System.setProperty("http.proxyHost", "127.0.0.1");
System.setPropery("http.proxyPort", "14000");
```
Ref:
http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html

**Comment by serge-rider** [comment]
HTTP proxy is different (and it can be configured in Preferences on Drivers page).
How exactly driver connects to a database depends on driver implementation. But in most cases it is plain TCP/IP socket.
SOCKS proxy can be configured on connection properties->Network page.
But as far as I understood this doesn't work.

**Comment by tati-kru** [comment]
Hello @msmcgillis,

Does this problem continue to be actual or you find the way to solve it?

**Comment by msmcgillis** [comment]
Tried with dbeaver 4.2.3 and socks proxy now works as I expect over ssh proxy.

Thanks for the update glad to see this working now.
