### ISSUE TITLE
Check for Updates logic

### ISSUE THREAD

**Issue by emelsk** [serge-rider/dbeaver#516]
Running 3.6.10 EE on Win7 x86_64, when I do Help->Check for Updates, I get the output as follows:

![dbeaver cfu1 nfb](https://cloud.githubusercontent.com/assets/17256144/15893410/de5bf658-2d7f-11e6-93e6-5c8f6b92530c.png)

Is this intended? Clicking Update button results in the message I was expecting to see instead of the previous one:

![dbeaver cfu2 nfb](https://cloud.githubusercontent.com/assets/17256144/15893458/2cd8ac4a-2d80-11e6-9777-56f922705264.png)

**Comment by serge-rider** [comment]
It is a bug, update dialog is shown even if there are no updates.
You can get EA version (it is already fixed there).
