### ISSUE TITLE
SQL formatting does not work between brakets

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#517]
I have configured DBeaver to automatically set keywords in upper case (using Preferences -> General -> Editors -> SQL Editor -> SQL Formatting).
Formatter is set to "Default" and Keyword case is set to "Upper".

This works fine, except when the keyword is typed between brackets: the automatic upper conversion does not work (only on the same line of the opening bracket).

**Comment by serge-rider** [comment]
Can't reproduce. 
What exactly brakets? 
Maybe some SQL snippet?

**Comment by ced75** [comment]
Sorry, I should have give a screen copy:
![image](https://cloud.githubusercontent.com/assets/12892581/15964328/495dd3e2-2f18-11e6-9d31-2577badd3120.png)
Here, "where" should automatically be converted in upper case. But it is not the case...

**Comment by serge-rider** [comment]
Thanks for details
