### ISSUE TITLE
Tables filter and right click

### ISSUE THREAD

**Issue by your-mirror** [serge-rider/dbeaver#519]
I have an idea about tables filter.

I think it will be easier if you can add table to filter by right-click. You just select table/tables in "Database Navigator" or Main Window then you right-click and choose an option "Add to filter".

I'm thinking about "Remove from filter", but I'm not sure how it should work...

**Comment by serge-rider** [comment]
Yeah, I like it. And its easy to implement.
Thanks for idea.

I think that "Remove from filter" action may remain the same (thru Filters dialog). It is not so frequent operation and its ok.
