### ISSUE TITLE
[Feature Request] Copy data on other formats

### ISSUE THREAD

**Issue by williamokano** [serge-rider/dbeaver#520]
Hey, me again.

I just want to request, if possible, ability of copy the data in other formats, like json, csv or sql (insert/replace statement).

For example, if I query ```select name, age from users limit 2``` and get the following result:

|name|age|
|---------|----|
|william|26|
|serge-rider|33|

If I select all the rows, when I copy (ctrl + c) put the following content on the clipboard

```sql
insert into table (name, age) values ("william", 26);
insert into table (name, age) values ("serge-rider", 333);
```

Or even other formats, like a json

```javascript
[
    {"name": "william", "age": 26},
    {"name": "serge-rider", "age": 33}
]
```

DataGrip (from jetbrains) has this feature and I think it's very useful. Could be a plus to dbeaver :)

**Comment by serge-rider** [comment]
This feature is already implemented. Even twice:
- You can use "Export Resultset" feature (in the context menu). You can make export in any format and copy results into clipboard.
- You can use "Generate SQL" feature (for selected rows).

**Comment by williamokano** [comment]
Oh, I see. My bad :)

Thanks again!
