### ISSUE TITLE
Change window Result Set Order/ Filter Settings

### ISSUE THREAD

**Issue by jad986** [serge-rider/dbeaver#523]
Hi,

can you change window Result Set Order/ Filter Settings according to the following?

**A. Add new buttons**

1. move to the top (first place)
2. move to the bottom (last place)

**B.  Move more then one column etc. move all selected columns ?**

Thanks!

**Picture**

![2016-06-09 15_03_45-result set order_filter settings](https://cloud.githubusercontent.com/assets/17430370/15930886/6d2b42f0-2e55-11e6-968f-a23d049262a3.png)

**Comment by serge-rider** [comment]
Good point.
I'm going to redesign filters control toolbar.
