### ISSUE TITLE
Copy Selected Header/Headers

### ISSUE THREAD

**Issue by jad986** [serge-rider/dbeaver#524]
Hi,

Can you add new item "Copy Selected Header/Headers" to the menu ? When you will choose this item, only the name of column selected header will be copy and separated by commas -> next you can paste this string to the your new query (etc. after select).

Picture:
![dbeaver_2](https://cloud.githubusercontent.com/assets/17430370/15935115/7da9b84e-2e66-11e6-90b1-03dfc6342ea4.png)

Thanks!

**Comment by serge-rider** [comment]
Yeah, this is a very old feature request. Time has come.
