### ISSUE TITLE
persistence of procedural code issue with mysql/mariadb (3.6.10)

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#525]
When persisting code to mysql/maria database, dbeaver generates the following code for example:
```
DROP PROCEDURE IF EXISTS some_db.populateMart;
CREATE DEFINER=`dbuser`@`%` PROCEDURE `populateMart`()
BEGIN
...
```
In the above code the 'some_db.' preffix is missing in the 'CREATE PROCEDURE' statement which leads to the creation of the procedure in the current database (which isn't necessarily 'some_db'), instead of the one that the procedure belongs to. However, the real procedure is actually dropped.
The result is unexpected and unintended.

**Comment by serge-rider** [comment]
Thanks for report
