### ISSUE TITLE
persistence of procedural code issue with postgresql (dbeaver 3.6.10)

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#526]
When persisting changes to postgresql procedural code, the following statement is generated by dbeaver:
```
DROP FUNCTION IF EXISTS some_db.trfn_account_campaigns_biu();
CREATE OR REPLACE FUNCTION some_db.trfn_account_campaigns_biu()
```
When the edited code is a dependency for other db objects (views, triggers, etc.), the drop statement fails (unless 'CASCADE' option is specified, which might be catastrophic): 
`SQL Error [2BP01]: ERROR: cannot drop function trfn_account_campaigns_biu() because other objects depend on it`...

Moreover, when using 'OR REPLACE' construct, the 'DROP' statement is redundant.

**Comment by serge-rider** [comment]
Agreed. Preceding DROP statement doesn't make sense for PG. It is a copy/paste from MySQL extension.
Thanks for report.
