### ISSUE TITLE
Cannot delete rows in grid in SQL Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#528]
If I perform a select, and then I press the del key onto a row, and I click on the green check in order to confirm the changes, I get first a generic message: 
```
Can't detect source entity
```

and then I get
```
org.jkiss.dbeaver.DBException: No unique identifier defined
```

**Comment by serge-rider** [comment]
DBeaver cannot find any unique table identifier and thus it can't edit table's content.
When you try to save changes for the first time it will ask you to define your custom unique key. 
Or you can define custom key in the settings menu:
![rsv_settings_menu](https://cloud.githubusercontent.com/assets/6398845/15970056/5efe7828-2f3b-11e6-8027-a0db0159beaa.png)

**Comment by serge-rider** [comment]
The worst case when DBeaver cannot find a source table (it may happen when you edit results of custom SQL query). In this case it can't edit table at all.
Specify fully qualified table name (with schema name) in your query to let DBeaver to resolve table metadata.

**Comment by gabriele-ricci-kyklos** [comment]
When performing a `select * from table` the *Define virtual unique key* menu is disabled

**Comment by serge-rider** [comment]
It means the worst case (see above).
DBeaver doesn't have a special SQL Server extension (although we have plans to add it in the next major version). And JDBC driver doesn't provide enough meta information. So I'm afraid there is nothing I can do with this problem.

**Comment by gabriele-ricci-kyklos** [comment]
It seems that adding `dbo.` before the table name fixes the issue. Thanks for support

**Comment by CurvesTech** [comment]
For me, I refreshed the connection and the problem went away.
