### ISSUE TITLE
Wrong table is choosen when editing table in oracle

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#529]
If I try to edit a table by pressing F4, if the table I'm trying to edit exists in another schema, then it happens that I edit the one not on my schema.
Example:

- I want to edit the table *BTARTICLES*
- I'm on *MY_SCHEMA_DEV*
- I write `SELECT * FROM BTARTICLES` and I select the table name and click F4
- I end up editing the table *BTARTICLES* of schema *PRODUCTX_DEV*

If I right-click the table in the tree at the left side everything works correctly

**Comment by serge-rider** [comment]
It is a bug.
Object chooser (F4) uses the same algorithm as hyperlink detector and selects the first object in the hyperlink list (to see the list press CTRL and hover over identifier).
Tables in the active schema must be in the beginning.
Thanks for report.

**Comment by gabriele-ricci-kyklos** [comment]
You're welcome! I use dbeaver often at work, I'm glad to participate and make it better
