### ISSUE TITLE
when opening file from workspace with sql editor databases list is not populated

### ISSUE THREAD

**Issue by farmboy0** [serge-rider/dbeaver#53]
I am using DBeaver 3.5.3 as eclipse plugin.
I have associated DBeaver's SQL Editor with .sql files.
When I open one of them the databases list in the toolbar remains empty except for the None entry and the editor remains with the disabled background.
if i open a new SQL Editor from the SQL Editor menu the list is populated even for the already open SQL Editor.

**Comment by serge-rider** [comment]
Possibly this issue was fixed along with #60. 
Could you check version 3.5.4 and validate?

**Comment by farmboy0** [comment]
Still happening with 3.5.4

**Comment by farmboy0** [comment]
To give more context.
I am not using Scripts in the Project - Servers view.
I use the Java perspective with a list of projects in the project navigator.
One of these projects(not a java project) contains .sql files that I "Open with..." SQL Editor.

**Comment by farmboy0** [comment]
Is there something I can do to help you reproduce the issue?
Do you need more information?

**Comment by serge-rider** [comment]
I think I just reproduced that. And this is more than just a bug.

DBeaver connections are available only in some particular project. In the project where you created these connections actually. You can switch to DBeaver presentation -> view "Projects" and check where connections configuration actually lives. You can also set another active project and create connections there.

I assume that you created DBeaver connections in some project and then you opening an SQL scripts in another project. But SQL script can't be associated with a connection which defined in a different project. Possibility to see connection from another project is actually a bug.

Anyhow, although DBeaver works (more or less) as expected it works not good enough. Sometimes we have pretty many projects in a single workspace. Inability to share connections between projects is a kind of malfunction. In fact it is a kind of atavism of standalone version.

I'll think about all that.. Meanwhile you could create a feature request ;)

**Comment by farmboy0** [comment]
As far as I remember I used the Database menu and there the New connection entry to create connections. There was never any association to any project in the workspace as far as I remember.
I usually work with the DBeaver perspective and there with the database navigator to open tables or create SQL editor to run some SQL commands on the configured databases.

**Comment by serge-rider** [comment]
This association was even in the very first versions of DBeaver. When you are in DBeaver perspective and/or "Database Navigator" view then you are working in "active" project (you can see it in the "Projects" view).
But when you are in Java (or any other) perspective then there is no active project, there is just current project - project to which current SQL file belongs..

**Comment by farmboy0** [comment]
works in 3.5.6 please close
