### ISSUE TITLE
Cannot generate sql scripts on SQL Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#530]
If I right-click on a row in the grid and select *Generate SQL* the menu disables itself and nothing more happens.
Moreover, if I duplicate a row in the grid, and then I click on the *generate changes script* button I get
```
org.jkiss.dbeaver.model.exec.DBCException: Internal error: can't obtain entity identifier
```

**Comment by serge-rider** [comment]
This problem has the same source as in #528.
Marking as duplicate.
