### ISSUE TITLE
Detect active schema/database after SQL execution

### ISSUE THREAD

**Issue by jbujonwaibi** [serge-rider/dbeaver#531]
This is more about an improvement/ new feature request than a bug ...
This concerns MySQL but I think it could concern some other DBMS.
So, here is my request (low priority) :
Is it possible to make SQL "use someDbName;" statement execution change the active catalog/schema in DBeaver U.I. ?
Or at least, is it possible to show last used catalog/schema name somewhere in the results panel ?

**Comment by jbujonwaibi** [comment]
Sorry, I close it because I thing it's not an issue, and I hadn't seen I could send other requests by email.

**Comment by serge-rider** [comment]
It is much better to track issues here than by email.
Anyhow, this feature is already there.
You can switch active database in database navigator (context menu-> set active). Also you can switch it in the main tolbar of SQL editor.

**Comment by jbujonwaibi** [comment]
OK.
I think my first post was not clear.
I had seen that I can do it using context menu or main toolbar, but I've been used to create scripts with the "use" keyword in MySQL Workbench to select current database for further requests ; at least for elements not prefixed with the database name.
I don't know if it is the jdbc driver or the server that keeps the current database in "memory" but after I execute the "use" statement, my further MySQL requests will execute against that current schema. 
But the "problem" with my method is : after that in DBeaver, the active schema shown in the menu bar may not be the current database selected with "use" keyword...
And I would like to know if it is possible to detect requests executed containing "use" keyword, and change dynamically the active database shown in DBeaver U.I ?
I hope my issue is clearer now.
Thank you in advance for your answer.

**Comment by serge-rider** [comment]
Thanks for clarification.
Yes, this makes sense. For all databases not just MySQL.

**Comment by serge-rider** [comment]
One note: default database is set for whole DBeaver database connection (it is shown in the navigator tree and in the main toolbar of active editor).
But each DBeaver connection may have multiple physical database connections (one for metadata reading, one for each opened SQL editor, etc). If your SQL script changes default database it become inconsistent with other physical connections. 
Possible workaround: If I'll find that default database was changed I can explicitly change default database for all other connections too. Any thoughts?

**Comment by jbujonwaibi** [comment]
Thank you for your investigation.
I think the workaround should be the better solution for me, but I think you could maybe add a preference setting for user to choose default behaviour when a script changes default database (change apply to all physical connections or only concerned physical connection). 
But that's just my thoughts ... I'm not an expert in DB management.
Maybe you could ask advice for default behaviour to some other DB users ?

**Comment by serge-rider** [comment]
Well, I made it change active schema for all connections.
Looks good.
