### ISSUE TITLE
Generate Insert SQL from Result Set always includes all columns

### ISSUE THREAD

**Issue by Jeetah** [serge-rider/dbeaver#533]
I have a result set containing not all table columns. But if a choose Generate SQL -> Insert it always includes all table columns. There seems to be no obvious way to export only a subset of columns to an INSERT statement...

**Comment by carlosjrcabello** [comment]
Hi @Jeetah ,

I'm verifying this feature here, and seems strange... @serge-rider , When I send, for instance:

`desc tb_foo;`

Then, I select some result fields, then goes to context menu **'Generate SQL / Insert'**:

![image](https://cloud.githubusercontent.com/assets/637767/16017595/049fe360-3177-11e6-9772-9baa119c4166.png)

Does DBeaver will generate some insert statement from selected fields, or just for all tables columns ?

At this moment, this action returns this popup with _information_schema insert_...
![image](https://cloud.githubusercontent.com/assets/637767/16017684/58c291e0-3177-11e6-87a8-6228a73d4bf9.png)

I daily work with data migration and querying reports, and if the DBeaver had this option would be beautiful :), such as:

1. show columns from tb_foo / desc tb_foo;
2. select some columns;
3. Generate resumed insert for it;

**Comment by serge-rider** [comment]
Sounds reasonable.
Will check it after I'll be back from vacation ;)

**Comment by carlosjrcabello** [comment]
OK Serge, enjoy it.

**Comment by serge-rider** [comment]
Possible solution: I can use only visible columns for INSERT/UPDATE statements. So you can hide unneeded ones and generate needed SQL.
What do you think?

**Comment by Jeetah** [comment]
Sound pretty useful. Looking forward to it!

**Comment by serge-rider** [comment]
Ok. SQL generator will be fixed in the next version.
