### ISSUE TITLE
 Enter direct data on the grid

### ISSUE THREAD

**Issue by felipeths** [serge-rider/dbeaver#534]
Must have option to enter direct line of network "data" not only SQL. So How And Made By Edit A cell no grid .

**Comment by serge-rider** [comment]
Sorry, I don't get it.
What do you mean under network data? Any examples?

**Comment by felipeths** [comment]
Sorrry my English = ) 
I refer to the grid , see:
http://i.imgur.com/A2T7Ym7.png

**Comment by carlosjrcabello** [comment]
Hi there,

@felipeths , você tem essa opção para adicionar uma nova row na sua tabela através do atalho `Alt + Insert` quando tiver feito uma consulta de uma tabela.

![image](https://cloud.githubusercontent.com/assets/637767/16083020/e5a809c8-32e9-11e6-9db2-fb0c3ebd8fc3.png)

Para ativar a edição, basta dar um duplo clique na coluna da row deseja e ao final clicar no botão de salvar abaixo (tick) ou então usar o atalho `Ctrl + Alt +S`.
![image](https://cloud.githubusercontent.com/assets/637767/16083134/513d583c-32ea-11e6-8daf-63a180ed87b8.png)

Lembrando, que, quando você tem consultas complexas com diversos agrupamentos, não é recomendado fazer essa edição, uma vez porque é quase impossível de aplicar os updates/inserts nas tabelas que estão no 'from'.

**Comment by felipeths** [comment]
Desculpa, sou novato nesse programa, não tinha percebido essa opção, muito obrigado pelo esclarecimento =)

**Comment by carlosjrcabello** [comment]
Em paz.
