### ISSUE TITLE
SQLite extension (table rename, triggers, etc)

### ISSUE THREAD

**Issue by AndrzejKl** [serge-rider/dbeaver#535]
Hi.
I can't find an option to rename table in sqlite and edit/add/delete triggers like for example in PostgreSQL...

**Comment by serge-rider** [comment]
DBeaver doesn't yet support advanced functions for SQLite.

**Comment by sprintel** [comment]
I would like to have an option to rename a field as well if it is possible. Sqlite does not support field rename so a temp table has to be created. An auto generated script to rename a field will be helpful.

**Comment by serge-rider** [comment]
Most likely table/column rename features will be added in SQLite extension. Although I can't say when exactly. We have too many feature requests including SQL Server extension.
Will see at that after 3.8 release.

**Comment by sprintel** [comment]
Thanks again Serge!

**Comment by serge-rider** [comment]
SQLite extension will be added in 4.0.
It will support:
- View native DDL for tables/views
- Triggers view
- Sequences
- Support of SQLite-specific data type system
- Table rename support

**Comment by sprintel** [comment]
Is field rename included in version 4.0? I only see table rename but not field rename.

**Comment by serge-rider** [comment]
SQLite doesn't support column rename. It can be done only by table recreate and data reimport.

**Comment by sprintel** [comment]
If it is not too much to ask, can you add a feature to generate automatically an sql to recreate the table and reimport data when someone wants to rename a field? It will definitely helpful for people who wants to rename a field (instead of writing the script from scratch).  Again, thank you for your great works!

**Comment by serge-rider** [comment]
This feature will be useful for all databases which do not support column rename.

But this feature is really controversial. Because it is dangerous - especially on production databases. It may fail in the middle and you may loose your data.

**Comment by sprintel** [comment]
I guess if it has to be done, it will dangerous regardless of the methods unless there is a safer way of renaming a column. Maybe you add a comment on the sql that there is a risk of losing data if the script is executed. Just my 2 cents...

**Comment by serge-rider** [comment]
If database supports column rename as atomic DDL operation then there is no risk of data loss.

Anyhow - create a feature request. This task should be tracked in a different issue.
I think it won't be too hard to implement.

**Comment by iambudi** [comment]
Any update about column editing for sqlite?
