### ISSUE TITLE
New template variable ${cursor} is not working as spected

### ISSUE THREAD

**Issue by marco-sanjuan** [serge-rider/dbeaver#536]
Hi

The new template variable ${cursor} is not working as spected,

I spect that it only put the caret on desired position, instead of open a inline block:

![image](https://cloud.githubusercontent.com/assets/4165141/16040828/672b077e-3232-11e6-9434-b1d8b8199cdd.png)

Thanks!

**Comment by carlosjrcabello** [comment]
Hi there, 

I've created one template to test templates. How did you trigger it in editor ?

Here I didn't use it to test :/

**Comment by marco-sanjuan** [comment]
I triggered with tab key, after write "sel".
This is my template:
![image](https://cloud.githubusercontent.com/assets/4165141/16041703/35d6ed00-3237-11e6-94ba-d61ef11da5f6.png)

**Comment by carlosjrcabello** [comment]
It's little bit different from Eclipse, so, I've tested here and I got this:
![image](https://cloud.githubusercontent.com/assets/637767/16042378/c28974d8-3210-11e6-8fa0-6cb30ed16bac.png)
Then, in editor triggering by `alias + Tab`:
![image](https://cloud.githubusercontent.com/assets/637767/16042429/fe931150-3210-11e6-80b1-ddee168cff00.png)
Seems OK for me,  at least as Eclipse `${cursor}` does.

**Comment by marco-sanjuan** [comment]
That's what I mean, is it possible to automatically clean focus of cursor variable? I really don't pretend to be a variable, only a position for caret.

**Comment by carlosjrcabello** [comment]
Uhmm, I got. We'll have to wait for @serge-rider to see if he can customize it, since it's a core eclipse resource.

**Comment by serge-rider** [comment]
Yes, it is a bug in templates processor.
Thanks for report.

**Comment by marco-sanjuan** [comment]
As fast as usually, great work!

Thanks Serge and Carlos.
