### ISSUE TITLE
Calculated columns with no alias cannot be ordered in Sql Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#537]
If I execute this sample query (in SQL Server)
```SQL
SELECT field, LEN(field) FROM TABLE
```

It's ok when I order the columns by clicking on the doble rows in the column header in the grid in the normal order, but if I click again (desc ordering) I get

```
Errore SQL [156] [S1000]: Incorrect syntax near the keyword 'DESC'.
  java.sql.SQLException: Incorrect syntax near the keyword 'DESC'.
```

Everithing works correctly if I add an alias:
```SQL
SELECT field, LEN(field) AS Length FROM TABLE
```

**Comment by serge-rider** [comment]
Thanks for report
