### ISSUE TITLE
[CLOB] is shown as string instead of value in SQL Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#538]
If I perform a select and ther's a CLOB in the row, I'll see `[CLOB]` as a string, even if I try to edit inline the value of the cell.

![image](https://cloud.githubusercontent.com/assets/14179578/16046965/8fed67da-324e-11e6-8cca-4bcca4780c42.png)

**Comment by serge-rider** [comment]
Can't reproduce edit. 
- What is your database?
- Check Error Log (you can open it in main menu Window) for any related errors

To see LOB values you can enable LOB caching (Preferences->Database->Result Sets->Binaries->Cache CLOB Values)

**Comment by gabriele-ricci-kyklos** [comment]
Driver version is 4.0, I'll try to get the latest version anyway. 
I can't find the log though, is it under Window main menu?

The problem is resolved anyway by enabling LOB caching

**Comment by serge-rider** [comment]
Window->Show view->Error Log (if it is not there then Other->General->Error Log)
