### ISSUE TITLE
Unable to add user via wizard for MySql - popup closes when key is pressed in user name field

### ISSUE THREAD

**Issue by macfarlanguage** [serge-rider/dbeaver#54]
To reproduce (on Version 3.5.3 against MySql 5.5):
 - As 'root',
 - Create a connection to a DB on a local MySql server, connect.
 - Expand folders below the DB in the tree view.
 - Right-click 'Users' folder in the tree view
 - Click 'Create New User'
 - Highlight the default text in the 'User Name' field
 - Type 'test'

Expected: User name can be changed to 'test',

Actual: Popup closes if text in 'User Name' field is changed. User not saved.

Workaround: Instead of attempting to modify user name directly; 
 - Assign password and privileges in the popup
 - Click 'View/Persist changes' 
 - Click 'Copy', 'Cancel'
 - Paste into an SQL editor window
 - Find/replace 'user' with '<desired user name>'
 - Correct statement order and execute SQL manually.

**Comment by serge-rider** [comment]
It is a known issue in 3.5.3 (you can't change name of any new metadata object).
Will be fixed in hotfix version 3.5.4 (release on the next week).
Thanks
