### ISSUE TITLE
DB2/zOS: Description shown instead of column name

### ISSUE THREAD

**Issue by Magublafix** [serge-rider/dbeaver#541]
Hi,

I'm using DBeaver to connect to DB2. When querying a Table I get the Fielddescriptions as column header instead of the column name. Is it possible to configure this behaviour somewhere?

![unbenannt](https://cloud.githubusercontent.com/assets/4953529/16106937/12159070-3399-11e6-9729-78e04a2668cf.PNG)

thx,
Gerald

**Comment by serge-rider** [comment]
That's weird.
What is your DB2 database/driver version?

Does it happen only for custom query results or for table data too?

DBeaver shows column "label" in the grid header. By default label==name. In customn queries label can be overridden (e.g. `SELECT ColName as ColLabel FROM TableName` - DBeaver will show ColLabel).

**Comment by Magublafix** [comment]
Hi,

Sorry for my late reply, I missed the notification mail.

I'm not sure where I can find the version information !? I just got three .jar files 
![2016-06-23 14_10_47-jdbc-db2 treiber](https://cloud.githubusercontent.com/assets/4953529/16302627/80aa7fa6-394c-11e6-9797-42ec7db5b906.png)

It is the same for table data not only custom queries:
![2016-06-23 14_13_34-dbeaver - general - alord](https://cloud.githubusercontent.com/assets/4953529/16302684/c60e4910-394c-11e6-81d5-f64b0dfd31fd.png)


regards,
Gerald

**Comment by serge-rider** [comment]
You can see driver/database versions in Properties view (you can open it in main menu Window->Show view).

DB2 for z/OS has a tricky driver settings.
Try to change meta model in driver settings (open connection properties->Edit Driver Settings->Adv. Parameters). Set "Meta model type" to "standard".
![indexed-model-settings](https://cloud.githubusercontent.com/assets/6398845/16303998/28ab35ba-395c-11e6-90ac-da29391c9a83.png)

**Comment by Magublafix** [comment]
Hi,

Driver-Version: Driver	IBM DB2 JDBC Universal Driver Architecture [3.66.46]

I tried that but didn't change anything. I'm also not sure if it has something to do with the driver, because the column screen shows everything correctly:

![2016-06-23 15_21_54-dbeaver - general - aggeschaeft_hist](https://cloud.githubusercontent.com/assets/4953529/16304602/6d0d8bf0-3956-11e6-82f4-3605019c0dc5.png)
![2016-06-23 15_22_16-dbeaver - general - aggeschaeft_hist](https://cloud.githubusercontent.com/assets/4953529/16304607/70fa167a-3956-11e6-9e75-adf97757b2e3.png)

But it seems that for Tables with type Alias it works correctly but for normal tables it shows the description.



regards,
Gerald

**Comment by serge-rider** [comment]
That's odd. A few questions:

- Are column names correct when you execute a custom SQL query?
- Are column names correct when you browse table data?
- Could you create a new driver (using your jars). Because existing DB2 z/OS driver has a few preconfigured parameters which may affect column names.

**Comment by Magublafix** [comment]
Hi,

Are you talking about the properties view or the labels in the data view?
The Labels are wrong everywhere...

How do i create a new driver, I can only edit the driver settings....

**Comment by serge-rider** [comment]
I mean labels in results view. Are they wrong everywhere? Including custom queries?

To create a new driver:
- Cclick on Driver Manager icon (or main menu Database->Driver Manager).
- Click "New".
- Add your jars ("Add File").
- Set "Class Name", "URL Template" and "Default Port" - the same as in existing DB2 z/OS driver.
- Enter any value in "Driver Name".
- Click Ok.

Now you can create connections based on this new driver.

**Comment by Magublafix** [comment]
Hi,

Yes in result view they are wrong everywhere. Only for Alias Tables they are fine.

The custom driver didn't fix the problem

thx,
Gerald

**Comment by essam002002** [comment]
@Magublafix 
To fix how column headers behave, you should go to driver properties and clear the value for "describe option" property. This will fix your problem.

<img width="576" alt="temp" src="https://cloud.githubusercontent.com/assets/14147087/20657279/c90a6078-b588-11e6-948e-014da331f283.png">

**Comment by serge-rider** [comment]
Thanks for information.
So it seems to be a configuration issue, not a DBeaver bug.

**Comment by Magublafix** [comment]
Unfortunately I don't have such a configuration:

![unbenannt](https://cloud.githubusercontent.com/assets/4953529/20670180/115651c2-b578-11e6-9bca-cab0ce654ae9.PNG)

**Comment by serge-rider** [comment]
I think this depends on driver and (probably) default server settings.
@Magublafix could you say what driver do you use?

**Comment by Magublafix** [comment]
Hi @serge-rider 

I'm using the IBM jdbc driver
http://www-01.ibm.com/support/docview.wss?uid=swg21363866

![unbenannt](https://cloud.githubusercontent.com/assets/4953529/20671188/a07955a8-b57c-11e6-8e9b-16cce3c7466f.PNG)

**Comment by serge-rider** [comment]
@essam002002, could you say what is your driver? At least is it IBM?

**Comment by essam002002** [comment]
The driver I'm using is IBM DB2 ISeries/AS 400

**Comment by Magublafix** [comment]
Is there any update on this case.

Maybe it is zOS related. @essam002002 is using iSeries.

regards,
Gerald

**Comment by serge-rider** [comment]
No, there are no any news.
I can't reproduce that so I can't fix that.

Generally this seems to be a JDBC driver related issue. 
If anybody have any idea how to retrieve column name/description correctly for these drivers - please tell.

**Comment by Magublafix** [comment]
Hi @serge-rider,
I finally found the solution myself.
There is a jdbc-flag useJDBC4ColumnNameAndLabelSemantics, which hast to be set to 1.

**Comment by serge-rider** [comment]
Thanks for info

**Comment by spinjector** [comment]
Would someone advise where I use the setting useJDBC4ColumnNameAndLabelSemantics as mentioned above..? I'm also missing the column labels, and I would like to try it. But in my case I have the same database that was migrated to a new server. I still have the connection to the old server, and the column labels are ok from there. But on the new server they do not appear in the column information tab [tablename] > View Columns > Description column, nor in the pop-up "tool tip" bubbles when I hover my mouse over the name of a column.

**Comment by Magublafix** [comment]
Hi @spinjector,
You can set this as a jdbc-flag. Just do a right click on the connection ->Edit Connection->Driver Properties. There you can add the flag like in the screenshot:

**Comment by spinjector** [comment]
Ahhh, thank you..!!
