### ISSUE TITLE
Editing connection settings should also offer or warn to reconnect

### ISSUE THREAD

**Issue by andrei-dragusanu** [serge-rider/dbeaver#542]
DBeaver should offer to reconnect to an active connection when changin the connection settings, in order to apply them:

1. Connect to a database;
2. Right click connection -> **Edit Connection**;
3. Change user name;
4. Click OK;

The current connection remains connected to the old user name, an this is not very obvious to the user. It would be nice to at least display some message/warning that a reconnection is required, or even offer to do this on the spot. Thanks!

**Comment by serge-rider** [comment]
Agreed
