### ISSUE TITLE
SQL generation of CLOB is wrong on oracle

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#547]
If I generate an insert statement of a row with a CLOB value, I get `[CLOB]` as the value of that cell in the generated script. The script is correctly generated only when I double-click the cell in the grid in order to show the value

**Comment by serge-rider** [comment]
By default LOB values aren't read along with regular column values (because they can be huge).
You always can get correct SQL by using "Export ResultSet" function.

Or you can enable LOBs caching (Preferences->Database->Result Sets->Binaries->Cache CLOB Values).

**Comment by gabriele-ricci-kyklos** [comment]
It's ok not to read LOBs along with the rest of the column, but if I have to perform an insert statement in another database, I should be able to copy and paste, also with a LOB
