### ISSUE TITLE
Propose a prefilled list of connections in readonly mode

### ISSUE THREAD

**Issue by lliegeois** [serge-rider/dbeaver#548]
We would like to make DBeaver available for "end users". Those end users are not able to create nor edit their current connection settings (especially user/password)

Such functionnality could be activated in general settings by a "restrict connection edition to administrative mode" and entering to an administrative mode could be by entering a given password.

**Comment by serge-rider** [comment]
I wouldn't do a sophisticated UI for master password management or something.

I see a simple solution: mark "locked" connection (in .dbeaver-sata-sources.xml) with attribute "unlockPasswordHash" (MD5 hash of master password). Connection with this attribute will be locked (and can be unlocked with master password).

**Comment by lliegeois** [comment]
Hello serge, that's completly fine for me and your proposal match the requirement.

**Comment by serge-rider** [comment]
Read this: https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Connections

**Comment by lliegeois** [comment]
Many thanks ! tested and it works as expected. Congratulations !
