### ISSUE TITLE
 the application does not open properly

### ISSUE THREAD

**Issue by ennovatp** [serge-rider/dbeaver#550]
I'm trying to open the application and not charge anything. While it is opened, the screen goes as disabled. Ubuntu 16.04 and have already had the version installed, but at any moment stopped working.
I have installed previous versions, the current version and no work.
Please help.
Thank you

**Comment by serge-rider** [comment]
Please check error logs (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by carlosjrcabello** [comment]
Hi @ennovatp ,

Had you tried with EA versions?

http://dbeaver.jkiss.org/files/ea/

I remember when I used debian and ubuntu-based distros, installing DBeaver through .deb file, sometimes I got dependencies errors from apt-get...for those cases, I always installed Oracle JVM removing OpenJDK.

On slow PCs, sometimes Eclipse freezes himself while it not full initialized.
