### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by searli** [serge-rider/dbeaver#552]
Hi there,
First off - I love **dbeaver**, it is a fantastic tool and I love the fact that I can use the same tool for MySQL and NoSQL databases - brilliant!

I have a question with regards to ARM support - I am using a Chromebook with chroot Linux environment for development and would love to be able to use **dbeaver** on that; has anybody been able to run **dbeaver** on an arm device (chromebook with chroot or raspberry pie)?

**Comment by serge-rider** [comment]
At the moment Eclipse platform (Mars, 4.5) doesn't support ARM builds out of the box.
Check this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=406749

Although some guys have successful experience and run RCP apps on ARM (https://resheim.net/2013/05/running-eclipse-rcp-applications-on.html) but it requires pretty much effort.
Hopefully ARM binaries will be added in the next Eclipse/SWT versions (4.6. should be released soon). Once they will be there DBeaver will support ARM platforms as well. I'll just need to add an extra platform in release distributions.

**Comment by searli** [comment]
Strange, I am running Eclipse on my Asus Flip with Ubuntu and it seems to work fine;

**Comment by serge-rider** [comment]
Interesting. 
What Eclipse version do you have? 
Where did you download it?

**Comment by searli** [comment]
I am running 
Ubuntu 16.04 LTS, Xenial on a ARMv7 Rockchip Processor (Asus Chromebook Flip) in a Chromeos chroot environment;
The Eclipse Platform version is Version: 3.8.1, Build id: debbuild;
I installed it from the Ubuntu ARM repositories (just using apt-get) - I guess this version is too old?

**Comment by serge-rider** [comment]
Yeah, Eclipse 3.x is not officially supported since 2012. For some reason some Linux repositories stuck with 3.8.1 version (the latest 3.x version). 

Anyhow, I assume that Eclipse ARM was built for this particular repository but it is not available on the eclipse.org web site. And it is not available for other developers.

**Comment by serge-rider** [comment]
ARM support was added in version 21
