### ISSUE TITLE
Auto-maintenance of DB connections - Lifesaver feature request

### ISSUE THREAD

**Issue by amalizzio** [serge-rider/dbeaver#554]
Hi Dbeaver team. I love the product, it is my favorite place to live at work, and i've tried all of them.The feature balance is excellent.

I work in an environment where i have about 10-15 different applications with 3 schemas each, and they move around frequently (different servers, ports...you name it), and regular password changes.

I spend a massive amount of time (and frustration) adding and removing new db connections.

Considering all i need to create a new connection is 3 attributes per schema:

>**Connection Name|JDBC URL|username|password**
>DEV17_SCHEMA1|jdbc:oracle:thin:`@`app1:1521:APPSID

I would like the following feature to make my life easier (and hopefully others in the same situation):

1. Easist, DB  db connections upload from file, I can have a **CSV/XLS** with the 4 aforementioned attributes, for each of the 45 schemas. Result of import is a list of connections added/removed/updated, and the result of a test connection with a pretty icon.
2. Same as a above but I will host the connection config file on HTTP, and DBeaver will listen everytime i open the add or perform a **[refresh connections]** command...I would expect a menu item called **[http path for csv connection attributes file]** where i put the link.

Regards

**Comment by serge-rider** [comment]
I can make some kind of connections importer. In fact there are already two such importers - from SQL Squirrel and DBVisualizer configs - you can access them from menu File->Import (although they might be a little outdated).
But I don't want to make too many different importers.

Proposal: import connections from some predefined XML format. E.g.:
```xml
<connections>
  <connection name="Name1" url="jdbc-url" user="user" password="password"/>
  ...
  <connection name="NameX" url="jdbc-url" user="user" password="password"/>
</connections>
```
CSV format is also acceptable but is is less flexible. And you can always convert your CSV into XML with some simple regexp.
WDYT?

**Comment by serge-rider** [comment]
Read this: https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Connections
