### ISSUE TITLE
wrong columns info when export or import from PostgreSQL table

### ISSUE THREAD

**Issue by witwall** [serge-rider/dbeaver#556]
<img width="524" alt="screen shot 2016-06-25 at 4 07 48 pm" src="https://cloud.githubusercontent.com/assets/3222056/16355617/189f6a08-3aef-11e6-81be-0a93493d855b.png">

in this screenshot, only the last column is real(I know I can skip others I do not want)

**Comment by serge-rider** [comment]
Thanks for report
