### ISSUE TITLE
Cannot find content.xml from update site using RDz eclipse

### ISSUE THREAD

**Issue by alexardz** [serge-rider/dbeaver#557]
When updating DBeaver on RDz eclipse using "http://dbeaver.jkiss.org/update/latest/" the system report that no "content.xml" was found.
I've tried also to download a zip file but with it also didn't work .
Nenhum repositório localizado em jar:file:/C:/dbeaver/dbeaver-ce-3.6.10-win32.win32.x86_64.zip!/.
Can you give me any tip of what to do?
Thanks.

**Comment by serge-rider** [comment]
I'm not sure I'm fully understand the problem.
- What Eclipse version do you have (what is RDz?)
- How do you perform install (from Eclipse marketplace, using "Install New Software" action, somehow else?
- How is this related with standalone version setup (dbeaver-ce-3.6.10-win32.win32.x86_64.zip is a standalone version archive)

**Comment by alexardz** [comment]
RDz is a eclipse based software, but it is an Eclipse anyway. I've been using this Eclipse for 3 years long using DBeaver.

Q1. What Eclipse version do you have (what is RDz?) 
A1. Eclipse version: 4.2.1.v20130118-173121-9MF7GHYdG0B5kx4E_SkfZV-1mNjVATf67ZAb7
 Build ID: M20130204-1200

Q2. How do you perform install (from Eclipse marketplace, using "Install New Software" action, somehow else?
A2. The path is Help/"Install New Software"

Q3. How is this related with standalone version setup (dbeaver-ce-3.6.10-win32.win32.x86_64.zip is a standalone version archive)
A3. I've tried to download a zip file, but i didn't know that (dbeaver-ce-3.6.10-win32.win32.x86_64.zip) was a standalone version. Where do I find the plug-in version link? 

Thanks

**Comment by serge-rider** [comment]
Eclipse 4.2 is a bit outdated but DBeaver has to work with it.
At least plain Eclipse 4.2.2 works fine.

Just use Install New Software.
I've added content.xml file (in fact it is not required in recent E4 versions and 4.2 also works without it - but maybe RDz has some its own issues).
Try to install DBeaver one more time (from http://dbeaver.jkiss.org/update/latest/)

**Comment by alexardz** [comment]
Now I manage to install DBeaver 3.7.0 from update site.
Thanks!
