### ISSUE TITLE
double quotes are removed automatically 

### ISSUE THREAD

**Issue by witwall** [serge-rider/dbeaver#558]
When I copy only  a field with double quotes, the double quotes will be removed automatically, but as you know, PostgreSQL needs double quotes if the field begins with upper case.

for example, **"Product_id"** after copy and paste, will only **Product_id** left.
but if I copy and paste **count(distinct "Product_ID")**, the double quotes will be remained.

**Comment by serge-rider** [comment]
It is not a bug, it is a feature (DBeaver extract SQL queries from source code).
Workarounds:
- Press ctrl+z after paste (it will revert source code conversion)
- Disable source code extraction at all:
![sql-editor-extract-from-source](https://cloud.githubusercontent.com/assets/6398845/16408516/da4b3f90-3d21-11e6-9eb3-87153c4a44e0.png)

**Comment by carlosjrcabello** [comment]
Hi there,

I didn't know this option, I did some tests and, it's so useful copying / paste from statements as concatenated `String` from Eclipse for instance. So, copying this String statement:
![image](https://cloud.githubusercontent.com/assets/637767/16413449/6ad75ae0-3d08-11e6-921e-3486d0d6c4d0.png)

Then, pasting it, I get extracted SQL in one line only...What do you think if you add SQL Format for extracted SQL?

**Comment by serge-rider** [comment]
Extracted SQL will look exactly as in your app program. 
For instance if you'd use \n \t characters in your source code then they will be converted into line feeds/tabs.
I don't think we need implicit SQL formatting here. You can always do it with ctrl+alt+f.

**Comment by serge-rider** [comment]
But maybe I should leave line feeds even if they are outside of quotes..

**Comment by carlosjrcabello** [comment]
Uhmmm, yep, it's make sense.
