### ISSUE TITLE
MongoDB - JSON view

### ISSUE THREAD

**Issue by NullpointerForever** [serge-rider/dbeaver#559]
Hi,

If I double click on my collection, then I can change result view to Grid, Text, Json. But Json view is not available when I execute my custom script like:
```
db.getCollection('log').find().limit(5);
```
or
```
db.getCollection('log').find().limit(5).toArray();
```
Is there any way to view as JSON without executing SQL?

Regards

**Comment by serge-rider** [comment]
Thanks for report
