### ISSUE TITLE
Saved scripts name ordering and feature request for scripts list.

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#56]
Its littlebit annoying that the autonamed Script-XX are ordered badly on the Projects panel. On this image the problem seems not too big, but in my work computer it looks very very bad because I have more than 400 script saved :) This scripts are used for saving states so I can look back what I have done. Can you make the ordering better?

I suggest tree possible collumn include: Datetime, Notice (self notice for the script), First line preview.
Also it will be nice if I can search in the saved scripts content.

![Script ordering](http://a42server.net/static/dbeaver/screenshot004.png)
![Script ordering](http://a42server.net/static/dbeaver/screenshot005.png)

**Comment by serge-rider** [comment]
You already can order scripts by timestamp (right click on table header and add "Modified" column).
I think that adding a column with first line preview is a good idea. Will probably add it in one of next versions.

**Comment by serge-rider** [comment]
Script management redesign will be tracked in #70.
