### ISSUE TITLE
Add IF and RENAME to the list of keywords

### ISSUE THREAD

**Issue by lukaseder** [serge-rider/dbeaver#564]
There are probably more. Should I report them as individual issues when I encounter them, or is there a file where I can provide PRs?

A typical example in this case would be:

```sql
ALTER SEQUENCE if EXISTS s rename TO t;
```

In this statement, DBeaver doesn't recognise the keywords `IF` and `RENAME`

**Comment by serge-rider** [comment]
Ok. BTW what's your database?

And yes, it is better to create individual issues for each problem. Otherwise it is very hard to track them.

**Comment by lukaseder** [comment]
It was HSQLDB in this case

**Comment by lukaseder** [comment]
Excellent, thanks. I can now also see where that's done, so in the future, I'll submit a PR directly.
