### ISSUE TITLE
3.7: Order/Filter > Clipboard usability issue

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#567]
Hi,

The feature that allows you to right click a column > order/filter > from clipboard is now tucked away in "column_name = .." > clipboard > ok, which is several more clicks. I can understand that the contextual menu can get too long, but could we get a setting to keep it in the menu instead of in the dialog ?

**Comment by serge-rider** [comment]
Ok, I'll just bring it back.
Apparently many people used this feature. Although context menu is a bit bigger than I hoped it will - but I can't make a better UI solution. Making extra config for it is too non-obvious.
