### ISSUE TITLE
Oracle DBMS_OUTPUT.PUT_LINE function not working

### ISSUE THREAD

**Issue by CaptainBlasteroid** [serge-rider/dbeaver#568]
Hi, 
When I want to retrieve the underlying SQL of a view in Oracle, I would normally run the following SQL in TOAD:

DECLARE my_var LONG;
BEGIN 
	FOR x IN (
				SELECT DBMS_METADATA.GET_DDL( 'VIEW', 'VIEW_NAME', 'SCHEMA' ) x
				  FROM DUAL
			 )  
	LOOP my_var := DBMS_LOB.SUBSTR( x.X, 32000, 1 );
	END LOOP;

	DBMS_OUTPUT.PUT_LINE(my_var);
END;

In TOAD, the text that is stored in the my_var variable is then written to the Output tab. The SQL above runs without error, however the text in my_var isn't being written to the Output tab. 

Any ideas?

Thanks as always!

**Comment by serge-rider** [comment]
This is a bug in DBeaver, it fails when output lines are too long.
Thanks for report.
