### ISSUE TITLE
Please put back the refresh (F5) behaviour.

### ISSUE THREAD

**Issue by syedhassanshah** [serge-rider/dbeaver#569]
Currently the refresh short cut (F5) resets the filters and sorts, which is not what refresh should do. It has become annoying now so I have to re-filter and re-sort on each second refresh. All that is needed from an refresh behavior is to basically re-perform the existing action so that an updated result can be observed.

Or is there a way to change this from settings?

**Comment by serge-rider** [comment]
It's a bug. Thanks for report.
