### ISSUE TITLE
Connection Settings graphical corruption

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#57]
Under the database Edit Connection menu, graphical corruption occurs when repeatedly cycling through 'Connection Settings', 'Driver properties', 'Network', 'Shell Commands' by clicking on each one in succession. 

![image](https://cloud.githubusercontent.com/assets/1073841/11159622/839888e2-8a2f-11e5-8afc-eade7639c30a.png)
![image](https://cloud.githubusercontent.com/assets/1073841/11159624/8a0b9c32-8a2f-11e5-9230-6ba31d7404e6.png)
![image](https://cloud.githubusercontent.com/assets/1073841/11159627/8f311e26-8a2f-11e5-9eae-4001bbd8c3c1.png)

**Comment by codebling** [comment]
This is a Windows 7 x64 machine

**Comment by serge-rider** [comment]
It is a bug in MySQL connection page.
Thanks for report!
