### ISSUE TITLE
KST Timezone not supported

### ISSUE THREAD

**Issue by kaniblu** [serge-rider/dbeaver#573]
If the database server has KST (Korean Standard Time) timezone, it will complain that the timezone is unrecognized, despite the fact that the timezone is [well-established](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) and is used by more than 50 million people from South Korea. KST is technically the same as JST, so I can just workaround it by manually setting serverTimezone to JST, but it is quite annoying to do that for every server connection. And plus, it might deter some Korean friends from using this wonderful tool.
![image](https://cloud.githubusercontent.com/assets/938822/16575827/1bdf2ac6-42c6-11e6-80d1-b5953457ddaf.png)

**Comment by serge-rider** [comment]
I assume that you are using MySQL.
It is a bug in MySQL driver 6.x+.
There are two workarounds:
- Use 5.x version:
- Set serverTmezone property explicitly in connection settings (driver properties tab)

![maven-driver-version](https://cloud.githubusercontent.com/assets/6398845/16576218/5ff01b92-4296-11e6-8c54-0d3cba78ef19.png)

**Comment by nhs0912** [comment]
님 저도 라즈베리에다가 탐캣으로 웹 배포후 mysql 기능이 있는것은 KST 라는 것을 인식 못해서 오류가 나네요 ㅠㅠㅠ 혹시 이거 해결방법 하셨으면 알려주실수 있나요?
nhs0912@nate.com 제 메일 주소입니다 ㅠㅠㅠ 이것 떔에 엄청 고생하고 있어요 ㅠㅠㅠ

**Comment by mnezmah** [comment]
For DBeaver:
right-click on connection - edit connection.
Under connection settings set 'Server time zone' to your zone.Click OK
