### ISSUE TITLE
MySQL 5.7 using ALTER USER instead PASSWORD()

### ISSUE THREAD

**Issue by gemina** [serge-rider/dbeaver#577]
With dbeaver 3.7.0, I getting this message when I try to update a MySQL user:

> SQL Error [1054] [42S22]: Unknown column 'Password' in 'field list'

Since MySQL 5.7, the user table update was deprecated and ALTER USER introduced.

https://dev.mysql.com/doc/refman/5.7/en/alter-user.html

**Comment by serge-rider** [comment]
For now I'll just fix user update syntax. 
Thanks for report.
