### ISSUE TITLE
Cannot server-side sort with columns directly

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#578]
Hi,

Currently it's not possible to sort results server-side by clicking the up/down arrow next to the name of a column in the results view, this refreshes the results. For it to work it is needed to open the Order/Filter dialog and choose sorting there.
Maybe related to #569

**Comment by serge-rider** [comment]
Yes, it is the same issue as in #569. And it is already fixed.
Thanks for report anyway.
