### ISSUE TITLE
Can't put bookmark in bookmark folder

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#579]
Hello.

I would like to have an option to organize bookmarks. I tried the following:

1. Right click folder 'Bookmarks' 
2. Select 'Create a new folder'
3. I can't put anything in this folder via Drag&Drop

I also tried 1. then 'Create new Bookmark folder' but the following error appears:

    org.jkiss.dbeaver.DBException: Can't detect container for 'Bookmarks'

As you can see on the following screenshot, folder DBJAFIN is empty which is created using 1-2.
![image](https://cloud.githubusercontent.com/assets/85767/16619941/b983e044-4390-11e6-9426-e86ea4663a4a.png)

**Comment by serge-rider** [comment]
Can't reproduce that. What DBeaver version do you have?
There were a few fixes in Project Explorer view in 3.7.

**Comment by majkinetor** [comment]
3.6.9 using https://chocolatey.org/packages/dbeaver

Will try 3.7

**Comment by majkinetor** [comment]
No, it doesn't work with 3.7 also. The menu option 'Create new Bookmark folder' is also gone now.

I suggest to add bookmark folder in the CTRL + D menu (like browsers usually have) or that you at least support path syntax - for example if I create bookmark `project1\category\tableX` it would create `project1` folder and then `category` bookmark folder then add `tableX` in it.

![image](https://s32.postimg.org/vwk3ebr11/2016_07_08_13_59_13.gif)

**Comment by serge-rider** [comment]
Ok, I reproduced that.
I though you mean "drag-and-drop doesn't work at all". But it doesn't work only in case of dragging existing bookmark to another folder.

**Comment by majkinetor** [comment]
Please consider also my suggestions about adding bookmark. Having a last set up folder in the dialog is nice because you usually add to the same bookmark folder in the same session.

**Comment by serge-rider** [comment]
Ok

**Comment by majkinetor** [comment]
I confirm it works now.

**Minor suggestion**: keep the selection in `CTRL + D` dialog. Currently selection always returns at the folder 'Bookmarks' no matter what you selected in previous usage.

**Comment by serge-rider** [comment]
Ok, that makes sense.
