### ISSUE TITLE
Script run Cancel freeze, unable to run multiple scripts

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#58]
Often happens with me if I run some script or select in Firebird and I hit cancel it wont stop or it stops but the loader locked and I can not close the application. Often I kill the Java to close the application, because the close never ending. This happening not any case but most of the cases, also when this cancel freezed or some long script running I can not run an other script in a new script tab.

**Comment by adamos42** [comment]
For reproduce: Create a table with near 1million record with some dummy not indexed field and try search in it. After a few second try cancel it, it wont stop (least in visual) and you can not close the application either. It happending when you execute long procedures or selecting 10-15k rows. I have some log somewhere to upload it?

**Comment by serge-rider** [comment]
Jaybird JDBC driver has a bit unusual behavior. It blocks during resultset obtain operation (usually driver blocks during statement execution).
Anyhow I'll add a workaround in DBeaver.
Thanks for report.
