### ISSUE TITLE
Feature request: Named filters

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#580]
I have few databases that several projects use and each have its own tables it handles. I want to be able to quickly filter out tables and/or other objects using named sets so that I can only see relevant stuff for that particular project using the database in question.

Currently, to do this I have to create separate project for each such sub-project and set filter under General Connection Settings OR create bookmarks and organize them per project (I lose regex here and its a manual task not suitable for large databases).

It would be great if we could have named filters that could be visible in the project tree under category 'Filters'. This would allow me to quickly focus my efforts on particular database parts without noise.

**Comment by serge-rider** [comment]
This is an old task and UI was significantly changed since then (e.g. now we have quick filters in the top).
If this is still makes sense - please clarify it a bit. 
- Is this about filters on some particular schemas or global connection filters?
- How do you see this in UI?

**Comment by majkinetor** [comment]
Current behavior isn't related to this as table filtering is ad-hoc in nature and allows single query while this is permanent filter mechanism allowing for multiple queries.

i.e. named filter _customers_ could include: orders*, order_details*, products*  tables which can resolve into 10 or more tables.

This filter is on particular shcema and should be part of current table filters UI (just adding save/delete button and combobox to select saved filter is enough for this).

This allows one to concentrate on specific parts of the database without accidentally messing up other unrelevant parts. ORM frameworks works this way, by exposing only relevant set of table in the code of particular module. 

More full blown option would allow filtering out/in other parts of database such as stored procedures, but it would probably require more UI redesign.

**Comment by serge-rider** [comment]
Ok, this sounds reasonable.
In 4.1.2 we'll add the following:
![default](https://user-images.githubusercontent.com/6398845/29004924-a23b2fd4-7ad8-11e7-83d5-9f404e6c2b6e.png)

Further filters improvements should be tracked in separate tickets.

**Comment by majkinetor** [comment]
Awesome. Thanks a lot.
