### ISSUE TITLE
Mouse wheel isn't working?

### ISSUE THREAD

**Issue by CaptainBlasteroid** [serge-rider/dbeaver#581]
Hi Serge, 

Has anyone had any issues with their mouse wheel not scrolling in dBeaver? I started experiencing the issue after killing dBeaver due to high memory consumption. This hasn't been an issue historically. I've even uninstalled/reinstalled the application, but that didn't seem to fix it. I can scroll in other windows without issue, but dBeaver is the only application that I'm having this issue with.

Any thoughts?

Cory

**Comment by CaptainBlasteroid** [comment]
No idea why, but it started working again.

**Comment by serge-rider** [comment]
Seems to be some kind of glitch.
