### ISSUE TITLE
Search in all fields with type

### ISSUE THREAD

**Issue by Jeetah** [serge-rider/dbeaver#584]
The Full Text Search feature is great! Perhaps the next step could be to search in all fields of a specific type. 
Use Case (I think pretty common): UUID fields all over the DB - I want to search with e.g. '0089b141-52cd-4816-a2e2-ee8ea84e8c66' and field tpye 'UUID' (Postgres) to find the specific object with it...

**Comment by serge-rider** [comment]
I think I can add search in UUID columns easily. UUIDs are pretty standard nowadays.
Using any custom types is much more complicated. All databases have different rules for type<->string conversion.
