### ISSUE TITLE
Copy paste databae objects (tables, views, etc)

### ISSUE THREAD

**Issue by syedhassanshah** [serge-rider/dbeaver#585]
DBeaver has the **Export Data** feature which requires a few steps until finally the table is copied into another database. It would be great if these steps could be automated into a simpler copy paste feature. 

I am not sure how difficult or easy it is to implement a copy paste feature where tables/views/function e.t.c can be copied between different databases with ease, but I am sure it will be appreciate big time.

**Comment by serge-rider** [comment]
Next version (3.7.4) will support of MySQL tables structure copy/paste. 
In beta-testing mode for now.

**Comment by serge-rider** [comment]
3.7.6 supports copy/paste of any table into MySQL table (only metadata).

**Comment by serge-rider** [comment]
Closing as too general task.
Tables copy works for MySQL and (partially for PG). All further improvements should be tracked as separate tasks.
