### ISSUE TITLE
The cipher 'aes256-cbc' is required, but it is not available

### ISSUE THREAD

**Issue by syedhassanshah** [serge-rider/dbeaver#586]
I have already once reported about this issue (in http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1887) where the existing JRE policy file does not contain support for **cipher 'aes256-cbc'** so as a fix we have to download and replace the policy file which does contain the mentioned cipher.

**Comment by serge-rider** [comment]
That makes sense. I'll patch JRE shipped with Windows installer.
Thanks for reminder.

**Comment by filippopirrobetbright** [comment]
Hi Serge, I have downloaded the installer today and it does not work with tunnel

Can't initialize tunnel
  Cannot establish tunnel
    com.jcraft.jsch.JSchException: The cipher 'aes256-cbc' is required, but it is not available.

**Comment by serge-rider** [comment]
Make sure that JRE shipped with installer is actually used (main menu Window->Installation Information->Configuration->property java.home ).

**Comment by filippopirrobetbright** [comment]
Hi Serge,
Thanks for the reply.
Actually I have fixed it adding the right local_policy.jar in the security folder in my JRE.
I have another issue with the tunnelling, I could ask for some help later on.

Cheers
Filippo

**Comment by geek085** [comment]
I faced the same issue when trying to connect to a Cassandra DB using an encrypted Putty private key (.ppk) for SSH tunneling. 
Got it resolved by converting the putty private key (.ppk) to an OpenSSH one (this can be done by loading the putty private key in "Puttygen" & then converting it to OpenSSH key). Refer [stackoverflow.com/questions/17989883/the-cipher-aes256-cbc-is-required-but-it-is-not-available](url) for more details.
