### ISSUE TITLE
The ability to import connections from SQL Developer via xml

### ISSUE THREAD

**Issue by rockerlkj** [serge-rider/dbeaver#588]
I'm migrating to dbeaver from SQL developer, and it would be nice to be able to migrate all my connections over without having to write them in manually. I understand that passwords may be an issue, but if you could get the connection details in and then add the passwords in manually later, it would save a lot of time.

**Comment by serge-rider** [comment]
Useful feature. Also was noticed here: http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=3001&p=6420

**Comment by serge-rider** [comment]
Basic connections importer will be added in 3.7.2,
However it won't import passwords.

If anybody aware of that then he/she can investigate this issue (http://stackoverflow.com/questions/1032721/does-anybody-know-what-encrypting-technique-is-jdeveloper-sql-developer-using-to/3109774#3109774) and make a pull request with password decrypter.

**Comment by s-kocher** [comment]
To complete that topic : SQL Developer has different password cipherings systems depending of the version.
- v3.x : passwords in connections.xml only
- v4 to v18.1 :  passwords in connections.xml + use of db.system.id in product-preferences.xml
- \>=v18.3 : passwords in connections.json + use of db.system.id in product-preferences.xml

Example of values :
- v3 password like 054D4844D8549C0DB78EE1A98FE4E085B8A484D20A81F7DCF8
- v4 password like Shz0tQgqkuAfLy65s21gTVD7wacDYwG6
- \>= v19.2 password like LUA63VW21TqaHNJSvKF6DI8zv1/dvXzBhyMPVN8lAws=
- db.system.id like 7d97189a-4e22-4061-bc07-35b9d2b39f3c

This github project provides python code handling the 3 versions : https://github.com/maaaaz/sqldeveloperpassworddecryptor

Actually DBeaver import wizard for SQL Developers directly shows found connexions in the SQL Developer configuration. it will be a nice feature to provide the ability to browser manually any SQL Developer exported file (connections.xml / connections.json) without having first to have a working installation of SQL Developer with the configuration at the expected place.
