### ISSUE TITLE
Error creating new Table Under oracle 11g

### ISSUE THREAD

**Issue by babbomaria** [serge-rider/dbeaver#59]
Hi,
In version 3.5.3 
1)I have created a table 
2)I exit and press and don't persist table
3)The table is keept in left tree menu under table
4)When I try to recrate the table the table in tree is refreshd an pop up an error .

![2015-11-16_081038](https://cloud.githubusercontent.com/assets/344999/11176060/8f11f544-8c39-11e5-9abe-d1cf01cbd27d.jpg)

My solution is to refresh tree F5 after each operation- I think some refresh is missing after some operation that upgrade the left tree

When i create a

**Comment by serge-rider** [comment]
Could you check that this issue remains in 3.5.4?

**Comment by babbomaria** [comment]
Well done man !
