### ISSUE TITLE
After updating mysql driver,got error The server time zone 'fsf' is unrecognized or represent more than one time zone

### ISSUE THREAD

**Issue by AlexLuya** [serge-rider/dbeaver#590]
Details like this:
The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
  com.mysql.cj.core.exceptions.InvalidConnectionAttributeException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

**Comment by serge-rider** [comment]
Duplicate of #573
