### ISSUE TITLE
IntelliSense does not work with schema only named with numbers

### ISSUE THREAD

**Issue by andrecesaribr** [serge-rider/dbeaver#591]
Hello, intellisense does not display the list of tables when I'm working with schemas named with numbers only, eg '21070847000112', since for schemas named with letters work, eg 'public'.

I remember that it worked in previous versions.

I'm currently using the latest version 3.7.1 on Windows 8.1 x64.

Sorry for my poor english, I'm Brazilian :) thanks.

**Comment by serge-rider** [comment]
I think this is because such schema names are quoted. If so then this is the same problem as in #594 .

**Comment by andrecesaribr** [comment]
Hello, now updated to version 3.7.2 and the problem was corrected, thank you.
