### ISSUE TITLE
keywords and table names quoted in DBeaver 3.7.1

### ISSUE THREAD

**Issue by frankhsimon** [serge-rider/dbeaver#594]
Hello,
Problem with quoted tablenames/columnnames by keywords.
 
For example:
working with INFORMIX12 database.
a table named "module" caused an sql-error when opening by double-click.
Also referenced tables by pressing F7 e.g. column "state" will be shown as "state" not the value of it (unless quotes will be deleted in "define description/custom criteria") .
 
Is there a possibility to configure what keywords are quoted or switch off this quoting?
 
Thanks and regards
Frank

**Comment by serge-rider** [comment]
Informix is special. Looks like it has some non-standard rules for reserved keywords quoting.
As a workaround I've added a special config (in driver properties):
![quote-keywords-cfg](https://cloud.githubusercontent.com/assets/6398845/17080150/bd7d2fe8-512d-11e6-8331-4d811e3d7c62.png)

Here you can disable keywords quote at all. However this is not a final solution.
Could you suggest anything better?

**Comment by frankhsimon** [comment]
Well, I will have to test it first.
But I think, I’m fine with this solution.
If I’ll get a sudden inspiration I will tell you.

Regards
Frank

**Comment by frankhsimon** [comment]
works fine

Thank you
