### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ncgodinho** [serge-rider/dbeaver#598]
I'm using Linux Mint 64x 
Linux newdecision 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 U
TC 2015 x86_64 x86_64 x86_64 GNU/Linux

I believe I found a small problem with the Dark theme. That's how it looks on my computer.

![dbeaver_classic](https://cloud.githubusercontent.com/assets/20206610/16834292/19bd3328-49ab-11e6-8144-5d1764885ac7.png)

As you can see it's not possible to see the buttons text.
Thanks and best regards,
Nuno Godinho
(nuno.godinho@newdecision.pt)

**Comment by serge-rider** [comment]
I'm afraid there is nothing I can do. Dark theme is provided by Eclipse, all standard components (like buttons) are also colored by Eclipse CSS. 
Maybe it is a result of OS-specific coloring and Eclipse coloring..

**Comment by slestak** [comment]
Appears to work ok in Win10, just giving an example to compare.
![2016-07-25 13_11_24-dbeaver - general - viewtm_workorderanalytes](https://cloud.githubusercontent.com/assets/79189/17110151/7faa346c-5269-11e6-92ac-32f7414b56f0.png)

**Comment by baermathias** [comment]
This is still an issue in the version 6.1.3 on Ubuntu 19.04

**Comment by lucasMesquitaBorges** [comment]
Here was adjusted after restarting the application.. Maybe it was fixed on a recent release!!
I'm currently on Ubuntu 18.04.

**Comment by gustavorps** [comment]
+1
