### ISSUE TITLE
Export resulset to CSV, can't avoid Quote Character

### ISSUE THREAD

**Issue by Xrizoo** [serge-rider/dbeaver#599]
Hi Serge, 
It's a little problem, but I'd try to remove the doulble quote " as default by empty char. I try Null and none space, but alway apears the " char.
Thanks.

**Comment by serge-rider** [comment]
Hi,
what's the point of removing quotes? It will make CSV inconsistent (non-CSV actually).

**Comment by Xrizoo** [comment]
Hi Serge,
I use it for one special interfase, I've to remove double quote every time, there isn't a big problem, but in your system, you allow to change through a parameter so, why not allow any parameter?
PS: thanks for your interest.

**Comment by serge-rider** [comment]
Ok. This is easy so I'll add a workaround.
If you will set quote char to space character then quotes won't be used at all. And I'll this into config field description.

**Comment by Xrizoo** [comment]
Serge: Thank you very much.

**Comment by Xrizoo** [comment]
It works perfectly... (and I see your remark in the tip). 
Again... thank you so much. It's a great piece of software.

**Comment by danielgrubert** [comment]
It worked, thanks!
