### ISSUE TITLE
Active datasource changes for wrong editor

### ISSUE THREAD

**Issue by sorenbronsted** [serge-rider/dbeaver#60]
When I choose 'New SQL Editor', I get a new editor and the tab for the editor displays correctly the active datasource. I then open another editor with 'New SQL Editor' og the tab i correct. Now I change the active datasource, and I would expect that I am going to change the active datasource for the current tab, but instead the first editor now displays the newly choosen active datasource. This is kind counter intuitive very annoying, because the sql statements I had in the first tab was for another datasource.

**Comment by serge-rider** [comment]
Thanks for report!
