### ISSUE TITLE
Query won't execute if cursor is in a comment

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#600]
`select 1 -- test`

if my cursor is after the `--` then i get the error message `empty query string`
![image](https://cloud.githubusercontent.com/assets/9246654/16858929/7654c40a-49df-11e6-8e0e-b67440c73549.png)

if my cursor is before the -- it process correctly and shows `select 1 -- test` as the query executed
![image](https://cloud.githubusercontent.com/assets/9246654/16858922/6997d70c-49df-11e6-8a32-1f38bfcee628.png)

**Comment by serge-rider** [comment]
Thanks for report
