### ISSUE TITLE
MacOS icon for high resolution for dock & "cmd+tab"

### ISSUE THREAD

**Issue by fakarakas** [serge-rider/dbeaver#601]
Will be nice to have an high resolution icon in the dock or when switching from one app to another with "cmd + tab" on the macOS

**Comment by serge-rider** [comment]
MacOS and Linux icons will be fixed in the next version.

**Comment by sbecainfo** [comment]
Hi, tested this in 3.7.2 and the image still looks grainy. Is there any way to set the icon to high-res image?

**Comment by serge-rider** [comment]
Hmm, that's odd.
Could you check dbeaver.icns file in Contents/Resource? Since 3.7.2 it contains 128x128 pixel logo.

**Comment by sbecainfo** [comment]
I can see it's 256x256 but still looks grainy...
![grainy_icon](https://cloud.githubusercontent.com/assets/11276344/17194666/f623da58-540d-11e6-8012-2a8dacb25d9c.jpg)

**Comment by nchammas** [comment]
Yeah, the behavior I'm seeing in 3.7.2 is the following: When DBeaver is not running, the icon looks sharp. When you launch DBeaver, for some reason, the icon changes to the low-resolution one.

**Comment by sbecainfo** [comment]
I'm happy to help test this.

**Comment by serge-rider** [comment]
Ok, icns file is a static image which is used by shell to show program icon.
When program is running it uses another image (windowImage).

I've added big window images (maximum image size is 450x450). I hope it will finally resolve this issue.

**Comment by fakarakas** [comment]
Thanks it is perfect now in version 3.7.4 ;)

cheers
