### ISSUE TITLE
ability to automatically connect to a replica server in a mongo cluster

### ISSUE THREAD

**Issue by antonmos** [serge-rider/dbeaver#602]
it would be great to configure a cluster url like this and have the app automatically connect to the replica:
mongodb://<dbuser>:<dbpassword>@foo-a0.mongolab.com:4444,foo-a1.mongolab.com:444/<dbname>?replicaSet=rs-foo

**Comment by genseric** [comment]
+1

**Comment by serge-rider** [comment]
Multiple server config will be added in 3.8.1
