### ISSUE TITLE
ability to send native json queries to primary node on mlab

### ISSUE THREAD

**Issue by antonmos** [serge-rider/dbeaver#604]
Currently, I am able to connect to the primary node and execute SQL queries.
However, when trying to execute a native json query like db.collection.findOne()
I get the following error:

> com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on mydb  to execute command { $eval: "db.loan.find({ "_id":  ObjectId("5539380d41e9190300926dfa")}).toArray()", args: [] }' on server foo-a0.mongolab.com:4444. The full response is { "ok" : 0.0, "errmsg" : "not authorized on mydb  to execute command { $eval: \"db.loan.find({ \"_id\":  ObjectId(\"5539380d41e9190300926dfa\")}).toArray()\", args: [] }", "code" : 13 }

I think this has to do with using "eval" (https://github.com/mongeez/mongeez/issues/56)

While it is probably possible to grant eval permissions, it is not ideal because it require granting all access to the user (i.e. no readonly users) This is not recommended per the docs https://docs.mongodb.com/manual/reference/method/db.eval/#access-control

**Comment by antonmos** [comment]
Btw, huge thanks for this great tool!

**Comment by serge-rider** [comment]
I wondering is there any replacement for `eval`.

In theory it is possible to parse simple queries like `db.collection.findOne()` and execute them as direct commands. But it'll require pretty much effort.

**Comment by antonmos** [comment]
Crazy idea - i wonder if you can execute it via http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html :)

**Comment by serge-rider** [comment]
I'll postpone this feature for now.
It'll require too much effort to implement.
Maybe I'll return to it in future. I definitely won't use plan JS parser - but maybe Mongo driver will provide some extra commands processing functions..
