### ISSUE TITLE
Support for portable Oracle tnsnames.ora

### ISSUE THREAD

**Issue by moonwhaler** [serge-rider/dbeaver#606]
Since I am using DBeaver in a very portable fashion (USB stick), I am not able to add a TNS_ADMIN path on any machine I am using. For that, a configuration to support a **real** portable "tnsnames.ora" would be ideal in the sense of either adding a **relative path** where to look for this file - or the file directly.

This is already working fine with the SQL Developer tool (from Oracle), maybe adding this feature would benefit DBeaver, too.

**SQL Developer (4.1.1) screenshot:**

![2016-07-18 15_10_34-oracle sql developer](https://cloud.githubusercontent.com/assets/1736467/16915822/efde905e-4cf9-11e6-8407-b8ea9c58ca6d.png)

**Comment by serge-rider** [comment]
This makes sense.
