### ISSUE TITLE
DB2 DECFLOAT Values

### ISSUE THREAD

**Issue by Magublafix** [serge-rider/dbeaver#607]
Hi,

It seems that DECFLOAT values like NaN and Infinity are not detected correctly. They are shown as Null.

![2016-07-18 14_56_24-sitzung a - t0004750](https://cloud.githubusercontent.com/assets/4953529/16915450/d71ca5f8-4cf7-11e6-979f-56a3bb55a620.png)

![2016-07-18 14_55_29-dbeaver - general - _entwicklung_ script-14](https://cloud.githubusercontent.com/assets/4953529/16915442/ccb626e8-4cf7-11e6-8210-fa5fe6204d34.png)

regards,
Gerald

**Comment by serge-rider** [comment]
Thanks for report
