### ISSUE TITLE
Autoload Oracle thin client drivers

### ISSUE THREAD

**Issue by moonwhaler** [serge-rider/dbeaver#608]
As of now, putting the driver files in a local, relative "./drivers/oracle" directory (using the portable DBeaver "zip" file) does not work in terms of creating a new Oracle connection. Instead, DBeaver tells the user that no drivers could be found / should be downloaded manually and then be added to the drivers configuration.

This is somehow redundant since adding the files manually to the configuration might also be handled automatically, if found in a certain directory where they we placed beforehand.

![2016-07-18 15_07_23-dbeaver - general - _none_ script-1](https://cloud.githubusercontent.com/assets/1736467/16915741/7c2181f8-4cf9-11e6-8a8a-fdb7048264e0.png)
![2016-07-18 15_07_41-d__dl_dbeaver-ce-3 7 1-win32 win32 x86_64_dbeaver_drivers_oracle](https://cloud.githubusercontent.com/assets/1736467/16915742/7c23460a-4cf9-11e6-9fe5-523d055d8f7a.png)

**Comment by serge-rider** [comment]
The problem is that there are quite many different Oracle drivers with different jar names. We can't assume some particular ones.
But after all I don't think that adding jars manually in UI is much more complicated than copying them in some predefined location (moreover last way isn't obvious).

If you need to install preconfigured DBeaver then you could try to patch Oracle plugin.xml (and using relative path as it was before).

**Comment by moonwhaler** [comment]
Makes sense. :+1: 
I will try to hack it into the plugin.xml then. Thank you.

**Comment by serge-rider** [comment]
You will need to replace file source with direct file references.
<file type="jar" path="repo:/drivers/oracle/ojdbc.jar"/>
In that case DBeaver will first try to find this jar in local drivers location (in DBeaver workspace , can be changed in Preferences->Database->Drivers). So you can copy your pre-downloaded Oracle drivers there.

**Comment by moonwhaler** [comment]
I know tried it like this:

```
<fileSource url="./drivers/oracle" name="Oracle 11g drivers">
  <file name="./drivers/oracle/ojdbc6.jar" description="JDBC driver"/>
  <file name="./drivers/oracle/orai18n.jar" optional="true" description="NLS classes"/>
  <file name="./drivers/oracle/xdb6.jar" optional="true" description="SQLXML support"/>
</fileSource>
```

Since I am not sure from which directory DBeaver is referencing the drivers, I also tried using `../drivers/oracle/`, but it didn't work both ways. Anything I might have missed?

**Comment by serge-rider** [comment]
You don't need to use `<fileSource ...>`. Just `<file ..>`.
Use generic extension drivers `mssql_ms` or `informix` as an example.

**Comment by moonwhaler** [comment]
I will do that. Maybe you could consider my idea? Anyway, thank you!

**Comment by serge-rider** [comment]
I agree that hacking plugins configuration isn't the best solution.
But driver libraries configuration is already pretty complicated so it is not so easy to add yet another possibility to load jar.
Anyhow - I'll mark this as a feature request.

**Comment by majkinetor** [comment]
If you implement self contained projects like I suggested at https://github.com/serge-rider/dbeaver/issues/614#issuecomment-234188330 then only one person would need to set this up, everybody else would grab it up from repository and not think about it.

**Comment by majkinetor** [comment]
@moonwhaler #611, when fixed, should make this much easier as one person could setup drivers and others would just import the project and have everything set up.

**Comment by majkinetor** [comment]
I found my driver configuration at: `~\.dbeaver\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml`

>But driver libraries configuration is already pretty complicated so it is not so easy to add yet another possibility to load jar.

You should at least allow loading via environment vars. For example 

   ```
<provider id="oracle">
        <driver id="oracle_thin" custom="false" embedded="false" name="Oracle" class="oracle.jdbc.OracleDriver" url="jdbc:oracle:thin:@{host}[:{port}]/{database}" port="1521" description="Oracle thin driver. Doesn&#39;t require Oracle client.">
            <library type="jar" path="C:\Users\majkinetor\.dbeaver\.metadata\.plugins\org.jkiss.dbeaver.core\drivers\ojdbc7.jar" custom="true"/>
        </driver>
</provider>
```

Here, `path` could be specified as `~\.dbeaver\...` or `$HOME\.dbeaver...` which would allow one to simply copy the `.dbeaver` to another machine and everything will work.

**Comment by serge-rider** [comment]
Sounds reasonable. And easy to do. Will try to add this feature on the next
week (after ill return from vacation)

**Comment by serge-rider** [comment]
3.7.3 will support 3 standard variables in `drivers.xml`:
- `${home}` - user home
- `${workspace}` - DBeaver workspace path
- `${dbeaver_home}` - DBeaver installation path

**Comment by moonwhaler** [comment]
Just tried that, but a change in the drivers.xml in the <user_home> does not work. When starting up DBeaver is telling me that the drivers could not be found.

`	<provider id="oracle">
		<driver id="oracle_thin" category="Oracle" custom="false" embedded="false" name="Oracle" class="oracle.jdbc.OracleDriver" url="jdbc:oracle:thin:@{host}[:{port}]/{database}" port="1521" description="Oracle thin driver. Doesn&#39;t require Oracle client.">
			<library type="jar" path="${dbeaver_home}\drivers\oracle\ojdbc7.jar" custom="true"/>
			<library type="jar" path="${dbeaver_home}\drivers\oracle\orai18n.jar" custom="true"/>
			<library type="jar" path="${dbeaver_home}\drivers\oracle\xdb6.jar" custom="true"/>
			<library type="jar" path="${dbeaver_home}\drivers\oracle\xmlparserv2.jar" custom="true"/>
		</driver>
	</provider>`

**Comment by serge-rider** [comment]
Please create a bug report for that. Maybe something was broken in recent versions.

**Comment by serge-rider** [comment]
Well, I did reproduce that (var substitution worked only for Maven artifacts). 
See fix in the next version.

**Comment by serge-rider** [comment]
Also check this: https://github.com/serge-rider/dbeaver/wiki/Admin-Manage-Drivers

**Comment by moonwhaler** [comment]
Is it possible to keep a drivers.xml in the dbeaver home directory (where 
the binaries are, for example), which will then be prioritized?


Am 16. April 2017 9:49:34 nachm. schrieb Serge Rider 
<notifications@github.com>:

**Comment by serge-rider** [comment]
I don't think so. 
But you can use `-data` parameter and set workspace location to some DBeaver home subfolder.
