### ISSUE TITLE
[Linux][Gnome3] DBeaver has incorrect WM_CLASS

### ISSUE THREAD

**Issue by meden** [serge-rider/dbeaver#609]
Hello,

DBeaver on Gnome 3.x sets a generic `WM_CLASS="SWT", "SWT"`, as you can see using `xprop` on the application window. Being Gnome3 "application-based" [1], this prevents the correct association between windows and the application icon (I'm using a `.desktop` file created by me).

A workaround would be setting up the property `StartupWMClass="SWT"` in the desktop, but `SWT` looks too generic to be useful. A sensible value would be `DBeaver` o a more specific `DBeaver <Community|Enterprise>`.

Thanks for your work!

[1] https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased

**Comment by serge-rider** [comment]
Umm, will adding
`StartupWMClass=DBeaver`
into dbeaver.desktop solve the issue?

**Comment by meden** [comment]
I tried, but it couldn't work. The only ways to have it working are:
# having `WM_CLASS` equal to the property `Name` into `.desktop` file
# having `WM_CLASS` equal to the property `StartupWMClass` into `.desktop` file

I had (and still have, actually) a very similar problem with Eclipse. Here the solution I found:
http://askubuntu.com/a/741940/293463

Maybe you could do something similar, being DBeaver an RCP application.

**Comment by DanMan** [comment]
If you add `StartupWMClass=SWT` to the `.desktop' file it kind of works, I think. But I don't know, if that's a good idea. `SWT` seems kind of too generic.

**Comment by serge-rider** [comment]
I'll add `StartupWMClass=SWT` in the next version. Hopefully this will work fine.

I had to patch Debian .desktop builder task to do this (https://github.com/serge-rider/ant-deb-task)

**Comment by meden** [comment]
Hello,

I don't know what happened but I just installed DBeaver Enterprise 4.7.8 and the bug is gone. Now with `xprop` I get:

    WM_CLASS(STRING) = "DBeaver Enterprise", "DBeaver Enterprise"

Please note that this is not related to `.desktop` builder patch, as I did not installed the `deb` package, but I rather created my own `dbeaver.desktop` file. Actually, the patch you mentioned could reintroduce  this bug, as now the `WM_CLASS` is not `SWT` anymore.
Correct properties values to use should be:

    StartupNotify=true
    StartupWMClass=DBeaver

(For startup notification meaning, see https://developer.gnome.org/integration-guide/stable/startup-notification.html.en)

Thanks!

**Comment by serge-rider** [comment]
Ok, now I can change/add any properties in desktop so it is not a problem.
Next version will be with new props.

**Comment by michimartini** [comment]
Here is an image to illustrate (for you guys not running gnome 3);
(DBeaver Version 3.8.2, Ubuntu Gnome 16.04.1 LTS)
![swt-bug](https://cloud.githubusercontent.com/assets/4686893/21454703/c3321cd6-c91a-11e6-9f43-56080247b3af.png)

And this is with <pre>
StartupNotify=true
StartupWMClass=DBeaver
</pre>
in /usr/share/applications/dbeaver.desktop

Note the other SWT app (Pentaho DI) that shares the same problem.

**Comment by serge-rider** [comment]
I don't know how to fix that.
Aren't you aware about any known solution?

**Comment by Desmaster** [comment]
Having the same behavior as @michimartini, I might do some investigation around the .desktop problem.

**Comment by serge-rider** [comment]
That would be great. I still can't figure out how to handle this.

**Comment by MarcinWieczorek** [comment]
Why is the class SWT again? Changing everything to `SWT` for compatibility is not a good idea. I think every related value should be changed to the program's name. I need a proper value for my i3 configuration.

**Comment by serge-rider** [comment]
Check #1344
I don't know what to do to make everybody happy :)

**Comment by MarcinWieczorek** [comment]
Where can I find the desktop file in the repository?

**Comment by serge-rider** [comment]
There is no desktop file in the repository - it is generated in runtime by ant-deb utility.

**Comment by MarcinWieczorek** [comment]
Thank you.

**Comment by serge-rider** [comment]
If anyone has any idea how to fix desktop file to make it good enough for all standard environments - please post it here.
I can generate any desktop file.

**Comment by michimartini** [comment]
I looked into this and the fundamental idea seems to me to be the following: The values in the .desktop file like WM_CLASS and StartupWMClass just help the Desktop environment to match up icons and the like.  StartupWMClass seems to work like this: The executable mentioned in the field "Exec" is launched and a bouncing startup notification is started - as soon as a window with the mentioned StartupWMClass pops up the bouncing action is stopped. 
These strings simply have to match up with the values the app itself sets when it initializes its environment. The problem cannot be solved by putting different stuff into the .desktop file, but only by putting something else than the default "WM_CLASS=SWT" in the actual java code. 
see [this stackexchange](http://stackoverflow.com/questions/10593075/how-to-alter-wm-class-value-in-a-java-gui-application-based-on-swing-or-netbeans) page that explains how to set that exact property in the java code:

WM_CLASS is supposed to be specific to the the app (not the same for every app that uses the same toolkit) and static (not dynamicly changing for  example into the name of the currently opened document). 
see [the X11 docs ](https://www.x.org/releases/X11R7.5/doc/man/man3/XClassHint.3.html) for that matter

**Comment by MarcinWieczorek** [comment]
This issue apply to me because of i3. I want to assign DBeaver to a workspace but setting `SWT` as the keyword is obviously not a good idea.

**Comment by meden** [comment]
Just to add some info: it may well be a matter of timing/race condition. According to [this StackOverflow anser](http://stackoverflow.com/a/10203836) the application name should be set very early (but I don't know if it is already the case here, sorry for not peeking into the code).

**Comment by serge-rider** [comment]
@meden Good point. I've fixed DBeaver app init so display name now should be correct (it is `DBeaver` or `DBeaver Enterprise`).
You can check this in EA version (http://dbeaver.jkiss.org/files/ea/)

**Comment by michimartini** [comment]
It seems perfect now. Thank you Serge!

**Comment by MarcinWieczorek** [comment]
@serge-rider regarding the desktop entry file - how can I generate it separately? I need just that one file and the jar which I build with maven.

**Comment by serge-rider** [comment]
@MarcinWieczorek unfortunately you can't. 
DBeaver installer project is not public domain (it contains secured artifacts like sign certificates and other non-public stuff).
You can get dbeaver.desktop file from Linux distribution. 
Or you can get it from some public Linux repository (e.g. AUR: https://aur.archlinux.org/packages/dbeaver/)

**Comment by MarcinWieczorek** [comment]
I need it for the AUR package.

**Comment by kauanmocelin** [comment]
@serge-rider this bug come back on dbeaver-ce 24.2.2 on Ubuntu 24.04, VW_CLASS is set to "swt " again causing a broken icon  due to .desktop entry.
