### ISSUE TITLE
Rename produces wrong sql on oracle

### ISSUE THREAD

**Issue by babbomaria** [serge-rider/dbeaver#610]
When rename an oracle table SQL generated is 
`rename tim.bak to bakbak;`

The error is 
```
rename tim.bak to tim.bakbak
***
ERROR at line 1:
ORA-01765: specifying table's owner name is not allowed
```

The syntax of the RENAME command does not allow you to specify any schema other than the currently connected schema. So a first rapid fix is

`rename bak to bakbak;`

RENAME is an older command. You should be using the ALTER TABLE ... RENAME syntax

http://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_3001.htm#CJAHHIB

**Comment by serge-rider** [comment]
Thanks for report.
