### ISSUE TITLE
Oracle 12c - Tables editor fails to show

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#612]
I can see the tables in the Project/DB navigator but 'View Owner (F4)' doesn't work which is mainly problematic because search is not that practical in project navigation.

**Comment by serge-rider** [comment]
Can't reproduce.
Is there an error dialog or something in Error Log view?

**Comment by majkinetor** [comment]
No, nothing. As you can see menu item F4 is missing from Oracle database while it exists on MS SQL database. Clicking on 'tables' in breadcrumbs doesn't work either.

![2016-07-20_15-19-44](https://cloud.githubusercontent.com/assets/85767/16987569/41f9066e-4e8d-11e6-9037-9132306dcaff.gif)

**Comment by majkinetor** [comment]
![image](https://cloud.githubusercontent.com/assets/85767/16987623/7e74d2c6-4e8d-11e6-8e2b-310a946366ea.png)

**Comment by serge-rider** [comment]
I think I know where the bug is.
Thanks for details.

**Comment by majkinetor** [comment]
You are welcome !  Thanks for the quick fix !

**Comment by majkinetor** [comment]
I confirm it works with 3.7.2.
