### ISSUE TITLE
dbeaver silent crash

### ISSUE THREAD

**Issue by misutkowski** [serge-rider/dbeaver#616]
Hi,
I configured dbeaver to work with Postgresql 9.4. Dbeaver downloads driver and everything works fine until I exit from dbeaver and start it again. It cannot connect to databse. After waiting some time, it shows message: "org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadNode cannot be cast to org.jkiss.dbeaver.model.navigator.DBNNode". After this message dbeaver starts working unstable.
It's 100% reproducible.
Thanks.

**Comment by serge-rider** [comment]
Can't reproduce.
Please post error stacktrace.
You can get in Error Log view (which can be opened in main menu Windows->Show View)

**Comment by misutkowski** [comment]
Thanks for quick reply.

Of course. Here is a screenshot:

and there is an attachment in this mail with an Error Log.

I tried to work with driver "PostgreSQL (Generic)" now and it seems to 
work a little better then driver "PostgreSQL", provided there is no 
connection with driver "PostgreSQL" configured. Connection configured 
with driver "PostgreSQL (Generic)" is not 100% reproducible, but it 
occures often.
Besides showing this message (screenshot), program doesn't show objects 
under the Connection (schemas nor other objects). It shows "Loading", 
but arrow does not twist.

I tried to play with this error and I've noticed following behaviour: 
when I press F4 (Edit connection) and press "OK", it starts working as 
it should.
It works fine immediately after configuring connection, after fresh 
install also.

Thank you.
Kind regards.

**Comment by serge-rider** [comment]
Sorry, don't see any attachments..

**Comment by misutkowski** [comment]
I' ve dropped them to my message directly on github. They should be there, now.

**Comment by serge-rider** [comment]
Thanks for details.
Logs were really useful - I've fixed 3 different bugs.

**Comment by misutkowski** [comment]
Sounds lovely.
Thanks a lot.
