### ISSUE TITLE
Postgres function args weird types

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#618]
create type test.enum1 as enum ('foo','bar','baz','qux');
create function test.echo(test.enum1) returns test.enum1 as $$ select $1 $$ language sql;

This shows function test.echo() (no args!) in the navigator, which is broken.
Clicking it open the function ok, but it cannot be dropped, etc.

**Comment by lacanoid** [comment]
Update:
After closing and reopening the connection, the function arg shows up, but it is not schema-qualified. Instead of test.echo(test.enum1) it is test.echo(enum1), so drop etc still doesn't work.

Solution: use postgres format_type() function to convert type oids to sql strings.
It also takes care of identifier quoting and not explicitly adding current or system schemas.

**Comment by serge-rider** [comment]
1. When you create new type or new table in SQL editor - you'll need to refresh connection metadata. 
2. I will show fully qualified column type name if type owner schema differs from procedure owner schema.
