### ISSUE TITLE
Close button in title doesn't work on Windows 10

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#619]
Only file -> exit.

**Comment by majkinetor** [comment]
![2016-07-21_11-30-11](https://cloud.githubusercontent.com/assets/85767/17018050/3fbf9148-4f36-11e6-8725-7a99442415f2.gif)

**Comment by serge-rider** [comment]
Is this problem 100% reproducible? 
What is your OS?

**Comment by majkinetor** [comment]
On my Windows 10 it behaves like that, on my Windows 7 it doesn't. I will check tomorrow on few other machines. It didn't happen before, I will downgrade to see when it started to show.

**Comment by majkinetor** [comment]
I downgraded to 3.6.9 on machine where it doesn't work and killed all other programs. Still the same.

**Comment by serge-rider** [comment]
Still can't reproduce but I have a guess. Probably something happens during shutdown. I've add a small fix, maybe it'll help..

**Comment by majkinetor** [comment]
BTW, ALT+F4 doesn't work too, but dbeaver icon in taskbar starts to flash after it.

Is the Windows installer available for each build or just on new release ?

**Comment by serge-rider** [comment]
I can make EA version if you need.
Or - if you have Java dev environment - you can build from sources (`mvn install`).

**Comment by majkinetor** [comment]
No problem, I will build it myself or just wait for next release. Thanks.

**Comment by majkinetor** [comment]
OK, it works on my another Win 10. 

It asks that 'transaction commit' on exit which is never shown on my system. Perhaps it blinks because of it , like it is hidden somewhere....

**Comment by majkinetor** [comment]
I am talking about current dbeaver, not the updated one 14 hours ago not yet released.

**Comment by serge-rider** [comment]
Try yesterday's EA version: http://dbeaver.jkiss.org/files/ea/

**Comment by majkinetor** [comment]
I used http://dbeaver.jkiss.org/files/ea/dbeaver-ee-3.7.2-x86_64-setup.exe

That didn't work, actually, its worse, now File->Exit doesn't work too, only emergency exit.
Perhaps you should add some debug info to troubleshot this ? I don't see any message in the error log. 

I also did reset settings on installation on second try and it didn't make any changes.

**Comment by majkinetor** [comment]
Hah, found it

General -> Confirmation -> Exit DBeaver was set to Never. When I set it to Always or Prompt it works.

**Comment by serge-rider** [comment]
Well, ok then.
After all I've fixed the bug I found during examining the code :)

**Comment by majkinetor** [comment]
I am confused now. You seem to think this is not the bug but this behavior is wrong. Why should confirmation setting 'Never' prevent dbeaver from exiting ? I understand it as:

- Never:  'never ask for confirmation when exiting' (just exit)
- Always: 'always ask for confirmation when exiting' (always confirm)
- Prompt: ? 'prompt for confirmation when exiting' - I assumed this is dynamic based on changes.

However, Always doesn't ask anything, just exits, prompt always prompts and never prevents exit always. If that is not confusing, I don't know what is :)

**Comment by majkinetor** [comment]
Its also worth noting that I did say 'reset settings' during installation and some things did reset, but not this one.

**Comment by serge-rider** [comment]
Agreed, confirmation setting isn't obvious. Mostly because it is the same for all confirmations.
Need to do something with that..
