### ISSUE TITLE
Firebird View DDL

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#62]
Nice to have a header for views, but the views not need collumns (also it throw exception about the number of collumns) and make "CREATE or ALTER" from normal "CREATE"

**Comment by serge-rider** [comment]
Umm, why do you say "views not need columns"? View columns may have different names than columns in a source query.
I can't reproduce exception about incorrect column number. Could you post an example of some incorrect view?

**Comment by adamos42** [comment]
```
CREATE TABLE "VIEW_TEST_DATA"("COL1" INTEGER, "COL2" INTEGER, "COL3" INTEGER, "COL4" INTEGER);

INSERT INTO "VIEW_TEST_DATA"("COL1","COL2","COL3","COL4") VALUES (1,1,1,1);
INSERT INTO "VIEW_TEST_DATA"("COL1","COL2","COL3","COL4") VALUES (2,1,2,3);
INSERT INTO "VIEW_TEST_DATA"("COL1","COL2","COL3","COL4") VALUES (3,1,3,4);

CREATE OR ALTER VIEW "VIEW_TEST"
AS
SELECT
	"COL1" as "ROW",
	"COL2" as "A",
	"COL3" as "B",
	"COL4" as "C"
	
FROM "VIEW_TEST_DATA";
```
The generated DDL looks like this:
```
CREATE VIEW VIEW_TEST (ROW, A, B, C)
AS
SELECT
	"COL1" as "ROW",
	"COL2" as "A",
	"COL3" as "B",
	"COL4" as "C"
	
FROM "VIEW_TEST_DATA"
```
The first problem here the only CREATE, so If I copy&paste the source into a query editor then it wont run becuase the view is already exists.

The exception was my fault, because If I editing this DDL for example:
```
CREATE OR ALTER VIEW VIEW_TEST (ROW, A, B, C)
AS
SELECT
	"COL1" as "ROW",
	"COL2" as "A",
	"COL3" as "B",
	"COL4" as "C",
	SUM("COL2") as "SUM_A"
	
FROM "VIEW_TEST_DATA"
GROUP BY "COL1","COL2","COL3","COL4"
```
and in this case you can see the header column number is not the same than the select. It was my fault, but when I editing a view which has ~500row in source (near 100 column) I cannot edit every time the full columns list which need 3 monitor to show. The view creation does not require the full column list since Firebird 2.1: http://www.firebirdsql.org/refdocs/langrefupd21-ddl-view.html
so I suggest to not use in the "source" DDL, only use it when somebody export it as an SQL (for backup).

**Comment by serge-rider** [comment]
There are two issues:
- CREATE OR ALTER syntax supported only since FB 2.5. I didn't find a way how to easy determine server version to generate different DDL.
- Yes, column list is not required. But allowed. If you created a view with column names which differs from column names in the source query then the only correct way to recreate DDL is to use view column names explicitly.
Do you have any ideas?

**Comment by adamos42** [comment]
Hmm, If I have to add to a firebird connection the server version number, then you can determine the server version quickly, but the CREATE OR ALTER is the smaller problem I think (because easy to edit).
I like costumize my programs behavior so for me the best will be a something where I can toggle the option if its not required. One option for the source one option to an exporting, like the autoformatter settings in Eclipse.

By the way If you ``SELECT rdb$get_context('SYSTEM', 'ENGINE_VERSION') from rdb$database;`` then you will have the version number if the version is >= 2.1 if not then fallback mode :)

**Comment by serge-rider** [comment]
Having too many config options isn't my favorite approach. They adds flexibility but in fact most of users don't even know about their existence. I believe that about 80%+ of users always work with default settings.

I have tried "rdb$get_context" way to obtain the version. But it doesn't work with FB 2.0: "Context variable ENGINE_VERSION is not found in namespace SYSTEM".
But I can get version from jdbc metadata. E.g. my test FB has version "Firebird 2.0+WI [WI-V2.0.7.13318]". Too verbose for my taste. But I'l ltry to parse it.

**Comment by serge-rider** [comment]
View DDL fixed. Problem with column names still remains. 
Standard workaround is to delete them from generated DDL. 
If it is still too bothering - please make another feature request. Actually this is not FB-specific, all other databases have the same behavior/problem.
