### ISSUE TITLE
Run Query button in Query Manager

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#620]
Can you add new button __Run Query__ to window in __Query Manager > Event__ or directly to Context menu in __Query Manager__? I need to run some query multiple times and this will be very usefull.

If you want to run query again you must click many times instead one click:

1. Copy Query
2. Click on New SQL Editor in Toolbar
3. Paste Query
4. Select DB from Select in Toolbar
5. Click to another window because Execute script button in Toolbar is inactive
6. Click back to Script window and finally Execute script

**Comment by serge-rider** [comment]
Good feature. Although there is a UI question. Should I open new SQL editor for each query? Or reuse current editor. Or just show some popup dialog.

**Comment by MatyCZ** [comment]
You can implement more variants for different use case.

1. __Run query__ - Run query in backgroud and will be logged in __Query Manager__
2. __Edit & Run query__ - Open new SQL editor with selected query
