### ISSUE TITLE
Reloading a MySQL table scrolls the view to the left

### ISSUE THREAD

**Issue by albertaparicio** [serge-rider/dbeaver#623]
In version 3.6.10, when reloading a MySQL table, the data is updated and the selected cell is kept in view.

However, in version 3.7.1, when I reload, the data is updated, but the view of the table scrolls all the way to the left.

I find the way 3.6.10 worked to be mighty useful, so it would be great to have it work like this in the newer versions of DBeaver.

I am running Linux Mint 17.3 x64 Cinnamon

Thank you very much

**Comment by serge-rider** [comment]
Thanks for report
