### ISSUE TITLE
Excel export support

### ISSUE THREAD

**Issue by moonwhaler** [serge-rider/dbeaver#625]
Although there is already support for a dedicated CSV file export, it would be really handy to export directly to MS Excel. This could be achieved via Apache POI (https://poi.apache.org/) and would save time in the daily working environment (especially with people not familiar with CSV).

**Comment by r-richmond** [comment]
Genuine question.

Since excel can open CSVs directly what pain point is an xlsx export option solving?

**Comment by serge-rider** [comment]
Yep. I also don't really understand why XLS is better than CSV (in case of data export).

XLS makes sense if you have some complex formulas, drawings, etc.

**Comment by moonwhaler** [comment]
Thanks for reviewing this. In my day to day work, I have to generate a lot of exports for different departments. These exports are currently widely accepted since I'm using SQL Developer (which supports said Excel export). DBeaver does not.

You have to see it from another perspective: many (!) users don't know Excel or are unable to open up CSV files in the right way. Even my Excel doesn not do that automatically. See the attached screenshot.

I know how to use the "data tab" and import them manually, but many don't. And preparing this every time I export a CSV file is very time consuming.

I understand your position on this.
![2016-07-26 10_29_12-s cs](https://cloud.githubusercontent.com/assets/1736467/17131150/6a3e1c48-531c-11e6-9f05-f80da45d6c4e.png)

**Comment by serge-rider** [comment]
I see your point. It is reasonable.

However generating XLS will take some significant coding time (which I don't currently have).
For now I'll keep this request as a reminder..

**Comment by r-richmond** [comment]
@moonwhaler 

Hey I was unable to reproduce your screenshot. When I export a csv and open it in excel it correctly delimits the data

![excel_csv](https://cloud.githubusercontent.com/assets/9246654/17229232/8c33441c-54cb-11e6-81e1-f0909f4b76f0.gif)

Here are my export settings perhaps you've changed them in DBeaver? If not I would suspect that you've accidentally changed a setting in excel in regards to CSVs

![image](https://cloud.githubusercontent.com/assets/9246654/17229301/c1fe4fb0-54cb-11e6-8c19-f6ac99f7d875.png)

**Comment by majkinetor** [comment]
I wouldn't do this, its already achievable by selecting the right delimiter.

**Comment by serge-rider** [comment]
Potentially it is a useful feature. 
Taking into account that results grid may be colored, may contain complex data types which occupy more than one cell, etc. These features cannot be mapped in CSV format.
So I'll leave it as a feature request. Will return to it when I'll have some free time. Or somebody else will contribute an exporter.

**Comment by majkinetor** [comment]
You are right. There is also a very problematic aspect of CSV and multiline values. For example, this is my export from today that I had to fix in SQL by replacing new lines for all fields.

<pre>
8517002;04372;Some value
 containing a new line;100346317;07018762;0;RAČUN;49-15-301-00006568;2015-09-03 00:00:00.0000000;2015-09-04 00:00:00.0000000;NULL;53251.22;NULL;NULL;0;53251.22;2015-09-08 15:10:12.983;NULL;1;2015-10-19 00:00:00.0000000;2015-09-11 00:00:00.0000000
</pre>

You could still map XML export tho but its way unpractical for every day use.

I checked and MS SQL Manager also exports this way. Excel ofc breaks with this.

**Comment by Choens** [comment]
I'd like to add my support for using Apache POI to support import/export to/from Excel.

- It is true, Excel has limitations. For example, there are limits on the number rows/columns in a worksheet, but these limits do not affect everyone.
- Apache POI makes it possible to specify the worksheet, which means it is possible to dump data directly into a hidden worksheet, and then use pre-defined formulas, etc. for presentation. I have used this pattern before and it makes a terrific "poor man's BI tool". I was able to write a simple SQL script which I could run when requested and then export the results into a series of hidden worksheets. The end-user received an Excel file with nice cross-tabs which she could manipulate to drill down, etc. She was familiar with Excel, but not SQL. Quick, dirty, easy, and it pleased the boss. With CSV export, I have an extra, time-consuming, step in that process.

**Comment by mratsim** [comment]
@r-richmond Delimiter autodetection depends on your locale.
If you have a European locale, it will open csv with semicolon delimiter properly but not CSV with comma delimiter. Vice-versa for the US.

Having to open the csv file in Excel, save as .xlsx is cumbersome when dealing with several reports.
Furthermore, Excel is bad a guessing the csv locale encoding.

**Comment by ev-str** [comment]
Hi! Can i vote for this feature? 
It is using very often when you should send exported data to other persons in the company. CSV export is good, but when users are using different locales it makes everything worse due to different delimiters.

In addition, in CSV it is impossible to add query to a new tab.

I understand that this can take a lot of development time, but maybe it will be possible?

**Comment by majkinetor** [comment]
On the other hand, manually or with simple Powershell script you can load CSV in your local Excel and save it as a excel file.

**Comment by GiantCrocodile** [comment]
I disagree to use Excel format as it is closed source, commercial and Office products aren't really compatible between different OS' (files of Mac and Windows in Office are incompatible to each other). Rather I suggest an open format like OpenDocument formats. This can be opened by Excel too and if it's bad, it's a fault of Microsoft.

**Comment by serge-rider** [comment]
@GiantCrocodile I understand your point but life is complicated. Excel is very widely used, we can't ignore this fact. 
However I'd prefer use some non-proprietary format which is good enough for all office applications.

**Comment by mratsim** [comment]
@GiantCrocodile I totally understand and support the opensource advocacy.
However software live and die on ease of use and integration in an existing environment.

1. Excel is the defacto standard in entreprise and people expects exporting to Excel. (Though Microsoft SQL Server doesn't support Excel export for some reason ...)

2. Excel .xlsx format is arguably an open standard registered with ISO as OpenXML. Microsoft implementation differs from the standard for some stuff (formatting, images probably), it shouldn't for tabular data. Between Mac and Windows, there should be only formatting and VBA that differs. Microsoft must support Excel functionality in Windows, Mac, Office 365, Dropbox and Box, so the issue of different codebases/features should disappear.

Now on the implementation side, I've used [xlwrite](https://www.mathworks.com/matlabcentral/fileexchange/38591-xlwrite--generate-xls-x--files-without-excel-on-mac-linux-win) to export Matlab data to Excel. Matlab is also a java application and xlwrite use Apache POI. I couldn't find the source code though.

**Comment by AndrewKhitrin** [comment]
Is it possible to ask Serge-rider for add Apache POI JARs  in DBeaver developer ecosystem ?

I guess it might look like what we are currently using Apache CLI and commons-loggin in  http://dbeaver.jkiss.org/eclipse-repo/.

In this case I am ready to assign task of streaming export in Excel and Open Office (Libre) Calc.

_Andrew_

**Comment by serge-rider** [comment]
Implemented as optional extension:
https://github.com/serge-rider/dbeaver/wiki/Extension-Office

**Comment by kiravi** [comment]
The extension looks good.
There is 1 issue.  You can export the SQL from which the data is generated,  When you click on the cell holding the SQL Excel complains -  with a popup - that the text is too long. But the entire long SQL is still captured.

**Comment by serge-rider** [comment]
@AndrewKhitrin what do you think?

**Comment by kagrawal13** [comment]
@serge-rider  Is there any limit on the number of rows we can export from result set. I have very large data and I want to export all the rows of the query result , But I am getting only 10000 rows. There are around 100000 rows .

**Comment by carlosherranz** [comment]
Hi, I don’t know why I am receiving this mails…





[cid:image3dc3b6.PNG@219b401d.4ab96e6c]
CARLOS HERRANZ RODRIGUEZ
SISTEMAS DE GESTIÓN DE PRODUCTOS
SISTEMAS AUTOS Y GARANTÍA MECÁNICA
AVENIDA BURGOS, 109 - MADRID - 28050
Tel: 912146679


Antes de imprimir este correo electrónico piense bien si es necesario hacerlo: el medioambiente es cosa de todos.



ADVERTENCIA LEGAL:

Este correo electrónico, y en su caso, cualquier fichero anexo al mismo, contiene información de carácter confidencial, exclusivamente dirigida a su destinatario, salvo error u omisión involuntarios. Queda prohibida su divulgación, copia o distribución a terceros, sin la previa autorización por escrito de su remitente. En el caso de haber recibido este mensaje por error, se ruega comunique esta circunstancia mediante su reenvío a la dirección electrónica del remitente y proceda a su eliminación, así como la de cualquier documento adjunto al mismo.

La Compañía ha adoptado todas las medidas a su alcance para impedir la implantación de virus informáticos en este correo y su documentación adjunta hasta el momento de su emisión, sin que asuma responsabilidad alguna por los eventuales daños o pérdidas que pueda ocasionar la recepción del mismo.


De: kagrawal13 [mailto:notifications@github.com]
Enviado el: jueves, 6 de julio de 2017 14:49
Para: serge-rider/dbeaver
CC: Subscribed
Asunto: Re: [serge-rider/dbeaver] Excel export support (#625)


@serge-rider<https://github.com/serge-rider> Is there any limit on the number of rows we can export from result set. I have very large data and I want to export all the rows of the query result , But I am getting only 10000 rows. There are around 100000 rows .

**Comment by serge-rider** [comment]
@kagrawal13 there are no any limitations. 
How do you open xls file? 
Are there any errors/warnings in error log?

@carlosherranz somehow you subscribed on this topic. Just click on unsubscribe.

**Comment by AndrewKhitrin** [comment]
Hello all,

Limitations.
Unfortunatley Apache POI based export have row count restriction based on Excel 2007 file format - current release supported max 1048575 rows. Details here - https://poi.apache.org/apidocs/org/apache/poi/ss/SpreadsheetVersion.html. Sorry. But if someone need realy HUGE excel export let's discuss multipage export : data must be placed on different excel worksheet depends on rows count, column value(s) etc. Please send your comment in this issue - https://github.com/serge-rider/dbeaver/issues/1881

Long SQL Text.
I have prepared patch with export option which allows you to split the  text of the SQL query into Exel rows using CR. PR will be soon.

**Comment by jordosaxman** [comment]
Hey, I'm looking to ditch Oracle SQL Developer and have used it a couple of times.  Any update on the export to .xls feature?  Was it implemented or does it exist in a plugin and I'm just not seeing it?  I do a ton of SQL work that involves exporting to Excel for presentation and analysis and this would make dBeaver an obvious choice for me.
