### ISSUE TITLE
Print for Result Set

### ISSUE THREAD

**Issue by slestak** [serge-rider/dbeaver#626]
Print (Ctl-P) works for script source, but would it be possible to also allow it for Result Set, specifically if the user is in Record Mode?

I understand in Grid mode sending results to the printer could get ugly.  Record mode by design is limited to only one record.

**Comment by serge-rider** [comment]
I can easily add "Print" support for plaintext presentation. 
For Grid presentation it'll require a lot of coding. However plaintext is also useful (at least for simple column types).
