### ISSUE TITLE
DBeaver improperly scripts the date type as date(10) in MySQL/MariaDB stored procedures and functions.

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#63]
MySQL/MariaDB do not allow precision specification for date data type, thus the following error occurs when trying to modify/persist procedural code containing date parameters:
  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(10)
...
'

**Comment by serge-rider** [comment]
Thanks for report
