### ISSUE TITLE
Prevent auto-connect in SQL editor

### ISSUE THREAD

**Issue by iron0012** [serge-rider/dbeaver#635]
Let's say I have two connections to two different databases, database A and database B. I also have two editor tabs, each associated with one of the connections: editor tab A and editor tab B. 

I want to be able to write code in each of these tabs, and switch back and forth between them WITHOUT dbeaver attempting to automatically connect to the databases whenever the respective editor tabs associated with them are selected. That is, I want to be able to edit and switch between editors while being (and remaining) fully offline from any databases.

This could take the form of a preference menu check box: "Automatically connect to server on editor activation" which I would set to "off". Or does this feature already exist and I'm missing it?

**Comment by serge-rider** [comment]
There is no such option yet.

**Comment by majkinetor** [comment]
I would suggest an option to auto connect on script execution. I guess connection is establish on tab switch to provide intelisense, so it could be useful to have all 3 options:

- auto connect editor activation 
- auto connect on script  execution
- disable auto connection

**Comment by serge-rider** [comment]
Yeah, that makes sense too.

**Comment by serge-rider** [comment]
![sql-editor-conn-cfg](https://cloud.githubusercontent.com/assets/6398845/17246066/6b7cc7e4-5592-11e6-9c6a-a9b0ef5edc4e.png)

**Comment by iron0012** [comment]
Wow, thank you! I appreciate it. Since it looks like you have this feature slated for the 3.7.3 release, I'm going to close the issue. Thanks again.

**Comment by iron0012** [comment]
Wow, thank you! I appreciate it. 

(Sorry, I initially closed the issue because it looked like you had the feature all finished and slated for 3.7.3, but now I think it might be more appropriate to leave it open until that version has actually been released? I don't know all the details of github etiquette)
