### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#636]
Hello, there

FYI, I started to maintain dbeaver [package](https://chocolatey.org/packages/dbeaver/3.7.2) on Chocolatey and it is [automatic](https://gist.github.com/majkinetor/181b18886fdd363158064baf817fa2ff#dbeaver) so it will always follow your release (the scheduler runs daily).

You can install it on Windows (and in near future on Linux/Unix too) with: `cinst dbeaver`.

I could also create non-JRE version that grabs dependency via chocolatey resolution if you are interested.

**Comment by serge-rider** [comment]
That's great, thanks!
I'm not sure about JRE-less version. Currently installer version is most stable AND the smallest (because of super Java archiver which is not available in zip archive).
But if you see any reasons to add it - I'm ok with that.

**Comment by majkinetor** [comment]
I noticed that the size difference and was confused. 

The only reason now to use dependency would be because of the security updates of the JRE itself once the dbeaver is not updated on frequent basis....

**Comment by serge-rider** [comment]
Most of security updates are related to server-side or web-based Java solutions. DBeaver is a desktop application so security isn't an issue in most cases.
Anyhow sometimes having more recent version of Java makes sense. And Chocolatey is a sort of installer already. So, probably it is reasonable for some people.

**Comment by majkinetor** [comment]
I noticed now that you have JRE option in installer. I can automate installation so this can excluded during unattended, something like:

    cinst dbeaver /params 'nojre'

In that case dbeaver would use system's JRE which would not reduce the download size but would reduce installation size by 20MB or so and allow DBeaver to use global JRE settings etc. So this variant would still use Java archiver.

**Comment by majkinetor** [comment]
Actually, not 20MB, JRE is ~ 100MB.

**Comment by majkinetor** [comment]
FYI i split packages into [dbeaver](https://chocolatey.org/packages/dbeaver) and [dbeaver-ee](https://chocolatey.org/packages/dbeaver-ee)
