### ISSUE TITLE
Request: Persistent Query Manager Option

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#637]
I did a quick search but didn't find anything on this. If its a duplicate feel free to mark and close.

Basically,  I'd like an option to make the query manager log persistent between sessions/app restarts/computer restarts.

Currently I have `save log to file(s)` enabled but the raw log files aren't nearly as user friendly as the query manager.

Ideally, I'd have an option `Persist Query Manager` underneath `save log to file(s)` that would save the query manager data there. A Days to store data (similar to save log to file(s) option) would be useful as well. So that when I opened up Dbeaver I could see queries in the query manager/execution log that were run from previous sessions

Let me know if there is anything else I can provide to make the request more clear

**Comment by serge-rider** [comment]
QM persistence is already implemented in EE version. We keep all query history in embedded H2 database.
But there is no UI to manage this history (and there is #178 issue for that). 
However you can browse H2 tables using QMDB database driver.

**Comment by r-richmond** [comment]
Is there a guide for connecting to the embedded H2 Database?

also feel free to close out this issue as a duplicate of #178

**Comment by serge-rider** [comment]
No, there is no guide. Just create new connection using QMDB driver.

**Comment by tskarthik** [comment]
which table in the QMDB has the history information ?

**Comment by serge-rider** [comment]
Join of QM_EVENT, QM_STATEMENT and QM_QUERY.
You can open ERD of public schema to see the structure.
