### ISSUE TITLE
Firebird Procedure DDL

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#64]
The procedure DDL are working now, I just want a little adjustment:
- make the header collumns in the first line
- the returns columns should be in new line (each of them)
- use " around t he column names and the procedure names (maybe it should be a toggleable option)

Example:

```
CREATE OR ALTER PROCEDURE "MY_PROCEDURE"( "TEST" INTEGER )
RETURNS (
	"RETURN" VARCHAR(100)
)
AS
BEGIN
	
	-- some code
	
END
```

**Comment by serge-rider** [comment]
Ok.
Column names will be quoted only they need to be quoted (contains spaces or other non-letter/digit characters, have a name which conflicts with a keyword, etc)

**Comment by adamos42** [comment]
:+1:
