### ISSUE TITLE
Error when open Dbeaver 4.4 on mac Yosemite and java 1.6

### ISSUE THREAD

**Issue by caiofigueiredo** [serge-rider/dbeaver#642]
I need a help, when I open the Dbeaver on my iMAC, the Dbeaver don't open, and show a message of error, and create this log. What I do?

[1469816262048.txt](https://github.com/serge-rider/dbeaver/files/391146/1469816262048.txt)

**Comment by serge-rider** [comment]
DBeaver requires Java 1.7.

**Comment by caiofigueiredo** [comment]
It did not work, the Dbeaver displays the same error.

**Comment by serge-rider** [comment]
Check #133

**Comment by caiofigueiredo** [comment]
Ok, the problem was resolved.

Thanks for the support!
