### ISSUE TITLE
"Execute Script" Always Generates Results in Multiple Tabs 

### ISSUE THREAD

**Issue by mcquiggi** [serge-rider/dbeaver#644]
Hi There:

I'm a new DBeaver user, and have searched for this issue and looked in the docs etc.  My apologies if this is a newbie error!

I am running DBeaver 3.7.2 on OSX 10.11.6, and connecting to a backend MySQL database running on a FreeBSD machine.

The question:

I have a number of SQL statements in the SQL editor.  I can execute them as individual lines, but if I try to "execute script", I always get multiple tabs in the results window.  

There is no observable difference between the behaviour of "execute script" (ALT-X) and "execute script returning multiple tabs" (SHIFT-ALT-X).

I am hoping to generate a single window of results from all of my queries that I can then copy/paste into another application.

Again, sorry if I have missed something in the docs, but I have looked high and low and also searched the older forums and Github for this behaviour.

Thanks,

Kevin

**Comment by mcquiggi** [comment]
Hi, I wanted to see if this was an OSX-related problem, and it is not.  I observe the same behaviour under Linux and Windows versions.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
Actually there IS a difference. But you will see if you will disable "Fetch resultsets" option in SQL Editor/Processing preferences.
In that case ALT-X will not read results at all and will show only script execution stats.
CTRL+ALT+X always executes queries in separate tabs.
Maybe "Fetch resultsets" option should be turned off by default...

**Comment by mcquiggi** [comment]
HI Serge:

Thanks for the response.  It does as you describe.

My goal, though, was to get ALL the result sets from my queries into a single window, so that I can copy and paste them all into another document.

For example, my script would contain:

select…;
select …;
select …;

I would like one result window that contains:

[results for select 1]
[results for select 2]
[results for select 3]

Then I can Control-A and copy all the results into another document.Text output for each of the queries would be fine.

Is there a way to do this?

My workaround is to go through the 25 tabs of results, and copy and paste each result set separately.  Not a major problem but very time consuming.

Maybe this is really a suggestion for a new feature!

Thanks,

Kevin

**Comment by serge-rider** [comment]
Currently there is no way to do this. It is not possible to show multiple results in a single grid because:
- results may have very different columns
- DBeaver fetches just a segment of full resultset (200 rows by default). Visualization you described must dump full resultsets - this might be a problem in case of huge results.

But generally I like the idea to have a special view for that - it is more like a "Console" view.
I can make a separate presentation (in addition to Grid and Text).

Please create a separate issue with feature request, this one become a bit messy..

**Comment by mcquiggi** [comment]
Hi Serge:

 

Thank you for the reply!  I will submit a feature request!

 

Dbeaver is a fantastic program, thanks for writing it.  It has made me much more productive on my c urrent research project.  Do you have a donation link?  I would like to submit something for your efforts.

 

Kevin

**Comment by dellasavia** [comment]
Hi, mcquiggi. Did you open the feature request? I'd like to follow it, because I have the same issue...

**Comment by serge-rider** [comment]
Yep, #667
