### ISSUE TITLE
All string in sql result are NULL

### ISSUE THREAD

**Issue by stevenluan07** [serge-rider/dbeaver#645]
when I  execute a sql , such as but not limit 
>select n.nspname,
       c.relname,
       pg_catalog.pg_get_userbyid(c.relowner) as "Owner"
  from pg_catalog.pg_class c, pg_catalog.pg_namespace n
 where n.oid = c.relnamespace
   and c.relname iLIKE '%operationtotal%'
   and c.relkind = 'r'
   and relstorage in ('h', 'a');

ALL String in the results are NULL.

![1](https://cloud.githubusercontent.com/assets/6841338/17285678/bc8efd6c-57f6-11e6-9113-0e2d75b6bb71.png)

**Comment by serge-rider** [comment]
Can't reproduce.
What is you PG version?
Is there anything in Error Log?

**Comment by serge-rider** [comment]
Just a reminder. Still can't reproduce.
