### ISSUE TITLE
"Goto Database Object" should use the filters set up in Database Navigator

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#648]
When working in an environment that has lots of schemas (in the postgres world), but I'm only working with 1 or 2 of them, I set up schema filters in the databases navigator to prevent lots of scrolling and having to find my schema among all the others.

It would be nice if the "Goto Database Object" tool would ignore schemas that I've filtered out (and other objects that may be filtered).  It would probably need to be an option in that dialog, just in case I am actually searching for something that is currently filtered out.

**Comment by serge-rider** [comment]
Agreed

**Comment by serge-rider** [comment]
Schema filters and table filters will be taken in account in GoTo Object dialog. 
And in SQL completion processor too.
