### ISSUE TITLE
Export ER Diagram in SVG Format

### ISSUE THREAD

**Issue by Davilink** [serge-rider/dbeaver#649]
Would be nice to export ER Diagram in SVG format.

**Comment by jk3us** [comment]
For now, you can save it as graphml, which yEd editor and open and export as svg:

https://www.yworks.com/products/yed

**Comment by serge-rider** [comment]
Yeah, thanks for hint.
Implementing SVG image generator could be quite complicated. 
So most likely I won't do it in near future.

**Comment by serge-rider** [comment]
Probably we'll add SVG format support in 4.2.
It will use Batik library (yet another monstrous Apache framework for XML generation).
So most likely it'll be moved to EE version. Although I think I'll make it as optional extension for CE version (similarly to Office format extension).

**Comment by serge-rider** [comment]
To test in CE: https://github.com/serge-rider/dbeaver/wiki/Extension-SVG-Format

**Comment by Davilink** [comment]
Thx i will try it out.

**Comment by Davilink** [comment]
I have that error when i try to install it : 
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SVG Extension 1.0.0 (org.jkiss.dbeaver.ext.ui.svg.feature.feature.group 1.0.0)
  Missing requirement: SVG format support 1.0.0 (org.jkiss.dbeaver.ext.ui.svg 1.0.0) requires 'bundle org.apache.xmlgraphics.batik-awt-util 1.9.1' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SVG Extension 1.0.0 (org.jkiss.dbeaver.ext.ui.svg.feature.feature.group 1.0.0)
    To: org.jkiss.dbeaver.ext.ui.svg [1.0.0]

**Comment by serge-rider** [comment]
Thanks for report. Eclipse repo seems to be broken (missing Batik packages in svg feature).
Will be fixed shortly.

**Comment by serge-rider** [comment]
P2 repository was fixed.
You could try to reinstall DBeaver 4.2.0 (remove previous version folder or use windows installer). And then try to install SVG extension again.

**Comment by Davilink** [comment]
Hi serge-rider, it work now, but when i'm in the ER diagram i can see line for the relation between tables but i can't see them in the SVG is it normal ?

**Comment by serge-rider** [comment]
This is bug, #2129
