### ISSUE TITLE
new in 3.5.4: Exception when trying to save a modified procedure in MariaDB (and probably MySQL)

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#65]
Exception message:
JDBCException: SQL Error: Can't call commit when autocommit=true
  java.sql.SQLException: SQLException: Can't call commit when autocommit=true

Connection settings:
connection type: production, connection settings: auto commit by default - on.
connection properties: auto commit

That's a new behavior for dbeaver 3.5.4.

**Comment by serge-rider** [comment]
It seems to be a result of new "feature" of the recent Maria driver (1.3.0). At the same time DBEaver shouldn't try to commit in auto-commit state. So I'll consider this as a bug.
Workaround: use older Maria driver (in driver editor click on Download/Update and then choose another driver version in artifact list).

**Comment by gogosofta** [comment]
It's actually configured with MySQL driver: com.mysql.jdbc.Driver 5.1.37

**Comment by adamos42** [comment]
oOh, that happend with me too. I was added an index to a table (with persist) which has ~4mil record in it and it showed that autocommit error but the index has been created.

**Comment by serge-rider** [comment]
Yep. Apparently it appears in other drivers too.
Anyhow this issue is fixed. Will be added in 3.5.5
