### ISSUE TITLE
Copy a result column as one line list

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#650]
I want suggest a new option on "Advanced copy..." menu: copy a result column as one line list. Here is a example:

*Selecting and copying id column:*

**id**      | name
--------|--------
**4893**|Alice
**9865**|Bob
**6456**|Mario

*Pasting id column:*

4893, 9865, 6456

**Comment by majkinetor** [comment]
Its doable with SQL.

**Comment by serge-rider** [comment]
I have a better idea.
I'll add row delimiter configuration in Advanced Copy settings. So you can copy columns/rows in any form you need:
![adv-copy-settings](https://cloud.githubusercontent.com/assets/6398845/17821612/2d19899a-665b-11e6-8527-0e50f3f8a57b.png)

**Comment by majkinetor** [comment]
This also allows to quick markdown table export by setting column delimiter to |.

**Comment by majkinetor** [comment]
Algthough you have that in presentation mode :)
