### ISSUE TITLE
Bug: Bad tab title for multiple result sets

### ISSUE THREAD

**Issue by TseuX** [serge-rider/dbeaver#651]
Hello,

When DBeaver execute several queries, the first tab title is the name of the last table (last query), but the result set come from the first query.

![image](https://cloud.githubusercontent.com/assets/20822357/17376952/cd7b1922-5985-11e6-8629-3eacc1f0e139.png)

Thank you in advance.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
Generally it is a SQL Server-specific issue ( believe you are using SQL Server).
If you execute multiple queries as a single query (ctrl+enter) then DBeaver reads query metadata from underlying driver.
Workaround: execute queries as a script (alt+x) - but you'll need to set some query delimiters (`;` or `go`).

In fact I can't reproduce this problem exactly as on your screenshot.
What driver do you use, what is you SQL Server version?

**Comment by TseuX** [comment]
Sorry for the wait.

I'm using Sybase : Sybase jTDS driver / Adaptive Server Enterprise 15.5

The workaround works but that's not ideal.

**Comment by serge-rider** [comment]
To avoid confusing tab names I'll set tab name only if query produces single result.
Otherwise names Result 1, Result 2, etc will be used.
