### ISSUE TITLE
Feature request: execute statement and go to next step

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#653]
Hi,

For the moment, in dbeaver, we can point the cursor in a query, execute it (for exemple with ctrl + enter shortcut). Which is cool.

But a feature that could be very useful to me is that once the SQL statement is finished (without error if possible), the cursor automatically goes at the beginning of the immediately following statement.

Example:
![image](https://cloud.githubusercontent.com/assets/12892581/17404441/eeebca8a-5a5b-11e6-8415-d7acf7c6da6a.png)
I put the cursor in the red statement, I execute it.
If it works, the cursor automatically jumps at the beginning of the blue statement.

Does it already exists? Or is it difficult to add?

Thanks in advance.

**Comment by r-richmond** [comment]
fyi: you can execute everything in sequence using execute script (alt-x)

this would execute the red statement and then the blue statement.

if the red statement errors you get a popup with the options retry, stop, ignore/continue

**Comment by jk3us** [comment]
I'd probably rather see this as a "Move to next/prev statement", maybe Ctrl+Up/Down.  So if you want to step through several statements and execute them individually, you can Ctrl+Enter, Ctrl+Down, Ctrl+Enter, Ctrl+Down, etc.

**Comment by ced75** [comment]
Yes. 
What I'm thinking about is a "step by step" execution, better than a script execution.

**Comment by majkinetor** [comment]
You can still do this by executing each statement in separate tabs - CTRL ALT X - if the statements do not depend on each other. 

Otherwise, some other db managers combine the output of all executed commands in the Output window.

**Comment by serge-rider** [comment]
I think that adding a command like "move to the next/previous query" (with shortcuts like `Ctrl+Down`/`Ctrl+Up`) might be useful.
Just don't want to make yet another special execute command.

**Comment by ced75** [comment]
No problem. It makes the execution of consecutive queries easier.

Thanks.

**Comment by serge-rider** [comment]
Will be added in the next version (for now I set shortcuts ALT+Down and ALT+Up - because CTRL is reserved for text editor scrolling).
