### ISSUE TITLE
SSH Key Open File pattern on Linux

### ISSUE THREAD

**Issue by zuernBernhard** [serge-rider/dbeaver#655]
I'm using DBeaver 3.7.2 on UBuntu Linux 16.04 64 bit. When I create a new connection with SSH authenticated by private key a dialog opens to select the private key file. And I'm always confused because I can't find my id_rsa file. The reason is the preselected file pattern which has to be changed to * instead of *.* (see attached screenshot). How can I change the default ?
![auswahl_003](https://cloud.githubusercontent.com/assets/1442798/17471898/cddb6ce4-5d47-11e6-88e1-6584e51742f2.png)

**Comment by serge-rider** [comment]
There is no config for that.
I'll change default pattern to "*" in the next version. Thanks for noticing.

**Comment by zuernBernhard** [comment]
Thank you !
