### ISSUE TITLE
Allow to open query from table browser

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#656]
In the table browser, you can click on the left of the search bar and it displays some kind of pop up with the current query.
![Where you click](https://i.imgur.com/34yxknx.png)

There could be some action like Ctrl+click that would open the query in a SQL editor instead of copy/pasting the query.

**Comment by serge-rider** [comment]
Ok, I like this.
Note: opened SQL editor won't be linked with a physical file. 
It can be used as a SQL console but it can't be saved.
