### ISSUE TITLE
Triggers in Firebird

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#659]
Only one trigger is shown in firebird, which is transaction_commit. This trigger seems to be part of dbeaver

**Comment by serge-rider** [comment]
Global triggers are database-level triggers (they are definitely not part of DBeaver).

To see table triggers in have to go to a table:
![fb_triggers](https://cloud.githubusercontent.com/assets/6398845/17644567/04820a7e-6193-11e6-8f4b-2db5d070b89d.png)
