### ISSUE TITLE
Create, Alter, Truncate DDL in right click menu

### ISSUE THREAD

**Issue by adamos42** [serge-rider/dbeaver#66]
It will be helpfull if in every database tables, views, procedures, functions, and triggers (generators in firebird) can have a generate DDL function in right click menu which open a new script with the DDL.

**Comment by adamos42** [comment]
This is a easy feature, just grab the source from the metadata and insert in a new script tab with a contextmenu item :)

**Comment by serge-rider** [comment]
It is not so easy. I need to refactor existing API to be able to extract DDL in unified way. Also some objects have multiple DDLs (e.g. Oracle packages).

**Comment by adamos42** [comment]
Ooh, then I apologize for my comment earlier, I did not know that the Objects in the tree does not have a method what can return the Source DDL.

**Comment by serge-rider** [comment]
Generate SQL command shows objects DDL (in 3.7.3 it can show DDL for multiple objects).
