### ISSUE TITLE
"Edit procedure" option in the Database Navigator tab shows cached code content instead of re-fetching it from the database which may revert the code to an obsolete state.

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#660]
If an existing procedure/function is edited outside the designated code editor window in way of executing a normal DDL script in a simple SQL Editor window (create or replace procedure/function ...) its content remains obsolete in the cache and the next time you click on the same procedure/function in the Database Navigator, you get the old code content which causes regressions unless you refresh the DB Navigator tree view every time you execute a DDL in a SQL Editor (since you don't get the actual code when you choose to edit the object's code).
I believe this is a design bug and the current behavior should be amended so the code should be fetched on edit instead of using cached content.
BR,

**Comment by serge-rider** [comment]
I'm still not sure how to handle this.
Procedure source is just a sort of metadata (like column names/types, set of constraints, etc). DBeaver caches all metadata until you refresh it. I've added procedures text refresh for MySQL, PostgreSQL, Oracle and Generic drivers  (you can use f5 in database navigator tree).

**Comment by gogosofta** [comment]
just refresh the code on 'edit' ;)

**Comment by serge-rider** [comment]
I don' think that refreshing procedure (or any other object) every time you open an editor is a good idea. Sometimes it takes much time.

I've added extra preference. After enabling DBeaver will refresh objects (procedure, table, etc) from database before actual editor open.

![refresh-editor-prefs](https://cloud.githubusercontent.com/assets/6398845/18410160/deb8b884-7762-11e6-9e8f-eb9b5ccab1ee.png)

**Comment by gogosofta** [comment]
Way to go!  Perfect!
Thanks a lot!

BR,
Georgi
