### ISSUE TITLE
Filtering tables in the table window

### ISSUE THREAD

**Issue by your-mirror** [serge-rider/dbeaver#661]
Some times ago I wrote about HeidiSQL filtering search for tables. I think it's a cool feature that allow to simple find required table. I agree with you, that it isn't logic to do it in left panel, but I think it possible to add it in a table window. 

So, I see two ways how to realize it.
1. When you clicked ctrl+f  you will see only those tables which went through a filter. I think it allow to find required table faster then current method when you highlight a table by green color.
2. It works as in the previous example, except you should click shift+ctrl+f. So you can use ctrl+f or ctrl+shift+f where ctrl+f will still work to highlight tables by color and ctrl+shift+f will filter result.

I ask you to think about it! :)

**Comment by majkinetor** [comment]
+1

You should rename this to 'filtering tables in table window'

**Comment by serge-rider** [comment]
Agreed, that makes sense.
And will make UI more consistent.

**Comment by serge-rider** [comment]
I'll keep only "filter" search (first one). I don't want to overcomplicate simple feature.
Let's see how it will go..
