### ISSUE TITLE
Problem query and multiple icons

### ISSUE THREAD

**Issue by pablim** [serge-rider/dbeaver#665]
When I create a statement with start transaction and rollback or commit (like a image) and I select the statement and I execute with ctrl+Enter, occurs the problem. When I only ctrl+Enter on statement, it execute only the inner select.

Note also the multiple icons when I open a New SQL Editor. I am using Ubuntu.

Thanks.
![problem-query](https://cloud.githubusercontent.com/assets/11844740/17608704/a9bb842e-6004-11e6-8a6d-0930da11d59e.png)

**Comment by pablim** [comment]
The SGBD is MySql.

**Comment by carlosjrcabello** [comment]
Hi there,

If you're just querying you don't need use transaction blocks.

Anyway, you also can use transaction scopes from combo on side of databases
combo.

Be careful, starting transactions at dbeaver, others apps that are using
this database can get errors from locked rows.

**Comment by pablim** [comment]
Hi Carlos, I did just a test with the query, just for see whether the transaction went executed and the error happened.
