### ISSUE TITLE
Freezing on queries with lots of parentheses

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#666]
I've got some queries that have excessive numbers of parentheses, and when I run some of them, dBeaver completely freezes and requires killing and restarting.  After some experiments, at around 15 or 16 levels nested parentheses, my machine becomes unresponsive for about a second, and every level you add after that roughly doubles the amount of time it's unresponsive.  At 20 levels, it freezes for about 30 seconds, etc.

    select CURRENT_TIMESTAMP where (((((((((((((((1=1))))))))))))))) -- 15 levels

I'm trying to refactor some queries that have up to 29 levels, which I guess would eventually run, but dbeaver freezes for too long for me to wait.

**Edit:** For the record, I'm using dbeaver 3.7.2 with postgresql 9.4.1.4.

**Comment by serge-rider** [comment]
This is JSQLParser issue (https://github.com/JSQLParser/JSqlParser/issues/215)
I'll update it in the next DBeaver version, thanks for report.
