### ISSUE TITLE
Not latest data on table refresh

### ISSUE THREAD

**Issue by pquerner** [serge-rider/dbeaver#668]
I have an application which sets a flag to 1 if its running. In phpMyAdmin I can see the flag being set to 1. In DBeaver, after I hit "Table Refresh" button I can only see value "0".
How can I force refresh the data?

**Comment by serge-rider** [comment]
Maybe you are in transactional mode. You won't see changes until you will end current transaction (with commit or rollback).
You can switch to auto-commit mode (in the main toolbar or main menu).

**Comment by pquerner** [comment]
Yes, you're right. Its working when I switch it to auto-commit mode.
Is there a way to default this option ?

**Comment by serge-rider** [comment]
Yes, you can set default on connection properties page "General".
