### ISSUE TITLE
Search in files support

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#669]
Hi,

Is it possible to add a feature that search a word or a regular expression in SQL files, in a selected directory? The result should be the file(s) name(s) and the corresponding line(s). A clic on the corresponding result could open the file at the corresponding line.

Thanks a lot in advance,

cedric

**Comment by majkinetor** [comment]
Search could also be extended to scan DDL. If #672 gets implemented DBeaver should only export database domain to DDL and add this generated file to search set. This DDL search would be very nice feature as it occurs frequently that somebody asks what tables for example have specific columns or specific lines in stored procedures.

**Comment by serge-rider** [comment]
I'll try to reuse Eclipse file search for that. It understands regexes.
To afford that I'll need to refactor existing search pages (make them Eclipse compatible).
