### ISSUE TITLE
Flat file (csv) with Byte Order Marker messes up the name of the first column

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#670]
If you try to "open" a csv that has a utf [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) using the flat file connection type, it puts a few garble characters at the beginning of the first column name like `ï»¿"column1"`.

The file I found about about this on was from a "Export Restultset" operation to the csv file, so dbeaver knows how to write the BOM, but not consume it, I guess.

Opening the file in vim and running the `:nobomb` command (then saving it) removes the mark and everything works fine.

**Comment by serge-rider** [comment]
Looks like CSV JDBC driver (http://csvjdbc.sourceforge.net/) doesn't support BOM by default. There is nothing I can do with this.
But you can disable BOM in DBeaver CSV export (there is a special option for that in export wizard).

**Comment by antoniustefan** [comment]
Same issue occurs when trying to import a CSV file that has BOM using the Data Transfer wizard.
Is that also because of the JDBC CSV driver?
Thanks!

**Comment by serge-rider** [comment]
According to https://sourceforge.net/p/csvjdbc/feature-requests/103/ CSV JDBC driver supports BOM (since version 1.0.35).
