### ISSUE TITLE
Zoom editor with CTRL+- or CTRL mouse wheel.

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#671]
This is standard behavior of majority editors. There is a 'Zoom' shortcut but it doesn't seem to do anything.

**Comment by serge-rider** [comment]
This feature (or very similar) is shipped with Eclipse Neon (https://www.eclipse.org/eclipse/news/4.6/M4/#text-zoom-commands). It'll be automatically included in DBeaver once we'll migrate to 4.6. 
But I'm not going to do this in near few months (because of Java 8 dependency).

Maybe I'll migrate EE version first.
I'll set 4.0 milestone (most likely this version will be based on Eclipse Neon).

**Comment by majkinetor** [comment]
Yeah, that is the exact feature.
The concrete date is irrelevant as long as it gets there eventually. Thanks.

**Comment by allanlaal** [comment]
I was just about to propose this :+1:

**Comment by Lonniebiz** [comment]
I'm looking forward to this feature in 4.0:
http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1826

**Comment by ds0nt** [comment]
I also need this. I have a 4k laptop, and dbeaver is one of those applications I have to change my resolution to use, instead of just zoom in and out.

Cheers!

**Comment by serge-rider** [comment]
Zoom support validated after Eclipse Neon migration.
See it in DBeaver 4.0.

**Comment by Lonniebiz** [comment]
I'm not yet seeing Ctrl-scroll_wheel-zooming in 4.0.

**Comment by serge-rider** [comment]
It is `CTRL+=`, `CTRL+-` or `CTRL+SHIFT+` gray +/-.
This is supported by Eclipse 4.6 out of the box. Unfortunately they didn't implement zoom with mouse wheel (maybe because of differences in native SWT implementations).

**Comment by ephetic** [comment]
Is there a similar pending feature for zooming in the result set grid?

**Comment by serge-rider** [comment]
@ephetic No. Please create separate feature request (I like this, so it has a good chance to be implemented in one of next versions).

**Comment by Lonniebiz** [comment]
I submitted another bug, where I'm specifically focusing on the `ctrl+mouse-scroll-wheel` aspects of this general functionality:
https://github.com/dbeaver/dbeaver/issues/837#issuecomment-647161036
