### ISSUE TITLE
Database export - Pattern - List of variables

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#673]
Can you add list of variables for File name pattern in modal window __Database export__? There is no list which presents all available variables for pattern.

Can you add reset button to change current __File name pattern__ to its original format?

**Comment by serge-rider** [comment]
Makes sense. I'll add tooltip and and content assistance in this field.

PS Allowed variables are {table} and {timestamp}.

**Comment by MatyCZ** [comment]
I can`t see any tooltip and content assistance doesn`t work.

Is there something to change in settings or how it should work?

**Comment by serge-rider** [comment]
I've just realized that you meant MySQL db export.
Fix was done in general db export wizard.
