### ISSUE TITLE
Data Transfer: Ability to save settings as default for Project

### ISSUE THREAD

**Issue by conceptrat** [serge-rider/dbeaver#676]
Currently it appears that settings presented in the Data Transfer dialogs are saved to the Workspace not the individual projects.

It would be great if there was an option to save the settings for the Project using something similar to how you can save settings for the datasource by ticking the "Datasource ... settings" box in the Connection properties dialog.

Alternatively could variable substitution be added to the Directory field, much like the File name pattern field to allow for things like ${PROJECT_LOC}?

I can't seem to attach any files (jpg,png or zip) :(

**Comment by serge-rider** [comment]
Do you mean project or connection specific options?

BTW you can attach files/screenshots using drag-n-drop in the comment area.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
