### ISSUE TITLE
Highlighter doesn't support all MySQL comment types

### ISSUE THREAD

**Issue by DanMan** [serge-rider/dbeaver#678]
Up to DBeaver v3.7.2, MySQL comments starting with a `#` are not picked up by the highlighter. Only those starting with `--` or enclosed by `/* */`. MySQL also deviates from the standard in that it needs an empty space after the `--` sign.

https://dev.mysql.com/doc/refman/5.7/en/comments.html

**Comment by serge-rider** [comment]
Thanks for  report

**Comment by DanMan** [comment]
YW. But what about the space needed after the double-dash? It's misleading that a line without the space is displayed like a comment, even though it's not from MySQL's perspective. Might lead to SQL being executed that the user thought was a comment, judging from the highlighter.

**Comment by serge-rider** [comment]
Yep. Forgot about that.
Fixed.
