### ISSUE TITLE
Issues with SOCKS proxy

### ISSUE THREAD

**Issue by wavexx** [serge-rider/dbeaver#679]
I'm trying to connect to a postgresql DB via a SOCKS proxy, but can't. I'm using DBeaver 3.7.2 on Debian (with libpostgresql-jdbc-java - jdbc4 driver).

I can make a regular connection and everything works fine. However, if I switch to a SOCKS proxy, it behaves as if no proxy has been set: the proxy server is never contacted (inspected with tcpdump). Hostname resolution is also performed locally, which shouldn't happen, but I guess this can also because the proxy is not being used at all.

There's also an additional issue in that the socks proxy I'm using doesn't need authentication (as such, I just provide a dumb username/password). Although not an issue, if would be nice if authentication could be made optional.

Any idea why the setting has no effect? Is this supported on linux?
Thanks.

**Comment by wavexx** [comment]
If I manually set the socks proxy through _JAVA_OPTIONS (-DsocksProxyHost/Port) it works (all connections get gated through the proxy, which is obviously not wanted).

**Comment by serge-rider** [comment]
Seems to be a PostgreSQL specific issue.
Thanks for report.

**Comment by serge-rider** [comment]
PostgreSQL initiates socket connection in a separate thread. This doesn't let DBeaver to determine connection configuration for the socket address.
I'll try to find some solution though.
