### ISSUE TITLE
The "find/relace" dialog misbehaves when editing procedural code.

### ISSUE THREAD

**Issue by gogosofta** [serge-rider/dbeaver#68]
Most of the dialog's controls get disabled if you click in the code editor (while the dialog is visible) which makes further searches/replacements impossible.
It only happens when editing procedures/functions/triggers and not in the SQL editor window.
In my experience, it's always behaved this way (in all versions of DBeaver I've used so far).

**Comment by serge-rider** [comment]
Problem was in incorrect focus tracking.
Generally this issue is fixed although there could be some issues if you have multiple source tabs (e.g. in Oracle packages). These issues can be handled by reopening search dialog.
