### ISSUE TITLE
Incomplete list of postgres data types

### ISSUE THREAD

**Issue by wavexx** [serge-rider/dbeaver#680]
I'm trying to create a new table through "Create new table ... Create new column ... ".

I'd like to use the datatypes available in postgres here (such as integer, serial, etc), but the "Data type" dropdown doesn't contain them, and as such I'm even prevented to type them in.
When I write 'integer' and just press enter, my text is just discarded.

The data type list dropdown is also *very* long, and cannot be searched by pressing the initials when activated (so long it's a bit pointless, maybe autocomplete would be a better choice here).

Can I define my own types somewhere, or I should just revert to plain SQL?

**Comment by serge-rider** [comment]
Yep, PostgreSQL data types management has to be improved.

**Comment by serge-rider** [comment]
I've added data type aliases support (serial*, integer, bigint, etc). But in fact serial/integer/etc aren't real PostgreSQL data types. They are aliases.
Serial is int4 with auto-assigned default value (next_var of corresponding sequence). Serial makes sense only at column creation time.

Now DBeaver will resolve aliases (and convert it to real data types) in column type edit combo. But I'm still thinking about better support of aliases. I can try to keep alias for new objects (and then use them in DDL)..

Any thoughts?

**Comment by serge-rider** [comment]
Well, for now I'll keep this as is (just type aliases support).
In future PG type system can be improved more significantly.
