### ISSUE TITLE
Bug: Query returns nulls in DBeaver and not other clients

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#681]
The following query returns nulls in DBeaver but not other clients

```
select
  t.*,
  CAST( CAST(t.date_key AS CHAR(8)) AS DATE FORMAT 'YYYYMMDD')
from schema.test_table as t
```

looking at the tooltip it looks like dbeaver is confused on the type of the result given that its showing the datetime icon but hovering says integer?

![image](https://cloud.githubusercontent.com/assets/9246654/17978121/6cd73cec-6aa9-11e6-9bb1-608321aae0ee.png)

```
CREATE MULTISET TABLE schema.test_table ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      date_key INTEGER NOT NULL
     )
no primary index;
```

```
insert into schema.test_table values (20100101);
insert into schema.test_table values (20100102);
insert into schema.test_table values (20100103);
insert into schema.test_table values (20100104);
```

**Comment by serge-rider** [comment]
What database?

**Comment by r-richmond** [comment]
Teradata

**Comment by serge-rider** [comment]
Unfortunately I can't test it.
Please attach debug log, maybe there is something related to this problem.

**Comment by r-richmond** [comment]
I've attached 3 logs

`.log` appears to have the relevant errors at the bottom however there appeared to be a lot of uncaught exceptions.

Also I noticed that there were several query logs for loading tables, columns, indexes, primary keys, imported keys ran after my sample query. I'm assuming that this is for click through functionality? (if thats all its for is there a place I can turn this off?)

[logs.zip](https://github.com/serge-rider/dbeaver/files/437789/logs.zip)

**Comment by serge-rider** [comment]
This is what causes problem with date values:
```
Unrecognized type 'java.sql.Date' - can't convert to numeric
```
DBeaver thinks that this column has numeric data type. This is because you second column has the same alias as the real table column (date_key). DBeaver tries to discover real attribute data type from database metadata whenever it is possible. Smarty pants.

Workaround - set some alias for your expression.
And I'll think how to handle this problem better..

**Comment by r-richmond** [comment]
makes sense.. given that here is code that reproduces the issue in oracle

```
create table schema.test_table as select 20100101 as date_key from dual;

select
  t.*,
  to_date(cast(t.date_key as varchar(8)),'YYYYMMDD') as date_key
from schema.TEST_TABLE t;
```
