### ISSUE TITLE
Tooltip contrast

### ISSUE THREAD

**Issue by adridev** [serge-rider/dbeaver#682]
Hi, 

I am having issues with Eclipse tooltips. The text in tooltips is not visible.

ENV: 
Manjaro 4.4.19-1
KDE Plasma 5.7.3
Theme Maia (also with others)

Is there any option I can edit to make it visible? I try changing the gtk.css from my Manjaro theme without results (my first time editing a GTK theme).

Regards.

**Comment by serge-rider** [comment]
Seems to be an Eclipse issue:
http://askubuntu.com/questions/1620/how-to-fix-unreadable-tooltips-in-eclipse-helios
