### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#683]
Would it be possible for the results pane and the sql editor to support horizontal scrolling with a tilting mouse wheel?

**Comment by serge-rider** [comment]
This feature has to be supported by Eclipse framework first. For now it doesn't.
http://stackoverflow.com/questions/2119184/horizontal-scrolling-with-the-scrollwheel-in-eclipse

I'm afraid there is nothing I can do.

**Comment by ygoe** [comment]
Is there a bug somewhere in the Eclipse project that tracks this? The discussion you referenced has an unclear question that others likely have misunderstood. There isn't a lot knowledge about tilting mouse wheels out there so many probably can't imagine what that is. I'd rather ask myself if Java can do that at all.

**Comment by JohannesBeranek** [comment]
Same issue with an mx master 3 using the second scroll wheel. Interestingly I can see something like an old style scroll bar pop up exactly where the horizontal one is while I try to scroll horizontally, and it also actually moves, but jjumps back to the position of the "real" bar all the time again and the view itself just stays as it is, so somehow this to me looks more like a bug than something that's not supported.
