### ISSUE TITLE
Oracle: Unknown host specified 

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#684]
After update to 3.7.3 get this error while connecting to DB

> IO Error: Unknown host specified 
>   oracle.net.ns.NetException: Unknown host specified 

![image](https://cloud.githubusercontent.com/assets/9958813/18046069/c9516a5a-6dde-11e6-9e92-ed77698f7d05.png)
tnsnames.ora placed at default location C:\app\username\product\12.1.0\client_1\Network\Admin\

**Comment by serge-rider** [comment]
Check actual connection URL (you can see it in Properties view after clicking on your connection in Database Navigator).
Does it look correct? 
Can you connect using Basic or Custom connection type?

**Comment by infectormp** [comment]
No, i can't connect using Basic or Custom connection type, because DBeaver don't see host.
![image](https://cloud.githubusercontent.com/assets/9958813/18047737/12566cac-6de7-11e6-9e81-0ee5d25e7623.png)

After i set TNS name path, connection work normaly. 
Look like DBeaver don't catch old tnsnames.ora path after update.

**Comment by serge-rider** [comment]
I see.
Could you say how "old tnsnames.ora path" was resolved before - is it in ORA_HOME or in TNS_ADMIN env variable or you set Oracle client path manually?

**Comment by infectormp** [comment]
I set Oracle client path manually.
I not have ORA_HOME or in TNS_ADMIN in my env.

**Comment by pyhedgehog** [comment]
I have problem that looks same. But why DBeaver doesn't see host if I use Basic/Custom?
**Does DBeaver uses proxy** from environment (`%http_proxy%`, `%all_proxy%`) or from IE settings?

**Comment by serge-rider** [comment]
No, DBeaver doesn't use any proxies. Moreover it is not DBeaver but Oracle driver initiates the connection.

In fact TNS name is not a host name, it is just an alias in TNSNAMES.ora file. Trying to enter TNS name in host field most likely will result in "Unknown host" error. Real host name is in tnsnames.ora file. DBeaver should parse this file and extract real connection parameters - but for some reason it fails..

**Comment by serge-rider** [comment]
Please reopen this issue if you will have any new information.

**Comment by pyhedgehog** [comment]
@serge-rider: After reset of connection settings it works for me. 
@infectormp: What about you?

**Comment by infectormp** [comment]
@pyhedgehog After i set TNS name path, connection work normaly.

**Comment by infectormp** [comment]
but i need do this for all oracle connections that was working in 3.7.2
