### ISSUE TITLE
Update function error

### ISSUE THREAD

**Issue by SZubarev** [serge-rider/dbeaver#686]
Trying to update DBeaver EE (Windows 8.1 64bit) version 3.7.2 to 3.7.3 using built-in update:
1) "Check for update" - it shows screen with 3.7.3 information
2) Press "Update" - shows "No updates found"

Ok, trying to use "Install new software" menu instead:
3) It shows standard screen with updated plugins - "Select All" and press "Next" and got error:

`Your original request has been modified.
  "DBeaver DB2 Extension" is already installed, so an update will be performed instead.
  "DBeaver MySQL Extension" is already installed, so an update will be performed instead.
  "DBeaver Generic Extension" is already installed, so an update will be performed instead.
  "DBeaver Oracle Extension" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Runtime 3.7.3 (org.jkiss.dbeaver.runtime.feature.feature.group 3.7.3)
  Missing requirement: DBeaver Eclipse Plugin 3.7.3 (org.jkiss.dbeaver.core.eclipse 3.7.3) requires 'bundle org.eclipse.search 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Runtime 3.7.3 (org.jkiss.dbeaver.runtime.feature.feature.group 3.7.3)
    To: org.jkiss.dbeaver.core.eclipse [3.7.3]`

Ok, trying to update DBeaver Runtime first and got error:

`Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Runtime 3.7.3 (org.jkiss.dbeaver.runtime.feature.feature.group 3.7.3)
  Missing requirement: DBeaver Eclipse Plugin 3.7.3 (org.jkiss.dbeaver.core.eclipse 3.7.3) requires 'bundle org.eclipse.search 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver Runtime 3.7.3 (org.jkiss.dbeaver.runtime.feature.feature.group 3.7.3)
    To: org.jkiss.dbeaver.core.eclipse [3.7.3]`

**Comment by djjaysmith** [comment]
I have had the same issue as reported above, but with version EE (Windows 8.1 64bit) version 3.6.10.

**Comment by serge-rider** [comment]
org.eclipse.search extension is now included in dbeaver core. So this issue will go after 3.7.4.
