### ISSUE TITLE
Don't popup error dialog when user cancels request

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#687]
If you press the cancel button while a query is running, it pops up a dialog saying (this is with postgresql, not sure if that matters):

Query execution failed
Reason: SQL Error [57015]: ERROR: canceling statement due to user request

Since I'm the one that canceled it, I'd rather not have to see and dismiss the error dialog telling me that I canceled it.

**Comment by serge-rider** [comment]
That's not so obvious. Some drivers doesn't support statement cancel. In other cases cancel leads to query hang or execution error. Sometimes even to a disconnect.
Main problem is there is no universal error code for successful statement cancel. Different drivers returns different errors, sometimes without any error code/status at all. So it is practically impossible to determine what actually happened (at least in a universal way).
Showing error message is just a simple and unambiguous solution. I'd prefer to leave it as is for now.
