### ISSUE TITLE
Firebird - Domain support

### ISSUE THREAD

**Issue by rml1997** [serge-rider/dbeaver#69]
Firebird uses domains to create reusable column types tied to specific restrictions. I'd like to be able to view and edit these within the database like in flamerobin and to display the domain, rather than the underlying type, within the ddl

**Comment by Seralto** [comment]
Me too.

**Comment by rml1997** [comment]
SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS; will give you the domain

**Comment by MatheusAmelco** [comment]
Really, domains support would be great! ;)

**Comment by serge-rider** [comment]
Could you post some DDL with domain definition/data insert.
I'm not very familiar with Firebird domain model. Looks like every table defines explicit domain type (similarly to PostgreSQL).

**Comment by MatheusAmelco** [comment]
Of course...
```sql
CREATE DOMAIN DM_CNPJ AS CHAR(14);
CREATE DOMAIN DM_LOJA_STATUS AS SMALLINT DEFAULT 0 NOT NULL CHECK (value in (0, 1, 2, 3, 4, 5));
```

Creating a table using domains:
```sql
CREATE TABLE LOJA (
  ID INTEGER  NOT NULL  ,
  CNPJ DM_CNPJ  NOT NULL  ,
  LOJA_STATUS DM_LOJA_STATUS  NOT NULL  ,
PRIMARY KEY(id)  
);
```

And the insertion of data in the table is like default insertion, being limited to the characters accepted by the domain...

Something like this:
```sql
INSERT INTO LOJA (ID, CNPJ, LOJA_STATUS) VALUES (1, '9999999999999', 4)
```

**Comment by rml1997** [comment]
With the new data types view, I think this might be easier to do now

**Comment by serge-rider** [comment]
Yes, I also hope so.

RDB$FIELD_SOURCE provides only struct data types info.
I didn't find a way to obtain full domain info from system tables :(

**Comment by serge-rider** [comment]
Closing. 
As there is no good way to solve this using JayBird driver. Or I didn't find it.
Probably we'll need to make fully-functional Firebird extension (like for MySQL or PostgreSQL) which will include this feature along with other Firebird-specific stuff.
If anybody interested - please create feature request.

**Comment by rml1997** [comment]
I think you're looking for RDB$FIELDS.
These are the important fields (to me)
Hope this helps!

SELECT 
-- t.RDB$TYPE_NAME
f.RDB$FIELD_NAME,
f.RDB$FIELD_LENGTH,
f.RDB$FIELD_TYPE,
f.RDB$FIELD_PRECISION,
f.RDB$FIELD_SCALE,
f.RDB$NULL_FLAG,
f.RDB$DEFAULT_SOURCE,
f.RDB$VALIDATION_SOURCE,
f.RDB$COMPUTED_SOURCE,
f.RDB$CHARACTER_LENGTH
FROM rdb$fields f 
-- The line below can be used to get t.RDB$TYPE_NAME of the base type for the field if field_type isn't enough
-- LEFT JOIN RDB$TYPES t ON t.RDB$TYPE = f.RDB$FIELD_TYPE AND t.RDB$FIELD_NAME = 'RDB$FIELD_TYPE'
WHERE f.RDB$FIELD_NAME NOT STARTING WITH 'RDB$';

**Comment by rml1997** [comment]
This page might help
https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref-appx04-fields.html

**Comment by rml1997** [comment]
@serge-rider any chance of reopening this issue?

**Comment by serge-rider** [comment]
Yes.
Although I still don't know where to get information about simple domain types like
```sql
CREATE DOMAIN DM_CNPJ AS CHAR(14);
```

**Comment by Sargul** [comment]
Information should be in 
[RDB$FIELDS](https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref-appx04-fields.html)

Usage of these domains will be shown in [RDB$RELATION_FIELDS](https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref-appx04-relfields.html)

**Comment by serge-rider** [comment]
I'll move this to 4.2.1.
Maybe domain types metainfo will look simpler for on the second try.

**Comment by serge-rider** [comment]
Domain types metainfo (in read-only mode) is here.
Will try to extract source data type info from columns metadata (JayBird JDBC doesn't provide this info, I'll try some workarounds).

**Comment by serge-rider** [comment]
I've added a workaround for columns domain type. There is an extra property `Domain type` in FB table columns. It can be enabled in column configuration:
![image](https://user-images.githubusercontent.com/6398845/30521757-5f1e169c-9bcd-11e7-8d20-d1f6a8eeabbf.png)

Thus you can see column type in source form:
![image](https://user-images.githubusercontent.com/6398845/30521751-47a2bd9c-9bcd-11e7-9af3-d6619e4d5b2f.png)

Note: DBeaver will make a separate SQL query for each column to extract this value. Didn't find better workaround for JayBird driver (better way is to write fully functional extension which will read all FB metadata by itself).
