### ISSUE TITLE
Eclipse plugin dropdown glitch

### ISSUE THREAD

**Issue by michael-82** [serge-rider/dbeaver#691]
I am using the standalone version for a while now, and there it works flawless to click on a boolean value (or an enum) and choose from the drop down menu.

However, in the eclipse plugin (Version 3.7.3) there's just a short flicker of the dropdown, and then it disappears. Changing it via "edit cell" is working without a problem.

**Comment by serge-rider** [comment]
Can't reproduce.
Maybe DBeaver conflicts with some other your Eclipse plugins?
Could you test it with fresh Eclipse installation?

**Comment by michael-82** [comment]
I just downloaded a fresh copy with nothing else installed (Eclipse Neon for JEE Development). The same behaviour as described.

If it is of any importance, I'm on ubuntu gnome 16.04

**Comment by michael-82** [comment]
Sorry for the late reply. I checked it in windows 10 and there the problem doesn't occur.

**Comment by serge-rider** [comment]
Maybe this is a GTK issue.
The only difference (as far as I know) between DBeaver standalone and Eclipse on Linux is that DBeaver starts with parameter "--launcher.GTK_version 2".
You could try to add two lines
```
--launcher.GTK_version
2
```
in eclipse.ini. Maybe it'll help.

**Comment by michael-82** [comment]
That fixed it. Thank you!
