### ISSUE TITLE
Value View Panel: save command shortcut

### ISSUE THREAD

**Issue by kst83** [serge-rider/dbeaver#692]
Since the release 3.7.3 it seems the value view panel doesn't support editing anymore.
Will this be back? It was one of my most used features.
Btw, if it is coming back, how about adding a ctrl+return hotkey for saving the value?

**Comment by serge-rider** [comment]
No, value view panel still supports editing and always will.
There is a small bug - grid contents isn't refreshed after value change, it is already fixed and fix will be included in the next version.

And yes, we need some shortcut for saving..

**Comment by kst83** [comment]
That's good news, looking forward to the next release.

**Comment by serge-rider** [comment]
BTW besides "Save" shortcut (ctrl+s by default) I'll add auto-save feature (can be toggled) so grid values will be updated in sync with edited value.
