### ISSUE TITLE
I can't modify an edited cell on a resultset

### ISSUE THREAD

**Issue by Wespontin** [serge-rider/dbeaver#693]
I used the odbc bridge.
On a resultset, the cell takes the focus but i can't delete, insert or update any character.
I could do this before some update version...
![resultcell](https://cloud.githubusercontent.com/assets/21580607/18166318/cca07e8a-704a-11e6-8142-f973ecf730c6.jpg)

**Comment by serge-rider** [comment]
What database?
Is this behavior the same for all SQL queries or you can edit some results and can't edit others?
Can you edit cell values in table data editor?

**Comment by Wespontin** [comment]
Thanks for your reponse.
This is a Sybase DataBase (SQLAnyWhere).
The behavior is the same for all SQL queries and all type of data.
What do you mean with "table data editor"? I can't see any table of DB in interface.
![interface](https://cloud.githubusercontent.com/assets/21580607/18167172/61d33d40-704f-11e6-861c-c9c5a0a0b849.JPG)

**Comment by serge-rider** [comment]
I meant data viewer in table editor. But, obviously, there is no such thing because you have empty table list.
Is this a normal situation? Maybe it is a yet another bug in DBeaver?

**Comment by Wespontin** [comment]
I try with the Sybase Driver.
I have now the data in the "table data editor" but the problem is the same.
![date editor](https://cloud.githubusercontent.com/assets/21580607/18196367/3fc845a4-70f1-11e6-9939-6e9c9658bd88.JPG)

**Comment by serge-rider** [comment]
This looks like a bug but I can't reproduce it. At the moment I don't have test instance of Sybase.

For some reason DBeaver can't detect to what source database table result columns belong. This shouldn't happen ever when you browsing particular table data.

Please check logs for any related errors/warnings (https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by Wespontin** [comment]
I take a look in log file but i didn't see anything about this problem.
I try others plugins like "Quantum DB" and "DBViewer" and the problem is the same.
A friend try with DB Postgress and the problem is the same.
I try with the new Eclipse Neon, and always the same problem.
I don't think that is a DBEaver problem...

**Comment by serge-rider** [comment]
Ok then..
