### ISSUE TITLE
Where do I configure the Internet proxy?

### ISSUE THREAD

**Issue by sekaijin** [serge-rider/dbeaver#694]
Where do I configure the Internet proxy?
I guess the default config uses the proxy configured on the machine.
But the eclipse application does not support our proxy by default.
To allow access to the Internet we must use a different config,  manually set on eclipse.

`Unable to connect to repository http://dbeaver.jkiss.org/update/latest/content.xml
Unable to connect to repository http://dbeaver.jkiss.org/update/latest/content.xml
Connection timed out: connect`

**Comment by serge-rider** [comment]
You can configure proxy for drivers download on Preferences->Database->Drivers page.

There is no proxy config for version update in DBeaver. It is a part of Eclipse framework. I'll add standard Eclipse proxy configurator in one of next versions but for now it is impossible to configure it. 
Workaround: download fresh version from jkiss.org.

**Comment by sekaijin** [comment]
Thank

A+JYT

**Comment by emmanuelvi** [comment]
Hi can I configure the proxy with "Dbeaver Lite", I am blocked, the application is closing before to set the Proxy. (works fine on dbeaver free edition)
