### ISSUE TITLE
Comments increase query time

### ISSUE THREAD

**Issue by bberenz** [serge-rider/dbeaver#695]
Running a query with an inline comment inside of the statement seems to dramatically increase the run time of the query. This is especially noticeable on a larger table where the difference can go from ~20ms without to 5+ minutes with.

On just a 10MB table:
```sql
-- comment outside of query (4ms)
SELECT * FROM table; -- any comment

-- inline comment inside of query (~250ms)
SELECT * FROM table -- any comment
;

-- block comment inside of query (4ms)
SELECT * FROM table /* any comment */
;
```

This affects MySQL & MariaDB, and the latest DBeaver (3.7.3 CE and EE), though it seems several previous releases were affected by this too (3.7.0, 3.6.10, 3.5.9, maybe further).

**Comment by serge-rider** [comment]
Wow, this is interesting. Although I can't reproduce that - in my test environment comment presence doesn't affect performance at all.

Did you try the same in other SQL clients? Maybe problem is on server side.
Could you check Query Manager for statistics?

Also, in case of long running queries (5+ minutes) you can open session manager and check what's going on on the server.

**Comment by bberenz** [comment]
I've only noticed it on larger tables, ones smaller than around 10mb tend to be negligible.

I did try it with Intellij's built in DB console, and on the sql server itself, and neither had this problem with comments.

Here's a run (3 of each) from the Query manager:
```
16:27:54	SQL / USER	SELECT * FROM table_name /* any comment */ LIMIT 0, 200	3 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
16:27:53	SQL / USER	SELECT * FROM table_name /* any comment */ LIMIT 0, 200	2 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
16:27:53	SQL / USER	SELECT * FROM table_name /* any comment */ LIMIT 0, 200	132 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>

16:27:52	SQL / USER	SELECT * FROM table_name -- any comment LIMIT 0, 200	237 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
16:27:52	SQL / USER	SELECT * FROM table_name -- any comment LIMIT 0, 200	225 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
16:27:51	SQL / USER	SELECT * FROM table_name -- any comment LIMIT 0, 200	327 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>

16:27:50	SQL / USER	SELECT * FROM table_name LIMIT 0, 200	4 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
16:27:50	SQL / USER	SELECT * FROM table_name LIMIT 0, 200	3 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
16:27:49	SQL / USER	SELECT * FROM table_name LIMIT 0, 200	4 ms	200	Success	STB - Dev	SQLEditor <Script-2.sql>
```

The session manager shows a state of "Sending data", and the query shows up as
```
/* ApplicationName=DBeaver Enterprise 3.7.3 - SQLEditor <Script-2.sql> */ SELECT * FROM large_table -- any comment LIMIT 0, 200
```
It almost appears as though the `--` is commenting out the implicit `LIMIT 200`.
- - -
Actually, running it with any line after the comment seems to fix the issue, so that might just be it:
```sql
-- 4ms
SELECT * FROM table -- any comment
LIMIT 200;

-- 4ms
SELECT * FROM table
-- any comment
WHERE 1=1;

-- ~250ms
SELECT * FROM table
WHERE 1=1
-- any comment
;
```

**Comment by serge-rider** [comment]
Thanks for details. Now I can reproduce that.
Indeed, problem is in LIMIT clause. DBeaver adds it in the end of MySQL queries and in case of trailing single line comment LIMIT isn't used. I'll fix it in the next version (by using LIMIT on the new line).

Try this workaround: in Preferences->Database->Result Sets disable "Use SQL to limit fetch size". On new MySQL versions it should work fine, explicit LIMIT isn't required.
