### ISSUE TITLE
Hi, how can i connect at my remote Oracle Database

### ISSUE THREAD

**Issue by jomarcoelho** [serge-rider/dbeaver#696]
Hi, how can i connect at my remote Oracle Database.
The machine where I have my Oracle DB is named as W7VM.
I can access remotely using the address http://w7vm:8080/apex/, normally using the user that I have cadastrated before. Everything works by browser.
But, I need to work using DBeaver.
---
I tried to configure using the path: <File> <New> <DBeaver> <Database Connection> <Next> <Oracle>...

But, at the fields:
Host:
Port:
Database:
User Name:
Password:

Then, when I try to connect an message is displayed telling me:

IO Error: The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
    java.net.ConnectException: Connection refused: connect

Please, has some youtube video teaching how do I it work?
 Maybe, an manual with pictures...

**Comment by serge-rider** [comment]
You just need to enter valid database parameters.
Host may be the same as in web URL (but also may differ) but port is usually= 1521.
You can get database name from web UI.
User name and password are the same.

**Comment by gmeena** [comment]
I am also having the same problem.
@jomarcoelho did you get the solution?
Thanks
