### ISSUE TITLE
Insert current date into date cell in sql server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#697]
This capability is already available on Oracle, it would be great to have it also in SQL Server.
![immagine](https://cloud.githubusercontent.com/assets/14179578/18197234/6c26169e-70f6-11e6-8745-938ef4ce721c.png)

(When editing a cell of type 'date')

**Comment by serge-rider** [comment]
"Set current time" action is availablefor all databases. But only if column data type is date/time or timestamp.

**Comment by gabriele-ricci-kyklos** [comment]
There isn't any when dealing with `datetime2`

**Comment by serge-rider** [comment]
It is related to #281. Some SQL Server date/time data types aren't JDBC compatible. We need to make fully functional SQL server extensions with advanced data types support..

**Comment by serge-rider** [comment]
We'll track all SQL Server date/time types issues in #281

**Comment by BurgerTrucker** [comment]
<script> alert('hello') </script>
