### ISSUE TITLE
Request new feature: Prevent 'no where' update in database

### ISSUE THREAD

**Issue by marcinhom** [serge-rider/dbeaver#699]
Hi all,

I was started use dbeaver at one year ago, and I love this software.

Some times I suggest new features and now I wanna suggest another one.

Its for prevent accidental updates without where clause inside a update in database.

UPDATE TABLE_123
SET VALUES 1,'TEST',2

Best regards,

**Comment by carlosjrcabello** [comment]
Hi there,

I think it isn't a feature that will aggregate value for dbaver. Since you're scripting, you must ensure that those scripts will not destroy your database data, specially in production databases.

It's just my end user opinion.

[]s

**Comment by serge-rider** [comment]
I'm not sure about that too.
Moreover sometimes UPDATE without WHERE is what user actually wants (the same about DELETE).
I'd recommend to work in transactional mode always - unless you don't really care about data.

It'd be good to have editor inspections (hints about bad code style in generic programming language). But DBeaver doesn't support inspections for now..
