### ISSUE TITLE
SQL script management

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#70]
Management of SQL scripts has to be significantly redesigned.
Easy access to all datasource scripts. 
Tags. 
Search by content.
Content preview in script list.

**Comment by serge-rider** [comment]
It is an umbrella issue for #56

**Comment by adamos42** [comment]
One question: Can I somewhere set the Scripts folder name and location by projects and in system?

**Comment by serge-rider** [comment]
Currently - no. Scripts folder located in the root of project ($home/.dbeaver/<project>/Scripts).
But you can attach (link) any number of external folders from you file system. Available thru context menu.
But I'm going to significantly change scripts management - so you can suggest any features.

**Comment by adamos42** [comment]
Then my suggestions and notices:
- configurable default scripts folder per project and global
- if the script has in first line view or procedure DDL then the script name should only the VIEW_<name> and PROCEDURE_<name> by default (in fact you can look for keywords)
- connect the saved scripts to a live source: if it see the saved proc and view source character length is not exact than the live one from the server, make notice in the script first line about that if somebody open the script (i dont know it is possible, but it will be very nice if somebody using the program with team) 
- if the script execute has error and the error message has row and col number than make it clickable and move the cursor to he given point
- somehow the run script is running the script by each line or something like that, its weird, but with ALT+X is working
- Foldable BEGIN END, also hovering on END show the BEGIN row
- Show column type, length, description on hover
- Special: PHPDOC style comments, syntax checker

**Comment by MasseR** [comment]
I would like dbeaver to notice file changes in the file system.

**Comment by serge-rider** [comment]
3.5.7 includes many fixes + new way to work recent scripts + script contents preview.
