### ISSUE TITLE
Database navigator can not filter objects contains input string?

### ISSUE THREAD

**Issue by javalover123** [serge-rider/dbeaver#701]

**Comment by serge-rider** [comment]
Sorry, I don't get it.
What is input string?

**Comment by javalover123** [comment]
![dbeaver](https://cloud.githubusercontent.com/assets/9191388/18339445/232c5094-75d2-11e6-82be-de5f1c7cf688.png)
like HeidiSQL

**Comment by serge-rider** [comment]
DBeaver doesn't support inline filters. It has a bit more sophisticated filters model. You can configure filter on any navigator node (context menu->Filter->Hide/Show/Configure). You can use LIKE masks in object names.
Also you can open object list (e.g. double click on Tables) and use quick filter there (CTRL+F).

**Comment by javalover123** [comment]
OK
