### ISSUE TITLE
Minor interface misleading fix

### ISSUE THREAD

**Issue by dimitriadisg** [serge-rider/dbeaver#702]
Hello,

just a minor issue here. When you select to order the rows in the table (by clicking the '⇅' icon on the column you wish to order by), a pointing-down arrow appears for ascending order (⇩) and if you click again you'll get a pointing-up arrow for descending order (⇧).

This is misleading, commonly up arrow means ascending and down arrow means descending.

Best regards,
George

**Comment by serge-rider** [comment]
Agreed. The same about filters dialog.
