### ISSUE TITLE
Normal exit not working.  Having to use Emergency Exit

### ISSUE THREAD

**Issue by morridm** [serge-rider/dbeaver#703]
After updating to version 3.7.3 I'm not able to use the normal "Exit" from the File menu.   It will only close if I use "Emergency Exit".

Windows 7 Enterprise 64-bit
Service Pack1

**Comment by serge-rider** [comment]
Please check logs for any related errors (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by morridm** [comment]
I checked my C:\Users\<user>\.dbeaver\.metadata\.log and C:\Users\<user>\.dbeaver\.metadata\dbeaver-debug.log log files.  They do not update with any new information when I click "Exit".

**Comment by serge-rider** [comment]
Umm, any idea how can I reproduce that?
What's your OS?
Is there anything special about your project?

BTW you could try to reset workspace (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace) - sometimes it become broken after version update.

**Comment by morridm** [comment]
I'll try the reset.  If that doesn't work, I'll see what info I can gather
for you.

**Comment by morridm** [comment]
K, I tried the reset but no luck.  I'm running Windows 7 Enterprise 64-bit with Service Pack1.  I have multiple db2 connections.  Attached is my configuration...


[dbeaverconfig.txt](https://github.com/serge-rider/dbeaver/files/463986/dbeaverconfig.txt)

![image](https://cloud.githubusercontent.com/assets/4851907/18387713/d022a73a-7663-11e6-9e26-db592c8a849d.png)

**Comment by morridm** [comment]
Hey,

Well it is fixed now.  I changed my Theme and SQL Editor preferences and clicked apply.  After that normal "Exit" started working again.  

Thanks!

David

**Comment by serge-rider** [comment]
Great.
I've added extra error handling in shutdown hooks, just in case.

**Comment by cloudyster** [comment]
Hi,

I experience the same behaviour as morridm - exit not working. 

I'm running dbeaver 3.7.4 on RHEL6, JDK is a 1.8.0_25
Resetting workspace did not help, nothing to be seen in debug-log.

**Comment by cloudyster** [comment]
Forgot to mention:  changing  Theme and SQL Editor preferences did not help.
Thanks,
Marc

**Comment by eflipsivan** [comment]
Same here..
DBeaver 3.7.4 on Fedora 24 with JDK 1.8.0_101
The error apparently start ocorring after update from 3.7.2 to 3.7.3 and persists on 3.7.4

**Comment by serge-rider** [comment]
How do you perform version update?
What installer do you use (rpm, deb, zip archive)?

In any case - try to remove previous version completely (but don't touch workspace in ~/.dbeaver) and reinstall new one.

**Comment by cloudyster** [comment]
I'm removing the prev. directory completely, and unpack dbeaver-ce-$VERSION-linux.gtk.x86_64.tar.gz, that's it.

**Comment by eflipsivan** [comment]
RPM package.
I had forgotten, after quit it shows this message:

---
JVM terminated. Exit code=1
/usr/bin/java
-jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /usr/share/dbeaver/dbeaver
-name Dbeaver
--launcher.library /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
-startup /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.overrideVmargs
-exitdata 3178017
-vm /usr/bin/java
-vmargs
-jar /usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar

**Comment by eflipsivan** [comment]
"but don't touch workspace in ~/.dbeaver"
No success after remove/reinstall, but ironically after deleting ~/.dbeaver and configure connections "exit" and close button works again! :open_mouth: :grimacing:

**Comment by serge-rider** [comment]
Yeah, I was pretty sure that removing ~/.dbeaver will resolve the problem. But dropping workspace usually isn't an option (because you have lots of artifacts there).
Deleting ~/.dbeaver/.metadata should also help and it is less destructive. Although it contains all downloaded drivers and all UI preferences.

There should be less bloody way top resolve this problem..

**Comment by eflipsivan** [comment]
I believe I have discovered the cause ..

In "Preferences-> General-> Confirmation" has an option "Exit DBeaver," and I understood it was about "confirm exit DBeaver". So I put as "never" to, I thought, quit the application instantly without confirmation prompt "Are you sure?". In this scenario, the error described above occurred.
Checking "always" it worked as expected; both the close button and the "exit" are now usually worked :smile:
Thank you for your attention and the software, and please excuse any inconvenience :sweat_smile:

**Comment by serge-rider** [comment]
Well, this is almost the same as #619.
I'll fix it so setting "Exit DBeaver" to "Never" will be the same as "Always" (means "do not ask").
