### ISSUE TITLE
SQLite over SFTP?

### ISSUE THREAD

**Issue by Otiel** [serge-rider/dbeaver#704]
Is it possible to have a SQLite connection over SFTP/SCP/FTP ?

I have a SQLite database stored on a server. Right now I'm transferring the SQLite file to my computer (via SFTP) in order to access it with DBeaver, then modify the data, then I transfer the file back to the server. That would be neat if it was possible to access the file over some protocol like SFTP.

**Comment by serge-rider** [comment]
SQLite doesn't have network protocol at all. It is an embedded database so it is not possible to work with it by wire in any fashion.
Probably there are some existing "wrappers" which can be installed on server side to operate with SQLite remotely but I'm not aware about that. And in any case it is beyond of DBeaver functionality.

**Comment by Otiel** [comment]
Thanks for the reply, that makes sense.

**Comment by alun** [comment]
SQLite seem to be working with `sshfs` FUSE file system. Although super slow and inefficient and probably WAL won't be working as it's using memory mapped file. But might work in an emergency case.
