### ISSUE TITLE
bind variable is null

### ISSUE THREAD

**Issue by hhamli1** [serge-rider/dbeaver#705]
Using Oracle database and ojdbc6 jar, when I try to execute a query like this:

select * from table where name=:name;

I enter a varchar2 as the name but the generated query is 

select * from table where name=NULL;

The query works fine if I hard-code a value instead of binding a variable.

Thanks!

**Comment by serge-rider** [comment]
Can't reproduce.
What's your DBeaver version?

**Comment by hhamli1** [comment]
3.7.3 Enterprise.  I just figured it out.  When I type in the value and click OK the value is not saved.  I just went back and by accident I typed ENTER key on the field and then it worked.  I guess the UI is a little confusing in that regard.

Thanks for your help.
