### ISSUE TITLE
Update Conflict when closing file Updated from GIT Pull

### ISSUE THREAD

**Issue by hgrod** [serge-rider/dbeaver#706]
When trying to close a file, which I made changes to, but don't want to keep the changes... I received this error:
"The file [filename.sql] has been changed on the file system. Do you want to overwrite the changes made on the file system?" [No/Yes]

This is due to a GIT Pull, which included the file I have open. This is the reason I do not want to save changes, and overwrite what I pulled from GIT. 

If I click "No", it leaves the file open, and does not let me close without saving.
Also cannot open the same file in DBeaver with changes from GIT, since this version is still open.

How can I close it without saving changes??

DBeaver version 3.7.3
OS X Yosemite (V. 10.10.5)

**Comment by serge-rider** [comment]
I'll try to reproduce that in Eclipse.

Possible workaround: you can revert file changes (context menu->File->Revert) and then close it.

**Comment by serge-rider** [comment]
This dialog is a part of Eclipse framework. And it makes sense.
So I think that workaround with Revert changes is the only solution. Also you may disable "auto-save on close" option and just reject to save changes.

**Comment by hgrod** [comment]
@serge-rider , thank you. I don't see the option to disable "auto-save on close". 
Also, is there a way for it to pull from the linked data source, if the linked data source refreshes through GIT, or is the option to revert changes (will that pull the updated version?).

**Comment by serge-rider** [comment]
Preferences->General->Editors->SQL Editor->Auto Save.

I didn't really get it. What is linked data source?

**Comment by hgrod** [comment]
![screen shot 2016-09-08 at 12 05 54 pm](https://cloud.githubusercontent.com/assets/22058455/18360790/adcae8ca-75bc-11e6-9dd3-1525a99b441a.png)

Auto Save turned off. Thanks.

**Comment by serge-rider** [comment]
As far as I know Eclipse Git module (EGit) doesn't support linked folders.

Workaround: you can create/import a project in DBeaver and set project location to a different folder (e.g. where your Git repository was checked out).
Then you can copy/paste all your connections into this new project, set it active and live there all the time.
