### ISSUE TITLE
Postgresql: User pretty_bool=true for pg_get_* functions (that support it)

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#707]
See https://www.postgresql.org/docs/9.4/static/functions-info.html

>Most of these functions come in two variants, one of which can optionally "pretty-print" the result. The pretty-printed format is more readable, but the default format is more likely to be interpreted the same way by future versions of PostgreSQL; avoid using pretty-printed output for dump purposes. Passing false for the pretty-print parameter yields the same result as the variant that does not have the parameter at all.

One of the thing the pretty-print parameter does is to prevent the definition being returned with tons of extra parentheses (which caused #666), the non-pretty version also does lots of explicit type casting, which makes things pretty ugly.  It would be great if that that could be passed in as true (maybe even dependent on a driver preference?).

**Comment by serge-rider** [comment]
Yep, that makes sense. 
However it'll work only for views definition.
