### ISSUE TITLE
Conflicting RefreshCommandHandler

### ISSUE THREAD

**Issue by frankmusolf** [serge-rider/dbeaver#709]
in my log-File very often
```
!ENTRY org.eclipse.ui 4 4 2016-09-08 11:10:47.960
!MESSAGE Conflicting handlers for org.eclipse.ui.file.refresh: {org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerRefresh@2d27b794} vs {org.eclipse.linuxtools.internal.docker.ui.commands.RefreshCommandHandler}

```

regards
Frank

**Comment by serge-rider** [comment]
Looks like it conflicts with Docker plugin.
I'll add extra handler conditions for refresh command.

BTW in what context does it happen? When you press refresh DBeaver navigator view or somewhere else?

**Comment by frankmusolf** [comment]
no special context. eclipse start with dbeaver database navigator view and no action in eclipse
regards
Frank

**Comment by serge-rider** [comment]
Does it still happen in 3.7.4?

**Comment by frankmusolf** [comment]
3.6.10
