### ISSUE TITLE
autocommit results in SQL error when creating a new databas in MariaDB

### ISSUE THREAD

**Issue by grexe** [serge-rider/dbeaver#71]
On a fresh install of the latest (still my favorite;) DBeaver 3.5.4 on Linux x64 4.1.4.1, creating a new database in a fresh MariaDB version 5.5.43-0+deb8u1, with autocommit enabled, I get an error:

    JDBCException: SQL Error [HY012]:  committing transaction on a autocommit connection

The database is still created fine afterwards.

**Comment by serge-rider** [comment]
It is a known issue, will be fixed in the next version.
Thanks for report anyway.
