### ISSUE TITLE
support json view/edit

### ISSUE THREAD

**Issue by zinking** [serge-rider/dbeaver#711]
a feature request.
while it's already usable to use Text Control to achieve this. it will be neater to have a json formatted view of the underlying text and perhaps support editing.

**Comment by serge-rider** [comment]
DBeaver (EE) already supports JSON view/editor for MongoDB documents.
Where do you want to use JSON elsewhere? Edit JSON data type in PostgreSQL?

**Comment by zinking** [comment]
not particularly for which database.
my use case ( and probably others) is storing json data as Blob (raw)/Text in columns and then when selected the column out, would like to use `edit as Text` function to modify the original Blob.

**Comment by serge-rider** [comment]
JSON viewer/editor will be available in EE version 3.7.5
