### ISSUE TITLE
Materialized Views with Indexes

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#712]
In postgresql (at least), materialized views can have indexes.  But properties pane in dbeaver doesn't have a indexes tab, and Generate SQL -> DDL doesn't include indexes (like it does with tables).  Could that be added?

**Comment by serge-rider** [comment]
Will be added in the next version.

**Comment by jk3us** [comment]
Could there also be a DDL tab for Mat Views that include these indexes?  Unless I'm missing something, there's still no way to copy the CREATE statements for them.
