### ISSUE TITLE
Postgresql search proposals

### ISSUE THREAD

**Issue by ems2811** [serge-rider/dbeaver#714]
Hello
DBeaver 3.7.4 x86
Java build 1.8.0_101-b13 (x86)
Postgresql 9.5

When i type "from some_table" and press ctrl + space - DBeaver returns no results
When i type "from public.some_table" and press ctrl + space - DBeaver returns tables match
Is there some kind of setting " default schema " or is it a bug ?

**Comment by serge-rider** [comment]
DBeaver uses PG search path for completion proposals.
Sure, you can change default (active) schema. Just right click on schema name in navigator ans choose "Set Active".

**Comment by ems2811** [comment]
public selected by default scheme , but the problem remains

**Comment by serge-rider** [comment]
It is a bug in PostgreSQL completion processor.

**Comment by ems2811** [comment]
in DBeaver 3.7.5 x86 problem completely opposite
When i type "from some_table" and press ctrl + space - DBeaver returns tables match from active schema
When i type "from public.some_table" and press ctrl + space ("public" scheme is active)- DBeaver returns no results
there are still problems in PostgreSQL completion processor ?

**Comment by serge-rider** [comment]
Yep. That fix broke completion in another place. 
This issue was already fixed in #763, wait for 3.7.6.
