### ISSUE TITLE
Aggregate functions: count of distinct values

### ISSUE THREAD

**Issue by someotherdataguy** [serge-rider/dbeaver#715]
Many times, when working with "dimension" style columns, it is useful to be able to quickly see how many distinct values exist in a column in a result set. Eg, I might only expect two distinct values, in a column containing 10000 rows, but currently I find myself writing "select count(distinct myColName) from ..." - this is slow.

Many thanks

**Comment by serge-rider** [comment]
Good point.

**Comment by someotherdataguy** [comment]
Thanks for adding this, its very handy
