### ISSUE TITLE
Aggregate functions: non-numeric columns

### ISSUE THREAD

**Issue by someotherdataguy** [serge-rider/dbeaver#716]
It would be useful to see min/max/median values for a column that contains text or datetime values.

Many thanks

**Comment by serge-rider** [comment]
Makes sense.
Although I'm curious about text values median. I can calculate it but what is it supposed to mean?

**Comment by someotherdataguy** [comment]
Its the most frequently occurring value. If every single value is different, then I guess you could take the min - or leave blank.

I was hoping that aggregates could give a sense of the distribution of the data values, even for text and dates etc

**Comment by r-richmond** [comment]
@someotherdataguy  you've mixed up the mode & the median.

https://www.mathsisfun.com/definitions/mode.html
https://www.mathsisfun.com/definitions/median.html

**Comment by someotherdataguy** [comment]
You are right, I have. The mode would be the most useful I think. I can't think of a use for a text "median".

**Comment by serge-rider** [comment]
I've added both median and mode. Check them in the next version.

**Comment by someotherdataguy** [comment]
Its excellent and super useful.

Thank you so much.
