### ISSUE TITLE
Resultset metadata view

### ISSUE THREAD

**Issue by someotherdataguy** [serge-rider/dbeaver#717]
I would find it very useful to be able to see the meta data that the database provided as part of the result set. Eg, the datatype of the columns. For example, sometime it is very useful to see if a column was provided as a date type, or a datetime.

Many thanks

**Comment by serge-rider** [comment]
I think this should be a yet another results panel (in addition to value view and aggregate)

**Comment by serge-rider** [comment]
Any thoughts about metadata panel in 3.7.5?

**Comment by someotherdataguy** [comment]
I think its frickin' awesome!

Many many thanks!
