### ISSUE TITLE
How to import CSV file into Oracle database using DBeaver?

### ISSUE THREAD

**Issue by AnnLeeDC** [serge-rider/dbeaver#722]
Hi DBeaver users:

I am trying to import a CSV file into my schema using DBeaver. In MS SQL, this can be done easily using the Import/Export Wizard, but with DBeaver, a simple 1 step is split into many steps and somehow I still cannot figure out how... such a pain!

first I created a Flag File connection and I see I get connected to the CSV file. See below screenshot. 
![dbeaver - csv driver](https://cloud.githubusercontent.com/assets/22154862/18445649/93e65e2a-78ec-11e6-9d30-e533038c6387.png)
![dbeaver - csv connected](https://cloud.githubusercontent.com/assets/22154862/18445652/99bf32d6-78ec-11e6-86d8-eacd0b359130.png)

Then, I tried to import the CSV file... by clicking File->Import, 

![dbeaver - import page](https://cloud.githubusercontent.com/assets/22154862/18445674/b5eeb8aa-78ec-11e6-89d5-da41fedd29bf.JPG)

Next, I saw the Import detail page, I filled in the source CSV file path and file name. then the page asks me to fill in the Into Folder... Why? and What is the Into Folder? I need the csv file to be imported into my own schema, not any folder.. 

![dbeaver - csv import - into folder](https://cloud.githubusercontent.com/assets/22154862/18445748/109fb0ce-78ed-11e6-92b0-a1b05861a578.JPG)

I am confused now.. 

Did I miss something critical here? 

Can anyone help me with the import? thanks!

**Comment by serge-rider** [comment]
Import from file system has nothing to do with database data transfer.

1. Create CSV connection (you already did)
2. Create Oracle connection
3. Connect to CSV. Select a table you want to export, right click on it->Export Data->Database.
4. In data transfer wizard choose target database/schema in your Oracle connection
5. Set columns mapping.
6. Run data transfer

**Comment by AnnLeeDC** [comment]
Thank you Serge!

I dont see the CSV file under the CSV connection. Should I import the CSV into the CSV connection first? 

Below screenshot shows 2 active connection, 1 from the Oracle connection and the other is the CSV connection. 

![dbeaver - active connections](https://cloud.githubusercontent.com/assets/22154862/18450453/1775c0b4-7901-11e6-963e-cdf264e26fc4.JPG)

**Comment by AnnLeeDC** [comment]
and thank you very much for replying to my question! 

So my main confusion is at the 3rd step -- I dont see a table under the CSV connection. Did I miss a critical step here? 
3. Connect to CSV. Select a table you want to export, right click on it->Export Data->Database.

**Comment by r-richmond** [comment]
@AnnLeeDC is that path you used the path to the folder holding the csv or the csv itself? (it should be the folder holding the csv)

**Comment by AnnLeeDC** [comment]
Hi r-Richmond,

Yes the path is the folder holding the csv. 

Do I need to create a dummy table under the Flat File (csv) connection?

**Comment by serge-rider** [comment]
You can't create table in CSV - you have to have a bunch of CSV files. Which will be presented as tables in DBeaver. CSV JDBC driver does that. 
Check their docs: http://csvjdbc.sourceforge.net/

**Comment by ncdingari** [comment]
Analytic Functions are not working with CSV Driver

**Comment by blue-chip** [comment]
> 
> 
> and thank you very much for replying to my question!
> 
> So my main confusion is at the 3rd step -- I dont see a table under the CSV connection. Did I miss a critical step here?
> 3. Connect to CSV. Select a table you want to export, right click on it->Export Data->Database.

I'm having the same problem, but I see the issue is closed. Does anybody finds their csv files as tables when they connect this way?

**Comment by p91paul** [comment]
After setting up your connection you should see all files in the directory you choose during connection setup as tables.
If you drop files after connection creation, use F5 to make them appear as tables.
If nothing happens, double check your files are in the right folder and with the right extension

**Comment by AnnLeeDC** [comment]
from the OP: 

here is the steps I took:
1. From DBeaver Database tab, click on New Connection -> Flat Files
2. Specify a path for your csv files, for instance, your download folder

*** Once the flat file connection is created under DBeaver, you should be able to see the csv file structure such as the column names. Under the connection, all the csv files under your normal PC folder should display.  It cannot identify other files types like .txt, .dat, .xlsx etc. The flat file connection can only detect .csv files under your PC folder. 

3. Choose the csv file you would like to import to SQL table. Right click on the csv file, you would see options like Export Data, Import Data etc. Click on Export Data. Next you will see a Data Transfer dialogue

4. Click on Target and Mapping tabs, respectively, and fill in the target table name, it should automatically fill in the same name as the csv file.   

5.  Next, column mapping... Change the column type to varchar(255). The default type will fail the import job.  

Do the above steps quickly, try within 5 minutes, and before exporting to your oracle connection, make sure you are connected to your Oracle db.

**Comment by geo7** [comment]
Is this available on the community version?
