### ISSUE TITLE
"Query Running" indication in tabs

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#723]
Would it be possible for tabs to contain some sort of "a query is running" indication?  I find myself with way too many tabs open and I know/think a long-running query is running, but sometimes have trouble finding which of the tabs it's in to check on it.

**Comment by serge-rider** [comment]
You can check running queries (or cancel them) in "Background Tasks" view. Also you can see SQL in Query Manager.
In regards to indication in tab: how do you see it in UI?

**Comment by jk3us** [comment]
Something like the ["noisy tabs" indicator](https://chrome.googleblog.com/2014/01/everyone-can-now-track-down-noisy-tabs.html) in chrome would be nice:  Just some icon (or a character like [⟳](http://graphemica.com/%E2%9F%B3)), or color change/highlight, or subtle animation that indicates that it's running.

**Comment by someotherdataguy** [comment]
I would appreciate this also.

**Comment by serge-rider** [comment]
This feature is similar to #300. Main problem is that Eclipse framework doesn't support easy way to customize editor tabs look-and-feel. 
So it may take some extra time to implement.

**Comment by serge-rider** [comment]
I'll make it simple. SQL editor icon will change during query execution.

**Comment by jk3us** [comment]
Sounds great. Thank you.
