### ISSUE TITLE
ODBC Driver Connection Type Missing on Mac?

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#724]
Is the ODBC Bridge connection support on mac? It doesn't appear to be available in the New connection screen.

Enterprise 3.7.3

<img width="187" alt="screen shot 2016-09-12 at 1 56 41 pm" src="https://cloud.githubusercontent.com/assets/9246654/18452675/c5de1b1c-78f0-11e6-9309-265f8600a1be.png">

**Comment by serge-rider** [comment]
No, ODBC/JDBC bridge driver is Windows only (actually this driver is a part of Java runtime - or used to be before Java8).
So on Linux and Mac you will need some 3rd party ODBC driver. 
I'm not aware about existence of such drivers - at least free ones.
