### ISSUE TITLE
Problem with ResultSet size limits not working with Redshift

### ISSUE THREAD

**Issue by mtortolano** [serge-rider/dbeaver#725]
Having a problem with the ResultSet size limits not being honoured regardless of the settings I use. I've tried all the variations of "Use SQL to limit fetch size" and "Use fetch-size" but neither seem to be honoured in the SQL being sent to my database. Given some of my tables are 10million rows plus it's a bit of a pain. I've made sure I'm editing the connections settings for it as well as the global settings but neither have any effect.

Running DBeaver CE 3.7.4 with Redshift (tried both the default 1.1.10 and the latest 1.1.17 JDBC drivers, same behaviour with both), on Ubuntu 14.04, with OpenJDK 8.

**Comment by serge-rider** [comment]
What driver do you use for Redshift?
PosgreSQL?

**Comment by mtortolano** [comment]
I tried it with the Amazon Redshift JDBC driver that you bundle with DBeaver (1.1.10), and their latest one direct from the AWS website (1.1.17). Both had the same problem.

**Comment by serge-rider** [comment]
Redshift driver doesn't support SQL LIMIT.
As far as I know Redshift is based on PostgreSQL 8 engine. I'll change driver config so it will use PostgreSQL meta-model (it includes queries resultset size limit support).

**Comment by mtortolano** [comment]
Ah yes, good point.

http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-postgres-jdbc.html

It is a fork of Postgres 8 but it doesn't support all the features of the original product. I can easily try it out on Postgres JDBC driver and see how well it works.

**Comment by serge-rider** [comment]
try to run a query with explicit LIMIT:
`SELECT * FROM big_table LIMIT 100`
also you can try
`SELECT * FROM big_table OFFSET 100 LIMIT 100`

PostgreSQL supports it but I'm not sure about Redshift

**Comment by mtortolano** [comment]
Explicit LIMIT commands in the queries text definitely work with the Redshift driver, I had to start doing that already to get anything useful out.

However it means you can't use the feature you have to jump forward a chunk of data in the UI which is a shame as that's really nice to have.

**Comment by serge-rider** [comment]
Ok, thanks for info

**Comment by mtortolano** [comment]
I gave it a go using the "PostgreSQL standard driver" which mostly works ok with Redshift but still doesn't work right with the LIMITs unfortunately.

**Comment by serge-rider** [comment]
Try to use PostgreSQL (Generic) driver.

**Comment by mtortolano** [comment]
Ah yes that works perfectly, I can see the LIMIT commands on the Redshift server log. Thank you.

**Comment by serge-rider** [comment]
Good.
You can use Redshift driver in 3.7.5.

**Comment by serge-rider** [comment]
Additionally I've updated driver version

**Comment by mtortolano** [comment]
Thanks, appreciate the help
