### ISSUE TITLE
Oracle - Package declaration and body not loaded properly

### ISSUE THREAD

**Issue by shilkazx** [serge-rider/dbeaver#726]
When open an Oracle package from the DB Navigator panel by double-clicking, neither declaration nor body part is loaded, but pop up a window report a ORA-00942 error -- table or view does not exist.
After some google work, I believe this bug is related to this issue:
[https://github.com/serge-rider/dbeaver/issues/41](https://github.com/serge-rider/dbeaver/issues/41)
In the previous issue, the user reported that dbeaver should use DBA_SOURCE instead of ALL_SOURCE to get package information. In my case, I can't access DBA_SOURCE via sql or oracle will give me a ORA-00942 error, but I can get information from ALL_SOURCE without any problem.
Please check it. Thanks!!! 

————————
I've checked dbeaver‘s source code(dbeaver/plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleUtils.java), this issue is caused by `OracleUtils.getSource` which use `sourceObject.getDataSource().isViewAvailable` to detect whether DBA_SOURCE is accessable for current user. In the implementation of isViewAvailable, SYS.ALL_VIEWS is used to list all available views. In my situation, I could see the DBA_SOURCE defination in ALL_VIEWS, but I don't have sufficient permission to query DBA_SOURCE. If that's the case, non DBA users might meet similar privilege problem when using dbeaver.

**Comment by serge-rider** [comment]
Thanks for detailed report and investigation.
I've fixed isViewAvailable so it will try to perform real select from a view.

Can you try it?

**Comment by shilkazx** [comment]
@serge-rider Perfect job! I've already seen the new source code and I'll check it as soon as I back to office next Monday.
