### ISSUE TITLE
"Set To NULL" is not keybindable and doesnt have a keyboard shortcut

### ISSUE THREAD

**Issue by farmboy0** [serge-rider/dbeaver#728]

**Comment by serge-rider** [comment]
Fix will be tracked in #727 (both Set to NULL and Reset are now customizable commands).
I'll close this one as duplicate.

**Comment by RazvanModex** [comment]
Can you provide documentation on how to assign hotkey for `Set to NULL` and `Set to default`?

**Comment by amzar96** [comment]
> Can you provide documentation on how to assign hotkey for `Set to NULL` and `Set to default`?

You can use `CMD + X` for set to NULL

**Comment by AntoniusGolly** [comment]
`CTRL + X` on win.

**Comment by ldgmaia** [comment]
If you don't want to lose your clipboard data, you can also use SHIFT + DELETE. If you want to set it as the default value, use CTRL + BACKSPACE.
