### ISSUE TITLE
Postgresql jdbc error setcharacterstream

### ISSUE THREAD

**Issue by irizzant** [serge-rider/dbeaver#73]
Hello,
I'm using Postgresql database with jdbc driver 9-4-125-jdbc42.

Whenever I try to inline-edit a text field I get this error on commit:
```
Error SQL [0A000]: method «org.postgresql.jdbc42.Jdbc42PreparedStatement.setCharacterStream(int, Reader)» not implemented yet
```

**Comment by serge-rider** [comment]
This is a known issue, will be fixed in the next version.

**Comment by irizzant** [comment]
Perfect thank you
