### ISSUE TITLE
Is it possible to have DBeaver execute the statement that is contigious to the cursor position?

### ISSUE THREAD

**Issue by someotherdataguy** [serge-rider/dbeaver#732]
For example in an editor I have this:

select col1 from mySchema.myTable1;
select col2 from mySchema.myTable2;

I then place the cursor at "col2" (not text highlighted). I then press alt+x, and then it executes

"select col2 from mySchema.myTable2;"

Is that possible?

Many thanks

**Comment by serge-rider** [comment]
Just use Ctrl+Enter to execute a single query (the one under cursor or selection). 
Alt+x executes whole script.

**Comment by someotherdataguy** [comment]
Ah! SO COOL! thx!
