### ISSUE TITLE
question - Create a numeric column in postgresql

### ISSUE THREAD

**Issue by wishper** [serge-rider/dbeaver#733]
Hi, just downloaded and run for 1st time. I have troubles to create a column with numeric type: the "scale" property is not editable.
Also, is there a way to select a datatype besides scrolling the select box with the mouse wheel? I'd like to write a couple of characters and then trigger the  "intellisense" and choose from 2-3 options rather than scroll in hundreds of different datatypes

many thanks

**Comment by serge-rider** [comment]
- Scale and precision will be editable in the next version, thanks for reminder.
- You can just enter type name and press Enter.

**Comment by oulenz** [comment]
I just ran into the same issue, except that I was trying to change the datatype of an existing column, from varchar. When I toggle numeric, precision and scale are not editable (length is). Is it possible you fixed this only for column creation? I'm running 3.8.5 on Ubuntu.

**Comment by serge-rider** [comment]
This will be fixed in 4.0, thanks for noticing.
