### ISSUE TITLE
Maven artifact 'maven:/mysql:mysql-connector-java:RELEASE' not found

### ISSUE THREAD

**Issue by ragsnas** [serge-rider/dbeaver#734]
Uppon creating a new mysql connection i get teh following error:

```
Error resolving dependencies
  java.io.IOException: Maven artifact 'maven:/mysql:mysql-connector-java:RELEASE' not found
```

It then offers me to download the missing driver and when i clikc download, the following error appears in my terminal, from where i started DBeaver.

I tried staring it with -clean and deleting the user files (`sudo rm -rfv ~/.eclipse ~/.dbeaver`) but neither worked for me :-(

I am running the newest version, installed just now.

**Comment by serge-rider** [comment]
Do you have access to http://central.maven.org/ ?
If yes then please attach debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by fowlerrr** [comment]
I'm having the same problem, except for postgresql.

[dbeaver-debug.log.txt](https://github.com/serge-rider/dbeaver/files/864278/dbeaver-debug.log.txt)

**Comment by serge-rider** [comment]
From debug log:
```
2017-03-23 09:51:40.080 - Open [https://repo1.maven.org/maven2/org/postgresql/postgresql/9.4.1212.jre7/postgresql-9.4.1212.jre7.pom]
2017-03-23 09:51:40.438 - Maven artifact 'org.postgresql:postgresql:9.4.1212.jre7' not found in repository 'https://repo1.maven.org/maven2/': sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
Error happened when DBeaver tried to load driver from Maven Central. For some reason SSL connection cannot be established. Do you use Java provided by DBeaver installer?

Workaround:
In version 4.0.3 default Maven repository URL was changed on secured (https) version. You can change it back in preferences->Database->Drivers->Maven. Remove existing maven-central repository and add new one with URL http://repo1.maven.org/maven2/
Note that http Maven repositories aren't secure. You can be in risk because of MITM attacks.

**Comment by fowlerrr** [comment]
I'm pretty sure I'm using the Java provided.  It was the default setting on install.

It may be my company firewall that's blocking the URI, although I'm managing to get there via a browser.

The workaround has got me sorted, though.  Thanks.

**Comment by caiges** [comment]
Adding the other Maven repo worked around this issue, cheers @serge-rider

**Comment by rienheuver** [comment]
I'm having the same issue but with what it seems a different cause. It looks like it's trying to create a folder configured for Windows on my linux (ubuntu 19.10) machine. Log attached.
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3831146/dbeaver-debug.log)

**Comment by BrusJan** [comment]
> http://repo1.maven.org/maven2/
This url requires me to use https and tells me to find more info at some sonatype link where they mentioned this link that works: http://insecure.repo1.maven.org/maven2/

**Comment by GRajaMca** [comment]
As a workaround, we can download the respective jar file and add to the configuration that might resolve this issue. The primary root cause for this issue is the proxy network.
