### ISSUE TITLE
duplicate keys in generated DDL for Postgres

### ISSUE THREAD

**Issue by drx777** [serge-rider/dbeaver#735]
When exporting the DDL for a table with unique keys, both, a constraint in the table definition as well as a separate create unique index statement are generated. Executing such script results in an error due to the key already existing, e.g.:

SQL Error [42P07]: ERROR: relation "table_key" already exists
  org.postgresql.util.PSQLException: ERROR: relation "table_key" already exists

Steps to reproduce
1) create or select a table with a unique key
2) export DDL for this table
3) delete table
4) execute exported DDL

Expected result
* no errors occur

Actual result
* relation exists error occurs

Proposed solution:
A) generate no separate create unique index statement
B) offer option to select, which kind of constraints are to be included in the table definition or generated seperately

**Comment by serge-rider** [comment]
Agreed. PG unique indexes are created implicitly so we shouldn't show them in DDL.
Fix will be added in the next version.
