### ISSUE TITLE
Row are skipped when clicking delete/using Alt-Delete

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#737]
Hi,

When deleting a row in a result set, the cursor will go down one instead of staying at the same position, which deletes only half the rows if you spam the button/the shortcut.

To reproduce:
1. Create a bunch of rows
2. Select the first one
3. Click delete, cursor is moving to row 3 instead of staying on row 2

**Comment by serge-rider** [comment]
Thanks for report
