### ISSUE TITLE
Oracle Table - set/change tablespace support

### ISSUE THREAD

**Issue by guidobonerz** [serge-rider/dbeaver#738]
Hi.
I'm new to dbeaver. 
When i create a new table using the editor i'm not able to set tablespace attribute.

Is it known issue, or do i anything wrong?

Regards
Guido

**Comment by serge-rider** [comment]
Tablespace option isn't yet supported by Oracle extension.
I'll mark this issue as feature request.

**Comment by serge-rider** [comment]
Correlates with #582
