### ISSUE TITLE
Running SQL script as part of another... (including by using @ char)

### ISSUE THREAD

**Issue by JulianVolodia** [serge-rider/dbeaver#739]
Hi, 

notice feature in sqlplus and sqldeveloper:

```
select * from foo limit 1;
@nameOfScript.sql
drop database bar;
```

will "include" nameOfScript.sql into that listing... QUESTION - is dbeaver have any similar feature?

And, do anybody want to have it?

Docs [here](http://docs.oracle.com/cd/E11882_01/server.112/e16604/ch_five.htm#i1211006)

Best regards.

**Comment by serge-rider** [comment]
This correlates with #639

**Comment by JulianVolodia** [comment]
@serge-rider thanks for marking as related. Is there any option/abbrev. in dbeaver to do so?

**Comment by serge-rider** [comment]
These issues are related (both requires DBeaver to analyze script content and extract meta-information) but still different - and will be resolved separately.
Will set 3.8 milestone although it is not final.

**Comment by ilyacoos** [comment]
Hi,
Is it possible to enhance this feature by platform-specific MS-SQL command? Like this:
:r scriptFile.sql

See [sqlcmd reference](https://msdn.microsoft.com/ru-ru/library/ms162773.aspx#Anchor_5)

It's required for testing purpose performed in DBeaver followed by patch compiling/deploying in CI.

**Comment by JulianVolodia** [comment]
'Getting things done'

@serge-rider chop this task into some subtasks and say what community should do...

**Comment by serge-rider** [comment]
Not sure that it can be chopped at this stage.
I need to improve SQL evaluation in core module first.

**Comment by JulianVolodia** [comment]
Thanks. Could you point where they are described or you want to do it on your own?

**Comment by serge-rider** [comment]
In 4.1.2 DBeaver will support following syntax:
```sql
@include file-name
@include "file-name"
```
`file-name` is relative or absolute file path.

See https://github.com/serge-rider/dbeaver/wiki/Client-side-scripting for details.

If other database-specific syntax is needed - please create separate feature requests.
