### ISSUE TITLE
Problems with column names containing spaces

### ISSUE THREAD

**Issue by vser35** [serge-rider/dbeaver#741]
Hello

Thank you for DBeaver, it's great. I've found the following issues related to spaces in column names (3.7.4):

1. SQL editor's context assistant always capitalizes column names containing spaces. For example, a column named `Account Dr` is always inserted as `ACCOUNT DR`. No settings change this behavior.
2. If I try to rename column using DBeaver interface and the new name contains space, the proposed SQL script doesn't surround this new name with grave accents. Trying to run this script results in error.

**Comment by serge-rider** [comment]
Thanks for report

**Comment by vser35** [comment]
Hello

Thank you for fixing the always-uppercase bug. Now (as of 3.7.6) SQL editor has two options of inserting field names: the uppercase using the "Upper case" setting and the lowercase using "Lower case" and "Default" settings. So if i choose "Default" and try to autocomplete the `Document` field, it is inserted as `document`. Have such behavior been intended?

And referring to the second issue, now if I try to rename column and hit "ok" nothing happens.

Kind regards

**Comment by serge-rider** [comment]
What is your database?

**Comment by vser35** [comment]
MySQL

**Comment by serge-rider** [comment]
Will be fixed in the next version (column names will be used in the same form as they are stored in MySQL).
