### ISSUE TITLE
Database compare broken in Postgres

### ISSUE THREAD

**Issue by kkartaltepe** [serge-rider/dbeaver#743]
When comparing two databases in postgres and only showing differences pretty much every single thing is marked as a difference. Most notably it shows all datatypes like pg_catalog.int4 is different from pg_catalog.int4.

It looks like using the 'Compare only structure (ignore properties)' setting (the other two unchecked) gives a decently correct compare. Does this leave out some information that isn't shown in the compare without this checked but that causes the reported difference?

I checked the oids of the datatypes and they seem to be the same in both databases so im not sure what is causing the comparison to report them as differing when they are in-fact the same (created from the same ddls).

sample ddl
```sql
CREATE TABLE sample_table (
	datetime timestamp NOT NULL,
	"free" int8 NOT NULL,
	used int8 NOT NULL,
	total int8 NOT NULL,
	CONSTRAINT sample_pk PRIMARY KEY (datetime)
)
```
sample report showing differences at 
https://gist.github.com/kkartaltepe/50ba20f29bea9bd85362405f7ba25645

**Comment by kkartaltepe** [comment]
Forgot versions of things,
DBeaver 3.7.4
Postgres 9.5.0

**Comment by serge-rider** [comment]
Thanks for report. It is not just PostgreSQL problem.

**Comment by kkartaltepe** [comment]
Thanks for the super fast response!
