### ISSUE TITLE
Refresh isn't showing new schema with SqlServer Connection

### ISSUE THREAD

**Issue by DwordPtr** [serge-rider/dbeaver#744]
I'm connecting to a **Sql Server** database from the **Ubuntu 16.04** clieanand trying to use the explorer on a new schema, but it's not showing the new schema in the explorer after refresh. 

I am still able to query data based on the new schema, but am unable to use the db explorer to look at table + field names.

Note: Doing this same thing on the windows client works. I'm not sure about the mac client though.

**Comment by DwordPtr** [comment]
I'm using the Ubuntu 16.04 client

**Comment by serge-rider** [comment]
Can't reproduce. I'm clicking on a database name (in navigator), press f5 and see new schema.
How do you perform refresh? Maybe F5 shortcut has some other meaning on your Ubuntu machine (ten you can refresh using context menu or redefine refresh command shortcut in preferences).

**Comment by DwordPtr** [comment]
I'm hitting f5 (while watching the ui bring up a status bar) and the right-click menu. I'm still not seeing the schema. If it helps it's not under a standard name, but there aren't any exotic chars in it or anything.
I'm also on 3.7.4 

Also didn't expect such a fast reply thanks :)

**Comment by serge-rider** [comment]
Still can't reproduce.
When you perform refresh - check Query Manager view for metadata refresh query:
`-- Load schemas` row must appear there after each refreshing.

Also if can refresh whole connection (just select connection in navigator) - in that case physical reconnect will be done and all metadata will be re-read completely.

**Comment by DwordPtr** [comment]
From the log file I see Error reading schemas in catalog 'Schema Name' - null

**Comment by serge-rider** [comment]
These are just warnings.
Actual schema read happens.
Do you see new schema after connection refresh?

**Comment by DwordPtr** [comment]
Nope I keep seeing the line 
```

 55 2016-09-22 17:07:46.727 - Error reading schemas in catalog '<schema name?' - null                                                                                                                

```

**Comment by serge-rider** [comment]
"Error reading schemas" is just a warning (there are multiple ways to read schemas and one of them failed). If it'd be an error than you'd see an error dialog and empty list of schemas.

So if connection refresh doesn't help - does it mean that reconnect doesn't help? What if you restart DBeaver - do you see new schema?

**Comment by DwordPtr** [comment]
I forced object refresh in the connection properties and now it's working.

Thanks for your help!!
