### ISSUE TITLE
Exclude Table metatypes in postgres compare

### ISSUE THREAD

**Issue by kkartaltepe** [serge-rider/dbeaver#745]
Currently a comparison of databases includes table metatypes in the "Datatypes" list if there are table differences. Its not really wrong but it does add some bloat to the comparison since these already appear in the tables section.

For example when you create a type `test_table` postgres will create two entries in `pg_type` with a `typname` of `_test_table` and `test_table`. 

As best I can see the easiest  identification of these outside sql would be to exclude any types whose names match tables already found.

For sql based identification any row in `pg_type` with a `typtype` of 'c' refers to a table type (defined in `pg_class`) and these types will also have a non-zero value in `typarray` which refers to the `oid` of the `_table_name` row in `pg_type`

Versions:
DBeaver 3.7.4
Postgres 9.5.0

**Comment by serge-rider** [comment]
I believe this was fixed in 3.7.5
