### ISSUE TITLE
Postgresql: terminating a query/connection from the Sessions screen doesn't work

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#746]
When I go to the sessions screen, right click a connection, right click and click "Terminate" it executes

    SELECT pg_catalog.pg_terminate_backend(15646);

But returns this error:

    ERROR: function pg_catalog.pg_terminate_backend(bigint) does not exist
    Hint: No function matches the given name and argument types. You might need to add explicit type casts.

But I can copy that command and run it in a sql editor and it works correctly.  I think changing `setLong` to `setInt` in https://github.com/serge-rider/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/session/PostgreSessionManager.java#L78 might work?

**Comment by serge-rider** [comment]
Yep. 
Thanks for report and for solution :+1:
