### ISSUE TITLE
Resize combo box so all items are seen

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#748]
The pop up window should get automatically resized.

In the following case, I have to resize manually each time as I don't see entire text of last 2 items. Tooltip helps, but it still is not practical.

![image](https://cloud.githubusercontent.com/assets/85767/18664070/7c7c6ad2-7f21-11e6-8880-6c4df6d895f6.png)

The same thing should be done for the Schema combo box.

**Comment by serge-rider** [comment]
It is a standard control, I'm not sure that changing default behavior is a good idea. Although I coudl try to patch database/schema selectors.

BTW you can resize drop down area (no need to rely on tooltips)

**Comment by majkinetor** [comment]
I know I can resize, but the size returns on next click.

> I'm not sure that changing default behavior is a good idea. Although I coudl try to patch database/schema selectors.

This changes presentation, not behavior.

**Comment by serge-rider** [comment]
Ok.
I'll fix combos so they will remember previous drop-down panel size.

**Comment by majkinetor** [comment]
Remember forever or just until restart ?

**Comment by serge-rider** [comment]
For now just until DBeaver restart.
