### ISSUE TITLE
Oracle exec doesn't work

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#749]
This command:

`EXEC DBMS_STATS.DROP_EXTENDED_STATS(ownname=>'...', tabname=>'...', extension=>'...' )`

Works in SqlDeveloper but produces in dbeaver:

```
SQL Error [900] [42000]: ORA-00900: invalid SQL statement
  java.sql.SQLSyntaxErrorException: ORA-00900: invalid SQL statement
```

See [this](https://confluence.atlassian.com/bitbucketserverkb/database-upgrade-error-column-to-be-renamed-is-used-in-a-virtual-column-expression-827098665.html) link for command details.

**Comment by serge-rider** [comment]
EXEC is SQL*Plus command, it is no a part of PL/SQL.
Use CALL command:
`CALL DBMS_STATS.DROP_EXTENDED_STATS(ownname=>'...', tabname=>'...', extension=>'...' )`
or
`{CALL DBMS_STATS.DROP_EXTENDED_STATS(ownname=>'...', tabname=>'...', extension=>'...' )}`

**Comment by majkinetor** [comment]
Ah, my mistake, sorry.
