### ISSUE TITLE
Impossible to make data changes in the result set editor on Sybase connections

### ISSUE THREAD

**Issue by jeisoncp** [serge-rider/dbeaver#75]
After update to version 3.5.4, I can't make data changes in the result set editor on Sybase connections. The double click to edit in cell or in external dialog doesn't works. Add, duplicate, delete also doesn't works.

![sybase](https://cloud.githubusercontent.com/assets/7952798/11221654/649d319c-8d4d-11e5-8c88-775d3b374380.png)

**Comment by serge-rider** [comment]
This is not Sybase-specific issue. Some other databases were also affected.
Fix will be in the next release.
