### ISSUE TITLE
Export of bigint from mysql to oracle converts large numbers to negative numbers

### ISSUE THREAD

**Issue by RealSkeptic** [serge-rider/dbeaver#750]
Steps to reproduce:
---
In MySQL

    create table test1 ( example bigint not null);
    insert into test1 values (1111), (1111111), (978159842830),(978159842758);

* Refresh the table list
* Select "Export data" from the menu
* Choose "Database" as the target
* Use a target container in an Oracle 11g database
* Perform export with all default values/mappings

Result:

    example     |
    ------------|
    1111        |
    1111111     |
    -1092700658 |
    -1092700730 |

Note: this works neither with the default column type (DECIMAL(19,0)) nor choosing NUMBER explicitly from the menu.

Versions:
---
DBeaver: 3.7.4, on Linux Mint 17.3 (using Debian community version package, 64 bit)
MySQL: 5.5.52 (standard driver)
Oracle: 11g (using ojdbc6.jar)

**Comment by serge-rider** [comment]
It is a bug in DBeaver (long values was evaluated as 32-bit integers during data transfer).
Will be fixed in the next version.
Thanks for report.
