### ISSUE TITLE
Ambiguous column name error while filtering query results using a column used in the where clause (DB2 LUW  9.7) 

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#751]
While trying to filter on any of the columns used in the join, it fails with a message saying the column name is ambiguous.
I think I've seen other tools rename the column from the second table as VIN1 etc. in the result. 

query:
```SQL
SELECT * FROM tableP p, tableP_STG s WHERE p.vin=s.vin 
```

From the tooltip in the results pane header, I think the underlying query used for filtering would be something like:
```SQL
select * from (
SELECT * FROM tableP p, tableP_STG s WHERE p.vin=s.vin 
)z_q where z_q.vin='ABCD' 
```
We might need something like 
```SQL
select p.VIN,s.vin as VIN1 from (
SELECT * FROM tableP p, tableP_STG s WHERE p.vin=s.vin 
)z_q where z_q.vin1='ABCD' 
```

**Comment by serge-rider** [comment]
This issue persists for all database drivers.
In fact ordering should be applied in a different way. Instead subquery wrapping original query should be patched with ORDER BY clause. So it is a bug.
Although query modifications may also fail in complex cases.
