### ISSUE TITLE
Fetching of data in Data Editor takes unnecessary long

### ISSUE THREAD

**Issue by vlasisva** [serge-rider/dbeaver#752]
Hi all,

I'm using DBeaver 3.7.2 on Win7 64bit accessing Redshift using the RedshiftJDBC-1.1.10.1010.jar driver. 

Double clicking on a table and then going in the Data tab (the Data Editor), reports that the first X number of rows (configured to 200) are fetched in a reasonable amount of time. However, after that, the progress bar keeps staying up, with no results shown, for an unreasonably long amount of time (depending on table size)

The expected behavior is for the results to be displayed as soon as the first X number of rows are fetched. Instead, the progress stays up for some extended amount of time AFTER the requested results have been reported as fetched by the progress bar.

This behaves exactly as an older bug appearing on SQL Server and Vertica, and solved here:
http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1693

* Query manager shows '"Read Data' as the only active query, during that unexplained long waiting period.
* Looking at Redshift's query manager on AWS Console, I see a query of 'select * from my_table' being active throughout the period that dbeaver shows the progress bar.
* I experimented with increasing the 'number of rows fetched' setting to a very small value (still unreasonably slow) and to a very large value (query then takes really long time and it does seem that the data of all the requested rows are actually fetched from the server).

In my Preferences/Result Sets, I played with 
* 'Use SQL to limit fetch size' (turning it on or off does not change anything. Interestingly the submitted query is identical)
* 'Use fetch size': ditto -- no change

I am also wondering whether the trick of limiting the cursor fetch size, as reported by @serge-rider  at Fri Apr 10, 2015 9:49 pm at the above mentioned forum, does not work on Redshift.

Kind regards and thanks in advance :)

**Comment by serge-rider** [comment]
I think this is a duplicate of  #725 (check it for workaround).
RedShift driver config will be fixed in the next version.

**Comment by vlasisva** [comment]
Looks like it. Thanks.

I'll use the generic PostgreSQL (Generic) driver and will wait for Dbeaver v3.7.5

Cheers
