### ISSUE TITLE
Silent install (NSIS): not possible to set custom destination folder

### ISSUE THREAD

**Issue by LinLo** [serge-rider/dbeaver#754]
Hello,

First of all, thank you very much for this great software.
I know the windows setup use NSIS and I try to silent install in a custom directory.
I tried "setup.exe /S /D=D:\Program Files\DBeaver" but it install it on C;\Program Files\DBeaver

Do you know how to do it ?

Thank you

**Comment by serge-rider** [comment]
I think there is a bug in 64bit installer. It redefines default install path to default program files dir. And you can't change it from command line.

**Comment by serge-rider** [comment]
Will be fixed in the next version.
