### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by rltheis27** [serge-rider/dbeaver#755]
My organization has been reviewing DBeaver as a potential SQL client tool. The testers found some inconsistencies with some of the GUI features. They were insuring all component of the GUI can be accessed without using a mouse (for those individuals who cannot use a mouse). They also tested, using  JAWS to insure the fields were properly announced (for the seeing impaired). The tester found three items. 

1.	Certain user interface elements are not accessible via the keyboard.  As an example, within the “Create new driver” window, the “Driver Type:” combo box is not accessible via the keyboard.

Expected result:  All user interface elements are expected to be accessible via the keyboard.  In this instance the “Driver type:” combo box is expected to be accessible via the keyboard.  

Note: This defect may exist elsewhere within the application.

This drop down box only contains one value. Does it need to be on the edit window? Should it be grayed out?

2.	Labels for certain fields are not announced by JAWS. As an example, within the “Edit driver Apache Drill” window, when the “Embedded” checkbox is accessed JAWS announces, “Settings checkbox not checked to check press space bar” instead of announcing the label as, “Settings Embedded: checkbox not checked to check press space bar”.

Expected result:  All labels are expected to be announced by JAWS. In this instance, JAWS is expected to announce, “Settings Embedded: checkbox not checked to check press space bar”.

Note:  This defect also exists elsewhere within the application.

3.	Within the “Team” screen of the “Preferences” window, the “General Team Preferences” legend is not announced by JAWS. When the “Show all synchronization information in a resource’s text label” checkbox is accessed JAWS announces, “Show all synchronization information in a resource’s text label checkbox not checked, to check press Spacebar Alt + S’ instead of first announcing the legend as, “General Team Preferences: Show all synchronization information in a resource’s text label checkbox not checked, to check press spacebar Alt + S”. 

Expected result:  All legends are expected to be announced by JAWS. In this instance JAWS is expected to announce, “General Team Preferences: Show all synchronization information in a resource’s text label checkbox not checked, to check press spacebar Alt + S”. 

Note:  This defect may exist elsewhere within the application.

**Comment by serge-rider** [comment]
Thanks for report.

We can fix most of these issues (I've already fixed issues in driver dialog you mentioned above).
Main problem is that we do not have real QA, bugs a reported by users and then I fix them.
Moreover I do not test with JAWS (or other accessibility programs) - again, there are no QA people here (yet, hopefully).

So I can fix bugs/improve things if you will report about them. But I can't find/fix all of them by myself.

In  regards to "Team" preferences (and a few other preference pages) - this page is from standard Eclipse framework, we cannot change or improve it.

BTW there is #425 issue for general accessibility problems.
