### ISSUE TITLE
View table (F4 key) option does not use the default schema

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#756]
I have a two tables in two different schemas with the same table name . In the SQL editor,  when the tablename is used without the schema name, queries work OK using the default schema. But when I use F4 to view the table, it opens the table from the other (alphabetically first?) schema.

Database: DB2 LUW 9.7

**Comment by serge-rider** [comment]
Thanks for report.
Current active schema will be used in object search.
