### ISSUE TITLE
TAB key doesn't toggle grid mode

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#757]
In 3.7.4

Worked OK before.

It now switches to status bar
`| 44 row(s) fetched - 5ms`

**Comment by majkinetor** [comment]
Actually, it works on tables but not on results returned by scripts.

**Comment by serge-rider** [comment]
Can't reproduce.
- Try to restart DBeaver
- Check shortcuts preferences. What if you change TAB to any other shortcut?

**Comment by serge-rider** [comment]
If you will catch this problem again please reopen.
