### ISSUE TITLE
Rename script from the editor

### ISSUE THREAD

**Issue by majkinetor** [serge-rider/dbeaver#758]
I now have to find the script in the Projects to rename it with F2, the File->Rename option is grayed from within editor.
I hopped Link with editor would select it for me but it doesn't happen.

It would be practical to have some or all of:

* Make F2 work within the editor
* Add new option rename to _Context -> File_
* Make `<CTRL><SHIFT>,` select script in navigator.

**Comment by serge-rider** [comment]
"Link with editor" works in Project Explorer view. At least it should.

**Comment by majkinetor** [comment]
No, it select connection->schema used by the script here.

**Comment by serge-rider** [comment]
It selects connection->schema in database navigator view. 
There are no connections in Project Explorer.

**Comment by majkinetor** [comment]
Ah, OK, that works, I never used Project Explorer so far. Also, ctrl + shift + , from editor jumps to Projects, not Project Explorer. For this to work project needs to be activated too. Kinda convoluted, just to rename the file you look at.

**Comment by serge-rider** [comment]
Yes, maybe it is not convenient for people who use Project Navigator view.
I believe that most users (of standalone version) use Database Navigator + Project Explorer views.

Anyhow renaming script without selecting in tree is a good feature.

**Comment by majkinetor** [comment]
> I believe that most users (of standalone version) use Database Navigator + Project Explorer views.

I always thought that DN + PE serves no particular purpose - all that info is available in PN anyway. I still have to see a use case for those 2.

**Comment by serge-rider** [comment]
DN+PE makes sense if you have only one project. These views separate database metadata from local resources.

**Comment by majkinetor** [comment]
Do they really need to get separated ? The local resources depend on the database in question. Projects let you declare this dependency as it allows coupling of local resources to one environment (which usually have multiple testing databases) instead of one db connection.

**Comment by serge-rider** [comment]
In default views layout DN is right above PE so I always see both these views. They are co-dependent but still are very different. 
I have a lot of connections in a single project. And use project explorer view rarely (for most connections I have just one script - SQL scrapbook actually).

**Comment by majkinetor** [comment]
That is OK if you work alone. In a team of 10+ with dbeaver project in sync between them, everybody creates scripts.

**Comment by serge-rider** [comment]
Agreed

**Comment by serge-rider** [comment]
"Rename current script with F2" feature will be added in the next version.
