### ISSUE TITLE
PostgreSQL - schema and table autocompletion does not work

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#763]
Hi,

PostgreSQL 9.5
DBeaver 3.7.5 (Linux 64 .deb version)

When I try to perform a completion of a schema / table name with ctrl + space, if the table is in another schema than the "active" schema, nothing is displayed, since the table exists.
Only tables in "active" schema are displayed if I type the table name (without the schema name).
Schema names autocompletion does not work either.

This features worked well in previous versions.
No message in the error logs.

Thanks for your help.
Regards,

Cedric

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
Fix will be in the next version.
Till then as a workaround you can add database name ("postgres" by default) before schema name. So full table name will look like "postgres.public.table". Not convenient but works.

**Comment by ced75** [comment]
Thanks.
If the schema is active, it also works. So there are two workarounds.

**Comment by jaroet** [comment]
Having the same issue with DBeaver 4.0.7 and latest JDBC driver at the moment (42.1.1) 
when the schema is active the autocompletion is working (but not adding the schema which I think it should). I have the option to use short object-names disabled. 

When the schema is not active it CTRL+space gives 'no proposals'.

**Comment by serge-rider** [comment]
Auto-completion for non-active (and non-system) schema works only if you specify schema name before table.
So it works as expected.

**Comment by jaroet** [comment]
For those who want autocompletion over multiple schema's. Version 3.6.10 does this the old way. 
Example : select * from dat

When you hit CTRL-SPACE all schema's containing all tables with dat in the name will be shown. Just letting you know. 

Regards,
Jeroen
