### ISSUE TITLE
after connection closed

### ISSUE THREAD

**Issue by ssyang0102** [serge-rider/dbeaver#764]
![image](https://cloud.githubusercontent.com/assets/5800272/18833652/536caf96-8424-11e6-82d5-2cdef736231e.png)

after i click [Reconnect],connection is reconnected,but the tabgrid [data] can't refresh,i need reopen the table "seq" ,really cumbersome

**Comment by serge-rider** [comment]
I'll make refresh button enabled for such cases. So you can reconnect and the press refresh - no need to reopen editor.
