### ISSUE TITLE
Connections list getting smaller and smaller

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#765]
DBeaver: 3.7.5 (.DEB 64 bits).

A very strange thing: in the toolbar, the list of connections shortcuts is getting smaller and smaller each time I clic on the arrow to select a connection:
![image](https://cloud.githubusercontent.com/assets/12892581/18839602/dc95e440-840b-11e6-8a7d-23f49818300a.png)
![image](https://cloud.githubusercontent.com/assets/12892581/18839609/e29405de-840b-11e6-8c44-58d704618165.png)
After a few more clics, I have no more list. It became to slim.

Regards

**Comment by serge-rider** [comment]
Very strange, indeed.
Maybe it is a side-effect of fixing #748. Will try to reproduce it on one of my linuxes.

BTW you can resize this drop-down panel (and thus don't let it to slim).

**Comment by ced75** [comment]
Exact, I didn't notice it.
Thanks for the tip.
