### ISSUE TITLE
Error in incremental update (3.7.4 to 3.7.5)

### ISSUE THREAD

**Issue by SZubarev** [serge-rider/dbeaver#766]
During update 2.7.4 to 2.7.5 from within application receive the error:

Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver Runtime 3.7.5 (org.jkiss.dbeaver.runtime.feature.feature.group 3.7.5)
  Software currently installed: DBeaver Enterprise 3.7.4 (com.jkiss.dbeaver.core.product 3.7.4)
  Only one of the following can be installed at once: 
    DBeaver Model Plug-in 1.0.29 (org.jkiss.dbeaver.model 1.0.29)
    DBeaver Model Plug-in 1.0.30 (org.jkiss.dbeaver.model 1.0.30)
  Cannot satisfy dependency:
    From: DBeaver Enterprise 3.7.4 (com.jkiss.dbeaver.core.product 3.7.4)
    To: com.jkiss.dbeaver.enterprise.feature.feature.group [3.7.4]
  Cannot satisfy dependency:
    From: DBeaver 3.7.4 (com.jkiss.dbeaver.enterprise.feature.feature.group 3.7.4)
    To: org.jkiss.dbeaver.standalone.feature.feature.group [3.7.4]
  Cannot satisfy dependency:
    From: DBeaver Core 3.7.4 (org.jkiss.dbeaver.core.feature.feature.group 3.7.4)
    To: org.jkiss.dbeaver.model [1.0.29]
  Cannot satisfy dependency:
    From: DBeaver Core 3.7.5 (org.jkiss.dbeaver.core.feature.feature.group 3.7.5)
    To: org.jkiss.dbeaver.model [1.0.30]
  Cannot satisfy dependency:
    From: DBeaver Runtime 3.7.5 (org.jkiss.dbeaver.runtime.feature.feature.group 3.7.5)
    To: org.jkiss.dbeaver.core.feature.feature.group [3.7.5]
  Cannot satisfy dependency:
    From: DBeaver Standalone 3.7.4 (org.jkiss.dbeaver.standalone.feature.feature.group 3.7.4)
    To: org.jkiss.dbeaver.core.feature.feature.group [3.7.4]

**Comment by serge-rider** [comment]
I will make new update site repository for EE version (3.7.6+).
Existing update site can be used only for Eclipse plugin install/update - it can't be used to update standalone version.
