### ISSUE TITLE
3.7.5 for mac is corrupt

### ISSUE THREAD

**Issue by drewed** [serge-rider/dbeaver#767]
I attempted to download both the community and enterprise editions.  After launching the application, I received the following error:

> “Dbeaver.app” is damaged and can’t be opened. You should move it to the Trash.

I'm running OS X 10.11.6.

**Comment by serge-rider** [comment]
Check #95

**Comment by drewed** [comment]
I used the solution posted by jgroves-hw in the referenced issue to work around the problem.
