### ISSUE TITLE
Autocomple suggestions for literal values that are already present in the current file

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#768]
Case: I deal with a lot of ad-hoc querying in the database, and specific numbers and string literals like a customer ID or name are used repeatedly while trying to trace data. Some editors like Notepadd++ have autocompletion suggestions based on words that already appear in the file, which is very useful. It would be a nice additional feature IMO to search literal values in the file and offer these as suggestions after an operator like = is encountered.

**Comment by serge-rider** [comment]
This feature is already there. It has name "Word completion" and accessible using shortcut `CTRL+SHIFT+Space` (note - it is case sensitive).

**Comment by dbza** [comment]
Thanks for clarifying, I could not get it to work but it could be because I am not using the latest version. I'll check.

**Comment by serge-rider** [comment]
It should work in all 3.x versions.
