### ISSUE TITLE
Issues with ODBC Connection After Upgrade to 3.7.5

### ISSUE THREAD

**Issue by kyleflan** [serge-rider/dbeaver#770]
After upgrading to 3.7.5 from 3.7.1 I'm having issues a few issues connecting to any ODBC connection.

The initial issue was that my existing connections would seem to connect, but after expanding the "Tables" or "Views" subtrees nothing would show up. I attempted to recreate the connections but got the following error:

java.sql.SQLException: [Microsoft][ODBC Driver Manager] Connection not open (Details gives the same error)

I'm running 3.7.5 x86 on Windows 7 64-bit. I use the 32-Bit ODBC Administrator to create the DSNs. I've also installed on a Windows Server 2012 64-bit box with a number of 32-bit system DSNs with the same issue.

When editing the "ODBC" driver in dbeaver, I have the following present:

![image](https://cloud.githubusercontent.com/assets/5608074/18845559/c24a9b68-83e7-11e6-81bb-8eac8f569751.png)

I've reinstalled, reinstalled with "Remove Settings", removed the .dbeaver folder and reinstalled, rebooted and am still having the same issue.

For now I'm downgrading back to 3.7.1 and restoring the .dbeaver folder from backup. I can connect to existing databases; however, I cannot create new connections.

**Comment by serge-rider** [comment]
Thanks for report. This is an issue in ODBC driver + bad error handling in DBeaver.
Will be fixed in the next version.
