### ISSUE TITLE
Error in Routine "*RATE_DDL"  while generating DDL for a table - DB2 luw 9.7

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#771]
The operation failed with below text in the window. XXXXXXX is the database username. I am guessing it has something to do with the GRANT statements if DDL option is trying to generate those too. If you need specific information please let me know.

/* ERROR WHILE READING SOURCE:

SQL Error [38553]: Routine "*RATE_DDL" (specific name "*RATE_DDL") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: XXXXXXX,CREATE TABLE,SYSTOOLS".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.16.53
*/

**Comment by dbza** [comment]
The above was from the F4 -> view table option. I tried to do the same via connection >Schemas >Tables and it showed a different message

/* ERROR WHILE READING SOURCE:

SQL Error [38553]: Routine "DB2LK_GENERATE_DDL" (specific name "*TE_DDL") has returned an error SQLSTATE with diagnostic text "SQL0031 Reason code or token: /db2lkfun.bnd".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.16.53
*/

**Comment by serge-rider** [comment]
This is a known issue.
Check #492 (and #652).
