### ISSUE TITLE
Export schema oracle

### ISSUE THREAD

**Issue by huertas88** [serge-rider/dbeaver#772]
It is possible to make an export of the whole scheme in oracle?

**Comment by serge-rider** [comment]
No, it is not possible in current version.

**Comment by huertas88** [comment]
It is expected to add in new versions?

**Comment by serge-rider** [comment]
Not it the near versions.
At the moment we support full database export only for MySQL (PostgreSQL support is planned in one of near versions).
As far as I know Oracle do not have system utility which exports table data in SQL format. 
You can use standard DBeaver data export wizard (export to CSV, SQL, etc) but you can't export schema DDL.

**Comment by huertas88** [comment]
Thanks for your reply!
