### ISSUE TITLE
"Table Properties/Indexes" problem on version 3.7.5

### ISSUE THREAD

**Issue by roberto2357** [serge-rider/dbeaver#774]
I found a problem in "Table Properties/Indexes" visualization on Oracle connection. The fields names are not visible inside the index. Only the icons are visible.

Thanks.

**Comment by serge-rider** [comment]
Can't reproduce. Could you attach screenshot or some steps to reproduce.

**Comment by roberto2357** [comment]
![indexes](https://cloud.githubusercontent.com/assets/22471800/18874530/63669c1a-84c2-11e6-9a54-c07ed55605ff.png)

**Comment by serge-rider** [comment]
Well, I've reproduced that. Fix will be added in the next version.
Thanks for report.

**Comment by roberto2357** [comment]
Thank you very very much Serge !!
