### ISSUE TITLE
Delete table operation doesn't include database name.

### ISSUE THREAD

**Issue by adrinjalali** [serge-rider/dbeaver#775]
Hi,

I have a connection to an MSSQL server, having two databases DB1 and DB2.

Now assume I have a view V1 in DB1, and a table with the same name in DB2.

If my "active database" is DB1, and I browse to DB2 and find table V1, right click and try to "delete" the table, it gives me the error: "Cannot execute drop table on a view. V1 is a view, use drop table to drop a table". It seems to me that the name of the database is not included in the command, because if I set DB2 as the active database, the same procedure works fine.

Thanks,
Adrin.

**Comment by serge-rider** [comment]
Thanks for report.
Will be fixed in the next version (DBeaver will use catalog name in DDL operations with tables).

**Comment by adrinjalali** [comment]
Thanks for the fix, but I'm afraid this doesn't fix similar situations, since you have the `IsView()` condition there. This is what I did after checking your commit:

have `DB1` active, create a table `T1` in `DB1`. Then went to `DB2` (without making it the active database) and tried creating a table with the same name there. The persist window shows me that it doesn't include the database name, and when I try to persist, it tells me `T1` already exists. I believe it's safe to include catalog name in all ddl and query operations, which is what I do in my stored-procedures which use tables from different databases anyway.

**Comment by serge-rider** [comment]
Agreed, but SQL Server doesn't support `DROP VIEW` with catalog name. So there is nothing I can do about this. At least in Generic driver.

**Comment by adrinjalali** [comment]
I see. How about submitting the query as something like these ones?

```
declare @target_db nvarchar(255);
set @target_db = 'dbname';
declare @command nvarchar(500);
set @command = 'use ' + quotename(@target_db) + ';';
set @command = @command + 'create table testtable ( id int );'
execute sp_executesql @command;

declare @target_db nvarchar(255);
set @target_db = 'dbname';
declare @command nvarchar(500);
set @command = 'use ' + quotename(@target_db) + ';';
set @command = @command + 'drop table testtable;'
execute sp_executesql @command;
```

This way the active DB is changed for the little  session executing the command, and it doesn't affect the active database in the GUI. You might have a better way of wrapping commands though.

**Comment by serge-rider** [comment]
Yes, USE + DROP will work. But that's what I meant under "at least in Generic driver". This will require fully-functional SQL Server extension or refactoring of Generic extension to support such thing.
I.e. this is not easy.

**Comment by serge-rider** [comment]
Further improvements will be tracked in #810
