### ISSUE TITLE
Table autocomplete won't trigger after show view

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#776]
teradata has  a command called `show view <object_name>`

If I type `show table <schema>.` and press control space autocomplete triggers but if I type `show view <schema>.` it won't.

Note the exception here is that if show table exists earlier in the editor tab it will work.

![editor](https://cloud.githubusercontent.com/assets/9246654/18885343/2e4a7564-84a0-11e6-8088-bfb581f3b3d8.gif)

**Comment by serge-rider** [comment]
Thanks for report
