### ISSUE TITLE
Config option: disable "attribute binding" for queries

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#777]
Sometimes attribute binding (unique constraint and foreign keys resolution) takes a lot of time. Especially if you are working with remote database thru VPN over the globe (and if your database is Oracle).
Sometimes it is better to disable smart metadata read than to have ability to edit data/navigate foreign keys.

**Comment by serge-rider** [comment]
![query_metadata_read_config](https://cloud.githubusercontent.com/assets/6398845/18919155/c6398b02-85a5-11e6-9361-f1700028ecce.png)

**Comment by masebu** [comment]
This will be most welcome.
Eagerly awaiting 3.7.6 :-)
