### ISSUE TITLE
Problem using Chrome as the default browser

### ISSUE THREAD

**Issue by gfodranoel** [serge-rider/dbeaver#778]
When creating a new connection to a database, select the Oracle driver (Driver settings. For any link that will guide me to that site, happens an "Application Error." I conducted a test on two computers and the error happens to both. For another browser like Firefox, it worked perfectly. I'm using OS Windows 10.

**Comment by serge-rider** [comment]
Can't reproduce that.
Chrome acts exactly the same way as Firefox or IE or any other browser.
Does this problem happen only with driver download wizard or with any web links (e.g. about page)?

**Comment by gfodranoel** [comment]
The problem occurs when I click to make the driver download both the button as the link that redirects the page. This happened to the drivers for Oracle and DB2. With Firefox and IE worked perfectly.

**Comment by serge-rider** [comment]
Still can't reproduce. Works fine in Chrome on my test Windows machines.

DBeaver doesn't integrate with every browser. It just executes URL in shell. This works the same way on windows, Linux and Mac. Maybe there is something special with your Chrome installation?
