### ISSUE TITLE
Dbeaver Database Navigator "quick select" table

### ISSUE THREAD

**Issue by JaniWho** [serge-rider/dbeaver#779]
Hi,

First, massive "Thank You" for developing stuff like this!

Second, question about shortcut key:
Is there a shortcut key to open database table from Database Navigator -window to new SQL-editor window with complete select -statement?

Kind regards
-jani

**Comment by serge-rider** [comment]
Two options:
- You can open table, switch to tab Data, CTRL+click on table name in top-left corner. It will open SQL console with SELECT * FROM statement.
- You can right click on a table -> Generate SQL -> SELECT. Then open editor (CTRL+Enter) and paste generated query there.

**Comment by JaniWho** [comment]
Thank you for your quick reply,

Do you think it would be possible to dev such a shortcut key?
It would save time/energy/etc.

Now, if I double click table in Database Navigator i'll see colums and table data (and diagram), but if i need to create e.g. join select statement then it would be more simpler and easier with shortcut key to open complete select statement with all the columns in the table in a new SQL Editor window.

It may not seem as a big thing, but if i open dozens, maybe hundreds of tables and if I create several join select statements per day then it will take surprisingly lot of time and effort to open, copy-paste and close separate windows. 
Unfortunately "SELECT * FROM" doesn't help much, if i use only part of the columns of the table.

This is only a suggestion from my point of view, as a end-user of your product.

Kind regards
-jani

**Comment by serge-rider** [comment]
Agreed, this might be a useful feature.

**Comment by serge-rider** [comment]
![sql_console_from_table](https://cloud.githubusercontent.com/assets/6398845/18987369/04d8154e-870a-11e6-8eec-c4fe0ce77355.png)

**Comment by JaniWho** [comment]
Excellent!!!
And this will be on version 3.7.6?

Thank You!

Kind regards
-jani
