### ISSUE TITLE
Sybase jdbc driver code script does not accept 'go' in scripts.

### ISSUE THREAD

**Issue by hsplinter** [serge-rider/dbeaver#78]
Hi,

When using the SAP Tds client I get the following Error.

### Code:
```
-- install procedure for system wide usage in sybsystemprocs
use sybsystemprocs
go
 
-- drop stored procedure if exists
if object_id('sp_checkpoint') != null
begin
  drop proc sp_checkpoint
end
go
 
-- create stored procedure
create procedure sp_checkpoint
as
 
--------------------------------------------------------------------------------------------------------------
-- Author        : Harry Splinter   
-- Date          : 03 juli 2014
-- Purpose       : This stored procedure will perform a checkpoint in any database from any other database.
-- Dependencies  : None  
-- Modifications : -
--------------------------------------------------------------------------------------------------------------
 
begin 
  CHECKPOINT
  return 0
end
go
```
### Error:
```
DBCException: SQL Error [102] [42000]: Incorrect syntax near 'go'.
  com.sybase.jdbc3.jdbc.SybSQLException: SybSQLException: Incorrect syntax near 'go'.
```
### Info: 
- DBeaver Enterprise 3.5.3
- Microsoft Windows [Version 6.1.7601]  
- SAP(former) ASE 15.7 Client. jconn4.jar or jconn3.jar

Please advice,

Regards, Harry

**Comment by serge-rider** [comment]
If you created new (custom) driver for SAP Tds client then you could try this: 
- Go to the driver editor
- Open you driver
- Switch to "Adv. Parameters" tab
- Set "Script delimiter" to "go".
![adv-params](https://cloud.githubusercontent.com/assets/6398845/11422232/5d780c34-944b-11e5-9e63-65a439c5a090.png)

**Comment by hsplinter** [comment]
Hi Serge-rider,

thanks for the quick response. I already found that one.

![dbeaverdelimeter](https://cloud.githubusercontent.com/assets/16028357/11423108/e30fccb0-9441-11e5-90ea-ebd3678afa1b.jpg)

If you have any other thoughts please let me know

Regards,

Harry

**Comment by serge-rider** [comment]
So, it didn't help? The same error?

**Comment by hsplinter** [comment]
Yes, regret fully. But I keep on searching..... for an answer.

thanks for your help
