### ISSUE TITLE
Keyboard arrows not working while in "ctrl + f" mode

### ISSUE THREAD

**Issue by ashe23** [serge-rider/dbeaver#781]
For example if i hitting "ctrl+f" in table list, and while searching , i cant navigate between tables.
Version: 3.7.5

**Comment by serge-rider** [comment]
Could you clarify this (some screenshot maybe)?
I can't reproduce it - but maybe I'm just looking in a wrong place.

**Comment by ashe23** [comment]
![36863d95eb](https://cloud.githubusercontent.com/assets/8270558/18943310/67135f40-8627-11e6-855f-4ee75e2617b3.jpg)
Navigation between tables not working if i use keyboard arrows and buttons "Find next item" , "Find previous item" also not working.

**Comment by serge-rider** [comment]
Generally these keys are not supposed to work while focus is in text field.
Find next/previous buttons are atavism from previous implementation (they do not make sense now). Will remove them.

**Comment by your-mirror** [comment]
I think it will be a good feature to choose table via keyboard arrows. By this way you can select a necessary table and press "Enter" to open this table instead of using mouse.

**Comment by serge-rider** [comment]
Agreed, this makes sense.
