### ISSUE TITLE
Connection management improvement

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#782]
We need to improve connections management. 
Partially this task is covered in #297 (folders hierarchy).
Another ideas:
- Connections filter (similar to drivers filter)
- Folders coloring
- Tagging (it overlaps with folders)

Maybe some presentation switcher is needed in database navigator (flat, folders, tags)

**Comment by karora** [comment]
One really annoying issue I have related to connections, is running on a laptop which is suspended / resumed regularly....

Naturally when I resume from a different IP address, my connections all fail, and dbeaver fails them immediately in this situation, but even after this, when I click on "Disconnect", so I can "Reconnect", the disconnection takes so long that I end up quitting DBeaver and restarting it instead.

**Comment by serge-rider** [comment]
Nested folders management will be added in the next version.
