### ISSUE TITLE
Dbeaver 3.7.5 not working on ubuntu 16.04

### ISSUE THREAD

**Issue by DwordPtr** [serge-rider/dbeaver#789]
I upgraded from 3.7.4 to 3.7.5 and Dbeaver is no longer usable.

![dbeaver375broken](https://cloud.githubusercontent.com/assets/3793678/18955905/ec9bda2e-861e-11e6-836f-49c4a2bad947.png)

**Comment by carlosjrcabello** [comment]
Hi there,

Try to reset perspective at Window / reset perspective.

**Comment by DwordPtr** [comment]
I'm unable to do that. The UI is also mostly unresponsive. The two drop downs work, but I can't bring up any options menus by pressing alt.

**Comment by DwordPtr** [comment]
I downgraded and still had the same issue. Must be a library bug.

**Comment by serge-rider** [comment]
Try to remove DBeaver completely and reinstall.
It doesn't help try to reset workspace (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace)

**Comment by DwordPtr** [comment]
![dbeaver375broken2](https://cloud.githubusercontent.com/assets/3793678/18962685/74c1804e-8637-11e6-95e8-8be3af2860f5.png)

This is what I get after reseting the workspace.

**Comment by serge-rider** [comment]
Ugh.
(I assume that you have tried to reinstall DBeaver).

Try to delete directory `%HOMEPATH%\.dbeaver\.metadata\` (this must help - otherwise I give up).

**Comment by DwordPtr** [comment]
I deleted the directory. I'll just use the intellij db console. Thanks for your help though.

**Comment by serge-rider** [comment]
Well, something really bad happened.
Thanks for report anyway.

One last thing - are there any error/debug logs? This might help other people (at least we'll know what's going on - even if this is gtk-related).

**Comment by DwordPtr** [comment]
Heres my logfile.

[dbeaver-debug.log.txt](https://github.com/serge-rider/dbeaver/files/501403/dbeaver-debug.log.txt)

**Comment by serge-rider** [comment]
Thanks!
Most likely you are using Java 9 (OpenJDK Early Access). For some reason it doesn't contain javax.activation library (besides other issues).
Anyhow - I'll fix this. DBeaver don't really need this dependency.
