### ISSUE TITLE
Fuzzy auto-complete

### ISSUE THREAD

**Issue by esambo** [serge-rider/dbeaver#790]
I really like the fuzzy auto complete that some editors, IDE's or even bash history have. It makes me so much more productive if I can type in just some random character of the column, schema, table name, etc, as long as they are in the right order.

**Comment by serge-rider** [comment]
In fact DBeaver already supports fuzzy auto-complete. You can press `CTRL+Space` and type just a few letters which you hope to see in table name.

**Comment by esambo** [comment]
👍 Indeed, I wasn't aware of that new feature, very nice!
