### ISSUE TITLE
macOS Sierra Gatekeeper prevents app from starting

### ISSUE THREAD

**Issue by esambo** [serge-rider/dbeaver#791]
### Problem
The Apple: System Preferences: Security & Privacy: General: _Allow apps downloaded from:_ settings has changed in macOS Sierra (Version 10.12). `Anywhere` is **not** an option anymore as it has been since the introduction of Gatekeeper in OS X [Version 10.7.5](https://support.apple.com/en-us/HT202496) in Lion.

### Error
Download a DMG file, copying it into _/Applications/_, right clicking on it and selecting _Open_ now causes following error:
`"Dbeaver.app" is damaged and can't be opened. You should move it to the Trash.`

### Fix
1. The cleanest solution would probably be to add a [Provisioning](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppStoreDistributionTutorial/CreatingYourTeamProvisioningProfile/CreatingYourTeamProvisioningProfile.html) [Profile](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html) like [Airmail Beta does](https://rink.hockeyapp.net/apps/84be85c3331ee1d222fd7f0b59e41b04).
2. Otherwise, please update your [Install](http://dbeaver.jkiss.org/download/) instructions for macOS X. The current ones only mention the [workaround](https://support.apple.com/en-us/HT202491) that don't mention anything regarding the new macOS Version 10.12 (Sierra).
  1. One [solution from StackExchange](http://apple.stackexchange.com/questions/243687/allow-applications-downloaded-from-anywhere-in-macos-sierra#answer-253943) would be to execute following in the _Applications/Utilities/Terminal.app_: `sudo xattr -r -d com.apple.quarantine /Applications/DBeaver.app`
  2. Another solution is to temporarily disable Gatekeeper:
    - [How to Allow Apps from Anywhere in macOS Sierra Gatekeeper](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/)
    - http://apple.stackexchange.com/questions/243687/allow-applications-downloaded-from-anywhere-in-macos-sierra#answer-245029

**Comment by serge-rider** [comment]
Check #95 for other possible solutions

**Comment by esambo** [comment]
Nice. Perhaps add a link to this GitHub issue on the installation instructions for macOS http://dbeaver.jkiss.org/download/

**Comment by serge-rider** [comment]
Good point. Will do.

**Comment by maxisme** [comment]
This fixed it for me as a replacement for `zip`:

```
ditto -c -k --sequesterRsrc --keepParent <src_path_to_app> <zip_dest>
```
