### ISSUE TITLE
SQL Formatting improvements

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#792]
A few possible improvements in appearance

1.  Text under selection loses color and becomes the default single color
2. Keywords/datatypes appear in bold by default. This is not as pronounced in the default font, but IMO there should be a way to turn this off 
3. VARCHAR2 is not identified as a SQL Datatype

Screenshot with SQL Developer for comparison on left.

![image](https://cloud.githubusercontent.com/assets/419093/18976797/ab9b60b2-8669-11e6-976a-ca3dca1ed8fd.png)

**Comment by serge-rider** [comment]
I'm afraid I can't do it.
As far as I know Eclipse framework doesn't support selection coloring.
