### ISSUE TITLE
Keyboard shortcut for schema / suggestions refresh

### ISSUE THREAD

**Issue by someotherdataguy** [serge-rider/dbeaver#793]
Quite often when creating or modifying objects on the server, I want to then immediately run statements against these objects (in the same session). Is there a keyboard shortcut that I can use to refresh the meta data information so the auto-complete knows about my changes?

Could it also automatically refresh on a timer? Eg, every 1 minute? (configurable of course)

Many thanks

**Comment by serge-rider** [comment]
You can refresh metadata in Database Navigator view (`F5` on schema/database).
No, there is no auto-refresh feature.
