### ISSUE TITLE
PostgreSQL multi-dimensional arrays support

### ISSUE THREAD

**Issue by cristianpsg** [serge-rider/dbeaver#798]
Hi,
I'm receiving the below error with a field of type varchar[]
"{{text,text......,text}}"
Unrecognized type '[Ljava.lang.String;' - can't convert to string

**Comment by serge-rider** [comment]
Can't reproduce. 
Please post sample DDL with data inserts.

**Comment by cristianpsg** [comment]
CREATE TABLE test.poll_set (
	poll_set_id int4 NULL,
	poll_set_description varchar NOT NULL,
	poll_type varchar NOT NULL,
	mib_version varchar[] NOT NULL,
	oid_names varchar[] NOT NULL,
	community_strings varchar[] NOT NULL,
	CONSTRAINT poll_result_uk UNIQUE (poll_set_id,mib_version,oid_names,community_strings)
)
WITH (
	OIDS=FALSE
);

INSERT INTO poll_set VALUES (1, 'Poll set description', 'PST1', '{MACHINE-MIB}', '{{value1,value2,value3,value4,value5}}', '{{public,public,public,public}}');
INSERT INTO poll_set VALUES (2, 'Poll set description', 'PST2', '{MACHINE-MIB}', '{{value1,value2,value3,value4,value5}}', '{{public,public,public,public}}');


poll_set_id |poll_set_description |poll_type |mib_version   |oid_names                      |community_strings              |
------------|---------------------|----------|--------------|-------------------------------|-------------------------------|
1           |Poll set description |PST1      |{MACHINE-MIB} |{[Ljava.lang.String;@6b82fde0} |{[Ljava.lang.String;@64e9b444} |
2           |Poll set description |PST2      |{MACHINE-MIB} |{[Ljava.lang.String;@2b3a101e} |{[Ljava.lang.String;@70f837bd} |

**Comment by serge-rider** [comment]
Interesting. I've reproduced that but I'm not sure how to handle it.

According to DDL all 3 arrays columns have type varchar[].
But in inserts you set only mib_version values correctly. While oid_names and community_strings are two-dimensional arrays (`{{..}}` - good value for varchar[][]). 
It is surprising that PostgreSQL lets to insert such obviously incorrect data. Maybe I'm missing something or maybe it makes sense to write a bug report to PG team.
Anyhow - DBeaver get first element of array (which must be a varchar but in fact it is a yet another array) and can't convert it into anything valuable.

Have any thoughts?

**Comment by cristianpsg** [comment]
Hi Serge,

Thank you for taking time and look into this.

I dug  a bit more and I realized that when the table is described the DDL is not showing the field as a multidimensional array, also last time I took the DDL from the pgadmin3 console and in the same way is just showing the fields as unidimensional arrays.

test-# \d test.poll_set1
                 Table "test.poll_set1"
        Column        |        Type         | Modifiers 
----------------------+---------------------+-----------
 poll_set_id          | integer             | 
 poll_set_description | character varying   | not null
 poll_type            | character varying   | not null
 mib_version          | character varying[] | not null
 oid_names            | character varying[] | not null
 community_strings    | character varying[] | not null

So in any case if you use the DDL below that explicitly defines the oid_names and community_strings as multidimensional arrays, still DBeaver is not able to display the data.

To me postgres is not making difference between varchar[] or varchar[][] that I guess created the issues when you are trying to display the data, I hope this information could help you to find a solution.

CREATE TABLE test.poll_set1 (
poll_set_id int4 NULL,
poll_set_description varchar NOT NULL,
poll_type varchar NOT NULL,
mib_version varchar[] NOT NULL,
oid_names varchar[][] NOT NULL,
community_strings varchar[][] NOT NULL
)

INSERT INTO poll_set1 VALUES (1, 'Poll set description', 'PST1', '{MACHINE1-MIB,MACHINE2-MIB}', '{{value1,value2},{values1,value2}}', '{{public,public},{public,public}}');
INSERT INTO poll_set1 VALUES (2, 'Poll set description', 'PST2', '{MACHINE1-MIB,MACHINE2-MIB}', '{{value1,value2},{values1,value2}}', '{{public,public},{public,public}}');

poll_set_id |poll_set_description |poll_type |mib_version                 |oid_names                                                   |community_strings                                           |
------------|---------------------|----------|----------------------------|------------------------------------------------------------|------------------------------------------------------------|
1           |Poll set description |PST1      |{MACHINE1-MIB,MACHINE2-MIB} |{[Ljava.lang.String;@3ba33084,[Ljava.lang.String;@56c648b2} |{[Ljava.lang.String;@73ceca9f,[Ljava.lang.String;@d58c81f}  |
2           |Poll set description |PST2      |{MACHINE1-MIB,MACHINE2-MIB} |{[Ljava.lang.String;@63fc6493,[Ljava.lang.String;@4f2f222d} |{[Ljava.lang.String;@1f6ce0f8,[Ljava.lang.String;@2525c9e6} |

**Comment by serge-rider** [comment]
So, PostgreSQL array may have any number of dimensions.
No sure how visualize this in grid. In any case I can convert array to string to see value. But items edit won't be accessible in case of multi-dimensional arrays.

**Comment by cristianpsg** [comment]
Hi Serge,
I tested the change and looks great, thank you.
I noticed something though every time I double clicked on the field to get the value, the value windows open and the previous one remains there, also if you click on the X to close the previous one the value widget closes but it's not destroying the object.  in the image below you can see what I'm trying to describe.

I did the same test with the official release and doesn't behave this way, so It may be something introduced with your last change or something else, anyway I wanted to let you know in case you have not spotted the issue.

![2016-10-06_14-31-27](https://cloud.githubusercontent.com/assets/15220401/19165605/6e1e27d8-8bd2-11e6-9ec0-afad306d861f.png)

**Comment by serge-rider** [comment]
Hm. That's odd. And I can't reproduce it.
Do you have the most recent version from `devel` branch? There were some bugs which were fixed just a day or two ago.
