### ISSUE TITLE
Oracle: export result set as insert statement

### ISSUE THREAD

**Issue by guidobonerz** [serge-rider/dbeaver#800]
Hi, when I try to export a result set as insert statements. dbeaver creates the statements in MySQL style which is not supported by oracle db. In oracle SQL an insert statement can only have one set of values whether MySQL supports more.

Best regards
Guido

**Comment by serge-rider** [comment]
You can handle this by setting export parameter "Data rows per statement" to 1 (it is on second parameters page of export wizard).

**Comment by guidobonerz** [comment]
Hi Serge,

yes that's true. When i set the row parameter to 1. dbeaver creates one 
row per insert.

but when i try to execute this set of insert statements, it fails. the 
oracle message sound like 'undefined character', have to check it exactly.

i think dbeaver has a problem with the ";" letter at the end of a row. 
don't ask me why.

when i only execute one insert statement it works.


best regards

Guido

**Comment by serge-rider** [comment]
To execute a script use CTRL+X. DBeaver will execute queries one by one.

**Comment by serge-rider** [comment]
Line feeds (`;` on the new line) issue will be fixed in the next version.
