### ISSUE TITLE
improve Export result feature

### ISSUE THREAD

**Issue by parisni** [serge-rider/dbeaver#801]
Hello,

Two ways to improve export result in dbeaver:

1. To export result (as csv, json...), one have to first run a query. This poses problems because query is then run 2 times. This would be great to be able to save 1 time. Eg: right click on a SELECT statement -> export result
1. The data format is bad in oracle for integers, "100 000" instead of 100000 -> integer are broken

Thanks

**Comment by serge-rider** [comment]
1. This feature is already there. Right click on query in editor->Execute->Export from Query.
2.1 For SQL export format default data formatting is used for numbers (no dividers)
2.2 Data format is customizable (3rd page of export wizard)

**Comment by masebu** [comment]
Hi,

as for 2, I'm not sure that data formatting profiles are managed properly.
I have grouping enabled for numbers on my _<Global>_ profile but not on my _export_ profile.
Even though I select the export profile in "export settings", I still get a separator for thousands.
If I change my _<Global>_ profile not to use grouping, exported results are fine.

Regards,
<img width="544" alt="dbeaver_export_profile" src="https://cloud.githubusercontent.com/assets/19706602/19071036/650fc1e2-8a2e-11e6-9b60-4303345fbcf3.png">
<img width="454" alt="dbeaver_global_profile" src="https://cloud.githubusercontent.com/assets/19706602/19071038/651ad7b2-8a2e-11e6-95b0-848fedac58fe.png">
<img width="127" alt="dbeaver_exported_numbers" src="https://cloud.githubusercontent.com/assets/19706602/19071037/6512e37c-8a2e-11e6-8abe-d6e847477a59.png">

**Comment by serge-rider** [comment]
This is a bug (default format used isntead of export format).
Will be fixed in the next version, thanks for report.
