### ISSUE TITLE
Default constraints are not displayed in table properties in SQL Server

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#804]
I have a table's column with a default value, but I don't see it in the table properties, and if I try to delete it from there I get an error
```
The object [CONSTRAINT_NAME] is dependent on column [COLUMN_NAME]
```

**Comment by serge-rider** [comment]
Can you post a sample DDL?

**Comment by gabriele-ricci-kyklos** [comment]
Something like
```SQL
CREATE TABLE AAA
(
    I BIGINT NOT NULL PRIMARY KEY,
    X INTEGER NOT NULL DEFAULT 1
)
GO
```
If you try to do
```SQL
ALTER TABLE AAA DROP COLUMN X
```
You'll get the error. A way to delete this column is to query the table sys.default_constraints to find the constraint's name
```SQL
SELECT * FROM sys.default_constraints WHERE name LIKE '%aaa%'
ALTER TABLE AAA DROP CONSTRAINT DF__aaa__x__08EB22EA
```

Then you can drop the column

**Comment by serge-rider** [comment]
It is not possible to handle this in Generic driver.
Because JDBC interface doesn't provide information about non-unique table constraints (like CHECK).
This feature will be tracked in #810 (SQL Server extension).
