### ISSUE TITLE
Missing placeholder replacement when editing a table from the program

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [serge-rider/dbeaver#805]
If I try to delete a column from a table using the program, when I close the tab I'm asked
```
The object {0} has been edited. Do you want to save these changes in the db?
```

(The message is translated by me, because I have dbeaver in Italian)

The placeholder is not resolved

**Comment by serge-rider** [comment]
This is a bug in Italian localization. Thanks for report.
