### ISSUE TITLE
Issues compiling a procedure in Oracle

### ISSUE THREAD

**Issue by davitof** [serge-rider/dbeaver#806]
Hello,

I believe I found a bug when compiling a procedure on Oracle. I am currently using Oracle XE 11.2.0.2.0, dBeaver 3.7.5, Oracle plugin2.1.26, Oracle drivers 11.2.0.4.

Here is the code I used for my tests:
```
create or replace procedure test (i_nom_fichier in varchar2)
as
  l_apporteur_actuel varchar2 (10) ;
begin
  l_apporteur_actuel := i_nom_fichier ;
end test ;
```

dBeaver only, first test : Select all code and press Alt+X
```
SQL Error [6550] [65000]: ORA-06550: line 2, column 3:
PLS-00201: identifier 'L_APPORTEUR_ACTUEL' must be declared
ORA-06550: line 2, column 3:
PL/SQL: Statement ignored

SQL Error [6550] [65000]: ORA-06550: line 2, column 3:
PLS-00201: identifier 'L_APPORTEUR_ACTUEL' must be declared
ORA-06550: line 2, column 3:
PL/SQL: Statement ignored

  ORA-06550: line 2, column 3:
PLS-00201: identifier 'L_APPORTEUR_ACTUEL' must be declared
ORA-06550: line 2, column 3:
PL/SQL: Statement ignored

  ORA-06550: line 2, column 3:
PLS-00201: identifier 'L_APPORTEUR_ACTUEL' must be declared
ORA-06550: line 2, column 3:
PL/SQL: Statement ignored
```

dBeaver only, second test : cursor on first line and Ctrl+Enter
A green line appears in the statistics tab but in the Database Navigator, the Test entry has still a red mark, which I take means it is wrong. So I right-click on "Test" in the Database Navigator, then choose "Compile procedure"
```
[3:34] PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   := ; not null default character
```

Now a few tests using SQL Developer too as a reference:
In SQL Developer, same source code in a SQL Window
Ctrl+Enter on any line : 
`Elément Procedure TEST compilé`
In the SQL Developer equivalent of the Database Navigator, pressing Ctrl+R (to refresh) shows that the Test procedure is indeed correctly compiled.

Mixed test: Alt+X in dBeaver (triggers the errors above), in SQL Developer after refreshing, Test is marked red and the code is truncated:
```
create or replace procedure test (i_nom_fichier in varchar2)
as
  l_apporteur_actuel varchar2 (10)
```

Mixed test: Ctrl+Enter in dBeaver (triggers the error above), in SQL Developer after refreshing, Test is marked red and the code is truncated too, but in a different way:
```
create or replace procedure test (i_nom_fichier in varchar2)
as
  l_apporteur_actuel varchar2 (10) ;
begin
  l_apporteur_actuel := i_nom_fichier ;
end test   
```
(see the missing semicolon at the end)

**Comment by serge-rider** [comment]
To execute complex PL/SQL it is better to select statement and execute it with CTRL+Enter. Sometimes DBeaver fails to parse queries - PL/SQL support is still under development.

**Comment by davitof** [comment]
Sorry, I missed your answer, too much work. OK, I'll use SQL Developer when I want to compile procedures.
