### ISSUE TITLE
SQL Editor - bad script interpretation when using '\'

### ISSUE THREAD

**Issue by masebu** [serge-rider/dbeaver#807]
Hi,

I sometimes use `WHERE COMPANY LIKE 'A\_B%' ESCAPE '\'`
dbeaver has trouble with '\'

First, it produces bad syntax highlighting, similar as what is described in #543 
<img width="384" alt="dbeaver_escape_syntax_color_01" src="https://cloud.githubusercontent.com/assets/19706602/19094152/e76b49bc-8a8e-11e6-92f8-394974e48f68.png">
<img width="383" alt="dbeaver_escape_syntax_color_02" src="https://cloud.githubusercontent.com/assets/19706602/19094153/e76cae74-8a8e-11e6-9334-08db3a35884c.png">
<img width="453" alt="dbeaver_escape_syntax_color_03" src="https://cloud.githubusercontent.com/assets/19706602/19094154/e76d9c76-8a8e-11e6-832c-d309e2f3c2b2.png">

But it gets worse than that: if '\' is present more than once in a script, statement terminators are ignored.

For instance, if you have in an editor
```SELECT * FROM DUAL WHERE 1 LIKE 1 ESCAPE '\';
SELECT * FROM DUAL WHERE 1 LIKE 1 ESCAPE '\';```

Executing 1st statement gives a "SQL command not properly ended" error
<img width="460" alt="dbeaver_escape_stmterr" src="https://cloud.githubusercontent.com/assets/19706602/19094507/b19eebe8-8a90-11e6-8e53-a90082d516ff.png">

Removing ESCAPE '\' on either line makes everything ok (for instance using ESCAPE '!' instead)

Regards

**Comment by serge-rider** [comment]
It is a bug (in one of recent versions). Backslash character is evaluated incorrectly in strings. Will be fixed in the next version, thanks for report.

**Comment by serge-rider** [comment]
For now as a workaround you can select query and then execute it with ctrl+enter.
