### ISSUE TITLE
mariadb on non standard port - database export

### ISSUE THREAD

**Issue by CoyoteCzech** [serge-rider/dbeaver#808]
Tested on platform MariaDB.  
Consider you have access to remote database server over ssh only. If you use local port forwarding, for example local port 13306 to remote port 3306 (ssh -L 13306:localhost:3306 ...), everything works fine except export.

Export always connect to standard port 3306 on your localhost in this case, so database cannot be exported.

**Comment by serge-rider** [comment]
Try this workaround: http://dbeaver.jkiss.org/forum/viewtopic.php?f=2&t=1270&p=2917
Basically just try to replace `localhost` with `127.0.0.1`

**Comment by CoyoteCzech** [comment]
I forget, mysqldump connect to socket with localhost and ignore network port by default.
Thanks for help.
