### ISSUE TITLE
PostgreSQL - Unable to edit values in db, autocomplete not working, when connection to db was lost and is re-established again

### ISSUE THREAD

**Issue by sanneinther2013** [serge-rider/dbeaver#809]
DBeaver version 3.7.5

Steps to reproduce
- Open DBeaver and do a select on a table (in a PostgreSQL database) by double clicking it in the tables tree
- Restart PostgreSql database server (service)
- Or create a new database with the same name and same content
- Go back to DBeaver en try to edit a value in the table that was selected before
- Nothing seems to happen, the to be edited cell is grey
- Also when typing a new query the autocomplete function doesn't work anymore

To work around this issue you can disconnect and connect again to the database. Then you will be able to edit values and autocomplete is working again.
Note that this also happens when you restore a database backup without disconnecting from the database first.
Was hoping these two things could be solved by trying to reconnect to the database automatically again if no active connection is found :-) If you have any questions don't hesitate to contact me. Thanks!

**Comment by vmoraru** [comment]
This also happens when you restore a database backup without disconnecting from the database first.

**Comment by vmoraru** [comment]
It would seem like there is some sort of timeout/UI issue, I noticed that values can be edited for tables that I had opened beforehand, but any new tables need the aforementioned workaround, however, if I open a new SQL Editor window and execute an update script there, it works.

**Comment by serge-rider** [comment]
Partially this will be resolved by fixing PG metadata refresh function.
Will try to reproduce errors above a bit later.

**Comment by Yoshimit** [comment]
For me, the autocomplete do not work again after reconnecting.

**Comment by serge-rider** [comment]
Please check how it works in 3.7.8. There were a few fixes of PG metadata reading.

**Comment by vmoraru** [comment]
It works better, however, if you restore the database from a backup without closing the connection first or at very least restart after retoring, you would still not be able to edit cells of the newly open (those that you open after restoring) tables from the UI.

**Comment by serge-rider** [comment]
Thanks.
After database restore (outside of DBeaver) you need to refresh database metadata. Replacing database changes too many objects.
After implementation of #796 DBeaver will automatically refresh restored database.

Closing..
