### ISSUE TITLE
Null displayed in results for date converted to text and named as original

### ISSUE THREAD

**Issue by conceptrat** [serge-rider/dbeaver#81]
Tried to make the title as informative as possible.

So I have a simple SELECT query, running on an Oracle 10.2 database, that returns some data including two date fields.  You'll see below that I'm converting to date fields to text using TO_CHAR and naming them the same as the original fields in the table.  The resulting text field shows up as NULL and not the 'YYYY-MM-DD' I was expecting and retrieving a further set of rows results in an error (also see below).  If I change the output name to something other than the original name everything is hunky dory.

This worked in 3.5.4 but not in 3.5.5.  I suspect that perhaps this is to do with the "new" grid code.

Anyway here's a straight select from the table without the conversion and then with the conversion as well as the error:

```
SELECT
	INVOICENO,
	INVOICE_FROM_DATE,
	INVOICE_TO_DATE,
	DET_UNITS,
	DET_DOLLARS
FROM
	ADHOC_REPORTS.F_GENE_AOG_INV
WHERE
	TO_CHAR(INVOICE_TO_DATE,'YYYYQ') = '20153'
ORDER BY
	INVOICENO,
	INVOICE_TO_DATE
```
which produces this:

![dbeaver_straight](https://cloud.githubusercontent.com/assets/831863/11464240/84109d2c-9791-11e5-88bb-418616e2c946.jpg)

All good.  However this select:
```
SELECT
	INVOICENO,
	TO_CHAR(INVOICE_FROM_DATE,'YYYY-MM-DD') AS INVOICE_FROM_DATE,
	TO_CHAR(INVOICE_TO_DATE,'YYYY-MM-DD') AS INVOICE_TO_DATE,
	DET_UNITS,
	DET_DOLLARS
FROM
	ADHOC_REPORTS.F_GENE_AOG_INV
WHERE
	TO_CHAR(INVOICE_TO_DATE,'YYYYQ') = '20153'
ORDER BY
	INVOICENO,
	INVOICE_TO_DATE
```
Returns this:

![dbeaver_null](https://cloud.githubusercontent.com/assets/831863/11464268/c9390fec-9791-11e5-8938-1ffbd6640373.jpg)

And gives this error on retrieve next set of rows:

![dbeaver_error](https://cloud.githubusercontent.com/assets/831863/11464190/d422e28a-9790-11e5-9839-5e544b72d010.jpg)

And this select:
```
SELECT
	INVOICENO,
	TO_CHAR(INVOICE_FROM_DATE,'YYYY-MM-DD') AS INV_FROM_DATE,
	TO_CHAR(INVOICE_TO_DATE,'YYYY-MM-DD') AS INV_TO_DATE,
	DET_UNITS,
	DET_DOLLARS
FROM
	ADHOC_REPORTS.F_GENE_AOG_INV
WHERE
	TO_CHAR(INVOICE_TO_DATE,'YYYYQ') = '20153'
ORDER BY
	INVOICENO,
	INVOICE_TO_DATE
```
Returns:

![dbeaver_newname](https://cloud.githubusercontent.com/assets/831863/11464299/2bbb560c-9792-11e5-8f31-fed4e69a954a.jpg)

Which is what I wanted except for the field names.  It's also fine if you don't supply a new field name as the field is named with the full calculated field name which I don't really want.

**Comment by serge-rider** [comment]
Yep, 3.5.5 has a fix in query metadata reading. And this fix added yet another bug.
Honestly I never thought about such situation - when you query a table and transform column types while keep column names.
Going to improve SQL query analyzer..
