### ISSUE TITLE
Error: Bind parameter issue when formatting SQL

### ISSUE THREAD

**Issue by adamitj** [serge-rider/dbeaver#812]
When formatting a SQL statement all bind parameters gets a space between the colon and the first character of parameter name. Although this is not an issue with few parameters, when I have a SQL statement with 1 or 2 parameters distributed all along the text (let's say, like, 20 or more places)  a replace operation is needed.

Luckily I always define the bind parameters starting with "RA_", so the replace operation is flawless with my own SQL statements. However, when working with someone's else scripts, this is a huge pain (that's because I work with many projects and many databases, lots of SQL writers...).

A single SQL like:
`SELECT * FROM DEBT_SHEET WHERE DEBT_DATE BETWEEN :RA_DATEINI AND :RA_DATEEND`

turns into:
```
SELECT
	*
FROM
	DEBT_SHEET
WHERE
	DEBT_DATE BETWEEN : RA_DATEINI AND : RA_DATEEND
```

Then I need to check every ":" and remove the space to make it work again.

Note 1: I have tested with IBM DB2 LUW, couldn't test with other RDBMS as I'm travelling only with my notebook now;
Note 2: A good workaround is to use replace feature, but only works if all parameters have the same preffix.

**Comment by serge-rider** [comment]
Yes, it is a formatter bug.
Almost the same as #803. Will be fixed in the next version, thanks for report.
