### ISSUE TITLE
PostgreSQL - DDL generation for sequences does not work

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#813]
Hi,

DBeaver 3.7.5
PostgreSQL 9.5.4

I try to get the DDL of a sequence with a left clic to the sequence in the database navigator, then "Generate SQL", then "DDL".
I get a NullPointerException.

I suppose this is not supported yet, isn't it?

Regards,
Cedric

**Comment by serge-rider** [comment]
Yep.
But that's easy to do, I'll add it in the next version.

**Comment by ced75** [comment]
Thanks for reactivity.
