### ISSUE TITLE
The new search UI can't search any columns.

### ISSUE THREAD

**Issue by TseuX** [serge-rider/dbeaver#814]
Hello,

the new search UI (since 3.7.4) has no option for a search of column name. 

![image](https://cloud.githubusercontent.com/assets/20822357/19125632/d86367fc-8b05-11e6-82a8-0b6578bf603c.png)

No column name, only table name will be find. With the old search UI, we could search any database object, is there a new way to do it ?

thank you. 

Configuration : 3.7.5 with Sybase driver

**Comment by serge-rider** [comment]
New search UI acts exactly as old one.
You can search columns only in MySQL, PostgreSQL and DB2.
Generic driver (including Sybase) doesn't support this feature.

**Comment by Chealer** [comment]
Columns can be searched with the metadata (second) tab of Search (Ctrl+H).
