### ISSUE TITLE
Display multiple results of select - in tabs

### ISSUE THREAD

**Issue by shivan** [serge-rider/dbeaver#817]
Nice would be, when executing the following SQLs:
`select * from TableA;`
`select * from TableB;`

It would be great when marking and executing both, if there will be shown 2 Tabs in the result. One Tab for each result grid.

**Comment by serge-rider** [comment]
This is possible with "Execute in new tab" command. `CTRL+\`.

**Comment by shivan** [comment]
You mean, Ctrl+Alt+X -- "Execute Statements in separate Tabs"
Thats exactly what I meant. Thanks!

**Comment by eric-szakacs** [comment]
any way to do this by default?

**Comment by guai** [comment]
will in this case dbeaver split statements on client side send them independently, and display singular result sets, or will there be multiple result sets returned from DB?

**Comment by iKoru** [comment]
@eric-szakacs try to switch your shortcuts as default.
