### ISSUE TITLE
colored border around SQL window - depending on connection type

### ISSUE THREAD

**Issue by shivan** [serge-rider/dbeaver#818]
It would be great when the color of the border of the sql window would be the same as defined in connection type. 

So new checkbox in Connection Types Properties Dialog:
[ ] colorize sql editor border

**Comment by serge-rider** [comment]
What do you mean under border? If tab color then there is a lready a feature request for that (#300)

**Comment by shivan** [comment]
I mean a colored border around the sql editor area. See screenshot of another SQL tool (here it's dashed):

![line around sql area](https://cloud.githubusercontent.com/assets/1827692/19153274/221c8506-8bd6-11e6-9356-46c4ec9b8487.png)

**Comment by serge-rider** [comment]
I can change border color for active editor.
Don't think that extra config option is necessary.
Will try in the next version.

**Comment by shivan** [comment]
Great!

**Comment by chriszrc** [comment]
Should the border color at this point reflect the color of the connection type? It doesn't appear to be doing this?
