### ISSUE TITLE
Missing Datatype column since 3.7.5 (Ubuntu)

### ISSUE THREAD

**Issue by michael-82** [serge-rider/dbeaver#821]
Hi there,

since the latest update, when I create a new column in a table, the selection for the datatype is not shown and each column will be a varchar(100) by default.

This occurs in Ubuntu Gnome 16.04. In Windows 10 it is working fine. And in 3.7.4 it was still working on ubuntu.

**Comment by serge-rider** [comment]
Can't reproduce.
What database?

**Comment by michael-82** [comment]
postgresql 9.3 as well as 9.5
![screenshot from 2016-10-06 17-36-55](https://cloud.githubusercontent.com/assets/21363657/19159110/84078576-8beb-11e6-9823-83c0a2e4ae7a.png)

**Comment by serge-rider** [comment]
Seems to be the same as #774.

**Comment by michael-82** [comment]
Ah ok - thanks :)
