### ISSUE TITLE
set column nullable - column view shows old value

### ISSUE THREAD

**Issue by frankmusolf** [serge-rider/dbeaver#823]
After
ALTER TABLE t ALTER c DROP NOT NULL
shows Table-Properties-View (double click on table in Database Navigator) true for 'Not Null'.

After Reconnect shows Table-Properties-View also true for 'Not Null'.

After Disconnect and connect shows Table-Properties-View false for 'Not Null'.
Regards
Frank

**Comment by serge-rider** [comment]
You can use "Refresh" (F5) command in navigator tree to reload altered objects.
Invalidate/reconnect doesn't force reconnect - it just checks for dead connection and reconnects on demand.

**Comment by frankmusolf** [comment]
I try refresh on right mouse menu without any effect. After ALTER TABLE column shows NOT NULL.

reconnect - in my opinion it should be inactive and only active if connection status is broken
