### ISSUE TITLE
Ability to import connections

### ISSUE THREAD

**Issue by shivan** [serge-rider/dbeaver#826]
It would be great to have a rudimentary connection import from DBVisualizer.
# fields to import

In my optionion imported should be:
- connection infos (servername, port, database, username)
- maybe password, but that's encrypted, so can be left out I think
- folder structure
# source data

The source data can be found here:
`<userdir>\.dbiv\config70` (or if later version "config")
There you find a dbvis.xml.
## The nodes

DBVisualizer\Databases <- contain db connections
there 
Alias => Name
Driver => Driver
UserId = username

Either URL is set with a Java connectionstring or at UrlVariables\Driver there are URlVariables set
`<URLVariable UrlVariableName="Server">myValue</UrlVariable>`
Names are: Server, Port, Database

Properties contain for example on DB2:
`<Properties>`
`<Property key="retrieveMessagesFromServerOnGetMessage">true</Property>`
`</Properties>`
Which means show detailed errormessages by db2.
## folder structure

The node "Objects" shows the treeview structure of the connections. Folder = folder, Database references the database entry by id.

I think other properties maybe left out in the first step.

**Comment by serge-rider** [comment]
This feature is already there. Main menu File -> Import -> Third Party Configuration.
Note: some importers may be outdated.

**Comment by shivan** [comment]
Great.

Some notes:
1) when asking for a driver, some more information would be nice (connection name for which it's asked)
2) select all option in the import-list
3) import folder structure, too

**Comment by rml1997** [comment]
I like to generate my configuration from bash, importing a file we use to specify databases to generate .dbeaver-data-sources.xml. Will this still be supported within the new security framework in 3.8.1 and, as a seperate question, will the dbeaver importers still work?

**Comment by serge-rider** [comment]
3.8.1 will have full backward compatibility. Datasources configuration won't change.
