### ISSUE TITLE
Refreshing grid view in record mode switches back to grid mode

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#827]
Hi,

When in record mode, hitting the refresh button or F5 moves you from record mode back to the whole grid. I'm fairly sure this is a regression since I remember using that and staying on record mode.

**Comment by serge-rider** [comment]
Can't reproduce. Most likely your turned option "Switch to record/grid mode on single/multiple row(s)" on. It on `Preferences->Result Sets->Presentation` page.

**Comment by Azenet** [comment]
I feel like this is the behavior I'd want though, switch to record and grid automatically on load whether there is one or several rows.

Reproduction steps:
1. Load several rows in grid mode
2. Click on one
3. Press tab to switch in grid mode
4. Press F5

Expected: record reloads
Actual: switches back to grid mode

If we are talking about the same thing then I guess this would be a feature request instead of a bug report.

**Comment by serge-rider** [comment]
Well, if I understood correctly then it works as expected.
Results viewer switches to grid mode if query returns more than one row. There may be different number of rows on every refresh.
Maybe such mode switch shouldn't happen on explicit refresh. Is this what you mean?

**Comment by Azenet** [comment]
Yes, that is what I meant. It would be useful if I am expecting a certain row to refresh for example, and watching it on the record mode.

**Comment by Azenet** [comment]
Sorry about the delay on this but I think this is incomplete; right now it doesn't switch back to the grid mode, but it will switch to the first record of the ResultSet on refresh anyway (e.g. I am on record mode on row 30, pressing F5 will stay on record mode but it will show row 1, which kind of defeats the point). I can do another issue for it if you think it is separate.

**Comment by serge-rider** [comment]
Please create another issue.
