### ISSUE TITLE
Project refresh must refresh connections

### ISSUE THREAD

**Issue by beirtipol** [serge-rider/dbeaver#83]
I want to be able to store the c:\users\me\.dbeaver folder in source control so it can be shared among my team. However, refreshing the project in DBeaver does not refresh the contents from disk.

Version 3.5.5 Enterprise on Win7

**Comment by serge-rider** [comment]
What do you mean under "contents"?

**Comment by beirtipol** [comment]
I can see that there is an eclipse project created containing a .dbeaver-data-sources.xml. If I manually edit that file I can't see a way to refresh the connections within the application

**Comment by serge-rider** [comment]
Yes, this feature is not yet supported. You can refresh only project resources (scripts, bookmarks, etc).
