### ISSUE TITLE
Installation failed on Fedora 24

### ISSUE THREAD

**Issue by sasann** [serge-rider/dbeaver#831]
Tried installing dbeaver on my box, got this:
```
$ rpm -i dbeaver-ce-3.7.6-stable.x86_64.rpm 
error: Failed dependencies:
	jre >= 1.7 is needed by dbeaver-ce-0:3.7.6-stable.x86_64
```
But I thought I have Java installed.
```
java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by serge-rider** [comment]
Maybe your Java was installed manually (not with package manager)? If so then you have two options:
- Install OpenJDK using package manager (apt-get)
- Install DBeaver manually (download zip archive).

**Comment by sasann** [comment]
Fedora documentation was a bit confusing. It needs `dnf install java` to actually install OpenJDK. DBeaver runs fine now.
Closing.
