### ISSUE TITLE
Mysql export without local client

### ISSUE THREAD

**Issue by awikatchikaen** [serge-rider/dbeaver#834]
Hi,

In my enterprise, i can't install mysql workbench so i can't use the export function. I would like to backup some databases before making upgrades. generating sql export is so difficult ? how does the others softwares ?

Thank you

**Comment by serge-rider** [comment]
Yes, generating sql export in MySQL format is very difficult, it has a lot of nuances.
As far as I know all tools which can make MySQL database export use native MySQL client for that.

You don't need MySQL Workbench. You can try to install just MySQL Utilities. If MSI installations are no allowed in your company then you can try to download zip archive MySQL server - all utilities are there.

As a workaround you can try to use DBeaver data export wizard for individual tables. But it won't export metadata.
