### ISSUE TITLE
IBM DB2 DDL generation problem...

### ISSUE THREAD

**Issue by undertherainITA** [serge-rider/dbeaver#836]
Hi.
I have a problem with IBM DB2 DDL generation.
I would like to know the exact grant needed to run the DDL generation.
I have 2 IBM DB2 databases v. 10.5.

DB n.1) Rule DBADM - DDL Generation OK
DB n.2) Rule PUBLIC (with grant of connect, createtab, implicit_schema, bindadd and load). ERROR:

/* ERROR WHILE READING SOURCE:

Error SQL [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: <USER>,CREATE TABLE,SYSTOOL".. SQLCODE=-443, SQLSTATE=38553, DRIVER=4.21.29
*/

What are the grants that I must have to have no errors?
Thanks!
Ciao... ;)

**Comment by titou10titou10** [comment]
Hi,
Internally DBeaver user the `db2look` command, so you need the same right as this command. Check in the [db2look documentation here](http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0002051.html)
Also, the so called `explain tables` are required as for the `explain` sql statement:  [doc here](http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000952.html)
If they do not exist, DBeaver will try to create or use them. In your case, given the error message, it seems you do not have the right to do this: [More explanation here](http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.admin.perf.doc/doc/c0005137.html)
Maybe you should try to execute an `explain`statement and see how it goes
Hope this helps
Denis
