### ISSUE TITLE
Driver JAR location is obscure

### ISSUE THREAD

**Issue by tobia** [serge-rider/dbeaver#838]
As a new user, trying to configure a commercial DB, I got the following message in the driver dialog:

> Oracle driver files missing.
> 
> According to vendor policy this driver isn't publicly available and you have to download it manually from vendor's web site.
>
> After successful driver download you will need to add JAR files in DBeaver libraries list.

This is all well and good, except it doesn't say at all where to put the JAR file, or where to find this "libraries list"!

I managed to get it to work by creating `~/.dbeaver/jdbc/`, putting the JAR there, then Cancel on the download dialog, Next on the connection wizard, Edit Driver Settings, then Add File to select the JAR, Find class, select Driver class, and then OK. But not without several other attempts on different dialogs, including the Download settings, which then I had to revert, or the Add Folder button, which didn't work (it would add the folder to the list, but fail to find the driver class.)

I think it would be worthwhile to create an empty directory in an obvious place such as `~/.dbeaver/jdbc/` and have the connection wizard tell users to put their JARs there and auto-detect them, at least for the major DBs.

At the very least, the dialog with the message quoted above should have a button to open the Driver settings, to add the JAR, instead of a link to the Download settings, which was quite misleading in my case. It made me think I had to put my JARs in the place shown in Drivers location: Local folder (`/home/tobia/.dbeaver/.metadata/.plugins/org.jkiss.dbeaver.core`) which didn't really work as you may guess.

**Comment by serge-rider** [comment]
Well, maybe I need to improve UI to make it more obvious.
You don't need to create new driver, find class, mess with files in DBeaver workspace or anything like that. 

After download dialog appears you need to:
1. Click on "Open Download Page"
2. Download driver files from opened web page (you can actually get driver files from any other place, e.g. copy from college computer)
3. Return to DBeaver and click on "Edit Driver" button
4. Click "Add file" and add all download jars
5. Click "Ok"

That's it - now you may connect.

**Comment by shiwaforce-admin** [comment]
The solution is not good for machines that are air-gapped. Please provide a correct documentation for users who do not have access to the internet from the very same machine where DBeaver installed
