### ISSUE TITLE
Add Preference to AutoComplete in Lowercase

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#839]
I'm unable to find a preference in Dbeaver that would set auto-completion to be performed in lowercase instead of uppercase.

The closest thing I could find is this:
![](http://neartalk.com/ss/2016-10-12_001_892x722.png)

However, it doesn't control the case of auto-completed table-field-names.

As is, dbeaver's auto-completion is very useful for reminding me of the names of fields in a table. However, because I want them to be in lowercase, I still find myself typing out the entire field-name just for the purpose of preventing it from being in uppercase. I know that's silly, but preferences sometimes are.

**Comment by serge-rider** [comment]
Formatting case doesn't affect identifiers auto-completion.

You can configure auto-completion case on SQL Editor pref page:
![completion_insert_case](https://cloud.githubusercontent.com/assets/6398845/19412134/aca5960c-9317-11e6-91ed-69db227c9380.png)

BTW You can post inline images on GitHub by using drag-n-drop in comment text.

**Comment by Lonniebiz** [comment]
Perfect. Thank you.

I overlooked that previously because that entire form was [disabled](http://neartalk.com/ss/2016-10-16_002_888x711.png). I've [enabled](http://neartalk.com/ss/2016-10-16_003_880x710.png) it now. Many thanks.

**Comment by bryan831** [comment]
Honestly i am wondering why it is lowercase by default? Is that really a preference of most users?

**Comment by Lonniebiz** [comment]
I'm not sure, but I do all my sql in lowercase (except 'strings' of course).

**Comment by Hronom** [comment]
@bryan831 for me lowercase was confusing, since I saw almost everywhere uppercase...

**Comment by Lonniebiz** [comment]
Dbeaver already color-codes the keywords for you. I've been writing SQL for almost 20 years. I too capitalized those keywords for the first few years. At some point, I realized that those keywords are not case sensitive, and at that time it took extra effort to capitalize them, so I stopped doing it. At this point I prefer everything to be lowercase except for 'CertainStrings'. I don't care what the default is as long as I have a way to turn auto-capitalization off.

**Comment by kannes** [comment]
For anyone searching this in current versions, it is under "SQL Formatting" inside the "SQL Editor" tree nowadays.

@Lonniebiz If your project team agreed on using UPPERCASE (like most people anywhere) then it was a major PITA to not be able to copy and paste scripts you wrote in DBeaver to elsewhere. An editor should not be this opinionated.

**Comment by Lonniebiz** [comment]
@kannes : Uppercase is an unnecessary formality. I remember when people did HTML tags in uppercase. Lowercase will win out long-run. If you worked for me, I'd make you do it in lowercase just to make you sad. My management philosophy is: "if an employee is happy, you're doing something wrong". With all this said, know that I'm only joking :)

**Comment by ivaylo-infostrux** [comment]
> Uppercase is an unnecessary formality

I would have to strongly disagree!  Uppercasing keywords is key for SQL code readability.  Readability results in maintainability which reduces development cost.  There are reasons why there are SQL standards and the majority of them recommend keywords to be in uppercase.  In any forward-thinking organization, these rules are automatically enforced by linters run by the CI workflow, too.

Going against standards makes sense only if you are proposing a sensible new standard.  In the absence of a meaningful alternative proposal, you are only rebelling against standardization while at the same time you enforce your own custom standard.  Seems incongruent.

> it took extra effort to capitalize

It seems this is the only argument you have in favour of your standard.  However, code is read many more times than it is written, so the effort it takes to capitalize keywords is trivial compared to the effort it takes to read poorly formatted code.  As for the actual effort it takes to format properly, you can simply have DBeaver auto-format SQL for you - all it takes is pressing Shift-Ctrl-F.

> My management philosophy is: "if an employee is happy, you're doing something wrong"

Sad joke.

**Comment by Lonniebiz** [comment]
@ivaylo-infostrux : Modern SQL editors colorize keywords automatically. Automatically colorized keywords are enough distinction for readability sake. In cases where this is not the case, I agree with you that it does enhance readability. Yet, personally, I like everything to be in lowercase except for when uppercase is required to achieve a particular result set. CaPiTaLiZaTiOn rEqUiReS UnNeCeSsArY EfFoRt.

**Comment by ivaylo-infostrux** [comment]
Thanks for the response, @Lonniebiz, but standards are the exact opposite of personal preferences.  The needs of the team and the organization as a whole quite often outweigh the individual preference.  It's the price we all pay for efficient collaboration.

**Comment by Lonniebiz** [comment]
@ivaylo-infostrux : Thankfully, dBeaver can accommodate all users' preferences (even those who are luddites).

**Comment by ivaylo-infostrux** [comment]
The fact that you can use a tool a certain way is not, in itself, an endorsement of your mode of use.

BTW, Luddites would be breaking computers, not using them.

**Comment by kannes** [comment]
@Lonniebiz Your low effort trolling is really unnecessary. I am glad it is easy to unsubscribe from an issue, maybe you should do the same.

**Comment by bryan831** [comment]
@Lonniebiz your responses are extremely childish and surprising since you've mentioned "writing SQL for 20 years". I think you need to grow up figuratively speaking. Maybe you find it hard to capitalize keywords because your mechanics are bad. That doesn't mean you have to insist your preference is better

**Comment by dxp227** [comment]
For those searching for this setting in 2023:

Preferences > Editors > SQL Editor > Code Completion > **Insert Case**

**Comment by xdpiqbx** [comment]
In Dbeaver you can choose only lower or UPPER like in first two messages.
But i usually use
Ctrl + Shift + Y - to lower
Ctrl + Shift + X - to upper

<img width="800" height="973" alt="Image" src="https://github.com/user-attachments/assets/22b28533-9082-4f36-90ef-a18100bc6773" />
