### ISSUE TITLE
Select objects to export in Database export

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#84]
There is no way how to export only selected objects (tables, views, procedures, ...) at once.

For example: If you need export only 8 tables from database which contains 100 tables, you must export them separately one by one.

Can you add new step in Database export wizard, where will possible to select objects?

**Comment by serge-rider** [comment]
You can export any number of tables/views.
Just select them in database navigator and click on "Export Data" in the context menu.

**Comment by MatyCZ** [comment]
Sorry, I dont try select more items in database navigator. But your action export only data and create one file per database object. It is something else.

There is no way how to export selected objects to one file with complete syntax (DROP, CREATE, INSERT statement) how Database export do.

**Comment by serge-rider** [comment]
Agreed. Existing database dump UI is too simple.
It makes sense to add support of multiple databases, dump only selected tables and support of other mysqldump options.
