### ISSUE TITLE
Change the tabs

### ISSUE THREAD

**Issue by Vinibisineli** [serge-rider/dbeaver#841]
Hi there,

today on my company we use the SQLYog, but on Linux using the Wine. We trying to change to DBeaver but we need a new feature to organize our lives. I attach a photo to explain. I need a tab for organize the connections with the server. If you see the tab with color are the severs and the databases and when a select one, than the querys tab change to tha server.

Please contact me if you have some question.

![img_20161013_091923](https://cloud.githubusercontent.com/assets/6979641/19348924/c2e4824a-9126-11e6-9f0b-a6c4331aaaa5.jpg)

**Comment by serge-rider** [comment]
In DBeaver you can change editor database using main toolbar (there are two combo boxes - to select active database and active schema).
Is this tabs toolbar the same but with different layout? 
And what if number of connection more than 10 and these tabs doesn't fit the screen?

**Comment by Vinibisineli** [comment]
Hello mr Serge, i know i can change databases and schemes using the combo
boxes. But what i need is that when i alternate between databases/schemes
my query editor tabs also changes.
An example:
In database 1, i have 3 sets os query editor tabs, and in database 2 i have
5 different query editor tabs. When i switch between those databases (using
the combo boxes) , i'd like to only be able to see the query tabs that are
related to its database.


Database 1:
  Schema23:
    *QueryEditor1
    *QueryEditor2
  Schema42:
    *QueryEditor8
    *QueryEditor9
Database 2:
  Schema18:
    *QueryEditor3
    *QueryEditor4
    *QueryEditor5
    *QueryEditor6
    *QueryEditor7

2016-10-15 11:25 GMT-03:00 Serge Rider <notifications@github.com>:

**Comment by adrianog** [comment]
+1

**Comment by serge-rider** [comment]
I don;t think that this is possible in current DBeaver UI model.
There should be another way to simplify SQL editors management.
