### ISSUE TITLE
Request: Unlimited Strength Security JRE

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#843]
Hey @serge-rider not sure if this is already the case or not but can you include the unlimited strength security policy in dbeaver for the included windows JRE. 

http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

I'm running into an issue and my understanding is that because of our use of aes-256 java chokes as the default security policy doesn't include support for that.

**Comment by serge-rider** [comment]
JRE included in installer is already configured with unlimited security strength.
You can check `C:\Program Files\DBeaver\jre\lib\security\local_policy.jar` file, it contains `default_local.policy` file with the following contents: 
```
// Country-specific policy file for countries with no limits on crypto strength.
grant {
    // There is no restriction to any algorithms.
    permission javax.crypto.CryptoAllPermission; 
};
```
