### ISSUE TITLE
Feature Request: Shortcut to open a table

### ISSUE THREAD

**Issue by Treppenhouse** [serge-rider/dbeaver#844]
Analogous to Eclipse it would be great to have a short cut like:
**Ctrl+Shift+T**
where a dialog opens that lets you enter a name of a table and select the one that you want to open.

It could be similar to the Ctrl+Shift+R dialog or even integrated in it (That it lets you search for tables in this dialog as well)

In case of tables with the same name in different schemas or connections both should be shown just as in eclipse when you want to open a type but have different version of the same library in your workspace.

Thanks! And continue the great work!

**Comment by serge-rider** [comment]
It is already there: `Ctrl+Shift+D`. 
And it searches not just tables.

**Comment by Treppenhouse** [comment]
Ah great! I even opened the Preferences -> Keys section and entered "Open" in the search bar but I guess I just didn't know what "Database Meta Object" means. Must have overlooked it! (But maybe you could add some examples of what these meta objects are in the description field of the shortcut :P)

Thanks for the help!
