### ISSUE TITLE
Incorrect display of Cassandra time data type

### ISSUE THREAD

**Issue by WeissGotsman** [serge-rider/dbeaver#848]
Config:
DBeaver EE 3.7.5
Cassandra 3.9.0 (official release)
Windows 7 x64

Issue:
SELECT operation does not return (or display) the time data type column correctly, instead it displays something like "3054-10-09 00:53:20"

Datastatx DevCenter shows it correctly as "09:30:32.000000000"

**Comment by serge-rider** [comment]
What is exact column data type?
Can you post a DDL?

**Comment by WeissGotsman** [comment]
1. Create
CREATE TABLE IF NOT exists tidata.test1 (
idx int,
tm time,
PRIMARY KEY (idx));

2. Insert
INSERT INTO tidata.test1 (idx, tm) VALUES (7,'09:30:32');

3. Select
SELECT * FROM tidata.test1;

4. Result
![dbeaver](https://cloud.githubusercontent.com/assets/22855561/19411551/6dc8acf2-9336-11e6-9b05-06b519e246aa.png)

**Comment by serge-rider** [comment]
Yes, it is a bug, DBeaver incorrectly handles TIME values (as TIMESTAMP).
Will be fixed in the next version, thanks for report.
