### ISSUE TITLE
Check for update is broken

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#851]
I'm using DBeaver 3.7.6 under Linux and when I use the check for update function it tells me that the new version is N/A. Detecting my current version works but it doesn't detect the latest version so it tells me there is no update available.

**Comment by serge-rider** [comment]
But 3.7.6 is the most recent version at the moment. There are no newer versions - that's why it says NA.

**Comment by GiantCrocodile** [comment]
Well this is quite confusing then! I expected it to report 3.7.6 as latest and currently installed then so it matches. N/A sounds like it wasn't able to ask the server for version information.

**Comment by serge-rider** [comment]
Hmm, never thought that it is confusing. "There is no new version" sounds quite unambiguous for me.
I can change N/A on the current version number, maybe it'll be more clear.

**Comment by stevieJ** [comment]
Same issue Windows 10 DBeaver Enterprise  7.1.0.202006211226 new install
