### ISSUE TITLE
Create new constraint produces duplicate names

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#852]
When I try to add multiple constraints like unique keys one by one they are all called the same so I can't save them. It should add some index to name so it doesn't create duplicate names. Also unique keys are given names like primary keys which is confusing. Maybe UQ or UNIQUE should be used instead of PK or PRIMARY.

**Comment by serge-rider** [comment]
You can change constraint name in the constraint list (just click on the Name column).
But I agree, DBeaver should generate unique constraint names. And probably it has to have constraint name field in create dialog.
