### ISSUE TITLE
Trigger is missing in Table > Properties > Triggers view if it is created with SQL query

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#853]
1. Create a trigger with a SQL query
2. Go to table > Properties > Triggers and press refresh
3. No trigger is shown

If you do a refresh on triggers in Database navigator it will also refresh the Table > Properties > Triggers view and then it does show the trigger you've created in step 1.

**Comment by serge-rider** [comment]
What database?

**Comment by GiantCrocodile** [comment]
@serge-rider I'm using MariaDB.

**Comment by serge-rider** [comment]
Thanks for report
