### ISSUE TITLE
Where to put the MySQL connector driver in DBeaver installation without changing classpath?

### ISSUE THREAD

**Issue by bsto** [serge-rider/dbeaver#854]
I want to use DBeaver to connect to MySQL.
Therefore I need the corresponding MySQL driver "mysql-connector-java-5.1.40-bin.jar"

Now assume I don't want to use the guided installation but install this driver manually and WITHOUT having to change the CLASSPATH.

Where (into which DBeaver folder) do I have to copy the driver *.jar to get DBeaver working?

Peter

**Comment by serge-rider** [comment]
You can put driver jar anywhere you want.
Then edit driver settings in DBeaver.
Main menu->Database->Driver Manager->Find MySQL driver->Add File.

**Comment by MeaningOfLights** [comment]
Alternatively you can edit the Drivers.xml file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core
