### ISSUE TITLE
How to move settings folder?

### ISSUE THREAD

**Issue by bsto** [serge-rider/dbeaver#855]
By default the settings folder for DBeaver under Windows 7 is:

C:\Users\\\<username>\\.dbeaver\\....

Is there a way (=an option inside DBeaver) to move this settings folder to another location e.g. to

D:\databases\mysql\dbeaver\mysettings\

or even better as a relative path:

..\mysettings\

Peter

**Comment by serge-rider** [comment]
You can start DBeaver with command line parameter `-data <path>`
Where &lt;path&gt; is location of "settings folder".
