### ISSUE TITLE
Alter procedure instead of Drop / Create procedure

### ISSUE THREAD

**Issue by webmaster-lg** [serge-rider/dbeaver#856]
I would like to do a feature request:

In my case in MySQL, 
When I edit a stored procedure and then I want to save it. If there is an error in the stored procedure the stored procedure doesn't want to be saved, but it has already been dropped. So if you close your editor, thinking you'll get back to the original savable version of your stored proc you loose it forever. Through a stored proc update you wouldn't have been able to update but at least you wouldn't have lost your stored procedure.

It happens to me. Trust me not fun ;)

**Comment by serge-rider** [comment]
Yep, that's not fun.
But MySQL doesn't support CREATE OR REPLACE PROCEDURE (as some other databases). The only way to change procedure body is drop + create.
And you can see it in SQL script so it shouldn't be a surprise.
I'd wish to make this operation less dangerous but honestly I don't know how.

**Comment by webmaster-lg** [comment]
What about ALTER PROCEDURE instead? Sorry to have stated UPDATE... It was a shoot from the hip ;)
http://dev.mysql.com/doc/refman/5.7/en/alter-procedure.html

I recall I saw this in our ugly old friend Mysql Workbench
![image](https://cloud.githubusercontent.com/assets/15920466/19451098/ff60c160-9479-11e6-85c2-047877c0a44b.png)

**Comment by webmaster-lg** [comment]
Just realized

> This statement can be used to change the characteristics of a stored procedure. More than one change may be specified in an ALTER PROCEDURE statement. However, you cannot change the parameters or body of a stored procedure using this statement; to make such changes, you must drop and re-create the procedure using DROP PROCEDURE and CREATE PROCEDURE.

>

**Comment by serge-rider** [comment]
ALTER PROCEDURE doesn't change body so it makes very little sense.
I can imagine something like this:
1. CREATE with unique generated name
2. If CREATE was successful then DROP original procedure
3. Rename procedure into original name (by mysql.proc table update).

Quite sophisticated way, I'd say.

**Comment by webmaster-lg** [comment]
I agree. 

It's like adding an extra safety net over MySQL since it's something not easily doable from a MySQL Console. The conventional approach is to Drop/Create which I think is a little bit riskier. I would like Oracle to apply their CREATE or REPLACE structure to MySQL . 

If it has an extra level of security on top of MySQL, my question is: why not doing it since other like Oracle have it? Will it generate more errors? Will it simplify the creation/update process? 

It's arguable. 

Note: It would also apply to function. 

Thanks for listening, love your soft!
