### ISSUE TITLE
Can not change datatype in Postgresql after restart application

### ISSUE THREAD

**Issue by zigic88** [serge-rider/dbeaver#858]
Hello Sir, sorry for my bad English.
I found a problem, when I'm restart dbeaver without disconnect database connection on dbeaver.
I can't change datatype for my table in my database.
But if I'm restart dbeaver after disconnect database connection on dbeaver. This problem was solved.

Is this bug in application ?

**Comment by serge-rider** [comment]
What do you mean under "change datatype"? Change type of column, edit values, or ..?

**Comment by zigic88** [comment]
Change type of column Sir.

**Comment by yujishe** [comment]
If you disconnect database,you can't change type of column ,edit values. When you restary dbeaver, dbeaver  default setting is auto-commit.
![image](https://cloud.githubusercontent.com/assets/22394316/19953196/4b1c0b44-a1a6-11e6-9822-121d2e2fea7f.png)

**Comment by zigic88** [comment]
My problem is can not change column type like below screenshot :
![2016-11-03-083145_1366x768_scrot](https://cloud.githubusercontent.com/assets/10239853/19953461/a705cd38-a1a0-11e6-8c72-cc614e8d5852.png)

so my scenario like this : 
1. Connect database
2. Open some table
3. Close Dbeaver without disconnect database
4. Open Dbeaver
5. Edit table from database
6. Then column "Data Type" not shown in Column Properties.

**Comment by yujishe** [comment]
oh , I change column type by sql . like  ALTER TABLE TABLE_NAME MODIFY COLUMN_NAME NEW_DATATYPE;  
Maybe you should commit and refresh the table when you edit the table.





yuji
 
From: zigic88
Date: 2016-11-03 09:40
To: serge-rider/dbeaver
CC: yujishe; Comment
Subject: Re: [serge-rider/dbeaver] Can not change datatype in Postgresql after restart application (#858)
My problem is can not change column type like below screenshot :
so my scenario like this : 
1. Connect database
2. Open some table
3. Close Dbeaver without disconnect database
4. Open Dbeaver
5. Edit table from database
6. Then column "Data Type" not shown in Column Properties.

**Comment by zigic88** [comment]
Already commit and refresh, but not change anything.
The solution only disconnect database,, close dbeaver and open dbeaver again. Like my first question.

**Comment by yujishe** [comment]
sorry ,I can't reproduce your problems.
I use dbeaver by default Settings.it's simple and dependable.maybe the problems is come from you database Server.

**Comment by zigic88** [comment]
Okay, no problem. I'm using Lubuntu LXDE. I think the problems come from my machine or my database server.
Thanks Yuji for your help.

**Comment by serge-rider** [comment]
Can't reproduce.
Please check Error Log view for any related errors. If there is nothing there - check debug log.
