### ISSUE TITLE
Editing pasted value doesn't work

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#86]
Paste a value in the cell. Then edit the cell and change the value. After editing, the cell reverts to the pasted value.

**Comment by serge-rider** [comment]
Can't reproduce. 
What cell do you mean? Cell in data editor (grid), properties editor?

**Comment by codebling** [comment]
Really? That's strange -- I didn't include more info because it was easy to reproduce. I'll try on another database. Meanwhile, I meant in the grid

**Comment by codebling** [comment]
I can only reproduce on certain databases at the moment, I'm not sure why -- maybe the column type? Try on 'text' and 'longtext' columns.

**Comment by serge-rider** [comment]
Still can't reproduce. Please provide more info: database, driver, exact column type and steps to reproduce.

**Comment by codebling** [comment]
Using DBeaver 3.5.5, have a MySQL connection using the default driver, whose database has a table with a column of type 'text' or 'longtext' with one or more rows. Open the table to the data view. Paste a value into a cell in a column of type 'text' or 'longtext'. (The cell will now be highlighted beige -- do not commit the data) Edit the cell. Delete some characters. Lose focus on the cell. 

We expect the new value (characters deleted) to show in the cell, but the value that was pasted is still shown (no characters deleted).

**Comment by serge-rider** [comment]
Got it, thanks for info.

**Comment by codebling** [comment]
Cool,  sorry for not including all of the relevant info right away -- thought this would be easier to reproduce
