### ISSUE TITLE
CREATE TRIGGER bugged?

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#861]
I tried to run this query with MariaDB engine:
```
DELIMITER $$
CREATE TRIGGER bla BEFORE INSERT ON buerger_status
FOR EACH ROW
BEGIN
    IF (new.id = 1) THEN
        SIGNAL SQLSTATE 'bla' SET MESSAGE_TEXT = 'message', MYSQL_ERRNO = 1000;
    END IF;
END;$$
DELIMITER ;
```

This doesn't work and reports:
```
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '$$' at line 1
```

Generally I have some troubles with TRIGGERS and DBeaver (sometimes unreproducable :(!).

**Comment by carlosjrcabello** [comment]
Hi there, 

I tested your trigger code in my mysql server here, I got errors about syntax of delimiter scope and bad state signal, to make it execute here, a did some adjustments:

https://gist.github.com/carlosjrcabello/9b30f4c61724d7c8d38e3ad8d794d182

I don't have enough knowledge about state signals on MySQL and even MariaDB, based on docs, I changed state value from 'bla' to '0100'. See docs:

https://dev.mysql.com/doc/refman/5.5/en/signal.html

**PS:** DBeaver has support for triggers creation using delimiters, but delimiters has certain rules as blank lines between each line, using `$$` to mark line-end, etc..all my triggers, functions, etc. I use the same syntax as at my gist...all runs OK through DBeaver.

**Comment by GiantCrocodile** [comment]
@carlosjrcabello I tried to run your modified query but I get a syntax error in line 6. After executing it again I get an syntax error at line 6. After pressing again and again nothing happens. I think the editor isn't properly executing the queries: sometimes it does, sometimes it doesn't.

**Comment by carlosjrcabello** [comment]
uhmmm,

@GiantCrocodile if you put your trigger in `bla.sql` file then import it on MariaDB's console using `\. bla.sql`, is it work?

I don't know exactly how DBeaver runs statements that contains `delimiters`, may it's necessary some code to support MariaDB if your script runs ok.

**Comment by carlosjrcabello** [comment]
I forgot to say, I always run scritps that contains delimiters trough `Alt + X` keys.

**Comment by GiantCrocodile** [comment]
It does work in console and also in DBeaver with `ALT + X`. It doesn't work with `CTRL + ENTER`, it causes weird behaviour.

**Comment by carlosjrcabello** [comment]
I don't know if dbeaver supports execute statements that contains delimiters through `Ctrl + Enter`. 
The only problem that I see in this case is if you have some script with dozen of queries but only want to execute just that trigger through `Ctrl + Enter`.

**Comment by GiantCrocodile** [comment]
I think this case is my fault by using `CTRL + ENTER` for statements which contains delimiters. But on the other hand there should be always the same error happening - not two or more different error messages/behaviours. This should be debugged to see if it is completely bugfree and user's fault.

**Comment by serge-rider** [comment]
Yep, you need ALT+X if you going to execute multiple queries.
Let's track scripts processing bugs in other issues.

**Comment by ChinYikMing** [comment]
> I forgot to say, I always run scritps that contains delimiters trough `Alt + X` keys.

This is very helpful! Thank you!
