### ISSUE TITLE
Autocomplete from multiple schemas?

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#862]
It seems that autocomplete only looks at the first entry in search_path (postgres).  If I `set search_path to first_schema, second_schema`, I can't get autocomplete to ever see anything from second_schema without using `second_schema.t...`.  Could dbeaver use the full search_path in that case? (Or is this already possible somehow?)

**Comment by serge-rider** [comment]
Agreed, DBeaver should use full PG search path for auto-completion. Now it uses just active schema.
