### ISSUE TITLE
Unable to download Hive Apache Driver Files

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#864]
When attempting to download the hive apache drive files I receive a timed out error.

<img width="930" alt="screen shot 2016-10-19 at 11 18 35 am" src="https://cloud.githubusercontent.com/assets/9246654/19531816/ef4a9b50-95ed-11e6-811c-a6a79d420aa7.png">

**Comment by serge-rider** [comment]
Hive driver (the one which is published as "Hive jdbc" in Maven) is enormously huge, some artifacts are located on 3rd party Maven repositories. Maybe you don't have access to them or maybe it was some temporary web site unavailability. At least I can download Hive driver with no problems.

You can also try to download Hive driver manually from their web site (it has much less size).

**Comment by r-richmond** [comment]
kk, thanks for the tips.
