### ISSUE TITLE
ARM support/Eclipse Neon is here

### ISSUE THREAD

**Issue by sudhirkshirsagar** [serge-rider/dbeaver#865]
We wanted to run DBeaver on a Raspberry Pi. Would you be compiling for that? Thanks.

**Comment by serge-rider** [comment]
Similar to #552.
Well, DBeaver will be migrated to Neon in November (hopefully). 
However I don't see any downloads or announcements about ARM support on official Eclipse web site. I can build DBeaver version for any supported platform but ARM isn't in the list.

How do you managed to run Eclipse Neon on ARM?
Maybe you have some special build.

**Comment by sudhirkshirsagar** [comment]
I think I was mistaken that Neon supports ARM natively.

**Comment by serge-rider** [comment]
Ok, let's wait a bit more. I believe that eventually ARM support will be there.
