### ISSUE TITLE
Saving a changed trigger in trigger view is not possible

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#869]
MariaDB:
1. Create a trigger
2. Open this trigger in its view and change it somehow
3. save it

DBeaver will generate a create trigger statement but not dropping the previously generated trigger. Also it does generate BEGIN and END block too which has been greated already by manual create statement so it is twice and trigger creation will fail also.

**Comment by carlosjrcabello** [comment]
I consider so awful use graphical interface to create views, triggers, functions, etc., there are a lot of situations to control each database. 

If you're good coding queries, I recommend to you do it by scripts in editor, you'll save a lot of time.

_(not ignoring the but on trigger/view creation)_

**Comment by serge-rider** [comment]
Problem with BEGIN/END was already solved as a part of another issue.
DROP TRIGGER statement will be added before CREATE (as MySQL doesn't support CREATE OR REPLACE) in the next version, thanks for noticing.

**Comment by GiantCrocodile** [comment]
@serge-rider I'm using 3.7.7 now and I noticed a small issue: If you a trigger like this:
```
	IF (SELECT id FROM buerger WHERE EXISTS(SELECT * FROM benutzer WHERE new.id = id) > 0) THEN
		SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'message', MYSQL_ERRNO = 1000;
	END IF;
```

Then it will add a second semicolon after your END IF because it seems like it doesn't recognize you have no BEGIN and END tags.

**Comment by GiantCrocodile** [comment]
Also I noticed that it is not possible to save a trigger if we have deleted it by an other script. To make it possible we should have a `DROP TRIGGER IF EXISTS <trigger name>;`

**Comment by serge-rider** [comment]
- Can't reproduce issue with BEGIN/END blocks. Please provide more info.
- You can disable keyword case conversion in SQL editor preferences.
- Agreed with DROP IF EXISTS.

**Comment by GiantCrocodile** [comment]
I changed keyworde case conversion again @serge-rider. I will keep an eye on this and see if this is gone now.

To reproduce BEGIN/END blocks issue:
1. Edit a trigger which has a BEGIN/END block already
2. remove BEGIN/END block
3. save

It will add a second ; now. I can reproduce it constantly with this trigger:
```
BEGIN
	IF ([...]) THEN
		# [...]
	END IF;
END
```

**Comment by serge-rider** [comment]
Second ";" you see in the script isn't actually added to trigger body, it is visible only in script preview.
I'll fix this, apparently this can be confusing.

**Comment by GiantCrocodile** [comment]
I see this second semicolon also happening if the db is exported. Maybe you can verify/fix this too? I don't know if this is related to each other.

**Comment by serge-rider** [comment]
DB export is performed by MySQL native tool, I don't think that I can/should fix it.
