### ISSUE TITLE
Sort Autocomplete for Template popup

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#87]
Thanks for implementing [autocomplete for templates](http://dbeaver.jkiss.org/forum/viewtopic.php?f=3&t=1935) its a great feature that I'm using daily.

1) request though can you alphabetically sort the popup? it currently appears to be showing in the order in which the templates were input which isn't consistent / or as useful as an alphabetical sort.

![image](https://cloud.githubusercontent.com/assets/9246654/11520154/90f78284-9855-11e5-8e94-f5e37fdfd1b8.png)

**Comment by serge-rider** [comment]
Sure, templates have to be ordered
