### ISSUE TITLE
Sybase jTDS driver error handling

### ISSUE THREAD

**Issue by jsteiner27519** [serge-rider/dbeaver#870]
Sometimes when running 'CREATE TABLE' statements for Sybase databases, I get this error message: 2762 ...'CREATE TABLE' command is not allowed within a multi-statement transaction ...

In other tools, like Squirrel and RapidSQL, this error is handled properly and does not cause tempdb to fill up and stops the execution of the script. However, using DBeaver, tempdb does fill up and causes database outages.

My question or issue is:
1) Is this something that I should try to correct in the SQL? If so, can the forum give me some advice on this?
2) Can the DBeaver tool be enhanced so as to not have tempdb fill up?

**Comment by serge-rider** [comment]
Maybe you need to switch to auto-commit mode?
This can be done in main toolbar or in main menu Database->Transaction mode.

**Comment by sakthp** [comment]
Thanks @serge-rider. Switching to auto-commit mode in Dbeaver worked for me.
