### ISSUE TITLE
Diagram View: Dotted line vs straight line?

### ISSUE THREAD

**Issue by dgellow** [serge-rider/dbeaver#871]
Hi,

In the diagram view what's the difference between straight (1) and dotted (2) lines to represent references?

<img width="308" alt="screen shot 2016-10-20 at 17 58 19" src="https://cloud.githubusercontent.com/assets/2451004/19567751/3e95e2d0-96ef-11e6-8971-18085324357d.png">

**Comment by serge-rider** [comment]
Straight line is identifying relationship (FK migrates into PK).
Dotted line is non-identifying relationship.

It is from some ERD standard (honestly I forgot which exactly).

**Comment by dgellow** [comment]
@serge-rider Thank you. I found [here](http://stackoverflow.com/a/762994/709884) a short explication on identifying vs non-identifying relationships

**Comment by laurianops** [comment]
Thanks @dgellow  I had the same problem.
