### ISSUE TITLE
When SOCKS proxy is specified, it should use SOCKS proxy for DNS resolution

### ISSUE THREAD

**Issue by testn** [serge-rider/dbeaver#872]
I'm not sure whether this is possible but when SOCKS proxy is specified, it should use SOCKS proxy for DNS resolution.

**Comment by GiantCrocodile** [comment]
I think you need to configure your SOCKS proxy in your OS to make sure DNS requests are done over your SOCKS proxy. Or you have to use some special proxy software to tunnel every request through your SOCKS proxy. I doubt that tunneling DNS requests over SOCKS is task of the specific application (here DBeaver) but of your OS.

**Comment by testn** [comment]
@GiantCrocodile I think it's because https://bugs.openjdk.java.net/browse/JDK-8028776
