### ISSUE TITLE
Trigger view is not refreshed correctly

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#873]
MariaDB:
1. Create a trigger
2. Open this trigger in a view
3. Change trigger with a script
4. look at the trigger

The trigger is still the same as like as it didn't change. I had to refresh trigger folder in Database Navigator and open and close the view multiple times to get it refreshing to show the current trigger query.

**Comment by serge-rider** [comment]
This is a known issue, already fixed.
