### ISSUE TITLE
Update from 3.7.3 to 3.7.6, users cannot change settings for number format grouping

### ISSUE THREAD

**Issue by hgrod** [serge-rider/dbeaver#874]
Good morning,

Our users have started updating from version 3.7.3 to 3.7.6 for MAC , and some are unable to change settings as previously able:

![image](https://cloud.githubusercontent.com/assets/22058455/19605776/6bd1afb4-977a-11e6-8598-3e48611678a2.png)

Preferences > Database > Result Sets > Data Formats > Type: Numbers > Use Grouping > Yes/No

It used to be a checkbox which switched to  a yes/no dropdown, but in the update it appears that that was replaced with a checkbox. The problem that occurs now is that a checkbox appears over the top of the checkbox that is there, and neither are click-able:
![image](https://cloud.githubusercontent.com/assets/22058455/19605835/cc69aeee-977a-11e6-8a62-e2b217e82b71.png)
![image](https://cloud.githubusercontent.com/assets/22058455/19605838/d52cc5f2-977a-11e6-9e6a-e92a96d8c4b0.png)
![image](https://cloud.githubusercontent.com/assets/22058455/19605842/db67b242-977a-11e6-8984-0731adaacd21.png)

Most of our integers within our database are IDs not actual "numbers", and we do not want commas in them... Is this already being addressed, or can this be fixed?

**Comment by serge-rider** [comment]
It is a bug in the recent version. Boolean editor works fine on Windows, a bit crappy on Linux and doesn't work on Mac.
Going to fix in the next version, thanks for report.

**Comment by hgrod** [comment]
Thanks! Looks great now
