### ISSUE TITLE
Table creation grid cell width is 0

### ISSUE THREAD

**Issue by tcak** [serge-rider/dbeaver#875]
I am on version 3.7.6 on Ubuntu 16.10 x64.

When I click on "Create new table", and open the "Columns" tab, width of all empty columns is 0px. Please see below in the screenshot.

![screenshot from 2016-10-22 17-44-37](https://cloud.githubusercontent.com/assets/10595665/19620169/b094dd82-987f-11e6-99d4-c5f2d7ef6461.png)

**Comment by serge-rider** [comment]
Can't reproduce (tried on Ubuntu 16). Could you provide a bit more details about your OS/WM?
I remember that someone already reported about very similar problem..

BTW 3.7.7 will have improved columns creation UI.

**Comment by tcak** [comment]
Ubuntu 16.10. Unity Desktop. Unity 7 comes with that AFAIK.

I wasn't having this issue until a while ago. In recent times it has started. Can be due to Ubuntu 16.10 upgrade, but I am not sure. So I wanted to report it here.
