### ISSUE TITLE
Editing/Adding Row within grid

### ISSUE THREAD

**Issue by MrSourabh** [serge-rider/dbeaver#878]
Hello Guys, I would like make a feature request, it would be really helpful if user can add new row by directly editing the new blank line at the bottom of data set (or similar way) rather than clicking +  everytime. I'm expecting the result similar to feature used in MS SQL Server Studio.
Thanks

**Comment by serge-rider** [comment]
Not sure about that. For my personal DBeaver is more convenient.
1. You don't need to click - just use keyboard (`ctrl+insert` or `ctrl+alt+insert`)
2. Current way allows to insert multiple rows at once.

**Comment by cupliz** [comment]
it would be good if new data is defined by default value in column properties rathern than cloning from previous data. thanks
