### ISSUE TITLE
Ordering of results does not work on multi-page result sets

### ISSUE THREAD

**Issue by evll** [serge-rider/dbeaver#880]
After upgrading to 3.7.7 I can no longer order results by clicking on arrows in column headers. I click and nothing happens.

![selection_067](https://cloud.githubusercontent.com/assets/9748640/19635677/b5f31890-99cc-11e6-8b22-55c71a89f321.png)

**Comment by evll** [comment]
Correction - ordering does not work only when there are more rows than are loaded initially. Maybe this issue existed prior to 3.7.7 as well, not sure.

**Comment by evll** [comment]
Order result set confirmation is set to "Always"

**Comment by serge-rider** [comment]
This is a bug in one of recent versions. Thanks for report.
Actually ordering happens but it is not visualized in column header.

Workaround: to click in descending order use ALT+click. Also you can use filter dialog.
