### ISSUE TITLE
Oracle NLS parameters configuration

### ISSUE THREAD

**Issue by darkangel60** [serge-rider/dbeaver#881]
I'm using Dbeaver basically to work on Oracle databases, and I'm looking for a way to configure the session NLS parameters when I connect to them.

Is there a way to set the NLS parameters by default? In Dbeaver I was able to change the way the dates are shown by Dbeaver, but it doesn't change the NLS settings, and I have to execute an "ALTER SESSION SET NLS_DATE_FORMAT" each time I create a new connection.

```
SELECT sysdate FROM DUAL;

SYSDATE             |
--------------------|
24-10-2016 11:07:42 |

CREATE TABLE test (date_column date);
INSERT INTO test (date_column) VALUES ('24-10-2016 11:04:12');

-> Get error "Not a valid month"

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY HH24.MI.SS';
INSERT INTO test (date_column) VALUES ('24-10-2016 11:04:12');

-> Row inserted
```

**Comment by serge-rider** [comment]
I'll add date format parameters in Oracle connection properties.
As a workaround you can use Bootstrap queries configuration.

**Comment by sschneider-ihre-pvs** [comment]
can we have that for following NLS parameters too?
```sql
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD-HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ". ";
ALTER SESSION SET NLS_COMP=LINGUISTIC;
ALTER SESSION SET NLS_SORT=BINARY_CI;
```
