### ISSUE TITLE
SQL formatter does not align line after a "single line comment"

### ISSUE THREAD

**Issue by kiravi** [serge-rider/dbeaver#883]
E.g. see txt3 below:

SELECT
    'abc' AS txt1,
    'bcd' AS txt2,
    -- comment to test
 'efg' AS txt3,
    'hij' AS txt4
FROM
    dual;

**Comment by kiravi** [comment]
Any input?

**Comment by serge-rider** [comment]
Thanks for report

**Comment by kiravi** [comment]
Formats with 1 extra space as below
SELECT
  'abc' AS txt1,
  'bcd' AS txt2,
  -- comment to test
 'efg' AS txt3,
  'hij' AS txt4
FROM
  dual;
