### ISSUE TITLE
Filter is cleared when refreshing grid view

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#884]
Hi,

Since updating to 3.7.7, doing F5 or clicking the refresh button on the grid view will refresh once but clear the filter at the same time, whether it's the place to enter `WHERE` conditions above the grid view or using the `Order/Filter` dialog. Doing F5 again or refreshing again will show the unfiltered view.

**Comment by serge-rider** [comment]
This seems to be a result of the same problem as in #880.
Already fixed. Thanks for report anyway.
