### ISSUE TITLE
Autocomplete Template Command Name is verbose

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#89]
When changing the hotkey for autocomplete templates this appears.

![image](https://cloud.githubusercontent.com/assets/9246654/11548793/e50efc20-9914-11e5-8f79-6ecb97a8b2ca.png)

**Comment by serge-rider** [comment]
This issue was fixed in 3.5.4 or so. Unfortunately Eclipse caches localization resources and even if you have fixed version you'll still see that trash. 
Workaround: delete workspace.xmi file in .dbeaver/.metadata.
