### ISSUE TITLE
DBeaver does not see installed Java JRE MacOS 10.12.1

### ISSUE THREAD

**Issue by XiozTzu** [serge-rider/dbeaver#891]
Used Brew to install current DBeaver.  All went well, it put the app in the Applications folder.  When you double click on DBeaver a window shows saying "To open 'Dbeaver' you need to install the legacy Java 6 runtime", problem is I already installed it (https://support.apple.com/kb/DL1572?locale=en_US) and it still is giving this message.  I version I have installed is Java build 1.8.0_111-b14.

**Comment by serge-rider** [comment]
It a known MacOS issue. It seems that Mac installs JRE only in web browser (and this message about legacy JRE is a nonsense).

You need to install JDK (1.7 or 1.8).

**Comment by XiozTzu** [comment]
As I said in my original post, I have Java 1.8 installed.  Now what?

**Comment by serge-rider** [comment]
You need JDK, not JRE

**Comment by GeBeater** [comment]
I adjusted the "/Applications/DBeaver.app/Contents/Info.plist" to fix this issue. There is a section available to specific a java installation. I used "/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java".

**Comment by ajeesh2705** [comment]
I used Mac OS X (pkg installer + JRE) option, its also mentioned in Notes session of https://dbeaver.io/download/

'It is recommended to use JRE shipped with DBeaver. It won’t be breaking any existing JRE installation, nothing will be copied in system folders, registry or environment variables. This JRE will be accessible only for DBeaver.'
