### ISSUE TITLE
Active database/schema selection combo doesn't work

### ISSUE THREAD

**Issue by nikodc** [serge-rider/dbeaver#893]
The active database/schema selection combo doesn't work. You click on it and nothing happens, it seems to be stuck. Using dbeaver 3.7.2 I was able make it work by dragging the toolbar where it is present to another location in the GUI and then dragging it back. With 3.7.7 that trick simply hangs the whole UI and the only solution is to kill the application.

Dbeaver: 3.7.7
OS: Ubuntu 16.04
JRE: 1.8.0_91

**Comment by serge-rider** [comment]
Can't reproduce (tested on Ubuntu 16.04).
Maybe some workbench config was broken after major version update.
Try to reset workbench (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace) and to reset perspective (in main menu Window).

**Comment by nikodc** [comment]
Thanks for your quick answer! 

Deleting workbench.xmi worked, but sadly just the first time. As soon as I close the editor and open another one (or the same) the whole toolbar gets locked. Can I do anything else to figure out what's going on?

FYI, this problem happens since the first time I did a clean install of 3.7.2. I won't say this issue is related to the upgrade. The reason I posted this issue is because the workaround I mentioned hangs the GUI.

**Comment by nikodc** [comment]
BTW, deleting %HOMEPATH%\.dbeaver\.metadata\ produces the same result. I deleted the folder, created new connections and had the same problem working with an editor.

**Comment by serge-rider** [comment]
Hmm. Still can't reproduce.
Could you post a screenshot of a "locked" toolbar?

Note: just in case - database selector combo is enabled only for SQL editor. In all other editors it is read-only.

**Comment by nikodc** [comment]
I'm opening SQL files (.sql) and editing/running queries. So I'm using the SQL editor. The same one that works ok the first time. Is there other possibility?

Regarding the combo, it look just as it wasn't disabled. But nothing happens when you click it or any other control within the toolbar:

![selection_001](https://cloud.githubusercontent.com/assets/7115723/19743259/fb4f7ad6-9b9e-11e6-91c6-7a8a8db2eb36.png)

**Comment by nikodc** [comment]
BTW, that behavior happens working on my PC as well as on my laptop. Both have the same configuration:

Dbeaver: 3.7.7
OS: Ubuntu 16.04
JRE: 1.8.0_91

**Comment by serge-rider** [comment]
Please check 3.7.8. Although I still can't reproduce that - there were a few fixes in combo selector.

**Comment by nikodc** [comment]
Hi again. Thank you for the feedback. Sadly, the same thing happened again. Is there any kind of debug info I could take from the app? How can I help to figure out what's going on?

**Comment by serge-rider** [comment]
I think this is a bug in Eclipse CSS rendering in GTK.

You could try to change schema (Preferences->General->Appearance), maybe it'll help.
Also we going to migrate to Eclipse 4.6 in the next version - maybe this bug was fixed there.

**Comment by nikodc** [comment]
Maybe. I'll wait for 4.6 then. BTW, my theme under Preferences->General->Appearance is Classic, not GTK.

**Comment by jvstein** [comment]
I was getting this problem with DBeaver 3.7.8 and 3.8.0. The whole dropdown was non-functional and wouldn't even work on the first attempt. Updating my GTK theme so it matched my Ubuntu version resolved the issue for me. For what it's worth, I was using an old 15.04 version of the Ambiance-Dark theme.

**Comment by jvstein** [comment]
The problem is intermittent, but definitely persists. Deleting these files from my ~/.dbeaver/ folder and restarting the application always resolves an unresponsive drop down, but I haven't tracked it down to a specific file, yet.

```
.metadata/.dbeaver-server.properties
.metadata/.lock
.metadata/.log
.metadata/.plugins/org.eclipse.core.resources/
.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.core.resources.prefs
.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.e4.ui.workbench.renderers.swt.prefs
.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs
.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.prefs
.metadata/.plugins/org.eclipse.e4.workbench/
.metadata/.plugins/org.eclipse.equinox.p2.ui/
.metadata/.plugins/org.eclipse.ltk.core.refactoring/
.metadata/.plugins/org.eclipse.ltk.ui.refactoring/
.metadata/.plugins/org.eclipse.ui.workbench/
.metadata/.plugins/org.jkiss.dbeaver.core/dialog_settings.xml
.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml
.metadata/.plugins/org.jkiss.dbeaver.core/drivers/
.metadata/.plugins/org.jkiss.dbeaver.core/maven/
.metadata/.plugins/org.jkiss.dbeaver.core/security/
.metadata/.plugins/org.jkiss.dbeaver.model/
.metadata/dbeaver-debug.log
.metadata/qmdb/
```

**Comment by serge-rider** [comment]
Please test how it works in DBeaver 4 EA (http://dbeaver.jkiss.org/files/ea/). It is based on Eclipse 4.6.

**Comment by nikodc** [comment]
Hi. I've tried  DBeaver 4 EA and now the combo box never gets locked. Unfortunately, it does something else. It gets compacted, as shown in the next image:

![selection_001](https://cloud.githubusercontent.com/assets/7115723/22789647/64abc978-eec2-11e6-81d3-110d810c4e8a.jpg)

The workaround I've mentioned previously, that one consisting on dragging the box to another place in the menu re-renders the combo with the appropriate size. Luckily, this time the combo remains enabled/unlocked. It's still annoying.

**Comment by serge-rider** [comment]
Crap. I thought I fixed that "compacting" thing.
Need more tests on linuxes..

Thanks for testing.

**Comment by serge-rider** [comment]
Please try it one more time (fresh EA was uploaded).
Tested on Ubuntu and RHEL.

**Comment by nikodc** [comment]
Hi again. Congratulations, now all seems to work ok! Thank you so much.

**Comment by serge-rider** [comment]
Great
