### ISSUE TITLE
Order/filter configurable presets

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#894]
Result Set Order/Filter settings should persist or one should be able to save the current version as a default preset

use case 1:
I always want all tables sorted by id DESC on all tables I open to see the newest rows first - even though I have not explicitly saved this behaviour through the 'Result Set Order/Filter settings' window, but rather in some general settings for that Database.

use case 2:
I always want some_random_nonstandard_column to be sorted DESC when I open table X. this will override the column(s) specified in use case 1.

**Comment by serge-rider** [comment]
New action will be added in results viewer toolbar:
![image](https://user-images.githubusercontent.com/6398845/29384715-c94b5ec0-82dd-11e7-86e2-09764234b751.png)

It saves current filters state (criteria and ordering). This state will be restored on next table open.

**Comment by allanlaal** [comment]
@serge-rider I found and used this feature today intuitively without remembering it was my feature request. You are truly a master of great UX!

[offtopic]
Could you recommend any good books/podcasts/learning resources, so I could become an UX god too? :)
[/offtopic]

**Comment by jeisoncp** [comment]
@serge-rider I tried with different SGBDs, databases, SOs, but the button always is disable for me.

**Comment by serge-rider** [comment]
This works only for table data editor (not for custom SQL queries)

**Comment by jeisoncp** [comment]
Ah... OK.

**Comment by serge-rider** [comment]
Maybe this is a subject for a separate feature request. Although it won't be a bit more complicated (because it is not so easy to identify custom SQL queries)
