### ISSUE TITLE
Connecting through JDBC - ODBC bridge

### ISSUE THREAD

**Issue by dipasi** [serge-rider/dbeaver#895]
Hi Gurus

I'm trying to connect to a MS Access database in dbeaver. First I tried connecting through UCanAccess, but it won't open the .mdb file because several reported errors with procedures and such.

I'm trying to connect through ODBC, but I'm missing something (probably a simple thing, but I can't figure out what).

Step1: I created the ODBC connection in the System DSN (in the ODBC Administrator), and name it as "Campaign".
Step2: I downloaded the JDBC-ODBC drivers in DBeaver and configure a connection which JDBC URL is jdbc:odbc:Campaign
Step3: I click on Test Connection and get a java.sql.SQLException: No data found error.

DBeaver version: 3.7.3
Connection parameters: by default

Thanks in advance!

**Comment by serge-rider** [comment]
1. Upgrade DBeaver to the recent version
2. Make sure that ODBC driver (which one exactly btw?) matches DBeaver/Java version. 
64-bit driver can be used only from 64-bit DBeaver, the same about 32-bit.

**Comment by dipasi** [comment]
Thanks for your quick answer.

Java version is 	1.7.0_67
ODBC is 32 bits, the same as DBeaver.

I'll test with the latest version and let you know if it works.

Thanks!

**Comment by serge-rider** [comment]
What exactly ODBC driver do you use?

**Comment by dipasi** [comment]
Well, I was using the "Microsoft Access Driver (*.mdb)" driver, as my Access DB was .mdb... but because of you asking, I tried with the "Microsoft Access Driver (*.mdb, *.accdb)" and know it works just fine.

Thanks!

**Comment by serge-rider** [comment]
Cool ;)
