### ISSUE TITLE
Request: add "Evaluate SQL Expression" feature

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#896]
This is something along the lines of Execute -> Select row count for a query

Here's how: Select some text and run "Evaluate SQL Expression", which would basically run something like "SELECT <sql_expression> (FROM DUAL, etc...)" and display the result in the result pane. This would eliminate some typing (like it is the case with count) and make it possible  to work with a database in a more "functional" way, which can sometimes work quite well with SQL, making it a bit more like Lisp :)

It might be relatively simple to implement, but could turn out to be quite useful.

It would be super awesome, if this worked for row and set returning functions as well.

**Comment by serge-rider** [comment]
I like this. And simple to implement.
See it in next version, maybe some other improvements will be needed.

**Comment by lacanoid** [comment]
Great!

And thank you very much on your hard work on this project! DBeaver is surely the most advanced open source database client by now. Together with Postgres, it makes for a truly awesome combination!

Best of luck,
Žiga
