### ISSUE TITLE
ADD selecting a new active table also scrolls the Database Navigator pane to that table

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#897]
this could be an optional feature or a shortcut key (like in Netbeans: ctrl+shift+1)

**Comment by serge-rider** [comment]
There is "Link with Editor" action (ctrl+shift+,). Scrolls navigator to the objects currently opened in editor.
Isn't it the same?

**Comment by allanlaal** [comment]
that is exactly what I was looking for :)

I'll try to research a bit more next time I post an issue, I feel stupid now.

**Comment by serge-rider** [comment]
That's ok. I don't remember all DBeaver features myself.
We need a better documentation, that's for sure.
