### ISSUE TITLE
FIX clicking on column sort button will reset the table view back to starting from first column

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#898]
how to reproduce:

1. find a table with lots of columns (MySQL?)
2. scroll horizontally right, so that the initial columns are now longer visible
3. click on a sort icon :arrow_double_up::arrow_double_down:  to sort the column

expected behaviour:
table resorts, view stays at the same position

actual behaviour
table resorts, but resets the table view back to start from the first column

**Comment by serge-rider** [comment]
Yep, it's a bug
