### ISSUE TITLE
Inconsistent behavior Next/Previous Tab/Subtab

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#90]
I've been using the commands highlighted below and noticed in consistent behavior. 

![image](https://cloud.githubusercontent.com/assets/9246654/11548881/ccb00a74-9915-11e5-9b8b-0c17ebf9f26b.png)

My current understanding of the sections (will use below):
![image](https://cloud.githubusercontent.com/assets/9246654/11548916/29298a8c-9916-11e5-8ccc-210237a98dc5.png)

- Use case 1: Next tab when focus in in tab section (Editor)
  - Expected: When pressing next tab it will continue until the end of the tab section and then cycle through to the beginning of the tab section
  - Observed: When pressing next tab it will go until the end of the tab section freeze for 1 press and then switch to the sub tab section at which point continued presses will switch sub tabs.
- Use case 2: Previous tab when focus is in Tab section (Editor)
  - Expected: When pressing previous tab it will continue until the beginning of the tab section and then cycle through to end of the tab section
  - Observed: When pressing previous tab it will continue until the beginning of the tab section and then do nothing more with continued presses.
- Use case 3: Next tab when focus is in subtab section (Results)
  - Expected: When pressing next tab it will cycle the tab section
  - Observed: when pressing next tab it will cycle the subtab section (note: this will cycle through when an end is reached unlike Use case 1&2)
- Use case 4: Previous tab when focus is in subtab section (Results)
  - Expected: when pressing previous tab it will cycle the tab section
  - Observed: when pressing previous tab it will cycle the subtab section (note: this will cycle through when an end is reached unlike Use case 1&2)
- Use case 5: Next Subtab when focus is in tab section (Editor)
  - Expected: when pressing next subtab it will cycle the subtab section
  - Observed: if the subtab focus is on anything besides results (i.e explain plan, execution log, output) it will cycle the tabs
- Use case 6: Previous Subtab when focus is in tab section (Editor)
  - Expected: when pressing previous subtab it will cycle the subtab section
  - Observed: pressing previous subtab always switches the tab section
- Use case 7: Next subtab when focus is in subtab section(Results)
  - Expected matches Observed (Complete with cycling through to the beginning)
- Use case 8: Previous subtab when focus is in subtab section (results)
  - Expected matches Observed (Complete with cycling through to the beginning)

Bonus: Using the command "Activate Editor" when in the sub tab should put the focus back in the tab section (Editor). Currently I'm not observing any thing.

**Comment by serge-rider** [comment]
Tab switching is controlled by Eclipse framework. I'm afraid this is not my area of expertise to change default framework behavior. 
But if you see that some standard command work differently than they work in Eclipse - then, most likely, it is a result of a bug. For now, in use cases you described, I see that DBeaver acts as a typical RCP application.

**Comment by r-richmond** [comment]
Hmm unfortunate but understandable.

Is it possible to request new commands next/previous sql_editor/result_pane (this would include explain plan/execution log & output) so that it functions as listed above and avoids the eclipse problem?

p.s. next/previous sql_editor is suggested as next/previous editor is already taken. This is somewhat useful however I would like to have the switch be instant (not have to see a dialog box) and I would like the order to be dictated by the order of the tabs not the order in which i last opened the editors.

**Comment by serge-rider** [comment]
Anyhow, I can't fix that. Tabs switching order is controlled by JFace/SWT.
