### ISSUE TITLE
Postgres. Create function bug

### ISSUE THREAD

**Issue by busyscout** [serge-rider/dbeaver#900]
Simple code for function creation for postgres gives me error "Internal jdbc driver error  java.lang.ArrayIndexOutOfBoundsException".
Example function body:
`CREATE OR REPLACE FUNCTION test()
  RETURNS timestamp without time zone AS
$BODY$
    BEGIN
        RETURN now() AT time ZONE 'utc';
    END;
$BODY$ LANGUAGE plpgsql;`
If you replace $BODY$ with $$ then it works:
`CREATE OR REPLACE FUNCTION test() RETURNS timestamp without time zone AS $$ BEGIN RETURN now() AT time ZONE 'utc'; END; $$ LANGUAGE plpgsql;`

Both work from pgAdmin, but in DBeaver works only the second one.

![dbeaver-bug](https://cloud.githubusercontent.com/assets/23096209/19762126/4e171682-9c41-11e6-9f4a-f5869aa9355b.png)
DBeaver version is 3.7.7, OS is Windows 7 64bit, postgres version is 9.6, DBeaver version is portable. No special drivers for postgres were installed, DBeaver was downloaded from site and launched from folder.

**Comment by serge-rider** [comment]
This seems to be a PostgreSQL driver issue. I can't fix this.
Anyhow, delimiting procedure creation with $$ is the correct way to define PG procedures. What this $BODY$ thing supposed to mean?

**Comment by busyscout** [comment]
My driver is set to postgresql-9.4.1211.jre7.jar (default). Do I need another one? How can I change it?
In Postgres you can use any marker for function definition ($$ is used in examples, but you can use any other string). The problem is when you open function definition from DBeaver (F4 -> Source) the marker is $function$, from pgAdmin it is $BODY$. So if you try to execute this sql you receive an error.
Also this error is given in some other correct scripts, this one is just an obvious example.

**Comment by serge-rider** [comment]
You can choose any driver version in driver editor dialog (click on Download/Update and choose another version). Or you can add jar files from externally downloaded driver.
Anyhow I don't think that this will help - DBeaver uses the most recent driver version by default.
You can submit a bug report to PostgreSQL jdbc driver dev team.

BTW you can use $BODY$ (or any other) delimiter - just remove ; character after END.
```sql
CREATE OR REPLACE FUNCTION test() RETURNS timestamp without time zone AS $BODY$ BEGIN RETURN now() AT time ZONE 'utc'; END $BODY$ LANGUAGE plpgsql;
```
works fine.
