### ISSUE TITLE
Teradata: View definition isn't showing

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#904]
Teradata View definitions stopped working.

You implemented this feature in #127. I'm not sure when it stopped working. Just seeing the message "--view definition is not available" I'm not seeing any errors related to it in the log.

Table definition is still working.

**Comment by serge-rider** [comment]
Anything in Error Log or in debug log?

**Comment by r-richmond** [comment]
I didn't see anything in the error logs.

**Comment by serge-rider** [comment]
Could you check Query Manager to see what actual queries DBeaver executes when you opening view sources? There should be something like "SHOW VIEW view_name" and number of fetched rows (you need to enable metadata queries visibility in preferences).

**Comment by r-richmond** [comment]
It doesn't appear to be running aything.

```
13:02:32	SQL / META	-- Load indexes [null, dlab_rrichmond, test_table]	0 ms	0	Success	Teradata	Metadata
13:02:27	SQL / META	-- Load imported keys [null, dlab_rrichmond, test_table]	0 ms	0	Success	Teradata	Metadata
13:02:24	SQL / META	-- Load primary keys [null, dlab_rrichmond, test_table]	0 ms	0	Success	Teradata	Metadata
13:02:23	SQL / META	-- Load columns [null, dlab_rrichmond, test_table, %]	13 ms	2	Success	Teradata	Metadata
13:02:06	SQL / META	-- Load columns [null, dlab_rrichmond, v_d3_d_season, %]	45 ms	5	Success	Teradata	Metadata -- Runs After I click Columns under Information
13:01:47	SQL / META	-- Load tables [null, dlab_rrichmond, %, null]	3 ms	25	Success	Teradata	Metadata -- Runs when i Browse to my schema
13:01:29	SQL / META	-- Load schemas	12 ms	475	Success	Teradata	Metadata
13:01:28	SQL / META	-- Load catalogs	1 ms	0	Success	Teradata	Metadata
13:01:28	SQL / META	-- Load type info	4 ms	40	Success	Teradata	Metadata
13:01:28	Connection	Connected to "Teradata"				Teradata	Metadata
13:01:27	Connection	Connected to "Teradata"				Teradata	Main
```

**Comment by serge-rider** [comment]
Umm.
Is table DDL you see was produced by Teradata server or by DBeaver (you can see server-side DDL with SHOW TABLE command)?
Can you see procedures source?

If no then it looks like Teradata extension wasn't used at all.
Are you still using the driver configuration shipped with DBeaver (driver class name is com.ncr.teradata.TeraDriver)?

**Comment by r-richmond** [comment]
I'm using an updated version of the jdbc drives and it appears the class name has changed to `com.teradata.jdbc.TeraDriver`

**Comment by serge-rider** [comment]
That was a problem (DBeaver use driver class name to find appropriate metadata extractor).

**Comment by r-richmond** [comment]
Can confirm that this was fixed, thanks for the quick fix and awesome tool.
