### ISSUE TITLE
dbeaver 32bit connecting to ODBC 32bits in a 64 bits machine

### ISSUE THREAD

**Issue by dipasi** [serge-rider/dbeaver#906]
Hello Serge

Yesterday I opened a similar case for my 32bits machine and you helped me setting up a connection to MS Access using the JDBC-ODBC Bridge driver. 

Today I'm trying to set up this 64-bits machine, where I have dbeaver 32bits and Java VM 32 bits. 

When I tried to create an ODBC connection to MS Access in my Windows ODBC Administrator, I could only create a MS Access ODBC driver in the 32bits version (C:\Windows\SysWOW64\odbcad32.exe). If I tried to create it in the 64bit version, it won't find the driver.

Unfortunately, when I try to connect to that ODBC driver in DBeaver through the bridge, it does not find it. I presume is because it's looking for a connection in the 64bits ODBC Administrator C:\Windows\System32\odbcad32.exe)

How should this work?

I'm using Dbeaver 3.7.7 32 bits version. I tried the 64-bits version but it won't open as it reports this error with the Java VM being 32bits: "No Java virtual machine was found"
ODBC connection is MS Access (*.mdb, *.accdb)

**Comment by serge-rider** [comment]
I'm not sure I'm the right person to ask about different ODBC drivers issues. That's a whole bunch of issues, most of them already covered on stackoverflow.
For instance: http://stackoverflow.com/questions/10289655/how-to-connect-to-a-32-bit-access-database-from-64-bit-jvm

**Comment by dipasi** [comment]
Thanks for your help! I'll look into that.
