### ISSUE TITLE
Parser ignores `END;` part of a trigger creation statement

### ISSUE THREAD

**Issue by tomsoflow** [serge-rider/dbeaver#907]
DBeaver seems to have issues parsing a trigger statement and cuts off parts of it.

For example the trigger:

    CREATE OR REPLACE TRIGGER TEST_TRIGGER
    BEFORE INSERT ON TEST
    FOR EACH ROW
      BEGIN
      IF :NEW.ID IS NULL
      THEN
        SELECT TEST_SEQ.nextval
        INTO :NEW.ID
        FROM DUAL;
      END IF;
      END;
    /

When executed in a SQL Editor window all seems to be fine (query runs without reported issues), but when checking the trigger, then it is:

    CREATE OR REPLACE TRIGGER TEST_TRIGGER
    BEFORE INSERT ON TEST
    FOR EACH ROW
      BEGIN
      IF :NEW.ID IS NULL
      THEN
        SELECT TEST_SEQ.nextval
        INTO :NEW.ID
        FROM DUAL;
      END IF;

So, it is missing the final `END;`. The trigger naturally can't be compiled.

But if one uses the statement style

    CREATE OR REPLACE TRIGGER "TEST_TRIGGER"
      before INSERT ON "TEST"
        FOR EACH ROW
          WHEN (NEW.ID IS NULL)
          BEGIN
            SELECT TEST_SEQ.NEXTVAL
            INTO :NEW.ID
            FROM DUAL;
          END;
    /

Then the trigger will be created successfully. So I guess the issue occurs when the parser finds two `END;`s ?

------

Some information for simulating this issue:

Table and sequence:

    CREATE TABLE "TEST" (
      "ID" NUMBER(*,0), 
      "DATA" VARCHAR2(100 CHAR)
    );

    CREATE SEQUENCE "TEST_SEQ";

DBeaver version 3.7.7 MacOSX-Version
Oracle 11g with OJDBC7 drivers

**Comment by serge-rider** [comment]
DBeaver doesn't have full support of PL/SQL yet. Sometimes it can't parse complex object definitions.
To execute Oracle DDL statements it is recommended to select query text and then execute it with CTRL+Enter.

**Comment by tomsoflow** [comment]
Thanks for the reply. Yes, selecting the query works fine if I omit the final `/`. Also this report might be a good test case if the development of the PL/SQL support progresses.
