### ISSUE TITLE
FIX Sorting columns by Data Type in Table->Column view should sort numeric values by number size

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#908]
Right now that column is alphabetically sorted like this:

	varchar(64)
	varchar(55)
	varchar(50)
	varchar(320)
	varchar(32)
	varchar(255)
	varchar(200)
	varchar(128)
	varchar(10)
	varchar(10)
	tinyint(1) 
	...	

expected sorting:

	varchar(320)	
	varchar(255)
	varchar(200)
	varchar(128)	
	varchar(64)
	varchar(55)
	varchar(50)
	varchar(32)
	varchar(10)
	varchar(10)
	tinyint(1)
	...

**Comment by serge-rider** [comment]
What database?

**Comment by allanlaal** [comment]
MySQL

**Comment by serge-rider** [comment]
I'm afraid it'll be too complicated. 
Type is name is a string (read from MySQL system catalog) - having semantic parser just for ordering isn't an easy task.
Maybe someday in a future..
