### ISSUE TITLE
Issue with oracle if schema filtering enabled with include list.

### ISSUE THREAD

**Issue by ravshansbox** [serge-rider/dbeaver#909]
<img width="456" alt="screen shot 2016-10-28 at 12 13 54 pm" src="https://cloud.githubusercontent.com/assets/1499188/19798065/4baca9f8-9d08-11e6-9c79-a26e0c2d8054.png">
<img width="552" alt="screen shot 2016-10-28 at 12 13 35 pm" src="https://cloud.githubusercontent.com/assets/1499188/19798064/4ba1fddc-9d08-11e6-8198-2d013d77fde3.png">

**Comment by ravshansbox** [comment]
problem occurred with version 3.7.7, previous versions worked well.

**Comment by infectormp** [comment]
duplicate https://github.com/serge-rider/dbeaver/issues/882

**Comment by serge-rider** [comment]
Yes, it is a duplicate.
Next version will fix this.
