### ISSUE TITLE
Column reposition

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#91]
New column is automatically added to the bottom of columns list. Can you add drag&drop to change column position before saving? It would be nice to add new column under selected column (column where was right-click fired) too.

Change context menu for creating column?
Add new column - add column to the bottom
Insert new column - Insert new column under selected column

Place: Table > Properties > Columns
Action: Context menu - Create new column

**Comment by serge-rider** [comment]
Most databases do not support column position change (at least easily, without table recreation). 
So I assume this feature is MySQL-specific.

**Comment by MatyCZ** [comment]
Yes, maybe Mysql and MariaDb specific - I use both of them.

**Comment by serge-rider** [comment]
The same feature needed for FireBird.

**Comment by adamos42** [comment]
The Firebird littlebit stupid with repositioning, you must give position for every column with POSITION:
```ALTER TABLE <table> ALTER <column> POSITION <new_position>;```

MySQL and MariaDB has the CHANGE COLUMN AFTER, which only needed the changed column:
```ALTER TABLE <table> CHANGE COLUMN <column> AFTER <column>;```

**Comment by CoyoteCzech** [comment]
+1

**Comment by egurelli** [comment]
For Mariadb ;

ALTER TABLE tbl_name MODIFY COLUMN col_name column_definition AFTER col_name;

Source : https://mariadb.com/kb/en/mariadb/alter-table/

**Comment by bsienn** [comment]
Except doing it with query manually, Still no option to reorder columns, mysql- mariadb? v3.8.5

**Comment by serge-rider** [comment]
Moving to 4.0.

**Comment by MrBrax** [comment]
Very cool, i'm trying to switch from SQLYog and this was the first issue i encountered, and it's even getting fixed, props 👍

**Comment by serge-rider** [comment]
I don't have time to add this in 4.0. Moving to 4.0.1.

**Comment by serge-rider** [comment]
Columns reorder implemented for MySQL/MariaDB.
Please test this in EA version. Going to include this feature in 4.0.2 version (release on the next week).

**Comment by MatyCZ** [comment]
When I click on button Move object up or Move object down I dont see any changes in list of columns (expected move object in list up/down).

**Comment by MatyCZ** [comment]
Can you add items **Move object up** and **Move object down** to the column context menu too?

**Comment by serge-rider** [comment]
This should work like this: 
![column-reorder](https://cloud.githubusercontent.com/assets/6398845/23352506/8bbf269e-fcd8-11e6-9333-bf93aa7e04ac.gif)

If nothing happens then please check debug log. There must be some error.

**Comment by MatyCZ** [comment]
Error log was empty and Debug log had only debug informations.

I try uninstall DBeaver, delete .dbeaver4 and now it works. Maybe some upgrade issue? Previous version was 4.0.1 - not EA version.

**Comment by MatyCZ** [comment]
Minor enhancement - Can you call refresh for tab **Data** after persist? Reposition changes are visible only when I click on Refresh in the Context menu.

**Comment by bsienn** [comment]
@serge-rider Thanks for your efforts. And helping in this project making it better for everyone. A lot of thanks.

**Comment by serge-rider** [comment]
@MatyCZ Not sure that refreshing data on save is a good idea. Sometimes you need old data, sometimes you have changes there, etc. One extra click isn't a big problem, I think.

This could be configurable but I don't believe that anyone will find such non-obvious option in preferences :)

So, closing. Further improvements of this feature should be tracked in separate issues.

**Comment by kid1412621** [comment]
@serge-rider won't show changes in real-time , version 5.2.5 windows. But after I saved the changes, it's fine.

**Comment by iambudi** [comment]
Any Update for firebird column reposition?

**Comment by silogos** [comment]
> This should work like this:
> ![column-reorder](https://cloud.githubusercontent.com/assets/6398845/23352506/8bbf269e-fcd8-11e6-9333-bf93aa7e04ac.gif)
> 
> If nothing happens then please check debug log. There must be some error.

Thanks, I don't see that
