### ISSUE TITLE
Flat Files Access

### ISSUE THREAD

**Issue by ravgulat** [serge-rider/dbeaver#911]
I am  running an query on flatfiles

**Comment by ravgulat** [comment]
I am running an query to select column from flatfiles, am returned with an error message attached herewith. 
![capture](https://cloud.githubusercontent.com/assets/23041233/19813730/fac7de62-9d08-11e6-81da-b224785ae14e.JPG)

Any suggestion will be welcomed.

**Comment by serge-rider** [comment]
Did you solve this?
