### ISSUE TITLE
Challenge Accessing table from flatfiles schema

### ISSUE THREAD

**Issue by ravgulat** [serge-rider/dbeaver#912]
Running an query on the table exist under flatfiles schema resulted in the attached error message. Table exists. Note I am connected to Oracle database. 

![capture](https://cloud.githubusercontent.com/assets/23041233/19813835/6f1cafae-9d09-11e6-962e-727afd768f86.JPG)

**Comment by serge-rider** [comment]
That's no clear.
If you are connected to Oracle then you can't query CSV datasource.
Open a separate SQL editor for CSV and run queries.
If you need to transfer data between CSV and Oracle you can use Data Export wizard.

**Comment by ravgulat** [comment]
Thanks for your prompt response. I want to query this csv table against oracle table. How can I do this ?

Thanks, 

Ravi

**Comment by serge-rider** [comment]
That's not possible out of the box. Oracle and CSV are different databases and you can't "join" them.

There are pretty many different approaches here - db links, federated databases. 
Or some kind of "composite" driver which can represent multiple databases as a single database (I know a couple of similar commercial products but do not know about free ones).

**Comment by ravgulat** [comment]
Thanks,

Ravi
