### ISSUE TITLE
List triggers on views

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#913]
In the properties window for a view, could you have a tab for triggers on that view like you have for tables?

**Comment by serge-rider** [comment]
What database?

**Comment by jk3us** [comment]
Postgres. See https://www.postgresql.org/docs/current/static/sql-createtrigger.html. Triggers can be created for tables, views and foreign tables (foreign data wrappers).

**Comment by serge-rider** [comment]
Will be added in 3.8
