### ISSUE TITLE
hive jdbc URL kerberos Authentication

### ISSUE THREAD

**Issue by dins2k2** [serge-rider/dbeaver#914]
Is there any way to connect to hive DB (kerberosied) through JDBC URL. I tried below URL with some parameters, but it doesn't work.

`jdbc:hive2://hiveserve2_host:10000/default;principal=hive/hiveserve2_host@realm_name;saslQop=auth`

Getting below error,

```
Unexpected driver error occurred while connecting to database
  java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
    java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
```

I have all the dependency jars (libraries) included.
I have installed MIT Kerberos in Windows 7 machine and have a valid ticket.

OS : Windows 7 64 bit
Dbeaver v3.7.7

**Comment by serge-rider** [comment]
This looks like very Hive-JDBC specific question. There are a few similar problems reported on Stackoverflow.
In any case this is not DBeaver bug or misfunction.

**Comment by r-richmond** [comment]
Hey @dins2k2 i wrote a blog post on this in case you are still having issues http://justnumbersandthings.com/2017-05-06-Dbeaver-Hive-Kerberos.html

**Comment by dharaniPV** [comment]
Hi @r-richmond 
I have configured Hive JDBC connection as you mentioned in the blog..but im getting a error 

[Cloudera][HiveJDBCDriver](500168) Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .
[Cloudera][HiveJDBCDriver](500168) Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .
javax.security.auth.login.LoginException: Unable to obtain Principal Name for authentication

Can you please help me solve this issue..
thanks.

**Comment by VenkataNU** [comment]
I am also facing the same issue, could you please share the details if you found a way to solve this @dharaniPV    -  "java.lang.RuntimeException: java.lang.RuntimeException: class org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2240)
"

**Comment by dharaniPV** [comment]
Hi @VenkataNU check this Link: http://disq.us/p/1j4o7rc and tell this issue to your admin who set the kerberos.
