### ISSUE TITLE
Oracle: show error position in SQL query

### ISSUE THREAD

**Issue by kiravi** [serge-rider/dbeaver#915]
Would help if the error returning also contained the SQL editor line number?

**Comment by serge-rider** [comment]
Well, whenever SQL script fails DBeaver highlights problem script query.
Also if you have a big query DBeaver points to the actual problem line/position in this query. But this is supported only for some databases (MySQL, Oracle, etc).
What is your database?

**Comment by loboaureo** [comment]
Hi, i use oracle, and when a run a query, it doesn't put the error line.
![screenshot_2](https://cloud.githubusercontent.com/assets/681482/19967491/d565d738-a1d0-11e6-86ba-8d654ff74e32.png)

**Comment by loboaureo** [comment]
By the way, this is how oracle SQLdeveloper inform of the error line 
![screenshot_3](https://cloud.githubusercontent.com/assets/681482/19967583/404d323a-a1d1-11e6-8666-f2af42033991.png)

**Comment by serge-rider** [comment]
Good point, DBeaver do not extract error position for non PL/SQL errors.
Will add position reading in the next version.

**Comment by kiravi** [comment]
loboaureo: Thanks. That was my precise comparison with Oracle SQL Developer.

**Comment by kiravi** [comment]
Using oracle connection.  
Ran this query:
SELECT
  'A' AS a1,
  10 AS a2,
  'B' AS a3
FROM
  dual
WHERE
  1 = TO_NUMBER( 'A1' );

Does not show error is at line number 8.

**Comment by serge-rider** [comment]
DBeaver uses dbms_sql parse/last_error_position to obtain error position. But this approach works only for SQL parse errors. In your example query is correct - problem happens in runtime.
I don't know how to get error position for such errors :(

**Comment by kiravi** [comment]
In PL/SQL (10G+):
    
    This can be obtained by 
    DBMS_UTILITY.format_error_backtrace

on exceptions.  Don't know if this helps.


    
    Ravi
        
        
    
        On 11/21/2016 12:53 PM, Serge Rider
          wrote:
        
        
        
      
      DBeaver uses dbms_sql parse/last_error_position to obtain error
        position. But this approach works only for SQL parse errors. In
        your example query is correct - problem happens in runtime.
        I don't know how to get error position for such errors :(
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/serge-rider/dbeaver","title":"serge-rider/dbeaver","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/serge-rider/dbeaver"}},"updates":{"snippets":[{"icon":"PERSON","message":"@serge-rider in #915: DBeaver uses dbms_sql parse/last_error_position to obtain error position. But this approach works only for SQL parse errors. In your example query is correct - problem happens in runtime.\r\nI don't know how to get error position for such errors :("}],"action":{"name":"View Issue","url":"https://github.com/serge-rider/dbeaver/issues/915#issuecomment-262031570"}}}

**Comment by serge-rider** [comment]
This works only in PL/SQL context - but not for plain SQL queries.
When you execute PL/SQL in DBeaver (e.g. in begin/end blocks) you will see valid error position (in the same form as format_error_backtrace returns).

But I don't know how to do the same for non-PL/SQL.

**Comment by kiravi** [comment]
Serge,

Any inputs on this for Oracle SQL?

This is the only reason why I need to switch to some other client when errors do not point to location of error.

Ideally there are 2 things that should happen:

Error indicates --> the error itself + line number of the error.
The cursor moves to location of the error automatically.
With 1./2. it should be so easy to write code :)

Example:
Query:
SELECT
3 + 'a' AS num
FROM
dual t;

This is the reason text:
Reason:
SQL Error [1722] [42000]: ORA-01722: invalid number

This is the "details":
SQL Error [1722] [42000]: ORA-01722: invalid number
SQL Error [1722] [42000]: ORA-01722: invalid number
SQL Error [1722] [42000]: ORA-01722: invalid number
SQL Error [1722] [42000]: ORA-01722: invalid number
ORA-01722: invalid number
ORA-01722: invalid number

Ravi

**Comment by serge-rider** [comment]
Yep, I did find the way to extract error position directly from Oracle exception (this works at least with Oracle 12 drivers). See fix in 5.0.6.
Thanks for reminding.

**Comment by kiravi** [comment]
Still does not work:

valid query:
------------
SELECT
  t.*
FROM
  (
    SELECT
      1 AS num
    FROM
      dual
  ) t;

dropped the sub-select table to create the error:

SELECT
  t.*
FROM
  (
    SELECT
      1 AS num
    FROM
      dual
  );

in oracle sql developer the error is:
----------------------------------------
ORA-00904: "T": invalid identifier
00904. 00000 -  "%s: invalid identifier"
*Cause:    
*Action:
**Error at Line: 2 Column: 5**

in DBeaver:
-------------
SQL Error [904] [42000]: ORA-00904: "T": invalid identifier
  SQL Error [904] [42000]: ORA-00904: "T": invalid identifier
    SQL Error [904] [42000]: ORA-00904: "T": invalid identifier
      SQL Error [904] [42000]: ORA-00904: "T": invalid identifier
        ORA-00904: "T": invalid identifier
        ORA-00904: "T": invalid identifier

In fact not only you do not get a line number, but the details shows too many repeated lines.

**Comment by kiravi** [comment]
DBMS_UTILITY.FORMAT_ERROR_BACKTRACE was introduced in 10g and is used to resolve this.  Please explorer it.

**Comment by serge-rider** [comment]
Try to use Oracle 12 JDBC driver (generally it is backward compatible with all earlier Oracle server versions).

**Comment by kiravi** [comment]
It worked!

Used all files from this link on 12.2.0.1 drivers:
http://www.oracle.com/technetwork/database/features/jdbc/jdbc-ucp-122-3110062.html

**Comment by MichalKorniak** [comment]
@serge-rider 
Hi
I still don't get information about error positon on Oracle. I'm using newest DBeaver (6.1.3) and JDBC in version 19.3.0 (also trying downgrade to 12.2.0.1, but result is same). Can you help me?

**Comment by ppruchnicki** [comment]
Unfortunately error persist in the 18.3.0.0 driver version, I'm unable to use 12.2.0.1 due to wallet configuration. Using @kiravi example the obtainable error is still displaying cursor position not the error line like it's done in SQL Developer:
`SQL Error [904] [42000]: ORA-00904: "T": invalid identifier`
