### ISSUE TITLE
Clicking through from HTTP Links contained in result sets

### ISSUE THREAD

**Issue by mtortolano** [serge-rider/dbeaver#918]
We generate a lot of SQL queries that factor in a URL to the output:

e.g. select sub.name, 'https://org.my.salesforce.com/' || sub.id as url from subscriptions

Is there a way to make the column in the resultset show those as links we can click on to directly open a browser window rather than having to cut and paste them all the time?

**Comment by serge-rider** [comment]
I like this. Hopefully it won't be to hard to implement.
