### ISSUE TITLE
Please add an option in 'Preferences' to set default text file encoding

### ISSUE THREAD

**Issue by netmole** [serge-rider/dbeaver#920]
I have a lot of SQL files that have chinese character.When the sql editor open the file ,it always use encoding  'utf-8'  by auto detecting from the flle encoding and the editor dislay the file incorrectly .
The properate encoding is 'GBK', I need set every file's encoding before open it.
Could you add a option in  'Preferences' to set the default encoding for sql editor?

**Comment by serge-rider** [comment]
Ok. I'll add extra preference option for that.

**Comment by netmole** [comment]
Thanks!

发自我的 Windows Phone
________________________________
发件人: Serge Rider<mailto:notifications@github.com>
发送时间: ‎2016/‎11/‎2 4:48
收件人: serge-rider/dbeaver<mailto:dbeaver@noreply.github.com>
抄送: neil shi<mailto:netmole@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [serge-rider/dbeaver] Please add an option in 'Preferences' to set default text file encoding (#920)


Ok. I'll add extra preference option for that.
