### ISSUE TITLE
Pua.Solimba virus threat from dbeaver 3.7.8 exe

### ISSUE THREAD

**Issue by dmacaro-broadsoft** [serge-rider/dbeaver#921]
Hi guys, the antivirus has identified the latest version 3.7.8 as a virus 
Pua.Solimba infection. Can you please investigate further?
![capture2](https://cloud.githubusercontent.com/assets/9848327/19885612/7e12c56e-a017-11e6-924d-ad2a90de1f79.PNG)

**Comment by serge-rider** [comment]
Interesting.
Where did you download this archive? (it has name `...-setup1.exe` while original installer named `...-setup.exe`).
Could you download fresh archive from here: http://dbeaver.jkiss.org/files/dbeaver-ce-latest-x86_64-setup.exe and try again?

**Comment by dmacaro-broadsoft** [comment]
that's because I've downloaded it several times, as Chrome was failing to finalise the downloaded file.
I've downloaded from the official website (http://dbeaver.jkiss.org/files/3.7.8/dbeaver-ce-3.7.8-x86_64-setup.exe)
![capture3](https://cloud.githubusercontent.com/assets/9848327/19886964/ada90832-a01d-11e6-9c7e-fe8d3785195e.PNG)

**Comment by carlosjrcabello** [comment]
I didn't get anything about threats from Avira and AVG (other machine) here.

![screen280](https://cloud.githubusercontent.com/assets/637767/19887136/e4b888a8-a00d-11e6-8758-9980d765c8ad.png)

I recommend you to scan your system, sometimes may have some threat running and infecting downloaded files.

**Comment by serge-rider** [comment]
Weird.
DBeaver installer definitely doesn't contain any malware. And it is built on Linux machine so it is very unlikely that it could be infected by Windows virus.

Webroot find it by mistake - maybe because Pua.Solimba may present in NSIS installers (actually it is one of the most popular installer in the world). I'll write to Webroot support. Thanks for report.

For now you can download zip archive instead of installer (if Webroot blocks installation).

**Comment by dmacaro-broadsoft** [comment]
Thanks Serge,

In response to Carlos, the second screenshot was from a full system scan.

**Comment by serge-rider** [comment]
BTW here is yet another virus scan report from Chocolatey package manager: https://chocolatey.org/packages/dbeaver
They use 50 different anti-viruses. 1 of 50 checks fails. False-positive as they call it.

**Comment by serge-rider** [comment]
Here is the reply from Webroot support:
```
RE:DBeaver installer issue

Hello,

Thank you for your report.
We have reversed the false positive detections.
Apologies for the inconvenience.

Regards,
Webroot Support
```
Hopefully this resolves the problem.
