### ISSUE TITLE
Can not edit directly value on table data grid

### ISSUE THREAD

**Issue by caladfelipe** [serge-rider/dbeaver#923]
On any table data grid, when you select a value from the dropdown of an enum field and the focus is lost, the selected cell resets and undo the selection returning to the original cell value.

**DBeaver version:** DBeaver Community Edition 3.7.8 - Mac OS X (dmg)

**Comment by serge-rider** [comment]
Can't reproduce (Mac OS X Yosemite). 
What is your Mac version?
Can you edit enums using value view panel (f7)?

**Comment by caladfelipe** [comment]
My Mac version is Mac OS X El Capitan.
![dbeaver issue 923](https://cloud.githubusercontent.com/assets/3412545/19895824/411568de-a020-11e6-8354-56a6e1c27a41.gif)
