### ISSUE TITLE
Named parameters no longer seen

### ISSUE THREAD

**Issue by bberenz** [serge-rider/dbeaver#924]
In the latest version (3.7.8), named parameters fail to work.

Using a simple query such as `SELECT * FROM somewhere WHERE id = :id;`
The `:id` parameter shows up properly in the "Bind Parameter(s)" dialog, but fails to execute with reason:

>Can not bind statement parameter
>java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).

This did work in v3.7.7, and unnamed parameters (`id = ?`) do still work in the latest version.

**Comment by serge-rider** [comment]
Yes, it is a bug in 3.7.8. Thanks for report.
