### ISSUE TITLE
Temp Table Question

### ISSUE THREAD

**Issue by sprintel** [serge-rider/dbeaver#925]
I actually submitted this question via email (support@jkiss.org) not knowing that I can submit my question here. How do I view sqlite temp tables on DBeaver? I can only see the regular tables on the left hand panel but not the temp tables. Does DBeaver support this?

**Comment by serge-rider** [comment]
It is tricky.
Temp tables exist only within current connection. You can see these tables after table list refresh but there is a bug (or misfunction) in DBeaver - as SQLite do not support schema refresh performs reconnect (which obviously removes all your temp tables).
I've fixed that so you'll be able to see your temp tables in the next version.
Another thing: you will need to disable "Open separate connection for each editor" option in SQL editor preferences.

**Comment by sprintel** [comment]
Thanks Serge for the quick response. Looking forward to the enhancement.

Also, on issue #535 (SQLite extension (table rename, triggers, etc)), do you also plan to add an option to rename a field as well? I commented on that thread but I don't see any response. In sqlite, renaming a field is kind of a pain. To have an auto generated script will be helpful.
