### ISSUE TITLE
Scroll cursor can't select blob columns 

### ISSUE THREAD

**Issue by yujishe** [serge-rider/dbeaver#928]
I connection informix that use the default configuration. when I select some table that alert error message (

SQL 错误 [IX000]: Scroll cursor 不能选取 blob 字段群。
  Scroll cursor 不能选取 blob 字段群。
    java.sql.SQLException: 
 )
 In English that mean  Scroll cursor can't select blob columns .
I'm very confused with this error, especially the error after I use the latest version.But after I go back to the old version, found that the problem is still there.
So now I use the DbVisualizer, it no problem.

**Comment by serge-rider** [comment]
Unfortunately I can't test this (I don't have test Informix server).
Try to enable BLOB cache:
![prefs-lob-cache](https://cloud.githubusercontent.com/assets/6398845/19924852/c2a20b44-a0fe-11e6-8b24-df0429fd6fd6.png)

Also, if you execute custom SQL queries you could try to turn on option "Keep open cursors in SQL editor" (on Result Sets pref page).

**Comment by yujishe** [comment]
it doesn't work. I repeatedly try,the error is still there. Maybe the error is come from   Informix  @serge-rider

**Comment by serge-rider** [comment]
I have no ideas so far. 
According to error message this may mean that LOBs can't be read from "scrollable" cursors but DBeaver doesn't use scrollable cursors.

Try another trick - set resultset fetch size to 0 (you can do it right in the main toolbar or in ResultSets preference page).

**Comment by yujishe** [comment]
Once again, thanks for your   @serge-rider  
 I suspect the problem is a JDBC driver setting problem, and  discover the cause of the problem is here.
![image](https://cloud.githubusercontent.com/assets/22394316/20162639/6a245df8-a731-11e6-8bf0-7ac2f82e2f64.png)
After I cancelled the choice, I success.

**Comment by serge-rider** [comment]
Great!
As far as I see this option is off by default (for Informix) so there is nothing to fix..
