### ISSUE TITLE
ER-diagram is broken in 3.7.8

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#929]
I just updated to DBeaver 3.7.8 and now I'm not able to refresh my MariaDB ER-diagram or view it. It simply errors out and suggest me to check my log. As I think you are able to reproduce this instantly I won't attach a log. My log is full of errors and I'm not sure which is enough. If you can't reproduce it I will attach it with your support.

EDIT: Closing and starting DBeaver again just fixed it. Maybe this bugs only occurs after upgrade once on first launch?

**Comment by serge-rider** [comment]
No, I can't reproduce that, please attach the log.

**Comment by GiantCrocodile** [comment]
I've attached my logfile @serge-rider. I hope this is enough as I had to delete a lot of sensitive data ... I don't feel like it is a good idea to store clear-text log in details to server in log ...
[log.txt](https://github.com/serge-rider/dbeaver/files/566453/log.txt)

**Comment by serge-rider** [comment]
Thanks.
As far as I see the problem is in broken connection. When you opening ERD connection is lost and all attempts to read metadata fail.
I'll add extra checker/error dialog before ERD rendering. This will let you to reconnect.

**Comment by GiantCrocodile** [comment]
@serge-rider I'm not sure why I always loose the connection. I run my server locally and timeout shouldn't happen this fast. Sometimes I'm loosing connection seconds after seconds ... Maybe there is a bigger bug hiding behind this.

**Comment by serge-rider** [comment]
I can't say for sure.
All (even local) connections are closed if you put your machine in sleep (this is how my local db loose connections from time to time). Or in case of network interface reset.
Generally you shouldn't loose your local server connections ever (unless you have some special connection timeout settings).

**Comment by GiantCrocodile** [comment]
Then there is somewhere a bug. I never loose my connection to my database when I'm in mysql console and in DBeaver I can loose it in seconds. Also I don't know why my connection is lost, just after starting DBeaver. I just started DBeaver and clicked on ER-diagram tab. Standby is nothing I do and a network interface reset doesn't happen too.

**Comment by serge-rider** [comment]
I think this worth another issue, this is not related to ERD at all.
From the log file I see that you started DBeaver and connection was lost after 12 minutes. It is not clear when exactly it was opened and what operation were performed between these two events.

Please create another issue. If you will be able to reproduce this connection lost - please post error log again leaving as much details as possible (it makes sense to cleanup error log before trying to reproduce this).

> I don't feel like it is a good idea to store clear-text log in details to db server in log

What choices do we have? There are no passwords or SSL certs in the log, everything else may be needed to understand the problem. This log is never transmitted to anywhere and it is stored in user home folder - so it is more or less safe.

**Comment by GiantCrocodile** [comment]
@serge-rider I have to disagree with you that there are no passwords stored. I found a line of some query where I was able to see IP, username, password. So if I had uploaded the file over here without checking I would have exposed sensitive data to public. That's why I was not amused.

**Comment by serge-rider** [comment]
This may happen only if you execute such query manually. 
Passwords you enter in connection settings (and any other explicit passwords) are never logged. At least they shouldn't - if you see any of them in log then this is a bug and it should be fixed.
