### ISSUE TITLE
SQL Error [1064] [42000] : Editing data contained in columns using reserved keywords as names

### ISSUE THREAD

**Issue by tpizza** [serge-rider/dbeaver#93]
Issue title sums it up.

In the instance I've run into multiple tables are using a column named 'release'.  Any attempt to apply edits to data within those columns throws SQL Error [1064] [42000].

After testing a multitude of tables as well as editing data from other columns within tables containing the 'release' column with success, I was able to deduce that the issue is keywords used as column names are not being escaped correctly.

I just started using dbeaver a couple days ago, and overall have to say dbeaver is a pretty rad GUI.  Great work.

Steps to reproduce:

1.)  Create or import a table with a column named 'release'.  The data type does not matter.
2.)  Open the table in IDE and view its data.
3.)  Edit a value for any row in the 'release' column.
4.)  Attempt to save the change and observe the SQL error thrown.

**Comment by serge-rider** [comment]
What database?

**Comment by tpizza** [comment]
Did a quick data dump from Navicat of one of the tables I was testing the issue with yesterday.

This table is using tinyint, the others were using varchar.



/*
Navicat MySQL Data Transfer

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2015-12-06 15:51:08
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for ReleaseVersions
-- ----------------------------
DROP TABLE IF EXISTS `ReleaseVersions`;
CREATE TABLE `ReleaseVersions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `state` varchar(2) NOT NULL,
  `release` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=57 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ReleaseVersions
-- ----------------------------
INSERT INTO `ReleaseVersions` VALUES ('1', 'AL', '1');
INSERT INTO `ReleaseVersions` VALUES ('2', 'AK', '1');
INSERT INTO `ReleaseVersions` VALUES ('3', 'AS', '1');
INSERT INTO `ReleaseVersions` VALUES ('4', 'AZ', '1');
INSERT INTO `ReleaseVersions` VALUES ('5', 'AR', '1');
INSERT INTO `ReleaseVersions` VALUES ('6', 'CA', '1');
INSERT INTO `ReleaseVersions` VALUES ('7', 'CO', '1');
INSERT INTO `ReleaseVersions` VALUES ('8', 'CT', '1');
INSERT INTO `ReleaseVersions` VALUES ('9', 'DE', '1');
INSERT INTO `ReleaseVersions` VALUES ('10', 'DC', '1');
INSERT INTO `ReleaseVersions` VALUES ('11', 'FL', '1');
INSERT INTO `ReleaseVersions` VALUES ('12', 'GA', '1');
INSERT INTO `ReleaseVersions` VALUES ('13', 'GU', '0');
INSERT INTO `ReleaseVersions` VALUES ('14', 'HI', '1');
INSERT INTO `ReleaseVersions` VALUES ('15', 'ID', '1');
INSERT INTO `ReleaseVersions` VALUES ('16', 'IL', '1');
INSERT INTO `ReleaseVersions` VALUES ('17', 'IN', '1');
INSERT INTO `ReleaseVersions` VALUES ('18', 'IA', '1');
INSERT INTO `ReleaseVersions` VALUES ('19', 'KS', '1');
INSERT INTO `ReleaseVersions` VALUES ('20', 'KY', '1');
INSERT INTO `ReleaseVersions` VALUES ('21', 'LA', '1');
INSERT INTO `ReleaseVersions` VALUES ('22', 'ME', '1');
INSERT INTO `ReleaseVersions` VALUES ('23', 'MD', '1');
INSERT INTO `ReleaseVersions` VALUES ('24', 'MA', '1');
INSERT INTO `ReleaseVersions` VALUES ('25', 'MI', '1');
INSERT INTO `ReleaseVersions` VALUES ('26', 'MN', '1');
INSERT INTO `ReleaseVersions` VALUES ('27', 'MS', '1');
INSERT INTO `ReleaseVersions` VALUES ('28', 'MO', '1');
INSERT INTO `ReleaseVersions` VALUES ('29', 'MT', '1');
INSERT INTO `ReleaseVersions` VALUES ('30', 'NE', '1');
INSERT INTO `ReleaseVersions` VALUES ('31', 'NV', '1');
INSERT INTO `ReleaseVersions` VALUES ('32', 'NH', '1');
INSERT INTO `ReleaseVersions` VALUES ('33', 'NJ', '1');
INSERT INTO `ReleaseVersions` VALUES ('34', 'NM', '1');
INSERT INTO `ReleaseVersions` VALUES ('35', 'NY', '1');
INSERT INTO `ReleaseVersions` VALUES ('36', 'NC', '1');
INSERT INTO `ReleaseVersions` VALUES ('37', 'ND', '1');
INSERT INTO `ReleaseVersions` VALUES ('38', 'MP', '1');
INSERT INTO `ReleaseVersions` VALUES ('39', 'OH', '1');
INSERT INTO `ReleaseVersions` VALUES ('40', 'OK', '1');
INSERT INTO `ReleaseVersions` VALUES ('41', 'OR', '1');
INSERT INTO `ReleaseVersions` VALUES ('42', 'PA', '1');
INSERT INTO `ReleaseVersions` VALUES ('43', 'PR', '1');
INSERT INTO `ReleaseVersions` VALUES ('44', 'RI', '1');
INSERT INTO `ReleaseVersions` VALUES ('45', 'SC', '1');
INSERT INTO `ReleaseVersions` VALUES ('46', 'SD', '1');
INSERT INTO `ReleaseVersions` VALUES ('47', 'TN', '1');
INSERT INTO `ReleaseVersions` VALUES ('48', 'TX', '0');
INSERT INTO `ReleaseVersions` VALUES ('49', 'UT', '1');
INSERT INTO `ReleaseVersions` VALUES ('50', 'VT', '1');
INSERT INTO `ReleaseVersions` VALUES ('51', 'VI', '1');
INSERT INTO `ReleaseVersions` VALUES ('52', 'VA', '1');
INSERT INTO `ReleaseVersions` VALUES ('53', 'WA', '1');
INSERT INTO `ReleaseVersions` VALUES ('54', 'WV', '1');
INSERT INTO `ReleaseVersions` VALUES ('55', 'WI', '1');
INSERT INTO `ReleaseVersions` VALUES ('56', 'WY', '1');
