### ISSUE TITLE
Keywords color disappears when renaming open SQL files

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#930]
Hi,

DBeaver version: 3.7.8
OS: Linux Mint 17.3

Steps to reproduce:

1. Create a new script file (Ctrl + F3). Its name is "script.sql";
2. Add a few SQL commands;
3. Rename the file without closing it (F2), without precising the ".sql" extension (it is done automatically);
4. In the SQL editor, words coloration has disappeared.

I did not notice this bug in older versions.

Regards,

Cedric

**Comment by serge-rider** [comment]
Thanks for report
