### ISSUE TITLE
Question: Url Template with additional variables?

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#932]
Hey serge quick question when defining a new driver/ URL Template I've run across an issue where I need an additional variable (outside of host, user, password, database, & port). For example {realm}.

If I place {realm} in the template where do I configure the variable realm for a given connection for the new driver? (Note: I'd expect a new dialog box on the Connection settings page but it doesn't seem to appear)

<img width="806" alt="screen shot 2016-11-02 at 9 09 50 am" src="https://cloud.githubusercontent.com/assets/9246654/19936819/26d10b10-a0dc-11e6-9d15-f26bc6328ad7.png">

p.s. is it possible to change the background for the JDBC URL for the dark theme? the default color is very hard to read.

**Comment by serge-rider** [comment]
It is not possible to add custom variables for connection.
As a workaround you can use variable {server}. This gives 3 different database config fields: host, server and database name.

**Comment by serge-rider** [comment]
JDBC field background will be fixed in the next version.

**Comment by r-richmond** [comment]
Thanks I didn't know about the server variable.

Its a low priority request as this is the first time I've ran across this issue but custom server variables might be worth considering. Even if its just a static list of 1-3 more. i.e. variable 1, 2, 3

p.s. thanks for fixing the background
