### ISSUE TITLE
PostgreSQL 9.6 connection not showing any tables

### ISSUE THREAD

**Issue by gtirloni** [serge-rider/dbeaver#933]
When connected to a local PostgreSQL server, DBeaver does not show any tables.

Steps to reproduce:

 * Use some other tool to create tables (tested with postgres DB and public schema)
 * Create a PgSQL connection in DBeaver
 * Navigate to tables

Results:

No tables are shown even though they exist (confirmed through other tools).

Environment:

 * DBeaver 3.7.8
 * PostgreSQL 9.6.1
 * Fedora 24

**Comment by serge-rider** [comment]
Just tested with PG 9.6.1 and I didn't reproduce that.
- Can you see tables in other schemas? E.g. pg_catalog
- Are there any error in error log?
- To read tables in `public` DBeaver executes query `SELECT n.oid,n.* FROM pg_catalog.pg_namespace n WHERE nspname='public' ORDER BY nspname`. Could you try it in SQL editor.

**Comment by gtirloni** [comment]
@serge-rider rookie mistake, working on the wrong database. sorry about that.

I can confirm everything is working fine.

**Comment by tomrod** [comment]
Second this issue. I created tables both in DBeaver and via psql. I have tried disconnecting and reconnecting DBeaver, restarting the system, restarting the service. The tables aren't showing up in database navigator although I can query the tables.

**Comment by serge-rider** [comment]
Most likely it is some kind of config problem (e.g. you co necting to a different databases in dbeaver and psql).
If you 100% sure then I'll need more info (what driver do you use, is there anything in error/debug logs). And its better to create a ne ticket.

**Comment by tomrod** [comment]
You are right, it was user config issue.

**Comment by mnfabiao** [comment]
Hi
are you using the exact same database Instance in connection string?
Check if you are wrongly connecting to default "postgres" instance in your database in Connection Settings.
