### ISSUE TITLE
Update to Version 3.7.8 fails in Eclipse

### ISSUE THREAD

**Issue by wormuth** [serge-rider/dbeaver#935]
An error occurs while trying to install the latest DBeaver update:

Unable to read repository at http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer$1.performFileTransfer(AbstractRetrieveFileTransfer.java:178)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Step 1:
![screen1](https://cloud.githubusercontent.com/assets/2778069/19959045/0538e5c2-a1a4-11e6-94ab-766db322d8ed.png)

Step 2:
![screen2](https://cloud.githubusercontent.com/assets/2778069/19959044/0538c722-a1a4-11e6-9b1f-bb096d6206e9.png)

Error Log:
![screen3](https://cloud.githubusercontent.com/assets/2778069/19959046/05397c44-a1a4-11e6-9400-5ad1ad884d16.png)

**Comment by pfhjgd0** [comment]
Getting the same error on Eclipse Luna

An error occurred while collecting items to be installed
session context was:(profile=MFWorkbenchEnterprise, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar.
Connection reset

**Comment by serge-rider** [comment]
Does retry help? Seems to be working now.
This looks like temporary web site unavailability (maybe due to high load - this happens after new version release).

**Comment by pfhjgd0** [comment]
I tried it again and get the same error. I am using the Eclipse Marketplace to do the install. Tried 3 times with same resulting error.

John Dannenberg | Product Owner | Compuware Mainframe Solutions
john.dannenberg@compuware.com<mailto:john.dannenberg@compuware.com> | O: +1 313 227-7177
____________________________________________________________________________
Compuware.com/<http://www.compuware.com/en_us/mainframe-solutions.html>mainframe  |  Facebook <https://www.facebook.com/compuware>   | Twitter<https://twitter.com/compuware>  | Blog<http://insidetechtalk.com/>

**Comment by wormuth** [comment]
High load problems after new release seems probable, yet currently the problem is still present.

Will try out in a few days time again, thanks for now for the feedback!

**Comment by wormuth** [comment]
Still not working, perhaps it isn't a temporary high load problem after all...

**Comment by serge-rider** [comment]
Yes, probably this is something else.
I can't say what exactly - I can update (or install using "Install New Software" or install from Marketplace) without any errors.
Maybe you need a fresh Eclipse install.

**Comment by wormuth** [comment]
No,
I don't think it's a problem with my eclipse - esp. since the direct download http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar using my web browser does not work for me...

I tried a fresh install anyway, without success.

**Comment by pfhjgd0** [comment]
I agree. Navigate in Chrome to http://dbeaver.jkiss.org/update/latest/plugins/
from there select then selected the file Eclipse wanted to download org.jkiss.dbeaver.ext.generic_2.3.30.jar

Get same error "Failed - Network error"

**Comment by koval-jan** [comment]
I have the same problem. I even adjusted eclipse timeout settings and retry attempt count but it did not help.

Eclipse version (eclipse.buildId=3.8.2.201610040914-RELEASE-e45)

Added arguments:
-Dsun.net.client.defaultReadTimeout=120000
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.closeTimeout=120000
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.readTimeout=120000
-Dorg.eclipse.ecf.provider.filetransfer.httpclient4.retrieve.connectTimeout=120000
-Dorg.eclipse.ecf.provider.filetransfer.httpclient4.retrieve.readTimeout=120000
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.retryAttempts=20
-Dorg.eclipse.equinox.p2.transport.ecf.retry=5

Error during install:

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Failed to transfer artifact canonical: osgi.bundle,org.jkiss.dbeaver.ext.generic,2.3.30.
Connection to http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar failed on Connection reset. Retry attempt 1 started
Connection reset
Connection to http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar failed on Connection reset. Retry attempt 2 started
Connection reset
Connection to http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar failed on Connection reset. Retry attempt 3 started
Connection reset
Connection to http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar failed on Connection reset. Retry attempt 4 started
Connection reset
Connection to http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar failed on Connection reset. Retry attempt 5 started
Connection reset
Unable to read repository at http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar.
Connection reset

**Comment by serge-rider** [comment]
Wow, that's interesting. Because I can download this file without error (and I thought that you also can do this). I tested it from at least 4 different machines from 3 different countries and it works just fine. From apache log I see that there were a lot of successful downloads of http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar file during last few days (and zero errors).
This makes me frustrating.

Is org.jkiss.dbeaver.ext.generic_2.3.30.jar is the only problem file or you can't download any jars?

**Comment by serge-rider** [comment]
Just a thought: is it possible that some antivirus software blocks this?

**Comment by koval-jan** [comment]
It seems you are correct I've tried to download the file through mobile direct connection and I was able to download it.
Normally I am behind company firewall.

**Comment by pfhjgd0** [comment]
I tried to download and it failed with all the extensions selected.
I **De-selected** Exasol, Generic, and Oracle Extensions and the download worked.

**Comment by koval-jan** [comment]
When I'm behind the firewall I have problem only with http://dbeaver.jkiss.org/update/latest/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar
All other files within the folder http://dbeaver.jkiss.org/update/latest/plugins are downloadable

**Comment by serge-rider** [comment]
Weird. So far I have no idea what's going on. Maybe this jar has false-positive detection in some antivirus software (see #921). But maybe something else happens.

Could you also try to update/check jars at: 
- http://dbeaver.jkiss.org/files/3.7.8/repository-ce/plugins/
- http://dbeaver.jkiss.org/files/3.7.7/repository-ce/plugins/

**Comment by wormuth** [comment]
Cannot download org.jkiss.dbeaver.ext.generic_2.3.30.jar from both locations, all other jars OK.
WTF...

**Comment by koval-jan** [comment]
I've created a tcpdump while fetching http://dbeaver.jkiss.org/files/3.7.8/repository-ce/plugins/org.jkiss.dbeaver.ext.generic_2.3.30.jar

[capture.pcap.zip](https://github.com/serge-rider/dbeaver/files/575409/capture.pcap.zip)

**Comment by serge-rider** [comment]
Looks like some glitch.
I've cleaned up Apache config and restarted everything. Please try again.

**Comment by koval-jan** [comment]
There is still a problem. When downloading through chrome donload fails but then when I resume it it will finish correctly

[capture2.pcap.zip](https://github.com/serge-rider/dbeaver/files/575457/capture2.pcap.zip)

**Comment by wormuth** [comment]
Everything's fine now for me - manual download succeeded, update via eclipse as well!
Thanks for the help!

**Comment by mcrobbj** [comment]
Not working for me: Unable to read repository at https://dbeaver.jkiss.org/update/latest/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
