### ISSUE TITLE
"desc" support in oracle

### ISSUE THREAD

**Issue by loboaureo** [serge-rider/dbeaver#936]
Desc[ribe] is a command of oracle that shows the info of a table. Could it be implemented in dbeaver?

http://docs.oracle.com/cd/B19306_01/server.102/b14357/ch12019.htm

**Comment by serge-rider** [comment]
No, desc (or describe) won't be implemented in DBeaver. It is SQLPlus command which shows table structure. In DBeaver you can see table structure/details in table editor.
