### ISSUE TITLE
Edit results of join

### ISSUE THREAD

**Issue by kiravi** [serge-rider/dbeaver#937]
Assume we have editable permissions on table A
and no editable permissions on table B.

A select statement like this:

select A.rowid, A.*, B.z from A, B where A.x = B.y will not allow any of cells or inline edit on table A.

Why is this?

**Comment by serge-rider** [comment]
That's because DBeaver doesn't support edit of results of joined tables.

**Comment by kiravi** [comment]
I tested this in oracle sql developer and pl/sql developer from all around automations and DB visualizer.

All allow this as long as rowid is known because rowid is preserved in an insert/update statement.

**Comment by kiravi** [comment]
it is on oracle

**Comment by kiravi** [comment]
I checked an apparently inline edits are allowed in most dbs
where if I permissions on table a, b and no permissions on table c.
Then
select a.rowid as a_rowid, a.*, b.*, c.rowid as c_rowid, c.* from a,b,c

should allow 

1) edits on any field in a --> since rowid is preserved in edit and has permissions,
2)  no edits on b since rowid is missing
3) no edits on c since user has no permissions even when c.rowid is present.

Ravi

**Comment by pyhedgehog** [comment]
You can create editable view and use it. You can ever create view with 'instead of update/insert/delete' triggers.
