### ISSUE TITLE
Show Epoch time (integer) columns like datetime

### ISSUE THREAD

**Issue by your-mirror** [serge-rider/dbeaver#94]
Some times I have to work with integer types that have used like timestamp. Will be great if u will add right click option "Show like datetime" that exist in HeidiSQL.

**Comment by serge-rider** [comment]
Do you mean epoch time (aka unix time aka java time)?
I think it is a good feature. And it will be useful not only for MySQL but for any other database as well.

**Comment by your-mirror** [comment]
Yes, In MySQL it's a timestamp.

**Comment by serge-rider** [comment]
![view_as_epoch](https://cloud.githubusercontent.com/assets/6398845/14674769/4372d9c8-070e-11e6-87ba-dbf1a73c1ed6.png)

**Comment by your-mirror** [comment]
great
