### ISSUE TITLE
dBeaver should use rowid in Oracle

### ISSUE THREAD

**Issue by davitof** [serge-rider/dbeaver#940]
I have a table with no unique key. I am trying to manually remove duplicate rows. After SELECTing rows, I can mark rows to delete, but when I press Save, dbeaver tells me that since my table does not have a unique key, he would use all columns to filter the rows to be deleted, which of course would not suit my needs. So I edited my SELECT to include the ROWID pseudo-column, but now I get an error dialog telling me "(my_table_name) has no unique key", and when I press OK, I get a second error dialog saying "No unique identifier defined". I saw in this forum that dbeaver knows about rowid pseudo-columns, so I think that it should use this in my situation. If I explicitly select rowid, dbeaver would use it to delete or update rows. If I don't explicitly select the rowid pseudo-column, dbeaver could silently retrieve it (but without displaying it) and use it to perform operations.

(Oracle XE 11g / Windows 10 / dBeaver )

**Comment by serge-rider** [comment]
Currently DBeaver supports ROWID columns only in table editor, it is not used in custom queries.

**Comment by davitof** [comment]
OK.

**Comment by serge-rider** [comment]
RowId processing will be changed in the next version. Not only for Oracle but also for DB2 and PostgreSQL.

**Comment by davitof** [comment]
Excellent ! 

Off topic: I just saw above that I modified the milestone. I did not know I had such powers!
