### ISSUE TITLE
Bind Parameters BINARY column

### ISSUE THREAD

**Issue by adkhare** [serge-rider/dbeaver#942]
with using bind parameters for binary, there is no way to use binary data

**Comment by serge-rider** [comment]
Parameters binding is broken in 3.7.8.
Binding of binary/LOB parameters is not yet supported. I'll add this feature if it won't be too complicated.

**Comment by serge-rider** [comment]
Next version will support dynamic parameters of any type (you can even use expressions/subquerys as parameter values).
To specify binary parameter you'll need to enter value binary representation. It depends on database. For instance in MySQL is `0x01234...`.
