### ISSUE TITLE
dbeaver enterprise 3.7.7: connect redis failed.

### ISSUE THREAD

**Issue by hkun0120** [serge-rider/dbeaver#945]
new -->redis--->type the correct ip and port ----> test connection 
the connection error occurs !! but command in the linux shells "redis-cli -h 10.211.55.13 -p 6379"connect right!

the error information like below:
Could not get a resource from the pool
  redis.clients.jedis.exceptions.JedisDataException: ERR Syntax error, try CLIENT (LIST | KILL ip:port)
![Uploading 屏幕快照 2016-11-06 下午10.21.17.png…]()

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view).

**Comment by hkun0120** [comment]
where is it? in the dbeaver folder?

**Comment by serge-rider** [comment]
Thanks. Looks like your Redis server is quite old. Do you know the version number?
Connection fails when Jedis tries to execute command CLIENT SETNAME (which was added in 2.6.9).

**Comment by hkun0120** [comment]
thank you very much! the question is resolved!

**Comment by serge-rider** [comment]
Ok
