### ISSUE TITLE
Pressing [Add new row] while editing a column

### ISSUE THREAD

**Issue by davitof** [serge-rider/dbeaver#946]
Hello,

I found a small glitch in the UI: in the table editor, press [Add new row], fill enough info so that the new row can be inserted, enter some value in one of the remaining columns and **_without leaving the column_** click on [Add new row] again to create yet another row. In this situation, the value disappears silently and the first row gets created with a null in the column where the cursor was. IMO, dBeaver should at least send a warning saying the value was lost, or it could keep the value, or the [Add new row] button could be disabled while a column is being edited.

**Comment by davitof** [comment]
This was corrected in dBeaver 3.8.0:the "+" is now disabled while editing a value. Thank you, Serge

**Comment by serge-rider** [comment]
Ok, good.
Forgot to include this issue in 3.8 milestone.
