### ISSUE TITLE
Dbeaver is not displaying results of the select query correctly for MySQL db

### ISSUE THREAD

**Issue by igupta** [serge-rider/dbeaver#949]
When I connect dbeaver to MySQL it is not displaying the rows present in the table when I fire a select query.It displays no rows fetched for the query but rows are actually present in the db.

**Comment by serge-rider** [comment]
Please provide more details.
Maybe you are working in transaction mode (thus you need to perform commit/rollback to see changes made by another program).

**Comment by igupta** [comment]
Hi Serge I am not working in Transaction mode I am just firing select queries from Dbeaver but I am not getting results for select query from Dbeaver but same query is returning results when fired from MySQL workbench.

**Comment by serge-rider** [comment]
Can't reproduce that. More details needed.
