### ISSUE TITLE
MacOS installer broken

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#95]
Due to some build/sign problem DBeaver can't be run on recent MacOS versions. 
It fails with "damaged and can't be opened" error.
Possible workarounds: 
- https://support.apple.com/en-us/HT202491
- http://portingteam.com/frontpage/_/news/portingteam-news/wrapper-damaged-on-mac-os-x-109-mavericks-r46

**Comment by ArloL** [comment]
I am not sure if it helps but this is the result of spctl or codesign verification

```
$ spctl --assess DBeaver.app/
DBeaver.app/: invalid Info.plist (plist or signature have been modified)

$ codesign -v DBeaver.app/
DBeaver.app/: invalid Info.plist (plist or signature have been modified)
```

**Comment by NBOnGithub** [comment]
Any chance of getting this fixed? - my company stops me selecting 'anywhere' on the preferences so I cannot install if the signature is not correct :-(

**Comment by serge-rider** [comment]
You could try Homebrew (http://brew.sh/).
At the moment DBeaver doesn't have associated Apple developer ID (which costs money).

**Comment by NBOnGithub** [comment]
That works perfectly. You can install either version with one of these commands
brew install Caskroom/cask/dbeaver-enterprise
brew install Caskroom/versions/dbeaver-community
Many thanks for the rapid reply.

**Comment by jgroves-hw** [comment]
I resolved this by replacing the invalid code signature with a new one with the following command:

sudo codesign --force --sign - /Applications/DBeaver.app

OS X will then treat the app as a normal unsigned application and allow you to open it accordingly

The answer by user495470 in http://apple.stackexchange.com/questions/18306/fixing-a-sealed-resource-is-missing-or-invalid-warning lead me to this solution.

**Comment by f-lima** [comment]
My problem is not related with code sign. To force macOS Sierra open, it is easy as select Open from the pop-up menu (right-click with mouse). I have many apps installed that are not code signed and I open all without problem (like Meld and DBVisualizer) but DBeaver stopped to work when I tried to update and none of previous versions, not only the last one, can be installed because gives the error saying that file is corrupted. I think that is something related with the download manager used at site because I don't have this problem with any other site but DBeaver.

**Comment by ggiessen** [comment]
This works for me:  xattr -rc /Applications/DBeaver.app

**Comment by cederom** [comment]
the same here :-(

**Comment by g4brielvs** [comment]
Try using [Homebrew Cask](http://caskroom.io) for managing macOS applications from the command line!

`brew install dbeaver-community`

**Comment by cederom** [comment]
I am using MacPorts :-) `xattr` fixed the problem for now so case closed thanks! :-)

**Comment by yhjhoo** [comment]
The following works for me : 


`chmod  +x /Applications/DBeaver.app/Contents/MacOS/dbeaver`

**Comment by hgrod** [comment]
My users were getting "DBeaver cannot be opened", with no further suggestions or details.
I had to both remove the extended attributes AND update the permissions with chmod.

The DBeaver.app was being installed without the proper permissions. For all my users, they needed to change their permissions to: drwxrwxr-x
I navigated to the Applications folder for the machines (not user's applications) and ran the following:

first remove the extended attributes
`xattr -rc DBeaver.app `
then recursively give permissions to all in all DBeaver folders, note this gives drwxrwxrwx not drwxrwxr-x. If you don't want ALL, please find the proper command for that.

`sudo chmod -R uog+wxr DBeaver.app`

**Comment by serge-rider** [comment]
Problem with non-executable binary in MacOS tar.gz will be fixed in the next version. 
Thanks for noticing.

**Comment by ftstc451810** [comment]
Encounter this problem while brewing DBeaver:
<img width="570" alt="clip02" src="https://cloud.githubusercontent.com/assets/16112232/24185109/668f68c0-0f0c-11e7-9ace-78cb064bed56.png">
Did it mean that Brew should be upgraded? or was the failure just caused by the Error: "Unknown command: cask"？

**Comment by strangelove1969** [comment]
I tried upgrading by downloading the latest dmg file.  When I double click it the installer never appears.  (I set up my preferences to allow anything and I was able to install an earlier version... I don't remember how).  Not sure what is going wrong.  :(

**Comment by serge-rider** [comment]
@strangelove1969 Make sure you have Java 8 (JDK) installed.

**Comment by strangelove1969** [comment]
Thank you @serge-rider .  Yes, I do.

I can't even begin to install this because the installer won't start.

**Comment by serge-rider** [comment]
@strangelove1969 There is no real installer for MacOS (yet). Just copy and start DBeaver application. If it doesn't start then there should be some error message and/or logs (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by strangelove1969** [comment]
I downloading the dmg and then trying to install it in the usual manner but nothing happens.

**Comment by tarun** [comment]
dbeaver-community version 4.0.3 is working fine for me on macOS Sierra 10.12.3

Updated the brew cask to reflect the same `brew cask install dbeaver-community` works now.

**Comment by nkev** [comment]
Not working for me either. I installed Java 8, downloaded the enterprise version (dbeaver-ee-3.8.5-macosx.cocoa.x86_64.tar.gz), extracted the dbeaver.app and put it in the applications folder. When I run it I get this popup:

<img width="427" alt="screen shot 2017-03-29 at 8 59 06 am" src="https://cloud.githubusercontent.com/assets/5410916/24429839/8143bbf0-145f-11e7-9b16-acc90639f6bf.png">
When I open that log file mentioned in the popup, this is the last entry:

```terminal
!ENTRY org.eclipse.osgi 4 0 2017-03-29 08:58:46.380
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

The `xattr` and `chmod` solutions above make no difference. Installing with Brew makes no difference. I am running Macbook (15-inch, Late 2016), Sierra 10.12.3. I'm hoping someone has gone further with this. @serge-rider Is there an ETA for the next version containing the fix?

**Comment by nkev** [comment]
I fixed my issue above by downloading and installing the [JDK version](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) of Java 1.8. It works now!

**Comment by matthewlmcclure** [comment]
@nkev's solution also works for me. I installed JDK 8 using `brew cask install java`.

**Comment by serge-rider** [comment]
Please check version 4.0.7. 
DMG installer was reworked, now it should work in Sierra (although installer UI is quite ugly). 
Perhaps there will be some warnings but I very hope that "move to trash" message won't appear.

**Comment by niwat-panrit** [comment]
I tested it and YES it works (version 4.0.7, with warning message as you mentioned). Thank You

Note:
- The message is “
Your security preferences allow installation of only apps from the App Store and identified developers.

Safari downloaded this file today at 12:26 from dbeaver.jkiss.org<http://dbeaver.jkiss.org>
“ -> Fix this by go to System Preferences > Security & Privacy > General Tab (Select by default) > Allow apps downloaded from: section > click Open Anyway and enter administrator password to authorize Dbeaver (Check application before allow it).

Thanks again.
----------------------------------------
Niwat Panrit
(66)02-648-1216 — 9:00 a.m. to 4:00 p.m.
(66)092-268-8423
----------------------------------------

On May 15, 2560 BE, at 03:41, Serge Rider <notifications@github.com<mailto:notifications@github.com>> wrote:


Please check version 4.0.7.
DMG installer was reworked, now it should work in Sierra (although installer UI is quite ugly).
Perhaps there will be some warnings but I very hope that "move to trash" message won't appear.

**Comment by bodonova** [comment]
What worked for me was (thanks to @hgrod ):

first remove the extended attributes
`xattr -rc /Applications/DBeaver.app`

then recursively give permissions to all in all DBeaver folders, note this gives drwxrwxrwx not drwxrwxr-x. If you don't want ALL, please find the proper command for that.

`sudo chmod -R uog+wxr /Applications/DBeaver.app
`
However, I had previously re-signed the app due to an earlier suggestion so I can't be sure if that was necessary or not:
`sudo codesign --force --sign - /Applications/DBeaver.app`

**Comment by gantir** [comment]
What worked for me was (thanks to @bodonova ):

First remove the extended attributes

`xattr -rc /Applications/DBeaver.app
`

Then recursively give permissions to all in all DBeaver folders, note this gives drwxrwxrwx not drwxrwxr-x. If you don't want ALL, please find the proper command for that.

`sudo chmod -R uog+wxr /Applications/DBeaver.app`
