### ISSUE TITLE
Oracle procedure error PLS-00103

### ISSUE THREAD

**Issue by lisdoo** [serge-rider/dbeaver#950]
I execute this procedure: 

declare 
  var_level_no NUMBER;
begin
  for var_level_no in 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE('-------------------');
  END LOOP;
end;

And it reports me this error:
PLS-00103

I found log record with:
declare 
  var_level_no NUMBER;
begin
  for var_level_no in 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE('------------------');
  END LOOP;

It shows the procedure was not complete, the last line "END;" was absenced.

**Comment by serge-rider** [comment]
Duplicate of #907

**Comment by lisdoo** [comment]
thx
