### ISSUE TITLE
Tables properties  - Columns appear multiple time EXASOL connection

### ISSUE THREAD

**Issue by holzben** [serge-rider/dbeaver#952]
Viewing table properties and columns one row appears multiple times (in my case its also the PK column).
![dbeaver](https://cloud.githubusercontent.com/assets/16157973/20104263/a035bc9e-a5cd-11e6-8360-fb1d78eab3de.PNG)

Best regards,

Ben

**Comment by Sargul** [comment]
I'll look into it
