### ISSUE TITLE
MySQL's TIMEDIFF is returning null

### ISSUE THREAD

**Issue by fabianofa** [serge-rider/dbeaver#954]
On MySQL Community Server 5.7.14, running the following query listed on official documentation: 

`SELECT TIMEDIFF('2008-12-31 23:59:59.000001', '2008-12-30 01:01:01.000002') from dual;`

is returning null value. Tested on a PHP script it returned the same value as the documentation states: 46:58:57.999999

Doc: https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_timediff

**Comment by serge-rider** [comment]
This is a driver (Connector/J) bug: http://bugs.mysql.com/bug.php?id=70892

It can't be fixed on DBeaver side. You can use a workaround - convert timediff into varchar on server side. For instance:
```sql
SELECT CONVERT(TIMEDIFF('2008-12-31 23:59:59.000001', '2008-12-30 01:01:01.000002'),CHAR(100));
```
