### ISSUE TITLE
Query triggers on view

### ISSUE THREAD

**Issue by Xerosss** [serge-rider/dbeaver#955]
Hello,

I´m using a Oracle Database, when selecting the trigger button on a table view it take too long to execute the query:

SELECT * FROM SYS.ALL_TRIGGERS WHERE OWNER=:1 ORDER BY TRIGGER_NAME ;

Could this one be faster?
SELECT * FROM SYS.ALL_TRIGGERS WHERE OWNER=:1 and table_name = :2  ORDER BY TRIGGER_NAME;

Where the :2 is the name of the table in the view.

Regards.

**Comment by serge-rider** [comment]
How long does it take to load all schema triggers? 
This happens just one for all schema tables.
But if this takes really long time then I could try to refactor current metadata loading..

**Comment by serge-rider** [comment]
Will reopen if new details will be discovered.

**Comment by Xerosss** [comment]
Hello,

Sorry for taking so long to answer.

The query manager show for:
SELECT *
FROM SYS.ALL_TRIGGERS WHERE OWNER='USER'
ORDER BY TRIGGER_NAME

A duration of 90640 ms for 3023 rows (The number of triggers of the user).

Regards.

**Comment by serge-rider** [comment]
Well, this looks like a real problem.
