### ISSUE TITLE
Eclipse: "Database Navigator" doesn't allow configuring connections (no active project)

### ISSUE THREAD

**Issue by alexardz** [serge-rider/dbeaver#959]
Dear Serge,

When right-clicking on "Database Navigator" view there are no "New Connections" dialog window. Neither at "Database" Menu.
The last time I use that "New Connections" dialog window was on DBeaver 3.7.0 installed on the same eclipse.
How can I stablish a new connections with DB2?

![20161109 - erro dbeaver v3.7.8 - configuracao de conexao desabilitada](https://cloud.githubusercontent.com/assets/20108897/20139648/4456bd1e-a66e-11e6-8cdd-7315d4b34f27.JPG)

Eclipse Platform
Versão: 4.2.1.v20130118-173121-9MF7GHYdG0B5kx4E_SkfZV-1mNjVATf67ZAb7
ID da Construção: M20130204-1200

Ativação do Eclipse Data Tools Platform
Versão: 1.9.400.v201008311711
ID da Construção: 1.6.1.v20140731-1705

Eclipse Data Tools Platform Sybase Enablement
Version: 1.100.2.v20140731_1705-7E8cFA7FAFkN_6Ofwf0_fOI
Build id: 1.6.1.v20140731-1705

Thanks.

**Comment by serge-rider** [comment]
You need to create a project first.
You can do it on Project Explorer view or in some standard Eclipse perspective.

**Comment by alexardz** [comment]
I've created a project, but neither the "New Connection" icon on "Database" view nor the "New Connection" option on "Database" Menu.

![20161110 - erro dbeaver v3.7.8 - configuracao de conexao desabilitada 2](https://cloud.githubusercontent.com/assets/20108897/20171889/e4523e50-a719-11e6-8b00-c9db1c3f2f44.JPG)

Testing earlier versions of DBeaver I manage to connenct using DBeaver 3.6.10 version (and 3.7.0, that I couldn't find).

Thanks

**Comment by serge-rider** [comment]
This looks like a bug, although I can't reproduce this.
Open "Projects" view (main menu Window->Show View->Others->Database->Projects).
Select a project, open context menu and click on "Set Active Project". This should resolve the problem. 

Actually active project had to be selected automatically but for some reason it didn't. Will check this.

**Comment by alexardz** [comment]
I did the step "Open "Projects" view (main menu Window->Show View->Others->Database->Projects).", created the "alm-DB2" project using the icon for this operation on that view but no project appeared inside "Projects" view, although it has being created. (see "Navegador" view).

![20161110 - erro dbeaver v3 7 8 - configuracao de conexao desabilitada 3](https://cloud.githubusercontent.com/assets/20108897/20175510/39bb149c-a72a-11e6-9979-7c9d6a438974.JPG)

I manage to create two connections but none of then appears at "Database Navigator" view.

I'm working not with a java project, but a general eclipse project.

**Comment by serge-rider** [comment]
You need to switch to DBeaver "Database Navigator" view. Or to DBeaver "Projects" view. 
Generally it is better to work in DBeaver perspective.
Generic Eclipse Navigator view can not show database connections (obviously) - it knows nothing about databases.

**Comment by alexardz** [comment]
I've switched, but no better news. If you need to test anything just let me know.
![20161110 - erro dbeaver v3 7 8 - configuracao de conexao desabilitada 4](https://cloud.githubusercontent.com/assets/20108897/20176989/97aef256-a731-11e6-8b48-77c5afb70c1b.JPG)

**Comment by serge-rider** [comment]
Well, something is definitely broken.
Please open Error Log view and post any related errors (with stacktraces) here.

**Comment by alexardz** [comment]
Ok. Thanks.

[20161110 - DBeaver 3.7.8 no new database connection log error 1.txt](https://github.com/serge-rider/dbeaver/files/583488/20161110.-.DBeaver.3.7.8.no.new.database.connection.log.error.1.txt)

**Comment by serge-rider** [comment]
Well, you are using old Eclipse version (I'm not sure what exactly version is used in IBM Rational Developer).
This also explains why DBeaver views looks broken (grayed).
I've removed unnecessary dependencies but it is not a guarantee that everything will work (recently we stopped official support of 3.x versions because of too many differences with modern 4.x). 
We'll see after 3.8 release.

**Comment by alexardz** [comment]
Can I try again DBeaver version 3.7.8 to see if it works?
Later on I'll install DBeaver on RDz Luna version. Probably it'll work.
So I'll install DBeaver version 3.6.10 on that version of RDz Eclipse I'm using by now.

Thanks.

**Comment by serge-rider** [comment]
Unfortunately that's not easy.
I can easily build standalone EA version but not Eclipse update site. 
I will try to improve this but right now it is not possible.

**Comment by alexardz** [comment]
Ok. I can wait. 'till then I'll use version 3.6.10. Later on I install a Luna based compatible version of RDz.
Thanks a lot again.

**Comment by serge-rider** [comment]
3.8 has been released
