### ISSUE TITLE
Mac OS, DBeaver 3.5.5 - Inline Editing of Postgres HSTORE Column leads to DBException when saving

### ISSUE THREAD

**Issue by loskultos** [serge-rider/dbeaver#96]
Inline Editing of Postgres HSTORE Column leads to DBException when saving

My table looks like this:

    CREATE TABLE public.entry (
	    id bigserial NOT NULL,
	    uuid uuid DEFAULT uuid_generate_v4(),
	    type varchar(64),
	    name varchar(255),
	    attributes hstore,
	    creation timestamp DEFAULT 'timezone('UTC'::text, now())',
	   last_modified timestamp DEFAULT 'timezone('UTC'::text, now())'
    );

Trying to manipulate values in the attributes column (hstore type) and saving lead reproducible to a DB Exception:

    DBCException: SQL Error [XX000]: ERROR: Syntax error near 's' at position 9
       org.postgresql.util.PSQLException: PSQLException: ERROR: Syntax error near 's' at position 9

DB: PostgresQL 9.4.4
jdbc: 9.4-1206-jdbc4

**Comment by serge-rider** [comment]
hstore value should look like "key1"=>"value1", "key2"=>"value1"
What actual value causes this issue?

**Comment by loskultos** [comment]
data is represented in the grid like this:
    {key_activity=sport, key_location=gym}

    UPDATE entry set attributes = attributes || '"key_activity"=>"soccer"'

works
