### ISSUE TITLE
Copy / exporting clob values from oracle results

### ISSUE THREAD

**Issue by beirtipol** [serge-rider/dbeaver#961]
I have a CLOB column in my results and would like to copy-paste out to a text editor. I guess that in order to preserve memory, the CLOB values are not converted to Text until you mouse click on the cell. I can export it to csv or clipboard but it's a little bit long-winded. Perhaps as part of 'advanced copy' ?

**Comment by serge-rider** [comment]
If you need to see CLOB values right in the grid you can enable CLOBs caching: Preferences->Database->Result Sets->Binaries

**Comment by beirtipol** [comment]
Thanks!
