### ISSUE TITLE
Capitalize Dbeaver.app to DBeaver.app

### ISSUE THREAD

**Issue by g4brielvs** [serge-rider/dbeaver#963]
On macOS, the suggestion is to change Info.plist to read as follows below

```
<key>CFBundleName</key>
<string>DBeaver</string>
...
<key>CFBundleDisplayName</key>
<string>DBeaver</string>
```

In fact, it uses `${dbeaver-product}` variable. Is it possible to capitalize it?

**Comment by serge-rider** [comment]
This is a known issue, going to fix it in 3.8.
Thanks for report anyway.
