### ISSUE TITLE
Cannot change main tree font size

### ISSUE THREAD

**Issue by squalsoft** [serge-rider/dbeaver#964]
It would be great if i can scale entire app because i think that everything is too small.

**Comment by serge-rider** [comment]
Unfortunately this can't be done easily. This is Eclipse limitation (base font is taken from OS defaults).
But there is a bunch of workarounds: http://stackoverflow.com/questions/3124629/how-can-i-configure-the-font-size-for-the-tree-item-in-the-package-explorer-in-e
