### ISSUE TITLE
DB2 - Not able to view XML in the editor view

### ISSUE THREAD

**Issue by mikethewizz** [serge-rider/dbeaver#966]
I am using dBeaver V3.7.5
The dB is 10.1 Fp4

The dB has several columns that are defined as XML in the latest version I cannot see any XML contents in the editor pane.  I just get a message stating "No Editor".  In dBeaver version 3.6.7, the editor view worked fine.

I assume there is some IBM jar I need, but I have had no luck in finding this info anywhere.

Any assistance would be greatly appreciated.

**Comment by serge-rider** [comment]
First of all you need to upgrade to the most recent version (3.7.8).

After that please provide more details:
- Errors from Error Log view (with stacktrace)
- Screenshot with error will also be useful.

**Comment by flequi** [comment]
I've the same error with the 3.7.8 version:

![errorxmldbeaver](https://cloud.githubusercontent.com/assets/4034173/20435560/e061dd8e-adac-11e6-9065-e85bc010d543.png)


[ErrorDBeaver.txt](https://github.com/serge-rider/dbeaver/files/600289/ErrorDBeaver.txt)

**Comment by titou10titou10** [comment]
Hi,
Could you check what version of the the db2 driver you are using (file `MANIFEST.MF` in `db2jcc4.jar`) and also provides us the DDL to create the `OPERACION_BATCH` table
Thanks
Denis

**Comment by flequi** [comment]
Hi.

Of course, the version it's:
Version: 3.66.46

I've read another post of Serge-rider about to add additional Jars to see XMLs in Oracle, ¿Is it necesary for DB2 to do this?

The DDL of the table it's the next code, but the problematic field it's declared like XML, nothing more.
"CONFIGURACION XML NOT NULL," 

CREATE
    TABLE CONFIGURACION_APLICACION
    (
        ID_CONFIGURACION_APLICACION INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
        ID_CADENA SMALLINT,
        ID_PAIS SMALLINT,
        CRITERIO XML,
        ID_TIPO_CONFIGURACION_APLICA SMALLINT NOT NULL,
        CONFIGURACION XML NOT NULL,
        DESCRIPCION VARCHAR(40),
        FECHA_DESDE DATE NOT NULL,
        FECHA_HASTA DATE,
        CONSTRAINT PK_CONFIGAPLICA PRIMARY KEY (ID_CONFIGURACION_APLICACION),
        CONSTRAINT FK_CONFAPL_CADENA FOREIGN KEY (ID_CADENA) REFERENCES CADENA (ID_CADENA),
        CONSTRAINT FK_CONFAPL_TCONF FOREIGN KEY (ID_TIPO_CONFIGURACION_APLICA) REFERENCES TIPO_CONFIGURACION_APLICACION (ID_TIPO_CONFIGURACION_APLICA),
        CONSTRAINT FK_CONFAPL_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS),
        UNIQUE (CONFIGURACION),
        UNIQUE (CRITERIO)
    );

**Comment by titou10titou10** [comment]
Thanks
No,for DB2 you don't need an extra jar to handle XML data types.
Given [this page ](http://www-01.ibm.com/support/docview.wss?uid=swg21363866) , you are using  the `JDBC v3.0` driver for `DB2 v10.5.FP1 ` from `db2jcc.jar`, right? 
If it is possible for your, could you test it with the `JDBC v4.0` driver instead (from `db2jcc4.jar`) from the highest version of DB2, either `v10.5.FP8`, `v11.1.FP0`, but `v10.5FP1` would be ok too for the test
Thanks
Denis

**Comment by flequi** [comment]
Great, with the db2jcc4.jar with JDBC 4.0 the program works perfect and it shows the XMLs correctly. I don't know if I'll can use this driver because my customer gave us the JDBC 3.0 driver for the 9.7 DB2 DataBase they have, but I'll try it.

**Comment by titou10titou10** [comment]
Great news.
Support of XML data in JDBC is officially available since JDBC v4. Before JDBC v4, support was partially offered and most databases JDBC drivers (DB2, Oracle..) offer partial or proprietary support for handling such data.
So if you plan to manipulate XML data in a generic/standard way, you must use a JDBC v4 compatible driver
On the link I gave you before, you can download the equivalent DB2 v9.7 JDBC v4 driver if you want to stick with the exact same version as your DB2 server, but using the latest one (DB2 v11.1.0 driver) will work too (And maybe better).
Denis

**Comment by mikethewizz** [comment]
Sorry I did not get back to this sooner, and thanks to flequi for providing the additional detail, and to titou10titou10 & serge-rider for their responses.

I updated dBeaver, and then followed these instructions to configure the app with db2jcc4.jar

Thanks all!

**Comment by xaviereraso** [comment]
Hi,

I have almost the same problem, I am not able to view XML or CLOB in the editor view but the display is different.

Here is a screenshot of the problem : 

![image](https://user-images.githubusercontent.com/51155797/58545160-ff859200-8202-11e9-811c-4d1685f29749.png)

I am using Dbeaver V4.3.5
The DB version  is 12.01
The JDBC diver version is : 4.21.40

Any assistance would be greatly appreciated.

**Comment by luki88** [comment]
Hello!
I have the same problem. I can display only short XML. When I try display longer XML, I have empty view. Whek I check content view on binary, I see all. The same situation when I click right mouse button on XML cell and I check 'save as'. In file I see all XML content. I have problem only with view in DBeaver. Please help.

**Comment by luki88** [comment]
I'm using DBeaver 6.2.1.
