### ISSUE TITLE
Auto-completion deletes words in some cases

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#967]
Hi,

In the SQL editor, sometimes validating an auto-completion will delete the word next to it if there's no space.

Reproduction:

```sql
SELECT * FROM table GROUP BY ORDER BY id DESC
----------------------------/\ place your caret here, next to ORDER without a space
```

Press Ctrl-Space to open the autocompletion dialog, choose one and press Enter. The query will read : `SELECT * FROM table GROUP BY col BY id DESC`

**Comment by smcateer** [comment]
I am still getting this bug on the Eclipse plugin version 4.3.5.
