### ISSUE TITLE
Bug in 3.7.8: Invalid thread access on connect

### ISSUE THREAD

**Issue by shivan** [serge-rider/dbeaver#969]
Description:
Invalid thread access in treeview when connecting.

Reproduction:
Connection is closed. Only username - but no password - is set in the connection. Now click on the + in front of the item, to open the treeview item.

You'll get that exception then.

Expected result:
Login-Dialog - like when double clicking on the item.

**Comment by infectormp** [comment]
Same as https://github.com/serge-rider/dbeaver/issues/931?

**Comment by serge-rider** [comment]
Yes, duplicate.
