### ISSUE TITLE
DB2 slowness exporting to CSV

### ISSUE THREAD

**Issue by dipasi** [serge-rider/dbeaver#973]
Hi 

I'm running a complex query in DB2 10.5, that at the end generates around 45 rows. When exporting the results to CSV, the export wizard takes a long time to complete, I was expecting this to take no more than a few seconds, but it took more than 6 minutes, is it running the query again?

Dbeaver is 3.7.7, system is Windows 7 32 bits, and file is exported to a local dir.

**Comment by r-richmond** [comment]
exporting the results to csv runs the query again

**Comment by dipasi** [comment]
Any option to avoid DBeaver to run the query again?

**Comment by r-richmond** [comment]
I edited my comment above perhaps before you saw the second part of my response so I'll just repeat what I have above

If you don't want to run the query again you can copy/paste the results into an excel/csv file

**Comment by dipasi** [comment]
Thanks for your answer.

Anyway, it would be a nice feature to allow exporting the results to file, instead of copy&paste them, as the wizards allows several formats of exporting the data.

**Comment by dipasi** [comment]
Another question related to the above.

Would it be possible to directly run an extraction, without need to run the query first, and exporting later?

Thanks in advance!

**Comment by serge-rider** [comment]
You can execute query just once:
SQL editor context menu->Execute->Export from query (query under cursor will be executed).

**Comment by dipasi** [comment]
Thanks Serge

That was exactly what I was expecting to find, I didn't realize it was possible through the context menu. 

Thanks!
