### ISSUE TITLE
Add option to show views in ER-diagram

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#977]
Like already mentioned in #934 it is not possible to see views in ER-diagram because they don't have any relationships and so they won't make much sense in a ER-diagram. I just have a need for this now because I'm using ER-diagram also to get a overview of DB (not only for relations) and it would make it easier to get a overview over information_schema. Furthermore I'm in need to show a complete visual model of my database to someone. This is why I need also my views included.

**Comment by serge-rider** [comment]
Already implemented. Will be in 3.8
