### ISSUE TITLE
Postgres trigger information improvement

### ISSUE THREAD

**Issue by lacanoid** [serge-rider/dbeaver#978]
This applies to Postgres, but may be relevant for others as well.

Trigger listing when viewing a table is missing data for "Timing" and "Type".
Also "When Expression" and "Trigger Description", but these are somewhat less important.

These (sans comment) can usually be got from the SQL standard information_schema.triggers, which should work fine for Postgres as well, but it currently doesn't.

Postgres specific: triggers are implemented with procedures. It would be super cool, if you provided links to appropriate procedures in trigger list, so one can just go there with a click. Also, include the relevant procedure definition along with trigger definition when creating DDL for a trigger.

**Comment by serge-rider** [comment]
Agreed.
Timing, type and trigger functions will be fixed in the next version.
When Expression and Description are actually work (but in most cases triggers do not have any values for them).

**Comment by lacanoid** [comment]
Wonderful!

Works much better now!
However there seems to be a minor problem still. Run this:

create table table1 (id serial);
create function trigger() returns trigger as $$begin return new; end$$ language plpgsql;
create trigger trigger1 before insert or update or delete on table1
 for each row execute procedure trigger();

Trigger table shows only INSERT in the Type column, but no sign of UPDATE or DELETE!
Also, it would be quite helpful to add trigger action orientation (ROW or STATEMENT) to the table.

Thanks!

**Comment by serge-rider** [comment]
Yep. Will fix that.
