### ISSUE TITLE
Feature request: Oracle PL/SQL package editor

### ISSUE THREAD

**Issue by cz-michi** [serge-rider/dbeaver#979]
Could you change visual of PL/SQL package editor, would be nice to have tabs instead of splitted windows.
Code outline would be also nice.

thanks for think about

**Comment by serge-rider** [comment]
Agreed. Splitted windows were made similar to generic procedures source viewer. Isn't really convenient for Oracle.
Code outline is complicated. We are working on SQL parser improvements - this will make outline possible. But I don't think that such feature will appear before 4.x version.
