### ISSUE TITLE
Oracle generate DDL on package

### ISSUE THREAD

**Issue by cz-michi** [serge-rider/dbeaver#980]
Code generation on package generates only spec, how can i generate package body?

**Comment by serge-rider** [comment]
Maybe I'm missing something but package bodies are also visible.
Maybe you don't have permissions to see package bodies?

**Comment by cz-michi** [comment]
maybe i'm missing something, but i go to packages in my own schema, double click openes spec+body, in tree i see only spec and if i go to right click on package - generate sql - ddl, it opens window with only spec in it :(

![2016-11-17_095619](https://cloud.githubusercontent.com/assets/9120203/20382515/85b7b3b4-acac-11e6-97c2-82503236187d.png)

**Comment by serge-rider** [comment]
Ah, I see. This looks like a bug.
