### ISSUE TITLE
Where to see CHECK-conditions of tables?

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#981]
I've added a CHECK-condition to one of my MariaDB tables but I've not been able to see it anywhere in DBeaver. Am I blind or is this feature lacking?

**Comment by serge-rider** [comment]
MySQL doesn't support CHECK constraints.
You can specify them in table create query but they will be ignored. Official docs: http://dev.mysql.com/doc/refman/5.7/en/create-table.html

**Comment by GiantCrocodile** [comment]
While I searched something else I just found this: https://mariadb.com/kb/en/mariadb/check-constraints-support/ . So MariaDB does support CHECK constraints since v10.2.1 but MySQL doesn't. So indeed, this should be fixed.

Source: https://jira.mariadb.org/browse/MDEV-7563

**Comment by MSKhodadady** [comment]
As i see in mysql documents, the version 8 of mysql supports CHECK constraint. See this:
`https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html`

**Comment by derekparsons718** [comment]
Looks like this has come up again in #6069
