### ISSUE TITLE
An error has occured during initialization in macos sierra

### ISSUE THREAD

**Issue by nick3389** [serge-rider/dbeaver#982]
Hi,

I installed dbeaver but when i start the app there is always an error and i get this:

An error has occured.
See the log file /Applications/Dbeaver.app/Contents/Eclipse/configuration/1479462740360.log

The log is:

[dbeaver_log.txt](https://github.com/serge-rider/dbeaver/files/599584/dbeaver_log.txt)

**Comment by serge-rider** [comment]
This is a known MacOS issue.
You need to setup Java JDK (not JRE!) 1.7 or 1.8.

**Comment by nick3389** [comment]
@serge-rider  Perfect! Fixed now. Thank you!
