### ISSUE TITLE
SSH Tunnel fails to reconnect.

### ISSUE THREAD

**Issue by ottothecow** [serge-rider/dbeaver#984]
I am able to set up a connection to a PostgreSQL server over an SSH tunnel.

But if that session times out, DBeaver will always fail to reconnect.  When I then try to connect again manually, it connects fine.

For instance, if I try to do an operation after it has lost connection, I get this message as I would expect (can't communicate to the server after the tunnel has closed/connection has been lost):
![image](https://cloud.githubusercontent.com/assets/5453276/20456860/b36fd892-ae44-11e6-9bb7-437fcc0bc798.png)

If I click reconnect, I get this box:
![image](https://cloud.githubusercontent.com/assets/5453276/20456872/d6e8dbd4-ae44-11e6-97e7-64cb47d4de43.png)

Which quickly pops up this box:
![image](https://cloud.githubusercontent.com/assets/5453276/20456875/eb911826-ae44-11e6-885e-c338c47fe4b6.png)

However, after that, if I go and right click on the connection in the Database Navigator pane and choose "Connect", it will connect just fine.

My guess is that DBeaver is trying to invalidate the connection before reconnecting.  But since it has lost its connection to the server (and the tunnel is no longer active), it cannot do so.  It instead tries to connect to that port on my local machine which obviously has nothing running on it.  I would expect it to recognize that the SSH tunnel is gone and then proceed to reestablish the tunnel and reconnect to the database.

**Comment by ottothecow** [comment]
And I should note that I don't have keep alive turned on.

That might work to keep the connection alive, but that's a separate issue from reconnecting causing an error.

**Comment by serge-rider** [comment]
Tunnel invalidation + reconnect error handling improvement will be added in the next version.

**Comment by ottothecow** [comment]
Behavior is different now, but I don't think the issue is quite fixed.
This is to a default PostgreSQL server running on free tier AWS RDS, SSH tunneled through another AWS ubuntu machine,  so I don't think it is due to the server configuration being weird.

First error looks the same:
![image](https://cloud.githubusercontent.com/assets/5453276/21337155/6b9370c0-c630-11e6-97eb-fc2c0b9a2c4f.png)

Then the "Invalidate..." box pops up and immediately pops up this new error message:
![image](https://cloud.githubusercontent.com/assets/5453276/21337175/96ab99d6-c630-11e6-80ac-6977e244c7b4.png)

If I hit retry, it repeats with the same message.  If I hit ignore, it drops me back to the window I was in, but has not actually reconnected the database.  If I hit Disconnect, it will close any open data windows I have and mark the connection as disconnected.

Thanks much for working on this problem though!

**Comment by serge-rider** [comment]
Yep, in some cases simple SSH reconnect doesn't help. 
Tunnel must be closed and opened again. Fix will be in the next version.

**Comment by vmouse** [comment]
Still having the same problem with the Postgres driver. I have to click the "Reconnect" after about 1 min of inactivity.
