### ISSUE TITLE
I am unable to find SSL Option when using Hive driver

### ISSUE THREAD

**Issue by sureshkumar1902** [serge-rider/dbeaver#985]
I am using latest version of DBeaver and not able to add the SSL Certificate. I see the SSL Option when using MYSQL Driver but that option not available when I am using Apachi Hive driver.

**Comment by serge-rider** [comment]
SSL is not supported for Hive (generic) driver.
Each driver has it's own SSL configuration - this is not a part of JDBC API. 
DBeaver has special SSL UI/config only for For MySQL, PostgreSQL and Oracle. All other drivers can be configured manually (using driver properties or DBeaver command line parameters).

**Comment by sureshkumar1902** [comment]
Thank you Serge. Can you also provide the instructions to configure manually. I have SSL Certificate in my local drive.

**Comment by serge-rider** [comment]
I'm not a Hive expert but I believe you can find these properties here https://www.cloudera.com/documentation/enterprise/5-3-x/topics/sg_hive_encryption.html or somewhere else on Hive site.
