### ISSUE TITLE
Can't edit table name and column name in dbeaver 3.8.0

### ISSUE THREAD

**Issue by ydq** [serge-rider/dbeaver#989]
I can't edit table name and column name when I update dbeaver to 3.8.0 today.
OS:MacOS
DB:MySQL/SqlServer
![edit](https://cloud.githubusercontent.com/assets/8097340/20486385/72e273be-b03a-11e6-8de5-efc7ed7cc51b.gif)

**Comment by serge-rider** [comment]
Existing objects names never were editable. 
You need to use Rename action (F2). 
Click on a table or column and press F2 (or choose Rename in the context menu).

**Comment by ydq** [comment]
@serge-rider Oh..Thanks!!

**Comment by rsmolkin** [comment]
I also just ran into this, I'm connected to SQL Server 2016, and when I right click or try F2, no option to rename a column?

**Comment by hotdesc** [comment]
In sql server on linux F2 does nothing

**Comment by serge-rider** [comment]
Tables and columns rename is not supported for SQL Server.
Please create a feature request.

**Comment by MikeStrider** [comment]
MS SQL ... run this in dbeaver:
EXEC sp_rename 'dbo.old_table_name', 'new_table_name';

**Comment by keerthivasan-r** [comment]
@serge-rider I think the contraints name couldn't be edited via F2 yet? Does that right?
