### ISSUE TITLE
Freshly created table is not recognized by DBeaver

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#990]
1. open DBeaver and ER-diagram view
2. create a table outside of DBeaver
3. refresh ER-diagram

Table of step 2 is not found. You have to refresh tables in database navigator manually and then you can refresh DBeaver table.

System: DBeaver 3.8.0 with MariaDB.

**Comment by serge-rider** [comment]
This was made on purpose - diagram refresh doesn't refresh metadata but just re-render diagram.

**Comment by serge-rider** [comment]
I'll make active object refresh. It won't make much sense in case of individual tables diagram (because referenced tables won't be refreshed). But this can be used in schema diagrams.
