### ISSUE TITLE
Copy-Paste integer value

### ISSUE THREAD

**Issue by filosssof** [serge-rider/dbeaver#991]
When I try to copy an integer (i.e. ID) it copies the value with comma that is not so comfortable to use. It will be better to display with comma, but when we try to edit/copy to display without comma.

**Comment by serge-rider** [comment]
Can't reproduce.
By default DBeaver copies numeric values without extra formatting.
If you use advanced copy (ctrl+shift+c) then you can choose formatting options.

**Comment by filosssof** [comment]
![screenshot from 2016-11-22 12 03 49](https://cloud.githubusercontent.com/assets/4747627/20519603/a3bb8f46-b0b4-11e6-8da5-43ef565d3d5b.png)

**Comment by filosssof** [comment]
Ubuntu 14.04

**Comment by serge-rider** [comment]
Just press ctrl+c on a cell - no need to activate value editor. The same about paste.

Editor uses grouping (not required!) just because it is more convenient.
