### ISSUE TITLE
Autorefresh after loosing connection.

### ISSUE THREAD

**Issue by filosssof** [serge-rider/dbeaver#992]
When connection is lost after timeout I don't know this and I'm trying to open a table. On clicking at table I get an error message about the lost connection with opportunity of reconnect. I press reconnect button and the table isn't refreshed after connection. For displaying data I should close the tab with this table and open it

**Comment by allanlaal** [comment]
I was just about to suggest this. I have multiple instances open with tens of tables and I keep forgetting to refresh my connection after a while being absent

**Comment by serge-rider** [comment]
I believe this issue was resolved in 4.0. 
Please check.

**Comment by allanlaal** [comment]
@serge-rider I last experienced this issue with 4.0, the keepalive of that db was 0 at that time. I neede to manually refresh the connection before attempting change

**Comment by serge-rider** [comment]
Yeah, but before 4.0 manual refresh didn't work (you had to close and reopen editor). This was fixed.
Keep-alive procedure also was changed (it will re-establish connection once it will detect disconnect).

I think that manual refresh is a better than silent connection reopening - at least you will know that there were some problems (and your transaction was ended).

**Comment by allanlaal** [comment]
You make an excellent point for mission critical Live databases :)

However, it would be great to force silent autorefresh from some (even Live) connections (as a connection setting), that are not as mission critical

**Comment by serge-rider** [comment]
Maybe you are right, this may be usefull (but this must be configurable).
Please create feature request for that.
closing this one as resolved.
