### ISSUE TITLE
Local Client Dump Issues (Mac)

### ISSUE THREAD

**Issue by ubergeekzone** [serge-rider/dbeaver#993]
I have tried using mysql workbench for the local client on a mac and i get the following errors:

/Applications/MySQLWorkbench.app/Contents/MacOS/mysqldump --routines --add-drop-table --disable-keys --extended-insert -v --host=localhost --port=3306 -u ****** ****** tbl_invoate
Export started at Tue Nov 22 22:21:07 EST 2016
mysqldump: [Warning] Using a password on the command line interface can be insecure.
-- Connecting to localhost...
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect
Export finished at Tue Nov 22 22:21:08 EST 2016
Process exit code: 2

**Comment by ubergeekzone** [comment]
solved

**Comment by delmicio** [comment]
@ubergeekzone please share your solution -.-

**Comment by zhan3333** [comment]
Execute Script Script configuration set: 

Extra command args: `--protocol=tcp`

Because need to access mysql over tcp.
