### ISSUE TITLE
Anonymous PL/SQL Block execution as script results in error

### ISSUE THREAD

**Issue by trankas** [serge-rider/dbeaver#996]
Hello,

With version 3.8.0 64 bit Linux running the following statement as script 

```/* check online schemas available */
DECLARE
    V_COUNT NUMBER := 0;
BEGIN
    /* TIBCOBPMAPP */
    SELECT COUNT(1) INTO V_COUNT FROM ALL_TABLES WHERE UPPER(OWNER) = 'SOME_TABLE';

    IF V_COUNT >= 1 THEN
      EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM SOME_TABLE_SYN FOR SOME_TABLE';
    END IF;
END;
```
results in the following error:

> SQL Error [6550] [65000]: ORA-06550: line 10, column 11:
> PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:
> 
>    ( begin case declare end exception exit for goto if loop mod
>    null pragma raise return select update while with
>    <an identifier> <a double-quoted delimited-identifier>
>    <a bind variable> << continue close current delete fetch lock
>    insert open rollback savepoint set sql execute commit forall
>    merge pipe purge
> 
> SQL Error [6550] [65000]: ORA-06550: line 10, column 11:
> PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:
> 
>    ( begin case declare end exception exit for goto if loop mod
>    null pragma raise return select update while with
>    <an identifier> <a double-quoted delimited-identifier>
>    <a bind variable> << continue close current delete fetch lock
>    insert open rollback savepoint set sql execute commit forall
>    merge pipe purge
> 
>   ORA-06550: line 10, column 11:
> PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:
> 
>    ( begin case declare end exception exit for goto if loop mod
>    null pragma raise return select update while with
>    <an identifier> <a double-quoted delimited-identifier>
>    <a bind variable> << continue close current delete fetch lock
>    insert open rollback savepoint set sql execute commit forall
>    merge pipe purge
> 
>   ORA-06550: line 10, column 11:
> PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:
> 
>    ( begin case declare end exception exit for goto if loop mod
>    null pragma raise return select update while with
>    <an identifier> <a double-quoted delimited-identifier>
>    <a bind variable> << continue close current delete fetch lock
>    insert open rollback savepoint set sql execute commit forall
>    merge pipe purge

Selecting the whole statement and running it as a single statement works.

Thanks for a great SQL Client :-)

**Comment by trankas** [comment]
`UPPER(OWNER)` => `UPPER(TABLE_NAME)`

**Comment by serge-rider** [comment]
PL/SQL processing will be improved in the next version.
