### ISSUE TITLE
Pink background colors on linux with default themes

### ISSUE THREAD

**Issue by jvstein** [serge-rider/dbeaver#997]
The background colors are pretty unusable on my Ubuntu linux machine and I haven't found a decent way to fix them. The GTK theme in Eclipse is pretty rudimentary, so I typically use the Dark theme in other Eclipse-derived tools. With DBeaver, however, several UI widgets are showing up with a light-pink background color.

The "Projects" and "Database Navigator" panels:
![image](https://cloud.githubusercontent.com/assets/293465/20579831/d65d6f9e-b183-11e6-911d-010c1395270d.png)

The connection selector is initially OK, but turns light-pink after I open up a second connection: 
![image](https://cloud.githubusercontent.com/assets/293465/20579877/0c5bd4f0-b184-11e6-890a-7efc3c20ca48.png)

If I use the classic theme, the situation gets even worse for the editor and results panes:
![image](https://cloud.githubusercontent.com/assets/293465/20580300/78407ebc-b186-11e6-9721-d2f69609044c.png)

I'm using the 3.8.0 EE tar.gz distribution, not the community installer.

OS: Ubuntu 16.04 (xenial)

**Comment by serge-rider** [comment]
This pink color is a color of "Production" connections. Looks more or less decent in classic themes.
You can configure it (both - connection type and/or background color) in connection properties/preferences.

**Comment by jvstein** [comment]
Thanks! I was expecting the colors to be under "General > Appearance" section in Preferences, but they were under the "Database > Connection Types" section.
