### ISSUE TITLE
Launch Batch Scripts

### ISSUE THREAD

**Issue by pealp** [serge-rider/dbeaver#999]
Hi there - I'm a new user of DBeaver and I was wondering if it's possible to run multiple Scripts in DBeaver subsequently. 

I've searched around the web but the only mention I seem to find is from 2012 where it says it's not "currently" possible. Any updates on this since then?

Thanks!

**Comment by serge-rider** [comment]
Sure, just open multiple SQL editors and execute scripts (alt+x).

**Comment by pealp** [comment]
Yes, however via Alt+X you must execute them individually and manually, correct? I'm assuming this means there is no way to automatically execute scripts sequentially (one ends, next starts, etc.)

**Comment by serge-rider** [comment]
No, there is no such feature.
But there is a feature request: #739. I think this is the same what you need.

**Comment by pealp** [comment]
Yes, that feature request would solve this. Glad it's in the pipeline at least.
Thanks!
